### ISSUE TITLE
DICOM Segmentation image storage IOD support

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1]
It would be really helpful if OHIF viewers supported DICOM Segmentation. There are several on-going projects in ITCR and beyond that would probably benefit from this capability. Lots of sample data is publicly available for testing. Several tools, both open source and commercial, support DICOM SEG natively. Would be great to get an idea if/when this capability will be supported by OHIF Viewers.

**Comment by swederik** [comment]
Hi Andrey,

I don't know if it's planned for the immediate future but it certainly seems worthwhile and we do intend to follow DICOM standards as much as possible. If you'll be at RSNA, you can bring this up at the next OHIF Community Forum.

See here for more details:

http://forum.ohif.org/t/ohif-community-forum-meetings/18

**Comment by fedorov** [comment]
Thanks for the reply Erik! If I don't make it to the in-person meeting, I look forward to a clarification on the plans regarding this topic here on github.

**Comment by fedorov** [comment]
> Lots of sample data is publicly available for testing. Several tools, both open source and commercial, support DICOM SEG natively. 

To follow up on this, here is the article that discusses all the tools and sample data we made publicly available: https://peerj.com/preprints/1541/

**Comment by sedghi** [comment]
I think we have support for read, write, edit right now. So I will close this
