### ISSUE TITLE
Study lazy load should be true by default

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1002]
https://github.com/OHIF/Viewers/blob/9e10c2b2ded5dcf5c05779ca9ef9a7fc453750ad/platform/core/src/studies/services/wado/retrieveMetadata.js#L472-L476

Thanks @salimkanoun

**Comment by dannyrb** [comment]
merged here: https://github.com/OHIF/Viewers/pull/1004
Release won't be cut until this is resolved: https://github.com/OHIF/Viewers/issues/1001
