### ISSUE TITLE
Set a series into the viewport programmatically

### ISSUE THREAD

**Issue by ivan-aksamentov** [OHIF/Viewers#1006]
## Request

Given a study opened, I want to to be able to set a given series into the viewport programmatically, that is, without manual user interaction.

I imagine that this is a perfect scenario for a Redux action: user code dispatches an action containing series UID and viewer magically displays the series.

In fact, it seems that `VIEWPORT::SET` action is what is responsible for setting a series on UI interactions, so, I think, it makes sense to develop this path further.

**Why should we prioritize this feature?**

This is important for our project. This may be important for other projects.
This may help to rectify the situation with `VIEWPORT::SET` inconsistencies (see #1005)
I would like to contribute the implementation, just need a couple of tips for where to start :)

### Research

For instance, I want to trigger SEG obverlay programmatically on https://viewer.ohif.org/viewer/1.2.826.0.13854362241694438965858641723883466450351448

Patient Name: Dummy
MRN: 716713622818558421526494572171041020891020924597
Study: 1.2.826.0.13854362241694438965858641723883466450351448

I observed that manual drag and drop of SEG thumbnail leads to dispatching of  these two Redux actions:

```js
{
  type: 'VIEWPORT::SET',
  viewportIndex: 0,
  data: {
    displaySetInstanceUid: 'ef7897ea-1060-59f4-0510-147747277137',
    seriesInstanceUid: '1.2.826.0.53608788865337544170015089925954063493496832',
    studyInstanceUid: "1.2.826.0.13854362241694438965858641723883466450351448",
    seriesDate: '20190129',
    seriesTime: '153943',
    seriesNumber: 1001,
    seriesDescription: 'White matter hyperintensity segmentation',
    numImageFrames: 48,
    modality: 'SEG',
    isMultiFrame: true,
    instanceNumber: 1,
    sopClassUids: [
      '1.2.840.10008.5.1.4.1.1.66.4'
    ],
    isClip: true,
    plugin: 'cornerstone',
  }
}

{
  type: 'VIEWPORT::SET',
  viewportIndex: 0,
  data: {
    displaySetInstanceUid: 'ef7897ea-1060-59f4-0510-147747277137',
    studyInstanceUid: '1.2.826.0.13854362241694438965858641723883466450351448',
    currentImageIdIndex: 0,
    sopInstanceUid: '1.2.826.0.11521735486436309604024223829282084628708383'
  }
}
```

Great, so what happens if I emit these actions without UI interaction? If I dispatch the same  two actions programmatically (using Redux DevTools dispatcher tool), I receive an error (images not found) from segmentation handler. After some digging it turned out that `displaySetInstanceUid` changes on page refresh, so I have to take `displaySetInstanceUid` for my actions from current state.

However, after providing the same actions with the correct `displaySetInstanceUid` nothing happens. There are no error messages and no viewport changes.

### Questions:

 - other than these actions, what other conditions need to be satisfied in order for series to be displayed?
 - is there something particular regarding SEG series?
 - what are some of the relevant parts of the codebase responsible for this behavior?

**Comment by dannyrb** [comment]
`react-cornerstone-viewport` is the component we ultimately need to influence here. [Here is an open PR](https://github.com/cornerstonejs/react-cornerstone-viewport/pull/41/files#diff-96d8498106f747b405fd3ba4b07d6cdeR193-R219) that has better support for controlling the current series (stack) and displayed image id.

The `StackManager` has a `findOrCreateStack` method that returns the `imageIds` that are passed to the `CornerstoneViewport` Component. I don't know if `imageIdIndex` is currently passed as a prop, but if we added it as a passed props, updates to it would call `scrollToIndex` for the `CornerstoneViewport`

There are SOP Class Handlers responsible for determining _how_ we load data, and which plugin to use. We have `handleSegmentationStorage.js` in the Cornerstone and VTK Viewports that will parse and load the SEG into Cornerstone ToolState so Cornerstone's "Segmentation Module" can display it:

- `addSegMetadataToCornerstoneToolState`

It keys of the SOP Class Id (SEGMENTATION_STORAGE: "1.2.840.10008.5.1.4.1.1.66.4")

**Comment by sedghi** [comment]
you can use `viewportGrid.setDisplaySetsForViewport`
