### ISSUE TITLE
Errors while prefetching series in a study

### ISSUE THREAD

**Issue by atisman89** [OHIF/Viewers#101]
The browser console log reveals this error while loading a study:
--> study.getSeriesByUID is not a function (undefined)
which seems to cause a problem when switching back and forth between series (using UI) while loading data.

I traced it back in the source and it looks like the error was introduced with the following commit:
https://github.com/OHIF/Viewers/commit/0f30648646b58dd0cf6c92bb1d67e08d270eeff1
When I reverted this change, the error disappears and switching series works normally.

Additionally, calling of prefetchDisplaySets() doesn't seem to make a difference in the prefetch behavior. My understanding was that this function would prefetch all other non-active series in a study after completing prefetching the active series but it doesn't seem to work that way.

**Comment by brunoalvesdefaria** [comment]
We were migrating the metadata to a new structure and it was broken at that point.
There were some work on another fork that was merged yesterday.
The fix is on master branch now. This was the commit: https://github.com/OHIF/Viewers/commit/927b0c470c2d9b6c2c93da518c3792f6f33545fe
