### ISSUE TITLE
Is not possible to add Measurement Description if Relabel was not previously selected

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1013]
### Description

On measurement panel, user is not able to add a measurement Description if a Relabel was not previously selected.

![bug-description](https://user-images.githubusercontent.com/13245529/66440171-8267f600-ea08-11e9-8d78-3a178a5982ae.gif)

### Steps to Reproduce

1. Load view studies page
2. Add a Length measurement
3. Click on Measurements button
4. Select the measurement item and click on Description
5. Add "Text test" and click on Confirm button

### Actual Result

The description text was not added to the panel. If user clicks again on 'Description' button, he/she will see the entered text there.

### Acceptance Criteria

User should be able to add a Description text on the measurement, even if Relabel was not selected yet.

**Comment by dannyrb** [comment]
@evren217 want to double check and see if this was a conscious decision. Description does not show unless a label is set.

**Comment by evren217** [comment]
We should be able to show description only if entered without relabeling.

**Comment by dannyrb** [comment]
Thanks for confirming that this is a bug @evren217
