### ISSUE TITLE
Exit MPR button

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#1024]
Hi,

Can we have a specific MPR exit button on MPR view?

Thanks

**Comment by dannyrb** [comment]
We've been having internal talks about being able to register different layouts, and the UI/UX required to make them work well. Do you have any suggestions? We're very receptive to sketches, comments, and other applications you think handle this well (as an example).

**Comment by karthikvrao** [comment]
Hi, @bhavesh-pandey @dannyrb. My suggestion is that to display a button to exit MPR when MPR is clicked. So, in effect it will be a toggle. I will submit a PR soon for this.
