### ISSUE TITLE
Study List data formatting

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1029]
@pieper has a DICOM store on Google Cloud which fails every time it gets to Page 2 of the study list. It looks like it's because React is trying to render an Object inside one of the table cells in the study list. We need to ensure that each of the fields in the study object used below are renderable as Strings by React.

https://github.com/OHIF/Viewers/blob/659649e10b3732d4ce9a0d851390bb75786727eb/platform/ui/src/components/studyList/StudyList.js#L224-L253

> Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in td (created by StudyList)
    in tr (created by StudyList)
    in tbody (created by StudyList)
    in table (created by StudyList)
    in div (created by StudyList)
    in div (created by StudyList)
    in StudyList (created by TranslatedComponent)
    in TranslatedComponent (created by withI18nextTranslation(TranslatedComponent))
    in withI18nextTranslation(TranslatedComponent) (created by WrapperComponent)
    in I18nextProvider (created by WrapperComponent)

**Comment by pieper** [comment]
I can share the dicom store if needed to help debug.

**Comment by pieper** [comment]
Thanks for finding that 👍 !  You are correct, that value is invalid, but since it's it's in TCIA I guess we need to have a way to detect and workaround invalid data values.  Happy to test whatever you are able to come up with.
