### ISSUE TITLE
VTK Extension: Slab Thickness slider and Mode checkbox crashes the application

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1035]
### Description

On the VTK Extension, when user clicks on the `Slab Thickness` slider or on the `Mode` checkbox, the application seems to crash, displaying only a black screen.

![vtk-bug](https://user-images.githubusercontent.com/13245529/66689480-6c08a700-ec61-11e9-81c2-f681d7e05c98.gif)

### Steps to Reproduce

1. Load a Study
2. Click on 2D MPR button
3. Click on the `Slab Thickness` slider or on the `Mode` checkbox

### Actual Result

The application crashes, displaying a black screen. User has to reload the page to be able to get back to the application.

### Acceptance Criteria

1. User should be able to check/uncheck the `Mode` checkbox without crashing the application
2. User should be able to change the `Slab Thickness` slider  without crashing the application

**Comment by dannyrb** [comment]
Duplicates https://github.com/OHIF/Viewers/issues/1022
