### ISSUE TITLE
Long paths can break builds on Windows

### ISSUE THREAD

**Issue by jiangx25** [OHIF/Viewers#104]
![wechatimg22](https://user-images.githubusercontent.com/7488062/29491982-971e3872-859f-11e7-960f-1e28282a0200.jpeg)
when i run the program, it errors. How can i solve it?
set METEOR_PACKAGE_DIRS=..\Packages
meteor --settings ../config/orthancDICOMWeb.json
[[[[[ ~/Desktop/Medical-Cloud-master/Viewers/OHIFViewer ]]]]]

**Comment by steve7n** [comment]
Check this issue: [https://github.com/OHIF/Viewers/issues/97](url)

**Comment by h2zzhou** [comment]
METEOR_PACKAGE_DIRS didn't work

**Comment by steve7n** [comment]
What's the output you are getting?

**Comment by h2zzhou** [comment]
‘/Desktop/Medical-Cloud-master/Viewers/OHIFViewer’  the path name is too long. Shorten the folder name and try again

**Comment by swederik** [comment]
This looks like it's a Windows-specific issue. See https://forums.meteor.com/t/long-paths-names-make-build-on-windows-impossible/21387/10

You can try enabling Long Paths for Windows: https://betanews.com/2016/05/29/long-paths-windows-10/
