### ISSUE TITLE
Custom template layouts

### ISSUE THREAD

**Issue by Y4kuz4** [OHIF/Viewers#1040]
> :hand: Many people requests features. Tell us why yours is important to the
> community. How does it add value? Why _this feature_?
>
> Is your request very specific to your needs? Consider
> [contributing it](https://docs.ohif.org/contributing.html) yourself! Or reach
> out to a community member that offers
> [consulting services](https://docs.ohif.org/help.html#paid--commercial).

## Request

**What feature or change would you like to see made?**

template layouts for dental viewer like LEADTOOLS DENTAL VIEWER 

ej: https://medicaldemos.leadtools.com/DentalViewer/#/login

**Why should we prioritize this feature?**

for custom layouts

**Comment by dannyrb** [comment]
We have hanging protocols and advanced layout support on the roadmap. If you want to propose something more concrete, or spike the changes yourself, please don't hesitate to open a new issue.
