### ISSUE TITLE
How build and release viewer can open image page with URL(ex: http://192.168.9.137:82/viewer/1.2.840.16056.79586.20120503.143620.937.6882.4)?

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#1047]
I have build viewer by command 'yarn run build' and copied directory of '\node_modules\\@ohif\viewer\dist' to release in IIS, and I can access StudyList by URL 'http://192.168.9.137:82', also can access Study data with DicomCloud, can goto image page  with click StudyItem. But why cannot directtly goto image page by input URL http://192.168.9.137:82/viewer/1.2.840.16056.79586.20120503.143620.937.6882.4? Is my manner of build or release wrong?Or copied directory wrong?

**Comment by dannyrb** [comment]
1. `yarn run build` will create new output at `<repository root>/platform/viewer/dist/**/*`
    - That is the output that can be served as static content by IIS
2. You can go directly to URLs like that if you setup an appropriate rewrite rule in IIS
    - See this related issue: https://github.com/OHIF/Viewers/issues/606

**Comment by peerct** [comment]
please to add this to your web.config：

<system.webServer>
        <httpErrors errorMode="Custom">
            <remove statusCode="404" subStatusCode="-1" />
            <error statusCode="404" prefixLanguageFilePath="" path="/index.html" responseMode="ExecuteURL" />
        </httpErrors>
        <defaultDocument>
            <files>
                <clear />
                <add value="index.html" />
                <add value="Default.htm" />
                <add value="Default.asp" />
                <add value="index.htm" />
                <add value="iisstart.htm" />
                <add value="default.aspx" />
            </files>
        </defaultDocument>
        <staticContent>
            <mimeMap fileExtension="." mimeType="application/octet-stream" />
        </staticContent>
    </system.webServer>

**Comment by peerct** [comment]
please add this to you web.config:

` <system.webServer>
        <httpErrors errorMode="Custom">
            <remove statusCode="404" subStatusCode="-1" />
            <error statusCode="404" prefixLanguageFilePath="" path="/index.html" responseMode="ExecuteURL" />
        </httpErrors>
        <defaultDocument>
            <files>
                <clear />
                <add value="index.html" />
                <add value="Default.htm" />
                <add value="Default.asp" />
                <add value="index.htm" />
                <add value="iisstart.htm" />
                <add value="default.aspx" />
            </files>
        </defaultDocument>
        <staticContent>
            <mimeMap fileExtension="." mimeType="application/octet-stream" />
        </staticContent>
    </system.webServer>`

**Comment by peerct** [comment]
![1](https://user-images.githubusercontent.com/6157454/66976071-1d309680-f0d3-11e9-9b4d-4adb21c431e6.png)

**Comment by JiangWeian** [comment]
Thank you for you help! By looking for relevant knowledge, I have solved this problem. This problem is caused by IIS that not supporting routing. I download and setup the UrlRewrite.exe and add the web.config to the dist directory. This is my added web.config:
<?xml version="1.0" encoding="utf-8"?>

  <configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="Handle History Mode and custom 404/500" stopProcessing="true">
          <match url="(.*)" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>

In this way, when IIS cannot resolve the URL， it will return 404 page, and then cause the viewer's route.




------------------ 原始邮件 ------------------
发件人: "peerct"<notifications@github.com>; 
发送时间: 2019年10月17日(星期四) 中午11:42
收件人: "OHIF/Viewers"<Viewers@noreply.github.com>; 
抄送: "安"<717569691@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [OHIF/Viewers] How build and release viewer can open image pagewith URL(ex:http://192.168.9.137:82/viewer/1.2.840.16056.79586.20120503.143620.937.6882.4)?(#1047)

**Comment by mokbelt** [comment]
Dears,
Could you advise the same rewrite rule for Apache 2.4 httpd.conf ??
