### ISSUE TITLE
PDF viewer frame can't be closed

### ISSUE THREAD

**Issue by alcheb** [OHIF/Viewers#1049]
Hello there, first timer here. Apologies in advance. I am not a developer and my contributing skills are close to inexistent. I use OHIF primarily to look at liver imagery (CT/MR).

## Bug Report
When opening a PDF file in the viewer (DOC modality) it is not possible to close it.

### Describe the Bug
Replacing the open PDF viewer frame with another stack by drag-and-drop is not possible. Changing the layout doesn't help either. The only way around I found, besides reloading the page, is entering MPR mode on another stack and then exiting it.

### What steps can we follow to reproduce the bug?

1. Open a study containing a PDF file/DOC modality (*e.g.* https://viewer.ohif.org/viewer/1.2.826.0.13854362241694438965858641723883466450351448)
2. Drag-and-drop the DOC stack to open it
3. Try to close it

Thanks for your help!
Al

**Comment by dannyrb** [comment]
Thanks, @alcheb! No need to be a developer to help out. Reproducible bug reports like this are incredibly valuable ^_^

**Comment by mirnasilva** [comment]
Hi team! Amazing work!
Great job, @igoroctaviano ! I just did a round of tests and everything is working fine. 
The issue was fixed and I'm moving it to Done!
Thanks!
