### ISSUE TITLE
I'm not getting image.data

### ISSUE THREAD

**Issue by juanise** [OHIF/Viewers#1050]
Hi, I've been using react-cornerstone-viewport/example.
Into src/App.js i changed the source, to point to my dicom file:

```js
  const exampleData = { 
      stack: {
        currentImageIdIndex: 0,
        imageIds: [
          "dicomweb://localhost/01104CCI.dcm",
        ],
      }
```
So, when it execute image.data exits and is populated.

But when I use OHIF Viewer i don't have image.data.

In the next part of code:

```js
  function wadoUriMetaDataProvider(type, imageId) {

    var _cornerstoneWADOImage2 = cornerstoneWADOImageLoader.wadouri,
        parseImageId = _cornerstoneWADOImage2.parseImageId,
        dataSetCacheManager = _cornerstoneWADOImage2.dataSetCacheManager;

    var parsedImageId = parseImageId(imageId);
    var dataSet = dataSetCacheManager.get(parsedImageId.url);

    if (!dataSet) {
      return;
    }
```

when I use react-cornerstone-viewport example:
`imageId = "dicomweb://localhost/01104CCI.dcm"`

but when I use OHIFViewer:
`imageId = "wadors:/dicom-web/studies/9999.174780901338287554044300426359743680680/series/9999.77425552656524319077507825652554652353/instances/9999.44273083905554043655151507507458873410/frames/1"`

and dataSet is always undefined.

So, is there anyway to obtain this data?.
Any suggestion?

Thank you.

**Comment by dannyrb** [comment]
I'm not 100% sure I follow. Are you saying that your image loads as expected when using `react-cornerstone-viewport`, but not with your DICOMWeb generated instance ids? Or are you trying to access metadata for your study/series/instance and are unable to?

**Comment by juanise** [comment]
I am able to access metadata when I use example App of react-cornerstone-viewport with above changes.

And I'm not able to access metadata when I use OHIF/Viewers, because is never populated. 
But I don't know why.

**Comment by dannyrb** [comment]
What event are you using to grab `event.detail.image.data`? `cornerstone-wado-image-loader` create a Cornerstone "Image Object", but it has this shape:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/31a9b5a5eb267cfdfcf6db45218ad70c6d7ee115/src/imageLoader/createImage.js#L112-L131

The object you're playing with looks like what's returned here: 

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/31a9b5a5eb267cfdfcf6db45218ad70c6d7ee115/src/imageLoader/wadouri/dataSetCacheManager.js#L62-L66

The raw result of `dicomParser`'s `parseDicom` method [would create the object `elements`](https://github.com/cornerstonejs/dicomParser/blob/82573d94342e12b4bae4fcd2e93f91bb061474cf/src/parseDicomDataSet.js#L61).


### How we set our metadata provider:

```
  const metadataProvider = new OHIF.cornerstone.MetadataProvider();

  // ~~ Set our MetadataProvider
  cornerstone.metaData.addProvider(
    metadataProvider.provider.bind(metadataProvider)
  );

  StackManager.setMetadataProvider(metadataProvider);
```

Our `createAndAddStack` method, in our `StackManager` is responsible for adding metadata. I believe with this shape:

```js
{
      instance: image, // instance will be the data of the InstanceMetadata object
      series: displaySet,
      study,
      numImages,
      imageIndex: imageIndex + 1,
}
```

That same metadataprovider implements `getMetadata`, which takes the `imageId` and returns the stored data.

**Comment by juanise** [comment]
Ok. Time to read :).
I will back. 

Thank you again.

**Comment by juanise** [comment]
> The object you're playing with looks like what's returned here:
> 
> https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/31a9b5a5eb267cfdfcf6db45218ad70c6d7ee115/src/imageLoader/wadouri/dataSetCacheManager.js#L62-L66
> 
> The raw result of `dicomParser`'s `parseDicom` method [would create the object `elements`](https://github.com/cornerstonejs/dicomParser/blob/82573d94342e12b4bae4fcd2e93f91bb061474cf/src/parseDicomDataSet.js#L61).
> 
Yes this is the object I need. If I am not wrong it is created when an image is loaded, but it is not.

So that's what i do:

git clone https://github.com/cornerstonejs/react-cornerstone-viewport.git
git checkout tag 0.1.31
cd react-cornerstone-viewport/example
edit dependencies package.json -> change version `react-cornerstone-viewport` from `^0.1.21`, to `0.1.31`,
yarn install && yarn start

 set a breakpoint on onMouseClick on react-cornerstone-viewport/dist/index.umd.js
and  check event.detail.image.data. It is ok, data is not undefined.

next:

git clone https://github.com/OHIF/Viewers.git

follow all steps to finally run it.

 set a breakpoint on onImageRendered on react-cornerstone-viewport/dist/index.umd.js 
and  check event.detail.image.data. Data is undefined.

What I am missing?

Thank you again.

**Comment by dannyrb** [comment]
I don't know that we've made a conscious decision to expose the tags like that. Generally, a metaDataProvider will contain a map of the data, then you use the image's ID (from any cornerstone event) to request the tags from a metaDataProvider.

**Comment by juanise** [comment]
Ok I'll try to get that from somewhere. Maybe I will post the solution, If I finally find it.

Thank you for your time

**Comment by juanise** [comment]
Finally I get what i need from cornerstone.metadata.get. But there is a difference when I retrieve pixelSpacing. With cornerstone.metadata.get('x00280030', image.imageId); I get "0.5", but with image.data.string('x00280030') I was getting "0.5/0.5" or something similar. I just wonder why exist that difference. 
I think you can close this isue.

Than you

**Comment by dannyrb** [comment]
`cornerstone.metadata.get('x00280030', image.imageId);`

Should be using whatever `metadataProvider` is registered. It looks for that "key" for that "image id", and returns the value (if found) as specified by the `metadataProvider`. I'm not familiar with requesting it in this fashion using it's tag. I'll often request the modules (sets of data) that the `cornerstoneWadoImageLoader` lays out.

`image.data.string('x00280030')` is showing you the raw/parsed values from dcmjs, I believe. PixelSpacing is Decimal String with 2 values: RowSpacing/ColumnSpacing

https://dicom.innolitics.com/ciods/ct-image/image-plane/00280030
