### ISSUE TITLE
Embedded viewer within Vue.js app and Google Cloud Healthcare routing

### ISSUE THREAD

**Issue by quentin-sensome** [OHIF/Viewers#1058]
### Context

I am trying to embed the OHIF viewer within a Vue.js application. To achieve this i simply followed the [embedded viewer deployment recipe](https://docs.ohif.org/deployment/recipes/embedded-viewer.html). This setup worked and I was able to display the study list and visualise DICOMs properly.

Now, I wish to configure the OHIF viewer to use the Google Cloud Healthcare API as my data source. I also have for goal to hide the study list from the viewer (using the `showStudyList: false`option), and instead rely on custom Vue.js components, filling a similar role but with specific filtering / searching.

### Issue

I have to say I am a bit lost on how to configure the viewer properly to route to specific DICOM instances. Actually, I was not even able to display the study list, so that it could handle the routing to the DICOM instances itself.

I followed the [Google Cloud Healthcare recipe](https://docs.ohif.org/connecting-to-image-archives/google-cloud-healthcare.html), and also changed the viewer's configuration to enable the Google Cloud adapter (comments are from the original `config/google.js` file):

```js
var containerId = "root";
var componentRenderedOrUpdatedCallback = function() {
    console.log("OHIF Viewer rendered/updated");
};

window.OHIFViewer.installViewer(
    {
        routerBasename: "/",
        enableGoogleCloudAdapter: true,
        servers: {
            // This is an array, but we'll only use the first entry for now
            dicomWeb: []
        },
        // This is an array, but we'll only use the first entry for now
        oidc: [{
            // ~ REQUIRED
            // Authorization Server URL
            authority: "https://accounts.google.com",
    	    client_id: "XXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com",
    	    redirect_uri: "/callback", // `OHIFStandaloneViewer.js`
            response_type: "id_token token",
	    scope: "email profile openid https://www.googleapis.com/auth/cloudplatformprojects.readonly https://www.googleapis.com/auth/cloud-healthcare", // email profile openid
            // ~ OPTIONAL
    	    post_logout_redirect_uri: "/logout-redirect.html",
    	    revoke_uri: "https://accounts.google.com/o/oauth2/revoke?token=",
            automaticSilentRenew: true,
	    revokeAccessTokenOnSignout: true
        }],
        studyListFunctionsEnabled: true
    },
    containerId,
    componentRenderedOrUpdatedCallback
);
```

When landing on the page responsible for installing the viewer, I get prompted to login with a google account (so far so good), but get redirected to the `/callback` route, which lands I believe nowhere. The comment `// OHIFStandaloneViewer.js` seems to indicate the callback route is not meant to work with the embedded viewer.

What do you think I am missing here ? Are there any pointers I could follow to make this work ?

**Comment by quentin-sensome** [comment]
Here is a [minimal Vue.js CodeSandBox](https://codesandbox.io/s/vue-template-gjwbn?fontsize=14), which uses Vue Router to route requests to the embedded viewer.

For this set up to work, the following needs to be done:
  - replace the `client_id` property in the `EmbeddedViewerComponent` with your OAuth 2.0 Client ID.
  - add `csb.app` to your OAuth Consent screen authorized domains.
  - add `https://gjwbn.csb.app` to your list of authorized javascript origins.
  - add `https://gjwbn.csb.app/ohif/callback` to your list of authorized redirect URIs.

Note that I ideally, I would like to get rid of the study list altogether, and directly route to specific DICOM instances. Any suggestion on this ? Thanks.

**Comment by dannyrb** [comment]
I think the issue is, simply, that for the OAuth flow to work, you need to be able to hit the `/callback` route of the OHIF application. This is part of the OAuth flow where you receive an authorization code from Google. That code is likely used by our app to validate the handshake with Google and acquire a token that can be used in subsequent calls.

Because the OHIF application isn't handling routing in the embedded scenario, you'll need your application to handle the handshake. Next, you _should_ be able to override the OHIF Viewer's auth to simply use the provided token, assuming you've configured a DICOMWeb Server correctly.

I'm not sure there's a way, currently, to leverage the Google Adapter + Store Picker in the embedded scenario. We'd be willing to accept a PR to support the use case, but it should probably be the parent app handling the handshake and our app receiving the info it needs to make requests.

**Comment by dannyrb** [comment]
This probably isn't on our short or mid-term roadmap. I can provide some light guidance and review PRs, but we don't have the bandwidth to spearhead the implementation for this with current funding.

**Comment by Diex** [comment]
in my case (angular) I added:

`  { path: 'dicoms', component: OhifComponent },
  { path: 'dicoms/callback', component: OhifComponent},
`
in my Routes[] list.

@dannyrb my question is : how could I override the OHIF Viewer's auth to simply use the provided token?
thx

**Comment by HowardLander** [comment]
I actually have the exact same question as @Diex.  We have already, elsewhere in our platform, performed the Google OIDC workflow and have the token.  What I would really like is to be able to set the token as an environment variable: much like the CLIENT_ID env variable directs the viewer to the Google Health API, I'd like to be able set an ENV var called (for example), GOOGLE_CLIENT_TOKEN which when set would bypass the OIDC workflow and provide the token directly to the viewer.  Does that sound feasible?
