### ISSUE TITLE
Why viewer haven't the basic function of Synchronizing Series and Reference Line? When will these functions be implemented?

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#1060]
The function of Synchronizing Series and Reference Line are basic demand for browse of CT or MR study. These functions is more basic and essentially then MPR, 3D images and so on. I hope and believe viewer team will be implemented these functions as soon as possible.

**Comment by swederik** [comment]
Reference lines has a ticket already here: https://github.com/OHIF/Viewers/issues/619 but I don't believe we have one open for synchronized scrolling.

I tend to agree that these are useful features, but we haven't gotten around to implementing them after the move to React and I don't know where they sit on our roadmap. If your group has engineering team members, we can help guide them to implement the functionality. If you have funding, you can look at [Commercial Support](https://docs.ohif.org/help.html#commercial-support).

What may be helpful is to document the expected end-user interaction with synchronized series scrolling:
- How does the user enable it?
- How does the user select which viewports to synchronize?
- What types of synchronization are necessary (image position? Cornerstone has a number of these)?

If you could screenshot or make videos of some implementations in other viewers which you (as a clinician) find to be user-friendly, it would be helpful to see them.

**Comment by salimkanoun** [comment]
Hi,

I have seen this kind of feature in some web app and here are somes ideas

- The user does not have to enable it, it is automatically activated when multiple series are visualized in the same view (so if the layout have at least 2 images it can be activated) and sync is applyed only to series that could be synced (ignoring secondary capture, scoot for example)

Salim
- Yes I think ImagePosition is the correct one by taking in the other series the one with the closest image position.

I think in OHIF the issue will be that this will significantly increase Ajax request to retrieve images and could be detrimental in rendering speed as N series has to be loaded. 
Maybe a button to enable this "auto sync series" could be useful to activate / deactivate (and keept in memory in user preferences).

**Comment by JiangWeian** [comment]
The synchronized series 
scrolling and reference lines I have seen in Open Source of ClearCanvas. But ClearCanvas is a Windows desktop application, the code source link is https://github.com/ClearCanvas/ClearCanvas, your can download it and compile the ImageViewer.sln. In this application:
- Enable or disable synchronized series scrolling or reference lines via clicking buttons.
- Which series can apply synchronized scrolling or display reference lines are automatically calculated, these data for calculating can be available in DICOM meta information.
I have done some projects with ClearCanvas Open Source. I made a video to show these two features. Hope your can see these videos.
[Video.zip](https://github.com/OHIF/Viewers/files/3748734/Video.zip)

**Comment by dannyrb** [comment]
👞 💨 🤖

**Comment by dannyrb** [comment]
Some more info on synchronization: https://github.com/cornerstonejs/cornerstoneTools/issues/1162

**Comment by richsmith123** [comment]
Hello All,

It seems like some people already have implemented basic functionality of **Synchronizing Series** and **Reference Line** on their own. However, is there any possibility of implementing these two much needed features as part of the official release?

Thank you!

**Comment by dannyrb** [comment]
@richsmith123, the grant and organizations currently funding OHIF development don't have these features on the short-term roadmap. We would be more than happy to review a community PR that adds these features, or I can connect you with a consultant capable of delivering them.

We're working on more transparently showing what is "near future", but the best way to see anything time sensitive contributed is to do the work (author a Pull Request), or to work with someone who can.

**Comment by salimkanoun** [comment]
Hi there,

I found someone with an educational project on radiology, he is missing series Scroll Sync to start teaching with OHIF.

He would want to make a first teaching session mid december.
And he can fund this developpement. (And i think once his group will start teaching with OHIF other developpement will appear)

I dont know what is the status of this feature. However if it Can be scheduled, i have an opportunity for funding.

Best regards 

Salim

@dannyrb @swederik

**Comment by JiangWeian** [comment]
@salimkanoun @dannyrb  , What's the situation? Is Synchronizing Series and Reference Line  possible implementation?

**Comment by salimkanoun** [comment]
We are discussing it, I have a funding for them but money does not resolve everything, they have to get developper's time with experience in OHIF to build this.

**Comment by sedghi** [comment]
This are implemented in mater right now
