### ISSUE TITLE
erro 404 access study URL link

### ISSUE THREAD

**Issue by ramonsousa89** [OHIF/Viewers#1063]
Hello,

when I try to access the viewer via a link,

http://192.168.0.3:8081/viewer/1.3.12.2.1107.5.1.7.135302.30000019093007210965200000282

when I access this link in another tab, or in another browser, from error 404, my version is compiled into ubuntu.

**Comment by dannyrb** [comment]
This sounds like a server configuration issue. There is no "static file" located at that route. You need to configure your server to fallback to the `index.html` for `404`s. You can see an example of how we accomplish this in our own `nginx` configuration file:

https://github.com/OHIF/Viewers/blob/b59c8c277af38ab601c2f3baa5a0cef8841c4438/platform/viewer/.recipes/OpenResty-Orthanc/config/nginx.conf#L116-L121

How you accomplish this will vary from web server to web server

**Comment by ramonsousa89** [comment]
thank you for answering, but I couldn't understand,

when i try to access the study link, still with error 404, i'm using config / default.js, my pacs is dcm4chee.

**Comment by dannyrb** [comment]
When you request that URL, the simple server you're using looks for a literal folder/file at that location. When it can't find one, it shows the `404` not found error. Whatever web server you land on, it needs to support the ability to "try other files" or "fallback" if it cannot find a file at that location.

The OHIF Viewer is a "single page application"; which means all routing is handled by the client application, and not at the server. Hence the need to fallback to the the `dist/index.html` file (our application entrypoint).

It sounds like you're using a simple npm package to serve the files. You'll likely need something more robust for production usage, and that can support falling back to `index.html` for 404s.

Popular web servers would be:

- `nginx` (linux)
- `iis` (windows)
- `apache`

And then use a "rewrite rule" or "fallback" to serve the `index.html` if a `404` (not found) error would normally be served. 

It's also possible to accomplish this with many simple hosting services. You have a lot of options. Hopefully this shines a little more light on where you currently stand.

It's worth noting that you may also encounter CORS errors if you intend to host the Viewer at a domain or port different from your PACS. These are possible to work around, but may be difficult without some level of technical assistance.

**Comment by ramonsousa89** [comment]
Thank you very much brother, it worked perfectly, I was not understanding the fact that running OHIF on any web server, now that I understand and it worked, thank you, God bless you.
