### ISSUE TITLE
hiding/removing "measurements" button?

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1067]
Hello,
         is there any way to hide/remove the "measurements" button?

![Annotation 2019-10-21 140732](https://user-images.githubusercontent.com/5023419/67192109-69017980-f40c-11e9-9caf-20f47c819757.png)

**Comment by dannyrb** [comment]
Hi @ranasrule, this button is added when the `MeasurementsExtension` registers itself. You _should_ be able to remove it by modifying this array:

- https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/App.js#L171-L176

It's currently a default extension for the PWA and `@ohif/viewer` builds, as there are some parts of the application that still need to be decoupled from it. When that happens, we'll remove it as part of the default bundle and you'll need to add it to the PWA entry point or register it at runtime for packaged source use.
