### ISSUE TITLE
Single-click to load thumbnail only works after performing drag-n-drop

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1072]
Related to #895. Issue still happening.

### Description

User is not able to load a new series by single-clicking on a thumbnail. This is only possible after performing an initial drag-n-drop.
This issue can also be reproduced with multiple layouts.

![bug-singleclick-thumbnail](https://user-images.githubusercontent.com/13245529/67342168-f4136a00-f507-11e9-9654-a38a0d683271.gif)

### Steps to reproduce

1. Load a study
2. Single-click on any thumbnail
3. Verify that the series was not loaded
4. Drag-n-drop any thumbnail into the viewport
5. Single-click again on any thumbnail
6. Verify that the series was loaded with success

### Acceptance Criteria

User should be able to load a new series by single-clicking on the thumbnail. This should be valid for single viewport and multiple viewports.

**Comment by dannyrb** [comment]
This is resolved; We've created separate smaller issues to address the other incorrect behaviors around this.
