### ISSUE TITLE
Returning to the Study List before all series have finished loading throws multiple errors in console

### ISSUE THREAD

**Issue by emfol** [OHIF/Viewers#1075]
### Reproduction Steps

1. Make sure lazy load of series is enabled
2. Load a study with multiple series;
3. Before all series finish loading, click the `Study List` button to return to the study list;
4. Check the errors in the console;

![console-errors](https://user-images.githubusercontent.com/1145367/67397634-db469b00-f57f-11e9-9cfe-ce664ebddf7f.png)

**Comment by dannyrb** [comment]
PR: https://github.com/OHIF/Viewers/pull/1090
