### ISSUE TITLE
When layout is decreased, the activeViewport is not set to an index that is still available

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1077]
- Set viewport 9 active
   - Shrink to 1x3
   - The active viewport should switch to number 1

This is a regression. We need an E2E test to make sure it doesn't continue to slip back in.

- [ ] **Should have E2E test**

Previously resolved here: https://github.com/OHIF/Viewers/issues/999

You can add the E2E test yourself, or complete this issue and create a new issue specific to creating an E2E test. If you create a new issue, please let me know.

**Comment by rodrigolabs** [comment]
As I said here: #1146, it seems to not be a bug anymore, since the right viewport is being set as active.
The E2E test was created in #1146.
