### ISSUE TITLE
Delay loading dicom images on local server running OHIF

### ISSUE THREAD

**Issue by ramonsousa89** [OHIF/Viewers#1096]
I'm not sure if this is a BUG, but here's my question:
I'm running pacs and OHIF on the same server locally, but the images take a long time to load, download, the word LOADING comes up ... very often, there is some way to load the images faster, running multiple instances while loading series images?

**Comment by pieper** [comment]
What pacs are you using?  What kinds of studies?

**Comment by ramonsousa89** [comment]
> What pacs are you using? What kinds of studies?

Dcm4chee arc light

**Comment by pieper** [comment]
Dcm4chee usually performs pretty well.  That's what we use for the demos on viewer.ohif.org.  Does that work okay for you?

**Comment by dannyrb** [comment]
@ramonsousa89, more than happy to re-open this, but unfortunately we don't have enough information to assist you at this point in time. Best of luck 👋
