### ISSUE TITLE
Misc. Measurement Table issues:

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1098]
1. Unable to remove description once set
  - Add a description to a measurement
  - Edit description
  - Attempt to set to an empty value
  - Description is not updated/removed
2. Not enough visual separation between the measurement's label and description
  - Add a label to a measurement
  - Add a description to a measurement
  - Notice that parentheses has no space between label
  - Potentially start description on a new line, or at least add a space
3. Long descriptions overflow off screen
  - Add a measurement with an obnoxious description
  - `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
  - Note that the css "break-word" is not used, so text overflows off screen
4. Unable to save description by hitting enter
  - Right click a length measurement
  - Click Relabel
  - Click edit description
  - Attempt to set new description by hitting enter

**Comment by ladeirarodolfo** [comment]
Coding for it.
