### ISSUE TITLE
Any way to save annotations?

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1102]
Is there any way to save annotations in OHIF Viewer 2.x? If not, is it part of the roadmap?

**Comment by dannyrb** [comment]
1. You could do this with a quick and dirty extension that has a SidePanel module
2. To Persist:
    - Panel has a button that serializes cornerstone toolstate
    - Serialized toolstate is passed to the backend of your choice
3. To Restore:
    - Panel initiates request to check for existing/persisted toolstate
    - If it exists, button to "restore" toolstate is shown as "active"
    - Clicking "restore" hydrates cornerstone's toolstate

We're also very open to exposing new extension points and services based on community needs as we continue to identify those needs.

Long-term, our default/bundled solution will be persistence with DICOM-SR. You can see an in-progress PR here: https://github.com/OHIF/Viewers/pull/954

**Comment by dannyrb** [comment]
We're using this issue to track progress: https://github.com/OHIF/Viewers/issues/758
You can see it on our short-term roadmap as in-progress here: https://github.com/OHIF/Viewers/projects/4?card_filter_query=assignee%3Agalelis

We're definitely open to exposing an extension point around this functionality. Not everyone is going to want to use DICOM SR to persist/restore annotations. More than happy to kick up a discussion and scope out something we would be willing to merge if implemented.

**Comment by KhyatiMehta3** [comment]
Hey @dannyrb could you provide a sample code reference for the mentioned process? I'm trying to add a segmentation tool extension and want to load the marked segmentation to the DICOM. I'm looking at the process you've provided but unable to find a vague code reference to get started. Could you help me out? I'd like to send a PR after implementing this too.
