### ISSUE TITLE
Improve control over test data

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1104]
- docker-compose or docker image that contains a DICOMWeb instance
- Simple, version controlled, studies
- CI uses image

1. Allows for tests to happen locally (much faster)
2. Allows for tighter control of the data we're using for testing
3. Decreases the chances that data changes will break existing tests
4. Also functions as a quick way to develop "offline"/locally

**Comment by sedghi** [comment]
Done in master
