### ISSUE TITLE
About Modal version is one version behind

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1105]
Here's how this is happening:

- CI builds solution
- Unit tests pass, e2e tests pass
- CI splits and runs in parallel
    - NPM_PUBLISH (where new version is determined)
    - BUILD_DEMO (version is pulled from package,json, build # from CI)

So the updated version number from `NPM_PUBLISH` is not used. To fix this, we can chain `BUILD_DEMO` after `NPM_PUBLISH`. To persist the updated version, we need to create a simple text file that contains the version, or set it as an env variable that `BUILD_DEMO` can use.

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
