### ISSUE TITLE
Series automatic loading

### ISSUE THREAD

**Issue by ramonsousa89** [OHIF/Viewers#1107]
Hello,
I would like to know if there is a possibility of loading the series automatically avoiding the doctor to startup every serie he would like to reed at once loading images.
Is there any way to enable to load the series automatically?
Example, RM with 10 series:
Load series 1 and after that, follow the sequence below OR else load all series at once.

**Comment by dannyrb** [comment]
We have something called the "StudyPrefetcher" that is not currently implemented in this version of OHIF. The idea is that series, other than series currently visible in viewports, will be lazy loaded into the cache in the background (assuming the cache is not full).

If you're interesting in spiking a change to implement this, I can point to how it was implemented in OHIF v1, and provide some guidance on how it should probably be implemented in v2.

This is on our roadmap, but I'm not sure it's prioritized for near future.

**Comment by dannyrb** [comment]
Best to track the issue here: https://github.com/OHIF/Viewers/issues/1000

**Comment by vicOnGit75** [comment]
Hello,
Can you "point to how it was implemented in OHIF v1, and provide some guidance on how it should probably be implemented in v2.", please?

**Comment by dannyrb** [comment]
Can you comment on #1000? That is the tracking issue for this feature.
