### ISSUE TITLE
Study Date: no mask, no validation and clear button disappears

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1120]
### Description

**A couple of issues were found on Study Date fields:**
1. Once user clicks on `Clear dates` button, the button disappears and user is not able to clear the fields again if he/she adds the dates manually. The button only shows again if the user selects a date on the Date Picker.
2. User is able to insert more characters than 8, including letters. There is no validation when user inserts the value manually. i.e. `12341231234`or `asdfasdfasdf`.
3. When user manually inserts a date (typing it) the field does not add a mask into the added value. i.e. User adds `10102000`, the field should mask it as `10/10/2000`.
4. When user manually inserts an invalid date (i.e. future date), there is no warning/error message to inform that the date is invalid. Although the results are not filtered by the invalid date, it may confuse the user and mislead he/she to think that the results are correctly filtered. _**Suggestion:** display an error message after field validation and display 0 study results on the table list._
5. When user manually inserts a valid start and end dates, the search is returning 0 results. i.e. `01/01/2000 and 10/10/2019`

**Improvement:**
1. User is not able to navigate between `years` on the date picker. If the user wants to select a start date from year 2000, he/she has to navigate month-by-month until he/she gets to the desired year. 
_**Suggestion:** can we also add a year range selection? Once user clicks on the date picker header (where is placed `Month Year`), then a year range could be displayed like in [this example](http://jsfiddle.net/lemonkazi/ucfxywh6/)_ 
2. Once user opens the date picker and selects the Start Date, the selected range follows the mouse cursor on the calendar and the dates inside the range become white/light gray. The light gray color can mislead the user to think that those are invalid/unavailable dates instead of the selected range. _**Suggestion:** can we change the color of the selected range? Maybe use the same light blue of the application version label in the cell background (`#9ccef9`)._

![Screen Shot 2019-10-28 at 21 09 06](https://user-images.githubusercontent.com/13245529/67727216-4a305380-f9c7-11e9-8a03-39b75e5fba9a.png)

![Screen Shot 2019-10-28 at 21 21 38](https://user-images.githubusercontent.com/13245529/67727677-12c2a680-f9c9-11e9-9ec0-88a3f12ac409.png)

**Comment by dannyrb** [comment]
I think these are good UX improvements, and some are clearly small bugs that need fixed (for our usage, anyway). Thanks for taking the time to right up a report :+1:

**Comment by dannyrb** [comment]
The bulk of these issues are fixed in #1153, but some are not possible with the library we're using. Most are minor enough that I don't know it's worth the cost of swapping out for a new component. I'll close this PR when #1153 is merged.
