### ISSUE TITLE
Manifest assets at incorrect route

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1125]
#  Bug Report

### Describe the Bug

The manifest asset paths are static `/assets/name-of-file.png`, but where they're hosted is not. If the PUBLIC_URL is at a non-root route (`/pwa` or `/viewer`) the asset paths may not resolve. The manifest icon paths need to be set at runtime to access the environment variable that indicates our directory, or we need to identify a way to set them relative to the app's "base route"

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
