### ISSUE TITLE
Show "Loading..." message instead of blank black page when study is opened 

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1132]
OHIF viewer should show a "Loading..." message instead of blank black page when study is opened. This was the behavior in 1.x. Without this the user gets confused weather the study is being loaded or not.

![Annotation 2019-10-30 121508](https://user-images.githubusercontent.com/5023419/67836984-d188de80-fb0f-11e9-85e9-86f05c904b3d.png)

**Comment by dannyrb** [comment]
@ranasrule I think we actually want to get to the point where there is no "loading". We're in the process of cleaning up our service worker and codesplitting usage to achieve this. Time to first paint should be less than 500ms.
