### ISSUE TITLE
Add funding acknowledgment of the IDC project

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1136]
## Request

**What feature or change would you like to see made?**

Add acknowledgment of funding from the IDC project: "NCI Imaging Data Commons: contract number 19X037Q from Leidos Biomedical Research under Task Order HHSN26100071 from NCI."

**Why should we prioritize this feature?**

Because IDC project is funding some of the effort for the OHIF developers, prioritizing for the specific features as needed for IDC.

@pieper I do not have the permissions to assign labels - can you please add "IDCwishlist"?

**Comment by dannyrb** [comment]
👋 @fedorov, added you as an outside collaborator. Don't hesitate to reach out if you experience other permission related issues.

**Comment by fedorov** [comment]
Just seeing this - @swederik added me to the organization. I am fine either way. Thank you guys!

**Comment by pieper** [comment]
Just readme in repo is fine

**Comment by fedorov** [comment]
I can make a PR to make it simpler

**Comment by fedorov** [comment]
@sedghi @igoroctaviano IDC acknowledgment somehow disappeared from the OHIF README - can this be added back?

**Comment by sedghi** [comment]
sure

**Comment by igoroctaviano** [comment]
Done!
