### ISSUE TITLE
requestOptions.auth isn't saved in sessionStorage when using a function

### ISSUE THREAD

**Issue by MuriloSchaefer** [OHIF/Viewers#1137]
### Describe the Bug
I had the same problem described in [#928](https://github.com/OHIF/Viewers/pull/928). So I used its solution, setting `requestOptions.auth` in server configs as a function, to be called by `getAuthorizationHeader()` to get authorization headers. 

The problem is that when the app starts it calls `addServers`, which call the dispatch function in redux:

addServers.js
``` addServers.js
const addServers = (servers, store) => {
  if (!servers || !store) {
    throw new Error('The servers and store must be defined');
  }

  Object.keys(servers).forEach(serverType => {
    const endpoints = servers[serverType];
    endpoints.forEach(endpoint => {
      const server = Object.assign({}, endpoint);
      server.type = serverType;

      store.dispatch({
        type: 'ADD_SERVER',
        server,
      });
    });
  });
};
```

But before save it, redux uses `JSON.Stringify` to convert to string and the `stringify` function ignores functions in the object, so the `requestOptions` ends up without `auth` key:

sessionStorage.js
``` sessionStorage.js
export const saveState = state => {
  try {
    const serializedState = JSON.stringify(state);
    SessionStorageApi.setItem(sessionStorageKey, serializedState);
  } catch (e) {}
};
```

So, my config file is as shown below:
``` js
servers: {
    dicomWeb: [
      {
        name: 'DCM4CHEE',
        ...
        requestOptions: {
          auth: () => {
            return 'token';
          },
        },
      },
    ],
  },
```
But the config saved in sessionStorage is:
``` js
servers: {
    dicomWeb: [
      {
        active: true
        name: 'DCM4CHEE',
        ...
        requestOptions: {
        },
      },
    ],
  },
```
any method after this call the config in the sessionStorage, which does not have the auth function.

What would be the best approach to solve it? 
I thought as a workaround I call the `auth` method before the app call `addServers` and update `requestOptions.auth` to have the token before saving it into the storage. But this is not even close to the best approach

**Comment by adamdav** [comment]
> I thought as a workaround I call the auth method before the app call addServers and update requestOptions.auth to have the token before saving it into the storage. But this is not even close to the best approach

Would it make sense to take that approach and bake it into `addServers`?

```
const addServers = (servers, store) => {
  if (!servers || !store) {
    throw new Error('The servers and store must be defined');
  }

  Object.keys(servers).forEach(serverType => {
    const endpoints = servers[serverType];
    endpoints.forEach(endpoint => {
      const server = Object.assign({}, endpoint);
      server.type = serverType;

      // Call auth function before saving to session storage
      if (server.requestOptions && server.requestOptions.auth && typeof server.requestOptions.auth === "function") {
        server.requestOptions.auth = server.requestOptions.auth(server.requestOptions)
      }

      store.dispatch({
        type: 'ADD_SERVER',
        server,
      });
    });
  });
};
```

**Comment by MuriloSchaefer** [comment]
I think this is a good workaround initially, but this creates some edge cases, i.e. what if the token generated has a time to live and need to be updated? I still don't have the answer to this question.

**Comment by dannyrb** [comment]
Ideally, you're using an authentication workflow that our `oidc` settings support. This allows for things like timeouts, refresh tokens, etc.

We can discuss pulling "authentication" configuration and lifecycle out of `@ohif/viewer` and into `@ohif/core`, then exposing those hooks with `@ohif/viewer`'s application configuration. Most clientside auth isn't a "forever valid" token, so hooks to address common situations would be a nice value add.

What are the situations we should support? Where would you expect there to be hooks?

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
