### ISSUE TITLE
Deployed but getting just a black window

### ISSUE THREAD

**Issue by julivert82** [OHIF/Viewers#114]
Hi,

I've tried to run the OHIF viewer locally, I followed all the steps and now the OHIF viewer is properly install using the settings with orthanc DICOMweb which is running into a docker container on the same server.

Basically, accessing the URL http://IP:3000 gives me a nice black screen.

I've checked the JSON file with the settings and it's using some url which doesn't exist on the Orthanc like BASEURL/wado and BASEURL/dicom-web

Does anyone have a clue about what I did wrong?

Cheers

**Comment by julivert82** [comment]
Added into the wiki a page about step by step configuration:
https://github.com/OHIF/Viewers/wiki/Step-by-Step-installation-of-OHIFViewer-in-Ubuntu-14-and-above

Cheers

**Comment by swederik** [comment]
This is a common mistake. Orthanc doesn't have those URLs by default. They are added when you use the Orthanc DICOMWeb plugin (https://bitbucket.org/sjodogne/orthanc-dicomweb/ https://www.orthanc-server.com/static.php?page=dicomweb).

**Comment by arunnad007** [comment]
HI everyone,
I have exact same problem like juli-vert. Dicomweb plugin is installed ,but same black window only i am seeing
Any solution please
