### ISSUE TITLE
Blank MPR windows

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#1140]
### Describe the Bug

MPR mode doesn't work for this study:

https://idc-sandbox-000.firebaseapp.com/projects/idc-sandbox-000/locations/us-central1/datasets/sdp-dev/dicomStores/scratch/study/61.7.22285965616260355338860879829667630274

### What steps can we follow to reproduce the bug?

* Open the study
* click 2D MPR mode
* reformatting progress messages appear, but the windows remain black
* tools appear to be working, but nothing ever shows up

**Comment by pieper** [comment]
Note that this is a 661 slice CT, so that's 338MB of texture memory.

**Comment by dannyrb** [comment]
Is there a separate form or approval process to gain access to the `idc-sandbox-000` project? If it's not available at this time, is there another way for you to share this study?

**Comment by pieper** [comment]
Sorry, yes, I'll request access for you.

This gets you to the same study pulled from TCIA:

https://idc-sandbox-000.firebaseapp.com/projects/chc-tcia/locations/us-central1/datasets/ct-lymph-nodes/dicomStores/ct-lymph-nodes/study/61.7.22285965616260355338860879829667630274

**Comment by dannyrb** [comment]
In `getOrCreateVolume`, we see that `imageMetadata0` has an undefined width and center. Setting `lower`/`upper` range to `NaN` doesn't throw an error or warning, but it does appear to be the issue.

If we instead use any number as a fallback, everything begins working again.
