### ISSUE TITLE
load series from array of .dcm files

### ISSUE THREAD

**Issue by pedropaulofreitas** [OHIF/Viewers#1144]
Hi, I have a server that returns me image series as an array of dicom images links that belong to that particular series, is it possible to integrate this api with the viewer without creating a dicomWeb server?

**Comment by dannyrb** [comment]
See: https://github.com/OHIF/Viewers/issues/891

You can add a queryString parameter `url` who's value is a URL that returns JSON. If the JSON matches this format:

https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/PTCTStudy.json

You can get around using a `dicomWeb` server.

After some recent changes, we're in a better place to allow a higher degree of customization around data fetching and mapping to our application's viewmodel, but I don't believe it's a priority at the moment.

**Comment by pedropaulofreitas** [comment]
thanks!
