### ISSUE TITLE
E2E tests: visual snapshot comparison

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1149]
Cornerstone:
- Pan tool
- Invert tool
- Rotate Right tool
- Flip H
- Flip V

VTK:
- Crosshairs
- WWWC
- Rotate
- Slab Thickness
- MIP, AvgIP, MinIP

Microscopy:
- Pan

**Comment by dannyrb** [comment]
@mirnasilva, you can also do a `mousewheel` zoom with the Microscopy plugin

**Comment by dannyrb** [comment]
New ones:

- About Modal open
- Download Modal open
- Hotkey Settings Modal open (soon, not yet merged)
