### ISSUE TITLE
Can this be implemented in Angular 7?

### ISSUE THREAD

**Issue by zuesmano** [OHIF/Viewers#1155]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by swederik** [comment]
Implemented in what way? Embedded into an Angular application?

**Comment by zuesmano** [comment]
Yes i have embedded into my angular application

**Comment by dannyrb** [comment]
> Can this be implemented in Angular 7

Yes ^_^

**Comment by Diex** [comment]
Hi! I'm new to the project. I'm starting to integrate OHIF in my angular app.
Our goal is to implement a prosthesis CAD designer.

At this time I read over the docs but still there's nothing in this topic actually useful. 

this seems to be something  going on here: https://github.com/OHIF/Viewers/issues/1755 but still no demo/example.

on my side I tryed: 

`<div [innerHTML]="ohifviewer | async"></div>`

`this.ohifviewer = httpSv.getHtml('assets/ohif-viewer.html');
`

and the service goes like: 

```
getHtml(source: string) {
    const headers: HttpHeaders = new HttpHeaders({ Accept: 'text/html'});
    return this.http.get(source, { headers, responseType: 'text' }).pipe(
      tap((res: any) => res),
      catchError(this.handleError)
    );
  }
```

but what I get is a pretty obvious:

"OHIF Standalone Viewer You need to enable JavaScript to run this app."

any direction in wich path I should continue tryng will be really apreciated. 
thank you very much !

**Comment by dannyrb** [comment]
👋 Hi @Diex, you may have better luck asking this in a new issue. Closed issues aren't often revisited. Your request is outside the scope of what we can active support and provide guidance on -- hopefully a different community member will be able to lend some assistance.

As this isn't really a medical imaging question, or even all that OHIF specific, StackOverflow may also provide some helpful insights.
