### ISSUE TITLE
StudyUID become a mess! If access viewer with URL http://localhost:3000/viewer/3250535166565556525152515252537056575065536753544851535150576953

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#1156]
I test this problem is due to the StudyUID in the URL does not contain '.'
In console log see the picture 
![1](https://user-images.githubusercontent.com/56569509/68380446-cc203980-018a-11ea-9816-5657b89bc2ae.png)

If I add a '.' in StudyUID, URL such as "http://localhost:3000/viewer/3250535166565556525152515252537056575065536753544851535150576953.", 
the uid will be displayed.
In console log see the picture 
![2](https://user-images.githubusercontent.com/56569509/68380653-3638de80-018b-11ea-86fc-58060c1e55d2.png)

**Comment by dannyrb** [comment]
O_O That's really odd.
Is there an easy way to reproduce this?
Will any study with an ID not containing a `.` cause this issue?

**Comment by JiangWeian** [comment]
@ Memberdannyrb, enter URL 'http://localhost:3000/viewer/3250535166565556525152515252537056575065536753544851535150576953' manually in the URL bar can reproduce this issue. Or replace a simpler URL 'http://localhost:3000/viewer/123', the '123' will become a mess.

**Comment by dannyrb** [comment]
This isn't reproducible on our demo viewer: https://viewer.ohif.org/viewer/123
I'm also unable to reproduce using the local Webpack Dev Server.

**Comment by JiangWeian** [comment]
@Memberdannyrb, do you have pressed F12 to see the output of the console?

**Comment by JiangWeian** [comment]
@Memberdannyrb, OK, I have find the reason. The problem is due to the following code (line in '\Viewers-master\platform\core\src\utils\urlUtil.js'):
const decode = (strToDecode = '') => {
  try {
    const decoded = window.atob(strToDecode);
    return decoded;
  } catch (e) {
    return strToDecode;
  }
};

If strToDecode does not contain ‘.’, the method of window.atob() will turn it into a base-64 decoded string that is that mess. If strToDecode does contain ‘.’, this code will trigger an exception, directly return strToDecode! 
So, for safety, the StudyUID or other UID should use base-64 encode. And I think you should explain this in your user manual.

**Comment by JiangWeian** [comment]
@Memberdannyrb, I think should add a code in onSelectItem (line in '\Viewers-master\platform\viewer\src\studylist\StudyListRoute.js'), call window.btoa() method turn 'studyInstanceUID' into a base-64 encoded string:
          onSelectItem={studyInstanceUID => {
			 var base64StudyUID = window.btoa(studyInstanceUID);
            const viewerPath = RoutesUtil.parseViewerPath(appConfig, server, {
              studyInstanceUids: base64StudyUID,
            });

Should I pull request?

**Comment by dannyrb** [comment]
@JiangWeian, a pull request would be great! If you have the time/ability, a small unit test to verify the fix would also be appreciated. If not, if you leave your PR open for contributions, I can tack one on.

**Comment by JiangWeian** [comment]
@Memberdannyrb, I have pull request #1160. Will you deal with the request?

**Comment by dannyrb** [comment]
:boot: :dash: :robot:

**Comment by dannyrb** [comment]
👢 💨 🤖

**Comment by dannyrb** [comment]
Related to: https://github.com/OHIF/Viewers/pull/1175

**Comment by sedghi** [comment]
Take a look at our URL configuration


https://docs.ohif.org/configuration/configurationfiles/#environment-variables
