### ISSUE TITLE
Why does the URL of each interface point to the same in the runtime?

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#1163]
As shown in the picture:
![11](https://user-images.githubusercontent.com/56569509/68648519-86cd8480-055b-11ea-8ad0-fd9e2ae59b42.png)
Each interface URL points to 'qidors'. I thick it's unsafe in the runtime.

**Comment by dannyrb** [comment]
Are you experiencing any issues? (Failing requests in the app)

What does your app configuration file look like? Do you see the same values when using the default configuration file?

**Comment by JiangWeian** [comment]
I have find the reasons. It is caused by incorrect use of dicomweb-client. Line in 'Viewers-master\platform\core\src\studies\services\wado\retrieveMetadataLoaderAsync.js', should be modified as follows:
export default class RetrieveMetadataLoaderAsync extends RetrieveMetadataLoader {
  configLoad() {
    const { server } = this;
	
	var options = {
		url: server.baseUrl,
        headers: DICOMWeb.getAuthorizationHeader(server),
		qidoURLPrefix: server.qidoURLPrefix,
		wadoURLPrefix: server.wadoURLPrefix,
	};
	
	const client = new api.DICOMwebClient(options);
    this.client = client;
  }

the value of 'options' should contain qidoURLPrefix and wadoURLPrefix, even stowURLPrefix. If not, the same values will be assigned to qidoURL, wadoURL and stowURL in dicomweb-client through else statement. The relevant code in dicomweb-client as follow:
      if ('qidoURLPrefix' in options) {
        console.log("use URL prefix for QIDO-RS: ".concat(options.qidoURLPrefix));
        this.qidoURL = this.baseURL + '/' + options.qidoURLPrefix;
      } else {
        this.qidoURL = this.baseURL;
      }

      if ('wadoURLPrefix' in options) {
        console.log("use URL prefix for WADO-RS: ".concat(options.wadoURLPrefix));
        this.wadoURL = this.baseURL + '/' + options.wadoURLPrefix;
      } else {
        this.wadoURL = this.baseURL;
      }

      if ('stowURLPrefix' in options) {
        console.log("use URL prefix for STOW-RS: ".concat(options.stowURLPrefix));
        this.stowURL = this.baseURL + '/' + options.stowURLPrefix;
      } else {
        this.stowURL = this.baseURL;
      }

**Comment by JiangWeian** [comment]
@dannyrb, Do you have read my problem solving code ?

**Comment by dannyrb** [comment]
👋 Hi @JiangWeian, sorry for the delay. On my list. I'll either give it a read tomorrow (11/14), or make sure it's assigned to an appropriate individual.

**Comment by swederik** [comment]
@JiangWeian I think you are correct and that your fix makes sense.

The way RetrieveMetadataLoaderAsync is currently implemented it will only function correctly against PACS which have identical QIDO and WADO endpoints. In the real world this is not always the case. https://github.com/DICOMcloud/DICOMcloud is one example which uses different endpoints, though @Zaid-Safadi says he plans on changing that.

We should set the correct values so they can be used by dicomweb-client here https://github.com/dcmjs-org/dicomweb-client/blob/master/src/api.js#L53

**Comment by JiangWeian** [comment]
@swederik, then should I pull request?

**Comment by swederik** [comment]
Sure! That would be great!

**Comment by Zaid-Safadi** [comment]
DICOMcloud is updated to share the same base URL.
Here is the updated swagger: http://dicomcloud.azurewebsites.net/swagger/

The old URLs are also still supported, so these two are the same:
http://dicomcloud.azurewebsites.net/qidors/studies
http://dicomcloud.azurewebsites.net/api/studies

**Comment by dannyrb** [comment]
Guidance/Discussion provided in PR https://github.com/OHIF/Viewers/pull/1175

We specify:

- A base URL
- QIDO Prefix URL
- WADO Prefix URL
- QIDO Root (Base + prefix)
- WADO Root (Base + prefix)

Can we safely say the base is _always_ the same? Or should we ditch "prefix" and "base" and simply always use the Root key values? Then add deprecation warnings for the other keys until the next major bump.
