### ISSUE TITLE
E2E Tests for Hotkeys User Preferences menu

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1166]
- What shows if there are no hotkey definitions?
- What shows if there are enough to overflow the container?
- What happens if there are duplicate definitions?
- Restore to default?
- Create additional test cases

**Comment by mirnasilva** [comment]
Hi @dannyrb , I need clarification on the following questions:
1. Can we have a hotkey combination with more than 2 keys or 2 is the limit? Ex: `ctrl+shift+E`
2. Is it mandatory to insert a hotkey for a function or the field can be left blank on User Preferences modal?
3. What are all the "invalid" hotkey combination? I was able to identify:
- ctrl+z
- ctrl+x
- ctrl+c
- ctrl+v
- ctrl+b
- ctrl+n
- ctrl+a
- ctrl+d
- ctrl+f
- ctrl+g
- ctrl+h
- ctrl+j
- ctrl+l
- ctrl+w
- ctrl+r
- ctrl+t
- ctrl+o
- ctrl+p
- Do we have others?

**Comment by dannyrb** [comment]
> 1. Can we have a hotkey combination with more than 2 keys or 2 is the limit? Ex: ctrl+shift+E

We have the _ability_ to support as many key combinations as we would like. Including sequences (Like `ctrl+k` then `ctrl+c`). We're using this library to listen for a respond to keys: https://github.com/ccampbell/mousetrap

That being said, I think the "record keys" logic in the User Preferences panel may be currently limited to two keys.

> 2. Is it mandatory to insert a hotkey for a function or the field can be left blank on User Preferences modal?

We should allow functions/commands to be blank/empty.

> 3. What are all the "invalid" hotkey combination? I was able to identify:

"Built-in" hotkeys (like undo with `ctrl+z`) can't be registered the "normal" way with `mousetrap`. We should determine the best way to handle these cases, as it may not be good practice to simply allow users to override them:

- https://craig.is/killing/mice (`Stopping the default behavior`)
