### ISSUE TITLE
Add User Preferences to Standalone Viewer

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#117]
Hello, 

Please note when shortcut is assign for Length etc., the values disappears when the browser is closed and reopen.   Please note this is only true for shortcuts.

I'm using Standalone viewer.  Since, Standalone viewer does not have User Preferences in its fork I have copied files and folders from the OHIF viewer to Standalone viewer to make it work.

It is quite possible that I have missed something somewhere!

Many thanks,
Rick

**Comment by swederik** [comment]
Hi Rick,

Thanks for the report. I think nobody has spent time implementing this yet, probably because it wasn't clear how to store / retrieve the user preferences. We could store it in localStorage though.
