### ISSUE TITLE
Hotkeys throw exception and crash application

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1173]
## Bug Report

1. Open `https://viewer.ohif.org`
2. Select "Options"
3. Select "Preferences"

See: `TypeError: state.preferences.hotkeyDefinitions is undefined`

This may be tied to `localstorage` and trying to restore a no longer valid schema (given recent updates). If the schema is no longer valid, it should be tossed, and the default schema should be used. One clue here is that I am able to open, save, and restore the hotkeys in a new "private" or "incognito" window.

## Error Screenshot

![image](https://user-images.githubusercontent.com/5797588/68804373-94ecd500-062f-11ea-8e45-24bc53152319.png)

![image](https://user-images.githubusercontent.com/5797588/68804492-d7aead00-062f-11ea-8a94-8d5b62ff591c.png)

This fix has two parts:

1. Fix the underlying issue so this doesn't happen
2. Add an error boundary; likely around the `Modal`, so that future errors don't crash the app

**Comment by dannyrb** [comment]
Related to #1088

**Comment by dannyrb** [comment]
@mirnasilva, to test this, we could force some garbage values into `localstorage`. Although, I'd be happy with a unit test here as well from whoever grabs this for the fix.

**Comment by ladeirarodolfo** [comment]
taking a look on it..
qq: should we persist hotkeys definitions on localStorage?

**Comment by dannyrb** [comment]
Addressed in #1193 's fix PR.
