### ISSUE TITLE
PatientName's value is an object when it should be a string

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1178]
See: https://github.com/OHIF/Viewers/pull/1138#issuecomment-548551301

In some instances, the `patientName` is an object. This causes the application to crash, as we expect it to be a string.

Instead of patching up each place we expect a string, let's look higher up the chain to see how/why we're receiving an object.

**Comment by pieper** [comment]
As @swederik pointed out this issue is probably what causes this to crash: https://idc-sandbox-000.firebaseapp.com/projects/chc-tcia/locations/us-central1/datasets/prostate-diagnosis/dicomStores/prostate-diagnosis/study/1.3.6.1.4.1.14519.5.2.1.4792.2002.920024346241839833195823018831

**Comment by swederik** [comment]
This is still an issue. It's failing right now here: https://github.com/cornerstonejs/react-cornerstone-viewport/blob/f970829b4a74309b3748d315fb6b23467378b7a4/src/helpers/formatPN.js#L11

I agree with @dannyrb though we should sanitize it if it is not a string in the metadata provider.

**Comment by swederik** [comment]
This will be handles in https://github.com/OHIF/Viewers/issues/1460

**Comment by JamesAPetts** [comment]
> As @swederik pointed out this issue is probably what causes this to crash: https://idc-sandbox-000.firebaseapp.com/projects/chc-tcia/locations/us-central1/datasets/prostate-diagnosis/dicomStores/prostate-diagnosis/study/1.3.6.1.4.1.14519.5.2.1.4792.2002.920024346241839833195823018831

Tested this locally on the IDC sandbox, #1460 fixes this.
