### ISSUE TITLE
Default settings missing for Standalone Viewer

### ISSUE THREAD

**Issue by protectedfor** [OHIF/Viewers#118]
Hello, I need to run builded OHIF viewer on my server. I've run build command as described here:
https://github.com/OHIF/Viewers/wiki/Running-and-building-the-Standalone-Viewer
But when I've uploaded files on my server I'm getting this error: 
`Oops, looks like there's no route on the client or the server for url: "http://my-site.com/viewer/."`
In console I see error - 404 on address: `http://my-site.com/sockjs/info?cb=ded2pd_otk`

But locally when I run using `METEOR_PACKAGE_DIRS="../../Packages" meteor` command everything works perfectly!

I think something is missing in wiki. What am I doing wrong?

**Comment by CarnivorousRex** [comment]
Still need to be using routes for the Standalone viewer. 
If you haven't modified routes.js, have you tried:
http://my-site.com/viewer/testDICOMs
?

**Comment by protectedfor** [comment]
Great! It works! but why I'm getting errors in my browser console? 

https://s.mail.ru/Fr42/M53WrWwr8

**Comment by protectedfor** [comment]
Also how to correctly provide DICOM files for viewer? In the example `sampleDICOM.json` there using `dicomweb://` protocol. I've tried to use http but it doesn't work. What can you advice?

**Comment by swederik** [comment]
It looks like we don't have any default settings being used. You will need to add a config JSON file when building the standalone viewer. The argument is like --settings ../../config/orthancDICOMWeb.json

So the whole thing would be:

METEOR_PACKAGE_DIRS="../../Packages" meteor-build-client ../myOutputFolder -u localhost:3000/subdirectory/ --settings ../../config/orthancDICOMWeb.json

**Comment by swederik** [comment]
I added some default settings to index.html here:

https://github.com/OHIF/Viewers/commit/fc29b48b591c0259453ba97da43f0394db7feaa7#diff-b11222605e5ee5357bd25265ff2307d4R23
