### ISSUE TITLE
E2E Tests fail when pointed at an external URL

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1190]
https://circleci.com/gh/OHIF/Viewers/6829#artifacts/containers/0

**Steps to reproduce:**

1. Change `baseUrl` to `https://ohif-staging.netlify.com/`
2. Run E2E Tests
3. Note intermittent failure of `@getStudies`

**Comment by dannyrb** [comment]
While we do run E2E Tests in PR checks, it might be a nice gut check to enforce that they pass before deploying to production. We have the ability to point at a deployed instance and re-run our tests before "promoting our build" to the production environment.

What's tricky here, is that tests in `PR_CHECKS` and `DEPLOY` may need to look at different data.

It may not be worth supporting this use case if it doesn't add much confidence, but cataloging here for the time being.

**Comment by sedghi** [comment]
Not reproducible in master
