### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by kostaspapas** [OHIF/Viewers#1197]
I have written the following code:

```
import React, { Component } from 'react';
import ConnectedViewer from "./viewer/src/connectedComponents/ConnectedViewer";

class DicomViewer extends Component {
  state = {
    studies: [],
    error: null,
    studyInstanceUids: [
      "2.25.63009447009646876712620988718732709379"
    ]
  };

  render() {
    if (this.state.error) {
      return <div>Error: {JSON.stringify(this.state.error)}</div>;
    } else if (!this.state.studies) {
      return <div>Loading...</div>;
    }

    return (
      <ConnectedViewer
        studies={this.state.studies}
        studyInstanceUids={this.studyInstanceUids}
      />
    );

  }
}

export default DicomViewer;

```
I have added the follow components with yarn:
yarn add @ohif/core --exact
yarn add @ohif/ui --exact
yarn add @ohif/extension-cornerstone --exact

My machine:
- Windows 10 pro
- Processor: Intel Core i5
- Memory: 8GB
I have also a vagrant vm which use 2GB memory

When i 'yarn start', after a few minutes a get:

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1: node_module_register
2: v8::internal::FatalProcessOutOfMemory
3: v8::internal::FatalProcessOutOfMemory
4: v8::internal::Factory::NewUninitializedFixedArray
5: v8::internal::WasmDebugInfo::SetupForTesting
6: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
7: 0000021B509843C1

I did:

set NODE_OPTIONS=–max-old-space-size=8192
which I read it in 
[https://github.com/OHIF/Viewers/issues/79](https://github.com/OHIF/Viewers/issues/79)

But I still have the same problem. Does anyone have an idea what i need to do?

thank you,
Kostas

**Comment by dannyrb** [comment]
This could be an issue with your WebPack config? If you're trying to lint or transpile `@ohif/extension-cornerstone`, we've noticed some ongoing issues when/if `cornerstone-wado-image-loader`'s `codecs` get caught in the mix.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
