### ISSUE TITLE
blank black page on first load after clearing the browser cache

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1198]
OHIF viewer takes a while to load when it opened after clearing the browser cache and all that is displayed while its loading is a blank black page. Would it be possible to add some kind of loading progress indicator as this would make things a bit more user-friendly?

**Comment by dannyrb** [comment]
The goal here is to get to the point where a loading progress indicator isn't needed. For PWA builds, this should be possible by leveraging code splitting. We have several efforts under way to improve our time to first paint and time to first interaction metrics.

We started with our recent changes to meet the Google Lighthouse PWA requirements. We're now addressing code-splitting of `cornerstone-wado-image-loader`'s decoders/codecs. Next will be code-splitting extensions and larger dependencies in `@ohif/viewer`.
