### ISSUE TITLE
Modify filters; make filter independent of location in String

### ISSUE THREAD

**Issue by mtjvankuik** [OHIF/Viewers#12]
Whenever entering a filter that matches after several non-match characters, the worklist is emptied anyway. See example image below. If I enter thorax, I want to return all studies with StudyDescription CR THORAX. At the moment all the correct studies are returned only when entering cr, not when entering thorax.

PS: the filters are case-insensitive.

<img width="1280" alt="schermafbeelding 2016-03-30 om 16 12 54" src="https://cloud.githubusercontent.com/assets/10122364/14145088/bb9250be-f692-11e5-87f3-295fb85af267.png">

**Comment by chafey** [comment]
I don't recall if CFIND or QIDO-RS allows searching on substrings like that - we may be limited by what the standard allows.  If it does, Orthanc may not implement it.  If orthanc supports this kind of query, then it should be a simple change to our UI.  I suggest researching the DICOM Standard to see if it supports this kind of Query and if so, verify that Orthanc does the right thing. Sorry I can't help out more right now -very busy

**Comment by swederik** [comment]
Hi Martin,

For searches like 'THORAX' above I think you would have to use '*THORAX' according to the standard.

As for case sensitivity, it seems that the standard states case insensitivity is only allowed for Patient Name fields, and that even for Patient Name, whether or not to use case is left up to the PACS (see http://dicom.nema.org/dicom/2013/output/chtml/part04/sect_C.2.html).

Sorry we can't help in this situation. I suppose it is possible to retrieve / cache all studies and search through those with e.g. MongoDB, but for large archives this isn't feasible. I'll close this issue for now.

Cheers,

Erik
