### ISSUE TITLE
Update `react-bootstrap-modal` usage to new UIModalService

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1204]
See: https://github.com/OHIF/Viewers/pull/1202#discussion_r347582968

Update `DicomFileUploaderModal` and `DicomStorePickerModal` to use new UIModalService so we can remove our `react-bootstrap-modal` dependency.

**Comment by swederik** [comment]
Closed a while ago in https://github.com/OHIF/Viewers/pull/1904.
