### ISSUE TITLE
Extensions should be able to update viewport stack, sliceIndex, cineIsPlaying, etc.

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1205]
RE: https://github.com/OHIF/Viewers/pull/1202/files#r347591780

While discussing recent `UIDialogService` PR, in the context of the CINE Player as implemented by extension authors.

> This is great. Here is something we need to think about:
> 
> How can we make extensions powerful enough that this logic can live in them? Having "Built in" viewer behavior lets us offload some concerns to `viewer`, but it also makes us less flexible.
> 
> Ideally, we end up at something like:
> 
> - ToolbarButton is of type `Toggle`
>   - When clicked, is `enabled`, and extension's logic is called w/ `enabled: true`
>   - When clicked again, enabled is `false`, and extension's logic is called
> - The toolbar can use the now exposed `Dialog` service to hide/show dialog
> - **As the user interacts, the extension is able to update the ViewportComponent based on that interaction**
> 
> I think that last part is the only thing missing, and what we need a good solution for (outside the scope of this PR, but an upcoming issue for sure). If we wanted to update... cineIsPlaying, stack index, slice index, etc. What would that look like for an extension?

**Comment by dannyrb** [comment]
👢 💨 🤖

**Comment by dannyrb** [comment]
We're getting closer to this. We could likely expose `viewportSpecificData`, or some subset of it, using the new "services" pattern to make this possible.

**Comment by sedghi** [comment]
We have successfully addressed the majority of issues related to cornerstoneViewportService and other services.
