### ISSUE TITLE
Download Screen Shot modal should be self-contained with @ohif/extension-cornerstone

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1206]
RE: https://github.com/OHIF/Viewers/pull/1202/files#r347596387

> I think we can move this to the `@ohif/extension-cornerstone` and ditch the built in here (outside scope of this PR). This one's a bit closer/easier.
> 
> We use `state.viewports` to grab `viewportSpecificData` and `activeViewportIndex`
> We use those to grab `dom` off the `viewportSpecificData`'s `activeViewport`
> 
> DOM is just a reference to the active viewport's `enabledElement`
> `dom` is actually set/added by the `@ohif/extension-cornerstone`
> 
> The only bit of data we need exposed to refactor the `ConnectedViewportDownloadForm` _should_ be the `activeViewportIndex` which we already have exposed for extensions (albeit, that method could be cleaned up).

We can grab `activeViewportIndex` in a command. The button that launches the Screen Shot modal would need to:

- Call a command that uses state from `viewports`
- Use the new `UIModalService` to show the modal
- Update `@ohif/extension-cornerstone` to track `enabledElements` internally?
- Shift `connectedViewportDownloadForm` implementations to it's own project
- Remove lingering previous implementation

There's likely a step missing there, but that's the gist. The modal doesn't update application state, so it can be fairly self-contained once it has the data it needs.

**Comment by igoroctaviano** [comment]
@dannyrb  https://github.com/OHIF/Viewers/pull/1224
