### ISSUE TITLE
Add tooling to support linting of styles

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1208]
Addresses: https://github.com/OHIF/Viewers/issues/978#issuecomment-554682157

We've been having conversation internally about landing on consistent styling practices. Regardless of the path we choose, I'm confidant a linter will be part of the equation. It should operate similar to our current ESLint and Prettier usage.

**Comment by dannyrb** [comment]
👠 💨 🤖 
RE: https://github.com/OHIF/Viewers/commit/29bac8df7a6ebd9f7f3114fbaa9e8666bd1995ec

**Comment by shivasuri** [comment]
Are people still using [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)? I am using ESLint and there are errors marked throughout the repo.

**Comment by sedghi** [comment]
Done in master with eslint
