### ISSUE TITLE
Json opening error with build

### ISSUE THREAD

**Issue by FredGillain** [OHIF/Viewers#1210]
Hi,

I'm using OHIF as a Standalone, with the jSon method to open studies (_http://my-server:5000/viewer?url=my.study.json_) and I recently upgraded to the latest version of OHIF Viewer.

Here's my problem : when I use the viewer in developper mode, everything works as it should, with the series opening from the jSon and all, but when I build the static version (using the _yarn build_ comand), I get 404 errors instead of opening the jSon's data.

I've tried to follow the online doc, step by step, but I can't figure what I'm doing wrong.

I'm currently having to use the dev environment in production. It works fine but it rather takes time to boot (around 20 seconds to display the viewer, once the jSon is sent to my remote server).

Any help to find how to have the build act the same as the dev environment would be most welcome ! (or, if nothing better, a way to make the dev building process faster. I could live with the viewer taking 5-10 seconds to boot).

PS : just to be precise, I did not upgrade from version 1. I already used a previous release of version 2 up until last week and the jSon method worked perfectly with the build.

PPS : on a side note, the 2D MPR function doesn't seem to fire from my jSon generated series. Is there some special data that needs to be passed for the viewer to recognise if the MPR function is needed ?

Thanks in advance to anyone who can help me with this. I've been banging my head on this for days now.

Fred

**Comment by dannyrb** [comment]
👋 Hi @FredGillain,

What version were you using previously? What version did you upgrade to? Do you have an example file we can test?

Here is the `master`/latest using a known good JSON file:

- https://viewer-dev.ohif.org/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/PTCTStudy.json

**Comment by FredGillain** [comment]
Hi Danny,

Thank you for your help.

The previous version of OHIF viewer I used was 0.0.21 (with the "_build_" folder being generated at the root of the app) and the one I'm using now is the 2.8.4.

Regarding the jSon file, the one you gave as an example is the one I use for my tests, as I'm always sure it's properly formatted. If I use it in dev mode, it works fine. If I try to use it with the viewer built in the "_dist_" folder, it doesn't work.

I don't think the problem comes from the jSon.

**Comment by dannyrb** [comment]
I believe that `0.50.0` marks the beginning of our monorepo changes. You've made quite the jump ^_^

The new WebPack process `clears` the `platform/viewer/dist` folder on each run. I also don't think it uses the files in that folder when using the WebpackDevServer. I'm pretty sure all served assets reside in memory, or some special/other location.

If you include the file in the `PUBLIC_DIR`, it should be accessible:

`const PUBLIC_DIR = path.join(__dirname, '../public');`

**Comment by FredGillain** [comment]
Hi,

Thanks again for your advice but, unfortunately, it still didn't work.

This is becoming a rather academic issue as I managed to have the dev version working almost as fast as the built version buy reducing the size of the app.js file (as it happens, it was loading 40+MB file on each launch that slowed the system that much).

BUT I hate not understanding and I might end up needing a built version some day, so here is my complete process. Maybe you can tell me what I'm doing wrong...

I'm using a Windows 10 PC, Node 12.13.0 and Yarn 1.19.1.

1 - Download the master viewer from GitHub and unzip the folder on the C drive.
2 - Restore the dependencies (_yarn install_).
3 - Launch the developpement version (_yarn run dev_).
4 - Try opening a known good test Json file : http://localhost:3000/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/PTCTStudy.json

Up to this point, everything works fine. But then...

5 - Create the build (_yarn run build_). The build is created ok.
6 - Launch the built version, according to the test procedure described in the "_Build for production_" part of the docs : get the "_dist_" directory, then _yarn global add http-server_, and finally launch the server with _http-server_.

From that point on, I can't open any Json, I've tried changing the port (3000, 5000, 8080, 8042...), changing the url (adding "_dist_" in the mix, for example), hosting the Json in the "_public_" or the "_dist_" folders, etc... Nothing seems to be working. The only results I get are either 404 errors or a message saying the content I'm trying to open is corrupted.

I'm not doing anything more than what I've just described at this point. No customisation and alteration. The viewer master is used "_straight from the box_".

Maybe you'll be able to see what I'm doing wrong. Or maybe there's another program I didn't think of that needs to be upgraded ?

Any help is welcome.

Have a nice day,
F.

**Comment by swederik** [comment]
@dannyrb - could this be a terser issue again? Or possibly a flag that is
set in the config that disables the route? Do we have e2e tests for this?

**Comment by dannyrb** [comment]
@FredGillain, the `http-server` trick will load the application's entrypoint (`index.html`) if you visit `http://localhost:8080` directly. Any navigation within the app is handled by `react-route`.

If you try to visit a route other than the root, the simple `http-server` does not have the rewrite/redirect rules required to serve up the correct content. For example:

```
// Returns `index.html`
http://localhost:8080

// unable to find file at `<hosted-directory>/viewer/index.html`
http://localhost:8080/viewer
```

You can see where, in our own [Netlify configuration](https://github.com/OHIF/Viewers/blob/master/.netlify/deploy-workflow/_redirects#L5) (what we use to host our dev, staging, and production instances), that we redirect all "unmatched" resource requests to the root directory's `index.html`.

This is what allows our "Single Page Application" to handle route requests for non-root requests. React router will parse the URL, set route container props, and then it's business as usual.

The WebPack dev server accounts for this. Our simple `http-server` trick to test our build output does not.
