### ISSUE TITLE
Embedding OHIF Viewer as .html showing black screen 

### ISSUE THREAD

**Issue by vanye007** [OHIF/Viewers#1214]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

I followed the embedding. But I am getting a black screen

**Comment by dannyrb** [comment]
Can you provide a small reproduction in something like CodeSandox?

**Comment by vanye007** [comment]
https://codesandbox.io/s/quirky-framework-m61gz?fontsize=14&hidenavigation=1&theme=dark

**Comment by dannyrb** [comment]
@vanye007, your sandbox does not have any files in the `src/` folder

**Comment by dannyrb** [comment]
This has gone stale, so I'm going to close for now. If someone is able to provide a reproduction, please feel free to post here, or create a new issue.
