### ISSUE TITLE
protocol http or file possible ? 

### ISSUE THREAD

**Issue by Boukenty** [OHIF/Viewers#122]
Hi,

I'm working on standalone viewer build with meteor-build-client. I trying to load local dicom images routed in my "api/files.json" with http/file protocol.

I have this message :  "Access-Control-Allow-Origin" 

I've read here (https://enable-cors.org/server_meteor.html)  that i could configure Meteor.
But i can't found where add this in this project...

Thank you for help.

**Comment by swederik** [comment]
You don't need to enable CORS on the Meteor server, you need to enable it wherever the images are being served from.

**Comment by Boukenty** [comment]
You are right ! It works now.

In my virtualhost => Header set Access-Control-Allow-Origin "*"

Thank you.

**Comment by swederik** [comment]
Great!
