### ISSUE TITLE
lerna ERR! yarn run dev:viewer exited 1 in '@ohif/viewer' error Command failed with exit code 1.

### ISSUE THREAD

**Issue by vinodmehta367** [OHIF/Viewers#1220]
i followed steps in this guide:https://docs.ohif.org/essentials/getting-started.html
which led me to 
error: lerna ERR! yarn run dev:viewer exited 1 in '@ohif/viewer' error Command failed with exit code 1.

-------------------------the detailed error is pasted below----------------------------------------
C:\Users\vsm\Desktop\ME\yolo\Viewers>yarn run dev
yarn run v1.19.1
$ lerna run dev:viewer --stream
lerna notice cli v3.18.3
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run dev:viewer"
@ohif/viewer: $ yarn run dev
@ohif/viewer: $ cross-env NODE_ENV=development webpack-dev-server --config .webpack/webpack.pwa.js --watch
@ohif/viewer: i ｢wds｣: Project is running at http://localhost:3000/
@ohif/viewer: i ｢wds｣: webpack output is served from /
@ohif/viewer: i ｢wds｣: Content not from webpack is served from C:\Users\deeptek14\Desktop\ME\yolo\Viewers\platform\viewer
@ohif/viewer: i ｢wds｣: 404s will fallback to /index.html
@ohif/viewer: events.js:187
@ohif/viewer:       throw er; // Unhandled 'error' event
@ohif/viewer:       ^
@ohif/viewer: Error: spawn cmd ENOENT
@ohif/viewer:     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
@ohif/viewer:     at onErrorNT (internal/child_process.js:456:16)
@ohif/viewer:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
@ohif/viewer: Emitted 'error' event on ChildProcess instance at:
@ohif/viewer:     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
@ohif/viewer:     at onErrorNT (internal/child_process.js:456:16)
@ohif/viewer:     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
@ohif/viewer:   errno: 'ENOENT',
@ohif/viewer:   code: 'ENOENT',
@ohif/viewer:   syscall: 'spawn cmd',
@ohif/viewer:   path: 'cmd',
@ohif/viewer:   spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:3000/' ]
@ohif/viewer: }
@ohif/viewer: error Command failed with exit code 1.
@ohif/viewer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@ohif/viewer: error Command failed with exit code 1.
@ohif/viewer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run dev:viewer exited 1 in '@ohif/viewer'
error Command failed with exit code 1.

![Screenshot (3)](https://user-images.githubusercontent.com/51881821/69526820-0c582800-0f91-11ea-8499-f8157a69e9a5.png)

**Comment by dannyrb** [comment]
`yarn install --force`

What version of yarn, npm, node? What version/branch/commit hash of `OHIF/Viewers`? What OS? Are you able to provide a more verbose dump of the error? How much RAM does your machine have? Are you running these commands from an admin account?

**Comment by vinodmehta367** [comment]
>node --version
v12.13.1
>npm --version
6.12.1
>yarn --version
1.19.1

---------------------------------------
>git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   package.json
        modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")
-------------------------------------------
Hardware Specs:
os : WINDOWS 10 Home Single-64 bit
Processor: Intel core i5 8265U CPU
RAM: 8GB
acccount:admin

**Comment by dannyrb** [comment]
Were you able to run `yarn install --force`? Any changes?

Do you see a better, more verbose error, if you:

1. Navigate to `plaftorm/viewer`
2. Run `yarn run dev:viewer`

It looks like this could be related to `cross-env` not being able to spawn `cmd` because it's not in your PATH:

https://github.com/facebook/create-react-app/issues/7094#issuecomment-494611206

**Comment by vinodmehta367** [comment]
Yup,...it was cross env problem indeed.
i included C:\windows\System32\ in environment variable path,restarted my computer and now the application works fine.
Thanks a lot @dannyrb  for your continuous guidance and support.

**Comment by franklinhoracio** [comment]
Hello im getting this problem but in an ubuntu 18.04.03

**Comment by toj11001** [comment]
Hello,

I'm also running on Ubuntu (18.04.05)
`node --version v12.18.3`
`npm --version
6.14.6`
`yarn --version
1.22.5`

When `yarn run dev` from `/Viewers/`: 
```
Viewers# yarn run dev
yarn run v1.22.5
$ lerna run dev:viewer --stream
lerna notice cli v3.18.3
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run dev:viewer"
lerna ERR! Error: Command failed: yarn run dev:viewer
lerna ERR! 
lerna ERR! 
lerna ERR!     at makeError (/root/code/Viewers/node_modules/execa/index.js:174:9)
lerna ERR!     at /root/code/Viewers/node_modules/execa/index.js:278:16
lerna ERR! lerna Command failed: yarn run dev:viewer
lerna ERR! lerna 
lerna ERR! lerna 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried to install the config with `yarn install` from `/Viewers/`:

```
warning "workspace-aggregator-66306174-4862-40c8-b019-7158010b7263 > @ohif/extension-cornerstone > react-cornerstone-viewport@4.0.2" has unmet peer dependency "hammerjs@^2.0.8".
warning "workspace-aggregator-66306174-4862-40c8-b019-7158010b7263 > @ohif/extension-vtk > react-vtkjs-viewport@0.10.4" has unmet peer dependency "vtk.js@^11.14.0".
warning "workspace-aggregator-66306174-4862-40c8-b019-7158010b7263 > @ohif/ui > docz-plugin-css > docz-core > react-docgen-typescript-loader@3.7.1" has unmet peer dependency "typescript@*".
[5/5] Building fresh packages...
[6/14] ⡀ styled-components
[2/14] ⡀ puppeteer
[3/14] ⡀ core-js
[4/14] ⡀ husky
events.js:292-sass
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at tryReadStart (net.js:573:20)
    at Socket._read (net.js:584:5)
    at Socket.Readable.read (_stream_readable.js:467:10)
    at Socket.read (net.js:624:39)
    at new Socket (net.js:376:12)
    at Object.Socket (net.js:267:41)
    at createSocket (internal/child_process.js:314:14)
    at ChildProcess.spawn (internal/child_process.js:437:23)
    at Object.spawn (child_process.js:548:9)
    at /usr/share/yarn/lib/cli.js:25829:24
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOTCONN',
  code: 'ENOTCONN',
  syscall: 'read'
}
```


Then I tried to install the config with `yarn install` from `/Viewers/platform/viewer`:
```
[4/14] ⠄ husky
events.js:292-sass
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at tryReadStart (net.js:573:20)
    at Socket._read (net.js:584:5)
    at Socket.Readable.read (_stream_readable.js:467:10)
    at Socket.read (net.js:624:39)
    at new Socket (net.js:376:12)
    at Object.Socket (net.js:267:41)
    at createSocket (internal/child_process.js:314:14)
    at ChildProcess.spawn (internal/child_process.js:437:23)
    at Object.spawn (child_process.js:548:9)
    at /usr/share/yarn/lib/cli.js:25829:24
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOTCONN',
  code: 'ENOTCONN',
  syscall: 'read'
}
```

Running `yarn run build` from `/Viewers/platform/viewer` doesn't know the command:

running `yarn run build` from `/Viewers` from throws error code 134:
```
Viewers# yarn run build
yarn run v1.22.5
$ lerna run build:viewer --stream
lerna notice cli v3.18.3
lerna info versioning independent
Aborted
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```

Any Idea what I could do... I am a bit lost here :(

**Comment by toj11001** [comment]
@franklinhoracio do you still have the issue? 
I noticed that the issue with the build (and also starting the ohif/viewer docker container) was an issue because of my VM provider (the virtualisation technique they use). Therefore for me it help to change the hosting/ vm provider.
Locally on my pc it is working now for me.

**Comment by sulaimanvesal** [comment]
I am getting the same error. I added the system32 to the path, but it didn't work.

**Comment by JS-novotrax** [comment]
Windows 10 Home 22H2
node --version v18.13.0
npm --version 8.19.3
yarn --version 1.22.19
```
yarn run v1.22.19
$ lerna run build:viewer --stream
lerna notice cli v3.18.3
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run build:viewer"
@ohif/viewer: $ cross-env NODE_ENV=production node --max_old_space_size=4096 ./../../node_modules/webpack/bin/webpack.js --config .webpack/webpack.pwa.js --progress
@ohif/viewer: <s> [webpack.Progress] 0% compiling
@ohif/viewer: <s> [webpack.Progress] 10% building 0/0 modules 0 active 
@ohif/viewer: Error: error:0308010C:digital envelope routines::unsupported
@ohif/viewer:     at new Hash (node:internal/crypto/hash:71:19)
@ohif/viewer:     at Object.createHash (node:crypto:133:10)
@ohif/viewer:     at module.exports (C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\util\createHash.js:135:53)    
@ohif/viewer:     at NormalModule._initBuildHash (C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\NormalModule.js:417:16)
@ohif/viewer:     at handleParseError (C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\NormalModule.js:471:10)     
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\NormalModule.js:503:5
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\NormalModule.js:358:12
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
@ohif/viewer:     at iterateNormalLoaders (C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
@ohif/viewer:     at iterateNormalLoaders (C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:236:3
@ohif/viewer:     at runSyncOrAsync (C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:130:11) 
@ohif/viewer:     at iterateNormalLoaders (C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
@ohif/viewer:     at Array.<anonymous> (C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
@ohif/viewer:     at Storage.finished (C:\Users\<username>\Downloads\Viewers-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9        
@ohif/viewer: <s> [webpack.Progress] 10% building 0/1 modules 1 active C:\Users\<username>\Downloads\Viewers-master\node_modules\babel-loader\lib\index.js??ref--4!C:\Users\<username>\Downloads\Viewers-master\platform\viewer\src\index.js
@ohif/viewer: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
@ohif/viewer: node:internal/crypto/hash:71
@ohif/viewer:   this[kHandle] = new _Hash(algorithm, xofLen);
@ohif/viewer:                   ^
@ohif/viewer: Error: error:0308010C:digital envelope routines::unsupported
@ohif/viewer:     at new Hash (node:internal/crypto/hash:71:19)
@ohif/viewer:     at Object.createHash (node:crypto:133:10)
@ohif/viewer:     at module.exports (C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\util\createHash.js:135:53)    
@ohif/viewer:     at NormalModule._initBuildHash (C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\NormalModule.js:417:16)
@ohif/viewer:     at handleParseError (C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\NormalModule.js:471:10)     
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\NormalModule.js:503:5
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\webpack\lib\NormalModule.js:358:12
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
@ohif/viewer:     at iterateNormalLoaders (C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
@ohif/viewer:     at iterateNormalLoaders (C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:236:3
@ohif/viewer:     at context.callback (C:\Users\<username>\Downloads\Viewers-master\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
@ohif/viewer:     at C:\Users\<username>\Downloads\Viewers-master\node_modules\babel-loader\lib\index.js:55:71
@ohif/viewer:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
@ohif/viewer:   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
@ohif/viewer:   library: 'digital envelope routines',
@ohif/viewer:   reason: 'unsupported',
@ohif/viewer:   code: 'ERR_OSSL_EVP_UNSUPPORTED'
@ohif/viewer: }
@ohif/viewer: Node.js v18.13.0
@ohif/viewer: error Command failed with exit code 1.
@ohif/viewer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:viewer exited 1 in '@ohif/viewer'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
didn't work after adding `C:\windows\System32\` to path

**Comment by HBO30** [comment]
did you fixed ?

**Comment by pineklll** [comment]
> Probably adding this will resolve the issue in Ubuntu
> 
> `export NODE_OPTIONS=--openssl-legacy-provider`

this can help in windows by changing `export` to `set`

**Comment by spideep** [comment]
> Were you able to run `yarn install --force`? Any changes?
> 
> Do you see a better, more verbose error, if you:
> 
> 1. Navigate to `plaftorm/viewer`
> 2. Run `yarn run dev:viewer`
> 
> It looks like this could be related to `cross-env` not being able to spawn `cmd` because it's not in your PATH:
> 
> [facebook/create-react-app#7094 (comment)](https://github.com/facebook/create-react-app/issues/7094#issuecomment-494611206)

I've resolved this using **set** instead of cross-env
