### ISSUE TITLE
Configuration so viewer tools can nix handles

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1223]
Blocked by: https://github.com/OHIF/Viewers/issues/1222

## Acceptance Criteria

- Add a key to the `cornerstone` extension configuration that allows you to toggle on/off handle rendering
- When "adding" tools to `cornerstone` in the extension's `preInit` hook, if it's an annotation tool, set the configuration appropriately

Notes: This _could_ be pushed down to cornerstone-tools, but would require a bit more work. If you feel confident in an approach, that would be the preferable long-term route. If not, we can hold-off until we redo how cornerstone renders annotations.

**Comment by igoroctaviano** [comment]
Work in progress: https://github.com/cornerstonejs/cornerstoneTools/pull/1140
