### ISSUE TITLE
Integration of react project with spring boot

### ISSUE THREAD

**Issue by vinodmehta367** [OHIF/Viewers#1226]
how to integrate an existing reactjs application to any spring boot project? 

Description:
I'm working on a spring boot application and would like to integrate it with an existing react application .After a lot of research i found your project similar to mine .So if you could please guide me through the steps to integrate  any react application to an existing spring boot application that would be a great help. Or better how can i configure your project with my database without using any image archive.

**Comment by dannyrb** [comment]
@vinodmehta367, these are pretty broad questions. If you need a lot of assistance, you may want to reach out to consulting partner. I'll try to provide some general guidance.

> I'm working on a spring boot application and would like to integrate it with an existing react application

You can embed the OHIF Viewer the same way you would embed either an entire separate website into your own. It's static content, so one of the simplest ways is with an iFrame, and then use the URL of the iFrame to drive the routing of the embedded app. Another way is to use the exposed Application React component. You can grab this from our NPM package `@ohif/viewer` or from source. There is some guidance on embedding here:

https://docs.ohif.org/deployment/recipes/embedded-viewer.html

If the docs are out of date or unclear, please feel free to submit corrections or create a new issue.

> Or better how can i configure your project with my database without using any image archive.

The simplest way to do this is with JSON URLs. It is not documented well: https://github.com/OHIF/Viewers/issues/891

I would like the list and viewer routes to be much more flexible to support any custom data sources more easily, but we haven't had the time/funding to flesh out the details there. If you have the ability to contribute in some way, I can try to scope the PRs necessary to add this functionality.
