### ISSUE TITLE
Add modality filter to the Study List interface

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1227]
## Request

**What feature or change would you like to see made?**

Currently, it is possible to filter StudyList by all columns shown in the interface, except modality. I think it would be quite helpful to include modality into the filters.

![image](https://user-images.githubusercontent.com/313942/69659432-29056600-104c-11ea-8896-31e7fa7f1107.png)

**Why should we prioritize this feature?**

It might be helpful to show studies that have segmentations or structured reports. Large datasets, such as those on TCIA, do not always have those derived modalities for all of the imaging studies, and searching for matching studies manually is cumbersome.

It would also make the interface more consistent, since filters are available for other columns.

**Comment by pieper** [comment]
I think the idea was that the search bar spans the two fields and searches both.  So if you type in MR or SEG in the field it works for either study description or modality.

**Comment by swederik** [comment]
Can you try resizing your browser window (or zooming out with Ctrl + - )? The view you are looking at is the mid-size layout. There is a modality filter section on large screens. We may need to adjust our screen size breakpoints though because I also rarely see it on my laptop.

**Comment by pieper** [comment]
There are definitely some issues.  If I expand the window I do see all the search bars, but the Modality one doesn't work (never finds anything for QIN-HEADNECK and SEG isn't listed as a modality on any of the studies even though 0047 and others have them).

**Comment by swederik** [comment]
It seems to work on viewer.ohif.org. Is this only in the IDC sandbox, or do you also see it on dcm4chee. Maybe it's related to the Google Cloud adapter?

**Comment by pieper** [comment]
Yes, probably specific to Google.  We can keep it on the todo list but I
don't think it's urgent, Andrey just discovered it while preparing the RSNA
poster.

**Comment by fedorov** [comment]
Thank you for investigating! Absolutely no urgency, just wanted to document this.

Kind of related to this filtering topic, filtering does work as I would expect, anyway. E.g., if I type "47" for patient ID, I would expect it to find all IDs that include 47, but search seems to look for the prefix of the ID, not for pattern match.

**Comment by dannyrb** [comment]
A good number of compounding issues here. We do collapse search fields so we can support smaller displays. When we do this, fields begin to search across multiple columns. At mobile resolutions, you have a single field.

Outside of the UI, which could definitely be improved, we come up against inconsistencies and limitations when querying a PACS. There are small differences between DCM4CHEE, Orthanc, and Google; each also support functionality that's not defined by the standard in different ways.

If we assume only what is possible with the DICOMWeb spec, the user experience falls a bit short.

---

We've made some progress toward making a number of these things configurable. It would not be difficult to expose:

- The filter template(s), so you can define custom fields, and the breakpoints they show at
- A mapping layer where you receive filter values and can use it to build your request
- A mapping layer where you can format the result to match what your row template expects
- The row template(s)

Long-term, I think an approach like this allows us to provide an "okay" base implementation, but gives consumers the ability to leverage advanced features for their PACS / custom data source.

**Comment by fedorov** [comment]
> Outside of the UI, which could definitely be improved, we come up against inconsistencies and limitations when querying a PACS

@dannyrb are you saying that every time user types a search filter, filtering is not done on the client but results in a DICOM query?

**Comment by dannyrb** [comment]
> filtering is not done on the client but results in a DICOM query

@fedorov, that's currently the case, yes. I believe we debounce input, and use cancellation tokens if a second request goes out while the prior request is in-flight.

Client-side filtering/sorting would make things more consistent, but could result in a painfully slow initial load for larger datasets.

**Comment by fedorov** [comment]
Thank you for the clarification. This discussion helped a lot. I am removing the "IDC: candidate" tag, since searching through collections using OHIF study list interface will probably not be needed for us - search would be done in the IDC portal, and the viewer will be initialized with a small subset of studies/series.
