### ISSUE TITLE
Hide measurements text near the roi

### ISSUE THREAD

**Issue by rohit-takhar** [OHIF/Viewers#1228]
![issue_ohif](https://user-images.githubusercontent.com/10480197/69664456-6ef31600-10ae-11ea-8df9-48e189dc3920.PNG)
Hi,
Is there a way to remove the text **Mean Std ** around the roi?
I tried to refer to the docs but couldn't find a way? 

Thanks

**Comment by dannyrb** [comment]
This looks like a `freehandRoi`
The `freehandRoi` is implemented in `cornerstone-tools`, and some of it's settings are exposed via the `@ohif/extension-cornerstone` that adds this functionality.

If we take a look at the source for `freehandRoi`

- [Where the textbox is rendered](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/FreehandRoiTool.js#L463)
- [Default props for the tool](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/FreehandRoiTool.js#L52-L57)

It doesn't look like there's any way to conditionally render the textbox for this tool.

You could: 

- Propose changes on `cornerstone-tools` (new PR)
- Create a custom tool that extends, or is based on, the `freehandRoi` tool
    - Use `@ohif/extension-cornerstone`'s configuration to use your custom tool in place of the default one
