### ISSUE TITLE
Meteor 1.6

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#123]
Hello,

I see the OHIF viewer has now been upgraded to meteor 1.6.  However, Standalone viewer is still on 1.5.2.2.  Did we miss Standalone viewer from the upgrade? :)

Many thanks!
Rick

**Comment by swederik** [comment]
Yeah I think I forgot to update that one. I believe 1.6 is mostly node.js updates anyway so it's likely it makes no difference for the standalone viewer. Either way I will try to get that updated soon.

I'd also be happy to accept a PR!

**Comment by swederik** [comment]
I just updated it to 1.7 in this commit: https://github.com/OHIF/Viewers/commit/de7135f3b878954e99b7e8a278b8d2978b2e0161
