### ISSUE TITLE
Parameter 'event' must be added in function onChange in LanguageSwitcher.js

### ISSUE THREAD

**Issue by kostaspapas** [OHIF/Viewers#1230]
Hello,
in https://github.com/OHIF/Viewers/blob/master/platform/ui/src/components/languageSwitcher/LanguageSwitcher.js

it reads:

```
  const onChange = () => {
    const { value } = event.target;
    const language = getCurrentLanguage(value);
    setCurrentLanguage(language);

    i18n.init({
      fallbackLng: language,
      lng: language,
    });
  };
```

I think,  parameter 'event' must be added:

```
  const onChange = (event) => {
    const { value } = event.target;
    const language = getCurrentLanguage(value);
    setCurrentLanguage(language);

    i18n.init({
      fallbackLng: language,
      lng: language,
    });
  };
```

otherwise, you get:
Line 25:23:  Unexpected use of 'event'

**Comment by dannyrb** [comment]
@kostaspapas, are you using the UI component outside of the OHIF Viewer? Is this error reproducible at `https://viewer.ohif.org`? Are you able to submit a PR for the fix?

**Comment by kostaspapas** [comment]
I used to use '@ohif/ui' package but I had the problem as 
https://github.com/OHIF/Viewers/issues/909

So, I've added folder 
https://github.com/OHIF/Viewers/tree/master/platform/ui
in my code. 
In the first use, I got the error
Unexpected use of 'event

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
