### ISSUE TITLE
VTK not loading from Json

### ISSUE THREAD

**Issue by FredGillain** [OHIF/Viewers#1238]
It seems that the VTK 2D MPR extension doesn't work when a study is opened using a Json files.

See these two examples (both of the same study) :
 - https://viewer.ohif.org/viewer/1.3.6.1.4.1.25403.52237031786.3872.20100510032220.1
 - https://viewer.ohif.org/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/PTCTStudy.json

The 2D MPR button doesn't appear when using the Json version.

Is this a bug or is there some additionnal data that needs to be passed in the Json for VTK to work ?

Thanks in advance,
F.

**Comment by arthur-miller** [comment]
Hello!

The problem is that in the provided JSON the property "seriesModality" is incorrect:

`"seriesList": [
        {
          ...
          "seriesModality": "CT",
        }`

Adjusting it to "modality" will solve the problem.

**Comment by dannyrb** [comment]
To expand on @arthur-miller's comment, there is some tucked away criteria that determines if the active viewport contains a reconstructable dataset. If we determine that dataset isn't reconstructable, we simply hide the button.

We've highlighted that this isn't optimal, as the user may want to know when/why they can't enter MPR viewing. The current behavior can be confusing.

**Comment by dannyrb** [comment]
See: https://github.com/OHIF/Viewers/blob/2d75e01ea07f4322ccfaccd108089299be43d0df/platform/core/src/utils/isDisplaySetReconstructable.js
