### ISSUE TITLE
Cine dialog remains on screen after return to study list

### ISSUE THREAD

**Issue by vicOnGit75** [OHIF/Viewers#1242]
Problem:
Cine dialog remains on screen after return to study list

Step to reproduce: 
-Clone 3rd December(git clone https://github.com/OHIF/Viewers.git)
-yarn install
-change config in default.js to       **enableStudyLazyLoad: false,**
-yarn start
-go to NAME_ONE ( actually any)
- open cine dialog
-return to study list
-see attached image

![CineRemains](https://user-images.githubusercontent.com/13784498/70083454-0f988700-1615-11ea-8f33-12235b25fd79.png)

**Comment by dannyrb** [comment]
I'm able to reproduce here: https://viewer-dev.ohif.org/

This should be as simple as scoping the `DialogProvider` to the correct routes.

**Comment by mirnasilva** [comment]
Hey @igoroctaviano, good job! I just did a round of tests and everything is working fine.
The issue was fixed and I'm moving it to Done!
Thanks!
