### ISSUE TITLE
DICOM image discoloration

### ISSUE THREAD

**Issue by luohao110** [OHIF/Viewers#1243]
I have a group here. After uploading the DICOM, I found that the image changed color.
- 

- 
[9999937656700_.zip](https://github.com/OHIF/Viewers/files/3920394/9999937656700_.zip)

**Comment by dannyrb** [comment]
Can you include screenshots of the expected versus the actual rendering? Any relevant DICOM tags?

**Comment by luohao110** [comment]
Anticipatory：
![image](https://user-images.githubusercontent.com/48583201/70130890-5d1bff00-16bc-11ea-933e-a402d7835c64.png)

actually：
![image](https://user-images.githubusercontent.com/48583201/70130933-6f963880-16bc-11ea-807c-a4e879b903f9.png)

The DICOM file is in zip above.

**Comment by luohao110** [comment]
> Can you include screenshots of the expected versus the actual rendering? Any relevant DICOM tags?

Please read my reply.

**Comment by dannyrb** [comment]
If these images contain PHI, I'll have to ask you to remove them.
Selecting the images at `https://viewer.ohif.org/local` shows the expected result.
I am unable to reproduce the "actual"

**Comment by luohao110** [comment]
> If these images contain PHI, I'll have to ask you to remove them.
> Selecting the images at `https://viewer.ohif.org/local` shows the expected result.
> I am unable to reproduce the "actual"

Thank you

**Comment by luohao110** [comment]
> If these images contain PHI, I'll have to ask you to remove them.
> Selecting the images at `https://viewer.ohif.org/local` shows the expected result.
> I am unable to reproduce the "actual"



> 如果这些图像包含PHI，我将要求您删除它们。
> 选择图像`https://viewer.ohif.org/local`显示预期结果。
> 我无法复制“真实”
Upload through the Orthanc server and the result is "actual".

**Comment by luohao110** [comment]
> If these images contain PHI, I'll have to ask you to remove them.
> Selecting the images at `https://viewer.ohif.org/local` shows the expected result.
> I am unable to reproduce the "actual"

Upload through the Orthanc server and the result is "actual".

**Comment by dannyrb** [comment]
I'm not sure why that would be. Are you able to spell out the steps required to reproduce this with something like Docker? I'll try to circle back to this.
