### ISSUE TITLE
 Thumbnails dragging for viewing doesn't work in time of image playback

### ISSUE THREAD

**Issue by vicOnGit75** [OHIF/Viewers#1244]
Thumbnails dragging for viewing doesn't work in time of image playback

Steps to reproduce:
-https://viewer-dev.ohif.org/
- go to study with multiple thumbnails ( fro example venus-1.3.6.1.4.1.25403.345050719074.3824.20170126082902.1)
-open cine dialog
-start playback
- Try to drag another thumbnail to view port
Expected behavior- change of image to playback
Actual behavior: no change, also left-bottom corner overlay escapes

Speed change after not  successful attempt does the work.

![DragCine](https://user-images.githubusercontent.com/13784498/70143758-18d13480-16a5-11ea-8db3-526e37f4ecb1.png)

**Comment by dannyrb** [comment]
Hmm... @igoroctaviano, could this be the DraggableArea preventing drag events on the viewports?

**Comment by igoroctaviano** [comment]
> Hmm... @igoroctaviano, could this be the DraggableArea preventing drag events on the viewports?

@dannyrb I tried the mentioned flow but I could not replicate. I could drag normally. Can you check as well?

**Comment by dannyrb** [comment]
Study: https://viewer-dev.ohif.org/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170126083429.2

I'm using FireFox.
Intermittently, the series will not change. Sometimes it switches seamlessly.
The overlay always disappears.
Stopping/starting the CINE player resolves the issue.

This is likely a `react-cornerstone-viewport` issue, not Dialog Service.

**Comment by vicOnGit75** [comment]
I'm working with Chrome 78.
Misbehavior is pretty consistent, not 100% though.
Happened on viewer-dev and also on local server locally build.
Didn't experience such behavior on version from beginning of November.
Also scroll on thumbnail panel is not consistent.

**Comment by dannyrb** [comment]
If I had to guess, when `react-cornerstone-viewport` receives updates `imageIds` props, we should be checking to see if CINE `isPlaying`. We may need to "stop" and then "start" after the stack toolstate is updated.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
