### ISSUE TITLE
Local upload cannot be used.

### ISSUE THREAD

**Issue by luohao110** [OHIF/Viewers#1254]
![image](https://user-images.githubusercontent.com/48583201/70207260-349c0f80-1765-11ea-8479-6db1daa7921d.png)
The console reported an error. File upload and folder upload cannot be clicked, and not "cursor:pointer;"

**Comment by swederik** [comment]
@mirnasilva Can you re-test this? I think it's been fixed.

**Comment by mirnasilva** [comment]
Hi @swederik , I re-tested this on `dev` and `production` environments and the functionality is working as expected. The issue is not reproducible anymore.
I'm closing this ticket. Thanks!
