### ISSUE TITLE
How I can implement it in ionic.

### ISSUE THREAD

**Issue by pmd23** [OHIF/Viewers#1257]
Hi Team,

I am integrating OHIF Viewer into ionic app but while integrating it app while launching i am getting link with go back to study list
this is my fiddle.
http://jsfiddle.net/pdeshmukh/4L3m7hy9/4/
How I can implement it in ionic.

**Comment by dannyrb** [comment]
That message displays when the app can't find the route. That frame of the fiddle loads at a non-root route in an iFrame:

`//fiddle.jsshell.net/<some-string>/<some-string>/<#>/show/`

This is probably an issue with `routerBasename` in the app configuration file, as routes are relative.
