### ISSUE TITLE
How to Disable Timepoint?

### ISSUE THREAD

**Issue by shtl23** [OHIF/Viewers#126]
Hi
Is it possible to disable the Timepoint(ie. baseline/followup) in Lesion Tracker?

**Comment by swederik** [comment]
Hi there,

That depends what you mean. You can open unassociated (i.e. no study-timepoint association) studies, but I think we current disable some of the tools. If you want a general purpose viewer there is also the OHIF Viewer.

What is your use case? You want to make one-off lesion measurements?

**Comment by shtl23** [comment]
Hi,
use case is Save feature in Lesiontracker.
