### ISSUE TITLE
MPR Plugin

### ISSUE THREAD

**Issue by neelflexi** [OHIF/Viewers#1261]
Installed OHIF viewer but 2D MPR tool is missing. How to add or enable this feature? 
Thanks.
![image](https://user-images.githubusercontent.com/4989470/70385976-61486500-19b9-11ea-8270-392e4ff57d75.png)

> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by swederik** [comment]
That looks like the old Meteor version. It doesn't have MPR. Try installing the latest version from master.
