### ISSUE TITLE
CR image rendered with inverted levels

### ISSUE THREAD

**Issue by diaztula** [OHIF/Viewers#127]
Hello,
I have a CR DICOM file from Agfa and it is rendered with the gray levels inverted. I found that this DICOM has a RescaleSlope of -10 and RescaleIntercept of 3000. While this transformation "inverts" the pixel levels (high values stored in the DICOM become low in memory and viceversa), the image is shown correctly when loaded with the Dicom package in Python 2.7.
Anyone found a similar issue?
Thanks in advance
Antonio

**Comment by swederik** [comment]
What is the photometric interpretation (http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.3.html#sect_C.7.6.3.1.2)? It's possible there is a bug in Cornerstone.

Have you tried any other viewers?

**Comment by diaztula** [comment]
Dear Swederik, thanks for your prompt reply!

The photometric interpretation is MONOCHROME2. I have tried with Dicom Web Viewer and the image is rendered inverted. Nonetheless, the preview from Orthanc is not inverted (I found that Orthanc calls preview function from DCMTK and returns the image via Http).

I'm attaching all 0x0028 tags that are related to the image:

```
0028,0002 (SamplesPerPixel): 1
0028,0004 (PhotometricInterpretation): MONOCHROME2
0028,0010 (Rows): 1838
0028,0011 (Columns): 2803
0028,0030 (PixelSpacing): 0.1\0.1
0028,0100 (BitsAllocated): 8
0028,0101 (BitsStored): 8
0028,0102 (HighBit): 7
0028,0103 (PixelRepresentation): 0
0028,0300 (QualityControlImage): NO
0028,0301 (BurnedInAnnotation): NO
0028,1050 (WindowCenter): 1600
0028,1051 (WindowWidth): 2800
0028,1052 (RescaleIntercept): 3000
0028,1053 (RescaleSlope): -1.09803925E001
0028,1054 (RescaleType): OD
0028,1055 (WindowCenterWidthExplanation):
0028,2110 (LossyImageCompression): 00
```
Best regards
Antonio

**Comment by swederik** [comment]
Any chance you could upload an anonymized version? (or send one to me by email)

**Comment by diaztula** [comment]
Dear Erik, I have sent you an anonymized DICOM.

Thanks!

**Comment by swederik** [comment]
Closing this because the image is being displayed correctly.
