### ISSUE TITLE
Cross-reference lines

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1270]
Would it be possible to add cross-reference lines to OHIF viewer when browsing series with different image planes that mark the intersection of the image planes ? This would really help in better correlation of the anatomy.

**Comment by swederik** [comment]
Closing because this is a duplicate which has been asked many times:

https://github.com/OHIF/Viewers/issues/747
https://github.com/OHIF/Viewers/issues/1060

One of these was actually already asked by **YOU**: https://github.com/OHIF/Viewers/issues/619
