### ISSUE TITLE
Cannot import studies to Lesion Tracker

### ISSUE THREAD

**Issue by gokhandilek** [OHIF/Viewers#128]
It just freezes and upload won't progress.
Do you know if this is working for anyone?

**Comment by ouceduxzk** [comment]
import studies in OHIF viewer also freezes and not progress.

**Comment by dannyrb** [comment]
We are moving away from support for version 1 of the Viewer. The goal is to make Version 2 extensible and configurable enough that you can customize it for your workflow and purposes. (Like modifying it to look/feel like today's lesion tracker).

This issue hasn't seen activity in some time, so I'm going to close it. If you're able to provide a minimal reproduction I would be willing to open it for another 60 or so days to see if the issue can be recreated with your reproduction and for others to offer help.
