### ISSUE TITLE
Find and resolve two Bugs.

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#1280]
1.If the image header does not contain the tag of 00200032 (imagepositionpatient), the image will not be displayed. This is because not determine whether it exists when using this value. We should add judgment to the following code: Under file of '\platform\core\src\utils\isDisplaySetReconstructable.js',
function _getImagePositionPatient(instance) {
    let imagePositionPatient = instance.getTagValue('x00200032');
    // Should verify the value of imagePositionPatient is exists, if not, assign a default value
    if (!imagePositionPatient)
        imagePositionPatient = "0\\0\\0";

    return imagePositionPatient
    .split('\\')
    .map(element => Number(element));
}

2.I find that the image displayed on the thumbnail is inconsistent with the series, sometimes there are multiple thumbnails displaying the same image. This is due to in the componentDidMount() method of ImageThumbnail class, before displaying to the thumbnail when downloaded the image, it is not verified whether the image is the corresponding image of this thumbnail.
We should modify then() after fetchimage() in this way: Under file of '\platform\ui\src\components\studyBrowser\ImageThumbnail.js',
this.fetchImage(this.props.imageId)
            .then(image => {
            // Verify whether the two imageId are the same, we should download the image if they are different. Otherwise, the image of thumbnails will be inconsistent.
            if (image.imageId !== this.props.imageId) {
                cornerstone.loadAndCacheImage(this.props.imageId)
                    .then(image => {
                        cornerstone.renderToCanvas(this.canvas.current, image);
                        this.setState({
                            loading: false,
                        });
                    })
            }
            else {
                cornerstone.renderToCanvas(this.canvas.current, image);
                this.setState({
                    loading: false,
                });
            }
        })

**Comment by sgala** [comment]
Hi, we have experimented on a study seen on the field the first of the two bugs commented here, and verified that the patch fixes it:
* a CT with images (DERIVED,SECONDARY,MPR) missing imagepositionpatient.
* the following exception was thrown by OHIF in the console:
```
  TypeError: "instance.getTagValue(...) is undefined"
    _getImagePositionPatient http://10.56.1.125/app.bundle.1a03b0070f6b7f042a2d.js:92886
    processSingleframe http://10.56.1.125/app.bundle.1a03b0070f6b7f042a2d.js:92813
    isDisplaySetReconstructable http://10.56.1.125/app.bundle.1a03b0070f6b7f042a2d.js:92772
    makeDisplaySet http://10.56.1.125/app.bundle.1a03b0070f6b7f042a2d.js:93602
    ...
```
* screen blanked with a "Error: true" showed on black over the dark blue background.
* When I patch the following 
```
diff --git a/platform/core/src/utils/isDisplaySetReconstructable.js b/platform/core/src/utils/isDisplaySetReconstructable.js
index 950320540..fb64d8fa5 100644
--- a/platform/core/src/utils/isDisplaySetReconstructable.js
+++ b/platform/core/src/utils/isDisplaySetReconstructable.js
@@ -136,8 +136,11 @@ function _getSpacingIssue(spacing, averageSpacing) {
 }
 
 function _getImagePositionPatient(instance) {
-  return instance
-    .getTagValue('x00200032')
+  let imagePositionPatient = instance.getTagValue('x00200032');
+  // Should verify the value of imagePositionPatient is exists, if not, assign a default value
+  if (!imagePositionPatient)
+    imagePositionPatient = "0\0\0";
+  return imagePositionPatient
     .split('\\')
     .map(element => Number(element));
 }
```
and rebuild, the image gets visualized correctly and the exception is no longer present

**Comment by JiangWeian** [comment]
@sgala
OK. When obtaining DICOM tag information, if there is undefined in the meta-infomation, returning the default value can make the program more robust. You can refer to the fo-DICOM library to obtain DICOM tag information. Such as:
df.Dataset.Get(fo.DicomTag.PatientName, string.Empty);

The 'string.Empty' that is the default value.

**Comment by subhasishdash** [comment]
Same problem comes with ohifv3 and this workaround doesn't help.
