### ISSUE TITLE
Tool abstraction for vtk.js

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1285]
# Tool abstraction for vtk.js

## Context

`react-vtkjs-viewport` has slowly grown to include more and more features. We're now at the point where we need the ability to change "tool" bindings based on user input, or the context in which the viewer is currently being used.

Currently, we accomplish this be leveraging:

[`RenderWindowInteractor`](https://github.com/Kitware/vtk-js/tree/master/Sources/Rendering/Core/RenderWindowInteractor) (Interactor) -->
[`InteractorStyleXXX`](https://github.com/Kitware/vtk-js/tree/efc2840b7f77b0d1c6f035aa867aacaa5ca090f3/Sources/Interaction/Style) (InteractorStyle) -->
Manipulators

Where `RenderWindowInteractor` normalizes browser interactions and exposes those normalized events to an `InteractorStyle`. Interactor styles can then optionally handle each of those events. @JamesAPetts has pointed to the [`InteractorStyleManipulator`](https://kitware.github.io/vtk-js/api/Interaction_Style_InteractorStyleManipulator.html) as a good example.

We can only have one `InteractorStyle`, and we're currently extending and swapping them out depending on which behaviors we would like to have active. We have the ability to modify manipulators on the `InteractorStyle` even after it's set; where manipulators or _sort of like_ "one-button tools".

(I'm stating this in the hopes that someone corrects me if I've missed the mark.)

## Discussion

It has been suggested that the current pattern mirrors that of `cornerstone-tools@2`, where listeners for behaviors/tools would compete with each other. We could model our changes to make the same enhancements we accomplished in `cornerstone-tools@3` by:

- Treating `RenderWindowInteractor` as our "event listener"
- Creating a single `InteractorStyle` that:
    - Emits events akin to `cornerstonetoolsmouseclick`
    - Functions similarly to that of `cornerstone-tools` event dispatchers
- Define a tool abstraction similar to that of `cornerstone-tools` that our new "event dispatcher" can use to determine who should "capture" events and apply their active strategies

Perhaps the biggest difference here would be for "tools" that do more than modify the viewport/camera. `vtk.js` renders annotations differently from `cornerstone-tools`, and how that fits in is still unclear.

This is a discussion piece to get the ball rolling. Please feel free to weigh in.

**Comment by dannyrb** [comment]
👢 💨 🤖

**Comment by sedghi** [comment]
Since we have moved to cornerstone3D I will close this, thanks
