### ISSUE TITLE
Is it possible to use OHIF-viewer with a project that doesn't follow DicomWeb specs and also doesn't use any kind of image archive(orthanc etc) . If so How?

### ISSUE THREAD

**Issue by vinodmehta367** [OHIF/Viewers#1286]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by dannyrb** [comment]
Your GitHub issue is a title with no changes to the template/description. Can you please elaborate on what your requirements are?

The OHIF Viewer has a few different ways to retrieve and work with alternative data sources. Others are planned, but may require outside contributions to come to fruition.

**Comment by vinodmehta367** [comment]
mine is a spring boot project and i'm doing image processing on dicom files,so currently i'm just checking if i can upload my studylist to your viewer by making a Rest Api call.

**Comment by vinodmehta367** [comment]
without using DicomWeb and image viewer

**Comment by dannyrb** [comment]
> upload my studylist to your viewer

The OHIF Viewer has no REST API or server-side implementation.

You can view local files:
- viewer.ohif.org/local

You can configure DICOMWeb, or you can use a query string to use JSON (that you have to generate yourself) to power the viewer. There are a few other options slated, but they're unlikely to happen near future.
