### ISSUE TITLE
position line

### ISSUE THREAD

**Issue by shunjuan** [OHIF/Viewers#1287]
the position line function and preset  wwwc  is normal in pacs

**Comment by dannyrb** [comment]
Are you requesting reference lines and WWWC presets?

We have a tracking issue for reference lines here: #619
While it's on our roadmap, it's not being actively developed. A community member is more than welcome to submit a PR.

Window Level presets were implemented in the Meteor version of this application. We do not yet have an issue scoped to restore that behavior.

**Comment by shunjuan** [comment]
thanks&nbsp;for&nbsp;your&nbsp;reply&nbsp;,yes,&nbsp;reference lines and wwwc presets are&nbsp; often used in dicom view ,


When do you plan to implement this function?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Danny Brown"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 中午11:49
收件人:&nbsp;"OHIF/Viewers"<Viewers@noreply.github.com&gt;;
抄送:&nbsp;"如月之夫"<382902650@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [OHIF/Viewers] position line (#1287)




Are you requesting reference lines and WWWC presets?
 
We have a tracking issue for reference lines here: #619
 While it's on our roadmap, it's not being actively developed. A community member is more than welcome to submit a PR.
 
Window Level presets were implemented in the Meteor version of this application. We do not yet have an issue scoped to restore that behavior.

**Comment by dannyrb** [comment]
The core team's priorities are determined by grants and private funding. We share our very short-term roadmap here: https://github.com/OHIF/Viewers/projects/4

However, we are always willing to review pull requests from our community members, and to discuss recommended implementation steps. If there is something you need completed quickly, but are unable to complete the development work yourself, then I recommend reaching out to a contractor or consultancy.
