### ISSUE TITLE
Study list and QuickSwitch like LesionTracker

### ISSUE THREAD

**Issue by Y4kuz4** [OHIF/Viewers#1288]
Hello,

I need help to add study list (left side panel) and quick switch component on ohif viewer's react code like lesion tracker (red arrows on image). It's possible?

Thx!
<a href="https://ibb.co/yQF2kWq"><img src="https://i.ibb.co/yQF2kWq/20191211-231559.jpg" alt="20191211-231559" border="0"></a>

**Comment by dannyrb** [comment]
@Y4kuz4, both of these features should be possible using extensions. If you encounter issues or limitations with achieving this with extensions, please report back. We're heavily investing in improving extensions and empowering the community to build them:

https://docs.ohif.org/extensions/

**Comment by Y4kuz4** [comment]
thx!!
I'm oral and maxillofacial radiologist without skills on react coding, so i hope in the future your team can add this like lession tracker version. It is a necessary feature to load old study/series and compare for example 2 xray evolution on time with 1x2 layout on the same window.

**Comment by Y4kuz4** [comment]
dannyrb , can you help me? i need this components =(

**Comment by dannyrb** [comment]
@Y4kuz4, I appreciate how frustrating it can be when your needs are very close to being met, but not quite fulfilled. While I wish I could add this functionality for you immediately, I have other demands on my time that take priority.

We will likely eventually pursue the changes you're seeking. Probably as a way to demonstrate the recent extension enhancements, and as an example of how to create different viewer experiences with configuration (a la recreating the lesion tracker experience).

The easiest ways to expedite progress on issues important to you are: drafting pull requests for changes you would like to see (do the work), regularly participating in community issue discussions to influence the platform's direction (highlight the value in a direction), or work with a contractor/consultancy to do those things on your behalf.

FWIW, my priorities are dictated by:
- The grant(s) that fund the OHIF viewer's maintenance and development
- Paid consulting work through the consultancy I sub-contract through
- Time that I volunteer for issues personally important to me

**Comment by Y4kuz4** [comment]
thx for your answer. 

Have you thought about enabling a system like patreon?

**Comment by dannyrb** [comment]
@Y4kuz4, we've briefly looked into Patreon, OpenCollective, and bug bounties. Unfortunately, many other more popular OSS contributors and projects use these services and see little in the way of support. We decided against using them, as they may cost more in our time than the benefit they could bring.

The only thing that may change our stance on that would be if a few companies stepped forward and offered more comprehensive backing. It's all very tricky, as many want to help influence the direction of the project, but few want to offer support/resources.
