### ISSUE TITLE
Improve hotkeys configuration experience

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1297]
RE: https://github.com/OHIF/Viewers/pull/1290/commits/c89b03a55e2bb59ec92b9b17ceb8670113c71a72#diff-ab36e43f2e61e342166a626881931d9cR19

# Improve hotkeys configuration experience

## Context

- Components register named commands
- We have the ability to tie command names to keybindings
- Default associations is currently a manual process done in the app's config

## Problems

1. Setting up a default configuration for hotkeys requires us to investigate all commands for all extensions and generate config schema (time consuming, error prone, maintenance work)
2. If we don't setup commands, the User Preferences panel is empty and awkward

## Discussion of Solutions

It has been suggested that we should use "default hotkeys" when none are specified. This gets a little hairy, as extensions can share command names, and make for conflicting default bindings. We might need to add support for defining context specific commands, or leverage namespaced registration.

Related: [Commands docs](https://docs.ohif.org/extensions/modules/commands.html)

**Comment by sedghi** [comment]
In latest master we have modes that can configure their hotkeys
