### ISSUE TITLE
Retrieve and display amount of images per study and total in worklist

### ISSUE THREAD

**Issue by mtjvankuik** [OHIF/Viewers#13]
I want to show the amount of images in the worklist. This means in every row (corresponds to 1 study) the amount of instances of that study must be shown (1). In the top the total amount of images must be shown (2). 

So far I know the instanceNumber tag is necessary, i.e. instanceNumber(0020,0013). To accomplish (1), I have to count the total amount of instances within the study row. Then show this sum in the corresponding row. 

To accomplish (2), I have to count all the instances of all studies in the worklist. The sum of this count is the total amount of instances of all studies, i.e. the total count of all images.

So far I have some trouble accomplishing this. Is there someone who could give me a suggestion?

**Comment by knopkem** [comment]
Hi,
I don't think the instanceNumber tag will be of much use here (It's not reliable for any computation). If you want to show the number of images that are within a study, then the PACS (getting queried) has to support the optional tag: NumberOfStudyRelatedInstances (see: https://www.medicalconnections.co.uk/kb/Counting_Studies_Series_and_Instances) .
This was already sufficiently answered in the thread about the modality filters.
The naive way of counting instances would be possible but is not efficient as you have to traverse each study down to image level. You will just spam the PACS with hundreds of requests.
Hope that helps.
