### ISSUE TITLE
Decompose ToolContextMenu to generic ContextMenu and DialogService calls 

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#1303]
- Shift the monkey patching the MeasurementsExtension does to cornerstone-tools (it glues on a tool id to toolState, and a few other things).
- Use the generic ContextMenu component and DialogService to create a higher level ContextMenuService.
- Update MeasurementsExtensions to use ContextMenuService.
- Provide docs on ContextMenuService.

**Comment by dannyrb** [comment]
The idea here is that you essentially need to compose the `ContextMenu` component and `DialogService` each time you'd like to leverage something akin to a `ContextMenuService`. We think this may be a common enough usage, that we could make it an "off the shelf" service with a friendlier API and documentation.

Our current use case for the `contextMenu` does a few things that muddy the waters. The bullet points above outline how to clean it up before shifting to this new approach.

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
