### ISSUE TITLE
[Thumbnail Series] issues with scrolling list

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1309]
### Issue 1: Mouse wheel not scrolling thumbnail list on Series panel

If user isn't placing the mouse cursor on a thumbnail, the mouse wheel won't scroll the thumbnail list.

**Expected Result:**
1. Mouse wheel should scroll the thumbnail list when mouse cursor is placed anywhere inside the Series panel, not only on the thumbnail.

![bug-mouse-scroll-thumbnails](https://user-images.githubusercontent.com/13245529/71007431-c3921b80-20c5-11ea-9cc9-b14464085c18.gif)

### Issue 2: Arrows UP and DOWN scrolls thumbnails after drag-n-drop

If user drags a new thumbnail into the viewport and tries to navigate between the study frames with Arrow Up and Down, the thumbnail list will also scroll.

**Steps to reproduce:**
1. Open Patient Study `MISTER^MR`
2. Press hotkeys `ARROW UP` and `ARROW DOWN`
3. Verify that you will navigate in the study frames
4. Drag-and-drop the second thumbnail into the viewport
5. Press hotkeys `ARROW UP` and `ARROW DOWN`
6. Verify that you will navigate in the study frames
7. Verify that Thumbnails list will be scrolled

**Expected Result:**
1. Thumbnails list should not be scrolled by hotkeys `ARROW UP` and `ARROW DOWN`

![bug-arrow-scroll-thumbnails](https://user-images.githubusercontent.com/13245529/71007459-cf7ddd80-20c5-11ea-835c-8a8440894e3c.gif)

**Comment by mirnasilva** [comment]
**Issue 1**: I'm not able to reproduce this issue anymore. Tested on stage environment with build number 8952.

**Issue 2**: Still reproducible. Tested on stage environment with build number 8952.

**Comment by robert9g** [comment]
I cannot reproduce any of the two issues.
Started app with `yarn run dev`.
Tested with patients `MISTER^RF` and `MISTER^CT` (patient `MISTER^MR` does not exist).
OS: Linux Mint 19.2
Tested on two browsers:
- Chrome: Version 80.0.3987.132 (Official Build) (64-bit)
- Firefox: 74.0 (64-bit)

**Comment by Reminisque** [comment]
I attempted to reproduce both issues for both the live demo and locally. For the local app, I have the most recent version of the repository forked and cloned.

Started the app with `yarn start`.

**Issue 1**: I was unable to reproduce the issue for both the live demo and locally.
**Issue 2**: I was able to reproduce the issue for the live demo, but not locally. 

I found that the second issue is not only limited to after dragging and dropping thumbnails but also after whenever the user clicks inside the `<div class="scrollable-study-thumbnails">` element. 
Clicking in the areas of the parent  element `<div class="study-browser>` where they don't overlap does not reproduce the issue.

I don't know if this is also an issue, but I was also able to scroll the thumbnail list using `HOME`, `END`, `CTRL+HOME`, `CTRL+END`, `PAGE UP` and `PAGE DOWN`. 
This occurred with all the keys on the live demo, and all but `PAGE UP` and `PAGE DOWN` on the local app.

OS: Windows 10 Home Edition 64-bit
Chrome: Version 80.0.3987.149 (Official Build) (64-bit)
Tested with patients `Fall 2`, `MISTER^CT` and `MISTER^DX`

**Comment by mirnasilva** [comment]
Hi @Reminisque , thank you for taking the time to check this issue.

From my point of view, if the key is defined as a hotkey under user preferences, then it should not be able to scroll the thumbnail list. @dannyrb can you please confirm this?

In this case, since `HOME`, `END`, `CTRL+HOME`, `CTRL+END` were not assigned as a hotkey, then it should be fine if they are scrolling the thumbnail list.

Now, regarding the `PAGE UP` and `PAGE DOWN` keys, I noticed that the issue is actually on the **Previous Series** and **Next Series** hotkey function. Once we press any of these keys, nothing happens on the viewport and the following error is thrown on the console:

```
Uncaught ReferenceError: utils is not defined
    at updateViewportDisplaySet (commandsModule.js?66a2:36)
    at CommandsManager.runCommand (CommandsManager.js?a87a:184)
    at eval (HotkeysManager.js?9c96:206)
    at _fireCallback (mousetrap.js?77f4:616)
    at Mousetrap.self._handleKey (mousetrap.js?77f4:677)
    at Mousetrap.handleKey (mousetrap.js?77f4:1008)
    at Mousetrap._handleKey (recordPlugin.js?cb27:59)
    at Mousetrap.handleKey (recordPlugin.js?cb27:214)
    at HTMLDocument._handleKeyEvent (mousetrap.js?77f4:737)
```

<img width="500" alt="Screen Shot 2020-03-23 at 14 19 22" src="https://user-images.githubusercontent.com/13245529/77344108-77ccbf00-6d11-11ea-8705-901d27a19328.png">

I'll update the issue description accordingly with all the findings here.
Thanks!

**Comment by dannyrb** [comment]
> From my point of view, if the key is defined as a hotkey under user preferences, then it should not be able to scroll the thumbnail list.

If there is...
- A registered command
- Its bound hotkeys overlap a browser's own shortcut/hotkey
- The command is "in context" and "should fire" if executed

Then...
I would expect the browser's own shortcut/hotkey to not fire (preventDefault)

These should be tested at: https://viewer-dev.ohif.org or on latest/`master`

**Comment by mirnasilva** [comment]
Thanks @dannyrb, That's also my understanding. 
On `master` both issues were not reproducible.  I'll move forward and close this ticket.
