### ISSUE TITLE
[Save Measurements] issues when measurements are retrieved

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1311]
### Issue 1: Retrieved measurements are always displayed on the first viewport when we have multiple viewports

When user has multiple viewports and tries to navigate between the measurements (by clicking on each measurement inside the measurements panel), the measurements retrieved are displayed only in the first viewport.

If user activates another viewport and clicks on any measurement inside the right panel, the retrieved measurement will be loaded on the first viewport, ignoring the user selection.

**Steps to Reproduce:**
1. Load a Patient Study that has Measurements saved (i.e. Juno)
2. Set viewport layout to at least 3
3. Open Measurements panel
4. Click on first measurement item, under Measurements panel
5. Verify that the measurement annotation will be retrieved on the first viewport
6. Set the second viewport active by clicking on it
7. Click on any measurement item, under Measurements panel
8. Verify that the measurement annotation will be retrieved on the first viewport and not on the second viewport

**Expected Result**
1. Retrieved measurements should be displayed in the active viewport and not always in the first one.

![bug-layout-measurements](https://user-images.githubusercontent.com/13245529/71022933-71122880-20e0-11ea-9a00-071b6a137d90.gif)

### Issue 2: Some annotations are not being retrieved when Image has multiple measurements saved

When image frame has multiple measurements on it, some annotations are not being displayed in the viewport. Although all the measurements are listed under the panel, if user clicks on each of them, some are not being displayed on the viewport. If user makes any changes to existing displayed measurements, the "missing" measurements start to load/show up. (please see gif below)

**Steps to Reproduce:**
1. Load Patient Study: Juno
2. Select 3rd thumbnail (Serie 4), and scroll to Frame 71 (Img: 71 71/174)
3. Open Measurements panel
4. Verify that only 5 measurements are displayed on this frame
5. Click on Measurement items with index from `11 to 18`
6. Verify that none of them will be retrieved
7. Change some of the existing annotations on this frame
8. Verify that the missing annotations will start to show up

**Expected Results:**
1. All measurements should be displayed on the viewport
2. All measurements should have a distance/size displayed in the panel. The smallest measurement size/distance accepted should be `0.0 mm` and not `...`.

![bug-loading-saved-annotations](https://user-images.githubusercontent.com/13245529/71023482-96536680-20e1-11ea-859a-2701355d4a1d.gif)

**Comment by dannyrb** [comment]
These are great reports! Thank you. I think we need to do a bit of digging and discussion before we start on solutions for these, but I'll shift this to a verified bug that we intend to address.

**Comment by sedghi** [comment]
@jbocce can you verify this against latest master?

**Comment by jbocce** [comment]
No longer reproducible in master.
