### ISSUE TITLE
[Cornerstone tools] Image tools are interacting with measurement annotations

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1312]
## Bug Report

User is able to interact with measurement annotations using some of the cornerstone tools that should only manipulate the image. I.e. Tools: Stack Scroll, Zoom, Levels, Pan, etc.

If user selects one of the following tools and hover over one annotation, it will become green and the user will be able to interact with this annotation (move it, change its size, etc).

**Tools:** Stack Scroll, Zoom, Levels, Pan, Magnify, ROI Window, Probe

**Expected Result:**
1. By selecting one of the mentioned tools, the user should be able to only interact with the image inside the viewport and not with the measurements on it.
2. User should be able to manipulate the measurements only if one of the following tools are selected/active: Length, Annotate, Angle, Ellipse, Rectangle, Clear, Bidirectional, Eraser

![bug-cornerstone-tools-interacting-annotations](https://user-images.githubusercontent.com/13245529/71028039-3e216200-20eb-11ea-9e04-27799fdb83a4.gif)

**Comment by dannyrb** [comment]
This is the expected/desired behavior. We could decrease the distance threshold, but that could have the adverse effect of making annotations hard to grab.
