### ISSUE TITLE
[Measurements Panel] Too much text for Description breaks the item index layout

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1313]
## Bug Report

This is a very minor bug and does not impact any functionality.
When user enters a description that is a little bit longer, the measurement table index breaks the layout.

Please check the image below for reference:

![Screen Shot 2019-12-16 at 20 36 34](https://user-images.githubusercontent.com/13245529/71032188-99efe900-20f3-11ea-9f59-2921d6d95d43.png)

**Comment by barhantas** [comment]
Also we have an invisible delete button in this case.

**Comment by mirnasilva** [comment]
Tested and this issue was fixed by #1352.
Thanks for working on this one, @barhantas!
I'm closing this ticket. Thanks
