### ISSUE TITLE
Failed to run on Windows

### ISSUE THREAD

**Issue by hasanmansor** [OHIF/Viewers#132]
Hello Guys, 

I am trying to run OHIF viewer on my local system but failed. I have installed meteor and orthanc server and also have configured the Orthanc/Configuration/orthanc.json by adding this line:

`"  "ohif" : [ "OHIFDCM", "localhost", 3000 ] "`

I have tried different commands as shown in the attached image, to run the application but failed.. any help would be highly appreciated. Note, that meteor is running properly on my local. 

![capture](https://user-images.githubusercontent.com/22391260/32837986-d72b7c72-ca0f-11e7-8432-980afa53a219.JPG)

Regards,

**Comment by radicalrob** [comment]
Hi @hasanmansor,

That syntax is for linux / mac.  For Windows, the environment variable (PACKAGE_DIRS) has to be set with the command "set". 

Have a look at this .bat file: https://github.com/OHIF/Viewers/blob/master/OHIFViewer/bin/orthancDICOMWeb.bat

**Comment by hasanmansor** [comment]
Hi @radicalrob , 

Thanks for your response, I still have issues as shown in the image:

![1](https://user-images.githubusercontent.com/22391260/32839239-12ae6a3a-ca14-11e7-9238-4cb4f324b4bb.JPG)

**Comment by radicalrob** [comment]
the path needs to use '\' not '/' since it's on Windows.

**Comment by hasanmansor** [comment]
Thanks for your help but still the same issue 

![1](https://user-images.githubusercontent.com/22391260/32840187-3b4d79ce-ca17-11e7-8201-57ae6f8a7640.JPG)

**Comment by radicalrob** [comment]
try running the .bat file from that folder

**Comment by hasanmansor** [comment]
already have run this again and again but the issue still exists

**Comment by Zaid-Safadi** [comment]
I was able to get this to work by setting the packages full path in the "Environment Variables" rather than in the console, eg:
METEOR_PACKAGE_DIRS : D:\meteor\OHIFViewers\Viewers\Packages

**Comment by hasanmansor** [comment]
Hi Zaid, 
Thanks a lot .. It worked by setting the environment variable in the OS by providing the exact path (including the drive) of the Packages as you mentioned.. thanks again

**Comment by swederik** [comment]
Out of curiosity, which version of Windows is this? I've run the viewer on Windows 10 in the past and didn't need the full path.

**Comment by hasanmansor** [comment]
Its unfortunately Windows7 :(

**Comment by Zaid-Safadi** [comment]
@swederik, could there be a debug param (-verbose) when running OHIF viewer to display the packages folder path?
