### ISSUE TITLE
Cine dialog remains on screen after dragging SR/DOC thumbnails

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1321]
### Describe the Bug

If user opens de CINE dialog and loads a different type of file on the viewport (`SR` or `DOC` thumbnails), the dialog will remain displayed and the user can't close it.

**Steps to reproduce**
1. Open Patient Study: Dummy
2. Open CINE dialog
3. Drag into the viewport `SR` or `DOC` thumbnail
4. Verify that the dialog remains displayed and cornerstone toolbar is not available anymore

**Expected Result**
1. Once user loads a new file on viewport that doesn't support cornerstone toolbar, the CINE dialog should not be displayed.

![Screen Shot 2019-12-18 at 16 53 37](https://user-images.githubusercontent.com/13245529/71118717-670f2900-21b7-11ea-8407-5a84c93184e8.png)

Related PR: #1301

**Comment by dannyrb** [comment]
resolved in #1540
