### ISSUE TITLE
How to  use OHIF viewer Into Angular 7 or 8 application

### ISSUE THREAD

**Issue by abdullegend** [OHIF/Viewers#1325]
Dear Team,
Kindly advise that it possible to use this package (OHIF viewer) into Angular 7 or 8 application. It will be helpful.

> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by dannyrb** [comment]
You can use React components in angular by using `ReactDom.render` and wrapping them in an Angular component.

You could also embed and configure the entire `@ohif/viewer` application in an iFrame
