### ISSUE TITLE
VTK toolbar issues 

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1326]
## Bug Report

The issues described here are related to #1324

### Issue 1: 2D MPR button is not displayed if user clicks on Study List and selects the same Patient

When user is viewing a Patient series that is reconstructable the `2D MPR` button will be displayed as expected. But if user decides to click on `Study List` link and then selects the same Patient, the `2d MPR` button will not be displayed anymore. If user reloads the page, the button will be displayed again.

Although I tested this in incognito mode, it looks like something related to cache. (not sure though)

**Steps to Reproduce:**
1. Search and select Patient Name: Juno
2. Drag-n-drop 3rd thumbnail into the viewport
3. Verify that button `2D MPR` is displayed as expected
4. Click on link `Study list`
5. Search and select Patient Name: Juno
6. Drag-n-drop 3rd thumbnail into the viewport
7. Verify that button `2D MPR` is **not** displayed

**Expected Result:**
1. Button `2D MPR` should always be displayed if the active viewport contains a displaySet that is reconstructable
2. If user navigates back and forth between study list page and study viewer, button `2D MPR` should always be displayed if the active viewport contains a displaySet that is reconstructable

![issue 1](https://user-images.githubusercontent.com/13245529/71385931-09207e00-25c9-11ea-8607-68dee4ba50bd.gif)

### Issue 2: User can navigate between non-existent viewports and VTK toolbar is displayed

If user exits the `2D MPR` mode and press hotkeys`ARROW RIGHT` and `LEFT`, he/she will be able to navigate between viewports that are not visible and should not exist. Once user navigates to a viewport different from the current one, the VTK toolbar is displayed but user cannot interact with it.

**Steps to Reproduce:**
1. Search and select Patient Name: Juno
2. Drag-n-drop 3rd thumbnail into the viewport
3. Click on `2D MPR`button
4. Click on `Exit 2D MPR` button
5. Press hotkey `ARROW RIGHT`
6. Verify that VTK toolbar is displayed
7. Verify that the current viewport is not set as active
8. Click on `Exit 2D MPR` button and verify that nothing happens
9. Verify that by pressing hotkeys `ARROW RIGHT` and `LEFT` user is able to navigate between viewports that are not displayed

**Expected Results:**
1. After exiting the `2D MPR` mode, user should not be able to navigate between the recently closed viewports by pressing hotkeys `ARROW RIGHT` and `LEFT`.
a) After exiting the `2D MPR` mode, the other 2 viewports used to reconstruct the image should be removed/destroyed.
b) User should navigate only between viewports that exist and are visible to the user.
c) User should not be able to navigate between viewports that are not visible to the user.
2. After exiting the `2D MPR` mode, only one viewport should exist.
3. After exiting the `2D MPR` mode, the Cornerstone toolbar should be displayed with `2D MPR` button (if the active viewport contains a displaySet that is reconstructable).

![issue 2](https://user-images.githubusercontent.com/13245529/71386592-b6959080-25cd-11ea-96a7-e598fafc7875.gif)

### Issue 3: VTK initial state has Rotate button selected but Crosshairs is the active tool

VTK initial state has `Crosshairs` set as default, but the toolbar button icon is not being updated according to that. If user selects another VTK tool, closes the toolbar and opens again, the selected tool will remain the same although the active tool in the viewport will be the `Crosshairs`.

**Steps to Reproduce:**
1. Search and select Patient Name: Juno
2. Drag-n-drop 3rd thumbnail into the viewport
3. Click on `2D MPR` button
4. Click on `Rotate` button (or `WWWC` button)
5. Click on `Exit 2D MPR` button
6. Click again on `2D MPR` button
7. Verify that `Rotate` is the selected button on the toolbar, but Crosshairs is the active tool in the viewport

**Expected Results:**
1. VTK toolbar should be reset/updated each time the `2D MPR` mode is selected.
2. VTK toolbar should initiate with menu icon selected according to the default active tool (i.e. `crosshairs`)

![issue 3](https://user-images.githubusercontent.com/13245529/71387658-9d8fde00-25d3-11ea-9fdc-3800d57d8e4a.gif)

### Issue 4: User cannot exit VTK toolbar if the active viewport is not the first one

When user sets as active a different viewport (not the first one) and clicks on `Exit 2D MPR` button, the layout will change to display only one viewport, but the VTK toolbar remains displayed. If user clicks again on `Exit 2D MPR` button, nothing happens.

In order to close the VTK toolbar, the user has to click on the currently displayed viewport to set it as active and then the cornerstone toolbar will be displayed.

This issue may be related to issue 2.

**Steps to Reproduce:**
1. Search and select Patient Name: Juno
2. Drag-n-drop 3rd thumbnail into the viewport
3. Click on `2D MPR` button
4. Press hotkey `ARROW RIGHT`
5. Verify that the 2nd viewport is set as active
6. Click on `Exit 2D MPR` button
7. Verify that layout changed and only one viewport is displayed
8. Verify that VTK toolbar still being displayed
9. Click on `Exit 2D MPR` button
10. Verify that nothing happens
11. Click on the viewport displayed
12. Verify that now Cornerstone toolbar is displayed instead of VTK toolbar

**Expected Results:**
1. No matter which viewport is active, user should be able to close VTK toolbar by clicking on `Exit 2D MPR` button.
2. Once VTK toolbar is closed, the displayed viewport should be set as active.
3. Once VTK toolbar is closed, the Cornerstone toolbar should be displayed.

![Issue 4](https://user-images.githubusercontent.com/13245529/71387940-f7dd6e80-25d4-11ea-94b8-d6b1728836e5.gif)

**Comment by galelis** [comment]
Quick check on all issues reported, some of then where also reproducible before VTK toolbar refactor. Here is a quick study on each issue: 

#1 - valid issue
studyMetadataManager.all() returns empty after opening same study in sequence.

#2 - valid issue
layout manager does update the current layout but keep track of what we had in the other ones, commands is probably changing the current plugin into redux store and its chaging the toobar.

#3 - valid issue
Need to check how tools are being set as default active once we change between extensions and also how to clear old settings and make sure default ones are set.

#4 - valid issue
After going in and out of VTK and cornerstone viewports and changing the active viewports, the toolbar gets all messed up.
Possible issue: layout manager might be messing up with the toolbar, `Exit 2D MPR` is probably trying to exit mpr on a non visible active viewport that is hidden
