### ISSUE TITLE
How I use standalone Viewer ?

### ISSUE THREAD

**Issue by Malik-Adil** [OHIF/Viewers#1329]
When i Try to Use on platform/viewer. It extract some configuartion for main Viewer folder for e.g babel.config.js and some other config file using in webpack. 

Can guide me how i use standalone viewer ?

**Comment by dannyrb** [comment]
Have you tried the instructions outlined in the repository readme and/or at https://docs.ohif.org? What have you tried? Where are you having trouble?

**Comment by lizwxup** [comment]
can you guide me how to load data in standalone viewer?? it shows no imageId??

**Comment by lizwxup** [comment]
how to build about standalone viewer??

**Comment by lizwxup** [comment]
why  build a dist  directory and  i dont view a dicomviewer through a config url?? i  should how to do

**Comment by dannyrb** [comment]
I don't understand your questions, @lizwxup. The same questions I asked @Malik-Adil apply. I need more information in order to assist you.

**Comment by yadavvirus** [comment]
@dannyrb Sir can you please give me steps from begning what i have to do for running OHIF Viewer. I failed to get  https://docs.ohif.org
I am really begnnier for this. I want simple guided steps from download to run.
If possible help Me.
Thank You

**Comment by yadavvirus** [comment]
@dannyrb What is Static Assets and from where I will get this?

**Comment by dannyrb** [comment]
@yadavvirus, what is your goal? Are you trying to run a simple viewer on a single machine? Does it need to be web accessible? Are you trying to develop/extend the OHIF Viewer?

**Comment by yadavvirus** [comment]
@dannyrb Yes Now only I want to run OHIF Viewer from my local Machine and View DICOM Image from my own Workstation by QUADO-RS . Please help me in documnet link https://docs.ohif.org there are many things making confused Plz If you have any simple steps to run plz provide me. Once this run then I ll do rest my own.
Thank You

**Comment by dannyrb** [comment]
The OHIF Viewer is not an installable desktop viewer. It requires a web server to "serve" the web application. You configure the QIDO-RS and WADO-RS endpoints in the `/platform/viewer/public/config/default.js` file, or the `app-config.js` file in the built output for the solution. Eventually we want these values to be in-app configurable.

**Comment by Malik-Adil** [comment]
> I don't understand your questions, @lizwxup. The same questions I asked @Malik-Adil apply. I need more information in order to assist you.

After Clone the Viewer it give us the full repo But i need only use the viewer inside the platform folder.  when I extract form platform folder then it gives error due to missing configuration.
