### ISSUE TITLE
WADO Proxy error when loading images

### ISSUE THREAD

**Issue by xhli3028** [OHIF/Viewers#133]
Hi,

Just installed and ran OHIF standalone viewer, study list and metadata were returned by the remote dicomweb server fine, but when double-clicked to open a study go the following error:

An error has occurred while loading image: dicomweb:http://localhost:3000/__wado_proxy?url=http%3A%2F%2Flocalhost%2Fpacsone%2Fwadouri%3FrequestType%3DWADO%26study
UID%3D1.2.840.113674.514.212.200%26seriesUID%3D1.2.840.113674.514.212.82.300%00%26objectUID%3D1.2.840.113674.950809132337081.100%26contentType%3Dapplication%252Fdicom%26transferSyntax%3D*&serverId=x2fcTfSkzkhMuauKN

I checked the Apache/httpd access log but there was no incoming request with the above WADOURI "http://localhost/pacsone/wadouri?requestType=WADO&studyUID=xxx", so it seems the problem was with the WADO proxy? Was there any configuration setting that needs to be enabled in the "Option->Server Information" menu?

Thank you.

**Comment by xhli3028** [comment]
After enabling Loggin Responses, the Windows Powershell displayed the following additional information about the error:

**W20171116-10:33:48.639(-8)? (STDERR) TypeError: Request path contains unescaped characters**

It seems like the "*" wildcard character "transferSyntax=*" URL parameter was not escaped? But where was that parameter appended to the WADOURI string?

**Comment by swederik** [comment]
Looks like here? https://github.com/OHIF/Viewers/blob/315ec935d945770115bb9809e7cef1f55a1be3b3/Packages/ohif-studies/imports/server/services/wado/retrieveMetadata.js#L67

**Comment by xhli3028** [comment]
Bingo!

Once I remove Line 67 and rebuild, the images can now be loaded successfully. I also noticed another bug in the line above it (Line 65) within the same function:

`65          params.push('contentType=application%2Fdicom');`

The output URL passed to the WADO proxy was "**contentType%3Dapplication%252Fdicom**", with the "%2F" escape code escaped/encoded again.
