### ISSUE TITLE
there is any possibility to use our server images i want to access our server image so please help where i need to set configurations in the react js

### ISSUE THREAD

**Issue by shubhamvishwakarma19** [OHIF/Viewers#1331]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by dannyrb** [comment]
@shubhamvishwakarma19, what have you tried? Where are you getting stuck? Have you read through our readme and documentation? ( https://docs.ohif.org )

**Comment by shubhamvishwakarma19** [comment]
I have clone that repo https://github.com/OHIF/Viewers/tree/master/platform/viewer
i want to integrate the our dicom images . where i need to set configuration i had change in the some files default.js and other files getting some issue so please guide me where i can put my all dicom image  url which i want to show.

**Comment by dannyrb** [comment]
Are you able to see images from the default test server? If so, you have a few options:

- Use `/local`
- Mimic the DICOMWeb endpoints
- Use the Standalone JSON query parameter
- Help add support for something more robust

I'm on my phone so I can't provide any links, but you should be able to find similar issues with each of these solutions detailed.

**Comment by nenadfemic** [comment]
> 
> 
> Are you able to see images from the default test server? If so, you have a few options:
> 
>     * Use `/local`
> 
>     * Mimic the DICOMWeb endpoints
> 
>     * Use the Standalone JSON query parameter
> 
>     * Help add support for something more robust
> 
> 
> I'm on my phone so I can't provide any links, but you should be able to find similar issues with each of these solutions detailed.

Hi danny,

I can get localy files using http://localhost:3000/local, but is it possible  
when run http://localhost:3000 to load directly local dicomm images without using url above and 
Drag and Drop DICOM files.

I would like to load local diccom file directly as list in application, i guess that need to modify this a part of code, but not so skilled to fit this

 dicomWeb: [
      {
        name: 'DCM4CHEE',
        wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado',
        qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,

Can y help me, what exactly need to modify and point on my local dicom folder.

Thansk in advance

**Comment by dannyrb** [comment]
@nenadfemic, I have responded to your other issues. Please do not ask new questions on old/stale issues.
