### ISSUE TITLE
What do I wrong when I can´t compose Docker in my Terminal?

### ISSUE THREAD

**Issue by bizhub1** [OHIF/Viewers#1336]
> :hand: ERROR with Docker by command "docker-compose up --build" in Terminal
> What do I wrong when I can´t compose Docker in my Terminal?

I can´t help myself because sometimes it works but sometimes not.

I´m new to coding and bought Nick Janetakis course "build-a-saas-app-with-flask"
But sometimes when I try to use this command -->docker-compose up --build

**I get this ERROR:** 

ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**But why?**
That is the DockerBug report code:
36322EA6-F00F-4E81-B1C5-47F0C376A059/20191228181745

Maybe somebody can explain me why:)

**Comment by sedghi** [comment]
Can you check our latest docker documentation and re-open the issue if still it happens

https://docs.ohif.org/deployment/docker
