### ISSUE TITLE
Bug Standalone Viewer on CT Study - Switch first and middle instance of each series

### ISSUE THREAD

**Issue by Boukenty** [OHIF/Viewers#134]
Hello,

i'm using standalone viewer with python script launcher and json file for view CT study.

First and middle image of each series is inversed... maybe my json file is bad 

Here join the file
[test.zip](https://github.com/OHIF/Viewers/files/1481870/test.zip)

Thanks in advance for help.

**Comment by swederik** [comment]
Hi there,

Thanks for the report! I'm not sure when we will get to this. Anyone else using the standalone viewer having this problem? @richsmith123?

**Comment by Boukenty** [comment]
The first image viewed is same than the icon serie in left menu (probably for don't view black image at the CT series beginning)

**Comment by richsmith123** [comment]
Hello there,  I'm not experiencing the issue in Standalone viewer.  I'm not
using the latest code though!

**Comment by Zaid-Safadi** [comment]
@Boukenty, feel free to upload your image to the online viewer here and see if the problem exists:
http://dicomweb.azurewebsites.net/

**Comment by Boukenty** [comment]
@Zaid-Safadi study is too large for upload ...

**Comment by Boukenty** [comment]
@swederik I send you by mail an url with application and CT study.

**Comment by franzronan** [comment]
I fix mine by including the Instance Number (0020,0013) in the returned json.

**Comment by Boukenty** [comment]
It's ok for me, thank you.
