### ISSUE TITLE
why build a dist directory and i dont view a dicomviewer through a config url?? i should how to do

### ISSUE THREAD

**Issue by lizwxup** [OHIF/Viewers#1341]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by lizwxup** [comment]
so.... a dist directory contains a many files   is it right??

**Comment by dannyrb** [comment]
I'm sorry. I'm not sure I follow. Can you elaborate? Providing a detailed explanation of:

- What you are trying to accomplish
- Your attempted steps
- The result, versus your expected result

Would go a long way toward making it possible for me to provide guidance.

**Comment by lizwxup** [comment]
when i use 
`http://localhost/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/PTCTStudy.json`

![微信图片_20200102195711](https://user-images.githubusercontent.com/29390455/71666042-35db4f00-2d9a-11ea-9e83-6c8adaa4bca8.png)

**Comment by lizwxup** [comment]
![route](https://user-images.githubusercontent.com/29390455/71666065-4e4b6980-2d9a-11ea-8fab-c8b75485f540.png)

**Comment by lizwxup** [comment]
when i want to load standalone Routing through a "http://localhost/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/PTCTStudy.json",it occur 404 about nginx Server 
![route](https://user-images.githubusercontent.com/29390455/71666359-71c2e400-2d9b-11ea-9347-96cd99fd94ac.png)

nginx Server:
`
    server {
      listen       80;
      client_max_body_size 1024m;
      root         /usr/share/nginx/html;


      location / { 
           index index.html; 
           try_files $uri $uri/ /index.html; 
           add_header Cache-Control "no-store, no-cache, must-revalidate"; 
      } 
    }`

**Comment by dannyrb** [comment]
This means that `nginx` is not returning the OHIF/Viewer's `index.html`
