### ISSUE TITLE
Runtime server configuration

### ISSUE THREAD

**Issue by galelis** [OHIF/Viewers#1343]
### Feature description
We want to have the ability of changing our server configuration runtime, by manually adding server config and choose which on to use. 
This configuration should be stored into the app, it can use sessionStorage/localStorage.

The server configuration can only be a DICOMWeb server for now.

### User cases
As an user: 
- I should be able to create a new server config, activate it and have the current app using it. 
- I should be able to create multiple server configs and select the one of then to use in the app. 
- I should be able to delete a server configuration if we have more than 1 (we should always have one there)
- I should be able to see all configurations added after refresh the page and also make sure its persisted and the app is using the selected one. 

### Screenshots
These are screenshots from legacy version, newer version can be sligly different.
![Screen Shot 2020-01-02 at 17 19 03](https://user-images.githubusercontent.com/2378326/71690678-27823880-2d84-11ea-87a7-026b8fc31098.png)
![Screen Shot 2020-01-02 at 17 19 23](https://user-images.githubusercontent.com/2378326/71690685-2b15bf80-2d84-11ea-9482-ddcc1b5638a7.png)

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
