### ISSUE TITLE
Local viewer can query Orthanc PACS but does not load images

### ISSUE THREAD

**Issue by HenriqueSilva-al** [OHIF/Viewers#1344]
I am running an local Orthanc version 1.5.6 with dicom-web plugin version 0.6 and an nginx reverse proxy.

My yarn run dev is as follows:
"cross-env NODE_ENV=development PROXY_TARGET=/dicom-web PROXY_DOMAIN=http://localhost:4000  webpack-dev-server --config .webpack/webpack.pwa.js --watch"

My nginx will reverse proxy the requests on port 4000 to my orthanc port, that works fine and I manage to load the studies into the viewer, but I can't load the images as I get these errors
![image](https://user-images.githubusercontent.com/59484994/71742037-34b02d80-2e3f-11ea-8857-1d7399cac1a6.png)

**Comment by dannyrb** [comment]
It looks like your image requests are taking place over port `3000`? What does your application configuration look like? Your NGINX Config?

**Comment by HenriqueSilva-al** [comment]
This is the config on default.js
```
routerBasename: '/',
  whiteLabelling: {},
  extensions: [],
  showStudyList: true,
  filterQueryParam: false,
  servers: {
    WebDicom: [
      {
        name: 'ORTHANC',
        wadoUriRoot: '/wado',
        qidoRoot: '/dicom-web',
        wadoRoot: '/dicom-web',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
      },
    ],
  },

```
and this is my NGINX config

```
server {
        listen 4000;
        location / {
                proxy_pass http://127.0.0.1:8042/;
        }
}

```

just to redirect traffic on 4000 to the Orthanc port

**Comment by dannyrb** [comment]
Should these:

```
        wadoUriRoot: '/wado',
        qidoRoot: '/dicom-web',
        wadoRoot: '/dicom-web',
```

Be:

```
        wadoUriRoot: 'http://mystery-ip:4000/wado',
        qidoRoot: 'http://mystery-ip:4000/dicom-web',
        wadoRoot: 'http://mystery-ip:4000/dicom-web',
```

**Comment by HenriqueSilva-al** [comment]
Thanks I had some major configuration errors on my nginx, now my configuration files are as follow:

Default.js
```
  routerBasename: '/',
  whiteLabelling: {},
  extensions: [],
  showStudyList: true,
  filterQueryParam: false,
  servers: {
    WebDicom: [
      {
        name: 'ORTHANC',
        wadoUriRoot: 'http://172.19.0.121/orthanc/wado',
        qidoRoot: 'http://172.19.0.121/orthanc/dicom-web',
        wadoRoot: 'http://172.19.0.121/orthanc/dicom-web',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
      },
    ],
  },
```

NGINX

```
server {
   listen  80  default_server;
   location  /orthanc/  {
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow_Credentials' 'true';
                add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
                add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }
      proxy_pass http://127.0.0.1:8042;
      proxy_set_header HOST $host;
      proxy_set_header X-Real-IP $remote_addr;
      rewrite /orthanc(.*) $1 break;
      add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
      add_header 'Access-Control-Allow-Origin' '*';
   }
}
```

But I'm still getting this error when trying to load the images
![image](https://user-images.githubusercontent.com/59484994/71834871-02950a80-308f-11ea-8778-8de46e216feb.png)

**Comment by dannyrb** [comment]
Are you able to hit the URLs with a utility like Postman, or with simple GET requests in your browser? Do you have basic auth disabled?

**Comment by HenriqueSilva-al** [comment]
Ok so thanks for the responses and sorry for long time without commenting.

After separating the Orthanc and Viewer on different servers, building the latest version of Orhanc and dicom-web plugin I realized that I can't retrieve the images from 
`dicom-web/studies/{study-id}/series/{series-id}/instances/{instance-id}/frames/1`

as it returns me 400 Bad request.

But if I do curl that same URI but with `/rendered -H 'accept: image/png' ` at the end of it I can download the PNG for that instance.

**Comment by joweste** [comment]
Hi, did you solved It? I have the same problem.

**Comment by HenriqueSilva-al** [comment]
No, due to administration changes I postponed this project, but if you manage to solve it please do share.
