### ISSUE TITLE
Layout and Series Synchronisation features available or not?

### ISSUE THREAD

**Issue by jaizz2003** [OHIF/Viewers#1348]
I am trying to build new features in OHIF viewer like the layout as currently, it's 3x3, I want to ask is there a feature to customize it like 4x4 or something like that?
Also, I am trying to build a Synchronisation feature in which different series under the same study can be synchronized ( like we have 3 series and I want to scroll the images in all 3 at the same time) so I want to ask are these features already implemented?
If yes, Are they in v2 of OHIF viewer (as i don't see) and if not what is the best way to start?

**Comment by jaizz2003** [comment]
Regarding the Layout, Yes it is already implemented and we can extend the size of the grid to any size we want as OHIF viewers have this support and there is no support for series synchronization as much as I find so I am still stuck there.

**Comment by dannyrb** [comment]
Responded to the synchronization portion of your question here: https://github.com/cornerstonejs/cornerstoneTools/issues/1162
