### ISSUE TITLE
Button to reset viewports while the 2D MPR tool is active

### ISSUE THREAD

**Issue by luccascorrea** [OHIF/Viewers#1354]
## Request
Hi. First of all, thank you for this project! It is very well made and a truly great tool!

**What feature or change would you like to see made?**
The feature I'd like to request is for a new button to be added while the 2D MPR tool is active that would reset any changes made to the viewports using the WWWC, crosshair or rotate tools. I had a look at this and noticed that this would also require changes to the react-vtkjs-viewport dependency which is a bit out of my league so I decided to post this request here.

**Why should we prioritize this feature?**
This feature would improve the user experience while using the 2D MPR tool. I may be wrong but it seems like it would be relatively simple to implement.

**Comment by dannyrb** [comment]
Transitioning from request to a story. I think this is something we would like to see implemented and merged. @JamesAPetts may be able to provide guidance on an implementation he would be comfortable merging.

**Comment by igoroctaviano** [comment]
@JamesAPetts after we merge #2115 we can close this one?

**Comment by sedghi** [comment]
We have this implemented now in latest master branch, re-open the issue if that is not what you want
