### ISSUE TITLE
Some questions about data fetching and RAM usage in MPR++

### ISSUE THREAD

**Issue by Stormert** [OHIF/Viewers#1355]
Hi, 

We are working on customising this viewer with a couple of developers and have some questions regarding how the viewer is set up and about how data is fetched. We have fairly large image sets of about 600MB or about 1100-1500 CT images stored in Google cloud Healthcare API. 
Our workflow is usually to looking at multiple image sets one after the other in MPR view so to make this efficient we would like to preload the next study in a list while working on the first study.

- 	Using OHIF to view large studies the app uses a lot of RAM ( about 5 GB) in MPR view, which causes the app to be very slow, Is this a common problem? do we have any solution to make it use less RAM?
- 	As I mention before, we are fetching quite a lot of data from google’s healthcare Api, is there anyway we can optimise it? Like preload the data before clicking on a study, or fetching bulks of data instead of 1 at time. Or as google prefers , can we increase the number of parallel requests?
- 	Where in the code does the fetching happen? We tried to find it in the viewer application but we didn’t succeed. 
- 	Is there a way to make more than 1 list of studies? and possibly customise the query for the list 
 of study's sent to google? 
- I have seen issues about Length tool not existing on the VTK view, do you have any plans on developing this feature? Or Is there anyone from the community that is working on it?

**Comment by swederik** [comment]
Our team is pretty busy at the moment with [Project Week](https://projectweek.na-mic.org/PW33_2020_GranCanaria/) next week and this is a long list of questions, we'll try to get back to you on this soon.

**Comment by pieper** [comment]
Hi @Stormert  - is there any chance your developers would be willing to take on some of the things on our mutual wishlists?  Maybe they could participate in the project week events or similar to coordinate.

**Comment by Stormert** [comment]
Hi guys, unfortunatly our resources where moved off this project.

We did review of the viewer this week and tried to estimate what it would take to get it to a point where it could be used for our purposes and unfortunately some of the issues we ran into where show stoppers for us. 

Mainly the load times of MPR due to our large CT sets, we had hopes about working around this by using preloading several studies in the background. We did not get this to work properly in our test period due to high memory usage (one of our ct sets loaded into MPR view where using between 5-8GB of RAM). This was causing the browser to crash at times with just one set in memory so we deemed it unrealistic to be able to preload another one as it stand today and we where not able to uncover any obvious ways to reduce memory usage. 

Due to this we had to move our development resources momentary solution using a native app for now and will have to do another review of a web based solution at a later date.

**Comment by dannyrb** [comment]
@Stormert, if you venture this way again, please don't hesitate to reach out to better collaborate. We're investigating solutions to deliver the OHIF viewer as a cross-platform desktop app; our team has experience accomplishing this with viewers built on similar technology.

Having a real-world company/target/partner would help us focus our efforts.

I'm going to close this issue for now, but more than happy to discuss your questions when you do revisit. For collaborations, you can always reach me privately at danny.brown@radicalimaging.com
