### ISSUE TITLE
How to save oauth credentials?

### ISSUE THREAD

**Issue by fernandogbi** [OHIF/Viewers#1356]
Hi everyone !!!

I'm running OHIF Viewer with docker and all time i need log in with my gmail user that has my cloud healthcare project. Has any way to save my oauth credentials for don't need log in every time? Maybe using a database?

**Comment by sedghi** [comment]
You can use userAuthService in latest master

**Comment by niirdan** [comment]
Dealing with the same here , how to use the userAuthService ? anywhere in Docs ?

**Comment by MatheusRdk** [comment]
I also need to implement my own authentication with jwt token and login page. If anyone could give any advice I would be very grateful.
