### ISSUE TITLE
Integration or Redirection, in the ASP.NET application ?

### ISSUE THREAD

**Issue by hasanmansor** [OHIF/Viewers#136]
Hello Everyone, 

I have an ASP.NET webform application and I want to integrate the OHIF viewer into this application. Can anybody tell me whats the best way to integrate (either putting OHIF viewer directly in the ASP.NET solution or redirecting the ASP.NET webform to the standalone OHIF). I would really appreciate your help. 

Hasan

**Comment by swederik** [comment]
Hi Hasan,

I would guess that it would be easiest to use the standalone viewer in this case, but I'm not really sure. Anybody else have any ideas?

**Comment by Zaid-Safadi** [comment]
@hasanmansor , I believe the standalone viewer is the best option for integrating with an ASP.NET app unless you will run your own customized version of the full viewer. 

The standalone viewer now supports a url query parameter to retrieve the study (see issue #91)

I have implemented an example of this integration in the DICOMweb-js which you can see here: 
http://dicomweb.azurewebsites.net/

**Comment by hasanmansor** [comment]
Thank you @swederik and @Zaid-Safadi !

Yeah, it seems the better option to use the standalone viewer.
