### ISSUE TITLE
image file support

### ISSUE THREAD

**Issue by luohao110** [OHIF/Viewers#1364]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**
Can local upload support JPG BMP AVI? 
I tried it, but it didn't seem to work.

**Comment by dannyrb** [comment]
@luohao110, it does not currently. Support is limited to the transfer syntaxes covered by the cornerstone-wado-image-loader.

It is possible to add support for additional formats, but would require additional programming.

**Comment by luohao110** [comment]
Thank you. I see.

**Comment by swederik** [comment]
You can look into adding the https://github.com/cornerstonejs/cornerstoneWebImageLoader to support JPG and BMP.

**Comment by luohao110** [comment]
> You can look into adding the https://github.com/cornerstonejs/cornerstoneWebImageLoader to support JPG and BMP.

Hello, I need to use the existing toolbar. Is there a lot of work to do with such additional programming?
