### ISSUE TITLE
using a custom tool with multiple viewports

### ISSUE THREAD

**Issue by web2ls** [OHIF/Viewers#1365]
I'm trying to add a custom tool. It looks like the tool is working correctly
But the problem appears when I work with several viewports
if I select any other tool, then it works in the first viewport and my tool is disabled, but in my other viewports my custom tool continues to work
what actions need to be done so that my custom tool turns on and off correctly for all viewports

my example custom tool is simple as that

``` import csTools from 'cornerstone-tools';
const BaseTool = csTools.importInternal('base/BaseTool');

export default class MyTool extends BaseTool {
	constructor(
	  name = 'MyTool',
	  mixins = ["activeOrDisabledBinaryTool"],
	  supportedInteractionTypes = ['Mouse', 'Touch'],
	  configuration = {},
         ) {
		super({
			name,
			supportedInteractionTypes,
			configuration,
			mixins,
		});
	}

	preMouseDownCallback(event) {
		console.log('premousedown event calling');
		return true;
	}
}

**Comment by dannyrb** [comment]
How are you adding the tool to CornerstoneTools? When/how are you activating it?

It's nice to see someone using the cornerstone-tools custom tools API. If you can provide enough information to reproduce your issue on a vanilla OHIF build, I can help identify if this is a bug or expected behavior.

**Comment by sedghi** [comment]
I think it does makes sense for us to create documentation on how to create new tools. But meanwhile, we have couple of tools that you can inspire from. 

extensions/cornerstone-dicom-sr/src/tools/DICOMSRDisplayTool.ts
extensions/cornerstone/src/tools/ImageOverlayViewerTool.tsx
