### ISSUE TITLE
Optimize for Mobile Devices

### ISSUE THREAD

**Issue by avait1** [OHIF/Viewers#1366]
Hi Everyone,
First, thank you for this product, it is a really beautiful thing !
How can I to Optimize OHIF VIEWER for Mobile Devices ?

**Comment by dannyrb** [comment]
We are accepting pull requests for changes that improve our current layouts to be responsive. You can find an old check list here: https://github.com/OHIF/Viewers/issues/507

The majority of our UI Controls and Viewports already work well in a mobile context; our biggest issue are around simple layout responsiveness. If you're interested in contributing, I can help prioritize.
