### ISSUE TITLE
Deploying static files into Tomcat

### ISSUE THREAD

**Issue by Diegovictorbr** [OHIF/Viewers#1368]
I have a Tomcat folder called `ohif `where i want to deploy `platform/viewer/dist` content. However, OHIF is not able to find its static files. Here is a screenshot of what happens:

![72273401-0bdf2380-3609-11ea-8112-15bf266f71e0](https://user-images.githubusercontent.com/19496924/72286662-58842800-3624-11ea-82e3-2fd7496775d6.png)

Tomcat runs at http://149.56.20.137:17545 and i want to serve OHIF at http://149.56.20.137:17545/ohif

Ultimately what i want to do is connect OHIF with an Orthanc instance behind a NGINX reverse proxy. So the final result would be accessing OHIF at http://149.56.20.137:17000/ohif and Orthanc at http://149.56.20.137:17000/orthanc

The steps i used to generate static files:

1. `yarn config set workspaces-experimental true`
2. `yarn install`
3. `yarn run build`

Then i copied `platform/viewer/dist` content into `webapps/ohif` folder on Tomcat.

**Comment by Diegovictorbr** [comment]
By appending PUBLIC_URL=/ohif to the `build:viewer` script configuration on `platform/viewer/package.json` i was able to correct some dependencies, but some files are still missing:

![Sem título](https://user-images.githubusercontent.com/19496924/72289083-1a3d3780-3629-11ea-9740-5026f1046e47.png)

**Comment by Diegovictorbr** [comment]
Silly mistake. Changed `PUBLIC_URL=/ohif` to `PUBLIC_URL=/ohif/` and everything worked (including Orthanc behind NGINX)! :)

Here is the relevant platform/viewer/package.json relevant line for anyone wondering: 
![Sem título](https://user-images.githubusercontent.com/19496924/72290867-eebc4c00-362c-11ea-9f04-d0ca6993b408.png)

**Comment by Diegovictorbr** [comment]
Now what i am trying to understand is when i access http://149.56.20.137:17000/ohif/, OHIF shows this screen:

![Sem título](https://user-images.githubusercontent.com/19496924/72292281-d7329280-362f-11ea-8504-9bb39ec58a47.png)

If i click on go back, i can see the list connected to Orthanc showing everything as expected, but the browser URL changes to http://149.56.20.137:17000/

**Comment by dannyrb** [comment]
Awesome! That's great to hear. We should probably auto-append the trailing slash if it's not there. I can't think of a scenario where you wouldn't apply it. :thinking: 

Another common "gotcha" are the SPA redirect rules that allow direct linking to specific studies. You may want to make sure you have those in place.

If all has been resolved, feel free to close this issue. Please don't hesitate to create a new issue, or PR document or code changes to help others with lessons you learned along the way.
