### ISSUE TITLE
Improved user experience while handling fractional SEG

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1369]
> **Before Creating an issue**
>
> - Are you running the latest version?

No, this is tested with 3.3.7.

> - Are you reporting to the correct repository?

I think so.

> - Did you search existing issues?

Yes, the closest related issue is this https://github.com/OHIF/Viewers/issues/1346, but the present issue not about support of fractional segmentation, but about another (hopefully, easier) issue about reporting to the user that fractional segmentation is currently not supported.

## Bug Report

Dragging SEG series 52001 "Breast Tissue Segmentation" into the viewer does not result in segmentation rendering, and does not produce any hints to the user as to why.

The same series shows up in the latest stable version of Slicer 4.10.2 with the Quantitative Reporting extension installed as shown below: 

![image](https://user-images.githubusercontent.com/313942/72286359-02f34f80-3613-11ea-9440-82412b000e76.png)

### Describe the Bug

Segmentation series does not show in the viewer, and it is not clear why.

### What steps can we follow to reproduce the bug?

1. Open this link: https://idc-sandbox-000.firebaseapp.com/projects/chc-tcia/locations/us-central1/datasets/ispy1/dicomStores/ispy1/study/1.3.6.1.4.1.14519.5.2.1.7695.1700.301904873570071685223271646148
2. Drag series 102001 into the viewer - nothing happens. Looking at the developer console, there is the error below:

![image](https://user-images.githubusercontent.com/313942/72286448-2a4a1c80-3613-11ea-8e72-785616ff07b2.png)

### Suggestion for improvement of the functionality

I suggest it would be helpful if there was some more clear way of communicating to the user if certain functionality is not supported. In this case, even from the developer console it is not clear if fractional segmentations are supported or not (but it is alluded to in another thread that they are not #1346).

After completing this issue report, I realized that this is observed in 3.3.7, which is what is used on IDC sandbox, and not the latest 3.3.8. It might be that the latest version behaves differently.

**Comment by fedorov** [comment]
@pieper updated the IDC sandbox, and I confirm the issue remains in 3.3.8.

**Comment by fedorov** [comment]
Based on some discussions about this, one idea could be the following:
1) show every single series in the left column of the interface (including SEG etc)
2) when study is received, identify series that are not supported
3) mark series that are not supported with an exclamation mark or something like that

**Comment by Punzo** [comment]
this has been implemented in the context of series warning UI
