### ISSUE TITLE
Not able to save and retrieve label description in LesionTrackerTool

### ISSUE THREAD

**Issue by shtl23** [OHIF/Viewers#137]
In the lesiontracker tools(target tool, ie. bidirectional tool) after adding label and the description in these tools, I am not able to see the description (which is the free text)

**Comment by swederik** [comment]
Hi there,

Sorry about that. This is a known issue which will be addressed soon.

Thanks!

**Comment by dannyrb** [comment]
Unfortunately this issue has grown stale, and with the release of our most recent major version, it is unlikely that we will have the bandwidth to address this issue for our `v1.x` branch. 

If you find that this feature has not yet been implemented in our `master` branch, you are more than welcome to create a [GitHub Issue](https://github.com/OHIF/Viewers/issues/new) to request or discuss it. If you're curious to see what we have planned in the near future, you can [check out our roadmap](https://ohif.canny.io/), and [read our docs](https://docs.ohif.org/).
