### ISSUE TITLE
Viewer config ignored

### ISSUE THREAD

**Issue by knopkem** [OHIF/Viewers#1374]
Hi,
I did not specify this as a bug, as I'm sure I must be doing something wrong. I did read the docs though and still stuck.
Here is the issue:
* I've setup a local server, serving the prebuild (from unpkg) index.html and app-config.js (latest version 3.4.0)
* No matter what I change in app-config.js server section, always the default DCM4CHEE server is used (pointing to https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs)
* however the app-config is in use: console: window.config.servers["dicomWeb"][0] shows my custom end-points.
* also changing (for testing) the showStudyList to false disables the viewer (so the config is indeed active)
config looks like this:
`dicomWeb: [
      {
        name: 'DCM4CHEE',
        wadoUriRoot: 'http://localhost:8899/wado',
        qidoRoot: 'http://localhost:8899/rs',
        wadoRoot: 'http://localhost:8899/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
      },
    ],`
Any help would be much appreciated.

**Comment by swederik** [comment]
I ran into an issue like this with the Google Cloud adapter and in that case it was because data was being stored in localStorage. Could you try clearing that?

I'm not sure why this would happen. Maybe @dannyrb or @igoroctaviano can shed some light on how configuration information makes it into Redux / Context.

**Comment by knopkem** [comment]
It was stored in session storage (I guess this is intended behavior), so changing config without restarting the browser won't work. Thanks Erik for the tip, should have found this myself.

**Comment by swederik** [comment]
Ugh, right yeah OK that sounds familiar. If this is intended behaviour it should be documented somewhere.

**Comment by dannyrb** [comment]
It is not intended. I believe there is some accidental caching happening either with our global redux listener or as a part of some hotkeys logic. Either way, I don't see the value in tossing all of the app config in local storage -- it only creates issues like this.

More than happy to accept a PR to address this issue.

**Comment by Diegovictorbr** [comment]
> Was this closed because of inactivity? I'm also hitting this issue and even though I can't provide a fix, I think it'd be better to keep this one open in case someone wants to and can fix it.
> 
> Anyways, my dirty workaround was to put a `sessionStorage.clear();` line at the beginning of the app config js file to make sure that updated config values will always take effect.

Indeed, you can clear the sessionStorage as it holds a `state` object for OHIF usage. But I recommend using

`sessionStorage.removeItem('state');`

To delete specifically what you need instead of the entire sessionStorage object.
