### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined when using @ohif/core

### ISSUE THREAD

**Issue by fexman** [OHIF/Viewers#1376]
Hey,

For an Angular project of mine I try to use @ohif/core to make use of wado/qido services. I'm on the latest version `"@ohif/core": "2.3.2"`. When trying to start up my client I always run into the following runtime exception, when trying to import `import { studies as ohifQido } from '@ohif/core'`:

> ReferenceError: regeneratorRuntime is not defined 
>    at node_modules/@ohif/core/dist/index.umd.js:2:4961961
>    at Module.<anonymous> (node_modules/@ohif/core/dist/index.umd.js:2:4962398)
>    at i (node_modules/@ohif/core/dist/index.umd.js:2:332)
>    at node_modules/@ohif/core/dist/index.umd.js:2:1131
>    at node_modules/@ohif/core/dist/index.umd.js:2:1142
>    at node_modules/@ohif/core/dist/index.umd.js:2:81
>    at Object.<anonymous> (node_modules/@ohif/core/dist/index.umd.js:2:197)

I've seen that there already has been an issue with that, that should have been fixed in Sept 2019: https://github.com/OHIF/Viewers/pull/902. Yet, it's not working for me! Any help with that?

**Comment by dannyrb** [comment]
Are you using the monorepo or the `@ohif/core` package in a different project? Are you consuming the dependency from source, or es5?

**Comment by fexman** [comment]
Ive added the dependency via `npm i @ohif/core --save-exact `as mentioned here: https://github.com/OHIF/Viewers/tree/master/platform/core. Then I'm just referencing `@ohif/core` as menitoned above in a TypeScript file.

**Comment by fexman** [comment]
I've just created a clean, new Angular project and only added the @ohif/core dependency. When referencing `import { studies } from '@ohif/core';` in the generated app.component.ts, I face the same issue.

**Comment by dannyrb** [comment]
We primarily consume @ohif/core via our monorepo and from source. This means that we transpile and bundle it. 

It's likely that our "packaged" build does not include regeneratorRuntime (I think this is used for async/await). It may work if you include it globally. If it does, then we need to note as much in @ohif/core. If it does not, then our packaged build for @ohif/core has a bug.

**Comment by dannyrb** [comment]
@fexman, were you able to investigate alternative solutions or identify the culprit of your issue?
