### ISSUE TITLE
[Measurement Panel] Delete button is not displayed when Spanish language is selected

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1377]
### Describe the Bug

PR #1352 found that `delete` button was not visible under Measurement Panel.

The `delete` button is now visible, but if user changes the language preferences to Spanish, the `delete` button will disappear. Please check images below for reference:

**English language selected:**
<img width="411" alt="bug1 - no delete button" src="https://user-images.githubusercontent.com/13245529/72437351-508dca80-3781-11ea-8fe1-c16052406a0b.png">

**Spanish language selected:**
<img width="409" alt="bug1 - delete button" src="https://user-images.githubusercontent.com/13245529/72437370-58e60580-3781-11ea-831f-9e245efbcf00.png">

### Steps to Reproduce:

1. Load any Patient Study
2. Add Length annotations
3. Click on "Measurements" button to open the panel
4. Verify that `Delete` button is displayed
5. Click on "Options" at the top right of the screen
6. Select "Preferences" and click on "General" tab
7. Select Spanish Language and Save
8. Check again the Measurements Panel and verify that the `Delete` is not visible anymore.

### Expected Result:

1. `Delete` button should always be displayed, no matter which language was selected.

**Comment by dannyrb** [comment]
We appear to have an issue where the actions hide  if they exceed the set width.

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
