### ISSUE TITLE
Open viewer at specific URL (study) when hosting static files on Tomcat

### ISSUE THREAD

**Issue by Diegovictorbr** [OHIF/Viewers#1378]
I have deployed OHIF static files on Tomcat inside webapps/ohif folder. I changed PUBLIC_URL and routerBasename to `/ohif/` to match the URL and Everything is working fine. 

The only problem is that when i try to open specific OHIF URLs (for example a study), Tomcat returns 404. However, when i run OHIF locally, i can open specific URLs. For example:

http://149.56.20.137:17000/ohif/ -> Works fine
http://149.56.20.137:17000/ohif/viewer/1.2.392.200036.9116.2.2.2.1762671362.1578986208.521930 -> 404 from Tomcat

Is that something related to Tomcat?

**Comment by dannyrb** [comment]
See: https://stackoverflow.com/questions/41246261/react-routing-is-able-to-handle-different-url-path-but-tomcat-returns-404-not-av

Sometimes referred to as SPA (single page app) routing.

**Comment by Diegovictorbr** [comment]
Thanks Danny! Here is what i did to open a specific URL:

Create a `WEB-INF` folder on `webapps/ohif/` with two files:

**rewrite.config**:
```
RewriteCond %{SERVLET_PATH} !-f
RewriteRule ^/ohif(.*)$    /index.html [L]
```
**web.xml**:
```
<!DOCTYPE web-app PUBLIC
 "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
 "http://java.sun.com/dtd/web-app_2_3.dtd">
<web-app>
    <display-name>My Angular Application</display-name>
    <welcome-file-list>
        <welcome-file>index.html</welcome-file>
    </welcome-file-list>

    <error-page>
        <error-code>404</error-code>
        <location>/index.html</location>
    </error-page>

    <error-page>
        <error-code>410</error-code>
        <location>/index.html</location>
    </error-page>
</web-app>
```

This is it! Everything works, and visualizing a specific study from Orthanc is much faster than searching through the home page (not OHIF's fault) 🎉🔥⚡️

**Comment by naimatamaan** [comment]
hi,

i have shared a details video link in below where to guide how to setup a static viewer of ohif on custom domain or any domain 

[https://www.youtube.com/watch?v=tvA2jdBLLtc](url)
