### ISSUE TITLE
Does ohif support video (dicom format)?

### ISSUE THREAD

**Issue by IIAT-MR-LW** [OHIF/Viewers#1380]
Does OHIF support video (dicom format)? 

I downloaded video (dicom format) from https://demo.softneta.com/md5/index.html?study=1.2.826.0.1.3680043.8.1055.1.2019021915646791.694729768.59014658&storage=ORTHANC

This the product of MedDream that is based on OHIF viewer. I found that MedDream can support the video(dicom format). 
![image](https://user-images.githubusercontent.com/52825694/72617187-695dd200-3973-11ea-9f70-019948a63298.png)

I wonder that how to add this function to make OHIF viewer support the video.

**Comment by dannyrb** [comment]
It does not. However, you could duplicate the DICOM HTML or DICOM PDF extension and add support in a similar manner.
