### ISSUE TITLE
How can I enable MPR?

### ISSUE THREAD

**Issue by DANIELMWAMBI** [OHIF/Viewers#1385]
Which values should i add to my results so that I can enable MPR?
Thanks in advance 
![viewer json](https://user-images.githubusercontent.com/7789532/72669360-ddff4200-3a41-11ea-8574-a75a0f549166.png)

**Comment by dannyrb** [comment]
I believe I saw a related issue by you on the DICOM Cloud repo that @Zaid-Safadi maintains? At a minimum, the fields called out in this function:

https://github.com/OHIF/Viewers/blob/460e375f0aa75d35f7a46b4d48e6cc706019956d/platform/core/src/utils/isDisplaySetReconstructable.js

If those are provided and you're still experiencing issues, we have an internal document that details all the fields we use for DICOMWeb calls that I can dig up. Anything missing that's crucial for MPR should likely be added to that function (or we should explore better ways to indicate feature dependence on specific tags).
