### ISSUE TITLE
Clean up JSON launch with DICOMWeb server

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1387]
"Standalone routing" provides the ability to launch the OHIF Viewer with a JSON file which points to a DICOM Web server as well as a list of study and series instance UIDs.

An example would look like this:
`http://localhost:3000/viewer?url=http://localhost:3000/testRemoteServer.json&studyInstanceUids=2.16.840.1.113669.632.20.121711.10000158860`

If you add a JSON file named testRemoteServer.json into platform/viewer/public: 

```json
{
   "servers": {
      "dicomWeb": [
         {
            "name": "DCM4CHEE",
            "wadoUriRoot": "https://demo.kheops.online/api/link/ye2BvvlkzbX9YdU5XaJ9b0/wado",
            "qidoRoot": "https://demo.kheops.online/api/link/ye2BvvlkzbX9YdU5XaJ9b0",
            "wadoRoot": "https://demo.kheops.online/api/link/ye2BvvlkzbX9YdU5XaJ9b0",
            "qidoSupportsIncludeField": true,
            "imageRendering": "wadouri",
            "thumbnailRendering": "wadouri",
            "enableStudyLazyLoad": true
         }
      ]
   }
}
```

Right now this calls retrieveStudyMetadata and then provides the result, after the promise resolves, to ConnectedViewer. Instead of this behaviour, it should provide the list of study and series instance UIDs to the [ConnectedViewerRetrieveStudyData](https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/connectedComponents/ConnectedViewerRetrieveStudyData.js) component, which handles this logic internally already.

Essentially you need to remove these lines:
https://github.com/OHIF/Viewers/blob/1d02f5485f39efbe905c642f0c63037a0b5dc604/platform/viewer/src/routes/StandaloneRouting.js#L61-L75

and instead set the studyInstanceUids and seriesInstanceUids state inside the StandaloneRouting component and pass this state into ConnectedViewerRetrieveStudyData in the render function.

This should only happen if this condition is true `data.servers && query.studyInstanceUids` (see https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/routes/StandaloneRouting.js#L57).

**Comment by sgala** [comment]
Note: after this commit it *mostly* works, but I have seen a problem:

If I go to 

`http://myserver/viewer?url=http://myserver/testRemoteServer.json&studyInstanceUids=Uid1`

it works, but if I then click the "Measurements" button, a black screen ensuits. The error in console is:  **TypeError: "activeServer is undefined"**

**Comment by swederik** [comment]
Thanks for the report! @spalte did you encounter this?

**Comment by spalte** [comment]
I have not, but we have not moved our OHIF code since ProjectWeek. I do not have this issue with the [branch](OsiriX-Foundation/Viewers/tree/projectweek) we hacked together then.

**Comment by cmcfadden** [comment]
Haven't read up on how you prefer to get fixes for this project yet, but I resolved this issue in https://github.com/cmcfadden/Viewers/commit/915b4f09392ac1585d126229195e5f95ad7eba1b by checking if activeServers is set and returning null if not.  All the places that use the saveFunction check for it being null, so this seems safe?

**Comment by sedghi** [comment]
@igoroctaviano why did you add awaiting reproduction recently? Is this still an issue?

**Comment by sedghi** [comment]
@igoroctaviano can you please check this?

**Comment by igoroctaviano** [comment]
@sedghi this is v2 and its probably staled by now. Feel free to close it.
