### ISSUE TITLE
Meteor 1.6 problem

### ISSUE THREAD

**Issue by jonasscherer** [OHIF/Viewers#139]
Hi,
I'm trying to dockerize the OHIF Viewer.
I successfully created a build, but when I launch the bundle, I get this error:
```
build/bundle/programs/server/boot.js:50
    const { pause } = require("./debug.js");
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
...

```
I'm using Meteor 1.6 and it seems to be related to this version.
Can somebody give me a hint or  is there already a OHIF docker image?
Thanks!

**Comment by sunbiz** [comment]
Any solution to this?

**Comment by davidi1** [comment]
I had this issue when I tried to install this on Ubuntu Server 16.04. After some trial error and searching for a solution, I decided to wipe the system and install Ubuntu Server 17.10. Once I moved to Ubuntu 17.10, everything installed and worked just fine. Not exactly sure why it did not work on Ubuntu 16.04.

**Comment by swederik** [comment]
Not sure why this existed, but it doesn't appear to occur any longer, so I'll close it.
