### ISSUE TITLE
Exams with modality SEG/MR/DOC/SR

### ISSUE THREAD

**Issue by renataakhm** [OHIF/Viewers#1390]
Hi! On the demo we can see lots of exams that include not only image but also DOC attribute. We desperately need recreate dcm file with the same attributes but could have found any resource describing how it actually works. We would really appreciate if you could explain the structure of that kind of document and/or send one of this docs to us. Thank you very much in advance!

**Comment by pieper** [comment]
All of that data is according to [the dicom standard](https://www.dicomstandard.org/), at least as close as we can get.

**Comment by swederik** [comment]
I believe those DOC were made with pdf2dcm from dcmtk:
https://support.dcmtk.org/docs/pdf2dcm.html

**Comment by renataakhm** [comment]
Thanks for a quick reply! I've recreated dcm file using the library you've mentioned. I've copied the data about examination from existing dcm document (checked, can see modalities and other things) but when I open it in the viewer only PDF file is shown (without exams images itself). Maybe I don't completely understand the structure of the dicom files you have in demo? Maybe there are a packages that include directories with several dicom files (one of them with image, another with pdf) ?

**Comment by wiekern** [comment]
An example will be very pleased, I have the same trouble here. If I have a label map (2D/3D) of segmentation in numpy array, how could I pack it into a dicom file that is a standard dicom seg, e.g. which attributes in dicom seg I must provide. I have been working on it.

**Comment by fedorov** [comment]
>  If I have a label map (2D/3D) of segmentation in numpy array, how could I pack it into a dicom file that is a standard dicom seg, e.g. which attributes in dicom seg I must provide.

This notebook may be helpful:

https://github.com/RSNA/AI-Deep-Learning-Lab-2021/blob/main/sessions/dicom-seg/RSNA_2021_DICOM_IN_DICOM_OUT_Segmentation.ipynb

**Comment by wiekern** [comment]
Thanks! I wrote a simple solution in python. https://github.com/razorx89/pydicom-seg/issues/42
