### ISSUE TITLE
Images are not loading when image type is DERIVED\SECONDARY\SCREEN SAVE

### ISSUE THREAD

**Issue by chiragmalaviya** [OHIF/Viewers#1394]
I have integrated OHIF viewer with Orthanc in backend and facing image loading issue while loading the study with multiple series. The viewer gives error in console for updating the state of the unmounted component, which is stopping the execution. Adding the error I am getting as below.

```js
backend.js:6 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in AsyncComponent (created by ViewportGrid)
    in div (created by ViewportPane)
    in ViewportPane (created by ViewportGrid)
    in div (created by ViewportGrid)
    in ViewportGrid (created by ConnectFunction)
    in ConnectFunction (created by ViewerMain)
    in div (created by ViewerMain)
    in ViewerMain (created by ConnectFunction)
    in ConnectFunction (created by Viewer)
    in div (created by Viewer)
    in div (created by Viewer)
    in Viewer (created by WrappedComponent)
    in WrappedComponent (created by ConnectFunction)
    in ConnectFunction (created by ViewerRetrieveStudyData)
```

**Comment by dannyrb** [comment]
Can you provide a minimal reproduction? Issues like this can be difficult to troubleshoot with an error message.

**Comment by chiragmalaviya** [comment]
Ok, here I am attaching the zip file of the sample dicom files, You can upload in your orthanc server and can move forward to the reproduction of the issue, also one thing i have figured out, this is happening when viewer starts requesting instances before the series metadata is loaded completely.
[Sample Dicom.zip](https://github.com/OHIF/Viewers/files/4117814/Sample.Dicom.zip)

**Comment by chiragmalaviya** [comment]
@dannyrb Have tried with the given file ?

**Comment by dannyrb** [comment]
@chiragmalaviya, it may be a while. I've been out on leave and have a backlog of issues. I can test this quicker and more reliably if you can setup a reproduction w/ docker. Otherwise, it'll have to wait until I have a good chunk of time.

**Comment by cfirdous** [comment]
Hi @dannyrb , 
I work with Chirag and familiar with the issue . As Chirag mentioned , we feel it is happening when there are multiple series ,   and  image fetch getting triggered before meta data fetch is completed . It could be an out of order issue with asynchronous  processing .
To make your reproduction easier, we can give below given url which directly opens a patient with multiple series .
Viewer is NOT working for below given patient (The one mentioned in the bug . We also feel the issue random and sometimes the viewer works for the same patient if we retry)
http://3.6.87.143:3000/viewer/1.2.840.113619.2.312.4120.8416133.17092.1528192786.492
Viewer is working for below given patient (Most of the time )
http://3.6.87.143:3000/viewer/1.2.840.113619.2.312.4120.8416133.17092.1528192786.964

Hope you should be able to play around and debug with chrome dev tools .

**Comment by cfirdous** [comment]
You should be able to see all patients here
http://3.6.87.143:3000/

**Comment by cfirdous** [comment]
@dannyrb , We analyzed multiple patient studies and found that there is a pattern . It is not a random issue as we thought before . This issue happens only when the series contains of dicom files with image type =`DERIVED\SECONDARY\SCREEN SAVE`  . Also all other series are getting loaded properly when we delete the docm files with image type=`DERIVED\SECONDARY\SCREEN SAVE' .  That again proves our theory . Even if you don't have time to fix the issue, any direction  you give will be helpful . ( e.g : files or modules we can analyze or some other tricks to figure out why it fails with DERIVED\SECONDARY\SCREEN SAVE\ ) . Waiting for your reply

**Comment by dannyrb** [comment]
Ah. So the issue is that it doesn't include the original modality? It's possible we're doing some filtering when creating the display sets if the series/image does not contain a modality in a whitelist. Do you have an anonymized study we could use to reproduce?

Any steps you can detail out would be helpful. I can't guarantee we have the bandwidth to address it, but a community member who does may be able to run with the information you provide and draft a PR.

**Comment by cfirdous** [comment]
@dannyrb 
We think we found the exact issue . We noticed that  the series with DERIVED\SECONDARY\SCREEN SAVE images have a different SOPClassUID than other series under the same study  . Inside OHIF code , StudyMetadata.js file  , _getDisplaySetFromSopClassModule function has below given line .

```
 // TODO: For now only use the plugins if all instances have the same sopClassUid
  if (sopClassUids.length !== 1) {
    console.warn(
      'getDisplaySetFromSopClassPlugin: More than one SOPClassUid in the same series is not yet supported.'
    );
    return;
  }
```

This explains why viewer was not working for our case .  We are learning and getting familiar with OHIF code . If you think if it's something a newbie can fix , you can give some direction and we can try .

**Comment by chsasank** [comment]
I can confirm that this happens even when IMAGETYPE is `DERIVED\PRIMARY\LOCALIZER\CT_SOM5 MPR`

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

Feel free to reopen when you have the data
