### ISSUE TITLE
How to include an authorization header in the standalone viewer parameters?

### ISSUE THREAD

**Issue by Zaid-Safadi** [OHIF/Viewers#140]
Currently you can load a study in the standalone viewer by providing a URL query parameter. 

How can an authorization header be included in the request for:
1. The JSON study in the query url parameter
2. The DICOM images described in the JSON study

**Comment by diaztula** [comment]
Hello Zaid

> The JSON study in the query url parameter

You can do somethig like this: `oReq.setRequestHeader('header-name', headerValue);` before calling `oReq.send`.

> The DICOM images described in the JSON study

You have to configure cornerstoneWADOImageLoader, see this link: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/bb8d9777ccc91de5daaaae2d478e1f14482159ec/examples/wadors/index.html#L94

Something like this worked for me (in the routes.js file):

`
import { cornerstoneWADOImageLoader } from 'meteor/ohif:cornerstone';
`

Then somewhere before rendering the study:

`
cornerstoneWADOImageLoader.configure({
  beforeSend: function(xhr) {
    // Add custom headers here (e.g. auth tokens)
    xhr.setRequestHeader('header-name', headerValue);
  }
});
`

Cheers

**Comment by Zaid-Safadi** [comment]
Thanks @diaztula , this makes sense. I'm wondering what is the best way to support this in the standalone viewer with the URL parameter. 

For example, the authorization token could be sent in the query parameters just as the URL parameter, which can be used for loading the JSON study data. Then either 1) sore this token value and use it when loading the images later on, or 2) send the authorization token as part of the JSON data to load the images.

Best!

**Comment by diaztula** [comment]
In the standalone viewer I'm passing the token as a query paremeter. Then I get the token and pass it to the metadata request and to all wadoImageLoader calls.

`Router.route('/:id?', {`

     onRun: function() {
            ...
            if (this.params.query.token) {
                token = this.params.query.token;
                oReq.setRequestHeader('access-token', token);
                cornerstoneWADOImageLoader.configure({
                    beforeSend: function(xhr) {
                        // Add custom headers here (e.g. auth tokens)
                        xhr.setRequestHeader('access-token', token);
                    }
                });
            }
            // Fire the request to the server
            oReq.send();`

Not sure whether this is the best practice (passing the token as a query parameter) but it's working!
