### ISSUE TITLE
Missing 2DMPR menu in the toolbar or MR study, when loaded images using standalone JSON format

### ISSUE THREAD

**Issue by nagarjunaa** [OHIF/Viewers#1405]
Hi
 I have loaded the images using http endpoint, Maping the data to our standalone JSON format in this case I miss the 2DMPR menu in the toolbar, for the same images in the ohif viewer I am getting it. whether I am missing any element or tag in the json. please guide me in this
my json format is
{
"transactionId": "BRAIN SELLA",
  "studies": [
    {
      "studyInstanceUid": "1.2.840.113619.2.5.1762583153.215519.978957063.78",
      "studyDescription": "BRAIN SELLA",
      "studyDate": "20140720",
      "studyTime": "120022",
      "patientName": "Image1^Test",
      "patientBirthDate": "",
      "patientId": "93840",
      "patientSex": "",
      "seriesList": [
{
          "seriesDescription": "SAG T-1",
          "seriesInstanceUid": "1.2.840.113619.2.5.1762583153.215519.978957063.121",
          "seriesBodyPart": "",
          "seriesNumber": 2,
          "seriesDate": null,
          "seriesTime": null,
          "seriesModality": "MR",
          "instances": [
            {
              "columns": 13,
              "rows": 13,
              "instanceNumber": 1,
              "acquisitionNumber": null,
              "photometricInterpretation": null,
              "sopInstanceUid": "1.2.840.113619.2.5.1762583153.215519.978957063.122",
              "url": "dicomweb://fffffff.com/PACSImages/DRAbishek/20140720/1.2.840.113619.2.5.1762583153.215519.978957063.78/1.2.840.113619.2.5.1762583153.215519.978957063.121/1.2.840.113619.2.5.1762583153.215519.978957063.122.dcm"
            }

**Comment by dannyrb** [comment]
See related response here, detailing the requirements for the MPR2D button to show:

https://github.com/OHIF/Viewers/issues/1385#issuecomment-576489780

We have a separate goal of _always_ showing the button, but detailing why MPR can't be used (missing fields, data set is not reconstructable, etc.)

**Comment by nagarjunaa** [comment]
Hi Dannyrb,
          I am not clear, could you please explain me better. I have gone through that link, what is the field I am missing.

**Comment by dannyrb** [comment]
Unfortunately, I don't have the bandwidth right now to compare each tag against your JSON. You need to look at each `getRawValue` and `getTagValue` call in this file:

https://github.com/OHIF/Viewers/blob/460e375f0aa75d35f7a46b4d48e6cc706019956d/platform/core/src/utils/isDisplaySetReconstructable.js

If you provide all of those tags, it's possible you don't meet a constraint of `isDisplaySetReconstructable`, or you've encountered an edge case or a bug that we need to investigate further.

**Comment by nagarjunaa** [comment]
https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/MRStudy.json
unable to get 2DMPR, i tried other options to but not getting, if anyone got this please let me know.

**Comment by nagarjunaa** [comment]
hi Danny,
     could you please help why 2DMPR is missing, for this 

https://viewer.ohif.org/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/MRStudy.json

**Comment by dannyrb** [comment]
Related: https://github.com/OHIF/Viewers/issues/1460

**Comment by dannyrb** [comment]
This should be resolved in #1500
