### ISSUE TITLE
Issue with loading images in the embedded viewer.

### ISSUE THREAD

**Issue by Sriram-Ananth** [OHIF/Viewers#1410]
Hi,
I am trying to integrate our PACS server with the embedded version of OHIF Viewer. I have got it working till loading the list of studies using WADO and QIDO. However when I double click on a study to open images I am getting the error as shown in attachment 1. I have also attached the index.html file. Can you please help me figure out how to load the images correctly? 
![OHIF Issue](https://user-images.githubusercontent.com/53596330/73589823-5addf180-4501-11ea-9ea1-330c4ef0a6c2.jpg)
[index.html.txt](https://github.com/OHIF/Viewers/files/4142366/index.html.txt)

Thanks and congrats on the amazing work being done.

**Comment by dannyrb** [comment]
Can you either create a CodeSandbox, GitHub gist, or CodePen with your `index.html` content and link to it? I'm trying to avoid downloading a file to assist.

**Comment by Sriram-Ananth** [comment]
We were able to update the library to the latest version and and it now works well through we need to use WADOURI instead of DicomWeb. Thanks for the assistance.
