### ISSUE TITLE
Access / Hook into viewer state (specifically measurements)

### ISSUE THREAD

**Issue by leoc** [OHIF/Viewers#1412]
Hello, thanks you very much for working on such a great open platform!

Is there a way to load the Viewer via React and hook into the state? I want to configure the viewer manually (split view, image series loaded) and listen to changes in measurements. Unfortunately I couldn't find this in the docs yet.

Can I access the app state of the viewer when I load it into my own simple react app? What would be your suggested path that I could take?

Thanks! I will continue to look scout the projects code. :sunglasses: :+1:

**Comment by dannyrb** [comment]
Exposing the entire application's state as API consumers can depend on is a bit brittle, as we make changes there fairly frequently. Instead, we try to expose services, broadcast events, etc. That provide a more stable interface, and allow for the underlying implementation to change.

Today, our Measurements are managed by `cornerstone-tools`'s "Tool State". Near future, we're creating a [MeasurementService](https://github.com/OHIF/Viewers/pull/1314) that has support for subscriptions, mapping between measurement representations, and a few other niceties.

We've also recently tasked @emfol at restoring our "Hanging Protocol Engine", which would allow programmatic control of the Viewport Grid and what's displayed in them.

That being said, I realize it's not always practical to wait for these to materialize. I would be willing to accept a PR that offers a brittle escape hatch, so long as it's labeled as such. Open to suggestions ^_^

**Comment by leoc** [comment]
Thank you very much for your thorough reply! :)

I will have a look at the pull request for the measurement service. Maybe I could integrate a custom build and enhance it if needed. Also I will try to wrap my head around the concepts of services.

Regarding the "Hanging Protocol Engine", are there docs or hints at this?

 Thanks a :100: ! :+1:

**Comment by dannyrb** [comment]
@leoc if you search the source for it, it's implementation is hiding in `platform/core` and it's usage is commented out in `platform/viewer`. The `v1.x` branch is when it was last used. It relies on some parts that we don't intend to support in the current version, and it needs to be decoupled from them to be restored.

We will likely slowly restore the functionality as we work to address issues like:

- https://github.com/OHIF/Viewers/projects/6

**Comment by dannyrb** [comment]
This was a good question, but I'm unsure of how to turn it into formalized requirements for a feature request. If you'd like to open a new issue, I think there are some great items buried in here that make sense as reasonable enhancements :+1:
