### ISSUE TITLE
Accept Upload images on viewer

### ISSUE THREAD

**Issue by trung1704ptit** [OHIF/Viewers#1414]
I tested the local upload page, but only accept the Dicom file or series of Dicom file.

I think we need to accept upload the image or series images and then we can visualize images

You figure out a solution that we use cornerstoneWebImageLoader, But how can we keep the tools bar for the image loader (.jpg, .png) ?

**Comment by dannyrb** [comment]
@trung1704ptit, are you asking that we add support for viewing JPG and PNG images via the `/local` route? Without metadata, the viewer would essentially by a JPG/PNG viewer (the tools would have little value).

**Comment by trung1704ptit** [comment]
I think we the standard input is Dicom file, So we don't need read JPG or PNG. Sorry, I will close this request. 

Thank you so much

**Comment by kienxuandaoit89** [comment]
@dannyrb , 
Dear Danny,
Can you guide me how to support for viewing JPG and PNG images via the /local route?
Or can me 'fake/generate a metadata' for JPG and PNG images to load into the Viewer

I understand this limited: Without metadata, the viewer would essentially by a JPG/PNG viewer (the tools would have little value).
Thanks
