### ISSUE TITLE
UI for Viewing and Editing PET SUV parameters

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1415]
If a study contains an image with modality PT:
- There should be a button in the Series panel (for each study), which opens a dialog to allow the user to view and edit the parameters used to calculate Standardized Uptake Value (SUV).
- Most of these parameters are study-specific, but two are series-specific (Series Date, Series Time)
- The dialog should display the current values that exist in the PET series as pulled from the Cornerstone metadata provider.

1. Patient Weight (kg): patientStudyModule > patientWeight
2. Patient Height (m): patientStudyModule > patientSize
3. Total Dose (MBq): petIsotopeModule > radionuclideTotalDose
4. Half-life (min): petIsotopeModule > radionuclideHalfLife
4. Injection time: petIsotopeModule > radiopharmaceuticalStartTime (Note: We probably need to add the injectedDateTime tag to the metadata provider instead of just injection time. The tag we should use is 0018,1078 if it is present.)

See https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/2420f321946b9c08442a7f82ed85155e1e9fec96/src/imageLoader/wadors/metaData/metaDataProvider.js#L142

- The dialog should show a dropdown listing the Series Description for each PET series in the study. The Series Date and Time for this series should be displayed next to the dropdown.
- If the user edits one of the values in the dialog, we should create a new Metadata Provider for Cornerstone which returns the edited values when one of these is requested. This metadata provider should have a higher 'priority' (see https://docs.cornerstonejs.org/concepts/metadata-providers.html) so that the edited values are used first.
- We will need to trigger a recomputation of anything displaying the PET image (or relying on the PET data) after a change to these values. We may want to emit an event to notify listeners that these have changed. The VTK volume will need to be recreated since the conversion to SUV happens when the volume is created.

Here is a similar dialog from @salimkanoun's [PET/CT viewer](http://petctviewer.org/:

<img width="485" alt="Screenshot 2020-02-04 16 56 52" src="https://user-images.githubusercontent.com/607793/73763902-64ba5b80-4772-11ea-8a6e-5d9fca982fb3.png">

Note: we do not need the 'American' option.

**Comment by dannyrb** [comment]
> If the user edits one of the values in the dialog, we should create a new Metadata Provider for Cornerstone which returns the edited values when one of these is requested.

Am I correct to assume that this new Metadata Provider should "clear" when the route's container is destroyed?

PS: This is also a useful trick for calibrating pixelSpacing.

**Comment by sedghi** [comment]
Done in master
