### ISSUE TITLE
PT images should be displayed and interacted with in SUV units

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1416]
This story already happens in the VTK viewport, but it is not consistent in Cornerstone.

- Cornerstone Core should convert to SUV before displaying the image, if possible (i.e. if all required tags are present). See the implementation in react-vtkjs-viewport here: https://github.com/OHIF/react-vtkjs-viewport/blob/e3435177fac7edb00c1e071cbec1cab70fd2d45c/src/lib/data/getPatientWeightAndCorrectedDose.js#L32

Once that's implemented, the W/L displayed in the bottom right corner will be in SUV units.

- If we are displaying a PET (whether or not it is in SUV), then then minimum bound for the window/level tool should be zero. That is to say that Level - Width / 2 must be 0 or above. It is not sensical to display values below zero because they do not exist.

**Comment by sedghi** [comment]
Done in tmtv mode
