### ISSUE TITLE
For PT, region of interest tools should display max value

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1417]
For PET analysis it is useful for elliptical ROIs to display maximum SUV value, in addition to mean, since this is used more often by clinicians. We should add this for modality = 'PT' to the ellipse and rectangle ROIs.

**Comment by dannyrb** [comment]
For reference, here: https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/EllipticalRoiTool.js#L446-L451

**Comment by sedghi** [comment]
Done in tmtv mode
