### ISSUE TITLE
For Philips PET, read private tag and convert to Bq/ml before computing SUV

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1418]
There is a private tag that Philips is using in their PET images which needs to be taken into account when converting to SUV. This will need to be taken into account when converting to SUV in both the Cornerstone and VTK viewports.

There is an implementation here which we should refer to:
https://github.com/salimkanoun/fijiPlugins/blob/master/Pet_Ct_Viewer/src/SUVDialog.java#L43

**Comment by sedghi** [comment]
Done in tmtv
