### ISSUE TITLE
cannot use 3d studies from CT modality

### ISSUE THREAD

**Issue by miconx** [OHIF/Viewers#1422]
we have a CT modality which sends studies to our orthanc server 
ohif is not able to render the studies 
if you click on a study the /viewer route will be opened but only a blck screen is visible

* browser webdev tools / console do not show ANY errors 
* orthanc does not produce ANY errors 

i have installed a demo server where i´ve imported 1 of these studies under: 
https://pacs.medalpgroup.at  
(user: orthanc, password: orthanc) 

the anonymised study is attached here 

Any other dicom viewers i have tried (inluding the build in  orthanc webviewer) are showing the study without any problems

[Anonymized2.zip](https://github.com/OHIF/Viewers/files/4165654/Anonymized2.zip)

**Comment by miconx** [comment]
with the latest commit e8d56c1 the problem went away

**Comment by swederik** [comment]
Happy to hear that! There are definitely some edge cases where things fail if tags are missing, because the code was probably written assuming that required tags are all present. Don't hesitate to file another issue if you find more cases like this.
