### ISSUE TITLE
production environment with docker image

### ISSUE THREAD

**Issue by fernandogbi** [OHIF/Viewers#1425]
I have some problem with my ohif deploy on docker. I just change the server path on app-config.js to my orthanc server and I configured CORS in this one. My OHIF container works if i deploy to my localhost, but when i try to run on my server with a domain configured OHIF just works the study list, and when I try to open some study I'm, noticied about a CORS error. Has some thing that con I need to do before run the OHIF docker image on production?

**Comment by dannyrb** [comment]
If your DICOMWeb instance is hosted at a different domain/port, you'll need to make sure the server/proxy that is responding to DICOMWeb requests appends the appropriate CORS Headers to responses.

In Production, Orthanc should not be directly receiving requests; it should be proxied by a true webserver. We often suggest `nginx` for this.

**Comment by fernandogbi** [comment]
Hi @dannyrb. Thanks for your answer. I already change my CORS header to allow my domain on production, and my orthanc is running through my nginx proxy. For some reason I get error only when I try to run OHIF outside my localhost. Maybe has any environment variable that I need to configure on my container?

**Comment by dannyrb** [comment]
If you're still seeing a CORS error, you likely don't have CORS configured correctly.
