### ISSUE TITLE
Series level Layout

### ISSUE THREAD

**Issue by jaizz2003** [OHIF/Viewers#1427]
I am trying to implement Series Levels Layout in which we can see various images under the same series. How to proceed, as there are lots of different files that have Layout but none has any option to change or display series level layouts.
I went through the Study Level Layouts but I don't seem to reach any closer to my goal.

My Approach: Instead of passing all the images to viewport we can pass one image and then set the viewport accrding to that. I am not able to implement it yet, so any clue will help.

**Comment by trung1704ptit** [comment]
We can choose multiple folder when we upload file.
In /local route, you can upload multiple folder => you have multiple series.

But this application has a bug, we cannot change the series after we click on each of them in left navigation.

**Comment by sedghi** [comment]
This logic should be handled in the getSopClassHandlerModule of your extension
