### ISSUE TITLE
Import study from disk via DIMSE to Orthanc server fails for certain DICOM files

### ISSUE THREAD

**Issue by EmilOJ** [OHIF/Viewers#143]
The two attached DICOM files are part of the same study and series. When uploading them separately using the "Import study" button at the top right corner of the study list, they are uploaded properly via DIMSE to my Orthanc server (running in docker). However, **when uploading together** it seems that the files are corrupted somehow. The same error occurs when trying to upload the entire study (around 500 files). It successfully uploads 249 files but then fails. I narrowed it down to failling with just these two files (failling together, but working separately). 
See the following output when uploading the two files together (placing them in the same directory).

Meteor server log:
```
I20171205-14:21:31.780(1)? Services.DIMSE.Studies
I20171205-14:21:31.781(1)? Associating...
I20171205-14:21:31.783(1)? Starting Connection...
I20171205-14:21:31.791(1)? Connect
I20171205-14:21:31.791(1)? Connection established
I20171205-14:21:31.803(1)? ==Associated
I20171205-14:21:31.805(1)? Sending command C-FIND-RQ
I20171205-14:21:31.858(1)? Data received
I20171205-14:21:31.864(1)? Connection closed
I20171205-14:21:35.294(1)? Dicom file /tmp/dicomDir/11706606 found
I20171205-14:21:35.294(1)? Dicom file /tmp/dicomDir/11707156 found
I20171205-14:21:35.295(1)? Starting Connection...
I20171205-14:21:35.296(1)? Connect
I20171205-14:21:35.297(1)? Connection established
I20171205-14:21:35.300(1)? Sending file /tmp/dicomDir/11706606
I20171205-14:21:35.301(1)? Sending command C-STORE-RQ
W20171205-14:22:05.407(1)? (STDERR) Association aborted with reason 0
I20171205-14:22:05.408(1)? Connection closed
```

Orthanc log (shortened - full output is attached): 
```
W: DcmItem: Length of element (5343,000a) is odd
W: DcmItem: Non-standard VR ' �' (03\a3) encountered while parsing element (a303,a503), assuming 2 byte length field
W: DcmItem: Length of element (a303,a503) is odd
W: DcmItem: Non-standard VR '� ' (ea\03) encountered while parsing element (03e5,03e6), assuming 2 byte length field
W: DcmItem: Length of element (03e5,03e6) is odd
W: DcmItem: Dataset not in ascending tag order, at element (03e5,03e6)
W: DcmItem: Non-standard VR ' �' (03\d5) encountered while parsing element (d203,d603), assuming 2 byte length field
W: DcmItem: Length of element (d203,d603) is odd
W: DcmItem: Non-standard VR '� ' (f5\03) encountered while parsing element (0401,03fb), assuming 2 byte length field
W: DcmItem: Length of element (0401,03fb) is odd
W: DcmItem: Dataset not in ascending tag order, at element (0401,03fb)
W: DcmItem: Non-standard VR '  ' (04\13) encountered while parsing element (0303,0e04), assuming 2 byte length field
W: DcmItem: Dataset not in ascending tag order, at element (0303,0e04)
W: DcmItem: Non-standard VR ' �' (01\bc) encountered while parsing element (ab01,bb01), assuming 2 byte length field
W: DcmItem: Length of element (ab01,bb01) is odd
W: DcmItem: Dataset not in ascending tag order, at element (ab01,bb01)
W: DcmItem: Non-standard VR ' �' (00\a9) encountered while parsing element (9500,a100), assuming 2 byte length field
...
W: DIMSE Warning: (OHIFDCM,ORTHANC): DIMSE receiveDataSetInMemory: dset->read() Failed (Invalid stream)
E1205 13:21:49.984349 StoreScp.cpp:294] Store SCP Failed: DIMSE Failed to receive message
```
full output: [orthanc output.txt](https://github.com/OHIF/Viewers/files/1531280/orthanc.output.txt)

To check if they are corrupt, I tried to run DCMTK's `dcmdump` on all files (both originals and the ones copies to `/tmp/dicomDir` by meteor):

```
mydicom/11706606
mydicom/11707156
tmp/dicomDir/11706606
tmp/dicomDir/11707156
```
but all of them look fine (dcmdump just outputs all the tags and their values as it is supposed to).

I tried uploading the files together directly to Orthanc using the admin interface at localhost:8042, and it works fine. Thus I suspect this to be an OHIF Viewer bug rather than Orthanc. 

I tried opening the files in ITK-SNAP, and they load and display just fine. 

The two dicom files can be found here: [dicom.zip](https://github.com/OHIF/Viewers/files/1531262/dicom.zip)

Extra info: I'm running the OHIFViewer using:
```
cross-env METEOR_PACKAGE_DIRS=\"../Packages\" meteor --settings ../config/orthancDIMSE.json
```
I'm running orthanc using a custom configuration file, where the only thing I changed was adding 
```
"ohif": [ "OHIFDCM", "localhost", 3000 ]
```
to `DicomModalities`.

**Comment by dannyrb** [comment]
We are moving away from support for version 1 of the Viewer. The goal is to make Version 2 extensible and configurable enough that you can customize it for your workflow and purposes; however, DIMSE support is not yet planned.

This issue hasn't seen activity in some time, so I'm going to close it. If you, or anyone else, has new info to add on this issue, please don't hesitate to comment and continue the discussion.
