### ISSUE TITLE
When we use Dicom PDF

### ISSUE THREAD

**Issue by trung1704ptit** [OHIF/Viewers#1430]
Hi everyone,

I try to read about the document, but I don't know about the dicom-pdf.

What is this and how does it works in application.

In document:  dicom-pdf is View DICOM wrapped PDFs in viewport. So why we need to render file PDFs in viewport?

Please explain it

**Comment by wtlatli** [comment]
Hi @trung1704ptit.

PDF Documents can be stored in archive as DICOM files. (1.2.840.10008.5.1.4.1.1.104.1 Encapsulated PDF Storage)

Rendering PDFs in viewport is very usefull to have read the report with the same viewer as the DICOM images.

**Comment by sedghi** [comment]
we have demo for it here https://viewer.ohif.org/viewer?StudyInstanceUIDs=2.25.317377619501274872606137091638706705333
