### ISSUE TITLE
2D MPR missing when loaded MRI images using dicomweb

### ISSUE THREAD

**Issue by nagarjunaa** [OHIF/Viewers#1431]
unable to get 2DMPR, i tried other options to but not getting, if anyone got this please let me know.

json loading url is below

https://viewer.ohif.org/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/MRStudy.json

**Comment by dannyrb** [comment]
See related response here, detailing the requirements for the MPR2D button to show:

https://github.com/OHIF/Viewers/issues/1385#issuecomment-576489780

We have a separate goal of _always_ showing the button, but detailing why MPR can't be used (missing fields, data set is not reconstructable, etc.)

**Comment by dannyrb** [comment]
Ahh. I see you're actually re-asking a question you've previously sought help for:

https://github.com/OHIF/Viewers/issues/1405

Please don't create duplicate issues.
