### ISSUE TITLE
How to easy use in mobile web browser?

### ISSUE THREAD

**Issue by wangning08115** [OHIF/Viewers#1432]
The Viewers run fine on PC web browser.
![image](https://user-images.githubusercontent.com/3455705/74145135-10fbb680-4c39-11ea-9879-1ee606ab1711.png)

But in mobile web browser,The menu toolbar can't be click like below:
If the toolbar can On the bottom and folding then it will look better.

![image](https://user-images.githubusercontent.com/3455705/74145233-42748200-4c39-11ea-875e-6036325a6da3.png)

And if the left series panel can popup on view,then it will look better.

**Comment by dannyrb** [comment]
@wangning08115, thanks for the feedback! We're aware that there are a few simple improvements we could make to improve viewing on mobile devices. Unfortunately, the core team doesn't have those changes slated for the near future.

We do, however, welcome community pull requests to improve mobile support 🙌
