### ISSUE TITLE
Longitudinal Viewing: Left Panel

### ISSUE THREAD

**Issue by galelis** [OHIF/Viewers#1433]
### Description
Create a left panel for Lesion Tracker that should receive a mock data and display it as we have on legacy lesion tracker application (screenshots taken below) we should keep the layout

This task should only cover the UI layout on top of a mock data. 

### Screenshots
<img width="308" alt="Screen Shot 2020-02-10 at 13 10 28" src="https://user-images.githubusercontent.com/2378326/74167284-cbbe9100-4c06-11ea-91b9-325e5d0b1e71.png">
<img width="303" alt="Screen Shot 2020-02-10 at 13 10 35" src="https://user-images.githubusercontent.com/2378326/74167288-cd885480-4c06-11ea-83bd-2fb6a81febeb.png">
<img width="307" alt="Screen Shot 2020-02-10 at 13 10 41" src="https://user-images.githubusercontent.com/2378326/74167289-ce20eb00-4c06-11ea-9e3e-36fb44f910cc.png">
<img width="309" alt="Screen Shot 2020-02-10 at 13 10 53" src="https://user-images.githubusercontent.com/2378326/74167291-ceb98180-4c06-11ea-832a-60d32ae94a8e.png">

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
