### ISSUE TITLE
JS exception when loading study viewer for study with existing measurement saved

### ISSUE THREAD

**Issue by ladeirarodolfo** [OHIF/Viewers#1439]
### Describe the Bug
There is a JS exception on the log and page is not displaying text Box with length unit.

### What steps can we follow to reproduce the bug?
- Go to study viewer `viewer/1.2.840.113619.2.5.1762583153.215519.978957063.78` or any which has a study with a measurement (length) previously saved.
- Open console tab on devtools.
- Verify the following exception 
<img width="926" alt="Screen Shot 2020-02-12 at 13 57 35" src="https://user-images.githubusercontent.com/39910206/74358124-b16beb00-4d9f-11ea-8016-80fe91d4541a.png">

Actual behavior
- There is a JS exception on the log and page is not displaying text Box with length unit.

Expected behavior
- Should not be such js exception and text Box with length unit should be displayed near to related length tool

#### Technical info
This occurs on:
[https://github.com/cornerstonejs/cornerstoneTools/blob/e38e2f5c81b0f83cca5a29a03334bee287028a8a/src/tools/annotation/LengthTool.js#L235](
https://github.com/cornerstonejs/cornerstoneTools/blob/e38e2f5c81b0f83cca5a29a03334bee287028a8a/src/tools/annotation/LengthTool.js#L235)

This is caused by: when retrieveMeasurements and then trying to generate toolData from:

[https://github.com/OHIF/Viewers/blob/695ad732e122b30043be280c612f738f8487d655/platform/core/src/DICOMSR/parseDicomStructuredReport.js#L22](
https://github.com/OHIF/Viewers/blob/695ad732e122b30043be280c612f738f8487d655/platform/core/src/DICOMSR/parseDicomStructuredReport.js#L22)

LengthTool (or in this case toolData) has different structure. I.e its different from when creating it manually :
Manually:
```
{
....
  invalidated: true,
  length: undefined
}
```
From MeasurementReport.generateToolState
```
{
...
  // there is no invalidated prop
  length: undefined
}
```
On the process of rendering LengthTool, it uses `invalidated` prop to update its length (plus many other annotation are created with invalidated being true at a very first moment)

[https://github.com/cornerstonejs/cornerstoneTools/blob/e38e2f5c81b0f83cca5a29a03334bee287028a8a/src/tools/annotation/LengthTool.js#L200.](
https://github.com/cornerstonejs/cornerstoneTools/blob/e38e2f5c81b0f83cca5a29a03334bee287028a8a/src/tools/annotation/LengthTool.js#L200.
)
So considering, there is no invalidated on From `MeasurementReport.generateToolState` toolData state, then length is not update and js breaks.

**Comment by dannyrb** [comment]
Fixed in #1233, mappers will account for schema differently in @igoroctaviano's upcoming MeasurementService changes that add support for additional annotations
