### ISSUE TITLE
Study List based on Patient or Study Unique ID

### ISSUE THREAD

**Issue by mreddymd** [OHIF/Viewers#144]
Hello All,

   By default, OHIF study list shows all patients one row for each study type. Please let us know is there any way to filter to show study list for one particular patient if I pass the ID as filter argument.

Regards,
Murali

**Comment by swederik** [comment]
Let's do this using the IHEInvokeImageDisplay route (https://github.com/OHIF/Viewers/blob/9116d0895963d8644311fb88527b15bff4f10ef6/src/routes/IHEInvokeImageDisplay.js#L43-L46). It can add a filter to the study list to search by medical record number (MRN).

**Comment by swederik** [comment]
Turns out this was already done here (https://github.com/OHIF/Viewers/pull/543)

**Comment by swederik** [comment]
You can thank @dlwire for this!
