### ISSUE TITLE
Standardize on front-end practices

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1440]
See: https://github.com/bradfrost/frontend-guidelines-questionnaire

We're in the process of iterating on design concepts for a fresh new look as OHIF approaches an official, stable v2 release. After the design is finalized, we'll want to begin on creating the components that comprise the design.

Our current component library, `@ohif/ui`, located in `platform/ui`, is using `docz` and was cobbled together with components we had available at the time. It has been a handy tool, but the various components don't follow atomic principles, are not styled consistently, and run into issues when we attempt to compose them.

Are goal is to create a feature branch that replaces the `platform/ui` project with the tooling, stylelint, and guidance in place to allow us to iterate swiftly and confidently on the new design.

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
