### ISSUE TITLE
Support for programmatic control of viewport layout and study association

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1441]
We would like to be able to force a 1x2 viewport grid layout, where the first viewport is tied to a specific studyInstanceUid, and the second viewport is tied to a different studyInstanceUid.

When the route first loads, the viewports are filled with the first image from the first series from the correct study.

When we attempt to view an image from either of those studies (selection from thumbnail list, or drag-n-drop), the correct viewport is updated to display the selected image.

The viewports can be configured to "switch" to a different studyInstanceUid.

We should gracefully handle instances where one or neither study is present.

**Comment by sedghi** [comment]
Done in master
