### ISSUE TITLE
Filters, sort, pageNum and rowsPerPage must be persisted when moving to/from studyList/viewer

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1443]
See: https://github.com/OHIF/Viewers/pull/1437

As I user I would like to have filters, sort, pageNum and/or rowsPerPage persisted into studyList page when moving from studyList to viewer and then back to studyList.

#### Technical requirements
- Persist filters, sort, pageNum and/or rowsPerPage on sessionStorage
- Add a clear button to clear all filters

#### User experience example
- Filter on patient name "Bellona"
- View study
- Navigate back to study list
- Study list should still be filtered by patient name "Bellona"
- Close browser
- Open browser
- Navigate to viewer application
- Filters should be clear

**Comment by sedghi** [comment]
Will do in https://github.com/OHIF/Viewers/pull/1437
