### ISSUE TITLE
Support for user defined routes

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1444]
Our Viewer implementation (`@ohif/viewer`, `/platform/viewer`) currently exposes several hardcoded routes. This has lead us to a "kitchen sink" model, whereby our viewing route consumes and exposes all extension functionality.

As we continue to expand the features available to our viewer, it will become important to also have the ability to filter, guide, or more explicitly define when and how we expose features to our end users. Custom, user defined routes, are the first step toward making this possible.

Some context:

### Extensions:

- May or may not have initialization logic
- Add new functionality
- Encapsulate third party libraries
- Filter encapsulated functionality to appropriate contexts

### Application Configuration:

- Configures our implementation of a "Viewer"
- Determines how disparate functionality by extensions should be composed/used (see: hotkeys)
- Where/how we determine runtime extensions and any supplemental extension configuration

The current idea is that we allow users to define routes in the "Application Configuration". Routes are defined by a route "container template", currently provided by the viewer project ("List" or "Viewer"), a route pattern ("/viewer/:studyInstanceUid"), and options that configure the target "container template" (TBD).

**Comment by sedghi** [comment]
CustomizationService makes it possible now. https://docs.ohif.org/platform/services/ui/customization-service
