### ISSUE TITLE
Cannot combine connerstone-tools turn into monorepo

### ISSUE THREAD

**Issue by nghiahsgs** [OHIF/Viewers#1450]
There are my step and it does not work with me:
Step 1: I copy cornerstone-tools project into extension folder
Step 2: I import "@ohif/extension-cornerstone-tools" to viewer

I think I forget some step to it work, now it always errors not found "@ohif/extension-cornerstone-tools"

Pls help me, tks to reading !

**Comment by dannyrb** [comment]
I'm not sure I understand your steps versus your expected result.

**Comment by nghiahsgs** [comment]
Hi @dannyrb , Thanks for reply
 
My situation is that I want to customize the cornerstone-tools, so I think I need to combine the project cornerstone-tools into the ohif project.

I want to use cornerstone-tools as the extenstions plugin, so do some steps:
1. Copy the project cornerstone-tool from your github into the extensions folder,
2. Replace import from "cornerstone-tools" to => "@ohif/extensions-cornerstone-tools" really like that you declare.
3. Delete node_modules and run yarn again.
=> error that cannot find the module @ohif/extensions-cornerstone-tools", Maybe I miss some steps because we are working on lernajs.
Do you hanve any ideal, when you want to integrate more extension, what will you do?

Thanks for your help, hope get your response soon.

**Comment by dannyrb** [comment]
Why do you need a custom cornerstone-tools? 

You can use yarn link in the repository root and build the PWA, or the cornerstone extension package.

For adding a single custom tool, you can pass it in to the cornerstone extension using the extension's configuration object, or create a new extension that adds it in the preregistration hook.
