### ISSUE TITLE
Failed to map 'CornerstoneTools@4'

### ISSUE THREAD

**Issue by helghast79** [OHIF/Viewers#1451]
JS error  triggers on viewer load 

> Failed to map 'CornerstoneTools@4' measurement for definition stack...

Most of the measuring tools (except for the length tool), when used, will show similar error messages. What can be the cause of this? is cornerstoneTools not being loaded properly? build issue or configuration error? Despite the error the tools work in the viewer as expected but on the measurements tab show an "unsupported tool" sign

<img width="1164" alt="Screen Shot 2020-02-18 at 11 12 07" src="https://user-images.githubusercontent.com/16775681/74731431-da78f980-523f-11ea-9b9a-429c1e368ff5.png">

**Comment by dannyrb** [comment]
Ah, those should be warnings, not exceptions. We're improving how measurements are stored and exposed by the OHIF platform internally. The `MeasurementService` will eventually replace `cornerstone-tools` "ToolState" as the source of truth for measurements, and provide some niceties around mapping measurements between the different shapes/schemas expected by various 3rd party libraries and extensions.

The "not supported" warning in the UI is specific to what we can and cannot support for persisting with DICOM SR at this time. We currently only persist `Length`, but are looking to add support for bidirectional in the near future.

Other tools will likely eventually have support as well, but I'm not sure where they fall on our roadmap. If someone is interested in adding additional support, I could preemptively scope the issues that lay out guidance for what we would be looking for in a PR.

**Comment by dannyrb** [comment]
CC: @igoroctaviano ^

**Comment by helghast79** [comment]
Thanks Danny, do you know how can i get the details of the tool
measurements done by the user. I mean, if I draw a rectangle for example,
how can I get the position, size, etc.
My goal is to use the rectangle or circle tool to select a ROI and to
export it as some kind of binary mask for processing later. Do you have any
ideia if this is doable with the current viewer and how?

cheers

Miguel Chambel

**Comment by dannyrb** [comment]
You can hook directly into cornerstone-tools "tool state". Check out the docs and source here:

- https://github.com/cornerstonejs/cornerstoneTools

In the near future, extensions will have access to a new "MeasurementService" that provides an OHIF specific way to request that information

**Comment by helghast79** [comment]
Great thanks

Miguel Chambel

**Comment by wangning08115** [comment]
Hi @helghast79   Have you solved the problem?  
I have the same problem.
Can you help me?

**Comment by helghast79** [comment]
Hi there,

While persisting tool state in standard Dicom-SR looks appealing, I have
made some tests and I'm able to use DCMJS to generate a report in dicom-sr
format and store it in Pacs system (Orthanc in my case) but it seems that
only some tools are translated by DCMJS, for example RectangleRoi is not
present but ellipticRoi is. I can point you in this direction if you want
but what I ended up doing is persisting the toolstate in database and
restore it later

save toolstate to variable
const toolState =
cornerstoneTools.globalImageIdSpecificToolStateManager.saveToolState()
you can then stringify it and append to a form for example
to restore the toolstate in ohif it's not so easy, you can however do
cornerstoneTools.globalImageIdSpecificToolStateManager.restoreToolState(
toolState)
after getting the toolstate and parse it if it was in string form of course
but this will not affect the measurements API so if you click on
measurements panel you'll see nothing but at least the tools will be loaded
and you will see them in the viewer

For now I'll stay with this procedure until I find a better solution, maybe
you can come out with a better one I hope, in that case, please share what
you find

cheers

Miguel Chambel

**Comment by smilegok** [comment]
const toolState =
cornerstoneTools.globalImageIdSpecificToolStateManager.saveToolState()
you can then stringify it and append to a form for example
to restore the toolstate in ohif it's not so easy, you can however do
cornerstoneTools.globalImageIdSpecificToolStateManager.restoreToolState(
toolState)

This is what I use for that solution so far. But if there is a way to get masurements and set it with SET_MEASUREMENTS would do the trick somehow.  In 1800 issue of OHIF @timoangerer says that SET_MEASUREMENTS does not renders inside the viewer.
