### ISSUE TITLE
whether OHIF supports the viewing of Dose and Plan in the dicom-rt supplementary specification?

### ISSUE THREAD

**Issue by huatianyu** [OHIF/Viewers#1455]
May I ask whether OHIF supports the viewing of Dose and Plan in the Dicom-RT supplementary specification?

**Comment by dannyrb** [comment]
This is the extent of our planned near-term DICOM-RT support: https://github.com/OHIF/Viewers/issues/1373

We're open to expanding support, but do not currently have community members championing development work or funding to move forward.

**Comment by JamesAPetts** [comment]
Just to clarify Danny's point. Only the static display (no editing) of RTSTRUCT files has any funding at this time.
