### ISSUE TITLE
Looking to deploy local standalone version of ohif with suggestion

### ISSUE THREAD

**Issue by supermansrf** [OHIF/Viewers#1457]
I have been doing a ton of looking around and I am convinced that I want to use OHIF for a project that I'm working on for a friend.  We have deployed an Orthanc server locally on a Windows 2016 virtual.  In fact we have been using it for a while already.  The one feature the built in web viewer lacks is freehand ROI which I have tested here and like.  

That being said, my options of deploying OHIF are pretty much endless, except for my lack of understanding most of this.  I'm not a developer and most of the time here I feel in over my head.   My thoughts already...

Deploy ohif via docker but after messing around with docker for the past 2 days I'm completely frustrated (I have another virtual CentOS 7 machine on the same host).  

Deploy ohif via IIS on the same Windows server hosting our Orthanc database.  

I'm looking for anyone who has done this with some experience that can just help point me in the right direction.  Anyone accessing this would be doing so via local network.  This will NOT be published via the internet so a lot of the suggestions of hosting this online really only cause us issues (we are in the US and I want to avoid having to really secure things as this is only for research purposes).  The doctor will either access the viewer from Chrome inside our network or via VPN when he is at home same way.  

I need it to be as easy as possible for him to get access to files.  He likes his technology but is easily frustrated.  What would be amazing is if I could just replace the button within Orthanc with OHIF viewer but I don't know how simple of a task that would be.  Probably not.  

Any suggestions or ideas?

**Comment by dannyrb** [comment]
> Deploy ohif via IIS on the same Windows server hosting our Orthanc database.

This is probably the lowest effort approach that fits your situation. Are you having trouble building the application? Hosting static files with IIS? Setting up SPA redirect rules?

What steps are you taking, and what problems are you running into?

**Comment by supermansrf** [comment]
So I have a CentOS VM setup just with simple Apache just to host the static content.   I hadn't thought about IIS.  I assumed I could just download the github project and drop it in www folder and away I go but I don't know enough about any of this.  I tried hosting it via Github but that didn't seem to work as the directions showed either.  None of the folders except for the docs folder did anything, but the docs folder gave me a CNAME error (duplicate CNAME docs.ohif.org).  Which makes sense.  

I can figure out the majority of IIS, I just need to know what files to put into the site folder in order to host it.  If I use surge does this deploy over the web or just locally?

**Comment by supermansrf** [comment]
I think I may have figured out my issue.  I'll report back either fixed or need help.  I missed a step.

**Comment by dannyrb** [comment]
The GitHub project is "source code" that you need to build (using Webpack, Rollup, etc.) to create the "built" (dist, output) that you then host.

We intend to eventually offer a "release" for each version that are the pre-built files you can dump into something like the `IIS` `www` folder. Easier, but limited in that you're stuck with whatever "built in" extensions we default to.

Another option is creating an `index.html` file that uses a script include for our `@ohif/viewer` package.

I realize that may be too high level. Let me know how I can help clear things up.

**Comment by supermansrf** [comment]
So I do have a question - I finally got it built.  Where I was running into issues was finding the files after running yarn run build - not realizing there was a folder viewers (created from forking Git) and then inside that my dist folder was in /viewers/platform/viewer/dist

Now that I have my build built, and its deployed using your PACS server.  If I want to change the PACS server, I need to go edit the default.js file then build it again?  Is that correct?

**Comment by supermansrf** [comment]
Actually let me word this again...

My OHIF viewer is hosted on the same network as my PACS.  We will ALWAYS access OHIF via local network, not over web.  

So If I want to change the DCM4CHEE to my local Orthanc server, located at 192.168.1.7 can you help me figure out how my default.js file should look for that?

**Comment by dannyrb** [comment]
> not realizing there was a folder viewers

I have been wondering if we need a better project structure, or if we should shift all output to the root directory. It is not obvious that the output will be in `platform/viewer/dist`

> If I want to change the PACS server, I need to go edit the default.js file then build it again? Is that correct?

The `default.js` is just what's copied over during the build process. You can modify the output `app-config.js` directly. You're right in that you can also update `default.js` or target a different configuration file at build time.

**Comment by dannyrb** [comment]
> So If I want to change the DCM4CHEE to my local Orthanc server, located at 192.168.1.7 can you help me figure out how my default.js file should look for that?

If you're local Orthanc Server is sitting behind something that sets the appropriate CORS headers (like `nginx`), or if you're hosting the web application at the same domain/ip + port, and if your Orthanc has the DICOMWeb plugin turned on, you just need to update the DICOMWeb Server endpoints in the configuration to point to the Orthanc DICOMWeb endpoints.

**Comment by supermansrf** [comment]
So I have a few questions.  I did not deploy Orthanc via Docker.  I used the Windows installer that they distributed.  So I'm not sure if it uses nginx or not.  I just moved my OHIF build to IIS instead of trying to host on a separate machine.  

I can access Orthanc via localhost:8042 and can access OHIF at localhost (deployed via IIS).  When the old connection to DCM4CHEE was in place it was working fine.  When I change my app-config.js file to match what I have found on the documentation to my Orthanc server I get a black screen.  

In the documentation, it says:

window.config = {
  routerBasename: '/',
  servers: {
    dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: 'http://localhost:8899/wado',
        qidoRoot: 'http://localhost:8899/dicom-web',
        wadoRoot: 'http://localhost:8899/dicom-web',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
      },
  

Where did you get port 8899 from?  I have tried this config with both 8899 and 8042 and neither work.  

I'm not sure now what I'm missing.  I thought for sure moving OHIF to the same Windows server running Orthanc would help but it doesn't seem to be the issue.  

The only other thought I had was because we had authentication enabled on Orthanc that might be messing me up but I just disabled it and still get nothing.  

What am I missing?  This is a real pain in the butt.  I can usually figure anything out with enough trial and error.  This is frustrating.

**Comment by supermansrf** [comment]
DICOMM web plugin is enabled fyi

**Comment by supermansrf** [comment]
Actually fyi, when I refresh OHIF I get an empty OHIF viewer for one brief moment, then it all goes blank.

**Comment by dannyrb** [comment]
It's difficult for me to provide guidance without a full reproduction. It may be helpful to check what errors/warnings you see in Chrome's `console` and `Network` tabs

**Comment by joweste** [comment]
I have the same problem. I think the docs are not clear about It.  Do you solved It?

**Comment by supermansrf** [comment]
No and I agree. It would be nice to have better docs on this. At least for
what we are trying to do.

COVID hit and the office I was working for cut back on spending. I plan on
getting back on this one day but it may be a while. My plan was to have a
developer friend of mine figure it out for me.

If/when I get a solution I’ll reply.


Sent from my iPhone

On Aug 6, 2020, at 4:04 PM, joweste <notifications@github.com> wrote:

﻿

I have the same problem. I think the docs are not clear about It. Do you
solved It?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OHIF/Viewers/issues/1457#issuecomment-670165258>, or
unsubscribe

**Comment by dannyrb** [comment]
There is no way to connect to Orthanc without OHIF at the same domain/port, or by proxying requests to Orthanc. Anything else causes CORS errors, which will crash the application.
