### ISSUE TITLE
Measurements don't wok with Microscopy Slides

### ISSUE THREAD

**Issue by sgala** [OHIF/Viewers#1463]
> **Before Creating an issue**
>
> - Are you running the latest version?

I checked that the behavior is substantially the same for 3.7.1

> - Are you reporting to the correct repository?

Not sure

> - Did you search existing issues?

Yes, couldn't find anything relevant under SM, Slide or Microscopy

### Describe the Bug

When a SM image is displayed (see [for instance](https://viewer.ohif.org/viewer/1.2.392.200140.2.1.1.1.2.799008771.3960.1519719403.819)) measurements don't work.

### What steps can we follow to reproduce the bug?

See https://viewer.ohif.org/viewer/1.2.392.200140.2.1.1.1.2.799008771.3960.1519719403.819 

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by dannyrb** [comment]
This is less of a bug and more of a feature request. We currently do not have support (or financing) for this feature short or long-term. If you're interested in seeing whole slide microscopy use cases expanded, I recommend reaching out to an OHIF consultant or working with the community to create the features you need in an OHIF extension.
