### ISSUE TITLE
Workflow for integrating image processing tools

### ISSUE THREAD

**Issue by trypag** [OHIF/Viewers#1467]
Hello,
I am very new to DICOMs and OHIF, I am trying to progressively understand both. So this is a very generic question regarding processing of DICOMs and the integration of this workflow into OHIF.

Very simple use case : I would like to add a button on the visualization interface allowing the user to register/resample the current image. This simple use case generates the following questions :
- As I am used to handle nifty images for image processing tasks, I have no clue if it can be as simple for DICOMs ? if no, should I convert to a nifti type, run my transformation and convert back to DICOM ? what is your experience with regard to this type of job ? is there anything I should absolutely not do ?
- After running the task, it might generate a new series, should it replace my original ? or maybe it can be considered as a different one ? I guess it's up to me to decide on this, I just don't want to go in a bad direction again :smile: 

I agree my first point is not specific to OHIF, it's more about your experience of DICOMs processing, I thought you guys already went through this.

PS: is there any slack or discord I could join ? (no worries if it's limited to the contributors, I understand)

Thanks

**Comment by trypag** [comment]
Hey,
This remains an open question, but I prefer to close it not to pollute already opened issues.

**Comment by pieper** [comment]
@trypag - to learn about open source tools for dicom and image processing in general, you may want to study some of the work that we do at [Project Week](https://projectweek.na-mic.org/).  This includes a lot of OHIF-related work, but also [Slicer](https://www.slicer.org/).  The [Slicer forum](https://discourse.slicer.org/) is one place where these kinds of topics are discussed.

**Comment by dannyrb** [comment]
:wave: @trypag, perfectly okay to keep it open ^_^
Not sure how this issue escaped my attention.

> I would like to add a button on the visualization interface allowing the user to register/resample the current image. 

Check out:

- Toolbar Module: https://docs.ohif.org/extensions/modules/toolbar.html
- Commands Module: https://docs.ohif.org/extensions/modules/commands.html

>  is there any slack or discord I could join ? (no worries if it's limited to the contributors, I understand)

Send the e-mail you would like an invite for to: `danny.brown@radicalimaging.com`

@pieper's call-outs are great. Slicer has a larger community, and Project Week is a fantastic way to connect, learn from, and share with the community.

**Comment by trypag** [comment]
Thank you for the replies, very informative.
