### ISSUE TITLE
Reference Lines and Length Tool aren't working properly

### ISSUE THREAD

**Issue by afurkan** [OHIF/Viewers#147]
I builded OHIF with latest git repository and run with DCM4CHEE (DIMSE).
They were running before but not now.
There are no Reference lines when 2x2 layout with MR/CT studies.
Length tool always show length as pixel. (CT/MR)
Thanks.

**Comment by franzronan** [comment]
How to make the length tool unit to mm? My build is standalone viewer and the length tool unit is also in pixel.

**Comment by franzronan** [comment]
I think I solved it or just a work around ... You need to have the right Pixel Spacing from Dicom or json.

I followed the deployment steps of the viewer in https://github.com/OHIF/Viewers/tree/master/StandaloneViewer, ran it and the unit is in pixel, I ran the Prebuild Sample and the unit is correct. I compared the two scripts and able to locate the "t.instance.pixelSpacing" replaced the whole line at 147 from the prebuild at line 149 and ran it again and now I'm seeing the correct unit in mm. Could this be a bug or something?

**Comment by afurkan** [comment]
I getted latest code from git, And they seem working well. Thanks
