### ISSUE TITLE
Can I download images as other types of files besides png jpg？

### ISSUE THREAD

**Issue by w779788572** [OHIF/Viewers#1474]
When I finish labeling a file, I want to download it as another type of file Like(BMP,TIFF).

**Comment by dannyrb** [comment]
We support what the browser natively provides: JPEG and PNG

Anything else would likely require a 3rd party dependency and converting from one of those two sources, or encoding using the raw pixel data.

**Comment by w779788572** [comment]
Another thing i can not use some tools  (angle,ellipticalRoi,rectangleRoi),Is it necessary to use these tools in specific situations.

**Comment by dannyrb** [comment]
The tools don't work, or you're not aware of their use cases for radiologists?

**Comment by w779788572** [comment]
Now,First question i just extention two options(bmp,tiff) in download file type options,it seems work.
:-D
