### ISSUE TITLE
Guidance with reference line implementation

### ISSUE THREAD

**Issue by sinanmb** [OHIF/Viewers#1479]
Hi,

I'm trying to implement reference lines for a layout with two viewports only. I've taken a look at [the issue #619](https://github.com/OHIF/Viewers/issues/619) as well as some older ones (that seem relevant to the viewer prior to the move to React) and am still confused about how to go about the implementation. 

Can someone give me some guidance, please?

**Comment by dannyrb** [comment]
@sinanmb, can you give https://github.com/OHIF/Viewers/pull/1482 a try and indicate if it resolves your issue?

**Comment by sinanmb** [comment]
Hi @dannyrb, thank you for responding quickly! I will give this a try.
