### ISSUE TITLE
How can I add Freehand tool manually using (x,y) coordinate array?

### ISSUE THREAD

**Issue by Vishal568** [OHIF/Viewers#1486]
> :hand: Hello Team I want to add freehand tool with static array data which has X and Y coordinate array

**Comment by mtm12** [comment]
The FreehandRoi tool position data is stored in the "points" object in the FreehandRoiTool variable in cornerstoneTools.js. You could assign it to your array before it's drawn. See the code around line 24149 in cornerstoneTools.js

**Comment by Vishal568** [comment]
@mtm12 Thank You for guiding me 👍
