### ISSUE TITLE
build the OHIFViewer floder error

### ISSUE THREAD

**Issue by tiancantudousi** [OHIF/Viewers#149]
when i try to build the OHIFViewer,some strange problem happend
this is the error
=> Errors while initializing project:

While selecting package versions:
error: unknown package in top-level dependencies: ohif:polyfill
unknown package in top-level dependencies: ohif:core
unknown package in top-level dependencies: ohif:commands
unknown package in top-level dependencies: ohif:hotkeys
unknown package in top-level dependencies: ohif:header
unknown package in top-level dependencies: ohif:cornerstone
unknown package in top-level dependencies: ohif:viewerbase
unknown package in top-level dependencies: ohif:study-list
unknown package in top-level dependencies: ohif:dicom-services
unknown package in top-level dependencies: ohif:hanging-protocols
unknown package in top-level dependencies: ohif:metadata

my nodejs version is 8.8.1 and meteor version is 1.6.0.1 ,how can this happen,and i have tried add the package of ohif by code meteor add twbs:ohif.   but new error happened ,error: no such package

if someone tell me how to solve this problem ,i would appreciate it if

**Comment by jacklau88** [comment]
the same error with you,did you solved it?

**Comment by tiancantudousi** [comment]
you should use meteor build a packages like this meteor create --package test (run this command under OHIF)，and then you will find a floder name packages under OHIF ,open this packages you will find a test floder . then you can copy all the (ohif:core,ohid:commands,...) to this  packages.  then run metero build .
