### ISSUE TITLE
slowness of more than 5 min for 1200 studies in the ohif viewer / studylist

### ISSUE THREAD

**Issue by carlosareco** [OHIF/Viewers#1491]
good day
I have a problem with the ohif, when it is going to load on the screen the studies take more than 5 minutes every time you select a localhost: 3000 study, instead in the orthanc localhost: 8042 it is super fast. Could you please help me
Thanks a lot

**Comment by dannyrb** [comment]
@carlosareco, this is likely an issue with Orthanc's DICOMWeb implementation. There is a known issue when queries pull more info than is immediately available in the database for each study/instance/series, that Orthanc is forced to touch physical files to aggregate info.

There has been some _very_ recent developments here that make newer versions of Orthanc faster for these queries. You may need to tweak your configuration to leverage these changes:

https://groups.google.com/forum/m/#!msg/orthanc-users/y1N5zOFVk0M/aR1A-gmaBwAJ

(Thanks to @swederik for tipping me off to these updates. You'll also see several familiar OHIF community members advocating for this change in-thread.)
