### ISSUE TITLE
cannot use measurements

### ISSUE THREAD

**Issue by fiona3668** [OHIF/Viewers#1493]
Hi guys. 
We are students and trying to do some projects on OHIF. 
For now we just down load Lesion Tracker on our PC. When we upload some DICOM files on Archive and displace the image on Lesion Tracker, the measurements button can't be used.
![image](https://user-images.githubusercontent.com/57859067/76134488-91f96400-5fd3-11ea-9f81-4a415f81c613.png)
Why this happens? Is that because the time point doesn't match? How can we solve this problem?

**Description**

**Comment by dannyrb** [comment]
:wave: Hello @fiona3668,

Always great to hear from real-world users of the OHIF Viewer. I believe you need to view a baseline study that has a linked/comparison study, but I'm not as familiar with our Lesion Tracker instance as I should be.

We have on our short-term roadmap the ability to compare and create DICOM SR + PDF Reports for most use cases previously covered by Lesion Tracker. These features would be available in a "Basic Viewing" mode for our now much more extensible version of the Viewer.

What are the key features you need for your use case?

**Comment by fiona3668** [comment]
For now just to do some easy segmentation and save it.
