### ISSUE TITLE
relative urls for viewer config

### ISSUE THREAD

**Issue by knopkem** [OHIF/Viewers#1494]
Hi, 
tried to find the answer in the docs and issue section but could not find anything.
When hosting the standalone viewer static files on a server that also acts as a dicomweb endpoint it would be nice if one could just use relative urls, e.g.

`dicomWeb: [
      {
        name: 'PROXY',
        wadoUriRoot: '/wado',
        qidoRoot: '/rs',
        wadoRoot: '/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        enableStudyLazyLoad: true,
      },
    ],`
But that doesn't seem to be supported. What are the chances that a PR with this goes through? Not sure if this is needed for anyone else but I believe it wouldn't hurt to have. What do you think?

**Comment by dannyrb** [comment]
I'm not opposed to this. The tricky part is that our DICOMWeb usage is spread all over. Ideally, if we consolidated, changes would be smaller and easier to merge/maintain.

If we saw a PR come through that was unit tested, small, and a easy to review; we would be hard pressed not to accept it.

**Comment by swederik** [comment]
Yeah I agree. I'm actually kind of surprised that doesn't work already. What happens when you try it? Where is it sending the requests?

**Comment by knopkem** [comment]
Thanks for the quick replies. So after testing a bit more it mostly works, but with a small quirks.
For relative URLs not using the prepending slash is mandatory as otherwise it tries to use it as an absolute URL (this actually makes sense, I was under the impression that leaving out http(s):// would be enough though, as I have seen this usage somewhere else). Anyway, when using qidoRoot: '/rs' it works on study level but seems to prefix  'viewer' for any other route (series level, metadata, wadouri etc.). Example: 
study level: http://localhost:5000/rs/studies/... 
series level: http://localhost:5000/viewer/rs/studies/.../series
This isn't too critical for me as I can just rename my routes, but should be addressed. I will see if I can fix this (but this might take some time, digging through the code)
