### ISSUE TITLE
sopInstanceUid always undefined

### ISSUE THREAD

**Issue by trung1704ptit** [OHIF/Viewers#1495]
Hi there,

We want to check the currentImageIdIndex of stack, but always get undefined.
In file: "/extentions/cornerstone/src/OHIFCornerstoneViewport.js"

`    if (sopInstanceUid) {
      const index = stack.imageIds.findIndex(imageId => {
        const sopCommonModule = cornerstone.metaData.get(
          'sopCommonModule',
          imageId
        );
        if (!sopCommonModule) {
          return;
        }

        return sopCommonModule.sopInstanceUID === sopInstanceUid;
      });

      if (index > -1) {
        stack.currentImageIdIndex = index;
      } else {
        console.warn(
          'SOPInstanceUID provided was not found in specified DisplaySet'
        );
      }
    }`

The sopInstanceUid always get undefined. We follow the code to fix it, but cannot figure out where it   was wrong.

**Comment by dannyrb** [comment]
This PR cleans up metadata usage: https://github.com/OHIF/Viewers/pull/1481
I recommend keeping an eye on it.

My best guess is that you're butting up against the same issues that caused @JamesAPetts to pursue his PR.

**Comment by JamesAPetts** [comment]
Yeah its likely this is a WADO-RS / WADO-URI metadata fetching issue, if you can try using the fix later today when its pushed to master and report back that's be awesome.

**Comment by JamesAPetts** [comment]
That PR is merged, so feel free to give it a test.

**Comment by trung1704ptit** [comment]
Thank you, I see it works well now
