### ISSUE TITLE
Is it any way to Freehand tool data add in Measurement panel List?

### ISSUE THREAD

**Issue by Vishal568** [OHIF/Viewers#1496]
> Can we add freehand tool data add in measurement panel with Label, Description and Delete Action? Like ROI tool data shown in the measurement List panel.

>There is a problem with Handler when inserting data into the collection. When inserting the data getting error
> insert failed: Error: Handles must be an object

**Comment by dannyrb** [comment]
This is not currently supported. You can take a look at the `MeasurementTable` extension in the Viewer project folder, or at the new "MeasurementService" implementation that maps annotations to our internal format. The latter takes place in the cornerstone extension's `preRegistration` hook
