### ISSUE TITLE
Help with adding callback for cornerstone tool

### ISSUE THREAD

**Issue by sinanmb** [OHIF/Viewers#1503]
Hi,

I would like to add a callback to the Probe tool in order to display a popup after the click on the viewport, (similar to the dialog modal that shows up for the arrowAnnotate tool). I have created a custom cornerstone tool and am looking for pointers on how to setup the callback to open the dialog modal and prompt the user to select a location/description for the measurement.

Thank you

**Comment by dannyrb** [comment]
As this question is specific to cornerstone-tools, I'm going to keep the issue in that repository open and close this one. When/if the time comes you need assistance wiring up your custom tool to the cornerstone-tools extension or in a custom extension, you are more than welcome to create a new issue in this repository.
