### ISSUE TITLE
Where i can get more information about how to fill config to dicomWeb?

### ISSUE THREAD

**Issue by marcosguti** [OHIF/Viewers#1507]
currently i'm starting react PWA site to show DICOM images but i don't know how to configure correctly params to dicomWeb, i want to know what represents each parameter in config like (name, wadoUriRoot, qidoRoot, wadoRoot , ....) my goal is host files in some aws folder and render list of my images like https://viewer.ohif.org/, in what field i should add my cloud url?

**Comment by dannyrb** [comment]
PACS (Picture Archiving and Communication System) implement [DICOMWeb](https://www.dicomstandard.org/dicomweb/). The "roots" are the base endpoints/URLs where we can expect to find the RESTful DICOMWeb implementation.

Example configuration files can be found in this directory: https://github.com/OHIF/Viewers/tree/master/platform/viewer/public/config

If you do not have a PACS, an alternative is using the "Standalone Viewer" that can be powered by a JSON file/route that's specified with a query string parameter.

Old Format: https://github.com/OHIF/Viewers/issues/891
New Format: https://github.com/OHIF/Viewers/issues/1500

**Comment by sedghi** [comment]
https://docs.ohif.org/configuration/configurationFiles
