### ISSUE TITLE
Support of combining data from multiple DICOMweb sources in a single viewer instance

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1512]
## Request

**What feature or change would you like to see made?**

I'd like to be able to combine individual series that are stored on different DICOMweb stores into a single Viewer instantiation.

**Why should we prioritize this feature?**

There are several use cases where this might be very helpful. I think the use cases below are very common, and users will need this functionality pretty soon (we already have examples where this would help a lot):
* visualization of analysis results for public collections: Google Healthcare is hosting a copy of TCIA public collections. Annotations or analysis results produced by individual users/projects will have to be stored in a DICOM store separate from the collection store. With the current capabilities of OHIF Viewer, source collection will need to be replicated to allow visualization of those. Some of those collections are VERY large (e.g., [LIDC-IDRI](https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI#f633413761b746ff9e49dd8f0d5b679d) is 125Gb). There is a very real and specific dataset of LIDC annotations that motivates this use case, see [here](https://wiki.cancerimagingarchive.net/display/DOI/Standardized+representation+of+the+TCIA+LIDC-IDRI+annotations+using+DICOM).
* even if data size and replication is not a concern, separate DICOM stores can help in logically organizing analysis analysis results and annotations produced by several projects for the same image collection.

Specifically for IDC, it is reasonable to expect that there will be fully resolved location for the individual series that need to be included in the visualization. Those can be populated by the cohort search interface. The Viewer task would be just to take those and visualize the result as a collection of series.

**Comment by dannyrb** [comment]
This issue is likely blocked until we have support for configuring modes, routes, and route templates. As currently prioritized, that's likely a month or two out, and may live on a feature branch until as late as August. If you need this before then, we should discuss how we might expedite, and make sure that any changes here aren't lost when the feature branch is rolled out.

You could use a "Higher Order Component" (HOC) to wrap the existing Viewer route, but add support for additional query string or route template parameters. You would then use those parameters to query for the data as you see fit, and map the data to the viewer routes "viewmodel".

**Comment by fedorov** [comment]
For many reasons, including this limitation of OHIF, we will most likely set up a single DICOM store for all IDC data in the MVP. This issue should not be in the critical path for IDC MVP.

I think we should keep it as priority, since I think in the general  case we will want to support users that have image analysis/annotation results in their own stores with the imaging data in the IDC store.

**Comment by pieper** [comment]
We should probably do a smoke test to see how well the dicom store scales to this data size (e.g. how does the size impact query times).  It would be pretty simple to create a scratch store and then upload all the tcia data from gcs for testing.

**Comment by JamesAPetts** [comment]
Say we have two dicomweb servers in our configuration, if a series exists in both stores do we fallback to the first in the array of dicomweb servers? I.e. have a priority list?

**Comment by JamesAPetts** [comment]
When you STOW which one do you STOW back to?

**Comment by JamesAPetts** [comment]
Do we want to have some UI to show which scan came from where?

**Comment by fedorov** [comment]
Great questions. Although full functionality answers will need more thought, for the initial iteration, I think it is fair to assume that sources are curated, and no duplicates will exist. Also, for MVP we assume read only access so nothing will be tired back.

**Comment by pieper** [comment]
As a common use case, I would want to be able to designate just one source dataset (the images, generally speaking) vs the annotations (measurements and segs).   For now they can both be read only but the idea would be to save out annotations to your own database for further analysis.

**Comment by fedorov** [comment]
Per discussion with @Punzo today, considering there's work in this direction in Slim being explored between @igoroctaviano and @hackermd, and that the urgency of being able to avoid data replication is much greater for slide microscopy data, we should probably wait until a solution in Slim is developed, and then use that experience to add support in OHIF.

**Comment by Punzo** [comment]
@igoroctaviano summary from the multiple/dynamic discussion

Use case:
Reading data from multiple servers. Wwe can start from 2, but we would need to generalize to N. 

NOTE: writing segmentation to another server use case is out for the moment.

Steps to implement:
1) implement reading from multiple servers in DICOMwebclient library
2) add the servers in the config
3) add UI to select the servers 
4) using the url to select the servers -> we need a generic solution, not only using google.

**Comment by manoocher** [comment]
> @igoroctaviano summary from the multiple/dynamic servers discussion
> 
> Use case: Reading data from multiple servers. We can start from 2, but we would need to generalize to N.
> 
> NOTE: writing segmentation to another server use case is out for the moment.
> 
> Steps to implement:
> 
> 1. implement reading from multiple servers in DICOMwebclient library
> 2. add the servers in the config in a static way
> 3. add UI to select the servers dynamically
> 4. using the url to select the servers -> we need a generic solution, not only using google.

Is there any update about this, glad to see it in progress now.

**Comment by fedorov** [comment]
I know we've been going back and forth about this, but I want to refocus this discussion to the original issue and specific use case where we need support.

We have an analysis use case where we perform segmentation for a large number of CT series, and we want to visualize those series. It is absolutely not practical (and very expensive) to replicate the CT series segmented. As part of the processing notebook, we are creating a separate DICOM store that will contain segmentations. Here are the constraints and expectations:
* There will be only 2 DICOM stores. 
* The user will know exactly the locations of those stores at runtime. 
* The user will have full control and complete understanding of what is located in which DICOM store. 
* The user will be able to specify via explicitly via URL fully resolved location of the study in the first DICOM store that will have images, and fully resolved location of the (same as defined by StudyInstanceUID) study in the second store that will have the segmentations. 
* The user will want to see the content of the study loaded from 2 stores in the viewer without the need to differentiate in the interface the specific DICOM store from where a given series of the study is coming from.

**Comment by hackermd** [comment]
> The user will not need to write anything to either of the DICOM stores through the viewer. All writing of the segmentations to the DICOM store will happen outside of the viewer. The segmentations store can be expected to be fully populated at the time viewer is invoked

There will be situations, though, were data will be stored. The question then arises which store shall be used. Both? Only one of them? Which one?

**Comment by hackermd** [comment]
> The user will be able to specify via explicitly via URL fully resolved location of the study in the first DICOM store that will have images, and fully resolved location of the (same as defined by StudyInstanceUID) study in the second store that will have the segmentations

If we can make the assumption that one store will serve as the "primary" store for source images and the other store(s) as "secondary" score for annotations/segmentations, then this would potentially simplify things a lot. The "primary" store would then be used to search for studies. The "secondary" store would then have to be searched for a selected study. If we can further assume that the results don't have to be merged (i.e., images will only be queried and retrieved using the "primary" store and annotations/segmentations will only be queried and retrieved using the "secondary" store), then we can use separate DICOMweb client instances and they don't necessarily have to be aware of each another.
This will mean, however, that any annotations/segmentations in the "primary" store would be ignored.

**Comment by fedorov** [comment]
This issue has been available in the IDC fork for some time now, and seems to work well, so I am closing this issue.
