### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1514]
### Describe the Bug

Once user navigates to Study Viewer page, the TypeError exception is thrown in the browser's console.
This is happening only for some studies (`MISTER^MR`). If user selects a CT Study, PDF file or an SR, the error won't occur (`Fall 2`, `MISTER^CT`).

This error is a blocker for the test automation execution in the CI pipeline.

<img width="1680" alt="Screen Shot 2020-03-12 at 14 09 27" src="https://user-images.githubusercontent.com/13245529/76548961-54cb2100-646e-11ea-89d1-8ee8dfaf47de.png">

### Steps to Reproduce

1. Navigate to OHIF Viewer
2. Open the browser console
3. Search and select Patient Name: `MISTER^MR`
4. Verify that the Exception message is thrown in the console
5. Navigate back to the Study List
6. Select Patient Name: `Fall 2` or `MISTER^CT`
4. Verify that the error won't happen

### Expected Result

1. User should be able to open the study without errors.

### Actual Result

1. When user open the study, the error is displayed:
```
Uncaught TypeError: Cannot read property 'toFixed' of undefined
    at textBoxText (app.bundle.68b71d4724d54d9697d2.js:48163)
    at app.bundle.68b71d4724d54d9697d2.js:48143
    at app.bundle.68b71d4724d54d9697d2.js:25040
    at _loop (app.bundle.68b71d4724d54d9697d2.js:48096)
    at LengthTool.renderToolData (app.bundle.68b71d4724d54d9697d2.js:48149)
    at app.bundle.68b71d4724d54d9697d2.js:26253
    at Array.forEach (<anonymous>)
    at HTMLDivElement.onImageRendered (app.bundle.68b71d4724d54d9697d2.js:26251)
    at triggerEvent (app.bundle.68b71d4724d54d9697d2.js:21595)
    at app.bundle.68b71d4724d54d9697d2.js:18276
```

**Comment by dannyrb** [comment]
Let's go on a debugging journey

## Danny's Debugging Journey

git bisect is nice, but is tricky when you're testing the commits of a dep, not the commits of the actual project itself. Good ol' yarn link in the monorepo root.

4.12.4 is bad
4.12.3 is bad
4.12.2 is bad
4.12.1 is bad
4.12.0 is bad

Okay. What is actually going on here. Restored length annotations have a "length" property value of undefined. This is an SR thing. Let's debug.

What's the value in the SR?
Can we see it pre-parse?
How does the DCMJS `generateToolState` handle it?
Can we see it post-parse?

SR Should have value at...
Measurement Group -->  Measured Value Sequence --> Numeric Value (is not set)

Is the issue on save....
"Updates measurement and saves"

**Everything begins working again**

## Hypothesis:

- CI Rapidly creates new annotation
- While cached stats is still calculating, CI initiates DICOM SR save (no value for length)
- All future CI runs fail

## Hardening/Fix(es)

- Gracefully handle "no value" measurements in SRs
- Preventing persist/save of "no value" measurements

**Comment by dannyrb** [comment]
PR to "gracefully handle" no value measurements in at least the length tool were pushed down stream.
