### ISSUE TITLE
csTools dies after changing the layout disposition when the active tool is in an intermediate state

### ISSUE THREAD

**Issue by arthur-miller** [OHIF/Viewers#1517]
### Describe the Bug

Cornerstone tools dies after changing the layout disposition when the active tool is in an intermediate state.

### What steps can we follow to reproduce the bug?

1. Choose any study.
2. Set the layout to 2x1.
3. Select the Angle tool.
4. Click on the second viewport.
5. Set the layout to 1x1.

![viewers](https://user-images.githubusercontent.com/58273771/76569175-3cb8c900-6491-11ea-83ea-3f01dbc41af3.gif)

After that point, no tools will work anymore.
I will be happy to make a PR for this if you help me find out what the cause is 😬.

**Comment by dannyrb** [comment]
👋 Hi @arthur-miller 
When a `cornerstone-tools` annotation tool is not finalized, it sets an internal property that prevents new click events from triggering the eventDispatcher. It looks like we need to check for `cornerstonenewimage` and `cornerstoneelementdisabled` events to unset this check.

Here are some examples where we set/check the `isToolLocked` property:
- https://github.com/cornerstonejs/cornerstoneTools/search?q=isToolLocked&unscoped_q=isToolLocked

The places that need to listen for those events are the same places where we set `isToolLocked = false`, namely "manipulators" (what we call interactions with annotation "handles"):

- https://github.com/cornerstonejs/cornerstoneTools/blob/e38e2f5c81b0f83cca5a29a03334bee287028a8a/src/manipulators/moveNewHandle.js#L178
- https://github.com/cornerstonejs/cornerstoneTools/blob/e38e2f5c81b0f83cca5a29a03334bee287028a8a/src/util/findAndMoveHelpers.js#L120

Another consideration is "how do we clean up unfinished annotation data?" as you orphan it by doing this.

---

I hope that at least provides some context. I'm open to discussing workarounds or alternative fixes.

**Comment by arthur-miller** [comment]
Hello Danny!

Thank you for the guidance. I'll make a PR on Cornerstone Tools in the next few days.

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
