### ISSUE TITLE
"Flip H" and "Flip V" are not reseting the image reference after performing "Rotate Right"

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1519]
### Describe the Bug

After rotating the image, `Flip H` and `Flip V` don't reset their orientation and the image transformation is the opposite. For example, after the rotation, once user clicks on button `Flip H` the action performed on the image is a vertical flip.

![bug3](https://user-images.githubusercontent.com/13245529/76576437-d89e0100-64a0-11ea-8375-1c10f8a2b4ba.gif)

### Steps to Reproduce

1. Go to a study
2. Select tool Rotate Right
3. Verify that the image was rotated 90 degrees
4. Select Flip H
5. Verify that the image was vertically flipped instead of horizontally.

### Expected behavior

1. The Flip tool must be applied to the current image orientation.

### Actual behavior
1. Flip is being applied to the initial image orientation instead of the current image orientation.

**Comment by dannyrb** [comment]
This would be an issue in `cornerstone-core`. Good catch!
I'm not sure these tools are commonly used together, so this is likely low priority, but good to be aware of.

**Comment by swederik** [comment]
Thanks for the report, but this is expected behaviour, it is flipping based on the image's original orientation.
