### ISSUE TITLE
Support for rendering different measurements in different viewports

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1522]
RE: https://github.com/OHIF/Viewers/issues/1373#issuecomment-598722322

For IDC we need support for displaying the same scan in two viewports and displaying different RTSTRUCTs, SEGs and cornerstone planar measurements in each.

> In Slicer there is a pop up menu with a check box per viewport, but it might also make sense to have a drag and drop option.

![](https://user-images.githubusercontent.com/126077/76625367-75968380-650d-11ea-9ec8-cfa224139dea.png)

What is the best way to do this in OHIF in an extensible way?

**Comment by dannyrb** [comment]
@swederik and I have recently discussed something similar. Currently, most tools use the default global `imageIdSpecificToolStateManager`. We could create/destroy them per viewport, and designate their usage for data like this (restored / 3rd party).

Tool's are also fairly flexible. In the render loop, we can examine ToolState or use a callback to make determinations on what should be rendered.

Taking a step back, we may want to discuss how we want to structure this with the MeasurementService, and if we expect this to impact vtk viewports.

**Comment by sedghi** [comment]
@fedorov @igoroctaviano Do you want this to be open?

**Comment by fedorov** [comment]
This is v2, and I think this can already be done at least to some degree.
