### ISSUE TITLE
Is there a function to scroll by series in ohif viewer?

### ISSUE THREAD

**Issue by rjsgml5698** [OHIF/Viewers#1528]
Hello!

Is there a function to scroll by series in ohif viewer?

I want to scroll by series if there are more than one dicom series (not each)

**Comment by dannyrb** [comment]
What have you tried? Technically, cornerstone supports this, but we default to loading a "display set" per viewport -- not multiple series per viewport. How we split/determine display sets is based on `sopClassHandler` logic. Where a display set is really:

many series in --> collection of grouped imageIds out

There are "commands" to switch iterate the active viewport through displaysets
