### ISSUE TITLE
Segmentation panel is confusing when you have on segmentation on a scan and not on the other.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1530]
Addressing [this issue](https://github.com/OHIF/Viewers/issues/1391#issuecomment-599764955).

The segmentation panel currently behaves as follows:
- When a series with associaited segmentations is loaded into the viewport, the most recent segmentation is loaded by default.
- The drop down menu shows segmentations for the current viewport.
- If a series has no segmentations associated with it, the segmentation panel is empty.

In order to address the confusion brought up in the above issue, we could improve the second and third points:
- The drop down menu shows all segmentations present in the study. If a segmentation is selected, the associated series + segmentation is loaded into the viewport.
- If a series has no segmentations associated with it, the segmentation panel would still display a drop down for segmentations, allowing you to easily navigate to the series of interest.

@pieper @fedorov

**Comment by fedorov** [comment]
Yes, I believe this would be a more intuitive interface.

> If a segmentation is selected, the associated series + segmentation is loaded into the viewport.

What is going to be the behavior when a segmentation does not reference the source series? Note that it is also possible for a segmentation to reference multiple series.

**Comment by JamesAPetts** [comment]
> What is going to be the behavior when a segmentation does not reference the source series?

Currently its not associated with any displaySet and not visible. Maybe it should show in the list greyed out with an on-hover that says "refenced data is missing" or something?

> What is going to be the behavior when a segmentation does not reference the source series?
We discussed before that for the MVP we are assuming an individual struct/seg references only one series. Should we start looking into relaxing this assumption for IDC?

**Comment by fedorov** [comment]
>> What is going to be the behavior when a segmentation does not reference the source series?
>>
> We discussed before that for the MVP we are assuming an individual struct/seg references only one series. Should we start looking into relaxing this assumption for IDC?

No, I didn't mean to imply that! Just wanted to clarify the behavior. I think there's enough on your plate already to relax the assumptions, and, practically, I don't think this will happen often (I can't think of a single dataset on TCIA that has this issue).

**Comment by sedghi** [comment]
@fedorov I'm cleaning up issues for OHIF. Do you need this to be open?

**Comment by fedorov** [comment]
This issue was about v2, and we have no concerns or plans to refine SEG interface in v2.
