### ISSUE TITLE
Segmentation UI when viewing segmentations in MPR mode.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1531]
Currently switching the segmentation/changing segmentation settings does not apply whilst in MPR mode, until you leave MPR mode and return.

This ticket would be done after #1458 add the following whilst MPR view is open:
- Segmentation hide/show.
- Jump to segment (puts crosshairs on the volumetric centre and jumps all views to the appropriate slices).
- Live update of changeing e.g. opacity, etc.
- Switching segmentation should load the new segmentation into the viewport.

**Comment by JamesAPetts** [comment]
@pieper @fedorov

**Comment by sedghi** [comment]
I don't think this happens in master any more. 
@fedorov  can we close this?

**Comment by fedorov** [comment]
This was about v2, and we refined v2 seg interface to our liking. A while ago.
