### ISSUE TITLE
Improving first display time

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#1536]
Hi all,

I come back again on the image rendering time.
We made a HUGE improvement since the first time I used OHIF when OHIF was querying the full metadata at the study level and where Orthanc DicomWeb was affected by performance issue that have been solved with the recent dicomweb 1.1 release.
On my server, the first image rendering time using Orthanc dropped from 50 seconds to 5 seconds, so this is a very significant performance improvement.

However it might still have a small performance improvement in OHIF side, that could reduce these 5 seconds before the first rendering.
OHIF start by making a /series call to fetch series details, for this one the answer is extremely fast  (50ms on my server).
And then for each series OHIF call the /metadata API that calls for all instance metadata. 
Here there is a difference with Orthanc and DCM4CHE, Orthanc do not store all metadata in his internal database, it read the original source file which is I/O consuming in the hard disk, thus in my server (HDD) the /metadata of a CT serie (600 slices) is around 5 seconds.
There is not too much we can do about it (except retrieve the metadata at the instance level, slice by slice for progressive rendering but I guess you have some reason you didn't choose the instance level)

The point I think OHIF can be a bit faster for the first rendering is : why OHIF have to wait for the first serie's metadata answer to show the series thumbnail series in the left column ?
The study/UID/series API already returns all series descriptions, series numbers, number of slices.
I guess it is enough to display the all thumbnails series before calling the first /metadata API that is much more time consuming.

So the order might be
/series apis
get 1 thumbnail of each series 
=> display all series thumbnail in the left column
then call the /metadata API of the first serie (and you already have the waiting wheel on the thumbnail to show that there are some data being fetched).

All of this is to reduce the first rendering, for now OHIF display an almost black page (except OHIF menu bar) during 5 seconds. During these 5 seconds the user do not know if there is a process pending so the app look like it have crashed (while it's not).

These 5 seconds probably do not exist with DCM4CHE because DCM4CHE duplicate a lot of data in it's internal database.
However the slowness of Orthanc might highlight some area of optimization that could benefit for all backends.

Best regards,

Salim

**Comment by dannyrb** [comment]
@salimkanoun, I recommend trying out the new setting exposed in #1581. @swederik has also recently completed a change that allows thumbnails to show sooner. Anything faster (for thumbnails) will be difficult to justify until our redesign takes in later this year.

@ckedar has recently completed some code-splitting that nets us a faster first "time to first paint". @swederik has a summary of some remaining areas we could code-split. The updates we have planned for "modes" and "routes" also allow us to trim a lot of fat from the default build, and create more natural splitting points:

https://github.com/OHIF/Viewers/pull/1575#issuecomment-608391935

**Comment by salimkanoun** [comment]
Very good improvement, I confirm the first rendering in now faster, the loading is more progressive and deliver the information as soon as they are ready.
Limiting the concurrent metadata is also a very good idea on a slow HDD server.

Thank you @swederik @ckedar @dannyrb , really great work !

Best regards,

Salim
