### ISSUE TITLE
Add configuration option to restrict editing of DICOM nodes

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#154]
See
- https://groups.google.com/forum/?nomobile=true#!topic/cornerstone-platform/GAj4kmfffIU
- https://groups.google.com/forum/?nomobile=true#!topic/cornerstone-platform/BSh1Z99oJ5Q

**Comment by dannyrb** [comment]
I don't know how possible this is without a custom server based API that interacts with the PACS and imposes restrictions.

We offer Keycloak and OpenID Connect as an option for general auth and app level permissions, but DICOMWeb requests "just work" so long as you're authenticated in our UAC recipe.

If there's a way to do this without adding a layer, more than happy to assist, but I would need guidance. If not, then this may be outside the scope of what this project is trying to provide, and you likely need some custom software development.
