### ISSUE TITLE
Overlay Text Lost for thai character

### ISSUE THREAD

**Issue by java2guide** [OHIF/Viewers#1541]
Hi,
Hope you are doing good. Currently I have deployed your latest ohif viewer v2.0 and working good except overlay text lost for thai characters. I am trying to load study files from a json path
like - ?url=http://localhost/study/*.json files(Json file contains thai charters for patient name).
![image](https://user-images.githubusercontent.com/818409/77113396-55128000-6a5d-11ea-8cb1-6897edc8fa4e.png)

So if guide me to solve the issue I will be really grateful to you.

Thanks
Surajit

**Comment by dannyrb** [comment]
Are you able to test this in isolation on `react-cornerstone-viewport`? It might make it easier to identify where exactly the issue is happening.

**Comment by java2guide** [comment]
Thanks for you reply. Without react-cornerstone-viewport it can not initialize images. Only thumbnails are available.
