### ISSUE TITLE
Import from @ohif/ui in a unit test inside the viewer module

### ISSUE THREAD

**Issue by sinanmb** [OHIF/Viewers#1547]
Hi,

I built a custom component that imports the RoudedButtonGroup component from '@ohif/ui' and it is is working as expected. 
I'm writing a unit test for it and the test fails at the line where RoudedButtonGroup is imported from @ohif/ui:

`Cannot find module '@ohif/ui' from 'LandmarkLocationButtonGroup.js'`

How can I specify to Jest where to find the @ohif/ui module?

**Comment by dannyrb** [comment]
Great question. Are you using the monorepo setup? If so, the symlinks it puts in place should resolve the package (I think). If you're not, you may need to setup custom module resolver logic in your jest config.

**Comment by sinanmb** [comment]
Hi @dannyrb, thank you for getting back to me! Yes I am using the monorepo setup.
