### ISSUE TITLE
DICOM node configuration via User Interface not working properly

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#155]
See https://groups.google.com/forum/?nomobile=true#!topic/cornerstone-platform/uKsV7DQNcrs

**Comment by dannyrb** [comment]
Unfortunately this issue has grown stale, and with the release of our most recent major version, it is unlikely that we will have the bandwidth to address this issue for our `v1.x` branch. 

If you find that this has not yet been addressed in our `master` branch, you are more than welcome to create a [GitHub Issue](https://github.com/OHIF/Viewers/issues/new) to request or discuss it. If you're curious to see what we have planned in the near future, you can [check out our roadmap](https://ohif.canny.io/), and [read our docs](https://docs.ohif.org/).
