### ISSUE TITLE
[W/L tab Presets] Issues with W/L Presets

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1551]
Tracked as `OHIF-60`

### Issue 1: User can't add new W/L presets

User is not able to add new W/L presets in the Window Level tab.

![ohif_issue_windowlevel](https://user-images.githubusercontent.com/13245529/77379225-f1d36700-6d56-11ea-8cf3-cbdc2a8f84aa.gif)

**Steps to Reproduce:**

1. Visit: https://viewer-dev.ohif.org/viewer/1.2.840.113619.2.5.1762583153.215519.978957063.78
2. Click on Options > User Preferences
3. Select the "Window Level" tab
4. Click on any empty field
5. Try to type anything on it
6. Verify that user is not able to type into any of the empty fields
7. Try to click on the arrows to increment the values on `Window` field or `Level` field
8. Verify that user is not able to add any value into those fields

**Expected Result:**

User should be able to add new W/L presets in the Window Level tab.

### Issue 2: User can't reach/select preset 10. Should we replace it by 0?

We have 2 issues here: 
1) `Preset 10` doesn't exist in the Hotkeys list
2) User can't type `10` on the viewer page. Once he/she starts to type `1` it will select the `preset 1` and it will ignore the `0`. My suggestion is to replace the `Preset 10` by `Preset 0`.

Therefore, as per my suggestion: we should add the `W/L Preset 0` in the Hotkeys list and replace the `preset 10` by `preset 0` in the Window Level tab. (Please check images below)

<img width="909" alt="Screen Shot 2020-03-23 at 22 18 57" src="https://user-images.githubusercontent.com/13245529/77378856-fea38b00-6d55-11ea-900d-62f3c3b53bc7.png">

<img width="917" alt="Screen Shot 2020-03-23 at 22 18 49" src="https://user-images.githubusercontent.com/13245529/77378862-0105e500-6d56-11ea-999c-48655907ca41.png">

### Issue 3: "Reset to Defaults" button doesn't reset the information under Window Level tab

When user changes any value under the Window Level tab and clicks on "Reset to Defaults" button, nothing happens and the values are not restored.

**Steps to Reproduce:**

1. Visit: https://viewer-dev.ohif.org/viewer/1.2.840.113619.2.5.1762583153.215519.978957063.78
2. Click on Options > User Preferences
3. Select the "Window Level" tab
4. Edit `Description` 1: "Soft tissue ASDAASD"
5. Edit `Window` 1: "1550"
6. Edit `Level` 1: "444"
7. Click on `Reset to Defaults` button
8. Verify that default values were not restored
9. Click on `Save` button
10. Reopen "User Preferences" option and select "Window Level" tab
11. Click on `Reset to Defaults` button
12. Verify that default values were not restored

**Expected Results:**

1. Once user clicks on `Reset to Defaults` button, all values in the selected tab should be restored.
2. Once user clicks on `Reset to Defaults` button and the Window Level tab is selected, all values  should be restored in this tab

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
