### ISSUE TITLE
Cannot export single image with measurement

### ISSUE THREAD

**Issue by trung1704ptit** [OHIF/Viewers#1554]
I everyone,
I have an issue that I cannot export image with label. In app now, we can show all label 1 single image, but we want to show one label on one image.

example with 1 dicom image I have 3 labels. So how can I show image with label one by one.
the result will have 3 image with one label on each.

How can I do that, please show me the solution, thanks

**Comment by dannyrb** [comment]
It's tricky. You either need to have a different tool instance per label, or create a custom tool that allows you to set the visibility per label in the toolState schema, and then conditionally render based on that visibility flag.

You could also push the concern "up" a layer, and have the application swap toolState in and out depending on what you would like to be visible.
