### ISSUE TITLE
Improve error handling / feedback for Standalone Viewer when incorrect URLs are provided

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#156]
See https://groups.google.com/forum/?nomobile=true#!topic/cornerstone-platform/Wmtkyk6BJck

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now.
