### ISSUE TITLE
unable to see ohif viewer after logging through keycloack

### ISSUE THREAD

**Issue by akshyakumarsubudhi** [OHIF/Viewers#1561]
Hii
we followed the [Nginx + Image](https://docs.ohif.org/deployment/recipes/nginx--image-archive.html#setup) react documentation to set up Nginx. we are able to run our Orthanc on the following link http://127.0.0.1/pacs-admin but we are unable to see the study list in  http://127.0.0.1. while accessing to this link we are getting 403 forbidden
![png](https://user-images.githubusercontent.com/34866440/77616180-1007b580-6f57-11ea-8cf5-cc2fc6daaa47.png)

we are also trying to enable the login page through keycloack but after logging in we are facing the same issue 403 forbidden. we followed this [User Account Control documentation](https://docs.ohif.org/deployment/recipes/user-account-control.html#user-account-control) 
can anyone please help in solving this issue

**Comment by dannyrb** [comment]
Hoping you figured this out, @akshyakumarsubudhi! If you did, please don't hesitate to share the resolution so that others may benefit ^_^
