### ISSUE TITLE
French translation ?

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#1562]
Hi there,

I noticed that OHIF documentation has a french sample of translation (https://docs.ohif.org/viewer/internationalization.html#how-to-set-a-whole-new-language)

However I didn't find any FR folder in the i18n repository.

Is there a French translation somewhere or is it something missing?
If missing I will do a PR to add French translation,

Best regards,

Salim

**Comment by swederik** [comment]
We don't have one yet! You can start with this link: https://www.locize.io/register?invitation=Nj8jRPaFKYwtIfNZ6Y5GVOJOpeiXNAdVuSiOg9ceaiveP6uF6y1wVXM9lgfKoYZX

I'll create a new link once those translation strings are done.

Thanks!

**Comment by salimkanoun** [comment]
Thanks, i started to fill it
There are some item that have some variable pattern like "$t(Common:Reset) to Defaults"
How should i write the translation ? Did i need to put the "$i(Common:" as well ?

Also i let some item in english, for exemple "play" would be "jouer" in french, but it is very uncommon to use it in software, usually the english word is kept.

**Comment by dannyrb** [comment]
@salimkanoun I'm not a huge of how we chose to compose translations. You can likely forego using them. I'll speak with @mirnasilva about creating an improved contributor guide with best practices.

**Comment by swederik** [comment]
Agreed. I think adding the translations together is unlikely to work properly in a lot of situations.

**Comment by salimkanoun** [comment]
Ok I think I got it, they are tags to reuse some already translated item in another sections (some word a re used in several sections)
So I filled all items.
If you need another translations in French don't hesitate,

Salim

**Comment by swederik** [comment]
Voilà!

<img width="1058" alt="Screenshot 2020-04-07 09 54 26" src="https://user-images.githubusercontent.com/607793/78647659-2d277700-78bb-11ea-8ec5-a0016b2204f9.png">

**Comment by salimkanoun** [comment]
@swederik That's cool ! 
There are some items not translated : 
The options panels are not translated : About and preference GUI are still in english only
Download, anotate and save measurement buttons are also not translated.

Probably some of this component are more recent, anyway the day you will want to update the translations for the new interfaces I will handle the french one.

Best regards,

Salim

**Comment by sylvainb31** [comment]
Hello,
I am using the OHIF Viewer and I need to change the missing translations (download, measurements ...).
Can you give me access to the link to change them ?
Thanks for your help.

Best regards,

Sylvain
