### ISSUE TITLE
Cannot open labelling dialog immediately after using tool

### ISSUE THREAD

**Issue by trung1704ptit** [OHIF/Viewers#1563]
Hi everyone,

I try to show the labelling dialog immediately after using end of tool,

example when I using rectangle to draw in image, after draw, We want to show labelling immediately,
but when I set open it in onMeasurementAdded, it make site really slow. It really bad.

So how can we apply this. please let us know

**Comment by sinanmb** [comment]
Hey trung1704ptit, you need to create your own custom tool and add a callback to open a labelling dialog after the measurement has been placed, similar to how arrowAnnotate does it.
