### ISSUE TITLE
Segmentation loading is broken on master/`viewer-dev.ohif.org`.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1564]
Something recently broke the segmentation loading, and no segmentation info loads in the sidebar.

Example: https://viewer-dev.ohif.org/viewer/1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046

**Comment by dannyrb** [comment]
You can still view the seg if you:

- Drop first SR thumbnail into viewport
- Drop first imaging data thumbnail into viewport

(You may need to do this several times. This doesn't trigger the data to load, I think it just triggers a re-render, and if the data has completed loading, it shows.)

**Comment by dannyrb** [comment]
A 3rd party contribution cleaned up our accidental re-renders. We were doing 1000s unnecessarily. It's possible this state isn't tracked properly and just "happened to work" previously

**Comment by igoroctaviano** [comment]
> You can still view the seg if you:
> 
> * Drop first SR thumbnail into viewport
> * Drop first imaging data thumbnail into viewport
> 
> (You may need to do this several times. This doesn't trigger the data to load, I think it just triggers a re-render, and if the data has completed loading, it shows.)

@dannyrb / @JamesAPetts , just tracked this issue. It's because of a recent change in ViewportGrid, where the useEffect that calls loadAndCacheDerivedDisplaySets is watching only the viewportData prop, when watching studies as well, everything goes back to normal.

**Comment by dannyrb** [comment]
Were you able to track down the commit/PR?

I'm sure part of the issue is that `studies` makes entirely too much tracked/reactive.
