### ISSUE TITLE
Issue with tools when upload multiple file 

### ISSUE THREAD

**Issue by trung1704ptit** [OHIF/Viewers#1565]
Hi everyone,

In /local page I tried to upload multiple dicom files (Chest X-Ray).
Each file belong to one person. After that I use tools in tool bar, but all tool response too slow.
I mean really hard to draw in Viewer
When I upload 1 dicom file (Chest X-ray too) it works well.

I think it can be a bug.

Please test it.

**Comment by dannyrb** [comment]
Can you provide a clearer reproduction?

**Comment by trung1704ptit** [comment]
Hi @dannyrb ,

1. I go to /local page
2. I choose "upload files"
3. I select 10 files from 10 people, they are dicoms file about Chest X-ray (10 single files from 10 people)
4. I select tools in toolbar to draw something => tool can draw in view, but response quite slow, I mean tool moving quite slow on view

It can be a bug when we upload multiple single file.

**Comment by dannyrb** [comment]
@trung1704ptit, I can leave this open, but I unfortunately don't think this issue will be prioritized by the core team with our current bandwidth. If you make headway on identifying the cause and wish to submit a PR, I am more than happy to conduct a review & merge.
