### ISSUE TITLE
Provide some type of one-click deployment solution

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#157]
This is a pretty common request. We need some way for people to get the OHIF Viewer + a PACS up and running on a server easily.

- Docker?
- AWS Marketplace?

Open to suggestions (and pull requests!)

See https://groups.google.com/forum/?nomobile=true#!topic/cornerstone-platform/Tp2czNk3LV4

**Comment by pieper** [comment]
+1 for docker - could do a docker compose on top of dcm4chee.

**Comment by howardm** [comment]
I would appreciate this. I have an OsiriX Teaching File: http://207.254.60.104:3333

I'm not a techie but have installed items on my Digital Ocean droplet. It would be nice if I could have a viewer there to enable folks to view cases in my Teaching File in their browser.

The instructions here: https://github.com/OHIF/Viewers/wiki/Step-by-Step-installation-of-OHIFViewer-in-Ubuntu-14-and-above  are too cryptic for me   :-)  

I also cannot really determine whether they're applicable to my situation.

Howard

**Comment by kmader** [comment]
For one-click, binder works really well, but everything would have to fundamentally run inside a single Docker image and be viewable as a Jupyter Notebook but RStudio and JupyterLab both made interfaces to it. The main advantage would be you could deploy in one-click for free without having to install anything locally. @betatim might say this is a really ugly bad idea though

**Comment by kmader** [comment]
so far got Orthanc working and meteor installed

![image](https://user-images.githubusercontent.com/116120/36568654-151a6b42-182b-11e8-9d15-f5c9fc7f117a.png)

but the meteor site doesn't work since the proxy prepends a proxy/port-number to the URL path and thus all of the hard-code paths stop working
```
<script type="text/javascript" src="/packages/meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8"></script>
```
which should instead be
```
/proxy/3000/packages/meteor.js?...
```
but there must be ways to configure this

**Comment by kmader** [comment]
ROOT_URL doesn't seem to quite fix it, any advice is appreciated here: https://github.com/4QuantOSS/ohif_binder/issues/2 it seems close enough and binder is a great free compute environment

**Comment by EsrefDurna** [comment]
Hello,

Best way to accomplish this is probably docker compose. There is currently several docker-compose examples under docker folder.

FYI “docker-compose”

**Comment by dannyrb** [comment]
As @EsrefDurna has mentioned, we've added a fair bit of guidance for common deployment scenarios in our documentation. You can find a general overview and more specific recipes here:

https://docs.ohif.org/deployment/

These are mostly maintained as `docker-compose` files in `<project-root>/docker`. I am more than happy to review any new recipes or enhancements to the existing ones.
