### ISSUE TITLE
Error loading images using WADO-URI (v3.8.11)

### ISSUE THREAD

**Issue by tillmon** [OHIF/Viewers#1571]
The following Error occurs using WADO-URI:

`updateImage: image has not been loaded yet`

**Example:**

https://nqsxd.codesandbox.io/viewer/1.2.840.113619.2.30.1.1762295590.1623.978668949.886

**CodeSandbox: (v3.8.11)**

https://codesandbox.io/s/viewer-script-tag-nqsxd

**Comment by dannyrb** [comment]
![image](https://user-images.githubusercontent.com/5797588/78102028-401be200-73b7-11ea-87fd-51d42196cb47.png)

This issue is caused in `retrieveMeasurements`

We're trying to trigger an updateImage before an image has been rendered in an enabledElement.

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
