### ISSUE TITLE
Configuration loading via url parameter is broken

### ISSUE THREAD

**Issue by spalte** [OHIF/Viewers#1572]
### Bug Report
Since v3.7.8.10404, configuration loading via the url parameter is broken.

### Describe the Bug

When loading a configuration via the url query parameter, OHIF breaks.

### What steps can we follow to reproduce the bug?

1. Launch a local OHIF with docker
```
docker run --rm -p 3000:80 ohif/viewer:v3.7.8.10404
```
2. Open a web broswer to
``` URL
http://127.0.0.1:3000/viewer?url=https%3A%2F%2Fdemo.kheops.online%3A443%2Fapi%2Flink%2Fc2hyQTv1zZfe4JxO7aO7Ql%2Fohifservermetadata&studyInstanceUids=2.16.840.1.113669.632.20.1211.10000502993&seriesInstanceUids=1.3.12.2.1107.5.2.31.30222.30000007072005313478100001711
```
Which will load the local OHIF using a configuration provided by KHEOPS

#### Result
A screen saying *Error: "No study instance uids specified"*

### Expected behavior:

1. Launch a local OHIF with docker with the previous version of OHIF
```
docker run --rm -p 3000:80 ohif/viewer:v3.7.7.10368
```
2. Open a web broswer to
``` URL
http://127.0.0.1:3000/viewer?url=https%3A%2F%2Fdemo.kheops.online%3A443%2Fapi%2Flink%2Fc2hyQTv1zZfe4JxO7aO7Ql%2Fohifservermetadata&studyInstanceUids=2.16.840.1.113669.632.20.1211.10000502993&seriesInstanceUids=1.3.12.2.1107.5.2.31.30222.30000007072005313478100001711
```

#### Result

An MRI is displayed

*note: Don't forget to clear the browser cache*

**Comment by dannyrb** [comment]
I'm guessing this was accidentally removed/disabled. This is something that should have an accompanying Cypress (E2E) test to make sure we don't accidentally break it.

**Comment by Hampycalc** [comment]
I am currently facing the same problem. When the OHIF viewer is launched (locally) via the Kheops-UI, the same error as above is displayed:
"Error: "No study instance uids specified"
Go back to the Study List""
Interestingly, clicking the "Go back to the Study List" link will allow access to the DICOM data viewer the OHIF viewer

**Comment by auarstadtt** [comment]
Hi Guys,
I'm facing the same problem.
How did you solved it ?
Thank you for your help.
Kind regards
Antoine

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
