### ISSUE TITLE
How to cause the client browser reload if I update the next version of viewer?

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#1574]
I Find if I update the next version of viewer, the client browser don't reload js script because of the browser's cache mechanism. I should press Ctrl+F5 or clear the browser's cache data then cause client browser reload. 
I've tried to change the version number of version.js in a directory '\platform\viewer\src\', but can't cause all reloads

**Comment by dannyrb** [comment]
@JiangWeian, the service worker should auto-update if it detects a new version. Are you setting cache headers on the server? Do you have a service worker that won't uninstall? What version do you have? What version are you unable to update to?

**Comment by JiangWeian** [comment]
@dannyrb, what's you said 'service worker'? Is a software? It can be installed in an environment without network connection? Because I have some clients whose server machines are not connected to the Internet

**Comment by dannyrb** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
