### ISSUE TITLE
Embedded viewer in asp net core - Customize Panel

### ISSUE THREAD

**Issue by sylvainb31** [OHIF/Viewers#1578]
Hello,

I have managed to make the viewer work inside my asp net core 3.1 web app thanks to your useful guide : 
[https://docs.ohif.org/deployment/recipes/embedded-viewer.html](https://docs.ohif.org/deployment/recipes/embedded-viewer.html)

Now I would like to customize the viewer. Is it possible using the embedded version ?
I would like to change the panel side (the one displaying the series) from the left to the right. 
I would also like to change the content of the panel displaying the series, so it displays series from previous studies as well.

How can I grab the panel and change its configuration and content ?
Could you give me a hint about how to proceed ?

Thanks a lot for your help.

Sylvain

**Comment by dannyrb** [comment]
We're improving extension support in the near future to give you more control. Today, you can create an extension and provide it to the OHIF Viewer via configuration:

- Docs: https://docs.ohif.org/extensions/
- CodeSandbox: https://codesandbox.io/s/ohif-script-tag-v103-custom-extensions-3qnd2 (inline extension)

If you want to replace an existing side panel, you will need to modify or remove the extension that is providing it today. In the future, you'll be able to configure/add routes, and specify which extension modules should be made available. This decreases the amount of work required to achieve a target user experience.

**Comment by sedghi** [comment]
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
