### ISSUE TITLE
Docs for Adding a Tool to the Viewer do not work

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#158]
Reported twice:
- https://groups.google.com/forum/?nomobile=true#!topic/cornerstone-platform/H0ZK-Tfilmw
- https://groups.google.com/forum/?nomobile=true#!topic/cornerstone-platform/jeypxgjRrF4

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now.

Related: https://github.com/OHIF/Viewers/projects/3#card-21712696
