### ISSUE TITLE
How to directly load LOCAL diccom files in viewer, insted using remote files.

### ISSUE THREAD

**Issue by nenadfemic** [OHIF/Viewers#1583]
**How to directly load LOCAL diccom files in viewer, insted using remote files.**

Hi , can some explain how to modify code, so can directly load my own local diccom files, instead remote dicom files.

I know that is possible to input over http://localhost:3000/local, using Drag and Drop files,  

but is it possible when run http://localhost:3000/, to open directly my stydy list from my local server as did in this moment with remote files from ohif server.

I guess need modification in code, 

 dicomWeb: [
      {
        name: 'DCM4CHEE',
        wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado',
        qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,

but not sure, what exactly need to correct, can some share experience if already face with this task.

also is it possible to load diccom images directly from amazon s3 storage

Cheers

**Comment by dannyrb** [comment]
> also is it possible to load diccom images directly from amazon s3 storage

Yes. Please see your other issue where I've responded to this question.

> but is it possible when run http://localhost:3000/, to open directly my stydy list from my local server as did in this moment with remote files from ohif server.

Yes, but only if you have a DICOM Web implementation, and the viewer is configured to use it. Otherwise, you have to use "standalone", or modify the viewer's source to support your custom endpoints.

This is something we want to improve long-term, but don't currently have funding for.

**Comment by Todilo** [comment]
I was wondering if there has been any progress regarding the local folder solution. localhost/local does not seem to work for me in the v3 branch.
