### ISSUE TITLE
Is it possible to point viewer to open diccom file from amazon s3 storage

### ISSUE THREAD

**Issue by nenadfemic** [OHIF/Viewers#1584]
**Is it possible to point viewer to open diccom file from amazon s3 storage**

Hi,
is it possible to open diccom file from amazon s3 storage.

Thanks

**Comment by dannyrb** [comment]
These two issues have some guidance:

- https://github.com/OHIF/Viewers/issues/891
- https://github.com/OHIF/Viewers/issues/1500

Long-term, we want to make this even easier, but today this is the guidance for data sources that don't conform to DICOM Web.

**Comment by eolasd** [comment]
Hi..  I would love to contribute to this project - and I have just spent a few days integrating this very scenario (standalone ?url with JSON & s3 files)

Is the best approach for me to write some documentation and submit a PR?
Or is there a preferred workflow outside of PR's for Docs?

Thanks!
Dave.

**Comment by dannyrb** [comment]
> Is the best approach for me to write some documentation and submit a PR?
> Or is there a preferred workflow outside of PR's for Docs?

@eolasd, if you have questions about the content, placement, etc. You can always create or respond in an existing issue to see clarification (GitHub has a "Discussions" feature they're rolling out soon that should make this nicer). You can also open a "Draft" PR to receive feedback while you work.

Thanks for taking the time to look into how to give back and help out the community 🙏
