### ISSUE TITLE
Which compression formats does this viewer support with "wadors"?thanks

### ISSUE THREAD

**Issue by 3833430** [OHIF/Viewers#1589]
I found that the compressed dicom could not be displayed normally when retrive frame with wadors.
thanks

**Comment by dannyrb** [comment]
Do you have an example or reproduction? We use the [`cornerstone-wado-image-loader`](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/docs/TransferSyntaxes.md) library to request and decode

**Comment by 3833430** [comment]
> Do you have an example or reproduction? We use the [`cornerstone-wado-image-loader`](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/docs/TransferSyntaxes.md) library to request and decode

thank your replay.
i found the  request header  of   retrive frame
include 
accept: multipart/related; type="application/octet-stream"
but in my seriesmetadata every instance include  :
{"00020010":{"VR":"UI","Value":["1.2.840.10008.1.2.4.70"]}
why  request header  of   retrive frame still is "application/octet-stream"
It shouldn't be “image/image/x-jls”?

seriesmetadata Request URL: http://localhost:1000/WADO/PACSSERVER/studies/1.3.46.670589.28.26690171471530920200312015756768959/series/1.3.46.670589.28.26690171471530920200312025146407021.2.2/metadata
retrive frame Request URL: http://localhost:1000/WADO/PACSSERVER/studies/1.3.46.670589.28.26690171471530920200312015756768959/series/1.3.46.670589.28.26690171471530920200312025557814030.2.2/instances/1.3.46.670589.28.266901714715309202003120256103719622211221/frames/1

With sincere thanks！

**Comment by 3833430** [comment]
sorry ,i found it is fault of  my pacs server's respone .
thanks
