### ISSUE TITLE
StandaloneViewer - Left Sidebar & Thumbnail Progressbar

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#159]
Hello,
I just compiled Standalone viewer from Feb 2018 release.  I noticed 2 issues -

1. The leftSidebarOpen for series is close when browser is open even when the leftSidebarOpen flag is set to true in packages\ohif-servers\both\schema\server.js.

2. Thumbnail progress bar does not show.  Even when the showStackLoadingProgressBar is set to true.

Many thanks!
Rick

**Comment by eagle49** [comment]
Hi Rick
For the first point you can set the session variable 'LeftSideBar' as true in StandAloneViewer/client/component/viewer/viewer.js
![image](https://user-images.githubusercontent.com/29590370/46908927-83348c00-cf5c-11e8-8633-46605958692d.png)
For the second on point it is shown in my case.
Thank you.

**Comment by dannyrb** [comment]
We are moving away from support for version 1 of the Viewer. The goal is to make Version 2 extensible and configurable enough that you can customize it for your workflow and purposes.

This issue hasn't seen activity in some time, so I'm going to close it. AFAIK, version 2 does not yet display series load progress in the thumbnails list. If this is a feature you would like to see, please feel free to create a new issue.

It's worth noting that this can be a little difficult to get right, especially for large CT series/study. Most implementations I see show % progress, and don't correlate to which slices have been loaded. Also, at a certain point, we exceed and start to remove slices from the cache. For a large CT, we may not be able to fit the entire series in the cache, resulting in 100% loaded, but 15% unloaded.
