### ISSUE TITLE
Allow Google Cloud routes to be enabled independently of the rest of the adapter UI

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1590]
For the [NCI Imaging Data Commons](https://imagingdatacommons.github.io/) project, users will be to view publicly accessible cancer imaging data hosted in Google Cloud DICOM Stores. The project will allow the users to view cases even without being logged in to the system, similar to how [The Cancer Imaging Archive](https://www.cancerimagingarchive.net/) allows users to view the data. In this case, the OpenID Connect settings will not be required.

The routes are enabled here:

https://github.com/OHIF/Viewers/blob/1d85f7a74e887f628ca8171bfd595340c8960b97/platform/viewer/src/routes/routesUtil.js#L59

and here:
https://github.com/OHIF/Viewers/blob/a5d6bc6a51784ed3a8a40d4ae773de9099f116b9/platform/viewer/src/customHooks/useServer.js#L20

We need to have a configuration setting which allows us to use the routes to be used so we can do the following:
- Direct link to a study in the Viewer
- Direct link to a collection in the Study List

without any login requirement.

**Comment by fedorov** [comment]
The "owner" of this issue on IDC side is @wlongabaugh.

**Comment by swederik** [comment]
Turns out we can do this already using a config like this:

```
window.config = {
  routerBasename: '/',
  enableGoogleCloudAdapter: true,
  showStudyList: true,
  filterQueryParam: true,
  healthcareApiEndpoint: YOUR PROXIED OPEN GOOGLE CLOUD ENDPOINT (see https://github.com/ImagingDataCommons/ThrottleProxy)
  studyListFunctionsEnabled: false,
};
```

Basically, if OIDC is not enabled, but the adapter and endpoint are set, you can still link to studies. If you disable Study List functions, the DICOM Store switcher is hidden.

So I think this is safe to close.

**Comment by Diex** [comment]
I got: 

index.umd.js:178515 TypeError: Cannot read property 'access_token' of null
    at DatasetSelector.render (index.umd.js:204674)
    at vi (index.umd.js:178500)
    at ui (index.umd.js:178499)
    at gk (index.umd.js:178580)
    at fk (index.umd.js:178549)
    at Zj (index.umd.js:178548)
    at Lj (index.umd.js:178542)
    at index.umd.js:178440
    at exports.unstable_runWithPriority (index.umd.js:178646)
    at fg (index.umd.js:178439)
