### ISSUE TITLE
do ohif viewers support multi-frames dicom play?

### ISSUE THREAD

**Issue by 3833430** [OHIF/Viewers#1591]
i found the viewer only display first frame of mulit-frames dicom,and the cine tool dont play.
please ask me how  could the viewer  dislay all frame of mulit-frames?
thanks!

**Comment by swederik** [comment]
It should support this yes, and it used to support it perfectly fine. It looks like this has been broken in master though.

It's working on viewer.ohif.org/local and viewer-stage.ohif.org/local, but not on viewer-dev.ohif.org/local

I'm not sure what broke this, but I would guess #1500.

**Comment by 3833430** [comment]
> It should support this yes, and it used to support it perfectly fine. It looks like this has been broken in master though.
> 
> It's working on viewer.ohif.org/local and viewer-stage.ohif.org/local, but not on viewer-dev.ohif.org/local
> 
> I'm not sure what broke this, but I would guess #1500.
thank your reply.
can repair this problem?

**Comment by dannyrb** [comment]
fixed by: https://github.com/OHIF/Viewers/pull/1595

**Comment by dannyrb** [comment]
Let me know if #1595 did or did not resolve this for you. We can reopen if you're still experiencing issues.
