### ISSUE TITLE
Embedded viewer: Query params

### ISSUE THREAD

**Issue by laksmig6** [OHIF/Viewers#1592]
> :hand: REQUIREMENT:
We have a web application on which we are trying to embed a OHIF viewer. 
A separate link. On click of the link,  a study page should open on the new tab using the OHIF viewer.
At this point I have the studyInstanceUid available.

**Description**

We have a separate dicomIndex.html file on which we have added server configuration to embed the viewer with DOM element to attach(<div id="root"></div>)  where '*root*' being the containerId. 

https://github.com/ProjectEKA/hiu-ui/blob/pathology-report/dicomIndex.html

constructing reference to a link on the page to open in a new tab ( herf = 'http://localhost:8080/viewer/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170?dicomCtx=L2RpY29tLXdlYi8=') which is '*base_url/viewer/studyInstanceUid*'
https://github.com/ProjectEKA/hiu-ui/blob/4b59d61a1bb2bf4344f6ddace021e28959a773e0/src/components/DiagnosticReport/DiagnosticReportComponent.js#L83

Currently when the route matches '/viewer/' I have dev server configuration in webpack to load the dicomIndex.html. I see it not the ideal way to load my index file.
https://github.com/ProjectEKA/hiu-ui/blob/4b59d61a1bb2bf4344f6ddace021e28959a773e0/webpack/webpack.dev.config.js#L47

When I directly call the index like this 'http://localhost:8080/dicomIndex.html/?studyInstanceUid =1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170&dicomCtx=L2RpY29tLXdlYi8=' I see the viewer getting loaded but with an error of 'Page Not found'.

Does the viewer always expects the URL to be '/viewer/studyInstanceUid' ?
Is there a way to pass studyInstanceUid as a queryparam(path param) in the route? If yes, how do I set the configuration in IndexPage?

**Comment by dannyrb** [comment]
You would not call the index directly like that. It sounds like a server-side routing issue. You likely need redirect rules

**Comment by laksmig6** [comment]
@dannyrb,
1. Is there a way I can specify what dicom-instance to load up? Does OHIF config have anyway to specify the specific instance study
2. If I want to render the viewer in my current page, (say inside a DIV) for a specific dicominstance - can I do that?
3. Must the URL have "/viewer/studyinstanceuuid" for a specific instance to open?

**Comment by dannyrb** [comment]
Yes, but you need appropriate server redirect rules. If you don't have access to that, you would likely need to rebuild the viewer to use hash routing, then you could use hash routes for the iframe source

**Comment by laksmig6** [comment]
@dannyrb,
Thanks for your quick response and suggestions here.
I have set up redirect on server to load the dicomIndex.html on matching '/viewer'. Locally everything works fine. but on the deployed environment I see the call failing for undefined values in the url.

Locally when I hit 'http://localhost:8080/viewer/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170?dicomCtx=L2RpY29tLXdlYg==' 

I see this making a network call to  
- series ('http://localhost:8080/dicom-web/studies/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170/series') and 
- metaData(http://localhost:8080/dicom-web/studies/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170/series/1.2.826.0.1.3680043.8.1055.1.20111102150758591.96842950.07877442/metadata) 
- Frame 1 (http://localhost:8080/dicom-web/studies/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170/series/1.2.826.0.1.3680043.8.1055.1.20111102150758591.96842950.07877442/instances/1.2.826.0.1.3680043.8.1055.1.20111102150758591.03296050.69180943/frames/1)

When I try to do same on the deployed environment, 
On hitting https://ncg-dev.projecteka.in/viewer/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170?dicomCtx=L2RpY29tLXdlYg== 
I see the network call for series(https://ncg-dev.projecteka.in/dicom-web/studies/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170/series) failing. am getting 404 Not found error

I tried debugging the issue, and I see the seriesInstanceId id **undefied** at certain level

The url where the orthanc server is set up is: https://ncg-dev.projecteka.in/dicom-web/
studies: https://ncg-dev.projecteka.in/dicom-web/studies
study url: https://ncg-dev.projecteka.in/dicom-web/studies/studyInstatnceUid (as per image uploaded: https://ncg-dev.projecteka.in/dicom-web/studies/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170)
When I hit this url am not getting the right response.

the sameWay, If I hit the backend server url (orthanc) with studyId 
https://ncg-dev.projecteka.in/dicom-web/studies/3abaec0a-ebfaaa87-f830d52b-d62df074-6a692c12 I get the response. 

Now am confused about the expected network url when I hit https://ncg-dev.projecteka.in/viewer/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170?dicomCtx=L2RpY29tLXdlYg== on the browser

Could you please help me here?

**Comment by laksmig6** [comment]
am using same image on both local and deployed servers to make sure my example urls are not confusing. both the cases url remains same except the base path.

**Comment by laksmig6** [comment]
@dannyrb, I still have this issue. could you pls help me over here?

**Comment by andresmmujica** [comment]
hi @laksmig6  did you solve this issue?  I'm kinda stuck in a similar situation
