### ISSUE TITLE
How to extract image from dicom viewer?

### ISSUE THREAD

**Issue by kkmehta03** [OHIF/Viewers#1594]
Hello! I'm back with another question
I want to extract the image in the study, but I'm not able to find a straightforward way to do this. 
![image](https://user-images.githubusercontent.com/25249564/78216418-69cc2a80-74d7-11ea-8220-8bcbefda4bb9.png)
I see that the image is loading up on cornerstone-canvas. I want to extract this image and do some manipulations to it. Can you help me figure at what part of the code this image is getting loaded?

As an inspiration, I saw the code of `ViewportDownloadFrom.js` to understand how the image is loading but couldn't understand the entry point. 
I learned that `activeEnabledElement.image.imageId` can be used to call `cornerstone.loadImage()` function. But when I try to do that, it gives an error that says `activeEnabledElement.image is undefined`. 
Is there a better way to extract the image highlighted above?

**Comment by dannyrb** [comment]
@KhyatiMehta3, it depends. Do you need the original pixel data of the DICOM, or will an 8-bit JPEG suffice?

**Comment by KhyatiMehta3** [comment]
The original pixel data of the dicom. I want to convert that into a blob or a base64 string to send it over an API

**Comment by dannyrb** [comment]
I'm not sure there's much value in converting it to base64. You likely want to use `cornerstone.getpixels()`: https://docs.cornerstonejs.org/api#getpixels

That won't be the representation on the canvas, so would not include annotations, overlays, etc. It would be the underlying raw pixel data (ie. the decoded pixels from the original DICOM).

**Comment by KhyatiMehta3** [comment]
So I can just hit 
```
const activeViewportIndex = viewports.activeViewportIndex;
const activeEnabledElement = getEnabledElement(activeViewportIndex);
cornerstone.getPixels(activeEnabledElement);
```
in my extension's commandsModule.js right?

**Comment by KhyatiMehta3** [comment]
I tried the above code but didn't get any pixels

**Comment by dannyrb** [comment]
getPixels takes more than one parameter: 

> 
    element HTMLElement The DOM element enabled for Cornerstone
    x Number The x coordinate of the top left corner of the sampling rectangle in image coordinates
    y Number The y coordinate of the top left corner of the sampling rectangle in image coordinates
    width Number The width of the of the sampling rectangle in image coordinates
    height Number The height of the of the sampling rectangle in image coordinates

**Comment by KhyatiMehta3** [comment]
Hi Danny, 
When I hit these 2 commands,
```
const activeViewportIndex = viewports.activeViewportIndex;
const activeEnabledElement = getEnabledElement(activeViewportIndex);
console.log("element =>", activeEnabledElement)
```
I get the html div element, where the image is rendered. 
![image](https://user-images.githubusercontent.com/25249564/78332481-bc741800-75a5-11ea-90a4-9d9eb062a853.png)

But, when I try to log the image Id, 
`console.log("element image id", activeEnabledElement.image.imageId)`,
It gives me this error:
![image](https://user-images.githubusercontent.com/25249564/78332861-6e134900-75a6-11ea-84e0-ab76f78b5035.png)

What I want to do is be able to load the image into a variable and then send it over. 
I found that the below line should work -
`const image = cornerstone.loadImage(activeEnabledElement.image.imageId)`
but i'm not able to get the image element..
Can you tell me what I might be doing wrong?

**Comment by yesid08** [comment]
@KhyatiMehta3  Can you please explain me, how did you import "viewports" here? I am trying to get the viewport or at least dicom-metadata related with SeriesInstanceUID and SOPInstanceUID but I can't figure out how to do it, I was looking for this "viewports" but I don't see any information in the docs.

Thanks in advance!

**Comment by KhyatiMehta3** [comment]
@yesid08 Refer to [this link](https://github.com/OHIF/Viewers/blob/d98889f1ebafd164024be92e99e627e1ef527e0a/extensions/cornerstone/src/CornerstoneViewportDownloadForm.js), to know how viewports are being injected as parameters to the functions in that extension.

**Comment by sedghi** [comment]
In latest master you can use cornerstone3D api

`viewport.getImageData()`
