### ISSUE TITLE
Cleanup dcmjs imports

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1599]
Now that we have a default export for dcmjs we can use `import dcmjs from 'dcmjs'` instead of `import * as dcmjs from 'dcmjs';`

See:
https://github.com/dcmjs-org/dcmjs/pull/110

https://github.com/OHIF/Viewers/search?q=import+*+as+dcmjs&unscoped_q=import+*+as+dcmjs

**Comment by khalidwilliams** [comment]
@swederik I'd be interested in helping with this issue!

**Comment by dannyrb** [comment]
@khalidwilliams, feel free to draft a PR ^_^

**Comment by khalidwilliams** [comment]
I went ahead and made a PR. Not sure if it still needs to be drafted (this is my first contribution, apologies if I misunderstood the workflow!)

**Comment by dannyrb** [comment]
@khalidwilliams, you knocked it out of the park 💨 ⚾ 
Thanks for taking the time to draft a PR and contribute to OSS 🎉🥇🎉
