### ISSUE TITLE
Use HTML5 routing

### ISSUE THREAD

**Issue by pedrohml** [OHIF/Viewers#16]
Hi there,
Maybe we could improve the user experience using HTML5 routing (currently used only in user area). Most of the user navigation is stored in a single history state and this is lost when page is refreshed and after back/forward interaction. Use could use HTML5 routing to:
- Specify active viewer tab;
- Specify the image shown in the current tab;
- Specify work list filters and sort;
- DO NOT specify active tools.

Best regards.

**Comment by swederik** [comment]
Hi Pedro,

This is a nice idea, but it is not a top priority at the moment. I'll leave this open until someone can get to it. If you or anyone else feels like implementing it I'd be happy to take a pull request!

Thanks,

Erik

**Comment by dannyrb** [comment]
I believe this has been addressed in the `React` branch, and maybe the current `master` as well? If I'm mistaken, please let me know and I can re-open this issue.
