### ISSUE TITLE
Reference Lines causing displaying of random dot on Image

### ISSUE THREAD

**Issue by cenktrms** [OHIF/Viewers#160]
Hello,

I would like to inform you a problem. When we open stack scroll (Reference lines), there is a little green dot show ups. We think that it should be a line through image. In attachment you can see the image for issue. 
On image i circled the dot you can see it. Also i draw a line for what it should be.

Sincerely,

![image](https://user-images.githubusercontent.com/15123025/35966606-5ab12d88-0ccf-11e8-811e-33fd087c2d89.png)

**Comment by swederik** [comment]
Could you provide an anonymized copy of the study in question? That would make it easier to debug. Thanks!

**Comment by dannyrb** [comment]
This issue has grown pretty stale, so I'm going to close it. If you're able to provide a reproduction, I would be more than happy to take a peak and see if I can reproduce. It's very likely this is a Cornerstone issue and not an OHIF issue.
