### ISSUE TITLE
Error in StandaloneRouting

### ISSUE THREAD

**Issue by nenadfemic** [OHIF/Viewers#1600]
I am not sure, what is error.

I am generate json file for dicom, and try to open with standlone viewwer, but get error in console

![image](https://user-images.githubusercontent.com/6898640/78362744-e84dc880-75ba-11ea-859e-961aaded2c7c.png)

My generate json file looks:

{
  "studies": [
    {
      "studyInstanceUid": "1.3.12.2.1107.5.2.30.25049.30000007071111324087500000017",
      "studyDescription": "RECHERCHE^fMRI",
      "studyDate": "20070711",
      "studyTime": "162114.843000",
      "patientName": "BRAIN",
      "patientAge": "038Y",
      "patientBirthDate": "111111",
      "patientId": "wHQVJPgZ",
      "patientSex": "M",
      "seriesList": [
        {
          "seriesDescription": "ToF-2D",
          "seriesInstanceUid": "1.3.12.2.1107.5.2.30.25049.30000007071110510826500012654",
          "seriesNumber": "8",
          "seriesDate": "20070711",
          "seriesTime": "170935.843000",
          "seriesModality": "MR",
          "instances": [
            {
              "columns": 256,
              "rows": 256,
              "instanceNumber": "1",
              "acquisitionNumber": "1",
              "photometricInterpretation": "MONOCHROME2",
              "bitAllocated": 16,
              "bitsStored": 12,
              "pixelRepresentation": 0,
              "samplesPerPixel": 1,
              "pixelSpacing": "0.9765625\\0.9765625",
              "highBit": 11,
              "imageOrientationPatient": "0.12186933756846\\0.99254615235798\\-2.75772039e-008\\-0.0381016563199\\0.00467826714965\\-0.9992629171555",
              "imagePositionPatient": "-92.106763378728\\-136.46620856638\\139.05216664506",
              "imageType": "ORIGINAL\\PRIMARY\\M\\ND",
              "sopInstanceUid": "1.3.12.2.1107.5.2.30.25049.30000007071110510826500012674",
              "url": "dicomweb://localhost:8081/slika/1.3.12.2.1107.5.2.30.25049.30000007071110510826500012674.dcm"
            }
          ]
        }
      ]
    }
  ]
}

**Comment by dannyrb** [comment]
It does not look like you're using the updated format/casing as specified here: https://github.com/OHIF/Viewers/issues/1500

**Comment by nenadfemic** [comment]
Ok i will  check.

I was use suggeations

https://gist.github.com/swederik/b7901bd933e6497720783e532616eec0

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dannyrb** [comment]
I appreciate the note. That's a 2-year old GitHub gist. The changes outlined in the "Metdata Overhaul" provide the updated format + casing.
