### ISSUE TITLE
Support initialization of segment color from RecommendedDisplayCIELabValue

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1601]
## Request

**What feature or change would you like to see made?**

Per @JamesAPetts, "SEGs just load in the default cornerstone color LUT per segment index at the current time", even if color is included in the segment sequence. It would be better if the color was initialized based on what is in SEG.

**Why should we prioritize this feature?**

* in the situations where there are multiple segmentations for a given structure (e.g., multiple readers or algorithms), showing them all in the same color makes interpretation difficult
* make visualization consistent with the other tools that support SEG (e.g., Slicer initializes the color)

**Comment by pieper** [comment]
For reference:

https://github.com/dcmjs-org/dcmjs/blob/master/examples/vtkDisplay/index.html#L485-L496

**Comment by fedorov** [comment]
@swederik @JamesAPetts considering the "In progress" stack is almost empty, and I recall James mentioned this should be quite straightforward, I suggest we move this one to "priority" and "in progress" - do you have any concerns?

**Comment by swederik** [comment]
Nope! Sounds good to me

**Comment by fedorov** [comment]
Thanks! I use the LIDC dataset for testing often, and it is very annoying to have all segments painted the same color, since there is only one segment per object, but multiple segments for the individual lesion. Navigation of this kind of data becomes a lot more intuitive when colors are initialized from the data.

**Comment by JamesAPetts** [comment]
Igor is working on a couple of issues, I'll take this one.

**Comment by JamesAPetts** [comment]
Resolved in #1709. Let me know if there are any issues.
