### ISSUE TITLE
Segmentations panel is not being updated after selecting another series

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1603]
## Bug Report

If user opens the Segmentations panel and selects another series, the panel is not being updated. The user has to perform a second action to see the updated panel.

![bug-seg](https://user-images.githubusercontent.com/13245529/78397188-336dd880-75c7-11ea-8f5a-f05109285676.gif)

### Steps to Reproduce:

1. Go to study: https://viewer-dev.ohif.org/viewer/1.2.826.0.1.3680043.2.1125.1.99615878007501689887866317012655114
2. Open the Segmentations panel and verify that the panel has no segments
3. Select 1st thumbnail in the Series list (it has 1 segment)
4. Verify that the Segmentations panel was not updated and still empty
5. Click on Measurements button
6. Click again on Segmentations button
7. Verity that the Segmentations panel was updated

### Expected Result:
1. When user selects a different Series, the Segmentations panel should be updated to display the correct information related to that series.

**Comment by igoroctaviano** [comment]
Fixed here: https://github.com/OHIF/Viewers/pull/1685.
