### ISSUE TITLE
401 Unauthorized when loading study list

### ISSUE THREAD

**Issue by samannand** [OHIF/Viewers#1604]
### Description

A project I am working on is using the Google Cloud Healthcare API, as well as Google OAuth, in OHIF. On the latest version, specifically after the pull request #1575 into master, I am able to select a Dicom Store, however when I have chosen a store and the viewer attempts to load the study list, I get a 401 error.

![Screen Shot 2020-04-04 at 10 31 19 AM](https://user-images.githubusercontent.com/34386761/78406616-7b403e80-765f-11ea-8b40-e0f3699e2bc5.png)

The error subsides when reverting to prior commits.

### What steps can we follow to reproduce the bug?

1. Create a valid google.js config file
2. Run the app using
```
APP_CONFIG=config/google.js yarn run dev
```
3. Run through the process of selecting a dicom store

**Comment by dannyrb** [comment]
That's really odd. Do you notice anything different between the network requests before and after? (Do you see the same headers set)

Does the auth complete and load the token into storage after hitting the callback route?

**Comment by samannand** [comment]
Hi @dannyrb,

In both cases, the auth completes and an access token is loaded into localstorage after hitting the callback route, however the authorization header is missing from the erroneous request.

The response from this request also points this out.

![success_request_headers](https://user-images.githubusercontent.com/34386761/78411856-afbaf700-766d-11ea-8215-e21838878043.png)
![error_request_headers](https://user-images.githubusercontent.com/34386761/78411859-b34e7e00-766d-11ea-8682-88447d63ff98.png)
![error_request_response](https://user-images.githubusercontent.com/34386761/78411861-b3e71480-766d-11ea-9386-cc682329368c.png)

**Comment by FossilBlade** [comment]
I am facing the same issue as described over here https://github.com/OHIF/Viewers/issues/1597.

The ajax call request to get the the dicom frame doesnt have the authorization header as shown in the the screen shot at the bottom of my question.

**Comment by dannyrb** [comment]
Have you identified where the AJAX request for the frame is originating from? If it's the DICOMWeb client, it should be using the appropriate headers. If you can find what's initiating the request, and where it's headers should be set (why they're not). I can create a more clear cut fix issue for this.

**Comment by dannyrb** [comment]
Using this ticket as the tracking issue for: https://github.com/OHIF/Viewers/issues/1597

**Comment by dannyrb** [comment]
This issue should be resolved. Please don't hesitate to open a new issue if you're still experiencing problems.

**Comment by samannand** [comment]
Sorry I have been away for a while to focus on University however I can confirm after updating our repos today that the issue has been resolved. Thanks @dannyrb 😄

**Comment by Diex** [comment]
Hi @dannyrb , would you please take a look at https://github.com/OHIF/Viewers/issues/1736?
I think is related. still having 401 when trying to fetch images.
thanks in advance.!
