### ISSUE TITLE
Allow Unavailable series

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#1606]
Hi all,

I'm facing a problem with OHIF.
I have my Orthanc DICOMWeb accessible through a reverse proxy.
The reverse proxy check if the user is allowed to access a ressource on the basis of my software database.
The access can be forbiden at the serie level (some series allowed to been seen and other not).
If the user is not allowed to see a series it answer an 403 status. 

The problem is, during the serie loading when OHIF get a 403 it crashes and so none images can been seen (instead other series would respond correctly).

It there a way to prevent this ? If a series in unavailable, let it unavaible in OHIF but continue to fetch other series.
This is something going to impact as well the study level, I have seen you are working on displaying patient history, there are multiple reason that some integration of OHIF would prevent the user the full history of the patient (for example disallow to see other modality history). 

If OHIF crashes at the first unavaible ressource, it will be impossible to make server side filtering access (which is important for security).

Also some library rely on some custom HTTP error code for some special behaviour, if needed it would be also possible that the reverse proxy use a custom HTTP 4XX status code to say to OHIF 'The ressource is here but I won't give you access, continue your job'.

I'm pretty sure that the old version of OHIF didn't crashe when a serie is unvailable, the other series were loaded correctly but it was the time OHIF was loading the metadata at the study level.

Best regards,

Salim

**Comment by dannyrb** [comment]
@salimkanoun, we should definitely handle this more gracefully. I'd be willing to consider this a `bug`. As a user, what would you expect to happen if you could not retrieve one or more series (or studies in a multiple study viewing session)?

An empty thumbnail with text to indicate it can't be retrieved? Nothing in the list, but a notification to indicate one or more series in the study could not be retrieved?

Is it odd that they can see the series in the list of series for the study, but be blocked from retrieving it? (If you don't have permission, does the first request leak information you shouldn't have?) Is it possible/desirable to filter blocked series from the initial series list request?

**Comment by salimkanoun** [comment]
Dear Danny,

Its hard to imagine a solution that will fit for eveyrone.

I think de should respect as much as possible the dicom and web standards.

So my ideas would be :

- if the study API are Not filtered then the answers have to be displayed,
the Idea would be to display eveything available and let the system owner
manage his server side filtering.

So i think it is good to display series presence even if the serie itself
is forbiden to Access.

This way the front end just give the data it can Access and its backend
responsability to filter the data that should not be displayed (for exemple
if you want to not show study content you could rewrite the study answer in
your backend to filter some series elements, it would be technical but not
impossible)

- I think we should use http error message to display in the thumbmail
(either series or study thumail when it comes to patients History)
This way the server owner could chose is own message by using a custom http
error message.
So it will be possible to use the standard error code ( unauthorized, Not
found) but also to make some personalized message to the front end.

Of course all of this are personal opinions, my main Idea is to let the
front end be the slave of the backend, just render what the backend gives
you.
Again just my opinion, nothing more.


Best regards,

Salim

Le lun. 6 avr. 2020 à 20:37, Danny Brown <notifications@github.com> a
écrit :

**Comment by sedghi** [comment]
@salimkanoun What about this?

**Comment by salimkanoun** [comment]
It's better than before as it don't crash anymore but yet HP is not started if some series metadata are not accessible

See https://github.com/OHIF/Viewers/issues/3674

**Comment by sedghi** [comment]
I have that one for development, can we close this one?

**Comment by salimkanoun** [comment]
Yes sure
