### ISSUE TITLE
Can I get the apis for back-end?

### ISSUE THREAD

**Issue by Hynn01** [OHIF/Viewers#1607]
Hello, I want to develop a back-end by myself to match the OHIF Viewer. I am wondering if it is possible to get all the apis a server need to match this front-end? Since I am not familiar with the front-end, I find it hard to find the restful api the front-end need, for example, the restful api for the the right panel part(Measurement). I can't find this information in the docs. Thanks!

**Comment by JamesAPetts** [comment]
OHIF primarily uses a dicom web server as its backend, the API for this is detailed here:

https://www.dicomstandard.org/dicomweb/

> the restful api for the the right panel part(Measurement).

This is performing a STOW operation to store a DICOM-SR to the dicomweb server as defined above.

Its also possible to use a custom datasource, by just returning json from some backend in the form described here, under "JSON Launch" : https://github.com/OHIF/Viewers/issues/1500, e.g. `/viewer?url=https://url/to/your/testJSON.json`.

In this case you'd have to make some bespoke API to push to the DICOM-SR for the measurements back to.

**Comment by Hynn01** [comment]
Thank you!

**Comment by Hynn01** [comment]
Now I get information about the API, but I still don't know how to organize the response.
![image](https://user-images.githubusercontent.com/26082974/79036120-8a8f3100-7bf7-11ea-94bc-89a1a50e5c41.png)
Is it the response follow this kind of forms?
In addition, I get the information for DICOM-SR in this link http://dicom.nema.org/dicom/2013/output/chtml/part20/sect_A.3.html, but I have no idea that which Tag(or Attribute Name) in DICOM-SR represent the measurement...
Sorry to bother you again, could you please tell me more about these? Thank you! @JamesAPetts

**Comment by pilacoepouco** [comment]
@Hynn01, were you able to evolve into something? I have the same interest

**Comment by PoyangLiu** [comment]
Here is a live example of how OHIF gets a list of studies on study list.
1. Open OHIF study list (https://viewer.ohif.org/)
2. Open the browser dev console and goto the network tab
3. Reload the browser to refresh the network requests
4. Find the first `xhr` network request, this is the first `GET | {s}/studies?...` query the front-end made to the server for a list of studies
![image](https://user-images.githubusercontent.com/3383903/98380054-10e8e580-2016-11eb-9878-ee2da9d079f2.png)
5. Preview the `xhr` request and you'll see this
![image](https://user-images.githubusercontent.com/3383903/98380089-1e05d480-2016-11eb-820a-f8b2e96727d6.png)
6. Hopefully you can match the network request and DICOMWeb spec and figure out how the structure comes about.
http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.6

**Comment by sedghi** [comment]
You can look at the datasources to learn more https://docs.ohif.org/configuration/dataSources/introduction
