### ISSUE TITLE
connect static pages on netlify to local orthanc server

### ISSUE THREAD

**Issue by kkmehta03** [OHIF/Viewers#1608]
Hello! 
I have the viewer built and running as a PWA on netlify. 
I used the `yarn run build` command and dropped the dist files on netlify.
I have the local orthanc server up using command `yarn run orthanc:up`
I open the netlify pwa url and the display is blank. 
I look at the inspect, it says that the dicom-web is not found on that url. 

I wish to know how to configure the PWA so it connects to the local machine's orthanc server
Thanks!

**Comment by sedghi** [comment]
That is not technically possible unless you expose your orthanc to the internet
