### ISSUE TITLE
Anonymized Cases are hard to see

### ISSUE THREAD

**Issue by kmader** [OHIF/Viewers#161]
If you look at anonymized cases they are hard to see, it might be a good idea to have (anonymized) or (empty) appear in place of a blank name. For this case the only part that is visible is the modality (which for some datasets like the MRI heart segmentation data might also be missing)

![image](https://user-images.githubusercontent.com/116120/36143151-9143c7d2-10aa-11e8-99fa-124863656971.png)

**Comment by radicalrob** [comment]
@kmader - thanks for reporting this.  It's a good point as I don't typically think of anonymized data as having empty fields for things like Patient Name and MRN, although they can.

**Comment by kmader** [comment]
Great, thanks!👍
