### ISSUE TITLE
CORS blok from S3 Amazon storage

### ISSUE THREAD

**Issue by nenadfemic** [OHIF/Viewers#1616]
Hello everyone,

I am create json file for 2 dicom images, which i already upload on s3 amazon storage.
On my local server all works fine, 
![image](https://user-images.githubusercontent.com/6898640/78766463-9675bb80-7989-11ea-9381-fb65ee338087.png)

BUT on amazon s3 storage when i use this link, get CORS error

https://viewer.ohif.org/viewer?url=https://s3-eu-west-1.amazonaws.com/doctestbucket/DEV1FILES/3/6856014358-2020-04-07-12-12-47-studyne1.json

How to fix this.

Thanks in advance

**Comment by dannyrb** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-cors-configuration.html

**Comment by legiaquangvn** [comment]
I experienced the same issue and follow the instruction for setting CORS on the bucket. Here it is
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>https://viewer.ohif.org</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
    <ExposeHeader>x-amz-request-id</ExposeHeader>
    <ExposeHeader>x-amz-id-2</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
It will eliminate the error, but the whole page is dark/black, no image displays. I have looked at some other issues, for example [1657](https://github.com/OHIF/Viewers/issues/1657), [891](https://github.com/OHIF/Viewers/issues/891), and it seems that the issues related to open dicom file on S3 have not been resolved.
