### ISSUE TITLE
Is it possible to load 2 image archives in the config?

### ISSUE THREAD

**Issue by kkmehta03** [OHIF/Viewers#1617]
Hi!
I have a local archive running orthanc. 
I want the viewer to connect to the demo dcmjs.org URLs if orthanc server is down at any point.
I went over to the default.js and added 2 image archives, like so:
```
servers: {
    dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: '/wado',
        qidoRoot: '/dicom-web',
        wadoRoot: '/dicom-web',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
      },
      {
        name: 'DCM4CHEE',
        qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
      },

    ],
  },
```
What I wish to achieve is that the viewer can populate the study list from such a configuration that can have more than 1 image archives to load from, so that if the local orthanc server is down, the demo dcmjs populates the list.

**Comment by sedghi** [comment]
We have a new PR that we are targeting this  https://github.com/OHIF/Viewers/pull/3633
