### ISSUE TITLE
Annotation UI lags while working with mammography dicom files

### ISSUE THREAD

**Issue by rohit-takhar** [OHIF/Viewers#1618]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**
Hello everyone,
I am facing a strange issue. When I load a mammography study on viewer.ohif.org and use the annotation tools, it works perfectly. But, when I clone the GitHub repo and build it using yarn, UI lags while marking the annotations( I tried length tool, rectangle tool). Just wanted to know if this is a known issue with large studies(each image is ~50 mb and there are 4 images in a study)? What version is hosted at viewer.ohif.org? 

Thanks,
Rohit

**Comment by dannyrb** [comment]
@rohit-takhar, `viewer.ohif.org` reflects a regression tested, stable release. `viewer-dev.ohif.org` is a reflection of the current code on master.

If you're experiencing performance issues, any information you can provide to create a reproducible result on our end would be helpful.

**Comment by rohit-takhar** [comment]
Hi @dannyrb,
Apologies for the delay.
To reproduce the issue, please load a mammography file from your local system on viewer-dev.ohif.org and try rectangle annotation. You will be able to feel the lag. **Try dragging the ROI**. If you want I can share a sample Dicom file that I downloaded from the web to verify the issue.

**Comment by nithin-samudrala** [comment]
same problem

**Comment by nithin-samudrala** [comment]
same problem is there any solution for this
