### ISSUE TITLE
Context Path support in Ohif Viewers

### ISSUE THREAD

**Issue by dhavalsolankislk** [OHIF/Viewers#1621]
Hello, 
We are using OHIF in our application. We have want to deploy Ohif Viewer standalone so we created build convert to war file and deployed in tomcat. When we deployed in tomcat it works fine when we are deploying in context path root. 
But we are creating a context path example dicom-viewer and deploying it then it is not working properly
Example our url after creating context path dicom-viewer is http://localhost:8080/dicom-viewer
So Ohif Viewer application working fine in root context path but not working context path is changed to dicom-viewer or anything else. 
We are using apache tomcat server for deployment.

**Comment by dannyrb** [comment]
@dhavalsolankislk, have you tried changing the `routerBasename` application configuration property?

https://github.com/OHIF/Viewers/blob/master/platform/viewer/public/config/default.js#L3

**Comment by kamlesh0606** [comment]
Working .
But Also make build using this command 

cross-env NODE_ENV=production **PUBLIC_URL=/dicomviewer/** **APP_CONFIG=config/app.js** node --max_old_space_size=4096 ./../../node_modules/webpack/bin/webpack.js --config .webpack/webpack.pwa.js --progress

So change only config file Or and also change build command ?
