### ISSUE TITLE
extra query params break viewer

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#1623]
Links like this one break ohif:
```
https://www.google.com/url?q=https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us-central1/datasets/lidc-idri-seg-sr-dcm/dicomStores/lidc-idri-seg-sr-dcm/study/1.3.6.1.4.1.14519.5.2.1.6279.6001.131383203689189807643685075952&sa=D&ust=1586369794567000&usg=AFQjCNHVY4eaLmveYQCRHA98Hwr7lOXIVA
```
if these query params are deleted it work as expected:
```
&sa=D&ust=1586369794567000&usg=AFQjCNHVY4eaLmveYQCRHA98Hwr7lOXIVA
```

Not sure where those params come from, maybe slack or elsewhere.

**Comment by sedghi** [comment]
@jbocce ditto

**Comment by jbocce** [comment]
I tried with https://www.google.com/url?q=http://localhost:3000/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5&sa=D&ust=1586369794567000&usg=AFQjCNHVY4eaLmveYQCRHA98Hwr7lOXIVA
and it worked.
