### ISSUE TITLE
OverlayPlane TopLeft TopRight Missing and ColorLUT Problem

### ISSUE THREAD

**Issue by nutzlastfan** [OHIF/Viewers#1624]
I am using the Viewer with the Json Start and DicomCloud (modified for the new JSON Format) as backend. 
Since I changed to the new Version with the Metadata Overhaul  (from 3.3.4 to 3.8.17)
I have two issues that weren't there before, first is the the OverlayPlane TopLeft and TopRight are empty regardless of what Dicom Image I use.

The other is with some with SC/OT Images where the Color is not displayed correctly, the message in the console says: The provided colorLUT only provides 0 labels, whereas segmentsPerLabelmap is set to 65535. Autogenerating the rest.

The images are JPEG LS NearLossless with RGB as Photmetric.

Everything else works a expected, as far as I can tell.

I added a sample Image:
https://box.fu-berlin.de/s/LWWYLqeiwdZk7ey
and the Metadata:
https://box.fu-berlin.de/s/9z3X6k2Sms7LNJP

I saw #1546 is this the same issue, or something else ?

Update: 

So after some searching, I found that the viewer tries to get patientid and name from the instance:

        case WADO_IMAGE_LOADER_TAGS.PATIENT_MODULE:
          var PatientName = instance.PatientName;

which is the instance.metadata{} part in the new format when i add patientid and name additionally
to instance.metadata{} it has the data available but still doesn't display it. Is it intended that the PatientID, Name is in both studies and the instance part ?

Update: 
Now the Overlay is shown, the Patient Name only passes if I remove the .Alphabetic

        case WADO_IMAGE_LOADER_TAGS.PATIENT_MODULE:
          if (PatientName) {
            patientName = PatientName.Alphabetic;
          }
,Patient ID was on me passing PatientId not PatientID in the Metadata. 

Update:
For the color problem the LUT Message come regardless and doesn't seem to be directly related, when I use the normal non Json Version the image is displayed correctly so this seems to be also metadata related.

Update: 
So after looking through tags that could influence the color I finally added 
PlanarConfiguration, although only necessary if PixelRepresentation is greater 1 it seems to be required regardless now it displays the image normally.

I will leave this open if anyone wants to add something.

**Comment by nutzlastfan** [comment]
-

**Comment by doug1n** [comment]
I also have this problem. Did you solve this?
