### ISSUE TITLE
Is there any way to open NIFTI format file in the OHIF viewer?

### ISSUE THREAD

**Issue by rlaxodnjs199** [OHIF/Viewers#1629]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

Hello,
I want to open CT images in .nii format. I tried to convert it to DICOM and open in the viewer but faced some errors(conversion manipulates original data) so I want to know if there is any way to load NIFTI format image in the viewer.

Thank you

**Comment by trypag** [comment]
Hello,

I am not sure there is an easy way. Though you could write an extension that could read and display nifti images, with a specific viewport. There is a cornerstone loader to read nifti https://github.com/cornerstonejs/cornerstone-nifti-image-loader

It requires a little bit of work to understand how an extension [can be implemented](https://docs.ohif.org/extensions/). 

**A blocking point is how the nifti file is going to be handled, as OHIF only works with DICOM files.**

**Comment by dannyrb** [comment]
@rlaxodnjs199, there is not a well defined path today. The core team does have some experience modifying the viewer to work with NIFTI data sources, but we don't have anything planned (or funded) to support that functionality near future.

We do have some upcoming changes that make it easier to add support for different data sources.

**Comment by armaneshaghi** [comment]
I am reopening this thread after two years. Has there been an update or example implementation to open the NIFTI format with `conerstone-nifti` inside the OHIF viewer?
