### ISSUE TITLE
CT large sequence cannot be opened with MPR, which will cause page crash

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#1630]
What is your email address? If my network  condition allows, I can try to send you some sequence of problems. The number of images in these sequences has exceeded 800. If really can't open such a large sequence with MPR, can viewer give a prompt if can't open it?

**Comment by dannyrb** [comment]
@JiangWeian, we likely do not have the bandwidth to investigate these issues (even if provided a set of images.) Memory issues and optimizations generally take more time than we have available to track down unless they're particularly egregious. You are more than welcome to include an example set here, and a community member may be able to better assist.

If this is something that is urgent or critical for you and your team, I recommend reaching out to an OHIF consultant or consultancy.

**Comment by JiangWeian** [comment]
@dannyrb , Where to upload the DICOM series ? The attachment of GitHub has limited in size

**Comment by dannyrb** [comment]
For temporary shares: https://send.firefox.com/

For something persistent, you would likely need to leverage a paid service. You might be able to get away with sharing a repo that is using GitHub LFS, or by zipping the files and adding them as a "release asset" to a "Release" in GitHub and then sharing the link to that release + assets.

**Comment by JiangWeian** [comment]
@dannyrb , OK, I've uploaded the seies to the  https://send.firefox.com/ .You can download it at the following address: [](https://send.firefox.com/download/f6447dfc2231a3d8/#0Byfu2rEDFe_ZYXXqWpQSw) , the password is **4152637**. 
Hope there are enough people in the community to download these series, only 7 days!
