### ISSUE TITLE
Regression: WADOURI requires image level metadata

### ISSUE THREAD

**Issue by knopkem** [OHIF/Viewers#1638]
### Describe the Bug

Since the big metadata overhaul beginning from V3.7.8 fetching images via WADOURI will fail with cornerstone reporting failure to decode the image. Previously the metadata query for WADOURI required only Study, Series and SOPInstanceUIDs to work. Now several image level attributes need to be returned as well, e.g. pixelspacing, rows, cols, bits allocated, bits stored, highbit etc.
This is especially annoying when using OHIF with a dicomweb to dimse proxy as C-FIND won't be able to query those image level attributes from PACS, thus it's necessary to fetch the data first and to parse it.

### What steps can we follow to reproduce the bug?

* Install Orthanc with dicomweb plugin
* Import some data then test with default settings and latest OHIF viewer. 
** Test viewing: Viewer should render the images correctly
* Now change the [dicomweb plugin](https://book.orthanc-server.com/plugins/dicomweb.html) config to return only the most basic attributes:
** SeriesMetadata: MainDicomTags 
* Restart the server
* Test viewing: Viewer fails to render the image

Alternative approach: Use the [dicomweb-proxy](https://github.com/knopkem/dicomweb-proxy) and update the viewer version (currently at V3.7,7) in the public folder 

I tried to find the issue myself but the code changes for the big overhaul are immense and I need to better understand the code first.

**Comment by dannyrb** [comment]
Do you have any recommendations around how to proceed or address this issue?

**Comment by knopkem** [comment]
Sorry, I did not have the time to look at this any further, but will try to look into this asap.

**Comment by knopkem** [comment]
I could find the issue, please see my PR here https://github.com/OHIF/Viewers/pull/1785

**Comment by sedghi** [comment]
I will document the absolute minimum metadata to run OHIF soon, you can track it here https://github.com/OHIF/Viewers/issues/3093

The additional regrettablyis not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
