### ISSUE TITLE
Mobile Touch Support

### ISSUE THREAD

**Issue by davidi1** [OHIF/Viewers#164]
Hello, I am having an issue with iOS not handling touch support correctly. Whenever I try to open a study from the main page, it just zooms in on the patient’s name. If I try to long press on the patient’s name, it just sits there and does nothing. 

I have tried using Safari and Google Chrome on an iPad and iPhone. Both devices are on iOS 11.

While searching to see if others have had this issue, I came across an older issue (https://github.com/OHIF/Viewers/issues/20) that says it has been fixed. But, for the life of the me, I cannot get it to work.

Am I missing something while compiling? Is it a feature I need to add separately? Or is this a bug? Any help would be much appreciated! If you need anything from me, let me know I will be happy to provide any help I can on my end.

Side note, I did try this on an Android tablet that is running Android 7.1.1 and while touch did bring up a study, it would crash while loading images. I will open a separate issue for this. So, as of right now, it appears to be just an iOS issue.

**Comment by swederik** [comment]
We don't really have mobile support as a priority on our roadmap at the moment, so I am sure there are tons of bugs. I'll keep this open until we get to it.

**Comment by davidi1** [comment]
Sounds good, thank you for letting me know.

**Comment by swederik** [comment]
Hi David,

We've fixed the double-tap to zoom issue. It looks like the Hammer.js events were not being caught by handlers defined in the Template.*.events object. I don't know why that stopped working.

**Comment by davidi1** [comment]
Hello, this is working great now. Thank you!
