### ISSUE TITLE
Thumbnail drag and drop

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#1640]
I downloaded latest code from github.  When I drag series from thumbnail I don't see the visual affect.  

Am I missing something to enable drag and drop of thumbnail to drop series to a specific viewport?

Thank you so much!

**Comment by dannyrb** [comment]
Nope! This is a bug. Thanks for the report. We'll need to investigate what's causing it. I am able to reproduce here: 

https://viewer-dev.ohif.org/viewer/1.3.51.0.7.633918642.633920010109.6339100821

**Comment by dannyrb** [comment]
We're in the middle of a redesign, so this is unlikely to get prioritized as it will get swiped up in those changes. If anyone needs this sooner, please feel free to submit a PR and I can review.

**Comment by richsmith123** [comment]
Thank you Danny for quick reply.

Redesign sounds interesting.  May I ask bit more info on that please?

Thank you!

**Comment by dannyrb** [comment]
There is an open PR that generates updated deploy previews for the changes as they progress:

- https://github.com/OHIF/Viewers/pull/1523

Study List: https://deploy-preview-1523--ohif.netlify.app/ui/examples/studyList
Viewer: https://deploy-preview-1523--ohif.netlify.app/ui/examples/viewer

There's more planned, but that's all I'm able to speak to at this time. I have started posting monthly summaries of OHIF / Cornerstone work completed here:

https://ohiftraining.com/articles/

**Comment by dannyrb** [comment]
I can no longer reproduce on the viewer-demo link provided in this issue. Are you able to?

**Comment by richsmith123** [comment]
Yes, still no drag-n-drop on thumbnail to veiwport.
Thank you!

**Comment by dannyrb** [comment]
@richsmith123 , which browsers? All studies or specific ones? Unfortunately, I can't fix the issue unless I can reproduce it.

**Comment by richsmith123** [comment]
I'm using **Chrome** ver 81.0.4044.129  and **FireFox** ver 75.0 

https://viewer-dev.ohif.org/viewer/1.3.51.0.7.633918642.633920010109.6339100821

Thank you!

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
