### ISSUE TITLE
Custom cornerstone tool not working as expected in production

### ISSUE THREAD

**Issue by sinanmb** [OHIF/Viewers#1644]
Hi,

I created a custom tool similar to Probe that is working well in development mode. I have added a callback to open a custom dialog (similar to ArrowAnnotate behavior) when a measurement is added. The problem is that in production mode, with minimization enabled, my custom tool is no longer recognized in `extensions/cornerstone/src/init.js` in this method: 

``` 
 /* Add tools with its custom props through extension configuration. */
  tools.forEach(tool => {
    const toolName = tool.name.replace('Tool', '');
    const externalToolsConfig = configuration.tools || {};
    const externalToolProps = externalToolsConfig[toolName] || {};
    const internalToolProps = internalToolsConfig[toolName] || {};
    const props = merge(
      internalToolProps,
      parseToolProps(externalToolProps, tool)
    );
    csTools.addTool(tool, props);
  });
```

In production mode it returns a [class like this](https://imgur.com/z1SSlHO) whereas in development mode, it returns [this](https://imgur.com/aByQ7Ac)

The problem is that in production mode, tool.name returns "t" for all tools, so the internalToolsConfig is not set for my custom tool, which results in the custom dialog not opening when I click on the viewport to place a measurement. 

Please let me know if you have any tips to address the situation. I have tried to exclude my customTool from the minimization in TerserJSPlugin but it didn't help.

**Comment by dannyrb** [comment]
> The problem is that in production mode, with minimization enabled, my custom tool is no longer recognized in extensions/cornerstone/src/init.js in this method:

Where/how have you configured the OHIF Viewer to add your custom tool?

> In production mode it returns a class like this whereas in development mode, it returns this

Does this hold true for any custom tool you provide? Or just this one in particular?
----

We usually add custom tools in new extensions that call `cornerstoneTools.addTool` directly. Another common path is via the appConfiguration file, but tools referenced and specified there would normally be included via a separate script-tag/bundle.

**Comment by sinanmb** [comment]
Hey Danny, thank you for getting back to me! 

I have configured the OHIF Viewer to add my custom tool inside `extensions/cornerstone/src/init.js` by adding it in `toolsGroupedByType` under annotations property.

Yes actually the same behavior occurs with ArrowAnnotate where a custom modal dialog shows in development whereas the default browser prompt is show in production.

**Comment by dannyrb** [comment]
That is odd. I'm not sure why our deploy preview would use the custom UI, but your local build would not. `ArrowAnnotate` in particular shouldn't simply throw the default browser prompt; it would likely error instead. This makes me think that the "config" for that tool is not being set and the original behavior is running.

I'm not sure how to diagnose and provide guidance without the source in front of me. It sounds like you're in an odd situation.

**Comment by sinanmb** [comment]
> This makes me think that the "config" for that tool is not being set and the original behavior is running.

Yes this is what is happening. the settings in internalToolsConfig are not applied in production mode, neither for arrowAnnotate, nor for my custom tool, thus reverting back to the "original behavior" set in ArrowAnnotateTool.js at the end of the file:  

```
function getTextCallback(doneChangingTextCallback) {
  doneChangingTextCallback(prompt('Enter your annotation:'));
}

function changeTextCallback(data, eventData, doneChangingTextCallback) {
  doneChangingTextCallback(prompt('Change your annotation:'));
}
```

I believe this it because of minification that impacts `toolName` in the method I shared in my first post, which results in the configuration not being set and the default behavior happening instead.

 Actually you can see the behavior I'm referring to if you go to a study on the ohif demo viewer, like this one https://viewer.ohif.org/viewer/999.999.1.19941016.083000 and try to use the arrowAnnotate tool. You will get the default prompt [like this](https://imgur.com/0XmhaZO)

Let me know if that makes sense. I can also share my code if that helps, and it will be very similar to the configuration not working for arrowAnnotateTool.

**Comment by dannyrb** [comment]
`viewer.ohif.org` is a few versions behind. `https://viewer-dev.ohif.org` is always a reflection of the code merged to `master`. It appears to be using a Modal instead of a Dialog for some reason, but regardless, it's a custom UI.

**Comment by sinanmb** [comment]
Oh I didn't know that. You're right then it's odd that in production on my machine the prompt looks like the default browser's one for both my custom tool and arrowAnnotateTool, but not on `https://viewer-dev.ohif.org`

Here's the code I have in Viewers/extensions/cornerstone/src/init.js https://github.com/spreemohealth/Viewers/blob/da2f8e8c385d68ad65f422bbc87c9c25fb815e48/extensions/cornerstone/src/init.js#L1-L545

And here is the code for my custom tool (I have gotten rid of the default getTextCallback here temporarily while I was testing, which means there's no prompt at all currently)
https://github.com/spreemohealth/Viewers/blob/da2f8e8c385d68ad65f422bbc87c9c25fb815e48/extensions/cornerstone/src/landmarkTool.js#L1-L217

Thank you so much for your help and please let me know if you see anything odd here for either the arrowAnnotateTool or my custom tool.

**Comment by facuescobar** [comment]
hi @sinanmb, hope you are doing well!
I'm trying to add a new cornerstoneTool but I'm not getting any luck.

If you have time, could you please help me to set up a new tool? 
I just created this issue: https://github.com/OHIF/Viewers/issues/2025 

I would love to get some feedback to know how to setup a new tool, so I can code a custom one.

**Comment by guohuihot** [comment]
I have the same problem

**Comment by guohuihot** [comment]
![image](https://user-images.githubusercontent.com/3119995/164619766-68b41b05-aebd-4ddf-aa59-2793898e63bb.png)
This is always the case in production mode

**Comment by guohuihot** [comment]
@dannyrb Help me analyze it, thank you

**Comment by guohuihot** [comment]
![image](https://user-images.githubusercontent.com/3119995/165897744-63c8cd41-db1c-41be-a8dc-699d6aebcd16.png)
webpack config
