### ISSUE TITLE
Viewer error when making measures

### ISSUE THREAD

**Issue by sctkndl** [OHIF/Viewers#1649]
Using the sample json and my own person json based on 
https://github.com/OHIF/Viewers/issues/1500
I'm able to successfully get the images to display in OHIF
http://localhost:3000/viewer?url={location of json file}

If I run Dev mode in Firefox on launch of the above site, I do see a JSON parse error, but the json is formatted fine. Again, I tested with the sample in the above #1500 and also with my own json pointed to files I have.
Image of ![error1](https://user-images.githubusercontent.com/26793494/79596979-75127f00-80af-11ea-84d9-f6a2758a2893.jpg)

If I don't turn Firefox Dev mode on while loading the viewer, I see my images fine. 

The issue then comes when I go to make a measure. There is an error thrown about 
timepoint.studyInstanceUIDs is undefined
And I get no measures on the Measurement panel on the right.
Image of ![error2](https://user-images.githubusercontent.com/26793494/79596999-7cd22380-80af-11ea-8d57-d86f5cef37bc.jpg)

I'm not sure if it's a code, or json issue. Perhaps the json formatting has changed. I tested the current and previous versions of the viewer. 

Thanks in advance!

**Comment by dannyrb** [comment]
Are you able to provide a code reproduction of this issue? Ideally in a separate repository or code sandbox? Your first image is a bit confusing, as the exception is thrown in a 3rd party dependency I'm not familiar with. The second image could be an error caused by our recent casing changes, or related to your JSON. It's really hard to tell going off just images.

**Comment by sctkndl** [comment]
The first image may be a non-issue.

For the second image, I'm using the exact json below from #1500 , and I'm using the 3.9.1 code, running as outlined in the guide.  As for getting public sandbox up, I can work on it, but could be some time before I can.

Any json changes since #1500 I may have missed?

{
    "studies": [
      {
        "StudyInstanceUID": "1.2.840.113619.2.5.1762583153.215519.978957063.78",
        "StudyDescription": "BRAIN SELLA",
        "StudyDate": "20010108",
        "StudyTime": "120022",
        "PatientName": "MISTER^MR",
        "PatientId": "832040",
        "series": [
          {
            "SeriesDescription": "SAG T-1",
            "SeriesInstanceUID": "1.2.840.113619.2.5.1762583153.215519.978957063.121",
            "SeriesNumber": 2,
            "SeriesDate": "20010108",
            "SeriesTime": "120318",
            "Modality": "MR",
            "instances": [
              {
                "metadata": {
                    "Columns": 512,
                    "Rows": 512,
                    "InstanceNumber": 3,
                    "AcquisitionNumber": 0,
                    "PhotometricInterpretation": "MONOCHROME2",
                    "BitsAllocated": 16,
                    "BitsStored": 16,
                    "PixelRepresentation": 1,
                    "SamplesPerPixel": 1,
                    "PixelSpacing": [0.390625, 0.390625],
                    "HighBit": 15,
                    "ImageOrientationPatient": [0,1,0,0,0,-1],
                    "ImagePositionPatient": [11.600000,-92.500000, 98.099998],
                    "FrameOfReferenceUID": "1.2.840.113619.2.5.1762583153.223134.978956938.470",
                    "ImageType": ["ORIGINAL","PRIMARY","OTHER"],
                    "Modality": "MR",
                    "SOPInstanceUID": "1.2.840.113619.2.5.1762583153.215519.978957063.124",
                    "SeriesInstanceUID": "1.2.840.113619.2.5.1762583153.215519.978957063.121",
                    "StudyInstanceUID": "1.2.840.113619.2.5.1762583153.215519.978957063.78"
                },
                "url": "dicomweb://s3.amazonaws.com/lury/MRStudy/1.2.840.113619.2.5.1762583153.215519.978957063.124.dcm"
             }
           ]
         }
       ]
     }
   ]
}

**Comment by sctkndl** [comment]
The problem seems to happen in MeasurementApi.js  with studyInstanceUIDs on the line 697.

`    let timepoint;
        
    if (measurement.StudyInstanceUID) {
      timepoint = this.timepointApi.study(measurement.StudyInstanceUID)[0];
    } else {
        
      const { timepointId } = measurement;
      timepoint = this.timepointApi.timepoints.find(
        t => t.timepointId === timepointId
      );
//    }
timepoint=this.timepointApi.timepoints[0];
  log.info(timepoint);
`
