### ISSUE TITLE
Android 7.1.1: Issue with Routing / Reloading of pages

### ISSUE THREAD

**Issue by davidi1** [OHIF/Viewers#165]
Hello, I am having a weird issue when I try to open a study on an Android tablet that is running Android version 7.1.1., sometimes it will load correctly, other times Chrome will say that it needs to reload the page. If I reload the page, sometimes it will work. Often, I will have to go back to the main page and try to open the study again. That will usually work.

Any help would be much appreciated. If you need anything from me, let me know I will be happy to provide any help I can on my end.

**Comment by swederik** [comment]
Sounds like there is an issue with the Router not functioning on the tablet. It's hard to debug without the device. Could you use Chrome Remote Debugging to get the logs from the Tablet?

**Comment by davidi1** [comment]
Hi @swederik 

I am attaching two crash logs. I hope this helps. When the page crashed while trying to load the image, the remote dev tools said "dev tools lost connection" and it appeared to wipe the console. So, I hope these logs captured the crashes...
[crash.log](https://github.com/OHIF/Viewers/files/2167316/crash.log)
[crash2.txt](https://github.com/OHIF/Viewers/files/2167317/crash2.txt)

**Comment by dannyrb** [comment]
We are moving away from support for version 1 of the Viewer. The goal is to make Version 2 extensible and configurable enough that you can customize it for your workflow and purposes.

This issue hasn't seen activity in some time, so I'm going to close it. OS and device specific issues like this are notoriously hard to diagnose. We're currently considering ways to make reporting issues like this easier. Most mobile device issues are related to the device's memory, GPU, or an outdated browser version.

Sorry we weren't more helpful on this one. Please don't let that stop you from reporting future issues or contributing to the community ^_^
