### ISSUE TITLE
Is there a method to validate if a given file is a valid DICOM file?

### ISSUE THREAD

**Issue by antwort7** [OHIF/Viewers#1650]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Hi, I have a service that uploads dicom files to aws. Is there a way to validate first if a given file has a valid DICOM format?

**Comment by dannyrb** [comment]
If `dicom-parser` can parse the file without throwing an exception, and the codecs bundled in the `cornerstone-wado-image-loader` are able to decode the underlying image data, then it is "valid" as far as our application is concerned.

There are lots of ways to not throw an exception but still pass those two litmus tests. A DICOM file is a dictionary of unsanitized user input.

**Comment by antwort7** [comment]
Hi, I did what you told me. Thanks.

Upon uploading a file in my input I called this function from dicomParser that fails if the format is incorrect.
So I basically did a try and catch

`try{ dicomParser.parseDicom(new Uint8Array(arrayBuffer)) }`
`catch(err) { // Inform the user is not a valid DICOM }`

Its probably not bulletproof. But it works for the basic error cases.
