### ISSUE TITLE
Isolating why "docker run -p 3000:80 ohif/viewer:latest" doesn't run on my server

### ISSUE THREAD

**Issue by chethanjjj** [OHIF/Viewers#1651]
Greetings,

I am new to docker, nginx, and the ohif viewer, so I apologize in advance if my question requires a simple solution. I'm trying to run ohif/viewer:latest on my linux machine, but anytime I run `docker run -p 3000:80 ohif/viewer:latest` it hangs on `Starting Nginx to serve the OHIF Viewer...` and when I ping the server at port 3000 it refused to connect. I know this may not be enough details, so please let me know what more info I could provide to help with finding a solution. I initially though that maybe I would need to install nginx beforehand, however when going to https://hub.docker.com/r/ohif/viewer, they explain the image "bundles the static HTML, CSS, and JS files that comprise The OHIF Viewer progressive web application with the nginx:1.15.5-alpine image".

**Comment by dannyrb** [comment]
@chethanjjj, you could try swapping in an alternative `nginx` config and mapping `nginx`'s log/output to some location on your machine? You can also do something like `docker run -it <image> /bin/bash` to start the image with an interactive bash session.

It may be worth trying an alternative port mapping. Maybe something on your machine is already using `3000`?

I would test the image to verify that it's working for you, but I'm on a Windows machine that doesn't support docker at the moment.

**Comment by chethanjjj** [comment]
**you could try swapping in an alternative nginx config and mapping nginx's log/output to some location on your machine?**

As in using Apache instead? do you have any learning material to explain how to to do this?

**You can also do something like docker run -it <image> /bin/bash to start the image with an interactive bash session.**

I'll try that

**It may be worth trying an alternative port mapping. Maybe something on your machine is already using 3000?**

I've tried using a different port number and yet the problem still persists

**Comment by chethanjjj** [comment]
Hi I solved it. It look
