### ISSUE TITLE
Hi, I really found interested in this DICOM-viewer project, is it possible to save annotations from the embedded version of OHIF-Viewer?

### ISSUE THREAD

**Issue by yesid08** [OHIF/Viewers#1652]
I was able to load the OHIF Viewer locally and connected with orthanac, I am wondering if is it possible to use the viewer to label and then to save the changes in the dicom file? I am using the embedded version, by the way and thank you so much for your time!

**Comment by dannyrb** [comment]
>  I am wondering if is it possible to use the viewer to label and then to save the changes in the dicom file

Possible? Yes. Our current implementation only supports saving _very_ specific information, and in a way that's not as interoperable as I'd like. We're working to offer a cleaner extension/export point for persisting and restoring data like this; as well as updating our own code to more closely follow the recommendations around persisting with DICOM SR (structured reports).

With DICOM, there are a lot of ways to encode the information. Your requirements can drastically change the approach though, and you'll likely need to write a _little bit of code_ either in a custom extension, or by submitting a PR to improve support.

If your application is a closed system, and you don't need to share the information in an interoperable way, I'd argue there's no harm in persisting/restoring by whatever method is most convenient for you.
