### ISSUE TITLE
Unable to run openResty Orthanc with keycloak

### ISSUE THREAD

**Issue by kkmehta03** [OHIF/Viewers#1654]
Used [this](https://docs.ohif.org/deployment/recipes/user-account-control.html) recipe for user control, but didn't find folder structure in accordance with the documentation.
Found the actual recipe under Viewers -> viewer -> platform -> .recipes -> OpenResty-Orthanc-keycloak
When I tried running `docker-compose up` from there, it just threw an error saying dockerfile not found.
So I copied the folder and created the directory according to the documentation <project_root> -> docker -> OpenResty-Orthanc-Keycloak
Again I hit `docker-compose up` and this time I get the below error

![image](https://user-images.githubusercontent.com/25249564/79850820-136d5000-83e2-11ea-86e1-2824522f3a7a.png)

**Comment by dannyrb** [comment]
@KhyatiMehta3, the folder structure has changed since that documentation was written. As you find issues, please don't hesitate to submit PRs to patch things up 🙏

**Comment by KhyatiMehta3** [comment]
I'm not sure I understand.. :smile:  i just pulled in the master code, and tried `docker-compose up`. What should I specifically do to avoid the issue?

**Comment by dannyrb** [comment]
@KhyatiMehta3, this guide: [OHIF + User Account Control](https://docs.ohif.org/deployment/recipes/user-account-control.html) was written as an example. Unfortunately, the dockerfile and other assets used in that guide have not been well maintained. They may need to be updated and fixed.

I was specifically calling out that [this image](https://github.com/OHIF/Viewers/blob/master/platform/viewer/.recipes/OpenResty-Orthanc-Keycloak/dockerfile#L26) likely needs to be a newer one that comes pre-installed with a more recent version of `yarn`.

Then advocating for a PR to fix similar issues and to update the docs as you work through them to help out other community members.

**Comment by KhyatiMehta3** [comment]
Ah okay I think I understood. I'll experiment with it & if successful, I'm happy to submit a PR :smile: Thanks!

**Comment by KhyatiMehta3** [comment]
Hi! I tried it out but it didn't work out :( Anyone tried to achieve orthanc with keycloak after their folder structure change?

**Comment by SurgeGuo** [comment]
I also have the similar question.Anyone succeed using the new structure folder?

**Comment by eng-rsalha** [comment]
I faced the same problem, but I replaced in dockerfile:
"RUN yarn install" with "RUN yarn install --ignore-engines", 
it continued ; ; ;
But stuck again at the followed line:
"RUN yarn run build:web",
error: error Command "build:web" not found.
It should read from packeges.json, but there is no script with this name!!,
Should I try "build:viewer"??, 
Anyone??!!

**Comment by nithin-samudrala** [comment]
did anyone fix this error?
even I am getting the same error

**Comment by sedghi** [comment]
We fixed this recipe recently https://docs.ohif.org/deployment/nginx--image-archive

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
