### ISSUE TITLE
OHIF viewer with access json file to s3  storage not load dicom file

### ISSUE THREAD

**Issue by nenadfemic** [OHIF/Viewers#1657]
Hello,

I am already finish all on my localhost, and it work fine with s3 storage, but i wonder is it possbile to use already online ohif viewer https://viewer.ohif.org/viewer?url=some.json file to load and view dicom file from s3 storage.

https://viewer.ohif.org/viewer?url=https://doctestbucket.s3.eu-west-1.amazonaws.com/3-2020-04-22-14-01-26.json

I am try, but get error in console

Failed to register/update a ServiceWorker for scope ‘https://viewer.ohif.org/’: Storage access is restricted in this context due to user settings or private browsing mode. Workbox.js:453:54
SecurityError: The operation is insecure.

![image](https://user-images.githubusercontent.com/6898640/79980100-dddc6b80-84a2-11ea-95f8-12bf95ee76e0.png)

but with my localhost no problem

![image](https://user-images.githubusercontent.com/6898640/79980202-05cbcf00-84a3-11ea-8fea-ddf9202e936f.png)

Can somebody help . 

Thanks, Nenad

**Comment by sedghi** [comment]
You can look here https://docs.ohif.org/configuration/dataSources/introduction
