### ISSUE TITLE
Check IDC Segmentation scans are now displaying correctly, and debug if not.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1668]
Check that segmentations show up on this study: 

https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us-central1/datasets/lidc-idri-seg-sr-dcm/dicomStores/lidc-idri-seg-sr-dcm/study/1.3.6.1.4.1.14519.5.2.1.6279.6001.131383203689189807643685075952

@fedorov posted that it was working before and broke ([useful background at bullet point (2) here](https://github.com/OHIF/Viewers/issues/1458#issuecomment-611633917)). It may be fixed with all the recent changes.

@igoroctaviano  you can test with the latest branch locally by connecting to IDC. This may be fixed. If not, debug into what the issue could be for this particular study.

**Comment by igoroctaviano** [comment]
@JamesAPetts they show up correctly. 👍
