### ISSUE TITLE
Check show display in dropdown for SEG works correctly.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1669]
> when I select segment from the dropdown, the content of the list below does not change - is this expected behavior or a bug? Screencast here: https://www.screencast.com/t/5l5ttFLWo4T.

Check if this visual bug is still present for studies with multiple segmentations. Can try latest developments on this study: 

https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us-central1/datasets/lidc-idri-seg-sr-dcm/dicomStores/lidc-idri-seg-sr-dcm/study/1.3.6.1.4.1.14519.5.2.1.6279.6001.131383203689189807643685075952

cc @fedorov

**Comment by igoroctaviano** [comment]
@JamesAPetts it was a bug actually, fixed here: https://github.com/OHIF/Viewers/commit/60d249532ef9d3410ac9270afccde691edb87abf

**Comment by fedorov** [comment]
Confirmed, it appears to be fixed. Thanks!
