### ISSUE TITLE
Add and change current Server

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#167]
Now I can add a new server from Server Information box. After that I can change the server for query.
It work perfectly but If someone changes to other server, my current selected server is also changed according to.

My current Server is CR but after someone changes to CT, my current Server becomes CT(at Setting/Server Information box).
Server should be changed per owner (who did change) only.

Server list Information
![selectedserver](https://user-images.githubusercontent.com/12405565/36970309-b62c517c-209a-11e8-9b04-98f83e95caed.png)

**Comment by swederik** [comment]
This is a good point. We should store CurrentServer for the user instead of as a separate collection.

**Comment by dannyrb** [comment]
Unfortunately this issue has grown stale, and with the release of our most recent major version, it is unlikely that we will have the bandwidth to address this issue for our `v1.x` branch. 

If you find that this feature has not yet been implemented in our `master` branch, you are more than welcome to create a [GitHub Issue](https://github.com/OHIF/Viewers/issues/new) to request or discuss it. If you're curious to see what we have planned in the near future, you can [check out our roadmap](https://ohif.canny.io/), and [read our docs](https://docs.ohif.org/).

It may be worth noting that a component for configuring servers does not yet exist for version 2.
