### ISSUE TITLE
Highlight segment when click to jump

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1672]
When we click on a segment in the SEG side-panel and jump to it (possible contour from the RTSTRUCT panel also?), it can be unclear which segment it is if there are many many segments.

It would be nice if this segment flashed for a brief moment so that the user could easily see what segment was jumped to.

**Comment by fedorov** [comment]
This should also help when segmentation is very tiny, and does not have very good contrast:

![image](https://user-images.githubusercontent.com/313942/90694054-f50b4a00-e245-11ea-94c8-077f37eedf75.png)
