### ISSUE TITLE
adding extension 

### ISSUE THREAD

**Issue by fiona3668** [OHIF/Viewers#1673]
Dear developers:

Hi~I am a student want to use this viewer. After I looked at your document, I still do not know how to add the extension tools you list to the viewer. Can you tell me the specific steps I need to do? Like how to register..
![image](https://user-images.githubusercontent.com/57859067/80243119-7138ac80-861b-11ea-8da8-2f6ebeb68ec7.png)

**Comment by dannyrb** [comment]
👋 Hello @fiona3668, this could probably be clarified better in the docs. I'm going to add labels to indicate we would accept improvements/clarifications around how to do this.

When you're building an instance of the OHIF Viewer, you're building the `platform/viewer` project. It consumes the other projects in this monorepo. It can be built with one or more extensions "baked in", or "bundled" with the application. This takes place in: [`platform/viewer/src/index.js`](https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/index.js#L26-L54)

Extensions can also be configured and registered to an already built version of the OHIF Viewer by passing an extension in via the OHIF Viewer's application configuration. You can see an example of post-build registration in this CodeSandbox:

https://codesandbox.io/s/viewer-script-tag-microscopy-extension-44unk

In this example, if you filter the worklist by a modality "SM" and attempt to view it, you'll see that the whole-slide microscopy extension has been registered.

**Comment by knopkem** [comment]
+1 for improving the docs about extensions. The most confusing part for me is the actual naming of extensions. E.g. in the above linked index.js it is used like this:
`defaultExtensions: [OHIFDicomMicroscopyExtension]`
While in the sandbox it is used:
`extensions: [OHIFExtDicomMicroscopy]`
And on the documentation page none of the above is mentioned. It would be nice to add a new column to the table to specify the module name and unify how to use it.

**Comment by wanghan0501** [comment]
+1, I'm confused too

**Comment by sedghi** [comment]
https://docs.ohif.org/development/ohif-cli
