### ISSUE TITLE
 Keycloak Invalid parameter: redirect_uri 

### ISSUE THREAD

**Issue by Vishal568** [OHIF/Viewers#1677]
https://github.com/OHIF/Viewers/issues/268#issuecomment-424265270

Hello, I want to configure Ohif Viewer with dcm4che secure. But I am getting an error 

#### Login with username password.
TypeError: OHIF.user.userLoggedIn is not a function.

#### Login with Keycloak.
Invalid parameter: redirect_uri
![Capture](https://user-images.githubusercontent.com/54707074/80273576-efb34e00-86f0-11ea-94d3-139cfb525f52.JPG)

:8843/auth/realms/dcm4che/protocol/openid-connect/auth?client_id=ohif-viewer&redirect_uri=http://0.0.0.0:3300/_oauth/keycloak&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiIyYVUySlBpeWYzNW5PZWszejJPUGRVR2RGcGxNQ0hOY1lBblhFNHNlV2JNIiwiaXNDb3Jkb3ZhIjpmYWxzZX0=&nonce=rGVP0srYL0LkhZnqLCPNPpJZofJSPKH6uB3hEp8HCWw&response_mode=query&response_type=code&scope=oidc:1 GET https://192.168.1.109:8843/auth/realms/dcm4che/protocol/openid-connect/auth?client_id=ohif-viewer&redirect_uri=http://0.0.0.0:3300/_oauth/keycloak&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiIyYVUySlBpeWYzNW5PZWszejJPUGRVR2RGcGxNQ0hOY1lBblhFNHNlV2JNIiwiaXNDb3Jkb3ZhIjpmYWxzZX0=&nonce=rGVP0srYL0LkhZnqLCPNPpJZofJSPKH6uB3hEp8HCWw&response_mode=query&response_type=code&scope=oidc 400

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
