### ISSUE TITLE
i need to help for fix 2 issues

### ISSUE THREAD

**Issue by yegannezhad** [OHIF/Viewers#1678]
scroll series in mobile view 
in mobile view series not scroll with touch 

 need to close series after click in thumbnail

**Comment by ranasrule** [comment]
> 
> 
> scroll series in mobile view
> in mobile view series not scroll with touch
> 
> need to close series after click in thumbnail

turn on stack scroll to scroll with touch

**Comment by yegannezhad** [comment]
![Untitled](https://user-images.githubusercontent.com/12870943/80317880-a3b0f800-881b-11ea-9f8b-717fce8851da.jpg)

this area not scrolling with touch in mobile .

please help for this issue 

** close series after click in thumbnail in this area**

**Comment by dannyrb** [comment]
We do not maintain support mobile resolutions. This means touch interactions are not tested. If you can introduce a fix/PR, I can merge it; but I can't guarantee it will be regression tested moving forward.

If you need mobile support, you best bet is a hard fork and to apply the necessary changes to add support; find long-term funding so the core team can add and maintain mobile support ^_^ or reach out to an OHIF conultant or consultancy.

**Comment by yegannezhad** [comment]
thanks @dannyrb
