### ISSUE TITLE
Send To Remote DICOM Modality

### ISSUE THREAD

**Issue by davidi1** [OHIF/Viewers#168]
Hello,

I am trying to get the "Send" function of OHIF Viewer to work. No matter what I do, it is greyed out and if I hover over it just shows a Red Circle with a line through it. I attached a screenshot to show what I am seeing (the red circle will not show up in the screenshot, not sure why...)

![ohifsend](https://user-images.githubusercontent.com/36856675/37222460-27f91b3e-239b-11e8-929f-4a0d0131a4c2.jpg)

I am using Orthanc as the DICOM server and if I go to Orthanc Explorer, the "Send to remote modality" option works beautifully from there. I double checked the "DicomModalities" section of orthanc.json and that appears to be correct because I am able to send from Orthanc Explorer.

I am not sure if its a configuration issue on my end or the "Send" option in OHIF Viewer is not fully functional yet. Any help would be much appreciated!

**Comment by swederik** [comment]
This has not been implemented yet. I think the Send button was added as a placeholder, and we just never got around to adding the dialog. I'd be happy to review a pull request for the functionality!

**Comment by davidi1** [comment]
Hi @swederik 

Well, to be completely honest, I have no idea how to create a pull request. I am very new to GitHub and coding in general. I did look for documentation on how to do it and it appears I have to fork and write the code for it?! If that is true, coding is not my strong suit (yet) and I would not be able to contribute anything useful that way.

However, I would like to contribute in some way and I hope this helps...I went and looked up the Orthanc documentation on how they are doing it.

They are using a C-Store command to send the DICOM images to a server that you specify in the DicomModalities section of Orthanc's server config file.

This link provides slightly more information than I did: 
http://book.orthanc-server.com/dicom-guide.html#c-store-sending-images-to-a-server

I am not sure if you could read/use the DicomModalities section of the users Orthanc's server config file in OHIF or not. If not, then I would imagine there would have to be some place in OHIF's config where the user would have to define the remote server. The DicomModalities section of Orthanc's config file includes the Symbolic Name, AET, Port, Host parameters of the remote server where you want to send the DICOM images to. 

I hope this helps!

**Comment by swederik** [comment]
Yeah we would need to do a few things:
- Allow the developer (in the config files) or user (in the UI) to define whether or not a server will accept store requests (either C-STORE or STOW-RS)
- Allow the user to specify which Server they want to send the study to
- Determine 'where' to Send from (e.g. from client via DICOMWeb, from server via DICOMWeb, or from server via DIMSE), depending on the server setup
- Implement the actual Send functions (C-STORE or STOW-RS)
- Monitor / report in the UI the progress of the Send job

Nothing revolutionary, but it's still a non-trivial amount of work. I'd be happy to take a PR if anyone wants to address it!

**Comment by davidi1** [comment]
Thanks for getting back to me.

Please, someone address this. It would be a nice feature to have :-)

**Comment by dannyrb** [comment]
Unfortunately this issue has grown stale, and with the release of our most recent major version, it is unlikely that we will have the bandwidth to address this issue for our `v1.x` branch. 

If you find that this feature has not yet been implemented in our `master` branch, you are more than welcome to create a [GitHub Issue](https://github.com/OHIF/Viewers/issues/new) to request or discuss it. If you're curious to see what we have planned in the near future, you can [check out our roadmap](https://ohif.canny.io/), and [read our docs](https://docs.ohif.org/).
