### ISSUE TITLE
OHIF Viewer hangs when Orthanc Dicomweb "StudiesMetadata" set to "MainDicomTags"

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1680]
Im using the latest version of Orthanc and OHIF Viewer. When Orthanc Dicomweb's "StudiesMetadata" parameter is set to "MainDicomTags" OHIF Viewer hangs after the fetching metadata stage when opening a study. Changing the value of "StudiesMetadata" parameter to "Full" fixes the issue.

**Comment by dannyrb** [comment]
I'm not sure I have enough information to action this one way or the other. Generally, the OHIF Viewer should work with and support DICOMWeb features. If you can point which part of the spec we're not handling correctly, then I know we have a bug to fix. If this is a general integration / Orthanc compatibility issue, it may be outside of scope.

**Comment by ranasrule** [comment]
> 
> 
> I'm not sure I have enough information to action this one way or the other. Generally, the OHIF Viewer should work with and support DICOMWeb features. If you can point which part of the spec we're not handling correctly, then I know we have a bug to fix. If this is a general integration / Orthanc compatibility issue, it may be outside of scope.

It seems to get stuck after reading all the metadata from Orthanc...doesnt move to the next step

![Annotation 2020-04-27 053341](https://user-images.githubusercontent.com/5023419/80324155-d1f8fc80-8848-11ea-8980-5f434169bb92.png)

**Comment by dannyrb** [comment]
Unfortunately this is not enough information for me to go off of.

**Comment by knopkem** [comment]
This reason for this issue can be found here: https://github.com/OHIF/Viewers/issues/1638
I also mentioned my test case using orthanc with maindicomtags and it's not only orthanc that has problems since v3.7.8

**Comment by dannyrb** [comment]
We'll continue to follow in #1638, as it captures this issue more clearly.
