### ISSUE TITLE
Using the OpenResty-Orthanc recipe

### ISSUE THREAD

**Issue by darrent1974** [OHIF/Viewers#1681]
Hi,

I've spent quite a bit of time trying to get an OHIF Viewer running in a docker container that is linked to a Orthanc server running in another docker container on the same machine. I'd like the viewer to start and display the list of studies on my server rather than the "canned" demo studies.

I've gone around in circles with the documentation and seem to have all the elements in place, however whatever I do the viewer always shows the demo data!

In the end I have landed on the "OpenResty-Orthanc" recipe, which I have noticed is now located under the ".recipe" folder (docs need updating). And have attempted the following:

1. Created my own docker-compose file similar to the recipe version for building both the orthanc image and the viewer (attached).

2.  Made a few updates to the dockerfile at "ohif-viewer/platform/viewer/.recipes/OpenResty-Orthanc/dockerfile" (attached in zip), updating the base image references and the copy source for the build output to get it to build.

3. Copied a version of the Nginx config file in the recipe folder to one referenced in my docker-compose file.

4. I can successfully build and launch the containers via docker-compose build and up, however I just can't seem to get my studies to be displayed when I launch the viewer in a browser.

I feel like I'm pretty close to getting it going the way I want but are probably missing some settings or configuration.

Any pointers or suggestions as to where I'm going wrong would be greatly appreciated!

BTW, I think you've done a great job with the viewer and am in the process of slotting this into a full solution using Nvidia Clara for processing and visualising Synchrotron datasets.

Feel free to contact me if you require any further info.

[files.zip](https://github.com/OHIF/Viewers/files/4537272/files.zip)

Regards,

Darren Thompson

**Comment by dannyrb** [comment]
Hello! Thanks for taking the time to provide feedback and clue others in to your solutions. I'm on my phone right now, but my best guess for why you're still pulling up the default studies is that either:

- There is a caching issue, and you're pulling the cached config
- The placement/name of your configuration file does not match the expected (it should be something like `app-config.js` at the root of the directory that serves static content for nginx)

Our recipes and docs due tend to lag. The grant that funds the bulk of the OSS work for OHIF has a very small portion allocated to maintenance and community support. Volunteers and consultancies pick up some of the slack.

Docs and docker recipes are usually pretty quick for me to review. If you tag me on PRs for them, I can try and make time to provide feedback and make sure your effort isn't wasted and your work is merged.

Sending this from my phone. I'll try to double-check your app config location shortly.

**Comment by sedghi** [comment]
This is fixed already in master 

See our recipes https://docs.ohif.org/deployment/nginx--image-archive
