### ISSUE TITLE
RTSTRUCTs not loading correctly.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1683]
This study, and others on the IDC-sandbox, throw on master.

https://idc-sandbox-000.firebaseapp.com/projects/chc-tcia/locations/us-central1/datasets/nsclc-radiomics/dicomStores/nsclc-radiomics/study/1.3.6.1.4.1.32722.99.99.14396249311925406690047103439997976083

The study on the dcmjs PACs is fine.

**Comment by igoroctaviano** [comment]
We load the most recent display set based on **SeriesDate** and **SeriesTime**. Looks like they are not being returned causing load failure.

I'll add an update on our side so if one of these it's not available, we just take the first display set.

@pieper I have checked the metadata req response, maybe something has changed on the config of IDC so that these headers aren’t being returned?

**Comment by fedorov** [comment]
It looks like individual RTSTRUCT contour toggles do not work when I turn off visualization for the whole set. Is this intentional? I interpreted the structure-set toggle as a shortcut to turn on/off individual contours in the hierarchy, and expected I can still toggle them individually.

**Comment by igoroctaviano** [comment]
> It looks like individual RTSTRUCT contour toggles do not work when I turn off visualization for the whole set. Is this intentional? I interpreted the structure-set toggle as a shortcut to turn on/off individual contours in the hierarchy, and expected I can still toggle them individually.

We are setting the visibility property of the whole set. So it's not a batch update like you expected. @JamesAPetts I'm curious if this was the intended behaviour though.

**Comment by fedorov** [comment]
> We are setting the visibility property of the set itself. 

If this indeed is the intended behavior, then the interface needs to be revisited. If by toggling off the whole set I am not longer supposed to be able to toggle individual structures, then why should those eyes be shown and change appearance if I click them? The whole list should probably be greyed out and disabled when the set is off. But I would much rather prefer to have that top-level toggle as batch update (this is how it works in Slicer by the way).

**Comment by JamesAPetts** [comment]
> But I would much rather prefer to have that top-level toggle as batch update

I'm have no strong feeling on this, and I don't have a huge amount experience with the expected UX. Upon reading your comments, a batch update sounds like it does make more sense. Also following similar patterns to slicer just makes sense. This is really easy and small change to make.
