### ISSUE TITLE
OHIF Viewer not pointing to local Orthanc DB

### ISSUE THREAD

**Issue by chethanjjj** [OHIF/Viewers#1687]
I have a podman pod set up for orthanc, mongo, and the ohif viewer.

Each works fine individually, however my OHIF Viewer will not link to my Orthanc DB. I'm not sure why this is happening.

I followed these instructions (Slide 25 and 26), but when I load the OHIF Viewer it just defaults to the 25 studies. Not sure where to go from here.

[Deploying an Open-Source DICOM Archive and Web Viewer with OHIF and Orthanc (Hands-on).pdf](https://github.com/OHIF/Viewers/files/4542922/Deploying.an.Open-Source.DICOM.Archive.and.Web.Viewer.with.OHIF.and.Orthanc.Hands-on.pdf)

**Comment by dannyrb** [comment]
This is the first time I'm seeing that document. It appears to be using the older OHIF version that was based on Meteor. The latest version of OHIF is React based.

> when I load the OHIF Viewer it just defaults to the 25 studies. Not sure where to go from here.

If you're using a newer image, it's likely the application configuration path you're mapping to is incorrect.

**Comment by chethanjjj** [comment]
Changes Made:
1. I used the older version of OHIF Viewer: v1.x
2. Moved the config file (viewer.json) to the same dir as docker compose file and updated the path in the compose file

Result:
when I load the OHIF Viewer it just defaults to the 25 studies

Viewer.json:

For security purposes, I can't reveal the IP address we're using, so I put in a placeholder `[redacted]`, but it's the IP address where my Orthanc DB is located. Anytime I type in "http://[redacted]:8042" into my web browser I can connect to my Orthanc db.

`{
  "apps" : [{
    "name"        : "ohif-viewer",
    "script"	  : "main.js",
    "watch"	  : true,
    "merge_logs"  : true,
    "cwd"         : "/app/bundle/",
    "env": {
	"METEOR_SETTINGS": {
                  "servers": {
                    "dicomWeb": [
                                        {
                        "name": "Orthanc",
                        "wadoUriRoot": "http://[redacted]:8042/wado/",
                        "qidoRoot": "http://[redacted]:8042/dicom-web/",
                        "wadoRoot": "http://[redacted]:8042/dicom-web/",
                        "qidoSupportsIncludeField": false,
                        "imageRendering": "wadouri",
                        "thumbnailRendering": "wadouri",
                        "requestOptions": {
                          "auth": "orthanc:orthanc",
                          "logRequests": true,
                          "logResponses": false,
                          "logTiming": true
                        }
                      }
                    ]
                  },
                  "defaultServiceType": "dicomWeb",
                  "public": {
                             	"ui": {
                                       	"studyListDateFilterNumDays": 365
                                }
                        },
                  "proxy": {
                    "enabled": true
                  }
                }
    }
  }]
}`

**Comment by chethanjjj** [comment]
Solved. it a port problem setting for the OHIF viewer. It was set to 3000:80, instead of 3000:3000
