### ISSUE TITLE
Incorrect bit length when applying Palette Color

### ISSUE THREAD

**Issue by sedenardi** [OHIF/Viewers#1689]
> **Before Creating an issue**
>
> - Are you running the latest version?
Yes
> - Are you reporting to the correct repository?
Yes
> - Did you search existing issues?
Yes

### Describe the Bug

For images with a `PhotometricInterpretation` of PALETTE COLOR, the Palette Color Lookup Table can be either 8 or 16 bits. For 16 bit frames, the lookup table is being squashed because [`arrayBufferToPaletteColorLUT`](https://github.com/OHIF/Viewers/blob/master/platform/core/src/utils/metadataProvider/fetchPaletteColorLookupTableData.js#L122) is converting it to an `Uint8array` before taking into account the bits per entry.

I've ingested the [attached DCM image](https://we.tl/t-hLGHn1hnkX) for WADO-RS following the NEMA docs and this [CornerstoneWADO code](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadouri/metaData/getImagePixelModule.js), producing an array of 16 bit words for the lookup tables that's served in the series metadata fetch. The CornerstoneWADO examples displayed the image correctly, so it led me to examining how the viewer was applying the palette color to the frame. 

### What steps can we follow to reproduce the bug?

1. Open and serve the the attached image on the viewer. You'll just see a black image, and if you inspect you'll see that the lookup table is all `0`s.
2. If you change `arrayBufferToPaletteColorLUT` to use an `Uint16Array` depending on the bits, as the code demonstrates below, it'll show the frames property.

Existing code found [here]:(https://github.com/OHIF/Viewers/blob/master/platform/core/src/utils/metadataProvider/fetchPaletteColorLookupTableData.js#L122)
```js
const arrayBufferToPaletteColorLUT = arraybuffer => {
  const byteArray = new Uint8Array(arraybuffer);
  const lut = [];

  if (bits === 16) {
    for (let i = 0; i < numLutEntries; i++) {
      lut[i] = readUInt16(byteArray, i * 2);
    }
  } else {
    for (let i = 0; i < numLutEntries; i++) {
      lut[i] = byteArray[i];
    }
  }

  return lut;
};
```

Code that works.
```js
const arrayBufferToPaletteColorLUT = arraybuffer => {
  const byteArray = bits === 16 ?
    new Uint16Array(arraybuffer) :
    new Uint8Array(arraybuffer);
  const lut = [];

  for (let i = 0; i < numLutEntries; i++) {
    lut[i] = byteArray[i];
  }

  return lut;
};
```

I'm not sure whether the spec mandates that I serve the lookup tables as 8-bit entries regardless, which would make the Viewer code correct, or whether I'm right in serving them as the correct entry length in the code, which I assume is the case since CornerstoneWADO works.

**Comment by sedenardi** [comment]
FYI, the file I attached is fully anonymized from a sample data set, so no risk of PHI to use for further testing.

**Comment by swederik** [comment]
Ah thanks, could you make a PR for this? We should definitely defer to whatever we are doing in the WADO Image Loader. The file works fine in the local drag/drop (https://viewer.ohif.org/local) so I guess the WADO-RS code is wrong.

**Comment by sedenardi** [comment]
Sure thing, PR submitted https://github.com/OHIF/Viewers/pull/1698.

The local drag/drop passes the file directly to WADO-URI which converts it to the [byte-appropriate LUT](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadouri/metaData/getImagePixelModule.js#L13). Cornerstone's WADO-RS code simply [parses the array of numbers](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadors/metaData/getNumberValues.js#L23) rather than adding them to a typed array before, but that works because it's always coming from an array in that tag's element. Since it looks like the viewer's `MetadataProvider` is taking palette data from multiple sources - URI request, `InlineBinary` (which WADO Image Loader doesn't directly handle) - it needs to cast it as a typed array. This change this will bring the behavior more in line with the Image Loader.

**Comment by sedghi** [comment]
@sedenardi Do you happen to know if this happen in master branch currently? I know it is 3 years later 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by sedenardi** [comment]
We are no longer using the OHIF viewer, so I'm unable to test this. But I assume since https://github.com/OHIF/Viewers/pull/1698 was merged back in 2020 that this issue has been resolved.

**Comment by sedghi** [comment]
Cool, what are you using if you can share

**Comment by sedenardi** [comment]
We have a 3rd party cloud PACS system that bundles their own viewer.

**Comment by sedghi** [comment]
I see, good luck and thanks!
