### ISSUE TITLE
Using ohif as react component

### ISSUE THREAD

**Issue by najimhashgraph** [OHIF/Viewers#1690]
Dear developers,

I want to use Ohif viewer as a react component. in the documentation is the following code described, see below. I do not understand the code , it is not in a class or function structure.
My question is how can I implement the code below to used it as a react component?

import { installViewer } from '@ohif/viewer'

const ohifViewerConfig = window.config // or set it here
const containerId = 'ohif'
const componentRenderedOrUpdatedCallback = function() {
    console.log('OHIF Viewer rendered/updated');
};

componentDidMount() {
   installViewer(
      ohifViewerConfig,
      containerId,
      componentRenderedOrUpdatedCallback
    );
}

render () {
   ...
   //you can render in any element you wish
   <AnyTag id={containerId}/>
}

**Comment by dannyrb** [comment]
`installViewer` is a convenience method for users not familiar with React. You can just use the `<App />` component directly:

https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/index-umd.js

**Comment by najimhashgraph** [comment]
Thank you for your very quick reaction,
I want it to used in in an already existing react app and use ohif as a component in the already existing app, how should i tackle this

**Comment by dannyrb** [comment]
```js

import App from '@ohif/viewer'

<App config={config} />
```

**Comment by najimhashgraph** [comment]
I am sorry , i don't understand, I tried the code below, and i got an error:Minified React error #321;
how should i define {config}



import React, { Component } from "react";
import { App } from "@ohif/viewer";

window.config = {
  // default: '/'
  routerBasename: "/",
  servers: {
    dicomWeb: [
      {
        name: "DCM4CHEE",
        wadoUriRoot: "https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado",
        qidoRoot: "https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs",
        wadoRoot: "https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs",
        qidoSupportsIncludeField: true,
        imageRendering: "wadors",
        thumbnailRendering: "wadors",
      },
    ],
  },
};

class Viewer extends Component {
  render() {
    return (
      <div>
        <h1>Viewer</h1>
        <App config={window.config} />
      </div>
    );
  }
}

export default Viewer;

**Comment by salimkanoun** [comment]
Hi I take this disscusssion (i'm interessted to include OHIF in React App).
What if i want to display OHIF to view directly a particular StudyInstanceUID (not the study list), is there a prop to pass the StudyUID in it ?

**Comment by dannyrb** [comment]
> error:Minified React error

This isn't something we test/use often, so the use case may have some issues that need addressed (feel free to draft a PR). It's possible there is a conflicting `React` version between your Application and what's bundled with our App component?

---
@salimkanoun, this is not (currently) a supported use case. We can influence the application with:

- Application configuration (App component's props)
- By setting the window/frame containing the app's route
    - React router will identify component, set its props, kick off data fetching
    - This requires URL redirect rules on hosting server unless you rebuild the app with `<HashRouter />`

After the "Mode" architecture changes are complete, being able to set the mode and props you would normally find in the URL via the application configuration, would be a nice addition.

**Comment by SaptarshiMisra** [comment]
I have similar requirement like @najimhashgraph 's. 

I have .dcm files present on S3. 

And I am trying to create a React component on my react app that can display that DICOM image ( present on S3 ) . 

I have already written functionality to get the object from S3. And also have installed ohif-viewer (npm i ohif-viewer).


Can anyone guide me on how to proceed next ?

**Comment by legiaquangvn** [comment]
I am interested to see if there is a guidance on this topic, especially with selected dicom file on S3.

**Comment by vasut02** [comment]
how to install @ohif/viewer 'npm i @ohif/viewer' is not working

**Comment by harmakit** [comment]
> I have similar requirement like @najimhashgraph 's.
> 
> I have .dcm files present on S3.
> 
> And I am trying to create a React component on my react app that can display that DICOM image ( present on S3 ) .
> 
> I have already written functionality to get the object from S3. And also have installed ohif-viewer (npm i ohif-viewer).
> 
> Can anyone guide me on how to proceed next ?

+1
it would be nice to use ohif viewer as a component in my react app
