### ISSUE TITLE
Service worker cache messing with authentication

### ISSUE THREAD

**Issue by arantes555** [OHIF/Viewers#1691]
Hello there ! Thanks for the amazing work !

I am trying to make OHIF work behind a reverse-proxy which handles authentication. When unauthenticated, it simply redirects to the login page.

The problem is, whenever the status changes (when logging-in or logging-out), the OHIF page is broken, because it caches everything : the browser's request to `/` gets answered by the ServiceWorker, which prevents my reverse-proxy redirection.

Is there a way to disable the caching for the main page?

**Comment by dannyrb** [comment]
> I am trying to make OHIF work behind a reverse-proxy which handles authentication. When unauthenticated, it simply redirects to the login page.

Ah. I think most of our examples have auth configured through the `oidc` object in the application configuration, so we don't bump into this issue.

> the browser's request to / gets answered by the ServiceWorker, which prevents my reverse-proxy redirection.

You could probably exclude the `index.html` by adding it to the glob ignore patterns for the WorkBox plugin in the WebPack config or `service-worker.js` file. This does negate some of the benefits -- ideally, you would have the client handle redirect for auth.

We're currently using v5.beta1 for workbox. I would have to double check the exact syntax for how to accomplish this for the latest version. They generally have good docs/examples as it's a Google project:

- https://github.com/GoogleChrome/workbox 
- https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest#InjectManifest

**Comment by arantes555** [comment]
@dannyrb thanks for your help, but I managed to work-around my problem by not putting OHIF itself, but only the backend it connects to, behind the authenticating reverse-proxy, then using the `httpErrorHandler` option of `app-config.js` to redirect to the login page upon 401.

I must however point out that having `index.html` cached this aggressively seems to me to be contrary to usual best-practices... For example, if the server updates its version of OHIF Viewer, a client can basically never get the new version without doing a manual Hard reload. From what I have seen most often in deployments, the main page (which is usually pretty light anyway in modern SPAs) is not cached at all, and calls resources (JS and CSS) with unique names (random, or even hashes), so they are cached as much as possible, but are updated as soon as the main page requests a new version.

**Comment by dannyrb** [comment]
@arantes555, we're mostly using WorkBox defaults. I think the default assumes you're trying to achieve an offline capable web application (PWA); which means that `index.html` needs to be cached. Changes to the cache manifest, file content hashes, and the service worker are all effectively handled for new builds. After a new deploy to `https://viewer-dev.ohif.org` on a merge to master, you'll see the old application load, detect a new service-worker, and flash as the worker's `skipWaiting()` is called to trigger it's install while the previous worker is removed.

There are a few user experience items I would like to improve around service workers, it just hasn't been a priority for the group(s) that direct my efforts.

**Comment by pieper** [comment]
One extra comment - I also have found I need a hard reload when updating OHIF, but also if for testing I reuse a localhost port like 8080 that once hosted OHIF it tries to use the OHIF service worker and won't load the page.  @dannyrb if you think there's a solution for this I can open this up in a new issue.

**Comment by dannyrb** [comment]
@pieper can you open a new issue with steps to reproduce? I believe WebPack purposefully prevents serviceworker registration when you use its dev-server. If you're only seeing this locally, we could add a check to in the worker to prevent it from registering when run locally.

If you're seeing this anywhere other than from a simple local http server, then this is a much bigger issue that bumps the priority (imo).

**Comment by pieper** [comment]
Thanks, @dannyrb I'll keep an eye open for when this happens so I can document how to reproduce and file a report.  Basically I was just using the `http-server` package on a static site and it would not load unless I used `command-shift-R`.
