### ISSUE TITLE
Access to imageIdIndex value when updated

### ISSUE THREAD

**Issue by sinanmb** [OHIF/Viewers#1694]
Hi, 

I would like to have access to the updated imageIdIndex value of a CornerstoneViewport. I see that it's present in CornerstoneViewport's state but I don't see how I could access it for example from `OHIFCornerstoneViewport.js `

As a workaround, I manage to read it from the element passed in the event to `_updateTextForNearbyAnnotation` to a custom tool I created (similar to the implementation in `arrowAnnotateTool`, but that's quite hacky and I was wondering if there's a cleaner way to do it.

Thank you.

**Comment by sedghi** [comment]
In latest master, there are STAKC_NEW_IMAGE and VOLUME_NEW_IMAGE at the cornerstone3D that you can listen to
