### ISSUE TITLE
SVG Crosshair issues in VTK

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1696]
The crosshairs are implemented as SVG and are thus dom elements and need to be carefully resized when its parent is resized.

![](https://media.giphy.com/media/KEMJBb3zjRuaZlIL6Q/giphy.gif)

Notes:
- The crosshairs are properly resized on scaling of the window.
- This issue may need to be fixed at the `react-vtkjs-viewport` layer.

**Comment by pieper** [comment]
This may be out of date -- need to test and close if not needed.

**Comment by pieper** [comment]
This should be addressed as part of the update to the core off screen rendering functionality. Related to #2238

**Comment by Punzo** [comment]
out of date
