### ISSUE TITLE
/Callback not found issue in GCP OAuth

### ISSUE THREAD

**Issue by capt2101akash** [OHIF/Viewers#1697]
> **Before Creating an issue**
>
> - Are you running the latest version? Yes
> - Are you reporting to the correct repository? Yes
> - Did you search existing issues? Yes

### Describe the Bug

When authenticating with GCP's Oauth and trying to use the viewer for production. In the /callback stage the error is showing /callback not found. I am using http-server to run the viewer locally.

### What steps can we follow to reproduce the bug?

1. Build for production for google cloud integration.
2. Run the components using http-server.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by capt2101akash** [comment]
Following up to the previous question, Can anyone help me in identifying the problem.

**Comment by dannyrb** [comment]
http-server does not setup the redirects a SPA application expects. OHIF's routing is client-side, so all server routes that don't return a resource need to redirect to index.html

**Comment by capt2101akash** [comment]
So, if we want to build a production level instance of GCP Healthcare integrated OHIF viewer what would be the proper steps to do. Because while running in the dev environment it's responding very slowly.

**Comment by dannyrb** [comment]
For the developing, use `yarn run dev`. For production, build the application and deploy it to a server that has appropriate redirect rules in place.

I'm not sure I understand what issue(s) you're running into. A better overview of what you've tried and the specific issues/bottlnecks/unmet expectations would be helpful.

**Comment by capt2101akash** [comment]
Thanks @dannyrb  for your responses got to make it run by changing the `NODE_ENV` environment variable to `production`
