### ISSUE TITLE
Error Loading Image

### ISSUE THREAD

**Issue by yehudahkay** [OHIF/Viewers#170]
Hi I built the standalone viewer as described but I get the following for both the sample dicom and jpeg

![image](https://user-images.githubusercontent.com/9964988/37655157-291e7468-2c4d-11e8-8e3a-d05f9ad0cb2a.png)

**Comment by swederik** [comment]
What kind of error do you have in your browser console?

**Comment by yehudahkay** [comment]
Here it is, I guess i need to use local files? I was just following the instructions on https://docs.ohif.org/standalone-viewer/usage.html

![image](https://user-images.githubusercontent.com/9964988/37658789-01dd7278-2c57-11e8-9ddf-a02da9ecb50d.png)

**Comment by swederik** [comment]
Ah it looks like rawgit turned off CORS.... I guess we will have to switch to AWS S3 or something. Thanks for the heads up!

**Comment by swederik** [comment]
There is some more sample data JSON files here: https://github.com/OHIF/Viewers/tree/bec5d144437202b0a86bd26f7df387f15cdc5e52/StandaloneViewer/StandaloneViewer/private/testData

which point to S3 but they are still improperly organized, so the series / images do not show up in the correct order.

**Comment by swederik** [comment]
This is weird though, since this one works fine:

http://ohif-viewer.s3-website.eu-central-1.amazonaws.com/?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/sampleDICOM.json

And the JSON file:

https://s3.eu-central-1.amazonaws.com/ohif-viewer/sampleDICOM.json

also points to rawgit.

**Comment by dannyrb** [comment]
Unfortunately this issue has grown stale, and with the release of our most recent major version, it is unlikely that we will have the bandwidth to address this issue for our `v1.x` branch. 

If you find that this has not yet been addressed in our `master` branch, you are more than welcome to create a [GitHub Issue](https://github.com/OHIF/Viewers/issues/new) to request or discuss it. If you're curious to see what we have planned in the near future, you can [check out our roadmap](https://ohif.canny.io/), and [read our docs](https://docs.ohif.org/).
