### ISSUE TITLE
Breast Tomosynthesis  support

### ISSUE THREAD

**Issue by vicOnGit75** [OHIF/Viewers#1702]
OHIF ( 3.11.2 Viewer version ) is  hanging on attempt to display file of SOP Class 1.2.840.10008.5.1.4.1.1.13.1.3.
( actually after errors in dcmje.es.js?f5f5:1214 --Invalid vr type ).
Is such behavior somehow expected?
Or there is the problem with specific instance?
File has  ~200 MB size and supposed to have 72 frames.
It can be successfully opened in Weasis 3.5.4
Thank you

**Comment by sedghi** [comment]
We have a study in the demo for Tomo
https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.2.826.0.1.3680043.8.498.11387662677066579919319049302075478647

**Comment by arturojain** [comment]
for some reason my images are displaying each image as a separate image instead of the series. I use DICOMJSON. Any idea what could be the reason?

**Comment by sedghi** [comment]
@arturojain probably your metadata is diverse and OHIF thinks it is different displaysets

**Comment by arturojain** [comment]
> @arturojain probably your metadata is diverse and OHIF thinks it is different displaysets

It displayed correctly as a series in v2. That is what is throwing me off balance.

**Comment by sedghi** [comment]
@arturojain can you create a separate issue and share your anonymized data?

Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by arturojain** [comment]
@sedghi yes, here is the new issue: https://github.com/OHIF/Viewers/issues/4239
