### ISSUE TITLE
how to disable toolbar buttons on OHIF

### ISSUE THREAD

**Issue by visconnect** [OHIF/Viewers#1704]
Hi Folks,

We need to provide a "read only" instance of OHIF where one set users can use complete feaure set of OHIF but another set of users can only view the images with measurements (no edit or new annotations or measurements) .

How do we acheive this ? great if any leads can be provided to help us.

**Comment by eolasd** [comment]
Hi @visconnect 
I had a similar issue and I ended up just removing/commenting out the tools I didn't require in the file below..
https://github.com/OHIF/Viewers/blob/f9fe4232e755d2478dae4c70dac90a7b42e34846/extensions/cornerstone/src/toolbarModule.js#L37

For your requirements -  maybe you could copy the extension and create a new custom version with the tools you require that gets enabled only for certain users.

Not sure about programmatically enabling/disabling extensions - I think you could that in the config file by switching out configs outside of OHIF before it loads - depending on where your user logic is.

For measurements in particular - they seem to be more 'baked in' in to the core viewer app - not in an extension... Hopefully the core team will correct me if I am wrong on this and can provide some insight.

**Comment by juanise** [comment]
Here is what i have done in an older version, but i do not know if it is the best way.

extensions/cornerstone/src/toolbarModule.js
in definition i have added a field in all buttons:

id: 'Zoom',
    label: 'Zoom',
    icon: 'search-plus',
    type: TOOLBAR_BUTTON_TYPES.SET_TOOL_ACTIVE,
    commandName: 'setToolActive',
    commandOptions: { toolName: 'Zoom' },
    group: 'GENERAL', // this could be GENERAL for the ones that do not change, or 'SPECIFIC'

in platform/core/redux/actions.js

add an action like this:

// I show some buttons depending on modality
export const toggleButtons = (modality) => ({
  type: 'TOGGLE_BUTTONS',
  modality,
});
and add toggleButtons to exported actions.

in my case in platform/viewer/src/connectedComponents/ConnectedViewer,js
const { setTimepoints, setMeasurements, toggleButtons } = OHIF.redux.actions;

add to mapDispatchToProps:
onToggleButtons: modality => {
        dispatch(toggleButtons(modality));
    },
in platform/viewer/src/connectedComponents/Viewer,js I add this function

onToggleButtons = modality => {
    if (this.props.onToggleButtons) {
      this.props.onToggleButtons(modality);
    }
  };
and I make a call to this.onToggleButtons from componentDidUpdate

in platform/viewer/src/store/layout/reducers.js
const defaultState = {
  labelling: {},
  contextMenu: {},
  showTool: false
};

add a case

case 'TOGGLE_BUTTONS':
      const ui = Object.assign({}, state.ui, {
        showTool: action.modality === 'MG',
      });

      return Object.assign({}, state,{
        ... ui,
      });

in platform/viewer/src/connectedComponents/ToolBarRow.js
function _getButtonComponents(toolbarButtons, activeButtons) {
return (
      <ToolbarButton
        key={button.id}
        label={button.label}
        icon={button.icon}
        onClick={_handleToolbarButtonClick.bind(this, button)}
        isActive={activeButtons.includes(button.id)}
        group={button.group} // add this
      />

in platform/ui/src/viewer/ToolBarButton.js


const { isActive, icon, labelWhenActive, onClick, t, showTool, group } = props;

return (<div> {showTool === true && group === 'SPECIFIC' ?
    <div className={className} onClick={handleClick}>
      {iconProps && <Icon {...iconProps} />}

      <div className="toolbar-button-label">
        {t(label)}
        {arrowIcon}
      </div>
    </div>  : group !== 'SPECIFIC' &&
    <div className={className} onClick={handleClick}>
      {iconProps && <Icon {...iconProps} />}
      <div className="toolbar-button-label">
        {t(label)}
        {arrowIcon}
      </div>
    </div>}
      </div>
  );

I connect ToolbarButton

const mapStateToProps = state =>({
  showTool: state.ui.showTool
});

export default connect (mapStateToProps, {})(withTranslation('Buttons')(ToolbarButton));


I supose you have to do something similar.
Hope it helps.

**Comment by kevalnagda** [comment]
Any update on this?
Is there any way to configure this from ohifViewerConfig?

**Comment by sedghi** [comment]
How about in the other version you don't put a toolbar?

**Comment by CellCS** [comment]
is it possible to disable button like 'Zoom' in ohif.js when using ohif plugin? 

Like to add some configuration in 

```
window.config = {

}
```
