### ISSUE TITLE
CircleCI e2e test failure in latest build with message: Timed out retrying: expected '<div>' to contain text 'Reform'

### ISSUE THREAD

**Issue by gurpreet-tavisca** [OHIF/Viewers#1706]
Hello,

I am new to this project. My first question/finding.

I noticed the latest CircleCI build was [red](https://circleci.com/gh/OHIF/Viewers/11359). On further investigation it was because of the following failure in Cypress E2E test: 

```
1) OHIF VTK Extension "before all" hook for "checks if VTK buttons are displayed on the toolbar":
     CypressError: Timed out retrying: expected '<div>' to contain text 'Reform', but the text was ' W: 350 L: 50)} W: 350 L: 50)} W: 350 L: 50)}'

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'OHIF VTK Extension'
```
I ran the cypress test suite locally on my MBP and it also failed with the same message. On further investigation I realised it is because the app is taking time to "Reformat" the image, and the test times out before reformatting is complete. The timeout is currently set in code to 30000ms (30 sec), but on my MBP it takes about 45sec for formatting to complete. I guess the same thing is happening on CircleCI where the formatting is taking longer than the timeout period. If I increase the timeout to 60sec, test passes. 

Code change needed was in file: `platform/viewer/cypress/support/commands.js`, for command: `waitVTKReformatting`

```
// Wait for finish reformatting
  cy.get('[data-cy="viewprt-grid"]', { timeout: 30000 }).should($grid => {
    expect($grid).not.to.contain.text('Reform');
  });
```

Let me know if you would like me to raise a PR to increase the timeout. Or maybe this is a known issue and the problem is somewhere else since earlier builds seem green.

Thanks!

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
