### ISSUE TITLE
Loading a scan with missing pixel data leads to uninformative endless loading.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#171]
Hi,
Today my colleague discovered an edge-case which I believe should be changed to throw an error.

If a DICOM instance has complete and valid headers, but no pixel data, the page will endlessly load rather than show an error. If one has an entire series with missing pixel values (due to some error), the user has no idea about this and will sit at an endless loading screen. I believe showing a DICOM loading error stating that there is insufficient data to render an image would be more useful.

Unfortunately I cannot share the problem DICOM, but this should be easily reproducible by taking any DICOM image and deleting the pixel data information.

Thanks for all the hard work,
James

**Comment by swederik** [comment]
Hi @JamesAPetts,

Looks like this will be fixed by https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/176

We'll try to get that in ASAP.

Thanks for the report!

**Comment by JamesAPetts** [comment]
Hi @swederik,

Aha, I searched to make sure the issue wasn't already present here, but didn't search the cornerstone issues page.

Thanks for the reply!
James
