### ISSUE TITLE
Adding new DICOM tags to OHIF viewer

### ISSUE THREAD

**Issue by capt2101akash** [OHIF/Viewers#1720]
Can anyone help me out in adding new DICOM metadata tags to OHIF viewer. I have added a new tag in the qido/studies.js and the viewers/services. But unable to show it in the top right corner of the ohif viewer.
Any help would be greatly appreciated.

**Comment by capt2101akash** [comment]
@dannyrb any guidance?

**Comment by nutzlastfan** [comment]
I have done it with directly adding the tags in the reactcornerstoneviewport (ViewportOverlay.js and metadataProvider.js ) you have to build the project first after editing it and than copy it over the dependency in the ohif build, than build the viewer.

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
