### ISSUE TITLE
IDC Sandbox crash when source data for segmentation unavailable.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1728]
This study has a SEG and no data, which causes the viewer to crash when you open the side panel:

https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us/datasets/issues/dicomStores/issue-2-kits/study/1.3.6.1.4.1.14519.5.2.1.3344.2526.263641901853377103400543370074

We need to handle this case gracefully and not crash. I suppose the side panel should open with the SEGs greyed out on dropdown @fedorov ?

**Comment by fedorov** [comment]
Yes, makes sense to me.
