### ISSUE TITLE
`yarn run dev` cannot live-reload the example viewer app

### ISSUE THREAD

**Issue by kwafok** [OHIF/Viewers#1730]
> **Before Creating an issue**
>
> - Are you running the latest version?
Yes. I git clone repo and test master branch today.
> - Are you reporting to the correct repository?
Yes. I git clone repo https://github.com/OHIF/Viewers and test it by `yarn run dev` 
> - Did you search existing issues?
Yes, I have some keywords: "reload", "refresh", "hmr" , but have not found related issues.
### Describe the Bug

I found `yarn run dev` cannot live-reload the example viewer app
### What steps can we follow to reproduce the bug?
1. Run `git clone https://github.com/OHIF/Viewers.git ohif-viewer`
2. Run `yarn install`
3. Run `yarn run dev` to test the example viewer app in Chrome at http://localhost:3000/
4. Visit the file https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/App.js#L151 and add some `console.log`.

The viewer app cannot receive updated code. I have to re-run `yarn run dev` to apply updated code.

Console have some warning messages:
![image](https://user-images.githubusercontent.com/7870790/81916331-47fdb180-9606-11ea-81ef-64a66afe83a6.png)
![image](https://user-images.githubusercontent.com/7870790/81916359-5055ec80-9606-11ea-8a1e-f45849ddc25e.png)

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

If the issue persists please reopen
