### ISSUE TITLE
Embeded viewer: 404 on loading series

### ISSUE THREAD

**Issue by laksmig6** [OHIF/Viewers#1731]
> :hand: REQUIREMENT:
> We have a web application on which we are trying to embed a OHIF viewer.(viewer@3.11.7)
> A separate link. On click of the link, a study page should open on the new tab using the OHIF > viewer.
> At this point I have the studyInstanceUid available.

**Description**

I have Orthanc server running locally and another instance running on docker ( jodogne/orthanc-plugins version-1.5.6 )

Locally when I try to hit the viewer url, dicom image is rendered fine but the same image if I try to hit on the deployed environment ( docker instance ), series call is throwing 404.

Attached both the local and deployed url screenshots for reference:
- I see difference in response of series url
- study url
- as well as meta data

<img width="1440" alt="Screenshot 2020-05-14 at 11 06 43 PM" src="https://user-images.githubusercontent.com/19832110/81966868-be66d780-9637-11ea-81fe-5b0c146d1e3c.png">

<img width="1440" alt="Screenshot 2020-05-14 at 10 54 30 PM" src="https://user-images.githubusercontent.com/19832110/81966883-c292f500-9637-11ea-9e20-4574c0f3f5c9.png">

<img width="1440" alt="Screenshot 2020-05-14 at 10 58 08 PM" src="https://user-images.githubusercontent.com/19832110/81966885-c3c42200-9637-11ea-8a07-57a1b5a26bd3.png">

<img width="1440" alt="Screenshot 2020-05-14 at 10 59 27 PM" src="https://user-images.githubusercontent.com/19832110/81966887-c4f54f00-9637-11ea-95cb-6a2deef6751f.png">

<img width="1440" alt="Screenshot 2020-05-14 at 10 59 08 PM" src="https://user-images.githubusercontent.com/19832110/81966890-c4f54f00-9637-11ea-809f-64a05d60d163.png">

<img width="1440" alt="Screenshot 2020-05-14 at 10 58 59 PM" src="https://user-images.githubusercontent.com/19832110/81966891-c58de580-9637-11ea-88ba-16aa376d529c.png">

**depoyed orthan explorer url:** https://ncg-dev.projecteka.in/dicom-web/app/explorer.html ( I have the same images uploaded here )
**deployed app url:** https://ncg-dev.projecteka.in/viewer/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170?dicomCtx=L2RpY29tLXdlYg==

refer https://github.com/OHIF/Viewers/issues/1592 for few details in case it is required.

**Comment by laksmig6** [comment]
If i try to hit the url https://ncg-dev.projecteka.in/dicom-web/studies/3abaec0a-ebfaaa87-f830d52b-d62df074-6a692c12/series which is with the UID (studies/UID/series) not the studyInstanceID, it gives me the response.
But again this response is not matching with what I get locally when I hit 'studies/studyInstanceId/series'

I need support on understanding what is wrong here and also whether to use UID or studyInstanceID

**Comment by laksmig6** [comment]
@dannyrb, Could you please help me out here ?

**Comment by sedghi** [comment]
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe

Feel free to reopen if the issue persists
