### ISSUE TITLE
Infinite frame index change when quickly jumping between two segments.

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#1733]
#1645 was recently merged and it generated another issue with segmentations panel:

- When quickly jumping between two segments (faster than the debounce time of the jump function invocation), the onNewImage event from react-cornerstone-viewport (which triggers the jump to image command) is being called in an infinite loop, this is probably caused by event binding in react-cornerstone-viewport or state check in ohif cornerstone viewport.

**Comment by igoroctaviano** [comment]
@fedorov I'm working to fix this issue now.

**Comment by fedorov** [comment]
Nice - now I know that I am faster than the debounce time of the jump function invocation! :-D

**Comment by igoroctaviano** [comment]
> Nice - now I know that I can be faster than the debounce time of the jump function invocation! :-D

😆
