### ISSUE TITLE
Embedded viewer does not include Authorization headers when fetching dicom instances, stand-alone does

### ISSUE THREAD

**Issue by fvdnabee** [OHIF/Viewers#1736]
## Bug Report
When setting up a requestOptions.auth element for dicomWeb in OHIF's config, the embedded viewer only includes the Authorization header for GET requests to dicom-web/studies, dicom-web/studies/xxx/series and dicom-web/studies/xxx/series/yyyy/metadata. 

Requests to studies/xxx/series/yyy/instances/zzz1/frames/1,  studies/xxx/series/yyy/instances/zzz2/frames/1, etc. do not include the Authorization header. This leads to a 401 Unauthorized response from the dicom-web server. 

I experience this using the latest ovif release via an embedded script pointing to https://unpkg.com/@ohif/viewer (see below). When I build OVIF for production, as per [the documentation](https://docs.ohif.org/deployment/recipes/build-for-production.html); so from latest master, the Authorization header is included and the instance requests receive a 200 response.  

I've included two screenshots of the XHR requests of the embedded and the production viewer below. Embedded is on the left, production on the right. The first screenshot compares the CORS preflight requests. The second the actual requests for retrieving the dicom instances. Note that already in the CORS preflight requests, the Access-Control-Request-Headers header does not include authorization in the embedded viewer. It does in the standalone. In the actual requests, the authorization header is missing in the embedded viewer.

### Describe the Bug

Embedded viewer does not include Authorization headers for dicom-web dicom instance requests

### What steps can we follow to reproduce the bug?

1. Setup an embedded ovif viewer coupled with a dicom-web server that expects Authorization (basic) headers
2. Try to view a dicom series in the viewer
3. The viewer fails to render, inspection of the network traffic reveals 401 Unauthorized responses

```js
  <script src="https://unpkg.com/@ohif/viewer" crossorigin></script>
  <script>
    var containerId = "root";
    var componentRenderedOrUpdatedCallback = function(){
      console.log('OHIF Viewer rendered/updated');
    }

window.config = {
  // default: '/'
  routerBasename: '/',
  extensions: [],
  showStudyList: true,
  filterQueryParam: false,
  servers: {
    dicomWeb: [
      {
        name: 'scorthanc',
        wadoUriRoot: 'https://orthanc.yyy.zzz/orthanc/wado',
        qidoRoot: 'https://orthanc.yyy.zzz/orthanc/dicom-web',
        wadoRoot: 'https://orthanc.yyy.zzz/orthanc/dicom-web',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        requestOptions: {
          auth: 'user:password',
        },
      },
    ],
  },
  cornerstoneExtensionConfig: {},
  // Following property limits number of simultaneous series metadata requests.
  // For http/1.x-only servers, set this to 5 or less to improve
  //  on first meaningful display in viewer
  // If the server is particularly slow to respond to series metadata
  //  requests as it extracts the metadata from raw files everytime,
  //  try setting this to even lower value
  // Leave it undefined for no limit, sutiable for HTTP/2 enabled servers
  // maxConcurrentMetadataRequests: 5,
};

    window.OHIFViewer.installViewer(
      window.config, containerId, componentRenderedOrUpdatedCallback);
	</script>

```

Details of a preflight CORS request (embedded left, production build right):
![ovif-pre-flight](https://user-images.githubusercontent.com/1157936/82030304-9196dc80-9698-11ea-8f1a-ff284fa588aa.png)

Details of a dcm instance request (embedded left, production build right):
![ovif-dcm-instance](https://user-images.githubusercontent.com/1157936/82030309-952a6380-9698-11ea-899d-d7cdcf007d7a.png)

**Comment by Diex** [comment]
same here using embeded option:
script.src = 'https://unpkg.com/@ohif/viewer@latest/dist/index.umd.js';
Studies retrived (authorization header included in the request) but when it starts getting images I get 401:

code: 401
message: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
status: "UNAUTHENTICATED"

config:

dicomWeb: [
              {
                wadoUriRoot: 'https://healthcare.googleapis.com/v1/projects/blablabla/dicomWeb',
                qidoRoot: 'https://healthcare.googleapis.com/v1/projects/blablabla/dicomWeb',
                wadoRoot: 'https://healthcare.googleapis.com/v1/projects/blablabla/dicomWeb',
                qidoSupportsIncludeField: true,
                imageRendering: 'wadors',
                thumbnailRendering: 'wadors',
                requestOptions: {
                  auth: (options) => { 
                    return 'Bearer ' + token 
                  }
                }
              }
            ],

**Comment by Diex** [comment]
maybe related to this https://github.com/OHIF/Viewers/pull/1646 but still out from my understanding.

**Comment by Diex** [comment]
I can confirm this also happens on the standalone version. so the bug has to do with the image request not adding the header. could anyone point me to the file/class where this is take place?

**Comment by Diex** [comment]
found this: 

```
retrieveTimepoints
getAuthorizationHeader.js?2067:17 get authorization {auth: ƒ}  <<< --- added log in getAuthorizationHeader.js looks good
TimepointApi.js?dda4:92 Timepoint data retrieval
<<<< ---- click on study
dicomweb-client.es.js?f399:873 search series of study 1.2.840.113704.1.111.10096.1570895568.1
dicomweb-client.es.js?f399:903 retrieve metadata of series 1.2.840.113704.1.111.10096.1570895684.8

getAuthorizationHeader.js?2067:17 get authorization undefined  <<<< ---- now requestOptions is undefined
MeasurementService.js?59d2:350 Subscribing to 'event::measurement_added'.
```

**Comment by christianvargasforero** [comment]
Hello @Diex, a question, how are you generating the Bearer type token? I have tried to generate it through JWT and OIDC but I have not been able to create a token that functions for me to make authorized machine-to-machine calls to google healthcare.

**Comment by Diex** [comment]
the answer is here: https://cloud.google.com/healthcare/docs/how-tos/authentication

I started a new firebase project from scratch.
the usual way is to set an endpoint to retrieve it (your token). because you need to sign it using your service account RSA private key. so you need to keep it safe.

I used cloud functions with express for creating an api.

`this.http.get(this.api + '/sign', { responseType: 'text' }).subscribe(
result => this.token = result );`

then you have to use the 'requestOptions' parameter on the ohif servers settings (remove odic);

```
requestOptions: {
                  auth: (options) => { return 'Bearer ' + this.token }
                }
```

token needs to be signed and include a valid date/expiration

see:

https://jwt.io/
https://firebase.google.com/docs/auth/admin/create-custom-tokens
https://github.com/auth0/node-jsonwebtoken (used to sign the token)

**Comment by christianvargasforero** [comment]
@Diex Thank you very much, I will review it.

**Comment by dannyrb** [comment]
I believe most metadata requests are made by OHIF via dicomweb-client, and image requests are made by cornerstone-wado-image-loader (a dependency of the `@ohif/extension-cornerstone` and `@ohif/extension-vtk` projects)

The requests you're having issues with are likely made by cornerstone-wado-image-loader. If you have a back-end, you can create a proxy. If things aren't working as expected, this may be the area you need to inspect:

https://github.com/OHIF/Viewers/blob/709f14708e2b0f912b5ea509114acd87af3149cb/platform/viewer/src/config.js#L45-L60

Some extensions handle requests themselves, and not necessarily in a consistent way. It's also possible you're seeing an issue crop up because of inconsistent requesting.

Ideally, extensions would ask _OHIF the platform for information_, and if it's not available, OHIF would handle all requests. Doing something like that would make it easier for us to be a bit more predictable.

**Comment by Diex** [comment]
oh I see... thank you very much @dannyrb 
I'll let you know. 
thanks.

**Comment by Diex** [comment]
I figured out how to reverse proxy the dicomweb endpoint. but regardless using my custom proxy url, when OHIF tries to fetch the images 'https://healthcare.googleapis.com/v1beta1/projects/... bla bla' is where it points to. Is there any way to avoid this?

```
wadoUriRoot: 'http://localhost:5001/myproject-prod/us-central1/api/wado',
        qidoRoot: 'http://localhost:5001/myproject-prod/us-central1/api/wado',
        wadoRoot: 'http://localhost:5001/myproject-prod/us-central1/api/wado',
```

that's my proxy that seems to work ok because I get the studies list but fails on the image fetch.

Any advice, recipe or 'where to look' will be greatly aprecieated.

**Comment by Diex** [comment]
> I figured out how to reverse proxy the dicomweb endpoint. but regardless using my custom proxy url, when OHIF tries to fetch the images 'https://healthcare.googleapis.com/v1beta1/projects/... bla bla' is where it points to. Is there any way to avoid this?
> 
> ```
> wadoUriRoot: 'http://localhost:5001/myproject-prod/us-central1/api/wado',
>         qidoRoot: 'http://localhost:5001/myproject-prod/us-central1/api/wado',
>         wadoRoot: 'http://localhost:5001/myproject-prod/us-central1/api/wado',
> ```
> 
> that's my proxy that seems to work ok because I get the studies list but fails on the image fetch.
> 
> Any advice, recipe or 'where to look' will be greatly aprecieated.

**enableGoogleCloudAdapter: false,**  solved it.
but still can't fetch the image... (now silently)

Timepoint data retrieval
dicomweb-client.es.js?f399:873 search series of study 1.2.840.113704.1.111.7728.1441400043.1
dicomweb-client.es.js?f399:903 retrieve metadata of series 1.2.840.113704.1.111.7728.1441400195.11

but nothing happens... 
any thought?

**Comment by christianvargasforero** [comment]
@Diex As an end point of the GC API, i use dicomWeb not wado, you have tested this
          qidoRoot:'https://healthcare.googleapis.com/v1beta1/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomstore/dicomWeb',     wadoRoot:'https://healthcare.googleapis.com/v1beta1/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomstore/dicomWeb',         wadoUriRoot:'https://healthcare.googleapis.com/v1beta1/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomstore/dicomWeb',

**Comment by Diex** [comment]
yes indeed. that was my first approach:

```

servers: {
            // This is an array, but we'll only use the first entry for now
            dicomWeb: [
              {
                wadoUriRoot: 'https://healthcare.googleapis.com/v1/projects/my-project/locations/us-central1/datasets/chest-wall/dicomStores/dicoms/dicomWeb',
                qidoRoot: 'https://healthcare.googleapis.com/v1/projects/my-project/locations/us-central1/datasets/chest-wall/dicomStores/dicoms/dicomWeb',
                wadoRoot: 'https://healthcare.googleapis.com/v1/projects/my-project/locations/us-central1/datasets/chest-wall/dicomStores/dicoms/dicomWeb',
                qidoSupportsIncludeField: true,
                imageRendering: 'wadors',
                thumbnailRendering: 'wadors',
                requestOptions: {
                  auth: (options) => { 
                    return 'Bearer ' + token // custom token generator -> it works only on studies list
                  }
                }
              }
            ],
          }
```

what do you suggest?

**Comment by epileftico** [comment]
I'm having the exactly same issue, but, the only difference is, I'm using HTTP Basic Auth, so my server looks like:

servers: {
            // This is an array, but we'll only use the first entry for now
            dicomWeb: [
              {
                wadoUriRoot: 'https://dummysite.com/dummypacs/wado',
                qidoRoot: 'https://dummysite.com/dummypacs/rs',
                wadoRoot: 'https://dummysite.com/dummypacs/rs',
                qidoSupportsIncludeField: true,
                imageRendering: 'wadors',
                thumbnailRendering: 'wadors',
                requestOptions: {
                  auth: (options) => { 
                    return 'Basic XXXxxXXXXXXXXX'
                  }
                }
              }
            ],
          }

I'm deploying DCM4CHEE PACS, and HTTP is handled by Apache Reverse Proxy. Even, writing the header in the code to and forcing the function to return one value always, I'm still getting 401 when fetching the instances, but it works ok when loading StudyList and initial metadata.

`cornerstoneWADOImageLoader.configure({ 
   beforeSend: function(xhr) { 
     const headers = OHIF.DICOMWeb.getAuthorizationHeader(); 
  
     /* if (headers.Authorization) { 
       xhr.setRequestHeader('Authorization', headers.Authorization); 
     }*/
    xhr.setRequestHeader('Authorization', 'Basic XXXXXyyyyXXX'); 
   }, 
   errorInterceptor: error => { 
     // const { appConfig = {} } = AppContext; 
  
     if (typeof appConfig.httpErrorHandler === 'function') { 
       appConfig.httpErrorHandler(error); 
     } 
   }, 
 }); `

Hope we can find someway to fix this.

P.S.: just to let you know, in this pandemic, OHIF Viewer is helping so much in our hospital enviroment. Thank you very much for contributing this great project.

**Comment by Diex** [comment]
OHIF is a great tool. We are really happy with and really willing to collaborate. 

@epileftico : what we did was to add Authorization headers in the proxy:

OHIF Client -> back proxy (add Auth) -> googlehealthcare 
and yes, it works ok on listing our dicom store but now it fails in showing the images with no error.
so I'm thinking some chage was introduced recently... I'm investigating this so we could have a proper reproduction.
I assume it's probably two different issues.

**Comment by christianvargasforero** [comment]
@dannyrb @Diex @epileftico 

Solve the problem partially by storing the Bearer type token in a session variable, it must be passed to the cornertoneWADOImageLoader method, 

```
cornerstoneWADOImageLoader_min_default.a.configure({
      if (headers.Authorization) {
        xhr.setRequestHeader('Authorization', headers.Authorization);
      }
      else{
        xhr.setRequestHeader('Authorization', "Bearer ".concat(window.sessionStorage.getItem("auth_ghc")));
      }
    },
  });
```


I see that the getAuthorizationHeader method when it sets the value of headers.Authorization remains empty, if I change the value to requestOptions.auth it works but when it is check again in cornerstoneWADOImageLoader the header is still empty.

```
function getAuthorizationHeader() {
if (typeof requestOptions.auth === 'function') {
// Custom Auth Header
headers.Authorization = requestOptions.auth(requestOptions.auth);
}
```

**Comment by natanaelsimoes** [comment]
https://github.com/OHIF/Viewers/blob/709f14708e2b0f912b5ea509114acd87af3149cb/platform/viewer/src/config.js#L45-L60

At line 47 I've managed to workaround this issue by passing to `getAuthorizationHeader` my dicomWeb configuration as follows:
```js
const headers = OHIF.DICOMWeb.getAuthorizationHeader(appConfig.servers.dicomWeb[0]);
```

**Comment by morpheus302** [comment]
> https://github.com/OHIF/Viewers/blob/709f14708e2b0f912b5ea509114acd87af3149cb/platform/viewer/src/config.js#L45-L60
> 
> At line 47 I've managed to workaround this issue by passing to `getAuthorizationHeader` my dicomWeb configuration as follows:
> 
> ```js
> const headers = OHIF.DICOMWeb.getAuthorizationHeader(appConfig.servers.dicomWeb[0]);
> ```

I deployed OHIF on un Unraid Server in a docker container and i'm facing the same authentication error. Can you tell me please which file to edit in the docker container? thanks

**Comment by ausmurp** [comment]
If you change the config to be a function instead of an object, this works as is. 
```
window.config = () => ({
  // default: '/'
  routerBasename: '/',
  extensions: [],
  showStudyList: true,
  filterQueryParam: false,
  servers: {
    dicomWeb: [
      {
        name: 'scorthanc',
        wadoUriRoot: 'https://orthanc.yyy.zzz/orthanc/wado',
        qidoRoot: 'https://orthanc.yyy.zzz/orthanc/dicom-web',
        wadoRoot: 'https://orthanc.yyy.zzz/orthanc/dicom-web',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        requestOptions: {
          auth: 'user:password',
        },
      },
    ],
  },
  cornerstoneExtensionConfig: {},
  // Following property limits number of simultaneous series metadata requests.
  // For http/1.x-only servers, set this to 5 or less to improve
  //  on first meaningful display in viewer
  // If the server is particularly slow to respond to series metadata
  //  requests as it extracts the metadata from raw files everytime,
  //  try setting this to even lower value
  // Leave it undefined for no limit, sutiable for HTTP/2 enabled servers
  // maxConcurrentMetadataRequests: 5,
});
```

**Comment by Ali-2210** [comment]
salam , in config.js try change this code :
   `beforeSend: function(xhr) { `
       `const headers = OHIF.DICOMWeb.getAuthorizationHeader(); `
       `if (headers.Authorization) { `
        ` xhr.setRequestHeader('Authorization', headers.Authorization); `
      ` } `
     `},`
to this :
`beforeSend: function (xhr) { `
 `      debugger `
 `      const state = window.store.getState(); `
  `      const activeServer = state.servers.servers.find(t => t.active); `
  `     const headers = OHIF.DICOMWeb.getAuthorizationHeader(activeServer); `
  `     debugger `
  `     if (headers.Authorization) { `
  `       xhr.setRequestHeader('Authorization', headers.Authorization); `
  `     } `
  `   },`

**Comment by edcheyjr** [comment]
> https://github.com/OHIF/Viewers/blob/709f14708e2b0f912b5ea509114acd87af3149cb/platform/viewer/src/config.js#L45-L60
> 
> At line 47 I've managed to workaround this issue by passing to `getAuthorizationHeader` my dicomWeb configuration as follows:
> 
> ```js
> const headers = OHIF.DICOMWeb.getAuthorizationHeader(appConfig.servers.dicomWeb[0]);
> ```

Hey, could someone help me and show how this could be achieved since I am trying to connect with Orthanc which as a Basic authentication set it seems that config.js is not in v3-stable.
