### ISSUE TITLE
Multiframe images where the Frame Increment Pointer points to Page Number Vector are currently unsupported.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#174]
Hey all,

Whilst looking at some combined CT/PET scans I noticed some scanners produce multi-frame images which are currently unsupported.

MetadataProvider can currently only parse multi-frame DICOMs where the Frame Increment Pointer (FIP) (0028,0009) points to either Frame Time (0018,1063) or Frame Time Vector (0018,1065). Scans where the FIP points to Page Number Vector (0018,2001) are currently unsupported and will cause the loading sequence to hang on line 149 of MetadataProvider.js.

Is this issue known and is further support for other vectors on the horizon? I've only encountered the Page Number Vector, but in principal a scanner could use any of these Vectors: https://dicom.innolitics.com/ciods/multi-frame-single-bit-sc-image/sc-multi-frame-vector.

Thanks a lot,
JamesAPetts

**Comment by dannyrb** [comment]
@JamesAPetts is this still impacting you, or can this be closed?

**Comment by JamesAPetts** [comment]
Hey, I only ever saw this on one image, which at the time I hacked in a change to our local version. These problems still exist, but the lack of others complaining about it make me believe its currently low priority. It may not be in the future, however, if more scanners start using other vectors more frequently.
