### ISSUE TITLE
[@ohif/core v2.9.6] import { studies } from '@ohif/core',doesn't work

### ISSUE THREAD

**Issue by h2zzhou** [OHIF/Viewers#1740]
1、npm -i @ohif/core --save

2、
Example: retrieving study metadata from a server

```
import { studies } from '@ohif/core';
 
const studiesMetadata = await studies.retrieveStudiesMetadata(
  server, // Object
  studyInstanceUIDs, // Array
  seriesInstanceUIDs // Array (optional)
);
```
`import { studies } from '@ohif/core'; `doesn't work

And，@ohif/core　sourcemap file(index.umd.js.map) is not correct.

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
