### ISSUE TITLE
Ohif Viewer and Google Healthcare with fixed project/dicom store and service account?

### ISSUE THREAD

**Issue by marcoscarrilho** [OHIF/Viewers#1741]
Hi 
Is possible use the OHIF viewer for acess a specific and fixed project and dicom store in Google Healthcare? 
And i need use a google service account for authentication too.

Is possible?
Thank's for any help

**Comment by pieper** [comment]
Not sure exactly what you need here, but OHIF works well with Google dicom stores.  You manage access like you would other google resources.  Typically for OHIF you log in as a user not a service account.  Only the dicomweb part is authenticated, not the OHIF app itself.

**Comment by marcoscarrilho** [comment]
> Not sure exactly what you need here, but OHIF works well with Google dicom stores. You manage access like you would other google resources. Typically for OHIF you log in as a user not a service account. Only the dicomweb part is authenticated, not the OHIF app itself.

Hi peiper,
Thanks for your repply.

I would like use the OHIF Embedded Viewer with a Google Healthcare API as the same way i use with DCM4CHE, without choose DICOM STORE and without authentication via user/browser.
I don't if its possible

Many thanks

**Comment by pieper** [comment]
I'm not sure about embedded, but should be able to just point to your dicom store like this:

https://static-website-host.ex/projects/GCP_PROJECT/locations/LOCATION/datasets/DATASET/dicomStores/DICOM_STORE

Here's what we do for one of our projects:

https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us-central1/datasets/lidc-idri-seg-sr-dcm/dicomStores/lidc-idri-seg-sr-dcm

**Comment by kswedberg** [comment]
> Not sure exactly what you need here, but OHIF works well with Google dicom stores. You manage access like you would other google resources. Typically for OHIF you log in as a user not a service account. Only the dicomweb part is authenticated, not the OHIF app itself.

Is there a way to use service account authentication rather than user login? If so, would you mind pointing me in the right direction? The project I'm working on requires service acct auth, and I'm just not seeing how to get it working with the ohif viewer

**Comment by sjmn** [comment]
@kswedberg did you find a solution for using a service account for OHIF authentication to Google Healthcare API? We are confronted with the same roadblock.

**Comment by marcoscarrilho** [comment]
> @kswedberg did you find a solution for using a service account for OHIF authentication to Google Healthcare API? We are confronted with the same roadblock.

Sorry @sjmn 

We frozen the project because in our vision is necessary change the source code.
Well, it's our conclusion about using the viewer without authentication or with a service account.
If you find some workaround, please let me know.
Thanks

**Comment by kswedberg** [comment]
> @kswedberg did you find a solution for using a service account for OHIF authentication to Google Healthcare API? We are confronted with the same roadblock.

I might have, but it's been a while since I've worked on that codebase. I'll try to take a look this weekend and let you know what I find.

**Comment by xtfer** [comment]
@kswedberg Wondering if you made any progress on this?

**Comment by kswedberg** [comment]
@sanjay3290 sorry, it has been a very long time since I've looked at this. I don't think I ever got it to work, unfortunately.
