### ISSUE TITLE
@ohif/core  v2.9.6   Syntax Error: "imageId" is read-only

### ISSUE THREAD

**Issue by h2zzhou** [OHIF/Viewers#1742]
/src/core/src/utils/dicomLoaderService.js
  114 | const imageId = getImageInstanceId(imageInstance);
   ...
  145 |         case 'wadouri':
  146 |           // Strip out the image loader specifier
> 147 |           imageId = imageId.substring(imageId.indexOf(':') + 1);
      |           ^
  148 | 
  149 |           if (someInvalidStrings(imageId)) {
  150 |             return;

Syntax Error: "imageId" is read-only

imageId  is constant.

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
