### ISSUE TITLE
How to implement hanging-protocol

### ISSUE THREAD

**Issue by trung1704ptit** [OHIF/Viewers#1743]
Hi everyone,

How can I implement hanging protocol?  I saw the hanging-protocol folder in cornerstone/core, but I cannot find the way to implement this to our mammo view.

Anyone know about this, pleas help us.

**Comment by trung1704ptit** [comment]
@dannyrb Can you for me some guideline?

**Comment by sedghi** [comment]
We have this dedicated section for hanging protocols https://docs.ohif.org/platform/extensions/modules/hpModule
