### ISSUE TITLE
3D VR available in OHIF viewer?

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1745]
I happened to come across this video which shows 3D VR being done in OHIF viewer. How can this be accessed in OHIF?

https://www.youtube.com/watch?v=NXXtb670hwk

**Comment by pieper** [comment]
It can be done, but it's still a work in progress.  So far the image reslicing is integrated but volume rendering is not exposed.

You can learn more here:

https://discourse.vtk.org/t/new-free-video-tutorials-vtk-js-and-ohif-web-apps/2164

Code contributions welcome!

**Comment by ranasrule** [comment]
> 
> 
> It can be done, but it's still a work in progress. So far the image reslicing is integrated but volume rendering is not exposed.
> 
> You can learn more here:
> 
> https://discourse.vtk.org/t/new-free-video-tutorials-vtk-js-and-ohif-web-apps/2164
> 
> Code contributions welcome!

is there an experimental build available like the one from the YouTube video that I could play around with and see if I could contribute to?

**Comment by pieper** [comment]
It's probably somewhere in an old pull request or something, but you'd be better off just to look at the [vtk extension](https://github.com/OHIF/Viewers/tree/master/extensions/vtk/src) in the current master which actually uses volume rendering but with different transfer functions.  It should be pretty much just a matter of putting in some of the code from the vtkjs demos.  Let us know how it goes for you.

**Comment by ranasrule** [comment]
> 
> 
> It's probably somewhere in an old pull request or something, but you'd be better off just to look at the [vtk extension](https://github.com/OHIF/Viewers/tree/master/extensions/vtk/src) in the current master which actually uses volume rendering but with different transfer functions. It should be pretty much just a matter of putting in some of the code from the vtkjs demos. Let us know how it goes for you.

I wish my JS skills were advanced enough to be of help but unfortunately I'm not sure they are. If you come across the build from the Youtube video I would be grateful if you could share it with me.
