### ISSUE TITLE
IDC Dev tool for posting data elsewhere

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1746]
Requirements:
- Create a dev (console only) function which will upload the current study to a different server.
- The function should be added as a command to the `dicom-p10-downloader` extension.

Technical details:
- The dev command should take config which contains the server + authorization to post to, you can see how this is done whenever a `dicomweb-client` instances is created.
  - Look how `dicomweb-client` is currently set up when STOWing SRs: https://github.com/OHIF/Viewers/blob/4293c073f04f8cdeceac940ab4f6a5f8f51fdbee/platform/core/src/DICOMSR/handleStructuredReport.js#L84
  - Inside the dev tool, perform the download study function (at least until you get all the instances), then push all the instances using `storeInstances` as shown in the above SR example.

**Comment by pieper** [comment]
Would be good to add/unify the upload with the features exposed here:

https://github.com/pieper/Viewers/blob/master/platform/viewer/src/App.js#L74

Would be fine to change the name from window.app to window.ohif to avoid possible namespace clash.  Also please add some documentation on a wiki or somewhere with example commands for downloading data and uploading to a new dicom store.  The overall goal is to have these utilities to facilitate debugging and data management.

**Comment by pieper** [comment]
As discussed with @fedorov this will be helpful for debugging public data with OHIF devs who don't have access to IDC dicom stores.

**Comment by JamesAPetts** [comment]
P.S. I vote to renam the `dicom-p10-downloader` extension to the `debug` extension, as that's what its molding into, and it makes it clearer for other consumers that might want to disable (easy) downloading/pushing of the data.
