### ISSUE TITLE
Not actually an issue.

### ISSUE THREAD

**Issue by surfer-admin** [OHIF/Viewers#175]
Just want to report this: I tried to install OHIFViewer following Step by Step installation in Ubuntu 16.04. When git clone Viewers under /opt/Viewers as instructed was performed, a new Viewers subdirectory was created under /opt/Viewers. So I had /opt/Viewers/Viewers/OHIFViewer/. No meteor build can be made.

**Comment by swederik** [comment]
Thanks! I've updated the Wiki page.
