### ISSUE TITLE
Volume Rendering

### ISSUE THREAD

**Issue by qmiwang** [OHIF/Viewers#1752]
Dose the VTK extension support Volume Rendering?

Is there some example to show how to implement the Volume Rendering ?

Many Thanks!!!

**Comment by dannyrb** [comment]
It has all of the data available it needs to render a volume, and at least at one point could through one of its components (exposed via react-vtks-viewport). I'm not sure it's still in working condition, but it shouldn't require much work to get it stood up.

The bulk of our funding/funders have us improving the vtk.js 2D viewport; seg visualization, annotation tools, etc.

If you're interested in 3D, I recommend contributing to react-vtkjs-viewport and authoring a custom extension (or improving the vtkjs extension) to expose it via the OHIF extension's viewports module.

**Comment by JamesAPetts** [comment]
> and at least at one point could through one of its components (exposed via react-vtks-viewport). I'm not sure it's still in working condition, but it shouldn't require much work to get it stood up.

Its functional in `react-vtkjs-viewport`, but we've never yet put it in OHIF. Its a seperate viewport component.

> authoring a custom extension (or improving the vtkjs extension) to expose it via the OHIF extension's viewports module.
Yeah I believe this would be an additional viewport in the vtkjs viewport, with additional commands to use that viewport instead (or as well as) the MPR2D.

Not sure if we have support for multiple viewports in a single extension currently?
