### ISSUE TITLE
reference lines / extensions in embedded ohif or as react component

### ISSUE THREAD

**Issue by najimhashgraph** [OHIF/Viewers#1754]
Dear developers,

First I want to thank you @dannyrb for your help and advise for using the OHIF viewer as  react component.
I want to use the react app I am building in a medical study and I have one issue left: the radiologists need also reference lines to make a good assessment.
I looked into the documentation and previous issues on github but I find it quit confusing how to implement this as a extension.
I saw that the vtk extension might provide this but there also some issues with it, and also i find it confusing how to implement a extension using ohif viewer as a react component.
I hope you can advise me in this matter. This would be great for the study otherwise it will create big limitations.

Thank you in advance.

Kind regards,
Najim

**Comment by dannyrb** [comment]
@najimhashgraph , there is an open PR that may resolve your issue:

https://github.com/OHIF/Viewers/pull/1482
