### ISSUE TITLE
How do I update the url of an embedded viewer from the web app where is embedded?

### ISSUE THREAD

**Issue by epetxepe** [OHIF/Viewers#1755]
**Goal**

Our goal is to embed the viewer in a web app and to control what is shown in the embedded viewer from the web app where is embbeded. In the web app, we've a timeline where the user can click different studies and we would like to update the url of the embedded viewer to open the study selected by the user.

**Steps & alternatives tested**

We have embedded the viewer following instructions at https://docs.ohif.org/deployment/recipes/embedded-viewer.html . More specifically _Installing OHIF viewer inside another react app_ described at the end of the page.

In order to load a specific DICOM study we've tested solution described in https://github.com/OHIF/Viewers/issues/1400#issuecomment-582529706 proposed by @EduardoSantanaSeverino . This works for initially specifying the StudyID, but not to dinamically update the Study ID from the general web app. Additionally we have an issue loaded medical image frame growing infinitely.

_Alternative 1: Use installViewer and use OHIF viewer builtin react-router to update components url_

We've seen that _App.js_ uses react-router-dom and that _OHIFStandaloneViewer.js_ exports 
```
export default ViewerbaseDragDropContext(
  withRouter(ConnectedOHIFStandaloneViewer)
);
```
so we have tried running => this.props.router.push('/'); to update the url, but with no luck for the moment.

_Alternative 2: Updating Redux states_

We have thought of updating the StudyID or url through some Redux command, but we've not been able to identitfy the correct way to do this.

_Alternative 3: Trying to use OHIF viewers subcomponent leading with routes in our Web app_

Looking at the code OHIF viewer code, we've have identified that routesUtil.js & ViewerRouting.js. We have even tried to use ViewerRouting & ConnectedViewerRetrieveStudyData components instead of _installViewer_ from (https://docs.ohif.org/deployment/recipes/embedded-viewer.html) to embed the viewer, but we got no success (we believe it needs more viewer components & initialisation steps).

**Questions**

- Which approach is the correct one to get the url update? We believe it should be the Alternative 1, but we're having some error stopping us. Could you confirm? Maybe point to a an example?

**Comment by dannyrb** [comment]
I recall seeing an interesting implementation for an extension that enabled PubSub between the iFrame'd OHIF and its parent application -- added via an OHIF extension.

There is also a few large changes coming down the pipe that:

- Add hashrouting via a build time var
- Expose services for programmatic control over most of the viewer's state
- Enable much more customized templates if you wanted to include the timeline as a part of the viewer

**Comment by epetxepe** [comment]
Thanks for the feedback @dannyrb 
  
   We prefer not to use iFrames as we're seeking for devs that will require integration with OHIF.

   Could you add a reference of an issue / url to follow up the large changes?

   We're integrating OHIF into an existing Angular development (i.e. our timeline is on Angular) so I believe customized templates won't fit for us.

   Meanwhile (i.e. while hashrouting or router is exposed somehow), we've been able to update url by adding a ref to the Router component. 

  ```
 this.routerRef = React.createRef();
   
  this.routerRef.current.history.push(
    //   '/viewer/1.2.826.0.13854362241694438965858641723883466450351448'
    // );
  }

 <Router ref={this.routerRef} basename={routerBasename}>

```
   
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8027532/83271189-c8591080-a1c9-11ea-8403-a5971940452a.gif)

Now we will proceed to integrate single viewer interaction from our Angular application.

Next steps are to play around with ViewRouting and ConnectedViewers (and posted issues) to select series instead of studies and show multiple series from different studies. 

Regards,

Gorka
