### ISSUE TITLE
default transfer syntax requested by OHIF viewer?

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1756]
Greetings,
                When OHIF viewer is connected to a PACS like Orthanc what is the default transfer syntax in which OHIF viewer requests images/instances? Is there any way to change is to a syntax like jpeg2000(1.2.840.10008.1.2.4.90) ?

**Comment by ranasrule** [comment]
anyone?

**Comment by dannyrb** [comment]
You can inspect the requests in Chrome's console in the network tab. I don't believe a specific transfer syntax is specified. That likely means what is retrieved is the acquisition format.

I believe you can use cornerstone-wado-image-loaders beforeSend hook to target a specific transfer syntax for all requests.
