### ISSUE TITLE
where can I change the encode ?

### ISSUE THREAD

**Issue by kongzhonglei** [OHIF/Viewers#1758]
i have a question,where can i change the  encode? i use chinese.thank you 
![1590696331(1)](https://user-images.githubusercontent.com/26484022/83188613-91034900-a162-11ea-8a08-80296c040777.png)
![1590696719(1)](https://user-images.githubusercontent.com/26484022/83188679-a6787300-a162-11ea-9484-2c8f185f3b82.png)

**Comment by dannyrb** [comment]
If you mean the internationalization (i18n), we have a crowdsourced locize project (although it is missing some phrases), that we try to regularly pull updates from.

Outside of that, I believe you can manually edit/add to the files in the platform/i18n project.

**Comment by qaler** [comment]
Well, what he implied was that the chinese characters in dicom tags (e.g. patient name) did not display properly due to incorrect text encoding/decoding. Has this issue ever got resolved yet?

**Comment by felixlinxk** [comment]
The Chinese characters are mostly encoded by GB18030 or GBK

**Comment by bonviesinfo** [comment]
@felixlinxk could you help  show how to solve the problem ?
