### ISSUE TITLE
Page is not available after yarn run dev

### ISSUE THREAD

**Issue by Andrew32bit** [OHIF/Viewers#1759]
I have this following error - 
<img width="1536" alt="Снимок экрана 2020-05-28 в 23 27 15" src="https://user-images.githubusercontent.com/28597674/83190303-e297dd80-a13a-11ea-922f-4142f9cfd5f6.png">
What can i do ?

**Comment by dannyrb** [comment]
That is just a warning that the file won't be cached by the service worker. You should still be able to access the webpack dev server.

**Comment by Andrew32bit** [comment]
Well its not available on port 3000 -page not found

**Comment by dannyrb** [comment]
I am unable to reproduce. Are you able to provide clarification around the steps required to bring about this bug?

**Comment by Andrew32bit** [comment]
I did this pipeline step by step https://docs.ohif.org/development/getting-started.html

**Comment by dannyrb** [comment]
Unfortunately, following those steps, I am unable to reproduce the issue.
