### ISSUE TITLE
Rad Read Plug-in 

### ISSUE THREAD

**Issue by willi3by** [OHIF/Viewers#1760]
## Request

**What feature or change would you like to see made?**

I would like to see a feature in the viewer to be able to fill out radiological reports while viewing images. It’s hard for me to think that this doesn’t already exist somewhere so I apologize if I am completely missing it. I am envisioning a drop down menu in the toolbar that contains multiple reports for a specific study. When a radiologist selects a report to fill out, it pops up on the right side of the screen so they are able to view images and fill out the report in the same window. 

**Why should we prioritize this feature?**

This feature is relevant to nearly all clinical imaging studies. It integrates two important components of all clinical imaging research: 1) viewing the images and 2) acquiring all radiological data points. The great OHIF viewer combined with this feature and something like XNAT for study management seems like the perfect system for clinical imaging research. 

Thank you for your time

**Comment by dannyrb** [comment]
@willi3by , I believe XNAT has a web based fork of the OHIF Viewer. Rumor has it they're wrapping a migration to the latest React version.

There is no existing extension that offers the functionality you're describing; however, the OHIF Viewer is built to support the addition of custom functionality like this through extensions. We also provide themed form components so whatever you build can achieve a consistent look and feel with the rest of the viewer.

**Comment by willi3by** [comment]
@dannyrb Interesting, thanks for the info! 

I am definitely interested in developing such an extension for our studies though not much of my programming experience is web-based. Are there any templates or documentation to achieve this type of plugin, other than the extensions page on the main site? 

Thanks again for your help

**Comment by ranasrule** [comment]
> 
> 
> @dannyrb Interesting, thanks for the info!
> 
> I am definitely interested in developing such an extension for our studies though not much of my programming experience is web-based. Are there any templates or documentation to achieve this type of plugin, other than the extensions page on the main site?
> 
> Thanks again for your help

Can u send me your email address? I might have something for you

**Comment by ranasrule** [comment]
> 
> ## Request
> 
> **What feature or change would you like to see made?**
> 
> I would like to see a feature in the viewer to be able to fill out radiological reports while viewing images. It’s hard for me to think that this doesn’t already exist somewhere so I apologize if I am completely missing it. I am envisioning a drop down menu in the toolbar that contains multiple reports for a specific study. When a radiologist selects a report to fill out, it pops up on the right side of the screen so they are able to view images and fill out the report in the same window.
> 
> **Why should we prioritize this feature?**
> 
> This feature is relevant to nearly all clinical imaging studies. It integrates two important components of all clinical imaging research: 1) viewing the images and 2) acquiring all radiological data points. The great OHIF viewer combined with this feature and something like XNAT for study management seems like the perfect system for clinical imaging research.
> 
> Thank you for your time

Can u send me your email address? I might have something for you
