### ISSUE TITLE
Example of using the OHIF Viewer to view a DICOM file

### ISSUE THREAD

**Issue by GleisonAndrade** [OHIF/Viewers#1769]
Hello, I have questions about the documentation, I did a quick reading and I didn't understand very well how OHIF Viewer works with a script tag.

In the basic configuration, I haven't found a location explaining how each parameter works.

```
window.config = {
  routerBasename: '/',
  servers: {
    dicomWeb: [
      {
        name: 'DCM4CHEE',
        qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
      },
    ],
  },
};
```
I would like to know what each one is for to understand how it works. I may not have paid attention, but how do I manage to view a DICOM image? From a directory with a file or a url.

![Captura de tela de 2020-06-04 10-41-00](https://user-images.githubusercontent.com/9152452/83764442-53b22600-a650-11ea-86f8-a75f6666aac3.png)

My goal is to use the viewer on any html page with javascript. Without a code it is difficult to help me, but I just need information to help me understand how it works and set it up correctly.

The following links did not clarify my doubts:

https://codesandbox.io/s/viewer-script-tag-tprch
https://docs.ohif.org/deployment/recipes/embedded-viewer.html
https://docs.ohif.org/configuring/

Thank you in advance.

Kind regards,
Gleison Andrade

**Comment by PoyangLiu** [comment]
Not sure if this help you.  But there is a local file mode.
In your https://codesandbox.io/s/viewer-script-tag-tprch example, Try adding `local` at the end of your url.
i.e. https://tprch.csb.app/local
You'll be prompted to select a file or directory.

**Comment by mathiasfink** [comment]
Does anybody have an idea why /local doesn't work in my setup?

**Comment by eric-taix** [comment]
@mathiasfink you should probably create a new issue AND explain what is your local setup? Otherwise sorry but it's impossible to help you...

**Comment by sedghi** [comment]
You can use /local or /localbasic on our demos

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
