### ISSUE TITLE
upload study button is broken

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#1770]
## Bug Report

When I click the + button next to the number of studies it should bring up an upload dialog box (used to work, it was contributed by the google consulting team).

### Describe the Bug
![image](https://user-images.githubusercontent.com/126077/83765456-2f9f1680-a649-11ea-8019-1cf5f22b6371.png)

Looks like images are broken and frame is behind the study list.

### What steps can we follow to reproduce the bug?

Choose a dicomweb server and then click the + button.

No messages in the console.

**Comment by NoorUnnisa** [comment]
same issue is replicating to me , and its going on making the root element's style as `display:none` 
![image](https://user-images.githubusercontent.com/17563636/84135562-c4e64480-aa67-11ea-91e8-80d51fd9028e.png)

**Comment by swederik** [comment]
Pretty sure this was fixed in #1904
