### ISSUE TITLE
Segmentations do not load when study opened for the second time

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1776]
### Describe the Bug

When the same study containing SEG/SR series is opened for the second time, segmentations do not show up in the drop-down. After "Empty cache and hard reload", everything loads as normal.

### What steps can we follow to reproduce the bug?

Here is the screencast demonstrating the issue: https://www.screencast.com/t/GB9CHIqbASl

Here's the specific study which I used for testing: https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us/datasets/tcia-etl-test/dicomStores/lidc/study/1.3.6.1.4.1.14519.5.2.1.6279.6001.899353684702041035700102438716

**Comment by JamesAPetts** [comment]
Can reproduce this on any Study with a SEG.

Can use this one, for example @rodrigolabs odrigo:
https://viewer-dev.ohif.org/viewer/1.3.6.1.4.1.14519.5.2.1.7311.5101.288989437471167339179420862837

- Open the Segmentations panel and click the dropdown to see the segmentation list.
- Navigate to the study list and back to the same study.
- The segmentation list is now blank (although the active segmentation displays).

**Comment by KhyatiMehta3** [comment]
@fedorov could you please tell me how you were able to add the segmentation extension? 
What is the procedure to add it? I've been trying to add the same extension for a while without any progress

**Comment by JamesAPetts** [comment]
@KhyatiMehta3 
It's actually on by default currently. The segmentation panel will show up if there is a DICOM SEG in the study. The segmentation functionality is read only for now.

This is only well tested if using a DICOMWeb server or google cloud as your backend.

**Comment by KhyatiMehta3** [comment]
@JamesAPetts Thank you so much for your response! 
I'm slightly new to this, could you please tell me what you mean by DICOM SEG? 
I followed the setup process as per the [documentation](https://docs.ohif.org/configuring/data-source.html), with Orthanc as the back end, and I'm just trying to find a way to add segmentation to the dicom and save that. 
If you wouldn't mind, could you please tell me the steps to do that?

**Comment by JamesAPetts** [comment]
By DICOM SEG I mean [DICOM Segmentation objects](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.20.html). Its a DICOM file format that holds segmentations. We currently only have read/display capability as shown here. If you have a study that has a scan and a segmentation in it, such as [this example](https://viewer-dev.ohif.org/viewer/1.3.6.1.4.1.14519.5.2.1.7311.5101.170561193612723093192571245493), the segmentation panel will appear automatically, and the segmentation will automatically be overlayed on the image.

> add segmentation to the dicom and save that.

Although all the building blocks exist to potentially edit and save segmentations. The segmentation extension does not yet do this. There are no painting/edit tools or save functionality in the extension at this time.

**Comment by KhyatiMehta3** [comment]
Okay, there's a segmentation extension that has tools namely brush, correction scissors & spherical. 
What tools are they? And How can the segmentation marked from that be saved into the DICOM?
![issue_3](https://user-images.githubusercontent.com/25249564/88521787-0ed4bb00-d013-11ea-881a-1f4bea0021c1.png)

**Comment by JamesAPetts** [comment]
It appears you are currently using a fork of OHIF, or have a screenshot of an OHIF fork. These are tools from cornerstone-tools. However these are not yet supported as core functionality OHIF in any official capacity.

**Comment by KhyatiMehta3** [comment]
Is it possible for you to guide me to add appropriate functionality? I could send a PR when I achieve it. 
I just want the segmentation marked from these tools to get loaded on to the DICOM.
