### ISSUE TITLE
How to proxy to local Orthanc

### ISSUE THREAD

**Issue by SamJBentley** [OHIF/Viewers#1777]
I've got a custom Orthanc Docker image that I am using. It's running on localhost:8042. How do I get standalone OHIC to proxy to it? I've followed the instructions in the Configuring documentation section, but I'm getting Cross Origin errors from Orthanc, which suggests that the proxy is not working.

My config is:
```
     {
        name: 'Orthanc',
        wadoUriRoot: 'http://localhost:8042/wado',
        qidoRoot: 'http://localhost:8042/dicom-web',
        wadoRoot: 'http://localhost:8042/dicom-web',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
      }
```

And I'm running via `yarn start`

Thanks

**Comment by buptxiaofeng** [comment]
you need a web server, such as nginx, and config the proxy policies of nginx

**Comment by sedghi** [comment]
Look at this recipe 

https://docs.ohif.org/deployment/nginx--image-archive
