### ISSUE TITLE
Zoom issue

### ISSUE THREAD

**Issue by Angelodaniel** [OHIF/Viewers#1779]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

Hi, 

First of all awesome functionality ! :)
I used the easy way by just using a script where it will be integrated with the use of the window and some scripts. 

But my question is, 
If i let the  window.OHIFViewer.installViewer do its work I arrive at the list of examples.
But when i click the example, the canvas keeps expanding. Is that common with the easy way intergration?

**Comment by mortezaa** [comment]
did you fix problem? 

I have the same issue here!
