### ISSUE TITLE
if i want to add myself package to OHIFViewer,what is necessary

### ISSUE THREAD

**Issue by tiancantudousi** [OHIF/Viewers#178]
①I create myself package like this  meteor create --package test:selfpackage.
②And then I wrote a template leftlist in the selfpackage.
③add selfpackage  to OHIFViewer by command meteor add test:selfpackage.(But it doesn't seem to work)
and When I used this template leftlist, I got it wrong.
![image](https://user-images.githubusercontent.com/30852480/38719504-f4aff4c8-3f24-11e8-8fee-101a391cae39.png)
![image](https://user-images.githubusercontent.com/30852480/38719527-0d48c8c0-3f25-11e8-8560-15678fed7b47.png)

I really appreciate your advice.

**Comment by dannyrb** [comment]
We are moving away from support for version 1 of the Viewer. The goal is to make Version 2 extensible and configurable enough that you can customize it for your workflow and purposes.

This issue hasn't seen activity in some time, so I'm going to close it. I'm sorry we weren't more help here, but please don't let that stop you from creating future issues ^_^

**Comment by tiancantudousi** [comment]
use meteor create --package name    
 
---Original---
