### ISSUE TITLE
Study does not render - NSCLC-Radiomics / LUNG1-001

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1782]
### Describe the Bug

When I open a non-empty study, nothing shows up in the left panel, while there are no errors in the console.

https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc-tcia/dicomStores/idc-tcia/study/1.3.6.1.4.1.40744.29.239341353911714368772597187099978969331

![image](https://user-images.githubusercontent.com/313942/84404253-98037000-abd4-11ea-9a94-1acaad477baa.png)

If I click on "Segmentations", I get a cryptic error message:

![image](https://user-images.githubusercontent.com/313942/84404313-a94c7c80-abd4-11ea-9f9e-2bf7d37fe222.png)

![image](https://user-images.githubusercontent.com/313942/84404354-b6696b80-abd4-11ea-9521-7f4f224c2dd7.png)

### What steps can we follow to reproduce the bug?

open https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc-tcia/dicomStores/idc-tcia/study/1.3.6.1.4.1.40744.29.239341353911714368772597187099978969331 and do the steps described above.

**Comment by pieper** [comment]
I don't have access to the idc-dev-etl project - is that one that you are able to share?

**Comment by pieper** [comment]
Also do you know anything about the study?  Does it load in Slicer?

**Comment by fedorov** [comment]
The study should be good - it is from Hugo, Dennis already used the version hosted by google in his use case, SEGs were generated with dcmqi. But I did not download the study or investigate in detail.

I asked Bill to add you to that project.

**Comment by fedorov** [comment]
If I click 'd', I get the following in the console:

![image](https://user-images.githubusercontent.com/313942/84412442-401d3700-abdd-11ea-861a-0441ba471288.png)

@pieper what is again the command i need to type in the console to download a study? I am again having troubles finding the ticket or PR where this was mentioned. Can we add this to the documentation somewhere?

**Comment by fedorov** [comment]
Found the instructions 

ohif.app.commandsManager.runCommand("downloadAndZip", {listOfUIDs: [window.location.href.split("/").pop()]})

**Comment by fedorov** [comment]
So the underlying problem seems to be that the study does not contain the image series. Will investigate that. I think it would be helpful to have a user-readable message about this.

**Comment by fedorov** [comment]
It appears that TCIA assigned SEG and RTSTRUCT to a study different from where CT is.

I submitted the issue below to the TCIA helpdesk.

---
there is an issue with at least some of the UIDs for the
NSCLC-Radiomics collection.

Subject LUNG1-001 has 3 series: CT, RTSTRUCT and SEG.

For whatever reason, CT is assigned to a different study than RTSTRUCT
and SEG, but the suffix of the StudyInstanceUID is the same:

CT is in study 1.3.6.1.4.1.32722.99.99.239341353911714368772597187099978969331

RTSTRUCT and SEG are in
1.3.6.1.4.1.40744.29.239341353911714368772597187099978969331.

This is not just an inconvenience and bad practice, but also it
appears that the StudyInstanceUID is inconsistent from how series were
organized for this collection in the past.

I checked the previous version of the collection, which is still
available from the Google copy, and in that collection RTSTRUCT is in
the same study as the CT image.

Can you explain what is happening? Is it intentional that
StudyInstanceUID was changed, and RTSTRUCT and SEG are assigned to a
study different from the CT series?

For your convenience, here's a zip file for LUNG1-001, both the
current and previous version:
https://app.box.com/s/3v73ot5pq7kza140yoi10qhqia4j7pqt

**Comment by fedorov** [comment]
@pieper we now have OHIF 4.2.3 in the IDC webapp, but the command to download the study is not working:

![image](https://user-images.githubusercontent.com/313942/84515240-3279b700-ac9a-11ea-9430-7de2f973a9a4.png)

Should something be done by @G-White-ISB to enable it?

**Comment by pieper** [comment]
I don't think there's any configuration required - @dannyrb ?

Does the webapp's ohif include this commit https://github.com/OHIF/Viewers/commit/63fd65690cba450721870a6222e0fb3ad71bb291

**Comment by pieper** [comment]
Actually it looks like the `ohif.app.commandsManager` object is there, but it's not finding the command, so there must be something else going on, but I'm not sure about that `context` stuff.

**Comment by JamesAPetts** [comment]
> So the underlying problem seems to be that the study does not contain the image series. Will investigate that. I think it would be helpful to have a user-readable message about this.

Yeah this looks like the issue. We should have a notification pop up and a clean failure in the side panel when no source data is present.

@rodrigolabs you can test this locally by adding just a SEG from TCIA to a study in a local PACs.

We should use the `UINotificationService` for this, similar to the out-of-plane segmentation resolved here: https://github.com/OHIF/Viewers/pull/1708.

**Comment by fedorov** [comment]
Response from TCIA:

---
Tracy Nolan commented:

Hi Andrey,

I have a response for you from the team that worked with the PI about this:

Hello,

 

The reason the Study UIDs for the RTSTRUCTs and SEGs are different from the CTs is because Leonard Wee created the SEGs and RTSTRUCTs from the original data rather than pulling it from TCIA. 

 

Leonard's data did not have hashed UIDs for the CTs.

 When Leonard created the RTSTRUCTs and SEGs they were based on the original UID values (not TCIA hashed values).

 

This issue was discussed. Bill Bennett, and Kirk Smith agreed, that hashing the UIDs for the SEGs and RTSTRUCTs would likely break linkages. We consulted with Larry and he stated that this was not an issue with the DICOM standard (different study UIDs).

 

We would have preferred to have the RTSTRUCTs and SEGs created from the TCIA data but it was not and so we processed the data received.

 

Please let us know further questions, comments, or concerns you have for this unusual  collection update.

-tracy

**Comment by JamesAPetts** [comment]
> I think it would be helpful to have a user-readable message about this.

@fedorov Just clarifying: is a user notification when the source series is missing good to work on for IDC priority?

Thanks

**Comment by fedorov** [comment]
Yes, I think so. This issue already has "priority" assigned. Or are you saying that's a separate issue?

**Comment by JamesAPetts** [comment]
Thanks for the quick reply, I just wanted to double check, as this initially started as a conversation about a particular study not rendering, which has been largely resolved.

I'll close this ticket and open a new ticket with just the isolated UI issue, and add it as priority.

**Comment by JamesAPetts** [comment]
Feel free to reopen this issue if any discussion needs to continue about hosting this particular study on the IDC platform.
