### ISSUE TITLE
Logo customization of viewer deployment

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1789]
## Request

We would like to be able to customize our deployment of the OHIF viewer with the logo of our organization. It would be best if this could be done through configuration.

**Why should we prioritize this feature?**

* users of OHIF inevitably will need to have their own branding of the deployment
* lacking ability to configure this, lack of this feature is adding extra motivation to fork and customize OHIF Viewer in a way that complicates contributions back to the upstream etc
* this is a priority for the IDC project, as logo branding was specifically requested by the IDC stakeholders

Or perhaps this is already possible to do through configuration? We talked with @pieper and he didn't think this is possible right now.

**Comment by dannyrb** [comment]
Noticed the post in the IDC repository first ^_^
This is currently possible. Some information here: https://github.com/OHIF/Viewers/pull/1659

**Comment by JamesAPetts** [comment]
Is this SVG logo sufficient for your needs @fedorov ? If so I shall close this ticket.

**Comment by fedorov** [comment]
@JamesAPetts yes, sorry for not closing this earlier!
