### ISSUE TITLE
Get DICOM metadata through Extensions

### ISSUE THREAD

**Issue by yesid08** [OHIF/Viewers#1790]
Hello! 
Currently I am trying to develop an extension, In this moment I would like to obtain the SOPInstanceUID and SeriesInstanceUID of the current instance that is being displayed on the screen.

I looked through the documentation, but I didn't find any information related to this.
Also, I checked the issues and I found that you made something like:
const { displaySetInstanceUid, studyInstanceUid } = viewportSpecificData[
  activeViewportIndex
];

How should I import those variables to my extension? How can I generally obtain DICOM metadata of the current Instance/Series that is being displayed by the user in the ViewPort?

Thanks in advance!

**Comment by sedghi** [comment]
`import { DicomMetadataStore } from '@ohif/core';`
