### ISSUE TITLE
Changing the Theme

### ISSUE THREAD

**Issue by giwl21** [OHIF/Viewers#1792]
Hello!  Our team is planning to use your software to preview dicom documents.  However, the dark theme is a stark contrast from ours.  Is there a configuration setting for changing the application's style, either embedded or self-developed?

**Comment by dannyrb** [comment]
https://docs.ohif.org/viewer/themeing.html

If existing components are missing color variables, more than happy to accept any PRs that update them to use these.

**Comment by nicoesiea** [comment]
Is this page the new one: https://docs.ohif.org/platform/themeing ?
