### ISSUE TITLE
What is the best approach to saving Ellipse Annotations into DICOM?

### ISSUE THREAD

**Issue by ckoudelka1** [OHIF/Viewers#1793]
Hi, 

I know that DICOM SR support for annotations such as Ellipse is already in the works, however I am trying to find a immediate solution to saving elliptical annotations in DICOM. I would like to save out the annotations so I can access them in a third-party application. I am currently using OHIF viewer with Google's Cloud Healthcare API for a image storage/viewer solution. I am new to Javascript and DICOM SR, so I was hoping to get some advice on how to pursue making modifications to OHIF.

What is the best / fastest approach to saving ellipse annotations?

1. Could I add an extensible to add the ellipse annotation into a custom private DICOM tag before uploading it back to Google Cloud Healthcare API? 

2. Update the DICOM SR to work with Ellipse Annotations?  

Thanks!

**Comment by pieper** [comment]
Hi - 

Right now OHIF can save and restore length measurements in SR to a DICOMweb endpoint, including google dicom store, so in theory you are very close.  In practice there's a lot of detail, and if you are new to this you might want to take a deep breath before jumping in.

Here's a document about storing planar annotations in SR:

https://docs.google.com/document/d/1bR6m7foTCzofoZKeIRN5YreBrkjgMcBfNA7r9wXEGR4/edit

As you can see, there are many considerations.

There's a lot of code to look at, even just for the length measurements.  You could look, for example, [here in OHIF](https://github.com/OHIF/Viewers/blob/f09ebbe2e86256b4dd7968f960b7e2cf569f01bb/platform/core/src/DICOMSR/parseDicomStructuredReport.js#L22) which uses code that is [here in dcmjs](https://github.com/dcmjs-org/dcmjs/tree/master/src/adapters/Cornerstone).

Let us know what you think.  This will no doubt eventually move forward and it would be great if you could help.

**Comment by ckoudelka1** [comment]
Thanks for getting back to me so soon. This information has been helpful!

**Comment by sedghi** [comment]
We have DICOM SR adapters in Cornerstone3D https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/adapters/src
