### ISSUE TITLE
Open side-by-side studies, prior studies for comparison in OHIF viewer

### ISSUE THREAD

**Issue by Facundo20** [OHIF/Viewers#1794]
Hello, I was looking through the docs but can´t find the option/answer. 

Beside of using lesion tracker, 

Sometimes it´s necessary to visualize prior studies for comparison of non-oncologic patients. 

Is there any way to open prior studies from the viewer? Can it be considered as a request? Thanks in advance!

**Comment by sedghi** [comment]
You can look at our hanging protocols 
https://docs.ohif.org/platform/extensions/modules/hpModule#matching-on-prior-study-with-uid
