### ISSUE TITLE
Looping error related to SEG loading

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#1797]
### Describe the Bug

while trying to load this study: https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc-tcia/dicomStores/idc-tcia/study/1.3.6.1.4.1.9328.50.1.216116555221814778114703363464001196508, I get looping error below:

![2020-06-19_16-31-31 (1)](https://user-images.githubusercontent.com/313942/85177911-2322dc80-b24b-11ea-8c83-685315e9d3e0.gif)

This may well be a problem with the dataset, but probably this is not the expected way to handle it in OHIF?

### What steps can we follow to reproduce the bug?

Open URL above, or download the study from TCIA as shown below:

![image](https://user-images.githubusercontent.com/313942/85177974-4baad680-b24b-11ea-8dec-e17d8d0ac1e1.png)

![image](https://user-images.githubusercontent.com/313942/85178103-aa705000-b24b-11ea-8adc-c233add93b9d.png)

**Comment by JamesAPetts** [comment]
For what reason was this moved back to in progress? Does the issue still persist after  #1877?

**Comment by fedorov** [comment]
@JamesAPetts no, the issue does not persist. I moved it back into "in progress", since it was not closed, and I was not sure about the true status. I will close it now.

**Comment by JamesAPetts** [comment]
Awesome, thanks for the quick response.
