### ISSUE TITLE
Clearcanvas(CC) Image Server Usage as Data Source

### ISSUE THREAD

**Issue by berkelmas** [OHIF/Viewers#1798]
Hello,

How do i need to configure clearcanvas image server in config/default.js file ? My CC server listens to port 1000 for wado requests.

**Comment by lam0620** [comment]
1. Ohif v2x support dicomweb only, doesn't support DIMSE standard that CC has unless you use ohif v1.x
2. You can use https://github.com/knopkem/dicomweb-proxy as broker proxy to connect to.
ohif <=> proxy <=> CC
