### ISSUE TITLE
Using just the viewer

### ISSUE THREAD

**Issue by giwl21** [OHIF/Viewers#1802]
**Description**

Hello, our team is planning to use the OHIF viewer for reviewing files.  However, we want to be able to use our own browser for dicom libraries that the user would click on and immediately view the images.  The docs, while extremely helpful in establishing context, did not offer much insight on using just this main component.  Our solution would be to grab just the files needed to run the viewer and "wire" it using our files. 

What we dont know is:
1.  The files necessary to run just the viewer
2.  How to wire them

Where would be a good place for us to start?

**Comment by ravitej177** [comment]
@giwl21 do you have any luck integrating the standalone viewer?

**Comment by sedghi** [comment]
You can achieve so if you have the studyinstanceUID

take a look here https://docs.ohif.org/platform/modes/
