### ISSUE TITLE
annotation always having frameindex=0

### ISSUE THREAD

**Issue by yash0906** [OHIF/Viewers#1826]
i am printing the measurementData on console. On whichever frame i am drawing the annotation, the data is always having frameindex=0. 
Having the measurement data, i want to draw the annotation on its correct frame.
![Screenshot from 2020-06-29 00-43-54](https://user-images.githubusercontent.com/43386041/85956172-ba9dd300-b9a1-11ea-86e4-be2158835e80.png)
here for example, the image belongs to 41st frame, but frameindex=0 in measurementData of annotation.

**Comment by yash0906** [comment]
I want to save annotation as a json object in my database, and redraw them on the frame on which they were drawn. 
This looks like a decent approach, does Ohif has anything of this sort built, like an API kinda thing.

**Comment by james-hanks** [comment]
@jbocce try to reproduce with multiframe data. @sedghi provide dataset to test if needed

**Comment by jbocce** [comment]
The issue as reported is no longer an issue in master. However issue #3751 was discovered while verifying this issue.

**Comment by phoenixsac** [comment]
@yash0906 were you able to save the annotations as json ad retrieve it again to be rendered in the viewer? does it work? would really appreciate if you could explain how you achieved it.
