### ISSUE TITLE
Extensions, how to config?

### ISSUE THREAD

**Issue by lucasmazevedo** [OHIF/Viewers#1845]
Hello everyone,

how to use extensions ??

How to configure them in config.js?

![Captura de Tela 2020-07-01 às 10 07 57](https://user-images.githubusercontent.com/13725462/86247423-d3191380-bb82-11ea-908d-811e1096a40e.png)

**Comment by joweste** [comment]
I´d like to know as well.

**Comment by dannyrb** [comment]
I believe only the `@ohif/extension-cornerstone` will use configuration if provided? All are capable, but would need to be updated to support whatever it is you're trying to make configurable.

Example of providing extension specific configuration:

```js
window.config = {
    extensions: [
        ExampleExtensionWithoutConfig,
        [ExampleExtensionWithConfig, { /* extension's config object */ }],
        AnotherExtension,
    ],
    ...
}
```

Where each extension adheres to the format spelled out in our example extension and docs. The `extensions/**/src/index.js` should be good examples.
