### ISSUE TITLE
Clicks in dropdown menus do not work in Safari

### ISSUE THREAD

**Issue by spalte** [OHIF/Viewers#186]
There is a race condition that makes it so that in Safari, clicks in dropdown menus are not processed. Not removing the 'open' class from the dropdown menu makes it so that clicks are processed, but this is not a solution.

```diff
--- a/Packages/ohif-core/client/components/base/mixins/dropdown.js
+++ b/Packages/ohif-core/client/components/base/mixins/dropdown.js
@@ -44,7 +44,7 @@ OHIF.mixins.dropdown = new OHIF.Mixin({
                     destroyHandle();
                     clearTimeout(timeout);
                 });
-                $dropdown.removeClass('open');
+                // $dropdown.removeClass('open');
             };
 
             // Destroy the view when the promise is fullfilled
```

**Comment by swederik** [comment]
Thanks for the report!

**Comment by dannyrb** [comment]
Unfortunately this issue has grown stale, and with the release of our most recent major version, it is unlikely that we will have the bandwidth to address this issue for our `v1.x` branch. 

If you find that this has not yet been addressed in our `master` branch, you are more than welcome to create a [GitHub Issue](https://github.com/OHIF/Viewers/issues/new) to request or discuss it. If you're curious to see what we have planned in the near future, you can [check out our roadmap](https://ohif.canny.io/), and [read our docs](https://docs.ohif.org/).
