### ISSUE TITLE
add app config to disable measurements panel

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#1864]
## Request

Not all use cases require measurements, so it would be good to be able to turn off the panel completely.

**What feature or change would you like to see made?**

Add an app config option so that the panel would not show.

@dannyrb suggested the changes could go here: https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/App.js#L283

**Why should we prioritize this feature?**

We'd like it for the IDC MVP, so I'll put on the corresponding label.

**Comment by JamesAPetts** [comment]
The measurements panel can now be disabled by adding `disableMeasurementPanel: true` to the appConfig.
