### ISSUE TITLE
configure which cornerstone tools should be displayed

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#1866]
Related to #1864 , some use cases don't want to expose annotation tools that cannot be saved.  Users could be confused/frustrated if they annotate carefully then lose their work.  Better not to lead them down that path.

## Request

It would be great if the app-config.js could specify a list of tools to display and the order (so they can be grouped by function). Extra nice would be a small space or other indicator between groups, but that's not essential.

For the IDC use case this could be:

* stack scroll

* zoom
* pan

* levels
* roi window
* invert

* reset

* cine
* layout

The `More` menu could have
* magnify
* rotate
* flips
* download

**Why should we prioritize this feature?**

It sounds like it would not take much effort but would make the UI clearer.

**Comment by fedorov** [comment]
@pieper if you remember for the next time, please assign IDC* labeled issues to the IDC project - this will add them to the board - otherwise I am afraid we may miss them in the review. 

![image](https://user-images.githubusercontent.com/313942/87687939-57a78c80-c754-11ea-860e-d5033c9bafaf.png)

**Comment by JamesAPetts** [comment]
Just to confirm discussions in the IDC slack, as the availability of these tools are hardcoded in the cornerstone extension, I believe we decided to cancel this one, and just comment them out in the IDC app at deployment/staging for now. Let me know if you need help with the latter.

**Comment by fedorov** [comment]
I created a corresponding issue under IDC WebApp, closing this one.
