### ISSUE TITLE
How to save OHIF measurement or annotation to mySQL

### ISSUE THREAD

**Issue by DarrenNi** [OHIF/Viewers#1868]
For work reasons, I need to use OHIF to view DICOM images

I followed the documentation to download and deploy OHIF + Orthanc, and it ran successfully.

I have stored the metadata of Orthanc’s uploaded DICOM images in MySQL, but I still don’t understand **how to save the measurement data in the OHIF viewer to MySQL**.

This problem has been plagued for many days and read Document several times.

In addition, there is a problem that the default downloaded by OHIF only supports round and square measurement. **How can we develop the labeling and measurement of arbitrary polygons**?

Thanks very much

**Comment by smilegok** [comment]
Here is what I have done. I searched all files for RectangleRoi and added FreehandRoiTool nesxt line to it. And renamed FreehandMouse.js to FreehandRoi.js , and added to toolbar with toolbarModole.js file as below. And its done but in measurements sidebar they still in yellow color with warning.
**
  {
    id: 'RectangleRoi',
    label: 'Rectangle',
    icon: 'square-o',
    //
    type: TOOLBAR_BUTTON_TYPES.SET_TOOL_ACTIVE,
    commandName: 'setToolActive',
    commandOptions: { toolName: 'RectangleRoi' },
  },
  {
    id: 'FreehandRoi',
    label: 'Freehand',
    icon: 'circle-o',
    //
    type: TOOLBAR_BUTTON_TYPES.SET_TOOL_ACTIVE,
    commandName: 'setToolActive',
    commandOptions: { toolName: 'FreehandRoi' },
  },**

**Comment by smilegok** [comment]
For tool issue.
Here is what I have done. I searched all files for RectangleRoi and added FreehandRoiTool next line to it. And renamed FreehandMouse.js to FreehandRoi.js , And added to tools needed to toolbar with toolbarModole.js file as below. And its done :) But in measurements sidebar they still in yellow color with warnings.
**
{
id: 'RectangleRoi',
label: 'Rectangle',
icon: 'square-o',
//
type: TOOLBAR_BUTTON_TYPES.SET_TOOL_ACTIVE,
commandName: 'setToolActive',
commandOptions: { toolName: 'RectangleRoi' },
},
{
id: 'FreehandRoi',
label: 'Freehand',
icon: 'circle-o',
//
type: TOOLBAR_BUTTON_TYPES.SET_TOOL_ACTIVE,
commandName: 'setToolActive',
commandOptions: { toolName: 'FreehandRoi' },
},**

**Comment by sedghi** [comment]
To interact with your server, confidently make an XHR POST call.
