### ISSUE TITLE
Can't inject JWT in Instance call ? 

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#1870]
Hi there,

I have my DicomWeb server accessible through a reverse proxy using a JWT auth mechanisme, so I need to inject the Authorization Bearer in the requests going from OHIF.

I did this 

servers: {
            dicomWeb: [
              {
                name: "Orthanc",
                wadoUriRoot:
                  "/api/wado",
                qidoRoot:
                  "/api/dicom-web",
                wadoRoot:
                  "/api/dicom-web",
                qidoSupportsIncludeField: true,
                imageRendering: "wadors",
                thumbnailRendering: "wadors",
                enableStudyLazyLoad: true,
                requestOptions : {
                  auth: (options) => { return `Bearer ${token}`}
                }
              }
            ]
          },

It is working properly to get the /series /metadata APIs but does not work for the /instances/{UID}/frames/1 API.
The outgoing request do not includes au authorization header for Instance fetching while it is OK for series and metadata,

How can I set the token to be included in every http request of OHIF ? 

thanks for help,

Best regards,

Salim

**Comment by salimkanoun** [comment]
Dear @swederik , I compiled OHIF with success, but in this compiled version I don't even have the authorization token anymore even in the /series /metadata APIs that were working with the script tag (sources downloaded yesterday, 
4.2.13 version)
at least the MPR is now working well with tbe built version ^^

Best regards,

Salim

**Comment by web2ls** [comment]
@salimkanoun FYI i find that getting metadata and getting images controls from different loaders (RetrieveMetadataLoaderAsync and cornerstoneWADOImageLoader)

i solved this issue by adding my auth headers in these loaders

**Comment by dannyrb** [comment]
Hello @salimkanoun, I'm having trouble finding it, but it appears others have hit this issue. I believe we're pulling the config and setting the headers for those requests here:

https://github.com/OHIF/Viewers/blob/709f14708e2b0f912b5ea509114acd87af3149cb/platform/viewer/src/config.js#L45-L60

It may not be setup correctly, or it's possible bundling or a different extension accidentally blows out the configuration or creates a duplicate loader at some point.

**Comment by salimkanoun** [comment]
thanks @dannyrb for this input

@web2ls could you share your config sample to inject the jwt in these two loader ?

**Comment by web2ls** [comment]
@salimkanoun 

metadata loader placed here:

platform/core/src/studies/services/wado/retrieveMetadataLoaderAsync.js

`client.headers = Object.assign(client.headers, getMyOwnAuthHeaders());`
 `this.client = client;`

and image loader placed here:

platform/viewer/src/config.js

    `if (headers.Authorization) {
          xhr.setRequestHeader('Authorization', headers.Authorization); // native OHIF headers
      }`

    `const oncoreHeaders = getOncoreAuthHeaders();` // custom headers

    `for (let key in oncoreHeaders) {
      xhr.setRequestHeader(key, oncoreHeaders[key]); // rewrite it
    }`

**Comment by Diex** [comment]
maybe related to https://github.com/OHIF/Viewers/issues/1736

**Comment by salimkanoun** [comment]
@Diex It is clearly the exact same issue

**Comment by Diex** [comment]
oh I see...
what I tried so far:

+ Using a proxy configuration for adding Authorization token on request.
+ Using custom header as @web2ls said

In both cases I have the same result:

no images loaded. 
output trace ends with:
```

Timepoint data retrieval
dicomweb-client.es.js?f399:873 search series of study 1.2.840.113704.1.111.10096.1570895568.1
dicomweb-client.es.js?f399:903 retrieve metadata of series 1.2.840.113704.1.111.10096.1570895684.8
```

and a new error:

_checkPropTypes.js?e034:20 Warning: Failed prop type: Invalid prop `fallbackComponent` of type `function` supplied to `OHIFErrorBoundary`, expected a single ReactElement._

seems unrelated to me but you never know.

**Comment by Diex** [comment]
@salimkanoun if you try @web2ls solution you need to be sure you do not have 
`cornerstoneExtensionConfig: {},` in your own configuration settings. In that case `cornerstoneWADOImageLoader.configure()` in config.js will be skipped.

**Comment by pavankjadda** [comment]
@salimkanoun have you ever fixed the issue?
