### ISSUE TITLE
Lesion Tracker is not working

### ISSUE THREAD

**Issue by fusion2013** [OHIF/Viewers#1871]
Since last week I am trying to access following url to get started with Lesion Tracker. But it seems like it is down.

http://lesiontracker.ohif.org/

From somewhere I have downloaded the setup but the lesion tracker server is not running on 3000. Also I am not able to view the start/stop service files on installation directory.

![image](https://user-images.githubusercontent.com/11787641/86585847-af036b00-bfa4-11ea-968a-d5b5ac6037ff.png)

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
