### ISSUE TITLE
Error: decodeTask: imageFrame.pixelData is undefined after decoding

### ISSUE THREAD

**Issue by kin3tik** [OHIF/Viewers#1882]
Hi All,

I am attempting to set up an embedded view using version 4.2.7 from [here](https://unpkg.com/@ohif/viewer@4.2.7/dist/index.umd.js) within my own ASP MVC application following [docs.ohif.org/deployment/#embedded-viewer](https://docs.ohif.org/deployment/#embedded-viewer), using the `?url=` param to pass my own JSON object. 

I've tried generating my own JSON from a DCM/Dicom file, and I have also tried using the sample JSON/DCM from the link above. Both result in the js error below:

`index.umd.js:55464 Uncaught (in promise) Error: decodeTask: imageFrame.pixelData is undefined after decoding`

If I drop the `?url=` param and use the worklist view provided by the sample viewer config ([here](https://codesandbox.io/s/viewer-script-tag-tprch?file=/index.html)) I can browse and view images correctly.

At this point I'm not sure what I'm missing - does anyone have any ideas? Thanks.

![2020-07-08 18_51_36-Window](https://user-images.githubusercontent.com/1654294/86898701-65558480-c14c-11ea-8f8a-87fbc54b5309.png)

**Comment by Zaid-Safadi** [comment]
@kin3tik, I didn't look at your solution but I have this feature implemented in [DICOMcloud](https://github.com/DICOMcloud/DICOMcloud) (.NET 4.7), check these referenced:
1. [ OHIFController](https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud.Wado.WebApi/Controllers/OHIFViewerController.cs) 
2. [OHIFService](https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud.Wado/Services/OhifService.cs)

The code generates an older version of the JSON metadata which need to be updated to work with the latest version of the viewer but may give you an idea.

**Comment by kin3tik** [comment]
Hi @Zaid-Safadi , thank you for the suggestion. I haven't had any issues (I think) parsing the dcm files using fo-dicom to generate the JSON metadata, and I've tried just using the JSON metadata + dicom file in the OHIF Viewer documentation as a sanity check, but both in the same issue from my original comment :(

**Comment by dannyrb** [comment]
@kin3tik, it's possible the documentation's JSON file is outdated. It's not living documentation, and we update it infrequently. This is an area I wish we were better, but we have funding limitations.

There should be an issue floating around where we discuss the new format. Have you verified that after the JSON is requested, a DICOM Web request to retrieve the frame is made?

**Comment by kin3tik** [comment]
@dannyrb hi danny, thanks for the reply. I can confirm it makes a network request to the dicom file - the issue seems to be occurring after this. I attached a visual studio solution to the second comment that reproduces my issue. Completely lost as to how to resolve.

**Comment by DraconPern** [comment]
I have the same issue.  The same configuration works on commit d76fab0bc9012cf4e619fc418b075abd30279745 from a year ago.  Not sure if it matters but I am using wadouri.  Also the same issue as OP, I see the dcm file transferred, but fails on decoding.

**Comment by thiagoss** [comment]
I believe I'm running into the same issue when trying wadouri with an old dcm4chee server. The wado downloaded file seems to be correct and works with other applications.
