### ISSUE TITLE
Error loading images in OHIFViewer

### ISSUE THREAD

**Issue by gholamrezaeesaeed** [OHIF/Viewers#189]
Dear Sir/Madam
hope everything goes well to you 
i will appriciate if you guide me for belw problem as attached picture 
![screen shot 2018-05-07 at 7 48 16 pm](https://user-images.githubusercontent.com/17097764/39710141-318b7fe2-5231-11e8-8c8d-1e6a43daf3f0.png)
we use dcm4chee-arc-light server
once in OHIFViewers study list loaded i choosed one study then the error in attached file display 
however i want to handled CORS error as below proxy nodejs code:
`var http = require('http'),
    httpProxy = require('http-proxy');

var proxy =  httpProxy.createProxyServer({target:'http://localhost:8080', auth: 'admin:saeed-7901'}).listen(8085);
//, auth: 'admin:saeed-7901' this code use for dcm4chee-arc authentication service

proxy.on('proxyRes', function(proxyReq, req, res, options) {
  // add the CORS header to the response
  console.log('in');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  console.log('out');
});

proxy.on('error', function(e) {
  // suppress errors
  console.log('error on the proxy happend');
});`
please notice my ohifviewer configuration code as below:
`{
   "servers": {
     "dicomWeb": [
       {
         "name": "DCM4CHEE",
         "wadoUriRoot": "http://localhost:8085/dcm4chee-arc/aets/DCM4CHEE/wado",
         "qidoRoot": "http://localhost:8085/dcm4chee-arc/aets/DCM4CHEE/rs",
         "wadoRoot": "http://localhost:8085/dcm4chee-arc/aets/DCM4CHEE/rs",
         "qidoSupportsIncludeField": false,
         "imageRendering": "wadouri",
         "requestOptions": {
           "auth": "admin:saeed-7901",
           "logRequests": true,
           "logResponses": false,
           "logTiming": true
         }
       }
     ],
     "dimse": [
       {
         "name": "DCM4CHEE_DIMSE",
         "wadoUriRoot": "http://localhost:8085/dcm4chee-arc/aets/DCM4CHEE/wado",
         "requestOptions": {
           "auth": "admin:saeed-7901",
           "logRequests": true,
           "logResponses": false,
           "logTiming": true
         },
         "peers": [
           {
             "host": "localhost",
             "port": 4242,
             "aeTitle": "DCM4CHEE",
             "default": true,
             "supportsInstanceRetrievalByStudyUid": false,
             "server": false
           },
           {
             "host": "0.0.0.0",
             "port": 11112,
             "aeTitle": "DCM4CHEE",
             "default": true,
             "server": true,
             "supportsInstanceRetrievalByStudyUid": true
           }
         ]
       }
     ]
   },
  "defaultServiceType": "dimse",
   "dropCollections": true,
   "public": {
     "verifyEmail": false,
     "ui": {
     "studyListFunctionsEnabled": true,
       "leftSidebarOpen": false,
       "leftSidebarDragAndDrop": true,
       "displaySetNavigationLoopOverSeries": true,
      "displaySetNavigationMultipleViewports": false,
       "displayEchoUltrasoundWorkflow": false,
      "autoPositionMeasurementsTextCallOuts": "TRBL",
       "showStackLoadingProgressBar": true,
       "cornerstoneRenderer": "webgl",
       "sortSeriesByIncomingOrder": false,
       "useMiddleSeriesInstanceAsThumbnail": true
     },
     "demoUserEnabled": true,
     "prefetch": {
       "displaySetCount": 1
  }
}`

**Comment by gholamrezaeesaeed** [comment]
@swederik 
please help me

**Comment by swederik** [comment]
You don't need to run a separate proxy. We include one for development ('wadoproxy'). Check your browser console. What is the error you are seeing?

**Comment by gccgomes** [comment]
I run without any error in my installation of dcm4chee . This error often happens when I setup wrong url for all wado urls on server tab or in server json file. Basically my pacs AET name is different from DCM4CHEE. 
The default url is
http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/wado
http://localhost:8080/dcm4chee-arc/aets/USEDAETITLENAME/rs

On my case, that solved this problem,change this  url on json 

http://localhost:8080/dcm4chee-arc/aets/USEDAETITLENAME/wado
http://localhost:8080/dcm4chee-arc/aets/USEDAETITLENAME/rs

Where USEDATITLENAME is my PACS AET.

**Comment by gholamrezaeesaeed** [comment]
hi geraldo
i install dcm4chee-arc and ohif viewer on linux centos 7
do you install these on linux or you install on windows
if you install dcm4chee-arc and ohif on linux plese send to me ohif dimse
configuration file
and i use on default dcm4chee AET on my server
thank you geraldo

**Comment by gholamrezaeesaeed** [comment]
hi Erik
thank you
