### ISSUE TITLE
Cannot load images from Orthanc

### ISSUE THREAD

**Issue by rangata** [OHIF/Viewers#19]
Dear Friends,

I have a problem with loading images from Orthanc repository via OHIFViewer.
I see patient list from orthanc server, but when I've try to open image, I got this error message
"an error occurred whole loadgin image: dicomweb:http://192.168.99.100:8042/wado?requestType=WADO&studyUID=2.16....." on next line Details: [object ArrayBuffer]"

In firebug I saw this: http://192.168.99.100:8042/wado?requestType=WADO&studyUID=2.16.840.1.113669.632.10.20140407.123623642.0.84&seriesUID=2.16.840.1.113669.632.10.20140407.123623642.0.85&objectUID=2.16.840.1.113669.632.10.20131219.130527112.10002.44&contentType=application%2Fdicom 401 Unauthorized

**Comment by swederik** [comment]
Hi Friend,

Sorry that this is not documented well enough, we plan to improve it. I need some more information to help you diagnose this problem.

- How are you running Orthanc? Standalone or in Docker?
- How are you planning to run this? On a server for web access, or locally for testing?

I see that you are using the IP that I included in the nodeCORSproxy.js script. This was my own Docker machine's IP, so it almost definitely doesn't apply to your situation. I have just pushed a commit updating the default configuration files, so please pull from master and try this:

- Start Orthanc
- Go to the /etc folder and running the CORS proxy:

````
node nodeCORSProxy.js
````

- Run the OHIFViewer with Meteor using:

````
cd OHIFViewer
./bin/localhostOrthanc.sh
````

**Comment by pedrohml** [comment]
Hello,

I also recommend the pull request #17. It runs the entire OHIFViewers in a few commands using _docker_.

**Comment by akshay87g** [comment]
Hello all,  I am having an issue as well with pulling studies/data into the OHIF Viewer.

So far I have: the Orthanc docker server running, proxy server running,and OHIF viewer running. I have modified the nodeCORSProxy.js file so the target points to the server. I also ran commands I [referenced](https://orthanc.chu.ulg.ac.be/book/users/rest.html#accessing-a-patient) (such as:  $ curl http://localhost:8042/patients) and seem to be getting the appropriate data back from the server so the problem as to be on the Viewer end.

Any idea why the viewer isn't talking to the server? Also I noticed the  "qidoRoot": "http://localhost:8042/dicom-web", etc in the localhostOrthanc.json but seems like the dicom-web url isn't pointing to anything?

Screenshots are attached.

 
<img width="741" alt="screen shot 2016-06-04 at 3 26 27 pm" src="https://cloud.githubusercontent.com/assets/19271735/15801638/b2e80fc0-2a69-11e6-8dbf-dbf15cd420b4.png">
![screen shot 2016-06-04 at 3 24 42 pm](https://cloud.githubusercontent.com/assets/19271735/15801640/b2e89e5e-2a69-11e6-811d-f8bd16283f3c.png)
![screen shot 2016-06-04 at 3 24 26 pm](https://cloud.githubusercontent.com/assets/19271735/15801639/b2e8921a-2a69-11e6-81e9-6598840d45ba.png)
![screen shot 2016-06-04 at 3 24 01 pm](https://cloud.githubusercontent.com/assets/19271735/15801641/b2ea00b4-2a69-11e6-8178-87588441aecc.png)

**Comment by pedrohml** [comment]
Hi there, 

I had the same issues in the beginning. Consider the pull requests #17 and #18

**Comment by akshay87g** [comment]
Thank you for your quick reply.

It seems like [#17 ](https://github.com/OHIF/Viewers/pull/17) is addressing the proxy/server issue but we have confirmed that our proxy and main server is working well.

How do we specify the viewer to communicate with proxy server properly? 

I am having trouble understand the localhostOrthanc.json file specifications -- is this relevant? (see below)

<img width="1186" alt="screen shot 2016-06-05 at 12 23 01 am" src="https://cloud.githubusercontent.com/assets/19271735/15803596/c94e7976-2ab3-11e6-9b45-42ed1ad41426.png">

**Comment by swederik** [comment]
Okay so the only thing that appears wrong above is that your proxy is running on 8042 (the .listen(8043) line) and your viewer is pointing to port 8043 (under wadoURIRoot).

That doesn't explain why you don't see the study list though. What do you get in the terminal running the Meteor instance? Or in the Chrome debug console?

**Comment by swederik** [comment]
The proxy is now internal, so this shouldn't be an issue anymore. Please reopen if you're having problems.
