### ISSUE TITLE
How should the extensions be added?

### ISSUE THREAD

**Issue by KhyatiMehta3** [OHIF/Viewers#1901]
Hello! This is probably a noob question, but I referred a few issues here and didn't get any solution. I want to add the segmentation extension, with the tools to my implementation of the viewer. 
I've referred [this](https://github.com/OHIF/Viewers/issues/1673) issue & [this](https://codesandbox.io/s/viewer-script-tag-microscopy-extension-44unk?file=/index.html) code snippet, but haven't got any luck. 
Where exactly should the extension be mentioned to apply while running the viewer?

Thanks in advance! :)

**Comment by KhyatiMehta3** [comment]
Also added [this](https://www.npmjs.com/package/@ohif/extension-dicom-segmentation) to the root of the project, but the tools didn't show up. I might be missing something, I'm not sure. Any help would be greatly appreciated! :)

**Comment by ranasrule** [comment]
same question here

**Comment by KhyatiMehta3** [comment]
It's mentioned [here](https://github.com/OHIF/Viewers/issues/1776#issuecomment-664191105) that the segmentation extension is added by default in the viewer, so closing this issue
