### ISSUE TITLE
Loading study : the "loading" display is always displaying 0% before showing the study image

### ISSUE THREAD

**Issue by sylvainb31** [OHIF/Viewers#1902]
Hello,

When loading the study takes some time, there is a "loading... 0%" message that displays instead of the study.
This is fine but it stays at 0% until the study is displayed. In my example it stays for many seconds at "loading... 0%" and then it shows the study.
Is it not supposed to display the progress as the loading is progressing ? I would expect it to be that way.

Thanks for your help.

Sylvain

![LoadingZero](https://user-images.githubusercontent.com/37896804/87409876-e043f280-c5c5-11ea-834e-620c7860fc6b.png)

**Comment by gccgomes** [comment]
I have the same issue too. The loading status is not updated. And series is loading all study images.
![image](https://user-images.githubusercontent.com/17948488/87414545-50408180-c5a2-11ea-936b-22120d6d0009.png)

**Comment by ranasrule** [comment]
same here. also the viewer just shows a blank black page sometimes while loading study info

**Comment by sylvainb31** [comment]
Wanted to add that when pointing toward this server, the loading works correctly : https://dicomcloud.azurewebsites.net

But it is not working when pointing toward this one : https://server.dcmjs.org

```
window.OHIFViewer.installViewer(
        {
            routerBasename: '/Home/Viewer',
            extensions: [],
            showStudyList: true,
            filterQueryParam: false,
            maxConcurrentMetadataRequests: 1,
            servers: {
                dicomWeb: [
                    {
                        name: 'DCM4CHEE',
                        wadoUriRoot: '/api/WadoQidoAPI', /* https://dicomcloud.azurewebsites.net/api https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado /api/WadoQidoAPI  /api/WadoUriAPI/getImageDicom */
                        qidoRoot: '/api/WadoQidoAPI', /* https://dicomcloud.azurewebsites.net/api https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs /api/WadoQidoAPI */
                        wadoRoot: '/api/WadoQidoAPI', /* https://dicomcloud.azurewebsites.net/api https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs /api/WadoQidoAPI */
                        qidoSupportsIncludeField: true,
                        imageRendering: 'wadors', /* wadors / wadouri voir : https://github.com/OHIF/Viewers/issues/1338 et https://github.com/OHIF/Viewers/issues/482 */
                        thumbnailRendering: 'wadors', /* wadors / wadouri */
                        enableStudyLazyLoad: true,
                    },
                ],
            }
        },
        containerId,
        componentRenderedOrUpdatedCallback
    );
```

Thanks for your help,

Sylvain

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
