### ISSUE TITLE
File formats support

### ISSUE THREAD

**Issue by pablovegaimexhs** [OHIF/Viewers#1906]
Hello OHIF team!
In the About section you said: It can retrieve and load images from most sources and formats.

exactly what file types do you support?

example: PNG, JPG, NIFTI, TIF, DICOM, etc

**Comment by maniappan** [comment]
Would like to see if we can load TIF file apart from Dicom, is this supported?

**Comment by cynde** [comment]
can somebody tell me are another file types other than dcm supported? such as NIFTI

**Comment by sedghi** [comment]
Nifti load is added in cornerstone3D, and it takes some time for us to add it to OHIF
