### ISSUE TITLE
Prevent double authentication with google

### ISSUE THREAD

**Issue by christianvargasforero** [OHIF/Viewers#1908]
God day, 

I have the following question; I am embedding the viewer in a RedwoodJS application, in which I already have an authentication with Google, when I enter the application for the first time it asks for user authentication but when it is loading the viewer comes back and asks for Google authorization a second time , Is it possible to pass the parameters (user or token) of the first login and prevent the viewer from asking for the login again?

**Comment by Diex** [comment]
hi: this was asked several times. I positively know about other people  (myself included) are trying to solve it. I have a research going on trying to understand in the first place how Google services / authentications / authorization flow works besides how OHIF actually gains access to healtcare endpoints. it's possible that the answer for this is really simple so it do not deserves being answered. I've been struggling with this for at least a month with no succes. I have to tell I've not experience on react neither OAuth specifics beyond the usual login flow. I'm using firebase (as I think you are too) and the key point rely on the fact that everything on fb is available on gcloud but this seems not to be the case. let me know if you find an aswer. thanks !

**Comment by dheerajd3v** [comment]
Similar usecase here. We have a frontend react app (installed on GCE VM)  that uses Firestore backend and calls the OHIF viewer endpoint to view the medical images auth is via simple email/password auth method provided by Firebase auth . The OHIF viewer is  installed on a 2nd  GCE VM.   I would like to know if it possible to extend the Firebase based authentication mechanism to call the OHIF viewer that in turn calls Cloud Healthcare APIs? The OHIF viewer on GCE VM is at present entirely controlled via end user IAM roles and would like to leverage Firebase auth

**Comment by apgal** [comment]
If any of you solved this issue, kindly share how you did it.  @dheerajd3v @Diex @christianvargasforero

**Comment by dheerajd3v** [comment]
@apgal Apparently what I hear is that Firebase does not support OAuth

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
