### ISSUE TITLE
Embedded nuxt framework

### ISSUE THREAD

**Issue by CloudWoR** [OHIF/Viewers#1913]
> :hand:nuxt have 234,299 star,More and more people choose to use nuxt, while OHI only supports nested react
> community. How does it add value? Why _this feature_?
>It can provide more developers with the "OHIF" plug-in based on nuxt out of the box
> Is your request very specific to your needs? Consider
yes, very.
> [contributing it](https://docs.ohif.org/contributing.html) yourself! Or reach
> out to a community member that offers
> [consulting services](https://docs.ohif.org/help.html#paid--commercial).

## Request

**What feature or change would you like to see made?**

Embedded nuxt framework

**Why should we prioritize this feature?**

...More and more people choose to use nuxt, while OHI only supports nested react

**Comment by sedghi** [comment]
Unfortunately, that is not part of the current plan and is not a priority at the moment.
