### ISSUE TITLE
Build : Manifest missing public url

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#1925]
Dear All,

I think I found a bug in the build of OHIF, if I use PUBLIC_URL=/viewer/ at build command, the index.html correctly integrates the relative path of OHIF viewer but not the manifest.json
And so I got some error message in the console saying the browser can't retrieve the chrome logo (for which the location is in the manifest.json)
this issue however do not impact viewer usability

Best regards,

Salim

**Comment by PoyangLiu** [comment]
Relates to #1125

**Comment by salimkanoun** [comment]
probably solved, outdated issue
