### ISSUE TITLE
Standalone Client build not working

### ISSUE THREAD

**Issue by yehudahkay** [OHIF/Viewers#193]
Hi I updated to the latest code which fixes #172 however the client build is not working for me now. Please see screenshot of errors. Thank you!

![image](https://user-images.githubusercontent.com/9964988/39868528-a9c947ea-5462-11e8-9baf-f8295dc53ed1.png)

**Comment by swederik** [comment]
Thanks for the report! We've added a stage to the CI pipeline which will automatically build the standalone viewer on each commit, so hopefully we can avoid this type of issue in the future: https://github.com/OHIF/Viewers/blob/master/.travis.yml#L50
