### ISSUE TITLE
How to modify Cornerstone Tools in OHIF

### ISSUE THREAD

**Issue by szwang-seedtech** [OHIF/Viewers#1932]
Hello,

I am trying to add a few my own cornorstone-based tools into OHIF, but it turns out that the Cornorstone in OHIF is in a packaged status, and I have no idea how to deal with that. So what shall I do if I want to modify the tools in OHIF?

Looking forward to your reply!

**Comment by PoyangLiu** [comment]
The core team can probably answer this question better.  But I hope this example can help with the modifying csTool in the confine of its extension capabilities.

Let's say you want to change the default `wwwcTool` window leveling strategy.  You can do the following
```
const appConfig = {
  cornerstoneExtensionConfig: {
    tools: {
      Wwwc: wwwcToolConfig
    }
  }
}
```
where key (`Wwwc` here) must match the [name of the tool](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/WwwcTool.js#L16).
```
const wwwcToolConfig = {
    defaultStrategy: myLevelingStrategy.name,
    strategies: { myLevelingStrategy }
}

function myLevelingStrategy(evt) {
    .... code of my strategy.
}
```
See the wwwc tool [basicLevelingStrategy](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/WwwcTool.js#L51) implemented in cornerstoneTool.

**Comment by PoyangLiu** [comment]
On the other hand, the tools seems to be added in the [`init.js`](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone/src/init.js#L57) of `extensions/cornerstone` extension.
If you are working in your own fork/branch, then perhaps create your own tools and add them to the list?

**Comment by szwang-wthealth** [comment]
Thank you for your reply, but I think you misunderstood my question

**Comment by szwang-wthealth** [comment]
Thank you for your help! I tried and it seems worked!
