### ISSUE TITLE
package.json "module" fields point to nonexistent files

### ISSUE THREAD

**Issue by Aurelius333** [OHIF/Viewers#1935]
## Bug Report

(I don't know much about this works; these are just my best guesses.)

### Describe the Bug

The `package.json` of every package in this repository includes this line:
https://github.com/OHIF/Viewers/blob/14da2473187a4728cdae915c1cd75802f768986c/platform/viewer/package.json#L9

However, they all also include these lines: https://github.com/OHIF/Viewers/blob/14da2473187a4728cdae915c1cd75802f768986c/platform/viewer/package.json#L41-L44

When installing these packages into `node_modules`, the `src` directory is not included, so the `"module"` field points to a file that doesn't exist. This doesn't seem to be a problem when using Webpack. (I'm guessing Webpack just moves on to `"main"` when the `"module"` field doesn't work.) However, I was trying to use [Vite](https://github.com/vitejs/vite) (a new dev tool / bundler that uses Rollup for bundling), which failed to load the `"module"` field.

### Proposed solution

~~I think it might be best to simply remove the `"module"` field. It doesn't seem to me like this would break anything; anything that relies on the `"module"` field would already be broken because the file it points to isn't there in the npm distribution. Removing the `"module"` field doesn't seem to have any effect on Webpack, but it does make Vite work (because it seems like Vite will use the `"main"` field as long as the `"module"` field isn't present).~~

~~I would be happy to create a pull request for this.~~ **Update**: I tried submitting a PR (#1937), but the checks failed. So maybe this solution won't work. I'm not sure what the best solution would be. It seems like the problem is that **Webpack relies on the `"module"` field internally during development, but this can cause problems when it's exported to npm as a package for other repos that may use a different bundler**.

### Alternative solution

You could have the `"module"` field actually point to an ES Modules distribution. However, this might be more difficult than it's worth. I thought at first that you could just add the `src` directory to `"files"`, but that doesn't seem to work because the files there aren't regular ESM because they include JSX. Webpack doesn't seem to natively support ESM as an output format, so if you wanted to generate ESM, I guess maybe you would want to just apply Babel on its own without Webpack. 

### What steps can we follow to reproduce the bug?
<https://github.com/Aurelius333/ohif-bug-repro>
```bash
git clone https://github.com/Aurelius333/ohif-bug-repro
yarn
yarn build
```
Error message:
```
vite v1.0.0-rc.3
⠴ Building for production...
[vite] Build errored out.
Error: [vite]: Rollup failed to resolve import "@ohif/viewer" from "src/main.js".
```

But if you manually modify all of the `@ohif/*` packages in `node_modules` to remove the `"module"` fields, then it works.

**Comment by eric-taix** [comment]
@Aurelius333 I know this issue is 2 years old, but did you able to run OHIF with Vite? We are struggling with very low startup time with webpack and we'd like to give a try toVite. 

Is there any special configurations (can you share your `vite.config.ts`?)

**Comment by Aurelius333** [comment]
@eric-taix No, I don't think I was able to get it to work at the time. But Vite has changed and improved a lot since then, so I wouldn't be surprised if it works better now. I don't have the time to try it again, unfortunately.
