### ISSUE TITLE
[IDC] Support reporting of problematic studies - Part 1 - On Screen report

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1939]
- Be able to generate a simple report template you can copy which holds:
  - App and extension versions.
  - Browser fingerprint.
  - The URL of current study.
  - get layout + displayed SeriesInstanceUIDs
  - ~~dump of cornerstone annotations.~~

Post to IDC Discourse
- Be able to automatically post a user defined issues/message to the IDC Discourse.
- Autogenerate screenshots of the application.

**Comment by JamesAPetts** [comment]
@fedorov 

Is the dump of cornerstone annotations still required? Since IDC has disabled all the tools?

**Comment by fedorov** [comment]
I admit I don't know what "dump of cornerstone annotations" is! Does it mean the actual annotations, or extensions supporting creation of annotations?

**Comment by JamesAPetts** [comment]
We talked briefly about logging out what annotations were drawn on the viewports during its use, incase this is something that caused an error. However, I don't think this last part is priority for IDC now that we have disabled all the drawing annotations for IDC?

**Comment by fedorov** [comment]
Yes, I agree.

**Comment by JamesAPetts** [comment]
Gotcha, thanks for the swift reply!
