### ISSUE TITLE
TypeError: studyMetadata.getSeriesByUID is not a function

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#194]
Hi

I got an error at console when view image. But the viewer also works well.

Uncaught (in promise) TypeError: studyMetadata.getSeriesByUID is not a function
    at longitudinalViewportOverlay.js:39
    at meteor.js?hash=cbcc712d51de4298c275e8dcf25c66c29914f19a:1167

Debug:
![image](https://user-images.githubusercontent.com/12405565/39991186-defeb3b2-5798-11e8-9bcd-a937e9f61be0.png)

Does any impact with this error?
Hope anyone know that.
Thank you

**Comment by jacklau88** [comment]
yes,i found the same problem ,maybe this version is not check before checkin.
