### ISSUE TITLE
Orthanc '/pacs' and '/' not accessible while using Keycloak

### ISSUE THREAD

**Issue by reubenwenisch** [OHIF/Viewers#1945]
I followed the documentation and was able to bring up OpenResty-Orthanc-Keycloak using the docker image in .recepies. 

I see the http://127.0.0.1/pacs is not accessible. However, http://127.0.0.1/pacs-admin/* is accessible. What am I doing wrong? Also I tried adding '/' (OHIF viewer) as client however keycloak says client not found when trying to access url. What is the right way to make these visible?

Thanks for the support in advance.

**Comment by dannyrb** [comment]
Unfortunately, I don't believe we have enough bandwidth to assist with this one. If you're able to provide more details, a community member may be able to help. If this is a blocker for you, you could also reach out to a consultant/consultancy.

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
