### ISSUE TITLE
Problem scrolling serie with multiple images using maxConcurrentMetadataRequests

### ISSUE THREAD

**Issue by sylvainb31** [OHIF/Viewers#1946]
Version of the viewer used : [4.2.13](https://github.com/OHIF/Viewers/compare/@ohif/viewer@4.2.12...@ohif/viewer@4.2.13) (2020-07-23)

I decided to use the property maxConcurrentMetadataRequests to improve the first diplay time of the thumbnail images on the left (which really improved the first display time, thanks guys ! ) as I am using a proxy server to get the data, but I encountered a problem : 

If I try to scroll down on a serie to see all its images while the metadatas are still loading, then the serie starts to act like crazy and just scroll on its own up and down.
If I try to scroll or to move the scrolling bar it doesn't change anything, and If i click on an other serie, then it goes automatically back to the faulty serie and it keeps scrolling up and down. 
Once all the metadata requests are done, then I can move the scrollbar and it works normally.

I would expect the image to display a "loading wheel" if trying to access images which metadata has not been loaded yet, or at least not to act like crazy scrolling up and down without stopping.

Configuration used : 

```
window.OHIFViewer.installViewer(
{
                routerBasename: '/Home/OhifViewerAllStudies',
                extensions: [],
                showStudyList: true,
                filterQueryParam: false,
                maxConcurrentMetadataRequests: 1,
                servers: {
                    dicomWeb: [
                      {
                        name: 'DCM4CHEE',
                        wadoUriRoot: '/api/WadoQidoAPI', 
                        qidoRoot: '/api/WadoQidoAPI', 
                        wadoRoot: '/api/WadoQidoAPI', 
                        qidoSupportsIncludeField: true,
                        imageRendering: 'wadors',
                        thumbnailRendering: 'wadors',
                        enableStudyLazyLoad: true,
                      },
                    ],
                }
},
containerId,
componentRenderedOrUpdatedCallback);
```

Thanks for your help !

**Comment by Diex** [comment]
I think 'maxConcurrentMetadataRequests' not even work. same issue here, if the study is huge enough (many series + many instances each), make the viewer useless (until every file is recalled). it's a enormous waste of money (if your using goggle healtcare)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
