### ISSUE TITLE
How do I manipulate dicom data?

### ISSUE THREAD

**Issue by tiancantudousi** [OHIF/Viewers#195]
I am doing the MPR function and want to generate the other two facets of the three-dimensional image, but after changing the image.data.byteArray in image in the Cornerstone.displayimage (image) method, the displayed picture does not change. What can I do to change the display of the Dicom data? For example, I want to change the dicom graph data, display half of the picture in the browser. So where should I change?

**Comment by MuriloSchaefer** [comment]
Hey,
I'm really interested in the MPR function, I need to implement it, but didn't find anything on the internet about the algorithm. Do you have something?

Cheers,

**Comment by tiancantudousi** [comment]
it's not easy to get dicomdata,It took me a month to get the dicomdata, but I didn't get anything.you can find in the ohif-cornerstone/packages/.npm/node_modules/ have four important library.cornerstone-core,cornerstone-tools,dicom-parser,cornerstone-math,those library deal with dicom load,parse,show,cache and so on. It's too hard to understand.My manager gave 3 files to implement the MPR function, and I took the mpr.html file as static resource access.
------------------ 原始邮件 ------------------
发件人: "MuriloSchaefer"<notifications@github.com>;
发送时间: 2018年7月17日(星期二) 晚上8:04
收件人: "OHIF/Viewers"<Viewers@noreply.github.com>;
抄送: "米影"<1329972027@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [OHIF/Viewers] How do I manipulate dicom data? (#195)




Hey,
 I'm really interested in the MPR function, I need to implement it, but didn't find anything on the internet about the algorithm. Do you have something?
 
Cheers,

**Comment by MuriloSchaefer** [comment]
About change an image in the client side, there's a tool in the cornerstone called [DynamicImage](https://rawgit.com/chafey/cornerstone/master/example/dynamicImage/index.html). Should be a good point to start diving into

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now.

**Comment by tiancantudousi** [comment]
I tried to get dicom data,but failed
 
---Original---
