### ISSUE TITLE
Show metadata in ohif viewer

### ISSUE THREAD

**Issue by ambawaleankita** [OHIF/Viewers#1951]
We have Ohif viewer setup
We are using /viewer?url=
Here we have instances array where we have metadata available in the object along with Dicom file location
Is there any utility to show the set of metadata available with a file when that file is being viewed?

**Comment by sedghi** [comment]
You can use our dicom tag browser tool 

![CleanShot 2023-10-12 at 17 01 14](https://github.com/OHIF/Viewers/assets/7490180/e8b5f357-6d1b-4179-bf83-f6acb3b25ada)
