### ISSUE TITLE
"No URL was specified" using iframe

### ISSUE THREAD

**Issue by joweste** [OHIF/Viewers#1963]
Hi, I did a build and I have the dist folder.
I created a iframe as:
```
<iframe
      src="http://localhost:3001/viewer/"
      width="1200"
      height="800"
    ></iframe>

```
But I get an error as:
```
Error: "No URL was specified. Use ?url=$yourURL"
Go back to the Study List

```

How Could I fix it?

**Comment by dannyrb** [comment]
It looks like you may need to configure your viewer to expect being loaded at a non-root URL. What does your OHIF Viewer configuration look like?
