### ISSUE TITLE
production build not working on ubuntu 18.04 server 

### ISSUE THREAD

**Issue by dpyadav340** [OHIF/Viewers#1971]
The app is properly working on development mode.
When we deploy build on a production server then files are showing from DCOM server only. JSON file and local files not working. Its showing page not found. Please suggests setup up of configuration file on the production server.

**Comment by web2ls** [comment]
try test your production build on local environment for getting more information

for example:

- build project
- use http-server (npm package) inside dist folder for up and running local http server
- go to localhost:8080 and test application

**Comment by dpyadav340** [comment]
Thank you for your reply.
As per your suggestion, I have made the changes I am getting the following error.

![Screenshot from 2020-08-08 12-25-47](https://user-images.githubusercontent.com/33520419/89704672-94415f00-d973-11ea-823e-f78745112d60.png)
![Screenshot from 2020-08-08 12-25-54](https://user-images.githubusercontent.com/33520419/89704673-95728c00-d973-11ea-841c-c086f0bca872.png)

**Comment by web2ls** [comment]
It is a same error that you get on the server?
Did you actually add new route /local to application?

**Comment by dpyadav340** [comment]
Yes, I have got the same error also on the server and I haven't added route /local to the application.

I want the same features after the execution of the "yarn run build" command whose gets on the execution of "yarn run dev".
Please help me with the suitable configurations to resolve this issue, Thanks for your valuable response.

**Comment by dannyrb** [comment]
This is a SPA redirect issue. Because the app is a "single page application", you need to redirect all routes to `index.html` that would otherwise result in a 404.
