### ISSUE TITLE
Why no data

### ISSUE THREAD

**Issue by ruanwenfeng** [OHIF/Viewers#198]
Website can run correctly.However, data cannot be displayed.

![capture](https://user-images.githubusercontent.com/27943586/40427346-0001d04c-5ed0-11e8-9d70-206bb4bb3bb4.PNG)

**Comment by radicalrob** [comment]
You need to include more information before anyone can help.  What back-end are you connecting to (orthanc, dcm4chee, etc), do you know there are studies in it, have you chosen an appropriate study date range in the UI?  Are there errors on the console, etc.
