### ISSUE TITLE
WSI Images not displayed, CT working

### ISSUE THREAD

**Issue by mrcolo** [OHIF/Viewers#1980]
I'm currently experiencing an issue related to rendering WSI on OHIF/Viewer. Attached is a log of my results. 
I am querying from a remote orthanc server I set up on EC2, which has CORS and hosted on nginx. 

I keep getting this AssertionError, which seems to be related to the way I export the wsi to dicom, since normal .dcm files are able to visualized..

![image](https://user-images.githubusercontent.com/12208440/89690457-639dee80-d8bb-11ea-9d2d-e1ae59cab09c.png)

**Comment by pieper** [comment]
Do you have dicom-microscopy enabled?

https://github.com/OHIF/Viewers/tree/master/extensions/dicom-microscopy

It should work like this example: https://viewer.ohif.org/viewer/1.2.392.200140.2.1.1.1.2.799008771.2448.1519719572.518
