### ISSUE TITLE
MPR View -Measurement 

### ISSUE THREAD

**Issue by cfirdous** [OHIF/Viewers#1982]
## Request

**What feature or change would you like to see made?**
Option to take measurement in 2D MPR View

**Why should we prioritize this feature?**
I had shown OHIF to few Radiologists and as per them one the feature OHIF missing is ability to take measurements when they open viewer in 2D MPR mode . We have the option to take measurement in regular mode .

...

**Comment by cfirdous** [comment]
@dannyrb , is there any plans to implement this feature ?

**Comment by dannyrb** [comment]
Development has slowed on OHIF until we can pick up a new grant or additional funding sources. While a feature like this would be welcomed, I'm uncertain of when/if it will be completed by the core team. FWIW, the 2D MPR uses VTK.js, which has _some_ support for annotations.

If we tackled this, I'm not certain if we would use their existing framework for placing annotations, or if we would explore a different approach.

If this functionality is critical for you, you may need to explore developing it yourself, or try reaching out to an OHIF consultant.

**Comment by cfirdous** [comment]
@dannyrb , Can you recommend some resource to better understand medical terminologies used in inside OHIF code ? Is there any book or document a developer can read to improve his skill levels to better understand the terms used inside OHIF viewer

**Comment by dannyrb** [comment]
@cfirdous, that's a great question. I've only been in this field for ~4 or so years. There are a lot of terms, and I've slowly picked them up by playing around with these libraries and liberally Googling as I encounter new terms.

For the very basics, this blog series provides a good simplified overview:

- http://dicomiseasy.blogspot.com/2011/10/introduction-to-dicom-chapter-1.html

And while a little dry, and with examples in MATLab, I was recommended and found the book "Applied Medical Image Processing" by Birkellher helpful.

This DICOM Tag browsing tool can be helpful for looking up specific information for a given DICOM tag:

- https://dicom.innolitics.com/ciods

This resource provides an okay overview of endpoints exposed by an API that implements DICOMWeb:

- https://www.dicomstandard.org/dicomweb

Chris Hafey also has good LinkedIn and personal blog posts that delve into image decoding.

If there are specific terms you're struggling with, feel free to ask. As developers rarely have the entirety of this domain in their head, it may be worth maintaining documentation that helps solidify key terms and concepts that are important to understanding this application and the problems it seeks to solve.

**Comment by cfirdous** [comment]
Thanks a lot @dannyrb . I will explore those documents  . Hopefully we will be able to contribute to OHIF in near future
