### ISSUE TITLE
404 handling in MPR and other modes

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#1986]
### Describe the Bug

It's currently possible for the app to hang or present a black screen when a request gives 404 or otherwise fails.

### What steps can we follow to reproduce the bug?

MPR mode makes many frame requests and the server may not be able to handle them.

I was able to get this behavior by opening several tabs with different studies and entering 2D MPR mode on each one.  Eventually the IDC throttle proxy stopped responding and I got a black screen on one of the tabs.

I also went into MPR mode on Kheops with a CT and the view hung at 4% with the console full of 404 messages.

### Suggested behavior

It would be best to report back to the user that there is trouble communicating with the server, perhaps suggesting that they reload and/or try again later.

**Comment by pieper** [comment]
Related to #1957, which is about avoiding too many requests, but this one is about graceful handling of failures that might happen anyway.

**Comment by pieper** [comment]
@JamesAPetts we can discuss on Thursday with @fedorov.   Probably this means adding some UI to report errors from the request pool.

**Comment by JamesAPetts** [comment]
Soungs good, yeah #1957 should help somewhat, but yeah a clean path for error handling without breaking the app in MPR would be nice. Look forward to discussing.
