### ISSUE TITLE
Intercept click on viewport before it adds a measurement

### ISSUE THREAD

**Issue by sinanmb** [OHIF/Viewers#1987]
Hi,

I'm trying to intercept the click event on the viewport before it draws the measurement on the viewport, in order to modify the behavior. I would like the first click on an unselected viewport to just select the viewport, and subsequent clicks to add measurements. I have not been able to find the event listener for the viewport click. Can someone please point me in the right direction?

**Comment by dannyrb** [comment]
@sinanmb, the feature you're requesting was recently added to our "feat/v2-main" branch. I'm not sure when it will be released, but that would be a good place to head to sneak a peak at the implementation:

https://github.com/OHIF/Viewers/tree/feat/v2-main

**Comment by sinanmb** [comment]
That's great news. Thank you Danny!
