### ISSUE TITLE
Overlaying the active cornerstone viewport with an image

### ISSUE THREAD

**Issue by anishsaha12** [OHIF/Viewers#1989]
Hello! :hand:

I'm trying to draw an image on the cornerstone viewport, as an overlay (A _heatmap_ generated using **AI** retrieved from an external server).
_(On an unrelated note, this is for analyzing chest X-rays and displaying the heatmaps, for **COVID-19**)_

I've achieved it by doing the following:

_Creating a reference to the viewport's canvas:_
```
let element = cornerstone.getEnabledElements()[0].element
let canvas = element.children[0]
let ctx = canvas.getContext('2d')
```
_Preparing the image:_
```
var img = new Image();
img.src = "http://myserver.com/images/instance_id_heatmap.png";  // url to image generated by AI in my server
```
_Drawing the image in the canvas, over the DICOM image:_
```
ctx.drawImage(img,0,0);
```

**Problems**
1. Although I mention it as an overlay, it's not actually one. The image is just getting drawn over the existing image.
2. **Major Problem:** Using the current approach the drawn image just **gets erased** whenever the viewport is updated (for example: when I change the level, or zoom, or pan)

So, I believe this is **not** the right way to draw an overlay.
Also, its not even a temporary solution for my requirement as the image just gets erased.

Can someone please point me in the right direction?

**Comment by PattersonOfficial** [comment]
Where you able to get it figured out? @anishsaha12

**Comment by juaesto** [comment]
Are there any advance in this topic? I have the same problem that has [anishsaha12](https://github.com/anishsaha12)
