### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by davidi1** [OHIF/Viewers#199]
Hello, I believe I found an issue with the "docker-compose.yml" file. Currently, under the Volumes section is:

**volumes:
      - /opt/docker/ohif-viewer/app.json:/app/app.json**

But, this does not work. I had to modify the Volumes section to:

**volumes:
     - /home/owner/Viewers/dockersupport/app.json:/app/app.json**

In order to get it to work properly. Otherwise there were build errors. Just wanted to bring it to someone's attention :-) For anyone else who reads this, please make sure the directory where you have the Viewers/dockersupport folder is correct. I put mine in my Home directory. YMMV.

**Comment by davidi1** [comment]
You're welcome :-) Speaking of Docker, how often will the Docker image itself be updated with the newest fixes/commits from the Master branch? I see that is has not been updated since it was first introduced...

**Comment by swederik** [comment]
Hi @davidi1 

Yes that is the goal, but we haven't set up the auto-build and updating yet.

**Comment by davidi1** [comment]
Awesome, thanks for letting me know. I'm looking forward to that because it is so much easier to work with the Docker image.
