### ISSUE TITLE
Load Study in Embedded Viewer

### ISSUE THREAD

**Issue by ambawaleankita** [OHIF/Viewers#1995]
Hi Guys, 

We have used the embedded viewer for our application, It's loading the study list table and on click of a specific study it is getting loaded in OHIF Viewer. We want to load the specific study in OHIF Viewer on load. Can we directly load the study without showing the study list table? If Yes where we can configure that for the embedded viewer?

**Comment by andredublin** [comment]
@ambawaleankita see https://github.com/OHIF/Viewers/issues/1909#issuecomment-668724477 on how to skip the study list and go straight to a study.

**Comment by sylvainb31** [comment]
Hello @ambawaleankita ,

Calling the viewer by suffixing the url with viewer/{studyUid} directly loads directly the wanted study.

For example, here is my viewer config :

```
window.OHIFViewer.installViewer(
            {
                routerBasename: '/Home/Viewer',
                extensions: [],
                showStudyList: true,
                filterQueryParam: false,
                maxConcurrentMetadataRequests: 1,
                servers: {
                    dicomWeb: [
                        {
                            name: 'DCM4CHEE',
                            wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado', 
                            qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs', 
                            wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs', 
                            qidoSupportsIncludeField: true,
                            imageRendering: 'wadors', /* wadors / wadouri : https://github.com/OHIF/Viewers/issues/1338 et https://github.com/OHIF/Viewers/issues/482 */
                            thumbnailRendering: 'wadors', /* wadors / wadouri */
                            enableStudyLazyLoad: true,
                        },
                    ],
                }
            },
            containerId,
            componentRenderedOrUpdatedCallback
        );
```

So to access directly a study without showing the study list, I have to call : 

https://localhost:44345/Home/Viewer/viewer/{studyUid}

**Comment by mokbelt** [comment]
Dears,
I tried your above approach to load the studyuid directly without passing by the study list, it is giving "page not found"...
Shall I make other configuration to make it work?

Thanks!

**Comment by matthiasg** [comment]
@sylvainb31 it worked sometimes for us, but not all the times. Sometimes we got the "page not found, go to study list" error.

**Comment by anarnoli** [comment]
@ambawaleankita Did you find any solution on it? 

@sylvainb31 I tried your approach but no luck. I have created a [sample](https://stackblitz.com/edit/dicom-ohif-viewer-file-upload) in which I am trying to embed viewer inside Angular app - can you help on this?

**Comment by sedghi** [comment]
In version 3 we have moved away from embedded viewer 

In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
