### ISSUE TITLE
Can't start PACS locally.

### ISSUE THREAD

**Issue by JonathanGilyadov** [OHIF/Viewers#1996]
Hey,

I am trying to fork the viewer and start it locally,although I tried to run `yarn install` and this was the output:
`
yarn install v1.22.4
$ yarn lerna:restore
yarn run v1.22.4
$ [ $NETLIFY_RESTORE = 1 ] && ./netlify-lerna-restore.sh || :
'[' is not recognized as an internal or external command,
operable program or batch file.
':' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`
Please any help would be highly appreciated.

**Comment by swederik** [comment]
Can you try now? This should be fixed

**Comment by JonathanGilyadov** [comment]
Yeah, it is fixed!

Thank you!
