### ISSUE TITLE
View Today's Results by Default

### ISSUE THREAD

**Issue by davidi1** [OHIF/Viewers#200]
Hello.

This is technically not an issue, but more of a "let me try to help others" type of a post :-) Mods, feel free to move this where it should go because I am honestly not sure where i should post this. I just want to pass this along to anyone else who might find it useful.

If you're using Orthanc like I am, you will more than likely notice that this Viewer takes forever to display results because it is trying to load the whole Orthanc database. I found a good workaround that displays Today's Date only and it requires very little editing. This is split in two methods, one for the Docker Image and the other one is if you're compiling the Viewer yourself.

For Docker Installs:
1.  Go to Viewers/dockersupport/ folder.
2. Modify the app.json file to include the following line:

**"ui": {
        "studyListDateFilterNumDays":1**

I put the above line right after where it starts with public. So now, that part in my app.json file now looks like this:

**"public": {
                        "ui": {
                            "studyListDateFilterNumDays":1
                        },
                  },
                  "proxy": {
                    "enabled": true
                  }
                }
    }
  }]
}**

3. That's it. Build the Docker image using docker-compose and you're ready to go. Please make sure the syntax and spacing are correct. It is not letting me paste it correctly here :-)

Building the Viewer yourself:
1. Go to Viewers/config.
2. Open the server config file that you want to use in your favorite editor. I used "orthancDIMSE.json".
3. In the "UI" section of the config file, add the following line and then save it:

**"studyListDateFilterNumDays":1**

My "orthancDIMSE.json" UI section now looks like this:

**"ui": {
        "studyListFunctionsEnabled": true,
        "leftSidebarOpen": false,
        "displaySetNavigationLoopOverSeries": false,
        "displaySetNavigationMultipleViewports": true,
        "autoPositionMeasurementsTextCallOuts": "TRLB",
        "studyListDateFilterNumDays":1**

4. Compile and then run the Viewer.

I really hope this helps someone :-)

**Comment by swederik** [comment]
This is a good point. We should update the default configuration to use this filter.

**Comment by davidi1** [comment]
This is awesome! Thank you!

**Comment by blezek** [comment]
Hi, I have tho opposite problem of @davidi1, my OHIF viewer is for some demo data that can be quite old, I'd like to query all studies by default.  @swederik, is there a way to do this using the config file?
