### ISSUE TITLE
Incorrect orientation for displayed SEG overlay

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2003]
### Describe the Bug

We have an inconsistency in displaying segmentation for T1 for this study (and for all segmentations in LGG/GBM collections) between Slicer and OHIF.

![image](https://user-images.githubusercontent.com/313942/90934035-9b825700-e3ce-11ea-817a-dd85e574f795.png)

### What steps can we follow to reproduce the bug?

It appears that all of the segmentations from the TCGA-GBM and TCGA-LGG collections are affected. A URL to the specific study is available in [this slack thread](https://cornerstonejs.slack.com/archives/GP0DDMVMF/p1598033636002400). All of the segmentations in that cohort were created by [dcmqi](https://github.com/QIICR/dcmqi) being converted from NIfTI, and were round-trip verified.

Notably, orientation of the SEG is different than MR for all those cases. It was observed that overlay is wrong in MPR as well. 

Quoting @pieper:
> I'm thinking now that it would make sense for the vtk view to be wrong if it got the image orientation vectors from cornerstone rather than getting them directly from dicom.

**Comment by VusionTechCo** [comment]
Does the NIFTI file have a correct coordination? If you converted DICOM to NIFTI using dcm2nii.exe tool, usually it messed up the coordinates.

**Comment by fedorov** [comment]
I updated the title of the issue, since it's been confirmed to be an OHIF issue.

**Comment by fedorov** [comment]
Here's the URL for a study that contains the data illustrating the issue: https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.3344.2526.782575807786219948893598067532

SEG is listed on the left, but when selecting segmentation on the right panel, it says there are 0 segments, which is not the case - I downloaded the study and confirmed that it does include segments.

**Comment by fedorov** [comment]
Correction - this is the study in question: https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc-tcia/dicomStores/idc-tcia/study/1.3.6.1.4.1.14519.5.2.1.4591.4003.241850919885310339695393380617

The one referenced above is for the 1p19q_deletion collection, which in fact was rendering correctly in OHIF at the time I was testing it before submitting to TCIA, so it might be a different issue in OHIF.

**Comment by fedorov** [comment]
As mentioned in https://github.com/ImagingDataCommons/Viewers/pull/8#issuecomment-705170119, this is not resolved.

**Comment by JamesAPetts** [comment]
[Fix here](https://github.com/ImagingDataCommons/Viewers/pull/9).

[Explanation here](https://github.com/ImagingDataCommons/Viewers/pull/8#issuecomment-705433576)

**Comment by JamesAPetts** [comment]
Feel free to reopen if there are still issues.

**Comment by fedorov** [comment]
This issue seems to be back. The example above in https://github.com/OHIF/Viewers/issues/2003#issuecomment-703838778.

**Comment by pieper** [comment]
What's the issue exactly?  For me trying to load the segmentation leads to a message that the case is not supported.

**Comment by fedorov** [comment]
I may be missing something, but my recollection and interpretation of the thread above in this issue is that this has been resolved, and those segmentation were working fine in OHIF at the time the issue was closed. So the issue exactly is the apparent regression in functionality to show the segmentation in the examples referenced in the issue.

**Comment by pieper** [comment]
I had thought that detecting and reporting the incompatible data was the fix (as opposed to failing silently or crashing).  I don't think there's any way to show out-of-plane segmentations on current cornerstone.  Once cornerstone3D is available it might work.

**Comment by fedorov** [comment]
I had that thought too, but the conversation and screenshots here imply (to me, anyway) that it was fixed by making it work: https://github.com/ImagingDataCommons/Viewers/pull/8#issuecomment-705433576.

Is it supposed to work in MRP? It doesn't for me either.

It doesn't even show the corresponding segmentations in the list: 
![image](https://user-images.githubusercontent.com/313942/134582592-3bec228c-9b2e-4102-b1b1-9185e5a6f002.png)

@JamesAPetts can you comment?

**Comment by fedorov** [comment]
Also, to clarify, I do not think this is an out-of-plane segmentation - if I remember correctly, it is something like LR vs RL. I recall we had a longer discussion about this, but it might have happened on Slack.

**Comment by pieper** [comment]
Yes, I see.  I think you are right it did work once but now it thinks they are out of plane.  Yes, maybe @JamesAPetts or @igoroctaviano knows what might have changed.

**Comment by fedorov** [comment]
@piiq owns the credit for detecting this regression as part of the work on TCGA-GBM/LGG project.

**Comment by Punzo** [comment]
this https://github.com/dcmjs-org/dcmjs/pull/220 fix the regression.
