### ISSUE TITLE
retrieve series UID from study

### ISSUE THREAD

**Issue by screeeen** [OHIF/Viewers#2008]
> :hand:hello,

at ohif core - 
Is there a function to retrieve the very first series and display them asap instead of retrieveStudyMetadata and wait for all the series?

**Comment by swederik** [comment]
I think you're looking for this:

https://github.com/OHIF/Viewers/blob/2093a0036584b2cc698c8f06fe62b334523b1029/platform/viewer/public/config/demo.js#L15

**Comment by screeeen** [comment]
Thank you. 
I found what I was looking for:
It is within the dicom tag: 0020000E
`      SeriesInstanceUID: DICOMWeb.getString(series['0020000E']),
      SeriesNumber: DICOMWeb.getNumber(series['00200011'], 0) || 0,`
