### ISSUE TITLE
How do I access the current SOP Instance UID

### ISSUE THREAD

**Issue by FirasGit** [OHIF/Viewers#2012]
Hey,
I'm trying to create a panel through which I can choose an algorithm that is applied to the currently shown instance. However, in order to specify the currently shown instance, I need access to the current SOP Instance UID. Is there any way I can get access to this UID inside my extension code?
Any help would be highly appreciated. :)

**Comment by web2ls** [comment]
i don't sure that it is wright way but in extension event listener you can get imageId via event.detail.image.imageId which contain instanceUid

**Comment by sedghi** [comment]
Hmmm
You need to access the viewport then get the currenImageId, and there you have the SOP
