### ISSUE TITLE
Embedded Viewer recipe in CodeSandbox not working

### ISSUE THREAD

**Issue by juliejsanchez** [OHIF/Viewers#2014]
### Describe the Bug

Embedded viewer recipe example in CodeSandbox is not working or displaying the OHIF viewer. The link to the deployed app found in the CodeSandbox did not work also. It shows the study list for a split second then disappears.

### What steps can we follow to reproduce the bug?

1. Visit [CodeSandbox](https://codesandbox.io/s/viewer-script-tag-tprch) and refresh app in `Browser`
2. Visit [https://tprch.csb.app/](https://tprch.csb.app/). Got this issue in the `Console`

```js
Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute
Because a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests
```
![image](https://user-images.githubusercontent.com/52226499/91299084-ac1e3d00-e7d3-11ea-9591-1dfdb9179b99.png)

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by kaveh-qritive** [comment]
Any help would be greatly appreciated!

**Comment by web2ls** [comment]
silently everything worked

**Comment by sedghi** [comment]
In latest version we have moved away from that approach to iframe

In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
