### ISSUE TITLE
Angular 8 - VTK Extension is not working  

### ISSUE THREAD

**Issue by ashrefmab** [OHIF/Viewers#2018]
### Describe the Bug
We successfully integrate the OHIF viewer into the angular view but when we try to view the MPR 2D from VTK, this option is not displayed in the toolbar.
 please find below the extract of code
### What steps can we follow to reproduce the bug?
1. Imports 
import { installViewer } from '@ohif/viewer';
import  {OHIFExtCornerstone}  from '@ohif/extension-cornerstone';
import {OHIFExtDicomHtml} from '@ohif/extension-dicom-html';
import {OHIFExtDicomPdf} from '@ohif/extension-dicom-pdf'
import {OHIFExtVtk} from '@ohif/extension-vtk';
import {OHIFExtDicomMicroscopy} from '@ohif/extension-dicom-microscopy';

2. Configurations 
containerId = "root";
  configuration={
    routerBasename: '/',
    servers: {
      dicomWeb: [
        {
          name: 'DCM4CHEE',
          qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
          wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
          qidoSupportsIncludeField: true,
          imageRendering: 'wadors',
          thumbnailRendering: 'wadors',
        },
      ],
    },
    extensions: [OHIFVTKExtention],
    whiteLabelling: {}
//          extensions:[OHIFExtVtk]
  };

3.  rendering the viewer 
componentDidMount() {
    installViewer(
      this.configuration,
       this.containerId,
       this.componentRenderedOrUpdatedCallback
     );
   }
public ngAfterViewInit() {
    this.hasViewLoaded = true;
   this.componentDidMount();
    
  }

The extensions are not loaded into the viewer and the MPR2D is not shown in the toolbar.

please find enclosed the screenshot.

![ohif-extension-vtk-issue](https://user-images.githubusercontent.com/70404586/91602326-11ecff00-e963-11ea-9351-57af245ac2ce.PNG)

**Comment by nicoesiea** [comment]
Hello,
How did you solve this missing tool?

**Comment by sedghi** [comment]
We have moved away from VTK plugin to Cornerstone3D. 

Try again on latest master and re-open this if necessary
