### ISSUE TITLE
Measurement error (pixel resolution) for US (PhysicalDeltaX & PhysicalDeltaY (0018,602c),(0018,602e))

### ISSUE THREAD

**Issue by rossetantoine** [OHIF/Viewers#202]
The measurements produced by OHIF are wrong, if pixel resolution is stored in PhysicalDeltaX & PhysicalDeltaY fields (SequenceOfUltrasoundRegions)).

See attached image and DICOM file: the diameter should be 20 mm, instead of 60 mm.

The DICOM file is attached.

If these US regions are not supported, it should be better to display pixels, instead of wrong mm.

<img width="1070" alt="screen shot" src="https://user-images.githubusercontent.com/1857100/41190102-ec2063fc-6bd8-11e8-9704-bf534cf52f55.png">

[8330.dcm.zip](https://github.com/OHIF/Viewers/files/2086818/8330.dcm.zip)

**Comment by swederik** [comment]
Thanks for the report! We will definitely fix that.

**Comment by dannyrb** [comment]
I believe we've defaulted to `px` in this instance. If you would like to see support for US PhysicalDeltaX & PhysicalDeltaY, it may be worth creating a new issue in the `cornerstoneWADOImageLoader` repository. I have seen these accounted for before, so I know an implementation is possible.
