### ISSUE TITLE
About box reports incorrect version number

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2023]
### Describe the Bug

The about box has contradictory information.  As shown below, the version number is old but this should be a build of the current master branch.

![image](https://user-images.githubusercontent.com/126077/91900388-9e056c00-ec6c-11ea-8c08-b8afac6a1976.png)

### What steps can we follow to reproduce the bug?

Open viewer.ohif.org (or other build) and go to Options->About.

My guess is that the version is based on when the build directory was first initialized and doesn't get updated on new builds.

**Comment by fedorov** [comment]
Discussed and agreed to query idcGitVersion.txt that is available on IDC deployment and show that in About. This will be done in fork, so @pieper will create an issue under fork to do this?

**Comment by pieper** [comment]
After a quick look at the webpack configuration for OHIF I think I'm not the best person to do this, or at least it would take me longer.

I believe all we need to do is add this plugin: https://www.npmjs.com/package/git-revision-webpack-plugin

and then make sure it is available to use in the dialogs.  I think this would be valuable for any ohif deployment.

@JamesAPetts or @dannyrb could you help?

**Comment by pieper** [comment]
Mailto tag is fixed.

About box is more tricky and I'm seeing what the OHIF team can suggest.

**Comment by fedorov** [comment]
From earlier conversation with @dannyrb:

![image](https://user-images.githubusercontent.com/313942/101032167-d0628600-3547-11eb-9591-d93952bb5d76.png)

**Comment by dannyrb** [comment]
Oof. Not a great comment for me to make before a long stint of vacation. Blocking off some time today to whip up a quick something.

**Comment by fedorov** [comment]
Thanks @dannyrb! The intent was not to put you on the spot, but to pull together all the pieces of information related to this issue. We would most definitely appreciate your help though!

**Comment by fedorov** [comment]
I have to admit I am not sure what is the best way to test this!

**Comment by igoroctaviano** [comment]
> I have to admit I am not sure what is the best way to test this!

1. build the viewer (generate dist)
2. Update version
3. build the viewer again (should update the last dist)
4. check the version if its updated (before the version wasn't being updated)

 the version was based on when the build directory was first initialized and doesn't get updated on new builds

**Comment by fedorov** [comment]
This was deployed to IDC production, and versions reported appear to be accurate.
