### ISSUE TITLE
IDC - MVP fork update.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#2037]
Once all of the current IDC tasks in priority are completed:

- Update the current IDC fork.
- Add example config for removing measurement panel.
- Add example config for splitting up multiple query parameters into multiple calls.
- Add DICOMTagBrowser extension to IDC fork.
- Add debug extension to IDC fork and configure its mail:to correctly.

**Comment by pieper** [comment]
When @JamesAPetts says this is done, we can update https://github.com/ImagingDataCommons/Viewers and also make pull request for app-config template https://github.com/ImagingDataCommons/IDC-Viewer-Support

**Comment by JamesAPetts** [comment]
Disabling measurments panel:
`disableMeasurementPanel: true,`


Splitting query parameters calls if you aren't using the google cloud adapter (e.g. IDC's proxy):
`splitQueryParameterCalls: true,`

I shall add the mailTo straight into the extension config in the fork.

**Comment by JamesAPetts** [comment]
> and also make pull request for app-config template
https://github.com/ImagingDataCommons/IDC-Viewer-Support/pull/5
