### ISSUE TITLE
Multiple Study Instance UID 

### ISSUE THREAD

**Issue by esefberfu** [OHIF/Viewers#2042]
> **Before Creating an issue**
>
> - Are you running the latest version? Yes
> - Are you reporting to the correct repository? Yes
> - Did you search existing issues? Yes

## Bug Report
Multiple Study Instance UID 

### Describe the Bug
http://localhost:3000/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170125112931.11;1.2.392.200140.2.1.1.1.2.799008771.2448.1519719572.518

Two or more study instance uids merged with ";" characters in above url. But ohif viewer gives error like "isDerived' of undefined". 

_A clear and concise description of what the bug is._

### What steps can we follow to reproduce the bug?

1. First step
Start ohif viewer
2. Second step
Merge multiple study instance uid with ";" character.
3. ...
enter to the url params like /viewer/:IDs

```js
ViewerMain: Cannot read property 'isDerived' of undefined
    in ViewerMain (created by ConnectFunction)
    in ConnectFunction (created by Viewer)
    in ErrorBoundary (created by OHIFErrorBoundary)
    in OHIFErrorBoundary (created by ErrorBoundaryDialog)
    in ErrorBoundaryDialog (created by Viewer)
    in div (created by Viewer)
    in div (created by Viewer)
    in Viewer (created by WrappedComponent)
    in WrappedComponent (created by ConnectFunction)
    in ConnectFunction (created by ViewerRetrieveStudyData)
    in ViewerRetrieveStudyData (created by ConnectFunction)
    in ConnectFunction (created by ViewerRouting)
    in ViewerRouting (created by AsyncComponent)
    in AsyncComponent (created by Context.Consumer)
    in ErrorBoundary (created by OHIFErrorBoundary)
    in OHIFErrorBoundary (created by Context.Consumer)
    in Transition (created by CSSTransition)
    in CSSTransition (created by Context.Consumer)
    in Route (created by OHIFStandaloneViewer)
    in OHIFStandaloneViewer (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(OHIFStandaloneViewer)) (created by Component)
    in Unknown (created by Component)
    in Component (created by App)
    in ModalProvider (created by App)
    in DialogProvider (created by App)
    in SnackbarProvider (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in I18nextProvider (created by App)
    in AppProvider (created by App)
    in Provider (created by App)
    in ErrorBoundary (created by OHIFErrorBoundary)
    in OHIFErrorBoundary (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by myousefipour** [comment]
This problem occurs when the output of this function (findDisplaySet in ViewerMain.js) is undefined,
For my case, the displaySetInstanceUid value for the last series was changed at runtime,

`<html>
<body>


const { displaySets } = this.state;
--
  |   |   |   |   |   |   |  
  |   |   | return study.displaySets.find(displaySet => { |   |   |   | return (
  |   |   | return displaySet.displaySetInstanceUID === displaySetInstanceUID; |   |   |   | study.displaySets.find(displaySet => {
  |   |   | }); |   |   |   | return displaySet.displaySetInstanceUID === displaySetInstanceUID;
  |   |   |   |   |   |   | }) \|\| displaySets[0]
  |   |   |   |   |   |   | );


</body>
</html>`

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

Please refer to the URL configuration documentation page at https://docs.ohif.org/configuration/url.
