### ISSUE TITLE
DICOM tag viewer does not sort entries for SEG

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2049]
It appears that entries for SEG are not sorted

![image](https://user-images.githubusercontent.com/313942/93645104-53f0ea00-f9d1-11ea-8ffc-25a7663c39ab.png)

I thought this is because of the presence of sequences, but they seem to be sorted for SRs...

**Comment by pieper** [comment]
Can you clarify what part is not sorted?  At a glance it seems that the tags are sorted by group and then element within each nesting level.  Or do I miss something?

**Comment by fedorov** [comment]
Well, maybe they are indeed sorted, but I don't know the sort order is. It is not obvious to me.

Here's where group 0002 is in SEG tag lilst:

![image](https://user-images.githubusercontent.com/313942/93645727-b4345b80-f9d2-11ea-81da-83b2f17a9553.png)

And for the CT instance is it at the very top (consistent with other tag viewers):

![image](https://user-images.githubusercontent.com/313942/93645755-c3b3a480-f9d2-11ea-904d-bbe097b01b9c.png)

**Comment by pieper** [comment]
I can't tell from your seg screenshot what's above the sequence.  Is it group 0000?

**Comment by fedorov** [comment]
it is group 5200

![image](https://user-images.githubusercontent.com/313942/93646394-1fcaf880-f9d4-11ea-8a13-2aa98d680e06.png)

**Comment by pieper** [comment]
Okay, yes, that's clearly incorrect.

**Comment by JamesAPetts** [comment]
Interesting.

I'm actually just iterating through the props, which for the most part are adding in the right order, which seemed largely fine. But the way we compose SEGs mean we add tags in different times. All groups will be fine, so I think we just need to sort the top level.

**Comment by fedorov** [comment]
Nitpick: can you also add a space between ">" and "("?

**Comment by fedorov** [comment]
I am not going to try to trace back the version of the viewer used in IDC to this one, but I see that this issue was fixed ~20 days ago, so I am going to take an educated guess it is in IDC. If that guess is accurate, the issue has not been fixed:

![image](https://user-images.githubusercontent.com/313942/95873542-051f4180-0d3e-11eb-9b6b-e9c4aaa96dbe.png)

**Comment by JamesAPetts** [comment]
After some discussion on slack it seems this is either fixed, or we have issues on certain SEGs.

@fedorov will check if he can reproduce.

**Comment by fedorov** [comment]
Can't reproduce it, must have been fixed! 👍
