### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by tongwensen** [OHIF/Viewers#2057]
=> A patch (Meteor 1.7.0.5) for your current release is available!
   Update this project now with 'meteor update --patch'.
Started MongoDB.
Errors prevented startup:

While downloading aldeed:collection2@2.10.0...:
error: certificate has expired

While downloading aldeed:collection2-core@1.2.0...:
error: certificate has expired

While downloading aldeed:schema-deny@1.1.0...:
error: certificate has expired

While downloading aldeed:schema-index@1.1.1...:
error: certificate has expired

While downloading aldeed:simple-schema@1.5.4...:
error: certificate has expired

While downloading aldeed:template-extension@4.1.0...:
error: certificate has expired

While downloading amplify@1.0.0...:
error: certificate has expired

While downloading autoupdate@1.4.1...:
error: certificate has expired

While downloading blaze@2.3.2...:
error: certificate has expired

While downloading blaze-html-templates@1.1.2...:
error: certificate has expired

While downloading blaze-tools@1.0.10...:
error: certificate has expired

While downloading caching-html-compiler@1.1.3...:
error: certificate has expired

While downloading clinical:router@2.0.19...:
error: certificate has expired

While downloading clinical:router-location@2.1.0...:
error: certificate has expired

While downloading clinical:router-middleware-stack@2.1.2...:
error: certificate has expired

While downloading clinical:router-url@2.1.0...:
error: certificate has expired

While downloading cultofcoders:persistent-session@0.4.5...:
error: certificate has expired

While downloading ddp-client@2.3.3...:
error: certificate has expired

While downloading dynamic-import@0.4.1...:
error: certificate has expired

While downloading fastclick@1.0.13...:
error: certificate has expired

While downloading fortawesome:fontawesome@4.7.0...:
error: certificate has expired

While downloading html-tools@1.0.11...:
error: certificate has expired

While downloading htmljs@1.0.11...:
error: certificate has expired

While downloading iron:controller@1.0.12...:
error: certificate has expired

While downloading iron:core@1.0.11...:
error: certificate has expired

While downloading iron:dynamic-template@1.0.12...:
error: certificate has expired

While downloading iron:layout@1.0.12...:
error: certificate has expired

While downloading johdirr:meteor-git-rev@0.0.4...:
error: certificate has expired

While downloading jquery@1.11.11...:
error: certificate has expired

While downloading lmieulet:meteor-coverage@1.1.4...:
error: certificate has expired

While downloading mdg:validation-error@0.5.1...:
error: certificate has expired

While downloading meteor@1.9.2...:
error: certificate has expired

While downloading meteor-platform@1.2.6...:
error: certificate has expired

While downloading meteorhacks:picker@1.0.3...:
error: certificate has expired

While downloading meteortesting:browser-tests@1.0.0...:
error: certificate has expired

While downloading meteortesting:mocha@1.0.0...:
error: certificate has expired

While downloading modern-browsers@0.1.2...:
error: certificate has expired

While downloading modules@0.12.2...:
error: certificate has expired

While downloading modules-runtime@0.10.2...:
error: certificate has expired

While downloading momentjs:moment@2.22.2...:
error: certificate has expired

While downloading mongo@1.5.1...:
error: certificate has expired

While downloading natestrauser:select2@4.0.3...:
error: certificate has expired

While downloading practicalmeteor:mocha-core@1.0.1...:
error: certificate has expired

While downloading raix:eventemitter@0.1.3...:
error: certificate has expired

While downloading silentcicero:jszip@0.0.4...:
error: certificate has expired

While downloading socket-stream-client@0.2.2...:
error: certificate has expired

While downloading spacebars@1.0.15...:
error: certificate has expired

While downloading spacebars-compiler@1.1.3...:
error: certificate has expired

While downloading standard-app-packages@1.0.9...:
error: certificate has expired

While downloading stylus@2.513.14...:
error: certificate has expired

While downloading templating@1.3.2...:
error: certificate has expired

While downloading templating-compiler@1.3.3...:
error: certificate has expired

While downloading templating-runtime@1.3.2...:
error: certificate has expired

While downloading templating-tools@1.1.2...:
error: certificate has expired

While downloading ui@1.0.13...:
error: certificate has expired

While downloading webapp@1.6.2...:
error: certificate has expired

Your application has errors. Waiting for file change.

**Comment by tongwensen** [comment]
Due to the requirements of internal use of the company for project loading speed, I have migrated the server from Amazon to alicloud. At present, I have encountered such problems when starting. Since the function was used two years ago, it is still an old version. What should I do if I encounter such problems

**Comment by ajitStephen** [comment]
Something stupid worked well, for me.
Restart the laptop, or server.

**Comment by toledoroy** [comment]
I had this same thing.  [For an unknown reason in my /etc/hosts file, there was the entry: 54.192.225.217 warehouse.meteor.com; removed that entry](https://forums.meteor.com/t/solved-error-certificate-has-expired/49912/4), now it's working again.

**Comment by clementbmn** [comment]
For me, It was because we were stuck to version 1.8, updating to 1.10 with --release 1.10.2 fixed the problem

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
