### ISSUE TITLE
Arkenea <> OHIF integration

### ISSUE THREAD

**Issue by richamohta146** [OHIF/Viewers#2058]
Hi Team,

I am writing this to you on behalf of a software development company known as Arkenea Inc. We are looking at the integration of DICOM viewers into a solution that we are building on for one of our clients. 
In accordance, we would like to know we  can have a call between the teams to ensure we understand how pricing works at your end.
If yes, could you please send us the time slots for the same? 
Do let me know if there is any more information required from our side.

1. Does the DICOM viewer provide APIs to be integrated with a system that is being built at the moment?
2. Is the DICOM viewer compatible with other PACS servers? If yes, is that integration limited to only a number of PACS?
3. What is the pricing model for the Above-mentioned APIs (Integration of DICOM with our system) along with the DICOM being able to connect with PACS?
4. Can the DICOM API be used on a web-platform?
5. Do you have any documentation we could refer to for the API integration?

Regards,
Richa

**Comment by pieper** [comment]
Hi - OHIF is open source, so you can pick it up and integrate it as you like, no strings attached.  If you find ways to improve the code it would be great if you could work with the community to contribute back.  Bug fixes and documentation are particularly welcome.

I'm guessing one or more of the commercial support partners might be reaching out to you to offer additional services.  Retaining a consultant who is familiar with the code could accelerate your development.

**Comment by richamohta146** [comment]
Hi,

Thank you for your response.
We now understand the OHIF framework better.

Just one question :
Can the DICOM Viewers connect to third party PACS?


Regards,
Richa
Asst. Vice President - Business

**Comment by pieper** [comment]
> Can the DICOM Viewers connect to third party PACS?

OHIF can access PACS via the DICOMweb standard.  If you need to use the widely used traditional DICOM networking (called DIMSE) you can use some middleware to translate between the protocols.
