### ISSUE TITLE
[IDC] - Add a copy to clipboard function to debug extension

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#2059]
[Would it be possible to add a "copy to clipboard" button? If it's complicated, maybe just add a note to copy paste the content of the debug window, and specify the support email where it should be sent?](https://github.com/OHIF/Viewers/issues/2051#issuecomment-696815113)

We should add a copy to clipboard button next to the Send Bug Report button.

**Comment by fedorov** [comment]
Would be good to also have a config option to specify support email. This would go into the fork, right @JamesAPetts ?
