### ISSUE TITLE
Problem displaying studies with VOI LUT

### ISSUE THREAD

**Issue by Pela2silveira** [OHIF/Viewers#2061]
> **Before Creating an issue**
>
> - Are you running the latest version?yes
> - Are you reporting to the correct repository? yes
> - Did you search existing issues? Yes I post a question [here](https://github.com/OHIF/Viewers/issues/818) butno shure if they are related.

### Describe the Bug
XA Modality Studies with VOI LUT attibutes loads all in [blank](https://user-images.githubusercontent.com/34963342/93900949-5ce10480-fccc-11ea-8479-2dac844ceca2.png).

[Here ]( https://we.tl/t-AB4f4GLecv) is a series anonymized.

I have tryied the dataset in cornerstone library examples available in rawgit.com, and it loads [correctly](https://user-images.githubusercontent.com/34963342/93900946-5bafd780-fccc-11ea-8c89-79b18647defc.png).

### What steps can we follow to reproduce the bug?

1. Load Dataset on a PACS
2. configure OHIF to retrieve against PACS
3. Load Study

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by Pela2silveira** [comment]
Hello @sedghi  I have tested in v3.7.0, last stable version and it does not display studies correctly:
<img width="1684" alt="Captura de pantalla 2024-03-15 a la(s) 13 37 09" src="https://github.com/OHIF/Viewers/assets/34963342/370f194b-6a20-40e7-96b9-f61c1c98b131">
<img width="1355" alt="Captura de pantalla 2024-03-15 a la(s) 13 37 43" src="https://github.com/OHIF/Viewers/assets/34963342/6dbbf41a-50f7-459c-9ab5-52b9495f5f7f">
<img width="1132" alt="Captura de pantalla 2024-03-15 a la(s) 13 37 56" src="https://github.com/OHIF/Viewers/assets/34963342/a0401b0e-0146-4b4c-83ef-2d2996ae1266">
