### ISSUE TITLE
Authorization code + PKCE

### ISSUE THREAD

**Issue by sinanmb** [OHIF/Viewers#2065]
Hi

First, I successfully setup user access control by login directly against the Google OAuth Application. Then I successfully setup the OHIF Viewer to login against my Keycloak server using the implicit flow, but I later realized that Keycloak doesn't support silent renew for the implicit flow, therefore I've tried to setup the authorization code + PKCE flow, however I'm getting stuck. I followed the example [here](https://github.com/henriquels25/redux-oidc-sample/blob/master/src/auth/userManager.js) for the setup, and receive an authorization code in my Callback component. 

What is the next step? I was under the impression the library would exchange the authorization code for an access token, however it seems I misconfigured something? 

I appreciate any pointers.  

This is the config I am using 
```
   {
      // Authorization Server URL
      authority: 'http://localhost:8080/auth/realms/<realmId>',
      client_id: '<clientId>',
      redirect_uri: 'http://localhost:3000/callback', // `OHIFStandaloneViewer.js`
      response_type: 'code',
      scope: 'openid email',
      grantType: 'authorization_code',
      automaticSilentRenew: true,
      revokeAccessTokenOnSignout: true,
      loadUserInfo: true,
    }
```

**Comment by sinanmb** [comment]
The problem was that I had a conditional rendering of the CallbackComponent, and thus prevented the second part of the authorization code flow.

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
