### ISSUE TITLE
using OHIF Viewers without PACS

### ISSUE THREAD

**Issue by dfsRony** [OHIF/Viewers#2071]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

I found your project is the best Viewers so far. I am currently working in a hospital company and we are developing viewers for our hospital. My question is , Is it possible to use this viewers to load our DICOM file without PACS and using local server storage instead ,

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by dfsRony** [comment]
thank you for your response, I already figured it out and the OHIF already run in our local system, but I have next question, this quite simple, Im not sure if I should open another question for this question.

My question are "What is INVESTIGATIONAL USE ONLY" means? does this describe any usage restrictions?
![image](https://user-images.githubusercontent.com/9107326/95171170-b45c9580-07df-11eb-83fb-dade347ed033.png)

thanks for your response 🥇 😃

**Comment by swederik** [comment]
It means the software has not been cleared by any regulatory agency and you should not be using it for e.g. diagnostic purposes.

**Comment by swederik** [comment]
It means the software has not been cleared by any regulatory agency and you should not be using it for e.g. diagnostic purposes.

**Comment by sedghi** [comment]
You can look into our datasources options https://docs.ohif.org/configuration/dataSources/introduction
