### ISSUE TITLE
Embedded viewer cornerstone canvas grows to infinity upon interaction

### ISSUE THREAD

**Issue by epetxepe** [OHIF/Viewers#2073]
**Description**

We have embedded the viewer following instructions at https://docs.ohif.org/deployment/recipes/embedded-viewer.html . More specifically Installing OHIF viewer inside another react app described at the end of the page.

But when we use it and we load a series with a cornerstone viewport (doesn't seem to happen with Dicom Microscopy extension), which doesn't happen if OHIF viewer is launched standalone:

- Initial viewport size is really small and doesn't take all ViewerMain area
- Upon interaction (change of layout, change of browser size) the cornerstone canvas (all of them) grow vertically to infinity 

![cornerstone-canvas](https://user-images.githubusercontent.com/8027532/94828490-d03ff000-0409-11eb-974a-a6cb3611517e.gif)

**Steps to reproduce & alternatives tested**
I've setup a public repo with a simplified example of the OHIF viewer embedding  (using the installViewer approach) to reproduce this issue at: https://github.com/epetxepe/example-ohif-installviewer

_Alternative 1:_
I've been able to avoid this issue by changing **extensions/cornerstone/src/OHIFCornerstoneViewport.js:234** with **style={{ width: '612px', height: '256px', flex: '1' }}** fixing the cornerstone canvas height & width, and building a modified OHIF-VIEWER package. 
But this way, cornerstone canvas are fixed to a size that keeps the same with different layouts or browser window resize, which is not a solution.

**Questions**
- Am I missing some configuration need for the OHIF viewer embedding installViewer approach?
- Is it some kind of bug?
- Could you tell me directions / hints on components to be debugged / revised? 
- Or confirm me if this could be something on cornerstone or react-cornerstone library?

**Comment by epetxepe** [comment]
It seems that when it's embedded within another react component it's not able to know what the height it should take so I'm using a workaround to set the height of the css of FlexBoxLayout set as vh (proportional to the browser window size) instead of 100% in ohif's code.

**Comment by kevalnagda** [comment]
How do I fix this if I'm using @ohif/viewer extension inside another react app?

**Comment by pmd23** [comment]
@epetxepe and @kevalnagda  I am using same thing in angular I am also facing same issue related to height. any solution on this?

**Comment by NicholasDascanio** [comment]
Has anyone found out how to solve this error?

**Comment by ASDrew94** [comment]
Echoing @kevalnagda's comment above. The OHIF embedded viewer has a locked problem.

If the FlexboxLayout component could be changed in the main source, could that be replicated to the embedded viewer package?

**Comment by selvesandev** [comment]
Bumped into the same issue!! The viewport is getting auto zoomed and not stopping unless the page is reloaded. Please let us know if any body has found a solution for this.
