### ISSUE TITLE
Open viewer with specific study uid without study list

### ISSUE THREAD

**Issue by mokbelt** [OHIF/Viewers#2079]
Hi...
Could you please advise what settings should be changed to open the viewer directly with a specific studyuid, such as http://localhost/viewer/1.234.33444444555
(Study list is opening successfully using my dcm4chee-arc-light PACS)

Trying it this way is giving error, since it is checking static location.
I am using embedded version with index.html file only and hosted using apache 24.

Please provide a solution for this issue.
THANKS!!

**Comment by sedghi** [comment]
See the URL configuration doc https://docs.ohif.org/configuration/url
