### ISSUE TITLE
Integrating OHIF Viewer into existing React web app.

### ISSUE THREAD

**Issue by buddy1014** [OHIF/Viewers#2091]
Hi, all.

Now I am trying to integrate OHIF Viewer into my existing React app. Just similar as following image:
![image](https://user-images.githubusercontent.com/59859330/95156069-4e035300-079e-11eb-8a57-db89c0f403ea.png)
But I am not sure how to start and how to integrate.

* I tried to fork this repo and carefully checked. But can not find any thing.
* And also when I try to run this repo in my local, I get javascript memory heap out error.

Looking forward to hearing from you
Thanks.

**Comment by epetxepe** [comment]
Instructions are here: https://docs.ohif.org/deployment/recipes/embedded-viewer.html

I've set a simple integration (in a React App) demo repo to report the issue (https://github.com/OHIF/Viewers/issues/2073) at https://github.com/epetxepe/example-ohif-installviewer

Have a look at it.

BR,

Gorka

**Comment by seniordev1014** [comment]
@epetxepe thanks for your reply.
By the way, what about heap out error?

**Comment by PoyangLiu** [comment]
FYI. The heap out error is also reported in #1466.

**Comment by web2ls** [comment]
the only thing that helped me was to disable generating source-map for Viewer
note that for my external react app i used create-react-app

**Comment by pavankjadda** [comment]
@web2ls Your suggestion worked for me. But my whole app CSS messed up. How do I prevent it other than using `iframe`?

**Comment by sedghi** [comment]
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
