### ISSUE TITLE
Use of uninitialized variables

### ISSUE THREAD

**Issue by matthiasg** [OHIF/Viewers#2105]
Why is it that variables are being used before being declared ? 

E.g. see for usages of `hide` and `show`:

https://github.com/OHIF/Viewers/blob/0ef88e88eb2ddf990e0307b9f07a20ef296fb853/platform/ui/src/contextProviders/ModalProvider.js#L53 

this is happening in some 'Providers'. It is also leads to exceptions when configuring Babel to leave the code and not compile down to es5.

**Comment by swederik** [comment]
Thanks for the report and the fix!
