### ISSUE TITLE
MPR does not work for a TCIA I-SPY series

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2113]
When I click MPR, I get blank in the viewers, and some errors in the console.

It looks like this is a contrast-enhanced series, and probably should not have MPR enabled. Or if it should be enabled, it should probably not be blank.

Study: 1.3.6.1.4.1.14519.5.2.1.7695.1700.251725059071532256976802593346
Series: 1.3.6.1.4.1.14519.5.2.1.7695.1700.284567351304426376226790714264

![image](https://user-images.githubusercontent.com/313942/96062809-9d174b00-0e64-11eb-8ea8-703bd3d15a7d.png)

**Comment by pieper** [comment]
Here's a direct sandbox link to reproduce:

https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_mvp_wave0/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.7695.1700.251725059071532256976802593346?SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.7695.1700.284567351304426376226790714264

This is a 4D series, so yes, we should detect that and disable MPR.

**Comment by fedorov** [comment]
Discussed and agreed should disable MPR button.

**Comment by fedorov** [comment]
Related to #2157, where it would be needed to have a better logic to identify 4d datasets, but here it is simpler as we just need to check if there are multiple slices for the same ImagePositionPatient and disable MPR.

**Comment by Punzo** [comment]
Done in https://github.com/OHIF/Viewers/pull/2160, waiting for review

**Comment by Punzo** [comment]
Merging https://github.com/OHIF/Viewers/pull/2160, but CI test fails (not related to the PR)
