### ISSUE TITLE
Series loading progress bar not showing on OHIF viewer 4.5.21

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#2119]
Series loading progress bar is no longer showing on OHIF viewer build 4.5.21

![Screenshot 2020-10-16 061907](https://user-images.githubusercontent.com/5023419/96202140-e1474000-0f77-11eb-8664-236569d175a7.png)

**Comment by sedghi** [comment]
We have plan to add this back to v3, I'm gonna close this in favor of https://github.com/OHIF/Viewers/issues/3363
