### ISSUE TITLE
TypeError: "imageLoadObject.promise.then is not a function"

### ISSUE THREAD

**Issue by Disen8138** [OHIF/Viewers#212]
when  i run the StandaloneViewer and vist http://localhost:3000/testId but report error  ‘’TypeError: "imageLoadObject.promise.then is not a function‘’ thanks!

**Comment by galelis** [comment]
Hey @Disen8138,

My name is Gustavo and I will help you with this issue. 
But I tried locally, but I was unable to reproduce the issue, would you be able to provide me some more information? 
Do you have any change in your local? 
Can you provide me more details about the issue (maybe the full exception log)? 
Do you see any issue in the server side (terminal/cmd logs)?

Thanks

**Comment by swederik** [comment]
My guess if you are using the older version of the Cornerstone Web Image Loader. This was updated by this commit: https://github.com/OHIF/Viewers/commit/5785d19ee1849d5930b96b3e8d90b281d9c372bf

Could you update the repository from Master again and then try once again?

**Comment by Disen8138** [comment]
Hey @swederik @galelis 
         Thanks very much！
          I update my local  repository from master,and run with my test image ,Your solution works.The problem has been solved。
          Pls accept my best wishes to you and your family! Thanks very much!
