### ISSUE TITLE
ChunkLoadError on Viewer Load Not Being Handled With a Retry 

### ISSUE THREAD

**Issue by wlongabaugh** [OHIF/Viewers#2121]
### Describe the Bug
Per the attached screen shot, we saw a black screen on load due to the error message:

"ChunkLoadError: loading chunk 0 failed"

as the Viewer loads. As this issue appears to result from a random network error, it has been impossible to reproduce. However, online review of similar errors suggest that such errors in the webpack module loading are not caught and retried (see e.g. https://dev.to/goenning/how-to-retry-when-react-lazy-fails-mb5). Absent a reproducible error, it would hopefully be possible to harden the code to handle this. 

![ViewerBlackScreen](https://user-images.githubusercontent.com/8441547/96320286-dbc51680-0fc6-11eb-81ba-290e940f2f3f.png)

### What steps can we follow to reproduce the bug?

Difficult. Launch the Viewer, but a network request to load a module would need to fail to reproduce. Inspection of code to find module load failures that are not handled seems the most likely way to address this.

**Comment by fedorov** [comment]
@swederik @JamesAPetts @pieper is there any way with these catastrophic errors to give some message to the user what is next (e.g., clear cache and hard reload, ask about this URL in the forum)? Or there is really no way around those black screens?

**Comment by pieper** [comment]
I would think we can catch any error that is being thrown, but I don't know the details of this one.  Yes, even a "Oh snap, something went wrong, please try reloading" would be good.

**Comment by igoroctaviano** [comment]
These errors happens when a dynamic import fails, i have tracked the ones we use in OHIF and created a boundary to handle these errors: https://github.com/OHIF/Viewers/pull/2145

**Comment by fedorov** [comment]
@wlongabaugh do you want to test this?

**Comment by fedorov** [comment]
I am seeing 404 and spinner for RTSTRUCT list for this study: https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.32722.99.99.247726286795860121686796574974227334270

![image](https://user-images.githubusercontent.com/313942/101682105-301dcd00-3a31-11eb-8a6a-6d6e76f01914.png)

Is this the same issue?

**Comment by wlongabaugh** [comment]
> @wlongabaugh do you want to test this?

Not something that can really be checked... it arises due to random network error.
