### ISSUE TITLE
Tag viewer broken for RTSTRUCT series

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2122]
I get the below when I try to open the following:

Study: 1.3.6.1.4.1.14519.5.2.1.1706.4009.192455081946878476141947586891
Series: 1.3.6.1.4.1.14519.5.2.1.1706.4009.528051917894993735599041861497

It also appears to be broken in this way for every RTSTRUCT series I tried.

![image](https://user-images.githubusercontent.com/313942/96357965-2aaaa300-10d0-11eb-81e3-07e243772462.png)

**Comment by pieper** [comment]
I can reproduce that.  Here's a sandbox link: https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_mvp_wave0/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.1706.4009.192455081946878476141947586891

Drag RTSTRUCT to layout, pick tag viewer, pick the struct from the dropdown menu to trigger stack trace:
![image](https://user-images.githubusercontent.com/126077/96373741-72671400-113c-11eb-96c8-ca9c7c87cfec.png)

**Comment by igoroctaviano** [comment]
> I get the below when I try to open the following:
> 
> Study: 1.3.6.1.4.1.14519.5.2.1.1706.4009.192455081946878476141947586891
> Series: 1.3.6.1.4.1.14519.5.2.1.1706.4009.528051917894993735599041861497
> 
> It also appears to be broken in this way for every RTSTRUCT series I tried.
> 
> ![image](https://user-images.githubusercontent.com/313942/96357965-2aaaa300-10d0-11eb-81e3-07e243772462.png)

Looks like ReferencedSOPInstanceUID and ReferencedSOPClassUID have undefined values in some depth so i have added a check to only include valid sequence values: https://github.com/OHIF/Viewers/pull/2187

**Comment by fedorov** [comment]
Now if I try to open the study mentioned in the original issue, I get this error:

![image](https://user-images.githubusercontent.com/313942/101645024-e5399080-3a03-11eb-93f1-5875fb7333a3.png)

https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.1706.4009.192455081946878476141947586891

**Comment by igoroctaviano** [comment]
> Now if I try to open the study mentioned in the original issue, I get this error:
> 
> ![image](https://user-images.githubusercontent.com/313942/101645024-e5399080-3a03-11eb-93f1-5875fb7333a3.png)
> 
> https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.1706.4009.192455081946878476141947586891

@Punzo fixed here: https://github.com/OHIF/Viewers/pull/2207

**Comment by Punzo** [comment]
perfect I'll test https://github.com/OHIF/Viewers/pull/2207 now
