### ISSUE TITLE
Custom RTSTRUCT dicom file failing to show results on OHIF

### ISSUE THREAD

**Issue by rushiKshirsagar** [OHIF/Viewers#2128]
![ohif_issue](https://user-images.githubusercontent.com/37549697/96688429-cb35e700-139e-11eb-8d9a-718ad945651b.JPG)

I have built a custom RTSTRUCT file with contour data and all necessary links made to the original DICOM. This file when uploaded together with the original DICOM shows the contour perfectly on 3D slicer, but gives the error below on OHIF(See attached image).

Any help is appreciated. Thank you.

**Comment by pieper** [comment]
Thanks for reporting this.  Can you create a sample that reproduces this issue using public data and share the files for debugging?  Also please describe the exact steps you used to create the files and which versions of Slicer, SlicerRT, and OHIF you tested.  We want these to be interoperable but as you know there are many variables involved.

**Comment by waba19** [comment]
Slicer version - 4.11.20200930 
You can find the test dicoms+rtstruct files I uploaded on local Orthanc in the link below. These same files were uploaded on 3D slicer and the contour was visible. 

https://drive.google.com/drive/folders/1Zi8T483rNbu4eufnW_agS76ZXmULi7V5?usp=sharing

**Comment by sedghi** [comment]
Could you please try using the latest master branch? If the issue still persists, kindly reopen this issue.
