### ISSUE TITLE
Optimize for mobile devices

### ISSUE THREAD

**Issue by jacklau88** [OHIF/Viewers#213]
dear,I run the viewer on Pc that normal, display the images are well, but is not good work on mobilephone, i use chrome browser.can you help me to fix this problem?

**Comment by radicalrob** [comment]
We haven't yet optimized the code to be responsive, have a good user experience on mobile devices and respond consistently to touch events.  What needs to happen is, someone needs to create thoughtfully designed layouts for mobile devices.  It's something we're aware of, but haven't been able to prioritize to get it done.  But if you, or someone you know has the time and knowledge of how to do that, please have a go at it and consider contributing it back!  Thx.

**Comment by jacklau88** [comment]
sorry.i mean that not about the responsive.it is a image dispaly problem.pls see attchments.
![_20180702151508](https://user-images.githubusercontent.com/7742138/42150060-1d10e2d6-7e0b-11e8-875c-4e13c314e482.jpg)
![_20180702151707](https://user-images.githubusercontent.com/7742138/42150063-1d7986ce-7e0b-11e8-87a6-1e6f1b979d47.png)

**Comment by swederik** [comment]
This looks like it might be related to another old issue with the Cornerstone WebGL renderer and the device's browser.

Can you try to change Meteor's settings for 'public.ui.cornerstoneRenderer' to 'canvas' in your configuration file? If you could provide an anonymized version the image, it would be helpful. Also, if this is PHI in the screenshots above, please remove them.

**Comment by jacklau88** [comment]
thanks your support.i understand your mean and fixed this issue.
