### ISSUE TITLE
Apply user authentication to viewer

### ISSUE THREAD

**Issue by m-shouman** [OHIF/Viewers#2135]
According to the documentation [user-account-control](https://docs.ohif.org/deployment/recipes/user-account-control.html) I've to use **Keycloak** server as identity provider so if I've to integrate with another one ([IdentityServer](https://identityserver.io/)) what configuration should I set to work with it?

**Comment by m-shouman** [comment]
got it

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
