### ISSUE TITLE
OpenResty-Orthanc recipe doesn't connect viewier to server

### ISSUE THREAD

**Issue by segakuz** [OHIF/Viewers#2139]
Hello!

I've built OHIF Viewer with Nginx and Orthanc as it described in Nginx + Image Archive documentation. But when I load files to Orthanc I can't see studies in the Viewer's Study List.

I tried paths from the root (in docker_nginx-orthanc.js) :

servers: {
    dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: '/wado',
        qidoRoot: '/dicom-web',
        wadoRoot: '/dicom-web'

I tried full paths :

servers: {
    dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: 'http://server-name/pacs/wado',
        qidoRoot: 'http://server-name/pacs/dicom-web',
        wadoRoot: 'http://server-name/pacs/dicom-web'

I tried full paths with port :

servers: {
    dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: 'http://server-name:8042/pacs/wado',
        qidoRoot: 'http://server-name:8042/pacs/dicom-web',
        wadoRoot: 'http://server-name:8042/pacs/dicom-web'

I used PROXY_TARGET and PROXY_DOMAIN variables in Dockerfile and in console command. Both in different variations (full path, from root and with port).

Please tell me what exactly I need to configurate to get studies from my orthanc server.

**Comment by sedghi** [comment]
This has been fixed in latest master 
https://docs.ohif.org/deployment/google-cloud-healthcare
