### ISSUE TITLE
use DICOM PDF extension with OHIF embedded

### ISSUE THREAD

**Issue by mokbelt** [OHIF/Viewers#2140]
Hello,

Any possiblity to use DICOM PDF Extension with the OHIF embedded viewer?
Tried adding the script:
<script
  src="https://unpkg.com/@ohif/extension-dicom-pdf/dist/index.umd.js"
  crossorigin
></script>

But it didn't execute.
Please advise.
Thanks!

**Comment by sscotti** [comment]
Similar issue for me.  I have some encapsulated PDF's that I created using Orthanc as part of a study.  The modality type is 'DOC' and:

0042,0012 (MIMETypeOfEncapsulatedDocument): application/pdf

OHIF recognizes it as a "DOC", but maybe not as a PDF.  

I've got this for CDN files:

<script src="https://unpkg.com/react@16.14.0/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@16.14.0/umd/react-dom.production.min.js" crossorigin></script>
<script src="https://unpkg.com/@ohif/viewer@4.9.15/dist/index.umd.js" crossorigin></script>
<script src="https://unpkg.com/@ohif/extension-dicom-pdf@1.1.2/dist/index.umd.js" crossorigin ></script> 
<script src="https://unpkg.com/@ohif/extension-dicom-pdf@1.1.2/dist/1.index.umd.js" crossorigin ></script> 
<script src="https://unpkg.com/@ohif/extension-dicom-pdf@1.1.2/dist/2.index.umd.js" crossorigin ></script> 

When I try to load the PDF's, it looks like it actually tries to load 1.index.umd.js, 2.index.umd.js from a different url, and a stack trace is thrown.

I am using the Docker Version of OHIF also.  The Docker version does display my PDF's, same study.  However, some of my PDF's are multi-page, and the viewer only displays page 1 of many.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
