### ISSUE TITLE
Migration from old standalone OHIF version 

### ISSUE THREAD

**Issue by IMP360** [OHIF/Viewers#2142]
Hi,

I am currently using the old version of OHIF (with meteor) in standalone. I load my DICOM images via dicomweb http or https.
I will want to use the new version (with the MPR) but I don't know how to load my exam information to the viewer ... here is an example of the JSON files that I was using until today :

`{
  "transactionId": "",
  "studies": [
    {
      "studyInstanceUid": "1.2.826.0.1.3680043.2.406.339208.1.503300.1.201924140052",
      "studyDescription": "",
      "studyDate": "03/09/2020",
      "patientName": "PATIENT^PATIENT^^^",
      "seriesList": [
        {
          "seriesInstanceUid": "1.2.826.0.1.3680043.3.29.1.423036699.48176.1600949700.1.3.1",
          "seriesDescription": "",
          "numImageFrames": 1,
          "seriesNumber": "1",
          "instances": [
            {
              "sopInstanceUid": "1.2.826.0.1.3680043.3.29.1.423036699.48176.1600949700.2.4.1",
              "rows": 512,
              "instanceNumber": "1",
              "columns": 512,
              "frameOfReferenceUID": "",
              "imagePositionPatient": "",
              "imageOrientationPatient": "",
              "url": "dicomweb://192.168.1.45/archiveDICOM/WEASIS_AE/2020/9/25/10/F348915F/5E2EDF2A/5E3CFA6C"
            },
            {
              "sopInstanceUid": "1.2.826.0.1.3680043.10.432.1.3.29532311515717071179964268894",
              "rows": 512,
              "instanceNumber": "2",
              "columns": 512,
              "frameOfReferenceUID": "",
              "imagePositionPatient": "",
              "imageOrientationPatient": "",
              "url": "dicomweb://192.168.1.45/archiveDICOM/WEASIS_AE/2020/9/25/10/F348915F/5E2EDF2A/A3123901"
            }
          ]
        }
      ]
    }
  ]
}`

Thank you in advance for your help.

Regards,

**Comment by DICOMSOFT** [comment]
I have found the new format json on this url => https://github.com/OHIF/Viewers/blob/master/docs/latest/deployment/index.md
But now, i have this warning :

![image](https://user-images.githubusercontent.com/5773662/98927562-fcef2900-24d8-11eb-9633-036c7f10d953.png)

Here is my json study : 
`{
   "studies":[
      {
         "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931",
         "StudyDescription":"RADOLO",
         "StudyDate":"20120927",
         "StudyTime":"1759",
         "PatientName":"DOE YANNICK",
         "PatientId":"10005679149",
         "series":[
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790647965110",
               "SeriesNumber":1,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":2583,
                        "Rows":1963,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.13",
                           "0.13 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555015834",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790647965110",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790647965110/instances/1.3.76.6.1.1.5.2.3026.1.411800555015834/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790656775201",
               "SeriesNumber":10,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1279,
                        "Rows":2787,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.135",
                           "0.135 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555065843",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790656775201",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790656775201/instances/1.3.76.6.1.1.5.2.3026.1.411800555065843/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790657395208",
               "SeriesNumber":11,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1105,
                        "Rows":2093,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.135",
                           "0.135 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555075844",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790657395208",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790657395208/instances/1.3.76.6.1.1.5.2.3026.1.411800555075844/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790648875115",
               "SeriesNumber":2,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1024,
                        "Rows":2370,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.135",
                           "0.135 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555015835",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790648875115",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790648875115/instances/1.3.76.6.1.1.5.2.3026.1.411800555015835/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790649355122",
               "SeriesNumber":3,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1024,
                        "Rows":2314,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.135",
                           "0.135 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555015836",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790649355122",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790649355122/instances/1.3.76.6.1.1.5.2.3026.1.411800555015836/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790651075147",
               "SeriesNumber":4,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1024,
                        "Rows":2381,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.135",
                           "0.135 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555025837",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790651075147",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790651075147/instances/1.3.76.6.1.1.5.2.3026.1.411800555025837/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790652285158",
               "SeriesNumber":5,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1176,
                        "Rows":1400,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.148",
                           "0.148 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555025838",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790652285158",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790652285158/instances/1.3.76.6.1.1.5.2.3026.1.411800555025838/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790653605165",
               "SeriesNumber":6,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1038,
                        "Rows":2258,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.135",
                           "0.135 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555045839",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790653605165",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790653605165/instances/1.3.76.6.1.1.5.2.3026.1.411800555045839/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790654305174",
               "SeriesNumber":7,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1024,
                        "Rows":2397,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.135",
                           "0.135 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555045840",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790654305174",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790654305174/instances/1.3.76.6.1.1.5.2.3026.1.411800555045840/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790655415185",
               "SeriesNumber":8,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1101,
                        "Rows":2536,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.135",
                           "0.135 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555045841",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790655415185",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790655415185/instances/1.3.76.6.1.1.5.2.3026.1.411800555045841/frames/1"
                  }
               ]
            },
            {
               "SeriesDescription":"00/00",
               "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790656055194",
               "SeriesNumber":9,
               "SeriesDate":"20190822",
               "SeriesTime":"1707",
               "Modality":"CR",
               "instances":[
                  {
                     "metadata":{
                        "Columns":1081,
                        "Rows":2383,
                        "InstanceNumber":1,
                        "AcquisitionNumber":0,
                        "PhotometricInterpretation":"MONOCHROME2 ",
                        "BitsAllocated":16,
                        "BitsStored":16,
                        "PixelRepresentation":0,
                        "SamplesPerPixel":1,
                        "PixelSpacing":[
                           "0.135",
                           "0.135 "
                        ],
                        "HighBit":15,
                        "ImageOrientationPatient":[
                           ""
                        ],
                        "ImagePositionPatient":[
                           ""
                        ],
                        "FrameOfReferenceUID":"",
                        "ImageType":[
                           "DERIVED",
                           "PRIMARY "
                        ],
                        "Modality":"CR",
                        "SOPInstanceUID":"1.3.76.6.1.1.5.2.3026.1.411800555065842",
                        "SeriesInstanceUID":"1.3.76.6.1.1.5.2.3026.3.411790656055194",
                        "StudyInstanceUID":"1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931"
                     },
                     "url":"http://192.168.1.45/wado/studies/1.2.826.0.1.3680043.8.394.12048.9984.37020.1.100448931/series/1.3.76.6.1.1.5.2.3026.3.411790656055194/instances/1.3.76.6.1.1.5.2.3026.1.411800555065842/frames/1"
                  }
               ]
            }
         ]
      }
   ]
}`

Anyone have any idea what the problem is?
Thank you in advance for your help.

**Comment by sedghi** [comment]
See migration guides https://docs.ohif.org/migration-guide
