### ISSUE TITLE
installViewer example is not using `id` which causes connections to the wrong server

### ISSUE THREAD

**Issue by matthiasg** [OHIF/Viewers#2146]
The examples using `installViewer` are missing the `id` property for configuring the servers.

See: [Embedded Viewer](https://github.com/OHIF/Viewers/blob/2412c08595dd478cfadffb3eefc55cf013ce2897/docs/latest/deployment/recipes/embedded-viewer.md) and [Configuration](https://github.com/OHIF/Viewers/blob/2412c08595dd478cfadffb3eefc55cf013ce2897/docs/latest/configuring/index.md).

The `id` property is important as the state is saved in session state and identified via `id`. That means once a server was added without id, changing the initial configuration does NOT override the previous settings. Which causes the viewer to keep connecting to a previously connected server.

Right now the solution is to ensure always specifying servers with a constant `id` to ensure changes during the next run are applied.

```
    ...
   servers: {
        dicomWeb: [
          {
            id: 'ConstantServerIdShouldNeverChangeEvenIfConfigLikeWadoUriRootChanges', 
            wadoUriRoot: '...',
            ...
        }
   }
   ...
````

**Comment by anarnoli** [comment]
Hello @matthiasg , Did you find any workaround on this?

I'm trying to push new configuration to OHIF viewer using `installViewer` approach but it always picks previous configurations.

**Comment by matthiasg** [comment]
@anarnoli I do not actually know at the moment, I am looking into that tomorrow again though, will update here

**Comment by anarnoli** [comment]
> @anarnoli I do not actually know at the moment, I am looking into that tomorrow again though, will update here

Any luck @matthiasg ?

**Comment by sedghi** [comment]
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
