### ISSUE TITLE
How to change left-right layout to top-bottom layout?

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#2150]
I want to browse images on the mobile end. It's better to display images with top-bottom layout on the phone:
![TIM图片20201105152346](https://user-images.githubusercontent.com/56569509/98210324-586e6380-1f7b-11eb-94e2-9cd613128d61.png)

How to change left-right layout to top-bottom layout?

**Comment by PoyangLiu** [comment]
It's not clear from your question what you have in mind.
1. With user interaction
    * Use the `Layout` toolbar button to do this
2. Detect window size (eg. https://usehooks.com/useWindowSize/)
    * dispatch the `setLayout` [redux action](https://github.com/OHIF/Viewers/blob/master/platform/core/src/redux/actions.js#L45) when Viewer is loaded
    * this is the same action that the `Layout` button calls

**Comment by JiangWeian** [comment]
@PoyangLiu @dannyrb , Now the layout is that the thumbnail is on the left and the image-viewer is on the right. I mean how to make the thumbnail on the top and the image-viewer on the bottom. Because there is more vertical space on the mobile phone, the display of top-down layout can better browse images.

**Comment by PoyangLiu** [comment]
There is no way to do that out-of-the-box.  You'll have to modify the code.  Specifically [`Viewer.js`](https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/connectedComponents/Viewer.js#L308) and [Viewer.css](https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/connectedComponents/Viewer.js) to style the `LeftSidePanel` to become the `TopSidePanel`

**Comment by JiangWeian** [comment]
@PoyangLiu ,OK, I've found a way to modify it by using the top-down layout on the mobile end and the left-right layout on the laptop. Revised Viewer.js , SidePanel.js , StudyBrowser.js and their CSS files.

**Comment by drsherifk** [comment]
@JiangWeian  Can you please share your modifications...

**Comment by JiangWeian** [comment]
@drsherifk , Some modified code can be shared with you, but not all.
The overall idea is to use ismobileend() method encapsulated in object to determine whether to use different CSS for mobile terminal and PC terminal, so as to present different layout.

Modified code list:
![TIM图片20201208130115](https://user-images.githubusercontent.com/56569509/101442043-76056300-3955-11eb-890f-d5ca91e02f3d.png)

Compression package of CSS and JS:
[CSS+js.zip](https://github.com/OHIF/Viewers/files/5656974/CSS%2Bjs.zip)

**Comment by annong163** [comment]
@JiangWeian 兄弟能发一份全的不 感激不尽

**Comment by urosch** [comment]
Would someone be willing to add this code to this project? I believe there is a big interest in this being implemented.
Also I understand this would not be the main priority for this project as well.
Have a nice day!

**Comment by liujun1998-liu** [comment]
能不能提供一下适应移动端布局的解决方案呢？
