### ISSUE TITLE
BUG: microscopy extension fix drag&drop feature to select a dataset for the view

### ISSUE THREAD

**Issue by Punzo** [OHIF/Viewers#2155]
### Describe the Bug

Drag and drop viewer feature for the microscopy extension does not work

### What steps can we follow to reproduce the bug?

1. open a miscropy datasets with more than one channel
2. try to drag and drop a channel study icon on the view
3. the visualized channel is not changed

### Expected behavior

load and visualize the selected channel when dragging and dropping the channel icon.

**Comment by Punzo** [comment]
@pieper since we will use the slim viewer, I guess this is not anymore a HTAN/IDC priority, isn't it? 

I will leave this open, but I will remove the HTAN IDC labels

**Comment by sedghi** [comment]
@igoroctaviano What is the status on this?

**Comment by igoroctaviano** [comment]
@sedghi now IDC uses SLIM for microscopy. @fedorov can we close this legacy issue?
