### ISSUE TITLE
Support visualization of 4D datasets

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2157]
We already have quite some data in TCIA that is 4D (DWI, DCE) and it would be helpful to allow users to scroll through the 4th dimension in 2d viewer.

**Comment by najimhashgraph** [comment]
Hi federov,

I am also interested in this feature.  Is there any timeline when it will be added to ohif?

kind regards,
Najim

**Comment by fedorov** [comment]
No, there is no timeline at this point. It is not currently a top priority for the IDC project.

**Comment by fedorov** [comment]
Here are couple of specific examples from TCIA/IDC (this is not yet in production):
* https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc/dicomStores/v2/study/1.3.6.1.4.1.14519.5.2.1.3671.4754.131608903441424620949571415524 (series called DCE and DWI)

**Comment by fedorov** [comment]
Most likely, superseded by #3082

**Comment by fedorov** [comment]
We in IDC do not plan to invest resources into adding this to v2, and no one else has such plans either, to my knowledge, so I think it makes sense to close.
