### ISSUE TITLE
Issue with rendering dicom images from the server Ohif Viewr

### ISSUE THREAD

**Issue by ravikant-cisin** [OHIF/Viewers#2162]
Hi,

I am using OHIF Viewer to rendering the dicom images in the viewer. But i am getting following issue while going through it.
1) I am trying to render .dcm format images so i have cretaed an api and changed the url directly from the source code.
When it is hitting to the sever it gives CORS policy error..In the response api i have added all the headers in the repsonse but i am getting the same issue.
2) If i have dcm format images how i need to send it in the response ? For example i am using core php api for the image and i am using "file_get_content" method to send response when image instance api calling...So will it be good way to return the response Or i need to change the way i am sending in the response.

Please help me in the above 2 points..I am really not getting how can i resolve it. Please help me.

Thanks

**Comment by VinayBaviri** [comment]
Hii @ravikant-cisin ,  we tried recently to render .dcm files with OHIF viewer support. Its rendered fine as expected. we tried both by browsing internal files and by passing configurable structured JSON. 
For reference, u can find node.js sample code here https://github.com/VinayBaviri/ohif-viewer.

Thank you.

**Comment by anarnoli** [comment]
Hello @VinayBaviri, I am searching for similar solution and found your sample code very impressive. 

One thing I wanted to understand is: I have series of .dcm files like [this example](https://www.dropbox.com/sh/zvkv6mrhpdze67x/AADLGK46WuforD2LopP99gFXa?dl=0). In your sample code at route `/view` there is a variable `imageUrl`. What could be the best way to pass file(s) or folder to generate JSON at once?

Many thanks.

**Comment by sedghi** [comment]
Could you please review our comprehensive documentation on Cross-Origin Resource Sharing (CORS) and OHIF? Below are the links provided for your reference.

- https://docs.ohif.org/deployment/cors
- https://docs.ohif.org/deployment/iframe
