### ISSUE TITLE
Upside down images

### ISSUE THREAD

**Issue by thiagobusa** [OHIF/Viewers#2163]
### Describe the Bug

Images are displayed upside down.
![upside-down-1](https://user-images.githubusercontent.com/5495168/98712436-0fe0ec80-2365-11eb-99f6-b9e569bf64c2.png)
![upside-down-2](https://user-images.githubusercontent.com/5495168/98712437-10798300-2365-11eb-8ba1-96834afd4497.png)

Another thing, is that, when you click reverse, it disappears.

![before-inverter-click](https://user-images.githubusercontent.com/5495168/98712430-0f485600-2365-11eb-8764-04d360b056ad.png)

In another viewers, like weasis, osirix,..., they are shown normally.

DICOM
[1.2.392.200036.9116.6.18.14572103.1467.20201106170621624.9.66-3606095176755323728.zip](https://github.com/OHIF/Viewers/files/5519304/1.2.392.200036.9116.6.18.14572103.1467.20201106170621624.9.66-3606095176755323728.zip)

**Comment by xtfer** [comment]
Can confirm. We're seeing this with several studies.

**Comment by thiagobusa** [comment]
Yes, but for a specific device. It still occurs.

Em seg., 14 de fev. de 2022 às 01:54, Christopher Skene <
***@***.***> escreveu:

**Comment by xtfer** [comment]
This appears to be specific to Toshiba Aplio systems.

**Comment by nigelheap** [comment]
Just another follow up on this one, it's happening in v3 as well @sedghi @thiagobusa 

This is the demo dicom Toshiba Aplio system
[1.2.392.200036.9116.6.18.14572103.1467.20201106170621624.9.66-3606095176755323728.zip](https://github.com/OHIF/Viewers/files/10718142/1.2.392.200036.9116.6.18.14572103.1467.20201106170621624.9.66-3606095176755323728.zip)

Single image it upside down
![Screenshot 2023-02-13 at 13 36 25](https://user-images.githubusercontent.com/293999/218358312-12e709a5-7d83-401f-b1a3-2d20240529e5.png)

Dual image the right way up
![Screenshot 2023-02-13 at 13 36 44](https://user-images.githubusercontent.com/293999/218358332-d819db3e-632a-46ae-a59b-5e2dcd857da7.png)

**Comment by sedghi** [comment]
I tried loading them in 3D slicer it gives the following warning 

![image](https://user-images.githubusercontent.com/7490180/220707546-d4c8b2d6-62f5-4b4b-80c5-84107e5dc43e.png)

**Comment by xtfer** [comment]
@sedghi Yes, its possible, but all the US imaging coming out of Toshiba (now Canon) Aplio's are doing this in OHIF. Here's an example of a real study which loads upside down in OHIF but is right way up in all other viewers. I can provide this if you need it, but since I can't scrub the patient name I don't want to put it in github. In any case, the test provided should be the same.

![CleanShot 2023-02-24 at 19 56 22@2x](https://user-images.githubusercontent.com/40190/221136948-3ad4a8b9-8f2c-4165-be65-d57a306a952d.jpg)

**Comment by sedghi** [comment]
I looked into the data and it was JLS encoded. I'm wondering maybe there is something especial about that. Can you export non compressed ?

**Comment by xtfer** [comment]
@sedghi Okay, we'll look into that. The imaging isn't exported by us though, it's in the format it arrives at our service. Could be getting reencoded during viewing, by Google, however. I'll
Get check it out and come back to you.

**Comment by sedghi** [comment]
@xtfer Could you send me the non jls ones again? one s that I have are all jls

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by subhasishdash** [comment]
Can you add the changeset id or a link to the commit or merge so that it will be helpful to navigate and see what code changes were done. 
I am currently trying to fix the same for OhifV2 as I need to fix for the v2 version. So I am trying to understand what as the fix

**Comment by alexliam83** [comment]
Any chance of having this issue finally solved?

**Comment by sedghi** [comment]
seems like this is still an issue
@alexliam83 can you share your anonymized data with us?

**Comment by alexliam83** [comment]
We have runing OHIF Viewer 3.11.0 beta.15 on production.

```text
(0002,0000) File Meta Information Group Length           => 220
(0002,0001) File Meta Information Version                => 00\01
(0002,0002) Media Storage SOP Class UID                  => 1.2.840.10008.5.1.4.1.1.6.1
(0002,0003) Media Storage SOP Instance UID               => [ANONYMIZED_UID]
(0002,0010) Transfer Syntax UID                          => 1.2.840.10008.1.2.1 (Explicit VR Little Endian)
(0002,0012) Implementation Class UID                     => [ANONYMIZED_UID]
(0002,0013) Implementation Version Name                  => OFFIS_DCMTK_361
(0002,0016) Source Application Entity Title              => [ANONYMIZED]
(0008,0005) Specific Character Set                       => ISO_IR 100
(0008,0008) Image Type                                   => ORIGINAL\PRIMARY\THYROID\0011
(0008,0012) Instance Creation Date                       => 20250602
(0008,0013) Instance Creation Time                       => 192807.643
(0008,0014) Instance Creator UID                         => [ANONYMIZED_UID]
(0008,0016) SOP Class UID                                => 1.2.840.10008.5.1.4.1.1.6.1
(0008,0018) SOP Instance UID                             => [ANONYMIZED_UID]
(0008,0020) Study Date                                   => 20250602
(0008,0030) Study Time                                   => 192527.321
(0008,0060) Modality                                     => US
(0008,0070) Manufacturer                                 => [ANONYMIZED]
(0008,0080) Institution Name                             => [ANONYMIZED]
(0008,0081) Institution Address                          => [ANONYMIZED]
(0010,0010) Patient Name                                 => [ANONYMIZED]
(0010,0020) Patient ID                                   => [ANONYMIZED]
(0010,0030) Patient Birth Date                           => [ANONYMIZED]
(0010,0040) Patient Sex                                  => [ANONYMIZED]
(0010,1010) Patient Age                                  => [ANONYMIZED]
(0018,1000) Device Serial Number                         => [ANONYMIZED]
(0018,1020) Software Versions                            => [ANONYMIZED]
(0018,1030) Protocol Name                                => [ANONYMIZED]
(0018,5010) Transducer Data                              => [ANONYMIZED]
(0018,602C) Physical DeltaX                              => -0.009072580374777317
(0018,602E) Physical DeltaY                              => 0.009072580374777317
(0020,000D) Study Instance UID                           => [ANONYMIZED_UID]
(0020,000E) Series Instance UID                          => [ANONYMIZED_UID]
(0020,0010) Study ID                                     => [ANONYMIZED]
(0020,0011) Series Number                                => 1
(0020,0013) Instance Number                              => 1
(0028,0010) Rows                                         => 720
(0028,0011) Columns                                      => 960
(0028,0301) Burned In Annotation                         => YES
(0038,0500) Patient State                                => [ANONYMIZED]
(0040,0244) Performed Procedure Step Start Date          => 20250602
(0040,0245) Performed Procedure Step Start Time          => 192527.491
(0040,0253) Performed Procedure Step ID                  => [ANONYMIZED]
(0040,0254) Performed Procedure Step Description         => [ANONYMIZED]
(0040,3001) Confidentiality Constraint Description       => [ANONYMIZED]
(7015,0010) Private Creator                              => PMTF INFORMATION DATA
(7015,1073) Unknown Tag & Data                           => [ANONYMIZED_PRIVATE_SEQUENCE]
(7FE0,0010) Pixel Data                                   => [OMITTED]
```
Let me know if this is enough.

**Comment by sedghi** [comment]
send image orientation patient and image position patient as well

**Comment by alexliam83** [comment]
It's empty.

**Comment by angeelmdev** [comment]
I'm encountering the same issue with images from Toshiba Aplio systems. These images don't include patient orientation tags like (0020,0037) or (0020,0020). However, they display correctly in other viewers we've tested, such as MicroDICOM, RadiAnt, and DAIPACS. I’m wondering if those viewers might be inferring the display orientation from ultrasound-specific tags like (0018,6011) Sequence of Ultrasound Regions, or perhaps applying a consistent default behavior. In OHIF, these images currently display incorrectly.

**Comment by sedghi** [comment]
please send as as much dicom data with this issue as possible, it helps us in the debugging

**Comment by alexliam83** [comment]
Here is another example:

```text
(0002,0000) File Meta Information Group Length           => 228
(0002,0001) File Meta Information Version                => 00\01
(0002,0002) Media Storage SOP Class UID                  => 1.2.840.10008.5.1.4.1.1.6.1
(0002,0003) Media Storage SOP Instance UID               => [ANONYMIZED_UID]
(0002,0010) Transfer Syntax UID                          => 1.2.840.10008.1.2.1 (Explicit VR Little Endian)
(0002,0012) Implementation Class UID                     => [ANONYMIZED_UID]
(0002,0013) Implementation Version Name                  => OFFIS_DCMTK_361
(0002,0016) Source Application Entity Title              => [ANONYMIZED]
(0008,0005) Specific Character Set                       => ISO_IR 100
(0008,0008) Image Type                                   => ORIGINAL\PRIMARY\THYROID\0001
(0008,0012) Instance Creation Date                       => 20250630
(0008,0013) Instance Creation Time                       => 175218.433
(0008,0014) Instance Creator UID                         => [ANONYMIZED_UID]
(0008,0016) SOP Class UID                                => 1.2.840.10008.5.1.4.1.1.6.1
(0008,0018) SOP Instance UID                             => [ANONYMIZED_UID]
(0008,0020) Study Date                                   => 20250630
(0008,0021) Series Date                                  => 20250630
(0008,0022) Acquisition Date                             => 20250630
(0008,0023) Content Date                                 => 20250630
(0008,0030) Study Time                                   => 175126.217
(0008,0031) Series Time                                  => 175126.222
(0008,0032) Acquisition Time                             => 175218.433
(0008,0033) Content Time                                 => 175218.433
(0008,0060) Modality                                     => US
(0008,0070) Manufacturer                                 => [ANONYMIZED]
(0008,0080) Institution Name                             => [ANONYMIZED]
(0008,0081) Institution Address                          => [ANONYMIZED]
(0008,1010) Station Name                                 => StationName
(0008,1090) Manufacturer Model Name                      => TUS-A300
(0010,0010) Patient Name                                 => [ANONYMIZED]
(0010,0020) Patient ID                                   => [ANONYMIZED]
(0010,0030) Patient Birth Date                           => [ANONYMIZED]
(0010,0040) Patient Sex                                  => F
(0010,1010) Patient Age                                  => [ANONYMIZED]
(0010,1040) Patient Address                              => [ANONYMIZED]
(0010,2154) Patient Telephone Numbers                    => [ANONYMIZED]
(0010,4000) Patient Comments                             => [ANONYMIZED]
(0018,1000) Device Serial Number                         => [ANONYMIZED]
(0018,1020) Software Versions                            => [ANONYMIZED]
(0018,1030) Protocol Name                                => Thyroid
(0018,5010) Transducer Data                              => [ANONYMIZED]
(0020,000D) Study Instance UID                           => [ANONYMIZED_UID]
(0020,000E) Series Instance UID                          => [ANONYMIZED_UID]
(0020,0010) Study ID                                     => [ANONYMIZED]
(0040,0253) Performed Procedure Step ID                  => [ANONYMIZED]
(7015,0010) Private Creator                              => PMTF INFORMATION DATA
(7015,1073) Unknown Tag & Data                           => [ANONYMIZED_PRIVATE_SEQUENCE]
(7FE0,0010) Pixel Data                                   => 2e1e\1e4e\4e2e\2d1e\1e4d\4e2e\2e1d\1e4e\4e2e\2e1e\1e4e\4e2d\2e1e...
```

Let me know if you need any of the anonymized tags, and I’ll check if it's possible to share them with you.

**Comment by sedghi** [comment]
if you can provide real data, it would be better, anonymized

**Comment by alexliam83** [comment]
This is real data extracted directly from the latest study uploaded to our platform from this ultrasound modality. Is there anything missing?

**Comment by sedghi** [comment]
I meant .dcm files

**Comment by rodrigobasilio2022** [comment]
https://github.com/cornerstonejs/cornerstone3D/pull/2194
