### ISSUE TITLE
Failed to get frame details from dicomweb-server to render in OHIF viewer

### ISSUE THREAD

**Issue by Karthik-Devaraj** [OHIF/Viewers#2165]
I am trying to use this dicomweb-server (https://github.com/dcmjs-org/dicomweb-server) to render in OHIF viewer.

I tried this setup in Window 10.

I have used the below configuration
dicomWeb: [{
name: 'dicomweb_server',
wadoUriRoot: 'http://localhost:8084',
qidoRoot: 'http://localhost:8084',
wadoRoot: 'http://localhost:8084',
qidoSupportsIncludeField: true,
imageRendering: 'wadors',
thumbnailRendering: 'wadors',
enableStudyLazyLoad: true,
supportsFuzzyMatching: true,
requestOptions: {
"requestFromBrowser": true
}
}, ],

I am facing issue to fetch wadors frame API
/studies/1.3.6.1.4.1.5962.99.1.3975984249.1189277055.1386955486329.3.0/series/1.3.6.1.4.1.5962.99.1.3975984249.1189277055.1386955486329.4.0/instances/1.3.6.1.4.1.5962.99.1.3975984249.1189277055.1386955486329.2.0/frames/1
Error message:
{"statusCode":404,"error":"Not Found","message":"Frame 1 was not found. Error: Empty buffer"}
![image](https://user-images.githubusercontent.com/1540308/98908859-0ed7c880-24e7-11eb-8ba7-89feb01f1aa8.png)

Other API's like fetch studies, series, instance are working fine.

I can able to download the instance stream as dcm file from the below URL
/studies/1.3.6.1.4.1.5962.99.1.3975984249.1189277055.1386955486329.3.0/series/1.3.6.1.4.1.5962.99.1.3975984249.1189277055.1386955486329.4.0/instances/1.3.6.1.4.1.5962.99.1.3975984249.1189277055.1386955486329.2.0

Please let me know, if I am missing anything in the configuration.

Thanks in advance.

**Comment by richsmith123** [comment]
Hello Karthik,

Did you find any solution to this issue? I am facing similar issue on my side. If you did find any solution then kindly share your findings.

Thanks,
Rick

**Comment by Oumaima26** [comment]
Hello Karthik,

Did you find any solution to this issue? I am facing similar issue on my side. If you did find any solution then kindly share your findings.

Thanks,
Omaima

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
