### ISSUE TITLE
OHIF keeps undefinetly retrying request after a 400 Bad Request DicomWeb answer

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#2170]
Hi there,

I have a series that produce a "Bad Request" answer in my DicomWeb Orthanc Back End (a special dicom file from a manufacturer that is probably not displayable).

This File is asked by OHIF when loading image (see screen capture) but this dicom is not an image so it can't be loaded.
The problem is : OHIF keep continue to reask this URI in an infinit loop, making overload in the server side.
As the HTTP answer is 400 Bad Request, it doesn't make sense to repeat the request without any substantial modification, that's a client error that souldn't be retried identically.

![Capture du 2020-11-16 11-17-53](https://user-images.githubusercontent.com/25229822/99241280-eeb54b80-27fd-11eb-9a0a-1a0167a6efa4.png)

I also put in attachement the responsible dicom (a settings file of a manufacturer that does not contains images but appreas in the series list)

[3589c0cc-4b40-4b71-94be-768e0bdbbc80.dcm.zip](https://github.com/OHIF/Viewers/files/5545612/3589c0cc-4b40-4b71-94be-768e0bdbbc80.dcm.zip)

Best regards,

Salim

**Comment by sedghi** [comment]
@salimkanoun Can you please re-verify this issue if still happens in master?

**Comment by salimkanoun** [comment]
We are OK now, no infinite queries anymore
