### ISSUE TITLE
HTAN Spike task: investigate OpenSeaDragon to replace OpenLayers for coloring/blending logic

### ISSUE THREAD

**Issue by Punzo** [OHIF/Viewers#2171]
https://cancerres.aacrjournals.org/content/77/21/e75

https://cancer.digitalslidearchive.org/#!/CDSA/acc/TCGA-OR-A5J1/TCGA-OR-A5J1-01A-01-TS1?slide=TCGA-OR-A5J1-01A-01-TS1.CFE08710-54B8-45B0-86AE-500D6E36D8A5.svs

https://openseadragon.github.io/examples/tilesource-custom/

**Comment by Punzo** [comment]
OpenSeaDragon renders the images with canvas 2D api as OpenLayers (e.g.: https://github.com/openseadragon/openseadragon/blob/db85f77c883ae6adb8478ff3e5165d5fde9cf559/src/imagetilesource.js#L234)

**Comment by Punzo** [comment]
Image filters in https://cancer.digitalslidearchive.org/#!/CDSA/acc/TCGA-OR-A5J1/TCGA-OR-A5J1-01A-01-TS1?slide=TCGA-OR-A5J1-01A-01-TS1.CFE08710-54B8-45B0-86AE-500D6E36D8A5.svs are applied simply with:

https://github.com/DigitalSlideArchive/dsa_girder_webix_base_viewer/blob/master/xbsBundles/DSA/sources/views/applyFilters.js#L220

**Comment by selko** [comment]
Is it possible to render Dicom WSI im OHIF using OpenSeaDragon?
