### ISSUE TITLE
CINE Images

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#2172]
Hello All,

I'm using ORTHANC server for dicom storage. ORTHANC server is running on a separate machine than from the OHIF viewer with NGINX.   Below is the configuration to the ORTHANC server.  

Somehow, ECHO studies does not by default comes as a cine images.  I manually have to click the play button to play it.

Is there any configuration that I need to do to make cine studies play by default?

servers: {
    dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: 'http://172.29.62.180:8080/wado',
        qidoRoot: 'http://172.29.62.180:8080/dicom-web',
        wadoRoot: 'http://172.29.62.180:8080/dicom-web',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  }

**Comment by sedghi** [comment]
No we don't have such configuration unfortunately
