### ISSUE TITLE
wadoRoot config setting is ignored

### ISSUE THREAD

**Issue by dyens** [OHIF/Viewers#2176]
Hi :hand:  !

I try to use OHIF viewer with my local dicomweb server. I have:

```js
  servers: {
    dicomWeb: [
      {
        name: 'My local dev',
        qidoRoot: 'https://127.0.0.1:8080/qido',
        wadoRoot: 'https://127.0.0.1:8080/wado',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },
```

But OHIF get metadata using this url:

https://127.0.0.1:8080/qido/studies/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170/series/1.519.342.3049.192.168.192.100.20200903094943600.32802/metadata

I think this is incorrect, because this method in [PS3.18 10.4 metada resources](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#table_10.4.1-2)

What am I missing? How i can configure wadoRoot prefix?

**Comment by JiangWeian** [comment]
@dyens ,  you can look ticket #1163

**Comment by dyens** [comment]
@JiangWeian, thank you! I think that is what i need.

Also i found, that if try to save measurements (it is stow request), Ohif send request to wado server... Should i close this issue and open issue about incorrect stow request?

**Comment by JiangWeian** [comment]
@dyens , yes, this ticket can be closed.
