### ISSUE TITLE
The PDF DICOM on the mobile terminal cannot adapt to the screen display

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#2178]
This is a screenshot of me in the developer tool (It's the same on my phone):
![TIM图片20201119101044](https://user-images.githubusercontent.com/56569509/99611964-95445b00-2a4f-11eb-8aff-bc6e8fe57243.png)

How to change display to adaptive screen?

**Comment by annong163** [comment]
> 这是我在开发者工具中的截图（我的手机也是这样）： ![TIM图片20201119101044](https://user-images.githubusercontent.com/56569509/99611964-95445b00-2a4f-11eb-8aff-bc6e8fe57243.png)
> 
> 如何将显示更改为自适应屏幕？

您好，方便给一下你修改之后的源码么？（主要是移动端适配相关）
