### ISSUE TITLE
Add new toolbar in the vtk extension

### ISSUE THREAD

**Issue by MAdelElbayumi** [OHIF/Viewers#2180]
Hello Guys, 
I have implemented some additional commands that perform 3D viewing functionalities using VTK, this implementation is inside VTK extension now so all the functions are shown when we click MPR button.
Now we want to make a separate toolbar/extension for these 3D functionalities(I am not sure which is the best approach). I tried the way of copying vtk extension but it's not working until now and many things need to be connected so: 
Which is the best approach to achieve this separation? and what are the steps?

**Comment by NicholasDascanio** [comment]
Hi! Have you eventually succeeded in doing such modifications? If so, which steps did you follow?

**Comment by NicholasDascanio** [comment]
Hello @MAdelElbayumi ! Did you manage to achieve this separation?
Kind regards

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
