### ISSUE TITLE
Pure-static deployment of Viewer and image archive: possible?

### ISSUE THREAD

**Issue by anderiv** [OHIF/Viewers#2182]
Hello all -

I have a use case where I'd like to be able to stand up OHIF instances by providing for each instance a directory of images that should be included by default in the viewer. I know conceptually how this would be done using Orthanc (or similar) as an image archive, however, ideally I would be able to deploy each OHIF instance to AWS S3 or some other static file hosting product.

To do this, I suspect I would need to parse the directory of images and generate a JSON manifest of all of the images, providing URLs for the images point to S3 (or elsewhere). This I can handle with some quick-and-dirty python. The question is - is this type of deployment supported? If so, where can I look for examples of what syntax would need to be used in the JSON file list?

Note: I'm aware of [this page](https://docs.ohif.org/deployment/recipes/static-assets.html) - it covers static hosting of the js application, but does not mention static hosting of the image archive.

Thank you!

**Comment by olivert1969** [comment]
Hi @anderiv 
Orthanc supports use of cloud for object storage like AWS S3. Details here: https://book.orthanc-server.com/plugins/object-storage.html.

**Comment by sedghi** [comment]
You can look here https://docs.ohif.org/deployment/static-assets
