### ISSUE TITLE
Setting hotkeys for Length, Window Level tool please ?

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#2188]
Hello All,

How do I assign hotkeys for Length tool and Window Level tool?

Thank you so much in advance!
Ric

**Comment by PoyangLiu** [comment]
1. Make sure the command for activating Length and WL tool exist
    * if they don't, create a [commandsModule](https://docs.ohif.org/extensions/modules/commands.html) and define these commands yourself.
2. Make sure there is a hotkey defined for these commands
    * see the `hotkeys` section of [configuration](https://docs.ohif.org/viewer/configuration.html)

**Comment by richsmith123** [comment]
Thank you so much for your assistance in guiding me.

Best regards,
Ric
