### ISSUE TITLE
Docker Image Error

### ISSUE THREAD

**Issue by davidi1** [OHIF/Viewers#219]
Hello, I updated to the new Docker image that was built yesterday and this is the error I am receiving when I try to start it by running **sudo docker-compose up**

"viewer_1  | [2018-07-06 13:18:43] PM2 log: App [ohif-viewer] with id [0] and pid [139], exited with code [1] via signal [SIGINT]
viewer_1  | [2018-07-06 13:18:43] PM2 log: Starting execution sequence in -fork mode- for app name:ohif-viewer id:0
viewer_1  | [2018-07-06 13:18:43] PM2 log: App name:ohif-viewer id:0 online
viewer_1  | The `stylus` package has been deprecated.
viewer_1  | To continue using the last supported version
viewer_1  | of this package, pin your package version to
viewer_1  | 2.513.14 (`meteor add stylus@=2.513.14`).
viewer_1  | Error: The @babel/runtime npm package could not be found in your node_modules
viewer_1  | directory. Please run the following command to install it:
viewer_1  |   meteor npm install --save @babel/runtime
viewer_1  |     at babel-runtime.js (packages/babel-runtime.js:25:9)
viewer_1  |     at fileEvaluate (packages/modules-runtime.js:322:7)
viewer_1  |     at Module.require (packages/modules-runtime.js:224:14)
viewer_1  |     at require (packages/modules-runtime.js:244:21)
viewer_1  |     at packages/babel-runtime.js:79:15
viewer_1  |     at packages/babel-runtime.js:86:3
viewer_1  |     at /app/bundle/programs/server/boot.js:411:36
viewer_1  |     at Array.forEach (<anonymous>)
viewer_1  |     at /app/bundle/programs/server/boot.js:220:19
viewer_1  |     at /app/bundle/programs/server/boot.js:471:5"

I tried to delete the containers & images so I could re-download them. After re-downloading & recreating the containers, the same error message came up.

**Comment by swederik** [comment]
I just pushed a commit to run meteor npm install inside the dockerfile. Hopefully that fixes it. 

It should be building now, and then it will be pushed automatically to dockerhub: https://travis-ci.org/OHIF/Viewers/builds/400919607

**Comment by davidi1** [comment]
It worked, thank you :-) However, there is another issue with this build. I opened a new issue...

**Comment by SANTHOSH-SJ** [comment]
Facing the same issue while building ohif viewer. any solutions?
