### ISSUE TITLE
Buffer allocation failure trying to do MPR for a large series

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2192]
Here's a large series that takes very very long time to download, and causes MRP failure:

https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.1706.4009.243406849348906151042089406192?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.1706.4009.304054433668574201838767925472

![image](https://user-images.githubusercontent.com/313942/100664709-09231500-3326-11eb-8abc-137326a0015b.png)

Is this the expected behavior for this specific dataset? When the series is too large, is it possible to disable MPR button?

**Comment by pieper** [comment]
yes, it's 3000 images, so it makes sense to me that it's too large.

We may not be able to know the exact allocation limit in advance, but we could certainly detect this error and give a more helpful message.  Ideally offering an alternative viewing option (e.g. download to slicer or similar).

I would bump this one to IDC:priorirty.

**Comment by fedorov** [comment]
Here's a legacy converted enhanced MF version of the same series, just in case: https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us/datasets/afshin_results_00_idc_tcia_mvp_wave0/dicomStores/MULTIFRAME/study/1.3.6.1.4.1.14519.5.2.1.1706.4009.243406849348906151042089406192?seriesInstanceUID=1.3.6.1.4.1.43046.3.1.9.5060456482850075494393251866013736567025

**Comment by pieper** [comment]
Here's the same study in the sandbox in case that helps:

https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc-tcia/dicomStores/idc-tcia/study/1.3.6.1.4.1.14519.5.2.1.1706.4009.243406849348906151042089406192

**Comment by pieper** [comment]
Related to #2223

**Comment by igoroctaviano** [comment]
@pieper @fedorov This PR adds a more helpful notification: https://github.com/OHIF/Viewers/pull/2246.

...also it adds a new option to the notification service which allows us to define an action (button), as suggested by Steve, we can use this action option to define a new button that will trigger something like: `download to slicer`.  If that's the case, we should align that's the correct behavior and add the action to that PR.

**Comment by pieper** [comment]
thanks @igoroctaviano - on our next prioritization call let's discuss what actions would make the most sense for cases like this.  Thinking about this now I realize in the past we haven't wanted to offer the download option so maybe the message should just say that the dataset is too big to display in MPR and the button should return to the default view.

**Comment by fedorov** [comment]
It gives the error in the viewer, but "Exit MRP" button is not responsive, at least not immediately - after some time, MPR seems to exit. Just wanted to confirm this is the intended behavior.

![image](https://user-images.githubusercontent.com/313942/113187786-4097c480-9227-11eb-8683-8f9634d9db0d.png)

**Comment by pieper** [comment]
It does seem like we could catch this early and avoid the console errors.

**Comment by igoroctaviano** [comment]
- When the notification service's error function is called it also logs to console but we could disable that and just notify the user.
- The button shouldn't be stuck while this is happening, we may need to investigate the blocking process.
- Currently, we just catch any errors popping from react-vtk/vtk and trigger a notification with a generic title + error message. This one specifies that the dataset is too big because we are poorly interpreting the error based on string matches to see if it's a buffer-related error. This is because we don't have error codes or proper throwing of errors that we could map to translated messages.

**Comment by fedorov** [comment]
Copying from slack, Madelyn had a different error message:

![image](https://user-images.githubusercontent.com/313942/113322238-7057d280-92e2-11eb-8a1c-59d62df4ec81.png)
