### ISSUE TITLE
how to display the home page based on patientid list ?

### ISSUE THREAD

**Issue by finch-xu** [OHIF/Viewers#2197]
the ohif's home page is now the study list, i can clearly find all studys , 
but i want the home page display on patientid list, or MRN list .
how can i do to get the patientid list home page ?
thanks.

**Comment by PoyangLiu** [comment]
Not sure what you mean.  But you can customize the studylist page
https://github.com/OHIF/Viewers/tree/master/platform/ui/src/components/studyList

Alternatively, define your own route and your own page.

**Comment by finch-xu** [comment]
thanks for that.
i mean the data is now organized by study id ， 
we know the dicom tags has many tags like studyid , patientid, accid , 
and i want to use the patient id to organize my dicom files, 
then there may be a web page named 'patient list' just like the 'study list',
just like this
![1607062578(1)](https://user-images.githubusercontent.com/39703270/101128789-54496a80-363b-11eb-8bb6-c2e6de6d0add.png)

**Comment by sedghi** [comment]
You can the queries for the MRN that you can use
