### ISSUE TITLE
Clear Annotation on multiframe image does not work

### ISSUE THREAD

**Issue by PoyangLiu** [OHIF/Viewers#2198]
### Describe the Bug

Trying to create and then clear measurement on a single frame image works.  But the tools are not removed on the multiframe image.

### What steps can we follow to reproduce the bug?

1. Open a MR multiframe image
2. Add an angle tool
3. Click on the "Clear" tool on the toolbar, which runs the "ClearAnnotation" command
4. Inspect the image
5. Inspect the measurement panel

Expected:
4. The angle too to be removed
5. The measurement panel tool to be removed

Actual:
4. The angle too remains
5. As expected

### Investigation
The bug seemed to be introduced in #1481

In [platform/core/.../getImageAttributes.js](https://github.com/OHIF/Viewers/blob/master/platform/core/src/measurements/lib/getImageAttributes.js#L16)
```js
const splitImageId = imageId.split('&frame');
const frameIndex = splitImageId[1] !== undefined ? Number(splitImageId[1]) : 0;
```
* The split parameter is incorrect. It should probably be `&frame=`
* Otherwise the `splitImageId` becomes `['....', '=N']`
* The following line `Number(splitImageId[1])` becomes `NaN`

In [platform/core/.../OHIFInstanceMetadata.js](https://github.com/OHIF/Viewers/blob/master/platform/core/src/classes/metadata/OHIFInstanceMetadata.js#L89)
```js
  getImageId(frame, thumbnail) {
    // If _imageID is not cached, create it
    if (this._imageId === null) {
      this._imageId = getImageId(this.getData(), frame, thumbnail);
    }

    return this._imageId;
  }
```
* `this._imageId` is cached once and reused
* `getImageId`is can be called with `frame` of `undefined | N`, `thumbnail` of `true | false`, Should the `_imageId` really be cached?

In [platform/viewer/.../Viewer.js](https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/connectedComponents/Viewer.js#L398)
```js
// In _mapStudiesToThumbnails function
imageId = displaySet.images[imageIndex].getImageId();
```
* The call to `getImageId` parameter doesn't pass in any frame number.  This causes the cached `_imageId` to be missing the `&frame=N`
* Should the `thumbnail` parameter of `getImageId` be `true` in this case?
* The measurementApi tries to find the tool state to delete, but cannot find a matching state due to the mismatched `imageId`

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
