### ISSUE TITLE
Showing DOB and Gender on viewport

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#2200]
Hello All,

How can date of birth and gender can be shown under patient name on viewport?

Thanks,
Ric

**Comment by PoyangLiu** [comment]
You should search for an existing issue before posting duplicated questions.

See #2125.

**Comment by richsmith123** [comment]
Thank you so much PoyangLiu for your assistance!!  Truly appreciated!!

Kind regards,
Ric

**Comment by sedghi** [comment]
You can use ViewportOverlay with the customizationService https://docs.ohif.org/platform/services/ui/customization-service
