### ISSUE TITLE
How can I see compressed DICOM images in the viewer?

### ISSUE THREAD

**Issue by jorgecaullan** [OHIF/Viewers#2201]
My main problem is that some of the DICOM images that I work with are too heavy, which means that a very good internet is required to be able to see them in a decent time.

For this, I began to investigate the Transfer Syntax that were used to compress DICOM images and made the images that were sent from an Orthanc server downloaded by a compressed syntax (1.2.840.10008.1.2.4.51).

Now my problem is that when I read these images from ohif (obviously) you can only distinguish nonsensical stripes.

Surely someone has ever had this problem and maybe it is not the best thing to compress the images. In that case I would like to know what they would recommend me to do. Or if there is any way to directly view the images in the viewer through some configuration.

Thanks in advance

**Comment by sylvainb31** [comment]
Hey Jorge,

I've had the same problem for a while but I've found a solution. I'm coding with asp net core.

What I did was setting the display of the images and thumbnails to wadouri :

```
imageRendering: 'wadouri', 
thumbnailRendering: 'wadouri', 
```

I have specified wadoUri et wado/qido root to my own api controller where I'm "re routing" the query and handling them.

```
wadoUriRoot: '/api/WadoUriAPI', 
qidoRoot: '/api/WadoQidoAPI', 
wadoRoot: '/api/WadoQidoAPI', 
```

In wadouri mode, the viewer expects a dicom file (application/dicom) to display the images.

To compress the images, I caugth them in my controller and compressed them using a library (https://github.com/fo-dicom/fo-dicom coupled with an other library (Efferent.Native) to compress to JPEG) and returned them to the viewer.

**Comment by jorgecaullan** [comment]
Thanks sylvainb! i'll try to make this and tell you how it works for me

**Comment by jorgecaullan** [comment]
Hi! I want to tell you that finally the solution that I implemented was, not to use the compressed format that I had sent, instead use 1.2.840.10008.1.2.4.70 (JPEG Lossless, Nonhierarchical).
Ohif supports using this format well and downloading images is noticeably faster.

**Comment by taijizhao** [comment]
@jorgecaullan Hello, Jorge! 
I also have problems with compressed dcm files. I am trying to build an mammographic dicom viewer based on OHIF. I use dcm4chee as the backend pacs. A mammogram is a 2D X-ray image of a breast, which has quite high resolution (about 4000x3000 pix) and big size (~26mb per image).  I compressed dicoms with a tool called "gdcmconv" according to syntax 1.2.840.10008.1.2.4.70, and the size of each file became ~3mb. I uploaded the files, and open them with OHIF. OHIF can show the images correctly, but it is still very slow. It seems OHIF to first decompress the dicoms at the server and send a data stream of the original image size (26mb). 
Could you tell me if you have done anything with OHIF, other than compress the dicom files?
Thank you very much!
