### ISSUE TITLE
Embedded Viewer 2D MPR not working (after adding its extension)

### ISSUE THREAD

**Issue by mokbelt** [OHIF/Viewers#2206]
I am trying to use the 2D MPR in the embedded OHIF; 
I added the settings as documented:

  **<script src="https://unpkg.com/@ohif/viewer/dist/index.umd.js" crossorigin></script>
  <script src="https://unpkg.com/@ohif/extension-vtk/dist/index.umd.js" crossorigin ></script>

window.config = {
  // default: '/'
  routerBasename: '/',
  extensions: [OHIFExtVtk],
  showStudyList: true,
  filterQueryParam: false,
  servers: {
    dicomWeb: [
      {
        name: 'DCM4CHEE',
        wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado',
        qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },**

but while loading on startup it is giving those errors:

_index.umd.js:185769 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

index.umd.js:21920 ToolbarRow Error Boundary Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings._

Please advise what is missing?
Is there any version of viewer that is compatible with any version of vtk?

Thanks!

**Comment by swederik** [comment]
I believe the VTK extension does not function with the viewer as a UMD module because it uses dynamic imports to load things like web worker scripts. I don't know if it's possible to use it in the embedded approach.

**Comment by mokbelt** [comment]
By changing some combination of older versions, example:
  <script src="https://unpkg.com/@ohif/viewer@2.9.0/dist/index.umd.js" crossorigin></script>
  <script src="https://unpkg.com/@ohif/extension-vtk@1.2.0/dist/index.umd.js" crossorigin ></script>
it was able to load succesfully. but Then fails when I click on the "2D MPR" icon with error: 
index.umd.js:2 Uncaught (in promise) TypeError: Cannot read property 'runCommand' of undefined

**Comment by sylvainb31** [comment]
@mokbelt @swederik  if you manage to make it work using the embedded version i am greatly interested ! 
It's not working for me as well.
Keep me updated please !

**Comment by mokbelt** [comment]
Couldn't work as UMD.
You need a whole build using the procedure in the documentation:
https://docs.ohif.org/deployment/recipes/build-for-production.html
