### ISSUE TITLE
From 0 to 1000 clicks a day;  OUCH!!

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#2211]
Hello All,

I had created a [post](https://github.com/OHIF/Viewers/issues/2194) regarding auto-play CINE images as soon as they are dragged/viewed into a viewport.  This feature was enabled by default and was working in version 1 of OHIF which I was using until now. 

I go thru around 20+/- studies a day which are all CINE and each study has around 50+ CINE series.  This has become a strenuous exercise in the recent version of OHIF where I have to manually click each series to play. This means I now have to click 20+/- studies TIMES 50+ series = 1000+/- click each day.

I created a [post](https://github.com/OHIF/Viewers/issues/2194) earlier requesting some help.  Mr. PoyangLiu **graciously** provided me some code snippet and guided me in the direction to make CINE images auto-play as soon as they are dragged/viewed into a viewport.  I know little programming.  I have been using Mr. PoyangLiu's generous code snippet along with my buggy code to make CINE auto-play but my efforts are failing.  

I was wondering if any generous coder could help me further in completing the code what Mr. PoyangLiu has suggested. This would be a life saver :).

Many thanks!! 
Ric

**Comment by sedghi** [comment]
If you have the CINE player running, and you drag and drop a thumbnail it should continue the play. And that is the current behaviour in the master branch
