### ISSUE TITLE
mouse events stop when cursor leaves window (MPR view)

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2214]
In the MPR view (vtk.js based) if you start an interaction, (e.g. grab a crosshair) and hold the mouse button down the tool is deactivated with the cursor leaves the tab boundary.

This is apparently a default behavior of vtk.js as reported by @mhalle here: https://github.com/Kitware/vtk-js/issues/1671

It must be possible to change this since the cornerstone tools versions of the same operations do not have this behavior.

**Comment by sedghi** [comment]
Thanks for the report Steve, Since we moved to cornerstone3D, I will close this issue
