### ISSUE TITLE
Error occurred when I use vtkRectangleWidget

### ISSUE THREAD

**Issue by StevenRoger** [OHIF/Viewers#2216]
### Describe the Bug

In View2D.js, I add the following code, when I enable painting(set props.painting to true), the viewport will crash with the error like the photo.

```js
this.rectangleWidget = vtkRectangleWidget.newInstance({
      resetAfterPointPlacement: false,
      useHandles: true,
});

......
this.viewWidget = this.widgetManager.addWidget(
      this.rectangleWidget,
      ViewTypes.SLICE
 );

this.widgetManager.grabFocus(this.rectangleWidget);
this.widgetManager.enablePicking();
this.genericRenderWindow.resize();
```
![image](https://user-images.githubusercontent.com/15900201/103082131-62742080-4614-11eb-8277-743edaf2e710.png)
![image](https://user-images.githubusercontent.com/15900201/103082155-715ad300-4614-11eb-89ce-9a5f2296621a.png)

**Comment by sedghi** [comment]
We don't have support for vtkRectangleWidget and it is not in the planning
