### ISSUE TITLE
NOT able to view generic tiff format in OHIF viewer

### ISSUE THREAD

**Issue by pawarjayesh1985** [OHIF/Viewers#2218]
We are NOT able to view the generic tiff format in OHIF viewer. 
WSI converted image to Dicom  http://openslide.cs.cmu.edu/download/openslide-testdata/Generic-TIFF/
using wsi2dcm tool and uploaded to GCP and tried to view that image from the OHIF viewer. But, is NOT showing anything

![image](https://user-images.githubusercontent.com/33840609/103287229-fb85ab80-4a07-11eb-80be-cdb79cf1c562.png)

We tried changing the extension version of "dicom-microscopy-viewer" from 0.6.1 to 0.22.1

We are getting following error:

"code: 17
message: "Assertion failed. See https://openlayers.org/en/v5.3.0/doc/errors/#17 for details."

Could you please help us know whether Generic tiff converted to dcm format is supported to be viewed OHIF viewer

**Comment by sedghi** [comment]
we don't have support for TIFF in OHIF (yet?), but in cornerstone3D there is a webimaagelaoder that you can take a look https://www.cornerstonejs.org/live-examples/webloader
