### ISSUE TITLE
Find active series all images are loaded?

### ISSUE THREAD

**Issue by kinsolutions** [OHIF/Viewers#2219]
please explain how to check selected series all images are loaded.  (or)
how to load all images after selected specific series without scroll or stack  

> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by olivert1969** [comment]
Hi @Hariprasathkin 
Below is a working OHIF configuration file. You can filter the study list by setting the number of days. Note that the length of results of the study list are also controlled by the underlying PACS, e.g. Orthanc uses "LimitFindResults" and "LimitFindInstances".

{
  "apps" : [{
    "name"        : "ohif-viewer",
    "script"      : "main.js",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/app/bundle/",
    "env": {
        "METEOR_SETTINGS": {
                  "servers": {
                    "dicomWeb": [
                                        {
                        "name": "Orthanc",
                        "wadoUriRoot": "http://orthanc:8042/wado",
                        "qidoRoot": "http://orthanc:8042/dicom-web",
                        "wadoRoot": "http://orthanc:8042/dicom-web",
                        "qidoSupportsIncludeField": false,
                        "imageRendering": "wadouri",
                        "thumbnailRendering": "wadouri",
                        "requestOptions": {
                          "auth": "demo:demo", 
                          "logRequests": true,
                          "logResponses": false,
                          "logTiming": true
                        }
                      }
                    ]
                  },
                  "defaultServiceType": "dicomWeb",
                  "public": {
                                "ui": {
                                        "studyListDateFilterNumDays": 7000
                                }
                        },
                  "proxy": {
                    "enabled": true
                  }
                }
    }
  }]
}

**Comment by sedghi** [comment]
We have stackPrefetch on by defualt which would do the trick for you. 
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
