### ISSUE TITLE
Error in loading  OT Modality file in ohif viewer

### ISSUE THREAD

**Issue by dhavalsolankislk** [OHIF/Viewers#2220]
Hello,

We are using dicom ohif in our application
We are getting following  below error in loading dicom file of Modality OT 

![OHIF](https://user-images.githubusercontent.com/59446200/103345573-bde05b80-4ab7-11eb-9888-399c8f75e86e.PNG)

Please help for the same
also attaching dicom file

[1.2.250.1.90.1.2867679910.1582958113.906 (1).zip](https://github.com/OHIF/Viewers/files/5753884/1.2.250.1.90.1.2867679910.1582958113.906.1.zip)

**Comment by dhavalsolankislk** [comment]
Any update ?

**Comment by sedghi** [comment]
They look correct in the current master 

![CleanShot 2023-10-13 at 10 51 59](https://github.com/OHIF/Viewers/assets/7490180/cd20fe3c-8616-4f2b-a817-b5901ecb3e97)
