### ISSUE TITLE
multiple SOPClassUIDs in the same series

### ISSUE THREAD

**Issue by olivert1969** [OHIF/Viewers#2221]
First, thanks @dannyrb, @swederik and team for this open source software. It is AMAZING.

FYI - in version 4.8.1, build 0 (from docker hub image) when viewing multiframe instances with CINE at 24 FPS, playback is very slow. As CINE steps through each frame, console issues warning "More than one SOPClassUID in the same series is not yet supported". This slowness and console warnings are not experienced in OHIF version 1.7 pointed against the exact same DICOMweb server (Orthanc 1.8.2 from docker hub image).

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
