### ISSUE TITLE
Reference line tool in ohif viewer (react)

### ISSUE THREAD

**Issue by kinsolutions** [OHIF/Viewers#2222]
Reference line tool available in ohif viewer? or any possibility to implement or enable.

**Comment by salimkanoun** [comment]
it's pending here
https://github.com/OHIF/Viewers/pull/1482
and here
https://github.com/OHIF/Viewers/tree/erik-ref-lines

Unfortunalty they didn't had the time to finished it yet.

**Comment by sedghi** [comment]
This is already done in master branch

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
