### ISSUE TITLE
Runtime error with hardware acceleration turned off in Chrome

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2223]
When opening this URL, I get the following errors:

https://idc-sandbox-000.firebaseapp.com/projects/idc-sandbox-000/locations/us-central1/datasets/sdp-dev/dicomStores/wsi-20210102/study/1.3.6.1.4.1.5962.99.1.3116129941.2022910149.1609433931413.3.0

![image](https://user-images.githubusercontent.com/313942/103489217-d1a1ff80-4de0-11eb-825c-c17b4bc149ef.png)

I turned off hardware acceleration due to runtime issues with Chrome (window turning completely blank). If hardware acceleration is required, is it possible to detect when it is turned off and notify the user?

**Comment by igoroctaviano** [comment]
@fedorov Libs like Mordernizr which specializes in feature detection lists hardware acceleration as "no reliable way to detect".
https://github.com/Modernizr/Modernizr/wiki/Undetectables

I think we can add an [error boundary](https://github.com/OHIF/Viewers/pull/2241) for the Microscopy Viewer instantiation which logs errors and shoot the message: ''Failed to load viewport. Please check that you have hardware acceleration enabled.". 

What do you think?

**Comment by fedorov** [comment]
Sounds reasonable - I think any update to make it more transparent to the user would help, since IDC users (for the most part) will not be developers looking into the dev console.

**Comment by fedorov** [comment]
Would it be possible to make the errors available in the popup after the popup disappears? This particular one stays on for a few seconds, and then disappears. Can errors be included in the debug info dialog?

**Comment by igoroctaviano** [comment]
> Would it be possible to make the errors available in the popup after the popup disappears? This particular one stays on for a few seconds, and then disappears. Can errors be included in the debug info dialog?

Not sure if I got the "..make the errors available in the popup after the popup disappears".  
You mean to leave the popup opened and let the user close it? If so, sure, just changing a flag

**Comment by fedorov** [comment]
Yes, it would be good to keep it open until the user closes it.

**Comment by igoroctaviano** [comment]
> Would it be possible to make the errors available in the popup after the popup disappears? This particular one stays on for a few seconds, and then disappears. Can errors be included in the debug info dialog?

Will be delivered here: https://github.com/OHIF/Viewers/pull/2283 (just waiting for Radical's review on it)
