### ISSUE TITLE
Facing CORS header error while integrating dcm4chee with OHIF viewer

### ISSUE THREAD

**Issue by ptt-bs23** [OHIF/Viewers#2226]
Hello! I am trying to integrate dcm4chee server in the OHIF viewer. I had success integrating **[this version of non secured dcm4chee](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host#optional-send-ct-images-to-the-archive-using-dcm4chedcm4che-toolsl)** which loaded my DICOM files properly. 

But when I am trying to inegrate **[this version of dcm4chee [secured version](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-secured-archive-services-on-a-single-host)**] in the same way, I am having the following error. 

`Access to XMLHttpRequest at 'http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies?limit=25&offset=0&fuzzymatching=false&includefield=00081030%2C00080060&StudyDate=19520727-20210106' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I am configuring it the same way like with the non secured dcm4chee version, where it worked.

**default.js** ( in the secured version where I am getting the error):

```
        wadoUriRoot: 'https://<my-local ip>:8443/dcm4chee-arc/aets/DCM4CHEE/wado',
        qidoRoot: 'https://<my-local ip>:8443/dcm4chee-arc/aets/DCM4CHEE/rs',
        wadoRoot: 'https://<my-local ip>:8443/dcm4chee-arc/aets/DCM4CHEE/rs',
```

**In this version, I get dcm4chee when I hit https://<my-local ip>:8443/dcm4chee-arc/ui2/**

I am attaching a screenshot of the console: 
![git1](https://user-images.githubusercontent.com/48043828/103737834-3053bd00-501d-11eb-960a-b60ad1c7d272.png)

- I have checked the network pane and nothing is loading in the page. 
- Returns me a blank page

Any help with this? I have tried to access with web browser extensions, but that didn't work either. 

Thanks in advance.

**Comment by ricardophp** [comment]
same problem!!!! please, could you solve it?

**Comment by olivert1969** [comment]
Hi @ptt-bs23 and @ricardophp,
In your webserver configuration, suggest adding Access-Control-Allow-Origin configuration. For specific examples, see: https://docs.ohif.org/deployment/recipes/nginx--image-archive.html#cors-issues

**Comment by reya276** [comment]
> Hi @ptt-bs23 and @ricardophp,
> In your webserver configuration, suggest adding Access-Control-Allow-Origin configuration. For specific examples, see: https://docs.ohif.org/deployment/recipes/nginx--image-archive.html#cors-issues

Well I don't think those Access configs work, at least not in Apache2. Bellow is my config for the vhost in Apache2 because I get the same CORS error as the person above.

`<Directory /var/www/html/dist>
    	<IfModule mod_headers.c>
    		Header add Access-Control-Allow-Origin "<iP>:8042"
    		Header add Access-Control-Allow-Origin "devdicom.<orgname>.com:8042"
			Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
			Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
			Header set Cache-Control "no-store"
		</IfModule>
    	allow from all
        Options None
        Require all granted
    </Directory>`

I've also tried using Header set Access-Control-Allow-Origin "*" and still no progress.

**CORS Error MSG:** 
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://devdicom.<orgname>.com:8042/dicom-web/studies?limit=25&offset=0&fuzzymatching=true&includefield=00081030%2C00080060. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)."

**Comment by elamathis18** [comment]
hi @ptt-bs23, were you able to get the workaround for the cors issue ? I am trying to build OHIF from scratch only and have added the changes in app-config.js but still to no avail.

**Comment by dem-v** [comment]
I was able to workaround this issue only by installing combined docker image of nginx + ohif + othanc and providing config for nginx from https://enable-cors.org/server_nginx.html

**Comment by sedghi** [comment]
Could you please review our comprehensive documentation on Cross-Origin Resource Sharing (CORS) and OHIF? Below are the links provided for your reference.

- https://docs.ohif.org/deployment/cors
- https://docs.ohif.org/deployment/iframe
