### ISSUE TITLE
Does the current program support displaying and modifying RT structure files? Can I see ROI?

### ISSUE THREAD

**Issue by goodsave** [OHIF/Viewers#2227]
Does the current program support displaying and modifying RT structure files? Can I see ROI?

**Comment by sedghi** [comment]
Display yes, not edit unfortunately. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
