### ISSUE TITLE
Integration with any Cloud Storage

### ISSUE THREAD

**Issue by varungandhi3** [OHIF/Viewers#2229]
Hi, Can we integrate this with any cloud storage? I do see it has been done with Google Cloud, but I want to know if its possible to do that. 

> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by olivert1969** [comment]
Hi @varungandhi3 
Yes, you can integrate OHIF with cloud storage. Specifically, if you use Orthanc as the DICOM PACS server, refer to these instructions https://book.orthanc-server.com/plugins/object-storage.html for details.

**Comment by sedghi** [comment]
Take a look here 

https://docs.ohif.org/deployment/google-cloud-healthcare
https://docs.ohif.org/configuration/dataSources/configuration-ui
