### ISSUE TITLE
JPEG 2000 tiles don't work in microscopy plugin

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2231]
This study was converted from SVS by @dclunie and has tiles in jp2k:

https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us-central1/datasets/tcia-idc-datareviewcoordination/dicomStores/DICOM_WSI-20210108/study/1.3.6.1.4.1.5962.99.1.3802655970.225997140.1610120457442.3.0

OHIF requests them as jpeg with this header:
`accept: multipart/related; type="image/jpeg"; transfer-syntax=1.2.840.10008.1.2.4.50`

But google responds with:
`generic::invalid_argument: image cannot be transcoded from 1.2.840.10008.1.2.4.91 to image/jpeg; transfer-syntax=1.2.840.10008.1.2.4.50, cause (internal only): generic::invalid_argument: com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: 
`

1.2.840.10008.1.2.4.91 is jp2k as documented here: http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_8.7.3.html

A suggested solution is that when the server says it cannot provide jpeg, we read the jp2k and convert it on the client using one of the codecs provided by @chafey.  Have not looked yet how easy or fast that would be.

**Comment by fedorov** [comment]
Should we move this issue under the Slim repo?

**Comment by pieper** [comment]
Yes, agreed.  done: https://github.com/MGHComputationalPathology/slim/issues/7
