### ISSUE TITLE
microscopy plugin should handle non-pyramid instances

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2232]
The WSI series can contain instances that are not part of the pyramid, such as a thumbnail or a picture of the slide label.  Currently OHIF silently ignores these.

Example data is here:
https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us-central1/datasets/tcia-idc-datareviewcoordination/dicomStores/DICOM_WSI-20210108

Possible we should show them in the series list as if they were different series or perhaps they should be selectable using a panel on the right, like segments are.

**Comment by Punzo** [comment]
Probably the best would be to show them as different series

**Comment by sedghi** [comment]
We upgraded the DMIV to very recent version, I'm wondering if this issue is resolved actually

**Comment by igoroctaviano** [comment]
@pieper now with SLIM, do we want to close this issue?

**Comment by igoroctaviano** [comment]
@pieper do we want to migrate this issue to SLIM?

**Comment by pieper** [comment]
Hi @igoroctaviano I think this one is obsolete.  I'm pretty sure Slim already handles this case by putting the label images to the side.  I'll close it but if you guys think it should be handled differently in DMV we can reopen or make a new issue.
