### ISSUE TITLE
tag browser unclear when working with WSI

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2233]
Since a WSI series contains multiple instances at different resolutions it's not clear which instance you are looking at for a particular pan/zoom setting and so you don't know how what the tag browser is showing relates to the image or how to get the tags for any particular instance (pyramid layer).

**Comment by sedghi** [comment]
@jbocce Not sure if our tag browser supports this, maybe try and update here our level of support?

**Comment by sedghi** [comment]
@IbrahimCSAE can you add the tag browser and see if we have support for it or not, should be a quick 5 min check
