### ISSUE TITLE
Unable to Run OHIF Viewer in the Window 10 Pro

### ISSUE THREAD

**Issue by Webrusterkk** [OHIF/Viewers#224]
Steps i tried (I have preinstalled with the Docker)
1. Open Terminal , and move to the Folder Project (i.e. Viewers/OHIFViewer)
2. Run `set PACKAGE_DIRS=..\Packages`
3. Run `meteor --settings ../config/orthancDICOMWeb.json`

after above process im getting the following error:

> => Started proxy.
> => Errors prevented startup:
> 
>    While selecting package versions:
>    error: unknown package in top-level dependencies: ohif:polyfill
>    unknown package in top-level dependencies: ohif:core
>    unknown package in top-level dependencies: ohif:commands
>    unknown package in top-level dependencies: ohif:hotkeys
>    unknown package in top-level dependencies: ohif:header
>    unknown package in top-level dependencies: ohif:cornerstone
>    unknown package in top-level dependencies: ohif:cornerstone-settings
>    unknown package in top-level dependencies: ohif:viewerbase
>    unknown package in top-level dependencies: ohif:study-list
>    unknown package in top-level dependencies: ohif:dicom-services
>    unknown package in top-level dependencies: ohif:hanging-protocols
>    unknown package in top-level dependencies: ohif:metadata

**Comment by Webrusterkk** [comment]
I figured it out ..

Tried with the bat file in the Folder using powershell and issue got resolved

**Comment by alaradi2006** [comment]
i have the same issue how did you fix it 
can you send me some guide
