### ISSUE TITLE
Ability to specify transfer syntax

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#2242]
## Request

**What feature or change would you like to see made?**

It is currently not possible to specify a transfer syntax when requesting images from a server. I would be great if this option could be added.
...

**Why should we prioritize this feature?**

On lower bandwidth connections specifying a compressed syntax would speed up transfers and make the application more usable.
...

**Comment by salimkanoun** [comment]
Yes it could be a way as Orthanc is supporting transcoding (I guess DCM4CHE as well).

The other way would be to activate zip compression in your http server, zipping already decrease size of dicomweb apis by half, so you will have a close compression than transcoding does.

**Comment by sedghi** [comment]
This has recently been added to configuration file https://docs.ohif.org/configuration/configurationfiles/#configuration-files
