### ISSUE TITLE
Unable to display study list after anonymizing using Google Healthcare API

### ISSUE THREAD

**Issue by jasonklotzer** [OHIF/Viewers#2249]
## Bug Report

Unable to display study list after anonymizing using Google Healthcare API

### Describe the Bug

_When using the [de-id functionality](https://cloud.google.com/healthcare/docs/how-tos/dicom-deidentify) on a DICOM store in the Google Healthcare API, certain tags that are used in the QIDO-RS DICOMweb query are removed from the DICOM metadata. This includes the StudyDate. The OHIF query for study list relies directly on StudyDate when no parameters are entered and uses a default value, which yields no results._

### What steps can we follow to reproduce the bug?

1. Create a de-id store using the Google Healthcare API using the DEIDENTIFY_TAG_CONTENTS profile.
2. Deploy OHIF and associate with the Dicom Store as described [here](https://docs.ohif.org/connecting-to-image-archives/google-cloud-healthcare.html)
3. Notice the study list shows nothing.

**Comment by jasonklotzer** [comment]
I have a fix for this as well (removing the default date values), which I'd like to PR.

**Comment by swederik** [comment]
I'm fine with removing that code that appears to be setting a default. There is supposed to be a config value for it anyway named studyListDateFilterNumDays: https://github.com/OHIF/Viewers/search?q=studyListDateFilterNumDays
