### ISSUE TITLE
Failure to load a valid SEG object due to incorrect expectations about ReferencedSegmentNumber

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2252]
This study fails:

https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc-tcia/dicomStores/idc-tcia/study/1.3.6.1.4.1.14519.5.2.1.4334.1100.123677133754901543013105036670

With this error:

![image](https://user-images.githubusercontent.com/313942/105648482-aeb3ba00-5e79-11eb-9637-a82af2b28737.png)

It is allowed not to have ReferencedSegmentNumber, see https://dicom.innolitics.com/ciods/segmentation/general-reference/00081140/0062000b. dciodvfy does not complain about it either, and Slicer can load that seg.

**Comment by igoroctaviano** [comment]
@fedorov I was debugging this issue and the code expects the following:

```
const segmentIndex =
            PerFrameFunctionalGroups.SegmentIdentificationSequence
                .ReferencedSegmentNumber;
```

According to innolitics: https://dicom.innolitics.com/ciods/segmentation/segmentation-multi-frame-functional-groups/52009229/0062000a/0062000b

The Referenced Segment Number Attribute under Segment Identification Sequence Attribute is a type 1 required, the one you mentioned is under Purpose of Reference Code Sequence Attribute which is optional.

**Comment by fedorov** [comment]
@igoroctaviano thank you, you are correct!

**Comment by fedorov** [comment]
I think it might make sense to check the number of segments, and accept the object that does not have a reference when that number is 1, but I definitely will understand your reluctance to add this special case. Let me know your thoughts.

**Comment by fedorov** [comment]
Meanwhile, I will contact the authors of that data and check if they would be willing to update the actual dataset.

**Comment by igoroctaviano** [comment]
> I think it might make sense to check the number of segments, and accept the object that does not have a reference when that number is 1, but I definitely will understand your reluctance to add this special case. Let me know your thoughts.

This will be a dcmjs change, it's a very small change if we want to add this case (checking the number of segs). Let me know if I should proceed with the update.

**Comment by fedorov** [comment]
Somehow, both of us missed that - ReferencedSegmentNumber IS available in the shared FG, and it does not need to be replicated in the per-frame FG. This is a bug in OHIF, after all.

**Comment by igoroctaviano** [comment]
> Somehow, both of us missed that - ReferencedSegmentNumber IS available in the shared FG, and it does not need to be replicated in the per-frame FG. This is a bug in OHIF, after all.

Good catch. PR opened in dcmjs: https://github.com/dcmjs-org/dcmjs/pull/166
