### ISSUE TITLE
Error 'does not contain a default export (imported as 'PaintFilterWorker')' when i import method from 'react-vtkjs-viewport'

### ISSUE THREAD

**Issue by comadaihiep92** [OHIF/Viewers#2257]
> **Before Creating an issue**
>
> - Are you running the latest version? Yes
> - Are you reporting to the correct repository? Yes
> - Did you search existing issues? Yes

### Describe the Bug

i use create-react-app and use this module. But when i import it will show this error:
```
import {
    vtkInteractorStyleMPRCrosshairs,
    vtkInteractorStyleMPRWindowLevel,
    vtkInteractorStyleMPRSlice,
    vtkInteractorStyleMPRRotate,
    vtkSVGCrosshairsWidget,
    vtkSVGWidgetManager,
  } from 'react-vtkjs-viewport';
```

Please help me fix this issue.
```
"react-vtkjs-viewport": "^0.14.2",
"vtk.js": "^16.1.1"
```
```
"scripts": {
    "start": "rescripts start",
    "build": "rescripts build",
    "test": "rescripts test",
    "eject": "rescripts eject"
  },
```
Please use code blocks to show formatted errors or code snippets
```js

./node_modules/vtk.js/Sources/Filters/General/PaintFilter/index.js
Attempted import error: 'vtk.js/Sources/Filters/General/PaintFilter/PaintFilter.worker' does not contain a default export (imported as 'PaintFilterWorker').

**Comment by muakdogan** [comment]
Any update on this issue? Have the exact same problem. I also tried with vtk.js@11.14.0 because it was configured that way in react-vtkjs-viewport's package.json but didn't help.

**Comment by gzt036** [comment]
PaintFilterWorker is missing and I cannot find it anywhere in the source directory.

**Comment by sedghi** [comment]
we have added segmentation editing tools and you can find it in latest master. Read more https://ohif.org/release-notes/3p7
