### ISSUE TITLE
Mechanism to communicate to the users inconsistencies within a single series

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2259]
Example series that motivate some discussion what should be done:

*  https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.8162.4009.498881901170332065029863238265 - first instance is a localizer
* https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.8162.4009.498881901170332065029863238265?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.8162.4009.329297441360267384643622758743-  one series has 2 subvolumes with different slice and pixel spacing

At the moment, OHIF Viewer does not have any indication about those inconsistencies, and presents the slices as if they belong to a single continuous volume.

![image](https://user-images.githubusercontent.com/313942/106286951-39970a80-6214-11eb-893a-d83ccc7272d5.png)

**Comment by Punzo** [comment]
have a little icon on the series to have a dialog overlay text box that reports any issue in the data (different spacing, etc....).
Tell the user also if you can have MPR button or not and why.

**Comment by Punzo** [comment]
PR in review https://github.com/OHIF/Viewers/pull/2331

**Comment by fedorov** [comment]
@Punzo the series in this study

![image](https://user-images.githubusercontent.com/313942/113185008-e6e1cb00-9223-11eb-9c4f-89cd360af456.png)

https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc/dicomStores/v2/study/1.3.6.1.4.1.14519.5.2.1.7695.1700.320115820687123759708360318530

is indicated as having inconsistent spacing, but I do not see those inconsistencies. Maybe a rounding issue, or something else?

![image](https://user-images.githubusercontent.com/313942/113185067-fc56f500-9223-11eb-8c3d-c028b3557612.png)

**Comment by Punzo** [comment]
ok, I will double check the spacing check and the data. I would also expect a tolerance issue (at the moment there is a 10% tolerance).

**Comment by fedorov** [comment]
@Punzo as I just realized, the indicator of the problem with a series is located in the list on the left, and the connection between what is shown in the viewer to the specific series on the left is subtle (series number). Did you guys think about some more prominent indication of what series is shown in the viewer from the list on the left? (e.g., highlighted boundary or something), or whether it makes sense to show the "warning" icon in the corner of the viewer, not just in the series thumbnails list?

**Comment by Punzo** [comment]
@fedorov  I would say that highlighted boundaries for the thumbnails of series currently shown in the viewport is a good idea and the way to go. 

I would open a new ticket since the implementation is not straightfoward, e.g. when having multiple viewports should we highlighted only the ones in connected with the active viewport or all the viewports? (probably just of the active one).

**Comment by fedorov** [comment]
To confirm, showing the warning icon in the corner of the viewer for the problematic series, in addition to showing it in the thumbnail view, is also not trivial?

**Comment by Punzo** [comment]
> To confirm, showing the warning icon in the corner of the viewer for the problematic series, in addition to showing it in the thumbnail view, is also not trivial?

I would have to look at the react elements for the view, so unless @igoroctaviano can provide insights, I would create an new issue (you may assing it to me and I can work on it tomorrow since I just finalized now the deconding/blending API PR for slim).

**Comment by igoroctaviano** [comment]
The image thumbnail already has some logic for highlighting the active series, I think something broke this style. We just need to debug and fix the problem.

**Comment by Punzo** [comment]
as discussed in the call we will do both. i.e.:  
1) add the warning icon on the active viewport as an overlay
2) highlight with a larger border the thumbnails of the current active series (i.e. series in the current active viewport)
