### ISSUE TITLE
JSON metadata multiframe example

### ISSUE THREAD

**Issue by shlomgad** [OHIF/Viewers#2262]
Hello,
Using the  /viewer?url= mechanism to load a JSON manifest.
My build renders single frame images correctly, but multiframe images are rendered in a bizarre way, as if all frames are rendered on top of each other (screenshot attached, very artistic result, but not very useful :-) )
Can you please add a note or an example how to refer to multiframe instances in the JSON example on issue  #1500 .
Thanks!

![Screenshot 2021-01-30 090755](https://user-images.githubusercontent.com/352509/106349983-20a55c80-62db-11eb-82a9-d1a72802cb19.png)

**Comment by sedghi** [comment]
Have you populated the url link correctly for the JSON? 
For each frame you need to add `?frame={frameIndex}` at the end (Note: frameIndex starts from 1)

example:  "url": "dicomweb:http://localhost:3000/multiframe/MR-MONO2-8-16x-heart?frame=1"

**Comment by shlomgad** [comment]
Thank you for the suggestion.
I have created separate json metadata entry for each frame as above - but still it looks like all frames are rendered on top of each other.

**Comment by shlomgad** [comment]
Turns out the overlapping display was related to issue #2420 .
Adding the Planar Configuration tag to the JSON solved that.
However, still no luck in displaying the multiframe images. Seems that adding &frame={frameIndex} at the end of the url is not doing the trick.

**Comment by arturojain** [comment]
Was there any progress on this?

**Comment by sedghi** [comment]
@shlomgad Do you think this still happens in the latest master branch?

Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by shlomgad** [comment]
This is displayed correctly in the recent V3-stable branch.

**Comment by kinsolutions** [comment]
Could you please share with me an example DICOM JSON file for multiframe? I have tried viewing it, and it shows the number of instances based on the number of frames, but when I scroll, it's not loading the next frame. Could you please suggest if there's anything I missed?

![image](https://github.com/OHIF/Viewers/assets/76163293/4d247884-5f09-4fe6-9a9e-1643dfa8c7b7)
