### ISSUE TITLE
Env variable PUBLIC_URL is ignored for output file manifest.json on build

### ISSUE THREAD

**Issue by shlomgad** [OHIF/Viewers#2263]
Steps to reproduce:

1. export PUBLIC_URL=/ohif2/
2. yarn run build

Resulting manifest.json links (example):
 "src": "/assets/android-chrome-36x36.png" should be "src": "/ohif2/assets/android-chrome-36x36.png"

**Comment by PoyangLiu** [comment]
Relates to #1125

**Comment by salimkanoun** [comment]
same as #1925
