### ISSUE TITLE
Error on measurement start

### ISSUE THREAD

**Issue by shlomgad** [OHIF/Viewers#2264]
1. Build as usual (yarn run build).
2. Deploy build results on webserver.
3. Load a dicom instance using /viewer?url=<link to JSON file>
>>Image is rendered correctly.
4. Click the Length measurement tool and start measuring.
5. Following console output and TypeError is thrown:

```
MeasurementService.js:305 Measurement ID not found. Generating UID: d175244c-91a9-ad1c-40f5-cdce004d2df5
value @ MeasurementService.js:305
addOrUpdate @ MeasurementService.js:133
(anonymous) @ init.js:247
(anonymous) @ init.js:270
r @ cornerstoneTools.js:37882
u @ cornerstoneTools.js:11524
t.default @ cornerstoneTools.js:3717
t.default @ cornerstoneTools.js:3969
r @ cornerstoneTools.js:37882
h @ cornerstoneTools.js:5768
MeasurementService.js:326 Measurement added. {id: "d175244c-91a9-ad1c-40f5-cdce004d2df5", SOPInstanceUID: "1.3.12.2.1107.5.1.4.78305.30000021012105263971600029940", FrameOfReferenceUID: "1.3.12.2.1107.5.1.4.78305.30000021012104511285400009745", referenceSeriesUID: "1.3.12.2.1107.5.1.4.78305.30000021012105263971600029627", label: undefined, …}
handleSingleMeasurementAdded.js:25 CornerstoneToolsMeasurementAdded

**TimepointApi.js:515 Uncaught TypeError: Cannot read property 'includes' of undefined
    at TimepointApi.js:515**
    at Array.filter (<anonymous>)
    at e.value (TimepointApi.js:514)
    at e.value (MeasurementApi.js:696)
    at at (handleSingleMeasurementAdded.js:34)
    at Object.onAdded [as added] (index.js:46)
    at i (init.js:39)
    at r (cornerstoneTools.js:37882)
    at u (cornerstoneTools.js:11524)
    at t.default (cornerstoneTools.js:3717)
```
The measurement appears on the image, but not saved to the measurements list.

**Comment by pmd23** [comment]
@shlomgad I am also facing the same issue. while applying the new measurement tools on image. 

I am using latest viewer which is available on npm.

**Comment by pmd23** [comment]
any update on this I am stuck here.

**Comment by shlomgad** [comment]
Unfortunately no update.

**Comment by ericmil87** [comment]
Any update on this yet?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
