### ISSUE TITLE
Can the viewer add the function of batch downloading jpg images?Download the image of one series or the whole study at a time

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#2265]
Now the viewer can only download one JPG image at a time. If I need the images of the whole study, downloading will be a difficult job. 
Can the viewer add the function of batch downloading jpg images?Download the image of one series or the whole study at a time.

**Comment by JiangWeian** [comment]
@dannyrb @swederik, Is there a way to do this? And there is an error in the function of downloading JPG image:
![TIM图片20201211161511](https://user-images.githubusercontent.com/56569509/106682096-be12d000-65fc-11eb-8945-77ecef41cfd1.png)

**Comment by andreiSeer** [comment]
Any luck?

**Comment by sedghi** [comment]
We currently do not have it implemented, and it is not currently in our planning.
