### ISSUE TITLE
How to display a bitmap segmentation with brushtool?

### ISSUE THREAD

**Issue by bnbn860904** [OHIF/Viewers#2270]
Hello, I have a question for you
I want to implement the function of this article on the OHIF viewer, but I have not succeeded
https://github.com/cornerstonejs/cornerstoneTools/issues/895
The following is the code I added in \extensions\cornerstone\src\commandsModule.js

	draw_test : ({ viewports }) => {
		
		
		const brushTool = cornerstoneTools.BrushTool;
        const element = getEnabledElement(viewports.activeViewportIndex);
        if (!element) {
          return;
        }
		const enabledElement = cornerstone.getEnabledElement(element);
		
		console.log(element);
		
		cornerstoneTools.setToolActive('Brush', { mouseButtonMask: 1 });
		
		var width = 600;
		var height = 600;
		var channel = 1;
		let pixelData = new Uint8ClampedArray(width * height * channel);
		for (let i = 0; i < 500; i++) {
			for (let j = 0; j < 500; j++) {
				pixelData[i*width + j] = 1;
			}
		}
		let toolState = cornerstoneTools.getToolState(enabledElement.element,'Brush');		
		console.log(pixelData);
		
		if (toolState) {
			toolState.data[0].pixelData = [...pixelData];
			
		} else {
			cornerstoneTools.addToolState(enabledElement.element,'Brush',{ pixelData });
			toolState = cornerstoneTools.getToolState(enabledElement.element,'Brush');
			
		}
		
		toolState.data[0].invalidated = true;
		
		cornerstone.updateImage(enabledElement.element);

Sorry for wasting your time
Thank you

**Comment by sedghi** [comment]
You can take a look at our latest release which ships segmentation support  https://ohif.org/newsletters/2023-07-12-ohif%20viewer%20v3.7%20with%20segmentation%20editing%20tools--release-note3p7
