### ISSUE TITLE
Asking for help on how to implement Cobb's Angle

### ISSUE THREAD

**Issue by akosijoy** [OHIF/Viewers#2271]
Hello,

I was hoping to ask for instructions on how to implement the Cobb's Angle feature for the Meteor version of OHIF Viewer. I managed to add a button to the toolbar but beyond that I'm very confused and unsure how to proceed. By using ctrl+f on the project folder I think the important files are in 

(added the button here)
/OHIFViewer/client/components/toolbarSection/toolbarSection.js 

(searched for the terms simpleAngle to find the other tools)
/Packages/ohif-viewerbase/client/lib/toolManager.js
/Packages/ohif-viewerbase/client/components/viewer/toolContextMenu/toolContextMenu.js
/Packages/ohif-viewerbase/client/components/viewer/

(searched for the term cobb)
/ohif-cornerstone/.npm/package/node_modules/cornerstone-tools/dist/cornerstoneTools.js
found this comment on this file
// Need to work on correct angle to measure.  This is a cobb angle and we need to determine
// Where lines cross to measure angle. For now it will show smallest angle.

Based on some google searches and from what I've seen in the code, I've seen variables named like simpleAngle, angle, or cobbAngle. But in the code there are also lines like "simpleAngle: 'Angle'," (in /Packages/ohif-viewerbase/client/components/viewer/toolContextMenu/toolContextMenu.js). So I really don't know how to start.

**Comment by sedghi** [comment]
Cobb-angle has been implemented in CornerstoneTools
You can take a look here: https://tools.cornerstonejs.org/examples/tools/cobb-angle.html
