### ISSUE TITLE
WebImages with JSON launch

### ISSUE THREAD

**Issue by drsherifk** [OHIF/Viewers#2275]
How about adding support of webimageloader to JSON launch.
All metadata values are passed through the JSON file, why not using just JPG files instead of dicom as long as we don't need the dicom tags inside image files any more.

> :hand: Many people requests features. Tell us why yours is important to the
> community. How does it add value? Why _this feature_?

It will make the viewer fast and simple.
You can preview WebImages natively in the storage or batch. Download it.
Less bandwidth & fast loading.

**Comment by sedghi** [comment]
I don't think we have that right now and it is not in planning
