### ISSUE TITLE
ROI/segmentation drawing tools and saving/loading

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [OHIF/Viewers#2278]
**Description**

Hi, I am new to OHIF and my team is investigating its use for a web-based application we'd like to develop.
Ideally we would use OHIF for users to view images and draw ROIs/segmentations which would be fed to a processing backend. We'd also like to be able to save them (separately from the image itself, as e.g. NIfTI or some format convertible to it like DICOM-Seg) and load/re-load them into the viewer(preferably programmatically). 

I tried looking at test drive demo and at the maintained extensions list (under https://docs.ohif.org/extensions/#maintained-extensions) but unfortunately from these I was not able to determine if these features exist.

Some searching indicates that some functionality has been tackled before (e.g. [this request](https://github.com/OHIF/Viewers/issues/230) which seems to be directly related, or [this issue](https://github.com/cornerstonejs/cornerstoneTools/issues/895)). 

While we are potentially open to developing an extension for this purpose, I would first like to know which of the above functionalities currently exist, if any, or if anybody could point me in the right direction.

Thanks, and please let me know if I should provide any additional information.

**Comment by FeryET** [comment]
Is there any progress regarding this feature? I am looking for a segmentation extension but apparently the dicom segmentation extension is currently only read only.

**Comment by leonfedden** [comment]
Hi folks - as mentioned in another issue my team at AZ is keen to add support for writing segmentations, perhaps as DICOM-SR, in a similar way to writing measurements to DICOM-SR. Does anyone know who would be good to speak to get an understanding of how to tackle this problem? We are happy to provide resources. 

cc @sedghi @AlexanderGetka-cbica @FeryET 

Please see my other comment here: https://github.com/OHIF/Viewers/issues/1934#issuecomment-1459987176

**Comment by pieper** [comment]
For reference, this project discusses reading/writing various datatypes in DICOM: https://dicom4qi.readthedocs.io/en/latest/ 

Here's a prototype of segmentation writing with dcmjs and cornerstone that could be the basis for an updated OHIF implementation: https://github.com/dcmjs-org/dcmjs/blob/master/examples/createSegmentation/index.html

Great to hear there are people interested in this topic - it will be great to see progress 👍

**Comment by sedghi** [comment]
@leonfedden Hey, Can you explain a bit more about how you want to encode segmentation inside DICOM SR?

**Comment by sedghi** [comment]
We have just released the segmentation editing tools. Take a look at them and if they don't meet your requirements, please provide us with updated details and reopen the issue. https://ohif.org/release-notes/3p7
