### ISSUE TITLE
Evaluate coverage of transfer syntaxes in IDC against OHIF capabilities

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2279]
Use BQ first to select representative cases, check coverage of transfer syntaxes in IDC by OHIF Viewer.

**Comment by fedorov** [comment]
Transfer syntaxes encountered in IDC collections (TCIA copy circa Summer 2020), with sample URLs, in the order of frequency of occurrence:

* 1.2.840.10008.1.2.1 Explicit VR Little Endian [sample](https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.3023.4012.101052098274837556406391462169?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.3023.4012.323683894073974637495373822467)
* 1.2.840.10008.1.2  VR Little Endian [sample](https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.3671.4007.159710065345539879485697628124?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.3671.4007.116995303901003029157521331470)
* 1.2.840.10008.1.2.2 Explicit VR Big Endian [sample](https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.4801.5885.239036450629614749201868579487?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.4801.5885.217177159229468186711891185673)
* 1.2.840.10008.1.2.4.70 JPEG Lossless, Non-Hierarchical, First-Order Prediction(Process 14 [Selection Value 1]) [sample](https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.3344.4020.116408330611973657376506223107?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.3344.4020.171639628979300860440520160292)

According to http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_8.7.3.html, "The Implicit VR Little Endian (1.2.840.10008.1.2), and Explicit VR Big Endian (1.2.840.10008.1.2.2 - Retired) Transfer Syntaxes shall not be used with Web Services."

**Comment by fedorov** [comment]
TODO: update this cross-checking with the updated content of IDC.

**Comment by sedghi** [comment]
@igoroctaviano  @fedorov Do you guys have any documentation on this so that I can add it to our docs on what we support?

**Comment by igoroctaviano** [comment]
@sedghi do we have a conformant statement for OHIF?

**Comment by fedorov** [comment]
> Do you guys have any documentation on this so that I can add it to our docs on what we support?

@sedghi can you let me know what you mean by "this" in the above?

**Comment by sedghi** [comment]
we recently added the statement
https://docs.ohif.org/conformance
