### ISSUE TITLE
Regression in support of SEG

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2280]
The problem is described in this issue https://github.com/dcmjs-org/dcmjs/issues/177, but I don't think it has been captured in the OHIF tracker.

Can we make sure this gets into this week's IDC release?

cc: @wlongabaugh

**Comment by igoroctaviano** [comment]
@fedorov fixed here: https://github.com/dcmjs-org/dcmjs/pull/179

**Comment by fedorov** [comment]
Has sandbox been updated to have this fix?

Is everything done to make sure this fix gets into the upcoming IDC release this week?

**Comment by igoroctaviano** [comment]
> Has sandbox been updated to have this fix?
> 
> Is everything done to make sure this fix gets into the upcoming IDC release this week?

First we need @pieper to merge it / release, then ill create a bump merge request for idc sandbox.

**Comment by pieper** [comment]
The dcmjs change is merged, but @igoroctaviano if you don't see a new npm version can you make a dummy semantic version commit to trigger the package?

**Comment by wlongabaugh** [comment]
Let me know when a fix is merged into master and works, and I will forward to test as well.

**Comment by igoroctaviano** [comment]
> The dcmjs change is merged, but @igoroctaviano if you don't see a new npm version can you make a dummy semantic version commit to trigger the package?

@pieper https://github.com/dcmjs-org/dcmjs/pull/180 here

**Comment by fedorov** [comment]
Test tier works fine with 4.9.7.
