### ISSUE TITLE
RTStruct tab not visible on the IDC viewer production tier

### ISSUE THREAD

**Issue by madelyngreyes** [OHIF/Viewers#2288]
### Describe the Bug

On the IDC portal when selecting a study with RTStruct data visible the tab to view RTStruct data does not appear.

### What steps can we follow to reproduce the bug?

1. open the explore page on the IDC
2. open a study with RTStruct data
3. No RTStruct tab is visible on the right hand side 

<img width="1429" alt="Screen Shot 2021-03-03 at 10 38 51 AM" src="https://user-images.githubusercontent.com/16824894/109832842-c0be1080-7c0e-11eb-919f-2de1bdc5b547.png">

**Comment by igoroctaviano** [comment]
@pieper @fedorov looks like this is related to https://github.com/dcmjs-org/dcmjs/issues/177
This ticket can be revisited after a new deployment. I'll comment here when it's available in the sandbox.

**Comment by igoroctaviano** [comment]
@Punzo can you please review this one? https://github.com/OHIF/Viewers/pull/2307

**Comment by fedorov** [comment]
Confirmed working in 4.9.7 in test tier.
