### ISSUE TITLE
Image load slowness regression

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2289]
https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.1706.4009.243406849348906151042089406192?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.1706.4009.304054433668574201838767925472 mentioned in https://github.com/OHIF/Viewers/issues/2192 used to load in the past, but not anymore.

Related to this, can we discuss the options for testing approaches to identify this kind of regressions, or at least have a way to measure load of a series to facilitate manual testing?

**Comment by pieper** [comment]
This is another scaling issue, probably due to the large number of requests.  Several of the frames have very long load times:
![image](https://user-images.githubusercontent.com/126077/109842422-11863700-7c18-11eb-8610-0c60da278c36.png)

**Comment by fedorov** [comment]
adding @wlongabaugh

**Comment by Punzo** [comment]
I did some debugging and I could reproduce that when scrolling the image the _isDisplaySetReconstructable is called in an almost infinite loop and since in _isDisplaySetReconstructable we do "heavy" checks (i.e.: https://github.com/OHIF/Viewers/commit/b59187c74dfd91fc886ef0314809b097c5f84006 ) the interface gets stucked. We could find better heuristics for the checks in _isDisplaySetReconstructable (but they are actaully pretty fast < 1 sec). @igoroctaviano do you have any idea why _isDisplaySetReconstructable is called so many times? should it just be called once at initialization?

**Comment by Punzo** [comment]
I think having test for checking the viewer loading time will be difficult: the reproducibility can be low and produce easly false negative, since the general loading of the viewer can heavly depends on the donwload time of the data.

But definitely we should have tests checking the viewer components updates. @igoroctaviano are these type of tests already in place?

**Comment by igoroctaviano** [comment]
@Punzo you could use tools like profiler to keep track of how long that function took to execute and take notes. I think component rendering should be the last resort considering that the majority of studies load fine.

**Comment by Punzo** [comment]
sure, I can mesaure the perfomances. But again my point is that calling N multiple times (where N is actually pretty large) the function VTKMPRToolbarButton everytime we scroll (still have to check if it happens with other interactions) an image does not make any sense.

**Comment by Punzo** [comment]
I analized the perfomances and in teh case of 512x512x3000 voxels _isDisplaySetReconstructable takes 7 sec to run. It is long, but at the moment we don't have better heuristic and we have to make a sequantial double loop for. Also the total time spent is mostly _isDisplaySetReconstructable so definitevely the slowness  issue is there. 

A better heuristic would be checking 4D tags, e.g. the presence of multiple TemporalPositionIdentifier values. However, some studies (e.g. https://github.com/OHIF/Viewers/issues/2113) do not have such tags. So, assuming that slices at different time have the same position, at the moment we just check if there are multiple slices for the same ImagePositionPatient and disable MPR.

I still believe taht we should call _isDisplaySetReconstructable only once when we load the study/series and not N times everytime we do an interaction with the view.

**Comment by Punzo** [comment]
Just noticed/realized that there is already one PR https://github.com/OHIF/Viewers/pull/2274 , which should solve this (exactly calculating _isDisplaySetReconstructable only once and save it as a flag). @racacere @swederik what is the status of the PR?

**Comment by racacere** [comment]
@Punzo Hi, I submitted that PR a couples of weeks ago, but it haven't be reviewed yet. However, at my workplace we have been using this solution on our [public OHIF fork](https://gitlab.nursoft.cl/foss/ohif-viewer) for a while and it works quite well.

**Comment by fedorov** [comment]
> A better heuristic would be checking 4D tags, e.g. the presence of multiple TemporalPositionIdentifier values. However, some studies (e.g. #2113) do not have such tags. 

I am afraid there may be no robust alternative in the existing data to checking for overlapping frames.

But we could precompute "is 4D" flag for each series on IDC. It would not be in DICOM. Should we even consider this as an approach?

**Comment by pieper** [comment]
> But we could precompute "is 4D" flag for each series on IDC. It would not be in DICOM. Should we even consider this as an approach?

Fixing it in OHIF makes much more sense to me.

**Comment by fedorov** [comment]
Sorry for the confusion, I meant doing that in addition to fixing repeated 4D checking in OHIF.

**Comment by Punzo** [comment]
> @Punzo Hi, I submitted that PR a couples of weeks ago, but it haven't be reviewed yet. However, at my workplace we have been using this solution on our [public OHIF fork](https://gitlab.nursoft.cl/foss/ohif-viewer) for a while and it works quite well.

perfect, I will test and review. @igoroctaviano could you also review the PR, please?



> Fixing it in OHIF makes much more sense to me.

I agree.



> Sorry for the confusion, I meant doing that in addition to fixing repeated 4D checking in OHIF.

for sure we can add a 4d tags in IDC data, but I remind a couple of conversations that we didn't want to add custom IDC specific metadata outside from the DICOM standard in the data (we had this conversaion for the overlapping segmentation). 

I would say once we merge the @racacere PR, the viewer should be responsive again and we can properly test again and see if we need to boost the perfomance with precomputed tags or not.

**Comment by fedorov** [comment]
Looks much better in 4.9.7! Instructions for performance regression testing have been added to IDC Viewer test docs, so closing this issue.
