### ISSUE TITLE
Simple web page

### ISSUE THREAD

**Issue by gittrolo** [OHIF/Viewers#2292]
how to create a simple web page with the Embedded Viewer  that reads files locally (DICOM folder with DICOMDIR file)

**Comment by sedghi** [comment]
You can take a look at example here
https://docs.ohif.org/deployment/

**Comment by gittrolo** [comment]
Thanks, 
i saw the guide, but i can't get it to work .

i have this folder under my web server 
/dicom
      |___ index.html
      |___ dicom.json
      |___ 44508106.dcm

is a simple html you can see it inside dicom.zip

But when I recall the address http://127.0.0.1/dicom/?url=http://127.0.0.1/dicom/dicom.json , it does not read json file studies 

[dicom.zip](https://github.com/OHIF/Viewers/files/6103698/dicom.zip)

**Comment by sedghi** [comment]
I'm seeing you are using an old ohif viewer
use this `https://unpkg.com/@ohif/viewer@4.9.0/dist/index.umd.js` and then things should work out for you

**Comment by gittrolo** [comment]
Does not work. perhaps we need to eliminate this section of code:
  servers: {
                    dicomWeb: [
                        {
                            name: 'DCM4CHEE',
                            qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
                            wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
                            qidoSupportsIncludeField: true,
                            imageRendering: 'wadors',
                            thumbnailRendering: 'wadors',
                        },
                    ],

if so, what should you put in the servers variable

**Comment by sedghi** [comment]
I'm not sure how you are serving it or the structure of the app, but you should use something like
`http://localhost:5000/viewer?url=http://localhost:5000/dicom.json`, you don't have **viewer** in the url

**Comment by gittrolo** [comment]
URL Without viewer  

![image](https://user-images.githubusercontent.com/52664193/110382418-2bca7580-805b-11eb-9a56-6c31f10d390e.png)


URL With viewer  

![image](https://user-images.githubusercontent.com/52664193/110382498-4866ad80-805b-11eb-984b-c0e88c877b37.png)

**Comment by sedghi** [comment]
Can you put everything in the dicom folder, serve that specific folder, so that everything appears in the root? and then use you url without the `/dicom` parts:
`http://127.0.0.1/viewer?url=http://127.0.0.1/dicom.json`

**Comment by gittrolo** [comment]
My public hosting web is like this https://www.mysite/dicom.
I don't have permissions to access the apache server configuration. The only thing I can do is upload the files inside the dicom folder via sftp .
Is it possible that the viewer cannot work with domains that contain subfolders?

**Comment by anarnoli** [comment]
> Can you put everything in the dicom folder, serve that specific folder, so that everything appears in the root? and then use you url without the `/dicom` parts: `http://127.0.0.1/viewer?url=http://127.0.0.1/dicom.json`

Hi @sedghi, I am struggling with that same situation right now. 

I am serving files using https://www.npmjs.com/package/serve. 
Version I am using https://unpkg.com/@ohif/viewer@4.9.0/dist/index.umd.js

**My folder structure:**
<img width="204" alt="Screenshot 2022-01-28 at 11 40 58 PM" src="https://user-images.githubusercontent.com/54370515/151599518-f7626393-7e47-41fc-b064-ecc9cb17cf1d.png">

`http://localhost:3000/` result
<img width="1268" alt="Screenshot 2022-01-28 at 11 42 32 PM" src="https://user-images.githubusercontent.com/54370515/151599644-d13b8480-4a16-4a3e-977a-63045e9affa5.png">

`http://localhost:3000/viewer/dicomjson?url=http://localhost:3000/dicom.json` says 404

<img width="977" alt="Screenshot 2022-01-28 at 11 46 10 PM" src="https://user-images.githubusercontent.com/54370515/151600132-4659071d-6ef7-4df9-8780-18ac7855aad3.png">

Can you please guide what I am doing wrong here?

**Comment by sedghi** [comment]
@anarnoli I don't think you need the `/dicomjson?url=` in the url that is for ohif-v3-alpha, can you make sure you are using url as I'm showing above?

**Comment by anarnoli** [comment]
Thanks @sedghi I made it working, issue was with the path.

Few quick understandings (Apologies if I am asking too basics being new to OHIF): 
1. Is it possible to populate Study List using DICOM JSON? Asking because I don't have DICOM server in my scenario and only .dcm files are present. 
2. Can the .dcm file be served from Google Drive directly?

Many Thanks.

**Comment by sedghi** [comment]
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
