### ISSUE TITLE
Infinite loop with standalone viewer prevents debugging

### ISSUE THREAD

**Issue by yehudahkay** [OHIF/Viewers#2298]
Hi and thank you for the library,

I've managed to surmount all the issues with cors using json and the standalone viewer, however I get an infinite loop when the viewer is trying to load my images. It is preventing me from debugging as well to try and figure out the issue. Attached screenshot.

![image](https://user-images.githubusercontent.com/9964988/110477133-785d9180-80eb-11eb-93b6-2394ace57241.png)

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
