### ISSUE TITLE
Can we change orthanc server to another server like (https://www.dicomserver.co.uk)

### ISSUE THREAD

**Issue by brikjr** [OHIF/Viewers#2299]
what steps can we take if we wanna to change orthanc server to another API service 
any ideas ?

**Comment by olivert1969** [comment]
@brikjr try updating the servers section of your OHIF config file:

  servers: {
    dicomWeb: [
      {
        name: 'dicomserver.co.uk',
        wadoUriRoot: 'http://www.dicomserver.co.uk/wado',
        qidoRoot: 'http://dicomserver.co.uk:81/qido',
        wadoRoot: 'http://dicomserver.co.uk:81/wado',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
      },
    ],
  },
