### ISSUE TITLE
Connect to dcm4chee-2.18.1

### ISSUE THREAD

**Issue by mkauzlar** [OHIF/Viewers#23]
Hello,
is there a way to start the OHIFViewer and connect to existing dcm4chee PACS server?
I tried to modify siimDCM4CHEE.json without luck.
Thank you
Marko

**Comment by swederik** [comment]
I don't have a dcm4chee server set up to test against, so I'm not sure. What errors are you receiving?

**Comment by mkauzlar** [comment]
The dcm4chee server is returning:

```
HTTP Status 400 - Not A WADO URL
type Status report
message Not A WADO URL
description The request sent by the client was syntactically incorrect (Not A WADO URL).
JBossWeb/2.0.1.GA
```
The output from OHIFViewer is:

`$ ./bin/TTPACS1.sh 
[[[[[ ~/Downloads/Viewers-master/OHIFViewer ]]]]]

=> Started proxy.                             
=> Meteor 1.3.3 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
I20160616-07:10:46.030(2)? Adding DIMSE peers 
=> Started your app.

=> App running at: http://localhost:3000/
I20160616-07:10:46.172(2)? Using custom LesionTracker settings: 
I20160616-07:10:46.172(2)? { dicomWeb: { endpoints: [ [Object] ] },
I20160616-07:10:46.172(2)?   dimse: { host: '172.19.118.173', port: 11112, hostAE: 'TTPACS1' },
I20160616-07:10:46.172(2)?   defaultServiceType: 'dicomWeb',
I20160616-07:10:46.173(2)?   public: {} }
I20160616-07:11:02.074(2)? http://172.19.118.173:8080/wado/studies?limit=20&includefield=00081030%2C00080060
I20160616-07:11:02.240(2)? Exception while invoking method 'WorklistSearch' Error: failed [400] <html><head><title>JBossWeb/2.0.1.GA - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#...
I20160616-07:11:02.241(2)?     at Object.Future.wait (/home/helena/.meteor/packages/meteor-tool/.1.3.2_4.omx7aa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:420:15)
I20160616-07:11:02.241(2)?     at Object.call (packages/meteor/helpers.js:119:1)
I20160616-07:11:02.241(2)?     at Object.HTTP.get (packages/http/httpcall_common.js:50:20)
I20160616-07:11:02.241(2)?     at Object.DICOMWeb.getJSON (packages/dicomweb/server/getJSON.js:20:1)
I20160616-07:11:02.241(2)?     at Object.Services.QIDO.Studies (packages/worklist/server/services/qido/studies.js:63:1)
I20160616-07:11:02.241(2)?     at [object Object].Meteor.methods.WorklistSearch (packages/worklist/server/methods/worklistSearch.js:12:1)
I20160616-07:11:02.241(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160616-07:11:02.242(2)?     at packages/ddp-server/livedata_server.js:711:19
I20160616-07:11:02.242(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160616-07:11:02.242(2)?     at packages/ddp-server/livedata_server.js:709:40
I20160616-07:11:02.242(2)?     - - - - -
I20160616-07:11:02.242(2)?     at makeErrorByStatus (packages/http/httpcall_common.js:13:10)
I20160616-07:11:02.242(2)?     at Request._callback (packages/http/httpcall_server.js:113:17)
I20160616-07:11:02.242(2)?     at Request.self.callback (/home/helena/.meteor/packages/http/.1.1.5.2l9r9r++os+web.browser+web.cordova/npm/node_modules/request/request.js:344:22)
I20160616-07:11:02.242(2)?     at Request.emit (events.js:98:17)
I20160616-07:11:02.242(2)?     at Request.<anonymous> (/home/helena/.meteor/packages/http/.1.1.5.2l9r9r++os+web.browser+web.cordova/npm/node_modules/request/request.js:1239:14)
I20160616-07:11:02.242(2)?     at Request.emit (events.js:117:20)
I20160616-07:11:02.242(2)?     at IncomingMessage.<anonymous> (/home/helena/.meteor/packages/http/.1.1.5.2l9r9r++os+web.browser+web.cordova/npm/node_modules/request/request.js:1187:12)
I20160616-07:11:02.243(2)?     at IncomingMessage.emit (events.js:117:20)
I20160616-07:11:02.243(2)?     at _stream_readable.js:944:16
I20160616-07:11:02.243(2)?     at process._tickCallback (node.js:458:13)


`

**Comment by mdg583** [comment]
I believe for dcm4chee, wadoRoot and qidoRoot in the OHIF config must not point to your wado url. Only wadoUriRoot should. I think wadoRoot is for wado-rs requests, and qidoRoot for qido-rs. wadoUriRoot is for wado-uri.

I think dcm4chee 2.x may not have any support for qido-rs.

**Comment by swederik** [comment]
So I tested against DCM4CHEE Archive 5.x (https://github.com/dcm4che/dcm4chee-arc-light) and ran into some issues with DIMSE C-FIND queries. It seems that we couldn't retrieve all instance metadata related to a specific StudyInstanceUid in one request, so @weiwei-ohif had already created a workaround to first ask for all Series data (https://github.com/OHIF/Viewers/blob/804488458c9085f215d6616a7944f6d05353c594/Packages/dimseservice/server/DIMSE.js#L189).

It seems to work for me now with both DIMSE and DICOMweb. I used docker-compose to install DCM4CHEE and storescu to send data to the archive.

Could you test again and let me know if that fixed it?

**Comment by mdg583** [comment]
I pulled in the changes above. Thanks, it worked.

In config/dcm4cheeDIMSE.json, should aeTitle on line 32 be DCM4CHEE?

**Comment by mkauzlar** [comment]
I installed DCM4CHEE Archive 5.x using docker. Pulled the viewer from here and started it with using config/dcm4cheeDIMSE.json
The viewer starts ok however when I open a study the images don't appear and just have the "Error " message in them

**Comment by swederik** [comment]
What kind of errors do you get in the javascript console? Or in the server console?

Can you also check the docker logs?

**Comment by mkauzlar** [comment]
The dcm4chee logs shows the find queries and all seems ok
below is the log from the viewer.
In my post above I was connecting with firefox which just shows the frames with the Error message (see
![pict1](https://cloud.githubusercontent.com/assets/4133383/17544632/c163f1e2-5ed8-11e6-8118-4d6afd9a0244.jpg)
![pict2](https://cloud.githubusercontent.com/assets/4133383/17544631/c15e50ac-5ed8-11e6-814c-138a816f2940.jpg)

 pict1)
Now I connected with Chrome and the page is different and presents an Error message (see pict2)

[[[[[ ~/Downloads/Viewers/OHIFViewer ]]]]]    

=> Started proxy.                             
=> Started MongoDB.                           
I20160810-08:54:12.391(2)? Adding DIMSE peers 
I20160810-08:54:12.464(2)? ------ Testing Meteor Settings ------
I20160810-08:54:12.464(2)? {
I20160810-08:54:12.465(2)?   "servers": {
I20160810-08:54:12.465(2)?     "dicomWeb": [
I20160810-08:54:12.465(2)?       {
I20160810-08:54:12.466(2)?         "name": "DCM4CHEE",
I20160810-08:54:12.466(2)?         "wadoUriRoot": "http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/wado",
I20160810-08:54:12.466(2)?         "qidoRoot": "http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs",
I20160810-08:54:12.466(2)?         "wadoRoot": "http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs",
I20160810-08:54:12.467(2)?         "qidoSupportsIncludeField": false,
I20160810-08:54:12.467(2)?         "imageRendering": "wadouri",
I20160810-08:54:12.467(2)?         "requestOptions": {
I20160810-08:54:12.468(2)?           "auth": "admin:admin",
I20160810-08:54:12.468(2)?           "logRequests": true,
I20160810-08:54:12.468(2)?           "logResponses": false,
I20160810-08:54:12.469(2)?           "logTiming": true
I20160810-08:54:12.469(2)?         }
I20160810-08:54:12.469(2)?       }
I20160810-08:54:12.470(2)?     ],
I20160810-08:54:12.471(2)?     "dimse": [
I20160810-08:54:12.471(2)?       {
I20160810-08:54:12.471(2)?         "name": "DCM4CHEE_DIMSE",
I20160810-08:54:12.472(2)?         "peers": [
I20160810-08:54:12.472(2)?           {
I20160810-08:54:12.473(2)?             "host": "localhost",
I20160810-08:54:12.473(2)?             "port": 4242,
I20160810-08:54:12.473(2)?             "aeTitle": "DCM4CHEE",
I20160810-08:54:12.473(2)?             "default": true,
I20160810-08:54:12.474(2)?             "supportsInstanceRetrievalByStudyUid": false,
I20160810-08:54:12.474(2)?             "server": false
I20160810-08:54:12.474(2)?           },
I20160810-08:54:12.474(2)?           {
I20160810-08:54:12.475(2)?             "host": "0.0.0.0",
I20160810-08:54:12.475(2)?             "port": 11112,
I20160810-08:54:12.476(2)?             "aeTitle": "DCM4CHEE",
I20160810-08:54:12.476(2)?             "default": true,
I20160810-08:54:12.476(2)?             "server": true,
I20160810-08:54:12.477(2)?             "supportsInstanceRetrievalByStudyUid": true
I20160810-08:54:12.477(2)?           }
I20160810-08:54:12.477(2)?         ]
I20160810-08:54:12.478(2)?       }
I20160810-08:54:12.478(2)?     ]
I20160810-08:54:12.479(2)?   },
I20160810-08:54:12.479(2)?   "defaultServiceType": "dimse",
I20160810-08:54:12.480(2)?   "public": {
I20160810-08:54:12.480(2)?     "verifyEmail": false,
I20160810-08:54:12.480(2)?     "ui": {
I20160810-08:54:12.480(2)?       "studyListFunctionsEnabled": true
I20160810-08:54:12.481(2)?     }
I20160810-08:54:12.481(2)?   }
I20160810-08:54:12.482(2)? }
I20160810-08:54:12.482(2)? server error {"code":"EADDRINUSE","errno":"EADDRINUSE","syscall":"listen","address":"0.0.0.0","port":11112}
=> Started your app.

=> App running at: http://localhost:3000/
I20160810-08:54:23.657(2)? worklist: Services.DIMSE.Studies
I20160810-08:54:23.658(2)? Associating...
I20160810-08:54:23.658(2)? Starting Connection...
I20160810-08:54:23.674(2)? { host: '0.0.0.0', port: 11112 }
I20160810-08:54:23.675(2)? Connect
I20160810-08:54:23.675(2)? Connection established
I20160810-08:54:23.684(2)? ==Associated
I20160810-08:54:23.688(2)? Sending command C-FIND-RQ
I20160810-08:54:23.777(2)? Connection closed
I20160810-08:54:27.318(2)? worklist: GetStudyMetadata(%s) 1.3.12.2.1107.5.2.31.31357.30000015050711013660900000002
I20160810-08:54:27.321(2)? Associating...
I20160810-08:54:27.321(2)? Starting Connection...
I20160810-08:54:27.323(2)? { host: '0.0.0.0', port: 11112 }
I20160810-08:54:27.326(2)? Connect
I20160810-08:54:27.326(2)? Connection established
I20160810-08:54:27.326(2)? ==Associated
I20160810-08:54:27.328(2)? Sending command C-FIND-RQ
I20160810-08:54:27.423(2)? Sending command C-FIND-RQ
I20160810-08:54:27.462(2)? Sending command C-FIND-RQ
I20160810-08:54:27.540(2)? Sending command C-FIND-RQ
I20160810-08:54:27.614(2)? Sending command C-FIND-RQ
I20160810-08:54:27.688(2)? Sending command C-FIND-RQ
I20160810-08:54:27.757(2)? Sending command C-FIND-RQ
I20160810-08:54:27.836(2)? Connection closed
I20160810-08:54:27.838(2)? worklist: resultDataToStudyMetadata
I20160810-08:54:49.601(2)? worklist: Services.DIMSE.Studies
I20160810-08:54:49.602(2)? Associating...
I20160810-08:54:49.602(2)? Starting Connection...
I20160810-08:54:49.603(2)? { host: '0.0.0.0', port: 11112 }
I20160810-08:54:49.603(2)? Connect
I20160810-08:54:49.603(2)? Connection established
I20160810-08:54:49.608(2)? ==Associated
I20160810-08:54:49.608(2)? Sending command C-FIND-RQ
I20160810-08:54:49.694(2)? Connection closed
I20160810-08:54:51.118(2)? worklist: GetStudyMetadata(%s) 1.3.12.2.1107.5.2.31.31357.30000015050711013660900000002
I20160810-08:54:51.120(2)? Associating...
I20160810-08:54:51.120(2)? Starting Connection...
I20160810-08:54:51.120(2)? { host: '0.0.0.0', port: 11112 }
I20160810-08:54:51.121(2)? Connect
I20160810-08:54:51.121(2)? Connection established
I20160810-08:54:51.125(2)? ==Associated
I20160810-08:54:51.125(2)? Sending command C-FIND-RQ
I20160810-08:54:51.220(2)? Sending command C-FIND-RQ
I20160810-08:54:51.255(2)? Sending command C-FIND-RQ
I20160810-08:54:51.325(2)? Sending command C-FIND-RQ
I20160810-08:54:51.389(2)? Sending command C-FIND-RQ
I20160810-08:54:51.450(2)? Sending command C-FIND-RQ
I20160810-08:54:51.509(2)? Sending command C-FIND-RQ
I20160810-08:54:51.563(2)? Connection closed
I20160810-08:54:51.564(2)? worklist: resultDataToStudyMetadata

**Comment by swederik** [comment]
It looks like your WADO URI url is incorrect. It should be pointing to the proxy, running on port 8043. Mine looks like this: http://localhost:8043/dcm4chee-arc/aets/DCM4CHEE/wado

You should be running using dcm4cheeDIMSE.json.

**Comment by mkauzlar** [comment]
The default docker installation of dcm4chee arc uses 8080 as port. Anyhow using 8080 or 8043 gives the same error message.
It's interesting to notice that using dcm4cheeDIMSE.json the viewer at startup gives:

I20160810-12:11:19.206(2)? server error {"code":"EADDRINUSE","errno":"EADDRINUSE","syscall":"listen","address":"0.0.0.0","port":11112}

that is because on port 11112 the dcm4chee server is already listening.
Is the viewer trying to start a listener for getting data?

**Comment by swederik** [comment]
Yeah I have seen that error as well and indeed there is something wrong there that we need to fix, but that's not the issue you're seeing (since it's an error related to the DIMSE library, and you can see the study list fine). 

dcm4chee does give 8080 as the port, but you can't use that in the configuration because you will run into CORS errors. You need to run the node proxy, which listens on port 8043 by default, and point the WADO URI requests through there. Is it running? What do you get in the Chrome console when the requests to the proxy fail?

**Comment by mkauzlar** [comment]
nothing is running on 8043 when I install dcm4chee-arc. The default is 8080.
Did you change the docker-compose.yml before installing dcm4chee?
In this case if I change the port from 8080 to 8043 than also the qido and wado root ports URL changes. In this case you would need to change all 8080 to 8043 in dcm4cheeDIMSE.json, right?

**Comment by swederik** [comment]
You have to be running the NodeJS Proxy for the WADO-URI requests to succeed. This is distinct from the DCM4CHEE installation. This prevents the CORS errors by adding the 'Access-Control-Allow-Origin' field to the response header.

In a separate Terminal tab, go to /etc in the Viewers repository and run:

````
node dcm4cheCORSproxy.js
````

You may need to use "nodejs" instead of node on Ubuntu.

**Comment by mkauzlar** [comment]
Right, that was it.
So, to reassume, here is what needs to be done to run the viewer on ubuntu/debian based systems to connect to dcm4chee arc:

```
#!/bin/bash
echo -e "\nInstall dependencies"
sudo apt install nodejs-legacy
sudo apt install npm
if [ -f /usr/local/bin/meteor ];
then
   echo "Meteor is already installed"
else
   echo "Installing Meteor"
   sudo curl https://install.meteor.com/ | sh
fi

echo -e "\nGet the latest code from git"
git clone https://github.com/OHIF/Viewers.git OHIF

echo -e "\nRun the DCM4CHE proxy"
cd OHIF/etc
npm install http-proxy
node dcm4cheCORSproxy.js &

echo -e "\nRun the OHIFViewer"
cd ../OHIFViewer
PACKAGE_DIRS="../Packages" meteor --settings ../config/dcm4cheeDIMSE.json


```

**Comment by swederik** [comment]
Awesome, sorry for the confusion. I'll try to improve the wiki pages.

**Comment by swederik** [comment]
We have now moved the CORS proxy internally and so the extra step of starting the proxy with Node is no longer required. I've also added a Wiki page describing how to get DCM4CHEE working with Docker-Compose: https://github.com/OHIF/Viewers/wiki/DCM4CHEE-with-Docker-Usage
