### ISSUE TITLE
yarn run dev error , ｢wdm｣: Failed to compile.

### ISSUE THREAD

**Issue by sambid9988** [OHIF/Viewers#2300]
Hi i am trying to install OHIF_orthanc server in aws  vm. While running command yarn run dev, i see below error. If anyone has any answer to this please let me know. Thanks in advance.

@ohif/viewer: ERROR in /home/sambid/Viewers/node_modules/react-transition-group/esm/CSSTransition.js
@ohif/viewer: Module not found: Error: Can't resolve 'dom-helpers/addClass' in '/home/sambid/Viewers/node_modules/react-transition-group/esm'
@ohif/viewer:  @ /home/sambid/Viewers/node_modules/react-transition-group/esm/CSSTransition.js 5:0-47 13:11-22
@ohif/viewer:  @ /home/sambid/Viewers/node_modules/react-transition-group/esm/index.js
@ohif/viewer:  @ ./OHIFStandaloneViewer.js
@ohif/viewer:  @ ./App.js
@ohif/viewer:  @ ./index.js
@ohif/viewer: ERROR in /home/sambid/Viewers/node_modules/react-transition-group/esm/CSSTransition.js
@ohif/viewer: Module not found: Error: Can't resolve 'dom-helpers/removeClass' in '/home/sambid/Viewers/node_modules/react-transition-group/esm'
@ohif/viewer:  @ /home/sambid/Viewers/node_modules/react-transition-group/esm/CSSTransition.js 6:0-53 19:11-25
@ohif/viewer:  @ /home/sambid/Viewers/node_modules/react-transition-group/esm/index.js
@ohif/viewer:  @ ./OHIFStandaloneViewer.js
@ohif/viewer:  @ ./App.js
@ohif/viewer:  @ ./index.js
@ohif/viewer: ℹ ｢wdm｣: Failed to compile.

**Comment by Jayj1997** [comment]
are you fixed that problem? I found save error :(

**Comment by Jayj1997** [comment]
I solved this problem, it was stupid…… you should yarn install with original yarn.lock，I removed it before and got same errors like you :)

**Comment by patricio-astudillo** [comment]
Can we please translate the knowledge of this issue into the documentation? It would have saved me 2h of checking dependencies... :)

**Comment by guohuihot** [comment]
Error is still

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
