### ISSUE TITLE
Hi, I am trying to integrate OHIF viewer in dotnet core(mvc template) not react. I am able to bring Viewer in index.cshtml, however I want to make default url with local file upload i.e localhost:5000/local. I have include script of index.umd.js and configure  window.OHIFViewer.installViewer.Also, it would be great help if you provide steps to embed OHIF for MVC template and how to customize embedded one. Thanks

### ISSUE THREAD

**Issue by bveeni** [OHIF/Viewers#2303]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by sedghi** [comment]
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
