### ISSUE TITLE
Version in OHIF Viewer website? https://viewer.ohif.org/

### ISSUE THREAD

**Issue by donghakang** [OHIF/Viewers#2305]
Just curious. What version (or github branch) are you guys using for the "actual" website demo ("viewer.ohif.org").

I found that some UI and some structures are different from the latest version. In addition, are you guys planning on updating the exported website?

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
