### ISSUE TITLE
MPR+crosshairs runtime error

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2308]
The error below happened when opening the CT series linked from the front page of IDC, switching to MPR, toggling crosshairs, and adjusting crosshairs in different views. Was not reproducible when attempted.

![image](https://user-images.githubusercontent.com/313942/110821737-5cc6c800-825e-11eb-9435-00439971ac07.png)

Debug info:

```
Enter the description of your problem here: 


============= SESSION INFO =============

== App ==
version	4.8.11

== Extensions Versions ==
generic-viewer-commands	4.8.11
cornerstone	2.10.2
vtk	1.10.5
html	1.3.2
microscopy	0.51.4
pdf	1.0.6
com.ohif.dicom-segmentation	0.5.3
rt	0.6.5
dicom-p10-downloader	0.1.6
dicom-tag-browser	undefined

== Browser Info ==
name	 chrome
os	 Mac OS
type	 browser
version	 88.0.4324

== URL ==
URL	 https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.6279.6001.224985459390356936417021464571?seriesInstanceUID=1.2.276.0.7230010.3.1.3.0.57823.1553343864.578877,1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680

== Viewport Layout ==
Rows	1
Columns	3

== Viewports ==
[0,0]	1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680
[0,1]	1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680
[0,2]	1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680
```

**Comment by j6u** [comment]
Hi @fedorov, I am curious how do you set up the MPR mode. Could you let me know how you are configuring the viewport and toolbar? Thanks!

**Comment by fedorov** [comment]
Sure, here you go:

![2021-03-19_16-44-32](https://user-images.githubusercontent.com/313942/111841215-0435a180-88d4-11eb-87fb-d6c33319504c.gif)

Coincidentally, I was able to reproduce the bug reported above on the first attempt.

**Comment by j6u** [comment]
I wasn't able to see 2d mpr mode in toolbar. Is there a special config or extension I need to enable to see it? Thanks!

**Comment by pieper** [comment]
> I wasn't able to see 2d mpr mode in toolbar. Is there a special config or extension I need to enable to see it? Thanks!

Yes, you need to have the vtk extension enabled and the data needs to be volumetric.

**Comment by Punzo** [comment]
> Sure, here you go:
> 
> ![2021-03-19_16-44-32](https://user-images.githubusercontent.com/313942/111841215-0435a180-88d4-11eb-87fb-d6c33319504c.gif)
> 
> Coincidentally, I was able to reproduce the bug reported above on the first attempt.

for completeness could you share the study UID? should we prioritize this as an IDC issue?

**Comment by fedorov** [comment]
Davide, it's all in debug info in the initial post.

**Comment by Punzo** [comment]
Ok, perfect, we can prioritize it later on. 

Oh you are right, I just scanned the issue too fast and I didn't see that the url line in the debug info and I thought it was missing. Thanks!

**Comment by j6u** [comment]
I am trying to repro this (in the process of testing MPR feature)...I am not sure if the DICOM file I have isn't volumetric or I miss configured things. Would really appreciate a sample volumetric DICOM file if someone has one for me to try out!

btw, this is my viewer/src/index.js, and you can see I have VTK extension as default.
```
const appProps = {
  config,
  defaultExtensions: [
    OHIFVTKExtension,
    OHIFDicomHtmlExtension,
    OHIFDicomMicroscopyExtension,
    OHIFDicomPDFExtension,
    OHIFDicomSegmentationExtension,
    OHIFDicomRtExtension,
    //OHIFDebuggingExtension,
    //OHIFDicomTagBrowserExtension,
  ],
};

```

I am using google.js as the app config, does it override it somehow? Curious if I need to relist OHIFVTKExtension.

**Comment by pieper** [comment]
There are lots of public datasets here: https://www.cancerimagingarchive.net/collections/

Most of the CTs and MRs should work with the MPR feature in the VTK extension.

**Comment by sedghi** [comment]
@fedorov Can we close this if it is fixed?

**Comment by fedorov** [comment]
I have not seen this one in a while, so makes sense to close. Hopefully it's been fixed.
