### ISSUE TITLE
lerna ERR on fresh  installation on centos 7

### ISSUE THREAD

**Issue by NicGLP** [OHIF/Viewers#2311]
I got  OHIF from: 
wget https://github.com/OHIF/Viewers/archive/master.zip

after running :
yarn config set workspaces-experimental true
yarn install   ( same problem with  --force )
yarn run build

error: ( last lines output )
.......
ohif/viewer: <s> [webpack.Progress] 91% recording
ohif/viewer: <s> [webpack.Progress] 92% additional asset processing
ohif/viewer: <s> [webpack.Progress] 92% chunk asset optimization
ohif/viewer: <s> [webpack.Progress] 92% chunk asset optimization TerserPlugin
ohif/viewer: error Command failed with exit code 1.
ohif/viewer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:viewer exited 1 in '@ohif/viewer'
error Command failed with exit code 1.
.......
I run on CENTOS 7
node --version
v12.21.0
npm --version
6.14.11
yarn --version
1.22.5

Anyone can help ?
would be much appreciated.
thanks

**Comment by brikjr** [comment]
`yarn update`
`yarn install --force`
`yarn run dev`
it should work !

**Comment by NicGLP** [comment]
Thanks, Done  and Working ....
