### ISSUE TITLE
Is it Possible ? if we can use different API to load images [not orthanc]

### ISSUE THREAD

**Issue by briyk** [OHIF/Viewers#2312]
For example , use [this api](https://www.dicomserver.co.uk)

**Comment by willmaw123** [comment]
If it supports DICOM Web then it's possible, I'm using OHIF with this archive: https://github.com/microsoft/dicom-server

**Comment by sedghi** [comment]
read more about how to connect to OHIF here https://docs.ohif.org/configuration/dataSources/introduction
