### ISSUE TITLE
Can we view .vsi files (BioMedical Samples) Using the Particular Tool? Can it be used as extensible plugin to a webpage ?

### ISSUE THREAD

**Issue by YOGESH-CHOUDHARY** [OHIF/Viewers#2316]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
