### ISSUE TITLE
Not able to connect to secured dcm4chee-arc-light (v5.17)

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#2323]
Hi, we recently shifted from unsecure to secured dcm4chee-arc-light server. I can generate the auth token from my secured dcm4chee-arc-light to use it with other QIDO/WADO urls (/auth/realms/dcm4che/protocol/openid-connect/token)

Is there a provision in OHIF to set this up? It needs setting up few parameters like clients secret, client id, grant type etc.

We are happy to go through any documentation if available.

**Comment by bhavesh-pandey** [comment]
I have asked this on dcm4chee group but I am not getting any response there https://groups.google.com/g/dcm4che/c/Mu4jcNH-dqI

**Comment by elamathis18** [comment]
Hi, I'm also using secured dcm4chee and the wado links seems to throw 401 when trying to access metadata and series. @bhavesh-pandey Were there any breakthrough?

**Comment by scope-antofa** [comment]
Hi, same issue with dcm4chee-arc-light-5.28.0-secure  and ohif 4.12

Any example or solution?, please.

Thanks

**Comment by sedghi** [comment]
@jbocce ditto

**Comment by bhavesh-pandey** [comment]
I deployed my dcm4chee-arc-light on AWS in an EC2 container, created a classic load balancer and routed 443 requests to configured http port, used AWS certificates for SSL.

**Comment by sedghi** [comment]
@bhavesh-pandey Is this still an issue in our latest master branch?

**Comment by bhaveshula** [comment]
@sedghi I have not worked on this for last 2 years, no idea if it still exists.

**Comment by bhavesh-pandey** [comment]
Sorry, I have not worked on this for last 2 years and did not check the issue again.

**Comment by sedghi** [comment]
can you re-try with latest master branch, or release branch and if this still happening open the issue please
