### ISSUE TITLE
Dicom SR and Measurements Panel

### ISSUE THREAD

**Issue by Shamanga** [OHIF/Viewers#2325]
**Description**

Hello,

I've been playing around with OHIF for a couple of months now, and I have a question regarding what the measurements panel should display. Most of the issues opened in the repo are regarding adding measurements and saving them or modifying a SR. My problem is slightly different. I've already populated a dicom SR using [TID 1500 Writer](https://qiicr.gitbook.io/dcmqi-guide/opening/cmd_tools/sr/tid1500writer) that contains volumes of segmentations of a T1W brain MRI image. The segments are present in the panel and the segmentations are displayed in the viewer but the measurements panel is empty.

My questions are: 
1- Does the measurementsService parse the dicom SR to extract the volumetric values to be displayed on the measurement panel.
2- Is using the [TID 1500 Writer](https://qiicr.gitbook.io/dcmqi-guide/opening/cmd_tools/sr/tid1500writer) and this [schema](https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-tid1500-schema.json) supported by OHIF? Are there extra fields that are required by OHIF that aren't mandatory for the creation of the SR with the writer?

In this [answer](https://github.com/OHIF/Viewers/issues/1215#issuecomment-571770735) by @dannyrb multiple goals were set, amongst which are: 

- Centralize DICOM SR Parsing / loading
- Broad support for rendering DICOM SR measurements

Within the same answer, it mentions that OHIF filters/matches **"Code Meaning"** with the string **"Length"**, and so does that mean that any other Code Meaning would not be parsed?

I've seen already for example [issue#225](https://github.com/OHIF/Viewers/pull/225#issue-201642333) that discusses the support of TID 1500 Report 2 years ago, with some follow ups  [#1846](https://github.com/OHIF/Viewers/pull/1846#issue-442706972), [#1885](https://github.com/OHIF/Viewers/pull/1885#issue-446366199) from @JamesAPetts and @pieper but no question about this specific situation.

If the viewer is able to save some measurements into a SR, and then recurrently read them as with the length tool case. Then it just might be a problem of parsing different measurement types.

Best,
Mezo

**Comment by pieper** [comment]
This is still an area of active interest and there is work going on, but I don't think it's gotten into state that just works out of the box.  A lot of the pieces are worked out but if you track #1215 you can see it's a complex work in progress.  I'm going to close this as a duplicate, but it would be great if you could contribute your efforts to the work.
