### ISSUE TITLE
How to Hook in the Embeded Ohif Library and send data to a different Location

### ISSUE THREAD

**Issue by mozzy11** [OHIF/Viewers#2326]
Hello team,
I have succesfuly ran the embeded Ohif Library.
I want to find a way of hooking in and get measurement data from tools (especially the arow anotate )and save it to a different location without making direct changes in the OHIF code.
What is the best way to do this.
are there call backs that can do this ??
Thanks in advance

**Comment by sedghi** [comment]
You can look into the data sources https://docs.ohif.org/configuration/dataSources/introduction
