### ISSUE TITLE
Meteor error

### ISSUE THREAD

**Issue by bionick87** [OHIF/Viewers#233]
Meteor shows this error:

Errors prevented startup:

While processing files with templating-compiler (for target web.browser):
StandaloneViewer/SampleClientOnlyBuild/index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)

While minifying app stylesheet:
app/StandaloneViewer/SampleClientOnlyBuild/d03b794e52cffaf1a76ed5395e54e18b09f20f15.css:1:113053: Missed semicolon
app/StandaloneViewer/SampleClientOnlyBuild/e4bae103351559e4cc4f1610f25c9bcfa9ae9646.css:1:166889: Missed semicolon

While processing files with templating-compiler (for target web.browser.legacy):
StandaloneViewer/SampleClientOnlyBuild/index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)

Your application has errors. Waiting for file change.
Started MongoDB.

**Comment by swederik** [comment]
The SampleClientOnlyBuild folder is pre-built into a client-only web page. I don't think it makes any sense for you to be trying to run it with Meteor. It's not a Node.js application, it's literally just an index.html and some JS / CSS.

You probably want the StandaloneViewer/StandaloneViewer folder instead.

**Comment by bionick87** [comment]
Hey, 

Thanks for your replay. Very interesting about your app. Just curios as it works. 
Then, I have been tried to run Meteor like the new instruction of it asked. 
 
$ meteor create ~/my_cool_app
$ cd ~/my_cool_app
$ meteor

Wheras, "my_cool_app" folder is the content of Viewers-master.
Indeed, after the meteor command all stuffs have been run automatically. 
The reason of way i used  Meteor is related within the app instruction that i have seen in: 
https://docs.ohif.org/essentials/installation.html (section 2)

Now, how can use this app? how can open on my browser i just need to go in a index main page?
Sorry for my questions bit new and very happy to understand more about it.

**Comment by swederik** [comment]
You don't need to create a new application, the application already exists in the folder.

You can use the OHIFViewer folder, and follow the instructions: https://docs.ohif.org/essentials/installation.html#set-up-and-test-the-ohif-viewer-or-lesiontracker-application

Pay attention where it says "Open a new terminal tab in one of the Application directories (OHIFViewer or LesionTracker)".
