### ISSUE TITLE
Problem loading CT image

### ISSUE THREAD

**Issue by pilacoepouco** [OHIF/Viewers#2330]
I'm accessing the viewer via the json URL. An MR image carries normal, but a CT does not. Didn't show any error, any idea what it might be?

![image](https://user-images.githubusercontent.com/53221609/112078051-728c9500-8b5c-11eb-9506-4efd5a88cdd4.png)

![image](https://user-images.githubusercontent.com/53221609/112078108-8e903680-8b5c-11eb-9c05-fc5c41ba509b.png)

**Comment by DICOMSOFT** [comment]
same problem here => https://github.com/OHIF/Viewers/issues/2319

**Comment by brikjr** [comment]
> I'm accessing the viewer via the json URL. An MR image carries normal, but a CT does not. Didn't show any error, any idea what it might be?
> 
> ![image](https://user-images.githubusercontent.com/53221609/112078051-728c9500-8b5c-11eb-9506-4efd5a88cdd4.png)
> 
> ![image](https://user-images.githubusercontent.com/53221609/112078108-8e903680-8b5c-11eb-9c05-fc5c41ba509b.png)

I think to maybe Cross-Origin Request Problem try to read about it

**Comment by pilacoepouco** [comment]
The requests are OK, without any error, so much so that it loading other modalities. Can it still be Cross-Origin Request ??

**Comment by brikjr** [comment]
> The requests are OK, without any error, so much so that it loading other modalities. Can it still be Cross-Origin Request ??

I think there are two possibilities for the problem , first one is what i said Cors-origin because you don't have any response like 200 or 404  and u should try to prevent it from chrome or Firefox .
second one that u  have problem in query itself so try to compare your query of frame by the one at OHIF main site

**Comment by jonasscherer** [comment]
Thanks @ngutman for the hint!
I can confirm that the new DCM4CHE was the root of this issue for me.

**Comment by pilacoepouco** [comment]
I found the problem.
I am a private server to return the metadata to me and load the images through Oracle's Object Storage and I ended up returning two tags that were outside of JSON Launch.
TAGS:

```
"RescaleSlope": "1",
 "RescaleIntercept": "0",
```
