### ISSUE TITLE
onNewImage code not called when image has frame index 0 (Cornerstone Extension)

### ISSUE THREAD

**Issue by Michael-Andersen** [OHIF/Viewers#2336]
Scrolling to frame index 0 is not registered because the Cornerstone new image handler is only called if the index is greater than 0.

To reproduce bug

1. Scroll past 0 and see that newImageHandler was called (for instance via console log message).
2. Scroll back to 0 and see that newImageHandler was not called.

```
    const newImageHandler = ({ currentImageIdIndex, sopInstanceUid }) => {
      const { displaySet } = this.props.viewportData;
      const { StudyInstanceUID } = displaySet;

      if (currentImageIdIndex > 0) {
        this.props.onNewImage({
          StudyInstanceUID,
          SOPInstanceUID: sopInstanceUid,
          frameIndex: currentImageIdIndex,
          activeViewportIndex: viewportIndex,
        });
      }
    };
```

from [OHIFCornerstoneViewport.js](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone/src/OHIFCornerstoneViewport.js#L218)

I believe changing the equality condition would fix the bug. Something like this: 

      if (currentImageIdIndex >= 0) {
        this.props.onNewImage({
          StudyInstanceUID,
          SOPInstanceUID: sopInstanceUid,
          frameIndex: currentImageIdIndex,
          activeViewportIndex: viewportIndex,
        });
      }
    };

I would be happy to create a PR for this change if others agree.

**Comment by swederik** [comment]
Good catch, I think a PR makes sense.
