### ISSUE TITLE
Double click viewport to toggle to single viewport from multiple

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#2344]
Hello,

I would like to toggle viewports to a single viewport if grid layout is not in single mode for example from 4x4 layout.  This is useful and time saver if measurement etc. is needed and by simply double clicking a viewport to toggle to a single viewport.

Could anyone guide me in achieving this feature.

Thank you!
Ric

**Comment by AstridTrj** [comment]
Did you solve it？

**Comment by sedghi** [comment]
latest master has this feature
