### ISSUE TITLE
Please provide an example of RTSTRUCT type！

### ISSUE THREAD

**Issue by NicCraver** [OHIF/Viewers#2350]
Please provide an example of RTSTRUCT type！

**Comment by NicCraver** [comment]
![20210407170002](https://user-images.githubusercontent.com/36131101/113839931-bf11da80-97c2-11eb-82e9-04b6e8e2705b.png)
Can you provide an RTSTRUCT type file？

**Comment by sedghi** [comment]
You can take a look at [IDC](https://portal.imaging.datacommons.cancer.gov/) (Imaging Data Commons) which uses OHIF viewer

Sample RTSTRUCT studies:

https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.32722.99.99.239341353911714368772597187099978969331

https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.32722.99.99.203715003805996641695765332389135385095

**Comment by NicCraver** [comment]
> 您可以看一下使用OHIF查看器的[IDC](https://portal.imaging.datacommons.cancer.gov/)（影像数据共享）
> 
> RTSTRUCT研究样本：
> 
> [https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.32722.99.99.239341353911911714772772597597099099969969331](https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.32722.99.99.239341353911714368772597187099978969331)
> 
> https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.32722.99.99.203715003805996641695765332389135385095

This is great!

Thank you very much for your help!

But how does this work? I am building an OHIF Viewer that can display RTSTRUCT types. Can you share these DICOM files?

I want to test whether my system can display these files correctly.

**Comment by fedorov** [comment]
If you want to download images, you can search TCIA portal here and follow TCIA instructions to download: https://nbia.cancerimagingarchive.net/nbia-search/

**Comment by NicCraver** [comment]
@fedorov Thank you very much for your help!
