### ISSUE TITLE
Unable to load DICOMDIR file.

### ISSUE THREAD

**Issue by PanchakshariPM** [OHIF/Viewers#2351]
When I try to load the DICOMDIR file via the load files component, it opens the viewer component but loads nothing and I can also see an error in the console like below.
![Screenshot (493)](https://user-images.githubusercontent.com/46017622/113871767-de176900-97d0-11eb-8761-3d6bd639a400.png)

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by sedghi** [comment]
can you re-try with latest master branch, or release branch and if this still happening open the issue please
