### ISSUE TITLE
Viewer error :ToolbarRow: e.find(...) is undefined

### ISSUE THREAD

**Issue by NicGLP** [OHIF/Viewers#2354]
Good Morning,
for some studies I get the following error,

![Capture d’écran 2021-04-10 à 10 55 36](https://user-images.githubusercontent.com/80526257/114264458-607b7500-99eb-11eb-9986-f07a61060cdd.png)

my config has only the following extensions ::
....
extensions: [
        { id: "cornerstone"},{id: "vtk"},{id:"extension-dicom-pdf"} ]
....
and nothing in toolbar, 

Any idea ?

**Comment by xeonfeng** [comment]
Me too!
Get some wrong information in ohif-viewer-4.8.10， Viewers--ohif-viewer-4.9.8，and master trunk.

"Something went wrong in ViewerMain" as :
![image](https://user-images.githubusercontent.com/11417207/114270934-9a776600-9a41-11eb-8981-b8305cd9c3c2.png)

**Comment by NicGLP** [comment]
Not really the same error !

**Comment by NicGLP** [comment]
I fixed it  .... nothing to do with the toolbar aparently  ....
