### ISSUE TITLE
OHIF Volume Rendering 

### ISSUE THREAD

**Issue by NicGLP** [OHIF/Viewers#2357]
Good Morning,
I have the following extensions:
{  id: "cornerstone"},{id: "vtk"},{id:"extension-dicom-pdf"}
How can I get a  Volume Rendering  ?  is it part of the vtk extension or do I need a new one ?
Can  add it at OHIF Build time ?
thanks for the help.

**Comment by sedghi** [comment]
you can access some volume rendering features from hanging protocols but we are working towards bringing it to the UI https://viewer.ohif.org/viewer?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2&hangingprotocolId=mprAnd3DVolumeViewport
