### ISSUE TITLE
TypeError: windowCenter.toFixed is not a function

### ISSUE THREAD

**Issue by xeonfeng** [OHIF/Viewers#2360]
### Describe the Bug

When using lastest version Viewer, opening a study,and drag the mouse with defalut level icon by pressed and holding the left mouse button, the error occurred!

![image](https://user-images.githubusercontent.com/11417207/114640553-f3c1ec80-9d02-11eb-9ec6-dbadd20a9f7f.png)
![image](https://user-images.githubusercontent.com/11417207/114640617-1522d880-9d03-11eb-8634-9f3eb8a192cc.png)

**Comment by igoroctaviano** [comment]
Fixed in the latest version!
