### ISSUE TITLE
Segmentation UI combobox does not get elements from the series

### ISSUE THREAD

**Issue by Punzo** [OHIF/Viewers#2361]
http://localhost:3000/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.7695.2311.111788911924319643511738623890

has segmentations, but the the Segs combox does not get filled:

![image](https://user-images.githubusercontent.com/7985338/114852889-7e7a1880-9de3-11eb-8d05-931505bba96f.png)

**Comment by Punzo** [comment]
OIHF viewer references Segmenetations to the source series by the attribute `ReferencedSeriesSequence` (0008,1115), which is conditionally required.

Study 1.3.6.1.4.1.14519.5.2.1.7695.2311.111788911924319643511738623890 segmentations metadata have instead `ReferencedImageSequence` (0008,1140) which is optional. 

@fedorov since for both RT and SEGs in many places the OIHF Viewer assumes references by `ReferencedSeriesSequence`, can you please confirm the metadata for the segmentations of this study are correct? 
If yes, @igoroctaviano , do you have any advise how to refactor OIHF?

**Comment by fedorov** [comment]
It may not be perfectly correct, but I won't believe by now you still believe in feasibility of DICOM perfection! I think we have to accept what we have. It would be more robust if OHIF checked FrameOfReferenceUID and geometry, and used that to decide whether a given seg can be composed with a specific image (and in turn, use the result of that check to decide if as given seg should be shown in the dropdown). What do you think?

**Comment by Punzo** [comment]
done in https://github.com/OHIF/Viewers/pull/2369. I added checks on FrameOfReferenceUID and it solves the bug.
