### ISSUE TITLE
Trouble Deploying Embedded Viewer with Local Orthanc

### ISSUE THREAD

**Issue by anshugoy-usc** [OHIF/Viewers#2373]
Hi,

I'm trying to deploy an embedded viewer with a local Orthanc archive. Using the deployment docs and the CodeSandbox I've managed to deploy a working page which links to the demo database. However, when I try to change the database to point to my local Orthanc database it gives me this error code, which I haven't been able to find elsewhere:

 request failed: XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, onreadystatechange: ƒ, …}

As well as: request failed at XMLHttpRequest.onreadystatechange

This is the only change I have made from the CodeSandbox demo:
>
      window.OHIFViewer.installViewer(
            {
             routerBasename: '/',
            servers:{
                 dicomWeb: [
                     {
                         name: 'Orthanc',
                         wadoUriRoot: 'http://localhost:8042/wado',
                         qidoRoot: 'http://localhost:8042/dicom-web',
                         wadoRoot: 'http://localhost:8042/dicom-web',
                         //name: 'DCM4CHEE',
                         //wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado',
                         //qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
                         //wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
                         qidoSupportsIncludeField: true,
                         imageRendering: 'wadors',
                         thumbnailRendering: 'wadors'

Additionally here is my dicom-web config for Orthanc:
>
      "DicomWeb" : {
      "Enable": true,
      "Root" : "/dicom-web/",
      "EnableWado" : true,
      "WadoRoot" : "/wado",
      "Host" : "localhost",
      "Ssl" : false,
      "QidoCaseSensitive" : true,
      "StudiesMetadata" : "Full",
      "SeriesMetadata" : "Full"

I can access the Orthanc explorer from the localhost, and I can view a list of studies uploaded onto Orthanc from http://localhost:8042/dicom-web/studies. I'm pretty new to this level of web development so I'm not sure where I've made my error, I tried to follow the deployment docs as closely as possible.

**Comment by anshugoy-usc** [comment]
Hi,

I managed to fix my previous issue. I had not properly set up the proxy. However, now I am running into another problem. I do not believe that Orthanc qido supports the query parameter includefield=all (at least when I try to run a query using that parameter I get an error) so I have set qidoSupportsIncludeField to false, however it is still making that query. When I set qidoSupportsIncludeField to true I do not get any studies to load in the OHIF viewer.

Any suggestions?

**Comment by reya276** [comment]
> Hi,
> 
> I managed to fix my previous issue. I had not properly set up the proxy. However, now I am running into another problem. I do not believe that Orthanc qido supports the query parameter includefield=all (at least when I try to run a query using that parameter I get an error) so I have set qidoSupportsIncludeField to false, however it is still making that query. When I set qidoSupportsIncludeField to true I do not get any studies to load in the OHIF viewer.
> 
> Any suggestions?

How did you fix the studies data issue? I'm running into the same issue. I'm running Ubuntu, Apache2 and Orthanc server. No Docker. so when I try to compile the viewer it completes but I get nothing but a black screen when the localhost:3000 shows. I'm also getting a CORS error. 
![CORS-Error](https://user-images.githubusercontent.com/25517972/123287372-b2a54000-d4dc-11eb-8c18-76828aee41cd.png)

wadoUriRoot: 'http://localhost:8042/wado',
        qidoRoot: 'http://localhost:8042/dicom-web/studies',
        wadoRoot: 'http://localhost:8042/dicom-web/studies',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,

**Comment by shridhargune1977** [comment]
Anyone got solution for this ? I am facing CORS Error issue in Windows

**Comment by sedghi** [comment]
Could you please review our comprehensive documentation on Cross-Origin Resource Sharing (CORS) and OHIF? Below are the links provided for your reference.

- https://docs.ohif.org/deployment/cors
- https://docs.ohif.org/deployment/iframe

In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe

**Comment by jairo-ab** [comment]
> wadoUriRoot: 'http://localhost:8042/wado',

Hi, I'm experiencing the same issue as described here. I was wondering if you’ve managed to find a solution or workaround for this problem?

If so, could you please share the solution you implemented?

Thanks!
