### ISSUE TITLE
exponential backoff and retry after 500 error

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2374]
As discussed in IDC slack. the proxy server is auto-scaling and sometimes returns 500 errors.  We should take this as an indication that the server needs time to scale and we should not re-issue the request right away.

Might use a package like this: https://www.npmjs.com/package/retry

**Comment by pieper** [comment]
See related discussion for python here: https://github.com/MGHComputationalPathology/dicomweb-client/pull/50

**Comment by igoroctaviano** [comment]
@sedghi do we have exponential backoff or retry capabilities in v3?
