### ISSUE TITLE
Access to documents 

### ISSUE THREAD

**Issue by tapeku** [OHIF/Viewers#2379]
The documentation its no working, where can I find another site with official docs?

Thanks

**Comment by igoroctaviano** [comment]
> The documentation its no working, where can I find another site with official docs?
> 
> Thanks

While we are taking care of it you can access the docs by cloning this repo, they are persisted alongside the codebase.

**Comment by tapeku** [comment]
I'll check, thanks

**Comment by sedghi** [comment]
This is resolved
