### ISSUE TITLE
how to load locally stored dicom image in viewer

### ISSUE THREAD

**Issue by tawatesumit** [OHIF/Viewers#2381]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by laithdj** [comment]
if you run and compile the master branch , in the url type /local and a uploader page should appear

**Comment by sedghi** [comment]
You can visit 

viewer.ohif.org/local

or 

viewer.ohif.org/localbasic
