### ISSUE TITLE
请问工具菜单栏是否有“定位线”功能

### ISSUE THREAD

**Issue by newPeter7** [OHIF/Viewers#2382]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

请问工具菜单栏是否有“定位线”功能？如果有怎么使用这个功能？谢谢

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by Davi-Wei** [comment]
目前好像没有，可以自己集成其他人给出的方案
