### ISSUE TITLE
VTK Extension 

### ISSUE THREAD

**Issue by EnricoScariot** [OHIF/Viewers#2384]
Hi, i can't add the VTK extension on my viewer, i'm trying to add it under a laravel project, 
I've follower exactly these steps:

1. Downloaded the repository from https://github.com/OHIF/Viewers.git
2. Then, from the root folder of the project  i run: **_yarn config set workspaces-experimental true_** , **_yarn install_** , **yarn run build:package**
3. under /extensions/vtk/src/index.js i've **_run yarn run build-package_**
4. then i've took the file created under the dist folder both for the viewer and the vtk extension)
5. After that i've correctly i mported that in my laravel project.
6. the app-config file looks like this (in the first part):
` window.config = {` 
    ` // default: '/'` 
    ` routerBasename: '/',` 
    ` extensions: [OHIFExtDicomPdf,OHIFExtDicomHtml,OHIFExtDicomMicroscopy,OHIFExtDicomSeg,OHIFExtVtk],` 
    ` showStudyList: true,` 
    ` filterQueryParam: false,` 
    ` servers: {` 
      ` dicomWeb: [` 
        ` {` 
          ` name: 'DCM4CHEE',` 
          ` wadoUriRoot: 'http://192.168.42.18:8080/dcm4chee-arc/aets/DCM4CHEE-DELL/wado',` 
          ` qidoRoot: 'http://192.168.42.18:8080/dcm4chee-arc/aets/DCM4CHEE-DELL/rs',` 
          ` wadoRoot: 'http://192.168.42.18:8080/dcm4chee-arc/aets/DCM4CHEE-DELL/rs',` 
          ` qidoSupportsIncludeField: true,` 
          ` imageRendering: 'wadors',` 
          ` thumbnailRendering: 'wadors',` 
          ` enableStudyLazyLoad: true,` 
          ` supportsFuzzyMatching: true,` 
        ` },` 
      ` ],` 
    ` },`
7. the main view looks like this: 
`<body>` 
    ` <noscript> You need to enable JavaScript to run this app. </noscript>` 
    ` <div id="root"></div>` 
    ` <script src="{{ asset('js/ohif/main_ext/index.umd.js')}}" crossorigin></script>` 
   `  <script src="{{ asset('js/ohif/cornerstone/index.umd.js')}}" crossorigin></script> ` 
    ` <script src="{{ asset('js/ohif/debugging/index.umd.js')}}" crossorigin></script> ` 
    ` <script src="{{ asset('js/ohif/dicom-pdf/index.umd.js')}}" crossorigin></script> ` 
    ` <script src="{{ asset('js/ohif/dicom-html/index.umd.js')}}" crossorigin></script> ` 
    ` <script src="{{ asset('js/ohif/dicom-microscopy/index.umd.js')}}" crossorigin></script> ` 
    ` <script src="{{ asset('js/ohif/dicom-rt/index.umd.js')}}" crossorigin></script> ` 
    ` <script src="{{ asset('js/ohif/dicom-segmentation/index.umd.js')}}" crossorigin></script> ` 
    ` <script src="{{ asset('js/ohif/dicom-tag-browser/index.umd.js')}}" crossorigin></script> ` 
    ` <script src="{{ asset('js/ohif/vtk/index.umd.js')}}" crossorigin></script>` 
    ` <script src="{{ asset('js/ohif/app-config.js')}}"></script> ` 
   `  <script>` 
    `   var containerId = 'root';` 
     `  var componentRenderedOrUpdatedCallback = function () {` 
    `     console.log('OHIF Viewer rendered/updated');` 
     `  };` 
     `  window.OHIFViewer.installViewer(` 
       `  window.config, // See  /config/default.js`
       `  containerId,` 
      `   componentRenderedOrUpdatedCallback` 
   `    );` 
    ` </script>` 
       
`   </body>`

In the view i got this error: **_ToolbarRow: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings._**
![Screenshot_20210426_161252](https://user-images.githubusercontent.com/19681750/116103814-3b0b8e00-a6b0-11eb-84a5-9f4e50f363b4.png)

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
