### ISSUE TITLE
/local to upload study from local on feat/v2-main

### ISSUE THREAD

**Issue by laithdj** [OHIF/Viewers#2385]
Hello , 
In the master branch there is a ViewerLocalFileData that upload dicom studies form local machine . 
is this implemented in the branch feat/v2-main also?

Is there a way to have similar functionality in this branch?

**Comment by fmansour10** [comment]
I have the same question

**Comment by sedghi** [comment]
latest master has a upload feature. Please see local_orthanc file to see how
