### ISSUE TITLE
Building Custom tool

### ISSUE THREAD

**Issue by ayamgorengtelur** [OHIF/Viewers#2386]
Hi everyone,

In the past week i've tried to comprehend on the official docs of cornerstone tool.
Unfortunately, i failed to understand on how to create new tool. Ive only manage on how to create custom marker tool in  #2025.
But, i need more reference on other tool such as length tool, cobbangletool or any custom tool that you guys had created and it will help me in my custom tool development.
The tool that i want to create is CTR tool which it has two line where the first line is for the heart length and the second is for internal diaphragm length. Then, it will calculate the ratio automaticly.
Your guys help will be very much appreciated. Thank You

**Comment by ayamgorengtelur** [comment]
after reverse engineering cobb angle tool and #1372 tool, I've succeed in creating CTR tool

**Comment by andresmmujica** [comment]
Hi @ayamgorengtelur  is there any place I can take a look on what you did and how you did it?  I want to add some tools but the lack of documentation and guides has become an issue to improve ohif-viewer

**Comment by IT-Highmore** [comment]
> after reverse engineering cobb angle tool and #1372 tool, I've succeed in creating CTR tool

Now I want to create CTR tool the same as you. @ayamgorengtelur  0.0

**Comment by boxedge** [comment]
hi guys, I found this thread interesting as I'm trying to build a CTR tool but not having much luck, keeps saying it's not available in corner stone tools - any help is appreciated
