### ISSUE TITLE
POST STUDIES

### ISSUE THREAD

**Issue by MongiBr** [OHIF/Viewers#2390]
I download dcmjs server and i tested it in postman  localhost:5895/studies 
file works in form-data 
but not works on POST request in reactjs with axios (STOW. Error: Response message has no multipart mime header)
how can i fix it ?
someone help me please!

**Comment by leonopteryx130** [comment]
have you fixed it?I have the same problem,can you help me ?

**Comment by MongiBr** [comment]
You have to add content-Type: form-data

headers: {
  
      'Content-Type': 'multipart/form-data'
    }

About the data : you have to use an instance of FormData then append your files

**Comment by MongiBr** [comment]
This is my code : 
handleSubmit =   event=> {
        event.preventDefault()

        const formData= new FormData();
        for (let i = 0; i < this.state.imageList.length; i++) {
        formData.append(`files[${i}]`,this.state.imageList[i])
        }
        const  taille=this.state.imageList.length;
        console.log('files : ', this.state.imageList)
        this.setState({loading:true});
        axios.post('http://localhost:5985/studies',formData,this.options, {
          headers:{
            'Content-Type':'multipart/form-data; type=application/dicom; boundary=--594b1491-fdae-4585-9b48-4d7cd999edb3',
            'Content-Length':taille || 0

          }
        })

        .then((res)=> {

            this.setState({percentage:100})
            this.setState({
              messageSucces:res.data,

            })


         } ).catch(err => { this.setState({
              messageError:err.message,

            }) });

 }

**Comment by amazarviz** [comment]
One scenario in which this error can occur is when the a BulkDataURI field has some invalid value, such as  "BulkDataURI": "N/A"
This causes the ohif viewer to attempt to load data from a bad url which can then default to the window's url. The function that tries to parse the expected binary response receives an html string instead, and throws the error

**Comment by sedghi** [comment]
We recently have added the upload which uses STOW. Can you try again on latest master?

Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
