### ISSUE TITLE
How to add button 3D

### ISSUE THREAD

**Issue by MongiBr** [OHIF/Viewers#2391]
Can i add button 3D in viewer?

**Comment by sedghi** [comment]
Right now you can launch 3D view from hanging protocol https://viewer.ohif.org/viewer?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2&hangingprotocolId=mprAnd3DVolumeViewport

But we have plan to add it to the UI soon
