### ISSUE TITLE
Use modified cornerstone tools 

### ISSUE THREAD

**Issue by donghakang** [OHIF/Viewers#2392]
Hello community!

I read couple discussions about this but they didn't help me.
Not only creating new tools from cornerstone-tools, I had to fix and create many thing in cornerstone-tools. So I forked from cornerstone-tools, modified it, and published to npm (@<username>/cornerstone-tools)

Is there anyway to use @<username>/cornerstone-tools instead of current version (^4.20.1, in package.json files)?

Specific steps might help me a lot.

**Comment by sedghi** [comment]
I think it does makes sense for us to create documentation on how to create new tools. But meanwhile, we have couple of tools that you can inspire from. 

extensions/cornerstone-dicom-sr/src/tools/DICOMSRDisplayTool.ts
extensions/cornerstone/src/tools/ImageOverlayViewerTool.tsx
