### ISSUE TITLE
The Cobb's Angle Tool

### ISSUE THREAD

**Issue by dbejarano32** [OHIF/Viewers#2399]
> :hand: Many people requests features. Tell us why yours is important to the
> community. How does it add value? Why _this feature_?
>
> Is your request very specific to your needs? Consider
> [contributing it](https://docs.ohif.org/contributing.html) yourself! Or reach
> out to a community member that offers
> [consulting services](https://docs.ohif.org/help.html#paid--commercial).

## Request

**What feature or change would you like to see made?**
Is very necessary cobb's angle, in the OHIF web viewer.
...

**Why should we prioritize this feature?**
The cobb's angle is a basic tool in any radiology viewer...
...

**Comment by ranasrule** [comment]
this would be a great addition

**Comment by jensen0914** [comment]
I vote for this also. I believe it is already embedded in the cornerstone viewer and can be exposed as a tool on the viewer toolbar.

**Comment by matthiasg** [comment]
Just having the angle between two independent lines would already be pretty perfect. The way angles are measured now with three points is not useful in most cases we have.

**Comment by andresmmujica** [comment]
Hi, is there any documentation on how to implement or expose the cobb's angle tool to Ohif Viewer?

**Comment by dbejarano32** [comment]
I have put a pull request with a "Cobb's Angle expose as a tool". 
https://github.com/OHIF/Viewers/pull/2505

**Comment by sedghi** [comment]
we only expose tools that later we can create a SR report from, so that is why. I'm not sure if we have the SR adapter for Cobb angle so that is why

**Comment by sedghi** [comment]
https://www.cornerstonejs.org/live-examples/stackannotationtools
