### ISSUE TITLE
Windows Deploy

### ISSUE THREAD

**Issue by fmrcenter** [OHIF/Viewers#24]
Any one succeed in deploying OHIF in a windows machine?
It always fail with errors.
I tested both 32  & 64 versions of windows

The error log is:

W20160623-14:53:18.244(3)? (STDERR)
W20160623-14:53:18.244(3)? (STDERR) C:\Users\Win7-32\AppData\Local\.meteor\packa
ges\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\
fibers\future.js:245
W20160623-14:53:18.244(3)? (STDERR)
throw(ex);
W20160623-14:53:18.244(3)? (STDERR)
      ^
W20160623-14:53:18.244(3)? (STDERR) ReferenceError: Accounts is not defined
W20160623-14:53:18.244(3)? (STDERR)     at app\Packages\active-entry\lib\Account
s.js:35:3
W20160623-14:53:18.244(3)? (STDERR)     at app\Packages\active-entry\lib\Account
s.js:50:4
W20160623-14:53:18.244(3)? (STDERR)     at C:\OHIF\Viewers-master---\Viewers-mas
ter\OHIFViewer\.meteor\local\build\programs\server\boot.js:283:10
W20160623-14:53:18.244(3)? (STDERR)     at Array.forEach (native)
W20160623-14:53:18.244(3)? (STDERR)     at Function._.each._.forEach (C:\Users\W
in7-32\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\d
ev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160623-14:53:18.244(3)? (STDERR)     at C:\OHIF\Viewers-master---\Viewers-mas
ter\OHIFViewer\.meteor\local\build\programs\server\boot.js:133:5
=> Exited with code: 8

**Comment by gitmribeiro** [comment]
Same mistake! The Phorum does not work ... I did my registration to 4 days and I am waiting for the confirmation e-mail today.

Can anyone help?

**Comment by swederik** [comment]
I wasn't able to reproduce this problem on a PC with Windows 10, and I can't see any reason why it would occur for the OHIFViewer since the active-entry package isn't even part of that application. Nevertheless I have updated both the Viewer and Lesion Tracker to Meteor 1.3.4.4 and tested them both on Windows.

![screenshot 2016-07-17 10 59 55](https://cloud.githubusercontent.com/assets/607793/16899696/d46a92e2-4c0d-11e6-9a87-bf75eb457ad2.png)

On the top you have the Lesion Tracker, and on the bottom the OHIF Viewer. Everything seems to be working for me. Could you test this again with the latest master?

**Comment by gitmribeiro** [comment]
Hello Erik,

Thanks for the support, the print previously sent was using Windows7, now
I'm trying on Windows8.1, the error remains but the messages have changed,
see:

Important: I used the Docker with a container ubuntu and it works perfectly,
but in Windows is difficult.
- My meteor Version: 1.3.2.4
- My nodejs version: 4.2

[image: Imagem inline 1]

Thank you,
Marcelo

2016-07-17 6:02 GMT-03:00 Erik Ziegler <notifications@github.com>:

**Comment by swederik** [comment]
Are you sure you've updated the Viewers repository from master? Your meteor version shouldn't be 1.3.2.4 anymore, instead it should say 1.3.4.4.

I can't see the image you're trying to post. It just shows up as [image: Imagem inline 1]. I'm trying to find a machine with Windows 7 to test on.

**Comment by swederik** [comment]
Just tested on Windows 7 with a fresh Meteor install on the latest master and I had no problems.

You'll need to add PACKAGES_DIR=..\Packages to your system environment variables, but other than that it works fine. Maybe try removing and redownloading the repository?

**Comment by gitmribeiro** [comment]
Hello Erik,

Perfect! 1 million excuses ...
Following in his footsteps, I cloned again from github and everything
worked (win8), thank you for your support!

Problem solved!

Thanks!
Marcelo

2016-07-18 5:20 GMT-03:00 Erik Ziegler <notifications@github.com>:

**Comment by swederik** [comment]
Awesome!
