### ISSUE TITLE
Is there any way to load a specific series ID and object ID in a study?

### ISSUE THREAD

**Issue by atisman89** [OHIF/Viewers#241]
Hello, I am wondering if there is a way to load a specific series and object (image/slice) initially in a study. For example, can we specify study id, series id, and object id at the same time in the URL so that the viewer would set the specific series and image at the time of initial loading of the study? Hope this question is clear and let me know if it is not. We are trying to use the (standalone) viewer in the context of our application and make it interact with other part of the app. Thanks!

**Comment by swederik** [comment]
What you're talking about is a hanging protocol. That's not currently supported in the standalone viewer.

**Comment by atisman89** [comment]
What is a hanging protocol? How does it work with the regular viewer (not standalone)? Thanks.

**Comment by dannyrb** [comment]
@atisman89, I realize that this is an old issue, and specific to `v1` of the OHIF Viewer, but I think it's a good candidate for our roadmap backlog. I'm going to close this issue, but you can track progress on this card:

https://github.com/OHIF/Viewers/projects/3#card-21713635

**Comment by kokokenada** [comment]
@dannyrb - we have the same question. Is there an updated link?
