### ISSUE TITLE
Development environment can be configured Orthanc, but what about the production environment, how to get开发环境可以配置Orthanc,那生产环境呢，怎么弄

### ISSUE THREAD

**Issue by ajn400** [OHIF/Viewers#2411]
[package.json](https://github.com/OHIF/Viewers/blob/master/package.json)
关于构建的问题，本地环境连接orthanc的pacs很方便，我想在ubuntu上部署也连接orthanc服务，可是关于build的script没有相应的，build后直接拖拽到netlify,连接的全是osimis的公开资源，我不是很会，求救

I want to deploy on ubuntu and connect to orthanc services, but there is no corresponding script for build, and after build, I directly drag and drop to netlify, and the connection is all osimis public resources, I am not very good at it, please help!

**Comment by Davi-Wei** [comment]
列表字段显示中文，还是内容显示中文？

**Comment by Davi-Wei** [comment]
> 你可以试试用nginx做端口转发，或者用frp做端口转发。把本地的8042映射过去。话说老哥，你知道怎么让OHIF的病例列表显示中文吗？

列表字段显示中文，还是内容显示中文？

**Comment by felixlinxk** [comment]
> 
就像我在这个issue里描述的这样
https://github.com/OHIF/Viewers/issues/2716

**Comment by sedghi** [comment]
Take a look at our deployment recipes https://docs.ohif.org/deployment/build-for-production
