### ISSUE TITLE
Hard coded colors

### ISSUE THREAD

**Issue by paul-asvb** [OHIF/Viewers#2414]
## Bug Report

Theme colors can't overwrite hard coded colors in certain places.
Example here:

https://github.com/OHIF/Viewers/blob/master/platform/ui/src/components/studyBrowser/StudyBrowser.styl#L6

### Describe the Bug

When trying to overwrite the default colors some components wont take the color from the :root css variables.

### How to find all hardcoded colors:
search for
`#([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?`
and exclude:
`*.svg, *.lock, *.md`

### Solution suggestion:
Replace them with css variables.
e.g. change `background-color: black` to `background-color:  var(--primary-background-color)`

**Comment by sedghi** [comment]
You should modify the tailwind configuration. Since we moved to tailwindcss

**Comment by nicoesiea** [comment]
Is it possible to ask for an example? For example, how to change the top bar color? The one with the tool icones?

**Comment by paul-asvb** [comment]
@sedghi that was a great decision. @nicoesiea i haven't tried, but from my experience with tailwind: Change this file `https://github.com/OHIF/Viewers/blob/master/platform/ui/tailwind.config.js ` and build the viewer.

**Comment by nicoesiea** [comment]
Just be careful, there are two tailwind.config.js files (the first in the APP folder and the second in UI). 
I do not understand the reason for these two files.
NOTE I created a new issue for splitButton hard-coded color (https://github.com/OHIF/Viewers/issues/3767)
