### ISSUE TITLE
Publishing Privately

### ISSUE THREAD

**Issue by evan-morgan** [OHIF/Viewers#2416]
Hi guys,

Just wondering, is there a special script/command to run to publish this package? I've basically made some edits to the code and want to host it within my organisation on npm. I've done the simple `npm login`, then `yarn publish` but it shows the package having a lot less dependencies and being much larger than your @ohif/viewer package on npm so I feel there must be something I'm doing wrong.

Any help is appreciated!

Thanks
Evan

**Comment by sedghi** [comment]
OHIF has moved away from using packages. 
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
