### ISSUE TITLE
Problem loading the US image. Image overwriting

### ISSUE THREAD

**Issue by pilacoepouco** [OHIF/Viewers#2420]
I have a problem loading images in US mode, all of them are overwritten. I'm accessing via URL.

![image](https://user-images.githubusercontent.com/53221609/119730769-7aaecc80-be4c-11eb-9259-7f73b4d1a3ec.png)

![image](https://user-images.githubusercontent.com/53221609/119731125-ee50d980-be4c-11eb-84a4-3029c9c7e101.png)

Any idea what it might be?

**Comment by pilacoepouco** [comment]
I found the solution by adding the TAG PlanarConfiguration in the JSON of the instance.

**Tag**                 
 (0028,0006) 
 **VR**
  US   
 **Name** 
  Planar Configuration

**Comment by shlomgad** [comment]
@pilacoepouco Can you please explain how exactly are you adding this tag to the JSON ?
Is it: "PlanarConfiguration" : "US"  ?

**Comment by ed-morais** [comment]
Hello, @pilacoepouco!
How can I access the JSON of the instance?

**Comment by Shuun26** [comment]
Thanks @pilacoepouco, but how do I find this JSON instance?

**Comment by pilacoepouco** [comment]
@Shuun26  and @ed-morais  I use a DICOMWeb server which returns a JSON. Following the documentation reference : https://v3-docs.ohif.org/configuration/dataSources/dicom-json

**Comment by Shuun26** [comment]
> @Shuun26 and @ed-morais I use a DICOMWeb server which returns a JSON. Following the documentation reference : https://v3-docs.ohif.org/configuration/dataSources/dicom-json

Thank you so much! 
Looking for some info in https://dicom.innolitics.com/ciods/rt-dose/image-pixel/00280006. Discovereded something interesting, the planar configuration solves the error because in some studies the tag Samples per Pixel has a value greater than 1, and, for some reason (I could be wrong, so please tell me if I'm ignoring something) the OHIF Viewer it's ignoring the Planar Configuration, because in the metadata doesn't appers the PlanarConfiguration tag.

Psd: So sorry for my bad redaction in English.

![image](https://user-images.githubusercontent.com/68860132/153613506-825c3db8-51af-47c5-91ac-96e4fd590eed.png)

**Comment by RoshniPal** [comment]
Hello @pilacoepouco ,
I did add the PlanarConfiguration tag in the instance JSON and the structure looks like below.
{
	"studies": [{
		"StudyInstanceUID": "1.2.8",
		"StudyDescription": "",
		"StudyDate": "20000415",
		"StudyTime": "120035",
		"PatientName": "0000015",
		"PatientId": "",
		"series": [{
			"SeriesDescription": "",
			"SeriesInstanceUID": "1.2.840.",
			"SeriesNumber": 1,
			"SeriesDate": "20180415",
			"SeriesTime": "120835",
			"Modality": "US",
			"instances": [{
				"metadata": {
					"Columns": 800,
					"Rows": 600,
					"InstanceNumber": 11,
					"AcquisitionNumber": null,
					"PhotometricInterpretation": "YBR_FULL_422",
					"BitsAllocated": 8,
					"BitsStored": 8,
					"PixelRepresentation": null,
					"SamplesPerPixel": 4,
					"PlanarConfiguration": 0
					"PixelSpacing": [],
					"HighBit": 7,
					"ImageOrientationPatient": [],
					"ImagePositionPatient": [],
					"FrameOfReferenceUID": [],
					"ImageType": ["DERIVED", "PRIMARY", "CARDIOLOGY"],
					"Modality": "US",
					"SOPInstanceUID": "1.2.840.",
					"SeriesInstanceUID": "1.2.840.11",
					"StudyInstanceUID": "1.2.840."
				},
				"url": "dicomweb:https://dummy.yrl.com/00010202.dcm"
			}]
		}]
	}]
}

But the image still appears overwritten. Am I missing on anything here?

**Comment by Shuun26** [comment]
> Hello @pilacoepouco , I did add the PlanarConfiguration tag in the instance JSON and the structure looks like below. { "studies": [{ "StudyInstanceUID": "1.2.8", "StudyDescription": "", "StudyDate": "20000415", "StudyTime": "120035", "PatientName": "0000015", "PatientId": "", "series": [{ "SeriesDescription": "", "SeriesInstanceUID": "1.2.840.", "SeriesNumber": 1, "SeriesDate": "20180415", "SeriesTime": "120835", "Modality": "US", "instances": [{ "metadata": { "Columns": 800, "Rows": 600, "InstanceNumber": 11, "AcquisitionNumber": null, "PhotometricInterpretation": "YBR_FULL_422", "BitsAllocated": 8, "BitsStored": 8, "PixelRepresentation": null, "SamplesPerPixel": 4, "PlanarConfiguration": 0 "PixelSpacing": [], "HighBit": 7, "ImageOrientationPatient": [], "ImagePositionPatient": [], "FrameOfReferenceUID": [], "ImageType": ["DERIVED", "PRIMARY", "CARDIOLOGY"], "Modality": "US", "SOPInstanceUID": "1.2.840.", "SeriesInstanceUID": "1.2.840.11", "StudyInstanceUID": "1.2.840." }, "url": "dicomweb:https://dummy.yrl.com/00010202.dcm" }] }] }] }
> 
> But the image still appears overwritten. Am I missing on anything here?

@RoshniPal Maybe the problem is that you have some Dicom Tags with null values, specifically that PixelRepresentation, I think that tag it's really important.
https://dicom.innolitics.com/ciods/rt-dose/image-pixel/00280103

**Comment by pilacoepouco** [comment]
I believe that @Shuun26 is right, here is a metadata that is working:
```
"metadata": {
                "Columns": 1024,
                "Rows": 768,
                "InstanceNumber": "5",
                "PhotometricInterpretation": "YBR_FULL",
                "BitsAllocated": 8,
                "BitsStored": 8,
                "PixelRepresentation": 0,
                "SamplesPerPixel": 3,
                "HighBit": 7,
                "ImageType": [
                  "DERIVED",
                  "PRIMARY"
                ],
                "Modality": "US",
                "SOPInstanceUID": "1.2.826.0.1.3680043.8.195.3.1.1.4.359664740.2012.1631534355.6",
                "StudyInstanceUID": "1.2.826.0.1.3680043.8.894.52.20210913065542950696018",
                "SeriesInstanceUID": "1.2.156.112536.1.2112.80192205242.1395492013640.2",
                "PlanarConfiguration": 0,
                "PatientName": {
                  "Alphabetic": "Sanches^Radames Pacheco"
                },
                "PatientID": "168820",
                "PatientAge": "048Y",
                "StudyDescription": "ULTRASSONOGRAFIA DE ARTICULACAO",
                "StudyDate": "20210913",
                "StudyTime": "081844"
              }
```

**Comment by pilacoepouco** [comment]
I believe that @Shuun26 is right, here is a metadata that is working:
```
{
  "metadata": {
    "Columns": 1024,
    "Rows": 768,
    "InstanceNumber": "5",
    "PhotometricInterpretation": "YBR_FULL",
    "BitsAllocated": 8,
    "BitsStored": 8,
    "PixelRepresentation": 0,
    "SamplesPerPixel": 3,
    "HighBit": 7,
    "ImageType": [
      "DERIVED",
      "PRIMARY"
    ],
    "Modality": "US",
    "SOPInstanceUID": "1.2.",
    "StudyInstanceUID": "1.2.",
    "SeriesInstanceUID": "1.2.",
    "PlanarConfiguration": 0,
    "PatientName": {
      "Alphabetic": "..."
    },
    "PatientID": "...",
    "PatientAge": "048Y",
    "StudyDescription": "ULTRASSONOGRAFIA DE ARTICULACAO",
    "StudyDate": "20210913",
    "StudyTime": "081844"
  },
  "url": "dicomweb:https:/..."
}
```

**Comment by RoshniPal** [comment]
Thank you so much for helping here @Shuun26  and @pilacoepouco. However, I had an observation wrt the value of PhotometricInterpretation tag's value. It seems the issue persists if the tag's value is "YBR_FULL_422" but resolves when changed to or originally the value is YBR_FULL or RGB. Any idea why the behaviour is so?
Additionally, the above JSON structure resolves the overwritten problem but not the viewing of all the frames of dicom image (only one frame is visible.) Do we have any solution around this?

**Comment by Shuun26** [comment]
@RoshniPal I think it's because you're getting just one frame per instance, when a instance has multiple frames, looks like this:
`
{
  "studies": [
    {
      "PatientID": "117",
      "PatientName": "John Doe",
      "StudyDate": "25420210",
      "StudyDescription": "Kneck Ultrasound",
      "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390",
      "StudyTime": "103312",
      "series": [
        {
          "Modality": "US",
          "SeriesDate": "25420210",
          "SeriesDescription": "",
          "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
          "SeriesNumber": "1",
          "SeriesTime": "103312",
          "instances": [
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 1,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.1.1104321",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.1.1104321"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 10,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.10.10105333",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.10.10105333"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 11,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.11.11105422",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.11.11105422"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 12,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.12.12105438",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.12.12105438"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 13,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.13.13105455",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.13.13105455"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 14,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.14.14105534",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.14.14105534"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 15,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.15.15105559",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.15.15105559"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 16,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.16.16105649",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.16.16105649"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 2,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.2.2104508",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.2.2104508"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 3,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.3.3104720",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.3.3104720"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 4,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.4.4104837",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.4.4104837"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 5,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.5.5104859",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.5.5104859"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 6,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.6.6105029",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.6.6105029"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 7,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.7.7105142",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.7.7105142"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 8,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.8.8105208",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.8.8105208"
            },
            {
              "metadata": {
                "AcquisitionNumber": 0,
                "BitsAllocated": 8,
                "BitsStored": 8,
                "Columns": 1024,
                "HighBit": 7,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "InstanceNumber": 9,
                "Modality": "US",
                "PhotometricInterpretation": "RGB",
                "PixelRepresentation": 0,
                "PlanarConfiguration": 0,
                "Rows": 768,
                "SOPInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1.9.9105259",
                "SamplesPerPixel": 3,
                "SeriesInstanceUID": "1.2.410.200001.1.6.1.25420210103312453.1",
                "StudyInstanceUID": "1.2.410.200001.1.6.1.25420210103312390"
              },
              "url": "dicomweb:http://xxx.xxx.xxx.xxx:xxxx/api/DicomFile/SOPInstanceUID/1.2.410.200001.1.6.1.25420210103312453.1.9.9105259"
            }
          ]
        }
      ]
    }
  ]
}

`
As you seen when an instance has multipleframes, in JSON you'll multiple metadata objects
Note: I'm using pydicom and pynetdicom to generate all this JSON

**Comment by RoshniPal** [comment]
@Shuun26 The above structure looks like for a series which has multiple images (16 instances) in it (The above structure I shared was a series with single image hence one metadata object).  How does the JSON structure differs for multiframe image ?
