### ISSUE TITLE
Guidance with segmentations

### ISSUE THREAD

**Issue by sinanmb** [OHIF/Viewers#2421]
Hi, 

I'm working on allowing users to paint segmentations on the viewport. I have displayed the segmentation tools in the toolbar and am able to paint on the viewport. In the segmentation panel, all the painting I did on the viewport is combined within one single segment. I'm looking for guidance to be able to paint a second, separate segment (that would have a different color and name) 

Appreciate any inputs.

**Comment by sedghi** [comment]
We just released the segmentation support, read here https://ohif.org/release-notes/3p7
