### ISSUE TITLE
Feature: Synchronous scrolling across aligned studies/series

### ISSUE THREAD

**Issue by matthiasg** [OHIF/Viewers#2428]
As already mentioned in #50 for real diagnostic work, it is often required for the radiologists to compare two series (potentially from different studies) to scroll synchronously. Either based on image index (with previous alignment and same number/thickness of slices) or via mm distance.

Is this (at least within the same study) a possibility or at least something were someone could give us some pointers as to which pieces of the code to touch in order to create a plugin/pull request ?

**Comment by salimkanoun** [comment]
it's pending there

https://github.com/OHIF/Viewers/pull/2169

**Comment by matthiasg** [comment]
Thanks. @swederik can you provide more input as to the status or if #2334 is related in getting this integrated ?

**Comment by matthiasg** [comment]
I merged in that branch in my own clone and it works pretty well.

**Comment by sedghi** [comment]
We have stack scroll sync in the master 


![CleanShot 2023-10-13 at 13 25 07](https://github.com/OHIF/Viewers/assets/7490180/80b3d255-1e3d-423d-a49d-843f39233f1c)
