### ISSUE TITLE
Download Complete Study via Download Dialog

### ISSUE THREAD

**Issue by Christian-e-S** [OHIF/Viewers#2430]
OHIF is a perfect frontend to the Google Healthcare API, and they both make up a complete PACS solution that is super easy to deploy.

Still, we see that many clinicians (e.g., clinical advisors in clinical studies) want to use their preferred and super-feature-rich (e.g., with fusion capability) locally installed DICOM viewers. 

A common workflow would be:
* Clinical advisor uses OHIF to log in the Web-based PACS (e.g., backed-up by Google Healthcare API)
* Clinical advisor can search/filter contents via OHIF
* Investigate the images online with OHIF capabilities
* When required, the user downloads the entire study of interest to his local machine (maybe even download multiple studies at once!) and switches to his local viewer.
* Over time, OHIF will get more and more features, and users will use their local viewers less and less.

The missing download capability is preventing to get the foot into the doors.

There is a related issue https://github.com/OHIF/Viewers/issues/1130# where a debugging extension has been developed that can be triggered with a shortcut. That is already great, but seems to be targeted on developers and not on end-users. There is no UI and any feedback is only visible in the developer console.

Augmenting the existing solution mentioned above with a simple download dialog, or at least a notification (e.g., "download started") would lift the feature to be acceptable by a standard medical user.

**Comment by pieper** [comment]
Agreed, this would be a nice general purpose features.  Note that for the IDC use case we only wanted this for debugging since we don't want to encourage downloads so restricted the scope to be consistent with our funding.  But this shouldn't prevent others from implementing this, ideally as an optional feature.

For reference here is the command that can be pasted in the developer console to initiate a download:
```
ohif.app.commandsManager.runCommand("downloadAndZip", {listOfUIDs: [window.location.href.split("/").pop()]})
```

**Comment by Christian-e-S** [comment]
> Agreed, this would be a nice general purpose features. Note that for the IDC use case we only wanted this for debugging since we don't want to encourage downloads so restricted the scope to be consistent with our funding. But this shouldn't prevent others from implementing this, ideally as an optional feature.
> 
> For reference here is the command that can be pasted in the developer console to initiate a download:
> 
> ```
> ohif.app.commandsManager.runCommand("downloadAndZip", {listOfUIDs: [window.location.href.split("/").pop()]})
> ```

@pieper:
I have created a pull request for a dedicated study download module.

Compared to the debugging extension, I had to choose a different phase because of the following reasons:

1) I do not use the progressTrackingUtils to monitor the progress of the download

 * I have made a new commit to the dicomweb-client https://github.com/dcmjs-org/dicomweb-client, which allows to get download progress information
 * Unfortunately, for the Google Healthcare API, the XMLHttpRequest can get only the downloaded bytes, but not the total bytes.  Therefore, I cannot calculate the percentage, and to my understanding the progressTrackingUtils need a value between zero and one.
 * Therefore, I decided to show to the user the progress in terms of downloaded bytes without relying on the progressTrackingUtils.
 * Please note, for this to work, you need the latest commit of the master branch of the dicomweb-client. The extension works still with older versions of the dicomweb-client, but you will not see the progress in terms of downloaded bytes.

2) I do not grab the StudyInstanceUID from the "sudies" storeContext (as in downloadAndZipStudy({ servers, studies, progress })), since this would work only for the very first selected study. If the user selects a study, and then subsequently selects another study, the "studies" object will have two studies (each time the user selects a new study, it will be added to this list), and the downloadAndZipStudy function will take always the very first entry in "studies" which is not what the user would expect.

* Therefore, I grap the  StudyInstanceUID  from the active viewport.

That being said, the debugging extension was a great starting point. Thank you very much!

**Comment by pieper** [comment]
Thanks for contributing this, it looks good to me 👍

**Comment by sedghi** [comment]
Currently, there is no plan for this particular matter in OHIF v3. Therefore, I will proceed to close it as "not planned."
