### ISSUE TITLE
Sort AcquisitionNumber in metadata

### ISSUE THREAD

**Issue by andytino** [OHIF/Viewers#2434]
Hi
I have loaded the images using http endpoint, and in the file DICOM JSON, i have multiples AcquisitionNumber in the same ImageSet, 
example:
displaySets: Array(5)
  ...
  2: ImageSet
    InstanceNumber: 1
    Modality: "CT"
    ...
   inconsistencyWarnings: (3) ["The dataset frames have different pixel spacing.", "The datasets is not a reconstructable 3D volume. MPR mode is not available.", "The datasets is missing frames: 41."]
  images: Array(159)
       [0 … 99]
            0: OHIFInstanceMetadata
            data
                metadata:
                   AccessionNumber: null
                   AcquisitionDate: "20210528"
                   **AcquisitionNumber: 4**
            1: OHIFInstanceMetadata
            data
                metadata:
                   AccessionNumber: null
                   AcquisitionDate: "20210528"
                   **AcquisitionNumber: 3**
So when i scroll mouse, the images show out of frame. please guide me in this
![test](https://user-images.githubusercontent.com/56918936/120419954-973b8f00-c38d-11eb-9af7-b12023a93d63.gif)

**Comment by sedghi** [comment]
I think you should write your own sop class handler to detect this and split them into separate displaySets
