### ISSUE TITLE
Authorization header not included 

### ISSUE THREAD

**Issue by amita125** [OHIF/Viewers#2436]
The issue I am facing is Eventhough I have send the Bearer token in the requestOptions , it takes the value the first time but if the page is refreshed the Bearer token is not present in header.

```
requestOptions: {
          auth: () => {
            return 'Bearer xxxxx';
          },
        },
```
This is the console log I get back , the first getAuthorisation gets the bearer from the request option but then after refresh nth.

![Capture](https://user-images.githubusercontent.com/49608334/120450546-745aac00-c388-11eb-9903-5c24a35a36b7.PNG)
![Capture1](https://user-images.githubusercontent.com/49608334/120450588-7a508d00-c388-11eb-977d-9c3e91e19930.PNG)

First img as soon as viewer load and the second when refreshed

**Comment by papy-ganjha** [comment]
I face the same issue how did you solve it? :smile:
