### ISSUE TITLE
Best way to display limited subset of scans from an image archive 

### ISSUE THREAD

**Issue by hpardoe** [OHIF/Viewers#244]
Hi all

I have OHIF Viewer running with images served using Orthanc & DICOM Web. I would like to restrict the scans displayed to a specific list (subjects with pathology). But would like to keep the rest of the scans on the Orthanc server for use in the future. Is there a way to do this?

Best wishes
Heath

**Comment by swederik** [comment]
That's a very good question... I know some PACS like dcm4chee can have virtual AE titles, and data can be separated into distinct compartments / requested by AE title. I don't know how that works with Orthanc.

**Comment by dannyrb** [comment]
As we gear up to formally announce a Version 2 of the OHIF Viewer, we're making an effort clean up stale issues. As this is an older issue, I'm going to go ahead and close it for now. Please don't let that discourage you from opening new issues, or continuing your conversation here.

I did take a peak at the `DICOMweb` plugin for Orthanc: https://book.orthanc-server.com/plugins/dicomweb.html#making-a-call-to-qido-rs-or-wado-rs

You might be able to use a custom DICOM tag to identify your groups, and then filter on it for all queries? Or split your collection across multiple DICOMweb instances, and only configure your viewer for the collection(s) you want to be viewed?
