### ISSUE TITLE
2dmpr function error

### ISSUE THREAD

**Issue by ldzxp** [OHIF/Viewers#2440]
Hello! When we use the 2dmpr function, when the number of DCM files reaches more than 1600, the memory occupation rate will reach 100%, and it will not be automatically released, and the browser will crash directly! Our configuration is windows 10, i5-10050, 16g memory. Hope to reply!

url:    dicom.heguyun.com

**Comment by sedghi** [comment]
See these that might be helpful 

- https://github.com/OHIF/Viewers/issues/3207
