### ISSUE TITLE
How do I configure the azure storage into OHIF

### ISSUE THREAD

**Issue by pmd23** [OHIF/Viewers#2441]
Hi Team,

I am trying to incorporate the standalone ohif viewer into my existing web application also I dont have an any wado server. I am displaying the dicom images from azure storage. So how I can configure that azure path into standalone viewer. 

for this what values do I need to configure into default.js file.

**Comment by sedghi** [comment]
Using dicomjson is simple. However, there is an important note that you should consider. Please read it here. https://docs.ohif.org/configuration/dataSources/dicom-json
