### ISSUE TITLE
ImageThumbnail causes infinite callback when image loading failed

### ISSUE THREAD

**Issue by PoyangLiu** [OHIF/Viewers#2443]
### Describe the Bug

The `ImageThumbnail` class `useEffect` includes [many functions as its dependencies](https://github.com/OHIF/Viewers/blob/78f1a7f3e5df07fc6adeb10dda4f8672a4cc1d79/platform/ui/src/components/studyBrowser/ImageThumbnail.js#L93).  When writing functional component, these local functions are created every single time the component is rendered.  This causes the `useEffect` code to be triggered every single render.  

The image loading promise is wrapped in a `cancellablePromise` and the `cancel` method is called if load failed.  But because all the functions are recreated, the correctly cancelled `cancellablePromise` is purged and re-created, causing it to be un-cancelled.  

### What steps can we follow to reproduce the bug?

These steps was only reproduced in a private customized version of OHIF/Viewers.  So I did not actually reproduce with pure OHIF/Viewers.  But I'm sure the problem is there and the steps are as followed

1. Shutdown the WADO service, causing the image thumbnail loading to fail
2. Set a breakpoint at [`cancelablePromise = utils.makeCancelable(...)`](https://github.com/OHIF/Viewers/blob/78f1a7f3e5df07fc6adeb10dda4f8672a4cc1d79/platform/ui/src/components/studyBrowser/ImageThumbnail.js#L68)
3. Set a breakpoint at the cancelablePromise error handler [`if (error.isCanceled) return;`](https://github.com/OHIF/Viewers/blob/78f1a7f3e5df07fc6adeb10dda4f8672a4cc1d79/platform/ui/src/components/studyBrowser/ImageThumbnail.js#L59)

Observed that
2. `cancelablePromise` is recreated at every render
3. `cancelablePromise.isCanceled` is always false

The following 3 dependency functions, `fetchImagePromise`, `setImagePromise` and `purgeCancelablePromise` should be wrapped in [`useCallback`](https://reactjs.org/docs/hooks-reference.html#usecallback) with their proper dependencies set.

```js
  const fetchImagePromise = useCallback(() => {
    if (!cancelablePromise) {
      return;
    }

    setLoading(true);
    cancelablePromise
      .then(response => {
        setImage(response);
      })
      .catch(error => {
        if (error.isCanceled) return;
        setLoading(false);
        setError(true);
        throw new Error(error);
      });
  }, [cancelablePromise]);

  const setImagePromise = useCallback(() => {
    if (shouldRenderToCanvas()) {
      cancelablePromise = utils.makeCancelable(
        cornerstone.loadAndCacheImage(imageId)
      );
    }
  }, [imageId]);

  const purgeCancelablePromise = useCallback(() => {
    if (cancelablePromise) {
      cancelablePromise.cancel();
    }
  }, [cancelablePromise]);
```

**Comment by jbocce** [comment]
As reported, this bug no longer occurs in the current master branch (3.8.0-beta.7). However, the  point of the promise creation being done via `useCallback` was considered and with the current thumbnail implementation `useCallback` should be used to avoid multiple promise creations for the same thumbnail/imageId.

**Comment by jbocce** [comment]
See the previous comment.
