### ISSUE TITLE
Open patient study directly from a URL without listing all patients 

### ISSUE THREAD

**Issue by hawodi** [OHIF/Viewers#2448]
Looking at opening a patient study directly using the url from my app. I have tried using 

`http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/dimse/DCM4CHEE/patients/50705` which returns a blank black page without any error and
`http://localhost/?patients/50705` which still returns all the patients.

**Comment by andresmmujica** [comment]
OHIF Viewer uses react routing, so what you need to do is to catch all request at your http server and send those to the viewer url.   With nginx it would be something like this:

`   location /viewer/ {
    try_files /viewer/index.html =404;`

**Comment by sedghi** [comment]
Have you seen URL configuration? https://docs.ohif.org/configuration/url/
