### ISSUE TITLE
Is it possible to  retrieve studies data from json objects Using Ohif as embedded viewer?

### ISSUE THREAD

**Issue by chengviz** [OHIF/Viewers#2453]
Hi all,
Thank you for this helpful open source.
We want to integrate Ohif viewer as a react component (by importing @ohif/viewer)
But we don't use any dicomWeb Services, so we have to send studies metadata as jsons.
Is there a way to pass json object as a prop to the viewer? Or there is another approach to solve this issue?
Thank you very much!

**Comment by annong163** [comment]
Hello, have you solved this problem? I have the same problem now

> 大家好， 感谢您提供这个有用的开源。 我们希望将 Ohif 查看器集成为一个反应组件（通过导入 @ohif/viewer） 但是我们不使用任何 dicomWeb 服务，因此我们必须将研究元数据作为 json 发送。 有没有办法将 json 对象作为道具传递给查看器？或者有另一种方法来解决这个问题？ 非常感谢！

**Comment by sedghi** [comment]
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
