### ISSUE TITLE
How to setup the viewer with Ubuntu/Linux, Apache and Orthanc (No docker)?

### ISSUE THREAD

**Issue by reya276** [OHIF/Viewers#2455]
``Is there any way to setup the OHIF viewer on Ubuntu/Linux apache2 without using docker?
I already have the Orthanc server installed and I can upload and actually already view studies with it's internal default viewer. However, when I try to look at them with the OHIF viewer the viewer fails and I get a CORS error.

![CORS-Error](https://user-images.githubusercontent.com/25517972/123162499-ac608680-d43e-11eb-948c-908cdb12b1f6.png)

here is the default.js wado config
`servers: {
    dicomWeb: [
      {
        name: 'ORTHANC',
        wadoUriRoot: 'http://localhost:8042/wado',
        qidoRoot: 'http://localhost:8042/dicom-web/studies',
        wadoRoot: 'http://localhost:8042/dicom-web/studies',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },`

**Comment by reya276** [comment]
well it seems like this does not work unless is with Docker. I have added the .htaccess file with
<IfModule mod_headers.c>
    		Header add Access-Control-Allow-Origin "ip:8042"
    		Header add Access-Control-Allow-Origin "domain:8042"
			Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
			Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
			Header set Cache-Control "no-store"
		</IfModule>
Yet nothing works, I also added the same thing into the vhost and I simply keep getting a damn "401
Unauthorized" How can I fix this?

**Comment by andresmmujica** [comment]
I had to put together an nginx to handle the cors issue, here the nginx.conf. the orthan may be your apache if you keep it


`http {
    server {
    listen 80 default_server;
    server_name localhost;

        #
        # Wide-open CORS config for nginx
        #
        location / {
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                #
                # Custom headers and headers various browsers *should* be OK with but aren't
                #
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                #
                # Tell client that this pre-flight info is valid for 20 days
                #
                add_header 'Access-Control-Allow-Headers' 'Authorization';
                add_header 'Access-Control-Allow-Credentials' true;
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Length' 0;
                return 204;
            }
            if ($request_method = 'POST') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
            }
            if ($request_method = 'GET') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
                add_header 'Access-Control-Allow-Headers' 'Authorization';
                add_header 'Access-Control-Allow-Credentials' true;
            }

            proxy_pass http://orthanc:8042;
        }

    }
}%`

**Comment by sedghi** [comment]
Take a look here, and if it does not work, please reopen the issue 

https://docs.ohif.org/deployment/docker
