### ISSUE TITLE
not able to access json file

### ISSUE THREAD

**Issue by shubhamvishwakarma19** [OHIF/Viewers#2459]
**Description**

hello all 
anyone can help to access json file via url.
this was working for me 22-JAN-2021 but suddenly it's not working don't know what the issues with that 
have uploaded  one file inside the folder path is **Viewers/platform/viewer/public/X-Ray-Chest.json** and run on our localhost 
**http://localhost:3000/viewer?url=X-Ray-Chest.json** it's working for me  till **22-JAN- 2021** and also working on my server as well 
http://example.com/viewer?url=X-Ray-Chest.json

but now i'm not able to accessing the json and didn't change anything in my code suddenly getting this issue and i'm not  getting  any error in the console 
<img width="1270" alt="Screenshot 2021-06-29 at 6 03 39 PM" src="https://user-images.githubusercontent.com/50484716/123798525-e3cea780-d904-11eb-8b92-d70ca334b682.png">

**Comment by sedghi** [comment]
You might need to add a fallback for 404 to index.html
