### ISSUE TITLE
IE 11 Issues with dcmjs 

### ISSUE THREAD

**Issue by esuapple03** [OHIF/Viewers#246]
I'm getting a Syntax error when trying to open OHIF in IE 11.  The error is in the ohif_cornerstone.js file after the dcmjs was added to that package.  IE 11 doesn't like the 'class'  in the dcmjs file.  I thought that Babel would have refactored this out as  api.use('ecmascript'); is being used in the Package.onUse for the ohif-cornerstone package. Is anyone else having is problem after dcmjs was added?

**Comment by pieper** [comment]
I can confirm that it's not working on IE11 for me.  I don't know why it's not working.

**Comment by esuapple03** [comment]
Nice to know I'm not alone.

**Comment by galelis** [comment]
I am on it. I will investigate and keep you guys posted .

**Comment by galelis** [comment]
I have change the Rollup configuration to use babel and transpile the ES6 as suggested by Erik/Zaid and add manually the bundled file into OHIF.

I will test more tomorrow on Windows IE11 and also on my mac. if its fine I will create a PullRequest on DCMJS and later on OHIF to update versions. 

I also have tested using Webpack as we use on all cornerstone Libs as suggested by Erik. 
@swederik  is it fine to use Rollup? or do you prefer webpack?

**Comment by swederik** [comment]
Rollup is also fine. I really don't care as long as whatever you do takes very little effort. It doesn't make sense to waste time looking into how to use rollup if you can copy/paste the webpack / karma / etc stuff from Cornerstone* which we know already works. Frankly, I don't want to spend *any* more time looking into concat / minify / transpile / test / coverage configuration stuff unless there is some obvious gain over what we have already in place.

**Comment by galelis** [comment]
I have worked with dcmJS and now its generating a transpiled version using babel and webpack. 

I have also created a PR with OHIF to update dcmjs with its latest version (0.1.5) 
https://github.com/OHIF/Viewers/pull/260

Here is a heroku with latest OHIFViewer code (with dcmjs 0.1.5)
http://ohifviewer-staging.herokuapp.com/studylist
