### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by matthiasg** [OHIF/Viewers#2460]
Is there any discussion about creating and maintaining a user manual for the application ?

We are interested in creating a MDR (Medical Device Regulation) compatible solution for integration into our existing platform. There are a number of regulatory requirements of course especially around user validation and verification, but in this question I would like to know whether there have been any discussion already on creating a user manual. 

A user documentation would necessarily need to be quite dynamic, modularized, and open in order for distributors to finalize and take regulatory responsibility for.

**Comment by sedghi** [comment]
Regrettably, we are unable to keep up with the rapid pace at which the app is evolving.
