### ISSUE TITLE
Tag browser crashes when opening the same study consecutively multiple times

### ISSUE THREAD

**Issue by Christian-e-S** [OHIF/Viewers#2473]
### Describe the Bug
When I select a study from the study list and then open the tag browser, the data is shown correctly. When I then go back to the study list, and then open the same study again, and open the tag browser again, the application crashes:

```js
Cannot read property 'metadata' of undefined

    in DicomTagBrowser (created by WrappedDicomTagBrowser)
    in WrappedDicomTagBrowser (created by ModalProvider)
    in div (created by OHIFModal)
    in div (created by ModalPortal)
    in div (created by ModalPortal)
    in ModalPortal (created by Modal)
    in Modal (created by OHIFModal)
    in OHIFModal (created by ModalProvider)
    in ModalProvider (created by App)
    in DialogProvider (created by App)
    in SnackbarProvider (created by App)
    in LoggerProvider (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in I18nextProvider (created by App)
    in AppProvider (created by App)
    in Provider (created by App)
    in ErrorBoundary (created by OHIFErrorBoundary)
    in OHIFErrorBoundary (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
```

### What steps can we follow to reproduce the bug?

1. use the latest commit of the master branch
2. enable the tag browser by uncommenting the following lines in index.js

```js
//import OHIFDicomTagBrowserExtension from '@ohif/extension-dicom-tag-browser';
//OHIFDicomTagBrowserExtension,
```
3. run the viewer with "yarn run dev"
4. select any study
5. click "Study List" to return to the study list
6. select the same study from step 4 again
7. open the tag browser
8. --> you will see the error message

### What I have found out
* The tag browser extension tries to access the displaySets from the studyMetadataManager, but they are undefined
* In ViewerRetrieveStudyData.js there is a function called _updateStudyDisplaySets which includes the following code:

```js
if (!study.displaySets) {
    study.displaySets = studyMetadata.createDisplaySets(sopClassHandlerModules);
  }
```

* When the study is opened for the first time, the study does not include displaySets, and therefore studyMetadata.createDisplaySets is called, and the displaySets are correctly populated in the study, as well as in the studyMetadata.

* When the study is opened for the second time, the study is not fetched from the server again, but accessed from a cashed promise (now already including the displaySets). 

* Since the displaySets are now present, the condition in the if statement above evaluates to false, and the studyMetadata is never populated with the displaySets.

--> I have proposed a small change in the constructor of StudyMetadata, which initializes the displaySets of the StudyMetadata with the displaySets of the study (in case they exist in the study)
--> I will link a corresponding pull request to this issue.

**Comment by sedghi** [comment]
I cannot reproduce this in master any more, can you please confirm?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
