### ISSUE TITLE
MeasurementApi imagePath should recognize undefined frameIndex

### ISSUE THREAD

**Issue by PoyangLiu** [OHIF/Viewers#2479]
## Bug Report

When a tool is created, an `imagePath` is constructed from `imageId` and added to the measurement data.

_**If the `imageId` does not contain frame information**,_ [getImageAttributes.js](https://github.com/OHIF/Viewers/blob/master/platform/core/src/measurements/lib/getImageAttributes.js#L17) automatically assumes frameIndex is 0.
```
  const splitImageId = imageId.split('&frame');
  const frameIndex =
    splitImageId[1] !== undefined ? Number(splitImageId[1]) : 0;

  const imagePath = [
    StudyInstanceUID,
    SeriesInstanceUID,
    SOPInstanceUID,
    frameIndex,
  ].join('_');
```

When user tries to clear the measurement tools using `clearAnnotations`, the MeasurementApi reconstruct the `imageId` using [getImageIdForImagePath](https://github.com/OHIF/Viewers/blob/master/platform/core/src/measurements/lib/getImageIdForImagePath.js)
```
  const [
    StudyInstanceUID,
    SeriesInstanceUID,
    SOPInstanceUID,
    frameIndex,
  ] = imagePath.split('_');
  ...
  return instance.getImageId(frameIndex, thumbnail);
```

The `instance.getImageId(...)` (implemented in [getIMageId.js](https://github.com/OHIF/Viewers/blob/master/platform/core/src/utils/getImageId.js#L47)) does allow for `undefined` `frameIndex`.
```
    if (frame !== undefined) {
      imageId += '&frame=' + frame;
    }
```

The reconstructed `imageId` (with the frameIndex) is then used to lookup a `toolState` in  `cornerstoneTools.globalImageIdSpecificToolStateManager`. This [comparison](https://github.com/OHIF/Viewers/blob/master/platform/core/src/measurements/classes/MeasurementApi.js#L984) failed because the original `imageId` has no `frameIndex` and the tool remains in the viewport.

```
     entries.forEach(entry => {
      const measurementsData = [];
      ... do stuff to populate the measurementData array

      measurementsData.forEach(measurementData => {
        const { imagePath, toolType } = measurementData;
        const imageId = getImageIdForImagePath(imagePath);
        if (imageId && toolState[imageId]) {
          ...remove the measurementData

        }
      });

      this.onMeasurementRemoved(toolType, entry);
    });
```

## Propose Fix

In [getImageAttributes.js](https://github.com/OHIF/Viewers/blob/master/platform/core/src/measurements/lib/getImageAttributes.js#L20), `imagePath` construction should allow for undefined `frameIndex`.

```
  const splitImageId = imageId.split('&frame=');
  const frameIndex =
    splitImageId[1] !== undefined ? Number(splitImageId[1]) : undefined;

  const imagePath =
    frameIndex === undefined
      ? [StudyInstanceUID, SeriesInstanceUID, SOPInstanceUID].join('_')
      : [StudyInstanceUID, SeriesInstanceUID, SOPInstanceUID, frameIndex].join(
          '_'
        );
```

[parseDicomStructuredReport.js](https://github.com/OHIF/Viewers/blob/master/platform/core/src/DICOMSR/parseDicomStructuredReport.js#L86) has a similar `getImagePath` function.  It should probably be updated to allow `undefined` `frameIndex` too.

**Comment by PoyangLiu** [comment]
@swederik , @dannyrb 
bump

**Comment by ArturRod** [comment]
The last thing you mention works, it has fixed bug # 2410 to erase the data, they should include this line of code in the official version. Thank you very much partner! @PoyangLiu 😉😊

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
