### ISSUE TITLE
UINotificationService doesn't not return ID for the show() method

### ISSUE THREAD

**Issue by SachidanandAlle** [OHIF/Viewers#2480]
> **Before Creating an issue**
>
> - Are you running the latest version? YES
> - Are you reporting to the correct repository? YES
> - Did you search existing issues? YES

### Describe the Bug
```
let service = UINotificationService.create({});
let id = service.show(...);
console.log(id) => it's undefined
```

**Comment by WoonchanCho** [comment]
@SachidanandAlle I don't know what you're exactly trying to do with the notification.
But, you can see the https://github.com/OHIF/Viewers/blob/master/platform/core/src/services/UINotificationService/index.js to check what the show method does.
It doesn't return any id. What the method function does is to add a queue when it's called. The enqueued requests are consumed asynchronously.

Additionally, I believe you don't need to call the UINotificationService.create({}) in most cases.
You can simply use the useSnackbarContext in a hook function or withSnackbar in class component.

**Comment by SachidanandAlle** [comment]
https://github.com/OHIF/Viewers/blob/master/platform/core/src/services/UINotificationService/index.js#L35-L36

> Create and show a new UI notification; returns the
> ID of the created notification.
