### ISSUE TITLE
Make client-side code debuggable right from the source code

### ISSUE THREAD

**Issue by WoonchanCho** [OHIF/Viewers#2483]
Hi Team,

I found that I couldn't set a breakpoint from the source code in the dev environment when it's run with "yarn run dev".

After some research, I found that it can be possible by changing the webpack config located in platform/viewer/.webpack/webpack.pwa.js.

as is =>
`        output: {
      path: DIST_DIR,
      filename: isProdBuild ? '[name].bundle.[chunkhash].js' : '[name].js',
      publicPath: PUBLIC_URL, // Used by HtmlWebPackPlugin for asset prefix
    },`

to be =>
`    output: {
      path: DIST_DIR,
      filename: isProdBuild ? '[name].bundle.[chunkhash].js' : '[name].js',
      publicPath: PUBLIC_URL, // Used by HtmlWebPackPlugin for asset prefix
      devtoolModuleFilenameTemplate: function(info) {
        return 'file:///' + encodeURI(info.absoluteResourcePath);
      },
    },`

After this change, I was able to set a breakpoint and debug easily from the editor like vscode.
![image](https://user-images.githubusercontent.com/19254333/126851024-1beb4345-1df2-47aa-b089-cf51365e65c2.png)

Please advise me if it's beneficial. If so, I will raise the pull request.

Thank you.

**Comment by swederik** [comment]
Yes definitely make a PR! That's great!
