### ISSUE TITLE
How add your tools correctly? 

### ISSUE THREAD

**Issue by Suriafla** [OHIF/Viewers#2497]
It is required to add tool to draw a points on medical images with ability to subsequently save the coordinates of the point for machine learning.

**Comment by PoyangLiu** [comment]
Not sure what you meant.  But it sounds like you are looking for the [FreehandRoiTool](https://tools.cornerstonejs.org/examples/tools/freehand-mouse.html).
You will have to
1. include this tool at initialization.
  * https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone/src/init.js#L59
1. add toolbar button to launch this tool
  * https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone/src/toolbarModule.js

As to how to save these measurement... I think you need to look at 
1. [MeasurementApi.js](https://github.com/OHIF/Viewers/blob/master/platform/core/src/measurements/classes/MeasurementApi.js)
2. which loads its [configurations](https://github.com/OHIF/Viewers/blob/master/platform/core/src/measurements/configuration.js)
3. and perhaps overwrite the [dataExchange.js](https://github.com/OHIF/Viewers/blob/master/platform/core/src/measurements/dataExchange.js)
