### ISSUE TITLE
Segmentation (mistakenly?) reported as orthogonal to image

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2500]
With a sample dataset available by request, I am seeing an error loading segmentation with the error "Segmentations orthogonal to the acquisition plane of the source data are not yet supported", while the orientation seems to be within the tolerance.

![image](https://user-images.githubusercontent.com/313942/128090887-745be6e5-4fad-494f-b015-27b104f3f038.png)

**Comment by Punzo** [comment]
dcmjs-org/dcmjs#220 should fix the regression.
