### ISSUE TITLE
Viewers--ohif-viewer-3.11.11 load pdfjs has error

### ISSUE THREAD

**Issue by JiangWeian** [OHIF/Viewers#2501]
I downloaded the Viewers--ohif-viewer-3.11.11 version. After the command yarn install is executed successfully, an error is reported:
![TIM图片20210804083308](https://user-images.githubusercontent.com/56569509/128104000-eee3c251-dac5-42d9-a875-c4944da443f7.png)

**Comment by sedghi** [comment]
We have moved away from pdfjs and just get the rendered end point from the dicom server
