### ISSUE TITLE
Error viewer loading very small images 

### ISSUE THREAD

**Issue by goddymugo** [OHIF/Viewers#2506]
> **Before Creating an issue**
>
> - Are you running the latest version?Yes, V4.8.6
> - Are you reporting to the correct repository? Yes, OHIF iewer
> - Did you search existing issues? Yes

## Bug Report
Viewer loading very small images with magnification of over 400%.
And not displaying patient information.

### Describe the Bug

Have connected OHIF Viewer with Conquest via DICOMWEB-proxy.
was initially getting error on loading images but after searching on the forum and web was able to get images loading but they are too bloody. on checking realized the magnification is about 402%, not showing patient information and img undefined.  

### What steps can we follow to reproduce the bug?

1. Search for same issue on forum and net.
2. Checked with DICOMWEB-PROXY team
3.Getting attached error
![Capture](https://user-images.githubusercontent.com/29998260/128491690-5fc3b5d4-d341-4f5d-bbc1-99627775ddfc.JPG)
![Capture1](https://user-images.githubusercontent.com/29998260/128491701-d34de3a2-6af2-487c-8983-27354574b565.JPG)

3. ...

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by jwitos** [comment]
The error message seems similar to https://github.com/OHIF/Viewers/issues/1882.
> they are too bloody. on checking realized the magnification is about 402%, not showing patient information and img undefined.
I'm not sure what do you mean by "too bloody". Are you talking about the default windowing?
Also, magnification here is most likely not a bug, OHIF is simply trying to stretch your image to fill the space in the viewer.

Metadata errors can be a bug, but to reproduce that you'd have to share sample DICOM files that OHIF is digesting, i.e. sent from dicomweb-proxy.

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
