### ISSUE TITLE
how to add new modules

### ISSUE THREAD

**Issue by leonopteryx130** [OHIF/Viewers#2509]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

I want to use yarn to add some new modules，but report a bug，how to add new modules?
![image](https://user-images.githubusercontent.com/69339697/128792035-542d14a8-b06f-4a2c-8142-77ffef0a7bb1.png)

**Comment by PoyangLiu** [comment]
From your command, it seems that you are trying to add `antd`, which is a UI library.

If I hazard to take a guess, you actually want to add `antd` to either [@ohif/viewer](https://github.com/OHIF/Viewers/tree/master/platform/viewer) or [@ohif/ui](https://github.com/OHIF/Viewers/tree/master/platform/ui).  You need to first find out which workspace you meant to add this dependency.  My suggestion is to change directory to the package and try your command there.

For example
```bash
cd platform/viewer
yarn add antd
```

`OHIF/Viewers` uses [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/).  The dependencies you add should be added to the individual workspace.  `yarn` will then add it to the root `node_modules`.  You should not be adding dependencies to the root.

If you `really` want to add dependency to the root, then yes, you'll have to provide the `-w` flag.
```
yarn add -w antd  (warning... this is probably not what you meant)
```

**Comment by sedghi** [comment]
To easily resolve this issue, add the package to the package.json of your extension.
