### ISSUE TITLE
Delete Measurements

### ISSUE THREAD

**Issue by ArturRod** [OHIF/Viewers#2510]
Version usage: Latest @ ohif / extension-cornerstone @ 2.10.10

When you create a measurement (circle, annotation, angle) in a view with several images (that has scroll), when deleting from measurements (the side panel) or from the trash icon, it deletes the measurements but they continue to appear. Only delete well if you right click, delete measurement.
This only happens when there are several images, if it is only one image, it erases it well.

Play bug:
1. Select a series with several images.
2. Put a measurement.
3. Give delete from the trash button or from the side panel.
4. See how the measurement is cleared but not cleared from view.
![image](https://user-images.githubusercontent.com/86238895/128863166-71e114ef-3d47-4789-a2b5-0950ba78f940.png)
![image](https://user-images.githubusercontent.com/86238895/128863235-fd91dff4-6c2d-4ddd-8192-f85e0ae79693.png)

**Comment by PoyangLiu** [comment]
AFAIK, this might be caused by [OHIF-2479](https://github.com/OHIF/Viewers/issues/2479).

**Comment by ArturRod** [comment]
@PoyangLiu the solution is definitely -> #2479 Thanks!
