### ISSUE TITLE
Abnormal display for some images on OHIF-V3

### ISSUE THREAD

**Issue by Xaiver97** [OHIF/Viewers#2518]
> **Before Creating an issue**
>
> - Are you running the latest version? Sure, the latest version in feat/v2-main
> - Are you reporting to the correct repository? feat/v2-main
> - Did you search existing issues? Yes

## Bug Report

The same image which display normally on ohif-v2(which in the master branch) but abnormally on ohif-v3(which in the feat/v2-main branch) . I have tried serveral ways like adjust the window level, use different pacs system and change the version of cornerstone components, but none of them worked. I'd appreciate any help for fixing the bug.
- The display effect on ohif-v3
![}{)ROC)UJR@2P{3(TJEWUY1](https://user-images.githubusercontent.com/46915084/130209443-32e148e2-e762-402b-a7b7-defe2288c17d.png)
- The display effect on ohif-v2
![KEO40JFOIZ(QA}N1XL31@O8](https://user-images.githubusercontent.com/46915084/130209461-7301e5e5-0b2b-4703-b895-7d62d3a17889.png)
- I have uploaded the abnormal dcm file to the following link
https://drive.google.com/file/d/1-Li3rB_LQqmkPema7NCr_3fF-txJfT7b/view?usp=sharing

Thanks a lot !

### What steps can we follow to reproduce the bug?

1. Start the ohif-v3 viewer
2. Loading the specific image
3. The bug will happen

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by ithet1007** [comment]
I got the same problem. The wrong display happened if the Dicom has large HU values.

**Comment by Xaiver97** [comment]
@swederik  Hope you can take a look! Thanks a lot.

**Comment by sedghi** [comment]
Thanks for reporting this. It will get merged soon here https://github.com/OHIF/Viewers/pull/2530

**Comment by ithet1007** [comment]
@sedghi, thank you. The problem has been corrected. However, I get another problem. The OHIF v2-main displays false for multi-channel images, such as Ultrasound or Micrograph.
![1630394513(1)](https://user-images.githubusercontent.com/12868302/131461154-1572d0bd-872a-4d1f-a83a-317c5b266be5.png)

![1630394549(1)](https://user-images.githubusercontent.com/12868302/131461310-6d793b44-8c86-4739-a56f-78a289e83be3.png)

**Comment by sedghi** [comment]
![CleanShot 2023-10-13 at 13 00 11](https://github.com/OHIF/Viewers/assets/7490180/91bd8e91-f2a9-4246-9f85-79ba23a60a09)

Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
