### ISSUE TITLE
Ohif viewer embedded into external React Application

### ISSUE THREAD

**Issue by amita125** [OHIF/Viewers#2519]
Goal :

Our goal is to embed the Ohif viewer into the application. The application is a simple steps where you can select the studyId which you want to view and as soon as the view button is selected you should be redirected to the Ohif viewer directly **Not the studylist of ohif viewer but study viewer directly**. 

As of now, i can only see the study route working the first time only but later if I select any study the old study is being viewed [ old study as in the first study that is viewed] .

![Capture](https://user-images.githubusercontent.com/49608334/130413468-28184f2e-6d06-455b-ba17-c64bdd86b14d.JPG)

as soon as the view is selected the particular study opens and the url is : http://localhost:8000/viewer/studyid1 . 
![Capture1](https://user-images.githubusercontent.com/49608334/130413516-0a83dc7c-70be-46ac-bed8-8db7b8ae232a.JPG)

Thats Ok but if i select the other studyid and click view i am redirect to the old studyId that is : http://localhost:8000/viewer/studyid1 . instead of : http://localhost:8000/viewer/studyid2 .

and the viewer.js react component looks like this-
 
![Capture12](https://user-images.githubusercontent.com/49608334/130414292-6412a3f2-e078-4327-b745-421a4f26de9d.JPG)

I tried looking into issues no #1755 and #1400 and tried with no luck.

**Comment by AWESOMEDustin** [comment]
Did you by any chance find a solution to that problem? 
I am facing a similar issue.

**Comment by nicoesiea** [comment]
@AWESOMEDustin  I'm wondering the same question, I have an angular app where I embed the react component... And I do not have the possibility to load the viewer in an iframe... I can neither use the URL to specify the study uid...

**Comment by sedghi** [comment]
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
