### ISSUE TITLE
The browser goes black with black text in the upper left corner Error: true

### ISSUE THREAD

**Issue by xujiakai1990** [OHIF/Viewers#2524]
It can be started for the first time. My environment is Centos7.6 python3.9.6 Node12.22.5 YARn1.22.5  
Here's what happens after I boot up with a warning
[root@localhost dr-ohif]# yarn run dev:orthanc
yarn run v1.22.5
$ lerna run dev:orthanc --stream
lerna notice cli v3.18.3
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run dev:orthanc"
@ohif/viewer: $ cross-env NODE_ENV=development PROXY_TARGET=/dicom-web PROXY_DOMAIN=http://localhost:8042 APP_CONFIG=config/docker_nginx-orthanc.js webpack-dev-server --config .webpack/webpack.pwa.js --watch
@ohif/viewer: ℹ ｢wds｣: Project is running at http://localhost:3000/
@ohif/viewer: ℹ ｢wds｣: webpack output is served from /
@ohif/viewer: ℹ ｢wds｣: Content not from webpack is served from /usr/local/dr-ohif/platform/viewer
@ohif/viewer: ℹ ｢wds｣: 404s will fallback to /index.html
@ohif/viewer: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
@ohif/viewer: ℹ ｢wdm｣: wait until bundle finished: /
@ohif/viewer: ⚠ ｢wdm｣: Hash: 068b6c582c2802b68bce
@ohif/viewer: Version: webpack 4.41.2
@ohif/viewer: Time: 25236ms
@ohif/viewer: Built at: 08/27/2021 4:57:59 PM
@ohif/viewer:                                                                                                   Asset       Size                                                                                               Chunks             Chunk Names
@ohif/viewer:                                                                                                    0.js    146 KiB                                                                                                    0  [emitted]  
@ohif/viewer:                                                                                                    1.js    228 KiB                                                                                                    1  [emitted]  
@ohif/viewer:                                                                                                   2.css   1.15 KiB                                                                                                    2  [emitted]  
@ohif/viewer:                                                                                                    2.js   71.6 KiB                                                                                                    2  [emitted]  
@ohif/viewer:                                                                                                   3.css  188 bytes                                                                                                    3  [emitted]  
@ohif/viewer:                                                                                                    3.js   56.7 KiB                                                                                                    3  [emitted]  
@ohif/viewer:                                                                                                    4.js   6.02 MiB                                                                                                    4  [emitted]  
@ohif/viewer:                                                                                                    5.js   39.9 KiB                                                                                                    5  [emitted]  
@ohif/viewer:                                                                                                    6.js   18.4 KiB                                                                                                    6  [emitted]  
@ohif/viewer:                                                                                                    7.js    994 KiB                                                                                                    7  [emitted]  
@ohif/viewer:                                                                                         CallbackPage.js   8.85 KiB                                                                                         CallbackPage  [emitted]  CallbackPage
@ohif/viewer:                                                                           ConnectedStandaloneRouting.js   31.5 KiB                                                                           ConnectedStandaloneRouting  [emitted]  ConnectedStandaloneRouting
@ohif/viewer: ConnectedStandaloneRouting~IHEInvokeImageDisplay~StudyListRouting~ViewerLocalFileData~ViewerRouting.css   4.93 KiB  ConnectedStandaloneRouting~IHEInvokeImageDisplay~StudyListRouting~ViewerLocalFileData~ViewerRouting  [emitted]  ConnectedStandaloneRouting~IHEInvokeImageDisplay~StudyListRouting~ViewerLocalFileData~ViewerRouting
@ohif/viewer:  ConnectedStandaloneRouting~IHEInvokeImageDisplay~StudyListRouting~ViewerLocalFileData~ViewerRouting.js    102 KiB  ConnectedStandaloneRouting~IHEInvokeImageDisplay~StudyListRouting~ViewerLocalFileData~ViewerRouting  [emitted]  ConnectedStandaloneRouting~IHEInvokeImageDisplay~StudyListRouting~ViewerLocalFileData~ViewerRouting
@ohif/viewer:                  ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerLocalFileData~ViewerRouting.css   2.63 KiB                   ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerLocalFileData~ViewerRouting  [emitted]  ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerLocalFileData~ViewerRouting
@ohif/viewer:                   ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerLocalFileData~ViewerRouting.js    232 KiB                   ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerLocalFileData~ViewerRouting  [emitted]  ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerLocalFileData~ViewerRouting
@ohif/viewer:                                       ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerRouting.js   58.2 KiB                                       ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerRouting  [emitted]  ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerRouting
@ohif/viewer:                                                                                IHEInvokeImageDisplay.js      7 KiB                                                                                IHEInvokeImageDisplay  [emitted]  IHEInvokeImageDisplay
@ohif/viewer:                                                                                    StudyListRouting.css   3.27 KiB                                                                                     StudyListRouting  [emitted]  StudyListRouting
@ohif/viewer:                                                                                     StudyListRouting.js    267 KiB                                                                                     StudyListRouting  [emitted]  StudyListRouting
@ohif/viewer:                                                                 StudyListRouting~ViewerLocalFileData.js     48 KiB                                                                 StudyListRouting~ViewerLocalFileData  [emitted]  StudyListRouting~ViewerLocalFileData
@ohif/viewer:                                                                       StudyListRouting~ViewerRouting.js   38.1 KiB                                                                       StudyListRouting~ViewerRouting  [emitted]  StudyListRouting~ViewerRouting
@ohif/viewer:                                                                                 ViewerLocalFileData.css  326 bytes                                                                                  ViewerLocalFileData  [emitted]  ViewerLocalFileData
@ohif/viewer:                                                                                  ViewerLocalFileData.js   23.4 KiB                                                                                  ViewerLocalFileData  [emitted]  ViewerLocalFileData
@ohif/viewer:                                                                                        ViewerRouting.js   13.1 KiB                                                                                        ViewerRouting  [emitted]  ViewerRouting
@ohif/viewer:                                                                                           app-config.js  357 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                                                 app.css    139 KiB                                                                                                  app  [emitted]  app
@ohif/viewer:                                                                                                  app.js   46.7 MiB                                                                                                  app  [emitted]  app
@ohif/viewer:                                                                                  assets/Button_File.svg   3.93 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                assets/Button_Folder.svg   4.03 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                       assets/android-chrome-144x144.png   1.45 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                       assets/android-chrome-192x192.png   1.91 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                       assets/android-chrome-256x256.png    2.4 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                         assets/android-chrome-36x36.png  423 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                       assets/android-chrome-384x384.png   4.69 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                         assets/android-chrome-48x48.png  585 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                       assets/android-chrome-512x512.png   4.93 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                         assets/android-chrome-72x72.png  773 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                         assets/android-chrome-96x96.png  949 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                   assets/apple-touch-icon-1024x1024.png   21.9 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                     assets/apple-touch-icon-114x114.png   1.06 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                     assets/apple-touch-icon-120x120.png   1.14 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                     assets/apple-touch-icon-144x144.png   1.45 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                     assets/apple-touch-icon-152x152.png   1.51 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                     assets/apple-touch-icon-167x167.png   1.59 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                     assets/apple-touch-icon-180x180.png    1.9 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                       assets/apple-touch-icon-57x57.png  607 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                       assets/apple-touch-icon-60x60.png  510 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                       assets/apple-touch-icon-72x72.png  773 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                       assets/apple-touch-icon-76x76.png  802 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                 assets/apple-touch-icon-precomposed.png    1.9 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                             assets/apple-touch-icon.png    1.9 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                          assets/apple-touch-startup-image-1182x2208.png     34 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                          assets/apple-touch-startup-image-1242x2148.png   35.4 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                          assets/apple-touch-startup-image-1496x2048.png   44.1 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                          assets/apple-touch-startup-image-1536x2008.png   41.1 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                            assets/apple-touch-startup-image-320x460.png   4.71 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                           assets/apple-touch-startup-image-640x1096.png   12.1 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                            assets/apple-touch-startup-image-640x920.png   11.4 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                           assets/apple-touch-startup-image-748x1024.png   13.8 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                           assets/apple-touch-startup-image-750x1294.png   16.1 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                           assets/apple-touch-startup-image-768x1004.png   13.8 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                assets/browserconfig.xml  442 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                                assets/coast-228x228.png   2.51 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                assets/favicon-16x16.png  214 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                                assets/favicon-32x32.png  325 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                                      assets/favicon.ico   32.5 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                          assets/firefox_app_128x128.png    1.5 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                          assets/firefox_app_512x512.png   7.43 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                            assets/firefox_app_60x60.png  685 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                                  assets/manifest.webapp  334 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                               assets/mstile-144x144.png   1.45 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                               assets/mstile-150x150.png   2.99 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                               assets/mstile-310x150.png   3.47 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                               assets/mstile-310x310.png   8.24 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                 assets/mstile-70x70.png   1.14 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                         assets/yandex-browser-50x50.png  546 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                     assets/yandex-browser-manifest.json  155 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                                         es6-shim.min.js   56.3 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                               google.js   1.02 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                              index.html   5.47 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                  init-service-worker.js   1.91 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                           manifest.json   1.27 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                      oidc-client.min.js    240 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                         polyfill.min.js   3.06 KiB                                                                                                       [emitted]  
@ohif/viewer:                                                                                     silent-refresh.html  579 bytes                                                                                                       [emitted]  
@ohif/viewer:                                                                                                   sw.js   16.7 KiB                                                                                                       [emitted]  
@ohif/viewer:           vendors~ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerLocalFileData~ViewerRouting.js    286 KiB           vendors~ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerLocalFileData~ViewerRouting  [emitted]  vendors~ConnectedStandaloneRouting~IHEInvokeImageDisplay~ViewerLocalFileData~ViewerRouting
@ohif/viewer:                                                                          vendors~ViewerLocalFileData.js    164 KiB                                                                          vendors~ViewerLocalFileData  [emitted]  vendors~ViewerLocalFileData
@ohif/viewer:                                                                      vendors~dicom-microscopy-viewer.js   5.18 MiB                                                                      vendors~dicom-microscopy-viewer  [emitted]  vendors~dicom-microscopy-viewer
@ohif/viewer: Entrypoint app = app.css app.js
@ohif/viewer: WARNING in /4.js is 6.32 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
@ohif/viewer: WARNING in /app.js is 49 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
@ohif/viewer: WARNING in /vendors~dicom-microscopy-viewer.js is 5.43 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
@ohif/viewer: ℹ ｢wdm｣: Compiled with warnings.

I view and play a file and I get an error message and then I start it again and it won't start and then the page that pops up will flash normal
![image](https://user-images.githubusercontent.com/60814262/131104603-1d67a3fc-8b9f-4f0b-8a9f-81158940097e.png)

Please friends can help me thank you

**Comment by I-am-vishalmaurya** [comment]
Did you solve this error?

**Comment by KernelPryanic** [comment]
In my case the authentication method was configured incorrectly, when I configured the OIDC like [here](https://github.com/OHIF/Viewers/blob/%40ohif/viewer%404.12.51/platform/viewer/public/config/google.js) and added the following parameters to the DICOM server configuration the issue was fixed.
```
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
        qidoSupportsIncludeField: false,
```

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
