### ISSUE TITLE
uncaught exception for non TID-1500 SR

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2526]
## Bug Report

A study with a SR that is not TID-1500 generates an error described here:

https://github.com/ImagingDataCommons/IDC-WebApp/issues/683

### Describe the Bug

See linked issue

### What steps can we follow to reproduce the bug?

See linked issue

**Comment by fedorov** [comment]
possibly related to https://github.com/OHIF/Viewers/issues/2348
