### ISSUE TITLE
Callback going to wrong index.html when serving in Subdirectory + Google Cloud auth

### ISSUE THREAD

**Issue by boneitis** [OHIF/Viewers#2540]
Hello,

I am trying to serve the OHIF Viewer from a subdirectory while also running in the Google Cloud OAuth configuration.

After hitting and addressing a bunch of snags, it feels like the final one obstructing me is in gracefully handling the callback. In my build tests, I am using the "nest" subdirectory. After the client authenticates and comes back to hit `/nest/callback`, it is returning the `index.html` _at the web root instead_ of returning to the OHIF application.

![s01](https://user-images.githubusercontent.com/1254941/132503236-c815f777-bfb2-44d8-b2ed-a5be77d4bb68.png)

[Edit: `/nest/callback` shows 200 in the screenshot but is just serving the root index.html after the client comes back from Google]

I am building with the Dockerfile, with the following deviating steps:
- changing the `routerBasename` from `'/'` to `'/nest'`
- dropping in my actual `CLIENT_ID`
- adding environment variables before the `RUN yarn run build` as follows:
    `ENV PUBLIC_URL="/nest/"`
    `ENV APP_CONFIG="config/google.js"`
- creating the subdirectory just before dropping the static files into nginx container as follows:
    `RUN mkdir /usr/share/nginx/html/nest`
- appending `/nest` to the nginx build's destination path during the Dockerfile `COPY` command

Of course, if I move the OHIF's index.html to the root and visit the domain root, the application knows where to correctly locate the assets and apparently works entirely.

[Edit2: I just realized a working root-level html with a name different from "index.html" will probably be an acceptable compromise if the fix is otherwise much easier. In any case, the application still tries to redirect to the root index.html. Best case, knowing how to do both would be tops, but a solution is a solution.]

#### This concludes the main question. The following are a couple (out of very many) additional steps taken while trying to investigate the issue.

Yanking the OHIF application files out of the container and serving them with a python3 http.server _exhibits the same symptom of trying to serve an index.html at the web root_ (at the time of the following screenshot, there is no index.html at the root); it incidentally looks for some js file belonging to the `third_party` directory in the wrong location.

![s02](https://user-images.githubusercontent.com/1254941/132503267-3562c80a-1294-41d3-a2ff-1bcaec9ae094.png)

When cloning the `third_party` directory to the root, the application preloads what seems to be the entirety of the application assets at the same time as the Google OAuth redirect. It pulls some of the workbox files from the root-cloned `third_party` directory but gets most of them from the correct nested location.

![s03](https://user-images.githubusercontent.com/1254941/132503291-55763249-ce9e-4b43-a753-9f415722c93c.png)

My html knowledge is extremely limited and my js knowledge non-existent.

Any leads on getting this working would be super duper appreciated.

(keyword salad: gcp subfolder sub redirect )

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
