### ISSUE TITLE
How to connect OHIF Viewer with Orthanc server running on localhost:8042 while my OHIF Viewer is running on localhost:3000

### ISSUE THREAD

**Issue by farooqbutt** [OHIF/Viewers#2546]

**Comment by jensen0914** [comment]
You need to update the app-config.js file that comes with the OHIF viewer to point to your Orthanac server's DICOMweb interface. See https://docs.ohif.org/configuring/

**Comment by farooqbutt** [comment]
I have done this but due to the CORS issue, I am not able to get the studies and series. so now how can I get the studies and series in OHIF Viwer? This is the issue.

**Comment by farooqbutt** [comment]
my Orthanc server is running at localhost:8042 and I have configured the OHIF viewer default.js file to get data from Orthanc server but I m facing a CORS issue.

**Comment by biskyt** [comment]
@farooqbutt - you need to use nginx to solve the CORS issue. There is a bunch of help on this in the OHIF and Orthanc documentation.

Here is an example docker-compose file that I'm using. That repo also contains the necessary nginx.conf file, and the ohif config js file. https://github.com/biskyt/OHIF_test/blob/master/docker-compose.yml

Basically, you tell OHIF to connect to the nginx endpoint, and nginx proxies the request through to orthanc. Hopefully that will help

**Comment by maya-harel** [comment]
Hey, I am also facing this issue. Using a docker-compose very similar to @biskyt 
I can see my files in the Orthanc web server, but they do not appear in the Ohif viewer
How can I make sure my viewer is configured correctly?

**Comment by juandp77** [comment]
@biskyt I´m getting stuck on the .env part of you docker-compose file. Any help?

**Comment by sedghi** [comment]
We have couple of deployment recipes, you can look at them https://docs.ohif.org/deployment/
