### ISSUE TITLE
Why Redux => internal pub/sub (v2 => v3)?

### ISSUE THREAD

**Issue by shivasuri** [OHIF/Viewers#2549]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

What drove the decision to switch from Redux to a pub/sub system for state management from v2 to v3?

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by swederik** [comment]
Hi @shivasuri,

Good question! So the main motivator is that we want to be able to have extensions (https://v3-docs.ohif.org/platform/extensions/index) which can add their own stateful services as necessary. We previously had the `@ohif/core` which was full of actions / reducers / etc (https://github.com/OHIF/Viewers/tree/master/platform/core/src/redux) and was more complicated to plug into from third party extensions. It just felt a bit weird the way that the extensions would connect and add their own mapStateToProps, etc (e.g. https://github.com/OHIF/Viewers/blob/master/extensions/vtk/src/ConnectedVTKViewport.js#L7). This model has extensions providing services which can provide their own API inside the viewer and are accessible anywhere via the service manager. We would like to move towards TypeScript so the services and their APIs are typed and we release / version them properly for extension authors that depend on them.

**Services Docs:** https://v3-docs.ohif.org/platform/services/index
**Code:** https://github.com/OHIF/Viewers/tree/v3-stable/platform/core/src/services
