### ISSUE TITLE
Error Firefox Ver. 92.0 Crash 

### ISSUE THREAD

**Issue by ArturRod** [OHIF/Viewers#2551]
Hi, I am having an error with Firefox Ver. 92.0.
The errors are:
-> Successfully compiled asm.js code (total compilation time 122ms).
-> mozImageSmoothingEnabled is deprecated.
This only happens with firefox Ver. 92.0, and it makes the program crash depending on studies, specifically the sidebar.
![image](https://user-images.githubusercontent.com/86238895/133972902-b6df701c-4033-4d75-a4d5-e5298d96a810.png)

To replicate this error, all you have to do is install Ver. 92.0 firefox.

**Comment by swederik** [comment]
Sounds like it's running out of memory when spinning up the web workers for
decoding. Only options I see is to limit the number of workers that get
created on that system.

**Comment by ArturRod** [comment]
@swederik when it fails I get this error:
![image](https://user-images.githubusercontent.com/86238895/133986246-0d9053d2-9eed-4854-a5b9-df675c8c222a.png)

**Comment by ArturRod** [comment]
@swederik  It is indeed a memory failure.
![image](https://user-images.githubusercontent.com/86238895/133988168-945b0aea-8363-4e65-b998-455224678333.png)
