### ISSUE TITLE
How to load SR Dicom file using json in OHIF viewer.

### ISSUE THREAD

**Issue by pmd23** [OHIF/Viewers#2558]
> :hand: 

we have few dicom images which are **SR images**  I want to be load it using json. So my question is that what kind of json file I need to be generate so that I can able to view that json file into OHIF viewer?

I checked all the questions (open n close) for this as well as official site I did not find any thing. So I am posting this question. 

Need help on this.

**Comment by sedghi** [comment]
Hmmm, I'm not sure what is the level of our support for SEG, SR, RT for dicom JSON. I will investigate

**Comment by sedghi** [comment]
see https://github.com/OHIF/Viewers/pull/3777

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
