### ISSUE TITLE
No loading indication leads to very user unfreienly behavior

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#2559]
In v1 of OHIF (meteor) while the viewer was preparing the initial display of the study it showed a loading screen as shown below:

![Screenshot 2021-09-24 130809](https://user-images.githubusercontent.com/5023419/134641218-1c7d8600-f656-4490-bf50-f33d9508f7f4.png)

The latest version of the OHIF viewer simply displays an empty viewer(see screenshot below) with no indication that anything is happening which makes the end user think that its not working correctly and they reload the page again and again

![Screenshot 2021-09-24 132355](https://user-images.githubusercontent.com/5023419/134643003-0f59185a-72b4-4e98-8c38-9958a605266b.png)

It would be very very helpful if the behavior of V1 could be replicated in the latest version.

**Comment by ranasrule** [comment]
I cant understand why this never gets any attention. I have tried raising this issue in the past as well. This really makes the viewer unusable specially over slow internet connections.

**Comment by ranasrule** [comment]
Can someone please tell me how I can change do the following?
![134643003-0f59185a-72b4-4e98-8c38-9958a605266b](https://user-images.githubusercontent.com/5023419/135184985-25f9e049-57b5-4152-8667-2277e9da3e6c.png)

**Comment by ranasrule** [comment]
> 
> 
> Can someone please tell me how I can change do the following? ![134643003-0f59185a-72b4-4e98-8c38-9958a605266b](https://user-images.githubusercontent.com/5023419/135184985-25f9e049-57b5-4152-8667-2277e9da3e6c.png)

@pieper @swederik  can you be of assistance please

**Comment by sedghi** [comment]
We have a loading indicator that is shown (you can see here https://viewer-dev.ohif.org/viewer/1.3.6.1.4.1.14519.5.2.1.7009.2403.459769504433903221904322299373), which uses the loadingIndicator [here](https://github.com/cornerstonejs/react-cornerstone-viewport/tree/master/src/LoadingIndicator)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
