### ISSUE TITLE
Facing issue while getting cors error in the  response data from frame api

### ISSUE THREAD

**Issue by afnan-softw** [OHIF/Viewers#2560]
Hi guys hope you are doing well, 
we are trying to integrate Dicom viewer with our own server and we are getting successful response from api as below 
1- Series API:- https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339/series
and
2- Metadata API:- https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339/series/1.3.6.1.4.1.14519.5.2.1.7009.2403.168353129945747450419572751964/metadata

but while trying to get details for the API name as "frames" it's not responding as required and giving cors error as mentioned in attached images.

Frame API:- https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339/series/1.3.6.1.4.1.14519.5.2.1.7009.2403.367700692008930469189923116409/instances/1.3.6.1.4.1.14519.5.2.1.7009.2403.296861241135036616434393975771/frames

without compressed data getting response successfully with status failed.

![code](https://user-images.githubusercontent.com/89979511/134650432-8bd6f14a-6f70-4e51-b46d-b696b87b9d52.PNG)
![firtResponse](https://user-images.githubusercontent.com/89979511/134651869-c4ae8e67-b9ae-403a-b54e-d46cd464cb32.PNG)

with compressed getting cors error

![secondcode](https://user-images.githubusercontent.com/89979511/134653376-72fd539b-f5c3-4a6b-adaf-478db0305a0e.PNG)

![cors](https://user-images.githubusercontent.com/89979511/134653649-022e3c2b-2df8-4a71-b38d-03a7b6286ed5.PNG)

we trying to get response like this way
![success](https://user-images.githubusercontent.com/89979511/134653994-26a0b74f-2208-45f5-85bb-a39dd5bc0bf5.PNG)

Kindly please go through the above details and help me to get proper response with compressed method.

Urgent request
Thanks

**Comment by sedghi** [comment]
Could you please review our comprehensive documentation on Cross-Origin Resource Sharing (CORS) and OHIF? Below are the links provided for your reference.

- https://docs.ohif.org/deployment/cors
- https://docs.ohif.org/deployment/iframe
