### ISSUE TITLE
Embedded ohif-viewer : Something went wrong in ViewerMain

### ISSUE THREAD

**Issue by amita125** [OHIF/Viewers#2567]
![image](https://user-images.githubusercontent.com/49608334/135049974-bca06393-bb2b-42a8-860c-b9373debd7de.png)

The left-hand panel displays the studies series but the viewer main is giving this error.

**Comment by anarnoli** [comment]
Hello @amita125 Did you get it resolved? Facing same issue in embedded viewer like below.

<img width="1106" alt="Screenshot 2022-10-29 at 7 43 01 PM" src="https://user-images.githubusercontent.com/54370515/200044888-211ea423-d24c-408a-ad3c-14cf161c82e5.png">

**Comment by sedghi** [comment]
In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
