### ISSUE TITLE
Ending up up with V2 of the viewer instead of V3

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#2568]
After successfully building OHIF viewer I still end up with V2 of the viewer instead of the new V3. What am I missing?

I'm downloading the latest source from the following link >>> https://github.com/OHIF/Viewers/releases/tag/%40ohif%2Fviewer%404.11.2

I have also tried the following link >>> https://github.com/OHIF/Viewers/archive/master.zip  as mentioned here >>> https://v3-docs.ohif.org/deployment/build-for-production

**Comment by jensen0914** [comment]
I believe that tag is associated with the v2 code branch. Maybe try the v3-stable branch? https://github.com/OHIF/Viewers/tree/v3-stable

**Comment by ranasrule** [comment]
> I believe that tag is associated with the v2 code branch. Maybe try the v3-stable branch? https://github.com/OHIF/Viewers/tree/v3-stable

Thanks. That did the trick
