### ISSUE TITLE
Vertical reference line Doubt

### ISSUE THREAD

**Issue by marcheschi** [OHIF/Viewers#257]
Hi
If I see the CT scan \:
![image](https://user-images.githubusercontent.com/3910408/44466398-7f515100-a620-11e8-8483-2acafefffd74.png)

While I understand the presence of the horizontal reference line ,
I do not understand the presence of the vertical one in the scout images.
Is it an error ?
Thank you
Paolo

**Comment by swederik** [comment]
Yeah there is some bug here, but I'm not exactly sure what it is. I wonder if this is a standalone viewer issue or if it also exists in the OHIF Viewer

**Comment by marcheschi** [comment]
Hi 
@CarnivorousRex  Images are from the demo CTStudy.json , if you scroll the scout appears the lateral or the frontal.
the error is present also on the other projection:
![image](https://user-images.githubusercontent.com/3910408/44511393-aeff6800-a6b7-11e8-9f5c-73da5b8fa5af.png)

Paolo

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

If you're able to provide a minimal reproduction, I can re-open this issue. Although, unless it is present in the v2 Viewer, I can't promise much in the way of resources from the core team to address this issue.

**Comment by matthiasg** [comment]
Is there a possibility to track the other line based on the current mouse position ?

**Comment by ArturRod** [comment]
You have to disable the reference line in the current viewer, and when you change you re-enable it, like this constantly. This will solve the problem with 2 viewers, but if you have more it will continue to appear in more views.

Example of some simple code to disable and enable:

  static async recargarVistas() {
    //Solo recargo la vista si esta habilitada la herramienta:
    if (habilitado) { //Variable global, true o false:
      //Scar los viewport:
      //Saco todos los viewports y activo los elementos:
      const vistas = Array.from(
        document.getElementsByClassName(
          'viewport-drop-target viewport-container'
        )
      );

      //Activo los que tienes que estar activados:
      for (var i = 0; i < vistas.length; i++) {
        var elemento = vistas[i].children[2].children[1];
        await cornerstoneTools.setToolEnabledForElement(
          elemento,
          'ReferenceLines'
        );
      }
      //Quito las lineas de la vista principal:
      //Saco el activado:
      //Y este le desactivo ya que no quiero que se muestre lineas en el que estoy posicionado actualmente:
      const vistaActivada = Array.from(
        document.getElementsByClassName(
          'viewport-drop-target viewport-container active'
        )
      );
      var elementoActivado = vistaActivada[0].children[2].children[1];
      await cornerstoneTools.setToolDisabledForElement(
        elementoActivado,
        'ReferenceLines'
      );
    }
  }
