### ISSUE TITLE
I Need Help For Enabling OHIF with 3D

### ISSUE THREAD

**Issue by kennethbrown65** [OHIF/Viewers#2572]
## Request

**What feature or change would you like to see made?**

Right now, we have the version for 2D. How do I suppose to add 3D? Someone or the some group of people can help me out regarding this? 

**Why should we prioritize this feature?**

Because it connected with CLARA.

**Comment by sedghi** [comment]
Right now you can launch 3D view from hanging protocol https://viewer.ohif.org/viewer?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2&hangingprotocolId=mprAnd3DVolumeViewport

But we have plan to add it to the UI soon
