### ISSUE TITLE
stack tracer format

### ISSUE THREAD

**Issue by Punzo** [OHIF/Viewers#2584]
related to issue https://github.com/OHIF/Viewers/issues/2581.

![image](https://user-images.githubusercontent.com/7985338/137503833-3ca8c1f3-e37c-4b92-a0d6-a968674dfa88.png)

@fedorov as we talked yesterday It would be nice to have a nicely formatted stack tracer and report it in the logger error console in the debug dialog. Is this a priority for you? or should we leave this as a candidate?

**Comment by sedghi** [comment]
I think we fixed it in master.
@fedorov can we close this?
