### ISSUE TITLE
Dynamically add series to already loaded study

### ISSUE THREAD

**Issue by vsaase** [OHIF/Viewers#2586]
Hi,

we are developing a viewer that should create PDF reports or trigger AI models. This means on the backend new series are created and we need the ability to dynamically load these new series into the already open viewer. I could not find a way to do that in the source code. Does anyone have a working example or hints on how to best implement it? I think ideally this would work through a redux action.

Victor

**Comment by sedghi** [comment]
We have this already in the master branch.
