### ISSUE TITLE
2D MPR Between Series/Sequences.

### ISSUE THREAD

**Issue by e-farias** [OHIF/Viewers#2587]
> In conversations with Brazilian medical professors, we found that this type of analysis makes understanding certain studies easier to understand.

I'm still getting acquainted with OHIF and I need help. Currently, 2D MPR viewing is done in a single sequence. I would like to know if in OHIF I can start 2D MPR visualization between different sequences. If not currently possible, is it possible to implement such a feature via vtk.js or another tool?

An example that illustrates this feature is present in Horus where we select distinct sequences, click 'Enter' and the '2D MPR' visualization starts:

https://user-images.githubusercontent.com/43360593/137923884-bcc6b8b4-f5af-4140-a73e-3afc4b8b1ade.mp4

In OHIF, if I start the 2D MPR and select another sequence, the view is broken:

https://user-images.githubusercontent.com/43360593/137925355-ddfceb0f-3290-4266-91b8-d2f6349441a9.mp4

**Comment by shravan26** [comment]
@e-farias Have you been able to solve this problem?

**Comment by linkfengs** [comment]
awesome！thanks for your share
