### ISSUE TITLE
OHIF viewer requests frames with Accept: transfer-syntax=* header which is not supported by Orthanc

### ISSUE THREAD

**Issue by szymswiat** [OHIF/Viewers#2591]
### Describe the Bug
I tried to setup OHIF v3 (bug can be reproduced with OHIF v2 too) with local orthanc server as described in [documentation](https://v3-docs.ohif.org/configuration/data-sources). Images loaded to orthanc are displayed correctly on list of images and can be downloaded through its UI, but when I'm launching viewer for selected image I'm getting black window instead of image (thumbnail is also empty).

Above issue is caused by failing GET request:

    GET /dicom-web/studies/2.25.33821232590408129531920511982967717759/series/2.25.72291574555945918176759302442880844677/instances/2.25.319280037670054236943789430461364251103/frames/1 HTTP/1.1

    Host: localhost:3000
    User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0
    Accept: multipart/related; type="application/octet-stream"; transfer-syntax=*
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate
    DNT: 1
    Connection: keep-alive
    Referer: http://localhost:3000/viewer?StudyInstanceUIDs=2.25.33821232590408129531920511982967717759
    Cookie: i18next=en-US
    Sec-Fetch-Dest: empty
    Sec-Fetch-Mode: cors
    Sec-Fetch-Site: same-origin

Looks like Orthanc server does not accept `Accept: transfer-syntax=*` header for uncompressed data and throws following error when viewer tries to fetch frame:

    orthanc_1  | E1022 19:14:43.249920 PluginsErrorDictionary.cpp:111] Exception inside the plugin engine: Bad request     
    orthanc_1  | E1022 19:14:43.325805 PluginsManager.cpp:164] Bad request: DICOMweb RetrieveFrames: Cannot specify a transfer syntax (*) for default Little Endian uncompressed pixel data

### What steps can we follow to reproduce the bug?

Setup local orthanc server as described in [documentation](https://v3-docs.ohif.org/configuration/data-sources).

**Comment by wiekern** [comment]
I meet the same problem when I am running a local orthanc docker container.

**Comment by DimChib** [comment]
I meet the same problem also. The solution in my case was to install the newest version of orthanc server, to start the local orthanc server. The error message doesn't appear anymore and the images can be displayed in the OHIV viewer.

**Comment by shravan26** [comment]
> I meet the same problem also. The solution in my case was to install the newest version of orthanc server, to start the local orthanc server. The error message doesn't appear anymore and the images can be displayed in the OHIV viewer.

This worked for me. Thanks, I used the 1.9.7 image and the errors got fixed.

**Comment by seandoyle** [comment]
I've encountered the same issue on the v3-stable branch from yesterday on two machines. A third machine is running with an older (sometime in May) release with the same docker/docker-compose/orthanc.json/ngnix settings. I've installed a version of Orthanc (the :latest) which looks like it's from May 2022. 

Is there something else I can update? Is there something in the new cornerstone/data streaming libraries that requires a change in the orthanc configurations? Thanks.

**Comment by sheep-tech** [comment]
Orthanc transcoding syntax was introduced in Orthanc 1.7.0 [Documentation](https://book.orthanc-server.com/faq/transcoding.html).
So you simply update the .docker\Nginx-Orthanc\docker-compose.yml file orthanc image version to like 1.11.0, for example:

`services:
  orthanc:
    image: jodogne/orthanc-plugins:1.11.0`

I think the master branch should use this version by default.
