### ISSUE TITLE
Error while compiling with "yarn run dev"

### ISSUE THREAD

**Issue by gfiorellaTA** [OHIF/Viewers#2599]
I installed the lastest version of code, but when i runned "yarn run dev" for opening the viewer, i obtained the following errors.

![image](https://user-images.githubusercontent.com/93374934/139416401-399002a5-5375-405f-98a7-322eec2997e4.png)

There are many others errors like these below and at the end the @ohif/viewer failed to compile.
I also installed the following version of packages requested:
- Node.js 14.18.0
- Yarn 1.22.15
- NPM 6.14.15

Could you please give me an idea of what could be the problem and maybe how to fix?
Thanks in advance.

**Comment by ynakanishi1985** [comment]
I have very similar issues when I enter "yarn run dev" .
Does anyone knows what is wrong, and how to solve it ?

**Comment by tonyno-soft** [comment]
install dependencies from "yarn install" or "npm i", install docker and try again.
