### ISSUE TITLE
Long patient list takes time to load

### ISSUE THREAD

**Issue by mdg583** [OHIF/Viewers#26]
Hello,

I am trying to use the OHIF viewer with a dicom store of X-Ray images. It's deployed and working (without Docker), but I am unsure of how to make customizations to it.

Specifically, when the startup page opens (worklist?) it takes some time to load the patient list. I can only imagine this getting worse as I add the rest of the X-Ray archive to the system (18000 images). Is there a way to make it not show an initial list of patients, or to enable some kind of pagination?

Thanks

**Comment by swederik** [comment]
You can try to use DIMSE instead of DICOM Web, which might make it faster (not sure if this applies to other servers than Orthanc), but you're right, some sort of pagination is probably necessary. I'll see what we can do about that.

**Comment by mdg583** [comment]
For now I made changes to worklistResult.js
```
--- worklistResult.orig.js	2016-07-21 13:37:31.595899787 +0300
+++ worklistResult.js	2016-07-21 13:36:42.778486103 +0300
@@ -1,5 +1,5 @@
 Session.setDefault('searchResults', {
-    showLoadingText: true,
+    showLoadingText: false,
     showNotFoundMessage: false
 });
 
@@ -174,7 +174,7 @@
     this.sortingColumns = new ReactiveDict();
 
     // Retrieve all studies
-    search();
+    // search();
 
     // Set sortOption
     var sortOptionSession = Session.get('sortOption');
```
