### ISSUE TITLE
Not able to change Logo using whiteLabeling

### ISSUE THREAD

**Issue by GopiWilco** [OHIF/Viewers#2603]
Hi,

First of all, thank you so much for the nice tool which is helping us great to view the DICOM images.

Actually we are using MVC C# Project, We were able to implement OHIF with orthanc server. But we couldn't able to change the logo.

I have tried to update the logo,

![image](https://user-images.githubusercontent.com/42967099/140050014-c60d0643-7014-44c6-860e-61b7071e78d9.png)

![image](https://user-images.githubusercontent.com/42967099/140050060-ac1f3858-1672-48e4-ac40-c9ddc929bb00.png)

But I can't see any updates to the Logo

https://docs.ohif.org/viewer/themeing.html

Could you please help on this.

Thanks and Regards,
Gopi.S

**Comment by ArturRod** [comment]
Hi @GopiWilco.
The logo is changed from viewer / components / OHIFLogo, that in v2:
![image](https://user-images.githubusercontent.com/86238895/140293850-39f3eeb4-1527-442f-9371-7478b061e254.png)

**Comment by GopiWilco** [comment]
Hi @ArturRod,

Thank you so much for the reply.

We are not using the React or Angular Application. 

We are integrating the OHIF in MVC HTML page. Here is the link for the sample code on fiddle which is similar to our implementation but it's not working.

https://codesandbox.io/s/viewer-script-tag-forked-th5zf?file=/index.html:0-2757

Source Code:


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />

    <meta
      name="description"
      content="Open Health Imaging Foundation DICOM Viewer"
    />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1.0,minimum-scale=1,maximum-scale=1,user-scalable=no"
    />
    <meta name="theme-color" content="#000000" />
    <meta http-equiv="cleartype" content="on" />
    <meta name="MobileOptimized" content="320" />
    <meta name="HandheldFriendly" content="True" />
    <meta name="apple-mobile-web-app-capable" content="yes" />

    
    <link
      href="https://fonts.googleapis.com/css?family=Sanchez"
      rel="stylesheet"
    />

    <title>OHIF Standalone Viewer</title>
  </head>

  <body>
    <noscript> You need to enable JavaScript to run this app. </noscript>

    <div id="root"></div>

    <script
      src="https://unpkg.com/@ohif/viewer@1.0.3/dist/index.umd.js"
      crossorigin
    ></script>

    <script>
      var containerId = "root";
      var componentRenderedOrUpdatedCallback = function () {
        console.log("OHIF Viewer rendered/updated");
      };
      window.OHIFViewer.installViewer(
        {
          routerBasename: "/",
          whiteLabeling: {
            /* Optional: Should return a React component to be rendered in the "Logo" section of the application's Top Navigation bar */
            createLogoComponentFn: function (React) {
              return React.createElement("a", {
                target: "_self",
                rel: "noopener noreferrer",
                className: "header-brand",
                href: "/",
                style: {
                  display: "block",
                  textIndent: "-9999px",
                  background:
                    "url(https://placehold.it/400x100?text=Placeholder+Logo&color=#53A548)",
                  backgroundSize: "contain",
                  backgroundRepeat: "no-repeat",
                  width: "200px"
                }
              });
            }
          },
          servers: {
            dicomWeb: [
              {
                name: "DCM4CHEE",
                wadoUriRoot:
                  "https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado",
                qidoRoot:
                  "https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs",
                wadoRoot:
                  "https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs",
                qidoSupportsIncludeField: true,
                imageRendering: "wadors",
                thumbnailRendering: "wadors"
              }
            ]
          }
        },
        containerId,
        componentRenderedOrUpdatedCallback
      );
    </script>
  </body>
</html>


Thanks and Regards,

Gopi.S

**Comment by ArturRod** [comment]
@GopiWilco Have you tried to open a file with a local path, ie ./image.svg?
I used to use this method before and if it worked for me, it is not loading the image or anything anyway, just forcing with **!important** to load it or something ...

**Comment by GopiWilco** [comment]
Hi @ArturRod ,

Yes, I have tried with Local Path also. But no changes are happening.

![image](https://user-images.githubusercontent.com/42967099/140386934-3bd7b3c2-5d78-4899-9245-8853fd0be492.png)


Thanks and Regards,

Gopi.S

**Comment by ArturRod** [comment]
Hi @GopiWilco 
How strange, in that case I would try to see where the original method of creating the logo is and try to modify it there ...
Since as I tell you in this method if it worked for me, of course I am using it in JS and reacjs.
Sorry I can not help anymore ...

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
