### ISSUE TITLE
KOS series don't show in series list (v2)

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2604]
### Describe the Bug

Key Object Selection instances are not shown.

It would be better to provide a series box with a message that they can't be handled.  (Actually handling them is not a request currently).

### What steps can we follow to reproduce the bug?

Here's an example of a study with KOS:
https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.2103.7010.333899005177230305399406859716

**Comment by bcli4d** [comment]
I suggest that, in the case that the viewer cannot display a series graphically, it fall back to adding some kind of symbolic thumbnail in the left hand series selection tray. If such a series is selected for viewing, the DICOM metadata of the instance(s) in the series are displayed. This is what is currently done for SRs.
We came across another case where this would help...an instance with modality MR but a Raw Data Storage SOP Class (no pixel data.) The IDC web app thinks it is displayable and allows the user to request displaying it in OHIF, which then just shows an empty window; the TCIA webapp is similar.
Though the IDC webapp could be made to recognize this last case and not offer to display it, as we add new instances there might be yet other instance types that the webapp doesn't recognize as non-displayable. It seems that the viewer is in the best position to perform some kind of fallback in these case.

**Comment by fedorov** [comment]
As discussed at the call today, if the series is not recognized by the thumbnail series selection logic, it should show the series with the Modality value in the thumbnail, and the series should also show up in the Tag Browser dropdown.
