### ISSUE TITLE
Viewing DICOM images stored in a directory

### ISSUE THREAD

**Issue by dcornfel** [OHIF/Viewers#2607]
Apologies this may be basic.  Similar questions have been asked before but without definite solutions.
I am wondering the best way to approach a problem.

I want to be able to link to an OHIF Viewer to display only a single study using locally stored data (stored on the same server as OHIF, not the client computer).

I have seen the https://v3-demo.ohif.org/local demo.  I assume this parses the selected client side folder to create a JSON file used to then open the study.  Is there a way to direct the OHIF Viewer towards a folder containing images located on the same server (as opposed to on the client computer)  so that the study is opened in a similar way?  If not, is there code I can use to parse a static folder containing DICOM images to create a json file that I can then use to open the study from that folder?  (i.e. manually create the folder with DICOM images, then create the json file, then hardcode the link to OHIF so it uses the json file to open the images in that folder) If so can someone direct me to information on how to do this (both how to create the json file and also how to use this to open the study from the folder)? 

Ive also read the Static Files section (under Configuration/Data Sources) in the v3 documentation.  This looks like it allows you to include a study list within the OHIF build.  However, since I want to only open a single study at a time and not generate a study list this may not be what I am looking for.

To answer why am I wanting to do this, I am trying to create a teaching file that can run without requiring internet access.  All the images plus the viewer would be encompassed using Cordova.  The teaching file would then be completely self  contained. (This still might not work if OHIF links to its dependancies as opposed to implicitly including them in its build).

Many thank for any suggestions,

Dan

**Comment by igoroctaviano** [comment]
Hi Dan, I have these links that might help you:
- https://github.com/wayfarer3130/static-wado
- https://github.com/chafey/dicomp10-to-dicomweb-js

**Comment by dcornfel** [comment]
Dear Igor,

Thank you very much.  I will look into these.

Dan

**Comment by acaland** [comment]
Hi @dcornfel,

I have a very similar goal. Did you find a viable solution? thx

**Comment by anarnoli** [comment]
Same here @acaland . Thanks

**Comment by EtnaTraining** [comment]
@anarnoli I was able to publish a static set of DICOM using [static-wado](https://github.com/wayfarer3130/static-wado)

**Comment by anarnoli** [comment]
Definitely yes @EtnaTraining

**Comment by anarnoli** [comment]
Hi @EtnaTraining I have problem in generating Metadata json using static-wado. Could you please help me at [issue](https://github.com/wayfarer3130/static-wado/issues/6)?

**Comment by anarnoli** [comment]
> @anarnoli I was able to publish a static set of DICOM using [static-wado](https://github.com/wayfarer3130/static-wado). Do you believe a blog post about how I did it could be of interest?

@EtnaTraining  Do you have a plan for blog post about static-wado?

**Comment by asemeria** [comment]
> @anarnoli I was able to publish a static set of DICOM using [static-wado](https://github.com/wayfarer3130/static-wado). Do you believe a blog post about how I did it could be of interest?

@EtnaTraining Yes please

**Comment by acaland** [comment]
I have still on plans to write a blog post but I am quite busy. Hopefully I will be able to do it by the end of the month

**Comment by asemeria** [comment]
Thank you @acaland. So, you figured out a way to show a study from a DICOMWeb (created by static-wado) from a folder directly, is it right?

**Comment by sulaimanvesal** [comment]
Any update on this? I would highly appreciate. I tried to check static-wado repo but couldn't figure it out completely.

**Comment by acaland** [comment]
I had plan to write a blog post, but I realised that my installation has been done on a local hosting provider and I had to customise some .htaccess rules to make it work. Not sure if my recipe will apply to others. What kind of hosting are you using for your static wado?
