### ISSUE TITLE
[Bug] There is error when upgrading ohif to version 3

### ISSUE THREAD

**Issue by thanhtd1012** [OHIF/Viewers#2609]
Hi @ALL !

I checkout the ohif version 3 at:
https://github.com/OHIF/Viewers/tree/v3-stable

Then I integrated my ohif ( running on  v4.9.17) into version 3.
There is following error:
![image](https://user-images.githubusercontent.com/70577879/141086238-259e1fb1-e851-4634-919c-9743cc82519f.png)

Please check and help me!
Thanks guys!

**Comment by sedghi** [comment]
What happens if you do a fresh yarn install for v3-stable?
