### ISSUE TITLE
Invalid date error on overlay

### ISSUE THREAD

**Issue by arturojain** [OHIF/Viewers#2616]
### Describe the Bug

When loading a new image I get an `Invalid date Invalid date` overlay instead of the patient data. I'm using `v2`.

<img width="167" alt="Screen Shot 2021-11-19 at 11 28 17" src="https://user-images.githubusercontent.com/5528886/142666192-b3539e81-b72e-4221-aba9-41ed4aa6c27e.png">

### What steps can we follow to reproduce the bug?

1. Load study using JSON from `url` param
2. Example JSON:

```json
{
  "studies": [
    {
      "StudyInstanceUID": "1.2.392.200036.9107.500.111704218022204451",
      "StudyDescription": "DEMO",
      "StudyDate": "20180223",
      "StudyTime": "020423.000000",
      "PatientName": "DEMO  DEMO",
      "PatientId": "DEMO",
      "series": [
        {
          "SeriesDescription": "DEMO",
          "SeriesInstanceUID": "1.2.392.200036.9107.500.220.17042.2018022220070409.122",
          "SeriesDate": "20180223",
          "SeriesTime": "020423.000000",
          "Modality": "CR",
          "instances": [
            {
              "metadata": {
                "Columns": 1430,
                "Rows": 1722,
                "InstanceNumber": 1,
                "AcquisitionNumber": 1,
                "PhotometricInterpretation": "MONOCHROME1",
                "BitsAllocated": 16,
                "BitsStored": 12,
                "PixelRepresentation": 0,
                "SamplesPerPixel": 1,
                "PixelSpacing": [
                  "0.17500000000000",
                  "0.17500000000000 "
                ],
                "HighBit": 11,
                "ImageOrientationPatient": null,
                "ImagePositionPatient": null,
                "FrameOfReferenceUID": null,
                "ImageType": [
                  "ORIGINAL",
                  "PRIMARY"
                ],
                "Modality": "CR",
                "SOPInstanceUID": "1.2.392.200036.9107.500.220.17042.20180222.200704.13701.1",
                "SeriesInstanceUID": "1.2.392.200036.9107.500.220.17042.2018022220070409.122",
                "StudyInstanceUID": "1.2.392.200036.9107.500.111704218022204451"
              },
              "url": "dicomweb://demourl"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by carlo-sivilotti** [comment]
I'm also experiencing this, did you find a workaround Arturo?

**Comment by arturojain** [comment]
> I'm also experiencing this, did you find a workaround Arturo?

Not yet.

**Comment by carlo-sivilotti** [comment]
Commenting out 
```
  cornerstone.metaData.addProvider(
    metadataProvider.get.bind(metadataProvider),
    9999
```
in extensions/cornertsone/src/init.js resolved this for me.

**Comment by huangji123** [comment]
After I commented out this code, my mpr can't work properly. What about this?

 cornerstone.metaData.addProvider(
    metadataProvider.get.bind(metadataProvider),
    9999

**Comment by huangji123** [comment]
> 由基石的`一般研究模块`元数据提供程序未能返回任何提供的研究标题。
> 
> 注释掉
> 
> ```
> cornerstone . metadata . add provider(metadata provider . get . bind(metadata provider)，9999
> ```
> 
> 在extensions/cornertsone/src/init . js中为我解决了这个问题。(进一步详情[这里](https://github.com/OHIF/Viewers/issues/2426#issuecomment-917193104))

After I commented out this code, my mpr can't work properly. What about this?

cornerstone.metaData.addProvider(
metadataProvider.get.bind(metadataProvider),
9999

**Comment by carlo-sivilotti** [comment]
@huangji123 
You might also be able to change the priority of the cornerstone provider (e.g. '9999' -> '-9999') to allow the other providers to be responsible for the date fields, while still keeping mpr.

`my mpr can't work properly` what is wrong with it? MPR still works for me with this provider disabled.

**Comment by arturojain** [comment]
> Caused by cornerstone's `generalStudyModule` metaData provider failing to return any of the provided study headers.
> 
> Commenting out
> 
> ```
>   cornerstone.metaData.addProvider(
>     metadataProvider.get.bind(metadataProvider),
>     9999
> ```
> 
> in extensions/cornertsone/src/init.js resolved this for me. (further details [here](https://github.com/OHIF/Viewers/issues/2426#issuecomment-917193104))

Solved the issue.

**Comment by huangji123** [comment]
> > Caused by cornerstone's `generalStudyModule` metaData provider failing to return any of the provided study headers.
> > Commenting out
> > ```
> >   cornerstone.metaData.addProvider(
> >     metadataProvider.get.bind(metadataProvider),
> >     9999
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in extensions/cornertsone/src/init.js resolved this for me. (further details [here](https://github.com/OHIF/Viewers/issues/2426#issuecomment-917193104))
> 
> Solved the issue.

Hello, could you tell me the reason why OHIF displays the garbled Chinese names?

**Comment by huangji123** [comment]
> > Caused by cornerstone's `generalStudyModule` metaData provider failing to return any of the provided study headers.
> > Commenting out
> > ```
> >   cornerstone.metaData.addProvider(
> >     metadataProvider.get.bind(metadataProvider),
> >     9999
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in extensions/cornertsone/src/init.js resolved this for me. (further details [here](https://github.com/OHIF/Viewers/issues/2426#issuecomment-917193104))
> 
> Solved the issue.

Hello, could you tell me the reason why OHIF displays the garbled Chinese names?

> @huangji123 You might also be able to change the priority of the cornerstone provider (e.g. '9999' -> '-9999') to allow the other providers to be responsible for the date fields, while still keeping mpr.
> 
> `my mpr can't work properly` what is wrong with it? MPR still works for me with this provider disabled.

Hello, could you tell me the reason why OHIF displays the garbled Chinese names?

**Comment by huangji123** [comment]
> > Caused by cornerstone's `generalStudyModule` metaData provider failing to return any of the provided study headers.
> > Commenting out
> > ```
> >   cornerstone.metaData.addProvider(
> >     metadataProvider.get.bind(metadataProvider),
> >     9999
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in extensions/cornertsone/src/init.js resolved this for me. (further details [here](https://github.com/OHIF/Viewers/issues/2426#issuecomment-917193104))
> 
> Solved the issue.

Hello, could you tell me the reason why OHIF displays the garbled Chinese names?

> @huangji123 You might also be able to change the priority of the cornerstone provider (e.g. '9999' -> '-9999') to allow the other providers to be responsible for the date fields, while still keeping mpr.
> 
> `my mpr can't work properly` what is wrong with it? MPR still works for me with this provider disabled.

Hello, could you tell me the reason why OHIF displays the garbled Chinese names?

> ## Bug Report
> ### Describe the Bug
> When loading a new image I get an `Invalid date Invalid date` overlay instead of the patient data. I'm using `v2`.
> 
> <img alt="Screen Shot 2021-11-19 at 11 28 17" width="167" src="https://user-images.githubusercontent.com/5528886/142666192-b3539e81-b72e-4221-aba9-41ed4aa6c27e.png">
> 
> ### What steps can we follow to reproduce the bug?
> 1. Load study using JSON from `url` param
> 2. Example JSON:
> 
> ```json
> {
>   "studies": [
>     {
>       "StudyInstanceUID": "1.2.392.200036.9107.500.111704218022204451",
>       "StudyDescription": "DEMO",
>       "StudyDate": "20180223",
>       "StudyTime": "020423.000000",
>       "PatientName": "DEMO  DEMO",
>       "PatientId": "DEMO",
>       "series": [
>         {
>           "SeriesDescription": "DEMO",
>           "SeriesInstanceUID": "1.2.392.200036.9107.500.220.17042.2018022220070409.122",
>           "SeriesDate": "20180223",
>           "SeriesTime": "020423.000000",
>           "Modality": "CR",
>           "instances": [
>             {
>               "metadata": {
>                 "Columns": 1430,
>                 "Rows": 1722,
>                 "InstanceNumber": 1,
>                 "AcquisitionNumber": 1,
>                 "PhotometricInterpretation": "MONOCHROME1",
>                 "BitsAllocated": 16,
>                 "BitsStored": 12,
>                 "PixelRepresentation": 0,
>                 "SamplesPerPixel": 1,
>                 "PixelSpacing": [
>                   "0.17500000000000",
>                   "0.17500000000000 "
>                 ],
>                 "HighBit": 11,
>                 "ImageOrientationPatient": null,
>                 "ImagePositionPatient": null,
>                 "FrameOfReferenceUID": null,
>                 "ImageType": [
>                   "ORIGINAL",
>                   "PRIMARY"
>                 ],
>                 "Modality": "CR",
>                 "SOPInstanceUID": "1.2.392.200036.9107.500.220.17042.20180222.200704.13701.1",
>                 "SeriesInstanceUID": "1.2.392.200036.9107.500.220.17042.2018022220070409.122",
>                 "StudyInstanceUID": "1.2.392.200036.9107.500.111704218022204451"
>               },
>               "url": "dicomweb://demourl"
>             }
>           ]
>         }
>       ]
>     }
>   ]
> }
> ```

Hello, could you tell me the reason why OHIF displays the garbled Chinese names?
