### ISSUE TITLE
Saving measurements to structured reports incorrectly updates study date

### ISSUE THREAD

**Issue by ryan00012** [OHIF/Viewers#2617]
> **Before Creating an issue**
>
> - Are you running the latest version? Yes
> - Are you reporting to the correct repository? Yes
> - Did you search existing issues? Yes

### Describe the Bug

After creating a structured report, the displayed study dates have issues:
![Screen Shot 2021-11-22 at 6 29 32 PM](https://user-images.githubusercontent.com/20689297/142963028-06b7405d-ff19-4f27-9664-49ce33486f1f.jpg)

- Location 1 has the creation date of the structured report (22-Nov-2021) - this is expected
- Location 2 also has the creation date of the structured report (22-Nov-2021) - this seems unexpected as it should have the original study date that is shown in location 3.  Location 2 used to display 27-Apr-1998 as well until we created the SR. We are wondering if this is the intended behavior.
- Location 3 has the original date (27-Apr-1998) - this is expected

The dates get more interesting as time passes. See an example where we created a structured report on 09-Nov-2021. 
![Screen Shot 2021-11-22 at 6 26 10 PM](https://user-images.githubusercontent.com/20689297/142962851-80adba2c-e518-41ec-b71c-65a92e2001a4.jpg)

- Location 1 says the SR creation date (9-Nov-2021) - expected
- Location 2 and 3 both say the current date (22-Nov-2021) - seems incorrect

### What steps can we follow to reproduce the bug?

1. Open the viewer and make measurements using the measurements tool
2. Save the measurements to a structured report in the right measurements pane
3. Refresh the page
4. Within the studies pane on the left, the study date is at the top of the page. This is now updated to be the creation date (today) of the structured report. After some time, the date in the top left of the viewer will also reflect this date.
5. As days pass, the two dates that are shown will actually always update to the current date, even if the structured report create date was in the past. 

We are currently investigating ourselves. We are wondering if this is somehow the intended behavior though.

> :warning: Reports we cannot reproduce are at risk of being marked stale 
and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by james-hanks** [comment]
@jbocce to reproduce in current version

**Comment by jbocce** [comment]
No longer able to reproduce this issue in master 3.8.0-beta.6.
