### ISSUE TITLE
add new private tag and save changes to orthanc server

### ISSUE THREAD

**Issue by Raghad7** [OHIF/Viewers#2619]
hello, 
I am new to ohif and I was wondering if there is a way to let the user add new private tag and then save the modified dicom image back to the orthanc server, or to save it back to the server as new dicom file and still keep the original ?

thank you

**Comment by ranasrule** [comment]
> hello, I am new to ohif and I was wondering if there is a way to let the user add new private tag and then save the modified dicom image back to the orthanc server, or to save it back to the server as new dicom file and still keep the original ?
> 
> thank you

I don't think that's really within the scope of a dicom viewer.

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
