### ISSUE TITLE
bcrypt installation fails 

### ISSUE THREAD

**Issue by lexi2000** [OHIF/Viewers#262]
Dear all,
I am trying to install the OHIF viewer on a cloud linux machine.
It seems that binaries for bcrypt have been moved and despite multiple different attempts, I am not able to install npm (see below).
any suggestions are very welcome!

sudo meteor npm install
> bcrypt@2.0.0 install /opt/Viewers/OHIFViewer/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v2.0.0/bcrypt_lib-v2.0.0-node-v57-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@2.0.0 and node@8.11.3 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/Viewers/OHIFViewer/node_modules/bcrypt/build'
gyp ERR! System Linux 4.4.0-130-generic
gyp ERR! command "/home/paperspace/.meteor/packages/meteor-tool/.1.7.0_3.i19fj7.55mp++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/paperspace/.meteor/packages/meteor-tool/.1.7.0_3.i19fj7.55mp++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/Viewers/OHIFViewer/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/opt/Viewers/OHIFViewer/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--nodedir=/home/paperspace/.meteor/packages/meteor-tool/.1.7.0_3.i19fj7.55mp++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle"
gyp ERR! cwd /opt/Viewers/OHIFViewer/node_modules/bcrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error

**Comment by dedman** [comment]
@lexi2000 I'm having a similar issue except on Windows 2016, did you resolve the issue?

**Comment by dedman** [comment]
I needed to follow the installation instructions here https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

Which for windows was "meteor npm install --global --production windows-build-tools"

After that installed this was helpful for the subsequent C:\Microsoft.Cpp.Default.props  was not found error. https://stackoverflow.com/questions/41695251/c-microsoft-cpp-default-props-was-not-found (specifically setting the VCTargetsPath)

**Comment by swederik** [comment]
We've dropped Meteor accounts from the OHIF Viewer, and bcrypt is no longer present as a side effect. So I guess we can close this.

Thanks for the report!
