### ISSUE TITLE
Annotation window bug

### ISSUE THREAD

**Issue by ed-morais** [OHIF/Viewers#2624]
In development mode, the annotation window works just fine, as in the picture below:

![Screenshot from 2021-12-01 10-41-54](https://user-images.githubusercontent.com/61170661/144245328-fceff56e-c7c8-4f75-b513-ce865379d3bd.png)

But when I build the application, the annotation window doesn't appear, this is what is shown on the screen:

![Screenshot from 2021-12-01 10-40-22](https://user-images.githubusercontent.com/61170661/144245788-7450aea1-7057-4747-b56e-65af43cbd93a.png)

I'm wondering if this problem happens to other people and what can be done to solve it. (Ohif version: 4.12.2).

Thank you so much! :)

**Comment by supasus** [comment]
I've had the same issue

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
