### ISSUE TITLE
How to include mpr into ohif?

### ISSUE THREAD

**Issue by Rokaimi** [OHIF/Viewers#2625]

**Comment by sedghi** [comment]
OHIF v2 (master branch) can show MPR by clicking on the 2D MPR in the toolbar, if the series is reconstructable

**Comment by rohang1411** [comment]
But How to use MPR in v3. Or is there any other alternative in v3, if yes where is it and how to use it? And I'm trying to install the latest release but facing issues ininstallation. Can someone please guide me.

**Comment by arunvc** [comment]
check out the supported features in v3 https://v3-docs.ohif.org/release-notes

**Comment by cultulhul** [comment]
Do you have any idea what the Other plans is or when they will announce

**Comment by jrudascas** [comment]
Any update on this? The v3 release note says that VTK Extension + MIP / MPR layout is included, however, branch v3-stable by default does not include MPR tool.

**Comment by manoocher** [comment]
> The functionality is there now in code, but the v3 release will come with a MPR button which would convert the active viewport to a 1x3 MPR similar to v2.

When is the next release? can you tell me how to activate the button?

**Comment by mohammedameen028** [comment]
Any latest update on mpr in v3 release? mpr button still does't work in v3.

**Comment by sedghi** [comment]
@mohammedameen028 The icon is added v3-demo.ohif.org

**Comment by sedghi** [comment]
It is already there 

![CleanShot 2023-10-13 at 09 54 48](https://github.com/OHIF/Viewers/assets/7490180/dacaf10c-17e9-4cb5-acac-9e644bc9f349)
