### ISSUE TITLE
HangingProtocol.viewportSettings not working...

### ISSUE THREAD

**Issue by imzqqq** [OHIF/Viewers#2631]
> **Before Creating an issue**
>
> - Are you running the latest version? - Yes, v3-stable
> - Are you reporting to the correct repository? - Yes
> - Did you search existing issues? - Yes, no related issue or issues

### Describe the Bug

I want to achieve the effect as shown in the picture:
![B305_Morgan_HangProto_v1_Page_03](https://user-images.githubusercontent.com/38660211/144816275-de39555f-fc85-45f9-bf58-02afe73168ab.png)

so I changed the code in platform/core/src/services/HangingProtocolService/ProtocolEngine.js to test if viewportSettings can work, saddly it not, pelease help, thks.

### What steps can we follow to reproduce the bug?

1. change the code in platform/core/src/services/HangingProtocolService/ProtocolEngine.js, see `/// MARK ///` park below
2. run the Viewers

```js
const defaultProtocol = {
  id: 'defaultProtocol',
  locked: true,
  hasUpdatedPriorsInformation: false,
  name: 'Default',
  createdDate: '2021-02-23T19:22:08.894Z',
  modifiedDate: '2021-02-23T19:22:08.894Z',
  availableTo: {},
  editableBy: {},
  protocolMatchingRules: [],
  stages: [
    {
      id: 'nwzau7jDkEkL8djfr',
      name: 'oneByOne',
      /// MARK - this is working
      viewportStructure: {
        type: 'grid',
        properties: {
          rows: 1,
          columns: 1,
        },
      },
     ///
      viewports: [
        {
          /// MARK - followed the instructions in docs, not working
          viewportSettings: [
            {
              options: {
                voi: {
                  windowWidth: 400,
                  windowCenter: 40,
                },
              },
              commandName: '',
              type: 'viewport',
            },
          ],
          ///
          imageMatchingRules: [],
          seriesMatchingRules: [],
          studyMatchingRules: [],
        },
      ],
      createdDate: '2021-02-23T19:22:08.894Z',
    },
  ],
  numberOfPriorsReferenced: -1,
};
```

**Comment by sedghi** [comment]
ViewportSettings are not for placing the displaySets on the viewports. You need to find the correct displayset and putting it in the order you want it to be displayed in `viewports: [`

**Comment by sedghi** [comment]
You can take a look at our HP docs here https://docs.ohif.org/platform/extensions/modules/hpModule
