### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by shivasuri** [OHIF/Viewers#2635]
> :hand: Many people requests features. Tell us why yours is important to the
> community. How does it add value? Why _this feature_?
>
> Is your request very specific to your needs? Consider
> [contributing it](https://docs.ohif.org/contributing.html) yourself! Or reach
> out to a community member that offers
> [consulting services](https://docs.ohif.org/help.html#paid--commercial).

## Request

**What feature or change would you like to see made?**
Support multiple viewer windows where viewports can communicate with each other across windows.
 
...

**Why should we prioritize this feature?**
Many radiologists use multiple vertical diagnostic monitors in practice.

What would be the suggested approach to implement this? A few ideas:
1) Google Presentation API: https://googlechromelabs.github.io/presentation-api-samples/photowall/
2) Converting to an electron app
...

**Comment by swederik** [comment]
Yes this would be great, we just lack the funding to implement it. If your
organization is interested in funding it or willing to create pull requests
we would be interested in adding support.

**Comment by sedghi** [comment]
We have secured funding for this in our U24 grant. However, it is not a high priority at the moment

**Comment by radlinkhealth** [comment]
Any updates on this requirement now? Will it be ready in near future ?

**Comment by invent4health** [comment]
any updates on this requirement
