### ISSUE TITLE
BUG Method _imageLoadProgressEventHandle -> _imageLoadProgressEventHandler

### ISSUE THREAD

**Issue by ArturRod** [OHIF/Viewers#2638]
In the DICOMFileLoadingListener line of code the constructor method
this.imageLoadProgressEventHandler = this._imageLoadProgressEventHandle.bind(
      this
    );
This wrong, it appears without the 'r' at the end, causing it to break if you open types of XA studies.
![image](https://user-images.githubusercontent.com/86238895/147073553-4d6dabd4-047c-4b28-b51d-aca23a0cd93c.png)

**Comment by sedghi** [comment]
Thanks for reporting
