### ISSUE TITLE
Docker build fails on Raspberry Pi

### ISSUE THREAD

**Issue by kobuki** [OHIF/Viewers#2655]
I'm not 100% sure if this should be a bug report or a feature request, but I think it's the former as OHIF as s software is advertised as being able to run on a Raspberry Pi.

### Describe the Bug

Fresh checkout on Rpi4, Debian Buster 10.10, Docker 20.10.7
commit d7ba2fac69c7724602e82345c344d8c7630616bf (HEAD -> master, tag: @ohif/viewer@4.12.9, tag: @ohif/extension-vtk@1.12.9, tag: @ohif/core@2.16.5, origin/master, origin/HEAD)

Trying to build a docker image fails at `yarn install`, see included error messages.

### What steps can we follow to reproduce the bug?

Checkout the repo on a Raspberry Pi 4 and run `docker build .` Error message after `Step 17/31 : RUN yarn install`:

```
...
[5/5] Building fresh packages...
error /usr/src/app/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: /usr/src/app/node_modules/cypress
Output:
Installing Cypress (version: 6.9.1)

[18:40:45]  Downloading Cypress     [started]
[18:40:45]  Downloading Cypress     [failed]
[18:40:45] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/6.9.1?platform=linux&arch=ia32
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: linux (Debian - 9.13)
Cypress Version: 6.9.1
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/6.9.1?platform=linux&arch=ia32
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: linux (Debian - 9.13)
Cypress Version: 6.9.1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1
...
```

This might not be related to Docker as the build simply fails at yarn install. It doesn't look OS-agnostic as it apparently tries to download cypress for ia32. I haven't been able to find a cypress direct download for Arm on the official site.

**Comment by kobuki** [comment]
Well, I succeeded in building for RPi4 4GB. I'm leaving this info here in case anyone is interested.

Changes needed for a successful build:
- remove all cypress references in root `package.json` and in `platform/viewer/package.json` (cypress is for testing only)
- use `--max_old_space_size=2048` in `platform/viewer/package.json` where relevant, to ease memory pressure

I'm leaving a diff here as well. I won't close the issue as some dev might decide to incorporate some workflow or script to handle this type of build.

[ohif-viewer-RPi4-4GB-build-diff.txt](https://github.com/OHIF/Viewers/files/7856996/ohif-viewer-RPi4-4GB-build-diff.txt)

**Comment by kobuki** [comment]
@sedghi: has it been fixed or just closed because of lack of interest in building on the RPi? Both is fine for me as I have a solution, I would just like to know.

**Comment by sedghi** [comment]
It was stale, and you have your solution there for anyone interested in searching it. So that is why
