### ISSUE TITLE
LesionTracker: Error when refresh (F5)

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#266]
Dear All,

Please shared a error.

I got it when refresh (F5) screen while viewing image of LesionTracker module.
It seem login session lost.
![image](https://user-images.githubusercontent.com/12405565/45193801-33d2b000-b27a-11e8-8f32-83b9cca591d1.png)

Thank you,
lam0630

**Comment by swederik** [comment]
It looks like you don't have a server specified. How are you starting the application?

See: https://github.com/OHIF/Viewers/blob/26b14f1dab62ece0232a8c1fae355bac38285695/Packages/ohif-studies/imports/client/lib/retrieveStudyMetadata.js#L47

**Comment by lam0620** [comment]
Hi swederik,

Thank you for your information.
My config has worked smoothly up to now. I also can view image from studylist.
I got the error when F5 at viewer screen ( I got the error much time).
My config file:
[ClearCanvasDIMSE_1.json.txt](https://github.com/OHIF/Viewers/files/2368953/ClearCanvasDIMSE_1.json.txt)

I run "bin\ClearCanvasDIMSE_1.json" at LesionTracker folder

scenario test:
Login(demo drive)-> studylist->viewer(image displaying) -> F5 -> the error occurs

I did debug after clicking a study at studylist
![image](https://user-images.githubusercontent.com/12405565/45333089-74923800-b59e-11e8-9518-2568767959a8.png)

No error occurs.

Did debug after image viewing and click F5, the OHIF.servers.getCurrentServer() return "undefined"
![image](https://user-images.githubusercontent.com/12405565/45332671-2bd97f80-b59c-11e8-9507-e28acbc188e9.png)

lam0620

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

Hopefully you've found your answer since asking. Please don't hesitate to open new issues moving forward ^_^
