### ISSUE TITLE
It is possible to run OHIF on android/ios?

### ISSUE THREAD

**Issue by Med-Rokaimi** [OHIF/Viewers#2663]

**Comment by tonyno-soft** [comment]
I start ohif in windows but I can open the page from mobile browsers, be it chrome, mozilla, safari.

**Comment by sedghi** [comment]
OHIF can be executed on both Android and iOS platforms from a technical standpoint. However, it is important to note that our current layout is not specifically tailored for mobile devices. Nevertheless, we have plans underway to enhance and optimize our mobile support layout in the near future.
