### ISSUE TITLE
OHIF with Orthanc: error loading image + 401 unauthorized + 400 Bad Request

### ISSUE THREAD

**Issue by felixlinxk** [OHIF/Viewers#2667]
Hello! I'm a veterinarian, and I'm configuring our own local PACS system, I'm totally rooky to this so I prefer using docker images and apt tools to setup the PACS.

I used docker image ohif/viewer:latest to deploy the OHIF viewers, and I used "apt install orthanc orthanc-*" to install the orthanc.

Here is the error pages that I have. I did successfully get the studylist showed up, but when I click the specific study, it showed error loading image and the F12 showed 401 unauthorized. When I opened the dicomweb link, it showed 400 Bad Request.

![image](https://user-images.githubusercontent.com/96401924/149976981-7654becb-147f-43a4-823c-266e64a1f9a8.png)

![image](https://user-images.githubusercontent.com/96401924/149977436-9b17089d-ebc5-406c-a00d-293bdbb3c714.png)

![image](https://user-images.githubusercontent.com/96401924/149977517-8c845dda-e3a0-4c45-a1ff-84e11f53dc7b.png)

![image](https://user-images.githubusercontent.com/96401924/149977628-0a2584b9-8565-402c-bbfb-ac9725f8145d.png)

Here is my OHIF app-config.js setting:
![image](https://user-images.githubusercontent.com/96401924/149977735-40884eea-e452-4141-8a0e-912b61279692.png)

Here is my nginx.conf setting:
![image](https://user-images.githubusercontent.com/96401924/149977802-0d222fff-2176-45cd-a627-8cc30bbac923.png)

Here is my dicomweb.json setting:
![image](https://user-images.githubusercontent.com/96401924/149977920-ee2835fc-0ad2-4ebe-a22e-316c99e0e571.png)

I've set the CROS, proxy, authorization... but none of that helps, what should I do next?

**Comment by shravan26** [comment]
Use the latest version of orthanc for this 1.9.7. If you're using the docker-compose file change the version to the one i mentioned. That seemed to do the trick for me. Your configuration seems to be just fine it should work.
