### ISSUE TITLE
How to use OHIF Viewer in Angular project?

### ISSUE THREAD

**Issue by anarnoli** [OHIF/Viewers#2668]
I have an existing Angular project in which I wanted to embed OHIf Viewer. User should select .DCM file from local and view it on screen (as shown in https://v3-demo.ohif.org/local)

Is there any reference example/ document available which can help to take start?

**Comment by anarnoli** [comment]
I got the solution. Basically use /local at end of url and it works. 

Thanks

**Comment by sthomasACR** [comment]
> I got the solution. Basically use /local at end of url and it works.
> 
> Thanks
I also have a similar use case, I would like to know, how you handled it?
How did you add OHIF to your angular project?
> Loading OHIF inside an iframe?
> Adding OHIF as a component in the existing page?

Thanks.

**Comment by anarnoli** [comment]
Yes @sthomasACR 
Embedding OHIF viewer in a component. You may play around this sample https://dicom-json-study.stackblitz.io/local

**Comment by saisandirikrishna** [comment]
hello @anarnoli , iam unable to open the link which you provide above,
iam trying to install OHIF viewer in my Angular project , but not able to do it , how you have done it

**Comment by nicoesiea** [comment]
For the ones interested by the project source code on stackblitz.com, here is the link: https://stackblitz.com/edit/angular-ohif-viewer?file=src%2Fapp%2Fapp.component.ts

**Comment by nicoesiea** [comment]
Finally, I chose to embed the entire application inside an iframe and I load it into my component.
Then I can manage the rendering based on the URL... However, this is a bit frustrating because the entire application is reloaded when I have to change my series...
If there is another way to manage this Series Instance UID somehow else it could be perfect  :(

**Comment by Ahmed-Fathy017** [comment]
Hi guys, I am trying to integrate @ohif/viewer with angular 15 but the documentation is not that good and I am encountering errors. Does anyone have a solution for the problem?

**Comment by Ahmed-Fathy017** [comment]
Hi guys, I am trying to integrate @ohif/viewer with angular 15 but the documentation is not that good and I am encountering errors. Does anyone have a solution for the problem?
