### ISSUE TITLE
TypeError: Cannot set property '_constructUrl' of undefined

### ISSUE THREAD

**Issue by dedman** [OHIF/Viewers#267]
Hey guys, Firstly thanks for the great product and all the hard work that goes into it!

I'm trying to install on new Windows Server 2016 box, and I'm coming up against this error on the current master (2f1a227), when running 'meteor --settings ..\config\orthancDICOMWeb.json' after the initial checkout and meteor npm install. 

W20180907-14:29:26.990(2)? (STDERR) C:\Program Files\OHIF\Viewers\OHIFViewer\.meteor\local\build\programs\server\boot.js:475
W20180907-14:29:26.995(2)? (STDERR) }).run();
W20180907-14:29:26.998(2)? (STDERR)    ^
W20180907-14:29:27.001(2)? (STDERR)
W20180907-14:29:27.002(2)? (STDERR) TypeError: Cannot set property '_constructUrl' of undefined
W20180907-14:29:27.008(2)? (STDERR)     at url_server.js (packages\url.js:24:19)
W20180907-14:29:27.010(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:322:7)
W20180907-14:29:27.011(2)? (STDERR)     at Module.require (packages\modules-runtime.js:224:14)
W20180907-14:29:27.016(2)? (STDERR)     at require (packages\modules-runtime.js:244:21)
W20180907-14:29:27.024(2)? (STDERR)     at packages\url.js:53:15
W20180907-14:29:27.027(2)? (STDERR)     at packages\url.js:60:3
W20180907-14:29:27.031(2)? (STDERR)     at C:\Program Files\OHIF\Viewers\OHIFViewer\.meteor\local\build\programs\server\boot.js:411:36
W20180907-14:29:27.034(2)? (STDERR)     at Array.forEach (<anonymous>)
W20180907-14:29:27.043(2)? (STDERR)     at C:\Program Files\OHIF\Viewers\OHIFViewer\.meteor\local\build\programs\server\boot.js:220:19
W20180907-14:29:27.044(2)? (STDERR)     at C:\Program Files\OHIF\Viewers\OHIFViewer\.meteor\local\build\programs\server\boot.js:471:5

Can anyone point me in the right direction?

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

Please don't hesitate to create new issues or open PRs moving forward ^_^
