### ISSUE TITLE
Add tools to OHIF v2.0

### ISSUE THREAD

**Issue by TheLoFang** [OHIF/Viewers#2670]
Hello, I need your help and please quote, to add the following tools, some of them already present in OHIF v3.0 but I need them for Ohif v2.0

1- Color Presets Tool, Ex: Brain, Spine, Bone, etc.
2- Reference line in the scout view (To see the line on the pilot image in CT and MRI according to the image that the radiologist is viewing.
3- Measurement tools on MPR images for CT and MRI.

Thank you, I look forward to your comments.

**Comment by ArturRod** [comment]
Hi @TheLoFang 
Here is the guide on how it works:
https://tools.cornerstonejs.org/examples/
You need to implement it in your project by touching code.

**Comment by TheLoFang** [comment]
> Hi @TheLoFang Here is the guide on how it works: https://tools.cornerstonejs.org/examples/ You need to implement it in your project by touching code.

Thank you very much @ArturRod, if I could get help on this from some programmer with experience in OHIF it would be very healthy, I would greatly appreciate your services.

**Comment by jensen0914** [comment]
Some of the changes you requested are done in my fork for OHIF v2 on a branch [https://github.com/jensen0914/Viewers/tree/saincepacs-ohif-viewer](https://github.com/jensen0914/Viewers/tree/saincepacs-ohif-viewer) Changes include:

- Showing reference lines (ported from work done in https://github.com/OHIF/Viewers/pull/1482)
- Syncing all viewports to same slice location (can be toggled on/off with new Sync button on toolbar).
- Showing clicked point in other viewports (if available).
- Handling "undisplayable" SOP classes.
- Added a way to define WW/WL "favorites" in the app-configs.js that are accessed using a button on the toolbar that can be different from WW/WL presets set for hotkeys. [Not sure if you meant WW/WL presets when you say "Color" - or maybe you meant color lookup tables?] E.g., 

  wwwlFavorites: [
    { description: 'Abdomen Tissues', window: 400, level: 50 },
    { description: 'Brain', window: 80, level: 40 },
    { description: 'Head/Neck Tissues', window: 375, level: 40 },
    { description: 'Liver', window: 150, level: 30 },
    { description: 'Lung', window: 1500, level: -600 },
    { description: 'Mediastinum', window: 350, level: 50 },
    { description: 'Spine Bone', window: 1800, level: 400 },
    { description: 'Spine Tissues', window: 250, level: 50 },
    { description: 'Temporal Bones 1', window: 2800, level: 600 },
    { description: 'Temporal Bones 2', window: 4000, level: 700 },
  ],

- Open a viewport in full screen with a double click or via button on toolbar.


Todd Jensen, PhD
Jensen Informatics LLC

**Comment by TheLoFang** [comment]
> Some of the changes you requested are done in my fork for OHIF v2 on a branch https://github.com/jensen0914/Viewers/tree/saincepacs-ohif-viewer Changes include:
> 
> * Showing reference lines (ported from work done in [feat: reference lines #1482](https://github.com/OHIF/Viewers/pull/1482))
> * Syncing all viewports to same slice location (can be toggled on/off with new Sync button on toolbar).
> * Showing clicked point in other viewports (if available).
> * Handling "undisplayable" SOP classes.
> * Added a way to define WW/WL "favorites" in the app-configs.js that are accessed using a button on the toolbar that can be different from WW/WL presets set for hotkeys. [Not sure if you meant WW/WL presets when you say "Color" - or maybe you meant color lookup tables?] E.g.,
>   wwwlFavorites: [
>   { description: 'Abdomen Tissues', window: 400, level: 50 },
>   { description: 'Brain', window: 80, level: 40 },
>   { description: 'Head/Neck Tissues', window: 375, level: 40 },
>   { description: 'Liver', window: 150, level: 30 },
>   { description: 'Lung', window: 1500, level: -600 },
>   { description: 'Mediastinum', window: 350, level: 50 },
>   { description: 'Spine Bone', window: 1800, level: 400 },
>   { description: 'Spine Tissues', window: 250, level: 50 },
>   { description: 'Temporal Bones 1', window: 2800, level: 600 },
>   { description: 'Temporal Bones 2', window: 4000, level: 700 },
>   ],
> * Open a viewport in full screen with a double click or via button on toolbar.
> 
> Todd Jensen, PhD Jensen Informatics LLC


Hi Jensen0914,
I would like to be able to talk to you and consult some topics of your possible interest, you could send me an email to: thelofang@gmail.com

Thank you

**Comment by sedghi** [comment]
I think it does makes sense for us to create documentation on how to create new tools. But meanwhile, we have couple of tools that you can inspire from. 

extensions/cornerstone-dicom-sr/src/tools/DICOMSRDisplayTool.ts
extensions/cornerstone/src/tools/ImageOverlayViewerTool.tsx
