### ISSUE TITLE
OHIF working when 'run dev:orthanc' but not when 'build'

### ISSUE THREAD

**Issue by leandersantosm** [OHIF/Viewers#2675]
Hi, I'm facing a weird problem. When I do 'yarn run dev:orthanc' the studylist shows normally, but does not load any thumbnails or images when I open a study (in console it appears as Uncaught (in promise) Error: [object Object]). When I do 'yarn build'  the studylist does not even show, with a message "Error: true" in top-left corner, and this on terminal:

![image](https://user-images.githubusercontent.com/7034086/150413612-09e7d8c5-51ce-4300-8659-a6c763007528.png)

I'm using port 8042 for DICOM, 8080 when building and 3000 when developping, and saving images in AWS S3.

My docker_nginx-orthanc.js:

`
window.config = {
  routerBasename: '/',
  showStudyList: true,
  servers: {
    dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: '/wado',
        qidoRoot: '/dicom-web',
        wadoRoot: '/dicom-web',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
      },
    ],
  },
};
`

I'm using orthanc 1.9.7 (tried many versions) and OHIF local (both version 2 or 3 with same problem), but OHIF version 1 hosted in another server do the job perfectly, showing studies and images. I believe it is some misconfiguration but don't know what.

**Comment by TheScorpoi** [comment]
Hey, I have the same problem. Did you already fix it?
Can you help me?

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

Please try and re-open if the issue persists
