### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by scheiblr** [OHIF/Viewers#2680]
First of all I'd like to thank you for this amazing project!

The React components you released are based and dependent on React 16 of which the last version was released on October 14, 2020. On October 20, 2020, React 17 was released and on March 22, 2021 its latest version. In order to make your components compatible with the most recent version of React and therefore capable of being integrated and used with recent software components outside of the XNAT application. Are there already any plans for such an update?

**Comment by xmhealth** [comment]
+1

**Comment by pwespi** [comment]
It looks like the next version OHIF-v3 will be using React 17, see https://github.com/OHIF/Viewers/blob/v3-stable/platform/ui/package.json#L27-L28

**Comment by scheiblr** [comment]
Thank you for that hint! Does anybody know when that version will be released?

**Comment by Adviser-ua** [comment]
Can you help please with configuration OhifViewer for remote XNAT server

I've create React component with  
```
    ohifViewerConfig = {
servers: {
      dicomWeb: [
        {
          name: 'DCM4CHEE',
          wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado',
          qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
          wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
          qidoSupportsIncludeField: true,
          imageRendering: 'wadors',
          thumbnailRendering: 'wadors',
          enableStudyLazyLoad: true,
        },
      ],
    },
}
    installViewer(ohifViewerConfig, containerId, componentRenderedOrUpdatedCallback);

```
It works, but cant find any example with XNAT server connection
