### ISSUE TITLE
Cannot view entire text string in Debug window

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2698]
I think either there should be a wraparound added to the window, or there should be a horizontal scroll bar. The URL below appears truncated. It can still be selected and copy-pasted, but doesn't look good.

![image](https://user-images.githubusercontent.com/313942/152206766-d1e4e8f6-e1ae-48f0-a0b5-fdbf20bc6b4b.png)

**Comment by Punzo** [comment]
done in https://github.com/OHIF/Viewers/pull/2735
