### ISSUE TITLE
Doctor's note for study

### ISSUE THREAD

**Issue by mdg583** [OHIF/Viewers#27]
Some commercial full-pacs have viewers with the ability for a radiologist and doctors to view and edit a note about a study.

I was wondering if anyone knows what kind of protocol might be used for this kind of functionality. Would it normally just be a custom solution layered on top of a DICOM server + viewer setup? Or is there a special protocol for this? (Such as HL7)

Thanks for any help, I hope it is okay to post this here since I am wondering about whether this feature could exist in the OHIF viewer.

**Comment by mdg583** [comment]
It seems to me this may be a "dicom structured report"

**Comment by swederik** [comment]
We will likely add DICOM Structured Report viewing to the viewer at some point but it is not on the immediate roadmap. As for editing and saving, that is out of the scope of the OHIF Viewer itself and we don't have any plans to add that right now. I'll reopen this if that changes.
