### ISSUE TITLE
I having some problems - Infinite load Invalid prop studies[0].displaySets[0].SeriesNumber 

### ISSUE THREAD

**Issue by ederusena** [OHIF/Viewers#2705]
This is happening to me, in 2 specific studies, I click to view, but getting infinite loading.

I would like to learn how to debug, but I'm new to the ohif viewer and I'm lacking experience.

Warning: Failed prop type: Invalid prop `studies[0].displaySets[0].SeriesNumber` of type `string` supplied to `Viewer`, expected `number`.
    in Viewer (created by WrappedComponent)
    in WrappedComponent (created by ConnectFunction)
    in ConnectFunction (created by ViewerRetrieveStudyData)
    in ViewerRetrieveStudyData (created by ConnectFunction)
    in ConnectFunction (created by ViewerRouting)
    in ViewerRouting (created by Component)
    in Component (created by Context.Consumer)
    in ErrorBoundary (created by OHIFErrorBoundary)
    in OHIFErrorBoundary (created by Context.Consumer)
    in Transition (created by CSSTransition)
    in CSSTransition (created by Context.Consumer)
    in Route (created by OHIFStandaloneViewer)
    in OHIFStandaloneViewer (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(OHIFStandaloneViewer)) (created by Component)
    in Unknown (created by Component)
    in Component (created by App)
    in ModalProvider (created by App)
    in DialogProvider (created by App)
    in SnackbarProvider (created by App)
    in LoggerProvider (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in I18nextProvider (created by App)
    in AppProvider (created by App)
    in Provider (created by App)
    in ErrorBoundary (created by OHIFErrorBoundary)
    in OHIFErrorBoundary (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
printWarning @ checkPropTypes.js:20
checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `studies[0].thumbnails[0].InstanceNumber` of type `string` supplied to `StudyBrowser`, expected `number`.
    in StudyBrowser (created by ConnectFunction)
    in ConnectFunction (created by Viewer)
    in section (created by SidePanel)
    in SidePanel (created by Viewer)
    in ErrorBoundary (created by OHIFErrorBoundary)
    in OHIFErrorBoundary (created by ErrorBoundaryDialog)
    in ErrorBoundaryDialog (created by Viewer)
    in div (created by Viewer)
    in Viewer (created by WrappedComponent)
    in WrappedComponent (created by ConnectFunction)
    in ConnectFunction (created by ViewerRetrieveStudyData)
    in ViewerRetrieveStudyData (created by ConnectFunction)
    in ConnectFunction (created by ViewerRouting)
    in ViewerRouting (created by Component)
    in Component (created by Context.Consumer)
    in ErrorBoundary (created by OHIFErrorBoundary)
    in OHIFErrorBoundary (created by Context.Consumer)
    in Transition (created by CSSTransition)
    in CSSTransition (created by Context.Consumer)
    in Route (created by OHIFStandaloneViewer)
    in OHIFStandaloneViewer (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(OHIFStandaloneViewer)) (created by Component)
    in Unknown (created by Component)
    in Component (created by App)
    in ModalProvider (created by App)
    in DialogProvider (created by App)
    in SnackbarProvider (created by App)
    in LoggerProvider (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in I18nextProvider (created by App)
    in AppProvider (created by App)
    in Provider (created by App)
    in ErrorBoundary (created by OHIFErrorBoundary)
    in OHIFErrorBoundary (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)

**Comment by wanglihuaya** [comment]
I have the same problem

**Comment by 027xiguapi** [comment]
Modify file PanelStudyBrowserTracking.jsx, eidt code
const thumbnailProps = {
      displaySetInstanceUID,
      description: ds.SeriesDescription,
      seriesNumber: Number(ds.SeriesNumber),
      modality: ds.Modality,
      seriesDate: formatDate(ds.SeriesDate),
      numInstances: ds.numImageFrames,
      StudyInstanceUID: ds.StudyInstanceUID,
      componentType,
      imageSrc,
      dragData: {
        type: 'displayset',
        displaySetInstanceUID,
        // .. Any other data to pass
      },
      isTracked: trackedSeriesInstanceUIDs.includes(ds.SeriesInstanceUID),
      viewportIdentificator,
    };

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
