### ISSUE TITLE
View DICOM file stored on Google Drive

### ISSUE THREAD

**Issue by anarnoli** [OHIF/Viewers#2707]
### I'm trying to use OHIF viewer in my scenario.

- My DICOM files are stored on Google Drive
- No DICOM server involved
- No Study list required

Looking at the Static JSON approach which looks like suitable in my case. I prepared a backend server which returns required JSON format for the DICOM file. 

If the image is on AWS S3 then is works fine but when it is on Google Drive (even the file is shared without restriction) it is not working and throws Error loading image error (shown below).

<img width="1440" alt="Screenshot 2022-02-12 at 6 54 29 PM" src="https://user-images.githubusercontent.com/54370515/153714101-059e4ee9-0d37-4ecf-8f46-2d3c3c4bba0e.png">

### Looking for alternate approach

- Is there any feature available in which File directly be passed to the view programmatically? 
- In ```/local``` approach user have to select file while I'm looking if somehow I can pass file path directly to viewer so that viewer can parse file and display. 
- No Static Json generation required.

Appreciating help! Thanks

**Comment by anarnoli** [comment]
@shravan26 I got this [ref](https://github.com/VinayBaviri/ohif-viewer)

**Comment by shravan26** [comment]
So I have files that come in from s3 plugin or orthanc and I want to create json file for each study that comes in. Any idea or suggestions for how to go about this?

**Comment by anarnoli** [comment]
You may need to have a backend service which takes file and generate JSON passing to the OHIF viewer

**Comment by anarnoli** [comment]
@sedghi Do you think you can help me on this problem?

**Comment by sedghi** [comment]
@anarnoli I'm not sure you can get a direct link to a file in Google drive, basically a direct link is a link that when you open it it downloads the file (doesn't go to google drive page). I read somewhere about a trick for dropbox, see [here](https://zapier.com/blog/generate-direct-dropbox-link/)

**Comment by anarnoli** [comment]
Thanks @sedghi.

`/local` provides a way to user for file or folder selection option. Is there any way or configuration available in OHIF Viewer through which either I can provide file/ folder path (local file path) or DICOM file base64?

**Comment by sedghi** [comment]
static-wado is another option if you want to take a look [here](https://v3-docs.ohif.org/configuration/datasources/static-files/)

**Comment by anarnoli** [comment]
@sedghi Let me have a look once again at static-wado. Limitation for me is the Google Drive for DICOM files and it doesn't have direct file link as like AWS S3 or Dropbox.

**Comment by anarnoli** [comment]
@sedghi I tried with static-wado and facing below error. Requesting your help here:

I cloned repo and followed instruction mentioned [here](https://v3-docs.ohif.org/configuration/datasources/static-files/). It generates some data under `dicomweb` folder as shown below:
<img width="290" alt="Screenshot 2022-02-19 at 6 39 46 PM" src="https://user-images.githubusercontent.com/54370515/154802153-0e8a9465-e02b-4507-9e7f-9124d93756e6.png">

Then I ran `npx http-server -p 5001 --cors -g` to run it. While browsing it shows below folders:
<img width="482" alt="Screenshot 2022-02-19 at 6 41 26 PM" src="https://user-images.githubusercontent.com/54370515/154802209-9ea96c7d-4aef-41a4-ad38-e30cbe92bb52.png">

In my app here is the configuration which I entered.
<img width="496" alt="Screenshot 2022-02-19 at 6 42 39 PM" src="https://user-images.githubusercontent.com/54370515/154802261-960d9c5e-bb7c-444d-b40c-bdb9e80aa9f7.png">

**Problem**
When I ran everything, it is shows `No matching result`
<img width="1134" alt="Screenshot 2022-02-19 at 6 44 51 PM" src="https://user-images.githubusercontent.com/54370515/154802377-50b92a9b-796e-4428-9dbe-09d306c01090.png">

Can you please guide what I am doing wrong here?

**Comment by Georift** [comment]
@anarnoli I ran into something similar when trying to serve files staticly. The issue you're facing is because the `npx http-server` package is serving a index.html (as you've screen shot).

Try running the command instead as `npx http-server -p 5001 --cors -g -e json`.

I've opened [a PR](https://github.com/RadicalImaging/Static-DICOMWeb/pull/25) to make this change in the documentation over there.

**Comment by sedghi** [comment]
You can look on how to run OHIF against static assets in 

https://docs.ohif.org/configuration/dataSources/introduction
