### ISSUE TITLE
Differentiation of sequences in a series

### ISSUE THREAD

**Issue by Mamta92** [OHIF/Viewers#2715]
(In the Synedra viewer) There is a series which consists of 125 images, but they are stacked into 5 sequences with 25 images each. You can easily see the cuts when scrolling through the series. There are standard viewing tools that can automatically detect these sequences, e.g. Synedra:
![image](https://user-images.githubusercontent.com/12955134/154719106-416e7566-780a-420d-838c-0390f60bfd23.png)

Wanted to know if OHIF has this feature or it can be enabled? Currently OHIF directly shows 125 images without any sequence differentiator.
![image](https://user-images.githubusercontent.com/12955134/154719185-77dd56b7-471c-4708-af75-6e58e3c291a6.png)

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by sedghi** [comment]
you can write your custom getSOPClassHandler and split images how ever you want
