### ISSUE TITLE
Not able to display PatientName or InstitutionName within in the "ideographic" part of the DICOM tag "00100010"

### ISSUE THREAD

**Issue by felixlinxk** [OHIF/Viewers#2716]
> **Before Creating an issue**
>
> - Are you running the latest version? 
Yes
> - Are you reporting to the correct repository?
Yes
> - Did you search existing issues?
Yes, but no resolution was found.

### Describe the Bug

Both StudyList and Viewer are not able to display PatientName or InstitutionName as long as the SpecificCharacterSet is GB18030, which is a very common character set when it comes to Chinese characters. Besides, the PatientName and InstitutionName are showing "(empty)",  no matter whether the input is In Chinese or not.

A sample DICOM file is provided at the description of bug reproduction.

![Snipaste_2022-02-19_13-43-58](https://user-images.githubusercontent.com/96401924/154788527-8336a67f-faae-4683-bf55-2c14c3961ab5.jpg)

![Snipaste_2022-02-19_13-45-42](https://user-images.githubusercontent.com/96401924/154788529-c839be68-382d-4026-b864-427d60d7cec6.jpg)

![Snipaste_2022-02-19_13-46-15](https://user-images.githubusercontent.com/96401924/154788530-bc12e465-eade-438b-811a-4d361245e0ce.jpg)

![Snipaste_2022-02-19_13-53-46](https://user-images.githubusercontent.com/96401924/154788531-0d343a24-0979-43f6-86d6-8dfcccaff294.jpg)

![Snipaste_2022-02-19_13-54-32](https://user-images.githubusercontent.com/96401924/154788534-93b19594-b5b6-4686-8924-3dc5e8fd9fee.jpg)

![Snipaste_2022-02-19_13-54-52](https://user-images.githubusercontent.com/96401924/154788535-81a1d2e5-aef7-41e7-9572-26d94b264fae.jpg)

### What steps can we follow to reproduce the bug?

1. First step
upload a dicom file with SpecificCharacterSet set to GB18030, then viola!

This is a sample DICOM file with SpecificCharacterSet being GB18030, for who wants to test this, you can download it and have a try.
[sample DICOM with SpecificCharacterSet being GB18030.zip](https://github.com/OHIF/Viewers/files/8101544/sample.DICOM.with.SpecificCharacterSet.being.GB18030.zip)

If you never heard of GB18030 before, this is an illustration of the compatibility of several Chinese codes.
![v2-0d0285e7b9433eeedf7e705d6e082d13_720w](https://user-images.githubusercontent.com/96401924/154852657-962a14ba-0537-4c83-b8a0-55b759bee53c.jpg)

Wait.... I kinda know the reason why...  It seems like OHIF only reads and display the "Alphabetic" part of the PN, and ignoring the "ideographic" part which includes Chinese characters of course. The contents of "ideographic" are Unicode encoding for Chinese characters.

![Snipaste_2022-02-23_11-21-25](https://user-images.githubusercontent.com/96401924/155256715-ab0279a1-f750-424f-ad25-b3ea1803c2e0.jpg)

update...

I've found out that in those DICOM files which can be displayed normally, the chinese characters were recorded within the "Alphabetic" part of the PN value. Maybe this information can help solving this bug?

![Snipaste_2022-02-28_16-20-52](https://user-images.githubusercontent.com/96401924/155949248-5c7e92fd-8bd0-4ec5-bdcc-1c799ed6ec2a.jpg)

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by felixlinxk** [comment]
Here is what I've done to the getName.js

and problem solved!

![image](https://user-images.githubusercontent.com/96401924/157831320-ab0ed4b1-b507-4c7a-bbde-16e796240d8a.png)

![image](https://user-images.githubusercontent.com/96401924/157831407-316efcbf-e403-464c-9ea3-83ccc3e97784.png)

**Comment by bonviesinfo** [comment]
hi could you show other information about modifing code
Value not contain the ideographic word.

**Comment by felixlinxk** [comment]
> 

You can simply add more or modify if statements in the getName.js accordingly.

**Comment by bonviesinfo** [comment]
hi you only add the ideographic code and solve the problem?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
