### ISSUE TITLE
how can I upload DICOM file from modality to viewer.

### ISSUE THREAD

**Issue by Aman1229** [OHIF/Viewers#2719]
Hello everyone.!, I'm working on a PACS project, I want to connect my front-end UI to viewer in doing this I'm facing problem in uploading DICOM images and pdfs, actually I'm unable to figure out from where I should start.

**Comment by felixlinxk** [comment]
The viewer itself does not store DICOM files, you need to upload the files into the database which the viewer accesses, like orthanc or dcm4che, etc.

**Comment by sedghi** [comment]
You need to have a dicomweb setup and OHIF connect to that
