### ISSUE TITLE
thumbnail  loading error on production environment

### ISSUE THREAD

**Issue by jacklau88** [OHIF/Viewers#272]
hi,there is an issue that thumbnail  loading error on production environment,but ok on development environment，how can i fix this issue?

**Comment by swederik** [comment]
Hi there,

We're going to need more information than that to help with any debugging.

What type or archive are you connecting to? Are you using WADO-RS or WADO-URI for the thumbnails?

**Comment by jacklau88** [comment]
Yes, I using the orthancwebconfig.support the wado-rs or wado-uri.the server response 404 error.but viewport loading works fine.
		
		

		获取 Outlook for iOS
	





On Mon, Sep 17, 2018 at 3:55 PM +0800, "Erik Ziegler" <notifications@github.com> wrote:












Hi there,


We're going to need more information than that to help with any debugging.


What type or archive are you connecting to? Are you using WADO-RS or WADO-URI for the thumbnails?

**Comment by swederik** [comment]
Orthanc has an issue with WADO-RS. Switch thumbnail rendering to WADO URI.

**Comment by jacklau88** [comment]
thx a lot.
