### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by ankitsinghrana** [OHIF/Viewers#2721]
For my project, I have been trying to remove some overlay text but is not working. I'm using below code from the documentation.
 
 {
  "overlay": {
    "topLeft": [],
    "topRight": [],
    "bottomRight": [],
    "bottomLeft": []
  }
}

Could you please check?

**Comment by sedghi** [comment]
You can use the customizationService for this https://docs.ohif.org/platform/services/ui/customization-service
