### ISSUE TITLE
Can't load image

### ISSUE THREAD

**Issue by ghost** [OHIF/Viewers#2724]
## Bug Report

I'm using OHIF (Version3) with Orthanc inside of Docker.
And it works fine, mostly.

But there are a few studies, I can't open well as attached.  (shows only black image)
I can open these studies well or show correct image on Orthacn Web Viewer.
I think, study which is send from specific modality, has this issue.

Would you kindly advise me ?

You can download 1 sample study from GoogleDrive as below;
https://drive.google.com/file/d/1tZvG3tX2Yl4bjnKGqtv5rrRunK3TnN-P/view?usp=sharing

![screenshot_ 2022-02-27 225138](https://user-images.githubusercontent.com/71856005/155886547-b42ce46a-34aa-4454-9718-3602b4d791c7.png)

**Comment by sedghi** [comment]
![CleanShot 2023-10-13 at 13 15 00](https://github.com/OHIF/Viewers/assets/7490180/42e10d1f-3599-43ea-b44d-3717f1e976c6)

Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
