### ISSUE TITLE
IDC: Series filtering

### ISSUE THREAD

**Issue by Punzo** [OHIF/Viewers#2736]
Series filter in OHIFv2 when selecting by url ?seriesInstanceUID not always working.

**Comment by Punzo** [comment]
@fedorov for this one simply you need to set  `filterQueryParam: true` in your config file

e.g.: https://github.com/OHIF/Viewers/blob/master/platform/viewer/public/config/default.js#L6

**Comment by fedorov** [comment]
Thank you, I had no idea - obviously.
