### ISSUE TITLE
When a request fail all the series fail

### ISSUE THREAD

**Issue by godinezseba** [OHIF/Viewers#2744]
> **Before Creating an issue**
>
> - Are you running the latest version?
Yes, we are running version ohif/viewer@4.12.19 and Chrome 96.0.4664.110 (in all main operative systems this happens).
> - Are you reporting to the correct repository?
I hope so.
> - Did you search for existing issues?
Yes, I found a couple of issues that look similar (#2581, #2724), but they don’t have answers.

### Describe the **Bug**

Some images sometimes fail to load one or more series. We know it’s not a problem with the radiologist connection because the development team can reproduce the problem. And It’s not a problem with the images because we can open them with Horos and Orthanc.

### What steps can we follow to reproduce the bug?
I don’t think the OHIF team can reproduce the bug, but I hope someone can tell us how to fix it :).

#### 1. We open an image with OHIF. It’s run a server with the next configuration:
In `platform/viewer/public/default.js`:
```js
window.config = {
  routerBasename: '/',
  extensions: [],
  showStudyList: true,
  filterQueryParam: false,
  disableServersCache: false,
  studyPrefetcher: {
    enabled: true,
    order: 'closest',
    displaySetCount: 3,
    preventCache: false,
    prefetchDisplaySetsTimeout: 300000,
    maxNumPrefetchRequests: 100,
    displayProgress: true,
    includeActiveDisplaySet: true,
  },
  servers: {
    dicomWeb: [
      {
        name: 'OURNAME',
        wadoUriRoot: `${ORTHANC_SERVER}/wado`,
        qidoRoot: `${ORTHANC_SERVER}/dicom-web`,
        wadoRoot: `${ORTHANC_SERVER}/dicom-web`,
        qidoSupportsIncludeField: true,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
};
```
And in `platform/core/src/utils/xhrRetryRequestHook.js`:
```js
const defaultRetryOptions = {
  retries: 1000,
  factor: 3,
  minTimeout: 1 * 1000,
  maxTimeout: 60 * 1000,
  randomize: true,
  retryableStatusCodes: [404, 429, 500],
};
```

#### 2. Sometimes a complete series never load:
![image](https://user-images.githubusercontent.com/26770360/157967751-b44def94-d7d4-44c2-9eef-e7c2aa949a2b.png)

As you can see from the image, the image of the series “axial venoso” don’t load and if I click the button, the OHIF viewer doesn’t load the images.

#### 3. And when we open the Chrome console we see the next error and It’s the same with the network tab:
![image](https://user-images.githubusercontent.com/26770360/157967811-cffa4027-8ad1-4536-9b7a-0a0499ea0f1d.png)
![image](https://user-images.githubusercontent.com/26770360/157967840-eacf9bb9-3f9b-458d-97a4-84359f988775.png)

### Our questions

1. As you can see from step 2, we think that if a metadata request fails, all the requests from that series fail, are we right? If we are, What can we change to retry that request?
2. From step 1, What can we change to make more retries?
3. is It necessary to change the `cornerstoneWADOImageLoader` variable?

**Comment by XiDeng** [comment]
Hi,

I also can't load some series of images. But I resolve it by rewrite my url.

My OHIF Viewer runs on https://viewer.org/, for example, and my orthanc server runs on https://viewer.org/dcm/. I set the config of viewer like
`       { ...
        wadoUriRoot："https://viewer.org/dcm/wado"，
        qidoRoot："https://viewer.org/dcm/dicom-web" , 
        wadoRoot : "https://viewer.org/dcm/dicom-web",
        ...}
`
, but I found that the viewer request the bulk via url https://viewer.org/dicom-web/studies/xxxxxxxxx........, and the url miss the '/dcm/' prefix. Then I rewrite the url in the nginx, and the images are loaded correctly. 

I don't know whether we meet the same issue or not, and hope it can help you. : )

**Comment by jorgecaullan** [comment]
hi, after muliple test, I see this happened because some times, some request are getting a status 0 (probably for a overload of the PACs). This causes the viewer failed his series or the full view. Also, the requests messages arent sending again because a `.send()` was required on xhrRequests after the `request.open()`

![image](https://user-images.githubusercontent.com/54674745/162501190-6798b758-ac9b-426b-b6dd-a98e4a466ff6.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
