### ISSUE TITLE
OpenResty-Orthanc-Keycloak docker-compose up --build 

### ISSUE THREAD

**Issue by niepan11** [OHIF/Viewers#2748]
centos 8 .USER is root.The lastest version of OHIF/Viewers at 2022.3.18.
after getting started successfully ,I installed docker and docker-compose according to "https://docs.docker.com/engine/install/centos/".
Then I cd in the .../.recipes/OpenResty-Orthanc-Keycloak
RUN docker-compose up --build

I want to ask if I made mistakes in the process or there is bug in the dockerfile .

the information below:

Step 21/24 : RUN luarocks install lua-resty-openidc
 ---> Using cache
 ---> 450c1334dc5a
Step 22/24 : RUN luarocks install luacrypto
 ---> Running in 2f98bb1850db
Installing https://luarocks.org/luacrypto-0.3.2-2.src.rock
src/lcrypto.c: In function 'digest_pnew':
src/lcrypto.c:81:61: error: invalid application of 'sizeof' to incomplete type 'EVP_MD_CTX' {aka 'struct evp_md_ctx_st'}
   81 |     EVP_MD_CTX *c = (EVP_MD_CTX *)lua_newuserdata(L, sizeof(EVP_MD_CTX));
      |                                                             ^~~~~~~~~~
src/lcrypto.c: In function 'digest_reset':
src/lcrypto.c:120:10: warning: implicit declaration of function 'EVP_MD_CTX_cleanup'; did you mean 'EVP_MD_CTX_create'? [-Wimplicit-function-declaration]
  120 |     if (!EVP_MD_CTX_cleanup(c))
      |          ^~~~~~~~~~~~~~~~~~
      |          EVP_MD_CTX_create
src/lcrypto.c: In function 'encrypt_pnew':
src/lcrypto.c:331:69: error: invalid application of 'sizeof' to incomplete type 'EVP_CIPHER_CTX' {aka 'struct evp_cipher_ctx_st'}
  331 |     EVP_CIPHER_CTX *c = (EVP_CIPHER_CTX *)lua_newuserdata(L, sizeof(EVP_CIPHER_CTX));
      |                                                                     ^~~~~~~~~~~~~~
src/lcrypto.c: In function 'encrypt_fencrypt':
src/lcrypto.c:425:20: error: storage size of 'c' isn't known
  425 |     EVP_CIPHER_CTX c;
      |                    ^
src/lcrypto.c: In function 'decrypt_pnew':
src/lcrypto.c:470:69: error: invalid application of 'sizeof' to incomplete type 'EVP_CIPHER_CTX' {aka 'struct evp_cipher_ctx_st'}
  470 |     EVP_CIPHER_CTX *c = (EVP_CIPHER_CTX *)lua_newuserdata(L, sizeof(EVP_CIPHER_CTX));
      |                                                                     ^~~~~~~~~~~~~~
src/lcrypto.c: In function 'decrypt_fdecrypt':
src/lcrypto.c:561:20: error: storage size of 'c' isn't known
  561 |     EVP_CIPHER_CTX c;
      |                    ^
src/lcrypto.c: In function 'hmac_pnew':
src/lcrypto.c:604:57: error: invalid application of 'sizeof' to incomplete type 'HMAC_CTX' {aka 'struct hmac_ctx_st'}
  604 |     HMAC_CTX *c = (HMAC_CTX *)lua_newuserdata(L, sizeof(HMAC_CTX));
      |                                                         ^~~~~~~~
src/lcrypto.c: In function 'hmac_fnew':
src/lcrypto.c:621:5: warning: implicit declaration of function 'HMAC_CTX_init'; did you mean 'HMAC_CTX_new'? [-Wimplicit-function-declaration]
  621 |     HMAC_CTX_init(c);
      |     ^~~~~~~~~~~~~
      |     HMAC_CTX_new
src/lcrypto.c: In function 'hmac_clone':
src/lcrypto.c:631:10: error: invalid use of incomplete typedef 'HMAC_CTX' {aka 'struct hmac_ctx_st'}
  631 |     *d = *c;
      |          ^
src/lcrypto.c:631:8: error: invalid use of incomplete typedef 'HMAC_CTX' {aka 'struct hmac_ctx_st'}
  631 |     *d = *c;
      |        ^
src/lcrypto.c: In function 'hmac_gc':
src/lcrypto.c:697:5: warning: implicit declaration of function 'HMAC_CTX_cleanup' [-Wimplicit-function-declaration]
  697 |     HMAC_CTX_cleanup(c);
      |     ^~~~~~~~~~~~~~~~
src/lcrypto.c: In function 'hmac_fdigest':
src/lcrypto.c:711:14: error: storage size of 'c' isn't known
  711 |     HMAC_CTX c;
      |              ^
src/lcrypto.c: In function 'sign_pnew':
src/lcrypto.c:747:61: error: invalid application of 'sizeof' to incomplete type 'EVP_MD_CTX' {aka 'struct evp_md_ctx_st'}
  747 |     EVP_MD_CTX *c = (EVP_MD_CTX *)lua_newuserdata(L, sizeof(EVP_MD_CTX));
      |                                                             ^~~~~~~~~~
src/lcrypto.c: In function 'sign_fsign':
src/lcrypto.c:828:20: error: storage size of 'c' isn't known
  828 |         EVP_MD_CTX c;
      |                    ^
src/lcrypto.c: In function 'verify_pnew':
src/lcrypto.c:857:61: error: invalid application of 'sizeof' to incomplete type 'EVP_MD_CTX' {aka 'struct evp_md_ctx_st'}
  857 |     EVP_MD_CTX *c = (EVP_MD_CTX *)lua_newuserdata(L, sizeof(EVP_MD_CTX));
      |                                                             ^~~~~~~~~~
src/lcrypto.c: In function 'verify_fverify':
src/lcrypto.c:940:20: error: storage size of 'c' isn't known
  940 |         EVP_MD_CTX c;
      |                    ^
src/lcrypto.c: In function 'rand_pseudo_bytes':
src/lcrypto.c:992:5: warning: 'RAND_pseudo_bytes' is deprecated [-Wdeprecated-declarations]
  992 |     return rand_do_bytes(L, RAND_pseudo_bytes);
      |     ^~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/err.h:13,
                 from src/lcrypto.c:7:
/usr/include/openssl/rand.h:44:1: note: declared here
   44 | DEPRECATEDIN_1_1_0(int RAND_pseudo_bytes(unsigned char *buf, int num))
      | ^~~~~~~~~~~~~~~~~~
src/lcrypto.c: In function 'pkey_generate':
src/lcrypto.c:1064:9: warning: 'RSA_generate_key' is deprecated [-Wdeprecated-declarations]
 1064 |         RSA *rsa = RSA_generate_key(key_len, RSA_F4, NULL, NULL);
      |         ^~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/err.h:13,
                 from src/lcrypto.c:7:
/usr/include/openssl/rsa.h:235:1: note: declared here
  235 | DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
      | ^~~~~~~~~~~~~~~~~~
src/lcrypto.c:1074:9: warning: 'DSA_generate_parameters' is deprecated [-Wdeprecated-declarations]
 1074 |         DSA *dsa = DSA_generate_parameters(key_len, NULL, 0, NULL, NULL, NULL, NULL);
      |         ^~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/err.h:13,
                 from src/lcrypto.c:7:
/usr/include/openssl/dsa.h:117:1: note: declared here
  117 | DEPRECATEDIN_0_9_8(DSA *DSA_generate_parameters(int bits,
      | ^~~~~~~~~~~~~~~~~~
src/lcrypto.c: In function 'pkey_to_pem':
src/lcrypto.c:1164:27: error: invalid use of undefined type 'struct evp_pkey_st'
 1164 |     if (private && pkey_st->type == EVP_PKEY_DSA)
      |                           ^~
src/lcrypto.c:1165:55: error: invalid use of undefined type 'struct evp_pkey_st'
 1165 |         ret = PEM_write_bio_DSAPrivateKey(mem, pkey_st->pkey.dsa, NULL, NULL, 0, NULL, NULL);
      |                                                       ^~
src/lcrypto.c:1166:32: error: invalid use of undefined type 'struct evp_pkey_st'
 1166 |     else if (private && pkey_st->type == EVP_PKEY_RSA)
      |                                ^~
src/lcrypto.c:1167:55: error: invalid use of undefined type 'struct evp_pkey_st'
 1167 |         ret = PEM_write_bio_RSAPrivateKey(mem, pkey_st->pkey.rsa, NULL, NULL, 0, NULL, NULL);
      |                                                       ^~
src/lcrypto.c: In function 'pkey_tostring':
src/lcrypto.c:1277:60: error: invalid use of incomplete typedef 'EVP_PKEY' {aka 'struct evp_pkey_st'}
 1277 |     sprintf(buf, "%s %s %d %p", LUACRYPTO_PKEYNAME, (*pkey)->type == EVP_PKEY_DSA ? "DSA" : "RSA", EVP_PKEY_bits(*pkey), pkey);
      |                                                            ^~
src/lcrypto.c: In function 'seal_pnew':
src/lcrypto.c:1299:46: error: invalid application of 'sizeof' to incomplete type 'EVP_CIPHER_CTX' {aka 'struct evp_cipher_ctx_st'}
 1299 |     c->ctx = (EVP_CIPHER_CTX *)malloc(sizeof(EVP_CIPHER_CTX));
      |                                              ^~~~~~~~~~~~~~
In file included from src/lcrypto.c:8:
src/lcrypto.c: In function 'seal_tostring':
src/lcrypto.c:1320:81: error: invalid use of incomplete typedef 'EVP_CIPHER_CTX' {aka 'struct evp_cipher_ctx_st'}
 1320 |     sprintf(s, "%s %p %s", LUACRYPTO_SEALNAME, (void *)c, EVP_CIPHER_name(c->ctx->cipher));
      |                                                                                 ^~
src/lcrypto.c: In function 'seal_final':
src/lcrypto.c:1379:80: error: invalid use of incomplete typedef 'EVP_CIPHER_CTX' {aka 'struct evp_cipher_ctx_st'}
 1379 |     lua_pushlstring(L, (const char *)c->iv, (size_t)EVP_CIPHER_iv_length(c->ctx->cipher));
      |                                                                                ^~
src/lcrypto.c: In function 'seal_fseal':
src/lcrypto.c:1400:20: error: storage size of 'ctx' isn't known
 1400 |     EVP_CIPHER_CTX ctx;
      |                    ^~~
src/lcrypto.c: In function 'open_pnew':
src/lcrypto.c:1483:46: error: invalid application of 'sizeof' to incomplete type 'EVP_CIPHER_CTX' {aka 'struct evp_cipher_ctx_st'}
 1483 |     c->ctx = (EVP_CIPHER_CTX *)malloc(sizeof(EVP_CIPHER_CTX));
      |                                              ^~~~~~~~~~~~~~
src/lcrypto.c: In function 'open_tostring':
src/lcrypto.c:1509:20: error: invalid use of incomplete typedef 'EVP_PKEY' {aka 'struct evp_pkey_st'}
 1509 |             (*pkey)->type == EVP_PKEY_DSA ? "DSA" : "RSA", EVP_PKEY_bits(*pkey), pkey);
      |                    ^~
src/lcrypto.c: In function 'open_fopen':
src/lcrypto.c:1602:20: error: storage size of 'ctx' isn't known
 1602 |     EVP_CIPHER_CTX ctx;
      |                    ^~~

Error: Build error: Failed compiling object src/lcrypto.o

luacrypto 0.3.2-2 depends on lua >= 5.1 (5.1-1 provided by VM)
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/lcrypto.c -o src/lcrypto.o -I/usr/include
The command '/bin/sh -c luarocks install luacrypto' returned a non-zero code: 1
ERROR: Service 'ohif_viewer' failed to build : Build failed
[root@vultr OpenResty-Orthanc-Keycloak]#

I also tried ubuntu but issue is not solved.How can I build it successfully?

**Comment by XiDeng** [comment]
Same issue.

**Comment by valentinkv** [comment]
found some workaround by replacing `luacrypto` with `luaossl` on alpine-fat

**Comment by niepan11** [comment]
> found some workaround by replacing `luacrypto` with `luaossl` on alpine-fat

Thank you very much. I replaced luacrypto with luaossl and I built all the docker containers successfully.But it seems that I can't followed the document on https://docs.ohif.org/deployment/recipes/user-account-control.html
I visited the http://127.0.0.1/ and a whole black background was the result.Can you tell me how to configure further?

**Comment by valentinkv** [comment]
> niepan11

can't say right now, i'm playing with `OpenResty-Orthanc` plain recipe, not the Keycloak extension, so for my needs it solved image building issues, but not sure about the rest of functionality...

**Comment by valentinkv** [comment]
found a few issues may be related to black screen
* `ohif-keycloak-realm.json` wasn't loaded
there is some issue with KEYCLOAK_IMPORT functionality, check if `OHIF` realm is available in keycloak admin.
as well you should see log warn like this:
`keycloak  | WARN  [org.keycloak.services] (ServerService Thread Pool -- 59) KC-SERVICES0005: Unable to import realm ohif from file /tmp/ohif-keycloak-realm.json.: java.lang.RuntimeException: Script upload is disabled`

So, if ohif realm wasn't loaded (and not accessible from keycloak admin), it may be solved by fixing the next line in docker-compose.yml:
`KEYCLOAK_IMPORT: /tmp/ohif-keycloak-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled` 

related sw answer: https://stackoverflow.com/a/66518116




* Second issue related to running docker-compose on apple m1. in that case the keycloak admin is not accessible at all (you're getting 404 when accessing admin console)

may be solved like in this comment - rebuilding keycloak image (16.1.0) on mac device
 https://github.com/docker/for-mac/issues/5310#issuecomment-877653653

@niepan11
@ChrisAi89

**Comment by niepan11** [comment]
@valentinkv 
Thank you very much! I have built the containers successfully and the viewer runs well with your help .Now it cannot be accessed remotely and I am trying to revise configuration.I want to add ssl as well.

**Comment by linnengbo** [comment]
I replaced the luacrypto with the luaossl, successfully built the container, and the keycloak was loaded successfully, but it still shows a black screen. Are there any more changes?Does the base image need to be replaced?

**Comment by linnengbo** [comment]
@niepan11 
I replaced the luacrypto with the luaossl, successfully built the container, and the keycloak was loaded successfully, but it still shows a black screen. Are there any more changes?Does the base image need to be replaced?

**Comment by niepan11** [comment]
Follow valentinkv's guide,then you need visit 127.0.0.1 directly,but not remotely. @linnengbo

**Comment by linnengbo** [comment]
@niepan11 
Thanks, my local server have no desktop mode to test 127.0.0.1 successfully, do you have implemented remote mode now?

**Comment by Hasan-aga** [comment]
I am getting the same problem, did you find a solution for this?

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
