### ISSUE TITLE
ConfigPoint theme doesn't respect PUBLIC_URL

### ISSUE THREAD

**Issue by j6u** [OHIF/Viewers#2753]
### Bug description
Theme url is hardcoded and doesn't reflect PUBLIC_URL change

### Repro

1. Set PUBLIC_URL environment variable and run yarn build
2. Load the viewer
3. Observe everything works except for the theme.json5 load since it is hardcoded to /theme/theme/json5

```js
ConfigPoint.load(defaultTheme, '/theme', 'theme');
```

**Comment by sedghi** [comment]
config point is removed from the application. Please re-try again on master and re-open the issue if necessary
