### ISSUE TITLE
Fails to ```yarn install```

### ISSUE THREAD

**Issue by vshkolyar** [OHIF/Viewers#2755]
### Describe the Bug

_Executing quick start tutorial for developer failing to ```yarn install```"._

### What steps can we follow to reproduce the bug?

OS: latest MacOS

1. Execute the quick start tutorial.
2. For installing node.js and yarn user brew.
3. The ```yarn install``` step gives the following wanting and error:

```js
(base) shkolyar@SPB Viewers % yarn install
yarn install v1.22.18
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "@babel/runtime@7.16.3" is incompatible with requested version "@babel/runtime@7.7.6"
warning Resolution field "@babel/runtime@7.16.3" is incompatible with requested version "@babel/runtime@7.1.2"
warning Resolution field "@babel/runtime@7.16.3" is incompatible with requested version "@babel/runtime@^7.16.7"
[3/5] 🚚  Fetching packages...
error @npmcli/fs@1.1.0: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16". Got "14.8.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by elamathis18** [comment]
Hi, I had the same issue, I had to switch to node v14.15.0 as mentioned in the error which resolved the issue.

**Comment by seandoyle** [comment]
Same issue - changed dockerfile from 

`FROM node:12.22.1-slim as builder`
to
`FROM node:14-slim as builder`
and the application started as expected.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
