### ISSUE TITLE
Investigate failure to display segmentations for the NSCLC-Radiogenomics collection in IDC

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2761]
Example (pointing to the sandbox, since the prod viewer is outdated): https://idc-sandbox-000.firebaseapp.com/projects/canceridc-data/locations/us/datasets/idc/dicomStores/v7/study/1.3.6.1.4.1.14519.5.2.1.4334.1501.116796918629271881210561198785

**Comment by Punzo** [comment]
fixed in https://github.com/OHIF/Viewers/pull/2768
