### ISSUE TITLE
Investigate failure to display images for the pdmr_292921_168_r collection in IDC

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2762]
Demonstration: https://viewer.imaging.datacommons.cancer.gov/viewer/2.25.302663032735478633565561232177315735711

![image](https://user-images.githubusercontent.com/313942/160893452-4f5f6ed4-c04a-4ed7-81dc-a5d22c50372f.png)

**Comment by fedorov** [comment]
Upon further investigation, the series in question is an instance of [Raw Data IOD](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.37.html) (per `SOPClassUID`). 

I suggest this should be handled better in OHIF by 1) considering SOPClassUID in determining whether a given series is supported; 2) revising the error message - the declared modality in this instance is MR, and the current message is misleading.

**Comment by Punzo** [comment]
fixed in https://github.com/OHIF/Viewers/pull/2770
