### ISSUE TITLE
Failure to render segmentation series - IDC PROSTATEx

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2765]
I am pretty sure this worked in the past, and in any case - it fails without any error indication to the user. Series thumbnail on the left indicates linked seg, segmentation tab shows 2 segmentations, but selector is blank.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/313942/161178050-db158546-1fe5-4468-af75-114017d58b6f.png">

https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.7311.5101.194134898179466672796385912287

I am sure this was working at some point in the past.

This is confirmed to fail in 4.12.17, but also in 4.12.23.

**Comment by fedorov** [comment]
> setActiveLabelMap.js:23 Source Image Sequence information missing: individual SEG frames are out of plane. This is not yet supported. Aborting segmentation loading.

I am pretty sure those studies in PROSTATEx have 2 segmentations, one of which is out of plane and should not work, but should give an error to the user, and should also have a warning icon near the series thumbnail. But I am pretty sure the other one was working fine in the past.

**Comment by Punzo** [comment]
fixed in https://github.com/OHIF/Viewers/pull/2768
