### ISSUE TITLE
OHIF v3 not working if served from non root folder

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#2769]
Hi there, 

I'm trying to build OHIF v3, i'm taking the source code from v3-stable branch,
When i follow the build instruction `yarn run build` and serve the build form the root folder of my HTTP server, it is OK

But when I try to serve OHIF from the non root folder, for instance an "ohif" sub folder of the root http server,
I build using `PUBLIC_URL=/ohif/ yarn run build`
OHIF is build, but the serving of the build from http://server/ohif lands on a blank page. 

By inspecting the DOM and the js console, I see the index.html being served, I see Cornerstone Tools instanciated but the viewer initialization seems to fail (without very explicit error message)

Did anyone succeeded to serve OHIF outside the web server root folder ? 

Salim

**Comment by salimkanoun** [comment]
my report is similar to #2695
(but only for v3. For the v2 build from non root folder are OK)

**Comment by stackp** [comment]
Hi, I am running into the same issue on v3-stable. Only a blank page is shown, with no errors in the console or network tab.

Quick way to reproduce the issue:
```
PUBLIC_URL=/ohif/ yarn run build
mkdir -p /tmp/web/ohif && cp -r platform/viewer/dist/* /tmp/web/ohif/
npx http-server /tmp/web -o /ohif
```

While it works fine without PUBLIC_URL:
```
yarn run build
mkdir -p /tmp/web2 && cp -r platform/viewer/dist/* /tmp/web2/
npx http-server /tmp/web2 -o /
```

**Comment by fgjruiz** [comment]
Thank you Pierre and Erik.  I can confirm that the OHIF v3-stable branch is now working correctly off a non root folder when the PUBLIC_URL is set.  I am running OHIF off of IIS, talking to static-wado.

**Comment by sylvainb31** [comment]
@fgjruiz Hi, I am struggling to make OHIF work off of IIS.
Once the project built using yarn run build. I tried to host it via IIS. I started a website in IIS, with the physical location pointing to the dist folder with a custom web.config file but it doesn't work.
Do you think you could share with me your configuration ?
Thanks a lot :)

**Comment by frankievvh** [comment]
> @fgjruiz Hi, I am struggling to make OHIF work off of IIS. Once the project built using yarn run build. I tried to host it via IIS. I started a website in IIS, with the physical location pointing to the dist folder with a custom web.config file but it doesn't work. Do you think you could share with me your configuration ? Thanks a lot :)

What DICOMweb PACS are you trying to run OHIF off of?  The issue here was because we were trying to run OHIF off of an IIS subdirectory.  In my case /ohif .  You also have CORS to worry about for you to get OHIF to run.  The IIS configuration is more dependent on the DICOMweb PACS you are trying to talk to than anything else.

**Comment by fgjruiz** [comment]
> @fgjruiz Hi, I am struggling to make OHIF work off of IIS. Once the project built using yarn run build. I tried to host it via IIS. I started a website in IIS, with the physical location pointing to the dist folder with a custom web.config file but it doesn't work. Do you think you could share with me your configuration ? Thanks a lot :)

What DICOMweb PACS are you trying to run OHIF off of? The issue here was because we were trying to run OHIF off of an IIS subdirectory. In my case /ohif . You also have CORS to worry about for you to get OHIF to run. The IIS configuration is more dependent on the DICOMweb PACS you are trying to talk to than anything else.

**Comment by sylvainb31** [comment]
@fgjruiz 
The problem was coming from my web.config file.
I had to install the URL Rewrite module for it to work correctly and now everything works fine !
Thanks for answering :)
