### ISSUE TITLE
Not able to connect to dcm4chee DICOM Archive 5 light

### ISSUE THREAD

**Issue by m4mehdi** [OHIF/Viewers#2774]
Hi
I installed dcm4chee-arc-light in Ubuntu server which I've installed OHIF v-3.
I configured default.js as below
        wadoUriRoot: 'http://MyIP:8080/dcm4chee-arc/aets/DCM4CHEE/wado',        
	qidoRoot: 'http://MyIP:8080/dcm4chee-arc/aets/DCM4CHEE/rs',        
	wadoRoot: 'http://MyIP:8080/dcm4chee-arc/aets/DCM4CHEE/rs',
but in main page of OHIF only loading image is shown. By changing the urls to default dcmjs, studies will be available.
I tried to check if queries in localhost is working with curl command and  studies retrieve and there no issue to connect dcm4chee from url or postman. I think the issue is related to configuration file,
I am using latest vestion of OHIF, and dcm4chee DICOM Archive 5 light. I will appreciate any help
I got the error in console. Uncaught (in promise) TypeError: modalities.Value is undefined ,getModalities.js:15
It can retreive the studies, but there is problem in showing them because of modalities. I don't understand the error

**Comment by tantee** [comment]
I have the similar issue after upgrade dcm4chee-arc-light to version 5.26. I used latest OHIF v3-stable branch.
Main page showed only loading image. when looking at console there is a error like this.

getModalities.js:15 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at getModalities (getModalities.js:15:30)
    at qido.js:58:11
    at Array.forEach (<anonymous>)
    at Nu (qido.js:46:15)
    at index.js:116:18
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Nl (StaticWadoClient.js:10:22)
    at o (StaticWadoClient.js:10:22)

**Comment by tantee** [comment]
https://groups.google.com/g/dcm4che/c/ECOC6CisVyI

**Comment by m4mehdi** [comment]
I got the error in console. Uncaught (in promise) TypeError: modalities.Value is undefined ,getModalities.js:15
It can retreive the studies, but there is problem in showing them because of modalities. I don't understand the error

**Comment by m4mehdi** [comment]
> https://groups.google.com/g/dcm4che/c/ECOC6CisVyI

Thank you, but error is for version 3.0 and solution you mentioned is for version 1.0.

**Comment by tantee** [comment]
It's seem that v3 does not respect "qidoSupportsIncludeField" in config. please look at file extensions/default/src/DicomWebDataSource/qido.js in branch v3-stable.

**Comment by stinger0698** [comment]
has anyone figured out how to solve this problem?

**Comment by Sergio-P** [comment]
facing the same issue, any solution for this?

**Comment by stinger0698** [comment]
> facing the same issue, any solution for this?

worked with local orthanc server

**Comment by allisonbertrandsa** [comment]
I have some 3rd party anonymized files that don't have the modality tag (0008,0060) at all.  When I tried to load them with OHIF, I had similar results to what is reported here (study list would not display).  I was able to work around this and load the files with the following change, so maybe it will help others.  Of course, I acknowledge these files do not comply with the standard.

`$ git diff
diff --git a/platform/core/src/DICOMWeb/getModalities.js b/platform/core/src/DICOMWeb/getModalities.js
index 9d124f59b..46d69efb4 100644
--- a/platform/core/src/DICOMWeb/getModalities.js
+++ b/platform/core/src/DICOMWeb/getModalities.js
@@ -2,7 +2,9 @@ export default function getModalities(Modality, ModalitiesInStudy) {
   if (!Modality && !ModalitiesInStudy) {
     return {};
   }
-
+  if (!ModalitiesInStudy.Value) {
+    return {};
+  }
   const modalities = Modality || {
     vr: 'CS',
     Value: [],
`

**Comment by mokbelt** [comment]
I have the same issue. Even if the Study has Modality tag value present on (0008,0060), it is giving this error.
I am using dcm4chee-arc-light ver 29.0.
Anybody was able to resolve it?

**Comment by mrtesloni** [comment]
I have the same issue. Next patch I use to fix it. 

diff --git a/platform/core/src/DICOMWeb/getModalities.js b/platform/core/src/DICOMWeb/getModalities.js
index 9d124f59b..0ce94f3e5 100644
--- a/platform/core/src/DICOMWeb/getModalities.js
+++ b/platform/core/src/DICOMWeb/getModalities.js
@@ -2,7 +2,12 @@ export default function getModalities(Modality, ModalitiesInStudy) {
   if (!Modality && !ModalitiesInStudy) {
     return {};
   }
-
+  if (!ModalitiesInStudy.Value) {
+    return {};
+  }
+if (!Modality.Value) {
+  Modality.Value = [];
+}
   const modalities = Modality || {
     vr: 'CS',
     Value: [],

**Comment by sedghi** [comment]
we have local_dcm4chee configuration that you can use
