### ISSUE TITLE
series automatically download

### ISSUE THREAD

**Issue by ramonsousa89** [OHIF/Viewers#278]
Hello,

I wonder if there is a possibility to load the other series automatically?
Because when we play a series of images in the viewer, it does not automatically load the following series.

Load all the series automatically

**Comment by swederik** [comment]
Sounds like you're talking about prefetching. I don't think we have a setting for that. You can try the Prefetch settings:

https://github.com/OHIF/Viewers/blob/33755f7b8b92e33dd45974315fb6c7fe779df8f8/Packages/ohif-servers/both/schema/servers.js#L212

https://github.com/OHIF/Viewers/blob/e55e2ad05ad784ce3899378d438fbc198e6cf2da/StandaloneViewer/SampleClientOnlyBuild/index.html#L23
