### ISSUE TITLE
Single Ultrasound Cine DICOM

### ISSUE THREAD

**Issue by sulaimanvesal** [OHIF/Viewers#2780]
Hi, I have a dataset of TRUS DICOM images, that is for prostate. These are single images but a 3D TRUS cine loop. When I load them into OHIF, the viewer is not able to traverse through different slices and it shows only the first slice. 

Any idea on how to make this work:

![image](https://user-images.githubusercontent.com/20819071/163015836-cf8cdd9a-cfe9-4280-9903-247f3545d812.png)

**Comment by olivert1969** [comment]
experiencing the exact same issue 

? related to https://github.com/OHIF/Viewers/issues/2194 discussed by @richsmith123 and @PoyangLiu 
 
FYI @alvinak

**Comment by sulaimanvesal** [comment]
Any update on this?

**Comment by olivert1969** [comment]
just saw #2799 reported by @adityapol1058 on version 4.12.18
@sulaimanvesal which version were you using?
We experienced same issue on v3-stable

**Comment by sulaimanvesal** [comment]
I am using version 3.2.0.

**Comment by olivert1969** [comment]
confirming issue resolved in latest build of v3-stable
