### ISSUE TITLE
 Cannot read properties of undefined (reading 'getSeriesByUID') on StudyPrefetcher

### ISSUE THREAD

**Issue by arturojain** [OHIF/Viewers#2782]
_When loading a study StudyPrefetcher throws the following error when loading each image: `Cannot read properties of undefined (reading 'getSeriesByUID')`._

### What steps can we follow to reproduce the bug?

1. Enable StudyPrefetch in `config.json`
2. Load a study using JSON as a source

### Findings:

It appears `cornerstone.metaData.get` always returns `undefined`.

**Comment by sedghi** [comment]
We are planning to reintroduce the study prefetcher. I will proceed with its implementation. https://github.com/OHIF/Viewers/issues/3363
