### ISSUE TITLE
Can I use this in Angular 4?

### ISSUE THREAD

**Issue by ashishvadhwa** [OHIF/Viewers#2783]
I have an angular 4 application in which i want to display DICOM study file using OHIF viewer. My DICOM study file will be on Google Healthcare. Can anyone please help me out that how can i use it in my angular application

**Comment by sedghi** [comment]
I think you can use an iframe to do the trick 

In OHIf v3, you can make use of `iframe`

https://docs.ohif.org/deployment/cors/#embedding-ohif-in-an-iframe
