### ISSUE TITLE
Add support for qualitative slice-level SR annotations

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2797]
## Request

One kind of annotations that is quite common in practice is used to describe a qualitative property of the image at the series or instance level. For example, this kind of annotations can be used to indicate whether specific image slice contains some finding or not or describe the quality of the image. DICOM allows capturing such annotations in SR using TID 1500, specifically using its subordinate template [TID 1501](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#sect_TID_1501) rows 1, 10b and 11. 

We would like to see support for instance-level image annotations implemented in OHIF Viewer. This would mean that in the situation where a TID 1500 instance is encountered in a study, and that instance includes TID 1501 content pattern as in example below ("Measurement group" container that contains one or more IMAGE content item, and CODE content items), the values of the CODE content items are shown as image annotations. Those annotations could be shown as key:value labels in the bottom of the image view, only for the instances specified. For the example below, this would show "Target Region: Neck". A tooltip can be used to show Code/CodingSchemeDesignator for the CodeValues shown.

```text
<CONTAINER:(,,"Imaging Measurement Report")=CONTINUOUS>
  <has concept mod CODE:(,,"Language of Content Item and Descendants")=(en-US,RFC5646,"English (United States)")>
  <has obs context CODE:(,,"Observer Type")=(121006,DCM,"Person")>
  <has obs context PNAME:(,,"Person Observer Name")="Anonymous^Reader">
  <has concept mod CODE:(,,"Procedure reported")=(363679005,SCT,"Imaging procedure")>
  <contains CONTAINER:(,,"Image Library")=CONTINUOUS>
  <contains CONTAINER:(,,"Imaging Measurements")=CONTINUOUS>
    <contains CONTAINER:(,,"Measurement Group")=CONTINUOUS>
      <has obs context TEXT:(,,"Tracking Identifier")="Annotations group x">
      <has obs context UIDREF:(,,"Tracking Unique Identifier")="1.2.826.0.1.3680043.8.498.11346640510041906666146760516895890504">
      <contains CODE:(,,"Target Region")=(69536005,SCT,"Head")>
      <contains CODE:(,,"Target Region")=(45048000,SCT,"Neck")>
      <contains IMAGE:(,,"Source")=(CT image,)>
```

**Why should we prioritize this feature?**
* this feature is needed to display results of analysis for one of the IDC use cases
* this feature will be applicable for a variety of other tasks and datasets that contain or will contain qualitative annotations, and are expected to be in IDC

Here is the example CT series and corresponding annotations in DICOM SR: https://www.dropbox.com/s/v1bz77e4nmqpa9n/Qualitative_annotation_sample.zip?dl=0

**Comment by pieper** [comment]
> * this feature is needed to display results of analysis for one of the IDC use cases

Can you elaborate on which use case and what the annotation would look like?

**Comment by fedorov** [comment]
The use case is automatic detection of body part examined in the image (using this tool: https://github.com/mic-dkfz/bodypartregression). @deepakri201 is working on producing those analysis results. The annotation would look like a set of key:value labels in the bottom of the image view, only for the instances specified. For the attached, this would show "Target Region: Neck" (and "Target Region: Head", actually - since there are two annotations for that one slice).

**Comment by Punzo** [comment]
implemented in https://github.com/OHIF/Viewers/pull/2822

https://user-images.githubusercontent.com/7985338/173572053-cf9770ee-b034-48d2-bc08-d01405972333.mp4

**Comment by fedorov** [comment]
Thank you for reporting this @deepakri201!

@Punzo would be great if you could look into this.

**Comment by Punzo** [comment]
> Hi,
> 
> I'm trying to view the per slice level annotation as discussed above. With 1 annotation, the label is correct (e.g. `target region : head`). However, with 2 or more annotations, the labels are repeated for the slice (e.g. `target region : head` `target region : neck` `target region : head` `target region : neck`. I noticed that this issue seems to occur for the previous sample dataset as well (in the video 4 labels appear in a slice when only 2 should).
> 
>  slice_level_annotation_issue.mp4 
> I've provided an example CT series and the corresponding SR I have created to demonstrate this issue here: https://www.dropbox.com/scl/fo/glt3oimzw1v18mtwp1hr0/h?dl=0&rlkey=2gcdmitl5tqo2isdrh3g2zm4q
> 
> Thank you,
> 
> Deepa

Hi @deepakri201, thanks for reporting! Indeed it was a smalll bug when parsing the DICOM SR info into the measurements system. Fixed in https://github.com/OHIF/Viewers/pull/2830

@fedorov IDC fork already updated to 4.12.28 in https://github.com/ImagingDataCommons/Viewers/pull/144

**Comment by deepakri201** [comment]
Hi, 

Thank you for making the fix! I discovered another issue though -- in the above dataset I shared, on one slice there should be a single label `target region : head`, and on the second slice `target region : head` `target region : neck` . It seems that there are 3 measurements listed though, when there should only be 2, where the second slice+labels are repeated. 

The SR is in the dropbox folder linked above -- perhaps I made a mistake with the encoding. 

https://user-images.githubusercontent.com/59979551/176215533-957dd81b-dcd5-4e55-bb7c-55d293ce5480.mp4

**Comment by Punzo** [comment]
> Hi,
> 
> Thank you for making the fix! I discovered another issue though -- in the above dataset I shared, on one slice there should be a single label `target region : head`, and on the second slice `target region : head` `target region : neck` . It seems that there are 3 measurements listed though, when there should only be 2, where the second slice+labels are repeated.
> 
> The SR is in the dropbox folder linked above -- perhaps I made a mistake with the encoding.
> 
>  slice_level_annotation_issue_06_28_22.mp4

ok I am fixing it!

**Comment by Punzo** [comment]
@deepakri201 @fedorov UI improvements and bug fixes done in https://github.com/OHIF/Viewers/pull/2832. 

IDC fork updated to 4.12.29 in https://github.com/ImagingDataCommons/Viewers/pull/145


video:
https://user-images.githubusercontent.com/7985338/176336810-ce876610-5ddf-4323-b559-136b65380c3b.mp4

**Comment by fedorov** [comment]
Very nice Davide, thank you! I see you also updated `OHIF:IDC2servers` 👍

**Comment by Punzo** [comment]
> Very nice Davide, thank you! I see you also updated `OHIF:IDC2servers` 👍

Yes !

**Comment by fedorov** [comment]
I think it is all good, closing!

**Comment by fedorov** [comment]
Ah, one more little thing - would it make sense to add the chain link icon to the series that is accompanied by the SR instance? 

![image](https://user-images.githubusercontent.com/313942/176583563-7fe350fd-b5e5-4816-9370-2818daec639a.png)

**Comment by Punzo** [comment]
Done in https://github.com/OHIF/Viewers/pull/2834

IDC fork updated to v 4.12.30 in: https://github.com/ImagingDataCommons/Viewers/pull/146

IDC fork `IDC2servers` updated as well

https://user-images.githubusercontent.com/7985338/176648217-d8092c73-3fec-4859-8d5e-b23377d1fa02.mp4
