### ISSUE TITLE
CINE mode not working for Multiframe DICOM images

### ISSUE THREAD

**Issue by adityapol1058** [OHIF/Viewers#2799]
I am using the "4.12.18" version of OHIF viewer for viewing DICOM studies, series and images, and I came across an issue where multi-frame images are not being correctly rendered. I am using the JSON supplied via the '?url=' query parameter to render the images. 

<img width="959" alt="ohifMultiFrame" src="https://user-images.githubusercontent.com/37020118/167864823-3d397d87-3731-48f8-9596-76b3983351ec.PNG">

please note that the number of frames are 63 in above image but it shows only one frame.
@vicOnGit75 @dannyrb @swederik

**Comment by adityapol1058** [comment]
> I am using the "4.12.18" version of OHIF viewer for viewing DICOM studies, series and images, and we came across an issue where multi-frame images are not being correctly rendered. I am using the JSON supplied via the '?url=' query parameter to render the images. <img alt="ohifMultiFrame" width="959" src="https://user-images.githubusercontent.com/37020118/167864823-3d397d87-3731-48f8-9596-76b3983351ec.PNG"> please note that the number of frames are 63 in above image

**Comment by RoshniPal** [comment]
Any solution on this ?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by phoenixsac** [comment]
@adityapol1058 Can you please let me know how you fixed this issue? I am using the dicom-json-generator.js script to get the json for a multi-frame dicom and the url is as -

"url": "dicomweb:http://localhost:8080/dicom-files/fcfce428_0002.DCM?frame=96"

But i only have a single dicom (.dcm) file, do i need to extract frames from this and store it under a folder?
When I pass the url into the ohif viewer - https://viewer.ohif.org/viewer/dicomjson?url=http://localhost:8080/dicom-files/LIDC-IDRI-0001.json
the number of frames shows up as 96, but only a single dcm file is being displayed. 
Any suggestion or workaround would be really helpful.

**Comment by keyhooon** [comment]
i have same problem, i dont know how this is fixed????
