### ISSUE TITLE
daterangepicker gives error regarding moment.js

### ISSUE THREAD

**Issue by mdg583** [OHIF/Viewers#28]
The daterangepicker in the worklist page was giving me an error regarding moment.js. I had to add api.use('momentjs:moment'); to Packages/worklist/package.js to make it work.

**Comment by swederik** [comment]
Heh I literally just ran into this error as well. I'll push a fix soon, just trying to reconcile the designUpdate branch with changes to the OHIF Viewer first.

**Comment by mdg583** [comment]
Also, the datepicker search wasn't working, since new Date(studyDateTo).setHours(0,0,0,0) doesn't return a Date object. I had to make 2 new variables before the condition. (About line 155)
