### ISSUE TITLE
Study List

### ISSUE THREAD

**Issue by davidi1** [OHIF/Viewers#280]
Hello, I noticed a small bug. On the study list page, if you change the "Study Date" field to a different date, load a study and then click on "Study List" (located in the top left corner, next to the OHIF Logo). You will get taken back to the Study List page, however, OHIF is not showing the correct study list for the date in the "Study Date" box.

For example, in the screenshot you can see that the Study List is not reflecting the proper date that is in the "Study Date" field. This only seems to happen after I load a study and then click on "Study List" to go back to the study list.

![2018-09-25](https://user-images.githubusercontent.com/36856675/46025889-f5315800-c0b7-11e8-98ff-a32e60df1441.png)

I hope this makes sense.

**Comment by swederik** [comment]
Hmm that is weird. Thanks for the report!

**Comment by dannyrb** [comment]
Unfortunately this issue has grown stale, and with the release of our most recent major version, it is unlikely that we will have the bandwidth to address this issue for our `v1.x` branch. 

If you find that this feature has not yet been implemented in our `master` branch, you are more than welcome to create a [GitHub Issue](https://github.com/OHIF/Viewers/issues/new) to request or discuss it. If you're curious to see what we have planned in the near future, you can [check out our roadmap](https://ohif.canny.io/), and [read our docs](https://docs.ohif.org/).

FWIW, This issue does not appear to exist in our `master` branch (https://docs.ohif.org/demo/)
