### ISSUE TITLE
Blank Black screen when pionted to dcm4chee server

### ISSUE THREAD

**Issue by cunninghamb505** [OHIF/Viewers#2809]
When pointing app-config.js to dcme4chee server, the page loads all black and blank. I can see via inspect below i see my study but doesnt show in page, just black. 

- I am running OHIF in docker [ohif/viewer:v2.11.8.7749]

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12199633/169390201-c09b0e02-b3bf-4c39-b68e-7cd5cff6c46a.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12199633/169568522-f0f622c6-58bc-4b04-82bc-b9e51d689228.png">

snipit of my app-config.js

 servers: {
    dicomWeb: [
      {
        name: 'DCM4CHEE',
        wadoUriRoot: 'http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/wado',
        qidoRoot: 'http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs',
        wadoRoot: 'http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },

running latest dcm4chee versions on their docker-compose sample

**Comment by cubanitoalex** [comment]
change qidoSupportsIncludeField: true, to qidoSupportsIncludeField: false,   work for me.

**Comment by cunninghamb505** [comment]
Thank you. !, looks like that worked !
