### ISSUE TITLE
Measurement save / retrieve not working against Orthanc

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#282]

**Comment by malaterre** [comment]
FYI
```

message: "Cannot read property 'getTID300RepresentationArguments' of undefined"
stack: "TypeError: Cannot read property 'getTID300RepresentationArguments' of undefined↵    at http://localhost:3000/packages/ohif_cornerstone.js?hash=047fe52b1ad920e26f25f4509a7425dad91b0d64:41653:789661↵    at http://localhost:3000/packages/ohif_cornerstone.js?hash=047fe52b1ad920e26f25f4509a7425dad91b0d64:41653:789760↵    at Array.map (<anonymous>)↵    at s (http://localhost:3000/packages/ohif_cornerstone.js?hash=047fe52b1ad920e26f25f4509a7425dad91b0d64:41653:789612)↵    at http://localhost:3000/packages/ohif_cornerstone.js?hash=047fe52b1ad920e26f25f4509a7425dad91b0d64:41653:790414↵    at Array.forEach (<anonymous>)↵    at http://localhost:3000/packages/ohif_cornerstone.js?hash=047fe52b1ad920e26f25f4509a7425dad91b0d64:41653:790388↵    at Array.forEach (<anonymous>)↵    at Function.value (http://localhost:3000/packages/ohif_cornerstone.js?hash=047fe52b1ad920e26f25f4509a7425dad91b0d64:41653:790139)↵    at retrieveDataFromMeasurements (http://localhost:3000/packages/ohif_measurement-table.js?hash=771d956e53405b1a2af8796cd5ef2741747d6275:1108:36)"
__proto__: Error
```

**Comment by swederik** [comment]
Oops, looks like a dcmjs issue. I will take a look at this post-RSNA

**Comment by viss3595** [comment]
@swederik 

When i saving measurements it's throwing error popup "An error has occurred". 

![Screenshot (2)](https://user-images.githubusercontent.com/22858445/55320211-36098f80-5494-11e9-8379-688fc5d9dfba.png)

**"Cannot read property 'getTID300RepresentationArguments' of undefined"**

"TypeError: Cannot read property 'getTID300RepresentationArguments' of undefined
    at http://localhost:3000/packages/ohif_cornerstone.js?hash=a6c08303a6192f2dae9b644caff736f21eee02a5:42007:789661
    at http://localhost:3000/packages/ohif_cornerstone.js?hash=a6c08303a6192f2dae9b644caff736f21eee02a5:42007:789760
    at Array.map (<anonymous>)
    at s (http://localhost:3000/packages/ohif_cornerstone.js?hash=a6c08303a6192f2dae9b644caff736f21eee02a5:42007:789612)
    at http://localhost:3000/packages/ohif_cornerstone.js?hash=a6c08303a6192f2dae9b644caff736f21eee02a5:42007:790414
    at Array.forEach (<anonymous>)
    at http://localhost:3000/packages/ohif_cornerstone.js?hash=a6c08303a6192f2dae9b644caff736f21eee02a5:42007:790388
    at Array.forEach (<anonymous>)
    at Function.value (http://localhost:3000/packages/ohif_cornerstone.js?hash=a6c08303a6192f2dae9b644caff736f21eee02a5:42007:790139)
    at retrieveDataFromMeasurements (http://localhost:3000/packages/ohif_measurement-table.js?hash=afec177dcd57944fbd13e450e5c8c8e0fef9771f:1121:36)"

**Comment by swederik** [comment]
I believe this is because dcmjs is using the tool type names for Cornerstone Tools v3, but the Meteor version of OHIF might still be using v2.

**Comment by viss3595** [comment]
> I believe this is because dcmjs is using the tool type names for Cornerstone Tools v3, but the Meteor version of OHIF might still be using v2.

Thanks @swederik 

i am work on OHIF Viewer. i use Cornerstone Tools Version 2.4.0
and Meteor version 1.8.1(latest version) of OHIF. anything wrong with Version because still i getting error when saving measurement.

**Comment by dannyrb** [comment]
Unfortunately this issue has grown stale, and with the release of our most recent major version, it is unlikely that we will have the bandwidth to address this issue for our `v1.x` branch. 

If you find that this has not yet been addressed in our `master` branch, you are more than welcome to create a [GitHub Issue](https://github.com/OHIF/Viewers/issues/new) to request or discuss it. If you're curious to see what we have planned in the near future, you can [check out our roadmap](https://ohif.canny.io/), and [read our docs](https://docs.ohif.org/).
