### ISSUE TITLE
Open/Change PDF - BUG

### ISSUE THREAD

**Issue by ArturRod** [OHIF/Viewers#2821]
Using the latest version of OHIF and previous versions I have found the following error:
If you open a study with several PDFs (2 or more), you will only be able to see one, since if you try to change the view to the other PDF, it will not be updated.
Always showing the same.
To replicate this bug simply:
1- Upload 2 or more dcm PDF.
2- Try to change the PDF and you will see that it is not updated.

**Comment by wensong110** [comment]
May be we can rename the function 'componentDidMount()' to 'componentDidUpdate()' in OHIFDicomPDFViewport.js
