### ISSUE TITLE
Series Inconsistencies: the dataset frames have been different pixel spacing.

### ISSUE THREAD

**Issue by Med-Rokaimi** [OHIF/Viewers#2836]
<img width="340" alt="Screen Shot 2022-07-05 at 1 25 01 PM" src="https://user-images.githubusercontent.com/69142062/177307765-ef6df5af-8068-48b8-a60b-410fa827eadc.png">

**Comment by sedghi** [comment]
That means your data has problem. Feel free to reopen the issue with more details
