### ISSUE TITLE
Image with same resolution appear to be sharper in Horos viewer compared OHIF

### ISSUE THREAD

**Issue by kunjesh1** [OHIF/Viewers#2845]
I have uploaded a head CT scan of the same resolution in Horos and OHIF viewer. The image in Horos viewer appear to be more sharper than OHIF. Any reason why this is happening?

Horos viewer download link : https://files.slack.com/files-pri/T0L2DKJ2Y-F03J5U899FA/download/horos3.3.6.dmg?origin_team=T0L2DKJ2Y

I have attached the screenshots for both.
<img width="1440" alt="Screenshot 2022-07-20 at 5 04 56 PM" src="https://user-images.githubusercontent.com/16972191/180207473-e81b9b8b-9a03-4310-973b-414d3cafab8a.png">
<img width="1440" alt="Screenshot 2022-07-21 at 4 38 36 PM" src="https://user-images.githubusercontent.com/16972191/180207493-9541d6c7-6fd0-4eab-9bf7-e3bdc09ee1cc.png">

**Comment by kunjesh1** [comment]
Attached the CT scan as well
[routine.zip](https://github.com/OHIF/Viewers/files/9159095/routine.zip)

**Comment by swederik** [comment]
If this is v3-stable, then I think it's this: https://github.com/cornerstonejs/cornerstone/issues/84

How does it look on feat/cornerstone3D?

**Comment by kunjesh1** [comment]
In feat/cornerstone3D it looks like this, Is cornerstone 3D is webGL based ?

<img width="770" alt="Screenshot 2022-07-21 at 10 09 33 PM" src="https://user-images.githubusercontent.com/16972191/180268177-e44dd70d-5329-4bd4-82d7-f3a529083fda.png">

**Comment by pieper** [comment]
The image looks the same on Slicer as it does on OHIF, so I'd say horos is applying a different window/level for some reason.

Slicer reports:
```
Window/level found in DICOM tags (center=40.0, width=100.0) has been applied to volume 2: ROUTINE HEAD
```
<img width="701" alt="image" src="https://user-images.githubusercontent.com/126077/180274731-0b5e7d42-a976-467c-939a-9e6d2a430596.png">

**Comment by sedghi** [comment]
@kunjesh1 is this still happening in latest master?

**Comment by james-hanks** [comment]
@sedghi to investigate latest version and see if decoders need to be updated

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
