### ISSUE TITLE
3D IMAGES NOT DISPLAYING AS IT IS IN V2 AND V3

### ISSUE THREAD

**Issue by arunjoshtech** [OHIF/Viewers#2846]
Dear sir,
The 3D images displaying in ohif viewer with added color and blueness. the images are lossless compression. Lossless jpeg2000/Lossy jpeg 2000 both are same behavior, but same images opening fine in Radiant and weasis DICOM viewer.
I have attached images for your reference, The first images in clear display is from weasis, rest of the two are from V2 and V3 ohif viewer. Any advise to resolve it please
![OHIF 3D IN WEASIS](https://user-images.githubusercontent.com/63642104/180265824-124a6c31-172c-4ca5-bc80-5284db9cfe69.png)
![OHIF V3 3D](https://user-images.githubusercontent.com/63642104/180265839-29fe9878-e572-4572-86d2-205de2bfb576.png)
![OHIF VIEWER 3D IMAGE ISSUES](https://user-images.githubusercontent.com/63642104/180265845-7bb6e540-7ceb-4193-a8ed-011ed0dae710.png)

**Comment by tonitomystery** [comment]
Can you share the data?

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
