### ISSUE TITLE
When OHIF is configured with OIDC after auth it redirects to callbackurl again, another refresh works

### ISSUE THREAD

**Issue by smithago** [OHIF/Viewers#2850]
### Describe the Bug

OHIF viewer is configured with OIDC properties to support authenticated access to backend service.
After the auth redirections and confirmation, ohif redirects to callbackurl.

Refreshing the base url works.

### What steps can we follow to reproduce the bug?

We have a github repo on how to configure ohif viewer to Azure DICOM service and deploy ohif viewer as a static website in storage account.
https://github.com/microsoft/dicom-ohif
It has step by step instructions on how to set it up.

If you follow this and authenticate, you will run into the final stage of redirection to callbackurl.

It is also mentioned as a github issue from one of our customers
https://github.com/microsoft/dicom-ohif/issues/7

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Hey @smithago , thanks for the report. Can you try `v3-stable` and see if the problem still exists?

**Comment by smithago** [comment]
Will do @sedghi

**Comment by smithago** [comment]
I just tried, looks like lot of steps have changed in that branch. Here is what I was doing to generate index.html and minified and webpacked index.umd.js.*

cd platform/viewer
Yarn install
yarn run build:package

Looks like the build:package is missing and the webpack.commonjs.js

**Comment by sedghi** [comment]
you don't need to `cd` into viewer, run the `yarn build` at the root of the monorepo, the build files with (index.html) will become available in the `platform/viewer/dist`

**Comment by smithago** [comment]
It still has too many files. Before when I did the `yarn run build:package`, it just gave me the minimum basic, like below

![image](https://user-images.githubusercontent.com/6980724/181682227-e64c3df5-fb1e-405b-ba1f-57332534f33d.png)


Now if I upload all the content from `platform/viewer/dist` Is is blank when I browse index.html.

**Comment by sedghi** [comment]
Where do you upload the content? This doc page might be helpful https://v3-docs.ohif.org/deployment/build-for-production/

**Comment by smithago** [comment]
I upload the content to Azure Blob container with static website enabled. The build has changed in v3, I am not able to produce the same minified and merged content. Can someone help me?

**Comment by sedghi** [comment]
The built get separated into chunks, but still if you get index.html and main javascript bundle generated it knows each chunk path and load them as necessary. Can you send me an email at ar.sedghi@gmail.com , we can setup a meeting to fix this

**Comment by sedghi** [comment]
@jbocce ditto

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
