### ISSUE TITLE
Instance-level qualitative annotations not handled properly when there is more than one SR 

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2852]
It appears that if 2 SR instances with slice-level qualitative annotations are present, it is impossible to select the active one in the right-hand panel, and also there appears to be no labels with the annotations in the slice view.

@deepakri201 can share an example dataset.

Follow up on https://github.com/OHIF/Viewers/issues/2797

**Comment by deepakri201** [comment]
It seems that the annotations only appear for one of the SR instances. 

Here is an [example dataset](https://www.dropbox.com/s/tw68ylvdf8qhmnl/OHIF_two_SR_annotation_issue.zip?dl=0)

**Comment by fedorov** [comment]
@Punzo thanks for the quick fix! Can you maybe give a brief summary what was the underlying issue?

**Comment by Punzo** [comment]
> @Punzo thanks for the quick fix! Can you maybe give a brief summary what was the underlying issue?

just an error in the parsing code, the second SR was overwriting the read data of the first, instead of appending.

I also fixed a couple of very minor issues in the UI

**Comment by deepakri201** [comment]
Thank you for the fix! Unfortunately, I think there may be a problem as I get the following error: 

![image](https://user-images.githubusercontent.com/59979551/186538260-8f870049-1ad8-4f80-a4e3-2d545e46e3aa.png)

Here is a [dropbox link](https://www.dropbox.com/s/9hmurxp0p908h3v/OHIF_two_SR_annotation_issue_08_24_22.zip?dl=0) the with the 2 SRs and the corresponding CT data. 

Thanks!

**Comment by Punzo** [comment]
> I also noticed that in `/platform/viewer/public/config/default.js`, v9 is referenced. Could it be changed to v10?

sure! done in https://github.com/ImagingDataCommons/Viewers/commit/505b7d6337cda4323273595799a60ed8b563a799

> Here is a [dropbox link](https://www.dropbox.com/s/9hmurxp0p908h3v/OHIF_two_SR_annotation_issue_08_24_22.zip?dl=0) the with the 2 SRs and the corresponding CT data.

ok I will check it out now

**Comment by Punzo** [comment]
@deepakri201 for me both datasets are working:
1)
![Screenshot from 2022-08-25 09-59-36](https://user-images.githubusercontent.com/7985338/186609284-38676d56-4dec-4fa5-8432-bb8553de4155.png)
2) 
![Screenshot from 2022-08-25 10-00-06](https://user-images.githubusercontent.com/7985338/186609301-10c10cb1-4457-4b19-a652-e7bc34e24cac.png)

However, In your screenshot I see a study with a segmentation and two SRs, but no CT data (while I have in both data test 1 CT and 2 SR). Probably it is related to pointing v9 vs v10 release in the config. Can you please double check if v10 release has fixed the issue? Thanks

**Comment by deepakri201** [comment]
Hi, 

Thanks for taking a look -- I should have mentioned that I'm using this branch: `https://github.com/ImagingDataCommons/Viewers/tree/IDC2servers`

I realized that I made a mistake in how I was deploying our OHIF instance, once I fixed that, everything looks great  :) 

![image](https://user-images.githubusercontent.com/59979551/186713491-a0c2ed57-adf8-4bfd-a0d1-f805a0584104.png)

Thanks again!
