### ISSUE TITLE
MPR does not sync slices when selecting slice-level qualitative annotations

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2859]
Follow up on #2797.

**Comment by Punzo** [comment]
To discuss: in OHIFv2 the MPR viewport ddo not support measurements/annotation. In fact when clicking on an item on the right panel, the first left (red) viewport  will be automatically be switched to a cornerstone viewport. Adding annotation to the MPR mode is a major rework. We could disable the measurement/annotation panel in MPR mode.

**Comment by fedorov** [comment]
Yes, I think it is practical to just disable that panel then. It would be very nice to get it working, but I don't think major rework is a viable option for us, and would not be a good use of resources anyway given v3 on the horizon.

**Comment by Punzo** [comment]
> Yes, I think it is practical to just disable that panel then. It would be very nice to get it working, but I don't think major rework is a viable option for us, and would not be a good use of resources anyway given v3 on the horizon.

ok, there is a way to disable the panel in the config file at start up. I will see if it can be disabled at run time, so we can switch on/off when clicking the MPR mode.

**Comment by Punzo** [comment]
There is no easy way to disable the measurement panel at run time, but I implemented a check wheen clicking on the annotation item and if the viewport is MPR mode, it will not propagate the selection and a warning will pop up.

![Screenshot from 2022-08-25 11-08-43](https://user-images.githubusercontent.com/7985338/186624394-00e97b59-4d2b-4387-8210-85897a194a69.png)
