### ISSUE TITLE
Load study data from server dcm file

### ISSUE THREAD

**Issue by eagle49** [OHIF/Viewers#286]
How to get json data like CRStudy.json (StandAloneViewer/private/testData/CRStudy.json) from server side dcm file?
![image](https://user-images.githubusercontent.com/29590370/46268383-b9d9d200-c56c-11e8-98be-b564949b0031.png)
In StandAloneViewer project this using demo file, but I want to use server side dcm file.

**Comment by swederik** [comment]
This issue might help: https://github.com/OHIF/Viewers/issues/177

**Comment by eagle49** [comment]
thank you @swederik
