### ISSUE TITLE
Load local DICOM file from object url

### ISSUE THREAD

**Issue by fraform** [OHIF/Viewers#2863]
Hi all, and thanks for excellent work with ohif viewer.

I'm developing a web app that embed the viewer. I built the bundle from myself (following https://v3-docs.ohif.org/deployment/build-for-production).

I would to open local file programmatically so I'm trying to open a study from a JSON like this, where `url` is obtained by calling `window.URL.createObjectURL(file)`

> {
	"studies": [{
		"StudyInstanceUID": "1.2.3.4.5.6.7.8.9",
		"StudyDate": "20000101",
		"PatientName": "",
		"PatientAge": "",
		"PatientSex": "",
		"series": [{
			"SeriesInstanceUID": "1.2.3.4.5.6.7.8.9.10",
			"SeriesNumber": "1",
			"Modality": "CT",
			"SliceThickness": "2.500000",
			"instances": [{
				"url": "dicomweb:blob:http://localhost/73d234f5-4671-4c46-ba4c-274a84e93f30",
				"metadata": {
					"InstanceNumber": "3",
					"Modality": "CT",
					"SOPInstanceUID": "1.2.3.4.5.6.7.8.9.10.1",
					"SeriesInstanceUID": "1.2.3.4.5.6.7.8.9.10",
					"StudyInstanceUID": "1.2.3.4.5.6.7.8.9.10.2",
					"Rows": "512",
					"Columns": "512",
					"SOPClassUID": "1.2.3.4.5.6.7.8.9.10.3",
					"PhotometricInterpretation": "MONOCHROME2",
					"BitsAllocated": 16,
					"BitsStored": 16,
					"PixelRepresentation": 1,
					"SamplesPerPixel": 1,
					"PixelSpacing": ["0.703125", "0.703125"],
					"HighBit": 15,
					"ImagePositionPatient": ["-166.000000", "-171.699997", "-15.000000"],
					"ImageOrientationPatient": ["1.000000", "0.000000", "0.000000", "0.000000", "1.000000", "0.000000"],
					"FrameOfReferenceUID": "1.3.6.1.4.1.14519.5.2.1.6279.6001.229925374658226729607867499499",
					"ImageType": ["ORIGINAL", "PRIMARY", "AXIAL"],
					"WindowCenter": "-600",
					"WindowWidth": "1600"
				}
			}]
		}],
		"NumInstances": 1
	}]
}

but it fails
![2022-08-08_17:48:15](https://user-images.githubusercontent.com/34766291/183459117-de7876c0-3293-4f98-89c5-32e096b2240e.png)

and in developer console there is only an error (Failed to add or update measurement: Error: Failed to map 'CornerstoneTools@4' measurement for definition stack).

So my question is simple :smile: : can I load the file from this type of URL or not?

Thanks in advance

**Comment by abasb75** [comment]
i load and import dicoms and pdf file from url with a json like :
{
studies:[{url:https://...},{url:https://...},{url:https://...},{url:https://...},{url:https://...}]
}
i download all dicoms from url with ajax http request and save them in array as file object like input file object.
then i import files to local base ohif codes.
i change ohif.org/local.

**Comment by anarnoli** [comment]
Hey @fraform - Did you find out any solution on it?

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
