### ISSUE TITLE
Custom date filter

### ISSUE THREAD

**Issue by MurilosSampaio** [OHIF/Viewers#2865]
## Request

I'm trying to add in the sessionStorage the last arguments used in the filters from the studylist, so the next time the studylist is loaded the information of the last filter are used and make an agile way of access the previous exams.

I think it would be a good feature to add. Till now I'm having trouble to do this the right way, but if any progress happens I will continue to uptade this issue. I would appreciate some tips for the development of this feature.

**Comment by sedghi** [comment]
I think we are planning to fix this. The PR is here. I will close this issue https://github.com/OHIF/Viewers/pull/1437
