### ISSUE TITLE
Error 403 while loading image

### ISSUE THREAD

**Issue by tunglt1810** [OHIF/Viewers#287]
Hi, i setup an orthanc server by docker image and using cloudflare for ssl, nginx for proxy_pass to orthanc port.
I still query studylist but when view a studi i can not load the image. Do anybody know this problem?
![image](https://user-images.githubusercontent.com/19906349/46470673-a7c49180-c801-11e8-9518-0da3680942a6.png)

**Comment by tunglt1810** [comment]
@swederik i dont change anything, still origin authentication config
When i point UriRoot to ip:port , it's work. But when i change UriRoot to domain name control by nginx and proxy pass request to local port, but it's not.
I've try include proxy_set_header Authorization but it's no effect

**Comment by tunglt1810** [comment]
Hello! Anybody here?

**Comment by tunglt1810** [comment]
I have try put ssl configuration to connect orthanc server which protected by cloudflarem but nothing happens

**Comment by swederik** [comment]
What does Orthanc say? Is it rejecting because you don't have the proper authorization header? Is the proxy (nginx) forwarding the header properly?

**Comment by dannyrb** [comment]
@tunglt1810, we haven't heard from you in a while, so I'm going to close this issue. Please feel free to continue the conversation despite it being marked as closed.

FWIW, we will be releasing a small amount of documentation in the near future that covers a setup similar to the one you're describing.
