### ISSUE TITLE
Some hotkey does not work in v3.1

### ISSUE THREAD

**Issue by JennyLeePMH** [OHIF/Viewers#2870]
### Bug on a single viewport

1. Go to https://v3-demo.ohif.org/
2. Open any CT
3. Save the existing hotkey preference, by setting -> user preference -> save
4. The following shortcut does not work
- Page Up for Next Series
- Page Down for Previous Sereis
- Home for First Image
- End for Last Image
- z + mouse for Zoom 

### Bug with multiple viewports
1. Go to https://v3-demo.ohif.org/
2. Open a study with multiple series
3. Open 2 viewports or more
4. Save the existing hotkey preference, by setting -> user preference -> save
5. The following shortcut does not work
- Right for Next Image Viewport
- Left for Previous Image Viewport

**Comment by sedghi** [comment]
Can you try now with 3.2?

**Comment by horner** [comment]
Looks like a bug introduced by https://github.com/OHIF/Viewers/commit/ebc01a8ca238d5a3437b44d81f75aa8a5e8d0574  @galelis.  @rareramos found it for me.

**Comment by horner** [comment]
Welp, I cannot find this problem in v3.  It looks like it a different issue for v2.

**Comment by JennyLeePMH** [comment]
@sedghi , the following hotkeys still does not work on OHIF v3 demo
- Home for First Image
- End for Last Image

Also, I am unsure how to use the 'z' key for zoom.

**Comment by JennyLeePMH** [comment]
fixed in v3_master.
