### ISSUE TITLE
Examples demonstrating the implementation of Hanging Protocol in the docs

### ISSUE THREAD

**Issue by arunpdl** [OHIF/Viewers#2872]
> :hand: Many people requests features. Tell us why yours is important to the
> community. How does it add value? Why _this feature_?
>
> Is your request very specific to your needs? Consider
> [contributing it](https://docs.ohif.org/contributing.html) yourself! Or reach
> out to a community member that offers
> [consulting services](https://docs.ohif.org/help.html#paid--commercial).

## Request

**What feature or change would you like to see made?**

Please provide an example with a general usage of the hanging protocol module in the viewer. I cannot find any usage description in the docs besides [the description of the module](https://v3-docs.ohif.org/platform/extensions/modules/hpmodule/).
I am trying to implement a hanging protocol in the viewer, allowing users to set a series of images in certain layout in some order.

Any guidance or example showing the usage of the hanging protocol would be really helpful.

**Why should we prioritize this feature?**
It would help implementing the feature that is already ready to be used in the viewer.
...

Thank you.

**Comment by sedghi** [comment]
Take a look here https://docs.ohif.org/platform/extensions/modules/hpModule
