### ISSUE TITLE
v3.2 Unable to pass jwt token by url params ?

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#2884]
Hi there, 

With previous version of OHIF we had possibilities to pass the JWT token either: 
- with a &token= in the URL
- with a auth function in requestOption parameter of a server settings.

In OHIF v3.2 none of them seems to work, 

Is there a change in the way we can pass a token to OHIF ? 

Best regards,

Salim

**Comment by aprilis** [comment]
Hello, any update on this? As for now this is the only reason which prevents us from upgrading to OHIF v3

**Comment by salimkanoun** [comment]
you have to use the Authentication service by making your own extension. It's work well this way
