### ISSUE TITLE
Error while building OHIF Viewer

### ISSUE THREAD

**Issue by SANTHOSH-SJ** [OHIF/Viewers#289]
While processing files with templating-compiler (for target web.browser):
   Packages/ohif-user-oidc/public/silent-refresh.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for
   you)

   While processing files with stylus (for target web.browser):
   Packages/ohif-themes-common/themes/theme-crickets.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-crickets.styl:1:19
   1| $ohifThemesCommon['crickets'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('crickets')

   Packages/ohif-themes-common/themes/theme-honeycomb.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-honeycomb.styl:1:19
   1| $ohifThemesCommon['honeycomb'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('honeycomb')

   Packages/ohif-themes-common/themes/theme-mint.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-mint.styl:1:19
   1| $ohifThemesCommon['mint'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('mint')

   Packages/ohif-themes-common/themes/theme-overcast.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-overcast.styl:1:19
   1| $ohifThemesCommon['overcast'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('overcast')

   Packages/ohif-themes-common/themes/theme-quartz.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-quartz.styl:1:19
   1| $ohifThemesCommon['quartz'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('quartz')

   Packages/ohif-themes-common/themes/theme-tide.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-tide.styl:1:19
   1| $ohifThemesCommon['tide'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('tide')

   Packages/ohif-themes-common/themes/theme-tigerlily.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-tigerlily.styl:1:19
   1| $ohifThemesCommon['tigerlily'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('tigerlily')

   While processing files with templating-compiler (for target web.browser.legacy):
   Packages/ohif-user-oidc/public/silent-refresh.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for
   you)

   While processing files with stylus (for target web.browser.legacy):
   Packages/ohif-themes-common/themes/theme-crickets.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-crickets.styl:1:19
   1| $ohifThemesCommon['crickets'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('crickets')

   Packages/ohif-themes-common/themes/theme-honeycomb.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-honeycomb.styl:1:19
   1| $ohifThemesCommon['honeycomb'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('honeycomb')

   Packages/ohif-themes-common/themes/theme-mint.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-mint.styl:1:19
   1| $ohifThemesCommon['mint'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('mint')

   Packages/ohif-themes-common/themes/theme-overcast.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-overcast.styl:1:19
   1| $ohifThemesCommon['overcast'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('overcast')

   Packages/ohif-themes-common/themes/theme-quartz.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-quartz.styl:1:19
   1| $ohifThemesCommon['quartz'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('quartz')

   Packages/ohif-themes-common/themes/theme-tide.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-tide.styl:1:19
   1| $ohifThemesCommon['tide'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('tide')

   Packages/ohif-themes-common/themes/theme-tigerlily.styl: Stylus compiler error:
   Packages/ohif-themes-common/themes/theme-tigerlily.styl:1:19
   1| $ohifThemesCommon['tigerlily'] = {
   ------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

   cannot perform $ohifThemesCommon []= ('tigerlily')

**Comment by swederik** [comment]
Hmm that doesn't make too much sense to me. The files in /public are added as assets (https://github.com/OHIF/Viewers/blob/master/Packages/ohif-user-oidc/package.js#L24) so they shouldn't be processed by a template compiler at all.

I've never seen the stylus issue before either. Maybe there's a missing dependency? Which application is this? OHIF Viewer, LesionTracker, or StandaloneViewer? Can you post your .meteor/packages and .meteor/versions files?

**Comment by SANTHOSH-SJ** [comment]
cleared by replacing $ohifThemesCommon['tide']= {
to
$ohifThemesCommon='tide' {

**Comment by SANTHOSH-SJ** [comment]
> 
> 
> Hmm that doesn't make too much sense to me. The files in /public are added as assets (https://github.com/OHIF/Viewers/blob/master/Packages/ohif-user-oidc/package.js#L24) so they shouldn't be processed by a template compiler at all.
> 
> I've never seen the stylus issue before either. Maybe there's a missing dependency? Which application is this? OHIF Viewer, LesionTracker, or StandaloneViewer? Can you post your .meteor/packages and .meteor/versions files?

Thanks for you reply :)

**Comment by deligence** [comment]
app is working to do this , but theme is not working
