### ISSUE TITLE
TMTV Mode breaks when non attenuated series in study

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#2898]
Hi there,

Here is a "serious" problem that will probably need some thinking,
In PET/CT not all PET series are ATTN corrected, in PET/CT series it is frequent to have also a non attenuated corrected series.
The clinical value of such series is debated, but the fact is many PET/CT studies will have 2 (or more) PET series in which one of them (or more) will be non corrected (and thus in which no SUV will be calculated).

The actual problem is that the simple fact to have a non ATTN series breaks the OHIF TMTV modes. 

Probably we need to solve 2 problems : 
- Do not fails just because of a non ATTN series and search for other suitable series
- Do not compute SUV for non ATTN series
- Make an interface for the user to select which series to be displayed.

Best regards,

Salim

`Error: CorrectedImage must contain "ATTN" and "DECY": DECY,DTIM,RANSNG,DCAL,SLSENS,NORM
    at calculateSUVScalingFactors (app.bundle.981458de0f2f6e453cb8.js:244784:11)
    at Object.handlePETImageMetadata [as callback] (app.bundle.981458de0f2f6e453cb8.js:245030:25)
    at app.bundle.981458de0f2f6e453cb8.js:44224:16
    at Array.forEach (<anonymous>)
    at Object._broadcastEvent (app.bundle.981458de0f2f6e453cb8.js:44223:31)
    at Object.addInstances (app.bundle.981458de0f2f6e453cb8.js:40137:10)
    at _storeInstances (app.bundle.981458de0f2f6e453cb8.js:241774:66)
    at _callee6$ (app.bundle.981458de0f2f6e453cb8.js:241846:29)
    at tryCatch (app.bundle.981458de0f2f6e453cb8.js:241314:2440)
    at Generator._invoke (app.bundle.981458de0f2f6e453cb8.js:241314:2000)`

**Comment by JennyLeePMH** [comment]
@salimkanoun , I agree, that is an excellent point.  We have reported this issue in #3057 as well.  Since your issue been reported, OHIF have allow users to drag and drop which series to display on TMTV.  So, if a Non-ATTC PET is selected by default, user have the option to change.   However, SUV is still calculated for Non-ATTN PET.  Do you think this solution is acceptable?   

In addition, we have found that TMTV mode does not ensure the PET and CT have the same frame of reference UID, before permitting sync scrolling.  See #3063 .  For example, if the patient had to leave and return to the couch top for whatever reason, then the series would have different frame of reference in this study.  What is an acceptable behaviour for TMTV mode for such study, in your opinion?

**Comment by salimkanoun** [comment]
@JennyLeePMH , thanks for feedback.

- I agree that the drag and drop series is a very nice addition and really reduce this issue impact as the user can select the correct ATTN series. It would be better to make it automatically by loading the first instance metadata to access to the ATTN metadata but there is nothing urgent.
- However SUV shall not be calculated in non-ATTN series. The idea of the SUV calculation is to quatify the mesured uptake in the image and compared it to the theorical uptake if all injected tracer were uniformly diluted in the body. So it's a semi quantitative index. Non ATTN series does not reflect the real uptake, it reflect how photons are able to escape the patient body more than the real uptake, there is a huge gap between ATTN and Non ATTN series. I never seen any workstation calculating SUV in non ATTN series. Calculating SUV on non ATTN can also lead to physician to make wrong quantification because they used to be secured by viewer that will not calculate SUV on unsafe condition and i'm not sure all physicians actually have deep understating on how SUV is calculated (if they see it they probably take it).
- That's strange because I was about to report a bug, when you load a PET series from another study in place of a displayed PET Series I got an error in the console saying that the FrameOfReferenceUID was different (the bug was in fact when you replace also the CT series by the CT series with the frame of reference it doesn't restore the fusion). So I saw a safty check on FrameOfReferanceUID that's curious.  However the same of reference uid should be secured in my optinion, but it would be nice to have an alert or a dialog or a panel allowing you to "force" fused two series of different FrameOfReferenceUID and in this panel be able to move the image coordinate to register them manually (because if they don't share the same reference it's likely to mean they are not registered).

**Comment by JennyLeePMH** [comment]
@salimkanoun , sorry for the late reply

1. Yes, it would be better if TMTV can detect the PET AC via metadata, and load its automatically. I agree it is not so urgent, as user can now drag and drop.  While user drags and drops, TMTV should also confirm that the Frame of Reference of the two image sets selected are the same.
2. Agree as well.
3. Yes, I saw the check in the console when FoR are different as well. However, once different FoR is detected in the console, the TMTV starts behaving oddly.  Reported in #3063. 
When PET AC and CT have different FoR, they could be from the same study or from different studies.  As you mentioned, we think having an alert to inform the user is very important. However, having a panel that allows user to adjust/fuse two series with different FoR is an image registration problem.  It is probably outside the scope of TMTV mode.  
If you have other thoughts on this different FoR issue, please comment on #3063, so similar conversations are grouped together.

**Comment by salimkanoun** [comment]
Solved with the new matching rule system and drang/drop new series in the HP
