### ISSUE TITLE
Does OHIF provide support for React native(Mobile App) 

### ISSUE THREAD

**Issue by ctTushar** [OHIF/Viewers#2899]
I want to know can I used this library for React native mobile development? If yes, can you help me out with documentation or any demo application regarding it.

**Comment by saddam-hessein** [comment]
through cross-platform framework  OHIF will work as mobile App.

**Comment by DavidMGT** [comment]
yes,I. want to do that too.any ideas?anyone could help?

**Comment by sedghi** [comment]
Have you tried? not a react native expert, but give it a go and let us know about the limitations and we can work towards fixing them
