### ISSUE TITLE
how config OHIF to clearcanvas server

### ISSUE THREAD

**Issue by itcthienkhiem** [OHIF/Viewers#29]
dear all,
i wanted connect OHIF to clearcanvas server using wado? 
how config file in OHIF ?
thank all.

**Comment by radicalrob** [comment]
I haven't tried to do this before, but I think this should possible.  I will try to set it up and share my results.

**Comment by itcthienkhiem** [comment]
dear you? do you had document config in OHIF?
thank.

**Comment by radicalrob** [comment]
I tested with ClearCanvas image server and it's working fine.  A couple of things to be aware of: (1) ClearCanvas doesn't support DicomWeb, only WadoURI.  You'll have to use DIMSE for getting metadata.  Also, since I'm running my meteor instance locally, but sending WADO requests to another server (CC image server), I am running a proxy that listens on port 1001 and forwards the requests to my CC server (on port 1000 at host 'radserve').

Here's what I used:


{
   "servers": {
     "dicomWeb": [
       {
            "name": "ClearCanvas",
            "wadoUriRootNOTE" : "either this uri is not correct for wado-uri or wado-uri is not configured on ClearCanvas currently",
            "wadoUriRoot" : "http://localhost:1001/wado/PACSAE",
            "qidoRoot": "http://radserve:1000",
            "wadoRoot": "http://radserve:1000/wado/PACSAE",
            "qidoSupportsIncludeField": false,
            "imageRendering" : "wadouri",
            "requestOptions" : {
              "auth": "none:none",
              "logRequests" : false,
              "logResponses" : false,
              "logTiming" : false
       }
     }],
     "dimse": [{
       "name": "ClearCanvas",
       "peers": [
         {
            "host" : "radserve",
            "port" : 105,
            "aeTitle" : "PACSAE",
            "default" : true,
            "supportsInstanceRetrievalByStudyUid": false
         },
         {
            "host" : "0.0.0.0",
            "port" : 11112,
            "aeTitle" : "OHIFDCM",
            "default" : true,
            "server" : true
         }
       ]
     }]
   },
   "defaultServiceType": "dimse"
 }

**Comment by XingGuan** [comment]
Dear,
I want to connect OHIF to XNAT server with wado?
How to configure files in OHIF?
thank you all.

**Comment by XingGuan** [comment]
Dear,
I want to connect OHIF to XNAT server with wado?
How to configure files in OHIF?
thank you all.

**Comment by XingGuan** [comment]
Dear,
I want to connect OHIF to XNAT server with wado?
How to configure files in OHIF?
thank you all.

**Comment by lam0620** [comment]
@radicalrob Could you give a sample proxy to forward to server support DIMSE (WadoURI only)

Thanks!

**Comment by dannyrb** [comment]
@Iam0620, I'm going to close this issue. In general, you're much more likely to receive a response if you create a new issue as old/closed issues are infrequently monitored. Simply reference the old issue in your new one.

Thanks for understanding! ^_^
