### ISSUE TITLE
v3-stable: Improving style customization through tailwind

### ISSUE THREAD

**Issue by gabriellebaudy** [OHIF/Viewers#2902]
## Request: simplifying style overriding

**What feature or change would you like to see made?**
Currently it seems the only way to change global styles is to edit the following file: `platform\ui\tailwind.config.js`.
The thing is this would become hard to maintain since it is located at the core of the library.
It would be easier if we could add our own style config through some kind of optional config related to extensions or modes.

**Why should we prioritize this feature?**
This issue impacts the maintainability in case of a fork, since we have to check any conflict on this file every time we pull the latest changes.
OHIF's features are highly customizable. It would make sense if the UI could be as much.

**Comment by sedghi** [comment]
That is an interesting idea and a valuable one, tell us more about it or we are happy to review a PR
