### ISSUE TITLE
v3-stable tmtv regression with @cornerstonejs/tools@0.21.8 vs 0.21.7

### ISSUE THREAD

**Issue by Ouwen** [OHIF/Viewers#2914]
### Describe the Bug
Seems like there is a regression in the Crosshair tool in tmtv when fresh installing current `v3-stable` branch. Downgrading the cornerstonejs/tools to 0.21.7 seems to fix this. Perhaps it is related to the Crosshair tool rename?

### What steps can we follow to reproduce the bug?

1. Fresh install of `v3-stable`
2. `yarn install`, `yarn dev`, results in crosshair bug for tmtv view
3. Force `yarn add cornerstonejs/tools@0.21.7`, results in crosshair bug being resolved

**Comment by salimkanoun** [comment]
I also figured that bug, i also think it might be related to this typo (https://github.com/cornerstonejs/cornerstone3D-beta/commit/46d13bcb047c2b71c17b0246359d9494fbd8fb89)

We will see on the next release,

Salim

**Comment by Ouwen** [comment]
I'm not sure if it's that typo because I don't think the cornerstone extension uses hard strings to reference the tool.
