### ISSUE TITLE
Hotkeys priority system or namespace user Hotkey preferences by Mode

### ISSUE THREAD

**Issue by Ouwen** [OHIF/Viewers#2915]
Hotkeys are set in the mode and by user. Sometimes, the mode will set different window level hotkeys (1,2,3) may correspond to different ww/wl for Head CT imaging, vs Mammo, vs Lungs, vs Abdominal.

However, if the user has hotkeys set from one mode to another these keys will override (using head ct ww/wl presets vs mammo presets defined by the mode).

One way to solve this is priority, another is to namespace the hotkeys.

**Comment by sedghi** [comment]
We implemented a name space recently
