### ISSUE TITLE
What is the id of FreeformRoi?

### ISSUE THREAD

**Issue by eagle49** [OHIF/Viewers#292]
![image](https://user-images.githubusercontent.com/29590370/46864987-804b7580-ce4e-11e8-9149-f38d358a98ae.png)
I want to Add FreeformRoi tool in StandaloneViewer, but don`t know the id.
I tried `freeformRoi' but it didn`t work.

**Comment by eagle49** [comment]
> ![image](https://user-images.githubusercontent.com/29590370/46864987-804b7580-ce4e-11e8-9149-f38d358a98ae.png)
> I want to Add FreeformRoi tool in StandaloneViewer, but don`t know the id. I tried`freeformRoi' but it didn`t work.

I found that the id is "freehand", but when I add this in toolbarSection.js, it didn`t work.
it says `Command "freehand" not found in current context`.

**Comment by JamesAPetts** [comment]
Hey @eagle49 , you need to add it to the list in `hotkeyUtils.js` also, an open PR that includes the freehand tool can be found here:

https://github.com/OHIF/Viewers/pull/300

**Comment by liuchen1393193701** [comment]
how to add freehand in standaloneviewer

**Comment by liuchen1393193701** [comment]
how to add freeformRoi,i mean is realize this function

**Comment by liuchen1393193701** [comment]
you know i mean realize this function
