### ISSUE TITLE
Image Rendered (W/L) differently when loading series (Colored)

### ISSUE THREAD

**Issue by rathwale** [OHIF/Viewers#2927]
> **Before Creating an issue**
>
> - Are you running the latest version? Yes 
https://d18i6d3xyym493.cloudfront.net/viewer?StudyInstanceUIDs=2.25.272843087945392307095009963699086894492
> - Are you reporting to the correct repository? Yes
> - Did you search existing issues? No

### Describe the Bug

_A clear and concise description of what the bug is._

### What steps can we follow to reproduce the bug?

1. Load Study - https://d18i6d3xyym493.cloudfront.net/viewer?StudyInstanceUIDs=2.25.272843087945392307095009963699086894492
2. Drag & Drop one of the series - 602, 604 or 605
3. 1st image looks little dull 
4. 
![image](https://user-images.githubusercontent.com/108415306/189964995-913021a2-78a6-4e8d-934c-4b633d199ca6.png)
5. Scroll the series and come back to 1st image ( it displays correctly now)
![image](https://user-images.githubusercontent.com/108415306/189965175-81cf3c9d-7701-4497-895e-ef0230184acd.png)

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by rathwale** [comment]
I have also observed similar behavior with Tomo images as well.. Initial load it displays image but scrolling back & forth make it completely white.

**Comment by rathwale** [comment]
Thanks for the response..

Just FYI - same study works in v2 version..

Ritesh Athwale (he/him)
Principal Architect

m: +1 630.659.7198
e: ***@***.***
RapidAI.com <https://rapidai.com/>	
 <https://www.linkedin.com/company/rapid-ai>   <https://twitter.com/rapidai>   <https://www.youtube.com/channel/UC4KBnsVQpEwGkZWZcZBEU1A?view_as=subscriber>
iSchemaView, Inc. EMAIL CONFIDENTIALITY NOTICE: The information transmitted in this email is confidential. Any use, copying or distribution of the information, other than for the purpose for which it was provided, is strictly prohibited.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
