### ISSUE TITLE
Feature Request : 3d orientation with sagittal and coronal view. MPR (MultiPlaner Reformation)

### ISSUE THREAD

**Issue by Bhavya0304** [OHIF/Viewers#2932]
## Request

**What feature or change would you like to see made?**
> I am requesting a feature that can help many OHIF dicom viewer users and solve there only and major problem that is feature of sagittal and coronal view that is in MPR (MultiPlaner Reformation) section this is the most requested feature of radiologists that can make this dicom viewer a perfect dicom viewer without any lacking.

**Why should we prioritize this feature?**
> As I mentioned that this is the most demanded feature by radiologists and might be the only reason of not using this dicom viewer. So if this feature is added it might be the big leap.

**Comment by sedghi** [comment]
The code is implemented, but the button is commented out for now (until we finalize the UI). 
Uncomment here https://github.com/OHIF/Viewers/blob/v3-stable/modes/longitudinal/src/toolbarButtons.js#L293-L310
and here https://github.com/OHIF/Viewers/blob/v3-stable/modes/longitudinal/src/index.js#L105
