### ISSUE TITLE
BUG: Two server issue - Instance-level qualitative annotations not handled properly when there is a SEG/RTSTRUCT in the referenced study 

### ISSUE THREAD

**Issue by deepakri201** [OHIF/Viewers#2935]
Hi, 

I am working with the IDC2servers branch, and noticed some potential issues with handling of qualitative annotations. I am working with data from the NSCLC-Radiomics collection, where each patient contains CT, SEG and RSTRUCT DICOM data. I noticed that when I have my dicom store with a SEG and SRs, the SR annotations fail to appear in the menu on the right as well as for the labels per slice. Previously I did not have this issue when the referenced study included only CT files. 

The error that appears in the OHIF viewer is: 
![image](https://user-images.githubusercontent.com/59979551/190715484-23d7518d-1f23-43bb-bf05-2ad99556b0de.png)
![09_14_22_ohif_errors](https://user-images.githubusercontent.com/59979551/190709800-12f607b1-d5ca-456c-b788-9b1b62344a0b.JPG)

[Here](https://www.dropbox.com/s/ftbwbnrq98npmb2/OHIF_slice_level_annotation_issue_09_16_22.zip?dl=0) is a dropbox folder that contains the CT data, SEG and RTSTRUCT from IDC, as well as the SEG and two SRs that are in my own dicom store. 

Thank you! 

Deepa

**Comment by Punzo** [comment]
Fixed in https://github.com/OHIF/Viewers/pull/2940 (also now errors in the SR parsing will be catched by the Logger and UI notification service). IDC forks updated as well to version 4.12.39.
