### ISSUE TITLE
Contextmenu not showing in StandaloneViewer

### ISSUE THREAD

**Issue by eagle49** [OHIF/Viewers#294]
When click right mouse button on measurement like length, simpleAngle, probe, ellipticalRoi, etc, not showing the context menu in standaloneviewer.
This is showing on demo site on OhifViewer.
![image](https://user-images.githubusercontent.com/29590370/46883987-28306580-ce86-11e8-8b1a-925855c1ee3d.png)

**Comment by swederik** [comment]
Thanks for the report! That's weird...
