### ISSUE TITLE
v3 blurry images rendered if initial window is small

### ISSUE THREAD

**Issue by Ouwen** [OHIF/Viewers#2947]
<img width="184" alt="image" src="https://user-images.githubusercontent.com/5455421/191392163-feaaa8f1-d460-43dc-a4d1-cc02ea075b23.png">

It seems that the initial div/window size downscales the rendered image but does not refresh on a window resize. This may be a cornerstonejs issue.

**Comment by sedghi** [comment]
This is weird, can you share the anonymized data in slack maybe?

**Comment by Ouwen** [comment]
This is the same behavior in v3-demo:

https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170126083429.2
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/5455421/194629140-2d4f7557-a545-47ea-afb0-42756819aa53.png">

To reproduce: Start the viewer in a small 200x200 window and expand window size after initial load.

**Comment by sedghi** [comment]
Oh i thought window level, yeah that is weird, I'm wondering if resize listener is not working, can you manually force resize of renderingEngine and render after?
