### ISSUE TITLE
Cannot create annotation sometimes

### ISSUE THREAD

**Issue by cheyvaert-medexprim** [OHIF/Viewers#2950]
Hello, 

I'm running ohif viewer as npm package at the last version (4.12.40) on Firefox (104.0.2).

### Describe the Bug

After I have clicked on "Annotate" icon, I can create an arrow with the mouse but it does not stay at screen and the pop-up to add a label does not appear. 
On the bebug console I have:

### What steps can we follow to reproduce the bug?

1. On the view click on annotate button
2. Try to create an annotation. if it works, go to the measurement tab, close it and try to repeat this process a few times. 
3. You should see that the annotation arrow does not stay at screen.

```js
Cornerstone Element Event: cornerstonetoolsmeasurementmodified
Failed to add or update measurement: Error: Failed to map 'CornerstoneTools@4' measurement for definition ArrowAnnotate:
    value MeasurementService.js:444
    addOrUpdate MeasurementService.js:149
    L init.js:258
    L init.js:281
    r cornerstoneTools.js:38153
    p cornerstoneTools.js:8847
    l cornerstoneTools.js:8766
    r cornerstoneTools.js:38153
    p cornerstoneTools.js:5827
    b cornerstoneTools.js:5882
CornerstoneToolsMeasurementModified [handleSingleMeasurementModified.js:18:6](webpack:////ohif/Viewers/platform/core/src/measurements/measurementHandlers/handleSingleMeasurementModified.js)
CornerstoneToolsMeasurementRemoved [handleSingleMeasurementRemoved.js:12:6](webpack:////ohif/Viewers/platform/core/src/measurements/measurementHandlers/handleSingleMeasurementRemoved.js)
syncMeasurementAndToolData 3 [MeasurementApi.js:91:8](webpack:////ohif/Viewers/platform/core/src/measurements/classes/MeasurementApi.js)

​
```

**Comment by cheyvaert-medexprim** [comment]
One my colleague find an explaination: as the image is black on black background, the limit of the frame are not visible and I cannot see where my mouse exceed the space to create annotation arrow.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
