### ISSUE TITLE
v3 EllipseROI drawn outside field of view throws exceptions, cannot be tracked, deleted, or labelled

### ISSUE THREAD

**Issue by Michael-Andersen** [OHIF/Viewers#2955]
If you draw an ellipse outside of the field of view there is an error which I believe occurs in the toMeasurementSchema function. This causes the ellipse to behave like the rectangleROI and angle tools. It can't be tracked, deleted, or labelled. This is inconsistent with an ellipse drawn inside the field of view which can be tracked, deleted, and labelled.

This issue doesn't exist with the bidirectional tool even if it is drawn outside the field of view.

**Comment by sedghi** [comment]
This probably needs to be moved to Cornerstone issue tracking

**Comment by JennyLeePMH** [comment]
this is fixed.
