### ISSUE TITLE
OHIF on mobile app

### ISSUE THREAD

**Issue by deepeshgtm** [OHIF/Viewers#2957]
How can I integrate OHIF viewer on Mobile application. I have rendered the OHIF viewer on mobile app using webview but I want to integrate it on Mobile. So, can I get any documentation or ideas on how can I do it.

**Comment by sedghi** [comment]
OHIF can be executed on both Android and iOS platforms from a technical standpoint. However, it is important to note that our current layout is not specifically tailored for mobile devices. Nevertheless, we have plans underway to enhance and optimize our mobile support layout in the near future.
