### ISSUE TITLE
Demo site of Lesiontrack customer tool

### ISSUE THREAD

**Issue by eagle49** [OHIF/Viewers#296]
Is there any demo site to see the custom tool of LesiontrackViewer?https://github.com/OHIF/Viewers/tree/master/Packages/ohif-lesiontracker/client/compatibility 
Hope @brunoalvesdefaria help me.

**Comment by swederik** [comment]
Yeah sure, it's right there at the top of the README...

http://lesiontracker.ohif.org

(Click Test Drive)
