### ISSUE TITLE
OHIF V3 MPR

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#2962]
I just built the latest build of OHIF Viewer v3 and cant seem to figure out how to access the MPR feature... It's this a bug or am I missing something?

![Screenshot_20220927-193501](https://user-images.githubusercontent.com/5023419/192556162-8541b651-e53c-4d19-83a0-19b92fba6928.png)

**Comment by ranasrule** [comment]
anyone?

**Comment by sedghi** [comment]
the code is there, the tool is commented out, you can uncomment it search for 'MPR'. Not yet merged since we are working to make it work on SEG too

**Comment by ranasrule** [comment]
> the code is there, the tool is commented out, you can uncomment it search for 'MPR'. Not yet merged since we are working to make it work on SEG too

could you please tell me exactly which file the code you are talking about is in ?

**Comment by ranasrule** [comment]
@sedghi ???

**Comment by ranasrule** [comment]
> the code is there, the tool is commented out, you can uncomment it search for 'MPR'. Not yet merged since we are working to make it work on SEG too

Can I please get some help

**Comment by sedghi** [comment]
Sorry about that, there is bit of delay on the release, but you will hear very soon, make sure you have subscribed to the newsletter https://ohif.org/news/
