### ISSUE TITLE
OHIF v3 - wado-rs retrieve metadata doesn't work with .NET servers (DICOMcloud and MS Health)

### ISSUE THREAD

**Issue by Zaid-Safadi** [OHIF/Viewers#2969]
> **Before Creating an issue**
>
> - Are you running the latest version? yes
> - Are you reporting to the correct repository? yes
> - Did you search existing issues? yes

### Describe the Bug

When running OHIF v3 against a .NET DICOMweb server (examples are DICOMcloud and MS DICOMweb). The viewer fails to retrieve the studies metadata due to the server returning an error caused by improperly formatted request header.

******************* Update The description of this issue ************************
This is currently a Bug in OHIF v3 caused by improperly formatted "accept" header. The encoding of the accept header dictate the "type" to by quoted.

The fact that this code is needed for OHIF to work with DICOMcloud/MS DICOMweb is because the .NET Framework doesn't accept this improper header.

Ironically, this bug was introduced originally by the DICOM standard in its first DICOMweb revision. Later on, they realized this and updated the standard. We also had to get this fixed in the dcmjs library a while back.

Here is the header RFC of how to encode this: https://www.rfc-editor.org/rfc/rfc2387
Here is the fixed DICOM standard: https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.7.3.5.1
and the dcmjs issue: https://github.com/dcmjs-org/dcmjs/issues/113

Ultimately, I would like to see the actual streaming of the images decoupled from the wado-loader and off-loaded to something like dcmjs for example so we don't have to fix these kind of issues in multiple places
***************************************************************************************************

### What steps can we follow to reproduce the bug?

1. Run the DICOMcloud server and store some images
2. Configure OHIF config to connect to the installed server endpoints
3. Run OHIF and open the studies list
4. click on a study to open in the viewer 
5. The images fail to be rendered and the server returns 404 for the metadata request

**Comment by maiscelo** [comment]
Sorry my ignorance, but this code was upload to oficial repository? Because when I see the referred error the line is  const xhrRequestHeaders = {
        Accept: acceptHeader,
      };
