### ISSUE TITLE
How to speed up loading time of US movie ?

### ISSUE THREAD

**Issue by Yamada1985** [OHIF/Viewers#2991]
## Bug Report

It takes a lot minutes to loading US movie. (ex. 1 study 500 frame takes around 5 minutes.)
Is there any configulation or solution to speed up to loading ?

### Describe the Bug

I am running OHIF v3-stable version, connect with Orthanc ( v1.11.1 running on local windows11, not on docker).
It load smoothly for CR, DX, CT and US ( single frame ) study.
CT study ( contains around 700 frame ) can be load within a minute.
But it takes a lot minutes for US ( movie ) to loading.
Both of OHIF and ORTHANC running on local windows.

Windows machine Spec. is ;
OS windows11
CPU intel core-i3 10105 ( 4C8T / 3.7-4.4GHz / 6MB ) 
RAM 16GB
Strage 1TB SSD

Does loading speed depends on some configuration such as " Cache Size " ?
Or, it depends on CPU or GPU performance ?
Should we improve CPU and GPU ?

![OHIFv3_US_loading](https://user-images.githubusercontent.com/110296878/197471916-b594d2db-f3d8-4b31-9781-e7b5521d07c8.png)
![OHIFv3_version](https://user-images.githubusercontent.com/110296878/197471929-aa3b2be0-5bd5-4670-9c88-75fd29de4313.png)
![OHIFv2_US_loading](https://user-images.githubusercontent.com/110296878/197471953-8b6034fc-6af6-4cd4-ba7e-49cc4faa3d51.png)

**Comment by Yamada1985** [comment]
I have tried with OHIF v2, but the situation is same.

**Comment by mshunshin** [comment]
There are lots of different reasons for performance issues with OHIF and orthanc - this one may or may not cover you.

The best way is to look both at the progress of downloads on the client, and keep an eye on htop and iftop on the server (to see where the work is going).

When Viewing a multiframe dicom in OHIF and the image rendering config is set to imageRendering: 'wadors' - it will request each frame for the file individually and simultaneously.

If the file is not in Orthanc's cache - it will of-course re-read it from disk or, in my case S3 storage. As the requests come in simultaneously Orthanc's caching algorithm doesn't realise that the requests are for the same file - so will re-download it multiple times - slowing delivery to the client.

When you load a study it triggers them to be read - so they should be in Orthanc's cache - but the default cache size is only 128Mb ("MaximumStorageCacheSize" : 128) which may only accomodate one or two large DICOMS.

Increase this to a few Gb. If you are downloading from an S3 backend - you can add some swap space to the orthanc server to allow this to be raised so it gets cached locally.

Longer term fixes would be if OHIF requested all frames as a single request (or perhaps first frame, then remaining) and if orthanc had better caching algorithms.

**Comment by sedghi** [comment]
I know one bug that we have for loading us multiframes, This PR should fix it https://github.com/cornerstonejs/cornerstone3D/pull/667
