### ISSUE TITLE
Encapsulated PDF does not show last page of multi-page PDF's - using Docker ohif/viewer:latest

### ISSUE THREAD

**Issue by sscotti** [OHIF/Viewers#2996]
Not sure if this is the correct repository because the Docker Hub description isn't clear about that to me.  I am using this Docker image:

```
ohif/viewer:latest
```

and I am using that in conjunction with Orthanc and NGINX reverse proxy.

The issue I am having is that I have studies with encapsulated PDF instances.  These are sometimes more than 1 page long, and the little navigation arrows (right - left) do not bring me to the last page of the PDF for PDF's that are more than 1 page long.

It is funny though, because for a 3 page PDF, I can scroll to the 2nd page, but not the 3rd.  I have not tried it with PDF's that are more than 3 pages.  I also seems that for 2 page PDF's it only with show page 1, i.e. the right arrow doesn't 'work'.

The other thing I noted with that is that if I use the 'download' button to download the document, the downloaded document has all of the pages, so it seems like an issue with the navigation tools in the GUI, rather than some problem with the PDF document itself.

To reproduce, probably just create an instance in a study with a 3 or more page encapsulated PDF and see if you experience the same behavior.

**Comment by sscotti** [comment]
What do you need to reproduce ?  I am seeing the issue on an Orthanc system as mentioned above.  If you are able to upload the following file to a PACS or otherwise just open it directly with the OHIF viewer, try that and see if you can navigate to page 4 ?  I cannot.  I can navigate up to page 3, and I can download the document (4 pages), but the right arrow navigation does not go to 4. 

[IM-0001-10003.dcm.zip](https://github.com/OHIF/Viewers/files/9963365/IM-0001-10003.dcm.zip)

**Comment by sscotti** [comment]
I don't know if this is related, but:

1.  I am using the Docker image build.
2. In my window.config extensions is [].
3. If I try to add OHIFExtDicomPdf to that I get an error, OHIFExtDicomPdf is not defined.

I am not sure how to build and add extensions to the docker build.  I would like to experiment around with almost all of those:

[OHIFExtDicomPdf,OHIFExtDicomHtml,OHIFExtDicomMicroscopy,OHIFExtDicomSeg,OHIFExtVtk],

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
