### ISSUE TITLE
Ambiguous information on timeline for segmentation support in V3 

### ISSUE THREAD

**Issue by Christian-e-S** [OHIF/Viewers#3003]
According to 

![image](https://user-images.githubusercontent.com/59229557/199703352-beec5164-6287-4230-b306-473f31fdc535.png)

and 

![image](https://user-images.githubusercontent.com/59229557/199703169-c7e6988b-4ede-4574-97d6-6deeda01912f.png)

segmentation support should be already available, but I cannot find it in V3-stable. 

Could it be possible that I`m looking in the wrong branch, or is there an update of the timeline?

Thank you very much!

**Comment by Georift** [comment]
Segmentation support has now landed in branch v3-stable. If that's sorted it perhaps we can close this issue?

**Comment by sedghi** [comment]
We have release full segmentation support, read more here https://ohif.org/release-notes/3p7
