### ISSUE TITLE
Contrast stretching

### ISSUE THREAD

**Issue by anupamme** [OHIF/Viewers#301]
Hello,

I am interested in implementing the contrast stretching [1] feature in the OHIF Viewer. 

Would you be able to give some high-level guidance on how I can go about doing the same.

Best, Anupam

1. http://what-when-how.com/embedded-image-processing-on-the-tms320c6000-dsp/contrast-stretching-image-processing/

**Comment by dannyrb** [comment]
I could be mistaken, but isn't contrast stretching another name for windowing/leveling? I believe this is already implemented with the Cornerstone WWWC tool.

https://radiopaedia.org/articles/windowing-ct?lang=us

Closing for now. More than happy to take another peak if you can provide more information.
