### ISSUE TITLE
Elliptical Annotations not being added/tracked when created outside the actual image area

### ISSUE THREAD

**Issue by md-prog** [OHIF/Viewers#3020]
- When creating an elliptical annotations outside the actual image area, it won't either start the measurement tracking, or display the added annotation to the tracking panel
- This was due to the "area" calculated for the annotation would be "undefined" and that was causing exception
- We have `preventHandleOutsideImage` flag for each of the annotations, but this flag seems to be a more buggy.
   If we perform some of the monkey-test with this flag on, some of annotations that shouldn't be added are getting added to the tracking panel and some annotations that are supposed to be added are not being displayed properly.

**Comment by sedghi** [comment]
I think it is fixed in master
