### ISSUE TITLE
failed to retrieve study data

### ISSUE THREAD

**Issue by LogestCai** [OHIF/Viewers#3023]
*The viewer cann't work fine when StudyInstanceUID is a number*

> - I use the latest version 

## Bug Report
The viewer cann't work fine when StudyInstanceUID is a number

### Describe the Bug
- This is the studylist page ,it work fine.
![1668751750254](https://user-images.githubusercontent.com/22650696/202641112-60c7be57-ddfd-44bc-ba1f-4c5c12f9235a.jpg)
- When I click the item ,it go to the error page ,
![00002](https://user-images.githubusercontent.com/22650696/202641482-c1a83335-0fda-4fcc-b742-ce17697058ba.png)
> The qequested url is `http://localhost:3000/viewer/448137`. From the console window I can find two bad request! like below:

`http://10.87.230.199:8899/dicom-web/studies/%C3%A3%C2%8F5%C3%9F/series`
`http://10.87.230.199:8899/dicom-web/studies/%C3%A3%C2%8F5%C3%9F/series/undefined/metadata`
- When I add a dot to the url ,it works fine ! The requested url is `http://localhost:3000/viewer/448137.` 
![000005](https://user-images.githubusercontent.com/22650696/202642480-a955391a-acec-4b68-91a6-8bd5cb6df87b.png)
- The StudyInstanceUID is `448137`
![000006](https://user-images.githubusercontent.com/22650696/202643175-9b500400-37d4-4537-8a85-c3b0699df475.png)

### config 
> `default.js`
```js
 dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: 'http://10.87.230.199:8899/wado',
        qidoRoot: 'http://10.87.230.199:8899/dicom-web',
        wadoRoot: 'http://10.87.230.199:8899/dicom-web',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
```
### The question 
**How to use number StudyInstanceUID in Viewer project?**
Thanks!

**Comment by sedghi** [comment]
Can you try v3? it lives inside v3-stable branch

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
