### ISSUE TITLE
Load images from local Folder in online demo is showing out of memory

### ISSUE THREAD

**Issue by arunjoshtech** [OHIF/Viewers#3027]
![ohif](https://user-images.githubusercontent.com/63642104/202898260-ad77f5b5-bd68-486e-a921-dac06ea35fd0.png)
Dear Team,
To test Ohif viewer , when we try to load files from local  it is getting out of memory.
some times first windows are opening but when we select dual series windows then it is getting  out of memory too.

![Screenshot_20221120_160839](https://user-images.githubusercontent.com/63642104/202898024-e30f8ce2-79c8-4df2-95b5-ed2455c323d8.png)
![Screenshot_20221120_161500](https://user-images.githubusercontent.com/63642104/202898028-b3c3856e-a665-403a-85c3-96b353400813.png)

**Comment by sedghi** [comment]
I can't reproduce this on my machine. It loads fine
What does the Chrome console says ? https://developer.chrome.com/docs/devtools/open/

**Comment by sedghi** [comment]
Check this out https://github.com/OHIF/Viewers/issues/3207
