### ISSUE TITLE
MPR not working on OHIF v3 ("Your page is NOT cross-origin isolated" in console)

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#3033]
On the latest version of OHIF V3 MPR is not working for me.This exact setup works fine with OHIF v2. Im running OHIF in Nginx v1.23.2. Im posting my Nginx config file, OHIF app-config.js contents files below:

![Screenshot 2022-11-22 181350](https://user-images.githubusercontent.com/5023419/203322897-ce7470b0-7738-4354-b279-c01e53d6f7e0.png)

### What steps can we follow to reproduce the bug?

1. Open study from study browser
2. Click MPR toolbar button

**app-config.js**
```js
window.config = {
    routerBasename: "/",
    extensions: [],
    modes: [],
    showStudyList: !0,
    maxNumberOfWebWorkers: 4,
    omitQuotationForMultipartRequest: !0,
    showLoadingIndicator: !0,
    maxNumRequests: {
        interaction: 100,
        thumbnail: 75,
        prefetch: 10
    },
    dataSources: [{
        friendlyName: "dcmjs DICOMWeb Server",
        namespace: "@ohif/extension-default.dataSourcesModule.dicomweb",
        sourceName: "dicomweb",
        configuration: {
            name: 'Orthanc',
	    wadoUriRoot: '/orthanc/wado',
	    qidoRoot: '/orthanc/dicom-web',
	    wadoRoot: '/orthanc/dicom-web',
            qidoSupportsIncludeField: !1,
            imageRendering: "wadors",
            thumbnailRendering: "wadors",
            enableStudyLazyLoad: !0,
            supportsFuzzyMatching: !1,
        }
    }, {
        friendlyName: "dicom json",
        namespace: "@ohif/extension-default.dataSourcesModule.dicomjson",
        sourceName: "dicomjson",
        configuration: {
            name: "json"
        }
    }, {
        friendlyName: "dicom local",
        namespace: "@ohif/extension-default.dataSourcesModule.dicomlocal",
        sourceName: "dicomlocal",
        configuration: {}
    }],
    httpErrorHandler: e => {
        console.warn(e.status), console.warn("test, navigate to https://ohif.org/")
    },
    defaultDataSourceName: "dicomweb",
    hotkeys: [{
        commandName: "incrementActiveViewport",
        label: "Next Viewport",
        keys: ["right"]
    }, {
        commandName: "decrementActiveViewport",
        label: "Previous Viewport",
        keys: ["left"]
    }, {
        commandName: "rotateViewportCW",
        label: "Rotate Right",
        keys: ["r"]
    }, {
        commandName: "rotateViewportCCW",
        label: "Rotate Left",
        keys: ["l"]
    }, {
        commandName: "invertViewport",
        label: "Invert",
        keys: ["i"]
    }, {
        commandName: "flipViewportHorizontal",
        label: "Flip Horizontally",
        keys: ["h"]
    }, {
        commandName: "flipViewportVertical",
        label: "Flip Vertically",
        keys: ["v"]
    }, {
        commandName: "scaleUpViewport",
        label: "Zoom In",
        keys: ["+"]
    }, {
        commandName: "scaleDownViewport",
        label: "Zoom Out",
        keys: ["-"]
    }, {
        commandName: "fitViewportToWindow",
        label: "Zoom to Fit",
        keys: ["="]
    }, {
        commandName: "resetViewport",
        label: "Reset",
        keys: ["space"]
    }, {
        commandName: "nextImage",
        label: "Next Image",
        keys: ["down"]
    }, {
        commandName: "previousImage",
        label: "Previous Image",
        keys: ["up"]
    }, {
        commandName: "setToolActive",
        commandOptions: {
            toolName: "Zoom"
        },
        label: "Zoom",
        keys: ["z"]
    }, {
        commandName: "windowLevelPreset1",
        label: "W/L Preset 1",
        keys: ["1"]
    }, {
        commandName: "windowLevelPreset2",
        label: "W/L Preset 2",
        keys: ["2"]
    }, {
        commandName: "windowLevelPreset3",
        label: "W/L Preset 3",
        keys: ["3"]
    }, {
        commandName: "windowLevelPreset4",
        label: "W/L Preset 4",
        keys: ["4"]
    }, {
        commandName: "windowLevelPreset5",
        label: "W/L Preset 5",
        keys: ["5"]
    }, {
        commandName: "windowLevelPreset6",
        label: "W/L Preset 6",
        keys: ["6"]
    }, {
        commandName: "windowLevelPreset7",
        label: "W/L Preset 7",
        keys: ["7"]
    }, {
        commandName: "windowLevelPreset8",
        label: "W/L Preset 8",
        keys: ["8"]
    }, {
        commandName: "windowLevelPreset9",
        label: "W/L Preset 9",
        keys: ["9"]
    }]
};
```

**nginx.conf**
```
worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    #gzip  on;

    server    {
       
        listen 8099;
        server_name default_server;
       
		location / {
			try_files $uri $uri/ /index.html;
				  }
				  
        location /orthanc/{
            access_log  logs/access.log;
            proxy_pass http://localhost:8042;
            proxy_set_header HOST $Host:8099/orthanc/;
            proxy_set_header X-Real-IP $remote_addr;

            rewrite /orthanc(.*) $1 break;

            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Origin' '*';

        }
       
    }

}
```

**Comment by pwespi** [comment]
See:

* https://www.cornerstonejs.org/docs/getting-started/scope#browser-support
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements

These headers need to be set:
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

**Comment by Georift** [comment]
Hey @ranasrule, looks like you've solved this problem, if so would you mind closing the issue?

**Comment by ranasrule** [comment]
> Hey @ranasrule, looks like you've solved this problem, if so would you mind closing the issue?

well I thought the issue was resolved but I still get the same issue when accessing the viewer via the internet whereas it no longer happens when running the viewer on localhost....any ideas?

**Comment by Gabsha** [comment]
Hi! Yesterday I ran into the same issue. After adding the COEP and the COOP headers, it fixed the problem in Firefox, but Chromium (Version 107.0.5304.110) kept complaining that the workers were still missing headers. After reading a bit on the topic on [this page](https://web.dev/coop-coep/),  I realised that workers served with COEP set at `require-corp` needs to have a Cross-Origin-Resource-Policy explicitly set too. You  might want to try adding the following header too:

```
Cross-Origin-Resource-Policy: same-origin
```
For me it fixed the issue of the workers in Chrome.
Hope that helps!

**Comment by Georift** [comment]
@ranasrule Are you serving the internet version with the same headers as in localhost?

Can you share the response headers that are returning for the `index.html` in your production environment? Sanitizing any auth headers is probably advisable.

**Comment by ranasrule** [comment]
> Hi! Yesterday I ran into the same issue. After adding the COEP and the COOP headers, it fixed the problem in Firefox, but Chromium (Version 107.0.5304.110) kept complaining that the workers were still missing headers. After reading a bit on the topic on [this page](https://web.dev/coop-coep/), I realised that workers served with COEP set at `require-corp` needs to have a Cross-Origin-Resource-Policy explicitly set too. You might want to try adding the following header too:
> 
> ```
> Cross-Origin-Resource-Policy: same-origin
> ```
> 
> For me it fixed the issue of the workers in Chrome. Hope that helps!

this seems to have fixed it...thanks

**Comment by Georift** [comment]
Glad it's fixed. If there was nothing else could we close this issue?

**Comment by ranasrule** [comment]
> Glad it's fixed. If there was nothing else could we close this issue?

yeah I don't see a reason why not....thanks for all the help

**Comment by mokbelt** [comment]
Dears, Could you please advise where shall I insert the above headers?

**Comment by Gabsha** [comment]
@mokbelt Your web server needs to provide those headers. For instance if you are using `nginx`, you could use the `add_header` directive in a server block, such as:
```nginx
server {
        listen 80;
        listen [::]:80;

        server_name my-ohif.my-org.com;

        location / {
                add_header Cross-Origin-Opener-Policy same-origin;
                add_header Cross-Origin-Embedder-Policy require-corp;
                add_header Cross-Origin-Resource-Policy same-origin;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
                proxy_pass http://localhost:8000;
        }
}

```

**Comment by mokbelt** [comment]
Merci @Gabsha 
I added this on my nginx conf on ubuntu 20 but still getting: Uncaught (in promise) Error: Your page is NOT cross-origin isolated, see https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated

This is my conf file:
**server {
  listen 3001;
  location / {
    root   /ohifv3/Viewers-3-stable/platform/viewer/dist;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;

    add_header Cross-Origin-Opener-Policy same-origin;
    add_header Cross-Origin-Embedder-Policy require-corp;
    add_header Cross-Origin-Resource-Policy same-origin;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

  }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /ohifv3/Viewers-3-stable/platform/viewer/dist;
  }
}**

**Comment by mokbelt** [comment]
:-( I removed but still getting same... The headers are coming in the response...
![image](https://user-images.githubusercontent.com/56265911/205120431-1b080e12-ce5d-43ae-8bc5-28e7bb5f033c.png)
Any other possible thing I missed?

**Comment by pwespi** [comment]
It needs to be served over https (not http).

**Comment by mokbelt** [comment]
@pwespi Patrick Thanks!! Worked with https!
@Gabsha Gabriel merci bcp pour ton assistance!
