### ISSUE TITLE
MPR generation fails ("Uncaught (in promise) Error: CACHE_SIZE_EXCEEDED" error in browser console)

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#3038]
On the latest version of OHIF V3 MPR generation fails with the following error in the browser console "Uncaught (in promise) Error: CACHE_SIZE_EXCEEDED" . Im running OHIF in Nginx v1.23.2. Im posting my Nginx config file, OHIF app-config.js contents files below:

![Untitled](https://user-images.githubusercontent.com/5023419/203775894-aee3466d-52a3-4d03-9126-ec873b138ce8.png)

**app-config.js**
```js
window.config = {
    routerBasename: "/",
    extensions: [],
    modes: [],
    showStudyList: !0,
    maxNumberOfWebWorkers: 4,
    omitQuotationForMultipartRequest: !0,
    showLoadingIndicator: !0,
    maxNumRequests: {
        interaction: 100,
        thumbnail: 75,
        prefetch: 10
    },
    dataSources: [{
        friendlyName: "dcmjs DICOMWeb Server",
        namespace: "@ohif/extension-default.dataSourcesModule.dicomweb",
        sourceName: "dicomweb",
        configuration: {
            name: 'Orthanc',
	    wadoUriRoot: '/orthanc/wado',
	    qidoRoot: '/orthanc/dicom-web',
	    wadoRoot: '/orthanc/dicom-web',
            qidoSupportsIncludeField: !1,
            imageRendering: "wadors",
            thumbnailRendering: "wadors",
            enableStudyLazyLoad: !0,
            supportsFuzzyMatching: !1,
        }
    }, {
        friendlyName: "dicom json",
        namespace: "@ohif/extension-default.dataSourcesModule.dicomjson",
        sourceName: "dicomjson",
        configuration: {
            name: "json"
        }
    }, {
        friendlyName: "dicom local",
        namespace: "@ohif/extension-default.dataSourcesModule.dicomlocal",
        sourceName: "dicomlocal",
        configuration: {}
    }],
    httpErrorHandler: e => {
        console.warn(e.status), console.warn("test, navigate to https://ohif.org/")
    },
    defaultDataSourceName: "dicomweb",
    hotkeys: [{
        commandName: "incrementActiveViewport",
        label: "Next Viewport",
        keys: ["right"]
    }, {
        commandName: "decrementActiveViewport",
        label: "Previous Viewport",
        keys: ["left"]
    }, {
        commandName: "rotateViewportCW",
        label: "Rotate Right",
        keys: ["r"]
    }, {
        commandName: "rotateViewportCCW",
        label: "Rotate Left",
        keys: ["l"]
    }, {
        commandName: "invertViewport",
        label: "Invert",
        keys: ["i"]
    }, {
        commandName: "flipViewportHorizontal",
        label: "Flip Horizontally",
        keys: ["h"]
    }, {
        commandName: "flipViewportVertical",
        label: "Flip Vertically",
        keys: ["v"]
    }, {
        commandName: "scaleUpViewport",
        label: "Zoom In",
        keys: ["+"]
    }, {
        commandName: "scaleDownViewport",
        label: "Zoom Out",
        keys: ["-"]
    }, {
        commandName: "fitViewportToWindow",
        label: "Zoom to Fit",
        keys: ["="]
    }, {
        commandName: "resetViewport",
        label: "Reset",
        keys: ["space"]
    }, {
        commandName: "nextImage",
        label: "Next Image",
        keys: ["down"]
    }, {
        commandName: "previousImage",
        label: "Previous Image",
        keys: ["up"]
    }, {
        commandName: "setToolActive",
        commandOptions: {
            toolName: "Zoom"
        },
        label: "Zoom",
        keys: ["z"]
    }, {
        commandName: "windowLevelPreset1",
        label: "W/L Preset 1",
        keys: ["1"]
    }, {
        commandName: "windowLevelPreset2",
        label: "W/L Preset 2",
        keys: ["2"]
    }, {
        commandName: "windowLevelPreset3",
        label: "W/L Preset 3",
        keys: ["3"]
    }, {
        commandName: "windowLevelPreset4",
        label: "W/L Preset 4",
        keys: ["4"]
    }, {
        commandName: "windowLevelPreset5",
        label: "W/L Preset 5",
        keys: ["5"]
    }, {
        commandName: "windowLevelPreset6",
        label: "W/L Preset 6",
        keys: ["6"]
    }, {
        commandName: "windowLevelPreset7",
        label: "W/L Preset 7",
        keys: ["7"]
    }, {
        commandName: "windowLevelPreset8",
        label: "W/L Preset 8",
        keys: ["8"]
    }, {
        commandName: "windowLevelPreset9",
        label: "W/L Preset 9",
        keys: ["9"]
    }]
};
```

**nginx.conf**
```

worker_processes  5;

events {
    worker_connections  4096;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    proxy_connect_timeout 3200s;
	proxy_read_timeout 3000s;
    #gzip  on;

    server    {
       
        listen 8099;
        server_name default_server;
       
		location / {
			try_files $uri $uri/ /index.html;
			add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Origin' '*';
			add_header 'Cross-Origin-Opener-Policy' 'same-origin';
			add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
				  }
				  
        location /orthanc/{
        
            proxy_pass http://localhost:8042;
            proxy_set_header Authorization "Basic YWxuYXNhcnBhY3M6YWxuYXNhcnBhY3M1Nzc=";
            proxy_set_header HOST $Host:8099/orthanc/;
            proxy_set_header X-Real-IP $remote_addr;

            rewrite /orthanc(.*) $1 break;

            

        }
       
    }

}
```

**Comment by ranasrule** [comment]
this error doesn't occur on small series but rather large ones with approximately 500+ instances and a size of 350+ mb

**Comment by ranasrule** [comment]
Anyone?

**Comment by Georift** [comment]
I think there will always be a tension between how well OHIF can manage the memory of large scans, and what the upper limit is of the browser. I'm not as deeply versed on the OHIF codebase, so maybe some others will have some recommendations.

Just a thought, it looks as if you're running Firefox? Could you also try on other browsers see if the issue occurs at the same point in the loading?

**Comment by ranasrule** [comment]
> I think there will always be a tension between how well OHIF can manage the memory of large scans, and what the upper limit is of the browser. I'm not as deeply versed on the OHIF codebase, so maybe some others will have some recommendations.
> 
> Just a thought, it looks as if you're running Firefox? Could you also try on other browsers see if the issue occurs at the same point in the loading?

I've tried on Firefox, Chrome and Edge and gotten the same results. The issue occurs immediately after the MPR button is pressed.

**Comment by Georift** [comment]
Perhaps you can share a zip with the images that caused this crash. Along with some system specs of the machine that you're running it on. Might help someone if they come across this issue and have time to dig into it?

**Comment by ranasrule** [comment]
> Perhaps you can share a zip with the images that caused this crash. Along with some system specs of the machine that you're running it on. Might help someone if they come across this issue and have time to dig into it?

The machine has good specs ie i7 7th gen processor with 32gb ram. I can provide a study in private to you if you can provide your contact info.

**Comment by ranasrule** [comment]
Would one of the devs please look into this? Its a pretty major issue.

@pieper @fedorov @swederik @rodrigoea @dannyrb @sedghi

**Comment by Georift** [comment]
Hi @ranasrule, not the greatest etiquette to go tagging everyone indiscriminately in the project.

Perhaps you can dive into this issue a little more yourself, [this method looks interesting](https://github.com/cornerstonejs/cornerstone3D-beta/blob/b80ea407eaa59da10fe06d0794b0356416410fdc/packages/core/src/cache/cache.ts#L41).

**Comment by ranasrule** [comment]
> Hi @ranasrule, not the greatest etiquette to go tagging everyone indiscriminately in the project.
> 
> Perhaps you can dive into this issue a little more yourself, [this method looks interesting](https://github.com/cornerstonejs/cornerstone3D-beta/blob/b80ea407eaa59da10fe06d0794b0356416410fdc/packages/core/src/cache/cache.ts#L41).

Im really not much of a JS developer but If I play around with this code how will it integrate into the OHIF v3 stable branch code that I use to build OHIF viewer ? The code you pointed to is in a totally different repo.

**Comment by ranasrule** [comment]
> Perhaps you can share a zip with the images that caused this crash. Along with some system specs of the machine that you're running it on. Might help someone if they come across this issue and have time to dig into it?

If I send you one of the studies causing this issue would you be willing to look into it?

**Comment by sedghi** [comment]
before doing that can you take a look at https://github.com/OHIF/Viewers/issues/3207

**Comment by ranasrule** [comment]
> before doing that can you take a look at #3207

thank you for the reply. I tried all possible solutions outlined in the link you provided....still the same error no matter which ANGLE I use

![gg](https://user-images.githubusercontent.com/5023419/222972839-ae55c3bd-f503-48e2-8456-9c94b1d7906c.png)

**Comment by sedghi** [comment]
probably your series is quite big that can't go MPR

**Comment by ranasrule** [comment]
> probably your series is quite big that can't go MPR

there is a limit in OHIF to how big a study can be?

**Comment by sedghi** [comment]
No limit, but for MPR seems like the cache is being full, maybe try increasing the cache limit too 
`cornerstone.cache.setMaxCacheSize(...)`

**Comment by ranasrule** [comment]
> MPR hols the stack viewport images, because usually it needs to go back to stack, so I guess the images load, but then the volume with same number of slices fail, maybe increasing our cache from 1GB to 2GB solves the issue for you

so how do I go about increasing the cache size? is there an option in the app-config.js file?

**Comment by sedghi** [comment]
you should do it inside the `extensions/cornerstone/src/init.tsx` with `cornerstone.cache.setMaxCacheSize(...)`

**Comment by ranasrule** [comment]
> you should do it inside the `extensions/cornerstone/src/init.tsx` with `cornerstone.cache.setMaxCacheSize(...)`

So just do the following?


change
```
const MAX_CACHE_SIZE_1GB = 1073741824;
  const maxCacheSize = appConfig.maxCacheSize;
  cornerstone.cache.setMaxCacheSize(
    maxCacheSize ? maxCacheSize : MAX_CACHE_SIZE_1GB
  );

```

to  

```

const MAX_CACHE_SIZE_2GB = 2147483648;
  const maxCacheSize = appConfig.maxCacheSize;
  cornerstone.cache.setMaxCacheSize(
    maxCacheSize ? maxCacheSize : MAX_CACHE_SIZE_2GB 
  );
```

**Comment by sedghi** [comment]
oh seems like we already have a config key for it, so just add `maxCacheSize` in your config and set it to 2GB, if it can't do 1.8 GB or so

**Comment by ranasrule** [comment]
> oh seems like we already have a config key for it, so just add `maxCacheSize` in your config and set it to 2GB, if it can't do 1.8 GB or so

ok....do I set in GB or Bytes ?

**Comment by sedghi** [comment]
Bytes

**Comment by hwanython** [comment]
Hi, [ranasrule](https://github.com/ranasrule)

is that solved?

**Comment by sedghi** [comment]
Maybe your GPU doesn't have enough memory. You can give it a shot by turning on the 16-bit texture and see if it helps reduce the memory usage on your GPU and RAM. Just keep in mind that not all hardware might support this feature. You can check the webgl2 report to find out more about it.

- https://docs.ohif.org/configuration/configurationFiles

`use16BitDataType `
