### ISSUE TITLE
unable to see text because of its colour

### ISSUE THREAD

**Issue by JennyLeePMH** [OHIF/Viewers#3043]
> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

### When saving an SR, unable to see text on button because of its colour

See attached.

```js
Please use code blocks to show formatted errors or code snippets
```
![odd_colour_measurement](https://user-images.githubusercontent.com/4551564/204035248-fb274cd3-0f38-4ae0-a80d-6d1e3d8faf07.PNG)

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by JennyLeePMH** [comment]
Forgot to mention, this is from OHIF's v3-stable branch.

**Comment by Georift** [comment]
I can see this on the current [demo url](https://v3-demo.ohif.org/). Likely related to this change: #3031?

**Comment by JennyLeePMH** [comment]
thanks.
