### ISSUE TITLE
Coronal view image location display in v3 is reverse of that expected

### ISSUE THREAD

**Issue by xtfer** [OHIF/Viewers#3046]
The coronal view in MPR mode in v3 shows Left to Right, where it should show Right to Left.

This is just a follow up on https://cornerstonejs.slack.com/archives/CEM89S010/p1669345052706219.

Screenshot showing heart on wrong side.

<img width="1187" alt="CleanShot 2022-11-29 at 09 20 29@2x" src="https://user-images.githubusercontent.com/40190/204394195-a7b16c22-9126-4c08-81aa-4b749db99e27.png">

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
