### ISSUE TITLE
v3.3 - Series does not auto-populate in multiple viewport

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#3048]
### Describe the Bug

Viewports are not automatically populated in version 3.3 if layout is chosen more than 1. This feature is working fine in v2.0 however, v3.3 does not replicate this feature. This feature is very crucial to have.

### What steps can we follow to reproduce the bug?

1. Go a deployment of OHIF from the master branch
2. Open a study with multiple series
3. Use the grid layout tool to create an multiple viewports. For example, 2 x 2 viewports.
4. Observe the viewports are automatically populated with series.
5. Go a deployment of OHIF from the master branch
6. Open a study with multiple series
7. Use the grid layout tool to create an multiple viewports. For example, 2 x 2 viewports.
8. Observe the viewports does not automatically populated with series.
9. Is the difference between step 8 and step 4 intentional or is it a bug?

This issue was previously mentioned in [August by JennyLee](https://github.com/OHIF/Viewers/issues/2871) but no response was posted regarding her inquiry.

Thank you!!

**Comment by sedghi** [comment]
Yeah that is a limitation currently, and on the roadmap to get fixed soon.

**Comment by jbocce** [comment]
Hi @richsmith123 , I believe PR https://github.com/OHIF/Viewers/pull/3154 addresses this.
