### ISSUE TITLE
Loading dcm files from other project

### ISSUE THREAD

**Issue by eagle49** [OHIF/Viewers#305]
Hi @swederik 
Thank you for your support for the issues until now.
I have urgent one more issue with StandaloneViewer.
I`m using port 80 for the origin php project(var/www/html) and 3000 port for StandAloneViewer(var/www/html/dicom).
When loading StandAloneViewer, it copies file to StandAloneViewer public folder(bundle/program/web.brower/app) from current project(var/www/html/uploads/...) and load these dcm files.
![image](https://user-images.githubusercontent.com/29590370/47151197-ad46cf00-d30b-11e8-9d2d-398107d5731b.png)

But in the first, it couldn`t display the dcm files in public folder.
I don`t know the program structure in depth, but finally I found that these files list should be added in program.json files(program/web.browser/program.json).
![image](https://user-images.githubusercontent.com/29590370/47151370-1f1f1880-d30c-11e8-8639-2bfad1c5ea9a.png)

I added theses files list programmitically when copy files to public folder but also not working properly.
It is working after restart the node server.
Do you have any idea to working them not restart the node, or any other method?
Thank you.

**Comment by liuchen1393193701** [comment]
hai,i see your web have freehand,can you tell me how to realize this function

**Comment by liuchen1393193701** [comment]
I see you project toolbar have freehand,can you tell me how to realase this function?
