### ISSUE TITLE
app-config settings are ignored in OHIF v3 3.3.0

### ISSUE THREAD

**Issue by mokbelt** [OHIF/Viewers#3051]
For V 3.3.0 the configuration settings are ignored, specially if using
**showStudyList : false
showLoadingIndicator: true**

are not applied.
The Study list is still visible and accessible (in V2 it gives Page not found) and no loading indicator is visible.

**Comment by ranasrule** [comment]
I can confirm that setting **showStudyList: !1** has no affect as study list is still visible and accessible. Whereas setting **showLoadingIndicator: !0** does show the loading indicator and setting it to **showLoadingIndicator: !1** disables it.

**Comment by sedghi** [comment]
This will get fixed with this https://github.com/OHIF/Viewers/pull/3009

**Comment by mokbelt** [comment]
@ranasrule showLoadingIndicator: !0 is not showing an indicator at my side...
![image](https://user-images.githubusercontent.com/56265911/205289792-084e9107-fcaf-43b1-9776-0d2961906b79.png)

**Comment by fordanic** [comment]
In my case using the latest built Docker image the app-config file is ignored completely. For instance, trying to change the servers settings, but regardless of what I write it runs with the default settings.

**Comment by sedghi** [comment]
I just merged a fix for app config fixes, can you try again? @fordanic 

@mokbelt there is no loading indicator for thumbnails

**Comment by sedghi** [comment]
what is your app config?

**Comment by fordanic** [comment]
@sedghi, sorry for the late response. Running with the default config, no changes made.

**Comment by elamathis18** [comment]
hi, running into the same issue with configuration not being applied. 
Is there any workaround to this in the meantime ?

**Comment by jbocce** [comment]
With https://github.com/OHIF/Viewers/pull/3114 showStudyList:false (and showStudyList:!1, etc.) will prohibit the search page from being navigated to via the default route. Note that the chevron in the top left corner of the viewer was already not displayed accordingly.

**Comment by jbocce** [comment]
FYI showLoadingIndicator:false is meant to hide the following and from what I can tell it does so correctly.

![image (1)](https://user-images.githubusercontent.com/109477394/211915293-6705c97f-c4bc-403b-9e7e-768592dca499.png)

**Comment by jbocce** [comment]
> @ranasrule showLoadingIndicator: !0 is not showing an indicator at my side... ![image](https://user-images.githubusercontent.com/56265911/205289792-084e9107-fcaf-43b1-9776-0d2961906b79.png)

@mokbelt please clarify what your expectation is for showLoadingIndicator: !0.

**Comment by jbocce** [comment]
> @sedghi, sorry for the late response. Running with the default config, no changes made.

@fordanic perhaps https://github.com/OHIF/Viewers/pull/3081 fixed your docker issues? Furthermore I have also checked that the config settings mentioned in this issue are applied.

**Comment by jbocce** [comment]
Fixed by https://github.com/OHIF/Viewers/pull/3114
