### ISSUE TITLE
TMTV mode always uses an SUV based window and Level of WW 5 WL 3 even if SUV can't be calculated

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3064]
Repository URL
https://github.com/OHIF/Viewers/tree/v3-stable
Version number
3.3.0
Build number
0
UHN Version
2.0.0 (11/27/2022, 3:03:57 PM)
Browser
Chrome 107.0.0
OS
Windows 10

TMTV mode uses a default window level of WW 5 and WL 3 for all PET data sets.  This is typically okay presuming the correct AC PET has been selected however if SUV can not be calculated for whatever reason (No AC available, no PT WT, injection time errors, no injected dose) The image will display in BQML but with a Window Level of 5/3 which makes for a large red blob.

Below is an example set from TCIA that shows this in action.

https://fileshare.uhn.ca/download/58160ff5-bbf2-4084-968e-17254d06535b  password "factor"
Please note that this file upload will expire in 30 days. 

![image](https://user-images.githubusercontent.com/112980389/205755235-20706211-21f2-40ab-ba26-2f45f24c9681.png)

You can see that the AC image was correctly selected but as per the message in the console, there was an issue with the time stamp so the image is being displayed in BQML.

Error: Decay time cannot be less than zero
    at calculate-suv.esm.js:443:13
    at Array.map (<anonymous>)
    at VQ (calculate-suv.esm.js:438:20)
    at GQ (calculate-suv.esm.js:503:26)
    at Object.QQ [as callback] (init.js:54:25)
    at pubSubServiceInterface.js:86:16
    at Array.forEach (<anonymous>)
    at Object.u [as _broadcastEvent] (pubSubServiceInterface.js:85:31)
    at Object.addInstances (DicomMetadataStore.js:203:10)
    at f (index.js:955:9)
Mode.tsx:40 gettingds

If I use a window of 20000 and Level of 15000 the image is visible however I believe this image set also has variable rescale slope and intercept so the rendering is not working correctly for that either.

![image](https://user-images.githubusercontent.com/112980389/205755746-b0b16f03-ab3f-4498-8354-acbec4abea64.png)

Finally I'd also suggest not using fixed values of WW 5 and WL 3 and instead use the dicom meta data tags already embedded in the images which you are using for CT.  Just convert those values to SUV (If SUV is calculable) and then use that value such that the image is scaled to a reasonable value, 5 and 3 is not a perfect window level for all PET images (though because SUV self normalizes it's not bad most of the time.

**Comment by BrandonDatUHN** [comment]
If an image can not be displayed in SUV, it should be displayed in whatever the default units are (BQML or propcounts) using the default window and level from the DICOM header.

**Comment by DevOriginalWang** [comment]
Hi,

I am facing the same issue. Did you or anybody else figure out a solution to this?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
