### ISSUE TITLE
The patient ID is not visible anywhere in TMTV mode.

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3065]
In TMTV mode the patient ID is not visible anywhere in the viewer so the user has no way of knowing what patient they have open.  

![image](https://user-images.githubusercontent.com/112980389/205756919-b1a3c8b3-e955-4863-8e48-2a1e991a110f.png)

This information is hidden in Basic Viewer which I understand from a privacy perspective but it's still available to the user.
![image](https://user-images.githubusercontent.com/112980389/205757076-2868bffd-eada-4033-a1b7-084676e9bc0a.png)

**Comment by sedghi** [comment]
We are planning to revamp the Toolbar to include patientID.
Meanwhilte TMTV has added back the left panel
