### ISSUE TITLE
v3 - measurements are not being cleared when stopping tracking and it causes ghost measurements being added when new tracking starts

### ISSUE THREAD

**Issue by md-prog** [OHIF/Viewers#3069]
This is related to measurment-tracking extension.

### How to reproduce

1. start a measurement tracking, by adding a new measurement or by hydrating an SR.
2. stop tracking
3. start a new tracking by adding a new measurement or by hydrating an SR.
4. Check the measurements panel, to see some ghost (added from previous tracking) measurements are there.

**Comment by sedghi** [comment]
This is by design as far as I know. I can check

**Comment by md-prog** [comment]
The intention of the design should be documented, I think.

Now, it looks weird especially when we are dealing with measurement SRs.
1) Open one SR, 2) cancel tracking 3) Open another SR, and we see measurements that are from previous SR and the only way we can clear them and properly display is to refresh

**Comment by sedghi** [comment]
Yeah that doesn't makes sense. We should deal with that. But measurement tracking purpose is for continuing on the previously untracked measurements
