### ISSUE TITLE
Why can't I use JSON data source schema after build

### ISSUE THREAD

**Issue by starSinking** [OHIF/Viewers#3075]
branch: v3-stable

After running yarn run build command, I uploaded the generated dist folder to the server, but I could not access the page of dicomjson mode. I wonder why that is

![1670922282532_C03600B0-1CDB-44cf-AA20-7D27218C2C7A](https://user-images.githubusercontent.com/43055274/207478974-c7da60dc-d532-401f-af11-606231c28ce1.png)

**Comment by Zaid-Safadi** [comment]
I wonder if this has to do with the web host and rewrites: https://render.com/docs/deploy-create-react-app#using-client-side-routing

Does the URL works for you in dev (yarn start)?

**Comment by starSinking** [comment]
It was the routing. I fixed it

**Comment by Zaid-Safadi** [comment]
@starSinking , glad it worked for you. is there something you can share about your environment and what did you do to fix it?
