### ISSUE TITLE
User Preferences 

### ISSUE THREAD

**Issue by ramonsousa89** [OHIF/Viewers#308]
Hello,

When I use OHIF Viewer I try to use the keyboard shortcuts and it does not work, then I go to Options, User Preferences and activate the shortcut keys.

It is always necessary to do this with each new study and this is not good.

Do you have this user preference setting already enabled by default? are set automatically without the user having to go to Options, Prefe ...

**Comment by swederik** [comment]
Yeah I noticed this too...
