### ISSUE TITLE
Search for Dicom tag browswer

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3083]
Currently the DICOM Tag Browser (under more tools) in v3-demo.ohif.org does not have search for specific tag 

![image](https://user-images.githubusercontent.com/7490180/208131034-7d05880b-3bc7-4f32-95e4-e40cb4781ef6.png)

We should add a input text field (can be borrowed from the same component that the worklist page search is using), and add this feature 

Slicer has a nice search 

![image](https://user-images.githubusercontent.com/7490180/208131282-c9e64813-3fad-431d-805a-c4031b19e291.png)

**Comment by fedorov** [comment]
I know it's a separate feature, but if you discuss improvements to DICOM browser, collapsible sequence items would be another one that would be VERY helpful.

**Comment by sedghi** [comment]
@fedorov Agreed, we can certainly think about that after v3 -> master release

**Comment by sedghi** [comment]
was checking meddream and they have a nice filtering

![image](https://user-images.githubusercontent.com/7490180/210837883-346ac5a4-6700-48ea-8308-a6bcab57154d.png)

https://demo.softneta.com/?study=1.2.826.0.1.3680043.8.1055.1.20161012115812848.450575715.8637545

**Comment by jbocce** [comment]
PR for this is https://github.com/OHIF/Viewers/pull/3306
