### ISSUE TITLE
View DICOM mpeg file

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#309]
Hello,

I got error  when view dicom mpeg file as below.
Uncaught (in promise) Error: No decoder for transfer syntax 1.2.840.10008.1.2.4.100

I know OHIF don't support viewing dicom mpeg (2, 4) yet. Do you have a plan for that?
Could you please show me a place where I can research to add more transfer syntax?

**Comment by swederik** [comment]
I don't have any plans for it at the moment, but I'd be happy to take a PR.

The relevant location is here: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/b468ad706276daa4c3cf6aefb3beca924a588b61/src/imageLoader/decodeImageFrame.js#L51

**Comment by lam0620** [comment]
Thanks @swederik 
Sorry, I've already re-built cornerstoneWADOImageLoader. Could you please guide me how to add to OHIF Viewer for test?

My dicom mpeg is stored in pacs server. When OHIF viewer get, server site will parse the file to multi-frame and return stream.

**Comment by dannyrb** [comment]
@lam0620, you may want to look at some of the Viewport OHIF extensions that allow you to conditionally handle viewing one or more specific transfer syntaxes. Similar to the PDF extension, you could leverage a custom component to view the MPEG file.

**Comment by swederik** [comment]
Could you provide a sample DICOM MPEG? The only ones I can find do not play in Osirix, so I don't really trust them.

**Comment by lam0620** [comment]
@dannyrb 
Thank you! I'll try with OHIF new React version

@swederik 
https://www.mediafire.com/file/vklb8g4stxqxnrm/Anonymized20170816_Noisoi1_mpeg4.dcm/file
https://www.mediafire.com/file/8g2yzuyvn7cqqrj/ETIAM_video_001_mpeg2.dcm/file

Download links are valid in 14 days!
