### ISSUE TITLE
Specify list of required metadata for the viewer to function correctly

### ISSUE THREAD

**Issue by shlomgad** [OHIF/Viewers#3093]
For OHIF Version 3
---------------------
When loading instances via the dicomjson method, all metadata must be prepared in advance and fed to the viewer by means of a URL to a JSON file.
Please make clear what are the minimum / recommended scopes of required metadata for each modality.

For example, by trial and error only,  these observations were made:
- When displaying color doppler ultrasound instances, 'PlanarConfiguration' must be specified in the metadata, while other metadata fields which are relevant for other modalities, such as 'WindowCenter' and 'WindowWidth' must be removed in order to achieve a correct display (even if those redundant tags are empty).

- Adding the 'NumberOfFrames' tag to the metadata breaks the display of multiframe ultrasound images (only the first frame is displayed).

- Frames are zero-indexed (to get frame 1 need to pass &frame=0)

#1500 listed metadata for version 2, but was not updated for version 3. It would be beneficial to post the minimum set of fields required for the most common types of modalities (CT/US/PT/DX) and instance types (for example single frame vs. multi frame).

Thanks you for this amazing project.

**Comment by sedghi** [comment]
I think that is reasonable ask. We will do it

**Comment by sedghi** [comment]
Seems like these are necessary, but I will investigate which feature requires which metadata

```js
PatientID,
PatientName,
PatientSex,
PatientAge,
PatientBirthDate,
PatientSize,
PatientWeight,
StudyInstanceUID,
SeriesInstanceUID,
SOPInstanceUID,
SOPClassUID,
Modality,
NumberOfFrames,
Rows,
Columns,
SamplesPerPixel,
PhotometricInterpretation,
PlanarConfiguration,
BitsAllocated,
BitsStored,
HighBit,
PixelRepresentation,
PixelAspectRatio,
InstanceNumber,
SeriesDate,
SeriesTime,
FrameTime,
ImagePositionPatient,
ImageOrientationPatient,
ImageType,
PixelSpacing,
StudyDescription,
SeriesNumber,
SeriesDescription,
```

**Comment by DevOriginalWang** [comment]
Hi @sedghi , I've added all those DICOM Tags that you've suggested, but it still doesn't seem to work. When I open the study, it is unable to open any PTs but it can load everything else. Do you know which tags I may be missing?

**Comment by sedghi** [comment]
Oh interesting, so for PT, it should be able to show you something but if you you want scaled PT to generate PT SUV then you need these I assume

extensions/default/src/getPTImageIdInstanceMetadata.ts

**Comment by DevOriginalWang** [comment]
Let me clarify some more my issue: 

I'm using Orthanc's DicomWeb in conjunction with the OHIF viewer. Everything functions correctly when Orthanc is set to use Full Dicom Tags. 

In order to optimize loading speeds, I've configured Orthanc to use only MainDicomTags, but the behavior makes it seem like some tags are still missing. 

With MainDicomTags and ExtraMainDicomTags (that include your list above), when I access the study list and open a study, I'm unable to see any PT-related series, and only CT or other series. They don't appear in the Series Panel on the left, nor is it available in the hanging protocol / viewing area.

**Comment by sedghi** [comment]
First, how do you configure Orthanc to only send main tags?

I want to spend time in fixing this issue and documenting it once and for all.

Can you maybe create reproducible steps to the issue for me?

Should I run the orthanc in docker?

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
