### ISSUE TITLE
OHIF V3 is not working for Eye modality

### ISSUE THREAD

**Issue by narbek-abd** [OHIF/Viewers#3094]
Hi. On v2 everything is fine.

My dicom file
[292eadcd-8bfb6560-6ee24272-532f7a62-b142e5f9.zip](https://github.com/OHIF/Viewers/files/10341622/292eadcd-8bfb6560-6ee24272-532f7a62-b142e5f9.zip)

I uploaded by orthanc and opened OHIF:
![image](https://user-images.githubusercontent.com/59279794/210489630-50fbaa7c-d2f2-4413-9f12-e9ddf493e2a5.png)

**Comment by sedghi** [comment]
I can't reproduce this, please re-open if the issue persists

![CleanShot 2023-10-03 at 10 23 39](https://github.com/OHIF/Viewers/assets/7490180/c343057a-a509-4a48-95d2-44744fd147b1)
