### ISSUE TITLE
OHIF v3 Study Prefetch

### ISSUE THREAD

**Issue by elamathis18** [OHIF/Viewers#3096]
Hi, we are recently planning to move our viewer from v2 to v3. Noticed that there is no StudyPrefetch option in the v3 which we use primarily. Is there any way to enable it from the code? Or there is another place to monitor downloading progress, performs some actions based on it and define downloading strategy?

Thank you.

**Comment by salimkanoun** [comment]
So far i think this not yet ported to v3....

**Comment by salimkanoun** [comment]
Maybe @sedghi if he is available. Try to connect to community meeting each Thursday. Maybe with some input we could participate as well

**Comment by sedghi** [comment]
We have another feature request for it that I will track there, so I will close this https://github.com/OHIF/Viewers/issues/3363
