### ISSUE TITLE
Duplicated segmentations objects in segmentation panel in OHIF

### ISSUE THREAD

**Issue by ccosmin97** [OHIF/Viewers#3098]
Hi,

I noticed that my segmentation objects stored in a custom dicom datastore are displayed twice in OHIF, in the segmentation panel, please see below :
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/72577931/210889228-f264b8f4-eb38-41b5-8439-b02b6487a3cf.png">

Upon further inspection of my dicom datastore, no duplicate segmentation objects were found :
2 segmentations objects matched that studyUID, as it should have.
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/72577931/210890371-a732c884-dcfe-4f09-b8aa-f20cacf6696d.png">

Could this be a OHIF display issue ?

Additional information :
OHIF version : 
4.12.41

[OHIF link(ref. screenshot above)](https://fir-idc-prostate-ohif.web.app/viewer/1.3.6.1.4.1.14519.5.2.1.7311.5101.334472970012885968541585915016!secondGoogleServer=/projects/idc-sandbox-003/locations/us-central1/datasets/prostate-seg/dicomStores/prostatex_segnnUNet_datastore)

I am more than happy to provide additional details.
Thank you!

@fedorov

**Comment by fedorov** [comment]
@ccosmin97 can you please confirm you added @GitanjaliChhetri to the DICOM store that you are using?

**Comment by ccosmin97** [comment]
> @ccosmin97 can you please confirm you added @GitanjaliChhetri to the DICOM store that you are using?

@GitanjaliChhetri You have permissions over the datastore mentioned above, prostatex_segnnUNet_datastore.

Please let me know if you encounter any issue!

**Comment by ccosmin97** [comment]
I will confirm the issue has been resolved after rebuilding ohif2servers post commit, thank you @GitanjaliChhetri

**Comment by ccosmin97** [comment]
Duplicated Series Seg Objects is not an issue anymore after your commit :


![image](https://user-images.githubusercontent.com/72577931/222798918-6bcb6f3c-5e2b-47ea-a5f5-5e855d163740.png)

For the same link as above, each segmentation object is only displayed once.

Thank you!

I think we can close the issue.
@GitanjaliChhetri @fedorov
