### ISSUE TITLE
Dicomviewer JPG2000

### ISSUE THREAD

**Issue by itcthienkhiem** [OHIF/Viewers#31]
Dear ad,
OHIF, are support for viewer dicom standard JPG2000?

**Comment by swederik** [comment]
Yes, we are using the Emscripten-compiled OpenJPEG for this. It's in the 'cornerstone' package for the moment:

https://github.com/OHIF/Viewers/tree/master/Packages/cornerstone/client

The performance can be improved, though, and @chafey is in the middle of adding decoding inside web workers, which should be very beneficial.
