### ISSUE TITLE
studylistResult search() filters on Date Exclusive ranges rather than Inclusive

### ISSUE THREAD

**Issue by TravisDean** [OHIF/Viewers#310]
(I'm connected to an orthanc database with DIMSE, in case that changes how search filtering works.)

Packages\Ohif-study-list\client\components\studylist\studylistResult has a bug where the search filters exclusively based on the range indices, rather than inclusively.

This is particularly noticeable if you try to view a study you took that day.

The fix seems easy:
```
[...].isBefore -> [...].isSameOrBefore
[...].isAfter  -> [...].isSameOrAfter
```

I'll look at opening a pull request, but wanted to make sure it was documented first.

**Comment by swederik** [comment]
That is a really annoying bug. We would definitely take a PR to fix it!

**Comment by dannyrb** [comment]
In Version 2:

![image](https://user-images.githubusercontent.com/5797588/58253020-74555980-7d35-11e9-8615-2a9103fc9d71.png)

![image](https://user-images.githubusercontent.com/5797588/58253133-b8e0f500-7d35-11e9-8131-b378f7b08bed.png)

It looks like the dates you select cannot be the same date, but the range does appear to be inclusive.

As this is specific to version 1 and is a bit stale, I'm going to close it for now. I'm more than happy to look at any incoming PRs that resolve this issue for version 1 if they're made in the next couple of months.
