### ISSUE TITLE
MPR doesn't work when I use JSON schema

### ISSUE THREAD

**Issue by kongzhonglei** [OHIF/Viewers#3103]
who can help me?thank you

**Comment by jbocce** [comment]
@kongzhonglei, thank for posting. MPR for dicomjson appears to work fine for me. Perhaps try pulling the latest v3-stable code and trying again? Here is a screenshot of what I experienced...
![image](https://user-images.githubusercontent.com/109477394/212168863-a8b15a35-b2f6-4c0c-a6b1-f29de380d24d.png)

**Comment by jbocce** [comment]
Likely fixed by 1d1b33224ad95a99e669e08ec1da809fb8880102
