### ISSUE TITLE
differences in the measurement

### ISSUE THREAD

**Issue by AlbertoRequena** [OHIF/Viewers#3106]
I use version V3_stable , we have found differences in the measurement, between the tomograph and ohif, any ideas? Thanks

![WhatsApp Image 2023-01-10 at 09 08 55](https://user-images.githubusercontent.com/96824148/211577817-0f73a1cb-0863-4134-b0c5-ca70991d285c.jpeg)
![WhatsApp Image 2023-01-10 at 09 10 40](https://user-images.githubusercontent.com/96824148/211577826-1bf1b639-d608-4b9c-bb79-3eb7105da86b.jpeg)
![WhatsApp Image 2023-01-10 at 09 55 12](https://user-images.githubusercontent.com/96824148/211577827-b9a4f516-76e6-41c2-8f41-4882a2e633a9.jpeg)
![WhatsApp Image 2023-01-10 at 09 55 52](https://user-images.githubusercontent.com/96824148/211577828-7b4051a2-6714-4aa8-8ac6-302936011164.jpeg)

**Comment by sedghi** [comment]
Can you describe what you mean in more details? I can't say what is different from camera photos of your screen.
