### ISSUE TITLE
Two-server issue: Instance-level qualitative annotation not correctly handled with inclusion of a modifier as a child

### ISSUE THREAD

**Issue by deepakri201** [OHIF/Viewers#3108]
Hi, 

I am working with the IDC2Servers branch and am having an issue loading a particular SR that displays slice-level qualitative annotations (see https://github.com/OHIF/Viewers/issues/2797). 

We had originally created a TID1501 SR where the modifier (106233006,SCT,"Topographical modifier") was a sibling of the (82687006, SCT, "Target Region"). This was displayed correctly in OHIF. We now modified our SR so that the modifier (106233006,SCT,"Topographical modifier") is a child of (363698007, SCT, "Finding Site"). Therefore, the slice-level annotation of this modifier is now not displayed in OHIF. 

```
Comprehensive 3D SR Document

Patient             : LUNG1-233 (M, #LUNG1-233)
Series              : BPR landmark annotations (#101)
Manufacturer        : IDC
Preliminary Flag    : FINAL
Completion Flag     : COMPLETE
Verification Flag   : UNVERIFIED
Content Date/Time   : 2023-01-07 23:34:29

<CONTAINER:(,,"Imaging Measurement Report")=CONTINUOUS>
  <has concept mod CODE:(,,"Language of Content Item and Descendants")=(en-US,RFC5646,"English (United States)")>
  <has obs context CODE:(,,"Observer Type")=(121007,DCM,"Device")>
  <has obs context UIDREF:(,,"Device Observer UID")="1.2.826.0.1.3680043.8.498.27240433346411684392357577971054636028">
  <has obs context TEXT:(,,"Device Observer Name")="BodyPartRegression_landmarks">
  <has obs context TEXT:(,,"Device Observer Model Name")="1.1.0">
  <has concept mod CODE:(,,"Procedure reported")=(363679005,SCT,"Imaging procedure")>
  <contains CONTAINER:(,,"Imaging Measurements")=CONTINUOUS>
    <contains CONTAINER:(,,"Measurement Group")=CONTINUOUS>
      <has obs context TEXT:(,,"Tracking Identifier")="Annotations group landmarks 1">
      <has obs context UIDREF:(,,"Tracking Unique Identifier")="1.2.826.0.1.3680043.8.498.16610384701180313622722645145270059837">
      <has concept mod CODE:(,,"Finding Site")=(66794005,SCT,"L1 vertebra")>
        <has concept mod CODE:(,,"Topographical modifier")=(111010,DCM,"Center")>
      <contains IMAGE:(,,"Source")=(CT image,)>
```

Would it be possible to have these latest changes of the SR reflected in the OHIF viewer? I have included a dropbox link that contains the new SR [here](https://www.dropbox.com/s/gi3z1tkrasbs47w/OHIF_slice_level_annotation_issue_01_10_23.zip?dl=0).

Thank you!

Deepa

**Comment by pieper** [comment]
I marked this as an IDC candidate issue for now, but we can discuss on the Thursday call decide if it's an IDC priority issue.  It sounds like it may not be difficult but I'm not familiar with the implementation details.

**Comment by fedorov** [comment]
In the past, modifier was encoded as a sibling to target region and was showing as follows

<img width="665" alt="image" src="https://user-images.githubusercontent.com/313942/212097978-ca74f87b-cd8c-4299-9e40-50b112ad5522.png">

Now that the modifier is a child, how can we indicate this relationship in the UI?

One idea is to have target region red box extend to have the modifier code inside. But I am open to other ideas.

**Comment by GitanjaliChhetri** [comment]
@deepakri201 can you also share the source data? the study in https://github.com/OHIF/Viewers/issues/2797 is a different one.

**Comment by deepakri201** [comment]
Hi, 
Here is a [dropbox link](https://www.dropbox.com/s/emke5s57ap68q1x/OHIF_slice_level_annotation_issue_01_13_23.zip?dl=0) to the source data as well as the SR file. Thanks!

**Comment by fedorov** [comment]
@GitanjaliChhetri can you update us on the status of this issue?

**Comment by fedorov** [comment]
Great news! We can consider refining the UI in a later iteration. 

@wlongabaugh we can then consider updating the test tier once this change is in, and Gitanjali updates the IDC fork?

**Comment by GitanjaliChhetri** [comment]
@fedorov here are some other UI options:


1. https://user-images.githubusercontent.com/112136540/214684594-24b2282c-46e0-40db-aad1-c58e0716997d.mp4



2. https://user-images.githubusercontent.com/112136540/214684625-11c52762-9845-458c-a4ea-7f6b1f66d16e.mp4


3. https://user-images.githubusercontent.com/112136540/214684638-da302455-28f6-4a02-9019-189487ad04a5.mp4

**Comment by fedorov** [comment]
Per discussion, agreed to use the last design with the modification that the modifier should be shifted a little bit to the right from the top concept, in order to indicate the hierarchical relationship. In the future, there is a potential to have sibling modifiers, or modifiers of modifiers, but we will not prioritize this for now.

**Comment by sedghi** [comment]
We are tracking the addition here https://github.com/OHIF/Viewers/issues/3358
Can we close this one?

@fedorov

**Comment by fedorov** [comment]
This issue describes the problem with the v2 implementation of this feature, and it will be important to take into account this problem. If this issue is closed, can you make sure the dataset linked in the original post and the details are captured/propagated to the other issue? 

I assume that @dan-rukas is doing the design, but can you confirm who is doing the actual implementation?

**Comment by sedghi** [comment]
We can keep this around if you like

**Comment by sedghi** [comment]
@fedorov @igoroctaviano is this something that IDC wants to prioritize?

**Comment by igoroctaviano** [comment]
@fedorov can we close this v2 issue in favor of https://github.com/OHIF/Viewers/issues/3358 (v3)? This issue is already linked to the new one.

**Comment by fedorov** [comment]
@igoroctaviano yes, this makes sense!
