### ISSUE TITLE
Previous Next toolbar buttons

### ISSUE THREAD

**Issue by olivert1969** [OHIF/Viewers#3112]
What feature or change would you like to see made?
meteor version had Previous and Next toolbar buttons - very efficient for echocardiography workflow
these buttons are missing from v3
meteor used moveDisplaySets - also missing from OHIF v3

any suggestions?

**Comment by sedghi** [comment]
Can you describe what those buttons should do?

**Comment by olivert1969** [comment]
move displayset to previous or next DICOM instance in the Ultrasound series
was fully functional in Meteor version

**Comment by sedghi** [comment]
Can you create a video on the meteor version to show how it looks? I joined the project after the Meteor version and I'm curious to know how it worked before

**Comment by olivert1969** [comment]
[OHIF Viewer - Google Chrome - 12 January 2023 - Watch Video](https://www.loom.com/share/ecfd60bd9f464c7f9a2f4046556b915e)

**Comment by sedghi** [comment]
That's what I expected. Adding buttons back to the toolbar is not in the roadmap, but fixing the keyboard shortcut to go to next/previous displayset is something we need to fix (CC @jbocce )

**Comment by xuliangming** [comment]
请教影像克隆下来的界面跟官网的不一样 克隆下来的工具栏没有窗宽窗位的功能

**Comment by sedghi** [comment]
We had this [here](https://github.com/OHIF/Viewers/blob/368b8308a4fa620123677d4e23b78bf83eba251a/platform/viewer/src/appExtensions/GenericViewerCommands/commandsModule.js#L8), we will add it to commands and you can add the toolbar icon to execute that command to not have regression with V2

**Comment by olivert1969** [comment]
thanks for this - greatly appreciated - will avoid LOTS of additional clicks by ultrasound users







---- On Wed, 17 May 2023 11:54:26 -0400 Alireza ***@***.***> wrote ---





We had this https://github.com/OHIF/Viewers/blob/368b8308a4fa620123677d4e23b78bf83eba251a/platform/viewer/src/appExtensions/GenericViewerCommands/commandsModule.js#L8, we will add it to commands and you can add the toolbar icon to execute that command to not have regression with V2
