### ISSUE TITLE
[v3-stable] X-ray images are not rendered properly using dicomjson

### ISSUE THREAD

**Issue by yigitsoy** [OHIF/Viewers#3115]
### Describe the Bug

v3-stable version cannot render x-rays (maybe also other series with single instances) via dicomjson approach. The same images get rendered using local route via drag&drop.

### Steps to Reproduce:

1. Open this [link](https://v3-demo.ohif.org/viewer/dicomjson?url=https://deepc-static-public-assets.s3.eu-central-1.amazonaws.com/ohif-v3-stable-test/dicom.json) which uses v3-demo instance to load the JSON file that references the mentioned x-ray images.
2. Thumbnails in the sidebar get rendered properly but the image itself not.

```js
Please use code blocks to show formatted errors or code snippets
```

### The current behavior

The image is not rendered as seen below 

![image](https://user-images.githubusercontent.com/5089181/212323395-8e63490e-f241-4dc4-a30a-1d51ad8f1d1f.png)

Also no errors in console indicating an issue.

There are no issues while rendering multi-instance series (such as CT).

### The expected behavior

Images get rendered.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by sedghi** [comment]
any chance you can try the latest, and re-open with more information if still an issue
