### ISSUE TITLE
Save/Restore Measurements against dcm4chee does not work

### ISSUE THREAD

**Issue by malaterre** [OHIF/Viewers#312]
While trying the OHIF viewer and Measurement here is what I see on https://k8s-testing.ohif.org:

![image](https://user-images.githubusercontent.com/228803/48263084-317d0580-e425-11e8-843c-a228f8ecdb90.png)

See that the text 'You have unsave changes' is not present, now if I open the case again:

![image](https://user-images.githubusercontent.com/228803/48263128-61c4a400-e425-11e8-92c3-c3781ee42576.png)

The actual geometric information of the measurements are accurate, but see how that meta information attached to each measurements got lost.

**Comment by swederik** [comment]
Ah yeah looks like we aren't storing / retrieving the label itself to the SR at the moment. I think we weren't sure where to put it, and then never got back around to sorting it out.

Tagging @pieper

**Comment by pieper** [comment]
Yes, definitely - we want your help @fedorov!  And thanks for testing @malaterre.  We are in the process of factoring the SR management out of OHIF and into dcmjs, so that's why this has remained in draft state for now.  We want to have a set of [general purpose SR utilities](https://github.com/dcmjs-org/dcmjs/tree/master/src/utilities) and [toolkit-specific adaptors](https://github.com/dcmjs-org/dcmjs/tree/master/src/adapters/Cornerstone) so that the OHIF code is a trivial layer.

**Comment by fedorov** [comment]
Speaking for myself, I am a _still_ a bit confused about how things are (dis?)connected together. I thought the samples Steve showed me in the past looked good, and we have confirmation from David, but what shows up in OHIF Viewer seems to be some other implementation... 😕

**Comment by pieper** [comment]
> but what shows up in OHIF Viewer seems to be some other implementation...
 
I'm sorry, were the previous posts unclear?

**Comment by fedorov** [comment]
I was was just confused from where the valid samples that I have seen before were coming from, and what the users are supposed to test to get the valid samples. I did not examine the repositories linked, sorry if the answers are there and I just missed them.

**Comment by viss3595** [comment]
#376 Save annotations and measurements does not work.

**Comment by dannyrb** [comment]
This issue appears to be specific to `v1.x`. Unfortunately, we don't have as much bandwidth to for previous major versions. I'm going to close this issue for now, but please don't hesitate to continue the conversation.

These features are slated for `v2.x`, but it's unclear where the priority lies for them.
