### ISSUE TITLE
PhotometricInterpretation ignored

### ISSUE THREAD

**Issue by edotassi** [OHIF/Viewers#3121]
Hi!

### Describe the Bug

Viewer ignore PhotometricInterpretation tag value

### Steps to Reproduce:

Open a studio with PhotometricInterpretation valued at MONOCHROME1

### The current behavior

<img width="1555" alt="Screenshot 2023-01-17 alle 14 59 17" src="https://user-images.githubusercontent.com/3192179/212918023-951b05c7-22fc-4f94-93cc-e08f2d8858be.png">

### The expected behavior

If I click on "invert" it works fine:

<img width="1555" alt="Screenshot 2023-01-17 alle 14 59 21" src="https://user-images.githubusercontent.com/3192179/212918082-6f53c62a-8bdc-4bfe-a905-02b7c0f0c719.png">

Thanks!

**Comment by sedghi** [comment]
can you drag and drop here and post the results

**Comment by edotassi** [comment]
Hi, this is the result:

<img width="1366" alt="Screenshot 2023-01-18 alle 22 07 47" src="https://user-images.githubusercontent.com/3192179/213295412-3ce63d44-01a5-4a59-8f2b-9945243a019f.png">

meanwhile I applied a temporary patch to our version, with this patch I can make the software work properly (at the moment it is used in production by our customers):

<img width="1912" alt="Screenshot 2023-01-18 alle 22 09 14" src="https://user-images.githubusercontent.com/3192179/213295810-355d28b1-9cda-4bff-969d-178bf82774f6.png">

<img width="1912" alt="Screenshot 2023-01-18 alle 22 09 36" src="https://user-images.githubusercontent.com/3192179/213295832-d1529473-e3ad-4f09-8797-a8d8e4399dd3.png">

now it works properly:
<img width="1912" alt="Screenshot 2023-01-18 alle 22 08 12" src="https://user-images.githubusercontent.com/3192179/213295897-e139bf49-bcd7-4a7a-91e3-9206a74ec3bd.png">

thanks!

**Comment by sedghi** [comment]
So this should get fixed on the [cs3d side](https://github.com/cornerstonejs/cornerstone3D-beta/)(since rendering engine is cs3d).

By the way what are you using for screenshots, they look awesome!

**Comment by edotassi** [comment]
@sedghi so is it a bug? or are our dicom files corrupt?

for screenshots I use the key combination SHIFT+CMD+4 and then SPACE on mac osx, did you mean this?

**Comment by sedghi** [comment]
Can you share the data?

**Comment by edotassi** [comment]
@sedghi sure! 

[dicom_test.zip](https://github.com/OHIF/Viewers/files/10455178/dicom_test.zip)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
