### ISSUE TITLE
Study list not updating after upload DICOM Image from Viewer

### ISSUE THREAD

**Issue by anarnoli** [OHIF/Viewers#3122]
### Study list not updating after upload DICOM Image from Viewer

Hello,

I have integrated OHIF Viewer with Google DICOM APIs and using "Upload DICOM Image" functionality from OHIF Viewer. Study list is not updating after successful image upload. Every time I have to refresh the page to view updated study.

Is there any configuration I am missing which refreshed Study List automatically or how can I achieve this functionality?

### Steps to Reproduce:

1. Config google.js and run OHIF Viewer
2. Click on + icon just before Study count
3. Select file or folder from Pop-up and click Ok
4. After successful file upload, click on pop-up X button

### The current behavior

Study list is not updating after successful image upload. Every time I have to refresh the page to view updated study.

<img width="1156" alt="Screenshot 2023-01-18 at 8 21 45 PM" src="https://user-images.githubusercontent.com/54370515/213205960-f02049f4-49ca-4f64-888e-e6ce4ecd5356.png">

### The expected behavior

Study list should update after successful image upload.

**Comment by sedghi** [comment]
It is not a bug just a limitation that we haven't implemented it yet.

**Comment by anarnoli** [comment]
> It is not a bug just a limitation that we haven't implemented it yet.

Thanks. In order to achieve refresh StudyList, should I need to customise functionality?

**Comment by anarnoli** [comment]
@sedghi I have a confusion here:

In `master` branch repo I see `+ button` to upload Dicom while in `v3-stable` branch I don't see + button to upload Dicom. As I know `studyListFunctionsEnabled: true` config enables upload button. Could you please confirm in `v3-stable` branch how I can enable upload button?

**master branch UI**

<img width="1069" alt="Screenshot 2023-01-25 at 3 26 36 PM" src="https://user-images.githubusercontent.com/54370515/214534074-db1df4dd-af18-4b7d-aa8e-f5731769ec10.png">

**v3-stable branch UI**

<img width="1317" alt="Screenshot 2023-01-25 at 3 31 23 PM" src="https://user-images.githubusercontent.com/54370515/214534365-0b9aefa8-049f-4b36-8236-798b918f183c.png">

**Comment by sedghi** [comment]
That is something we haven't ported to v3 yet. I would be glad to review your PR if you want to contribute it. I have more interest in fixing the refresh in v3 than v2

**Comment by hwanython** [comment]
> That is something we haven't ported to v3 yet. I would be glad to review your PR if you want to contribute it. I have more interest in fixing the refresh in v3 than v2

Hi, 

I appreicate with your fantastic contributing.

Do you have plan that add the uploaded button in the v3-stable ?

Best regards

**Comment by sedghi** [comment]
Yes, there will be one soon, we finalized the designs and probably start developing soon

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
