### ISSUE TITLE
UI: Rework viewport action bar and CINE player

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3123]
### Request

The current viewport action bar is too big which is not ideal for more than 1 row (e.g., 3x3). The only remaining concern is for the CINEPlayer since it is supposed to appear in the action bar. Here are the new designs for the CINE player.

![image](https://user-images.githubusercontent.com/7490180/213293705-26fc4684-a03b-4423-a520-55fb7cbf69f9.png)

New

![image](https://user-images.githubusercontent.com/7490180/213293943-1fec0bc3-9059-4a7f-b054-526e875fd35d.png)

![image](https://user-images.githubusercontent.com/7490180/213294194-104f5a5c-2697-4722-a76a-49532c6d64d9.png)

**What feature or change would you like to see made?**
- A new (not a replacement), action bar and cine player. 
...

**Why should we prioritize this feature?**
- Since there are a lot of wasted space

CC: Thanks to Dan Rukas for the great design as always

**Comment by jbocce** [comment]
Here is an updated screen shot of the viewport action bar...

![Viewport action bar](https://user-images.githubusercontent.com/109477394/219752678-a5bb14f9-2e7d-4b9b-8a67-7f0f106015d1.png)

**Comment by jbocce** [comment]
Here is an updated spec for the new cine player...

![Updated CINE](https://user-images.githubusercontent.com/109477394/221236146-78fd960a-e787-4cb5-bfb4-3f9052f90b43.png)

**Comment by jbocce** [comment]
Closing as a result of PR https://github.com/OHIF/Viewers/pull/3204
