### ISSUE TITLE
Viewer not working properly in mobile web browser

### ISSUE THREAD

**Issue by kundanashish** [OHIF/Viewers#3124]
Viewer version 3 is not working properly in mobile web browser. None of the mobile event like zoom are working that were working fine in version 2.

To replicate open viewer in mobile web browser.

**Comment by sedghi** [comment]
Touch events are in progress here https://github.com/cornerstonejs/cornerstone3D-beta/pull/247

**Comment by kundanashish** [comment]
Hi @sedghi 
Thanks for the information.

Is this already integrated in OHIF or any dare we have planned to do it?
Pls advise

**Comment by Omid-Heydarzadeh** [comment]
Hi @sedghi,
I made an (almost) responsive version of the viewer for mobile. Can you help me with the correct way to enable touch events? Especially for the Zoom tool.
