### ISSUE TITLE
MPR view missing slices after recent updates - V3

### ISSUE THREAD

**Issue by nigelheap** [OHIF/Viewers#3132]
### Describe the Bug

Enabling MPR view on certain studies causes either white images to be displayed in the 3 viewports or what appears to be missing slices.

This seems to only be happening on these cornerstone versions 
```js
    "@cornerstonejs/core": "^0.25.0",
    "@cornerstonejs/tools": "^0.34.2",
```

I'll open a PR with the bumped versions and link it to this issue.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

![CleanShot 2023-01-25 at 11 04 28](https://user-images.githubusercontent.com/293999/214985160-74ea316e-5493-419c-91a6-c92ca7edd623.jpg)
![Screenshot 2023-01-25 at 14 55 38](https://user-images.githubusercontent.com/293999/214985176-cfa41365-5882-49b3-8ac7-7e82d934752b.png)

**Comment by nigelheap** [comment]
@sedghi I've sent you the anonymized zip on slack

**Comment by sedghi** [comment]
Can you try in the latest build?

**Comment by nigelheap** [comment]
Thanks @sedghi
