### ISSUE TITLE
Ohif V2 Change Default Layout Window

### ISSUE THREAD

**Issue by nctasli** [OHIF/Viewers#3134]
Hi,
How can I 1x2 Default Layout in OHIF V2 ?
![Screenshot_1](https://user-images.githubusercontent.com/111058828/215107854-f2c0d5e0-e6f3-4da0-a097-b9e75d571146.png)

**Comment by Davi-Wei** [comment]
use setLayout function in ViewerMain.js

**Comment by nctasli** [comment]
thanks for replying. Can you give a code example ?
`
class ViewerMain extends Component {
  static propTypes = {
    activeViewportIndex: PropTypes.number.isRequired,
    studies: PropTypes.array,
    viewportSpecificData: PropTypes.object.isRequired,
    layout: PropTypes.object.isRequired,
    setViewportSpecificData: PropTypes.func.isRequired,
    clearViewportSpecificData: PropTypes.func.isRequired,
  };

  constructor(props) {
    super(props);

    this.state = {
      displaySets: [],
    };
  }

  getDisplaySets(studies) {
    const displaySets = [];
    studies.forEach(study => {
      study.displaySets.forEach(dSet => {
        if (!dSet.plugin) {
          dSet.plugin = 'cornerstone';
        }
        displaySets.push(dSet);
      });
    });

    return displaySets;
  }

  findDisplaySet(studies, studyInstanceUid, displaySetInstanceUid) {
    const study = studies.find(study => {
      return study.studyInstanceUid === studyInstanceUid;
    });

    if (!study) {
      return;
    }

    return study.displaySets.find(displaySet => {
      return displaySet.displaySetInstanceUid === displaySetInstanceUid;
    });
  }

  componentDidMount() {
    // Add beforeUnload event handler to check for unsaved changes
    //window.addEventListener('beforeunload', unloadHandlers.beforeUnload);

    // Get all the display sets for the viewer studies
    if (this.props.studies) {
      const displaySets = this.getDisplaySets(this.props.studies);
      this.setState({ displaySets }, this.fillEmptyViewportPanes);
    }
  }

  componentDidUpdate(prevProps) {
    const prevViewportAmount = prevProps.layout.viewports.length;
    const viewportAmount = this.props.layout.viewports.length;
    const isVtk = this.props.layout.viewports.some(vp => !!vp.vtk);

    if (
      this.props.studies !== prevProps.studies ||
      (viewportAmount !== prevViewportAmount && !isVtk)
    ) {
      const displaySets = this.getDisplaySets(this.props.studies);
      this.setState({ displaySets }, this.fillEmptyViewportPanes);
    }
  }

  fillEmptyViewportPanes = () => {
    const dirtyViewportPanes = [];
    const { layout, viewportSpecificData } = this.props;
    const { displaySets } = this.state;

    if (!displaySets || !displaySets.length) {
      return;
    }

    for (let i = 0; i < layout.viewports.length; i++) {
      const viewportPane = viewportSpecificData[i];
      const isNonEmptyViewport =
        viewportPane &&
        viewportPane.studyInstanceUid &&
        viewportPane.displaySetInstanceUid;

      if (isNonEmptyViewport) {
        dirtyViewportPanes.push({
          studyInstanceUid: viewportPane.studyInstanceUid,
          displaySetInstanceUid: viewportPane.displaySetInstanceUid,
        });

        continue;
      }

      const foundDisplaySet =
        displaySets.find(
          ds =>
            !dirtyViewportPanes.some(
              v => v.displaySetInstanceUid === ds.displaySetInstanceUid
            )
        ) || displaySets[displaySets.length - 1];

      dirtyViewportPanes.push(foundDisplaySet);
    }

    dirtyViewportPanes.forEach((vp, i) => {
      if (vp && vp.studyInstanceUid) {
        this.setViewportData({
          viewportIndex: i,
          studyInstanceUid: vp.studyInstanceUid,
          displaySetInstanceUid: vp.displaySetInstanceUid,
        });
      }
    });
  };

  setViewportData = ({
    viewportIndex,
    studyInstanceUid,
    displaySetInstanceUid,
  }) => {
    const displaySet = this.findDisplaySet(
      this.props.studies,
      studyInstanceUid,
      displaySetInstanceUid
    );

    this.props.setViewportSpecificData(viewportIndex, displaySet);
  };

  render() {
    const { viewportSpecificData } = this.props;
    const viewportData = viewportSpecificData
      ? Object.values(viewportSpecificData)
      : [];

    return (
      <div className="ViewerMain">
        {this.state.displaySets.length && (
          <ConnectedViewportGrid
            studies={this.props.studies}
            viewportData={viewportData}
            setViewportData={this.setViewportData}
          >
            {/* Children to add to each viewport that support children */}
          </ConnectedViewportGrid>
        )}
      </div>
    );
  }

  componentWillUnmount() {
    // Clear the entire viewport specific data
    const { viewportSpecificData } = this.props;
    Object.keys(viewportSpecificData).forEach(viewportIndex => {
      this.props.clearViewportSpecificData(viewportIndex);
    });
    // TODO: These don't have to be viewer specific?
    // Could qualify for other routes?
    // hotkeys.destroy();

    // Remove beforeUnload event handler...
    //window.removeEventListener('beforeunload', unloadHandlers.beforeUnload);
    // Destroy the synchronizer used to update reference lines
    //OHIF.viewer.updateImageSynchronizer.destroy();
    // TODO: Instruct all plugins to clean up themselves
    //
    // Clear references to all stacks in the StackManager
    //StackManager.clearStacks();
    // @TypeSafeStudies
    // Clears OHIF.viewer.Studies collection
    //OHIF.viewer.Studies.removeAll();
    // @TypeSafeStudies
    // Clears OHIF.viewer.StudyMetadataList collection
    //OHIF.viewer.StudyMetadataList.removeAll();
  }
}

export default ViewerMain;
`

**Comment by nctasli** [comment]
> use setLayout function in ViewerMain.js

thanks for replying. Can you give a code example ?
`
class ViewerMain extends Component {
static propTypes = {
activeViewportIndex: PropTypes.number.isRequired,
studies: PropTypes.array,
viewportSpecificData: PropTypes.object.isRequired,
layout: PropTypes.object.isRequired,
setViewportSpecificData: PropTypes.func.isRequired,
clearViewportSpecificData: PropTypes.func.isRequired,
};

constructor(props) {
super(props);

this.state = {
  displaySets: [],
};
}

getDisplaySets(studies) {
const displaySets = [];
studies.forEach(study => {
study.displaySets.forEach(dSet => {
if (!dSet.plugin) {
dSet.plugin = 'cornerstone';
}
displaySets.push(dSet);
});
});

return displaySets;
}

findDisplaySet(studies, studyInstanceUid, displaySetInstanceUid) {
const study = studies.find(study => {
return study.studyInstanceUid === studyInstanceUid;
});

if (!study) {
  return;
}

return study.displaySets.find(displaySet => {
  return displaySet.displaySetInstanceUid === displaySetInstanceUid;
});
}

componentDidMount() {
// Add beforeUnload event handler to check for unsaved changes
//window.addEventListener('beforeunload', unloadHandlers.beforeUnload);

// Get all the display sets for the viewer studies
if (this.props.studies) {
  const displaySets = this.getDisplaySets(this.props.studies);
  this.setState({ displaySets }, this.fillEmptyViewportPanes);
}
}

componentDidUpdate(prevProps) {
const prevViewportAmount = prevProps.layout.viewports.length;
const viewportAmount = this.props.layout.viewports.length;
const isVtk = this.props.layout.viewports.some(vp => !!vp.vtk);

if (
  this.props.studies !== prevProps.studies ||
  (viewportAmount !== prevViewportAmount && !isVtk)
) {
  const displaySets = this.getDisplaySets(this.props.studies);
  this.setState({ displaySets }, this.fillEmptyViewportPanes);
}
}

fillEmptyViewportPanes = () => {
const dirtyViewportPanes = [];
const { layout, viewportSpecificData } = this.props;
const { displaySets } = this.state;

if (!displaySets || !displaySets.length) {
  return;
}

for (let i = 0; i < layout.viewports.length; i++) {
  const viewportPane = viewportSpecificData[i];
  const isNonEmptyViewport =
    viewportPane &&
    viewportPane.studyInstanceUid &&
    viewportPane.displaySetInstanceUid;

  if (isNonEmptyViewport) {
    dirtyViewportPanes.push({
      studyInstanceUid: viewportPane.studyInstanceUid,
      displaySetInstanceUid: viewportPane.displaySetInstanceUid,
    });

    continue;
  }

  const foundDisplaySet =
    displaySets.find(
      ds =>
        !dirtyViewportPanes.some(
          v => v.displaySetInstanceUid === ds.displaySetInstanceUid
        )
    ) || displaySets[displaySets.length - 1];

  dirtyViewportPanes.push(foundDisplaySet);
}

dirtyViewportPanes.forEach((vp, i) => {
  if (vp && vp.studyInstanceUid) {
    this.setViewportData({
      viewportIndex: i,
      studyInstanceUid: vp.studyInstanceUid,
      displaySetInstanceUid: vp.displaySetInstanceUid,
    });
  }
});
};

setViewportData = ({
viewportIndex,
studyInstanceUid,
displaySetInstanceUid,
}) => {
const displaySet = this.findDisplaySet(
this.props.studies,
studyInstanceUid,
displaySetInstanceUid
);

this.props.setViewportSpecificData(viewportIndex, displaySet);
};

render() {
const { viewportSpecificData } = this.props;
const viewportData = viewportSpecificData
? Object.values(viewportSpecificData)
: [];

return (
  <div className="ViewerMain">
    {this.state.displaySets.length && (
      <ConnectedViewportGrid
        studies={this.props.studies}
        viewportData={viewportData}
        setViewportData={this.setViewportData}
      >
        {/* Children to add to each viewport that support children */}
      </ConnectedViewportGrid>
    )}
  </div>
);
}

componentWillUnmount() {
// Clear the entire viewport specific data
const { viewportSpecificData } = this.props;
Object.keys(viewportSpecificData).forEach(viewportIndex => {
this.props.clearViewportSpecificData(viewportIndex);
});
// TODO: These don't have to be viewer specific?
// Could qualify for other routes?
// hotkeys.destroy();

// Remove beforeUnload event handler...
//window.removeEventListener('beforeunload', unloadHandlers.beforeUnload);
// Destroy the synchronizer used to update reference lines
//OHIF.viewer.updateImageSynchronizer.destroy();
// TODO: Instruct all plugins to clean up themselves
//
// Clear references to all stacks in the StackManager
//StackManager.clearStacks();
// @TypeSafeStudies
// Clears OHIF.viewer.Studies collection
//OHIF.viewer.Studies.removeAll();
// @TypeSafeStudies
// Clears OHIF.viewer.StudyMetadataList collection
//OHIF.viewer.StudyMetadataList.removeAll();
}
}

export default ViewerMain;
`

**Comment by Davi-Wei** [comment]
import { redux } from '@ohif/core';
const { setLayout } = redux.actions;

componentDidUpdate(prevProps) {
    const prevViewportAmount = prevProps.layout.viewports.length;
    const viewportAmount = this.props.layout.viewports.length;
    const isVtk = this.props.layout.viewports.some(vp => !!vp.vtk);
    
    if (
    this.props.studies !== prevProps.studies ||
    (viewportAmount !== prevViewportAmount && !isVtk)
    ) {
      const layout = {
          numRows: 1,
          numColumns: 2,
          viewports: [{},{}],  
        };
      window.store.dispatch(setLayout(layout));
      const displaySets = this.getDisplaySets(this.props.studies);
      this.setState({ displaySets }, this.fillEmptyViewportPanes);
    }
}

**Comment by nctasli** [comment]
thank you for helping me progress on my project 👍 💯
