### ISSUE TITLE
Not able to edit!

### ISSUE THREAD

**Issue by gagandt** [OHIF/Viewers#314]
Hi!
I am editing some files in the OHIFviewer directory which are locates in .meteor folder.
These files are ohif_cornerstone.js and some more.
Whenever i edit the code and save the file and restart the server, the file restores itself to the original version.
Can somebody please help!

**Comment by jacklau88** [comment]
can’t edit on cornerstone.

**Comment by JamesAPetts** [comment]
These are being pulled in by NPM. In order to edit them you'll need to fork the cornerstone repository, publish it to NPM, and then change the version you are pointing at within the meteor application here: https://github.com/OHIF/Viewers/blob/master/Packages/ohif-cornerstone/package.js

**Comment by JamesAPetts** [comment]
If you don't want to publish to npm, you can also just check in the distribution files into your fork on git and point to them like this:

`'cornerstone-core': 'git+https://github.com/gagandt/cornerstone#myCornerstoneFork'`
