### ISSUE TITLE
OHIF v3 - Add Image overlay in Viewport

### ISSUE THREAD

**Issue by mokbelt** [OHIF/Viewers#3144]
Dears,
Trying to add Image overlay (from DICOM tags) to the view port.
I tried to add the configuration mentioned in the customization service documentation (https://v3-docs.ohif.org/platform/services/ui/customization-service/), but still the name still didn't appear on the viewport.
Can someone exaplin how to pull tags (mostly Patient name/gender/dob etc...) to appear on the view port.
I built the V3 and serving it on the "dist" folder with nginx.
```
// in the APP_CONFIG file set the top right area to show the patient name
// using PN: as a prefix when the study has a non-empty patient name.
customizationService: {
  cornerstoneOverlayTopRight: {
    id: 'cornerstoneOverlayTopRight',
    customizationType: 'ohif.cornerstoneOverlay',
    items: [
      {
        id: 'PatientNameOverlay',
        // Note the ohif.overlayItem is a prototype instance for this object
        // The ohif.overlayItem is defined up above
        customizationType: 'ohif.overlayItem',
        attribute: 'PatientName',
        label: 'PN:',
      },
    ],
  },
},
```
![image](https://user-images.githubusercontent.com/56265911/216819053-756ed619-896b-464b-bc09-518337e73a66.png)

**Comment by mokbelt** [comment]
PS: In Developer tools it was mentioned, but didn't appear on the overlay:
![image](https://user-images.githubusercontent.com/56265911/216834583-70d06fea-0021-495d-b231-34028436a321.png)

**Comment by mokbelt** [comment]
Dears,
Anyone were able to add overlay on OHIF v3?

**Comment by blabdouze** [comment]
I think you might have to specify a color otherwise it won't appear. 
Also the patient name field returns an object and can't be displayed with the `attribute` field. 

You'll need to define a custom `contentF` function :

in `platform/viewer/public/config/default.js` : 
```javascript
customizationService: {
    // Shows a custom route -access via http://localhost:3000/custom
    // helloPage: '@ohif/extension-default.customizationModule.helloPage',
    cornerstoneOverlayTopRight: {
      id: 'cornerstoneOverlayTopRight',
      customizationType: 'ohif.cornerstoneOverlay',
      items: [
        {
          id: 'PatientNameOverlay',
          // Note the overlayItem as a parent type - this provides the
          // rendering functionality to read the attribute and use the label.
          customizationType: 'ohif.overlayItem',
          label: 'PN:',
          title: 'Patient Name',
          color: 'yellow',
          condition: ({ instance }) =>
            instance &&
            instance.PatientName &&
            instance.PatientName.Alphabetic,
          contentF: ({ instance, formatters: { formatPN } }) => `${formatPN(instance.PatientName.Alphabetic)} ${(instance.PatientSex ? '(' + instance.PatientSex + ')' : '')}`,
        }
      ]
    }
  },
```

The HTML displayed can be customized in `extensions\default\src\getCustomizationModule.tsx` : 

```javascript
        {
          id: 'ohif.overlayItem',
          content: function (props) {
            if (this.condition && !this.condition(props)) return null;

            const { instance } = props;
            const value =
              instance && this.attribute
                ? instance[this.attribute]
                : this.contentF && typeof this.contentF === 'function'
                  ? this.contentF(props)
                  : null;
            if (!value) return null;

            return (
              <span
                className="overlay-item flex flex-row"
                style={{ color: this.color || undefined }}
                title={this.title || ''}
              >
                {this.label && (
                  <span className="mr-1 shrink-0">{this.label}</span>
                )}
                <span className="font-light">{value}</span>
              </span>
            );
          },
        },
``` 

Result : 
 
![ohif metadata](https://user-images.githubusercontent.com/15141805/235109530-74a14b79-52bb-4ae2-8a5f-5d5b24505e92.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by jmaratt** [comment]
This issue seems to be persisting. I used the example above and examples at: https://docs.ohif.org/platform/services/ui/customization-service/#configuring-customizations

But I cannot get the overlay to appear in the default viewer.

Using:
3.9.0-beta.21
Chrome 123.0.0
Linux x86_64
