### ISSUE TITLE
After loading a previous saved SR report, the annotation label does not show on the measurement panel

### ISSUE THREAD

**Issue by JennyLeePMH** [OHIF/Viewers#3150]
### After loading a previous saved SR report, the annotation label does not show on the measurement panel

Please refer below video for detailed description and steps to reproduce
https://watch.screencastify.com/v/yOwHMPpkTFp03tdKg6gE

### The current behavior

The current behavior is, after loading a saved SR report, the measurement panel does not shows the annotation and their label.

### The expected behavior
The expected behavior is, after loading a saved SR report, the measurement panel would shows the annotation and their label.

**Comment by abdou-chakhkhar** [comment]
@JennyLeePMH did you manage to resolve this problem??
