### ISSUE TITLE
Viewports in OHIF V3 can be reduced to zero and unusable small widths

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3159]
### Describe the Bug

OHIF V3 can be resized such that the viewports can be reduced to zero and/or unusably small widths. Consideration should be made as to what is a tolerable small width. Furthermore consideration should be made as to how the OHIF app page behaves once a minimum width is decided upon. For example, should a horizontal scroll bar appear for the entire page once the minimum viewport width is reached and the page contents are too wide for the browser window? Or perhaps maybe just a horizontal scroll bar for the viewport area?

### Steps to Reproduce:

1. Launch OHIF.
2. Resize the browser window such that its width becomes smaller (i.e. resize to a thinner window).
3. Notice that the viewports can become an unusable small size and can be reduced to zero width.

### The current behavior

See the attached video.

https://user-images.githubusercontent.com/109477394/218104748-862504c0-bd35-4d36-9e2f-4257b3e1bed7.mp4

### The expected behavior

Nothing proposed - this issue is being logged so that consideration is made for this.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by james-hanks** [comment]
Let's revisit when we redo mobile design @dan-rukas

**Comment by james-hanks** [comment]
@dan-rukas assigned to take a look at this when we do mobile design and make sure this isn't an issue after the new design
