### ISSUE TITLE
Bottom border of the last row of viewports gets clipped in V3 at smaller widths

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3160]
### Describe the Bug

Resizing the browser window to a smaller width will cause the bottom border of the bottom row of viewports to get clipped. The suspected cause of the problem is wrapping that occurs in the top toolbar - wrapping of the "Investigational Use Only" banner.

### Steps to Reproduce:

1. Launch OHIF V3.
2. Resize the browser window to a smaller width where the "Investigational Use Only" begins to wrap and/or the bottom border of the bottom row of viewports gets clipped.

### The current behavior

See the attached video...

https://user-images.githubusercontent.com/109477394/218106799-01edf117-3c91-42d4-a86c-2d26c04a44d0.mp4

### The expected behavior

The bottom border is not clipped.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by james-hanks** [comment]
Revisit when we redo mobile design @dan-rukas

**Comment by IbrahimCSAE** [comment]
No longer an issue

![image](https://github.com/OHIF/Viewers/assets/93064150/6bc1f748-94fd-4b53-bb85-61066f52b3a2)
