### ISSUE TITLE
Measurement tracking confirmation prompt buttons get clipped for thinner browser windows

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3161]
### Describe the Bug

For thin OHIF v3 browser windows, the prompt to confirm measurement tracking can have its buttons clipped.

### Steps to Reproduce:

1. Launch OHIF v3.
2. Resize the browser to have a small width.
3. Add a markup measurement to a viewport.
4. Notice the prompt to confirm measurement tracking has some of its buttons clipped.

### The current behavior

See the attached video.

https://user-images.githubusercontent.com/109477394/218108744-f3e53dfd-b348-4b3e-97ac-80195e11fd34.mp4

### The expected behavior

The buttons are not clipped.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by james-hanks** [comment]
Revisit when we redo mobile design @dan-rukas

**Comment by IbrahimCSAE** [comment]
no longer an issue

![image](https://github.com/OHIF/Viewers/assets/93064150/88109099-0969-46c0-ab9d-131e9d8ca0a9)
