### ISSUE TITLE
Modify the wadoUriRoot path in orthancDICOMWeb.json in the OHIF configuration file. The access path will not be updated. How should I modify it?

### ISSUE THREAD

**Issue by XingGuan** [OHIF/Viewers#317]
Dear,
I want to connect OHIF to XNAT server with wado?
How to configure files in OHIF?
Modify the wadoUriRoot path in orthancDICOMWeb.json in the OHIF configuration file. The access path will not be updated. How should I modify it?
thank you all.

**Comment by dannyrb** [comment]
Hi @XingGuan 👋
You might have better luck with the [OHIF Viewer XNAT Plugin](https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin) that's maintained by @JamesAPetts.

I'm going to close this issue for now, but feel free to comment with any additional questions you may have. Please try to include as much info as you can to reproduce your issue, and what you have already tried. The more info we have, the more likely we are to respond in a timely manner ^_^
