### ISSUE TITLE
Issues with the integration with the AZ PACS service.

### ISSUE THREAD

**Issue by devangparekh1** [OHIF/Viewers#3176]
Hello there, I am trying to integrate the OHIF renderer with the hosted Azure service where all my Dicom files are dumped, I have replaced the DicomWeb endpoints but I don't have any clue on where can I place the access token so that the request from the viewer can be authorised.

**Comment by devangparekh1** [comment]
@adamwimmj Can you guide me more on how I can set up OIDC in the local viewer, I have AZ services deployed and configured and have creds.

**Comment by sedghi** [comment]
Look here https://docs.ohif.org/deployment/authorization
