### ISSUE TITLE
Update services from Object.assign(this, pubSubServiceInterface) => implements IPubSubService

### ISSUE THREAD

**Issue by Ouwen** [OHIF/Viewers#3187]
### Request

**What feature or change would you like to see made?**
I saw there was a move to type services. Is the plan to update services from `Object.assign(this, pubSubServiceInterface)` to `class someService implements IPubSubService`?

...

**Why should we prioritize this feature?**
Javascript => TS is always nice.
...

**Comment by sedghi** [comment]
Yes, all of them

**Comment by sedghi** [comment]
Implemented
