### ISSUE TITLE
Incorrect ultrasound measurement

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#319]
Kindly find a picture of an OB ultrasound.  The yellow lines are from OHIF length tool.  When length is measured, it shows incorrect results.

Is there any way to disable Length tool or show the measurement in pixel rather than incorrect 'mm' if all the information is not present.  

Length information for this particular ultrasound study is present and could be calculate based on Chris'  [response](https://groups.google.com/forum/#!searchin/cornerstone-platform/length$20tool|sort:date/cornerstone-platform/DGDG2cone2E/FdVtgaQfAQAJ) in one post.  However, according to Erik - Cornerstone does not currently incorporate SequenceOfUltrasoundRegions at all at the moment.

I want to simply put this out there either for enhancement or a bug.

![capture](https://user-images.githubusercontent.com/23708609/49298516-37459400-f483-11e8-95ba-3f417eef12d3.png)

Many thanks!

**Comment by Zaid-Safadi** [comment]
This seems to be a bug introduced by the wadoImageLoader and is fixed [here](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/215)

**Comment by richsmith123** [comment]
Thank you for pointing out similar issue which was closed earlier.

Yes, you are correct - this is a bug which was re-introduced in new release.

Best regards,
