### ISSUE TITLE
no multipart mime header error when using version >4.12.40 with Azure DICOM server

### ISSUE THREAD

**Issue by adw424** [OHIF/Viewers#3193]
### Describe the Bug

Hello, I'm trying to setup a local OHIF viewer with Azure a DICOM server, using their open source offering https://github.com/microsoft/dicom-server. The study list is showing and loading all fine but I get this error when viewing a study in the viewer. 

<img width="411" alt="Screenshot 2023-02-23 at 15 58 46" src="https://user-images.githubusercontent.com/22202587/220964024-e57b1b56-2d62-4539-b2ff-a14e4ee56429.png">

I don't get the error when using version `4.12.39` but I do at `4.12.40` and greater of `@ohif/viewer`. 

I'm sorry if this isn't an issue with the viewer, rather an issue with the Azure DICOM server. But I'm unsure where the error originates from because at version `4.12.39`, it is working. 

Thank you for any help on this.

### Steps to Reproduce:

1. Start Azure DICOM server using version `10.0.104` at https://github.com/microsoft/dicom-server
2. Load viewer and configure to use Azure DICOM server 
3. Select a study

Here is a simple HTML page that loads from DICOM server locally with the two versions mentioned above

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>dicom web</title>
  </head>
  <body>
    <div id="ohif"></div>
  </body>

    <!-- This version does work -->
    <script src="https://unpkg.com/@ohif/viewer@4.12.39/dist/index.umd.js" crossorigin></script>
    
    <!-- This version does not work -->
    <!-- <script src="https://unpkg.com/@ohif/viewer@4.12.40/dist/index.umd.js" crossorigin></script> -->
    <script>
        window.config = {
            routerBasename: '/',
            extensions: [],
            showStudyList: true,
            servers: {
                dicomWeb: [
                    {
                        name: 'AzureDicomWeb',
                        wadoUriRoot: 'http://localhost:8080/v1/wado',
                        qidoRoot: 'http://localhost:8080/v1',
                        wadoRoot: 'http://localhost:8080/v1',
                        qidoSupportsIncludeField: true,
                        imageRendering: 'wadors',
                        thumbnailRendering: 'wadors',
                        enableStudyLazyLoad: true,
                        supportsFuzzyMatching: true,
                    },
                ],
            },
        };

        window.OHIFViewer.installViewer(window.config, "ohif");
    </script>
</html>

```

### The current behavior

When you try and view any images of a study on version `4.12.40` and above, an error occurs that looks like this

<img width="1217" alt="Screenshot 2023-02-23 at 16 22 56" src="https://user-images.githubusercontent.com/22202587/220968034-28dbdea8-5f6f-4644-b236-3f303d99961f.png">

And request/response headers:

<img width="701" alt="Screenshot 2023-02-23 at 16 23 45" src="https://user-images.githubusercontent.com/22202587/220968144-b28adcba-8427-4aa6-90de-d1150c8291b4.png">

### The expected behavior

Expected to view the image, which is possible on version `4.12.39`

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by NikGurev** [comment]
try to install `cornerstone-wado-image-loader@4.10.0`. It helped me, since it resolves an error with mediaType header
