### ISSUE TITLE
Files not rendering properly

### ISSUE THREAD

**Issue by Pierre-Baptiste** [OHIF/Viewers#3196]
### Describe the Bug

Since branch #3180 was merged, I am having trouble rendering my files. I am not sure why yet, if someone has a clue on where it could be coming from or how to fix it I'd appreciate it !
I am sure it is coming from this merge commit since it renders properly at the commit right before.

before :
![Screenshot 2023-02-24 at 09 44 06](https://user-images.githubusercontent.com/29004228/221136875-05557e87-7143-4a79-bf97-f404798e6703.png)

after :
![Screenshot 2023-02-24 at 10 01 36](https://user-images.githubusercontent.com/29004228/221136938-e05a450f-b3ae-4451-9cae-3b91ecb9f07b.png)

I run this script to launch the project :
`"dev:static": "cross-env NODE_ENV=development PROXY_TARGET=/api PROXY_DOMAIN=http://localhost:7777 webpack serve --config .webpack/webpack.pwa.js",`

we have a custom config file, maybe this could be at play ?

```
window.config = function (props) {
  /* dynamic configuration */
  const { url, routerBasename } = props;

  return {
    extensions: [],
    modes: [],
    showStudyList: true,
    routerBasename: routerBasename || '/',
    dataSources: [
      {
        friendlyName: 'Static WADO Files',
        namespace: '@ohif/extension-default.dataSourcesModule.dicomweb',
        sourceName: 'dicomweb',
        configuration: {
          name: 'LocalStatic',
          wadoUriRoot: url,
          qidoRoot: url,
          wadoRoot: url,
          qidoSupportsIncludeField: false,
          imageRendering: 'wadors',
          thumbnailRendering: 'thumbnail',
          enableStudyLazyLoad: true,
          supportsFuzzyMatching: false,
          staticWado: true,
        },
      },
    ],
    httpErrorHandler: (error) => {
      // This is 429 when rejected from the public idc sandbox too often.
      console.warn(error.status);
  
      // Could use services manager here to bring up a dialog/modal if needed.
      console.warn('test, navigate to https://ohif.org/');
    },
    defaultDataSourceName: 'dicomweb',
  };
};
```

### Steps to Reproduce:

I am not sure how to reproduce, since our only thing custom is a function as config, maybe if you used one.

```js
Uncaught (in promise) Error: decodeRGB: ybrBuffer length must be divisble by 3
    Je cornerstoneWADOImageLoader.min.js:1
    Je cornerstoneWADOImageLoader.min.js:1
    ct cornerstoneWADOImageLoader.min.js:1
```

### The current behavior

WADO files don't render properly. It consistently fails to render (tested on several files). I get errors in the console.

### The expected behavior

I would expect that e2e testing and test mode to not affect the rendering of WADO files.

Thank you for the help 🙏🏻 

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
can you share the anonymized images by any chance?

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

Please try and re-open if the issue persists
