### ISSUE TITLE
Set up orthanc with environment variables in the entrypoint

### ISSUE THREAD

**Issue by jordimassaguerpla** [OHIF/Viewers#3201]
### Request

**What feature or change would you like to see made?**

That we can setup orthanc with environment variables in the entrypoint, the same way you do with google healthcare.

**Why should we prioritize this feature?**

With this feature, we can use helm to set up a k8s deployment using environment variables.
...

**Comment by sedghi** [comment]
I think our docker added support for this. https://docs.ohif.org/deployment/docker
