### ISSUE TITLE
Minimal example of the UINotificationService and SnackbarProvider

### ISSUE THREAD

**Issue by EdwinBennink** [OHIF/Viewers#3203]
Dear OHIF team,

I'm trying to re-use the OHIF React UI components to build a web-app with the same looks and feel as the viewer, but got stuck on using the SnackbarProvider (React is returning a rather difficult to debug 'Invalid hook call').  As an example, see the TypeScript file attached. Would it be possible to provide a minimal working example showing how to use the UINotificationService and SnackbarProvider in a minimalistic React app? Thanks!

Kind regards,
Edwin

```typescript
import React from 'react'

// @ohif/ui requires regeneratorRuntime to be globally defined.
import 'regenerator-runtime/runtime.js'
import {ErrorBoundary, SnackbarProvider} from '@ohif/ui'
import {CommandsManager, ServicesManager, ExtensionManager, UINotificationService} from '@ohif/core'


let AppContext = React.createContext({})
const CONTEXTS = {
    DEFAULT: 'DEFAULT'
}
const useAppContext = () => React.useContext(AppContext)
const api = {contexts: CONTEXTS, hooks: {useAppContext}}
const getAppState = () => {return {}}
const getActiveContexts = () => ['DEFAULT']
const commandsManager = new CommandsManager({getAppState: getAppState, getActiveContexts: getActiveContexts})
const servicesManager = new ServicesManager()


export class App extends React.Component<any, any> {
    public extensionManager: ExtensionManager

    constructor(props) {
        super(props)
        servicesManager['registerServices']([UINotificationService])
        this.extensionManager = new ExtensionManager({commandsManager, servicesManager, api})
    }

    render() {
        const {UINotificationService} = servicesManager.services

        return (
            <div>
                <ErrorBoundary context="App">
                    <SnackbarProvider service={UINotificationService}>
                        Hello from the app!
                    </SnackbarProvider>
                </ErrorBoundary>
            </div>
        )
    }
}
```

**Comment by sagni-amsalu** [comment]
In react js  there is no any error generated , after I've changed your type-script to react js as shown below,

`import React, { Component } from 'react';
// @ohif/ui requires regeneratorRuntime to be globally defined.
import 'regenerator-runtime/runtime.js';
import { ErrorBoundary, SnackbarProvider } from '@ohif/ui';
import {
  CommandsManager,
  ServicesManager,
  ExtensionManager,
  UINotificationService,
} from '@ohif/core';

let AppContext = React.createContext({});
const CONTEXTS = {
  DEFAULT: 'DEFAULT',
};
const useAppContext = () => React.useContext(AppContext);
const api = { contexts: CONTEXTS, hooks: { useAppContext } };
const getAppState = () => {
  return {};
};
const getActiveContexts = () => ['DEFAULT'];
const commandsManager = new CommandsManager({
  getAppState: getAppState,
  getActiveContexts: getActiveContexts,
});
const servicesManager = new ServicesManager();

export class App extends Component {
  extensionManager;

  constructor(props) {
    super(props);
    servicesManager['registerServices']([UINotificationService]);
    this.extensionManager = new ExtensionManager({
      commandsManager,
      servicesManager,
      api,
    });
  }

  render() {
    const { UINotificationService } = servicesManager.services;
    return (
      <div>
        <ErrorBoundary context="App">
          <SnackbarProvider service={UINotificationService}>
            Hello from the app!
          </SnackbarProvider>
        </ErrorBoundary>
      </div>
    );
  }
}

export default App;
`

**Comment by sagni-amsalu** [comment]
![solution1](https://user-images.githubusercontent.com/92737552/221880004-90d398bc-0e15-4e68-81e5-6e98218b5dc6.png)

After changing the type-script to react js as attached above, there is no error in my end!

**Comment by EdwinBennink** [comment]
Hi @sagni-amsalu ,
Thank you so much for checking this! At least it's good to know that it should work like this. I'll give it a try with plain JavaScript too. It smells like some kind of configuration issue.

**Comment by sedghi** [comment]
Hopefully this is what you are looking for  https://docs.ohif.org/platform/services/ui/ui-notification-service
