### ISSUE TITLE
camera/view for an SR viewport resets when activating a different viewport

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3209]
### Describe the Bug

When displaying an SR together with other viewports, changing focus from the SR viewport to another viewport causes view items like pan, zoom, rotation, window level... (not sure what else) to reset.

### Steps to Reproduce:

1. Launch the OHIF viewer with a study that contains SRs.
2. View one SR with at least one other viewport.
3. Manipulate the SR (say zoom it in or out).
4. Click withing a different viewport.

### The current behavior

The SR loses the view manipulations (e.g. zoom).

### The expected behavior

The SR viewport's view should remain.

https://user-images.githubusercontent.com/109477394/222487244-7c60b226-ae28-4103-bf7f-ba6002b0d03f.mp4

### Preliminary Investigation

Some debugging showed that the `OHIFCornerstoneViewport` is getting reloaded via `loadViewportData` because the viewport's type is changing when it is enabled/disabled.
> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
@jbocce I think it is fixed right?

**Comment by jbocce** [comment]
It is fixed.
