### ISSUE TITLE
 Issue with displaying multiple frames from ULTRASOUND DICOM files in OHIF

### ISSUE THREAD

**Issue by LumiProj** [OHIF/Viewers#3216]
Hi All,

I have obtained the OHIF source code from the Github repository and am currently experimenting with it. My objective is to load a DICOM study along with its complete series and instances from a JSON file. I have referred to the documentation provided in the following link: [DICOM JSON | OHIF](https://v3-docs.ohif.org/configuration/datasources/dicom-json/) and have successfully converted my DICOM study into JSON format. Although the viewer appears to be functioning properly, I have encountered an issue where the ULTRASOUND files, which may contain multiple frames, are not being displayed. I am uncertain as to the exact cause of this issue, but it is possible that something may be missing from the JSON file. For your convenience, Following is my JSON file that I am currently using with the OHIF viewer.
 {
  "studies": [
    {
      "StudyInstanceUID": "1.2.840.113680.4.103.72907.20101006160156",
      "StudyDate": 634219200000000000,
      "StudyTime": null,
      "PatientName": null,
      "PatientID": null,
      "AccessionNumber": null,
      "PatientAge": null,
      "PatientSex": null,
      "series": [
        {
          "SeriesInstanceUID": "1.2.840.113680.4.103.72907.20101006160156.0.1.1",
          "SeriesNumber": "1",
          "Modality": null,
          "SliceThickness": 0.0,
          "instances": [
            {
              "metadata": { 
                "Columns": 576,
                "Rows": 456,
                "InstanceNumber": 1,
                "SOPClassUID": "1.2.840.10008.5.1.4.1.1.3.1",
                "PhotometricInterpretation": "YBR_FULL_422",
                "BitsAllocated": 8,
                "BitsStored": 8,
                "PixelRepresentation": 0,
                "SamplesPerPixel": 3,
                "PixelSpacing": null,
                "HighBit": 7,
                "ImageOrientationPatient": null,
                "ImagePositionPatient": null,
                "FrameOfReferenceUID": null,
                "ImageType": ["ORIGINAL", "PRIMARY"],
                "Modality": "US",
                "SOPInstanceUID": "1.2.840.113680.4.103.72907.20101006160156.0.1.1",
                "SeriesInstanceUID": "1.2.840.113680.4.103.72907.20101006160156.0",
                "StudyInstanceUID": "1.2.840.113680.4.103.72907.20101006160156",
                "WindowCenter": 220,
                "WindowWidth": 439,
                "SeriesDate": 0
              },
              "url": "dicomweb:http://localhost:3000/LIDC-IDRI-0001/01-01-2000-30178/3000566.000000-03192/IM00000.dcm"
            }
          ]
        },
        {
          "SeriesInstanceUID": "1.2.840.113680.4.103.72907.20101006160156.0.1.2",
          "SeriesNumber": "1",
          "Modality": null,
          "SliceThickness": 0.0,
          "instances": [
            {
              "metadata": {
                "Columns": 576,
                "Rows": 456,
                "InstanceNumber": 2,
                "SOPClassUID": "1.2.840.10008.5.1.4.1.1.6.1",
                "PhotometricInterpretation": "YBR_FULL_422",
                "BitsAllocated": 8,
                "BitsStored": 8,
                "PixelRepresentation": 0,
                "SamplesPerPixel": 3,
                "PixelSpacing": null,
                "HighBit": 7,
                "ImageOrientationPatient": null,
                "ImagePositionPatient": null,
                "FrameOfReferenceUID": null,
                "ImageType": ["ORIGINAL", "PRIMARY"],
                "Modality": "US",
                "SOPInstanceUID": "1.2.840.113680.4.103.72907.20101006160156.0.1.2",
                "SeriesInstanceUID": "1.2.840.113680.4.103.72907.20101006160156.0",
                "StudyInstanceUID": "1.2.840.113680.4.103.72907.20101006160156",
                "WindowCenter": 220,
                "WindowWidth": 439,
                "SeriesDate": 0
              },
              "url": "dicomweb:http://localhost:3000/LIDC-IDRI-0001/01-01-2000-30178/3000566.000000-03192/IM00001.dcm"
            }
          ]
        }
      ],
      "NumInstances": 35,
      "Modalities": "US"
    }
  ]
}

**Comment by LexusTI** [comment]
Hi,

I have the same problem when passing an MG image. Is there something wrong with my json file?

{
        "studies": 
        [
            {
                "StudyInstanceUID": "1.2.840.113681.2206606139.739.3355346425.680", 
                "StudyDescription": "Mammography", 
                "StudyDate": "20111231", 
                "StudyTime": "181417", 
                "PatientName": "Smith Nathalie", 
                "PatientID": "777777", 
                "AccessionNumber": "ACC456", 
                //"PatientAge": "", 
                "PatientSex": "F", 
                "series": 
                [
                    {
                        "SeriesInstanceUID": "1.2.840.113681.2206606139.739.3355346425.681.1", 
                        "SeriesDescription": "R CC", 
                        "SeriesNumber": 1, 
                        "Modality": "MG", 
                        "SliceThickness": "", 
                        "instances": 
                        [
                            {
                                "metadata": 
                                {
                                    "Columns": 2560, 
                                    "Rows": 3328, 
                                    "InstanceNumber": 53, 
                                    "SOPClassUID": "1.2.840.10008.5.1.4.1.1.1.2", 
                                    "PhotometricInterpretation": "MONOCHROME2", 
                                    "BitsAllocated": 16, 
                                    "BitsStored": 12, 
                                    "PixelRepresentation": 0, 
                                    "SamplesPerPixel": 1, 
                                    "PixelSpacing": [0.07, 0.07], 
                                    "HighBit": 11, 
                                    "ImageOrientationPatient": ["P", "L"], 
                                    "ImagePositionPatient": [], 
                                    //"FrameOfReferenceUID": "", 
                                    "ImageType": ["DERIVED", "SECONDARY"], 
                                    "Modality": "MG", 
                                    "SOPInstanceUID": "1.2.840.113681.2206606139.739.3355346425.685.1", 
                                    "SeriesInstanceUID": "1.2.840.113681.2206606139.739.3355346425.681.1", 
                                    "StudyInstanceUID": "1.2.840.113681.2206606139.739.3355346425.680", 
                                    "WindowCenter": 2047.0, 
                                    "WindowWidth": 4096.0, 
                                    "SeriesDate": "20070430"
                                }, 
                                "url": "dicomweb:https://lexusbucketnew.s3.amazonaws.com/imagens_dicom/1.2.840.113681.2206606139.739.3355346425.680/1.2.840.113681.2206606139.739.3355346425.685.1.dcm"
                            }
                        ]
                    }
                ], 
                "NumInstances": 1, 
                "Modalities": "MG"
            }
        ]
}

**Comment by sedghi** [comment]
closing in favor of the other one
