### ISSUE TITLE
No Thumbnails at all

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#3219]
Hello All,

With following configuration for OHIF v3 and Orthanc, I cannot get any thumbnail loaded. The left side bar is completely empty. The viewport loads the images and I could move between multiple series via keyboard shortcut, so this works. However, the thumbnail does not show/load any sequences. The browser shows 404 error.

I am using IIS and reverse proxy.

Any help would be greatly appreciated.

**browser error ...**
`request failed:  
XMLHttpRequest { onreadystatechange: onreadystatechange(), readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "https://dicomweb.mydomain.com/orthanc/dicom-web/studies?lim…tanceUID=1.2.392.200036.9123.100.12.11.12061.202302141090233", status: 404, statusText: "Not Found", responseType: "json", response: null }`

**OHIF config**
```
  dataSources: [
    {
      friendlyName: 'Orthanc',
      namespace: '@ohif/extension-default.dataSourcesModule.dicomweb',
      sourceName: 'dicomweb',
      configuration: {
        name: 'orthanc',
	wadoUriRoot: '/orthanc/wado',
	qidoRoot: '/orthanc/dicom-web',
	wadoRoot: '/orthanc/dicom-web',
        qidoSupportsIncludeField: false,
        supportsReject: false,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: false,
        supportsWildcard: true,
        staticWado: true,
        singlepart: 'bulkdata,video,pdf',
      },
    },
  ],
```
**Orthanc Web Config**
```
 DicomWeb" : {
	"Enable" : true,         
	"Root" : "/dicom-web/",  
	"EnableWado" : true,     
	"WadoRoot" : "/wado",    
	"Ssl" : false,           
        "StudiesMetadata" : "Full",  
        "SeriesMetadata" : "Full"   
    }
```

![Screenshot 2023-03-06 100620](https://user-images.githubusercontent.com/23708609/223165619-1d47e3b7-6a54-42e5-aa02-bd993ba17062.png)

**Comment by kundanashish** [comment]
Hi @richsmith123 
Did you find any solution? I am facing the same issue

**Comment by sedghi** [comment]
I think this is related to the implementation of the wildcard, that we request.

**Comment by sedghi** [comment]
We need to add documentation on this. This is a very common issue i'm seeing people are facing

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
