### ISSUE TITLE
Error when trying to create an extension to a specified directory/folder before it exists

### ISSUE THREAD

**Issue by edcheyjr** [OHIF/Viewers#3226]
### Describe the Bug

operating system is window 10

using the OHIF cli.

When trying to create an extension to a specified directory/folder before the specified folder exist it fails and errors out

### Steps to Reproduce:

1. First step
create an extension using the cli command create-extension
2. Second step
specify a folder/directory to add the extension NOTE: the folder/directory is yet to be created therefore the folder/directory should not be existing
3.
finish the create-extension process
```
Error:
node:fs:1382
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir '[AbsolutePATH]\Viewers\my-extensions\my-tools'
    at Object.mkdirSync (node:fs:1382:3)
    at createPackage ([AbsolutePATH]/Viewers/platform/cli/src/commands/createPackage.js:24:6)
    at file:[AbsolutePATH]/Viewers/platform/cli/src/index.js:76:7    
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '[AbsolutePATH]\Viewers\\my-extensions\\my-tools'
}
```

### The current behavior
errors out with the error above 
mkdir fails since there is no such directory

### The expected behavior
should create the folder for this instance "my-extension" directory/folder should be created and add the extension "my-tools" inside it

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
I prefer this approach as a safety measure. I want to avoid any accountability for potential accidental deletion of sensitive data that could occur due to automatic creation.
