### ISSUE TITLE
Impossible to load specific series in a study by Url: <base_url>/study/<studyInstanceUid>/series/<seriesInstanceUid>

### ISSUE THREAD

**Issue by cherhaishan** [OHIF/Viewers#3227]
### Describe the Bug

_Impossible to ooad specific series in a study by Url: <base_url>/study/<studyInstanceUid>/series/<seriesInstanceUid>

### Steps to Reproduce:

1. clone the project 
2. run these commands:
3. yarn config set workspaces-experimental true
4. yarn install
5. yarn orthanc:up
7. yarn dev:orthanc
8. upload some dicom images in orthanc
9. wait until http://localhost:3000 displays a list of studies
10. note a serie uid with its study uid in orthanc
11. try to open in browser: http://localhost:3000/study/1.3.6.1.4.1.5962.99.1.2786334768.1849416866.1385765836848.3.0/series/1.3.6.1.4.1.5962.99.1.2786334768.1849416866.1385765836848.3.0

```js

```

### The current behavior

_it shows that: Sorry, this page does not exist.
[Go back to the Study List](http://localhost:3000/)_

### The expected behavior

_The viewer should display images in the given serie_

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please refer to the URL configuration documentation page at https://docs.ohif.org/configuration/url.
