### ISSUE TITLE
Refresh of Study List page performs two identical XHR requests for the list data

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3230]
### Describe the Bug

Either refreshing or returning to the Study List page from the viewer results in two identical XHR requests for the list data. Only one is needed.

### Steps to Reproduce:

1. Visit https://v3-demo.ohif.org/.
2. Open the browser developer tools network tab.
3. In the network tab's filter box, enter `studies`.
4. Refresh the browser.

### The current behavior

In the network tab, 2 identical XHR requests are recorded to fetch the study list data.

### The expected behavior

Only one is needed.

https://user-images.githubusercontent.com/109477394/224197152-e7e68df1-7909-4ccb-8549-53bb0b803f41.mp4

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by jbocce** [comment]
The suspect offending code is in `DataSourceWrapper`. In particular the React `useEffect` where `getData` is performed looks like a prime suspect. That effect is both setting the `isLoading` state and is also dependent on that state variable.

**Comment by james-hanks** [comment]
Investigating #3427 IDC PR to determine how fix is related
