### ISSUE TITLE
Calibration changes W/L values and mess up the measurements 

### ISSUE THREAD

**Issue by Zaid-Safadi** [OHIF/Viewers#3234]
### Describe the Bug

When using the calibration tool, two issues occur:
1. Immediately W/L values are changed
2. When you scroll away from the frame where the calibration happens and scroll back, the measurements are misplaced 

### Steps to Reproduce:

1. Load a multi-frame series
2. Draw a measurement line
3. Select calibration tool and apply calibration to the frame
4. Notice W/L values change
5. scroll down then scroll back up, notice the existing measurement location has changed

```js
Please use code blocks to show formatted errors or code snippets
```

### The current behavior

_A clear and concise description of what happens instead of the expected
behavior._

* Notice W/L values change
* scroll down then scroll back up, notice the existing measurement location has changed
See attached GIF

### The expected behavior

_A clear and concise description of what you expected to happen._

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.
![OHIF-Calib-Bug](https://user-images.githubusercontent.com/10813109/224577135-734e4852-a172-4a22-b764-b63287f1e795.gif)

**Comment by sedghi** [comment]
@jbocce ditto

**Comment by jbocce** [comment]
No longer an issue.
