### ISSUE TITLE
why don't i apply blue theme like below?

### ISSUE THREAD

**Issue by mesutxk** [OHIF/Viewers#3238]
Hello,

ohif v3 latest version i am following the steps as explained on the site.

1
# If you haven't already, enable yarn workspaces
yarn config set workspaces-experimental true
2
# Restore dependencies
yarn install
3
# Build source code for production
yarn run build

later;

I am using the yarn run dev command. system is booting

The screen image that should be opened normally is blue, but the body is black design.
![2](https://user-images.githubusercontent.com/66259549/224624692-4af86f43-4c23-4ea1-9b5d-c86dffc21013.png)

why don't i apply blue theme like below?

![1](https://user-images.githubusercontent.com/66259549/224624800-df286202-111d-457c-b925-5aa25bf5f12b.png

**Comment by mesutxk** [comment]
No one to help?

**Comment by k3nw4y** [comment]
you have to switch the branch to v3 stable
`git switch v3-stable
`
[v3 docs](https://v3-docs.ohif.org/development/getting-started)

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
