### ISSUE TITLE
 Micro Frontend | CORS Error while loading remote app to viewer

### ISSUE THREAD

**Issue by ak-mile9** [OHIF/Viewers#3240]
### Describe the Bug
I have use case of consuming my remote app inside ohif viewer screen. 
eg.  `http://somehost:8081/remoteEntry.js`
I configured webpack (as below) to federate the module, and also i can see it is getting triggered while loading OHIF viewer. But since it is in some other domain so it is blocking the access. 

_A clear and concise description of what the bug is._

### Steps to Reproduce:

code inside ``viewer/.webpack/webpack.pwa.js``

 ```js
new ModuleFederationPlugin({
        name: 'reports',

        remotes: {
          './Reports': 'reports@http://somehost:8081/remoteEntry.js',
        },
      })
```
```js
 headers: {
        'Cross-Origin-Embedder-Policy': 'require-corp',
        'Cross-Origin-Opener-Policy': '*',
        'Access-Control-Allow-Origin': '*',
        'Cross-Origin-Resource-Policy': 'cross-origin',
        'Access-Control-Allow-Headers':
          'X-Requested-With, content-type, Authorization',
      }

```

What is the correct approach to consume the remoteApp inside viewer. ?

![image](https://user-images.githubusercontent.com/103760836/224989411-7e3f7c2c-878c-46b3-9e0b-b71919c81a47.png)

**Comment by sedghi** [comment]
Could you please review our comprehensive documentation on Cross-Origin Resource Sharing (CORS) and OHIF? Below are the links provided for your reference.

- https://docs.ohif.org/deployment/cors
- https://docs.ohif.org/deployment/iframe
