### ISSUE TITLE
I've just download the source code, but dicomjson config is not working as previously

### ISSUE THREAD

**Issue by renatofs** [OHIF/Viewers#3267]
I've just dowloaded the source code from master and tried to run as I used to with the version from last year.

On that version I configured dicomJson as below, on default.js:

dataSources: [
    {
      friendlyName: 'dicom json',
      namespace: '@ohif/extension-default.dataSourcesModule.dicomjson',
      sourceName: 'dicomjson',
      configuration: {
        name: 'json',
      },
    },
...
]

But now it seems that it changed the to use dicomJson.

**Comment by renatofs** [comment]
Anybody?

**Comment by bluesteel23** [comment]
Hi 
did you find resolution to this? I'm facing the similar issue.

Thanks,

**Comment by renatofs** [comment]
Hi @bluesteel23 the issue is the same for me, did you get anything?

**Comment by bluesteel23** [comment]
Unfortunately no. I have reached out on the OHIF slack channel as well. no
luck. what error are you getting?

**Comment by bluesteel23** [comment]
Unfortunately no. I have reached out on the OHIF slack channel as well. no
luck. what error are you getting?

**Comment by sedghi** [comment]
what error are you getting, I'm not able to reproduce your error in our demos

https://viewer.ohif.org/viewer/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json
https://viewer-dev.ohif.org/viewer/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json

**Comment by davidlatuno** [comment]
I'm on version 3.6.0

When running `yarn run build` and then hosting the viewer I get a 404 trying to hit `/viewer/dicomjson`

**Comment by bluesteel23** [comment]
Getting 404 not found. Here are few screenshots when tested the build output locally . Referred to the following instructions
![image](https://github.com/OHIF/Viewers/assets/132684122/26769511-8b06-447f-aa2d-50da3a0bd465)


![image](https://github.com/OHIF/Viewers/assets/132684122/026da56e-d3f8-4e83-aa28-a9f93763df73)

**Comment by davidlatuno** [comment]
@bluesteel23 I might have run into a similar situation.

When using `http-server`, if:
* `http://localhost:8080` loads correctly
* Viewing other routes from the root page (example: from a mouse click) loads correctly
* Trying to directly go to other routes (example: typing URL into browser) returns a 404

It is probably a routing configuration issue. React is normally a client-side rendered application. This stackoverflow comment details the underlying system and potential options to move forward: https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually/36623117#36623117

Personally I was not able to directly hit a route other than the root page locally unless I used the dev-server (https://github.com/LunaDNA/ohif-viewers/blob/master/package.json#L30).

I was able to get it working when deployed in production by explicitly routing requests back to the root at the server level (one of the options mentioned in the stackoverflow comment above).

**Comment by bluesteel23** [comment]
@davidlatuno  your response was very helpful and to the point. Got clear understanding of the exact behavior.  Thank you very much for your response!

Also, as @sedghi advised , 
we got the local testing of the build output done using following command(instead of using http-server) 
 **npx serve ./dist -l 8080 -s**

"it works the reason is that OHIF is a SPA  and any 404 should be re-directed to index.html that is apparently default behaviour in netlify"

In our case, the viewer will be deployed to azure  blob storage as static website. In that case, we have to set error page as 'index.html' while configuring the website. This takes care of routing in case of 404.

**Comment by sedghi** [comment]
Take a look at the end of https://docs.ohif.org/configuration/dataSources/dicom-json
