### ISSUE TITLE
Results Per Page Dropdown is hard to see

### ISSUE THREAD

**Issue by Michael-Andersen** [OHIF/Viewers#3268]
### Describe the Bug

When the results per page dropdown is opened and it overlays the studylist it is hard to see the options (reproducible here: https://v3-demo.ohif.org/) . I have it always opening downwards as a temporary fix on my deployment. But maybe a minor style adjustment would be a better fix.

**Comment by JennyLeePMH** [comment]
See below picture, from OHIF's demo site:
![ohif_dropdown_feedback](https://user-images.githubusercontent.com/4551564/228027976-3a1964e6-473d-44f5-9865-9f29245430f1.png)

**Comment by sedghi** [comment]
Fixed
