### ISSUE TITLE
ASP.NET Core API using JSON

### ISSUE THREAD

**Issue by LumiProj** [OHIF/Viewers#3276]
Dear OHIF Viewer team,

I am currently using the OHIF Viewer in my web application and I am experiencing an issue with playing all frames of a DICOM file when loading studies through my ASP.NET Core API using JSON. While this functionality works fine in local mode, it seems to be malfunctioning when the studies are loaded via my API.

I have followed the official documentation of OHIF Viewer closely and cannot seem to identify the missing segment causing the issue.

I would greatly appreciate your guidance in resolving this matter. Could you please advise me on what I may be missing or what steps I can take to troubleshoot this issue?

Thank you for your assistance.

**Comment by sedghi** [comment]
It might be that you need to add a fallback from 404 to index.html

see here https://docs.ohif.org/configuration/dataSources/dicom-json
