### ISSUE TITLE
Switching series in MPR with the crosshairs tool on throws exception

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3282]
### Describe the Bug

When switching the series displayed in MPR while the crosshairs tool is on throws the following exception in the console...
```
CrosshairsTool.js:673 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at CrosshairsTool.js:673:100
    at Array.filter (<anonymous>)
    at VM._filterAnnotationsByUniqueViewportOrientations (CrosshairsTool.js:670:77)
    at VM.renderAnnotation (CrosshairsTool.js:293:51)
    at triggerAnnotationRender.js:93:43
    at Array.forEach (<anonymous>)
    at triggerAnnotationRender.js:97:26
    at d (draw.js:4:5)
    at Object._triggerRender (triggerAnnotationRender.js:89:9)
    at _renderFlaggedViewports (triggerAnnotationRender.js:17:26)
```

### Steps to Reproduce:

1. Launch MPR for a reconstructable series in OHIF.
2. Turn on the crosshairs tool.
3. Drag and drop and/or double click a different reconstructable series in the series tray to display it in MPR.

### The current behavior

The exception mentioned above is thrown. In general, it appears that the client no longer functions.

### The expected behavior

The exception above is not thrown and the crosshairs tool remains active and can be used on the subsequent series.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by daker** [comment]
Hello, any fix or workaround for this issue? it seems that the ids of the viewports are wrong when you switch series

**Comment by sedghi** [comment]
I believe we fixed that in master which is our dev 

https://github.com/OHIF/Viewers/assets/7490180/6c8efbb1-02dc-4e39-aeb2-5912b4952d17




PS: 
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by daker** [comment]
Yes thanks it's fixed on dev
