### ISSUE TITLE
Limit DICOM images access

### ISSUE THREAD

**Issue by MaxiPigna** [OHIF/Viewers#3289]
Hello! I am trying to implement access permissions on DICOM images.
I created an Azure DICOM service and uploaded some DICOM images. Then, I deployed OHIF Viewer and connected it to Azure DICOM. To achieve this, I followed these [instructions](https://github.com/microsoft/dicom-ohif) and everything works fine.

The problem is that once a User is logged in, he/she can access all DICOM images stored on the DICOM service, while the idea is to make accessible only a subset of them. In other words, a User can see an image only if he/she has permission to read it.
Could you help me to understand what is the best way to achieve this? Thanks 😊

**Comment by wangning08115** [comment]
you can do this:
1.Setup a web api system.
add one api such as "api/Account/Authentication" , the api input studyuid and user token parameter ,so you can Authentication
2. In Viewers first load send a call to your api  "api/Account/Authentication", so you can return true or false , when false not load any other dicom images.
3. So you can Limit usee.

**Comment by MaxiPigna** [comment]
> you can do this: 1.Setup a web api system. add one api such as "api/Account/Authentication" , the api input studyuid and user token parameter ,so you can Authentication 2. In Viewers first load send a call to your api "api/Account/Authentication", so you can return true or false , when false not load any other dicom images. 3. So you can Limit use.

Thanks @wangning08115. Besides the Authentication API, do I need to modify the code of the Viewer or is it already designed to implement di flow?

**Comment by wangning08115** [comment]
you can add new code logic to viewers to call your Authentication API.
My system when api return false , i alert a message "Permission denied".

**Comment by sedghi** [comment]
OHIF should not be involved in this matter as it falls under the server-side concerns.
