### ISSUE TITLE
Provide a simple integration with react

### ISSUE THREAD

**Issue by fugset** [OHIF/Viewers#3295]
I had a very hard time trying to integrate OHIF DICOM viewer in a react app, can you help please

**Comment by wangning08115** [comment]
1. Build the Viewers to an standalone web site.
2. Then you can use html iframe link to your site in your react app.

**Comment by junxiant** [comment]
> I had a very hard time trying to integrate OHIF DICOM viewer in a react app, can you help please

Hello,

Have you had any progress with this so far? Maybe this might be for building the viewer in a standalone web

[https://docs.ohif.org/deployment/build-for-production](url)
