### ISSUE TITLE
Heavy ECHO studies does not display in v3. Works in v2

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#3299]
I have encountered issues with Echo studies v3. They do not display properly. I am using v3 (2023-04-01). However, these same studies are functioning properly in the previous version (v2). I am not sure what is causing this issue. Do you have any idea what could be the problem?

I have [attached three sample echo files](https://drive.google.com/file/d/13eyS16FzBfzqVoelWU54g3hdqUU7a0Dc/view?usp=share_link).

Please note all the other modalities are working fine in v3.

Thank you in advance.
![Screenshot 2023-04-02 121633](https://user-images.githubusercontent.com/23708609/229368987-803ed5d7-6df0-4865-838e-ee49e096ef54.png)

**Comment by olivert1969** [comment]
![image](https://user-images.githubusercontent.com/38795765/229526462-cd6e3cc5-c5b5-4427-b311-6e949d46e323.png)

@richsmith123 
screencap from v1 Meteor version using
"imageRendering": "wadouri"
"thumbnailRendering": "wadouri"

**Comment by richsmith123** [comment]
Thank you for the response @olivert1969!

Interestingly, in v3 if I replace wadors with wadouri for both imgeRendering and thumbnailRendering then the images are shown correctly. This issue has already been reported by @asemeria [back in Aug 23, 2022](https://github.com/OHIF/Viewers/issues/2887) but no one has ever commented the solution. In fact, I see @sedghi commented awaiting for reproduction in Jan of 11.

In [Jul 29, 2019](https://github.com/OHIF/ohif-core/issues/62) @swederik commented that wado-uri is slower due to duplicate retrieval and default should be waro-rs. 

So, the issue with wadors is there as many other have commented that wadouri works but wadors not for all their studies. I don't know when the solution will be provided.

Best regards,

**Comment by sedghi** [comment]
I'm investigating this early next week.

**Comment by richsmith123** [comment]
Thank you @sedghi for your attention! I look forward to the fix.
Best regards,

**Comment by richsmith123** [comment]
Dear @sedghi, did you get a chance to look into this issue? You know I have been using v2 for quite some time and I have no issues with either US or ECHO studies. However, v3 has some bug which prevents me switching. I would appreciate if you could look into this. Thank you so much!!

**Comment by sedghi** [comment]
Can you try with latest push to v3-stable now?

**Comment by richsmith123** [comment]
Dear @sedghi, thank you for your reply.

This morning I downloaded v3-stable. The result unfortunately remains the same.

Best regards,

**Comment by sedghi** [comment]
I can see the dicoms work in the /local route, can you try them in `v3-demo.ohif.org/local`?

**Comment by richsmith123** [comment]
Wow, works!

**Comment by richsmith123** [comment]
Well, upon further testing. The ECHO images which I have uploaded in this thread works. However, the ultrasound does not work. Both of these studies works well in v2. So, there is an improvement.

Just so you know these studies also do work in Weasis, RadiAnt, and of course OHIF v2 without any issues.

Best regards and thank you @sedghi for your kind attention.

**Comment by richsmith123** [comment]
Hello @sedghi ,

Interesting finding - the ultrasound does work in the v3-demo.ohif.org/local. This is very encouraging. However, it only works if I only load one image/frame. In other words, if I load the entire folder than the images does not display properly. 

Hope you could shed some light here :).

**Comment by sedghi** [comment]
I used DCM4CHEE and saw that thumbnails are incorrect, but viewport is correct, is that what you see as well?

![image](https://user-images.githubusercontent.com/7490180/235026229-5d2b59a3-f5c6-4a4f-a49b-887eb466d4a6.png)

**Comment by richsmith123** [comment]
For me, thumbnail and viewport does not work if used against Orthanc. It also wouldn't work if I use dicomjson.

However, the **v3-demo.ohif.org/local** did work just fine for my ECHO studies. It also worked for ultrasound if I send only one dicom file but would not work for the entire directory.

Many thanks!!!

**Comment by sedghi** [comment]
can you try now

**Comment by richsmith123** [comment]
Dear @sedghi, thank you so very much for getting back to me. I truly appreciate it!

I downloaded the latest files and ran against all modalities from various sources. Good news is that it worked against all modalities including for ECHO and ultrasound studies.  However, for one center only their ultrasound still does not work. I believe we are very close to nailing this issue down. I have attached the [ultrasound link](https://drive.google.com/file/d/17twVqr9b7DT1nA494N726OTHEy_AMVjh/view?usp=share_link) for your reference. I would greatly appreciate it if you kindly look into this please. 

Again, thank you so very much for your attention!

![Screenshot 2023-05-14 155937](https://github.com/OHIF/Viewers/assets/23708609/258e4a8c-0712-4ceb-aad4-4160b581de46)

**Comment by sedghi** [comment]
Glad to hear it is going in the right direction. I will look sometime this week

**Comment by olivert1969** [comment]
@richsmith123 wondering if your US workflow is affected by absence of Next / Previous toolbar buttons in v3? 

Reported in issue #3112

**Comment by sedghi** [comment]
we can work on adding a command that does the job for you and then in your modes you can add the toolbar that run that command, but I don't see we add those toolbar buttons to our demo

**Comment by olivert1969** [comment]
thanks - great news






---- On Wed, 17 May 2023 11:50:53 -0400 Alireza ***@***.***> wrote ---





we can work on adding a command that does the job for you and then in your modes you can add the toolbar that run that command, but I don't see we add those toolbar buttons to our demo

**Comment by richsmith123** [comment]
Dear @sedghi,
While searching through the log to check for any updates, I realized that I had forgotten to include the corresponding ultrasound which does not work. Unfortunately, all the ultrasound studies from one center continues to show issues in v3. 

Thank you for your attention. 

[Ultrasound study with issues.](https://drive.google.com/file/d/1cPbtTX7toxW1XzOsQsYTS4r8gtPpldRz/view?usp=share_link)

Best regards,

**Comment by sedghi** [comment]
Thanks, I'll check this out. what was your dicom server? or how do you retrieve them? 

PS: you can look here for some discussion on what I found for orthanc https://discourse.orthanc-server.org/t/orthanc-convert-ybr-to-rgb-but-does-not-change-metadata/3533

**Comment by richsmith123** [comment]
Dear @sedghi, Thank you for your quick reply.

We use Orthanc as our pacs. We receive studies from multiple sources and all is working as expected, expect for ultrasound from one center. Currently our OHIF v2 is working without any issues and I would like to migrate to v3 once this is taken care of.

I will definitely look into discussion [post.](https://discourse.orthanc-server.org/t/orthanc-convert-ybr-to-rgb-but-does-not-change-metadata/3533)

Again, appreciate your time and attention.

Best regards,

**Comment by sedghi** [comment]
I'm really happy that you are using orthanc, as something is not consistent in orthanc and I have posted it in theirs. So until I get a reply and find out what is going on, I can't fix it in OHIF.

**Comment by richsmith123** [comment]
Dear @sedghi,

Thank you for your reply and bringing the issue of inconsistency with Orthanc.

How would you describe the issue if I use **v3-demo.ohif.org/local** to load ultrasound directly from my file system. There I don't have any pacs involved?

[ultrasound.](https://drive.google.com/file/d/1cPbtTX7toxW1XzOsQsYTS4r8gtPpldRz/view?usp=share_link)

Best regards,

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
