### ISSUE TITLE
Instances deploy out of order

### ISSUE THREAD

**Issue by rmasad** [OHIF/Viewers#3303]
### Describe the Bug

Some Medical Centers send studies with series whose instances all come with the same "InstanceNumber". This causes the order of the studies to be 'random'.

The same study, in other viewers (like Horos), it looks good.

### Steps to Reproduce:

1. Display a study with a series whose instances all have "InstanceNumber" equal to 1
2. Scroll to that serie
3. The instances will be deployed out of order

### The current behavior

The instances deployed out of order

### The expected behavior

If all images in a series have the same "InstanceNumber" use "SliceLocation" to sort. We implement this in our OHIF fork: https://gitlab.nur.dev/foss/ohif-viewer/-/merge_requests/29/diffs

```js

  if (shallSort) {
    // If all image have the same instance number, sort by SliceLocation
    const allSameInstanceNumber = imageSet.images.every(
      instance =>
        instance.getTagValue('InstanceNumber') ===
        imageSet.images[0].getTagValue('InstanceNumber')
    );
    if (allSameInstanceNumber) {
      tagToSortInstances = 'SliceLocation';
    }

    imageSet.sortBy((a, b) => {
      // Sort by InstanceNumber (0020,0013)
      return (
        (parseInt(a.getTagValue(tagToSortInstances, 0)) || 0) -
        (parseInt(b.getTagValue(tagToSortInstances, 0)) || 0)
      );
    });
  }```

**Comment by sedghi** [comment]
is this still happening in latest master branch?

**Comment by andylinton** [comment]
I am noticing a similar problem - the order of the patient list keeps changing randomly. All the studies sent from our machine to the archive have InstanceNumber = 1

See discussion https://community.ohif.org/t/patient-list-changing-order-on-click/2093/8
