### ISSUE TITLE
where is the DIMSE from ? 

### ISSUE THREAD

**Issue by char1st** [OHIF/Viewers#331]
The importStudies  doesn't work .
https://github.com/OHIF/Viewers/blob/e1d846e3f76c81ec3612f5e24c2d128b4e94cbe3/Packages/ohif-study-list/server/methods/importStudies.js#L96

The DIMSE looks like need import and init .

**Comment by dannyrb** [comment]
Can you describe the issue you're experiencing in more detail? What are the steps to reproduce?

**Comment by char1st** [comment]
Sorry , can not reproduce
