### ISSUE TITLE
Any way to use MPR functionality without HTTPS?

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#3316]
Is there any way to use MPR functionality without HTTPS ie over plain HTTP ?  When MPR mode is activated over a HTTP connection it fails due to SharedArrayBuffer related errors.

Any help would be greatly appreciated.

**Comment by ranasrule** [comment]
anyone?

**Comment by ranasrule** [comment]
no one knows ?

**Comment by leon1227** [comment]
It's interesting that nobody cares about this issue... also it's absurd that https seems to be a must to use MPR.

**Comment by whage** [comment]
+1. OHIF is often deployed to an organization internally, where they use just IP addresses to reach their servers, no TLS certs. OHIF v3 should be accessible for such setups, as the previous version was.

**Comment by sedghi** [comment]
This issue has been discussed in length here https://github.com/OHIF/Viewers/issues/3220

Also 

Could you please review our comprehensive documentation on Cross-Origin Resource Sharing (CORS) and OHIF? Below are the links provided for your reference.

- https://docs.ohif.org/deployment/cors
- https://docs.ohif.org/deployment/iframe
