### ISSUE TITLE
Only render the serie, without all the stuff arround 

### ISSUE THREAD

**Issue by nicoesiea** [OHIF/Viewers#3325]
### Request

I'm trying to include an OHIF viewer in my own application, but I'm working with angular and I only need the viewer, not all the picture management around

**What feature or change would you like to see made?**

A way to render only the content of the viewport, not the entire application. Based on the study + series + server URL, it could be very nice to have only the viewer (with the component if needed)

**Why should we prioritize this feature?**

Low

**Comment by nicoesiea** [comment]
As it seems the only way to achieve this is to use the URL - and unfortunately I can manage the URL like this.
Is it possible to embed this viewer component inside an angular component and render it inside an iframe... That way I could manage the URL like a parameter in my component without having to change the "real" application URL.

Does someone know how to do that kind of stuff?

**Comment by StefanDenn3r** [comment]
Hi @nicoesiea, 
Thanks for being so active in this issue and keeping us updated. 
I will work on sth very similar starting in a few days. 
Therefore, I would appreciate your continued sharing of progress and maybe even the final code. 
If you are not done until I start working on this, I am very happy to also report here.

Thank you!

**Comment by sedghi** [comment]
You can take a look on how to configure url https://v3-docs.ohif.org/configuration/url

**Comment by nicoesiea** [comment]
Thank you very much @sedghi but I found already this page and I noticed this URL is not working as expected:
http://localhost:3000/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125113417.1&SeriesInstanceUID=1.3.6.1.4.1.25403.345050719074.3824.20170125113545.4

Using the latest version (in the master branch), when I start the application on dev and try this URL I get:
![image](https://user-images.githubusercontent.com/4542315/233578169-ccb8db11-0733-4e04-bb4f-64f3a4bf468e.png)

At the same time, if I try the URL with the study in the path, and the SeriesInstanceUID in the query param, like:
http://localhost:3000/viewer/1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339?SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.7009.2403.163066661055228905323984189931

It works but all the series are loaded - not only the one given as a parameter.

**NOTES:** 
* I'm still looking to understand how to integrate the application in an iframe. Yesterday it was working fine, but today I can no longer load the application. The initial error comes back:
![image](https://user-images.githubusercontent.com/4542315/233578723-95649f2b-9feb-46be-adac-139ca4399ba6.png)
- I'm still looking for a way to hide the SERIES thumbnails + the show/hide button on the menu (as I already have mine in my application)... Maybe I should modify the source code directly to match my needs :(

**Comment by sedghi** [comment]
sorry I miss guided you, that is for v3 which you can find in v3-stable, and also we are finlaizing the push to master

**Comment by StefanDenn3r** [comment]
Hi @nicoesiea,
I also didn't manage to fully extract only the viewing component via the configuration. Therefore, I created a patch for `extensions/default/src/ViewerLayout/index.tsx` based on the current v3-stable branch. 
You can then access the single series view, e.g. within an iFrame, by 
`/viewer?StudyInstanceUIDs={StudyInstanceUID}&SeriesInstanceUID={SeriesInstanceUID}`.

Since you anyways only wanted to use the OHIF Viewer in an iFrame, I hope it's not an issue, that this View gets basically unusable inside the actual viewer. 

I've attached the patch for you. I hope it helps. :)  

```
diff --git a/extensions/default/src/ViewerLayout/index.tsx b/extensions/default/src/ViewerLayout/index.tsx
index 30b8932a5..53c632df4 100644
--- a/extensions/default/src/ViewerLayout/index.tsx
+++ b/extensions/default/src/ViewerLayout/index.tsx
@@ -204,37 +204,14 @@ function ViewerLayout({
 
   return (
     <div>
-      <Header
-        menuOptions={menuOptions}
-        isReturnEnabled={!!appConfig.showStudyList}
-        onClickReturnButton={onClickReturnButton}
-        WhiteLabeling={appConfig.whiteLabeling}
-      >
-        <ErrorBoundary context="Primary Toolbar">
-          <div className="relative flex justify-center">
-            <Toolbar servicesManager={servicesManager} />
-          </div>
-        </ErrorBoundary>
-      </Header>
       <div
         className="bg-black flex flex-row items-stretch w-full overflow-hidden flex-nowrap relative"
-        style={{ height: 'calc(100vh - 52px' }}
+        style={{ height: 'calc(100vh' }}
       >
         <React.Fragment>
           {showLoadingIndicator && (
             <LoadingIndicatorProgress className="h-full w-full bg-black" />
           )}
-          {/* LEFT SIDEPANELS */}
-          {leftPanelComponents.length ? (
-            <ErrorBoundary context="Left Panel">
-              <SidePanel
-                side="left"
-                activeTabIndex={leftPanelDefaultClosed ? null : 0}
-                tabs={leftPanelComponents}
-                servicesManager={servicesManager}
-              />
-            </ErrorBoundary>
-          ) : null}
           {/* TOOLBAR + GRID */}
           <div className="flex flex-col flex-1 h-full">
             <div className="flex items-center justify-center flex-1 h-full overflow-hidden bg-black relative">
@@ -247,16 +224,6 @@ function ViewerLayout({
               </ErrorBoundary>
             </div>
           </div>
-          {rightPanelComponents.length ? (
-            <ErrorBoundary context="Right Panel">
-              <SidePanel
-                side="right"
-                activeTabIndex={rightPanelDefaultClosed ? null : 0}
-                tabs={rightPanelComponents}
-                servicesManager={servicesManager}
-              />
-            </ErrorBoundary>
-          ) : null}
         </React.Fragment>
       </div>
     </div>
```

While the solution is not ideal, it doesn't introduce too much overhead. 

Thanks again @nicoesiea for sharing your process. 

Of course, also thanks to @sedghi and the OHIF Team! This project is so amazing!

**Comment by nicoesiea** [comment]
I'm currently wondering if it is not possible now to integrate the OHIF viewer as a REACT component in my angular application.
But my first question is: is the npm package up to date?
![image](https://github.com/OHIF/Viewers/assets/4542315/0b47b651-5b42-4158-8082-cafdfeb46a5b)


Google help to find this page: https://www.npmjs.com/package/ohif-viewer?activeTab=versions
But I wonder if I should use it or not... It seems to be a very old version :(

**Comment by sedghi** [comment]
no it is not up to date and you should not use it. We don't offer packaged viewer as it is kind of impossible with wasm and codecs and webworkers. You should use an iframe for it read more here https://docs.ohif.org/deployment/iframe

**Comment by axetroy** [comment]
I search around and did not find a solution for this.

I am looking for a viewer that only render the DCM file like pdf viewer did.

eg. `https://mozilla.github.io/pdf.js/web/viewer.html?file=xxxx.pdf`

NO `api`/`proxy`, just static assets.
