### ISSUE TITLE
May I have a dicom file?

### ISSUE THREAD

**Issue by lang18276916053** [OHIF/Viewers#3329]
### Request
May I have a dicom file?zip formatt

**What feature or change would you like to see made?**

...

**Why should we prioritize this feature?**

...

**Comment by lang18276916053** [comment]
My version is  v3-stable

**Comment by nicoesiea** [comment]
I do not understand why did you create an issue here to request DICOM file?
The default configuration targets the DCM4CHEE server, it could give you many examples. 
May I google it for you? https://www.dicomlibrary.com/?manage=1b9baeb16d2aeba13bed71045df1bc65

**Comment by lang18276916053** [comment]
thank you

**Comment by lang18276916053** [comment]
But I want a copy of the seg data

**Comment by nicoesiea** [comment]
Did you search on https://www.cancerimagingarchive.net/collections/ ?
These images can include segmentation data for various structures of interest, such as tumors, lymph nodes, etc.
You can also search directly on GitHub opened projects, many of them have some DICOM files as samples.

Finally, I seem to recall that many online machine learning resources, such as deep learning platforms like TensorFlow or PyTorch, provide sample DICOM images with segmentation data in the context of machine learning. You can search for tutorials or sample machine-learning projects related to medical image segmentation to find DICOM images with segmentation data.

**Comment by lang18276916053** [comment]
![image](https://user-images.githubusercontent.com/56471842/233329974-40786baf-27ed-4c4b-9661-8ceb29d5ef10.png)
Thank you for your reply, but I would like to get the example of seg-dicom on the official website, so that Python technicians can make the same one in the format of seg-dicom file. Is there any way to achieve this?

**Comment by lang18276916053** [comment]
https://v3-demo.ohif.org/
