### ISSUE TITLE
Measurements and Study Date are not translated

### ISSUE THREAD

**Issue by nicoesiea** [OHIF/Viewers#3334]
### Describe the Bug

On **Measurements** right panel I can see the words "Measurements" and  "StudyDate" which are not translated into the current language.
![image](https://user-images.githubusercontent.com/4542315/233598172-1073715e-d1f0-423c-87ff-0d9111d9b923.png)

### Steps to Reproduce:

1. Open the viewer
2. Change the default language: top right corner, click on Options, go on panel General, and choose Spanish or French
3. Submit the selection by clicking on the SAVE button
4. Measurements menu is still the same when it should be "Medidas" or "Mesures" in Spanish or in French
5. Inside the Measurements menu, the word StudyDate looks to be wrong (probably a bad translation keyword)

### The current behavior

The translation is not working as expected

### The expected behavior

The displayed word must be translated according to the selected language

**NOTE:** sorry if I was wrong to open this issue - that the only way I know how to report this kind of bug (if it is a bug!)

**Comment by sedghi** [comment]
@jbocce ditto

**Comment by jbocce** [comment]
`Measurements` is still displayed with NO translation, however `StudyDate` no longer appears in the measurements' side panel

**Comment by sedghi** [comment]
@nicoesiea Hey, do you mind checking this documentation https://docs.ohif.org/platform/internationalization
and maybe shoot us a PR?

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
