### ISSUE TITLE
Turning on crosshairs in MPR prompts for tracking measurements and crashes when opening the tracked measurements panel

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3340]
### Describe the Bug

When turning on crosshairs, there should NOT be a prompt for tracking measurements.

### Steps to Reproduce:

1. Launch MPR
2. Turn on crosshairs.

### The current behavior

A prompt is displayed for whether to track measurements or not. I do not believe it should be shown. Answering yes to the prompt and then opening the measurements tracking panel causes the app to crash.

### The expected behavior

No prompt to track measurements and no crash.

_A clear and concise description of what you expected to happen._

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by ladeirarodolfo** [comment]
Joe a possible Fix for that would be: Prevent store measurement to fire exception in case there is nothing to save


commit 376b8991fc22945935126f1a83699b5b88651992
Author: Rodolfo <rodolfo@radicalimaging.com>
Date:   Fri Apr 28 14:24:50 2023 -0300

    fix siltently kip store measurement in case at end there is nothing to save

diff --git a/extensions/cornerstone-dicom-sr/src/commandsModule.js b/extensions/cornerstone-dicom-sr/src/commandsModule.js
index 09106c62b..2b1bf652c 100644
--- a/extensions/cornerstone-dicom-sr/src/commandsModule.js
+++ b/extensions/cornerstone-dicom-sr/src/commandsModule.js
@@ -27,6 +27,11 @@ const _generateReport = (
     additionalFindingTypes
   );
 
+  // cut in case there is nothing to save
+  if (!Object.keys(filteredToolState).length) {
+    return;
+  }
+
   const report = MeasurementReport.generateReport(
     filteredToolState,
     metaData,
@@ -106,6 +111,11 @@ const commandsModule = ({}) => {
           options
         );
 
+        // just skip in case there is nothing to save
+        if (!naturalizedReport) {
+          return;
+        }
+
         const { StudyInstanceUID, ContentSequence } = naturalizedReport;
         if (!ContentSequence?.[4].ContentSequence?.length) {
           console.log(
diff --git a/extensions/default/src/Actions/createReportAsync.tsx b/extensions/default/src/Actions/createReportAsync.tsx
index 5af20aa5b..c9956e82e 100644
--- a/extensions/default/src/Actions/createReportAsync.tsx
+++ b/extensions/default/src/Actions/createReportAsync.tsx
@@ -42,6 +42,12 @@ async function createReportAsync(
       'CORNERSTONE_STRUCTURED_REPORT'
     );
 
+    if (!naturalizedReport) {
+      console.log('No report to save');
+
+      return;
+    }
+
     const { SeriesDescription, StudyInstanceUID } = naturalizedReport;
     measurementService.setSeriesInformation(
       StudyInstanceUID,

**Comment by sedghi** [comment]
@jbocce Can you verify this again happens and close if not? Thanks

**Comment by jbocce** [comment]
@sedghi, this is no longer reproducible - closing.
