### ISSUE TITLE
need help in configuring V3 ohif viewer with my webapp which sends the .json url to the viewer

### ISSUE THREAD

**Issue by darshan-shinde** [OHIF/Viewers#3342]
### Describe the Bug

_A clear and concise description of what the bug is._

### Steps to Reproduce:

1. First step
2. Second step
3. ...

```js
Please use code blocks to show formatted errors or code snippets
```

### The current behavior

_A clear and concise description of what happens instead of the expected
behavior._

### The expected behavior

_A clear and concise description of what you expected to happen._

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by Hasan-aga** [comment]
you have not provided any description of your problem

**Comment by sedghi** [comment]
https://docs.ohif.org/configuration/dataSources/dicom-json
