### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by yensis80** [OHIF/Viewers#3346]
Need help with this problem. a solution is not found. the guide of https://v3-docs.ohif.org/development/getting-started is followed
Feature computer
Windows 10 Pro 22H2 
RAM 16GB 
Ohif v3-stable 
Node v18.18.16.0 
yanr v1.22.19 
npm v9.5.1

![IT](https://user-images.githubusercontent.com/87835845/235351885-478bb734-d0a5-4694-8c16-e8ffd68a9782.JPG)

`C:\ohif>npm start

> start
> yarn run dev

yarn run v1.22.19
$ lerna run dev:viewer --stream
lerna notice cli v3.18.3
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run dev:viewer"
@ohif/viewer: $ yarn run dev
@ohif/viewer: $ cross-env NODE_ENV=development webpack-dev-server --config .webpack/webpack.pwa.js
@ohif/viewer: <w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.
@ohif/viewer: <i> [webpack-dev-server] Project is running at:
@ohif/viewer: <i> [webpack-dev-server] Loopback: http://localhost:3000/
@ohif/viewer: <i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.103:3000/
@ohif/viewer: <i> [webpack-dev-server] Content not from webpack is served from 'C:\Users\P22\dicomweb, ../../testdata' directory
@ohif/viewer: <i> [webpack-dev-server] 404s will fallback to '/index.html'
@ohif/viewer: Error: error:0308010C:digital envelope routines::unsupported
@ohif/viewer:     at new Hash (node:internal/crypto/hash:71:19)
@ohif/viewer:     at Object.createHash (node:crypto:133:10)
@ohif/viewer:     at module.exports (C:\ohif\node_modules\webpack\lib\util\createHash.js:135:53)
@ohif/viewer:     at NormalModule._initBuildHash (C:\ohif\node_modules\webpack\lib\NormalModule.js:417:16)
@ohif/viewer:     at handleParseError (C:\ohif\node_modules\webpack\lib\NormalModule.js:471:10)
@ohif/viewer:     at C:\ohif\node_modules\webpack\lib\NormalModule.js:503:5
@ohif/viewer:     at C:\ohif\node_modules\webpack\lib\NormalModule.js:358:12
@ohif/viewer:     at C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:373:3
@ohif/viewer:     at iterateNormalLoaders (C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
@ohif/viewer:     at iterateNormalLoaders (C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
@ohif/viewer:     at C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:236:3
@ohif/viewer:     at runSyncOrAsync (C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
@ohif/viewer:     at iterateNormalLoaders (C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
@ohif/viewer:     at Array.<anonymous> (C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
@ohif/viewer:     at Storage.finished (C:\ohif\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
@ohif/viewer:     at C:\ohif\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
@ohif/viewer: node:internal/crypto/hash:71
@ohif/viewer:   this[kHandle] = new _Hash(algorithm, xofLen);
@ohif/viewer:                   ^
@ohif/viewer: Error: error:0308010C:digital envelope routines::unsupported
@ohif/viewer:     at new Hash (node:internal/crypto/hash:71:19)
@ohif/viewer:     at Object.createHash (node:crypto:133:10)
@ohif/viewer:     at module.exports (C:\ohif\node_modules\webpack\lib\util\createHash.js:135:53)
@ohif/viewer:     at NormalModule._initBuildHash (C:\ohif\node_modules\webpack\lib\NormalModule.js:417:16)
@ohif/viewer:     at handleParseError (C:\ohif\node_modules\webpack\lib\NormalModule.js:471:10)
@ohif/viewer:     at C:\ohif\node_modules\webpack\lib\NormalModule.js:503:5
@ohif/viewer:     at C:\ohif\node_modules\webpack\lib\NormalModule.js:358:12
@ohif/viewer:     at C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:373:3
@ohif/viewer:     at iterateNormalLoaders (C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
@ohif/viewer:     at Array.<anonymous> (C:\ohif\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
@ohif/viewer:     at Storage.finished (C:\ohif\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
@ohif/viewer:     at C:\ohif\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
@ohif/viewer:     at C:\ohif\node_modules\graceful-fs\graceful-fs.js:115:16
@ohif/viewer:     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
@ohif/viewer:   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
@ohif/viewer:   library: 'digital envelope routines',
@ohif/viewer:   reason: 'unsupported',
@ohif/viewer:   code: 'ERR_OSSL_EVP_UNSUPPORTED'
@ohif/viewer: }
@ohif/viewer: Node.js v18.16.0
@ohif/viewer: error Command failed with exit code 1.
@ohif/viewer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@ohif/viewer: error Command failed with exit code 1.
@ohif/viewer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run dev:viewer exited 1 in '@ohif/viewer'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\ohif>

`

**Comment by Bidouyeur** [comment]
I had the same error but then I switch to v3-stable branch and now it start:

git switch v3-stable (see [](https://v3-docs.ohif.org/development/getting-started/#kick-the-tires))

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
