### ISSUE TITLE
ERR_BLOCKED_BY_RESPONSE

### ISSUE THREAD

**Issue by yensis80** [OHIF/Viewers#3351]
I have orthan installed and running fine on windows without docker. set to ohif and it works fine with the web server. But when I change them to my custom configuration, it doesn't work, it gives me this error. characteristics of my team
Windows 10 Pro 22H2
32 RAM
nodejos v16.13.1
yarn v1.22.19
nmp v9.6.5

![p2JPG](https://user-images.githubusercontent.com/87835845/235817053-62e0b8f1-bb20-43df-9047-014f971c2dd8.JPG)

![full](https://user-images.githubusercontent.com/87835845/235817064-a28f8e19-0c25-4a6e-96af-a3c5c12e92f3.JPG)

create a virtual host with the configuration shown below.

configuration file httpd-vhosts.conf
C:\wamp\bin\apache\apache2.4.9\conf\extra\httpd-vhosts.conf
`# VHOST TEST
<VirtualHost *:80>
     DocumentRoot "c:/AppServ/www/ohif"
     ServerName test.do
     ServerAlias test.do
     <Directory "c:/AppServ/www/ohif">
         Options Indexes FollowSymLinks
         Allow Override All
         Order Deny,Allow
         Allow from all
     </Directory>
</VirtualHost>
`
where I copied the contents of dist when I finished building the project with my configuration. in a folder called ohif "c:/AppServ/www/ohif"

host file host configuration
C:\Windows\System32\drivers\etc\hosts
`127.0.0.1 localhost
127.0.0.1 test.do
::1 localhost`

![erro](https://user-images.githubusercontent.com/87835845/235817013-99a7d770-ff46-46e9-8842-c84ba3815e92.JPG)

`Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
C:\ohif\node_modules\webpack\hot\log.js:24 [HMR] Waiting for update signal from WDS...
C:\ohif\node_modules\react-dom\cjs\react-dom.development.js:27705 Download the React DevTools for a better development experience: https://fb.me/react-devtools
C:\ohif\node_modules\cornerstone-tools\dist\cornerstoneTools.js:36254 Cornerstone Tools
C:\ohif\node_modules\cornerstone-tools\dist\cornerstoneTools.js:36256 run localStorage.setItem("debug", "cornerstoneTools") to see console output
C:\ohif\node_modules\react-hot-loader\dist\react-hot-loader.development.js:2377  React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.
AppContainer @ C:\ohif\node_modules\react-hot-loader\dist\react-hot-loader.development.js:2377
C:\ohif\node_modules\cornerstone-tools\dist\cornerstoneTools.js:13005  The provided colorLUT only provides 0 labels, whereas segmentsPerLabelmap is set to 65535. Autogenerating the rest.
_checkColorLUTLength @ C:\ohif\node_modules\cornerstone-tools\dist\cornerstoneTools.js:13005
MeasurementService.js:158 New 'CornerstoneTools@4' source added.
MeasurementService.js:240 New measurement mapping added to source 'CornerstoneTools@4'.
HotkeysManager.js:171 Binding incrementActiveViewport to right
HotkeysManager.js:171 Binding decrementActiveViewport to left
HotkeysManager.js:171 Binding rotateViewportCW to r
HotkeysManager.js:171 Binding rotateViewportCCW to l
HotkeysManager.js:171 Binding invertViewport to i
HotkeysManager.js:171 Binding flipViewportVertical to h
HotkeysManager.js:171 Binding flipViewportHorizontal to v
HotkeysManager.js:171 Binding scaleUpViewport to +
HotkeysManager.js:171 Binding scaleDownViewport to -
HotkeysManager.js:171 Binding fitViewportToWindow to =
HotkeysManager.js:171 Binding resetViewport to space
HotkeysManager.js:171 Binding nextImage to down
HotkeysManager.js:171 Binding previousImage to up
HotkeysManager.js:171 Binding previousViewportDisplaySet to pagedown
HotkeysManager.js:171 Binding nextViewportDisplaySet to pageup
HotkeysManager.js:171 Binding setZoomTool to z
HotkeysManager.js:171 Binding windowLevelPreset1 to 1
HotkeysManager.js:171 Binding windowLevelPreset2 to 2
HotkeysManager.js:171 Binding windowLevelPreset3 to 3
HotkeysManager.js:171 Binding windowLevelPreset4 to 4
HotkeysManager.js:171 Binding windowLevelPreset5 to 5
HotkeysManager.js:171 Binding windowLevelPreset6 to 6
HotkeysManager.js:171 Binding windowLevelPreset7 to 7
HotkeysManager.js:171 Binding windowLevelPreset8 to 8
HotkeysManager.js:171 Binding windowLevelPreset9 to 9
C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:551 [webpack-dev-server] Hot Module Replacement enabled.
C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:551 [webpack-dev-server] Live Reloading enabled.
C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556  [webpack-dev-server] Warnings while compiling.
logger @ C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556
C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556  [webpack-dev-server] WARNING
/5.js is 6.32 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
logger @ C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556
C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556  [webpack-dev-server] WARNING
/app.js is 5.3 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
logger @ C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556
C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556  [webpack-dev-server] WARNING
/vendors~app.js is 42.4 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
logger @ C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556
C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556  [webpack-dev-server] WARNING
/vendors~dicom-microscopy-viewer.js is 5.43 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
logger @ C:\ohif\node_modules\webpack-dev-server\client\modules\logger\index.js:556
C:\ohif\node_modules\react-dom\cjs\react-dom.development.js:12338  Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DateInput
printWarning @ C:\ohif\node_modules\react-dom\cjs\react-dom.development.js:12338
C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:985 search for studies
C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:500  request failed:  XMLHttpRequest
request.onreadystatechange @ C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:500
C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:501  Error: request failed
    at request.onreadystatechange (C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:494:1)
    at XMLHttpRequest.onReadyStateChange (xhrRetryRequestHook.js:34:1)
request.onreadystatechange @ C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:501
C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:502  null
request.onreadystatechange @ C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:502
StudyListRoute.js:101  Error: request failed
    at request.onreadystatechange (C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:494:1)
    at XMLHttpRequest.onReadyStateChange (xhrRetryRequestHook.js:34:1)
_callee$ @ StudyListRoute.js:101
192.168.0.102:8042/orthanc/dicom-web/studies?limit=25&offset=0&fuzzymatching=true&includefield=00081030%2C00080060:1 
        
        
        Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
StudyListRoute.js:101  Error: request failed
    at request.onreadystatechange (C:\ohif\node_modules\dicomweb-client\build\dicomweb-client.es.js:494:1)
    at XMLHttpRequest.onReadyStateChange (xhrRetryRequestHook.js:34:1)
_callee$ @ StudyListRoute.js:101`

help to fix this error Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep.

**Comment by yensis80** [comment]
my configuracion 
`servers: {
    dicomWeb: [
      {
        name: 'IMPACS',
        wadoUriRoot: 'https://192.168.0.102:8042/orthanc/wado',
        qidoRoot: 'https://192.168.0.102:8042/orthanc/dicom-web',
        wadoRoot: 'https://192.168.0.102:8042/orthanc/dicom-web',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },
`

**Comment by yensis80** [comment]
my configuraction de file default.js

` servers: {
    dicomWeb: [
      {
        name: 'IMPACS',
        wadoUriRoot: 'https://192.168.0.102:8042/orthanc/wado',
        qidoRoot: 'https://192.168.0.102:8042/orthanc/dicom-web',
        wadoRoot: 'https://192.168.0.102:8042/orthanc/dicom-web',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },
`

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
