### ISSUE TITLE
[Bug] v3 and v2: RGB inconsistencies 

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3354]
RGB inconsistencies 

###  Sample 1 (frame 23)
![rgb-issue-1](https://user-images.githubusercontent.com/13886933/236047735-6e615041-922b-46be-aab8-e959ee72da00.png)
- Env: https://ohif-v3.web.app/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1078.3273.132220854463485495034769662271

### Sample 2 (series with 397 slices)
![rgb-2-ssie](https://user-images.githubusercontent.com/13886933/236048048-524300f7-f51a-4aa1-a294-caa75f361f46.png)
- Env: https://ohif-v3.web.app/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1188.2803.215544713257596275140185968379

### Sample 3
![Screenshot 2023-07-19 at 11 07 32](https://github.com/OHIF/Viewers/assets/13886933/d8a9c34b-e656-4f0e-bb7b-397b4921b40a)
- Env: https://ohif-v3.web.app/viewer?StudyInstanceUIDs=1.3.6.1.4.1.5962.1.2.0.1677425356.1733

### Sample 1 (v2)
![first-problem-rgb-v1](https://user-images.githubusercontent.com/13886933/236048802-f952d1c6-083e-4e03-8b9f-3c6512782046.png)
- Env: https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.1078.3273.132220854463485495034769662271

### Sample 2 (v2)
![v2-rgb-sample-2](https://user-images.githubusercontent.com/13886933/236048555-bb3eb062-32b0-4a61-8847-744ac23098c6.png)
- Env: https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.1188.2803.215544713257596275140185968379 

### Sample 3 (v2)
<img width="1787" alt="Screenshot 2023-07-19 at 13 37 59" src="https://github.com/OHIF/Viewers/assets/13886933/351b546f-944e-437b-b9cf-1d45dca1f971">
- Env: see IDC OHIF v3 gaps document or ask @fedorov

**Comment by vicongit23** [comment]
Moving from 2934 issue branch.
The problem is in cornerstone  

![RGB_US](https://github.com/OHIF/Viewers/assets/140082860/0f97ba02-6054-45da-a4e1-993e785b9afd)

**Comment by vicongit23** [comment]
The problem is  GPU case ( I have "intel uhd graphics 630")
Same environment , same dicom is rendered ok on CPU:
![RGB_US_CPU](https://github.com/OHIF/Viewers/assets/140082860/ecb13352-e554-49ad-8f73-6299f2f6d73c)

Can be that there is  missing /additional RGB<->RGBA buffer transformation in case of GPU in postProcessDecodePixel flow ?

**Comment by vicongit23** [comment]
> The problem is GPU case ( I have "intel uhd graphics 630") Same environment , same dicom is rendered ok on CPU: ![RGB_US_CPU](https://user-images.githubusercontent.com/140082860/256436259-ecb13352-e554-49ad-8f73-6299f2f6d73c.png)
> 
> Can be that there is missing /additional RGB<->RGBA buffer transformation in case of GPU in postProcessDecodePixel flow ?

Same behavior for ATI Radeon GPU

**Comment by vicongit23** [comment]
Another aspect of the  problem ( same RGB image degradation), but different workflow:
OHIFserver/Local-> load RGB file- >see display
v3.6.0-             image is fine.
v3.7.0-beta.41- image is mangled (` seen initially on v3.7.0-beta.37) .

**Comment by igoroctaviano** [comment]
@vicongit23 I noticed that the cornerstone issue you mentiioned was closed. Were you able to reproduce the problems presented in this issue with the new changes?

**Comment by vicongit23** [comment]
> @vicongit23 I noticed that the cornerstone issue you mentiioned was closed. Were you able to reproduce the problems presented in this issue with the new changes?

With the change in https://github.com/cornerstonejs/cornerstone3D/pull/707 cornerstone "local" examole behaves properly ( If I understood the question)

**Comment by igoroctaviano** [comment]
@sedghi @wayfarer3130 after updating to cornerstonejs/core ^1.10.0 I'm still getting these results (slightly different compared to a version before https://github.com/cornerstonejs/cornerstone3D/pull/702 changes:

# Sample 1
<img width="1134" alt="Screenshot 2023-08-04 at 13 57 30" src="https://github.com/OHIF/Viewers/assets/13886933/079a0aec-044c-410f-985a-9f2d075cbf36">
# Sample 2
<img width="1135" alt="Screenshot 2023-08-04 at 13 58 30" src="https://github.com/OHIF/Viewers/assets/13886933/b86a1c0b-7535-43b4-b50c-9f82bb871d58">
# Sample 3
<img width="1135" alt="Screenshot 2023-08-04 at 13 59 27" src="https://github.com/OHIF/Viewers/assets/13886933/259eed60-6a89-4a79-98cf-ab765e06479a">

**Comment by igoroctaviano** [comment]
@sedghi @wayfarer3130 some updates using cornerstone3d 1.10.0 version which includes [703](https://github.com/cornerstonejs/cornerstone3D/pull/702):

## Sample 1 fixed
![Screenshot 2023-08-04 at 14 32 15](https://github.com/OHIF/Viewers/assets/13886933/c4f52446-23ea-4f7b-86d2-b2a10a361f77)

## Sample 3 fixed
![Screenshot 2023-08-04 at 14 30 19](https://github.com/OHIF/Viewers/assets/13886933/4263aaf0-57fa-4e3a-8151-b0ba79bbb8ee)

## Sample 2 is still problematic (now the thumbnails are bad too compared to the PR screenshot before [703](https://github.com/cornerstonejs/cornerstone3D/pull/702) changes)
![Screenshot 2023-08-04 at 14 30 58](https://github.com/OHIF/Viewers/assets/13886933/a950440d-06c5-4bf3-8670-e2bb8a913517)

**Comment by fedorov** [comment]
Looking at the sample 3, it is NOT fixed. There should be a single color image, not 3x3 B&W tiles - both for the image and for the thumbnails.

<img width="773" alt="image" src="https://github.com/OHIF/Viewers/assets/313942/94b33429-b6c0-49ce-845d-f7dffdbf0e63">

**Comment by igoroctaviano** [comment]
> Looking at the sample 3, it is NOT fixed. There should be a single color image, not 3x3 B&W tiles - both for the image and for the thumbnails.
> 
> <img alt="image" width="773" src="https://user-images.githubusercontent.com/313942/258491950-94b33429-b6c0-49ce-845d-f7dffdbf0e63.png">

Thx for the input, I just updated the last comment.

**Comment by wayfarer3130** [comment]
Please include the relevant metadata and DICOMweb frame level header data.  Without that, it is impossible to tell if this is failing because the data is wrong, or there is a bug in OHIF.  Even if it is a bug in OHIF, it may well not be related to the changes made recently, which were mostly a decompression related issue.  Ideally I'd like to have the DICOM file as well as the headers for accept and response, and the first 5 lines of the response data itself (so that it is possible to tell how the response is encoded.)

**Comment by fedorov** [comment]
> Please include the relevant metadata and DICOMweb frame level header data.

Do you need this even though the dataset is public?

Or do you need instructions how to access the underlying dataset?

**Comment by fedorov** [comment]
@wayfarer3130 @sedghi if you would like to access a sample XC modality image for your testing, like the one above, we have them in public IDC buckets. Here's a quick 2-step process:
1. Download [`s5cmd` binary release](https://github.com/peak/s5cmd/releases) for your platform.
2. Run this command: `s5cmd --no-sign-request --endpoint-url https://s3.amazonaws.com cp "s3://idc-open-data/56f8119f-5940-48c1-96ee-8d445dc0b5fd/*" .`

If you would like more details etc about that dataset, check out [this notebook](https://github.com/ImagingDataCommons/IDC-Tutorials/blob/master/notebooks/collections_demos/nlm_visible_human_project.ipynb).

**Comment by wayfarer3130** [comment]
I will download that dataset (in progress actually - command seems to take a really long time - have left it 5 minutes now), but I do need the headers as they come from the PACS back end as well.  The reason is to figure out where the issue is coming from - OHIF or the PACS back end system.  At a minimum, having the PhotometricInterpretation from the metadata and the .../frames/1 first 5 lines of the response, plus the response headers is needed.  There are a few other things I might need still, but those can wait for the moment - I can grab those from the DICOM headers.

**Comment by wayfarer3130** [comment]
s5cmd doesn't seem to work for me.  Will try the windows 32 bit version to see if it is any different.

**Comment by fedorov** [comment]
> looks like s3 was having problems

Can you confirm - did you use s3 or s5cmd?

**Comment by fedorov** [comment]
> I will download that dataset (in progress actually - command seems to take a really long time - have left it 5 minutes now), but I do need the headers as they come from the PACS back end as well. The reason is to figure out where the issue is coming from - OHIF or the PACS back end system. At a minimum, having the PhotometricInterpretation from the metadata and the .../frames/1 first 5 lines of the response, plus the response headers is needed. 

@igoroctaviano can you add Bill to the v3 sandbox you set up?

**Comment by igoroctaviano** [comment]
> > I will download that dataset (in progress actually - command seems to take a really long time - have left it 5 minutes now), but I do need the headers as they come from the PACS back end as well. The reason is to figure out where the issue is coming from - OHIF or the PACS back end system. At a minimum, having the PhotometricInterpretation from the metadata and the .../frames/1 first 5 lines of the response, plus the response headers is needed.
> 
> @igoroctaviano can you add Bill to the v3 sandbox you set up?

The sandbox is using the same IDC config (oidc) which means that we don't have more seats, right?

**Comment by fedorov** [comment]
You are right. Sorry, I keep forgetting about this...

@wayfarer3130 I will PM you.

**Comment by wayfarer3130** [comment]
The issue is that the Planar Configuration is 1 and that isn't being handled by OHIF.  That means the images use the RGB format as:
R1 R2 R3 .... G1 G2 G3 etc
Looking now to see where that is occurring.

**Comment by sedghi** [comment]
@wayfarer3130 it is not in OHIF, it should be in the dicomImageLoader, maybe even in the `createImage` and `decodeImageFrame`

**Comment by wayfarer3130** [comment]
The code got removed to handle the colour space conversion.  It is a mess, but I hope to push a fix later today:
https://github.com/cornerstonejs/cornerstone3D/pull/730
That branch is working for me, but has a bunch of inconsistencies still depending on how images are encoded.

**Comment by wayfarer3130** [comment]
@igoroctaviano - could you try the current branch of CS3D?  You might need to ensure it gets linked properly, as sometimes yarn link fails to work as expected.

**Comment by igoroctaviano** [comment]
> * /viewer?StudyInstanceUIDs=1.3.6.1.4.1.5962.1.2.0.1677425356.1733

I tried the branch locally, here's the results: 
@fedorov 

## Sample 1
http://localhost:3000/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1078.3273.132220854463485495034769662271
![Screenshot 2023-08-10 at 11 57 57](https://github.com/OHIF/Viewers/assets/13886933/5826f96a-c917-4938-818c-d79f8f83a616)

##  Sample 2
http://localhost:3000/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1188.2803.215544713257596275140185968379
![Screenshot 2023-08-10 at 11 38 38](https://github.com/OHIF/Viewers/assets/13886933/f52c5e88-1839-46a8-83bf-d18776db48d8)

## Sample 3
[http://localhost:3000/viewer?StudyInstanceUIDs=1.3.6.1.4.1.5962.1.2.0.1677425356.1733](https://ohif-v3.web.app/viewer?StudyInstanceUIDs=1.3.6.1.4.1.5962.1.2.0.1677425356.1733)
![Screenshot 2023-08-10 at 11 40 40](https://github.com/OHIF/Viewers/assets/13886933/7ea2938d-b6aa-4c36-8aee-33664271cd7f)
![Screenshot 2023-08-10 at 11 41 09](https://github.com/OHIF/Viewers/assets/13886933/7fb2bdf9-f22c-406c-87e1-e25e99ddc305)

**Comment by fedorov** [comment]
Looking good!
