### ISSUE TITLE
[Feature Request] Auto load derived display sets when opening series

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3356]
### Request

Derived display sets are automatically loaded when the series is open in the viewport instead of double-clicking in the derived display set thumbnail in the left panel and accepting the hydration through a dialog

### Context

In OHIF v2 when clicking on a series with derived display sets, all derived data loads automatically.
This is useful for read-only viewers that do not require the hydration workflow in v3, and just want all data related to a given loaded series to be displayed instantly.

### Possible solutions

- Add a new hanging protocol option to automatically load derived display sets for series being loaded in the viewport which would disable all hydration dialogs 
- Add a new option to the viewer configuration

**Comment by james-hanks** [comment]
#3506

**Comment by fedorov** [comment]
For the sake of background, here is an example in v2 that demonstrates how v2 handles a series that has 2 segmentation series: https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.7311.5101.170561193612723093192571245493. We are basically trying to get the functionality that proved to work very well in v2 for IDC and not only for IDC.

**Comment by james-hanks** [comment]
@rodrigobasilio2022 could you let us know if this is fixed on IDC's side and OHIF has anything to look into?

**Comment by rodrigobasilio2022** [comment]
This functionality is under review and works in IDC side, as a complement of modes

**Comment by igoroctaviano** [comment]
@wayfarer3130 @sedghi do you guys think it would be useful to have a new property added to the hanging protocol to automatically load the latest derived display set for the active series? If so, I'll keep this ticket open and do that for the community. This is how v2 used to work, you didn't have to click on the SR and open the SR viewport. For now, we added this functionality only to the mode.

**Comment by wayfarer3130** [comment]
I would suggest not loading the latest of any derived instances, but matching a display set instance, and taking the first item of the display set instance that matches.  That way a hanging protocol can modify how the matching rules work for what to load.  I'd also suggest doing that for segmentation data, but you might want to allow more than 1 matching rule for segmentation to succeed

**Comment by igoroctaviano** [comment]
@wayfarer3130 @sedghi I'll close this issue for IDC purposes but I created another one for the better long term solution proposed by @wayfarer3130: https://github.com/OHIF/Viewers/issues/3879
