### ISSUE TITLE
[Feature Request]: v3: Viewer "read only" mode

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3357]
### Features
- Disable editing SEGs / RTs, etc
- Disable tools (tool by tool basis) e.g. never enable brush (could be done by mode config)
- Is it possible to disable all editing features at once (both editing of the images, but also editing of things like segment labels)? turn off hydration
- Render the measurements in the right panel but keep the read-only viewport (don't hydrate): When showing the intermediary viewport, don't popup and show the measurements in the right panel (panels are hydration dependent so maybe this is going to be a big change)

**Comment by fedorov** [comment]
@rodrigobasilio2022 specifically:
* it should be possible (probably via deploy configuration?) to disable the ability of the user to change the labels of the segments in the screenshot below:
![image](https://github.com/OHIF/Viewers/assets/313942/ef0c857d-5743-4ad5-b000-047205b876b7)
* it should be possible to disable renaming of the segment group:
![image](https://github.com/OHIF/Viewers/assets/313942/d809fba2-c51d-422f-804a-753a515ccd72)
* it should be possible to configure disable of the measurement tools:
![image](https://github.com/OHIF/Viewers/assets/313942/04891e69-fc5f-46b3-8741-7669134a2d60)

Please let me know if you have any questions!

**Comment by igoroctaviano** [comment]
@rodrigobasilio2022 just for reference, here are some notes based on the last meeting about this feature request:

- A new mode should be created without the editing tools
- The new mode should disable measurement hydration (which disables the editing of measurements)
- The measurement panel (the one that does not track measurements) could be modified so it would consume the unmapped measurements (non-hydrated measurements) so the user could see the measurement list without hydrating the measurements (this would require a new integration between the measurement service and the normal measurement panel)

**Comment by james-hanks** [comment]
Use case: UI component as workflow solution https://www.loom.com/share/5606990bfe5c408094dfd2bf6a78abb8?t=124

**Comment by rodrigobasilio2022** [comment]
And already merged.

**Comment by igoroctaviano** [comment]
Done! #3586

**Comment by vishnusureshperumbavoor** [comment]
How to make a viewport readonly in v3

**Comment by rodrigobasilio2022** [comment]
Add the variable `disableEditing` in the default.js or the configuration file you are using

**Comment by vishnusureshperumbavoor** [comment]
> Add the variable `disableEditing` in the default.js or the configuration file you are using

disableEditing: true,

like this??
