### ISSUE TITLE
v3: Add basic GCP url support 

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3361]
### Request
- Add support to retrieve study/series from GCP using dicomweb:
http://localhost:3000/projects/your-project/locations/us/datasets/your-dataset/dicomStores/test-store/study/123

**Comment by sanjay3290** [comment]
Hey Guys, any update or workaround for this?

**Comment by igoroctaviano** [comment]
> Hey Guys, any update or workaround for this?

@sanjay3290 With this PR you can accomplish this: https://github.com/OHIF/Viewers/pull/3543

**Comment by igoroctaviano** [comment]
Now with https://github.com/OHIF/Viewers/pull/3543 merged the first part of this issue is done. We can support gcp URLs (study level) using this config:
```
{
    friendlyName: 'GCP DICOMWeb Server',
    namespace: '@ohif/extension-default.dataSourcesModule.dicomweb',
    sourceName: 'gcpdicomweb',
    configuration: {
      name: 'gcpdicomweb',
      qidoSupportsIncludeField: false,
      imageRendering: 'wadors',
      thumbnailRendering: 'wadors',
      enableStudyLazyLoad: true,
      supportsFuzzyMatching: false,
      supportsWildcard: false,
      singlepart: 'bulkdata,video,pdf',
      useBulkDataURI: false,
      onConfiguration: (dicomWebConfig, options) => {
        const { params } = options;
        const { project, location, dataset, dicomStore } = params;
        const pathUrl = `https://healthcare.googleapis.com/v1/projects/${project}/locations/${location}/datasets/${dataset}/dicomStores/${dicomStore}/dicomWeb`;
        return {
          ...dicomWebConfig,
          wadoRoot: pathUrl,
          qidoRoot: pathUrl,
          wadoUri: pathUrl,
          wadoUriRoot: pathUrl,
        };
      },
    },
  },
```

**Comment by sanjay3290** [comment]
how can i send dynamic params for the below method during runtime.? or it can be set only during the build time?

onConfiguration: (dicomWebConfig, options) => {
          const { params } = options;
          const { project, location, dataset, dicomStore } = params;
          const pathUrl = `https://healthcare.googleapis.com/v1/projects/${project}/locations/${location}/datasets/${dataset}/dicomStores/${dicomStore}/dicomWeb`;
          return {
            ...dicomWebConfig,
            wadoRoot: pathUrl,
            qidoRoot: pathUrl,
            wadoUri: pathUrl,
            wadoUriRoot: pathUrl,
          };
