### ISSUE TITLE
ERROR plication/octet-stream".

### ISSUE THREAD

**Issue by yensis80** [OHIF/Viewers#3365]
I want to know if it helps me to finish configuring what I'm missing from the orthan pcas with ohif with nginx without dockers. in windows 10 pro it is installed on the same computer.  orsan funcion bien y ohif con el servidor de prubeba tambien. 

![p2JPG](https://user-images.githubusercontent.com/87835845/236116126-f0a3bbcf-4544-419d-ac8c-cba30dc6ce23.JPG)
![full](https://user-images.githubusercontent.com/87835845/236116137-69e0e22d-9915-4ca3-a432-d1fe3419532e.JPG)

**when i change and build with with my personality config it gives me that error.**
![erro](https://user-images.githubusercontent.com/87835845/236116291-1b4af5ce-7e9c-4994-a3bc-91f79e13128a.JPG)

`run localStorage.setItem("debug", "cornerstoneTools") to see console output
cornerstoneTools.js:13005 The provided colorLUT only provides 0 labels, whereas segmentsPerLabelmap is set to 65535. Autogenerating the rest.
I @ cornerstoneTools.js:13005
MeasurementService.js:158 New 'CornerstoneTools@4' source added.
MeasurementService.js:240 New measurement mapping added to source 'CornerstoneTools@4'.
HotkeysManager.js:171 Binding incrementActiveViewport to right
HotkeysManager.js:171 Binding decrementActiveViewport to left
HotkeysManager.js:171 Binding rotateViewportCW to r
HotkeysManager.js:171 Binding rotateViewportCCW to l
HotkeysManager.js:171 Binding invertViewport to i
HotkeysManager.js:171 Binding flipViewportVertical to h
HotkeysManager.js:171 Binding flipViewportHorizontal to v
HotkeysManager.js:171 Binding scaleUpViewport to +
HotkeysManager.js:171 Binding scaleDownViewport to -
HotkeysManager.js:171 Binding fitViewportToWindow to =
HotkeysManager.js:171 Binding resetViewport to space
HotkeysManager.js:171 Binding nextImage to down
HotkeysManager.js:171 Binding previousImage to up
HotkeysManager.js:171 Binding previousViewportDisplaySet to pagedown
HotkeysManager.js:171 Binding nextViewportDisplaySet to pageup
HotkeysManager.js:171 Binding setZoomTool to z
HotkeysManager.js:171 Binding windowLevelPreset1 to 1
HotkeysManager.js:171 Binding windowLevelPreset2 to 2
HotkeysManager.js:171 Binding windowLevelPreset3 to 3
HotkeysManager.js:171 Binding windowLevelPreset4 to 4
HotkeysManager.js:171 Binding windowLevelPreset5 to 5
HotkeysManager.js:171 Binding windowLevelPreset6 to 6
HotkeysManager.js:171 Binding windowLevelPreset7 to 7
HotkeysManager.js:171 Binding windowLevelPreset8 to 8
HotkeysManager.js:171 Binding windowLevelPreset9 to 9
/third_party/workbox/workbox-v5.1.4/workbox-window.dev.mjs:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
dicomweb-client.es.js:985 search for studies
dicomweb-client.es.js:500 request failed:  XMLHttpRequest
u.onreadystatechange @ dicomweb-client.es.js:500
dicomweb-client.es.js:501 Error: request failed
    at u.onreadystatechange (dicomweb-client.es.js:494:27)
    at t.attempt.e.onreadystatechange (xhrRetryRequestHook.js:34:36)
u.onreadystatechange @ dicomweb-client.es.js:501
dicomweb-client.es.js:502 null
u.onreadystatechange @ dicomweb-client.es.js:502
StudyListRoute.js:101 Error: request failed
    at u.onreadystatechange (dicomweb-client.es.js:494:27)
    at t.attempt.e.onreadystatechange (xhrRetryRequestHook.js:34:36)
(anonymous) @ StudyListRoute.js:101
192.168.0.102:8042/orthanc/dicom-web/studies?limit=25&offset=0&fuzzymatching=true&includefield=00081030%2C00080060:1     Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
StudyListRoute.js:101 Error: request failed
    at u.onreadystatechange (dicomweb-client.es.js:494:27)
    at t.attempt.e.onreadystatechange (xhrRetryRequestHook.js:34:36)
(`

my file **defauilt.js**
`window.config = {
  // default: '/'
  routerBasename: '/',
  extensions: [],
  showStudyList: true,
  filterQueryParam: false,
  disableServersCache: false,
  studyPrefetcher: {
    enabled: true,
    order: 'closest',
    displaySetCount: 3,
    preventCache: false,
    prefetchDisplaySetsTimeout: 300,
    maxNumPrefetchRequests: 100,
    displayProgress: true,
    includeActiveDisplaySet: true,
  },
  servers: {
    dicomWeb: [
      {
        name: 'IMPACS',
        wadoUriRoot: 'https://192.168.0.102:8042/orthanc/wado',
        qidoRoot: 'https://192.168.0.102:8042/orthanc/dicom-web',
        wadoRoot: 'https://192.168.0.102:8042/orthanc/dicom-web',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },

  // Extensions should be able to suggest default values for these?
  // Or we can require that these be explicitly set
  hotkeys: [
    // ~ Global
    {
      commandName: 'incrementActiveViewport',
      label: 'Next Viewport',
      keys: ['right'],
    },
    {
      commandName: 'decrementActiveViewport',
      label: 'Previous Viewport',
      keys: ['left'],
    },
    // Supported Keys: https://craig.is/killing/mice
    // ~ Cornerstone Extension
    { commandName: 'rotateViewportCW', label: 'Rotate Right', keys: ['r'] },
    { commandName: 'rotateViewportCCW', label: 'Rotate Left', keys: ['l'] },
    { commandName: 'invertViewport', label: 'Invert', keys: ['i'] },
    {
      commandName: 'flipViewportVertical',
      label: 'Flip Horizontally',
      keys: ['h'],
    },
    {
      commandName: 'flipViewportHorizontal',
      label: 'Flip Vertically',
      keys: ['v'],
    },
    { commandName: 'scaleUpViewport', label: 'Zoom In', keys: ['+'] },
    { commandName: 'scaleDownViewport', label: 'Zoom Out', keys: ['-'] },
    { commandName: 'fitViewportToWindow', label: 'Zoom to Fit', keys: ['='] },
    { commandName: 'resetViewport', label: 'Reset', keys: ['space'] },
    // clearAnnotations
    { commandName: 'nextImage', label: 'Next Image', keys: ['down'] },
    { commandName: 'previousImage', label: 'Previous Image', keys: ['up'] },
    // firstImage
    // lastImage
    {
      commandName: 'previousViewportDisplaySet',
      label: 'Previous Series',
      keys: ['pagedown'],
    },
    {
      commandName: 'nextViewportDisplaySet',
      label: 'Next Series',
      keys: ['pageup'],
    },
    // ~ Cornerstone Tools
    { commandName: 'setZoomTool', label: 'Zoom', keys: ['z'] },
    // ~ Window level presets
    {
      commandName: 'windowLevelPreset1',
      label: 'W/L Preset 1',
      keys: ['1'],
    },
    {
      commandName: 'windowLevelPreset2',
      label: 'W/L Preset 2',
      keys: ['2'],
    },
    {
      commandName: 'windowLevelPreset3',
      label: 'W/L Preset 3',
      keys: ['3'],
    },
    {
      commandName: 'windowLevelPreset4',
      label: 'W/L Preset 4',
      keys: ['4'],
    },
    {
      commandName: 'windowLevelPreset5',
      label: 'W/L Preset 5',
      keys: ['5'],
    },
    {
      commandName: 'windowLevelPreset6',
      label: 'W/L Preset 6',
      keys: ['6'],
    },
    {
      commandName: 'windowLevelPreset7',
      label: 'W/L Preset 7',
      keys: ['7'],
    },
    {
      commandName: 'windowLevelPreset8',
      label: 'W/L Preset 8',
      keys: ['8'],
    },
    {
      commandName: 'windowLevelPreset9',
      label: 'W/L Preset 9',
      keys: ['9'],
    },
  ],
  cornerstoneExtensionConfig: {},
  // Following property limits number of simultaneous series metadata requests.
  // For http/1.x-only servers, set this to 5 or less to improve
  //  on first meaningful display in viewer
  // If the server is particularly slow to respond to series metadata
  //  requests as it extracts the metadata from raw files everytime,
  //  try setting this to even lower value
  // Leave it undefined for no limit, suitable for HTTP/2 enabled servers
  // maxConcurrentMetadataRequests: 5,
};
`
my file **public_dicomweb.js**
`window.config = {
  routerBasename: '/',
  showStudyList: true,
  servers: {
    dicomWeb: [
      {
        name: 'IMPACS',
        wadoUriRoot: 'https://192.168.0.102:8042/orthanc/wado',
        qidoRoot: 'https://192.168.0.102:8042/orthanc/dicom-web',
        wadoRoot: 'https://192.168.0.102:8042/orthanc/dicom-web',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        supportsFuzzyMatching: true,
      },
    ],
  },
  i18n: {
    LOCIZE_PROJECTID: 'a8da3f9a-e467-4dd6-af33-474d582a0294',
    LOCIZE_API_KEY: null, // Developers can use this to do in-context editing. DO NOT COMMIT THIS KEY!
    USE_LOCIZE: false,
  },
};
`
my file **nginx.conf**
`worker_processes  2;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
 
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;
   

        location / {
            root   html;
            index  index.html index.htm;
        }

 
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
#Configuracion orthanc

server {
   listen  80;
 
   location  ^~ /orthanc/  {
      proxy_pass http://127.0.0.1:8042;
      proxy_set_header HOST $host;
      proxy_set_header X-Real-IP $remote_addr;
      rewrite /orthanc(.*) $1 break;
      add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
      add_header 'Access-Control-Allow-Origin' '*';
   }
  
}

    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    server {
        listen       80;
    #   listen       somename:8080;
        server_name  test.do;

       location / {
            root   C:/nginx/html/ohif;
            index  index.html index.htm;
        }
    }
}
`

my file **localhost**
`#
127.0.0.1 localhost
127.0.0.1 test.do
::1 localhost
`
Thank you hope you can help me

**Comment by Saleh-h-m-abbas** [comment]
any update?

**Comment by sedghi** [comment]
we have deployment recipes that you can take a look. https://docs.ohif.org/deployment/nginx--image-archive

Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
