### ISSUE TITLE
Static deployment of V3 does not work for DicomJson

### ISSUE THREAD

**Issue by bluesteel23** [OHIF/Viewers#3367]
### Describe the Bug
Have pulled data from V3 stable branch. When run locally, the dicomjson works well and displays iamges by using following url pattern : http://localhost:3000/viewer/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json.
After that we've built the code for production, copied the content of 'dist' folder to static website. This is done by using Azure blob storage and copying files to '$web' container. When navigated to the static website URL, the initial sample data loads. However when called for the viewer/dicomjson , it fails with error 'Content not found'.  Please advise. 

 
 
![screenshots](https://user-images.githubusercontent.com/132684122/236495137-5b4328b3-f794-4cfd-b1c1-51fdc866dafe.png)

**Comment by sedghi** [comment]
Most likely you need to setup a fallback from 404 to index.html, read the end of https://docs.ohif.org/configuration/dataSources/dicom-json
