### ISSUE TITLE
Save segmentation as RTSTRUCT or SEG

### ISSUE THREAD

**Issue by adityaapte** [OHIF/Viewers#3369]
### Request

**What feature or change would you like to see made?**

Ability to save segmentation as RTSTRUCT or SEG modality in DICOM.

**Why should we prioritize this feature?**

This ability would allow users to make edits to AI-generated segmentation and downstream usage in analysis.

**Comment by sedghi** [comment]
We have recently released the segmentation support, allowing you to accomplish this task confidently.

https://ohif.org/release-notes/3p7
