### ISSUE TITLE
OHIF viewer  Embeded viewer in react app does not work for DicomJson-displays blank screen

### ISSUE THREAD

**Issue by bluesteel23** [OHIF/Viewers#3371]
### Describe the Bug

React app with embeded ohif viewer works well with dicomweb. However for dicomjson, it displays blank screen 
 Below is the app.js code 

![image](https://user-images.githubusercontent.com/132684122/236583176-2aec2aef-d14f-4b69-b84a-93f498fe1fe9.png)

Below screen shot shows the browser response 
![image](https://user-images.githubusercontent.com/132684122/236583238-7361461c-313a-4d94-a8be-04a5bd2400e4.png)

Please advise

**Comment by junxiant** [comment]
Hello,

Were you able to get a fix for this problem? I'm trying to do iframe embedding but doesn't seem to work

**Comment by sedghi** [comment]
Have you looked into https://docs.ohif.org/deployment/iframe

**Comment by sedghi** [comment]
InstallViewer is in v2, master has moved forward with v3

**Comment by junxiant** [comment]
I faced a similar issue, I followed the iframe instructions as well. I posted for help [https://community.ohif.org/t/unable-to-use-iframe-in-react/887/2](url) here. 

Basically, I downloaded the zip file, placed the ohif folder in ./view/ohif and ran in the directory ./view I ran 
```
npx http-server ohif
``` 
But I received these errors:
![image](https://github.com/OHIF/Viewers/assets/25401067/f4d099b5-c084-4738-8f8d-a2ea003d227e)

And the terminal showing errors:
![image](https://github.com/OHIF/Viewers/assets/25401067/51a6a106-1263-4174-a97c-e186a4191145)

**Comment by junxiant** [comment]
Update:

It was just some directory error after all,

In ./view

```
npx http-server ./ 
```
And it worked
![image](https://github.com/OHIF/Viewers/assets/25401067/ca4c1ea0-e6ce-4875-adb4-ea4f9227c10e)

**Comment by sedghi** [comment]
@junxiant Can you maybe create a PR to update our docs? :)

**Comment by junxiant** [comment]
That was the fix for under the "Try it locally" section.

I'm going to try and integrate this into a new react app, and see how it works.

I'll post the detailed process if it works :-)

**Comment by junxiant** [comment]
Alright it worked out well so far, I'm not experienced in using React so I'll list down the steps I took to get it working.

1. I created a react app with version 18.2.0. 
```
npx create-react-app view
```

2. The directory structure looks like this:
![image](https://github.com/OHIF/Viewers/assets/25401067/605c4f06-abb8-40df-b035-e8affdf3d4fc)

3. Downloaded the ohif build folder and the index.html [here ](https://ohif-assets.s3.us-east-2.amazonaws.com/iframe-basic/Archive.zip)

4. Placed both the ohif folder and index.html to /view/public/ohif and /view/public/index.html . This will replace the existing index.html in the public folder. 

5. In the terminal, cd to the react root, which should be /view , and run 
```
npm start
```
This will show you 3 different sections, one with the ohif viewer, the "Hello from the parent of iframe" and the default react page
![image](https://github.com/OHIF/Viewers/assets/25401067/363cf8b0-38ee-43b7-863c-1ce5f126a2c1)

At this point im not sure what the best practice would be but I assume you could edit either the /view/public/index.html file or the /view/src/App.js file. I think the latter seems more appropriate?

After editing both files:
![image](https://github.com/OHIF/Viewers/assets/25401067/bb302634-f595-486d-ae29-83b39f4d2ab9)

Viewing a dicom scan:
![image](https://github.com/OHIF/Viewers/assets/25401067/861cf69e-dc57-4d48-981c-7e89fe517031)

**Comment by sedghi** [comment]
Thanks for the detailed documentation

**Comment by bluesteel23** [comment]
Could you please try if dicomjson works for your local ?
The URL could be something like :
127.0.0.1:8080/viewer/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json

or
127.0.0.1:8080/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json


Thanks in advance

**Comment by sedghi** [comment]
Could you please review our comprehensive documentation on Cross-Origin Resource Sharing (CORS) and OHIF? Below are the links provided for your reference.

- https://docs.ohif.org/deployment/cors
- https://docs.ohif.org/deployment/iframe

**Comment by RTAN0411** [comment]
> Alright it worked out well so far, I'm not experienced in using React so I'll list down the steps I took to get it working.
> 
> 1. I created a react app with version 18.2.0.
> 
> ```
> npx create-react-app view
> ```
> 
> 2. The directory structure looks like this:
>    ![image](https://private-user-images.githubusercontent.com/25401067/252603278-605c4f06-abb8-40df-b035-e8affdf3d4fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTc0MTgsIm5iZiI6MTcyNjI5NzExOCwicGF0aCI6Ii8yNTQwMTA2Ny8yNTI2MDMyNzgtNjA1YzRmMDYtYWJiOC00MGRmLWIwMzUtZThhZmZkZjNkNGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA2NTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZjZiNmNjZGEyZjNkNzliZTEwZWI2ZDhmNWZiMzZkNmU5MGVmZjRiODQ4Y2YxMjk5ZGNjOWVkZGI1M2I3MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UHJpkCYfV86IKgO2f2NJSwRObP4ppCDnGkcpGWqmZjM)
> 3. Downloaded the ohif build folder and the index.html [here ](https://ohif-assets.s3.us-east-2.amazonaws.com/iframe-basic/Archive.zip)
> 4. Placed both the ohif folder and index.html to /view/public/ohif and /view/public/index.html . This will replace the existing index.html in the public folder.
> 5. In the terminal, cd to the react root, which should be /view , and run
> 
> ```
> npm start
> ```
> 
> This will show you 3 different sections, one with the ohif viewer, the "Hello from the parent of iframe" and the default react page ![image](https://private-user-images.githubusercontent.com/25401067/252604841-363cf8b0-38ee-43b7-863c-1ce5f126a2c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTc0MTgsIm5iZiI6MTcyNjI5NzExOCwicGF0aCI6Ii8yNTQwMTA2Ny8yNTI2MDQ4NDEtMzYzY2Y4YjAtMzhlZS00M2I3LTg2M2MtMWNlNWYxMjZhMmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA2NTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjN2Q3ZTM4MTY1ZmM3NjIzYmYzNWMwYjk0ZDA2NzM3ZTA0NDA1NTgyOGY4OWEyMTMwMjgzYTdiZDNjNzYxM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FcpT3G3IVdzVzouv_zOeF6P5TkP1e3TTh5Y7J6hdicg)
> 
> At this point im not sure what the best practice would be but I assume you could edit either the /view/public/index.html file or the /view/src/App.js file. I think the latter seems more appropriate?
> 
> After editing both files: ![image](https://private-user-images.githubusercontent.com/25401067/252606273-bb302634-f595-486d-ae29-83b39f4d2ab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTc0MTgsIm5iZiI6MTcyNjI5NzExOCwicGF0aCI6Ii8yNTQwMTA2Ny8yNTI2MDYyNzMtYmIzMDI2MzQtZjU5NS00ODZkLWFlMjktODNiMzlmNGQyYWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA2NTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YTJhYTA0NzkwOTIyMzVmMTNmYjE1Y2Y2NmVhYjM1MDJmOTNkZTliZDRkNzBlMjhkOTIzZGFmNGRhYTBlNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcG00b_Wx4NdhlJYbqGzd8pNCi_emHqUC43j37Xo5s4)
> 
> Viewing a dicom scan: ![image](https://private-user-images.githubusercontent.com/25401067/252606525-861cf69e-dc57-4d48-981c-7e89fe517031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTc0MTgsIm5iZiI6MTcyNjI5NzExOCwicGF0aCI6Ii8yNTQwMTA2Ny8yNTI2MDY1MjUtODYxY2Y2OWUtZGM1Ny00ZDQ4LTk4MWMtN2U4OWZlNTE3MDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA2NTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwN2RlMDMyMmEzMzgxNjJmZWYwZTBhMDlhNTJjNmFlOWJjMzc2ZjhlYmNlM2U3N2Y2ZTQ4OTI2MzMwYWRmMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wae5LuvNb9kl5p8YGzXIZJWcLjcd8o2EkfOnIwtn1lU)

I have a question about this! How do we create the index and build files from the current Viewer? I realised that the build provided here and in the documentation does not have the segmentation capabilities
