### ISSUE TITLE
v3 Degraded performance and thumbnails not showing

### ISSUE THREAD

**Issue by yomarbuzz** [OHIF/Viewers#3386]
### Describe the Bug

After commit [84cb709](https://github.com/OHIF/Viewers/commit/84cb709b44074c7553fabd28bbcd2da4c1bd60d6) the issue described in #3373 has been resolved, but two other issues were created: 1) thumbnails are not displaying in study list 2) image loading performance of the viewport has degraded significantly.

here is the error:

caught (in promise) Error: loadAndCacheImage: parameter imageId must not be undefined
    at loadAndCacheImage (imageLoader.js:57:1)
    at sendRequest (loadImageToCanvas.js:20:1)
    at RequestPoolManager.sendRequests (requestPoolManager.js:84:1)
    at RequestPoolManager.startGrabbing (requestPoolManager.js:103:1)
    at RequestPoolManager.addRequest (requestPoolManager.js:52:1)
    at loadImageToCanvas.js:37:1
    at new Promise (<anonymous>)
    at Module.loadImageToCanvas (loadImageToCanvas.js:8:1)
    at getImageSrcFromImageId.js:9:1
    at new Promise (<anonymous>)

### Steps to Reproduce:

run the development version, check image loading performance, inspect the dev console in browser.

```js
Please use code blocks to show formatted errors or code snippets
```

### The current behavior

thumbnails not showing, perfomance degraded.
### The expected behavior

thumbnails showing, smooth loading of images.

--------
Unfortunately, there have been changes to > 80 files since the last working commit, this makes it very difficult for the community to pinpoint the issue and help with resolution. It would be great if commits were made atomically and code was not pushed to the stable branch without testing.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
