### ISSUE TITLE
SEG/RTSTRUCT origin series

### ISSUE THREAD

**Issue by 03shek** [OHIF/Viewers#3393]
### Request

**What feature or change would you like to see made?**
After opening a SEG and changing the viewport grid to show multiple series, all viewports show the segmentation where possible. It should be clear which series a segmentation originated from without having to double-click the SEG thumbnail again. For measurements, there is the checkmark next to a series thumbnail to indicate tracked measurements. The originating series is also stated explicitly under each measurement in the measurement panel. Please add a similar feature(s) for SEGs.

![image](https://github.com/OHIF/Viewers/assets/115667958/ce8b8393-a38f-440b-950c-aecadfbd5a7d)
![image](https://github.com/OHIF/Viewers/assets/115667958/9bf9f731-0f0a-4157-82a6-fe8cd62266b8)

...

**Why should we prioritize this feature?**
1. It would be easier for a user to identify the origin series of segmentations and make it unnecessary to reload SEG files to remind them. 
2. Different series may require different value ranges for the (re)creation of SEGs, so it will be easier to keep track of these ranges with this added feature(s).
3. Many SEG functionality in OHIF are shared with RTstructs. In the case of RTstructs, users may wish to add more contours to the same series. Or recreate a new set of contours on the same/different series as an exisiting RTstruct for comparison purposes. Again, it will be easier to keep track of with this added feature(s).

**Comment by james-hanks** [comment]
We should discuss user story for this in order for @dan-rukas to work on UI component. @igoroctaviano could we meet at some point to discuss?
