### ISSUE TITLE
v3: Stats missing for PlanarFreehandROI 

### ISSUE THREAD

**Issue by rghgit1** [OHIF/Viewers#3395]
### Describe the Bug

Stats like Area, Std Dev, Mean, Max are not displayed for PlanarFreehandROI tool.
As per this feat in cornerstonejs repo, stats are calculated for PlanarFreehandROI. https://github.com/cornerstonejs/cornerstone3D-beta/pull/326

1) Updated the dependencies to latest versions of cornerstonejs
"@cornerstonejs/core": "^0.46.1",
"@cornerstonejs/tools": "^0.67.1",
2) Ran 'yarn install'
3) The cornerstonejs code changes done as part of the above feature (https://github.com/cornerstonejs/cornerstone3D-beta/pull/326) is available under extensions\cornerstone\node_modules@cornerstonejs\tools\src\tools\annotation\PlanarFreehandROITool.ts

However, this is not getting called when the PlanarFreehandROI tool is used and no stats are displayed in OHIF Viewport.
Any pointers on how to invoke this when PlanarFreehandROI tool is used in OHIF would be great. Thanks

### Steps to Reproduce:

1. Enable PlanarFreehandROI tool
2. Mark an area in the scan and close the marking
3. Stats do not appear next to the marked area

```js
Please use code blocks to show formatted errors or code snippets
```

### The current behavior

After marking and area using PlanarFreehandROI tool, the stats are not displayed.
![image](https://github.com/OHIF/Viewers/assets/133641462/44e8da71-ba2b-41d7-b1ae-48afa174f4ff)

### The expected behavior

Display stats like Area, Std Dev, Mean, Max next to the PlanarFreehandROI marking

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by m00n620** [comment]
Did you try to set `calculateStats` option in the PlanarFreehandROITool configuration?

**Comment by rghgit1** [comment]
> Did you try to set `calculateStats` option in the PlanarFreehandROITool configuration?

Thanks a ton. I had set `calculateStats` option to true, but was not at the right place. After setting `calculateStats` to 'true' in toolsConfig for PlanarFreehandROI, stats are getting displayed.
