### ISSUE TITLE
Orthanc server sample data

### ISSUE THREAD

**Issue by lancelotsmith** [OHIF/Viewers#34]
I have installed the OHIF-Viewer on ubuntu but the app loader keeps rotating as if loading but no data ever gets loaded. I assume its perhaps there is no data in the orthanc server. How can i add data to the orthanc server?. Is there sample data i can get started with?.

**Comment by itcthienkhiem** [comment]
do you same this ? 
https://github.com/OHIF/Viewers/issues/32

**Comment by swederik** [comment]
There is sample data here: http://www.dicomlibrary.com/

In Orthanc you upload data in the browser at localhost:8042/app/explorer.html

Do you have any errors in the console?

**Comment by lancelotsmith** [comment]
@swederik  I have instaled ortahnc server in an ubuntu server and i am trying to access it like http://my-ip:8042/app/explorer.html but it asks for username and password

I don't know the username and password,not even the default username and password.

**Comment by swederik** [comment]
Try 'orthanc' as both username and password
