### ISSUE TITLE
[v2]  Can't display complete images

### ISSUE THREAD

**Issue by MKLM0222** [OHIF/Viewers#3404]
### Describe the Bug

When I get dicom images through wadouri in my interface, it has a problem with incomplete display, but the console does not report an error, as shown below.
![b4ab3ee95029c7f870f38220bca017060eaf98ac_2_1380x880](https://github.com/OHIF/Viewers/assets/24951601/cdb4fdd5-ac48-48b6-b5fd-a9d0066a8b41)
when i change windowlevel, the image will show a part of complete image
![3226fab1eac19fbdeb91a821e1be3ec51b9d456a_2_1380x752](https://github.com/OHIF/Viewers/assets/24951601/69009a5c-92b4-47d3-b359-438ccb8f8668)

### Steps to Reproduce

1. set my configuration
```
window.config = {
  routerBasename: '/',
  extensions: [],
  showStudyList: true,
  filterQueryParam: false,
  disableServersCache: false,
  studyPrefetcher: {
    enabled: true,
    order: 'closest',
    displaySetCount: 3,
    preventCache: false,
    prefetchDisplaySetsTimeout: 300,
    maxNumPrefetchRequests: 100,
    displayProgress: true,
    includeActiveDisplaySet: true,
  },
  servers: {
    dicomWeb: [
      {
        name: 'DCM4CHEE',
        wadoUriRoot: 'http://localhost:8010/dataset',
        qidoRoot: 'http://localhost:8010/dataset',
        wadoRoot: 'http://localhost:8010/dataset',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },
}
```
2. get images from interface 

### The current behavior

The viewer shows a part of dicom image.

### The expected behavior

The viewer shows complete image.
The viewer can show complete images when I download  them from interface and then upload them locally, as shown below
![66c263e38f546f75040823ccaae991956adc3ea4_2_1380x874](https://github.com/OHIF/Viewers/assets/24951601/802628b1-806c-4844-b95f-39f0ddd0fe9f)

### OS

MacOS 13.1

### Node version

14.21

### Browser

Chrome 113.0.5672.92

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
