### ISSUE TITLE
[Bug] SEG/RTSTRUCT breaks Stack Image Sync after loading

### ISSUE THREAD

**Issue by 03shek** [OHIF/Viewers#3408]
### Describe the Bug

Stack Image Sync works in the study before a SEG is loaded, but stops working after

### Steps to Reproduce

1. On v3-demo.ohif.org, load a study and set up a pair of viewports: series 5 | series 4 in this example, which both have 79 slices: 
https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1706.8374.643249677828306008300337414785

2. Enable Stack Image Sync.

3. Scroll through either viewport and see that the two series will scroll in sync together.
![stackimagesync_beforeSEG](https://github.com/OHIF/Viewers/assets/115667958/79d53023-ca3c-47db-8b24-ff74144d0a5f)

4. Drag the SEG into the first viewport (series 5, its origin series). 

6. Make sure Stack Image Sync is still enabled. 

7. Scroll through either viewport and see that only the active viewport will scroll. 
![stackimagesync_afterSEG](https://github.com/OHIF/Viewers/assets/115667958/1fecd965-8936-44bc-b42c-34ed48d2d576)

### The current behavior

Stack Image Sync works in the study before a SEG is loaded, but stops working after

### The expected behavior

Stack Image Sync should work with and without a SEG loaded into a viewport.

### OS

OS  Windows 10

### Node version

16.14.0

### Browser

Chrome 111.0.0

**Comment by sedghi** [comment]
Yes, since the viewports will get converted to volume viewports and stack image sync only works for stack viewports

**Comment by 03shek** [comment]
@sedghi Hi Alireza, I just tested this again on OHIF Demo v3.7 and it's still an issue.
https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1706.8374.643249677828306008300337414785

Version number 3.7.0
Commit Hash 5ddf8a16027255d28dc01c1740099cf85bbcf458
Browser Chrome 117.0.0
OS Windows 10

Stack image sync working before SEG/RTstruct is loaded:
![before](https://github.com/OHIF/Viewers/assets/115667958/9695a0a2-9e29-4b99-b373-2ad995a4ba10)

Default state after loading SEG/RTstruct:
![after_default](https://github.com/OHIF/Viewers/assets/115667958/e6b02d71-4e32-4622-81b1-c6f7007b05b3)

Stack image sync broken:
![after_triedscrolling](https://github.com/OHIF/Viewers/assets/115667958/914c7aa1-253f-4978-af70-9a29b308e40a)

Any fixes planned?

**Comment by sedghi** [comment]
Yes, in development

**Comment by sedghi** [comment]
Check here https://github.com/OHIF/Viewers/pull/3849

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
