### ISSUE TITLE
series not loading in version 3

### ISSUE THREAD

**Issue by kundanashish** [OHIF/Viewers#3412]
### Describe the Bug

I have created a .net dicom server
the dicom web calls are working fine in version 2 but it is not working in version 3

### Steps to Reproduce

jus changed wado base url to point to my server

### The current behavior

series not loading
but the images are shown from the series
![image](https://github.com/OHIF/Viewers/assets/13413950/3a2706a7-bf45-45cf-8528-26d12ed526d6)
![image](https://github.com/OHIF/Viewers/assets/13413950/25902f06-637c-44d3-a72d-8dfd3e69b871)

### The expected behavior

series should be listing in left area to use

### OS

Windows 11

### Node version

16.14

### Browser

Chrome

**Comment by kundanashish** [comment]
I missed to add study API correctly
It is working fine now after fixing that

Anyway thanks for the viewer :)

**Comment by Prashant117** [comment]
Hey @kundanashish
I am also facing the same issue with some specific scans from GE machines. Can you please let me know about the Study API and the changes needed?
 
Thanks in advance.

**Comment by Prashant117** [comment]
Hi @kundanashish 
thanks for the quick response. can you please let me know where have you made the changes? I am using Orthanc as server.

**Comment by kundanashish** [comment]
Sorry can't help with Orthanc. We build PACS server for ourself from scratch.

**Comment by Abhinav2212** [comment]
Hi do you know how to implement using s3 bucket link in nextjs app ?
