### ISSUE TITLE
[Bug] dicom segment mask cannot be loaded in v3 

### ISSUE THREAD

**Issue by Hasan-aga** [OHIF/Viewers#3413]
### Describe the Bug

I am trying to display a simple mask over a dicom series. it works fine in v2 and the [online v3 demo](https://v3-demo.ohif.org/local) but in the local v3 instance it throws this error:
```
dicomLoaderService.js:215 Uncaught (in promise) Error: Invalid dicom data loader
    at DicomLoaderService.findDicomDataPromise (dicomLoaderService.js:215:1)
    at _loadSegments (getSopClassHandlerModule.js:156:1)
    at getSopClassHandlerModule.js:125:1
    at new Promise (<anonymous>)
    at _load (getSopClassHandlerModule.js:120:1)
    at displaySet.load (getSopClassHandlerModule.js:98:1)
    at CornerstoneCacheService._getVolumeViewportData (CornerstoneCacheService.ts:188:1)
    at CornerstoneCacheService.createViewportData (CornerstoneCacheService.ts:80:1)
    at loadViewportData (OHIFCornerstoneViewport.tsx:401:1)
    at OHIFCornerstoneViewport.tsx:443:1
```

### Steps to Reproduce

1. switch to v3-stable
2. use `yarn orthanc:up` and `yarn dev:orthanc` to hook ohif to a local orthanc instance.
3. upload some studies and segmentation masks to orthanc. you can get studies [from here](https://github.com/Hasan-aga/2212-HeviProstate2212)
4. navigate to ohif and view the study. attempt to view the segmentation mask by double clicking on them.

### update
using [ohif v3 demo](https://v3-demo.ohif.org/local), I can upload my data and display the segmentation mask (although it has a small bug in the pop up dialog) this may mean that the problem is not in my data but that I have something missing in my local ohif instance. perhaps the default mode is missing some functionality that I need to add myself?!

### update 2
this may have to do with the fact that running `yarn dev:orthanc` uses a different config than running `yarn dev`. I am not sure how I can fix this though. I still want to see the segmentations mask using a local orthanc instance.

### update 3
this may be related to #2737

### The current behavior

currently we get a loading animation and an error in the console.

### The expected behavior

the expected behavior is displaying the segmentation mask over the series.

### OS

macos ventura 13

### Node version

v16.20.0

### Browser

Chrome Version 113.0.5672.126 (Official Build) (arm64)

**Comment by 920232796** [comment]
I also have the same problem. Do you have some new ideas with this problem? Thank you !

**Comment by Hasan-aga** [comment]
> I also have the same problem. Do you have some new ideas with this problem? Thank you !

make sure that your are loading the correct config. I think it is a problem with `yarn dev:orthanc` hence a solution maybe to run ohif with `APP_CONFIG=<your-config.js> yarn start` as we concluded in[ this community thread](https://community.ohif.org/t/unable-to-display-pdf-report-in-v3/810/11)

**Comment by 920232796** [comment]
I have tried your commands in community:

`yarn orthanc:up`
`APP_CONFIG=config/local_orthanc.js  yarn start` 

The content of "local_orthanc.js" is same with you. But I get a CORS error, as following:

<img width="761" alt="image" src="https://github.com/OHIF/Viewers/assets/32668889/a05e0a54-3316-4131-b67b-744d2aae8bd2">

Could you give me some advices about how I can do to solve this error?

**Comment by 920232796** [comment]
I am stuck in this page and can not load the "Basic Viewer page".
<img width="1644" alt="image" src="https://github.com/OHIF/Viewers/assets/32668889/bcd03b61-f660-4f45-94c7-8836867a0cbf">

I guess I didn't install the orthanc correctly? Could you write a blog to introduce the steps of installing orthanc? Thank you very much! I'm hoping your reply~

**Comment by Hasan-aga** [comment]
you can start an orthanc instance by running `yarn orthanc:up` but that is only half of the story. the other half is to connect ohif to orthanc by using a config. I will write a quick blog and return back to you.

**Comment by 920232796** [comment]
Yes, I am sure the config is correct. It's the log: 

<img width="767" alt="image" src="https://github.com/OHIF/Viewers/assets/32668889/3434ce19-aed0-40b6-9afd-0c7789dfbc6d">

**Comment by Hasan-aga** [comment]
when we run `yarn orthanc:up` we are running a docker container that has an nginx reverse proxy which deals with the cors problem. look at the file at this path: `/home/hasan/work/Viewers/.docker/Nginx-Orthanc/config/nginx.conf` it should look like this:
```
worker_processes 1;

events { worker_connections 1024; }

http {

    upstream orthanc-server {
        server orthanc:8042;
    }

    server {
        listen [::]:80 default_server;
        listen 80;

        # CORS Magic
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow_Credentials' 'true';
        add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';

        location / {

            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow_Credentials' 'true';
                add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
                add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            proxy_pass         http://orthanc:8042;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;

            # CORS Magic
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow_Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
            add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
        }
    }
}

```

**Comment by 920232796** [comment]
Thank you very much !

**Comment by sedghi** [comment]
So I investigated this and seems like your SEG are not sharing the same FOR as your referencedSeries so that is why they are not getting hydrated. Make sure they have the same frameofreferenceUID



![Image](https://github.com/OHIF/Viewers/assets/7490180/f6d3e2ee-3dbb-4c54-9c91-9af2c109dd92)

There was couple of small issues here and there that i will create a PR, but the big issue for this data that you shared in the first message is the discrepancy between FORs

Hope this helps

**Comment by fedorov** [comment]
@Yndiliadrin how did you create that SEG?

**Comment by vasiliykim98** [comment]
I have same problem. I used pydicom and pydicom-seg. I followed this documentation to create SEG https://razorx89.github.io/pydicom-seg/index.html

**Comment by diazandr3s** [comment]
> Hi!
> 
> I had the same problem with my DICOM-SEG files. With the same steps as you. I found that in this case the Viewer (I was using the v3-stable version) will fail at the point in the `extensions/cornerstone/src/utils/dicomLoaderService/[class]DicomLoaderService::*getLoaderIterator[line:198]`, the 3 method call in this method will look for valid loaders, the `getLocalData` wont do the trick in our case, nor the `getDataByImageType`, but the `getDataByDatasetType` will, it will fail, because the wadoRoot and wadoUri is both undefined in the dataset.
> 
> I was able to fix the issue, whit adding a fallback to the wadoRoot in the `extensions/cornerstone-seg/src/getSopClassHandlerModule::_getDisplaySetsFromSeries[57]`
> 
> So it went from this:
> 
> ```js
>   const displaySet = {
>     Modality: 'SEG',
>     loading: false,
>     isReconstructable: true, // by default for now since it is a volumetric SEG currently
>     displaySetInstanceUID: utils.guid(),
>     ...
>     instance,
>     instances: [instance],
>     wadoRoot,
>     wadoUriRoot,
>     wadoUri,
>     isOverlayDisplaySet: true,
>   };
> ```
> 
> to this
> 
> ```js
>   const displaySet = {
>     Modality: 'SEG',
>     loading: false,
>     isReconstructable: true, // by default for now since it is a volumetric SEG currently
>     displaySetInstanceUID: utils.guid(),
>     ...
>     instance,
>     instances: [instance],
>     wadoRoot: wadoRoot || 'dicom-web',
>     wadoUriRoot,
>     wadoUri,
>     isOverlayDisplaySet: true,
>   };
> ```
> 
> Important to note, that this solution won't fix the root of the problem (i didn't bother to look further) but can be a temporally fix.
> 
> I hope I could help!

I had the same issue and solved it following this change.
The DICOM-SEG files I had were correctly opened/visualized in OHIFv2 but OHIFv3 always showed me the same error.

> dicomLoaderService.js:215 Uncaught (in promise) Error: Invalid dicom data loader
>     at DicomLoaderService.findDicomDataPromise (dicomLoaderService.js:215:1)
>     at _loadSegments (getSopClassHandlerModule.js:156:1)
>     at getSopClassHandlerModule.js:125:1
>     at new Promise (<anonymous>)
>     at _load (getSopClassHandlerModule.js:120:1)
>     at displaySet.load (getSopClassHandlerModule.js:98:1)
>     at CornerstoneCacheService._getVolumeViewportData (CornerstoneCacheService.ts:188:1)
>     at CornerstoneCacheService.createViewportData (CornerstoneCacheService.ts:80:1)
>     at loadViewportData (OHIFCornerstoneViewport.tsx:401:1)
>     at OHIFCornerstoneViewport.tsx:443:1


Thanks @Yndiliadrin !

**Comment by sedghi** [comment]
I think this is fixed now, please re-open if the issue persists
