### ISSUE TITLE
[Bug] SEG/RTSTRUCT breaks Invert after loading

### ISSUE THREAD

**Issue by 03shek** [OHIF/Viewers#3419]
### Describe the Bug

Invert works in the study before a SEG is loaded, but stops working after

### Steps to Reproduce

1. On v3-demo.ohif.org, load a study https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1706.8374.643249677828306008300337414785
2. Display series 5 in the viewport
3. Click the Invert button. The color scale inverts as expected.
![image](https://github.com/OHIF/Viewers/assets/115667958/ae83d848-ec87-4a0f-8b85-3df44d224455)

4. Click the Invert button again to return to the gray+black color scale.
5. Load the SEG file. Click YES when prompted.
6. Click the Invert button. The color scale does not invert anymore.
![image](https://github.com/OHIF/Viewers/assets/115667958/0dd116f2-3426-4a6d-b942-2f2a8d3b3754)

### The current behavior

Invert works in the study before a SEG is loaded, but stops working after

### The expected behavior

Invert should work with and without a SEG loaded into a viewport.

### OS

Windows 10

### Node version

16.14.0

### Browser

 Chrome 111.0.0

**Comment by sedghi** [comment]
https://github.com/cornerstonejs/cornerstone3D/pull/677

**Comment by sedghi** [comment]
https://github.com/OHIF/Viewers/pull/3514
