### ISSUE TITLE
[Bug] v3: Segmentation flipped

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#3420]
### Describe the Bug

v2: https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.32722.99.99.99748660999232950779348544769645328227

<img width="1438" alt="image" src="https://github.com/OHIF/Viewers/assets/313942/f958bf0d-7414-4009-9a34-c174527a7b95">

v3:
https://ohif-v3.web.app/viewer?StudyInstanceUIDs=1.3.6.1.4.1.32722.99.99.99748660999232950779348544769645328227

<img width="1440" alt="image" src="https://github.com/OHIF/Viewers/assets/313942/843fa84d-253e-49e1-bca3-73426cc9d177">

### Steps to Reproduce

Click the links above.

### The current behavior

Segmentation orientation appears to be incorrect (or at least inconsistent vs v2).

### The expected behavior

v3 shows the same segmentation consistently with v2

### OS

macOS

### Node version

n/a

### Browser

Chrome

**Comment by fedorov** [comment]
As a side note - how do I know in v3 UI which of the SEG series I currently see in the viewport?

**Comment by jbocce** [comment]
@fedorov, I tried to click the links above but was denied access.

**Comment by fedorov** [comment]
@jbocce please confirm if you had denied access for the first link - that one should be public. The second one is expected to not be accessible.

You can download the study in question by installing [s5cmd](https://github.com/peak/s5cmd) and running the command below passing in the manifest attached here:

`s5cmd --no-sign-request --endpoint-url https://s3.amazonaws.com run ./manifest.csv`

[manifest.csv](https://github.com/OHIF/Viewers/files/11819689/manifest.csv)

For those interested, the study in question is located in [Imaging Data Commons](https://portal.imaging.datacommons.cancer.gov/). The manifest file was created by running the following query in BigQuery, which maps the DICOM StudyInstanceUID that can be seen in the URL to the locations of the AWS bucket folders containing the series included in that study:

```sql
WITH
  series_folders AS (
  SELECT
    DISTINCT(CONCAT("s3://",SPLIT(aws_url,'/')[2],'/',SPLIT(aws_url,'/')[3])) AS series_folder
  FROM
    `bigquery-public-data.idc_current.dicom_all`
  WHERE
    StudyInstanceUID = "1.3.6.1.4.1.32722.99.99.99748660999232950779348544769645328227" )
SELECT
  CONCAT("cp ", series_folder,"/* .") as manifest_cp_command
FROM
  series_folders
```

**Comment by jbocce** [comment]
Thank you so kindly @fedorov. It was the second link I was denied for and the first one I can access.

Thank you for all the information you provided which helped me reproduce the problem so that it can be triaged appropriately.

Thanks once again.

**Comment by hajrudinco** [comment]
We encountered this error when converting TotalSegmentator NIFTI output to DICOM SEG files and displaying them in the OHIF viewer.

- The converted DICOM SEG images were **LAS** oriented, while the source CT series were **LPS** oriented.
- In v2, DICOM SEG displayed correctly for the combination (SEG -> LAS, CT -> LPS).
- However, in v3, it did not display correctly for this case (SEG -> LAS, CT -> LPS).
- We **fixed** this issue by **changing the orientation of our DICOM SEG images to LPS**, which is the same as the source CT images.
- After the orientation change, the DICOM SEG displays correctly in v3 (and in v2).

**Comment by sedghi** [comment]
Thanks for the debugging info. This is already fixed in Cornerstone3D and I need to create a PR for it here
