### ISSUE TITLE
[Bug] SEG/RTSTRUCT names do not auto-populate as a grouping in Segmentation list

### ISSUE THREAD

**Issue by 03shek** [OHIF/Viewers#3426]
### Describe the Bug

RTSTRUCT/SEG name is not auto-populated as the name of that collapsible segmentation grouping after loading a RTSTRUCT/SEG.

### Steps to Reproduce

1. Load a study with RTSTRUCT or SEG that has a name. https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.2.840.113619.2.290.3.3767434740.226.1600859119.501
2. Double-click the RTSTRUCT (named "Contours on PET") to load it. Click YES when prompted.
3. RTSTRUCT/SEG ROIs are populated in the Segmentation list, but the RTSTRUCT/SEG name is not auto-populated as the name of that collapsible grouping.
![image](https://github.com/OHIF/Viewers/assets/115667958/704fa811-bb53-4407-b244-805413cbb309)

4. Another example study, but with multiple SEGS
![image](https://github.com/OHIF/Viewers/assets/115667958/fd64026b-1f66-486e-b209-f889c0df8605)

### The current behavior

RTSTRUCT/SEG name ("Contours on PET") does not auto-populate as the name of a collapsible segmentation grouping after loading a RTSTRUCT/SEG. User must manually rename that segmentation grouping to keep track of which RTSTRUCT/SEG has been opened.

### The expected behavior

RTSTRUCT/SEG name should auto-populate as the name of that collapsible segmentation grouping after loading a RTSTRUCT/SEG.

### OS

Windows 10

### Node version

16.14.0

### Browser

 Chrome 111.0.0

**Comment by jbocce** [comment]
This issue and https://github.com/OHIF/Viewers/issues/3421 will be addressed by the same change. For now I will keep both open so that each reporter can verify/comment on the ultimate fix.
