### ISSUE TITLE
[Bug] Window/Level defaults to 1/1 or 1/0 when loading RTStruct that references PT Image

### ISSUE THREAD

**Issue by dxlin** [OHIF/Viewers#3428]
### Describe the Bug

When loading RTStruct referencing PT image W/L values seem to use RTStruct intensity. When referencing CT image, W/L values load normally and as expected.

I am currently looking into identifying root cause and resolving this, please advise if any guidance or hints are available.

### Steps to Reproduce

1. Load study with PT image and RTStruct
2. Load PT image (note W/L value if SUV calculable 5/3 otherwise dependent on slice pixel values)
3. Load RTstruct referencing PT image (note W/L value)

### The current behavior

W/L value after loading RTStruct referencing PT image is 1/1 or 1/0

### The expected behavior

W/L value after loading RTStruct referencing PT image should be same as loading PT image itself (i.e. based on SUV or slice pixel values).

### OS

Windows 10

### Node version

18.12.1

### Browser

Chrome 113.0.5672.127

**Comment by sedghi** [comment]
[this](https://github.com/cornerstonejs/cornerstone3D/pull/676/files) will fix this most likely
