### ISSUE TITLE
MPR (Multiplanar Reconstruction)

### ISSUE THREAD

**Issue by robsonfagundes** [OHIF/Viewers#343]
Hi there
Folks, the OHIF Viewer offer support to MPR (Multiplanar Reconstruction)?
Thanks!

**Comment by swederik** [comment]
Not yet, but the upcoming React version will have a better plugin architecture to add MPR via VTK.js

**Comment by robsonfagundes** [comment]
Very Nice!
and... what is the forecast for release of the react version?

**Comment by swederik** [comment]
We don't have a timeline. It depends on how many people contribute. See https://github.com/OHIF/Viewers/issues/320

**Comment by robsonfagundes** [comment]
I understand... I'm will  try contribute too 
Thanks !!!

**Comment by TZubiri** [comment]
@swederik @robsonfagundes  By MPR do you mean constructing the 3D voxels from raw measurements? Or visualizing the 3D Voxels from all 3 possible angles?

**Comment by dannyrb** [comment]
We get a decent number of issues about MPR support, so I'm going to close this. We'll publish a better roadmap shortly. If you want to expedite things, or help shape MPR functionality, reach out and learn more about how you can contribute to development efforts.

**Comment by swederik** [comment]
Here you go: https://github.com/OHIF/Viewers/pull/557

Visible on https://viewer.ohif.org
