### ISSUE TITLE
[Bug] PerFrameFunctionalGroup Null Check Missing Causes Some Studies To Not Load

### ISSUE THREAD

**Issue by Michael-Andersen** [OHIF/Viewers#3432]
### Describe the Bug

When a study has a null value nested inside the PerFrameFunctionalGroup tag, it isn't handled properly, preventing the study from being displayed. A null in check in core/utils/combineFrameInstance.ts can fix the issue.

### Steps to Reproduce

1. Try to load a study with a null value inside the PerFrameFunctionalGroup tag. I've logged the PerFrameFunctionalGroup of my study in the console (value 4 is null):
<img width="745" alt="perframefunctionalgrouptag" src="https://github.com/OHIF/Viewers/assets/32403382/87b84daf-5713-41f5-b95b-f6b639fa25f9">

### The current behavior

The study won't load, here is the error from the above study:

<img width="1125" alt="perframefunctionalgrouperror" src="https://github.com/OHIF/Viewers/assets/32403382/801e2901-88d4-404e-9367-faea04b63788">

### The expected behavior

The code should ignore the null value and load the study. I have tested that adding an extra null check in combineFrameInstance.ts will fix this issue. Something like:

`const perFrame = (PerFrameFunctionalGroupsSequence
      ? Object.values(PerFrameFunctionalGroupsSequence[frameNumber - 1])
      : []
    )
      .map(it => {
        if (it == null) {
          return undefined;
        }
        return it[0];
      })
      .filter(it => it !== undefined && typeof it === 'object');`
      
     
I'd be happy to make a PR for this fix, if this is something the community would like.

### OS

Windows 10

### Node version

v16.17.0

### Browser

Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by rghgit1** [comment]
@Michael-Andersen 
We faced the same issue. Like you have mentioned adding null checked worked for us.

We added null check for both 
`const shared` and `const perFrame`

**Comment by jbocce** [comment]
@Michael-Andersen thanks for reporting this. Would it be possible for you to provide an anonymized DICOM file(s) that demonstrates the problem.
