### ISSUE TITLE
[Bug] OHIF v3 can't display dicom with jpeg anymore using /local

### ISSUE THREAD

**Issue by blabdouze** [OHIF/Viewers#3436]
### Describe the Bug

Since the migration to the `dicom-image-loader` loader, OHIF can't display dicom images with jpeg anymore. 
Trying to do so will raise the following error : 

```
Uncaught (in promise) TypeError: Cannot assign to read only property 'prototype' of function 'function DedicatedWorkerGlobalScope() { [native code] }'
    at jpeg.js:564:15
    at 945 (jpeg.js:29:17)
    at o (bootstrap:19:32)
    at o.t (create fake namespace object:10:23)
```

### Steps to Reproduce

1. Try to display a local DICOM with an image in jpg. (e.g. use https://viewer-dev.ohif.org/localbasic)
2. Open console to see the error

### The current behavior

Image is not displayed

### The expected behavior

Image is displayed

### OS

Windows 10

### Node version

v18.15.0

### Browser

Chrome, Firefox

**Comment by jbocce** [comment]
@blabdouze thank you for reporting this. However, I have not been able to reproduce this problem. Would it be possible for you to provide an anonymized DICOM file(s) that demonstrates the problem? Thanks.

**Comment by blabdouze** [comment]
Sure you'll find bellow a sample with the images that doesn't work  : 

[out.zip](https://github.com/OHIF/Viewers/files/11817905/out.zip)

They work fine with the v2 and other viewers so I don't this this is specific to this batch of data. 

Thanks !

**Comment by jbocce** [comment]
Thanks @blabdouze. However it works for me using either/both Orthanc and dcm4chee as the data source. What data source are you using?

![image](https://github.com/OHIF/Viewers/assets/109477394/d783d347-fc36-4661-bc3d-a758b4b27704)

**Comment by sedghi** [comment]
most likely a fix here https://github.com/cornerstonejs/cornerstone3D/pull/674, can you try after the package is published?

**Comment by blabdouze** [comment]
It seems to work fine with version 1.4.1 of conerstone, thanks !
