### ISSUE TITLE
[Bug] OHIF viewer v3-stable deployed in Azure doesn't load images

### ISSUE THREAD

**Issue by elenarogova** [OHIF/Viewers#3440]
### Describe the Bug

V3-stable OHIF viewer deployed on Azure doesn't load any images.

I deployed OHIF viewer on Azure using tutorial and Azure deploy template from here: https://github.com/microsoft/dicom-ohif#readme . And it doesn't work properly: studies and series lists are fine but all images doesn't load at all.

At the same time, V3-stable OHIF with the same settings and set up on my local machine (Windows 10) is completely fine and loads everything.

### Steps to Reproduce

1. Deploy V3-stable version on Azure using this tutorial and Azure deploy template https://github.com/microsoft/dicom-ohif#readme and this block in config 'default.js' instead of oidc: 
oauth: {
       azure: {
         authorizationURL: "https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/authorize",
         tokenURL: "https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/token",
         clientID: "{clientid}",
         callbackURL: "https://{url}/auth/callback",
         scope: "https://dicom.healthcareapis.azure.com/.default"
       }
     },
2. Set up V3-stable on a local machine with the same block in config 'default.js' instead of oidc. Run 'yarn run build:viewer' and then run prod version.
3. Call URL like this where token is an Azure service account access token (which I get from my another service and paste it in query manually):
 http://localhost:3000/viewer?StudyInstanceUIDs=1.2.826.0.1.3680043.6.38078.81833.20230221073117.6620.214.40685&token={token}
4. Check that study is opening fine and the image is loaded. Also quiting to all studies list is also works fine with no errors.
5. Do the same 3-4 steps but with Azure deployed base url. And there's CORS warning and error 'SharedArrayBuffer is not defined'. Any changes in Azure settings didn't work.

### The current behavior

1. On a local machine it all works fine and loads all images.
2. On Azure deployed viewer it doesn't load any images.

### The expected behavior

Viewer loads all images both locally and Azure deployed without any console errors and CORS warnings.

### OS

Windows 10

### Node version

16.15.0

### Browser

Yandex Browser 23.5

**Comment by jasonshea** [comment]
@elenarogova, I've been having the same issue.  After digging, I found that there was a breaking change that was introduced here: https://github.com/microsoft/dicom-server/discussions/1561%5D.

**Comment by ctpaep** [comment]
I have the same problem with VPS hosting. Images do not show, eternal inscription "Loading ..."
On the local machine in dev mode, everything works. 
<img width="990" alt="image" src="https://github.com/OHIF/Viewers/assets/101461462/14abd1ce-ba57-493c-b887-5154414163c9">

**Comment by daker** [comment]
Maybe you need to check the console to see what errors are returned by Azure

**Comment by Hasan-aga** [comment]
I have the same problem with the openResty recipe which is included with ohif. It could be a cors problem.

**Comment by malik-naik** [comment]
I have the same error when I build the app (commit HEAD: 869b8ced0581904ebac1867ca302635a93129f02)

**Comment by sedghi** [comment]
see here https://docs.ohif.org/configuration/dataSources/dicom-json
You prob need to create a fallback from 404 to index.html
