### ISSUE TITLE
Today's Date being inserted when DICOM has no date (or series date)

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3458]
### Describe the Bug

It appears that when a study doesn't have a date OHIF is instead displaying the current date in the viewer window.  

![image](https://github.com/OHIF/Viewers/assets/112980389/c268104e-6f84-4d26-9bb3-857123c06297)
![image](https://github.com/OHIF/Viewers/assets/112980389/5a407f31-9822-459d-ac33-972bf6cea641)

At the patient list level no date is displayed as expected
![image](https://github.com/OHIF/Viewers/assets/112980389/bf9f220d-3e6f-4339-bd12-5387d4030173)

This also seems to happen if a series date is missing.
In this example set there is a study date but no series date.  So the study date shown is correct but the series date shown at the top is todays date. 
![image (9)](https://github.com/OHIF/Viewers/assets/112980389/3e3bcd35-7c79-4a4a-a746-27a3544d4496)
(I have provided this data set for download here https://fileshare.uhn.ca/download/80667dae-ed36-4f15-a309-9aeae207e50c password "carpet" 
Please note that this file upload will expire in 30 days. )

### Steps to Reproduce

1. Open OHIF Demo
2. Sort by study date
3. select any of the studies which do not have study dates and open in basic viewer
4. the current date will appear instead of no date/invalid date.
5

### The current behavior

The current date is displayed in the viewer window when there is no date available in the DICOM header

### The expected behavior

For missing study dates : Either "Invalid Study Date" or "No Study Date" should be shown instead of using the current date which could be misleading.

For missing series dates  : Either "Invalid Series Date" or "No Series Date" or use the study date (if available). The current date should not be shown as it could be misleading.

### OS

Win 10 

### Node version

Using OHIF Demo 

### Browser

 Chrome 113.0.0

**Comment by JennyLeePMH** [comment]
@jbocce , please look into this.  Thanks.

**Comment by JennyLeePMH** [comment]
@jbocce , this is tested. Thanks.
