### ISSUE TITLE
 Help with the configuration of OHIF - CLEARCANVAS

### ISSUE THREAD

**Issue by Balth1590** [OHIF/Viewers#346]
Hi everyone,,
I recently installed OHIF in Centos and connected it to my PACS CLEARCANVAS server. It works perfectly My doubt is that in my server PACS I have 2 partitions (AETITTLE) A and B, when calling the patient and this is going to look for the PACS server in the partition A does it correctly, my problem comes when I need to go and find another patient to the partition B, this throws me an error of not finding the study.

How could I make him look for the patient no matter what part the patient is in?

also it would help me to be able to configure 2 or more partitions (AETITLES)

image AETITTLE A
![image](https://user-images.githubusercontent.com/47251958/52133927-264f0580-2621-11e9-9984-adbca8129fb8.png)

image AETITTLE B
![image](https://user-images.githubusercontent.com/47251958/52133974-467ec480-2621-11e9-9bdf-103fb9e5779d.png)

Thank you

**Comment by Balth1590** [comment]
Solved

**Comment by lam0620** [comment]
Hi @Balth1590 

Could you show your solution to fix this? I get the same issue.

**Comment by Vo-coder** [comment]
@Balth1590 I can access clearcanvas studies on OHIF but I cannot view them.can you help me. do I configure my computer?

**Comment by berkelmas** [comment]
@Balth1590 How do you configure for clearcanvas server ?

**Comment by abhinavswami9** [comment]
@Balth1590 How do you configure for clearcanvas server ?
