### ISSUE TITLE
[Feature Request] Default turn dragPan active for microscopy mode

### ISSUE THREAD

**Issue by j6u** [OHIF/Viewers#3478]
### What feature or change would you like to see made?

For Microscopy Mode, default active dragPan tool

### Why should we prioritize this feature?

This enables better experience for using microscopy as currently one will have to manually toggle dragPan on, which is what users expect as default.

**Comment by sedghi** [comment]
@md-prog I thought we added that. Could you please take care of this?

**Comment by j6u** [comment]
@sedghi, I am happy to take this on with some direction. I have figure out how to activate the dragPan, but I am curious which event I should listen to so that I can activate the tool at the right time.

```

onModeEnter: ({ servicesManager, extensionManager, commandsManager }) => {
      const { toolbarService, viewportGridService } = servicesManager.services;
      let unsubscribe;
      const activateDragPan = () => {
        toolbarService.recordInteraction({
          groupId: 'dragPan',
          itemId: 'dragPan',
          interactionType: 'tool',
          commands: [
            {
              commandName: 'setToolActive',
              commandOptions: {
                toolName: 'dragPan',
              },
              context: 'MICROSCOPY',
            },
          ],
        });

        // We don't need to reset the active tool whenever a viewport is getting
        // added to the toolGroup.
        unsubscribe();
      };

      // Since we only have one viewport for the basic cs3d mode and it has
      // only one hanging protocol, we can just use the first viewport
      ({ unsubscribe } = viewportGridService.subscribe(
        ViewportGridService.EVENTS.LAYOUT_CHANGED,
        () => {
          setTimeout(activateDragPan, 1000);
        }
      ));

      toolbarService.init(extensionManager);
      toolbarService.addButtons(toolbarButtons);
      toolbarService.createButtonSection('primary', [
        'MeasurementTools',
        'dragPan',
      ]);
    },
```

**Comment by j6u** [comment]
ViewportGridService.EVENTS.LAYOUT_CHANGED doesn't feel like the right event but that is the last event triggered before slide render.

**Comment by sedghi** [comment]
Hey, it should be much simpler than that. Since DICOM slide microscopy viewer (the lib we use) already has it https://github.com/search?q=repo%3AImagingDataCommons%2Fdicom-microscopy-viewer%20drag%20pan&type=code

**Comment by md-prog** [comment]
@sedghi By default, the middle button of the mouse (scroll) is set up with the drag pan.

**Comment by sedghi** [comment]
I wanted to fix this, and I tried the most recent viewer-dev.ohif.org and I can drag pan, I guess it is fixed somehow? 

https://viewer-dev.ohif.org/microscopy?StudyInstanceUIDs=2.25.141277760791347900862109212450152067508

Maybe what exactly you mean by drag pan? I thought you mean middle click pan? @j6u

**Comment by j6u** [comment]
You can drag pan but it is not default on. That is the issue that I am reporting.
I think drag pan should be on by default.

**Comment by sedghi** [comment]
@j6u Do you mean it should be bound to left click?

**Comment by sedghi** [comment]
@j6u Do you want to maybe explain a bit more what you mean?
