### ISSUE TITLE
can install OHIF with lesion tracker

### ISSUE THREAD

**Issue by alaradi2006** [OHIF/Viewers#348]
can i run both OHIF viewer and lesion tracker to connect  both to one PACS server 
by changing port or i have to run each one in diffrent server

**Comment by dannyrb** [comment]
There are a lot of options for standing up two single page app viewers at the same domain that connect to a single PACS. What have you tried? Where are you getting hung up?

**Comment by dannyrb** [comment]
It's been a while since I've reached out, so I'm going to close this issue. Please don't hesitate to respond if you need additional assistance.

**Comment by laithdj** [comment]
how do i run lesion tracker . i somehow only managed to compile the standalone viewer ?
