### ISSUE TITLE
Improve parsing/loading “time to first image”

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3480]
### Request

Investigate and implement possible improvements to the performance when loading the sample study below.

### Context

The time to first image (the time that it takes to render the first image in the viewport after a full reload) was higher in the new v3 version compared to OHIF v2 (legacy).

V2: https://testing-viewer.canceridc.dev/viewer/1.3.12.2.1107.5.1.4.60175.30000008042114404745300000007 - 13 sec

V3: https://ohif-v3.web.app/viewer?StudyInstanceUIDs=1.3.12.2.1107.5.1.4.60175.30000008042114404745300000016 - 35 sec

**Comment by fedorov** [comment]
@igoroctaviano the issue discussed in the document where you transferred this from is not about IDC - it is in general an observation that for that study it takes much longer for the first image to show up in the viewer than in v2. There are no segmentations in that study.

**Comment by igoroctaviano** [comment]
@fedorov there's also the issue with the totalsegmentator dataset. Do we need an independent issue for that?

**Comment by fedorov** [comment]
Yes, we need a separate issue comparing the performance of loading large SEG between v2 and v3.

**Comment by rodrigobasilio2022** [comment]
PR opened

**Comment by igoroctaviano** [comment]
@rodrigobasilio2022 can you please follow up with @sedghi to get the PR merged?

**Comment by sedghi** [comment]
also this one is finished?

**Comment by igoroctaviano** [comment]
@sedghi yes, it's finished.

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
