### ISSUE TITLE
[Bug] MultiFrame DICOM Problem

### ISSUE THREAD

**Issue by MartinK84** [OHIF/Viewers#3488]
### Describe the Bug

I’m currently trying to get the new Orthanc OHIF plugin to work with an existing larger Orthanc installation. This uses the Orthanc DICOM Web Plugin together with the Orthanc OHIF Plugin. OHIF is working fine with SingleFrame DICOMs, however, when trying to open Siemens MRI MultiFrame DICOMs OHIF just shows black images with the error message

```
Something went wrong
Something went wrongfalse.

Sorry, something went wrong there. Try again
```

The error message in the browser console is:

```js
331.bundle.bd0c13931a21d53086c9.js:29510 
        
       TypeError: Cannot read properties of null (reading '0')
    at app.bundle.599d31514539ffe1c788.js:14774:121
    at Array.map (<anonymous>)
    at combineFrameInstance (app.bundle.599d31514539ffe1c788.js:14774:109)
    at MetadataProvider._getInstance (app.bundle.599d31514539ffe1c788.js:14866:27)
    at MetadataProvider.get (app.bundle.599d31514539ffe1c788.js:14872:27)
    at Module.getMetaData (331.bundle.bd0c13931a21d53086c9.js:2813:37)
    at te (app.bundle.599d31514539ffe1c788.js:7:40923)
    at se (app.bundle.599d31514539ffe1c788.js:7:42930)
    at app.bundle.599d31514539ffe1c788.js:7:47832 'wadors:../dicom-web/studies/1.2.276.0.38.1.1.1.5631.20230503114015.46143371/series/1.3.12.2.1107.5.2.50.175785.2023050312011134582384252.0.0.0/instances/1.3.12.2.1107.5.2.50.175785.2023050312055486448984441/frames/41'
```
when trying to access the dicom-web resource via curl on ```.../dicom-web/studies/1.2.276.0.38.1.1.1.5631.20230503114015.46143371/series/1.3.12.2.1107.5.2.50.175785.2023050312011134582384252.0.0.0/instances/1.3.12.2.1107.5.2.50.175785.2023050312055486448984441/frames/41``` everything works fine and a resource is returned. There is also no error message on the Orthanc Server end so I do suspect that the error lies with OHIF.

Crosslink to community forum: https://community.ohif.org/t/multiframe-dicom-problem-together-with-orthanc/852

### Steps to Reproduce

Anonymized DICOMs that cause this issue can be downloaded here (link will work until 20 July 2023): https://upload.uni-jena.de/data/6493eb43ac2ed6.95743317/multiframe.dcm

### The current behavior

No images and an error message is displayed

### The expected behavior

Images should be displayed

### OS

Alma Linux 8.8

### Node version

unknown

### Browser

Edge 110.01587

**Comment by buileson93** [comment]
i have same problem 
<img width="1220" alt="image" src="https://github.com/OHIF/Viewers/assets/100753033/63ddc334-22fd-41aa-9e79-22a7bb7b7581">

**Comment by ada-s4c** [comment]
I am experiencing a similar issue with multi-frame MR SOPs but unlike this issue the OHIF 1.3 viewer is not giving any error in console, it just says shows the warning with 

    Display Set Messages
    1. Display set has missing position information.
    2. Display set is not a reconstructable 3D volume.

should I open a separate issue or attach an anonymized sample to this one?
