### ISSUE TITLE
Support for per-viewport W/L presets

### ISSUE THREAD

**Issue by james-hanks** [OHIF/Viewers#3493]
- [x] #3742
- [x] #3743
- [x] #3764
- [x] #3825 
- [x] #3814

Latest design and behviors - Updated Nov 2, 2023 by @dan-rukas 

- Viewport - Layout overview
- Viewport - Actions hide and show
- Viewport - Status
- Viewport - Actions and tools
- Viewport - Window Levels
- Component - Multi-level Menu

![Image](https://github.com/OHIF/Viewers/assets/2745168/0360e7c7-98b2-4d41-aef5-05842b4cda90)

![Image](https://github.com/OHIF/Viewers/assets/2745168/c87aa43c-c8ef-4612-b4e4-bbcf9fb802b3)

![Image](https://github.com/OHIF/Viewers/assets/2745168/27b1ed75-c3af-437b-bd9e-1b3242ad8ece)

![Image](https://github.com/OHIF/Viewers/assets/2745168/8a65b5f9-19a7-4d38-8c96-f4ebf4d35c2e)

![Image](https://github.com/OHIF/Viewers/assets/2745168/137b19b8-a97e-4110-a529-ce200af1f0f1)

<img width="809" alt="Component-Multi-Menu" src="https://github.com/OHIF/Viewers/assets/2745168/9624d137-f1bb-44ce-8b41-80a61f8d6d62">

**Comment by sedghi** [comment]
Some sketch ideas

![image](https://github.com/OHIF/Viewers/assets/7490180/cf1d691f-e700-4307-8634-ab3e41e22a98)

**Comment by sedghi** [comment]
![image](https://github.com/OHIF/Viewers/assets/7490180/76600072-abcd-4a0f-ba8a-91282f455519)

**Comment by james-hanks** [comment]
@jbocce to add development tasks and link

**Comment by dan-rukas** [comment]
Updated all finalized designs.

Includes:
- Viewport - Layout overview
- Viewport - Actions hide and show
- Viewport - Status
- Viewport - Actions and tools
- Viewport - Window Levels
- Component - Multi-level Menu

**Comment by sedghi** [comment]
Remaining stuff
- colorLUT 
- 3d presets 
- patient info on top

**Comment by dan-rukas** [comment]
Adding the last design piece here. Volume Rendering dialog is an option in the W/L menu that show an additional moveable modal window. 

Design below
3d thumbnail assets: 
[volume-rendering-presets-Feb23.zip](https://github.com/OHIF/Viewers/files/14386348/volume-rendering-presets-Feb23.zip)

![Image](https://github.com/OHIF/Viewers/assets/2745168/0625e8b2-c2e6-42b3-bee7-f2c4b6d2499a)

**Comment by james-hanks** [comment]
@dan-rukas to add updated volume rendering design

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
