### ISSUE TITLE
OHIF Docker image/container - allow for APP_CONFIG and TLS cert and private key to be supplied during `docker run`

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3495]
### What feature or change would you like to see made?

At present, for the OHIF Docker container, the APP_CONFIG configuration file for OHIF can only be specified via a Docker volume mount (i.e. `-v`). For greater flexibility, allow for a Docker environment variable to be set whereby the value of the environment variable is the configuration file contents itself.

The OHIF Docker container should allow for OHIF to be accessed in a secure context. At a minimum it should allow for the TLS certificate and private keys to be supplied and when supplied and deployed OHIF should only be accessible via https.

More documentation should be provided concerning CORS and OHIF.

### Why should we prioritize this feature?

Providing the APP_CONFIG file as an environment variable facilitates specifying the configuration file when deploying OHIF on Google Cloud.

With OHIF v3's dependency on `SharedArrayBuffer` for volume loading, running OHIF in a secure context is essential. Facilitating a convenient method for deploying the Docker container over HTTPS is a must.

**Comment by sedghi** [comment]
https://docs.ohif.org/deployment/docker#ca-signed-certificates
