### ISSUE TITLE
The trouble of getting started

### ISSUE THREAD

**Issue by JamieACE** [OHIF/Viewers#35]
### I really want to know how to run the OHIFViewer of Viewers in right way, First time I running the ./bin/medkenOrthanc.bat on windows10, but have the error about:
`=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: unknown package in top-level dependencies: cornerstone
   unknown package in top-level dependencies: dicomweb
   unknown package in top-level dependencies: design
   unknown package in top-level dependencies: ohif:core
   unknown package in top-level dependencies: viewerbase
   unknown package in top-level dependencies: worklist
   unknown package in top-level dependencies: hangingprotocols
   unknown package in top-level dependencies: wadoproxy

=> Your application has errors. Waiting for file change.`

### So I copy the Viewers/Packages in to the OHIFViewers , and run medkenOrthanc.bat again. Then it show me another errors:
`=> Started proxy.
=> Started MongoDB.

Unable to resolve some modules:

  "jquery" in /C/Users/Jamie/OHIF_workspace/Viewers/OHIFViewer/Packages/cornerstone/client/jquery.hammer.js
(web.browser)
  "jsdom" in
/C/Users/Jamie/OHIF_workspace/Viewers/OHIFViewer/Packages/active-entry/lib/jquery.pwstrength.bootstrap.js
(web.browser)
  "zlib" in /C/Users/Jamie/OHIF_workspace/Viewers/OHIFViewer/Packages/cornerstone/client/dicomParser.js
(web.browser)
  "hammerjs" in /C/Users/Jamie/OHIF_workspace/Viewers/OHIFViewer/Packages/cornerstone/client/jquery.hammer.js
(web.browser)
  "fs" in /C/Users/Jamie/OHIF_workspace/Viewers/OHIFViewer/Packages/cornerstone/client/libCharLS.js (web.browser)
  "path" in /C/Users/Jamie/OHIF_workspace/Viewers/OHIFViewer/Packages/cornerstone/client/libCharLS.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save jquery jsdom meteor-node-stubs hammerjs

Unable to resolve some modules:

  "jquery" in
/C/Users/Jamie/OHIF_workspace/Viewers/OHIFViewer/Packages/active-entry/lib/jquery.pwstrength.bootstrap.js
(os.windows.x86_32)
  "jsdom" in
/C/Users/Jamie/OHIF_workspace/Viewers/OHIFViewer/Packages/active-entry/lib/jquery.pwstrength.bootstrap.js
(os.windows.x86_32)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save jquery jsdom

=> Errors prevented startup:

   While preparing to run:
   ../config/medkenOrthanc.json: file not found (settings file)

=> Your application has errors. Waiting for file change.
`
Thanks
Jamie

**Comment by JamieACE** [comment]
I have try to use "meteor npm install --save jquery jsdom meteor-node-stubs hammerjs" and "meteor npm install --save jquery jsdom" , but without any help and return the same errors.

**Comment by itcthienkhiem** [comment]
Hi JamieACE,

Try starting it from one level up (/path/to/OHIF/Viewers/OHIFViewer) with the command:

# bin/localhostOrthanc.sh

**Comment by swederik** [comment]
Hi Jamie,

Try the Wiki article on Getting Started: https://github.com/OHIF/Viewers/wiki/Getting-Started

**Comment by JamieACE** [comment]
Hi all,
I follow the Wiki and running on the Linux then it works. Thanks a lot. 
But I really want to know how to run it on the windows os.

thanks 
Jamie

**Comment by swederik** [comment]
I've run it on Windows and everything worked fine. The annoying part is that you need to set the environment variable (PACKAGE_DIRS="../Packages") in the system settings.

**Comment by radicalrob** [comment]
@JamieACE - for Windows, I start the viewer using a .bat file.  The syntax is a little different than Unix.  Here is an example:

set PACKAGE_DIRS=c:\workspace\OHIF\Viewers\Packages
meteor --settings C:/Workspace/StatRad/Viewers/config/orthancDIMSE.json

**Comment by JamieACE** [comment]
Hi :
I have set the environment variable and running a .bat file, but still out of work.
The .bat file is (set PACKAGE_DIRS=..\Packages
meteor --settings ../config/medkenOrthanc.json)

`=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: unknown package in top-level dependencies: cornerstone
   unknown package in top-level dependencies: dicomweb
   unknown package in top-level dependencies: design
   unknown package in top-level dependencies: ohif:core
   unknown package in top-level dependencies: viewerbase
   unknown package in top-level dependencies: worklist
   unknown package in top-level dependencies: hangingprotocols
   unknown package in top-level dependencies: wadoproxy

=> Your application has errors. Waiting for file change.`
what can I do about this error?

Thanks
Jamie

**Comment by JamieACE** [comment]
Hi:
It has running in the right way. I modify the .bat file (set PACKAGE_DIRS=..\..\Packages
meteor --settings ../../config/medkenOrthanc.json) then it works.
Thanks a lot.
Jamie
