### ISSUE TITLE
[Bug] Microscopy never tracks measurement

### ISSUE THREAD

**Issue by j6u** [OHIF/Viewers#3500]
### Describe the Bug

When I add measurement, I expect the track measurement dialog to show but it doesn't.

There is currently no way to save the measurement for microscopy.

### Steps to Reproduce

1. Open a wsi microscopy
2. Add a measurement

### The current behavior

Measurement tracking dialog not showing and there is no way to track

### The expected behavior

Measurement tracking dialog should show

### OS

macOS 12.6

### Node version

16.14

### Browser

Chrome Version 114.0.5735.133 (Official Build) (arm64)

**Comment by j6u** [comment]
I am happy to take this on if I can get some direction.

**Comment by cheyvaert-medexprim** [comment]
Same behavior here  (os: Debian GNU/Linux 11,  browser firefox 114.0.2 (64 bits) node 18.16.0

**Comment by j6u** [comment]
Bump. Any updates?

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
