### ISSUE TITLE
[Feature Request] Support of two DICOM servers

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#3507]
### What feature or change would you like to see made?

Add support to configure the viewer with 2 DICOM servers as sources, so that when a study is selected, series from that study are retrieved from each of the servers.

### Why should we prioritize this feature?

In the situations where large number of images are analyzed, it is beneficial to be able to review the analysis results/annotations without having to contribute those into the same DICOM server where the images are. In some cases, this is not possible because the server containing the images is "read only" (e.g., for the content available from NCI Imaging Data Commons). In other cases, it is just not desirable to combine those annotations/analysis results with the images, since their quality may first need to be established, as an example. Replicating images that were analyzed in a separate server can be a very costly and time-consuming procedure (e.g., there are image collections with the size measured in terabytes in IDC).

In v2, we implemented experimental support for this feature in a fork (see this branch https://github.com/ImagingDataCommons/Viewers/tree/IDC2servers and https://github.com/OHIF/Viewers/issues/1512), and it proved to be extremely useful. We use this feature routinely for the development work. Without this feature, switching from v2 to v3 for us will be very disruptive.

**Comment by igoroctaviano** [comment]
@sedghi here is another item that was not part of our last meeting but should be. Any thoughts? is this something that might be on the roadmap or could be added?

**Comment by sedghi** [comment]
Hmmmm, interesting. 
I haven't looked into the code yet, but is it like when a study is opened it sends a qido to each server to see if it contains the study, and then merge the results?

We have multiple data source configuration in the immediate roadmap, which let you select the datasource in the worklist. There is another item in the roadmap to combine the results from multiple datasources in the worklist (nifti + dicom) and show each. But I guess what you are talking here is a little bit different, right?

**Comment by sedghi** [comment]
CC @jbocce  Since he is assigned to do the multi datasource item in near future

**Comment by igoroctaviano** [comment]
> Hmmmm, interesting. I haven't looked into the code yet, but is it like when a study is opened it sends a qido to each server to see if it contains the study, and then merge the results?
> 
> We have multiple data source configuration in the immediate roadmap, which let you select the datasource in the worklist. There is another item in the roadmap to combine the results from multiple datasources in the worklist (nifti + dicom) and show each. But I guess what you are talking here is a little bit different, right?

Here's the simplest use case I can think of: 
- Define one server to be the qido server (the original/main image server)
- When the user opens study X from the workflist
- Fetch original (CT) series A, B, and C from the original/main image server (A)
- Also fetch derived series (annotations) D and C from the annotations server (B)

This way we can retrieve other series from other servers without having to copy the derived series to the original/main image server or configure a new server with them combined.

Right now we could keep this even simpler and just support this if they are dicomweb data sources (no need to merge nifti with dicom or something else at the moment)

@fedorov please correct me if I'm wrong

**Comment by sedghi** [comment]
I understand the use case, but to me the feature (multi dicom server) should not care about if there some series are derived or not. It should just be a secondary call to retrieve anything from the secondary server as well.

**Comment by igoroctaviano** [comment]
> I understand the use case, but to me the feature (multi dicom server) should not care about if there some series are derived or not. It should just be a secondary call to retrieve anything from the secondary server as well.

This is just a use case, I'm not saying it has to worry about it being derived or not

**Comment by fedorov** [comment]
> is it like when a study is opened it sends a qido to each server to see if it contains the study, and then merge the results?

Yes!

> We have multiple data source configuration in the immediate roadmap, which let you select the datasource in the worklist. There is another item in the roadmap to combine the results from multiple datasources in the worklist (nifti + dicom) and show each. But I guess what you are talking here is a little bit different, right?

Except that we couldn't care less about nifti - yes! We 

> I understand the use case, but to me the feature (multi dicom server) should not care about if there some series are derived or not. It should just be a secondary call to retrieve anything from the secondary server as well.

Correct!

@igoroctaviano your description is correct.

Again - no niftis anywhere close for our use case or for IDC-motivated functionality, please!

**Comment by igoroctaviano** [comment]
- Add query param support to select secondary data source and series (even using multiple servers)

**Comment by rodrigobasilio2022** [comment]
The following pictures demonstrate this functionality.

Main datastore, with two studies. Note that the expanded study has three series.

image

Opening the study using an URL with the secondGoogleServer parameter, it shows four series, the dicom seg series belonging only to the second server

image

Next picture shows that the parameter SeriesInstanceUID works to filter a particular series. Remember that this url parameter works as follows: it tries to filter the series, but if the result is empty, it returns all series found of a particular study. That's why the segmentation series also appears

image

**Comment by rodrigobasilio2022** [comment]
Note there is a difference from v2:
In v2 the parameter was preceded by !

http://localhost:3000/viewer/1.3.6.1.4.1.14519.5.2.1.6655.2359.247426265538388028079845922798!secondGoogleServer=/projects/idc-tcia/locations/us-central1/datasets/tcia-idc-datareviewcoordination/dicomStores/planar_annotations

In v3 it is a normal html parameter, as you can see in the example:
http://localhost:3000/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.99.1071.26968527900428638961173806140069&secondGoogleServer=projects/idc-external-002/locations/us-west1/datasets/twoserversTest/dicomStores/test&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.24930372521077247896408083282537

**Comment by igoroctaviano** [comment]
> I added today in the PR the ability to define a second server with the URL parameter secondGoogleServer.
> 
> The following pictures demonstrate this functionality.
> 
> Main datastore, with two studies. Note that the expanded study has three series.
> 
> ![image](https://user-images.githubusercontent.com/114958722/268254581-c69f2843-f640-48ff-a093-69a9095a9c59.png)
> 
> Opening the study using an URL with the secondGoogleServer parameter, it shows four series, the dicom seg series belonging only to the second server
> 
> ![image](https://user-images.githubusercontent.com/114958722/268254831-3646cec6-31a6-41f3-a55c-8889c6e34035.png)
> 
> Next picture shows that the parameter SeriesInstanceUID works to filter a particular series. Remember that this url parameter works as follows: it tries to filter the series, but if the result is empty, it returns all series found of a particular study. That's why the segmentation series also appears
> 
> ![image](https://user-images.githubusercontent.com/114958722/268254680-132e5751-0f3a-4f98-9b2c-8fb8bddb0a27.png)

I reviewed the code, let's schedule a call first. I think we need to abstract things a bit (take gcp-specific things out) otherwise it won't make to master.

**Comment by rodrigobasilio2022** [comment]
@igoroctaviano and I discussed and the present solution is general enough and allows multiple server definitions

**Comment by fedorov** [comment]
How does the series filter work - is it applied to both servers, or to only one of them?

**Comment by rodrigobasilio2022** [comment]
Now it's applied to both servers.

**Comment by igoroctaviano** [comment]
@rodrigobasilio2022 whats the status on this one?

**Comment by rodrigobasilio2022** [comment]
Had two approvals. I think just depeding on Ali to approve and merge

**Comment by igoroctaviano** [comment]
> Had two approvals. I think just depeding on Ali to approve and merge

Please follow up with him to get it merged. Thanks!

**Comment by sedghi** [comment]
@igoroctaviano I think this is finished right?

**Comment by igoroctaviano** [comment]
> @igoroctaviano I think this is finished right?

Yes, its finished.

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
