### ISSUE TITLE
[Bug] Reset view tool not working properly in MPR mode

### ISSUE THREAD

**Issue by Yonatanmh** [OHIF/Viewers#3508]
### Describe the Bug

The reset view tool does not function as expected in MPR mode. After changing the angles with the crosshairs, one would intuitively expect the reset tool to return the angles back to their original positions. However, clicking on the reset tool does not perform this action - the crosshairs remain in their adjusted position.

### Steps to Reproduce

1. Open the OHIF Viewer.
2. Select a study and switch to MPR mode.
3. Utilize the crosshairs to modify the viewing angles.
4. Click on the "Reset View" tool in the toolbar.

### The current behavior

Upon changing angles with the crosshairs and clicking the reset tool, the view does not revert to the initial angles. The crosshairs maintain their adjusted position.

### The expected behavior

Following an adjustment of the viewing angles with the crosshairs, it is anticipated that clicking on the reset tool would return the angles to their starting positions.

### OS

macOS 13.4

### Node version

19.7.0

### Browser

Chrome 114.0.5735.133 (Official Build) (arm64)

**Comment by vitalii-komenda** [comment]
Any update on this? 

It's really important thing have I think

**Comment by sedghi** [comment]
works in master

**Comment by sedghi** [comment]
seems like still an issue

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
