### ISSUE TITLE
How to use Standalone OHIF Viewer within React or Vue app

### ISSUE THREAD

**Issue by johannamussolini** [OHIF/Viewers#351]
This is a fantastic initiative! I currently use Standalone OHIF Viewer within a React app but it has several limitations. Having OHIF implemented in React would open many new possibilities!

I would like to contribute to this project as well.

Cheers

_Originally posted by @diaztula in https://github.com/OHIF/Viewers/issues/320#issuecomment-448236950_

I'm currently working in a Vue project and I'm pretty new and I need to use the Standalone OHIF Viewer within my app, Does somebody have some guide of how to do this?
I'd really appreciate any guidance.
Thanks so much!

**Comment by swederik** [comment]
For the current standalone viewer: you can put it in an iframe.
For the React version, you can follow the example folder: https://github.com/OHIF/Viewers/tree/react/Packages-react/ohif-viewer/example

Specifically, index.html which just imports the library and uses ReactDom to render it:
https://github.com/OHIF/Viewers/blob/react/Packages-react/ohif-viewer/example/index.html#L166

You can try this now, you just have to switch it to use unpkg on this line: https://github.com/OHIF/Viewers/blob/react/Packages-react/ohif-viewer/example/index.html#L56

**Comment by johannamussolini** [comment]
Hi Erik, Thanks for your prompt response! I'm not and expert on React... but I'll see if I can reproduce this with Vue.js

Now I'm stucked trying to use the Standalone Viewer, I've tried to generate the JSON file following the script you suggested on previous posts from my DCM file (https://gist.github.com/swederik/b7901bd933e6497720783e532616eec0). I'm using some DICOM files that the client send me for testing... but for some reason when I parse it to a JSON using the script and then trying to display it using the Standalone viewer, the following error is thrown:

Error: loadImageFromImageLoader: no image loader for imageId
at loadImageFromImageLoader (ohif_cornerstone.js?hash=b2d4f3d201840adb2975e3fbc1f00e4786b64831:6133)
at Module.loadAndCacheImage (ohif_cornerstone.js?hash=b2d4f3d201840adb2975e3fbc1f00e4786b64831:6199)

This is the JSON that I was able to generate from my DCM file using the above JS script
{
"transactionId": "study",
"studies": [
{
"studyInstanceUid": "1.2.826.0.1.3680043.2.1208.154494870514920191158835635",
"studyDate": "20180817",
"studyTime": "080835.000000",
"patientName": "SANCHEZ MARIA DELIA",
"patientBirthDate": "20050226",
"patientId": "NO ID",
"patientSex": "F",
"seriesList": [
{
"seriesInstanceUid": "1.2.826.0.1.3680043.2.1208.254494870514920191158835642",
"seriesBodyPart": "SPINE LUMBAR",
"seriesNumber": "0001",
"seriesDate": "20180817",
"seriesTime": "080835.000000",
"seriesModality": "OT",
"instances": [
{
"columns": 3610,
"rows": 4400,
"instanceNumber": "0001",
"photometricInterpretation": "MONOCHROME2",
"bitAllocated": 16,
"bitsStored": 12,
"pixelRepresentation": 0,
"samplesPerPixel": 1,
"highBit": 11,
"rescaleSlope": "1.00",
"rescaleIntercept": "0.00",
"imageType": "ORIGINAL\PRIMARY\OTHER",
"sopInstanceUid": "1.2.826.0.1.3680043.2.1208.354494870514920191158835644",
"url": "file://Users/johannamussolini/code/Viewers/StandaloneViewer/StandaloneViewer/private/testData/examples/1.2.826.0.1.3680043.2.1208.154494870514920191158835635/1.2.826.0.1.3680043.2.1208.254494870514920191158835642/1.2.826.0.1.3680043.2.1208.354494870514920191158835644.dcm"
}
]
}
]
}
]
}

Is there any problem with the DICOM image file? Is it not supported? Does the standalone viewer supports any kind of DICOM file?
Any help would be really appreciated! thanks so much!

**Comment by swederik** [comment]
Your problem is that you are using a local file on your hard drive. I don't think file URLs will work (or at least we have never tested it). You need to serve it from a web server via http(s).

e.g. `python -m SimpleHTTPServer 3000`

**Comment by johannamussolini** [comment]
Hi!! yes that was the problem, I was able to solve this (https://github.com/OHIF/Viewers/issues/177#issuecomment-465627101). Thanks so much for replying back.

**Comment by dannyrb** [comment]
@johannamussolini, your original questions appears to have been answered. Please feel free to create a new issue if you have additional questions.
