### ISSUE TITLE
[Bug] Image Wrong Size in the viewport

### ISSUE THREAD

**Issue by francomotta** [OHIF/Viewers#3520]
### Describe the Bug

When loading a study, the images are the wrong size in the viewport.

### Steps to Reproduce

Select the TCGA-QQ-A8VH study, select the 1x3 layout. Notice that the first viewport image displays the image at the wrong size (big). If you hit the "=" key, it makes the image the correct size. The same problem occurs if you double-click the image to get it to 1x1 format.

The right thing would be to put an option after opening the images to adjust the size in the viewport.
![Wrong size-2023-07-05 140722](https://github.com/OHIF/Viewers/assets/62942118/e484825c-5f8e-4bb9-817d-b0f67612a280)

### The current behavior

Note that the first image is the wrong size.
![Wrong size-2023-07-05 140722](https://github.com/OHIF/Viewers/assets/62942118/4075bdca-cef1-445e-90e8-604cc0efadb1)

### The expected behavior

The right thing would be to put an option after opening the images to adjust the size in the viewport.
![Correct size-2023-07-05 140722](https://github.com/OHIF/Viewers/assets/62942118/8a8c8f2f-7897-47eb-8096-aedfeab776a7)

### OS

Windows 11

### Node version

20.3.0

### Browser

Chrome

**Comment by francomotta** [comment]
@jbocce , how are you?

Even with that tip, the error continues. Occurs most frequently in the 1x3 format with MR.

**Comment by sedghi** [comment]
Bill recently merged a fix for resize, maybe this is fixed now?

**Comment by sedghi** [comment]
So this is a tricky one, since we moved away from our previous setup where we re-created the viewports, and now the viewport (html div) would MOVE to the new location (for performance gain) and since there is no extra render, the camera is not changed. I don't think this is a sever problem, but if you think it is let us know

**Comment by sedghi** [comment]
So in tmtv mode for instance, if we move from one stage to another, the old viewport (image) sized is preserved as of the new way of assiging Ids to viewports and not index (React just moves the element and canvas to the next stage, which is really super performant, but comes at the cost that we get wrong size, and we should trigger a resize maybe after the layout change

![CleanShot 2023-10-18 at 10 43 06](https://github.com/OHIF/Viewers/assets/7490180/83165b2f-d78f-458f-86d1-0a2f554c8cda)

**Comment by Srikanthkurva** [comment]
Hi
I have successfully running this "https://github.com/OHIF/Viewers?tab=readme-ov-file". I  have one DCOM Images 
![Uploading OHIF1.PNG…]()
 folder. Now I have replace with my DCOM images. How to replace my DCOM images. I have Tried. Please Could you help me.

**Comment by Srikanthkurva** [comment]
Hi
I have successfully running this "https://github.com/OHIF/Viewers?tab=readme-ov-file". I  have one DCOM Images 
![OHIF1](https://github.com/OHIF/Viewers/assets/131551584/fd27838d-df10-4e2f-a1a6-447e643194ec)
folder. Now I have replace with my DCOM images. How to replace my DCOM images. I have Tried. Please Could you help me.
![OHIF1](https://github.com/OHIF/Viewers/assets/131551584/2232e698-61eb-41e6-adcd-161217c1bef0)

**Comment by Srikanthkurva** [comment]
Hi
I have successfully running this "https://github.com/OHIF/Viewers?tab=readme-ov-file". I  have one DCOM folder Images. Now I have replace with my DCOM images. How to replace my DCOM images. I have Tried. Please Could you help me.
![OHIF1](https://github.com/OHIF/Viewers/assets/131551584/c3c37abf-506c-415d-b260-8e3a4ef2218e)
