### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LexusTI** [OHIF/Viewers#3521]
### Describe the Bug

Hi All!

I'm having a problem in the OHIF viewer when rendering an MG/CR image via json. Here is my json file:

{
        "studies": 
        [
            {
                "StudyInstanceUID": "1.2.840.113681.2206606139.739.3355346425.680", 
                "StudyDescription": "Mammography", 
                "StudyDate": "20111231", 
                "StudyTime": "181417", 
                "PatientName": "Smith Nathalie", 
                "PatientID": "777777", 
                "AccessionNumber": "ACC456", 
                //"PatientAge": "", 
                "PatientSex": "F", 
                "series": 
                [
                    {
                        "SeriesInstanceUID": "1.2.840.113681.2206606139.739.3355346425.681.1", 
                        "SeriesDescription": "R CC", 
                        "SeriesNumber": 1, 
                        "Modality": "MG", 
                        "SliceThickness": "", 
                        "instances": 
                        [
                            {
                                "metadata": 
                                {
                                    "Columns": 2560, 
                                    "Rows": 3328, 
                                    "InstanceNumber": 53, 
                                    "SOPClassUID": "1.2.840.10008.5.1.4.1.1.1.2", 
                                    "PhotometricInterpretation": "MONOCHROME2", 
                                    "BitsAllocated": 16, 
                                    "BitsStored": 12, 
                                    "PixelRepresentation": 0, 
                                    "SamplesPerPixel": 1, 
                                    "PixelSpacing": [0.07, 0.07], 
                                    "HighBit": 11, 
                                    "ImageOrientationPatient": ["P", "L"], 
                                    "ImagePositionPatient": [0.0, 0.0, 0.0], 
                                    "FrameOfReferenceUID": "", 
                                    "ImageType": ["DERIVED", "SECONDARY"], 
                                    "Modality": "MG", 
                                    "SOPInstanceUID": "1.2.840.113681.2206606139.739.3355346425.685.1", 
                                    "SeriesInstanceUID": "1.2.840.113681.2206606139.739.3355346425.681.1", 
                                    "StudyInstanceUID": "1.2.840.113681.2206606139.739.3355346425.680", 
                                    "WindowCenter": 2047.0, 
                                    "WindowWidth": 4096.0, 
                                    "SeriesDate": "20070430"
                                }, 
                                "url": "dicomweb:https://lexusbucketnew.s3.amazonaws.com/imagens_dicom/1.2.840.113681.2206606139.739.3355346425.680/1.2.840.113681.2206606139.739.3355346425.685.1.dcm"
                            }
                        ]
                    }
                ], 
                "NumInstances": 1, 
                "Modalities": "MG"
            }
        ]
}

![image](https://github.com/OHIF/Viewers/assets/133989861/26b3db9c-cea6-4362-951d-6e6b0032eeb6)

### Steps to Reproduce

dd

### The current behavior

ddd

### The expected behavior

df

### OS

d

### Node version

fd

### Browser

dfd

**Comment by sedghi** [comment]
I can't download the file via https://lexusbucketnew.s3.amazonaws.com/imagens_dicom/1.2.840.113681.2206606139.739.3355346425.680/1.2.840.113681.2206606139.739.3355346425.685.1.dcm

If you make a public link I can investigate
