### ISSUE TITLE
[Bug] TotalSegmentator dataset taking longer to load compared to v2

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3523]
### Describe the Bug

Based on recent tests with v2 and v3 we identified that the loading of the segmentations are faster in v2. 
This issue should further investigate and address the problem.

- TotalSegmentator dataset shared with @sedghi

### Steps to Reproduce

1. Load TotalSegmentator dataset 
2. Load segmentation series (benchmark v2 and v3)

### The current behavior

Loads slower in v3

### The expected behavior

Loads better or equal to v2

### OS

macOS 13.4 (22F66)

### Node version

16

### Browser

Version 114.0.5735.198 (Official Build) (x86_64)

**Comment by sedghi** [comment]
I can't run the total segmentor case in OHIF v2, which study you are trying to load?

![image](https://github.com/OHIF/Viewers/assets/7490180/4402c266-b5e9-47cc-98d4-7fe5cff475b1)

**Comment by igoroctaviano** [comment]
@sedghi http://localhost:3000/viewer/61.7.186150680759207515465616855509993541745

**Comment by sedghi** [comment]
Were you supposed to share a screenshot or a dataset?

**Comment by igoroctaviano** [comment]
> Were you supposed to share a screenshot or a dataset?

Remember the drive I shared with a bunch of datasets e.g. the RGB one? there you can find the totalsegmentator dataset.

**Comment by sedghi** [comment]
This file doesn't have a SEG 

![image](https://github.com/OHIF/Viewers/assets/7490180/61d91a88-ba2c-4f9c-a614-2dc50b017cbe)

I'm using another study which you can find here, but I'm not able to load it in v2 either

https://www.dropbox.com/t/eEseMevPSwqJLsDt

**Comment by igoroctaviano** [comment]
@sedghi I just uploaded another zip with the seg file to that drive.

**Comment by igoroctaviano** [comment]
@sedghithe #3577 fix was tested using zip I uploaded or other dataset?

**Comment by rodrigobasilio2022** [comment]
It seems to be fixed as stated in the title: old v3 version (~33s) new v3 version (~11s). I couldnt open the cited study in v2 as it gives the following error

![image](https://github.com/OHIF/Viewers/assets/114958722/8824827d-430e-4456-ae70-af39820c017b)

**Comment by rodrigobasilio2022** [comment]
@fedorov do you have another TotalSegmentator studies to test, to tru to understand if this is an isolated problem?

**Comment by rodrigobasilio2022** [comment]
Using the link: https://viewer.imaging.datacommons.cancer.gov/viewer/61.7.186150680759207515465616855509993541745
The study opens in v2, but the comparison is bogus as the segmentation in IDC only has 13 segments while the segmentation in google drive has 98 segments. Also in v2, despite the segmentation appears to load fast the user cannot manipulate the image as it is loading the main series images

**Comment by rodrigobasilio2022** [comment]
@fedorov, do you want to investigate why v2 didnt load the full segmentation?

**Comment by fedorov** [comment]
The study in IDC contains only the segmentation that was loaded. It does not have the same segmentation with 98 segments shared separately.

**Comment by rodrigobasilio2022** [comment]
The file shared with Ali Reza has it. Anyway, problem seems to be solved.

**Comment by fedorov** [comment]
To confirm, tests O16 and O19 in the [IDC test inventory](https://docs.google.com/spreadsheets/d/12n1AWUynEFPatmNUphyW9IhOHaePN2jNUrzzjLunJtg/edit?usp=sharing) should be used to test this functionality.

**Comment by fedorov** [comment]
I confirmed performance is very good now, nice work @rodrigobasilio2022! 👍
