### ISSUE TITLE
[Bug]: incorrect Application of Colormap in MIP View with Windowing

### ISSUE THREAD

**Issue by simonalo** [OHIF/Viewers#3526]
### Describe the Bug

When creating a colormap for a MIP view, the conversion from values to color are applied after a windowing. The rendering depends of the windowing.
Moreover, if the color map extremes points are bigger or lower than the real values (HU values for CT scan), the colormap is not applied correctly.

### Steps to Reproduce

1. Create a new colormap with extremes points out of the range of the HU values for a CT scan ;
2. Apply this colormap to a MIP view.

### The current behavior

The colormap should is applied to the CT scan after the windowing.

### The expected behavior

The colormap should be applied to the CT scan without the windowing.

### OS

Windows

### Node version

16.14

### Browser

Chrome 114.0.5735.199

**Comment by sedghi** [comment]
can you send screenshots of what you see and what you expect to see?
