### ISSUE TITLE
[Bug] RtStructs loads but does not show contour outline

### ISSUE THREAD

**Issue by JennyLeePMH** [OHIF/Viewers#3535]
### Describe the Bug

For some RtStruct, it loads into the basic viewer sucessfully, but the contours does not shows.  

Tested with OHIF version number: 3.7.0-beta.26

### Steps to Reproduce

1. Download this dataset, where password is provided seperately: https://fileshare.uhn.ca/download/fa0fd4c1-aa83-4223-845f-d68827f10c74 
3. Load any RtStruct from the dataset
4. Observe that contours loaded on the segmentation panel, but the contours are not shown in the image

### The current behavior

Contours are loaded, but contours are not shown.  See below:
![contour_does_not_show](https://github.com/OHIF/Viewers/assets/4551564/e6f228ad-0129-4fa6-afff-2e4bd109c88c)

### The expected behavior

Expects a red contour to show in image.

### OS

Windows 10

### Node version

v16.17.0

### Browser

Chrome Version 114.0.5735.110

**Comment by james-hanks** [comment]
Will be fixed future PR from industry collaboration. Estimated timeline 4-5 months

**Comment by fedorov** [comment]
@james-hanks could you elaborate why this issue is happening, and what you believe is triggering it? Since it sounds like you know the answer to this question, based on your earlier comment.

**Comment by sedghi** [comment]
Since we are currently rendering contours seems like some floating point difference in the contour location vs slice location make them appear behind. 
The correct solution is what 3D Slicer does which is convert contour to surfaces and cut through surface that we are pursing now with convertors 

https://bitbucket.org/icrimaginginformatics/polyseg-wasm/src/master/

**Comment by sedghi** [comment]
We will tack it here https://github.com/OHIF/Viewers/issues/3651

**Comment by 03shek** [comment]
@sedghi Circling back after testing the latest fix from cornerstonejs... I'm still not seeing visible outlines for some cases.

Tested via https://viewer.ohif.org/local
Version number
3.7.0
Commit Hash
5ddf8a16027255d28dc01c1740099cf85bbcf458
Browser
Chrome 119.0.0
OS
Windows 10

You had noted above that,
> some floating point difference in the contour location vs slice location make them appear behind.

Any chance this was a misdiagnosis? I'm not sure I'm seeing the floating point issue... in fact, the slice location is ways away from the Image Position Patient IPP number (not close to rounding range). 

![image](https://github.com/OHIF/Viewers/assets/115667958/53c92719-c5d3-4281-a04a-35810d2cab46)

![image](https://github.com/OHIF/Viewers/assets/115667958/4f41fce8-c9f4-4c50-8dd0-78c7448fa815)

The contour points seem to reflect the IPP values too...
![image](https://github.com/OHIF/Viewers/assets/115667958/78ffc170-2c43-46bc-8e75-eda91d24cb4f)

Thanks!

**Comment by sedghi** [comment]
Hey Tina,
We are re-working this completely to not rely on contour and reconstruct the surface out of them for rendering. Stay tuned.
