### ISSUE TITLE
[Bug] RtStruct is currently displayed on a series with different FoR

### ISSUE THREAD

**Issue by JennyLeePMH** [OHIF/Viewers#3537]
### Describe the Bug

Consider an imaging study, where the patient has to be re-position during the scan.  This could be due to image-guided intervention, for example.  Then, there will be multiple frame of references (FoR) in the study.  Unless image registration is applied, only images and RtStruct of the same FoR should be fused on the same viewport.   However, there is a bug where RtStruct is shown on series of different FoR.  

Tested on OHIF version number:  3.7.0-beta.26     

### Steps to Reproduce

1. Download the sample dataset.  Password will provide separately.   Please note that this file upload will expire in 30 days. 
https://fileshare.uhn.ca/download/4b91d4da-100b-4c8a-9202-5f91c4cc63a1 

![image](https://github.com/OHIF/Viewers/assets/4551564/cadbbbbf-3cc3-4c38-b4df-1a8f94a8d7d8)

### The current behavior

![FOR_explain_2](https://github.com/OHIF/Viewers/assets/4551564/0640b5a5-59f3-4f59-962e-96c0a6ed86ce)

### The expected behavior

Primary objective: RtStruct should not be displayed on any series with different FoR.  

Secondary objective: If you look into RtStruct's metadata, it should state the study and series uid where the contour was drawn on.   Thus, these contours should be displayed on its originating series, and we should also be able to display them on any series with same FoR.   

### OS

Windows 10

### Node version

v16.17.0

### Browser

Chrome Version 114.0.5735.110

**Comment by JennyLeePMH** [comment]
https://fileshare.uhn.ca/download/b2d62cee-8b26-4701-bba5-99544d6d72be
password: density
@sedghi, I have zipped up the dicoms.  Please try again.

**Comment by 03shek** [comment]
@sedghi 

Version number 3.7.0
Commit Hash 5ddf8a16027255d28dc01c1740099cf85bbcf458
Browser Chrome 117.0.0
OS Windows 10

https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.2.840.113619.2.290.3.3767434740.226.1600859119.501

- All series in this study have 47 images, except for the CT Std with 76 images.
- Change viewport grid to 2x2
- Load the RTSTRUCT onto the AC192 PET viewport (bottom left)

I can see the CT Std viewport try to populate the RTSTRUCT, but it doesn't ultimately succeed.
![image](https://github.com/OHIF/Viewers/assets/115667958/2d522651-b1f3-409d-8824-7f1dd1b21ab6)

![image](https://github.com/OHIF/Viewers/assets/115667958/dd8b10d9-d364-4bc9-b25a-99a564447e5f)

**Comment by jenny-hm-lee** [comment]
The latest behavior of this bug is reported in #3909
