### ISSUE TITLE
[Feature Request] Fallback page for study/series/instance not found and invalid url

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3541]
### What feature or change would you like to see made?

Display a splash screen with information about the study, series, or instance not found depending on the query params used and which was not found.

Cases:
- Study not found
- Series not found (just show a notification tooltip?)
- Instance not found (just show a notification tooltip?)
- Page not found 

### With loading spinner enabled: displays 404 in the console + infinite loading 
<img width="1529" alt="Screenshot 2023-07-17 at 13 50 07" src="https://github.com/OHIF/Viewers/assets/13886933/498949b7-b2a5-45a7-8148-2421de8182f3">

### Loading spinner disabled: displays 'no mrn found' + blank screen
<img width="1534" alt="Screenshot 2023-07-17 at 13 48 41" src="https://github.com/OHIF/Viewers/assets/13886933/264cc8f1-e3bf-4f0c-b7de-d570cbb0fff6">

### Why should we prioritize this feature?

It's not clear what happened trying to load using an invalid URL.

**Comment by rodrigobasilio2022** [comment]
PR  merged. Will be integrated to IDC in the next update.
