### ISSUE TITLE
[Bug] instance.PhotometricInterpretation : MONOCHROME2

### ISSUE THREAD

**Issue by leety-radisen** [OHIF/Viewers#3544]
### Describe the Bug

if "instance. PhotometricInterpretation : MONOCHROME2" , the image is invisible.

{
  _vrMap: {
    PixelData: "UN",
  },
  PresentationLUTShape: "IDENTITY",
  SpecificCharacterSet: "ISO_IR 192",
  ImageType: [
    "ORIGINAL",
    "PRIMARY",
  ],
  SOPClassUID: "1.2.840.10008.5.1.4.1.1.1.1",
  SOPInstanceUID: "1.2.840.114257.3.6.5.1629699669.11.20210823150429",
  StudyDate: "20210823",
  SeriesDate: "20210823",
  AcquisitionDate: "20210823",
  StudyTime: "150252.000000",
  SeriesTime: "150429.000000",
  AcquisitionTime: "150429.000000",
  AccessionNumber: "20210823150252",
  Modality: "DX",
  PresentationIntentType: "FOR PRESENTATION",
  Manufacturer: "PedraView",
  InstitutionName: null,
  ReferringPhysicianName: null,
  StudyDescription: "****",
  SeriesDescription: "UPPER EXTREMITY",
  PerformingPhysicianName: null,
  NameOfPhysiciansReadingStudy: null,
  OperatorsName: [
    {
      Alphabetic: "admin",
    },
  ],
  ManufacturerModelName: "DXD",
  AnatomicRegionSequence: [
    {
      _vrMap: {
      },
      CodeMeaning: null,
    },
  ],
  "00090002": {
    InlineBinary: "W3siYzAueCI6MTM5Ni4yMDIyOTg4NTA1NzQ2LCJjMC55IjoxMDU5LjQyOTg4NTA1NzQ3MTIsInRleHQiOiJMIiwidHlwZSI6Im1hcmtlciJ9XQ==",
  },
  "00090010": "M",
  "00090020": "{\n    \".Version\": \"1.0.15.1\",\n    \"Background\": false,\n    \"BackgroundCollimator\": 0,\n    \"BackgroundWeight\": 100,\n    \"Clip\": true,\n    \"ClipPixels\": 10,\n    \"FixWindow\": false,\n    \"FixWindowCenter\": 33104,\n    \"FixWindowWidth\": 24335,\n    \"Gradation\": false,\n    \"GradationContrast\": 0,\n    \"GradationWeight\": 100,\n    \"GradationWhite\": 100,\n    \"Grid\": true,\n    \"GridWeight\": 1,\n    \"Noise\": true,\n    \"NoiseWeight\": 74,\n    \"Sharpening\": true,\n    \"SharpeningWeight\": 1,\n    \"Smoothing\": true,\n    \"SmoothingWeight\": 0,\n    \"Tissue\": true,\n    \"TissueDetail\": 40,\n    \"TissueFine\": 38,\n    \"TissueStructure\": 33,\n    \"TissueUltra\": 0,\n    \"TissueVolume\": 21\n}",
  PatientName: [
    {
      Alphabetic: "****",
    },
  ],
  PatientID: "3733-1",
  IssuerOfPatientID: "DCM4CHEE.031986EB.07076CCB",
  PatientBirthDate: "19590120",
  PatientSex: "Male",
  PatientAge: "000Y",
  PatientSize: "0",
  PatientWeight: "0",
  AdditionalPatientHistory: null,
  PatientComments: null,
  BodyPartExamined: "WRIST",
  KVP: "52",
  SoftwareVersions: "DDDDDD",
  ExposureTime: "40",
  XRayTubeCurrent: "125",
  ImagerPixelSpacing: [
    "0.14",
    "0.14",
  ],
  ExposureIndex: "0",
  TargetExposureIndex: "5000",
  DeviationIndex: "0",
  ShutterShape: "RECTANGULAR",
  ShutterLeftVerticalEdge: "209",
  ShutterRightVerticalEdge: "2386",
  ShutterUpperHorizontalEdge: "686",
  ShutterLowerHorizontalEdge: "2500",
  ShutterPresentationValue: 0,
  PatientPosition: "AP",
  DetectorType: "SCINTILLATOR",
  ExposureInmAs: 5,
  StudyInstanceUID: "1.2.840.114257.3.6.5.20210823150342",
  SeriesInstanceUID: "1.2.840.114257.3.6.5.1629699669.20210823150429",
  StudyID: null,
  SeriesNumber: "1629699669",
  InstanceNumber: "1629698670",
  ImageLaterality: null,
  SamplesPerPixel: 1,
  PhotometricInterpretation: "MONOCHROME2",
  NumberOfFrames: "1",
  Rows: 3052,
  Columns: 3052,
  PixelSpacing: [
    "0.14",
    "0.14",
  ],
  PixelAspectRatio: null,
  BitsAllocated: 16,
  BitsStored: 16,
  HighBit: 15,
  PixelRepresentation: 0,
  PixelPaddingRangeLimit: null,
  BurnedInAnnotation: "NO",
  PixelIntensityRelationship: null,
  PixelIntensityRelationshipSign: null,
  WindowCenter: "20400",
  WindowWidth: "38127",
  RescaleIntercept: null,
  RescaleSlope: null,
  RescaleType: null,
  WindowCenterWidthExplanation: null,
  VOILUTFunction: null,
  RedPaletteColorLookupTableDescriptor: null,
  GreenPaletteColorLookupTableDescriptor: null,
  BluePaletteColorLookupTableDescriptor: null,
  RedPaletteColorLookupTableData: null,
  GreenPaletteColorLookupTableData: null,
  BluePaletteColorLookupTableData: null,
  ICCProfile: null,
  LossyImageCompression: "00",
  VOILUTSequence: [
    {
      _vrMap: {
      },
      LUTDescriptor: null,
      LUTExplanation: null,
      LUTData: null,
    },
  ],
  PixelDataProviderURL: null,
  PatientInstitutionResidence: null,
  ScheduledProcedureStepStartDate: "20210823",
  ScheduledProcedureStepStartTime: "150252.000000",
  AcquisitionContextSequence: [
    {
      _vrMap: {
      },
      ConceptNameCodeSequence: [
        {
          _vrMap: {
          },
          CodeMeaning: null,
        },
      ],
    },
  ],
  RequestedProcedureID: "-",
  RequestedProcedurePriority: null,
  ImageHorizontalFlip: "N",
  ImageRotation: 90,
  PixelData: {
    BulkDataURI: "http://****",
    retrieveBulkData: () => {
      // handle the scenarios where bulkDataURI is relative path
      (0,_utils_fixBulkDataURI__WEBPACK_IMPORTED_MODULE_9__.fixBulkDataURI)(value, naturalized, dicomWebConfig);
      const options = {
        // The bulkdata fetches work with either multipart or
        // singlepart, so set multipart to false to let the server
        // decide which type to respond with.
        multipart: false,
        BulkDataURI: value.BulkDataURI,
        // The study instance UID is required if the bulkdata uri
        // is relative - that isn't disallowed by DICOMweb, but
        // isn't well specified in the standard, but is needed in
        // any implementation that stores static copies of the metadata
        StudyInstanceUID: naturalized.StudyInstanceUID
      };
      // Todo: this needs to be from wado dicom web client
      return qidoDicomWebClient.retrieveBulkData(options).then(val => {
        // There are DICOM PDF cases where the first ArrayBuffer in the array is
        // the bulk data and DICOM video cases where the second ArrayBuffer is
        // the bulk data. Here we play it safe and do a find.
        const ret = val instanceof Array && val.find(arrayBuffer => arrayBuffer?.byteLength) || undefined;
        value.Value = ret;
        return ret;
      });
    },
  },
  wadoRoot: "http://****",
  wadoUri: undefined,
  imageId: "wadors:http://****",
}

### Steps to Reproduce

.

### The current behavior

.

### The expected behavior

.

### OS

Windows 11

### Node version

.

### Browser

.

**Comment by leety-radisentech-com** [comment]
It's not a MONOCHROME2 problem.
Other MONOCHROME2 images look fine.

**Comment by leety-radisentech-com** [comment]
The image has been modified to display.
I hope someone will merge this into git.
MetadataProvider.js _getCornerstoneDICOMImageLoaderTag()
      case WADO_IMAGE_LOADER_TAGS.MODALITY_LUT_MODULE:
        const { RescaleIntercept, RescaleSlope } = instance;
        if (
          RescaleIntercept === undefined ||
          RescaleSlope === undefined ||
          RescaleIntercept === null ||
          RescaleSlope === null
        ) {
          return;
        }

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
