### ISSUE TITLE
New layout per image 

### ISSUE THREAD

**Issue by fmotta1968** [OHIF/Viewers#3545]
### What feature or change would you like to see made?

Currently the viewer only displays layout by series. 

MRI doctors, for example, prefer to view all the images in the series, not one by one. 

### Why should we prioritize this feature?

This functionality is used in several dicom viewer market and mr doctors.

**Comment by fmotta1968** [comment]
> can you share some videos of what other viewers have done?

Hi, yes, I will send to you tomorrow.

Do you know C++?

thinking about how to convert my post-processing workstation to OHIF. I'm thinking Vessel mode.

**Comment by sedghi** [comment]
I'm not following up on your request, can you elaborate more?

**Comment by fmotta1968** [comment]
Hi,  See this snapshot I can select the layout of images within the series I selected. In MRI exams, it is more important to view images than series at times. Make sense for you ?Rgds,Enviado do meu iPhoneEm 13 de out. de 2023, à(s) 16:07, Alireza ***@***.***> escreveu:﻿
I'm not following up on your request, can you elaborate more?

**Comment by sedghi** [comment]
I think you missed putting the snapshot

**Comment by fmotta1968** [comment]
No, i put a jpg image.Enviado do meu iPhoneEm 16 de out. de 2023, à(s) 12:11, Alireza ***@***.***> escreveu:﻿
I think you missed putting the snapshot

**Comment by sedghi** [comment]
I cannot see this at the moment. I will close it for now, but please reopen the issue once you have additional information.
