### ISSUE TITLE
[Feature Request] DICOM SEG export 

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3550]
### What feature or change would you like to see made?

DICOM SEG is a standard for storing segmentation data in DICOM images. It is used to represent the boundaries of different structures in an image, such as organs or tumors.

In v2 we used dcmjs/adapters for exporting DICOM SEG data. However, this adapter only supported exporting SEG data for wadouri, and not wadors.

In v3, the loading of segmentation data is considerably slower than in v2. For example, the totalSegmenter case, which is a 400 MB full-body SEG, takes 1 minute to load in v3, but only 20 seconds to load in v2.

### Why should we prioritize this feature?

Improved performance and adaptability

**Comment by fedorov** [comment]
How is this related/different from #3523?

Also, the title says "DICOM SEG export", but the description talks about performance of import, not export.
