### ISSUE TITLE
[Feature Request] Brush Tool UI

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3551]
### What feature or change would you like to see made?

There is currently no segmentation brush UI in OHIF. This makes it difficult to control the brush size, color, and mode. 

The new segmentation brush UI should have the following features:

- Controllable brush size: The brush size should be adjustable in the brush UI.
- Controllable brush color: The brush color should be adjustable in the brush UI.
- Threshold mode: The brush should have a threshold mode, which allows users to draw only pixels that are above or below a certain threshold value.
- Eraser mode
- Sphere draw mode

Ideally there should be another tool for scissors

- Controllable scissor color
- Controllable scissor shape

Here are some initial designs

![image](https://github.com/OHIF/Viewers/assets/7490180/dd04395c-0b95-4a38-b2a9-d43abf7b7e6a)

### Why should we prioritize this feature?

Segmentation Mode

**Comment by james-hanks** [comment]
Design discussed 7/19 @dan-rukas to add wireframe

**Comment by dan-rukas** [comment]
Hi everyone,

Attached here is the full panel design. This includes new components listed below:

- Panel overview (overall layout of all components
- Updated panel tab design 
- Panel section component
- Panel section: Segmentation tools (with tool options)
- Panel section: Segmentations (with options edit/view)
- Segment row component
- Form inputs, buttons, etc.



![Image](https://github.com/OHIF/Viewers/assets/2745168/d40c0caa-2e6c-4003-a0ad-ef2d77b97146)

![Image](https://github.com/OHIF/Viewers/assets/2745168/c64b0134-614c-40bf-9e40-0d70feba3190)

![Image](https://github.com/OHIF/Viewers/assets/2745168/4d9d60d1-d442-47a7-a581-188bb7f3d6f7)

![Image](https://github.com/OHIF/Viewers/assets/2745168/4787018e-3b22-4b12-98cd-b8d36f8382d4)

![Image](https://github.com/OHIF/Viewers/assets/2745168/797e80e8-bcf2-4761-a602-7bc991add96c)

![Image](https://github.com/OHIF/Viewers/assets/2745168/e9c8c542-8d17-4d8b-aee8-676155eea607)

**Comment by james-hanks** [comment]
@sedghi add PR

**Comment by sedghi** [comment]
https://github.com/OHIF/Viewers/pull/3632
