### ISSUE TITLE
[Feature Request] Segmentation Brush Integration inside OHIF

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3552]
### What feature or change would you like to see made?

The current segmentation panel in OHIF has two hidden functionalities: Add New Segmentation and Add New Segment. These functionalities should be enabled so that users can easily create new segmentations and segments.

Proposal:

The Add New Segmentation and Add New Segment functionalities should be enabled by default in the Segmentation mode. 

Additional Notes:

- The Add New Segmentation functionality should allow users to create a new segmentation from scratch.
- The Add New Segment functionality should allow users to add a new segment to an existing segmentation.
- The viewport should be converted to a volume viewport when the Add New Segmentation or Add New Segment functionalities are triggered. This is because all segmentations in cornerstone3D are 3D volumes, and there is no support for stack segmentation yet.

### Why should we prioritize this feature?

Segmentation Mode

**Comment by james-hanks** [comment]
@dan-rukas to add design

**Comment by sedghi** [comment]
https://github.com/OHIF/Viewers/pull/3632
