### ISSUE TITLE
[Bug] show() NOT IMPLEMENTED

### ISSUE THREAD

**Issue by leety-radisentech-com** [OHIF/Viewers#3557]
### Describe the Bug

version 3.6.0

It's fine in vscode debug mode.
But when I upload it to the server, the developer tools (F12) shows a warning message "show() NOT IMPLEMENTED" and the screen goes black.
And on the browser screen "Cross Origin Isolation
Cross Origin Isolation is not enabled. Volume rendering is not working (e.g. MPR)" message is displayed.

![image](https://github.com/OHIF/Viewers/assets/127184274/e06c623f-f756-445b-8e4e-d10eafc80ac1)

### Steps to Reproduce

.

### The current behavior

.

### The expected behavior

.

### OS

Windows 11

### Node version

.

### Browser

chrome 114.0.5735.248

**Comment by nicoesiea** [comment]
I confirm, I get the same issue
