### ISSUE TITLE
MR viewer issue on scroll over the first series

### ISSUE THREAD

**Issue by narbek-abd** [OHIF/Viewers#3559]
### Describe the Bug

Here is anonymized version of the MR study:
[c3c2e158-e6e7aa76-3808599c-39b437ff-0131a8da.zip](https://github.com/OHIF/Viewers/files/12145071/c3c2e158-e6e7aa76-3808599c-39b437ff-0131a8da.zip)

When you scroll over the first series on the viewer, it gets brighter for some reason
![image](https://github.com/OHIF/Viewers/assets/59279794/ff63c2be-441a-457b-9319-314c586143b9)

### Steps to Reproduce

1. Clone the last version of OHIF
2. Upload the study into the Orthanc f.e
3. Open it on the viewer
4. scroll over the first series

### The current behavior

it gets brighter

### The expected behavior

normal

### OS

every

### Node version

every

### Browser

every

**Comment by sedghi** [comment]
I can't reproduce this on latest master, please re-open if the issue persists

https://github.com/OHIF/Viewers/assets/7490180/db157d2c-ce3f-4acc-b624-23ac9dd30b69
