### ISSUE TITLE
Non-source code minifed js.

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#356]
I'm wondering why there is a minified file in the repository. https://github.com/OHIF/Viewers/blob/master/Packages/ohif-cornerstone/public/js/cornerstoneWADOImageLoaderWebWorker.es5.js

I though these weren't supposed to be in a repository. They are more of a compiled build artifact. Furthermore, they seem to be from another project.

Thank you.

**Comment by dannyrb** [comment]
You're right. These files _should_ be copied from the corresponding package in a pre-build non script. They're needed to setup the web workers that decode DICOM images. They shouldn't be checked in to source control.

The hope is that in future versions that these same files are handled with webpack's worker-loader to clean things up a little more.

**Comment by swederik** [comment]
Closing because we are now using cornerstoneWADOImageLoader 3.0.0 which does not need these files to be included anymore:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/releases/tag/3.0.0
