### ISSUE TITLE
[Feature Request] Control toolbar states on hanging protocol change

### ISSUE THREAD

**Issue by m00n620** [OHIF/Viewers#3565]
### What feature or change would you like to see made?

It would be great if we can control the toolbar states(disabling all tools, making some tools deactivated).

### Why should we prioritize this feature?

It can fix some existing bugs on switching hanging protocols, and provide better UX.

**Comment by sedghi** [comment]
We have a PR for this but we are near the release, we will include it in the next version https://github.com/OHIF/Viewers/pull/3608

**Comment by sedghi** [comment]
I will close this since it is in PR and we will merge it
