### ISSUE TITLE
[Feature Request] Custom worklist URL

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3569]
### Request
- Allow customization of worklist url so we add GCP worklist support to load all studies from a dicom store e.g. http://localhost:3000/projects/your-project/locations/us/datasets/your-dataset/dicomStores/test-store

Currently, it's possible to load a study/series from a dicom store using dynamic dicomweb config e.g.
http://localhost:3000/projects/your-project/locations/us/datasets/your-dataset/dicomStores/test-store/study/123

### Why should we prioritize this feature?

Allow customization of the worklist URL or an easy way to access the worklist component to be used from the customization /configuration service.

**Comment by igoroctaviano** [comment]
@sedghi what do you think?

**Comment by sedghi** [comment]
I don't understand the feature request. Can you add more details please?

**Comment by igoroctaviano** [comment]
> I don't understand the feature request. Can you add more use case details please?

When I go to **http://localhost:3000/projects/your-project/locations/us/datasets/your-dataset/dicomStores/test-store**
(a specific gcp dicom store) I want to display the worklist with a different dataSource (gcp).

Currently, I can use **http://localhost:3000/projects/your-project/locations/us/datasets/your-dataset/dicomStores/test-store/study/123** and open a specific study but for that, I had to create a copy of the longitudinal mode and then update the routeName to **/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/dicomWeb**. (btw I wish we had a way to define [multiple routes](https://github.com/OHIF/Viewers/issues/3570) for a given mode so I don't have to make copies of existing ones)

Now if the user opens **http://localhost:3000/projects/your-project/locations/us/datasets/your-dataset/dicomStores/test-store** (just a dicom store) then I want to render the worklist with the gcp dataSource activated.

I tried to do the following using the customization module but I had to export the worklist through the app namespace. Maybe we could move it to UI/make it reusable by other modes or maybe we can allow multiple routes for the worklist?
```
import AddGoogleDataSourceComponent from './components/AddGoogleDataSourceComponent';
import { WorkList }  from '@ohif/app';
import getDataSourceWrapper from './components/GCPDataSourceWrapper';

function getCustomizationModule({ servicesManager, extensionManager }) {

function getCustomizationModule() {
  return [
    {
      name: 'gcpWorklist',
      value: {
        id: 'customRoutes',
        routes: [
          {
            path: '/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore',
            children: getDataSourceWrapper({ extensionManager }),
            private: true,
            props: {
              children: WorkList,
              servicesManager,
              extensionManager
            },
          },
        ],
      },
    },
```

**Comment by sedghi** [comment]
@igoroctaviano is this valid anymore?

**Comment by igoroctaviano** [comment]
> @igoroctaviano is this valid anymore?

Well, I'm still curious if I could have more than one worklist e.g. one for GCP data source and another one for a different data source. Right now I can use the defaultDataSource but its one data source or the other.

**Comment by sedghi** [comment]
Doesn't changing of the active data source show the related worklist?

**Comment by igoroctaviano** [comment]
> Doesn't changing of the active data source show the related worklist?

I mean without having to use the URL to select a particular data source. Or there's other way?

**Comment by sedghi** [comment]
I don't get it. I thought you wanted to have access to different worklists from various data sources. Maybe I'm not getting the original restriction.
