### ISSUE TITLE
Network optimization: Requesting that the PACS server use lossy JPEG compression. 

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#357]
Here is what I have tried, I have fiddled with the code at https://github.com/OHIF/Viewers/blob/master/Packages/ohif-studies/imports/both/services/wado/retrieveMetadata.js :

```
    params.push('requestType=WADO');
    params.push(`studyUID=${studyInstanceUid}`);
    params.push(`seriesUID=${seriesInstanceUid}`);
    params.push(`objectUID=${sopInstanceUid}`);
    params.push('contentType=application/dicom');
    params.push('transferSyntax=*');
```

Specifying the Transfer Syntax to 1.2.840.10008.1.2.4.50 according to https://www.dicomlibrary.com/dicom/transfer-syntax/

Doesn't cause the PACS server (Orthanc)  to compress the image. The only way to receive a compressed image is to remove the contentType. However this causes one to receive an unrenderable compressed JPEG rather than a renderable compressed JPEG in a dicom envelope.

What I am trying to do is simply the equivalent of runing dcmcjpeg using transfer syntax process 1 before sending the image.

**Comment by dannyrb** [comment]
Are you able to hit Orthanc with a request from postman, or something similar, and get the result you expect from it? How does the request compare to what is being sent from OHIF?

If you can identify the differences, I should be able to help you adjust the OHIF request to match your known good request.

**Comment by dannyrb** [comment]
I'm going to close this for now, but if you can provide more guidance around how to achieve this with a web request, or docs for the specific pacs (or in the dicomWeb spec), then I would be more than happy to reopen.

**Comment by dannyrb** [comment]
@TZubiri, a colleague recently pointed me toward this change that accomplishes what you're attempting:

https://github.com/crowds-cure/cancer/pull/24/files

It's for a different syntax, but it should be a good starting point. Best of luck ^_^

**Comment by TZubiri** [comment]
Thanks for the attention Danny. I'll be circling back to this issue soon. I'll take a look at the link you posted, and update the results here. If I still can't get it to work, I'll post the details you requested.

Regards.
