### ISSUE TITLE
[Feature Request] Multiple mode routes with its default data source

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3570]
### What feature or change would you like to see made?

Allow users to define multiple routes per mode and a default data source per route. 

Related IDC issues: #3569 #3361 

**Example 1:**
```
function modeFactory() {
  let _activatePanelTriggersSubscriptions = [];
  return {
    // TODO: We're using this as a route segment
    // We should not be.
    id,
    routeNames: [
      /** Default route */
      'longitudinal',
      /** GCP route */
      'projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs', 
      /** Invoke Image Display e.g. /study?requestType=STUDY&studyUID=123 */
      '/study'
    ]
```

**Example 2:**
```
routeNames: [
  {
      url: '/viewer',
      defaultDataSource: 'dicomweb'
  },
    {
      url: 'projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs',
      defaultDataSource: 'gcp'
  }
]
```

### Why should we prioritize this feature?

This allows accessing the same mode using different URLs with different default data sources e.g. open longitudinal mode with a GCP route with a gcp dicomweb as a default data source or an invoke image display route with the default dicomweb datasource or just using the default /longitudinal route with the global default data source.
This way the user doesn't need to create copies of the same longitudinal mode just to allow access to that mode using different routes.

**Comment by igoroctaviano** [comment]
@sedghi what do you think?

**Comment by sedghi** [comment]
@wayfarer3130

**Comment by igoroctaviano** [comment]
> @wayfarer3130

@wayfarer3130 @sedghi The ideal scenario would be something like this:
```
routeNames: [
  {
      url: '/viewer',
      defaultDataSource: 'dicomweb'
  },
    {
      url: 'projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs',
      defaultDataSource: 'gcp'
  }
]
```

This way we can use the longitudinal mode with different routes and I can define a default data source per route. That is quite useful if I want to use a GCP URL to open the longitudinal mode with the GCP data source. I think it is also useful for invoke image display.

**Comment by sedghi** [comment]
@igoroctaviano @fedorov Do you want to pursue this?

**Comment by igoroctaviano** [comment]
> @igoroctaviano @fedorov Do you want to pursue this?

@sedghi For now we got around this by creating multiple copies of the same mode so it's accessible by different URLs. Feel free to close the ticket if there's not much value in having multiple routes per mode.
