### ISSUE TITLE
Discrepancy in Version between npm and GitHub - OHIF/viewer

### ISSUE THREAD

**Issue by nicoesiea** [OHIF/Viewers#3572]
### Describe the Bug

I noticed a discrepancy in the version of the OHIF/viewer library between the npm package and the GitHub repository. 

The npm package shows version 4.12.51 (available at https://www.npmjs.com/package/@ohif/viewer?activeTab=versions), whereas the GitHub repository (https://github.com/OHIF/Viewers/tree/v3.6.0) has a stable tag of version 3.6.0 released 2 months ago. 

This inconsistency may cause confusion for users and prevent them from accessing the latest features or bug fixes.

### Steps to Reproduce

1. Visit the npm page for OHIF/viewer: https://www.npmjs.com/package/@ohif/viewer?activeTab=versions
2. Note the listed versions, with the latest being 4.12.51 (4 months ago)
3. Go to the GitHub repository for OHIF/Viewers: https://github.com/OHIF/Viewers/tree/v3.6.0
4. Observe the tags and releases, finding a stable version 3.6.0 released 2 months ago.

### The current behavior

As of now, users who rely on npm to install the OHIF/viewer library might not be aware that a newer stable version (3.6.0) is available on GitHub. 
This can lead to discrepancies in the functionalities and features available to different users, depending on the version they have installed.

### The expected behavior

Ideally, both the npm package and the GitHub repository should be aligned and reflect the same version (4.12.51 or 3.6.0) to avoid confusion among users. 
The latest stable version available on GitHub should also be accessible through npm to ensure consistent and up-to-date functionality for all users.

### OS

Windows 10

### Node version

16.18.1

### Browser

Chrome

**Comment by nicoesiea** [comment]
According to @sedghi we should no more use this solution. I recommend removing/deleting the npm page and the related module

**Comment by sedghi** [comment]
exactly, also read more about versioning here 


Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
