### ISSUE TITLE
Cross Origin Isolation

### ISSUE THREAD

**Issue by nicoesiea** [OHIF/Viewers#3575]
### Describe the Bug

Hello everyone,
Today I'm updating my OHIF version to 3.6
I discovered there is now a way to specify the studyInstanceUID directly as a query parameter, and no more as a REST path value.
The viewer is well started, and when it opens during the start all the data are well reached.
I'm targeting the same *DICOM server as the one used by the demo* (https://d33do7qe4w26qo.cloudfront.net/dicomweb)

However, by encapsulated the viewer inside an **IFRAME** is a mess.
No files are loaded and I can see this warning message:
``Cross Origin Isolation``
``Cross Origin Isolation is not enabled, volume rendering will not work (e.g., MPR)``

I'm still on **development mode**
I'm starting the project via the command ``yarn run dev``
And I embed the content inside the iframe via:
<iframe *ngIf="url$ | async as url" [src]="url" width="100%" height="100%" allow="xr-spatial-tracking"></iframe>

Where the variable url looks like this: 
`http://localhost:3000/viewer?StudyInstanceUIDs=${study}&SeriesInstanceUID=${serie}`

In my browser console, I can see these errors:
![image](https://github.com/OHIF/Viewers/assets/4542315/5c716877-1e4b-42ad-b2cc-670425571f05)

I saw the documentation pages: 
https://docs.ohif.org/deployment/cors
https://docs.ohif.org/deployment/iframe/

But I do not understand what to change. As I'm using the development Server (via Webpack), as it is not the static build, I did not use the PUBLIC_URL nor the routerBasename.
I added the following config to the file \ohif\platform\app\.webpack\webpack.pwa.js:
``devServer: {
  headers: {
    "Cross-Origin-Resource-Policy": "same-site"
  }
}``
But it is still not working.
Can someone help me to understand what and how to do, please?
Regards,
Nicolas

### Steps to Reproduce

1. Get the latest 3.6 version source code
2. yarn install
3. yarn run dev
4. embed the OHIF application in an IFRAME
5. try to reach DICOM data and images from an external server (https://d33do7qe4w26qo.cloudfront.net/dicomweb)

### The current behavior

No data nor images are loaded
A warning message about the ``Cross Origin Isolation``
Error message in the console related to ``Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined``

### The expected behavior

Image and data are loaded, and MPR is working fine

### OS

Windows 10

### Node version

16.18.1

### Browser

Chrome

**Comment by abdou-chakhkhar** [comment]
I am facing the same issue but with a different case, I am running ohif with dcm4chee, and all the stuff is working locally but when building the project I am facing this issue
