### ISSUE TITLE
[Bug] v3 Stable is unable to show and render US multiframe dcm files using /local or dicomjson method.

### ISSUE THREAD

**Issue by efimfurman** [OHIF/Viewers#3583]
### Describe the Bug

Navigate to https://v3-demo.ohif.org/local
Load https://drive.google.com/file/d/1RKiT_m0hmtauRJA2PHmI7L_7T3A-Ntuy/view?usp=sharing which loads fine in: https://www.cornerstonejs.org/live-examples/local.html

OHIF viewer shows a blank screen. Similar steps can be taken using dicomjson with, the resulting screen displaying frame zero with no scrolling.

### Steps to Reproduce

1. Navigate to https://v3-demo.ohif.org/local
2. Load https://drive.google.com/file/d/1RKiT_m0hmtauRJA2PHmI7L_7T3A-Ntuy/view?usp=sharing
3. Note blank screen with no series or frame info.
4. Repeat the test with https://www.cornerstonejs.org/live-examples/local.html and note that images are being rendered correctly.
5. Repeat steps using dicomjson method with similar results.

### The current behavior

Blank screen

### The expected behavior

OHIF should show multiple series and allow the user to navigate between the frames. 

### OS

MacOS 

### Node version

16

### Browser

Chrome

**Comment by moonofmars** [comment]
I tried. It's ok.
