### ISSUE TITLE
Viewer does not display PET CT image if no patient weight is provided[Bug] 

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3587]
### Describe the Bug

When the OHIF viewer attempts to load a PET images which has either no patient weight or a patient weight of zero the image does not display in the main viewer panel.

### Steps to Reproduce

1) Download this phantom data set https://fileshare.uhn.ca/download/f74813e9-2522-4357-87e2-ad7115c7fb82 password "animal"
2) open it in basic viewer
3) drag series 401 into the main view panel

This test was done on our dev branch of the viewer but was confirmed by @jbocce it could be reproduced. (https://github.com/OHIF/Viewers/issues/3439#issuecomment-1671193859)

Repository URL
https://github.com/OHIF/Viewers/
Data Citation
https://github.com/OHIF/Viewers/blob/master/DATACITATION.md
Version number
3.7.0-beta.39
UHN Version
(7/27/2023, 8:17:33 PM)
Build number
0
Commit Hash
869b8ced0581904ebac1867ca302635a93129f02
Browser
Chrome 114.0.0
OS
Windows 10

### The current behavior

In this phantom image set (provided below) the units are "BQML" and patient weight is 0.

The automatic window level displayed shows values that appear to be in BQML but the image is blank.
When using the probe tool it appears to try and calculate in SUV.
![image](https://github.com/OHIF/Viewers/assets/112980389/00f51a9c-f8b8-4960-9b89-2d9f7cfd3b23)

When changing the window level to something more realistic for SUV (W 5 L 1) the image becomes grey.

![image](https://github.com/OHIF/Viewers/assets/112980389/96a002c8-a8d8-4587-8641-b66590757193)

### The expected behavior

The image should display in units of BQML on the screen as SUV can't be calculated without a patient weight.

### OS

Win 10 

### Node version

Not sure

### Browser

 Chrome 114.0.0

**Comment by BrandonDatUHN** [comment]
New upload as previous expired.
https://fileshare.uhn.ca/download/09b66cb1-d647-4f09-99fd-106ec1585474 password "haircut"
Please note that this file upload will expire in 30 days.

**Comment by jbocce** [comment]
FYI @sedghi and @BrandonDatUHN.

I have confirmed that this continues to be an issue despite the changes made for #3411. For #3411, the `PatientWeight` was completely missing from the DICOM, whereas in this case it is zero.

**Comment by jbocce** [comment]
This issue will be addressed by `@cornerstonejs/calculate-suv` [PR 19](https://github.com/cornerstonejs/calculate-suv/pull/19) and then a subsequent PR for OHIF to link the released `calculate-suv` library.

In summary, the change is to treat a zero `PatientWeight` as if it were missing.
