### ISSUE TITLE
Black spots in CT and MR studies

### ISSUE THREAD

**Issue by phpKahuna** [OHIF/Viewers#359]
This case was detected in OHIF Viewer on Meteor 1.7.0.5/Windows-x64. 
Studies are found without problems and shown in the list, using ORTHANC as PACS server. 
When displayed, CT and MR images show black areas and spots, mostly in bone tissue edges. Density values in the black zones are correct as compared to other DICOM viewers, but the visual effect is annoying for most users as they think that it's a case of over-exposition. 

![screencapture-localhost-8080-viewer-1-2-840-113619-2-332-3-2831164417-557-1518324296-512-2019-02-25-16_40_21 - copia - copia](https://user-images.githubusercontent.com/41792525/53426431-f5aa8380-39b4-11e9-8494-68ad41728d29.png)

In the past the getMinMax function was altered to handle correctly the actual pixel data, avoiding out-of-range or indefined values, using the STRICT mode. Is it there a quick fix for this situation, by the means of a setting/configuration?

**Comment by swederik** [comment]
I've removed the image because it looked like it contained PHI. Please do not post PHI.

I'll make a note to check this in Cornerstone Core and/or WADO Image Loader.

**Comment by phpKahuna** [comment]
The image was fixed. Thanks.

**Comment by phpKahuna** [comment]
Looks like there is an error in the WADO loader, regarding the WW/WC calculations in the MONOCHROME2 photometric interpretation, when it uses signed Int16 values. It doesn't happen when unsigned values are used. That's the case of most CT and MR studies stored in our PACS server.

**Comment by phpKahuna** [comment]
I've found the origin of the problem and it wasn't the viewer, but the PACS server. Old, unpatched versions of Orthanc have an error mixing MONOCROME1 and MONOCHROME2 photometric interpretation while it receives a study, saving images with incorrect pixel values. Other viewers just have workaround mechanisms to avoid the black (out of range) patches.
DICOM studies that were stored with this error must be sent again to correct them.
I provide two sample images, before the Orthanc upgrade and after it.

Before...
![Screenshot_2019-03-19 OHIF Viewer - Antes - Anon](https://user-images.githubusercontent.com/41792525/54611350-c66fbb00-4a24-11e9-9972-4f546fcb0007.png)

And after the Orthanc upgrade (same study, reloaded)...
![Screenshot_2019-03-19 OHIF Viewer - Después - Anon](https://user-images.githubusercontent.com/41792525/54611415-e4d5b680-4a24-11e9-9a13-1fb53ee6f187.png)

It would be handy to have a detection mechanism (some kind of warning, log message or JS console alert) for out-of-range pixel values.
