### ISSUE TITLE
[Bug] User preference hotkeys not reloaded from local storage

### ISSUE THREAD

**Issue by dmlambo** [OHIF/Viewers#3598]
### Describe the Bug

You can change hotkeys and save them, and they persist for the duration of the tab. However, on refresh (and likely on going from one Mode to another) the hotkeys get reset to default.

I think the problem is [here](https://github.com/OHIF/Viewers/blob/daf734e09e843f5474301124aab0429289436878/platform/app/src/routes/Mode/Mode.tsx#L173).

The change was good, insofar as if you add a hotkey object to a Mode, it will use the name member to set and retrieve the hotkeys. However, the default behaviour is to _write_ the hotkeys to 'hotkey-definitions', but read them from 'hotkey-definitions-v2'.

Fixed locally by changing above line to the expected 'hotkey-definitions'. 

@wayfarer3130 made the change, and may be able to add more context.

### Steps to Reproduce

1. Go to a [viewer](https://viewer.ohif.org/).
2. Open any BasicViewer.
3. Change a hotkey in Preferences.
4. Save.
5. Reload the page.
6. Note the hotkeys are back to defaults.

### The current behavior

No hotkeys are restored from LS.

### The expected behavior

User preference hotkeys are restored from LS.

### OS

Windows 10

### Node version

16.15.0-slim

### Browser

Chrome 115.0.5790.110

**Comment by sedghi** [comment]
Thanks for the report I can reproduce it
