### ISSUE TITLE
[Bug] Dicom overlay [6000,3000] not displayed in viewer V3

### ISSUE THREAD

**Issue by myoussef90** [OHIF/Viewers#3599]
### Describe the Bug

i was using OHIF V2 and was displaying dicom overlay fine, it get from meta file as inline binary string from tag [6000,3000] and parse it to get buffer array. now when switching to V3 with same meta file it dosn't display any overlay
How can i display it in V3 ?

<img width="954" alt="V2_DicomOverlay_" src="https://github.com/OHIF/Viewers/assets/99037947/7c767561-2513-40f3-a3ca-207c8141965e">

<img width="952" alt="V3_DicomOverlay" src="https://github.com/OHIF/Viewers/assets/99037947/87c24726-0f9a-4a8a-b1d3-d291829e07a5">

this is the dicom file 

[DicomOverlay.zip](https://github.com/OHIF/Viewers/files/12331299/DicomOverlay.zip)

### Steps to Reproduce

1- upload the dicom file 
2- compare between V2 and V3 displaed image

### The current behavior

Dicom Overlay dosn't display 

### The expected behavior

Dicom Overlay should display like V2 

### OS

Windows 11

### Node version

18

### Browser

Chrome

**Comment by sedghi** [comment]
This is fixed and merged in master

**Comment by whage** [comment]
@sedghi Are you sure this is part of master? We are using the `ohif/app:v3.7.0` docker image and I also tried it with `ohif/app:v3.8.0-beta.36` to see if the current latest has it but neither showed the overlay image. I tried with the sample data that @myoussef90 posted and also with some of our own. Is there maybe a configuration flag that has to be turned on for OHIF to show the overlay?

**Comment by whage** [comment]
Some more info (using the sample data provided by @myoussef90): in v3.7.0, even when I turn on the "Image Overlay" tool, nothing is displayed and there aren't any errors in the browser console.
In 3.8.0-beta.36 however, when the tool is turned on I noticed some errors about the overlay data:

![overlay_debugger_error](https://github.com/OHIF/Viewers/assets/2611101/4b2d80e6-0969-4ab6-adf5-7c566981f320)
![overlay_console_error](https://github.com/OHIF/Viewers/assets/2611101/8a59303c-89ac-4070-bd5d-e21ebfb54d26)

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by whage** [comment]
> Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

I reproduced it with the data posted by @myoussef90 in the original post above: https://github.com/OHIF/Viewers/files/12331299/DicomOverlay.zip

**Comment by sedghi** [comment]
I dragged and dropped and tried orthanc and it looks fine

![CleanShot 2024-01-09 at 10 15 43](https://github.com/OHIF/Viewers/assets/7490180/e569ae30-2979-47fc-9b06-42205106c657)

What are your steps

**Comment by whage** [comment]
Hm, I'm not  sure what "steps" I can provide. I have an Orthanc instance serving the data with quite a few customizations.
I suppose I'm missing some configuration in Orthanc or OHIF.
Is there a specific setting for the overlay tool to work? Anything required in the `dataSources` section of the OHIF config json maybe?
This is my `datasources` array in the config file:
```
dataSources: [
    {
      friendlyName: 'Orthanc',
      namespace: '@ohif/extension-default.dataSourcesModule.dicomweb',
      sourceName: 'dicomweb',
      configuration: {
        name: 'AE_RMCPACS',
        wadoUriRoot: '/pacs/wado',      // nginx should proxy it to the orthanc container
        qidoRoot:    '/pacs/dicom-web', // nginx should proxy it to the orthanc container
        wadoRoot:    '/pacs/dicom-web', // nginx should proxy it to the orthanc container
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        requestTransferSyntaxUID: '1.2.840.10008.1.2.4.70'
      },
    }
  ],
```
With no other ideas, I kept looking at the debugger while the image is being rendered and I noticed the following, maybe this could help find the cause:

![ohif-debugger-01_21](https://github.com/OHIF/Viewers/assets/2611101/743dd6d3-e914-4a2f-afed-c9d78e19f3fb)

What I'm trying to highlight is that as overlay data is being processed, at one point the code puts it into this `missingOverlay` array because `overlay.dataUrl` is not there. I'm wondering where that `dataUrl` should come from, maybe I have something turned off in Orthanc that should be served?
There is also this `pixelData.BulkDataURI` URL to which no request was sent. Why is there no request for the data?
I saw that it was @wayfarer3130 who committed the mentioned lines, maybe he could provide some info.

Any help is greatly appreciated!

**Comment by wayfarer3130** [comment]
Add in the ds configuraiton block:
bulkDataURI: {
          enabled: true,
},
That will setup a function callback to fetch the data.  Probably it should get enabled by default.

**Comment by jianghuaw** [comment]
I met the same issue while using dicomjson. But it works well with dicomlocal provider. They use different dicom parsers: cornerstonejs/dicomParser v.s. dcmjs. In csjs dicomParser, it seems not process the overlay data properly.

**Comment by jianghuaw** [comment]
> Add in the ds configuraiton block: bulkDataURI: { enabled: true, }, That will setup a function callback to fetch the data. Probably it should get enabled by default.

I may have a try with this proposal. Where should I put this setting? Seems not working with app-config.cfg?

**Comment by jianghuaw** [comment]
I confirm the bulkDataURI setting doesn't work for the dicomjson source data provider. Probably should some fix in cornerstonejs/dicomParser.

**Comment by whage** [comment]
> Add in the ds configuraiton block: bulkDataURI: { enabled: true, }, That will setup a function callback to fetch the data. Probably it should get enabled by default.

Wow, thanks a lot, this solved it!

**Comment by jianghuaw** [comment]
Andras, congrats!
 So the "bulkDataURI" is the resolution for Orthanc. Still need help on dicomjson at here:-) Thanks for any clue @wayfarer3130 @sedghi

**Comment by sedghi** [comment]
please take a look at the latest master and re-open this if still an issue
