### ISSUE TITLE
How to config with n AETitle

### ISSUE THREAD

**Issue by itcthienkhiem** [OHIF/Viewers#36]
Dear ad,
OHIF only working with 1 AETitle this mean only 1 file config to Server, so i can't change to config differences,
because my system required with n AETitle, i thing this is a new function can change aetitle (add,remove,update) and two paramater (wadoUriRoot,wadoRoot) don't in config.
"wadoUriRoot" : "http://192.168.201.46:1000/wado/CT",
"wadoRoot": "http://192.168.201.46:1000/wado/CT",
paramater:
CT -> user will change in interface 

{
"servers": {
"dicomWeb": [
{
"name": "ClearCanvas",
"wadoUriRootNOTE" : "either this uri is not correct for wado-uri or wado-uri is not configured on ClearCanvas currently",
"wadoUriRoot" : "http://192.168.201.46:1000/wado/ CT",
"qidoRoot": "http://192.168.201.46:1000",
"wadoRoot": "http://192.168.201.46:1000/wado/CT",
"qidoSupportsIncludeField": false,
"imageRendering" : "wadouri",
"requestOptions" : {
"auth": "none:none",
"logRequests" : false,
"logResponses" : false,
"logTiming" : false
}
}],
"dimse": [{
"name": "ClearCanvas",
"peers": [
{
"host" : "192.168.201.46",
"port" : 108,
"aeTitle" : "CT",
"default" : true,
"supportsInstanceRetrievalByStudyUid": false
},
{
"host" : "0.0.0.0",
"port" : 104,
"aeTitle" : "OHIFDCM",
"default" : true,
"server" : true
}
]
}]
},
"defaultServiceType": "dimse"
}

**Comment by swederik** [comment]
We are planning to add support for multiple DICOM servers but I don't have a timeline for this feature. I'll leave this open for now.
