### ISSUE TITLE
failed with the latest react

### ISSUE THREAD

**Issue by DavidMGT** [OHIF/Viewers#3603]
### Describe the Bug

when My project using  "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-bootsplash": "4.5.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",

it creashs

### Steps to Reproduce

Found: react@17.0.2
npm WARN node_modules/@ohif/ui/node_modules/react
npm WARN   peer react@"^0.14 || ^15.0.0 || ^16.0.0-alpha" from airbnb-prop-types@2.16.0
npm WARN   node_modules/@ohif/ui/node_modules/react-dates/node_modules/airbnb-prop-types
npm WARN     airbnb-prop-types@"^2.15.0" from react-dates@21.8.0
npm WARN     node_modules/@ohif/ui/node_modules/react-dates
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14 || ^15.5.4 || ^16.1.1" from react-dates@21.8.0
npm WARN node_modules/@ohif/ui/node_modules/react-dates
npm WARN   react-dates@"^21.8.0" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14 || ^15.5.4 || ^16.1.1" from react-dates@21.8.0
npm WARN   node_modules/@ohif/ui/node_modules/react-dates
npm WARN     react-dates@"^21.8.0" from @ohif/ui@3.6.0
npm WARN     node_modules/@ohif/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-dates@21.8.0
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/@ohif/ui/node_modules/react-dom
npm WARN   react-dom@"^17.0.2" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN     @ohif/ui@"*" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^0.14 || ^15.5.4 || ^16.1.1" from react-dates@21.8.0
npm WARN node_modules/@ohif/ui/node_modules/react-dates
npm WARN   react-dates@"^21.8.0" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN 
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^0.14 || ^15.5.4 || ^16.1.1" from react-dates@21.8.0
npm WARN   node_modules/@ohif/ui/node_modules/react-dates
npm WARN     react-dates@"^21.8.0" from @ohif/ui@3.6.0
npm WARN     node_modules/@ohif/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-modal@3.11.2
npm WARN Found: react@17.0.2
npm WARN node_modules/@ohif/ui/node_modules/react
npm WARN   peer react@"^0.14 || ^15.0.0 || ^16.0.0-alpha" from airbnb-prop-types@2.16.0
npm WARN   node_modules/@ohif/ui/node_modules/react-dates/node_modules/airbnb-prop-types
npm WARN     airbnb-prop-types@"^2.15.0" from react-dates@21.8.0
npm WARN     node_modules/@ohif/ui/node_modules/react-dates
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16" from react-modal@3.11.2
npm WARN node_modules/@ohif/ui/node_modules/react-modal
npm WARN   react-modal@"3.11.2" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0 || ^16" from react-modal@3.11.2
npm WARN   node_modules/@ohif/ui/node_modules/react-modal
npm WARN     react-modal@"3.11.2" from @ohif/ui@3.6.0
npm WARN     node_modules/@ohif/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-modal@3.11.2
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/@ohif/ui/node_modules/react-dom
npm WARN   react-dom@"^17.0.2" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN     @ohif/ui@"*" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^0.14.0 || ^15.0.0 || ^16" from react-modal@3.11.2
npm WARN node_modules/@ohif/ui/node_modules/react-modal
npm WARN   react-modal@"3.11.2" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN 
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^0.14.0 || ^15.0.0 || ^16" from react-modal@3.11.2
npm WARN   node_modules/@ohif/ui/node_modules/react-modal
npm WARN     react-modal@"3.11.2" from @ohif/ui@3.6.0
npm WARN     node_modules/@ohif/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-select@3.0.8
npm WARN Found: react@17.0.2
npm WARN node_modules/@ohif/ui/node_modules/react
npm WARN   peer react@"^0.14 || ^15.0.0 || ^16.0.0-alpha" from airbnb-prop-types@2.16.0
npm WARN   node_modules/@ohif/ui/node_modules/react-dates/node_modules/airbnb-prop-types
npm WARN     airbnb-prop-types@"^2.15.0" from react-dates@21.8.0
npm WARN     node_modules/@ohif/ui/node_modules/react-dates
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0" from react-select@3.0.8
npm WARN node_modules/@ohif/ui/node_modules/react-select
npm WARN   react-select@"3.0.8" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0" from react-select@3.0.8
npm WARN   node_modules/@ohif/ui/node_modules/react-select
npm WARN     react-select@"3.0.8" from @ohif/ui@3.6.0
npm WARN     node_modules/@ohif/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-select@3.0.8
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/@ohif/ui/node_modules/react-dom
npm WARN   react-dom@"^17.0.2" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN     @ohif/ui@"*" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0" from react-select@3.0.8
npm WARN node_modules/@ohif/ui/node_modules/react-select
npm WARN   react-select@"3.0.8" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN 
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0" from react-select@3.0.8
npm WARN   node_modules/@ohif/ui/node_modules/react-select
npm WARN     react-select@"3.0.8" from @ohif/ui@3.6.0
npm WARN     node_modules/@ohif/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-with-direction@1.4.0
npm WARN Found: react@17.0.2
npm WARN node_modules/@ohif/ui/node_modules/react
npm WARN   peer react@"^0.14 || ^15.0.0 || ^16.0.0-alpha" from airbnb-prop-types@2.16.0
npm WARN   node_modules/@ohif/ui/node_modules/react-dates/node_modules/airbnb-prop-types
npm WARN     airbnb-prop-types@"^2.15.0" from react-dates@21.8.0
npm WARN     node_modules/@ohif/ui/node_modules/react-dates
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14 || ^15 || ^16" from react-with-direction@1.4.0
npm WARN node_modules/@ohif/ui/node_modules/react-with-direction
npm WARN   react-with-direction@"^1.3.1" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN   1 more (react-dates)
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14 || ^15 || ^16" from react-with-direction@1.4.0
npm WARN   node_modules/@ohif/ui/node_modules/react-with-direction
npm WARN     react-with-direction@"^1.3.1" from @ohif/ui@3.6.0
npm WARN     node_modules/@ohif/ui
npm WARN     1 more (react-dates)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-with-direction@1.4.0
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/@ohif/ui/node_modules/react-dom
npm WARN   react-dom@"^17.0.2" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN     @ohif/ui@"*" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^0.14 || ^15 || ^16" from react-with-direction@1.4.0
npm WARN node_modules/@ohif/ui/node_modules/react-with-direction
npm WARN   react-with-direction@"^1.3.1" from @ohif/ui@3.6.0
npm WARN   node_modules/@ohif/ui
npm WARN   1 more (react-dates)
npm WARN 
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^0.14 || ^15 || ^16" from react-with-direction@1.4.0
npm WARN   node_modules/@ohif/ui/node_modules/react-with-direction
npm WARN     react-with-direction@"^1.3.1" from @ohif/ui@3.6.0
npm WARN     node_modules/@ohif/ui
npm WARN     1 more (react-dates)
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

### The current behavior

not work

### The expected behavior

can work

### OS

mac

### Node version

v20.5.0.

### Browser

CHrome

**Comment by sedghi** [comment]
you might want to look at this https://react.dev/blog/2022/03/08/react-18-upgrade-guide

the migration from 17 to 18 is not straightforward because of concurrent rendering

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
