### ISSUE TITLE
MPR [Bug] 

### ISSUE THREAD

**Issue by fmotta1968** [OHIF/Viewers#3605]
### Describe the Bug

First, congratulations to everyone who is involved in this project and has contributed to the success of the application.

You select a series that only has 1, 2 images (topogram, scout) and accidentally press the mpr function button.
The application displays a message that it is not possible to apply the protocol. Ok, it's correct. The problem is that this function does not check if the selected series meets the mpr rules (slice number, modality, it returns an exception.
After the exception is thrown, the user cannot correctly execute the function again. When you try to restore the preview mode, it is lost. To go back to working if the user presses the key with F5.

### Steps to Reproduce

To play, open the study
'Neptune". Load the topogram/scout and click on the mpr function.
At that moment, the application will create the exception and display the message on the screen.

Now load the "body 3.0" series in 1x1 format and click again on the mpr function. The 3x1 layout will open correctly. Then click again on the mpr function to restore the 1x1 layout. You can not. Note that even the size of the image is wrong. There is an old bug already reported in the 1x3 format. The images are not the correct size.

Press F5 and open the "body 3.0" series, select the mpr, click again and it restores the layout correctly.

https://github.com/OHIF/Viewers/assets/3778492/76e9deb3-98ff-4753-beb5-947b9df48bcd

### The current behavior

........

### The expected behavior

.........

### OS

Windows 11

### Node version

20.3.0

### Browser

Chrome

**Comment by sedghi** [comment]
can you try on the viewer-dev.ohif.org ?

**Comment by jianghuaw** [comment]
Just have a try with viewer-dev.ohif.org, the issues still exists: without refreshing the page, there is no way to disable MPR anymore in the end by following the reproduce steps.

**Comment by sedghi** [comment]
This is now fixed in https://github.com/OHIF/Viewers/commit/221dedde5dd4df086276406a9fa2da1cc23b4eb1
