### ISSUE TITLE
[Bug] No sign in redirect with secure dcm4chee archive

### ISSUE THREAD

**Issue by mccle** [OHIF/Viewers#3607]
### Describe the Bug

I have recently faced some issues implementing user authentication when transitioning from dcm4chee's [minimum set of archive services](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host) to their [secured archive services](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-secured-archive-services-on-a-single-host). Whenever I navigate to the page where I am hosting OHIF, I encounter a blank screen and am never redirected to Keycloak to sign in. Before #3556 was implemented, I encountered the error: `Uncaught (in promise) TypeError: user is null`. I no longer see this in my browser console, but am still unable to log in and stuck on the blank screen.

To solve this issue, I changed `handleUnauthenticated` in [OpenIdConnectRoutes.tsx](https://github.com/OHIF/Viewers/blob/master/platform/app/src/utils/OpenIdConnectRoutes.tsx) to the following:
```typescript
const handleUnauthenticated = async () => {
  await userManager.signinRedirect();

  // return null because this is used in a react component
  return null;
};
```
This alteration has consistently worked for me across multiple browsers and machines, but I feel it is worth confirming that it does not interfere with any of the other authorization flows commonly used by OHIF users. Alternatively, there may be a better solution to this issue, for which I would be very grateful.

### Steps to Reproduce

1. Set up a secured dcm4chee archive by following these [instructions](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-secured-archive-services-on-a-single-host). It is potentially worth noting that I am using podman-compose as opposed to docker, but I completed the rest of the guide as described. 
2. Configure a new client for OHIF in the Keycloak administration console. Specifically, define a client_id and update the web origins to include the url where OHIF will be hosted. 
3. Update OHIF's configuration file to connect to your archive and add an oidc block as described [here](https://docs.ohif.org/deployment/authorization). The exact details will be specific to each set up.
4. Host OHIF as described [here](https://docs.ohif.org/deployment/docker) with podman in place of docker.
5. Navigate to the page where OHIF is hosted in a browser.

### The current behavior

Currently, I am stuck on a blank page and never redirected anywhere else to sign in.
![Blank_login](https://github.com/OHIF/Viewers/assets/104479423/89db7f95-360f-4036-b5d1-8501eea17464)

### The expected behavior

After updating [OpenIdConnectRoutes.tsx](https://github.com/OHIF/Viewers/blob/master/platform/app/src/utils/OpenIdConnectRoutes.tsx), I am redirected to this page: 
![Successful_Login](https://github.com/OHIF/Viewers/assets/104479423/7e11ed4e-a2fa-4d9c-8a28-11003f112969)
After providing login credentials, I am redirected back to OHIF and it functions normally. This is exactly what I had expected to happen. 

### OS

Windows 11, MacOS 13.2.1

### Node version

16.15.0

### Browser

Google Chrome 115.0.5790.170, Firefox 115.0.3, Firefox Developer Edition 117.0b7

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
