### ISSUE TITLE
OHIF VIEWER as an active service Centos

### ISSUE THREAD

**Issue by Balth1590** [OHIF/Viewers#361]
Hello everybody.
I need some help to leave OHIF Viewer as an active service in Centos 7, that is to say, every time my computer is restarted, it will be automatically raised again.
I was reading some comments that as the viewer uses METEOR could not be lifted as a service without raising the meteor first.

This was asked in 2016, so I would like to know if there is any solution to this question.

So I ask for your help to generate the viewer as a service.

Any advice will help.

Thank you

**Comment by lam0620** [comment]
pm2 (http://pm2.keymetrics.io/) can help you.

Refer here
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-centos-7
