### ISSUE TITLE
[Bug]: Slow Loading and Application Crash when Using MPR Feature in OHIF Viewer with 1GB DICOM Data"

### ISSUE THREAD

**Issue by Dhathri528** [OHIF/Viewers#3614]
### Describe the Bug

I am new Diacom Viewer and OHIF features

1. I Have upload 1Gb diacom data and i'm trying to open in OHIF Viewer it's taking so much time to load diacom images and data in viewer . 
2. Once diacom data loaded when trying to apply MPR tool on particular diacom image or particular study instance image the page is crashed and not loading any viewer getting blank page.
Anyone can help us

Thanks In Advance

### Steps to Reproduce

i have uploaded 1 Gb diacom file

### The current behavior

Taking So much time to load viewer. Once loaded clicking on MPR feature application crashed and getting blank page.

### The expected behavior

Load time can be reduce. Need to Work MPR feature without any crash of application.

### OS

linux 18

### Node version

16.14.0

### Browser

chrome

**Comment by sedghi** [comment]
Maybe your GPU doesn't have enough memory. You can give it a shot by turning on the 16-bit texture and see if it helps reduce the memory usage on your GPU and RAM. Just keep in mind that not all hardware might support this feature. You can check the webgl2 report to find out more about it.

**Comment by bingjian** [comment]
In this case, whether to consider the server side instead of the implementation

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by sedghi** [comment]
should not, the limit is 2 GB and there are some tricks to render larger volume https://docs.ohif.org/faq#how-do-i-handle-large-volumes-for-mpr-and-volume-rendering
