### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Dhathri528** [OHIF/Viewers#3615]
### Describe the Bug

MPR feature is not working . Once Clicking MPR tool is not displying any thing.
![Screenshot from 2023-08-24 18-42-24](https://github.com/OHIF/Viewers/assets/142781848/0e54db68-519a-41d4-9ddc-8df74d4fdf63)
![Screenshot from 2023-08-24 18-42-24](https://github.com/OHIF/Viewers/assets/142781848/3f21fb19-a3e2-4e74-9ba8-edd3de43faf1)

### Steps to Reproduce

Once diacom images loaded after that selected on MPR tool is not loading any images

### The current behavior

Need to load diacom images on Click on MPR feature. But images not loaded

### The expected behavior

Need to load diacom images on Click on MPR feature.

### OS

linux 18

### Node version

16.14.0

### Browser

chrome

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

Or even better, try again with latest master branch

**Comment by sedghi** [comment]
try with latest and reopen if still an issue
