### ISSUE TITLE
Build for production -Error when install npm dependencies

### ISSUE THREAD

**Issue by armandoValer** [OHIF/Viewers#363]
Hi everybody ! , I have a problem when I "build for production" . I followed all steps of the documentation . It was fine when started some steps but when install npm install dependencies , show me error .
----------------------------------------------------
S.O :Linux - CentOS release 6.10 (Final)
----------------------------------------------------
Meteor version : 1.8.0.2
Mongo version : 3.4.19 (running locally) .
Mongo node version : 8.11.4
Mongo npm version : 6.4.1
node version : 8.14.0
npm version : 6.8.0

-------------------------------------------------------
../bundle/programs/server : 

[root@PRUEBAS server]# npm install

> fibers@2.0.0 install /opt/Visor/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Problem with the binary; manual build incoming
make: se ingresa al directorio `/opt/Visor/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
cc1: error: no se reconoce la opción de línea de comando "-std=gnu11"
make: *** [Release/obj.target/fibers/src/libcoro/coro.o] Error 1
make: se sale del directorio `/opt/Visor/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-754.10.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /opt/Visor/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: no se encontró la orden
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-28T15_15_13_906Z-debug.log

**Comment by dannyrb** [comment]
Are you still experiencing this issue? What are the steps to reproduce? Does it still occur with the latest version? (What about the React branch?)

This _might_ be a documentation issue we can address, or it could be an issue with your local environment/setup.

**Comment by dannyrb** [comment]
I'm going to close this issue for now. I'm more than happy to re-open it if we receive more information and can continue the conversation 👍
