### ISSUE TITLE
[Feature Request] New side Panel (tab) look-and-feel for embedding the new Segmentation mode panels

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3634]
### What feature or change would you like to see made?

The new side panels should follow the design from @dan-rukas as presented below...

![image](https://github.com/OHIF/Viewers/assets/109477394/aa2001d5-3cb1-4af4-8ae0-0b8788c59e52)

![image](https://github.com/OHIF/Viewers/assets/109477394/38999f84-6889-47ed-bffb-16a70f68a7f7)

Left panel (tab) design to follow later.

### Why should we prioritize this feature?

A better user experience and consistent design with the new Segmentation mode sub-panels.

**Comment by james-hanks** [comment]
PR #3657
