### ISSUE TITLE
[Bug] OpenResty - Orthanc - Keycloak Recipe is not working

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3637]
### Describe the Bug

Loosely following this v2 recipe for which the 'source' can be found in `platform\app\.recipes\OpenResty-Orthanc-Keycloak`, results in a redirect to http://127.0.0.1/notfoundserver when accessing the viewer and an internal server error when navigating to http://127.0.0.1/pacs-admin/.

### Spin Things Up

- Navigate to <project-root>/platform/app/.recipes/OpenResty-Orthanc-Keycloak in your shell
-  Run docker-compose up

### Create Your First User

- Navigate to: http://127.0.0.1/auth/admin
- Sign in with: admin/password
- From the top left dropdown, select the Ohif realm
- From the left sidebar, under Manage, select Users
-  Click Add User
    - Username: test
    - Email Verified: ON
    - Click Save
- Click the Credentials Tab
    - New Pasword: test
    - Password Confirmation: test
    - Temporary: OFF
    - Click: Reset Password
- From the top right dropdown, select Admin, then Sign Out

### Sign In

- Navigate to http://127.0.0.1/
- Username: test, Password: test
- Click Log In

### Upload Your First Study

- Navigate to http://127.0.0.1/pacs-admin
- If you're not already logged in, use test/test
- From the top right, select "Upload"
- Click "Select files to upload..." (DICOM)
- Click "Start the upload"
- Navigate back to http://127.0.0.1/ to view your studies in the Study List

### The current behavior

Everything up to the the "Sign in" step appears to work fine.

The "Sign in" step in results in this page...

![image](https://github.com/OHIF/Viewers/assets/109477394/3a258661-c372-4362-97b4-6077c07cdb6b)

Attempting to access http://127.0.0.1/pacs-admin/ results in an internal server error...

![image](https://github.com/OHIF/Viewers/assets/109477394/64270fa0-c7fd-460b-9a09-8d46f276ff9c)

### The expected behavior

All the steps should proceed as described in the v2 docs.

### OS

Windows 11

### Node version

16.14.0

### Browser

Chrome 116.0.5845.111

**Comment by sedghi** [comment]
Great description, thanks a lot

**Comment by threehappypenguins** [comment]
I also have this happening, as described [here](https://discourse.orthanc-server.org/t/role-permissions-issue/4559/9?u=threehappypenguins). I honestly don't understand what is happening and if it's a bug (or the same bug) that is described here. I'm attempting [this setup](https://github.com/orthanc-team/orthanc-auth-service/blob/main/minimal-setup/keycloak/docker-compose.yml) with the ohif plugin.

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
