### ISSUE TITLE
[Feature Request] Enhanced Layout Selector

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3643]
NOTE: [Original sketches moved down to this comment](https://github.com/OHIF/Viewers/issues/3643#issuecomment-1840813815)

### What feature or change would you like to see made?

Right now the layout selector is only capable of handling grid creation, we should enhance it and include 

- presets (most common layouts in read)
- Showing Hanging protocols and stages

### Why should we prioritize this feature?

Sub tasks involved with this...

- [] #3744 
- [] #3745

### Finalized design (added Dec. 5, 2023) @dan-rukas 

![Image](https://github.com/OHIF/Viewers/assets/2745168/bf430e1b-a7d9-422d-b758-1a4112a480ec)

**Comment by ahlaughland** [comment]
This is something I am looking into for our team who use Slicer and are eager to have similar functionality like this in OHIF-V3. 

This is the layout I created:
![image](https://github.com/OHIF/Viewers/assets/17124113/e17dc4c9-e147-468e-a61c-eccbc682bbc0)

Now I'm trying to determine how to add multiple protocols that can be selected from the toolbar above but haven't been successful to far. This would be a very welcome feature!

**Comment by sedghi** [comment]
If you are not in a hurry we have some ideas for this, the work has not started yet, but this goes to the next next version. We are wrapping up the next (3.7)

**Comment by ahlaughland** [comment]
No rush. We would prefer to use an "official" OHIF version anyway.

**Comment by sedghi** [comment]
Common layouts that we are targeting

1. Four up (Axial, Sagittal, Coronal and 3D)

![CleanShot 2023-10-16 at 10 32 44](https://github.com/OHIF/Viewers/assets/7490180/cf7f2646-9b43-4646-bc6d-3a7525197e1e)

2. 3D main

 
![CleanShot 2023-10-16 at 10 33 34](https://github.com/OHIF/Viewers/assets/7490180/9e32984d-112b-4ed3-ba1f-5a9b15e1f3c4)

3. MPR

![CleanShot 2023-10-16 at 10 33 52](https://github.com/OHIF/Viewers/assets/7490180/1c0ffd68-8c2f-4b40-91d1-67c046f66dfd)

4. Axial Primary

![image](https://github.com/OHIF/Viewers/assets/7490180/9a0e9d7d-3afb-4253-ac19-cf17483e243d)


5. 3D Only

![CleanShot 2023-10-16 at 10 35 52](https://github.com/OHIF/Viewers/assets/7490180/3919c58b-7711-4cbc-9e12-cc4188d52772)

6. 3D Primary

![CleanShot 2023-10-16 at 10 36 23](https://github.com/OHIF/Viewers/assets/7490180/727a3945-8bbd-43bb-8a8b-c56502863203)

**Comment by james-hanks** [comment]
@dan-rukas to update design for integrating hanging protocol into current layout selector vs. new UI

**Comment by dan-rukas** [comment]
This comment captures the original comments and sketches:

### What feature or change would you like to see made?

Right now the layout selector is only capable of handling grid creation, we should enhance it and include 

- presets (most common layouts in read)
- Showing Hanging protocols and stages

### Why should we prioritize this feature?

Here is some initial sketch

![image](https://github.com/OHIF/Viewers/assets/7490180/cee4b9da-5907-44ec-9514-f09e1a956575)

![image](https://github.com/OHIF/Viewers/assets/7490180/856659be-dbc4-499c-83fa-ee354812fd6e)

Sub tasks involved with this...

- [] #3744 
- [] #3745

**Comment by dan-rukas** [comment]
Added finalized design below and added to original issue comment

![Image](https://github.com/OHIF/Viewers/assets/2745168/8077782e-f58a-49bf-bb7b-11dd3553d22e)

**Comment by james-hanks** [comment]
@sedghi update estimate

**Comment by james-hanks** [comment]
Awaiting #3927

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
