### ISSUE TITLE
Question: Adding textMarker (spine) Tool

### ISSUE THREAD

**Issue by phpKahuna** [OHIF/Viewers#365]
Hello.
I successfully added the Cobb Angle Tool (angleTool) but I kindly request some advice to do the same with the textMarker/spine Tool. I'd appreciate your help.

**Comment by phpKahuna** [comment]
**Solved.** 

Clues:

1. Fix textMarker Configuration setter.
2. Include textMarker dialogs.

![Screenshot_2019-03-13 OHIF Viewer](https://user-images.githubusercontent.com/41792525/54313268-f17e8880-45a6-11e9-97cb-18328b7268cd.png)

**Comment by jaizz2003** [comment]
@phpKahuna Can you help me setting up CobbAngle Tool?

**Comment by dannyrb** [comment]
@jaizz2003, please create a new issue that references this one instead of commenting on old closed issues.
