### ISSUE TITLE
RTStruct contours are not being displayed in OHIF

### ISSUE THREAD

**Issue by rodrigobasilio2022** [OHIF/Viewers#3651]
### Describe the Bug

The RTStruct contour implementation in OHIF did not display contour lines for an IDC study

### Steps to Reproduce

1. Point OHIF to the IDC dicmwebserver (dont forget to change supportsWildcard: false)
2. open the link http://localhost:3000/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1078.3273.382194720873684027956624363347
3. Open any RTStruct not a seed point

### The current behavior

No RTStruct contours lines appears

https://github.com/OHIF/Viewers/assets/114958722/1093e40b-d32b-48b0-8484-1525bc690d79

### The expected behavior

Display of RTSTruct lines

### OS

Windows 10, Mac Os

### Node version

16.14.0

### Browser

Chrome 116.0.5845.188

**Comment by sedghi** [comment]
This is the issue with floating points error where the contour appears on below the image. We are moving to surface reconstruction of the contours as 3D Slicer does, you can track it here https://github.com/cornerstonejs/cornerstone3D/pull/808

**Comment by 03shek** [comment]
@sedghi Circling back after testing the latest fix from cornerstonejs... I'm still not seeing visible outlines for some cases.

Tested via https://viewer.ohif.org/local
Version number
3.7.0
Commit Hash
5ddf8a16027255d28dc01c1740099cf85bbcf458
Browser
Chrome 119.0.0
OS
Windows 10

You had noted in #3535 that,
> some floating point difference in the contour location vs slice location make them appear behind.

Any chance this was a misdiagnosis? I'm not sure I'm seeing the floating point issue... in fact, the slice location is ways away from the Image Position Patient IPP number (not close to rounding range). 

![image](https://github.com/OHIF/Viewers/assets/115667958/53c92719-c5d3-4281-a04a-35810d2cab46)

![image](https://github.com/OHIF/Viewers/assets/115667958/4f41fce8-c9f4-4c50-8dd0-78c7448fa815)

The contour points seem to reflect the IPP values too...
![image](https://github.com/OHIF/Viewers/assets/115667958/78ffc170-2c43-46bc-8e75-eda91d24cb4f)

Thanks!

**Comment by sedghi** [comment]
Tracking it here https://github.com/OHIF/Viewers/issues/3535
