### ISSUE TITLE
[Bug] Thumbnails preview become full black when realoading data on TMTV mode

### ISSUE THREAD

**Issue by Celian-abd** [OHIF/Viewers#3653]
### Describe the Bug

On TMTV mode, if you change some data in the PET SUV panel and press 'Reload Data', all the thumbnails that are displayed from the thumbnail list will become black.

![bug2](https://github.com/OHIF/Viewers/assets/101793092/7196bc29-2348-485c-b181-90381091a082)

### Steps to Reproduce

1. Go to [https://viewer-dev.ohif.org/](https://viewer-dev.ohif.org/)
2. Open TMTV mode
3. Open the study browser panel that shows the thumbnails
4. Open PET SUV panel
5. Change some data
6. Press Reload Data button

You can notice that all the thumbnails preview become black and we can't see the image anymore.

### The current behavior

The image preview in thumbnails become black instead of showing the image.

### The expected behavior

We should keep seeing the image preview

### OS

Windows 10

### Node version

16.14.0

### Browser

Chrome 116.0.0

**Comment by sedghi** [comment]
I can't reproduce this, please re-open if the issue persists
