### ISSUE TITLE
[Bug] New extension template outdated dependency version @ohif/i18n

### ISSUE THREAD

**Issue by jennydaman** [OHIF/Viewers#3656]
### Describe the Bug

https://github.com/OHIF/Viewers/blob/bd7f9592eaec1cc7c8347bb48419f449bed675ac/platform/cli/templates/extension/dependencies.json#L21

Version should be at least 3.6.0

### Steps to Reproduce

1. `yarn run cli create-extension`
2. `cd /path/to/created_extension`
3. `npm i`

### The current behavior

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: chris-pacsfiles@0.0.1
npm ERR! Found: @ohif/i18n@undefined
npm ERR! node_modules/@ohif/i18n
npm ERR!   peer @ohif/i18n@"^1.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @ohif/i18n@"3.6.0" from @ohif/extension-default@3.6.0
npm ERR! node_modules/@ohif/extension-default
npm ERR!   peer @ohif/extension-default@"^3.0.0" from the root project
```

### The expected behavior

`npm i` should work out-of-the-box

### OS

Arch Linux

### Node version

v20.6.1

### Browser

N/A

**Comment by sedghi** [comment]
This seems to be done #3689
