### ISSUE TITLE
Dear Yeam, [Feature Request] 

### ISSUE THREAD

**Issue by arunjoshtech** [OHIF/Viewers#3658]
### What feature or change would you like to see made?

when 3 D viewe will be released. 

### Why should we prioritize this feature?

Needed for online image view in 
 3 D

**Comment by sedghi** [comment]
You can achieve it using hanging protocol, but we are working on adding controls for presets in the 3.8 (not the next release, the release after) 

https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5&hangingprotocolId=mprAnd3DVolumeViewport
