### ISSUE TITLE
How to change the DICOM server in the react app branch?

### ISSUE THREAD

**Issue by atony88** [OHIF/Viewers#366]
I was able to run the react-app and now I am trying to connect it to our own DICM server. I changed the config file in `/react-config/ccc.json` and set the `wadoUri`, run 
```
REACT_APP_CONFIG=$(cat ../../config-react/ccc.json)
yarn start
```

But I am still connecting to the same server and studies. 
It's also not clear to me where exactly the server settings are getting set. 

Is there any other configurations that needs to be done to connect it to another server?

**Comment by swederik** [comment]
I just tested this and it's working fine for me.

If you edited the ccc JSON file, you should probably be removing OpenID Connect settings. It might be easier to start from public_dicomweb.json or local_dcm4chee.json instead, those don't use openid connect.

What operating system are you using?

**Comment by atony88** [comment]
Thank you so much, This is working by hardcoding the configuration in the `index` file.
