### ISSUE TITLE
[Bug] Hydrating a measurement SR/report throws an exception

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3660]
### Describe the Bug

The following exception is thrown when a measurement SR is hydrated and the OHIF viewer crashes.

```
Uncaught TypeError: o.removeVolumeActors is not a function
    at xi (removeLabelmapFromElement.ts:22:39)
    at labelmapDisplay.ts:485:5
    at Object.removeSegmentationRepresentation (labelmapDisplay.ts:116:3)
    at removeSegmentationsFromToolGroup.ts:74:21
    at removeSegmentationsFromToolGroup.ts:57:5
    at Array.forEach (<anonymous>)
    at Module.io (removeSegmentationsFromToolGroup.ts:56:33)
    at SegmentationService.ts:1993:7
    at Array.forEach (<anonymous>)
    at ft._removeSegmentationFromCornerstone (SegmentationService.ts:1981:18)
```

### Steps to Reproduce

1. Open this https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7695.4007.324475281161490036195179843543
2. Double click to hydrate the SR.
3. Answer yes to the load prompt.

### The current behavior

An exception is thrown in the console and the OHIF viewer crashes.

### The expected behavior

Measurement is hydrated with no crash.

### OS

Windows 11

### Node version

16.14.0

### Browser

Chrome 117.0.5938.89

**Comment by james-hanks** [comment]
Fixed by segmentation mode #3632
