### ISSUE TITLE
[Bug] 3D Rendering Freezing Issue on iOS 17 Safari

### ISSUE THREAD

**Issue by kushgadhvi16** [OHIF/Viewers#3661]
### Describe the Bug

I'm experiencing a critical issue with 3D rendering on iOS 17 devices using the Safari browser. Previously, this rendering worked seamlessly on earlier iOS versions, but with the iOS 17 update, it has started freezing consistently. This issue is impacting the performance and usability of our website/application.

### Steps to Reproduce

1. Open OHIF in IOS 17 Safari Browser.

### The current behavior

Was working seamlessly on earlier iOS versions.

### The expected behavior

Should work seamlessly as earlier iOS versions 16 etc.

### OS

IOS 17

### Node version

18.12.1

### Browser

Safari

**Comment by schopdekar** [comment]
Facing the same issue.

**Comment by arunjoshtech** [comment]
is 3d is released for use? not found in demo viewer. Kindly advise

**Comment by sedghi** [comment]
Yeah I think I experiencer this too. Does MPR viewports work for you? or is it just 3D ?

**Comment by rathwale** [comment]
MPR doesnt work as well.

**Comment by james-hanks** [comment]
@sedghi will look into Apple WebGL issue and monitor

https://developer.apple.com/forums/thread/737042
https://bugs.webkit.org/show_bug.cgi?id=262628

**Comment by sedghi** [comment]
https://developer.apple.com/documentation/safari-release-notes/safari-17_1-release-notes#WebGL

**Comment by sedghi** [comment]
I created this PR which would be good enough for a lot of use cases (except the PT Scaled data)

https://github.com/cornerstonejs/cornerstone3D/pull/1212
