### ISSUE TITLE
v3.7.0-beta.76 into Master

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#3666]
### What feature or change would you like to see made?

When will [**v3.7.0-beta.76**](https://github.com/OHIF/Viewers/releases/tag/v3.7.0-beta.76) get merged into Master? This version fixes [**Reference Line**](https://github.com/OHIF/Viewers/issues/3619) issue which is in current Master version.

Thank you!

### Why should we prioritize this feature?

.

**Comment by sedghi** [comment]
master is beta, we will merging in `release` branch soon (in testing right now)
