### ISSUE TITLE
The troubleshooting link in the installation page is broken

### ISSUE THREAD

**Issue by d13g0** [OHIF/Viewers#367]
At the bottom of this page:

https://docs.ohif.org/installation.html

The troubleshooting link is broken.

Should it link to: https://docs.ohif.org/essentials/troubleshooting.html?

Thanks!

**Comment by dannyrb** [comment]
The installation page has since moved to be in the essentials/ section, but this issue is still outstanding. Please feel free to make a quick PR to fix the link ^_^

**Comment by dannyrb** [comment]
New docs have rolled out for v2. While this is a quick fix, this is a pretty stale issue. I'm going to close this, but I am always more than happy to review and merge documentation updates :+1:
