### ISSUE TITLE
[Bug] Double click back to main layout on tmtv

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3671]
### Describe the Bug

Seems like broken

https://github.com/OHIF/Viewers/assets/7490180/56e61eb0-4139-4978-9675-898c946e2e9e

### Steps to Reproduce

Go to tmtv and double click and go back

### The current behavior

It has empty viewports	

### The expected behavior

Should not

### OS

mac

### Node version

18

### Browser

Chrome

**Comment by salimkanoun** [comment]
reported also here :https://github.com/OHIF/Viewers/issues/3652
