### ISSUE TITLE
[Bug] 0x0 mm Measurements from SRs that Span Multiple Series

### ISSUE THREAD

**Issue by 03shek** [OHIF/Viewers#3673]
### Describe the Bug

Loading SRs created from OHIF, but that spans multiple series, sometimes results in 0x0 mm measurements.

### Steps to Reproduce

1. Add a measurement from Series 1.
2. Track Series 1 when prompted.
3. Add a measurement from Series 2.
4. "Add to existing report" when prompted.
5. Create SR Report.
6. All measurements can be read and navigated to in this study session.
7. Reload the study entirely with CTRL+F5.
8. Load the saved SR and say Yes to continue tracking measurements.
9. All measurements in list seem non-zero.
10. Start working your way down the measurement list, clicking each measurement one by one.
11. Upon clicking a Series 2 measurement, it turns to 0x0 mm and there are no annotation visible in the viewport. The session has crashed.

### The current behavior

Not all measurements can be read and navigated to from an SR that includes measurements from multiple series.

### The expected behavior

All measurements should be readable and navigated to from an SR that includes measurements from multiple series, since its creation is allowed in OHIF.

### OS

OHIF demo local

### Node version

OHIF demo local

### Browser

Chrome 117.0.0

**Comment by jbocce** [comment]
See OHIF PR #3696 and CS3D PR [#810](https://github.com/cornerstonejs/cornerstone3D/pull/810)
