### ISSUE TITLE
[Bug] HP won't run if a series metadata is in 404

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#3674]
### Describe the Bug

We have a custom backend that might unallow access to some series dicomweb api.
When OHIF load, the Qido request can list all series but the /series/uid/metadata route may be interrupted by our backend responding a 404 status (in our case it correspond to a soft deletion of a dicom ressource)

At HP loading if a series metadata get a 404 errors, OHIF does not crash anymore (was crashing some months ago) but the HP doesn't start and OHIF keep deplaying the spinner indefintely.

No uncaught error are displayed in the console.

### Steps to Reproduce

Forbid access to a series /uid/metadata route in a reverse proxy
try to open ohif for this study

### The current behavior

Infinite OHIF spinner

### The expected behavior

HP should start, unacessible series should be marked innaccessible in the series display set panel but should not prevent the HP to start

### OS

Linux

### Node version

18

### Browser

Chome

**Comment by sedghi** [comment]
@salimkanoun can you help us reproduce it against our server?

**Comment by salimkanoun** [comment]
@sedghi I made a PR to get back the docker container in which Orthanc was served by a nginx reverse proxy (usefull in many cases) and add a location rule in Ngnix to prevent the access of one series metadata (to be updated to your available series in you dev environement)

**Comment by sedghi** [comment]
@salimkanoun is this fixed?

**Comment by salimkanoun** [comment]
Nop, it doesn't crash but doesn't load neither

**Comment by sedghi** [comment]
Maybe i"m wrong nevermind then it is still an issue

**Comment by salimkanoun** [comment]
@sedghi it is actually working and been properly fixed in the actual master branch.
Thank you !
