### ISSUE TITLE
Standalone viewer Not working in IE 11

### ISSUE THREAD

**Issue by sdibrahimgit** [OHIF/Viewers#369]
I have done the setup of Standlaone viewer client by following by instruction provided in document page in ubuntu server - https://docs.ohif.org/standalone-viewer/usage.html

Same is working in FF and Chrome and Not working in IE 11, throwing some javascript error.

Even demo site is not working in IE 11.
https://viewer.ohif.org/viewer/1.2.392.200140.2.1.1.1.2.799008771.2020.1519719354.757

Please find the attachment.

![IE_ohif-error1](https://user-images.githubusercontent.com/48521573/54285219-8f824b00-45c7-11e9-9a9a-2aef9d94d326.png)

![DemoSiteNW_IE11](https://user-images.githubusercontent.com/48521573/54287453-af1b7280-45cb-11e9-91fa-8755175a678f.png)

![FF_ohif-viewer1](https://user-images.githubusercontent.com/48521573/54285221-901ae180-45c7-11e9-8d77-1255daffdd8f.png)

**Comment by phpKahuna** [comment]
Not a good comparison and/or test tool, as IE11 doesn't support many modern ECMAScript features. You can check this table: http://kangax.github.io/compat-table/es6/

**Comment by sdibrahimgit** [comment]
Thanks for your comments. I agree with you. Same is working fine with Edge Browser, We thought to provide support for windows 7 users, which don't have Edge browser.  We will recommend other supported browser for Windows 7 users.
Closing this issue.
