### ISSUE TITLE
[Bug] Lagging Stack Image scroll on iOS 17 Safari (iPhone / iPad)

### ISSUE THREAD

**Issue by urosch** [OHIF/Viewers#3693]
### Describe the Bug

There is obvious performance lag when scrolling image stack in Ohif viewer on iOS 17 devices using the Safari browser. With  iOS 17 update the Stack scroll is skipping / lagging in rendering images, the device is also using a lot of resources. 
This issue is impacting the performance and usability of Ohif viewer.
Using another browser like for example Inspect browser or iCab browser shows no such bad performance - it works better as you can see in side by side comparison in the attached screenshot video I've made.

https://github.com/OHIF/Viewers/assets/15800755/1d3026f7-583a-47e1-8fd0-dc3f8018b8b1

### Steps to Reproduce

Open OHIF viewer in a Safari browser on a iOS 17 device.
Example URL you can use: [click to open](https://deploy-preview-3464--ohif-dev.netlify.app/viewer?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2)

### The current behavior

The lag and skipping of images makes Ohif viewer useless on Safari for ios 17 devices.

### The expected behavior

Should work as in other browsers, without lag or slow performance.

### OS

iOS 17.0.2

### Node version

18.12.1

### Browser

Safari (for ios 17)

**Comment by sedghi** [comment]
Seems like iOS17 has a lot of problems with WebGL, we are tracking them here https://github.com/OHIF/Viewers/issues/3661

**Comment by sedghi** [comment]
Threejs and unity apps seem to have problems too

https://developer.apple.com/forums/thread/737042

**Comment by sedghi** [comment]
https://developer.apple.com/documentation/safari-release-notes/safari-17_1-release-notes#WebGL

**Comment by sedghi** [comment]
Tracking it here https://github.com/OHIF/Viewers/issues/3661
