### ISSUE TITLE
[Bug] Reset view button doesn't reset the W/L

### ISSUE THREAD

**Issue by daker** [OHIF/Viewers#3694]
### Describe the Bug

Reset view reset all image manipulation except W/L.

### Steps to Reproduce

1. Open https://viewer.ohif.org/viewer?StudyInstanceUIDs=2.25.232704420736447710317909004159492840763
2. Click on MPR button
3. Do some image manipulation
4. Change the W/L
5. Click on the reset view button

### The current behavior

everything is reset except W/L

### The expected behavior

all image manipulation are reset

### OS

Windows 10

### Node version

16

### Browser

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by sedghi** [comment]
https://github.com/cornerstonejs/cornerstone3D/pull/821
