### ISSUE TITLE
[Bug] Hydrating certain measurements that exist on images not displayed, shows no units in the side measurements' panel

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3698]
### Describe the Bug

After hydrating measurements, those measurements that exist on images not (already) displayed do not show units in the measurements side panel. Once the image is displayed, the units show up.

### Steps to Reproduce

1. Add measurements with various units (e.g. ellipse has area units) to multiple series of the same study.
2. Whenever prompted, add the additional measurements on different to existing report.
3. Save the report.
4. Refresh the browser to show the same study as in step 1.
5. Hydrate the report saved in step 3.
6. Notice that some measurements are missing units.
![image](https://github.com/OHIF/Viewers/assets/109477394/d9ea44e0-4a07-4661-922c-b098dd421b2a)

### The current behavior

Some measurement units do not display.

### The expected behavior

Measurement units do display.

### OS

Windows 11

### Node version

18.16.1

### Browser

Chrome 117.0.5938.132

**Comment by sedghi** [comment]
@IbrahimCSAE please investigate

**Comment by IbrahimCSAE** [comment]
this no longer occurs, I tested it
