### ISSUE TITLE
[Bug] Exiting MPR should return to pre MPR layout

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3699]
### Describe the Bug

Exiting MPR should return to pre MPR layout

### Steps to Reproduce

1. Launch with ?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095722.1
2. Switch to 3x3 layout.
3. Drag and drop a reconstructible series into the top left  viewport
4. Launch the viewport in the second row and third column to MPR.
5. Exit MPR with the MPR button (i.e. toggle it off)
6. Switch to 1x1 layout via the layout menu. The top-left viewport should be the only one displayed.
7. Switch to MPR.
8. Toggle MPR off.
9. The layout returns to 3x3, but 1x1 is expected

### The current behavior

The layout returns to 3x3.

### The expected behavior

1x1 is expected

### OS

Windows 11

### Node version

18.16.1

### Browser

Chrome 117.0.5938.132

**Comment by sedghi** [comment]
This is not our design anymore as we have moved away from toggle MPR to it be one of many HPs
