### ISSUE TITLE
number of Images is problem display

### ISSUE THREAD

**Issue by itcthienkhiem** [OHIF/Viewers#37]
Hi all,
i had a problem display number of Images is Zero ?
review attachment
![capture](https://cloud.githubusercontent.com/assets/2140355/18270015/0b76825e-7455-11e6-804a-a56ac8914d9a.PNG)

**Comment by swederik** [comment]
Hi there,

Yes this is what is displayed when NumberOfStudyRelatedInstances is not returned from the server. We should default it to something other than 0.

**Comment by swederik** [comment]
This has now been switched to undefined, so I'll close this.
