### ISSUE TITLE
Standalone Viewer Toolbar Icons Disappearing - RHEL7

### ISSUE THREAD

**Issue by sdibrahimgit** [OHIF/Viewers#370]
I am trying to setup OHIF Standalone client viewer in RHEL7 environment, working but few toolbar icons are not appearing. tested with all latest browsers i am getting same issue (IE 11, FF 65.0.2, Chrome 72.0)

Same is working if we deploy in Ubuntu environment.

Setup script:
-------------

install npm, meteor & python

adduser ohifuser
passwd ohifuser
usermod -aG wheel ohifuser
su  ohifuser

mkdir /opt/dicom/
sudo chmod -R 777 /opt/dicom
cd /opt/dicom/

git clone https://github.com/OHIF/Viewers.git

cd Viewers/OHIFViewer/
export METEOR_PACKAGE_DIRS=/opt/dicom/Viewers/Packages
meteor update --patch

cd Viewers/StandaloneViewer/StandaloneViewer
meteor npm install --save cornerstone-web-image-loader
meteor npm install --save @babel/runtime@latest
meteor add stylus@=2.513.14
meteor update --patch

sudo npm install -g meteor-build-client
sudo mkdir /opt/dicom/ohif-dicom-client/
sudo chmod -R 777 /opt/dicom/ohif-dicom-client/
meteor-build-client  /opt/dicom/ohif-dicom-client -u 192.168.1.168:3000

cd ../etc/
sudo mkdir /opt/dicom/ohif-dicom-client/api/
cp *.json /opt/dicom/ohif-dicom-client/api/
cp redirectingSimpleServer.py /opt/dicom/ohif-dicom-client/

firewall-cmd --zone=public --add-port=3000/tcp --permanent
firewall-cmd --reload

cd /opt/dicom/ohif-dicom-client/
python redirectingSimpleServer.py

---------------------

PFA for reference.

![OHIF_Issue_RHEL7](https://user-images.githubusercontent.com/48521573/54287051-f8b78d80-45ca-11e9-8c4c-d391b253505d.png)

![OHIF_Working_Ubuntu](https://user-images.githubusercontent.com/48521573/54287050-f8b78d80-45ca-11e9-8d32-da9850961671.png)

**Comment by phpKahuna** [comment]
The icons affected are SVG images. The icons that do appear om the toolbar are Font Awesome 4.7 images. The render method and origin are different. You should try looking in the javascript console trace (any modern browser has one) for errors to figure out what causes the SVG render problem. 
I'm attaching a code example to show you how the toolbar mixes two different render methods.
![Render SVG](https://user-images.githubusercontent.com/41792525/54311840-6bad0e00-45a3-11e9-8339-4fc453005747.PNG)

**Comment by sdibrahimgit** [comment]
Thanks for your valuable comments, I am new to these java script frameworks, some one help would be appreciated for fixing this issue.

**Comment by dannyrb** [comment]
@phpKahuna is correct, we currently pull SVG icons in from a couple of different sources. We use classes we expect to be available globally (fontawesome), and we reference SVGs from an icon file we expect to find at the website's root (icons.svg).

Documentation for this will be clearer once the `react` branch is shifted to master. Long term, we intend to bake the SVGs in so there is a reduced risk of configuration/setup issues causing this problem.
