### ISSUE TITLE
[Bug] Dragging an ellipse measurement in TMTV toggles/flickers the unit for PT between SUV and raw

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3703]
### Describe the Bug

After adding an ellipse markup in TMTV and then subsequently dragging the ellipse to move it or to resize it, toggles/flickers the units between SUV and raw.

https://github.com/OHIF/Viewers/assets/109477394/7ffdb546-2e52-4f5c-8fd7-a40a65393234

### Steps to Reproduce

1. View a study in TMTV mode.
2. Draw an ellipse on the CT.
3. Resize or move the ellipse in the CT viewport.

### The current behavior

The units on the PR viewport flickers between SUV and raw.

### The expected behavior

The unit stays consistent.

### OS

Windows 11

### Node version

18.16.1

### Browser

Chrome 117.0.5938.150

**Comment by sedghi** [comment]
Fixed in #3706
