### ISSUE TITLE
[Feature Request] Loading multiple subjects on the Viewer UI

### ISSUE THREAD

**Issue by rupeshjaiswar** [OHIF/Viewers#3704]
### What feature or change would you like to see made?

Can we have a provision to load multiple studies on the OHIF Viewer(in the main view) UI  and instead of going back to the study table(that spins up as the very first page) we can directly switch to a new study by navigating through the studies in the OHIF Viewer UI itself?

> We have found there is a way to load multiple studies on the main view by viewer?StudyInstanceUIDs=1&StudyInstanceUIDs=2 and so on is this the correct way or do we have any other way.

If the above mentioned way is correct then is there any way when we load different subject inside the main OHIF UI viewer, the Studies related to that subject is loaded and also if this can be done will there be any performance related issues since we can have more than 100 studies/large number of studies inside a subject?
Also are there any limits on the the URL where StudyInstanceUIDs are present like we can have this much length in the URL not more than that, since we can have large number of studies.

### Why should we prioritize this feature?

Since I had a question regarding this as this is not a bug this is kind of feature which is good to have can we get answer for this no need to build the feature I need just some answer around this so I can be sure that what I am planning to do is doable on OHIF or not.

**Comment by sedghi** [comment]
if it is the same patient, the prior studies would appear in the All tab, otherwise you need a custom component and it is not our priority. meanwhile you can use hanging protocol to match to separate studies in URL https://docs.ohif.org/configuration/url#studyinstanceuids
