### ISSUE TITLE
Integrate Firebase with Ohif Viewer 

### ISSUE THREAD

**Issue by ikhizarwork** [OHIF/Viewers#3708]
### Describe the Bug

I Have my Dicom data stored in Firebase Storage, and I want to use Ohif Viewer to display that Dicom data, so I need help regarding how to connect Firebase storage with Ohif Viewer. (Also note that I would like to use Url method to access the dicom file in Ohif viewer,i.e I would be passing the storage path of my dicom file in Ohif viewer as a URL parameter )

for e.g :- "https://myohif-viewer.com/?url=Firebase_Storage_path "

I am using 3.7.0-beta.73 Version of Ohif viewer.

### Steps to Reproduce

NA

### The current behavior

NA

### The expected behavior

NA

### OS

windows 11

### Node version

18+

### Browser

Version 117.0.5938.149 (Official Build) (64-bit)

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
