### ISSUE TITLE
[Bug] "All" in left study panel only shows "recents"

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#3714]
### Describe the Bug

The left study panel has 3 buttons : Primary, Recent and All.
The primary shows the opened study 
Recent shows anteriorities within 1y

I guess All should display all studies according the current but it doesn't the primary study is not listed in it.

### Steps to Reproduce

1 . go to https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463
2. got to "all" tab of the study panel
3. the All tab displays only one study while it should include all patient's studies including the primary one

### The current behavior

Do not shows the primary study

### The expected behavior

Should display all studies including the primary one

### OS

Linux

### Node version

18

### Browser

Chrome

**Comment by sedghi** [comment]
is this still an issue? and whether Cellian can work on it

**Comment by salimkanoun** [comment]
@sedghi Celian is in school but I created a PR,
The problem here is that we have 2 panels have duplicated code : PanelStudyBrowser (used in most of modes) and PanelStudyBrowserTracking (used in basic mode)

As this panel has a significant logic in it, it would need to refactor both implementation so they can have a single code base to make it maintainable.

**Comment by sedghi** [comment]
I think we can safely close this now
