### ISSUE TITLE
[Bug] MPR button is not active with hangingprotocolid set to mpr

### ISSUE THREAD

**Issue by daker** [OHIF/Viewers#3716]
### Describe the Bug

The MPR button is not active with hangingprotocolid set to mpr in the queryparams

### Steps to Reproduce

1. Open https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.5962.99.1.2968617883.1314880426.1493322302363.3.0&hangingprotocolid=mpr

### The current behavior

MRP button is not active

### The expected behavior

MRP button is active

### OS

Windows 10

### Node version

16

### Browser

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by pwespi** [comment]
Possibly related to https://github.com/OHIF/Viewers/issues/3200

**Comment by sedghi** [comment]
We are completely changing how the layout selector works, so MPR will simply be a layout without any special requirements to be shown as active. You can track the progress [here](https://github.com/OHIF/Viewers/issues/3643)
