### ISSUE TITLE
[Bug] Interleve Top Bottum only works the first opened study

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#3723]
### Describe the Bug

When openy a PET/CT with TMTV mode the image are loaded in interleave top bottom which is good.

But then if you comme back to the studylist, select another PET/CT an open it with TMTV mode, the image are loaded CT first (full body) and then the PET full body (interleave doesn't work at the second opening)

### Steps to Reproduce

1. Go to https://viewer.ohif.org/
2. open this study with TMTV mode
 ![image](https://github.com/OHIF/Viewers/assets/25229822/cb79dd9b-e429-42ba-9cd4-29767880734f)
4. Interleave top bottom is OK
5. Return to study list 
6. Open a new study with TMTV mode 
![image](https://github.com/OHIF/Viewers/assets/25229822/12139b1e-131b-4148-834e-5282bd8acffe)
8. Image CT and PT are loaded sequentially and not interleave

### The current behavior

Interleave is applied only the first PET/CT opened

### The expected behavior

Interleave should be applied for all PET/CT opening in TMTV mode

### OS

Linux

### Node version

18

### Browser

Chrome 116

**Comment by sedghi** [comment]
I can't reproduce this anymore on the `master`. Viewer-dev.ohif.org

**Comment by salimkanoun** [comment]
Fix has been merged
