### ISSUE TITLE
[Bug] Autopan not working anymore

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#3725]
### Describe the Bug

Inital release of OHIF v3 was updating viewport pan if the camera were outside the visible area.

This was making OHIF displaying the area being reviewed by the physician when one viewport is using zoom (ex when zoom in coronal view and moving the axial viewport top to buttom the coronal viewport was automatically updated to follow the camera position)

This is not working anymore

### Steps to Reproduce

1. go to https://viewer.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
2. Zoom in the coronal viewport
3. Scroll the axial view to scroll head to foot, the coronal viewport is never updated

### The current behavior

 the coronal viewport is never updated

### The expected behavior

 the coronal viewport should be udated to display the camera position when this position is offscreen (auto pan)

### OS

Linux

### Node version

18

### Browser

Chrome

**Comment by sedghi** [comment]
This was an option with default false, have you turned it to `true` ?

**Comment by sedghi** [comment]
![CleanShot 2024-01-10 at 17 34 23](https://github.com/OHIF/Viewers/assets/7490180/677b2a9f-aed7-455c-b6a0-929d0a461af0)

**Comment by salimkanoun** [comment]
humm correct we didn't activate it.
Another question hitting me, as the Crosshairs is simply a GUI to manipulate the Camera (it just follow the camera), why the autoPan is linked to Crosshairs ? Wouldn't be more a camera sync option on the camera syncrhonizer ? (I guess the autopan would work even if the crosshair is not enabled)

**Comment by sedghi** [comment]
No specific reason I guess, it can be yet another synchronizer that acts within that toolGroup. Yes

**Comment by salimkanoun** [comment]
OK I put it in our tracker we will try to look into it.
