### ISSUE TITLE
[Bug] To load the App on localhost:3000/OHIF rather that localhost:3000

### ISSUE THREAD

**Issue by rupeshjaiswar** [OHIF/Viewers#3729]
### Describe the Bug

I want to load the UI of a different path then the default one
I want to load it on http://localhost:3000/ohif rather than just http://localhost:3000 but I cannot se anywhere in the file to customize this can anyone help over here?

### Steps to Reproduce

NA

### The current behavior

The app loads on http://localhost:3000

### The expected behavior

I want app to be loaded on http://localhost:3000/ohif

### OS

Windows 11

### Node version

16.20.2

### Browser

Chrome

**Comment by beavermml** [comment]
https://docs.ohif.org/deployment/build-for-production

please refer here on how to build for Build for non-root path

**Comment by nicoesiea** [comment]
Extract from the doc:

> If you would like to access the viewer from a non-root path (e.g., /my-awesome-viewer instead of /), You can achieve so by using the PUBLIC_URL environment variable AND the routerBasename configuration option.
> 
> - use a config (e.g. config/myConfig.js) file that is using the routerBasename of your choice /my-awesome-viewer (note there is only one / - it is not /my-awesome-viewer/).
> - build the viewer with PUBLIC_URL=/my-awesome-viewer/ APP_CONFIG=config/myConfig.js yarn build (note there are two / - it is not /my-awesome-viewer).

Basically, you can try to change the value here:
![image](https://github.com/OHIF/Viewers/assets/4542315/8a3b2b5b-c186-412b-a986-ca583e70ee71)

**Comment by sedghi** [comment]
please don't use issue in the repo for asking questions. There are other channels available for that. Thanks 
![CleanShot 2023-10-20 at 09 21 54](https://github.com/OHIF/Viewers/assets/7490180/127f30e7-c868-4d50-811d-9293af41f19f)
