### ISSUE TITLE
[Feature Request] Need 2D-based segmentation

### ISSUE THREAD

**Issue by hexiaoxiao-cs** [OHIF/Viewers#3731]
### What feature or change would you like to see made?

Please add 2D segmentation tool on a single dicom stack images. Basically treat every image as a series of 2D images and allow users to annotate them.

### Why should we prioritize this feature?

All 3D medical imaging can be viewed as stacks of 2D slices, so having the ability to annotate 2D slices without considering the 3D structure is a basic need.

**Comment by sedghi** [comment]
We are aware of that limitation and working to fix it

**Comment by hexiaoxiao-cs** [comment]
Thank you for responding.
