### ISSUE TITLE
Resize required when moving stages of hanging protocols

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3732]
So in tmtv mode for instance, if we move from one stage to another, the old viewport (image) sized is preserved as of the new way of assiging Ids to viewports and not index (React just moves the element and canvas to the next stage, which is really super performant, but comes at the cost that we get wrong size, and we should trigger a resize maybe after the layout change

![CleanShot 2023-10-18 at 10 43 06](https://github.com/OHIF/Viewers/assets/7490180/83165b2f-d78f-458f-86d1-0a2f554c8cda)

**Comment by sedghi** [comment]
related issue https://github.com/OHIF/Viewers/issues/3520

**Comment by james-hanks** [comment]
@sedghi to close and summarize all related resizing issues in #3520
