### ISSUE TITLE
[Bug] WADO call instead of QIDO

### ISSUE THREAD

**Issue by nicoesiea** [OHIF/Viewers#3737]
### Describe the Bug

Hello👋 
I'm observing strange behavior on the new OHIF version. 
I'm using the viewer setup by overriding the default configuration. I set the default.js file with **wadoUriRoot** and **wadoRoot** to my wado endpoint, and **qidoRoot** to my qido endpoint.
However, when I load a series in the viewer, I'm facing a strange call:
https://hostname/my_wado_endpoint/studies/2.16.56.465769650.1.49565750525656/series?SeriesInstanceUID=1.3.12.2.1107.5.3.33.1103.2.201005141318130750

Here the call looks like a QIDO call, not a WADO one.
![image](https://github.com/OHIF/Viewers/assets/4542315/ee59e86d-ca52-4f0c-924d-b31ed9fd3a76)

It would be constructive to give me feedback on this analysis.

### Steps to Reproduce

1. Load a series via a direct URL to the viewer: https://hostname/.../ohif/viewer?StudyInstanceUIDs=2.16.56.465769650.3317998548.3382173681&SeriesInstanceUIDs=1.2.840.113619.2.278.3.655633.665.1340370393.118.3

### The current behavior

The call https://hostname/my_wado_endpoint/studies/2.16.56.465769650.1.49565750525656/series?SeriesInstanceUID=1.3.12.2.1107.5.3.33.1103.2.201005141318130750
is targeting WADO url

### The expected behavior

https://hostname/my_WADO_endpoint/studies/2.16.56.465769650.1.49565750525656/series?SeriesInstanceUID=1.3.12.2.1107.5.3.33.1103.2.201005141318130750
Must be:
https://hostname/my_QIDO_endpoint/studies/2.16.56.465769650.1.49565750525656/series?SeriesInstanceUID=1.3.12.2.1107.5.3.33.1103.2.201005141318130750

This WADO URL must target the QIDO endpoint !

### OS

Windows 10 Professionnel

### Node version

16.19.0

### Browser

Chrome Version 118.0.5993.89 (Build officiel) (64 bits)

**Comment by nicoesiea** [comment]
Unfortunately, on the demo server, all the calls QIDO and WADO are sending to the same URL
![image](https://github.com/OHIF/Viewers/assets/4542315/09dca3b3-1b3b-4ba5-8e20-e3fe46238790)

This is because of this default configuration in the default.js file:
![image](https://github.com/OHIF/Viewers/assets/4542315/4bcf000f-4186-437c-8cf1-1cb90d579181)

Can someone test with different endpoints for QIDO and WADO to confirm, or reject, the issue please?

**Comment by sedghi** [comment]
@nicoesiea Do you have a demo server with different QIDO and WADO?

**Comment by nicoesiea** [comment]
I'm sorry @sedghi but I do not have a public server.
However, you can start a local instance and easily verify

**Comment by sedghi** [comment]
what do you mean a local instance. Local instance of what?

**Comment by nicoesiea** [comment]
A local instance of OHIF viewer running with a local instance of a backend server (like orthanc, or your own PACS system) in my case, I'm creating the backend responding for WADO and QIDO query returning the data from my file + my database

**Comment by sedghi** [comment]
This is related to #2711

**Comment by nicoesiea** [comment]
Yes true, this is exactly the same bug
Remember:
![image](https://github.com/OHIF/Viewers/assets/4542315/6f01fec2-256c-4f53-aa88-acc1bde97cb8)

I let you define the new status of this issue, should probably be closed, or marked as duplicated

**Comment by sedghi** [comment]
I like to keep this one open too since it has a lot of useful details, but we will look

**Comment by james-hanks** [comment]
@nicoesiea would you be able to take a look at @sedghi comment above and help with response? We are looking to clarify to include bug fix in the next version. Thanks

**Comment by sedghi** [comment]
@nicoesiea can you let us know which branch were you seeing this issue on?

**Comment by parneshraniga** [comment]
This is still an issue with latest app docker image (so v3.8 series). If the qido and wado URLs are identical (e.g Orthanc) then there is no issue. When they are not identical, then this becomes a problem with the call going to wado endpoint.

For me this happens only with enableStudyLazyLoad true. My hypotheses is that this is thrown in RetrieveMetadataLoaderAsync. There is a search for series in the getPreloaders function. I am assuming the client passed to this is the wado client and the search calls made on lines 111 and 114 would be using the Wado client when they should be the qido client.

Fix would be to pass both clients to any functions doing search and load.

**Comment by sedghi** [comment]
hey @parneshraniga can you share with us some reproducible steps that we can take a look please?

**Comment by parneshraniga** [comment]
Running standard docker app container with dicomweb pointing to an inhouse dicomweb pacs which has separate URLs for wad, qido and stow. If enableStudyLazyLoad is true, a qido call is made to wadoRoot/studies/{study_uid}/series. This is not path that is the spec for WADO. Moreover the accept type is application/dicom+json or application/octet-string. On our server this fails as it's not a path we support and the application hangs.

I looked into the Viewer code to get an idea of where this might be coming from I suspect that this is because the qido call to get all instances "metadata" for the series is being made using the wado client. 

This seems to be a known issue. https://github.com/OHIF/Viewers/issues/1163#issuecomment-553771840
