### ISSUE TITLE
Sorting occurs after pagination, should occur before.

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#374]
This involves moving the sorting to the server side.

Currently, if studies are split in more than 1 page, and you sort by newest, you can't guarantee that you will get the 25 newest studies.

**Comment by swederik** [comment]
Yeah that would be nice. Unfortunately, this is not supported in the DICOMWeb QIDO-RS specification (https://www.dicomstandard.org/dicomweb/query-qido-rs/).

It looks like dcm4chee includes orderby:
http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger-dicom.json#/QIDO-RS/SearchForStudies

Maybe we should propose a change to the standard? Or possibly start optionally including orderby in the query for those PACS which do support it.

**Comment by pieper** [comment]
@swederik are you sure it's not supported in the standard?  According to [6.7.1.2.1 Matching](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_6.7.html), QIDO should have the kind of [attribute matching used in CFIND](http://dicom.nema.org/medical/dicom/current/output/chtml/part04/sect_C.2.2.2.html), and that includes date ranges and related things.

**Comment by dannyrb** [comment]
Scoped and added to backlog: https://github.com/OHIF/Viewers/issues/829

**Comment by Christian-e-S** [comment]
So one possibility is to use server-side sorting when this is supported by the PACS. But what about PACS that do not support sorting (e.g., Azure DICOM service).

So why not use this state-forward approach?:
Disable sorting in the UI whenever the returned results do not fit on a single page.

What do you think?
