### ISSUE TITLE
[Feature Request] Implement redesign of ViewportActionBar tools into corner regions containing the various tools.

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3742]
### What feature or change would you like to see made?

See designs in the epic #3493

### Why should we prioritize this feature?

Part of per viewport window level design and implementation #3493

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
