### ISSUE TITLE
[Bug] Callback redirect fails when using PUBLIC_URL and OIDC together (incomplete auth standard workflow with keycloak)

### ISSUE THREAD

**Issue by alej4ndro** [OHIF/Viewers#3747]
### Describe the Bug

Hello,

The issue is somehow similar to a recurrent problem reported in old issues: #2263, #1125, #1925, #2695. But I guest is essentially the same problem reported at #2540, #2850 (tested both with master branch and with tag v3.7.0).

When configuring OIDC as [here](https://github.com/OHIF/Viewers/blob/master/platform/app/public/config/docker_openresty-orthanc-keycloak.js#L38) to work with keycloak, and at the same time using a [PUBLIC_URL](https://docs.ohif.org/configuration/configurationfiles/#environment-variables) and editing routerBasename as explained [here](https://docs.ohif.org/deployment/build-for-production#build-for-non-root-path), the authentication process is unable to work properly. It performs the auth request to keycloak and then is redirect to the callback page, but subsequent calls to keycloak token endpoint never happens:

![image](https://github.com/OHIF/Viewers/assets/12082241/e0ec1ff8-53f9-4b61-933b-de92d67cbf26)

Debugging a bit, I found that the problem occurs [here](https://github.com/OHIF/Viewers/blob/master/platform/app/src/utils/OpenIdConnectRoutes.tsx#L156), due to when routerBasename is modified pathname and redirect_uri do not match and the intended use case for that if does not work:
![image](https://github.com/OHIF/Viewers/assets/12082241/83b9d8f3-64e0-4f62-85d1-f4f145b8cc27). 

It happens only when routerBasename is different than '/'. In case of routerBasename = '/' (regardless PUBLIC_URL value if we are in dev mode with yarn start), it works as expected:

 
![image](https://github.com/OHIF/Viewers/assets/12082241/7463af33-bed0-4fac-9074-ea0d725bf8c9)

And the token request to keycloak occurs finalizing the entire authentication standard flow:

![image](https://github.com/OHIF/Viewers/assets/12082241/c4bd94aa-10d1-48aa-bbfe-bd892daa58e7)

And allowing finally load the study list interface, instead of being stuck at /callback.

I verified that with a minor fix [here](https://github.com/OHIF/Viewers/blob/master/platform/app/src/utils/OpenIdConnectRoutes.tsx#L150-L152):

![image](https://github.com/OHIF/Viewers/assets/12082241/ab0af62e-7fc9-4d82-9fa0-d94eb9378385)

 The problem is solved, and now [the mentioned if case](https://github.com/OHIF/Viewers/blob/master/platform/app/src/utils/OpenIdConnectRoutes.tsx#L156) works as expected for both routerBasename '/':

![image](https://github.com/OHIF/Viewers/assets/12082241/ca91057d-10ce-4842-8f60-c1a7a29fc056)

And routerBasename '/viewer':

![image](https://github.com/OHIF/Viewers/assets/12082241/19ae6a42-53ca-41d6-9c79-8765d7e05309)

This fix is for me an acceptable solution for those cases when authentication OIDC standard flow and context path is required. If it is ok for the community, I can open a PR with this minor change.

Thanks and regards!

### Steps to Reproduce

1. Deploy keycloak and configure a client id for OHIF (I used the quarkus keycloak image from dcm4chee arc project)
2. Configure default.js with the OIDC settings as explained in the description to work with keycloak
3. Edit the routerBasename to provide a context path different than '/' (for instance, '/viewer')
4. Try to access the OHIF interface, it fails both in dev mode (yarn start) and in prod mode (built with PUBLIC_URL env var)

### The current behavior

The authentication standard flow does not finished due to the request to /token endpoint never happens, as it never meets [this condition](https://github.com/OHIF/Viewers/blob/master/platform/app/src/utils/OpenIdConnectRoutes.tsx#L156)

### The expected behavior

once the /auth endpoint of keycload redirects to the /callback endpoint, it is expected that [this condition](https://github.com/OHIF/Viewers/blob/master/platform/app/src/utils/OpenIdConnectRoutes.tsx#L156) resolves to true and the authentication standard flow continues requesting the /token endpoint of keycloak. Finally, once the /token request is done, the application interface must continue to the study list.

### OS

Windows, developing with VS Code directly on WSL. The problem occurs both in dev mode, build mode, and from a docker container also (both official image and built image from the Dokerfile in the Viewers source)

### Node version

18.17.1, 18.18.2 and 20.9.0

### Browser

Chrome 118.0.5993.90

**Comment by sedghi** [comment]
Thanks for your in depth issue explanation. I trust your fix works against the keycloak. I tried your fix against our QA server in Google Cloud with OIDC (after confirming the bug), it seems reasonable and works in the `dev` (which was broken before), but I had hard time making the `build` works. Are you sure that this works with build as well? 

Can you try the google config? 

I'm following these
- Have your changes
- Change routerBaseName in config/google.js to `/viewer`
- Build the app with `PUBLIC_URL=/viewer/ APP_CONFIG=config/google.js yarn build`
- Navigating to `platform/app` 
- Renaming `dist` to `viewer` 
- Run `npx serve .`
- Navigate to `localhost:3000/viewer` 
- The login page appears correctly 
- After signing in it says below

Any comment on what is happening? maybe you create a PR and we discuss it there

https://github.com/OHIF/Viewers/assets/7490180/bd97c2ee-6106-4ce5-b881-bd4215d468da

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
