### ISSUE TITLE
green screen while using google.js 

### ISSUE THREAD

**Issue by niirdan** [OHIF/Viewers#3752]
### Describe the Bug

no matter what version i try to use greater than 3.7.0-beta.30 i have issues with rendering the dicom materials .. 
this is how it looks like : 
![err](https://github.com/OHIF/Viewers/assets/121875046/1e017df1-8809-4fde-86ae-4301e21135d2)

### Steps to Reproduce

non

### The current behavior

all the dicom material appear in greenish color

### The expected behavior

normal preview of my dicom material ..

### OS

window 11

### Node version

v16.17.1

### Browser

Version 118.0.5993.118 (Official Build) (64-bit)

**Comment by sedghi** [comment]
I think this is related to the encoding, and google healthcare api sending incorrect metadata. You can read more here in orthanc forum which we reported similar issue 

https://discourse.orthanc-server.org/t/orthanc-convert-ybr-to-rgb-but-does-not-change-metadata/3533/19
