### ISSUE TITLE
[Feature Request] Create new multi-level menu for per viewport window level as per the design in the parent epic.

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3764]
### What feature or change would you like to see made?

See the design for the menu in the epic #3493

### Why should we prioritize this feature?

It is needed for the per viewport window level changes.

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
