### ISSUE TITLE
[Feature Request] Display Patient Name

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#3769]
### What feature or change would you like to see made?

Hi all,

Stupid question but I don't find where the patient name is displayed when opening a study,

Maybe it would be better to add in the the study selector ? Or in some other evident place in the interface ?

![image](https://github.com/OHIF/Viewers/assets/25229822/c5a2a77f-87b9-4bec-93c1-833cda33b8ab)

### Why should we prioritize this feature?

Important for avoid patient identity confusion of the displayed study

**Comment by IT-Highmore** [comment]
I think you can add name on the left pannel head if you need.

**Comment by salimkanoun** [comment]
Sure we can, i just wonder if it wouldn't be better to have it by defaut ?

**Comment by 03shek** [comment]
It's tucked away inside the "i" in a circle in the top right of the basic viewer mode viewports. In segmentation, the "i" is missing, but you can check the dicom tags browser. In tmtv mode, it is entirely missing and there are no dicom tag browser at all. It would be more useful to have it displayed on the left by default without being tucked away in all modes...

**Comment by dan-rukas** [comment]
Thanks @salimkanoun for adding this! It is important –  I was looking at a few design options to add patient information in a more universal location (in the past). It is especially necessary when our current viewport design's action bar is missing from some modes. 

Now, we're working on an [updated viewport design](https://github.com/OHIF/Viewers/issues/3493) where viewport action buttons will be available in all modes. Along with that, we're looking at moving patient information to be more universal. These designs are not posted on Github, yet. I'll be finalizing these soon and will update this post when we share it.

**Comment by salimkanoun** [comment]
Take your time, you guys are making an outstanding project, really

**Comment by dan-rukas** [comment]
@salimkanoun and everyone,

I would like to get your feedback on this draft design for the patiet summary in the toolbar. This new location would be shown by default (instead of hidden). This new design would replace the OHIF logo when the viewer is loaded. OHIF branding would only appear on the Study List. Here's what's included by default:
- Patient name
- MRN
- Sex
- Date of birth (Age)

Take a look when you have a chance and let me know your thoughts. I'm also available on Cornerstone Slack as well.

Thanks!
Dan

![Patient-summary-draft](https://github.com/OHIF/Viewers/assets/2745168/bc7e59a0-3a16-4253-bc7a-4222a762bc0d)

**Comment by shlomgad** [comment]
I think this is a good design, as long as only studies that belong to the same patient are loaded.
Is the viewer supposed to support loading of more than one patient at once ?
In real life often there is a need to display side by side studies that are technically from different patients but actually belong to the same subject. For example, a patient may have studies that were performed in different institutions with a different MRN. Findings in the recent study are compared with those from the previous one and these must be displayed side by side for comparison although the viewer will consider them to be different patients .

**Comment by salimkanoun** [comment]
I advise to display a strong warning in place of patient name if the viewer is mixing differents patient like "Warning : Mixed Patients", or a modal warning, in this situation the physicians shall be clearly warn as patient's security is unsafe

**Comment by sedghi** [comment]
@shlomgad You can load unrelated studies yes, not sure how common is that but yes

See this

https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2,1.3.6.1.4.1.25403.345050719074.3824.20170125095258.1

**Comment by sedghi** [comment]
Closing this in favor of #3929
