### ISSUE TITLE
Adding a "3D Volume Rendering" button in the viewer

### ISSUE THREAD

**Issue by quinntera** [OHIF/Viewers#3778]
### What feature or change would you like to see made?

Is it possible to add a "3D Volume Rendering" button in the viewer next to the MPR button?

![Screenshot_4](https://github.com/OHIF/Viewers/assets/150328829/54555ef3-35aa-4a84-bf23-f64b5437ea48)

### Why should we prioritize this feature?

convenience usability

**Comment by sedghi** [comment]
Stay tuned, next version https://github.com/OHIF/Viewers/issues/3643
