### ISSUE TITLE
[Bug] Display Area

### ISSUE THREAD

**Issue by fmotta1968** [OHIF/Viewers#3779]
### Describe the Bug

Hello, I created a Hanging Protocol for Mammography. I’ve already managed to create rules for all types of layouts within the standard. I saw that there is an option called “displayArea parameter” that allows you to align a certain area (set right display area) and the manual asks to see an example in cornerstone ([https://www.cornerstonejs.org/live-examples/programaticpanzoom 1](https://www.cornerstonejs.org/live-examples/programaticpanzoom)) . I accessed the link so I can’t add it to my HP. can anybody help me ?

### Steps to Reproduce

[Bug] Display Area

### The current behavior

[Bug] Display Area

### The expected behavior

[Bug] Display Area

### OS

Windows 11

### Node version

20.3.0

### Browser

Chrome

**Comment by sedghi** [comment]
we are expanding our display area support, follow this PR https://github.com/OHIF/Viewers/pull/3808
