### ISSUE TITLE
Patient name and ID must be clearly displayed on each image overlay

### ISSUE THREAD

**Issue by shlomgad** [OHIF/Viewers#3782]
### What feature or change would you like to see made?

Patient name and ID are currently displayed behind an "i" icon and require user interaction to be displayed.
As a matter of patient safety, the name and ID must be clearly and prominently displayed as a default as part of the image overlay.

### Why should we prioritize this feature?

This is a matter of patient safety and is the norm in practically every DICOM viewer and PACS system out there.

**Comment by dan-rukas** [comment]
@shlomgad - 

I just posted a [design draft for community feedback](https://github.com/OHIF/Viewers/issues/3769#issuecomment-1819841501). If you have a chance, take a look and post and feedback in that issue. This is slightly different from what you're asking for in this issue and places patient information in a more universal location. Thanks!

**Comment by sedghi** [comment]
@shlomgad If you want to display on each viewport you should look at the customization service documentation https://docs.ohif.org/platform/services/ui/customization-service#customizable-viewport-overlay
