### ISSUE TITLE
[Bug] Default threshold values [-500, 500] in the Threshold Tool [Segmentation Mode] not being initially applied correctly

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3784]
### Describe the Bug

In [Segmentation Mode] when you start a "new segmentation" and add a a segmentation via the "threshold tool" the paintbrush will only select a tiny region of the image (not represented by -500->500) anything at all until the default values are changed (even to the same values [-500,500].

On load :
![image](https://github.com/OHIF/Viewers/assets/112980389/554ee34c-7e5c-4cf8-900e-c5deb7673ded)

After retyping 500:
![image](https://github.com/OHIF/Viewers/assets/112980389/00a52aef-3d3e-4478-be6c-8cbd78cbcd26)

### Steps to Reproduce

1. Select any image set on OHIF Viewer demo (or any version up to 3.8.15) and open in segmentation mode
2. Click New Segmentation 
3. Select Threshold Tool
4. Without changing the threshold draw on viewport selected when you created the new segment - only a couple voxels might be selected
5. Change the upper limit of the threshold to something else then 500 again
6. Contour again proper -500-> 500 range applied

### The current behavior

The initial values for the threshold are not being applied correctly when segmenting the image.

### The expected behavior

Default values should be applied when the user starts segmenting using  the threshold tool

### OS

Windows 10

### Node version

OHIF 3.7 demo

### Browser

Chrome Version 119.0.6045.124 (Official Build) (64-bit)

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
