### ISSUE TITLE
Updated Implementation Documentation Videos

### ISSUE THREAD

**Issue by james-hanks** [OHIF/Viewers#3789]
Update training videos:
- Create new page for deployment videos
- Add New Videos

**Comment by dan-rukas** [comment]
Below are the embed codes from Vimeo. Joe and I finalized editing and these are added to a new "Video Tutorials" page

Embed codes from new videos:
__
Video 1
Use the OHIF CLI to create and link a mode
`<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/884891676?badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="1 - Create and Link Mode"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>`

__
Video 2
Use the OHIF CLI to create an extension
`<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/884891718?badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Use the OHIF CLI to create an extension"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>`


__
Video 3
Use the OHIF CLI to publish an extension to NPM
`<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/884891701?badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Use the OHIF CLI to publish an extension to NPM"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>`


__
Video 4
Use the OHIF CLI to publish a mode to NPM
`<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/884893445?badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="4 - Publish OHIF Mode"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
`

__
Video 5
Use the OHIF CLI to add an NPM published mode to OHIF
`<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/884893388?badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="5 - OHIF Mode from NPM"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>`


__
Video 6
Sample submission of an OHIF Viewer mode
`<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/884893372?badge=0&amp;autopause=0&amp;quality_selector=1&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sample submission of an OHIF Viewer mode"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>`

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
