### ISSUE TITLE
Series layout

### ISSUE THREAD

**Issue by fmotta1968** [OHIF/Viewers#3797]
### What feature or change would you like to see made?

Doctors working with MRI need to view several series at the same time. Currently the OHIF version uses the maximum 3x3 format by default. In theory, it would just increase the number to 4x4 (Layoutselector) for it to work. Unfortunately there is an error in the application and it keeps the viewport fixed in the position it was first loaded.

Test and see the result:

     Change the Layoutselector to 4x4 (columns x rows), open a study, change it to 4x4, then reduce the layout to 2x4 or anything smaller than 4x4. See the result.

### Why should we prioritize this feature?

Who use RM studies.

**Comment by sedghi** [comment]
We are enhancing our layout selector, you will be able to go 4x4 soon after this #3194 
However, right now you can defined your own hanging protocol to match MR in the Modalities and switch to 4x4 automatically. 

See [Hanging Protocol Module](https://docs.ohif.org/platform/extensions/modules/hpModule) and [Hanging Protocol Service](https://docs.ohif.org/platform/services/data/HangingProtocolService)

**Comment by fmotta1968** [comment]
@sedghi 
I don't think you need to create a 4x4 layout. With any viewer, you can choose with 1 click how many rows and columns you want to view. A breast MRI exam can use 5x5. If there is this option to select the rows and columns in ohif, it would be easier to just add the user option to the layoutselect and toolbar to increase or not the number of rows and columns. The problem is that the calculation that ohif uses is wrong, it gets lost.

**Comment by fmotta1968** [comment]
![image](https://github.com/OHIF/Viewers/assets/3778492/d2879f92-cece-4348-a1f1-38bb3afb1f8c)

**Comment by fmotta1968** [comment]
https://github.com/OHIF/Viewers/assets/3778492/47142481-13db-4a65-9c0e-b574c8331ffa
