### ISSUE TITLE
How to add new tool to the viewer

### ISSUE THREAD

**Issue by nodevm** [OHIF/Viewers#38]
I want to add new tools to the viewer. I know how to add the icon to the toolbar for a new tool,but where the code resides for the new tool is not very clear.

Where for instance is the code for the length tool?.

**Comment by swederik** [comment]
Hello Lancelot,

The tools reside in the Cornerstone Tools library: https://github.com/chafey/cornerstoneTools/

The length tool specifically is here: 

https://github.com/chafey/cornerstoneTools/blob/master/src/imageTools/lengthTool.js

To add a tool to the Viewer there are a few steps:

1. Add the tool itself to the repository.
  If you're using something from Cornerstone TOols you can skip this step. Some examples of custom tools can be found in the lesion tracker: https://github.com/OHIF/Viewers/tree/master/Packages/lesiontracker/client/compatibility

2. Add the toolbar button itself to the array of tools in the Toolbar:
  https://github.com/OHIF/Viewers/blob/574a6d02b090b8b2f020430c5919f8377b8316c6/OHIFViewer/client/components/toolbarSection/toolbarSection.js

3. **A:** Add it to the toolManager (if it's a tool, such as length / angle): 

  https://github.com/OHIF/Viewers/blob/574a6d02b090b8b2f020430c5919f8377b8316c6/Packages/lesiontracker/client/tools.js#L2

  **OR**

  **B:** Add it to the functionList if it's a command (e.g. toggle CINE play, or Invert the current viewport): 

 https://github.com/OHIF/Viewers/blob/574a6d02b090b8b2f020430c5919f8377b8316c6/OHIFViewer/client/components/viewer/viewer.js#L12

Making this easier is one of our goals, so these steps might change in the future.

Hope that helps,

Erik

**Comment by lancelotsmith** [comment]
Wow,many thanks @swederik  for your detailed answer.

**Comment by henryhe1** [comment]
Hi @swederik, I want to add the freehandROI tool from CornerstoneTools to the OHIFViewer (not lesiontracker), and modify it so that it can also load and save ROIs. The idea is to show segmentations and allow them to be edited and saved. How exactly should I go about doing this? How are the tools called/accessed by OHIFViewer? Where should I put a custom version of this tool in my project? 

Many thanks
