### ISSUE TITLE
Patient ID is not displayed when route is refreshed

### ISSUE THREAD

**Issue by Balth1590** [OHIF/Viewers#380]
Hi all
I have a query, when viewing an image directly from the list of studies the image loads me well with all the patient data, but when doing the same example with an iframe it does not bring me the patient's ID, someone knows what this should .

Thank.

without iframe
![image](https://user-images.githubusercontent.com/47251958/55651921-73398e80-57c0-11e9-8fee-93793b54879d.png)

with iframe
![image](https://user-images.githubusercontent.com/47251958/55651872-5309cf80-57c0-11e9-9386-27b3d206bc81.png)

**Comment by Balth1590** [comment]
I correct is not with the iframe, this happens when reloading the page with the exam

**Comment by dannyrb** [comment]
I am unable to reproduce this with the LIVE OHIF Viewer demo: https://viewer.ohif.org/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170126085406.1

- Are you able to provide a minimal reproduction?
- What version of the viewer are you using?
- Have any modifications been made / is it a fork?

**Comment by Balth1590** [comment]
Hello,
Thanks for answering, I am using the version using Viewers-fix-issue-183, because for some reason it is not found in GITHUB but it is the most stable version I have tested, the others have given me problems with the proxy wado and different types of errors in the visualization of the image.

I also test the LIVE OHIF Viewer and the error that you mentioned does not occur.

**Comment by dannyrb** [comment]
@balth1590, if you create or link me to the issues that are preventing you from upgrading, I may be able to assist with those. However, it sounds like this specific issue is resolved.

It may be worth noting that we have a large release coming soon in the `react` branch.
