### ISSUE TITLE
Cine viewer tool stays on when leaving a study and going into a new study

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3800]
### Describe the Bug

The cine viewer tool stays on when leaving a study and going into a new study. The tool does not turn off until you go into the viewer - More Tools and click on the Cine tool again. The tool does not look like it is on from the top toolbar in the viewer screen however, you will see the cine viewer on the image(s) viewport(s).

### Steps to Reproduce

This was found in both of the following environments:
https://viewer.ohif.org/ - version 3.7.0
https://viewer-dev.ohif.org/ - version 3.8.0-beta.21

1. Select a study from the study list and select the Basic Viewer button to go to the viewer screen
2. Go into 2x2 grid layout
3. Select the More Tools - Cine tool = you will see the cine tool appear on the bottom of each of the 4 viewports
4. You can select play on one or more of the viewports at a time
5. On a side note: open the developer's console while completing the next steps
6. click on the OHIF logo in the upper left corner to go back to the study list
7. Side note: in the developer's console you will see an uncaught error that will continue to increase
8. from the study list select a different study and select the basic viewer button to go back to the viewer screen
9. When the viewer screen opens, you will see the cine at the bottom of the viewport (left from the last viewport you had open and viewing a cine)
10. Side note you will also see the uncaught new error that will continue to increase
11. The cine will continue to appear on image(s) until you purposefully go back to the More Tools menu and select the cine tool again

### The current behavior

The cine tool will stay active - even if you go to the study list and select a new study, until you turn it off in the More Tools list

### The expected behavior

1. the cine should turn off when leaving the viewer screen
2. you should not get uncaught errors in the developers console that will continue to climb to unprecedented numbers (if i left the window open with ohif this error would get into the thousands+)

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v119

**Comment by james-hanks** [comment]
@jbocce could you provide estimate for this? Thanks

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
