### ISSUE TITLE
Microscopy features not working

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3801]
### Describe the Bug

Multiple microscopy features are currently not working:
1) cannot drag and drop SM images from the left study panel into the viewport
2) creating length measurements sometimes works and other times i cannot get the measure to appear on the image
3) the Point tool creates the measurement (recorded in the measurement panel) but you cannot see them on the image
4) right click on a measurement on the image does not bring up the options to Add Label or Delete Measurement (there is no way to delete)

### Steps to Reproduce

This was found in both of the following environments:
https://viewer.ohif.org/ - version 3.7.0
https://viewer-dev.ohif.org/ - version 3.8.0-beta.21

1. From the study list filter on modality: SM - select an SM study and click on the Microscopy button
2. from the viewer screen, expand the study list panel and try to drag and drop the second series appearing  = nothing happens. That SM series will not appear in the viewport and replace the SM image that was displayed on entry to the screen
3. Click on the length tool and click on the image to create a line with the mouse = this is random to create the line - sometimes it creates it and sometimes it takes a few attempts. Expand the measurements panel to see the measure when it is successful
4. Click on the Point tool and create points on the image. The points will appear as entries in the measurements panel but the points themselves will disappear from the image. The only way to see that a point is there is to click on the entry in the measurements panel and the active measure becomes yellow (but to be consistent with other modalities and measurements, i think active measurements should be green?)
5. Right-click on any existing measurements on the SM image and you should get a menu that includes: add label + delete measurement: this is consistent with other modalities image features

### The current behavior

missing features consistent with other modality image features

### The expected behavior

1) drag and drop series images to the active viewport
2) measurement features to add measurement, label & delete

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v119

**Comment by james-hanks** [comment]
@sedghi to provide estimate

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
