### ISSUE TITLE
OHIF About Info for OS is incorrect while using a Mac

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3802]
### Describe the Bug

OHIF About Info for OS is incorrect while using a Mac. The OS is reported as OS X 10.15.7
This Mac OS is incorrect as my MacBook Pro version is Sonoma 14.1.1

![image](https://github.com/OHIF/Viewers/assets/143200290/e28c0d19-d792-4c69-a2ca-583483b8d376)

![image](https://github.com/OHIF/Viewers/assets/143200290/1410c263-71cd-47e5-8f13-e2856f0fbd38)

### Steps to Reproduce

This was found in both of the following environments:
https://viewer.ohif.org/ - version 3.7.0
https://viewer-dev.ohif.org/ - version 3.8.0-beta.21

1. Select the wheel icon or the drop-down icon from the upper right corner of the OHIF screen(s)
2. Select the About option
3. Verify the Browser & OS info = the OS info on my Mac displays: OS X 10.15.7 however, my Mac version is Sonoma 14.1.1

### The current behavior

The About info is reporting the incorrect OS version

### The expected behavior

The About info should report the correct OS (& browser info)...or, no info at all 

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v119

**Comment by sedghi** [comment]
Seems like an intentional security approach by apple, they have stopped properly mentioning the os version 

https://discussions.apple.com/thread/253178691

https://www.otsukare.info/2021/02/15/capping-macos-user-agent

[Other detectors also have issues](https://bestiejs.github.io/platform.js/), so i'm just removing the version

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
