### ISSUE TITLE
MPR Crosshairs are one color (green) however, were previously different colors depending on the viewport

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3803]
### What feature or change would you like to see made?

MPR Crosshairs are one color (green) however, were previously different colors depending on the viewport. The axial, sagittal & coronal viewports also had a color coded dot in the upper right corner of the viewport as well to help navigate the crosshairs.

Restore that feature or, provide the ability to alter the crosshair colours while in MPR. Should also investigate if this feature to alter crosshair colors would be needed for TMTV crosshair use as well.

Note: this was tested in both of the following environments:
https://viewer.ohif.org/ - version 3.7.0
https://viewer-dev.ohif.org/ - version 3.8.0-beta.21

### Why should we prioritize this feature?

Having crosshairs as different colors (red, yellow & green) was previously available in OHIF.
See the following link for a previous item with screen shot references from 2020 - Bring in rotatable crosshairs. #2101: https://github.com/OHIF/Viewers/pull/2101

**Comment by sedghi** [comment]
i think it is worthwhile to add this

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
