### ISSUE TITLE
[Feature Request] Reintroduce ROI window tool from OHIF 2

### ISSUE THREAD

**Issue by peerfunk** [OHIF/Viewers#3807]
### What feature or change would you like to see made?

It would be nice to reintroduce the ROI Window. I could not find a reason why it was removed in version 3.
If someone can point me in the right direction I can do it on my own. Sorry first open source interaction.
![grafik](https://github.com/OHIF/Viewers/assets/26229643/7bf0d404-6245-4749-9075-261d975d8128)

### Why should we prioritize this feature?

Some groups of users prefere this function over presets and manual contrast, because it generally produces better results with little knowledge. For some it is a make or break situation.

**Comment by sedghi** [comment]
I liked that too. Unfortunately, I don't see that we have resources available right now to make this a priority. However, I would be more than happy to guide you on how to implement that in Cornerstone3D.

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
