### ISSUE TITLE
How do I configure KeyCloak with OHIF?

### ISSUE THREAD

**Issue by Balth1590** [OHIF/Viewers#381]
Hi all
Do any of you have any information on how to configure keycloak with OHIF?

I have searched for several sites but I do not understand it very well.

It would be very helpful if someone has already achieved the configuration and has a guide that can share.

Thank.

**Comment by dannyrb** [comment]
What have you tried? What issues are you running into? We have a guide coming out soon for a recommended setup with the React branch.

**Comment by EsrefDurna** [comment]
Hello Balth,

dcm4che uses keycloak, 
Best way to start is dcm4che is arcligjt version.

Search dcm4che arclight docker-compose which includes keycloak.

**Comment by dannyrb** [comment]
@allcontributors please add @EsrefDurna for help answering questions

**Comment by dannyrb** [comment]
The latest release includes docs on a recipe for:

- The OHIF Viewer
- OpenResty (Nginx)
- Orthanc
- Keycloak

You can find the recipe here: https://docs.ohif.org/deployment/recipes/user-account-control.html

I am more than happy to review new recipes or enhancements to the existing one.
