### ISSUE TITLE
[Bug] Refreshing the page on a locally loaded study causes the study to no longer load

### ISSUE THREAD

**Issue by hugopereiragit** [OHIF/Viewers#3810]
### Describe the Bug

After loading my files through " https://viewer.ohif.org/local " the refreshing of the page (hitting f5) causes the page to no longer show anything, this is an issue because i wanted to add " &hangingprotocolId=mprAnd3DVolumeViewport " to see the 3d rendering of my files.

### Steps to Reproduce

1 - load some files
2 - open the loaded study
3 - refresh the page in anyway

### The current behavior

All content is lost

### The expected behavior

Page refreshes

### OS

Windows 11

### Node version

v.20.10

### Browser

Firefox, Edge and Chrome

**Comment by sedghi** [comment]
expected, since we don't store the data anywhere, it is in the browser and gets removed when you refresh it. If you want to store it it would be through either sessionStorage or localStorage and we don't want that in OHIF because of security reasons. But you can do it yourself

**Comment by hugopereiragit** [comment]
I see then its not currently possible to perform 3D rendering on you own studies via adding " &hangingprotocolId=mprAnd3DVolumeViewport "

**Comment by sedghi** [comment]
we are adding a better way very soon, track it here #3194
