### ISSUE TITLE
[Bug] Segmentations imported from RTStruct all linked to first segment in series

### ISSUE THREAD

**Issue by dxlin** [OHIF/Viewers#3811]
### Describe the Bug

All segmentations imported from RTStruct are linked to first segmentation in series. Issue appears to started from cornerstonejs 1.23.0 update (surface rendering for segmentation representation update).

### Steps to Reproduce

1. Open study with RTStruct (from demo list, Water Phantom) in Basic mode
2. Load RTStruct
3. Hide first segment
4. Unhide first segment
5. Hide any other segment

### The current behavior

When hiding first segment, all segments are hidden. When any segment other than first, nothing happens.

### The expected behavior

First segment shouldn't hide others. Other segments should be able to hide independently.

### OS

Windows 10

### Node version

18.16.0

### Browser

Edge Version 119.0.2151.72

**Comment by jenny-hm-lee** [comment]
@james-hanks , I am unsure if you have a chance to look at this bug on the segmentation panel.  Basically, after loading RtStruct, when hiding the first segment, all segments are hidden as well.

**Comment by sedghi** [comment]
I can confirm this bug, but considering that we are completely revamping the RT, I would suggest waiting to try it on the new implementation.

**Comment by jenny-hm-lee** [comment]
Once RT is revamped, this bug and bug #3909 should be looked at and check if still exists.

**Comment by jenny-hm-lee** [comment]
@sedghi , does this bug and #3909 depending on the work on revamping RTSTUCT and redesigning segmentation panel (#3421)?  If the bugs are not dependent, I can see if we can help with these two bugs.

**Comment by sedghi** [comment]
No i don't think it is related

**Comment by sedghi** [comment]
is this still an issue

**Comment by jenny-hm-lee** [comment]
@sedghi , this can not be reproduce at 3.9.0-beta.2.  Thanks.
