### ISSUE TITLE
[Feature Request] Add Color bar to the new window level action icon

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3814]
### What feature or change would you like to see made?

The new color bar in the cornerstone3D is a great tool that we should add to the OHIF. It should be abled to get toggled on and off, and should react to the preset changes (it does by design but we should make sure it works as well with other interactions in the color bar)

- https://www.cornerstonejs.org/live-examples/colorbar
- https://www.cornerstonejs.org/live-examples/advancedcolorbar

### Why should we prioritize this feature?

![CleanShot 2023-11-28 at 15 42 54](https://github.com/OHIF/Viewers/assets/7490180/161c16c5-d6ed-4314-a195-023f7855f0b4)

![CleanShot 2023-11-28 at 15 43 02](https://github.com/OHIF/Viewers/assets/7490180/2a64cdfb-b5f0-46b7-b8fd-285b90a79b96)

**Comment by james-hanks** [comment]
@IbrahimCSAE confirm with @dan-rukas about spacing
