### ISSUE TITLE
[Feature Request] Advanced ROI Tools

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3819]
### What feature or change would you like to see made?

We should bring the latest development in Cornerstone3D regarding the SplineROI tools.

We currently lack the ROI tools fully which is not good.

### Why should we prioritize this feature?

Also 

- [ ] https://github.com/OHIF/Viewers/issues/3721

Design with full toolbar and menu specs added on Feb 20, @dan-rukas 

Final OHIF Tool assets: [ohif-toolbar-icons-complete-Feb22.zip](https://github.com/OHIF/Viewers/files/14378120/ohif-toolbar-icons-complete-Feb22.zip)

![Image](https://github.com/OHIF/Viewers/assets/2745168/84fa8960-f50a-4ff5-bc17-e98f40aadf3a)

![Image](https://github.com/OHIF/Viewers/assets/2745168/1668bd1e-427d-400b-8487-457f081d6ec1)

**Comment by james-hanks** [comment]
@dan-rukas @sedghi lets discuss at design review meeting to determine how this can fit into current design

**Comment by dan-rukas** [comment]
Two artboards (with specs and examples):

![Image](https://github.com/OHIF/Viewers/assets/2745168/5a092eb7-0cfb-437d-b412-1d19d61df964)

![Image](https://github.com/OHIF/Viewers/assets/2745168/1668bd1e-427d-400b-8487-457f081d6ec1)

**Comment by dan-rukas** [comment]
Attached are all of the original OHIF toolbar icon designs with the new 28x28 artboard size. All icons should be consistent and make the above implementation easier and more consistent in the Viewer when displayed (no longer displaying smaller than originally designed). 

[ohif-toolbar-icons-complete.zip](https://github.com/OHIF/Viewers/files/14361026/ohif-toolbar-icons-complete.zip)

**Comment by dan-rukas** [comment]
Attached is the most updated complete set of OHIF Toolbar icons at 28x28 size.

Note - this includes re-created icons for these tools, so they likely have a different name than what is currently in the viewer:
- tool-crosshair.svg
- tool-stack-image-sync.svg
- tool-dicom-tag-browser.svg

[ohif-toolbar-icons-complete-Feb22.zip](https://github.com/OHIF/Viewers/files/14378120/ohif-toolbar-icons-complete-Feb22.zip)

**Comment by dan-rukas** [comment]
Quick note: For all of the dropdown lists layout, spacing, and margin notes are detailed in this issue for the W/L menu component: https://github.com/OHIF/Viewers/issues/3493#issue-1771651740

**Comment by sedghi** [comment]
@dan-rukas can you please include the new magnify tool too? thanks

**Comment by sedghi** [comment]
Also this https://github.com/OHIF/Viewers/issues/3721

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
