### ISSUE TITLE
I am unable to test the OHIF Viewer locally

### ISSUE THREAD

**Issue by zhongsiyuan** [OHIF/Viewers#382]
I pull the lastest project, and when I started the project, I found the image can't be load, and the chromeDev has error， it reminds seems like domain-corss

**Comment by dannyrb** [comment]
Hi @zhongsiyuan, I am unable to reproduce. Can you detail your environment, and the steps one would take to reproduce this issue?

**Comment by zhongsiyuan** [comment]
um, sry, I think it's my some config problem, and I forget them..
