### ISSUE TITLE
[Feature Request] 4D dynamic mode

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3823]
### What feature or change would you like to see made?

we already have a good PR for it here https://github.com/OHIF/Viewers/pull/3664

### Why should we prioritize this feature?

s

**Comment by james-hanks** [comment]
Let's discuss at design meeting. @sedghi can demonstrate to @dan-rukas current implementation so we can work on new mode design

**Comment by sedghi** [comment]
https://deploy-preview-3664--ohif-dev.netlify.app/dynamic-volume?StudyInstanceUIDs=2.25.232704420736447710317909004159492840763

**Comment by fedorov** [comment]
Just for the sake of completeness, related issue from v2 days: https://github.com/OHIF/Viewers/issues/2157

**Comment by james-hanks** [comment]
We need some test data for QA

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
