### ISSUE TITLE
[Bug] Segmentation mode mouse cursor dissapears

### ISSUE THREAD

**Issue by efimfurman** [OHIF/Viewers#3824]
### Describe the Bug

In segmentation mode, using a rectangle brush, I add a rectangle and then can cause the mouse cursor to disappear which makes it very difficult to know where to draw another rectangle.

### Steps to Reproduce

Updates steps from the OHIF office meeting:
Happens with several tools, clicking in segmentation mode on edge of shape.  Also seems to happen with a second segment getting added.  Issue is that tools allow both click/move/click to create, and drag to create.

Here's a video demonstration
https://www.loom.com/share/6e9094563a184af6ba4b2ec97d464fec?sid=9e503436-3ead-4d06-b0a8-ca9b967a7d60

### The current behavior

Mosue can disappear which makes it very difficult to know where to draw.

### The expected behavior

The Mouse pointer should always be visible.

### OS

MacOS Chrome

### Node version

18.16.1

### Browser

Chrome

**Comment by sedghi** [comment]
Hmmm, so seems like if you really try to break it it will break :D

**Comment by efimfurman** [comment]
@sedghi It happens to me frequently during normal use. I have to actually be very careful not to click multiple times. When I normally draw more than one box, I seem to lose the curser, so I disagree - for me, it happens during normal use. The  above is a forceful way to recreate the issue on demand.

**Comment by sedghi** [comment]
I see, I will look

**Comment by efimfurman** [comment]
@sedghi Per today's meeting, here are the updated details:

Happens with several tools, clicking in segmentation mode on edge of shape.  Also seems to happen with a second segment getting added.  Issue is that tools allow both click/move/click to create, and drag to create.

So, no need to click multiple times, nor is there a need to use MPR mode for this, the steps above are enough...

**Comment by sedghi** [comment]
OHIF should get updated with latest cs3d version for proper fix

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
