### ISSUE TITLE
Toolbar Overhaul for Patient and More Info

### ISSUE THREAD

**Issue by james-hanks** [OHIF/Viewers#3825]
As a result of the new viewport layout and for better visibility we need to move patient info from the viewport corner to the toolbar.

Requirements:

* There shall be a patient info icon in the toolbar 
* Clicking the patient info icon shall display patient information in line in the toolbar
* Clicking the patient info icon shall hide patient information

Deploy Requirements:
* There shall be two options for deployment:
* * Patient info hidden by default (this will be the default OHIF deploy setting)
* * Patient info displayed by default
* The ability for end user to click the patient info icon to display/hide patient information shall be enabled in each deploy scenario

Epic #3493 

Final design (added Feb 20, @dan-rukas )

![Image](https://github.com/OHIF/Viewers/assets/2745168/d3ae4857-a199-4951-a645-4cff002ff54a)

![Image](https://github.com/OHIF/Viewers/assets/2745168/e2525804-b884-4d59-826f-34de979b2ada)

**Comment by dan-rukas** [comment]
Revised and updated specs for toolbar component layout and new patient info component:

![Image](https://github.com/OHIF/Viewers/assets/2745168/d3ae4857-a199-4951-a645-4cff002ff54a)

![Image](https://github.com/OHIF/Viewers/assets/2745168/e2525804-b884-4d59-826f-34de979b2ada)

**Comment by dan-rukas** [comment]
Attached is ZIP that includes the new "multiple patients" icon along with the other navigation icons in the toolbar (no changes)

[toolbar-navigation-icons-Feb23.zip](https://github.com/OHIF/Viewers/files/14386131/toolbar-navigation-icons-Feb23.zip)

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
