### ISSUE TITLE
[Bug] Rectangles drawn in MPR mode can be tilted after being drawn into the plane of the MPR view

### ISSUE THREAD

**Issue by efimfurman** [OHIF/Viewers#3827]
### Describe the Bug

Rectangles drawn in MPR mode can be tilted after being drawn into the plane of the MPR view

### Steps to Reproduce

Navigate to 
https://viewer.ohif.org/segmentation?StudyInstanceUIDs=1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046

Enable MPR mode and draw a segmentation rectangle in one of the MPR viewports. During drawing, the rectangle will be horizontal to the viewport, however after the drawing is finished, the rectangle is tilted to be parallel to the actual frames within the image.

Here's the demonstration: https://www.loom.com/share/725b586c8aa14240acf3f8c81f05425c?sid=743256aa-368e-46fa-804f-898e8f4db1d5

### The current behavior

As described the segmentation rectangle gets tilted after being drawn in cases where MPR view plane is positioned differently from the original frame orientation.

### The expected behavior

I would assume the rectangle should be drawn in tilted to begin with if the plane is tilted. 

### OS

MacOS 

### Node version

Latest

### Browser

Chrome

**Comment by sedghi** [comment]
Hmmm, this is indeed interesting bug that you found. Thanks I will look into it

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
