### ISSUE TITLE
Responsive UI Redesign

### ISSUE THREAD

**Issue by james-hanks** [OHIF/Viewers#3836]
## Toolbar
* New toolbar elements need threshold to resize/convert to hidden
* 3 toolbar components
* * Left justified OHIF logo, patient info
* * Center justified tools
* * Right justified statement of use, settings 

## Related issues
- [ ] #3159 
- [x] #3161 
- [x] #3160

**Comment by KeiOne** [comment]
Hey James, when do you think the team will tackle responsive UI design and when do you think it'll be finished ?
I'm thinking about forking and doing it but i'm not very well versed in react and have problems figuring out the layout and components of the project. So I wanna know if I should just wait or try my hand on it.

**Comment by dan-rukas** [comment]
Hello @KeiOne! I'm working as a UX designer on the OHIF Viewer. The mobile and responsive design is what I'm working on next as our v3.8 design pieces are getting wrapped up. Our upcoming roadmap will likely include some details on what version and when this may be released into the OHIF Viewer.

There are a number parts of the viewer that are being reconsidered from a UX perspective to work responsively. We're also doing some user research to understand how people will use the Viewer in mobile/responsive. Let me know if you are interested in talking about your project or use case. We could setup a short meeting, Slack chat, or whatever works.

**Comment by fmrcenter** [comment]
Hi @dan-rukas  Please consider reviewing the great UI of  [ioviyam2](http://oviyam.raster.in/ioviyam2.html) 

http://oviyam.raster.in/ioviyam2.html

Its a bit old with small screen consideration but have a great concept to begin building new mobile UI.

**Comment by sedghi** [comment]
closing in favor of https://github.com/OHIF/Viewers/issues/4099
