### ISSUE TITLE
Problem with viewing PDF documents in Ohif Viewer v3

### ISSUE THREAD

**Issue by abrahamab7** [OHIF/Viewers#3837]
### Describe the Bug

Hello, we are opening this entry to see if anyone else has had problems viewing PDF documents in Ohif V3, since it indicates "No online PDF Viewer Installed" DCM4CHEE ARC 5.18 native installation - 5.29 installation with Docker is being used as the PACS server. We appreciate any support you can give us. Thank you!

### Steps to Reproduce

1.- Run DCM4CHEE
2.- Run Ohif v3

### The current behavior

![IMG-20231205-WA0339](https://github.com/OHIF/Viewers/assets/54897577/e71fa394-a756-404d-9cd0-0b801a7d412f)

### The expected behavior

![IMG-20231205-WA0340](https://github.com/OHIF/Viewers/assets/54897577/2be2bc40-6cd8-4b7c-a6d1-a528df9a8e38)

### OS

Server Ubuntu 20

### Node version

16.17.0 - 20.0

### Browser

Chrome 119.0.60.45.200

**Comment by sedghi** [comment]
I'm gonna close this in favor of https://github.com/OHIF/Viewers/issues/3826, please subscribe to updates there
