### ISSUE TITLE
Hot Key: C activates cine viewer for basic viewer + TMTV modes

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3838]
### Describe the Bug

When you press the letter 'c' when in basic viewer mode & when in TMTV mode, the cine will be placed on all viewports that have an image.

When in basic mode, the Cine tool will not appear in the top toolbar as active. However, the cine player appears on all viewports. I assume otherwise for basic mode, the 'c' hotkey is a good feature.

When in TMTV mode, and you press the 'c' key, the cine will appear on all 9 viewports plus the MIP image. You can activate the cine. TMTV mode does not have the cine tool available from the top toolbar or menu options (other than this c hotkey) so, i assume it should not be activated at all with the hotkey.

### Steps to Reproduce

1) From the study list filter by modality = PT
2) For a study select the TMTV button to go to the viewer screen
3) Press the 'c' key from your keyboard and verify that the cine tool appears on all 9 viewports plus the MIP image
4) press the cine play icon for the viewports to verify that the cine will play through the images (even the MIP  it will rotate through the image(s)
5) repeat steps 1-4 for a study in the study list and select the Basic Viewer button (as opposed to the TMTV button). However, after pressing the 'c' key to get the cine on all viewports, look at the top toolbar to verify that the cine is not active, & click on the More Tools menu to verify that the cone tool is not highlighted (active)

### The current behavior

hot key 'c' activates the cine tool in TMTV + basic viewer mode

### The expected behavior

1) cine is not a tool for TMTV mode
2) in basic viewer mode, if the cine tool is active, it should be on the top toolbar to indicate active (and highlighted)

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v119

**Comment by tzuccher** [comment]
This was found in version: 3.8.0-beta.25

**Comment by sedghi** [comment]
Hmmm, the activation of the toolbar with the hotkeys is also reported [here](https://github.com/OHIF/Viewers/issues/3200), I'll close this as duplicate if that is ok
