### ISSUE TITLE
[Bug]  Green screen

### ISSUE THREAD

**Issue by narbek-abd** [OHIF/Viewers#3843]
### Describe the Bug

Hi.
Here is an archive.
[e5824449-2d66de43-8459fe70-9ff5359c-97655c13.zip](https://github.com/OHIF/Viewers/files/13600013/e5824449-2d66de43-8459fe70-9ff5359c-97655c13.zip)

After this commit https://github.com/OHIF/Viewers/commit/6651008fbb35dabd5991c7f61128e6ef324012df  i see green screen for this study. In local mode it works, but I I use osimis/orthanc:22.11.3 and I downloaded source code before and after this commit and it was ok before  this commit, so i don't think it is an issue with Orthanc

### Steps to Reproduce

1. use osimis/orthanc:22.11.3
2. download source code before provided commit
3. open the study

### The current behavior

green screen

### The expected behavior

proper viewer

### OS

all

### Node version

all

### Browser

all

**Comment by niirdan** [comment]
same issue here , using google.js configuration latest version .
there is an estimated time for a fix  ?

**Comment by sedghi** [comment]
I don't think it is related to that commit honestly. This is a long lasting bug in Orthanc that we tried to communicate to fix, but they fixed and later reverted the fix. https://discourse.orthanc-server.org/t/orthanc-convert-ybr-to-rgb-but-does-not-change-metadata/3533/16

**Comment by sedghi** [comment]
I posted a comment there https://discourse.orthanc-server.org/t/orthanc-convert-ybr-to-rgb-but-does-not-change-metadata/3533/19?u=alireza

**Comment by niirdan** [comment]
hey @sedghi thanks for your answer, this is very appreciated ! how does orthanc works inside ohif ? is it a remote server that the ohif sends a request or this is a static node module , because if it is a node module , maybe the temporary solution is to downgrade it to the version with the fix that they released ?

**Comment by sedghi** [comment]
seems like this will help

https://discourse.orthanc-server.org/t/orthanc-convert-ybr-to-rgb-but-does-not-change-metadata/3533/20?u=alireza

**Comment by niirdan** [comment]
> seems like this will help
> 
> https://discourse.orthanc-server.org/t/orthanc-convert-ybr-to-rgb-but-does-not-change-metadata/3533/20?u=alireza

this actually fix the issue !!! many thanks for mentioning! 
please considerate fixing google.js in the next branch with this fix

**Comment by sedghi** [comment]
Checkout lastest master branch, it should have been fixed with the recent push

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
