### ISSUE TITLE
[Bug] DICOM SecondaryCapture in JPEG is not displayed correctly

### ISSUE THREAD

**Issue by github1-grousson** [OHIF/Viewers#3846]
### Describe the Bug

When loading a DICOM SC with TransferSyntax 1.2.840.10008.1.2.4.50 (JPEG Baseline(Process 1)), image is not display well in viewer.
Attaching DCM and screenshot:
![image](https://github.com/OHIF/Viewers/assets/113672043/eed6e17c-d054-4376-9d6a-b9ceef8dd11c)
[VLp.2.25.zip](https://github.com/OHIF/Viewers/files/13619028/VLp.2.25.zip)

### Steps to Reproduce

1. Load DICOM file in orthanc
2. Load study with basic viewer

### The current behavior

![image](https://github.com/OHIF/Viewers/assets/113672043/8ccbf9f1-ad95-4c59-bb33-510bf5c884ef)

### The expected behavior

![image](https://github.com/OHIF/Viewers/assets/113672043/825a8caa-6a13-44f3-9869-17d2dd8c427f)

### OS

Windows 11

### Node version

?

### Browser

chrome

**Comment by niirdan** [comment]
joining to the issue , same here (using google.js config file) gc healthcare api . (updated to the lastest version 3.8.0-beta.28

**Comment by sedghi** [comment]
This is a bug in Orthanc, you can follow our discussion there https://discourse.orthanc-server.org/t/orthanc-convert-ybr-to-rgb-but-does-not-change-metadata/3533/19?u=alireza

gc healthcare also has the same bug, it is not OHIF honestly

**Comment by sedghi** [comment]
I will close this in favor of the other issue here, track the status there please https://github.com/OHIF/Viewers/issues/3843
