### ISSUE TITLE
[Feature Request] export video in avi or mp4

### ISSUE THREAD

**Issue by JohnMulhall00** [OHIF/Viewers#3858]
### What feature or change would you like to see made?

I would like to be able to take a video snippet in avi or mp4 format. 

### Why should we prioritize this feature?

Some clinicians were requesting it as a valuable tool.

**Comment by sedghi** [comment]
Currently not in the roadmap unfortuantelly

**Comment by JohnMulhall00** [comment]
Ok. I'm going to start working on it. Thanks!
