### ISSUE TITLE
Cannot draw on canvas when it was resized

### ISSUE THREAD

**Issue by dongtanhuy** [OHIF/Viewers#386]
I am writing code for a feature that displays abnormal areas on DICOM image in OHIF viewer like below
<img width="513" alt="Screen Shot 2019-04-16 at 21 36 22" src="https://user-images.githubusercontent.com/12930043/56218758-b385f000-608f-11e9-9278-7e89da04f30d.png">
Here is the code that I used to draw a polygon indicated the abnormal area
```js
const canvas = document.getElementsByClassName('cornerstone-canvas')[0];
const ctx = canvas.getContext('2d');
cornerstoneTools.drawing.draw(ctx, drawPolygonCanvas);
```
```js
const drawPolygonCanvas = (ctx) => {
const points = [0, 0, 580, 250, 180, 280, 280, 350];
ctx.fillStyle = 'rgba(123, 145, 13, 0.3)';
ctx.beginPath();
ctx.moveTo(points[0], points[1]);
for (item = 2; item < points.length - 1; item += 2) {
    ctx.lineTo(points[item], points[item + 1]);
}
ctx.closePath();
ctx.fill();
};
```
I can draw it successful but when I click the `Measurements` button on the top-right corner then the polygon disappeard because the canvas was resized.
Can you show me how to make polygon that does not disappear when the canvas was resized?
Thanks

**Comment by dongtanhuy** [comment]
@dannyrb I don't want to create or add a tool, my purpose is allowing the user to click on a button like Find Abnormal button, then the system can draw the polygons on canvas that shows abnormal areas on the canvas. I've tried to use **cornerstone drawing tool** to draw as you can see on my code above, but it did not work 
`cornerstoneTools.drawing.draw(ctx, drawPolygonCanvas);`

**Comment by dannyrb** [comment]
@dongtanhuy, the documentation's a little rough, but you would want to "Create a Custom Tool", not just use the included drawing API:

https://tools.cornerstonejs.org/custom-tools/

You would use the `drawing` methods in the `render` method of a custom `annotation tool`. The render method is called at appropriate times, and based on the the viewport/tool state, will assist in accurate annotations.
