### ISSUE TITLE
[Feature Request] Config/hanging protocol option for read-only mode (+ option to disable hydration)

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3863]
### What feature or change would you like to see made?

- New property for hanging protocol or configuration to disable panels editing capabilities
- New property to diablo hydration dialogs (since everything will be read-only)

### Why should we prioritize this feature?

This would allow us to easily disable all editing capabilities of panels including stowrs via hanging protocol or configuration

**Comment by igoroctaviano** [comment]
@pedrokohler can you please follow up with Alireza before implementation to understand the best way to do this?
The idea here is to have an easy way to disable all editing capabilities of panels e.g. no save/reject report, delete or edit buttons. Also, we should have an easy way to disable the tracking dialogs or tracking altogether.

**Comment by fedorov** [comment]
@igoroctaviano we will test this functionality once the sandbox instance is available.

**Comment by sedghi** [comment]
is this done?

**Comment by igoroctaviano** [comment]
> is this done?

It's done.

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
