### ISSUE TITLE
[Feature Request] Ability to navigate to other modes directly from basic mode

### ISSUE THREAD

**Issue by jenny-hm-lee** [OHIF/Viewers#3864]
### What feature or change would you like to see made?

Currently, if user is in basic viewer and wants to view the same study in a different mode, user would have to return to the study list first.  When returned, the same study is not highlighted or persist, and thus user would have to find the study again.  

I propose to add a dropdown button to the toolbar of basic mode, and have it list out all other modes.  Clicking it would allow user to open the current study with a selected mode.    

### Why should we prioritize this feature?

We can implement this feature and create PR, but we want to check if it aligns with OHIF's development roadmap or GUI design.

**Comment by sedghi** [comment]
As we mentioned earlier, we don't currently have this feature available here. However, you can definitely implement it in your own code.
