### ISSUE TITLE
[Bug] Scrollbar not visible on ohif viewer

### ISSUE THREAD

**Issue by apurv53** [OHIF/Viewers#3867]
### Describe the Bug

The studies viewer in the OHIF Viewer is displaying an empty scrollbar and failing to load studies properly.

### Steps to Reproduce

Steps to Reproduce:
Access the studies viewer section.
Observe the scrollbar area.
Note how studies are loading or failing to load.

![MicrosoftTeams-image](https://github.com/OHIF/Viewers/assets/19800139/4a401c70-cd5b-4f39-87a4-c5d94d81747c)

### The current behavior

The scrollbar appears empty, and studies are not loading as expected.

### The expected behavior

The scrollbar should display relevant content and studies should load dcm files.

### OS

windows

### Node version

NA

### Browser

chrome, edge

**Comment by sedghi** [comment]
What is your server, this might be related to the thumbnails not appearing that is discussed in the FAQ https://docs.ohif.org/faq#viewer-opens-but-does-not-show-any-thumbnails

**Comment by alphacentauridigital** [comment]
It happens on Azure Dicom Service. We are using DicomWeb to integrate Ohifv3. Ohifv2 is working fine.

Disabling wildcard in app.config.js worked. Thanks a lot

**Comment by sedghi** [comment]
@alphacentauridigital yay
