### ISSUE TITLE
[Bug] Compilation Error 

### ISSUE THREAD

**Issue by niirdan** [OHIF/Viewers#3868]
### Describe the Bug

**Version : current Master .**
After fixing the green screen bug which i had to add this in google.js config file 
`        acceptHeader: [ 'multipart/related; type=application/octet-stream; transfer-syntax=*'],`
Compilation with errors and compilation doesn't contain the fix above and the result is that the green screen appears in compiled version and in dev mode it doesn't appear

### Steps to Reproduce

version master , work with google.js , and add the acceptHeader: [ 'multipart/related; type=application/octet-stream; transfer-syntax=*'] to fix the green screen issue .. 
yarn run dev - 
everything works as expected after compilation , it appears that it wont take the google.js new fields , even when i set showStudyList to false and ignore crossOrigin message warning to false . 
 

### The current behavior

after compilation green screen still appears, 
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  app.bundle.fd9c7b9b4b5554cbe9bf.js (4.27 MiB)
  dicom-microscopy-viewer.bundle.891b86d0c0df9ca3fe6b.js (2.18 MiB)
  26.bundle.121399fde7abcf84fd93.js (1.09 MiB)
  220.bundle.d0b0df6e3678c751fa3c.js (592 KiB)
  cornerstoneDICOMImageLoader.min.js.map (390 KiB)
  index.worker.64c896c4316fcd506666.worker.js.map (500 KiB)
  dicomMicroscopyViewer.min.js (2.18 MiB)
  index.worker.min.worker.js.map (726 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (4.35 MiB)
      app.bundle.css
      app.bundle.fd9c7b9b4b5554cbe9bf.js


webpack 5.88.2 compiled with 2 warnings in 59900 ms (5e5fbb83434425d247a0)



 >  Lerna (powered by Nx)   Successfully ran target build:viewer for project @ohif/app

   Nx read the output from the cache instead of running the command for 1 out of 1 tasks.

Done in 1.89s.
```
Compilation output warning . 
looks like the issue is about compilation 

### The expected behavior

after compilation , it will work exactly like it run perfectly fine in DEV mode (yarn run dev with google.js conf)

### OS

window 11

### Node version

v20.9.0

### Browser

Version 118.0.5993.118 (Official Build) (64-bit)

**Comment by sedghi** [comment]
Checkout the latest master branch, I think it is fixed, re-open if not

**Comment by niirdan** [comment]
@sedghi Thanks for answering! unfortunately i tried - pulled the latest master, used yarn run build and this is the result : 
`@ohif/app: assets by path *.js 12.4 MiB 48 assets
@ohif/app: assets by path assets/ 318 KiB 48 assets
@ohif/app: assets by path *.wasm 1.42 MiB 8 assets
@ohif/app: assets by path *.css 97.3 KiB 7 assets
@ohif/app: assets by path *.map 1.73 MiB 5 assets
@ohif/app: assets by path *.svg 32.3 KiB 2 assets
@ohif/app: assets by path *.html 5.36 KiB
@ohif/app:   asset index.html 4.71 KiB [emitted]
@ohif/app:   asset silent-refresh.html 665 bytes [emitted] [from: ../public/silent-refresh.html] [copied]
@ohif/app: assets by path *.json 1.64 KiB
@ohif/app:   asset manifest.json 1.34 KiB [emitted] [from: ../public/manifest.json] [copied]
@ohif/app:   asset serve.json 310 bytes [emitted] [from: ../public/serve.json] [copied]
@ohif/app: asset _headers 264 bytes [emitted] [from: ../public/_headers] [copied]
@ohif/app: asset _redirects 156 bytes [emitted] [from: ../public/_redirects] [copied]
@ohif/app: Entrypoint app [big] 5.5 MiB (19.1 MiB) = app.bundle.css 83.8 KiB app.bundle.20e2fc14b98128ebe05d.js 5.41 MiB 2 auxiliary assets
@ohif/app: LOG from InjectManifest
@ohif/app: <i> The service worker at sw.js will precache
@ohif/app: <i>         176 URLs, totaling 53.5 MB.
@ohif/app: WARNING in ../../../extensions/tmtv/src/utils/calculateSUVPeak.ts 94:2-44
@ohif/app: export 'utilities'.'pointInSurroundingSphereCallback' (imported as 'utilities') was not found in '@cornerstonejs/tools' (possible exports: annotationFrameRange, boundingBox, calibrateImageSpacing, cine, clip, contours, debounce, drawing, dynamicVolume, getAnnotationNearPoint, getAnnotationNearPointOnEnabledElement, getCalibratedAreaUnits, getCalibratedLengthUnits, getCalibratedScale, getSphereBoundsInfo, isObject, jumpToSlice, math, orientation, planar, planarFreehandROITool, pointInShapeCallback, pointToString, polyDataUtils, rectangleROITool, roundNumber, scroll, segmentation, stackContextPrefetch, stackPrefetch, throttle, touch, triggerAnnotationRender, triggerAnnotationRenderForViewportIds, triggerEvent, viewport, viewportFilters, voi)
@ohif/app:  @ ../../../extensions/tmtv/src/commandsModule.js 7:0-56 211:22-38
@ohif/app:  @ ../../../extensions/tmtv/src/index.tsx 5:0-46 35:11-25
@ohif/app:  @ ./pluginImports.js
@ohif/app:  @ ./index.js 19:0-89 33:4-21 34:4-16
@ohif/app: WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
@ohif/app: This can impact web performance.
@ohif/app: Assets:
@ohif/app:   app.bundle.20e2fc14b98128ebe05d.js (5.41 MiB)
@ohif/app:   dicom-microscopy-viewer.bundle.649323f830e61afc3dbf.js (2.18 MiB)
@ohif/app:   223.bundle.473c30ab997e3a001639.js (597 KiB)
@ohif/app:   cornerstoneDICOMImageLoader.min.js.map (397 KiB)
@ohif/app:   index.worker.64c896c4316fcd506666.worker.js.map (500 KiB)
@ohif/app:   dicomMicroscopyViewer.min.js (2.18 MiB)
@ohif/app:   index.worker.min.worker.js.map (726 KiB)
@ohif/app: WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
@ohif/app: Entrypoints:
@ohif/app:   app (5.5 MiB)
@ohif/app:       app.bundle.css
@ohif/app:       app.bundle.20e2fc14b98128ebe05d.js
@ohif/app:
@ohif/app: webpack 5.89.0 compiled with 3 warnings in 53939 ms (cb97047c198bdedfe5b0)


`

**Comment by sedghi** [comment]
@niirdan I don't see any error here, do you see the dist folder getting generated in the platform/app?

**Comment by niirdan** [comment]
Unfortunately no, stays empty

**Comment by sedghi** [comment]
what is your node version? you should use 18.x

**Comment by niirdan** [comment]
@sedghi i am using node version 20.9.0

**Comment by sedghi** [comment]
Can you try 18?

**Comment by niirdan** [comment]
Of course, I will try it and let you know
Thanks

**Comment by niirdan** [comment]
@sedghi
v18.17.1 should work?

**Comment by sedghi** [comment]
It should
