### ISSUE TITLE
[Bug] Thumbnail images are enlarged and displayed on the client side.

### ISSUE THREAD

**Issue by VetsImaging** [OHIF/Viewers#3869]
### Describe the Bug

Now, I am using v3.7.0 (release) on my local Windows11.
Thumbnail image is enlarged on the client side.
On the server side, the entire image is displayed without being enlarged.
<img width="1360" alt="ontheserver" src="https://github.com/OHIF/Viewers/assets/145171303/4e837b04-6298-4322-a7f7-4d5fbbc50502">
<img width="1437" alt="ontheclient" src="https://github.com/OHIF/Viewers/assets/145171303/033043e6-7af6-4738-aca9-32a24eb23870">

### Steps to Reproduce

1. git clone https://github.com/OHIF/Viewers.git
2. cd ./Viewers
3. git checkout tags/v3.7.0
4. yarn install
5. yarn run dev:orthanc

### The current behavior

On the Client : Thumbnail image is enlarged
On the server : Thumbnail image is not enlarged.

### The expected behavior

On the client side, the thumbnail image should be displayed in its entirety without being enlarged.

### OS

Windows11 pro

### Node version

node v16.20.0 , yarn v1.22.19

### Browser

Chrome120.0.6099.130

**Comment by Van-Ni** [comment]
I am also using v3.7.0 (release) on my v3.7.0 (release) on android mobile.I have 1 problem
The first time the thumbnail was rendered there was no problem, but when I selected another thumbnail it had an error displaying the thumbnail. T hope you can help me. Thanks
![1](https://github.com/OHIF/Viewers/assets/73803737/b9f4de0c-2ae9-4791-9694-687cd5e71b6c)
![2](https://github.com/OHIF/Viewers/assets/73803737/bcca5084-78dd-4f18-a2d5-2917ccddd548)

**Comment by Van-Ni** [comment]
It's like this image is encroaching on another image

**Comment by Srikanthkurva** [comment]
HI Bro This Srikanth Kurva. I have a Doubt Regarding OHIF Applications. I have sucueefully running this applications https://github.com/OHIF/Viewers?tab=readme-ov-file in my local. I did not understanding how the images will coming. one thing I have replace with my DCOM images. Could you help.
![OHIF](https://github.com/OHIF/Viewers/assets/131551584/23d5200f-af5e-479e-b4f3-4a8ff6808854)

![OHIF1](https://github.com/OHIF/Viewers/assets/131551584/f3d58771-64fd-49ce-9134-2bdf3965fe07)

**Comment by sedghi** [comment]
I have a fix for this thumbnail large, until i merge you can do this


extensions/default/src/Panels/getImageSrcFromImageId.js
extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/getImageSrcFromImageId.js

```
/**
 * @param {*} cornerstone
 * @param {*} imageId
 */
function getImageSrcFromImageId(cornerstone, imageId) {
  return new Promise((resolve, reject) => {
    const canvas = document.createElement('canvas');
    // Note: the default width and height of the canvas is 300x150
    // but we need to set the width and height to the same number since
    // the thumbnails are usually square and we want to maintain the aspect ratio
    canvas.width = 300;
    canvas.height = 300;
    cornerstone.utilities
      .loadImageToCanvas({ canvas, imageId })
      .then(imageId => {
        resolve(canvas.toDataURL());
      })
      .catch(reject);
  });
}
export default getImageSrcFromImageId;

```

inside  platform/ui/src/components/Thumbnail/Thumbnail.tsx
<img width="517" alt="CleanShot 2024-03-18 at 12 49 05@2x" src="https://github.com/OHIF/Viewers/assets/7490180/a66d960d-1263-4914-b749-787722b6f371">

**Comment by Srikanthkurva** [comment]
Dear Alireza

I hope this email finds you well. My name is Srikanth Kurva, and I am
reaching out to you  Regarding OHIF Applications. I have sucueefully
running this   applications
https://github.com/OHIF/Viewers?tab=readme-ov-file in my local. I did not
understanding how the images will coming. I have DCOM Images pdf now I want
replace with my images. Could you please help me.

****How to replace my images********

I would greatly appreciate it if you could take a moment to address my
query. Your expertise in this matter would be immensely helpful.

Thank you very much for your time and assistance.

Best regards,
Srikanth Kurva

**Comment by Srikanthkurva** [comment]
![OHIF1](https://github.com/OHIF/Viewers/assets/131551584/88c3f90a-2eae-424a-bd55-11dca9df0f09)
Dear Alireza

I hope this email finds you well. My name is Srikanth Kurva, and I am reaching out to you  Regarding OHIF Applications. I have sucueefully running this   applications https://github.com/OHIF/Viewers?tab=readme-ov-file in my local. I did not understanding how the images will coming. I have DCOM Images pdf now I want replace with my images. Could you please help me.

****How to replace my images********

I would greatly appreciate it if you could take a moment to address my query. Your expertise in this matter would be immensely helpful.

Thank you very much for your time and assistance.

Best regards,
Srikanth Kurva
![OHIF](https://github.com/OHIF/Viewers/assets/131551584/f899bed0-4bd1-4d20-89cb-256a7ac1b445)

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.

**Comment by VetsImaging** [comment]
I confirmed in v3.8.0 release and it works well !
Thank you so much !
