### ISSUE TITLE
MPR will load for one series then not load for any others within the same study [ 3.8.0-beta.35]

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3873]
### Describe the Bug

When using MPR in basic mode only one series can be loaded in MPR, any subsequent series will not work.

Series selected when MPR clicked [PET AC]
![image](https://github.com/OHIF/Viewers/assets/112980389/6550f589-3167-407b-b405-25f1c6ee67b3)

Drag another series in [CT Images]
![image](https://github.com/OHIF/Viewers/assets/112980389/d0220675-6995-4a43-8df9-fe40256a5a37)

or close MPR, select the CT and click MPR - same result
![image](https://github.com/OHIF/Viewers/assets/112980389/bd75cd0c-c4b2-4125-932f-065ee37f2eb4)

### Steps to Reproduce

Version number: 3.8.0-beta.35
Commit hash: 5915fada83d89c9acddeffc0f04a006aeeee2576

Method 1
1. Go to https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
2. Select the [PET AC] series 1 and click MPR - MPR should load fine
3. Drag the [CT Images] series 2 into to axial view port
4. CT will display as a grey rectangles in all 3 viewports

Method 2
1. Go to https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
2. Select the [PET AC] series 1 and click MPR - MPR should load fine
3. Close MPR
4. Select the [CT Images] series 2 and click MPR
5. CT will display as a grey rectangles in all 3 viewports

### The current behavior

Only the first MPR selected will display properly.  When selecting a second (either via drag and drop or closing MPR and opening it on another series) the second will not render.

It does not matter if PET is first or CT is first.  

### The expected behavior

Users should be able to select a second image set to view in MPR.

### OS

Windows 10

### Node version

viewer  3.8.0-beta.35

### Browser

Chrome 120.0.6099.130 (Official Build) (64-bit)

**Comment by salimkanoun** [comment]
+1 I see the same bug

**Comment by sedghi** [comment]
You can update your cornerstone versions and it is fixed now, until I push a PR to fix upstream.

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
