### ISSUE TITLE
MIP in TMTV mode no longer allows rotation [ 3.8.0-beta.35] [Bug] 

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3874]
### Describe the Bug

When a PET-CT is rendered in TMTV mode there is a Maximum Intensity Projection loaded on the right had side.  With the current beta version  https://viewer-dev.ohif.org/ [3.8.0-beta.35] this MIP no longer rotates through the use of the scroll wheel as it did in previous versions including the version on https://viewer.ohif.org/ [3.7.0].
3.8.0 beta 35
![image](https://github.com/OHIF/Viewers/assets/112980389/c11cb4a5-7e25-4d5c-a8d8-28dd84576b9b)
3.7
![image](https://github.com/OHIF/Viewers/assets/112980389/00e3fcdf-43d8-46ad-aa6a-b08db67cbe49)

### Steps to Reproduce

Version number: 3.8.0-beta.35
Commit hash: 5915fada83d89c9acddeffc0f04a006aeeee2576

1) Go to https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
2) Wait for the image to render.
3) Try to rotate the MIP using the scroll wheel. It will not rotate.

### The current behavior

The Maximum Intensity Projection  will not rotate in MPR more with the use of the scroll wheel.

### The expected behavior

In previous versions the use of the scroll wheel allows the rotation of the maximum intensity projection in TMTV mode.

### OS

Windows 10

### Node version

dev viewer  3.8.0-beta.35

### Browser

Chrome Version 120.0.6099.130

**Comment by salimkanoun** [comment]
Hi guys, actually is does rotate but we changed the angle unit here https://github.com/cornerstonejs/cornerstone3D/pull/837, so the angle which was interpreted in radiant is not interpreted as degree, will try to make a PR
