### ISSUE TITLE
[Bug] Tool state is buggy with measurement tools in MPR

### ISSUE THREAD

**Issue by m00n620** [OHIF/Viewers#3896]
### Describe the Bug

Tool state is not correctly saved & restored with measurement tools when switching hanging protocols.

### Steps to Reproduce

1. Load viewer
2. Click Zoom tool
3. Click Ellipse ROI
4. Click MPR

### The current behavior

Zoom is active although toolbar state shows Ellipse ROI.

### The expected behavior

Ellipse ROI should be active tool.

### OS

Windows 11

### Node version

18.16.0

### Browser

Chrome 120.0.6099.217

**Comment by sedghi** [comment]
We can add the current active tool to the state sync service I guess to remember, but then we should have some feedbacks

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
