### ISSUE TITLE
[Feature Request] Add measurement tracking in all 3 viewports of MPR

### ISSUE THREAD

**Issue by tobiedesgreniers** [OHIF/Viewers#3898]
### What feature or change would you like to see made?

- Be able to track measurements in the sagittal viewport in MPR mode.
- Be able tot rack measurements in the coronal viewport in MPR mode.

### Why should we prioritize this feature?

This would allow more flexibility to take measurements and then export those measurements so they can be used by medical teams to design surgical devices. The goal is also to eventually be able to track measurements in oblique views of a study.

I can implement the feature but I'd need some guidance to approximately learn what files/classes to modify.

**Comment by JeffersonCurveBeam** [comment]
Second this

**Comment by sedghi** [comment]
when we say tracking we mean you can export it. In MPR we only have support for SR export for acquisition, although user can draw on others, i think we should show them as untracked in the panel

**Comment by sedghi** [comment]
Non-tracked annotations (on reconstruction views) should be rendered in the `additional findings` section. The JSON download should export them, but the DICOM SR should not include them.

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
