### ISSUE TITLE
Unrecognized tag 80000

### ISSUE THREAD

**Issue by christianvargasforero** [OHIF/Viewers#39]
I'm trying to connect with  dcm4che 2x but when connection and the following problem is generated:

=> Meteor server restarted
I20160912-17:04:56.080(-5)? worklist: Services.DIMSE.Studies
I20160912-17:04:56.082(-5)? Associating...
I20160912-17:04:56.084(-5)? Starting Connection...
I20160912-17:04:56.102(-5)? { host: '10.10.0.1', port: 11112 }
I20160912-17:04:56.300(-5)? Connect
I20160912-17:04:56.303(-5)? Connection established
I20160912-17:04:56.475(-5)? ==Associated
I20160912-17:04:56.481(-5)? Sending command C-FIND-RQ
W20160912-17:04:56.838(-5)? (STDERR)
W20160912-17:04:56.840(-5)? (STDERR) /Users/xxxxxxx/developer/Viewers-master/OHIFViewer/.meteor/local/build/programs/server/packages/dimseservice.js:5016
W20160912-17:04:56.841(-5)? (STDERR)     throw 'Unrecognized tag ' + (tag >>> 0).toString(16);                                                              // 809
W20160912-17:04:56.842(-5)? (STDERR)     ^
W20160912-17:04:56.842(-5)? (STDERR) Unrecognized tag 80000
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

![captura de pantalla 2016-09-12 a las 5 05 40 p m](https://cloud.githubusercontent.com/assets/11984387/18454666/3a92b41c-790b-11e6-99a2-7d21879bd067.png)

thank you very much.

**Comment by swederik** [comment]
Hi Christian,

Could you try the branch called privateTagTest: https://github.com/OHIF/Viewers/tree/privateTagTest

Weiwei has added something that might fix your issue, but we don't have a file with your issue to test with.

Cheers,

Erik

**Comment by christianvargasforero** [comment]
Good morning,
Thank you very much for your help the problem was resolved in my local pc , when I tried it on a server in the cloud had some problems although it is already possible to make the conneccion and display the list of studies and respecitve images.

These messages are displayed :

=> Started proxy.
=> Started MongoDB.
I20160915-11:38:00.021(-5)? Adding DIMSE peers
I20160915-11:38:00.068(-5)? ------ Testing Meteor Settings ------
...
...
...
I20160915-11:38:00.105(-5)? server error {"code":"EADDRNOTAVAIL","errno":"EADDRNOTAVAIL","syscall":"listen","address":"10.14.0.50","port":11112}
=> Started your app.
=> App running at: http://localhost:3000/
I20160915-11:38:39.104(-5)? worklist: Services.DIMSE.Studies
I20160915-11:38:39.107(-5)? Associating...
I20160915-11:38:39.107(-5)? Starting Connection...
I20160915-11:38:39.118(-5)? { host: '10.14.0.1', port: 11112 }
I20160915-11:38:39.119(-5)? Connect
I20160915-11:38:39.119(-5)? Connection established
I20160915-11:38:39.129(-5)? ==Associated
I20160915-11:38:39.131(-5)? Sending command C-FIND-RQ
I20160915-11:38:39.322(-5)? Data received
I20160915-11:38:39.377(-5)? Data received
...
...
...
I20160915-11:38:44.529(-5)? Data received
I20160915-11:38:47.110(-5)? Invalid length for fixed length tag, vr DA, length 8 !== 6
I20160915-11:38:48.721(-5)? Data received
....
....
...
I20160915-11:39:54.419(-5)? worklist: Services.DIMSE.Studies
I20160915-11:39:54.420(-5)? Associating...
I20160915-11:39:54.420(-5)? Starting Connection...
I20160915-11:39:54.421(-5)? { host: '10.14.0.1', port: 11112 }
I20160915-11:39:54.422(-5)? Connect
I20160915-11:39:54.422(-5)? Connection established
I20160915-11:39:54.430(-5)? ==Associated
I20160915-11:39:54.434(-5)? Sending command C-FIND-RQ


As you can see there are two important mistakes but that does not prevent it work the viewer:

I20160915-11:38:00.105(-5)? server error {"code":"EADDRNOTAVAIL","errno":"EADDRNOTAVAIL","syscall":"listen","address":"10.14.0.50","port":11112}

I20160915-11:38:47.110(-5)? Invalid length for fixed length tag, vr DA, length 8 !== 6

![captura de pantalla 2016-09-15 a las 12 27 46 p m](https://cloud.githubusercontent.com/assets/11984387/18560134/ef072276-7b3f-11e6-86ae-ee657cf55ff5.png)

On the other hand I see that is a bit slow load the worklist , and move from one sheet to another takes a long time , if not because I have more than 80,000 studies. although I will continue testing performance.

Greetings.

**Comment by swederik** [comment]
I don't know why this branch was never merged before, but @weiwei-ohif's fix was just merged (https://github.com/OHIF/Viewers/commit/c5596128c1e327499bcbe86357fa83422aa18e04). Thanks for the report and thanks @weiwei-ohif for the fix!
