### ISSUE TITLE
Trouble changing wwwc in modality DX !

### ISSUE THREAD

**Issue by 15895860324** [OHIF/Viewers#390]
I can reset the wwwc of images(DX),but there are no changes in viewerport.JUST the modality DX can not adjust,CT,MR are OK.Someone have the same issue like this?Can someone solve it,thanks!!!

**Comment by dannyrb** [comment]
Hi 👋, I would be more than happy to look into this if you were to provide a minimal reproduction.

Ideally, in a GitHub repo, or at a minimum, the DX image(s) you are experiencing this issue with. If the issue is reproducible on our [live viewer](https://viewer.ohif.org/), a link to a study that reproduces the issue, and the steps required to reproduce it, would suffice.

**Comment by 15895860324** [comment]
> Hi 👋, I would be more than happy to look into this if you were to provide a minimal reproduction.
> 
> Ideally, in a GitHub repo, or at a minimum, the DX image(s) you are experiencing this issue with. If the issue is reproducible on our [live viewer](https://viewer.ohif.org/), a link to a study that reproduces the issue, and the steps required to reproduce it, would suffice.
Hello，now i have no way import DX image to [live viewer](https://viewer.ohif.org/).I can change wwwc of DX image in other DICOM viewer，so issue may happen in codes.I email the demo to you or can you email me a demo ，then  i have a try.

**Comment by swederik** [comment]
It is probably applying a VOI LUT embedded in the DICOM file, which will lock your WW/WC while it is applied. See https://rawgit.com/cornerstonejs/cornerstone/master/example/modalityAndVIOLut/index.html

You can test it here: https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

Uncheck the Apply VOI LUT box, and see if you can use W/L.

**Comment by 15895860324** [comment]
> It is probably applying a VOI LUT embedded in the DICOM file, which will lock your WW/WC while it is applied. See https://rawgit.com/cornerstonejs/cornerstone/master/example/modalityAndVIOLut/index.html
> 
> You can test it here: https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html
> 
> Uncheck the Apply VOI LUT box, and see if you can use W/L.

sorry，i can not test the image，when i select the image，it shows 【object object】on the head，i think the example can not cover the type of my image
