### ISSUE TITLE
ADD cobb angel

### ISSUE THREAD

**Issue by niepan11** [OHIF/Viewers#3908]
### What feature or change would you like to see made?

In the latest version of ohif, it seems that the cobb angle measurement function cannot be used. We hope to add this measurement function

### Why should we prioritize this feature?

Cobb angle measurement is widely used in orthopedics. Without this function, ohif would lose the enthusiasm of orthopedic doctors, which is regrettable

**Comment by fgjruiz** [comment]
I may be mistaken, but I believe that the cobb angle tool was moved to Cornerstone.js.  https://tools.cornerstonejs.org/examples/tools/cobb-angle.html

**Comment by niepan11** [comment]
> I may be mistaken, but I believe that the cobb angle tool was moved to Cornerstone.js. https://tools.cornerstonejs.org/examples/tools/cobb-angle.html

Can you tell me specifically how to operate it so that I can use Cobb? In the interface of the latest version of the software, I cannot find the cobb measurement tool

**Comment by sedghi** [comment]
I think there is enough request from community that we should add this

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
