### ISSUE TITLE
Displaying a PlanarFreeHandROI saved in dcm4chee does not work 

### ISSUE THREAD

**Issue by abdou-chakhkhar** [OHIF/Viewers#3910]
### Describe the Bug

I integrated PlanarFreehandROI and i can draw it, save it to dcm4chee but displaying it after this save is not working?

### Steps to Reproduce

1. Integrate PlannarFreeHand 
2. Connect to ohif
3. Draw a PlanarFreeHand save it to dcm4chee
4. Reload the page and Doubleclick on the Saved SR 

### The current behavior

the SR is not displayed

### The expected behavior

The SR should be visible

### OS

Ubuntu 22.04

### Node version

18

### Browser

Chrome

**Comment by sedghi** [comment]
this has been fixed
