### ISSUE TITLE
[Bug] Incorrect crosshairs when 2nd series is loaded in MPR mode

### ISSUE THREAD

**Issue by 03shek** [OHIF/Viewers#3911]
### Describe the Bug

MPR crosshairs is not resetting when 2nd series is loaded in MPR mode, leading to incorrect crosshairs across axial/sagittal/coronal views

### Steps to Reproduce

1. Load a PET-CT study https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463
2. Load CT series into viewport
3. Load MPR mode
4. Enable crosshairs
5. Move crosshairs to Right shoulder in coronal view
![crosshairs_1_loadedfirstseriesMPR](https://github.com/OHIF/Viewers/assets/115667958/f357046b-97ab-4689-90ad-2987dfc48853)

6. Do not disable crosshairs. Exit out of MPR mode.
7. Load PET series into viewport
8. Load MPR mode. Crosshairs is already visible, but button is not enabled.

9. Crosshairs is also not centered on the FOV of this new series; but still on Right shoulder in coronal panel, and now misaligned in axial and sagittal panel
![crosshairs_1_loadedsecondseriesMPR](https://github.com/OHIF/Viewers/assets/115667958/52f776dc-f9f9-41e6-b69b-cf8f916b2521)
![crosshairs_1_loadedsecondseriesMPRnowwrong](https://github.com/OHIF/Viewers/assets/115667958/7ddef188-c4d4-4cdc-a79c-ceb7a7839249)

### The current behavior

Crosshairs is persisting from last MPR mode (different series) and 1) not disabled, and 2) not centered on the current series's FOV.

### The expected behavior

Like in v3.7.0, if a series different from the last is opened in MPR mode, no crosshairs should be visible immediately after opening MPR mode. And crosshairs should need manual enabling to become visible. Once enabled, it should default to the center of the FOV. 

### OS

Windows 10

### Node version

3.8.0-beta.51

### Browser

Chrome 120.0.0

**Comment by jenny-hm-lee** [comment]
@dxlin , please look into this.

**Comment by sedghi** [comment]
i think this is fixed in master, re open if still an issue

**Comment by jenny-hm-lee** [comment]
@sedghi , please re-open this issue.  See #4088

**Comment by IbrahimCSAE** [comment]
This has been fixed by the crosshair changes in https://github.com/OHIF/Viewers/pull/4113
