### ISSUE TITLE
[Bug] Adding support of FreehandROI - Click -> Draw -> save -> view -> reload the page -> (Don't see any freehandroi Drawing)

### ISSUE THREAD

**Issue by ShubhamHiteshi** [OHIF/Viewers#3913]
### Describe the Bug

While creating a SR with FreehandRoI after Draw -> save -> view -> reload the page -> We don't see any drawing on it. 
Could someone please help on this ?

### Steps to Reproduce

1. Add FreeHandRoI support on viewer.
2. Open Viewer 
3. Create any Draw.
4. Save Report
5. Reload the page
6. Again open viewer and report 
7. It doesn't show what we've draw on it. 

### The current behavior

While creating a SR with FreehandRoI after Draw -> save -> view -> reload the page -> We don't see any drawing on it. 
Could someone please help on this ?

### The expected behavior

After saving the SR with FreehandRoi should work after reloading the page too.

### OS

macOS Ventura 13.0

### Node version

18.12.0

### Browser

Chrome

**Comment by sedghi** [comment]
this has been fixed
