### ISSUE TITLE
Investigational Use Display Changes

### ISSUE THREAD

**Issue by james-hanks** [OHIF/Viewers#3916]
We are moving the investigational use only message off the toolbar to make room for functional information.

The investigational use only message will always be displayed in the About page.

There shall be a prompt to end users on the first OHIF page they visit upon a new session. 
The prompt shall display the investigational use only message and require user interaction to close the dialog.
The display properties of the dialog are configurable at install level as follows:
- Never show dialog
- Always show dialog
- Show once and do not show after user closes dialog, with configurable number of days to be shown again and require user to close again. There shall be a comment in the code and deployment guide explaining this behavior 

Design added Feb 28, @dan-rukas 

![Image](https://github.com/OHIF/Viewers/assets/2745168/778c1014-46af-463d-9ec2-f1f20e5c85c9)

![Image](https://github.com/OHIF/Viewers/assets/2745168/de48e3e0-72f4-48d9-999d-b904a806c006)

**Comment by dan-rukas** [comment]
Here is the final messaging design component


![Image](https://github.com/OHIF/Viewers/assets/2745168/778c1014-46af-463d-9ec2-f1f20e5c85c9)

![Image](https://github.com/OHIF/Viewers/assets/2745168/de48e3e0-72f4-48d9-999d-b904a806c006)

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
