### ISSUE TITLE
[Bug] If opened in Basic Mode first, clicking the "Add Segmentation" button causes zoomed in 

### ISSUE THREAD

**Issue by jenny-hm-lee** [OHIF/Viewers#3925]
### Describe the Bug

If a study is opened in Basic Mode first and in segmentation mode next,  clicking the "Add Segmentation" button causes zoomed in. 

### Steps to Reproduce

1. go https://viewer-dev.ohif.org/
2. Open any study in basic mode
3. Return to study list
4. Open the same study in segmentation mode.  Note the image is displayed correctly.
5. Click "Add Segmentation"
6. The images is black or grey, and not longer displayed correctly.

### The current behavior

after step (5), the image is black or grey, and no longer displayed.  This is because the image is zoomed out.

### The expected behavior

The images should be correctly displayed.

### OS

Windows 10

### Node version

v16.17.0

### Browser

Chrome Version 114.0.5735.110

**Comment by sedghi** [comment]
can't reproduce it anymore in latest master
