### ISSUE TITLE
[Feature Request] Support visualization and overlay of SEG that do not include referenced SeriesInstanceUID

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#3936]
### What feature or change would you like to see made?

Currently, OHIF will only allow visualization of SEG series that include reference to the image series included in `SourceImageSequence` in the per-frame functional groups and in the top-level `ReferencedSeriesSequence`. I am not sure which of those, or if both, are checked and used by OHIF, but note that it is not possible/not allowed to have a series referenced in `ReferencedSeriesSequence` and not used in the `SourceImageSequence` in per-frame FGs - for the related discussion see https://github.com/QIICR/dcmqi/issues/489.

Therefore, the proposal is to add a feature that would  allow users to show SEG over any of the series within a given study as long as they share `FrameOfReferenceUID`.

You can see one example of a study that contains this kind of SEG in Imaging Data Commons:
* OHIF v2: https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.260497661906193334514226770342365856579
* OHIF v3: https://viewer.imaging.datacommons.cancer.gov/v3/viewer/?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.260497661906193334514226770342365856579
* instructions to download the DICOM files for the study above:
```bash
$ pip install idc-index
```
then
```python
from idc_index import index

c=index.IDCClient()
c.download_from_selection(studyInstanceUID="1.3.6.1.4.1.14519.5.2.1.260497661906193334514226770342365856579", destinationDir="<folder where to download>")
```

This data is available under CC-BY license. When using the data, please make sure to comply with the attribution requirements as listed here: https://dx.doi.org/10.7937/3RAG-D070.

cc: @pieper @dclunie 

### Why should we prioritize this feature?

The aforementioned references are optional whenever geometry information is available in the shared/per-frame FGs (which is the case in all SEGs I encountered). Furthermore, it is unclear/difficult/not possible to encode references to the segmented image in the situations where segmentation slices are not aligned with those of the segmented image (as discussed in https://github.com/QIICR/dcmqi/issues/489). Consequently, it is the case that users of OHIF will encounter situations where valid SEG series would not be possible to visualize in the viewer.

**Comment by sedghi** [comment]
related https://github.com/OHIF/Viewers/issues/3936
