### ISSUE TITLE
Infinite loop when using Ohif viewer + dcm4chee + keycloak

### ISSUE THREAD

**Issue by MatheusRdk** [OHIF/Viewers#3938]
### Describe the Bug

Hello! I’m seeking guidance on how to properly integrate the OHIF Viewer with Keycloak 23.0.6. I already have OHIF installed and a PACS setup (Dcm4chee, using WSL and docker), and I’m looking to add security (login and password) to the viewer. I managed to install and run Keycloak on Docker, and here’s what I did in the viewer config file:

```
oidc: [
    {
      authority: 'http://localhost:7080/realms/ohif',
      client_id: 'ohif-viewer',
      redirect_uri: 'http://localhost:3000/',
      response_type: 'code',
      scope: 'openid',
      //post_logout_redirect_uri: '/logout-redirect.html',
    },
  ],
```

However, upon initiating OHIF at localhost:3000, I encounter the Keycloak login screen, but after successful login, a loop occurs where the URL loads http://localhost:3000/ and also this URL: http://localhost:3000/?state=516d35530a7545b8895514e710393ccc&session_state=95a5052b-483c-40f9-9fd6-33b06beb5199&iss=http%3A%2F%2Flocalhost%3A7080%2Frealms%2Fohif&code=1bad81da-4c0e-4a1c-8bcd-15aa6e1685b5.95a5052b-483c-40f9-9fd6-33b06beb5199.945c8d99-d2a4-42a9-a422-634b1cdca822

It’s stuck in an infinite loop of this. Attached is a screenshot of the console:
![793abb6ebc8a5fb234bb54485ca9f42a5561c554_2_569x500](https://github.com/OHIF/Viewers/assets/119511463/183cc362-ae92-40fa-85bf-84c11b3bb85b)

I’d like to understand what I need to make this work. Do I need to use the recipe from the .recipe folder of OHIF? However, there’s no recipe for dcm4chee with Keycloak, only for Orthanc. I want only registered users on keycloak can access the ohif viewer

Could the loop be due to the keycloak realms? Would I have to have everything configured correctly within keycloak according to the file that creates the realms available in the files?

### Steps to Reproduce

1. Install ohif viewer;
2. Install dcm4chee and set as the viewer pacs (optional, the problem occurs either with or without dcm4chee installed);
3. Install keycloak 23, default docker installation guides
4. In keycloak console, create the ohif realm, ohif-viewer client and a user
6. Set the oidc variable in the viewer config file
oidc: [
    {
      authority: 'http://localhost:7080/realms/ohif',
      client_id: 'ohif-viewer',
      redirect_uri: 'http://localhost:3000/',
      response_type: 'code',
      scope: 'openid',
      //post_logout_redirect_uri: '/logout-redirect.html',
    },
  ],
7. Try log in the viewer

### The current behavior

I need to be able to use the viewer after successful login, but a loop starts and nothing appears.
I dont know if it occurs because of viewer config or keycloak config.  
I use dcm4chee but I only want authentication between viewer and keycloak working for testing.

### The expected behavior

Open the viewer and show the studies.

### OS

Windows 10

### Node version

18.15.0

### Browser

Firefox 122.0 / Chrome 121.0.6167.185

**Comment by MatheusRdk** [comment]
Maybe it's a redirection issue? Because the viewer's initial screen is localhost:3000/ , which calls the login screen, and after login the main screen that shows the studies is also just /

**Comment by MatheusRdk** [comment]
I managed to change the behavior. After logging in, it goes to this page.

![1](https://github.com/OHIF/Viewers/assets/119511463/142939c0-0380-4fe7-924d-737ab6910017)
![4](https://github.com/OHIF/Viewers/assets/119511463/bb0aba5c-7a8d-4e5d-9700-8768dc830c62)

I changed the routerBasename, thinking it could be a problem configuring routes between the app and keycloak.
It’s a black screen with no data, and the viewer/viewer path doesn’t exist, I don’t understand how it’s getting there.


![2](https://github.com/OHIF/Viewers/assets/119511463/81b1cfb7-0166-4ad5-b861-f0906364a793)
![3](https://github.com/OHIF/Viewers/assets/119511463/d422ee06-7258-4668-a400-35e911ef294e)
![5](https://github.com/OHIF/Viewers/assets/119511463/460bb230-ba62-4ffb-b1a4-759eea24ba85)

If anyone can help me, I’ve been stuck on this for days, I have little knowledge of JavaScript which makes solving this even more difficult.

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control

**Comment by pragyagm** [comment]
Hi @sedghi 
I tried using the ohif-keycloak-dcm4chee-nginx recipe. Ran it locally as per your video, but when i login to viewer, I get a 500 error on /pacs url
<img width="1500" alt="Screen Shot 2024-07-20 at 5 10 54 PM" src="https://github.com/user-attachments/assets/2da7729a-5726-4031-9c11-6968b3d40438">
