### ISSUE TITLE
This error occurred when yarn run dev

### ISSUE THREAD

**Issue by hfutgm** [OHIF/Viewers#3940]
### Describe the Bug

PS D:\VScode_project\Viewers-master> yarn run dev
yarn run v1.22.21
$ lerna run dev:viewer --stream
(node:9444) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
lerna notice cli v7.4.2

> @ohif/app:"dev:viewer"

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@ohif/app: **error** TypeError: Cannot create property 'https' on string 'https://registry.npmmirror.com'
@ohif/app:     at set (D:\environment\nvm\v21.6.2\node_modules\yarn\lib\cli.js:53964:28)
@ohif/app:     at set (D:\environment\nvm\v21.6.2\node_modules\yarn\lib\cli.js:53968:14)
@ohif/app:     at set (D:\environment\nvm\v21.6.2\node_modules\yarn\lib\cli.js:53948:16)
@ohif/app:     at objectPath.set (D:\environment\nvm\v21.6.2\node_modules\yarn\lib\cli.js:54001:14)
@ohif/app:     at NpmRegistry.mergeEnv (D:\environment\nvm\v21.6.2\node_modules\yarn\lib\cli.js:92144:18)
@ohif/app:     at NpmRegistry.<anonymous> (D:\environment\nvm\v21.6.2\node_modules\yarn\lib\cli.js:31953:12)
@ohif/app:     at Generator.next (<anonymous>)
@ohif/app:     at step (D:\environment\nvm\v21.6.2\node_modules\yarn\lib\cli.js:310:30)
@ohif/app:     at D:\environment\nvm\v21.6.2\node_modules\yarn\lib\cli.js:328:14
@ohif/app:     at new Promise (<anonymous>)

### Steps to Reproduce

1、yarn insall succeeded
2、yarn run dev an error occurred

### The current behavior

yarn run dev an error occurred

### The expected behavior

How to solve？

### OS

windows 10

### Node version

v21.6.2

### Browser

Chrome121.0.6167.185（64 bit）

**Comment by ketki-kerkar** [comment]
I am facing similar issue.
Please let me know if you have found a work around @hfutgm.
Thank you

**Comment by sedghi** [comment]
usually it is your node versions

**Comment by sedghi** [comment]
i see 21, revert to 18
