### ISSUE TITLE
OHIF not working on iOS 16

### ISSUE THREAD

**Issue by napest** [OHIF/Viewers#3941]
### Describe the Bug

Hi! I noticed that OHIF doesn't work on iOS earlier than 17. viewer.ohif.org shows black screen. In our custom viewer based on cornerstone 3D the same happens. All it says (in a Safari mobile debugging mode) is:
![image](https://github.com/OHIF/Viewers/assets/18447985/88bb68b2-668a-4fd0-92ac-906f969f5e65)

Do you plan to support earlier versions of iOS?

### Steps to Reproduce

iOS 16, Safari 16/Chrome. Open viewer.ohif.org

### The current behavior

Black screen 

### The expected behavior

Open normally

### OS

iOS 16

### Node version

latest

### Browser

Chrome, Safari 16

**Comment by ojaspatharkar-qure** [comment]
Facing the exact same issue. Any update on this?

**Comment by sedghi** [comment]
it should work for regular stack viewports, I see some reports for mpr viewports. Can you try viewer-dev.ohif.org?

**Comment by cdamorganda-dev** [comment]
any updates on this?

**Comment by sedghi** [comment]
I created this PR which would be good enough for a lot of use cases (except the PT Scaled data)

https://github.com/cornerstonejs/cornerstone3D/pull/1212

**Comment by mauricio-cdr** [comment]
Hi @sedghi , no, It is a different issue, since commenting on the PR already allows MPR to be carried out correctly in IOS 17.
In iOS 16 the viewer JS cannot be loaded.

https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.5962.99.1.2968617883.1314880426.1493322302363.3.0

**Comment by sedghi** [comment]
@IbrahimCSAE can you emulate and gather more info in the console on what is wrong

**Comment by IbrahimCSAE** [comment]
I'm closing this issue because per this screenshot there's nothing wrong @sedghi 

![Image](https://github.com/OHIF/Viewers/assets/93064150/e9368128-9d68-4f5e-8b9e-40238f43ab3b)
