### ISSUE TITLE
Using Independent Packages

### ISSUE THREAD

**Issue by andrei0807** [OHIF/Viewers#3942]
### What feature or change would you like to see made?

I'm going to change the OHIF viewer a little for me. 
I only need to change the UI, but it is included in the source with other modules, so the source is very big.
Please let me know how to make a project with only UI partial source and use the rest as npm package.
Regards

### Why should we prioritize this feature?

for modularization of the use

**Comment by sedghi** [comment]
you need to clone and create your own extensions and mode https://docs.ohif.org/development/video-tutorials
