### ISSUE TITLE
[Bug] When Create Report for Measurements fails, all measurements are lost

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3944]
### Describe the Bug

Added multiple measurements on multiple viewports for a study. When Create Report is selected and fails, all of the measurements created are lost

### Steps to Reproduce

1. Select study and the Basic Viewer button
2. Went into 2x2 grid layout and created multiple measurements on all viewports
![image](https://github.com/OHIF/Viewers/assets/143200290/2a5e30cf-acc0-4b6a-b701-184fda01f6c3)

3. Select the Create Report button from the measurements panel
4. Entered report name: test & saved = create report request failed message appears in lower right corner
5. All measurements on the viewport & images are gone as well as the measurements in the right side measurements panel
![image](https://github.com/OHIF/Viewers/assets/143200290/efc428b3-2e7a-49c3-9b09-6cb9e0b96ab8)

### The current behavior

measurements lost when create report is selected and fails

### The expected behavior

measurements should be retained when create report selection fails so that the user does not have to recreate them again

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v121

**Comment by james-hanks** [comment]
Fix to keep existing annotations if save fails for any reason (including external)

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
