### ISSUE TITLE
[Bug] Going from 2x2 layout into MPR with measurements then turn off MPR causes black viewports

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3946]
### Describe the Bug

Able to reproduce in OHIF dev version (https://viewer-dev.ohif.org/): 3.8.0-beta.53, Commit hash: 5bba98ed848bdf46b5ba4fc4708527cced3308b5

Turning off MPR to go back into 2x2 grid layout displays black viewports where there used to be measurements on images

### Steps to Reproduce

1. Select CT study (ACRIN-NSCLC-FDG-... WB PET/CT) and go to the viewer screen
2. Go into 2x2 layout
3. Add length measurement in viewport 2 on image 1 & on image 17
4. Add length measurements to viewports 3 & 4 both on image 1
5. Click on Viewport 2 to make it active and select the MPR tool
6. Select the measurements panel to expand it and see the 4 measurements made in steps 3 & 4
8. click on each measurement in the panel to jump to the image with the measurement
9. select the MPR tool to turn it off = the 2x2 layout will display but viewports 2, 3 & 4 are now black and do not display the images. 
If you click on the measurements panel items, the block viewport will display with the length measurements 
![image](https://github.com/OHIF/Viewers/assets/143200290/cd8ad5e3-84f8-422c-8fcf-d60dfdc99966)

### The current behavior

Turn off MPR and go back to 2x2 layout and viewports that previously had measurements are now black

### The expected behavior

Turn off MPR and the 2x2 viewports appear normally with images and measurements as they had before going into MPR

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v121

**Comment by sedghi** [comment]
can't reproduce it anymore

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
