### ISSUE TITLE
[Bug] Length measurements made on MPR images persist after closing study 

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3947]
### Describe the Bug

Length measurements made on MPR sagittal & coronal images persist after closing study and re-open again.

Able to reproduce from dev env (https://viewer-dev.ohif.org/): 3.8.0-beta.53, Commit hash: 5bba98ed848bdf46b5ba4fc4708527cced3308b5

### Steps to Reproduce

1. From the study list select COVID-19-NY-SBU with 477 images and go to the viewer screen
2. Go into 2x2 layout and select viewport 2
3. Click on the MPR tool
4. Make a length measurement on each of the 3 viewports & open the measurements panel = you will see only the axial measurement in the panel
5. Reselect the MPR tool to go back to 2x2 layout
6. Go back to the study list screen by selecting the Open Health Imaging Foundation verbiage in the upper left corner
7. Select the same study and go to the viewer screen
8. Go to 2x2 layout - select viewport 2 and go to the MPR = see the length on the sagittal & coronal views
![image](https://github.com/OHIF/Viewers/assets/143200290/138c1ec3-2576-472d-84f3-20905f5df907)

### The current behavior

Sagittal & Coronal measurements made remain in study after going to the study list (but in same browser session)

### The expected behavior

All measurements should be removed from the study when you leave the viewer screen

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v121

**Comment by james-hanks** [comment]
Fixed https://github.com/OHIF/Viewers/pull/3983

Re-test in 3.8.0-rc1

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
