### ISSUE TITLE
[Bug] Tool Tip Does not Disappear 

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3948]
### Describe the Bug

The Grid Layout tool tip remains on the screen well after it is selected

Able to reproduce in OHIF dev env (https://viewer-dev.ohif.org/): 3.8.0-beta.53, Commit hash: 5bba98ed848bdf46b5ba4fc4708527cced3308b5

### Steps to Reproduce

1. Display any study
2. Change Grid Layout to 2x2
3. Note that the tooltip persists until the mouse is moved over the tooltip
![image](https://github.com/OHIF/Viewers/assets/143200290/af20b61c-b95a-4ee8-886b-46e27ca56d7f)

### The current behavior

Tool tip remains on screen ever after performing another task (ex: creating a new length measurement)

### The expected behavior

Tooltips should go away after using the feature

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v121

**Comment by james-hanks** [comment]
@IbrahimCSAE could you confirm this won't happen in the new layout selector?

**Comment by IbrahimCSAE** [comment]
@james-hanks this will be fixed.
