### ISSUE TITLE
[Bug] TMTV SUV Peak NaN Value & Console Uncaught Exception

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3949]
### Describe the Bug

Creating an ROI Rectangle on the PT axial, then a length measure on the CT in the same area. Then create the label and run the segmentation causes a NaN pack value + uncaught exception 

this is reproducible in OHIF dev env (https://viewer-dev.ohif.org/): 3.8.0-beta.53, Commit hash: 5bba98ed848bdf46b5ba4fc4708527cced3308b5

### Steps to Reproduce

1. filter study list by modality PT
2. Select study ACRIN-NSCLC-FDG-... with 934 instances
3. Select the TMTV button
4. Select the Rectangle ROI Threshold tool
5. Click on the PT-axial image and create the rectangle
6. Select the length tool and create a line in the same area as the rectangle was created but make the line in the CT-axial image
7. From within the ROI Threshold panel, select the New Label button
8. Click on the PT - axial image, rectangle to make it green then select the Run button (from the right-side panel) = console error
9. The ROI Threshold panel - SEGMENTATIONS section will display the SUV Peak: NaN value
Note: may have to repeat steps 7-10 for a second label and rectangle
![image](https://github.com/OHIF/Viewers/assets/143200290/676dfc89-dabd-4dbc-a9f7-775c65e29cd6)

### The current behavior

SUV Peak NaN value + console error

### The expected behavior

valid SUV Peak value & no issues in console

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v121

**Comment by james-hanks** [comment]
I think this is expected but we should throw some type of user feedback

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
