### ISSUE TITLE
[Bug] Delete Measurement does not work after viewing SM study

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3950]
### Describe the Bug

Can no longer delete measurements after attempting to view an SM study (that creates a console error)

Able to reproduce in OHIF dev env (https://viewer-dev.ohif.org/): 3.8.0-beta.53, Commit hash: 5bba98ed848bdf46b5ba4fc4708527cced3308b5

### Steps to Reproduce

1. Filter the study list by modality SM 
2. Open the developer's console
3. Select the SM study and click on the Microscopy button = error in the console
![image](https://github.com/OHIF/Viewers/assets/143200290/c4e3463f-5141-4a91-9ca6-030797c8b1f7)

4. Go back to the study list and select the viewer button for a study (I used CTA Head and Neck with 295 CT instances)
6. create a measurement and right-click to try and delete the measurement = will not delete
7. Try any other study and have the same result. Cannot delete measurements until i clear my cache, start a new browser session and start over

### The current behavior

cannot delete measurements after trying to view an SM study

### The expected behavior

i should always be able to delete a measurement

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v121

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
