### ISSUE TITLE
[Bug] Zoom tool in touch mode

### ISSUE THREAD

**Issue by linkDicomDev** [OHIF/Viewers#3952]
### Describe the Bug

** _The Zoom tool in touch mode behaves like the Pan tool.._**

https://github.com/OHIF/Viewers/assets/155246686/aaf3788f-1bd2-4661-a8a4-034cef4945e6

### Steps to Reproduce

https://github.com/OHIF/Viewers/assets/155246686/aaf3788f-1bd2-4661-a8a4-034cef4945e6

### The current behavior

[sdsd](https://github.com/OHIF/Viewers/assets/155246686/aaf3788f-1bd2-4661-a8a4-034cef4945e6)

### The expected behavior

https://github.com/OHIF/Viewers/assets/155246686/aaf3788f-1bd2-4661-a8a4-034cef4945e6

### OS

w11

### Node version

20

### Browser

chrome

**Comment by haldawe2** [comment]
I believe this is caused by the variable "pinchToZoom: true" enabled by default on the ZoomTool configuration.

I extended the class (to modify it outside of node_modules) and turned it to false and now works as expected.

**Comment by torniker** [comment]
@haldawe2 Could you please share what you've changed to make `pinchToZoom: false`

**Comment by haldawe2** [comment]
No problem at all :) In orther to expose the class you have to import and extend it. Once done, you have to export it and make sure you update the new tool on your Mode files.

In my case I called it InvertedZoom because we wanted to invert the direction of the zoom through settings and had to expose the "invert" property.

`import { ZoomTool } from '@cornerstonejs/tools';

/**
 * ZoomTool tool manipulates the camera zoom applied to a viewport. It
 * provides a way to set the zoom of a viewport by dragging mouse over the image.
 *
 */
class ZoomInvertedTool extends ZoomTool {
  constructor(toolProps = {}, defaultToolProps = {
    supportedInteractionTypes: ['Mouse', 'Touch'],
    configuration: {
      // whether zoom to the center of the image OR zoom to the mouse position
      zoomToCenter: false,
      minZoomScale: 0.1,
      maxZoomScale: 30,
      pinchToZoom: false,
      pan: true,
      invert: false,
    },
  }) {
    super(toolProps, defaultToolProps);
    // other code in here
}

ZoomInvertedTool.toolName = 'ZoomInverted';
export default ZoomInvertedTool;`

Hope that helps!

**Comment by sedghi** [comment]
i guess this is done?

**Comment by linkDicomDev** [comment]
I was able to solve it, thanks for the help. 👍

**Comment by wangning08115** [comment]
@linkDicomDev How can you solve it? i have same problem.
can you help me?

**Comment by wangning08115** [comment]
Thanks @haldawe2   i use your code, run fine.

bleow is my code：

`import { ZoomTool } from '@cornerstonejs/tools';

/**
 * ZoomTool tool manipulates the camera zoom applied to a viewport. It
 * provides a way to set the zoom of a viewport by dragging mouse over the image.
 * 这里重写了默认的 ZoomTool
 * 这个写法来自一个网友  https://github.com/OHIF/Viewers/issues/3952  实测很好用啊
 */
class ZoomToolTouch extends ZoomTool {
  constructor(
    toolProps = {},
    defaultToolProps = {
      supportedInteractionTypes: ['Mouse', 'Touch'],
      configuration: {
        // whether zoom to the center of the image OR zoom to the mouse position
        zoomToCenter: false,
        minZoomScale: 0.1,
        maxZoomScale: 30,
        pinchToZoom: false,
        pan: true,
        invert: false,
      },
    }
  ) {
    super(toolProps, defaultToolProps);
    // other code in here
  }
}

ZoomToolTouch.toolName = 'Zoom';
export default ZoomToolTouch;
`

And：

change file D:\OhifViewerV3\extensions\cornerstone\src\initCornerstoneTools.js
`  //addTool(ZoomTool); 这里重写了默认的 ZoomTool
  addTool(ZoomToolTouch);`

And ：
`const toolNames = {
  Pan: PanTool.toolName,
  ArrowAnnotate: ArrowAnnotateTool.toolName,
  WindowLevel: WindowLevelTool.toolName,
  StackScroll: StackScrollTool.toolName,
  StackScrollMouseWheel: StackScrollMouseWheelTool.toolName,
  Zoom: ZoomToolTouch.toolName, //Change the Zoom to ZoomToolTouch.toolName ` 

Then run fine on mobile

**Comment by arturojain** [comment]
Zoom now works with @wangning08115 and @haldawe2 answers.

Is pinchToZoom a bug?

**Comment by Rajat-eng** [comment]
If I want pinchtoZoom, it zooms the whole screen. How will I be able to resolve that

**Comment by Rajat-Imme** [comment]
> i guess this is done?

Even if the issue is resolved temporarily, @haldawe2 has mentioned that two fingers pinch on screen zooms whole screen , rather than actual image. 

Any suggestion , how could we resolve that?
