### ISSUE TITLE
Unnable to use Dcm4chee secure + Ohif

### ISSUE THREAD

**Issue by MatheusRdk** [OHIF/Viewers#3957]
### Describe the Bug

![image](https://github.com/OHIF/Viewers/assets/119511463/d4cd46b6-1ccc-4643-8e8c-692fcb87efe6)
Black screen and error, i tried a lot of different configs.

### Steps to Reproduce

1.Install dcm4chee secured version
2.Ohif

Set oidc (this is how mine default.js is now):
![image](https://github.com/OHIF/Viewers/assets/119511463/7ef0c29f-1e73-427c-b09a-45c6a800334f)
Realm
![image](https://github.com/OHIF/Viewers/assets/119511463/5a2a8ae8-dfa0-4f31-9b8d-23164a1bbab2)

Datasource in default.js
![image](https://github.com/OHIF/Viewers/assets/119511463/32a082c6-1b1c-41b8-9857-52a4214aace3)

### The current behavior

Black screen and a log showing Cannot read properties of null (reading 'access_token')

### The expected behavior

I want to be able to use ohif secured. Should i create a realm or a new client in keycloak? But how to access protected images from dcm4chee?

### OS

Windows 10

### Node version

18.12.0

### Browser

Firefox 121.0 | Chrome

**Comment by sedghi** [comment]
what is the recipie you are following, it is ours? or your custom docker?

**Comment by MatheusRdk** [comment]
> what is the recipie you are following, it is ours? or your custom docker?

in this case it was my own. But I managed to make it work with yours.

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
