### ISSUE TITLE
[Bug] can not open the US file 

### ISSUE THREAD

**Issue by gupengju1024** [OHIF/Viewers#3958]
### Describe the Bug

[docpm.dcm.zip](https://github.com/cornerstonejs/cornerstone3D/files/14381376/docpm.dcm.zip)
can not render this file
![image](https://github.com/OHIF/Viewers/assets/23445960/4c851be5-c5c7-463e-bf5a-bfcb4e08b8d8)

### Steps to Reproduce

use  https://v3-demo.ohif.org/local open the file ,can not open 

### The current behavior

use  https://v3-demo.ohif.org/local open the file ,can not open 

### The expected behavior

use  https://v3-demo.ohif.org/local open the file ,can not open 

### OS

win11 and mac os

### Node version

16

### Browser

chrome

**Comment by sedghi** [comment]
seems like we don't have support for this SOPClassUID: 1.2.840.10008.5.1.4.1.1.3 [Ultrasound Multi-frame Image Storage (Retired)]

**Comment by gupengju1024** [comment]
> seems like we don't have support for this SOPClassUID: 1.2.840.10008.5.1.4.1.1.3 [Ultrasound Multi-frame Image Storage (Retired)]

thanks for your reply

**Comment by gupengju1024** [comment]
Hi,do you have a plan to support this SOPClassUID?

**Comment by sedghi** [comment]
@wayfarer3130 what do you think

**Comment by wayfarer3130** [comment]
> @wayfarer3130 what do you think

Should be as easy as just adding it to the list of supported classes.  I don't think there is anything special about this one, but I don't know offhand.

**Comment by sedghi** [comment]
Seems like it is a retired transfer syntax, and when I tried, it didn't seem easy to add.

https://www.dicomlibrary.com/dicom/sop/

![CleanShot 2024-05-21 at 17 44 20@2x](https://github.com/OHIF/Viewers/assets/7490180/833a1698-c7bb-4434-aeb8-478be365b861)
