### ISSUE TITLE
[Bug] Probe tool on US images are not working

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3966]
### Describe the Bug

Found in the dev env (https://viewer-dev.ohif.org/) on build: 3.8.0-beta.56, Commit hash: 21e8a2bd0b7cc72f90a31e472d285d761be15d30, on a mac (sonoma 14) + chrome browser (v122)

Cannot use the probe tool on US images with the latest dev build. It will create a small circle on the image that stays there without values. Moving the mouse does not move the probe icon as expected. There is also an error in the console:
![image](https://github.com/OHIF/Viewers/assets/143200290/bc23a208-73a9-47f3-bec8-4b1b843b5449)

After this, you cannot create & see other measurements but they appear in the measurements panel as an 'empty' measurement
![image](https://github.com/OHIF/Viewers/assets/143200290/f6101c3a-91f2-4ee2-915f-83105707ad29)

### Steps to Reproduce

1. from the study list select a US study and go to the viewer page
2. Select the probe tool 
3. From the image try to use the tool by a click in the viewport then move the mouse over the image

### The current behavior

- the mouse click and move mouse creates a small circle on the image and you cannot move it as i usually do to see the HU 
- error in the console
- cannot create any other measurement types on the image after this point 
- any attempted measurements  appear as empty items in the measurements panel

### The expected behavior

- I should be able to select the probe tool click on the image and hover over it to see the small circle move over the image and present the HU values as I move over the image
- there should be no errors in the console
- i should be able to create measurements of any kind and see them on the image and values in the measurements panel

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v122

**Comment by james-hanks** [comment]
This might be due to #3721 being in progress. Will confirm

**Comment by james-hanks** [comment]
Fixed in 3.8
