### ISSUE TITLE
[Bug] Existing SR items are not displaying measurements on image when selected from the measurements panel

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3967]
### Describe the Bug

Found in the OHIF dev env (https://viewer-dev.ohif.org/), 3.8.0-beta.56, Commit hash: 21e8a2bd0b7cc72f90a31e472d285d761be15d30 - tested on a mac + chrome browser

Existing SR items are not displaying measurements on the image. I dragged an existing SR into the viewport and then opened the measurements panel that displayed 2 existing measurements. I selected each from the panel and the correct image (as noted in the panel) was displayed but no measurements appeared on the image.
![image](https://github.com/OHIF/Viewers/assets/143200290/89d71693-ddfa-4d26-bf01-bab3ebdcb6bb)

I did go back and repeated the same steps with the same image in the OHID prod env (https://viewer.ohif.org/) with version 3.7.0,  Commit Hash: 5ddf8a16027255d28dc01c1740099cf85bbcf458 - and the measurements displayed on the SR images correctly. 
**Also note, that as you compare the 2 screenshots, the one from the dev env is also missing info on the measurements panel regarding item 1 for units of measure + max info
![image](https://github.com/OHIF/Viewers/assets/143200290/d0350a07-a8f6-45d1-bde5-cfffd1dfa89d)

### Steps to Reproduce

1. From the study list filter by modality: SR
2. Select study TCGA-09-1667 with 77 instances and go to the viewer page
3. Drag the SR thumbnail from the study panel to the 1x1 viewport
4. Open the measurements panel and click on each item (there should be 2 existing measurements for this SR) 
5. As you click on each item in the panel, the image displays with the measurement 

### The current behavior

SR existing measurements are not appearing on the image noted in the right-side panel

### The expected behavior

As you select items from the measurements panel for an existing SR, the correct image will display with the noted measurement on it

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v122

**Comment by sedghi** [comment]
This is fixed in master right now

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
