### ISSUE TITLE
MPR of big serie slice images error

### ISSUE THREAD

**Issue by nicoesiea** [OHIF/Viewers#3968]
### Describe the Bug

👋, I'm using the 3.6.0 OHIF viewer version and I'm trying to use MPR a CT series containing **1461** images.
The screen becomes completely black and then, the MPR three grids are visible but empty:
![image](https://github.com/OHIF/Viewers/assets/4542315/5ffa6de9-8f18-44ff-aa68-f5b301a5d442)

By opening the Chrome (Version 122.0.6261.70 (Build officiel) (64 bits)) debugger tool, I can see two major errors in the console:
![image](https://github.com/OHIF/Viewers/assets/4542315/96110885-9ab9-411f-bd24-646b81988fb5)
and
![image](https://github.com/OHIF/Viewers/assets/4542315/b5298541-64a9-4045-bcff-36378b24fb99)

I already read this other issue: https://github.com/OHIF/Viewers/issues/1438
But it was closed without any solution.

By any chance, do you believe it could be already fixed in the new version? Or is this bug ticket relevant, as long as the bug is still occuring?

### Steps to Reproduce

Load a Study with a CT modality series, Vol CTA was my example, with number of slices: 1461
click on MPR tool

### The current behavior

black screen then empty three grid 

### The expected behavior

MPR is generated, or at least there is a limitation warning or error message.

### OS

Windows 10

### Node version

16.18.1

### Browser

Chrome (Version 122.0.6261.70 (Build officiel) (64 bits)

**Comment by nicoesiea** [comment]
Please note that using Firefox, the error message has a better visibility
![image](https://github.com/OHIF/Viewers/assets/4542315/3c99e219-fb72-45cf-a9c1-0987c129ee74)

**Comment by sedghi** [comment]
can you see this https://docs.ohif.org/faq#how-do-i-handle-large-volumes-for-mpr-and-volume-rendering
