### ISSUE TITLE
[Bug] Segmentation mode - Circle Shape disappears on image

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3969]
### Describe the Bug

found in the OHIF dev env (https://viewer-dev.ohif.org/): 3.8.0-beta.56, Commit hash: 21e8a2bd0b7cc72f90a31e472d285d761be15d30, on a mac + chrome browser

While in segmentation mode, the Circle Shape will disappear after adding it to an image. With the console open, you will see an uncaught error when this happens:
![image](https://github.com/OHIF/Viewers/assets/143200290/0a227e64-3036-47ba-841c-c518fd01efe3)

Note: the rectangle & sphere shapes are not an issue as they stay on the image

### Steps to Reproduce

1. From the study panel select: Neptune and click on the segmentation button = 2x2 grid layout and the segmentation panel is expanded
2. Open the developer's console
3. From the right-side panel select the + Add Segment verbiage = Segment 1 with a red dot displays
4. Select the Shape icon from the Segmentation Tools section and then select the Circle option
5. Click on viewport B and create a circle = an uncaught error appears in the console
6. Then create a second circle  = both circles disappear
7. IF the circle remains on the image complete this step...Select the Rectangle option from the shapes and create a rectangle on the same image in viewport B = the circle disappears

### The current behavior

Circle shapes for segmentation disappear off of the image and there is an error in the console

### The expected behavior

circle segmentation shapes remain on the image

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v122

**Comment by sedghi** [comment]
Segmentation is referenced series dependent, when you create a labelmap on one series, you can't edit the other one

**Comment by james-hanks** [comment]
Same fix for #3976

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
