### ISSUE TITLE
[Bug] Frame-ancestors not working with ohif-keycloak

### ISSUE THREAD

**Issue by MatheusRdk** [OHIF/Viewers#3970]
### Describe the Bug

I have the OHIF protected with Keycloak using the recipe OpenResty-Orthanc-Keycloak, and it's working fine. However, I want to embed it in an iframe in my app running on localhost:8000. The viewer without authentication works normally, but when using Keycloak and trying to load it within my app, I receive the error `'Refused to frame 'http://127.0.0.1/' because an ancestor violates the following Content Security Policy directive: 'frame-ancestors 'self'.'`

From what I've read in my research, it seems I need to change the 'frame-ancestors' directive of the Content-Security-Policy to allow my app's host. The Content-Security-Policy configurations I found in OHIF were in the directory ohif\platform\app.recipes\OpenResty-Orthanc-Keycloak\config\ohif-keycloak-realm.json under the fields 'contentSecurityPolicy' and '_browser_header.contentSecurityPolicy'.

Here's my configuration:
`'contentSecurityPolicy': 'frame-src 'self'; frame-ancestors 'http://localhost:8080/*'; object-src 'none';'`

`'_browser_header.contentSecurityPolicy': 'frame-src 'self'; frame-ancestors 'http://localhost:8080/*'; object-src 'none';'`

However, I'm still encountering the same error. The config is correct, or is there something else missing?

### Steps to Reproduce

1.Install ohif secured with keycloak;
2.Create an app that use the ohif app as an iframe;

### The current behavior

Even after setting the Content Security Policy values apparently correctly, the error `'Refused to frame 'http://127.0.0.1/' because an ancestor violates the following Content Security Policy directive: 'frame-ancestors 'self'.'` persists.

### The expected behavior

Have ohif secured with keycloak on my app's page.

### OS

Windows 10

### Node version

18.12.0

### Browser

Firefox 121.0 | Chrome

**Comment by sedghi** [comment]
if you have successfully integrated OHIF and keycloak can you please update on the previous issues, are they closable? maybe answer to your issues?

-https://github.com/OHIF/Viewers/issues/3957
-https://github.com/OHIF/Viewers/issues/3938

**Comment by MatheusRdk** [comment]
Yeah, they are already resolved. Thank you.

**Comment by sedghi** [comment]
Did you use the latest Keycloak? I know our version is quite outdated, so if you have the latest setup, we would appreciate a pull request.

**Comment by MatheusRdk** [comment]
Not really, I did it another way. However, I can update the recipe's docker-compose to a more recent keycloak, I believe it only changes the names of the environment variables.

**Comment by sedghi** [comment]
Sure we appreciate a PR

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
