### ISSUE TITLE
Build issue for Viewer

### ISSUE THREAD

**Issue by ParthPatel-DA** [OHIF/Viewers#3971]
### Describe the Bug

I am trying to build the Viewer for iframe in React but it give error as below. This error coming when we load the build in iframe for our React project. Can you please help to resolve the issue?

![Screenshot 2024-03-02 at 14 41 13](https://github.com/OHIF/Viewers/assets/35848924/0512a746-f118-4c9e-81da-3254cdb7d1d0)

### Steps to Reproduce

1. `npm run build` in Viewer app
2. Place build in public folder of new React app
3. Issue will be found

### The current behavior

It's giving error.

### The expected behavior

It must be load for the iframe.

### OS

All

### Node version

20.9.0

### Browser

All

**Comment by sedghi** [comment]
Could you please provide additional details for your reproduction steps? The current information is insufficient for me to implement. It would be great if you could include a zip file as well.
