### ISSUE TITLE
[Question] Loading 4D Ultrasounds

### ISSUE THREAD

**Issue by milanp1022** [OHIF/Viewers#3973]
### Describe the Bug

I’ve been attempting to load in a DICOM of a 4D ultrasound (multi-frame sequences across the axial, coronal, sagittal planes) into the OHIF viewer, but I get a black canvas/thumbnail with a “Unsupported displayset” message. This same DICOM can be viewed in 3D slicer, which is where I exported the file from.

Is the viewing of 4D ultrasounds even supported or am I misplacing my efforts? Also, if I am able to get this resolved, my goal was to be able to perform segmentation across each of the frames in each of the views. I understand segmentation is not supported for US at the moment, so I was wondering what issue is preventing that feature from having been rolled out already.

Thank you for your time in advance!

### Steps to Reproduce

1. Load in 4D US DICOM
2. Open Basic Viewer

### The current behavior

Empty thumbnail and canvas with a "1. Unsupported display set." message

### The expected behavior

If viewing 4D US is indeed supported, I expect to see 3 different views loaded in (each being a sequence).

### OS

macOS 14.3

### Node version

18.13.0

### Browser

Edge (122.0.2365.59)

**Comment by sedghi** [comment]
We are adding some 4D support very soon, see [here](https://github.com/OHIF/Viewers/pull/3664)

Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
