### ISSUE TITLE
[Bug] Rectangle StartStopEnd broken in demo server

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#3974]
### Describe the Bug

The Rectangle ROI treshold is broken in the TMTV mode, while working properly in Cornerstone example.
The erreur is due to an undefined when trying to get the viewport id

### Steps to Reproduce

1. go to  https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
2. Try to draw a Rectangle roi threshold in the viewport pt axial

### The current behavior

The ROI is not drawn with the following error : 
Uncaught TypeError: Cannot destructure property 'viewportId' of 'i' as it is undefined.
    at l (state.ts:93:11)
    at h._calculateCachedStatsTool (RectangleROIStartEndThresholdTool.ts:412:5)
    at g (debounce.js:91:19)
    at debounce.js:118:22
    at h.I [as _throttledCalculateCachedStats] (debounce.js:195:16)
    at h.renderAnnotation (RectangleROIStartEndThresholdTool.ts:474:14)
    at triggerAnnotationRender.ts:196:33
    at Array.forEach (<anonymous>)
    at triggerAnnotationRender.ts:210:20
    at a (draw.ts:10:3)

### The expected behavior

Rectangle ROI should open

### OS

Linux

### Node version

20

### Browser

Chrome 120

**Comment by sedghi** [comment]
This will get fixed after I update cs3d, you can do it yourself for now

**Comment by salimkanoun** [comment]
Confirmed fixed in the current main branch, thank you !
