### ISSUE TITLE
[Bug] Cannot use Segmentation Brush - Circle or Sphere consistently and when it does not work = errors in console

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3976]
### Describe the Bug

Found in OHIF dev version: 3.8.0-beta.56, Commit hash: 21e8a2bd0b7cc72f90a31e472d285d761be15d30

While in segmentation mode, i cannot consistently use the segment brush - circle or sphere to create a segment

![image](https://github.com/OHIF/Viewers/assets/143200290/dabe4108-b983-4f29-bd42-08bd91b6bb48)

### Steps to Reproduce

1. Select MR study: COVID-19-NY-SBU and select the Segmentation button = viewer screen appears in 2x2 layout with right panel expanded
2. Click on the right-side panel and select the +Segmentation verbiage to add a new segment = Segment 1 with red dot appears in the right-side panel
3. Click on the brush icon and the Sphere option
4. Click on Viewport A and create a segmentation shape on the image by dragging the mouse over a piece of the image = a red shape appears on the image
5. Click on viewport B and do the same to create a shape. If nothing appears, click on the viewport and try again = NOTHING appears on the viewport and errors appear on the console
![image](https://github.com/OHIF/Viewers/assets/143200290/f2e733d1-7e3f-4700-9e2d-13a43ac5da42)

Repeat step 5 for viewports 3 & 4 = no more shapes and just errors in the console
![image](https://github.com/OHIF/Viewers/assets/143200290/e576d9c8-c554-4958-bb76-05b94cdf1c11)

### The current behavior

cannot consistenly use the segmentation brush-sphere shape to segment an image

### The expected behavior

the segment brush tool for the sphere shape should work on all viewports. For viewports that segmentation is not supported the user should get a message alerting them that the viewport is not supported for the segment feature.

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v122

**Comment by james-hanks** [comment]
For 3.8 we will prevent the error from throwing

We will revisit in 3.9 to properly implement for stack viewport

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
