### ISSUE TITLE
[Bug] Create measurements on MPR, turn off MPR and cannot create new measurements on 2x2 layout viewports

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#3978]
### Describe the Bug

Found in OHIF dev env: version 3.8.0-beta.56, Commit hash: 21e8a2bd0b7cc72f90a31e472d285d761be15d30 on a mac + chrome browser

Creating bidirectional measurements within the MPR viewports and then turning off MPR to return to 2x2 layout and try to create measurements on viewport b is not successful. The empty measure appears on the measurements panel but no measure on the image. Also note the errors in the console:
![image](https://github.com/OHIF/Viewers/assets/143200290/65a6a5f3-8224-4a1d-9711-c6c9d48aa685)

### Steps to Reproduce

1. Select CT\PT\SR study ACRIN...with 408 instances
2. Select 2x2 grid layout
3. Select viewport B + MPR tool
4. Select the bidirectional tool and measure all 3 MPR viewports (click yes to track measurements) = measurements appear in all 3 viewports but, only the axial image measure is in the right-side panel
5. Turn off MPR to go back to 2x2 layout
6. Click into viewport B, reselect the bidirectional tool and create measurements on the image = i) no measurements appear on the image, ii) empty measurements in the right-side panel and iii) errors in the dev console

### The current behavior

- no measurements appear on the image
- empty measurements in the right-side panel 
- errors in the dev console

### The expected behavior

measurements appear on the image, correct measures in the right-side panel & no errors in console

### OS

MacBook Pro - Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome v122

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
