### ISSUE TITLE
[Feature Request] Enable Images Download in background

### ISSUE THREAD

**Issue by NurGVaras** [OHIF/Viewers#3980]
### What feature or change would you like to see made?

currently when using the viewer, the initial load just request a handfull of images, and then when selecting a series the dowload starts, making the waiting time longer than needed.

This could be avoided or reduced, if after the initial load the download of all the images starts.

### Why should we prioritize this feature?

This problem is more apreciable in studies with several hundreds images, sometimes we have studies with more than 2000. And the diferrent series take a lot of time to download, so if the dowload starts on the backgorund, this time could be reduced

**Comment by sedghi** [comment]
we will work on this hopefully next release

**Comment by sedghi** [comment]
watch here https://github.com/OHIF/Viewers/issues/3363
