### ISSUE TITLE
Keycloak image on OpenResty-Orthanc-Keycloak does not exist

### ISSUE THREAD

**Issue by MatheusRdk** [OHIF/Viewers#3985]
### Describe the Bug

Apparently the keycloak image in docker-compose no longer exists and we can't pull it

### Steps to Reproduce

1.Download ohif and install packages
2.run docker-compose up in OpenResty-Orthanc-Keycloak folder

### The current behavior

https://hub.docker.com/layers/jboss/keycloak/14.0.0/images/sha256-00bf91597ffef4811c1b08cc88710d078e0b936a4ab473ced8a7abf34ee24fb8

### The expected behavior

Update the image and perhaps the keycloak variables will have to change their name depending on the image that is placed in place of the old one

### OS

Windows 10

### Node version

18.12.0

### Browser

Firefox 121.0 | Chrome

**Comment by MatheusRdk** [comment]
> yeah that is so weird, not sure what happened, but using the keycloak/keycloak also seems like not working right out of the box

If I'm not mistaken, the oldest version available in Keycloak/Keycloak is keycloak 17. And in these newer versions the names of keycloak variables have changed. E.g, instead of DB_VENDOR, DB_ADDR, and DB_PORT, you need to use KC_DB and KC_DB_URL.

**Comment by sedghi** [comment]
seems like it has moved to quay.io, see our new recipes

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
