### ISSUE TITLE
[Bug] The default size of segment pointer and the size of segment pointer after adjusting to the same value using slide ranger are not same.

### ISSUE THREAD

**Issue by Anakha0712** [OHIF/Viewers#3987]
### Describe the Bug

The user has drawn a segment with the default radius of the segment pointer and then adjusted the radius using the slide ranger / from the input box of the Radius option in the segment panel to the same default radius and drawn another segment. But both segments were showing different sizes.

### Steps to Reproduce

1. Launch a study in segmentation mode.
2. Select Add Segmentation.
3. Select the brush tool and draw segmentation.
4. Observe the radius of the segment pointer.
5. Adjust the slide ranger / enter value into the input box for the Radius option.(adjust to the default radius value)
6. Draw segment 
7. Observe the viewport and segment pointer.

### The current behavior

The default size of the segment pointer and the size of the segment pointer after adjusting to the same value in slide ranger are not same.

https://github.com/OHIF/Viewers/assets/106664893/356063fd-4fe0-48c1-84e1-d6591a2b8c58

### The expected behavior

The default size of the segment pointer and the size of the segment pointer after adjusting to the same value in Slide Ranger are should be the same.

### OS

Windows 10 

### Node version

16.14.2

### Browser

Version 122.0.6261.112

**Comment by sedghi** [comment]
interesting, thanks for the report

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
