### ISSUE TITLE
[Bug] No support for empty label maps, loading crashes, export ignores

### ISSUE THREAD

**Issue by rubenverhack** [OHIF/Viewers#3991]
### Describe the Bug

I am building a labeling platform in which I want labelers to have a segmentation with three predefined segments present. This is to ensure that every labeler has the correct identifiers. Empty label maps are completely valid for our application, i.e. indicating non-presence of a label globally.

When a DICOM SEG is loaded with 3 segmentation types that are non-empty, it correctly shows the three labels.

![image](https://github.com/OHIF/Viewers/assets/28840027/7925f506-d776-4009-bfe8-ec3c0db92252)

(1) BUG => If one of segments is empy (all labels are set to zero), then the loader hangs at 100%.

![image](https://github.com/OHIF/Viewers/assets/28840027/0b6718d7-c815-47b8-8d29-100ce6190bb5)

(2) When making a Segmentation in OHIF, and an empty segment is added, then it is not exported. 

Tested on version v3.8.0-beta.59

### Steps to Reproduce

I have added a DICOM SEG file with empty label maps for reference.

[2.25.337304097621488642328905952564813011907.zip](https://github.com/OHIF/Viewers/files/14614162/2.25.337304097621488642328905952564813011907.zip)

### The current behavior

(1) loading => loader crashes
(2) exporting => empty segments are deleted

### The expected behavior

Empty label maps should just be loaded as a label with only zeros.

Empty segments should be exported as empty DICOM SEG objects (containing all layers being all set to zero)

### OS

Ubuntu 22.04

### Node version

OHIF v3.8.0-beta.59

### Browser

Chrome

**Comment by sedghi** [comment]
can you provide the referencedSeiries as well? (CT, MR) the image itself

**Comment by rubenverhack** [comment]
Here's the anonimized data. Thank you for your time.

https://drive.google.com/file/d/1HegTfExX9pJwxx4br42jPz5CbnBlBea_/view?usp=drive_link

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
