### ISSUE TITLE
[Feature Request] Support for creating and exporting overlapping segmentations (not only loading) 

### ISSUE THREAD

**Issue by rubenverhack** [OHIF/Viewers#3992]
### What feature or change would you like to see made?

I am building a labeling platform in which I want labelers to have a segmentation with three predefined segments present. Apart from these labels sometimes to empty (https://github.com/OHIF/Viewers/issues/3991), I have the issue that they are overlapping.

My system outputs segmentations with overlapping segments, it has the segmentation overlap flag correctly set to YES (https://dicom.innolitics.com/ciods/segmentation/segmentation-image/00620013). 

OHIF loads the overlapping segmentations and shows them correctly (even though it gives me following warning):
![image](https://github.com/OHIF/Viewers/assets/28840027/a555c7b7-4fde-47a4-85d5-9474760b5f80)

However, if I open overlapping segmentations and export them unaltered, the segmentations are exported as non-overlapping. This is likely to the underlying merging of all the labels into a single multi-label map as mentioned in https://github.com/OHIF/Viewers/issues/2164. 

Apart from that, it is not possible alter the segmentations in an overlapping manner, since the tools automatically make exclusive labels.

### Why should we prioritize this feature?

The reason why I combine these segments into a single segmentation is to have an elegant way to instruct human labelers. My system was meant to create one segmentation for each dataset version for AI training purposes. They would make edits, and save it as one segmentation with an increased version bump. Sometimes starting from scratch, sometimes starting from an AI model output.

I can work around this by making a segmentation for each label separately, and I also have to work around the fact that OHIF does not support empty labels. However, this leaves room for human error in the data labeling process, since the process can't be sufficiently streamlined.

At least the exporter should notify that overlapping labels are unsupported (not only the renderer).

**Comment by sedghi** [comment]
> OHIF loads the overlapping segmentations and shows them correctly (even though it gives me following warning):

That is not true, we don't have support for overlapping segments, we simply over write the values (whomever is the last segment will over write the previous ones). I want to support overlapping segments at least in stack viewports, but that will happen later this year and is not immediate. Meanwhile you can create separate segmentations

**Comment by fedorov** [comment]
Related to https://github.com/OHIF/Viewers/issues/3496.

 > OHIF loads the overlapping segmentations and shows them correctly (even though it gives me following warning):

As a temporary solution, note that OHIF v2 can properly visualize overlapping segments. The issue mentioned above discusses this.

**Comment by rubenverhack** [comment]
Ok thanks for your replies and fantastic work. I will work with separate segmentations in the meanwhile.

**Comment by sedghi** [comment]
I'm gonna close this, you can follow it here https://github.com/OHIF/Viewers/issues/3496
