### ISSUE TITLE
Runing OHIF Viewer as a service without meteor

### ISSUE THREAD

**Issue by FWmaster** [OHIF/Viewers#4]
I would like tu run OHIF Viewer as a service daemon, and to keep it running when I quit the command line console. It seems like Meteor was made for development purpose and has no daemon running option.
Is there a way to run it as a service with Node.js or another serverside js framework ?

**Comment by swederik** [comment]
The most simple way would be to run it with & at the end of the command, I guess.

People usually use meteor deploy to deploy to servers. For a local daemon, there are a few suggestions here:

http://stackoverflow.com/questions/15657071/how-to-run-meteor-on-startup-on-ubuntu-server

Nothing here is specific to the OHIF Viewer, though. These are general to Meteor. There is no way to run the OHIF Viewer without Meteor, though.
