### ISSUE TITLE
How to delete one by one annotation, ellipse, retangle?

### ISSUE THREAD

**Issue by huyenzoo** [OHIF/Viewers#40]
Currently we  just delete all annotation and ellipse, retangle draw in imagebox on one time.

How can we delete one by one it? 

Please help me! thank you so much

Regards,
Huyen Do

**Comment by swederik** [comment]
Hi Huyen,

Thanks for the question. This is indeed something we have overlooked, thanks for pointing this out.

At the moment the only way is to drag it off of the screen. I will add a ticket to allow right-click or long-press (on touch devices) to open a menu and delete these types of measurements.

Cheers,

Erik
