### ISSUE TITLE
[Feature Request] Guide to implement custom auth

### ISSUE THREAD

**Issue by MatheusRdk** [OHIF/Viewers#4001]
### What feature or change would you like to see made?

I need to create my own authentication in the viewer, I can't use keycloak because we have another application that already has its own authentication and will use the viewer as an iframe, and keycloak doesn't fit well into the flow.
I saw in some similar issues that the UserAuthenticationService serves this purpose, but I don't understand how to use it.
A guide on how to use your own authentication API within this UserAuthenticationService would be good.
In my case, I have an api where I enter email and password and receive a token, which I want to use.

### Why should we prioritize this feature?

As there are already recipes for login service with keycloak, if there was at least a guide on how to implement your own auth, the project would be very complete in terms of security options.

**Comment by sedghi** [comment]
when you grab the token add it to the userauth, and later for the requests we grab it ourselve and send it. if the token is in the URL as token= we automatically read it as well

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
