### ISSUE TITLE
[Bug] Viewers cannot be opened in iOS WeChat

### ISSUE THREAD

**Issue by CTHD-Root** [OHIF/Viewers#4002]
### Describe the Bug

I can access the address on the computer webpage, and I can also open the website using Android's WeChat. However, when I use iOS WeChat, I cannot open it and the screen is black!
[
![5dba758ff916ff64a6ce346e07ee6dd](https://github.com/OHIF/Viewers/assets/46281714/3ff8af55-4f71-4aed-bf31-62e81282e458)
![69f8032f65f6c29aeeb67e96a4f40e1](https://github.com/OHIF/Viewers/assets/46281714/1e50000e-ead9-412b-90c4-07fc84f04e65)
](url)

### Steps to Reproduce

I use wechat open url,but error!!Display black screen

### The current behavior

I use wechat open url,but error!!Display black screen

### The expected behavior

Always black screen

### OS

ios16

### Node version

18

### Browser

wechat

**Comment by lihao6666** [comment]
It could be the vtk, I suggest you refer to this link to fix it.[ #1133](https://github.com/cornerstonejs/cornerstone3D/issues/1133)

**Comment by sedghi** [comment]
I created this PR which would be good enough for a lot of use cases (except the PT Scaled data)

https://github.com/cornerstonejs/cornerstone3D/pull/1212
