### ISSUE TITLE
Whether dicom images can be displayed with less metadata

### ISSUE THREAD

**Issue by Greyxy** [OHIF/Viewers#4003]
### What feature or change would you like to see made?

The dicom data returned by the server is as follows, and the image cannot be viewed in the viewer because the required metadata is missing

{
		"patientName": "HUANG CHANG BO",
		"studyInstanceUID": "1.2.840.113619.2.55.3.604659834.248.1708447883.18",
		"seriesID": "1163",
		"seriesInstanceUID": "1.2.840.113619.2.55.3.604659834.248.1708447883.21",
		"seriesNumber": "1",
		"modality": "CT",
		"sopInstanceUID": "",
		"instanceNumber": "1",
		"filePath": "http://192.168.1.251:8091/Image/CT/C0145468/44788318_20240226/1_ccb476c7523aa6afbae8b334b50086f2/AT000001.DCM"
	}

### Why should we prioritize this feature?

Is there a way to get the dcm file directly from filePath in the json file and render it to the viewer

**Comment by daemon29** [comment]
do you use the dicom-json-generator.js?

**Comment by Greyxy** [comment]
Yes, I have. 
But the current problem is that I can only get the dcm file through the url and lack the necessary metedata for rendering.
 It would be extremely inefficient
 if I first requested the dcm file to the local  through the url and then executed the dicom-json-generator.js to generate the json file

**Comment by daemon29** [comment]
what metadata is missing? Perhaps your dicom file is not standard. Can you cross-check with the metadata requirement. Can you try it again with a single dicom file that is not yours. In the document with dicom json provide a sample study, you can test it agaisnt your dicom.

**Comment by daemon29** [comment]
The metadata exists in dicom doesn't guarantee it will be saved in the database, as this is a developer's choice on database design. I don't recommend construct the metadata.json by yourself as you might miss a lot of optional field. What I did was putting all dicoms of that patient in a folder, and let the dicom-json-generator.js do the work for you.

**Comment by sedghi** [comment]
You can take a look at required metadata to load here https://docs.ohif.org/faq#what-are-the-list-of-required-metadata-for-the-ohif-viewer-to-work
