### ISSUE TITLE
[Feature Request] DCM4CHE (secured) authentication service implementation with keycloak in V3

### ISSUE THREAD

**Issue by muddasar-de** [OHIF/Viewers#4005]
### What feature or change would you like to see made?

![image](https://github.com/OHIF/Viewers/assets/75139126/75c023de-8a56-4d4a-a554-6c688dca74f8)

Implementation of these functions to enable OIDC functionalities for the secure or user-based authentication in DCM4CHE using keycloak.

### Why should we prioritize this feature?

This can help to improve more security and also the user-based functionalities with DCM4CHE will be enabled.

**Comment by sedghi** [comment]
checkout our recipes for auth https://docs.ohif.org/deployment/user-account-control

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
