### ISSUE TITLE
[Bug] Segmentation not supported on non-rebuildable displaysets for US modalities

### ISSUE THREAD

**Issue by aniketbharti** [OHIF/Viewers#4006]
### Describe the Bug

Apologies, I don't have much experience with OHIF Viewer. Currently I'm working with Ultrasound and wanted to have segmentations on US files. I tried to add segmentation on US modalities [Cardiac US’ file] but got ‘Segmentation not supported on non-rebuildable displaysets’. What is the reason for this? And if I want to fix this what would I need to do either on OHIF viewer or on DICOM file headers? Are there a special headers in DICOM that needs to be changed?

### Steps to Reproduce

Select Cardiac US file from the list and try adding sementations.

### The current behavior

It throws error 'Segmentation is not supported for non-reconstructible displaysets yet'

### The expected behavior

It should enable segmentation, similar to how we have CTs and other modalities

### OS

macOS

### Node version

18.16.1

### Browser

Chrome/Edge

**Comment by cokolele** [comment]
Upping, having the same "problem".

I don't have much experience either, but it seems to me that segmentation is supported only for 3D images ? Theres a tool for spherical regions, but it seems to me that ability of labeling structures on 2D (multiframe) US images is important as well. I am not sure if i am missing something though.

**Comment by sedghi** [comment]
this is related to stack viewport segmentation that we are workign for next release

**Comment by KatkaG** [comment]
Hello @sedghi, could you provide some updates regarding this topic? Will segmentations on non-reconstructible datasets be available in version 3.9?

**Comment by sedghi** [comment]
The first piece of puzzle (cornerstone3D 2.0) is merged, now version 3.9 can get released after QA
