### ISSUE TITLE
[Bug] New mode is greyed out in viewer, issue appeared in version 3.8 release

### ISSUE THREAD

**Issue by muzzkh** [OHIF/Viewers#4012]
### New mode is greyed out in viewer, issue appeared in version 3.8 release

Hi, I just updated to the latest version of OHIF and I was following the video instructions for creating a new mode. However, unlike the previous versions, when I create a new mode it is greyed out. This worked fine previously and I couldn't find a workaround to activate the mode. Starting from the Viewers directory my mode is saved in ../OHIF-modes/ohif-mode-training
<img width="462" alt="Screenshot 2024-03-30 at 8 50 48 PM" src="https://github.com/OHIF/Viewers/assets/86198251/00d2490d-d7a5-4231-9f83-64e7974979ed">

### Steps to Reproduce

Follow the instructions in the first video on creating and linking modes
[https://docs.ohif.org/development/video-tutorials](docs)

Also here
git clone https://github.com/OHIF/Viewers.git

yarn config set workspaces-experimental true

yarn install

cd ..

mkdir OHIF-modes

cd Viewers

yarn cli create-mode

### The current behavior

Currently once the mode is created and linked, it will show up at localhost:3000 but it will be greyed out.

### The expected behavior

Expected behavior is for the mode to be a functional feature that is not greyed out.

### OS

Mac Sonoma

### Node version

v21.6.1

### Browser

Edge

**Comment by muzzkh** [comment]
I went into`index.tsx` file containing the following line by default
`isValidMode: ({ modalities }) => true,` which seems to cause the issue.
Replacing this with the following derived from the core modes fixes the issue
`      return {
        valid: true,
        description: 'The mode is for testing',
      };`

**Comment by james-hanks** [comment]
Issue related to CLI fixed in 3.8
