### ISSUE TITLE
[Bug] segmentation mismatch on mpr view

### ISSUE THREAD

**Issue by l5769389** [OHIF/Viewers#4019]
### Describe the Bug

https://github.com/cornerstonejs/cornerstone3D/issues/1188  。but the ohif-viewer demo is all right。 what i miss? 

### Steps to Reproduce

like the link

### The current behavior

like the link

### The expected behavior

like the link

### OS

window11

### Node version

18.16

### Browser

"electron": "^28.2.0",

**Comment by l5769389** [comment]
https://private-user-images.githubusercontent.com/26296535/320259036-9f3aa719-5595-4c24-8158-e25cd3e44ed4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTQwMTAsIm5iZiI6MTcxMjY1MzcxMCwicGF0aCI6Ii8yNjI5NjUzNS8zMjAyNTkwMzYtOWYzYWE3MTktNTU5NS00YzI0LTgxNTgtZTI1Y2QzZTQ0ZWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA5MDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZjFhNGE4NjRkMDhmY2IwNDZiOGMyNmM5ZGQ1ZmVhNTMwOTE4NmQxNDZiYzk0OTFmOWQxMDFhMGU3M2IyNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TOA1tBHhGxCnPPRC1waZC2uWDa4cQCX8ukOUME0-Vmc

**Comment by l5769389** [comment]
![图片](https://github.com/OHIF/Viewers/assets/26296535/7e495af0-28ae-4326-abb3-4393917d6d66)

**Comment by sedghi** [comment]
we don't have yet support for segmentation in volume rendering, although you can convert labelmap to surface and render them, see here https://www.cornerstonejs.org/live-examples/polysegwasmvolumelabelmaptosurface

we have plan to support this in future
