### ISSUE TITLE
[Feature Request] Undo/Redo an action

### ISSUE THREAD

**Issue by tabeascherer** [OHIF/Viewers#4023]
### What feature or change would you like to see made?

Give users the option to undo and redo actions when editing segmentation, creating measurements, or any other actions they are taking during the workflow. This feature should be available as a button in the top navigation and as a keyboard shortcut (ctrl+z).

### Why should we prioritize this feature?

Typically, a radiologist's daily work is time-critical and requires the ability to undo or redo an action quickly. A usability study conducted with research and clinical radiologists confirmed this, as all participants looked for this feature.to undo or redo an action quickly

**Comment by sedghi** [comment]
Coming soon, stay tuned
