### ISSUE TITLE
There is a issue with the display on the mobile phone

### ISSUE THREAD

**Issue by 15399233911** [OHIF/Viewers#4024]
### What feature or change would you like to see made?

We would like to allow patients to view images on their mobile phones, but OHIF does not currently appear to be compatible with mobile displays. When is the plan to fix it? Looking forward to your reply. Thank you very much

### Why should we prioritize this feature?

Now that most people use their phones to view reports and images, it is becoming more and more important to support mobile

**Comment by sedghi** [comment]
It renders but layout is not responsive yet, we are releasing responsive layouts this year
