### ISSUE TITLE
[Bug] List of measurements disappears when the user creates a report

### ISSUE THREAD

**Issue by AlexPDesigner** [OHIF/Viewers#4026]
### Describe the Bug

We conducted usability tests on OHIF Viewer with research and clinical radiologists and one of the findings is a behaviour that surprised our users: **when creating a report for a list of measurements, the list of measurements disappears from the interface.** Our participants got confused and frustrated that their work has disappeared and was no-where to be found in the interface at one glance.

OHIF version: Version number 3.8.0-beta.73 (assumption is previous versions as well)

### Steps to Reproduce

1. Create measurements
2. Tracks measurements
3. Open the list of measurements
4. Create report
5. Measurements list gone 😵‍💫

### The current behavior

The list of measurements disappears when the user creates a report (or a version of the measurements) without informing the users about the result of the action they took - currently, the measurement list just disappears, there is no indication why, where and what the user can do about it. The user can get confused, frustrated and scared about where they work went.

### The expected behavior

1. Create measurements
2. Track measurements by default, no banner needed
3. Open the list of measurements automatically when a measurement is created
4. Change “Create report” to “Save version”
5. User creates the report
6. Measurement list still visible in the interface :bowtie:
7. Positive feedback banner informing the user that the action they took was successful

**For the current bug, we are focusing on step 6: Measurement list still visible in the interface after the user created a report.**

### OS

macOS 14.4.1

### Node version

N/A

### Browser

Chrome Version 123.0.6312.107

**Comment by sedghi** [comment]
i think it throws an error since we don't let public to push to our server and then it removes

**Comment by AlexPDesigner** [comment]
It does trigger an error when the user tries to create a report (create a new SR version actually) in the open source. However, in the local version, when a user tries to save their new version of measurements or Create Report, the software behaves as described above.

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
