### ISSUE TITLE
[Bug] Unable to switch MPR series

### ISSUE THREAD

**Issue by Greyxy** [OHIF/Viewers#4027]
### Describe the Bug

The first series of MPR operation, the page can be rendered normally, double-click the second series, the page will be black and can not render, and if you return to the first series will also be black
![firstSeries](https://github.com/OHIF/Viewers/assets/69888263/abbe55fe-f389-4987-98d7-070464ed8812)
![secondSeires](https://github.com/OHIF/Viewers/assets/69888263/dca7dacb-c4df-4661-b815-402797ee350a)

The browser reports an error message
![errorInfo](https://github.com/OHIF/Viewers/assets/69888263/06fb9473-e108-430c-9e85-116f1d472103)
![errorInfo1](https://github.com/OHIF/Viewers/assets/69888263/f9561ddb-67bd-4ea5-b44b-f17d7d16cfcf)

### Steps to Reproduce

1.According to dicomjson data source, 
2.the MPR of the first series is normal, 
3.double-click the second series when building the first series,
4 the page will be black, and then the corresponding image cannot be rendered on the canvas

### The current behavior

Stuck, black screen, page not rendered

### The expected behavior

Double-click on different series to build different series of MPR

### OS

win11

### Node version

16.20.2

### Browser

chrome latest

**Comment by sedghi** [comment]
Can you try with latest and if not working re open this issue please
