### ISSUE TITLE
[Feature Request] Create segmentation and track measurements in the same mode

### ISSUE THREAD

**Issue by JeffersonCurveBeam** [OHIF/Viewers#4032]
### What feature or change would you like to see made?

Measurement tools - e.g. `Angle`, `Length` - to be available in Segmentation mode. Or Create Segmentation tools available in Basic Viewer mode. 

In v3.7 measurement tools - e.g. `Angle`, `Length` - are unavailable in Segmentation mode, and creating a segmentation is unavailable in the Basic Viewer mode.

Curious if there is an architectural incompatibility that restricts these two services from existing in the same mode.

### Why should we prioritize this feature?

Enable users to create segmentations and track measurements without switching modes.

**Comment by sedghi** [comment]
Yiu van add those tools in the segmentation mode. Remember our demo modes are just demos to show you what is possible.
