### ISSUE TITLE
A button for AI CT scan classification

### ISSUE THREAD

**Issue by sickopickle** [OHIF/Viewers#4033]
### What feature or change would you like to see made?

I would like to add a feature where you can press a button to do AI classification on CT scans (specifically Lung CTs). I have been working on a machine learning architecture for lung cancer detection and have been looking for an open source DICOM viewer to integrate it into. How can I do this? (I've got the machine learning part down I just want to know where I need to edit code to add a button to the toolbar.) Thanks!

**Comment by sedghi** [comment]
Take a look at toolbar module and toolbar service in docs.ohif.org

**Comment by sickopickle** [comment]
Hi! I actually did figure out how to make a button. I had to edit a ton of stuff in the cornerstone library though, and it was pretty convoluted. 

Would you mind looking at this [post I made](https://community.ohif.org/t/how-to-access-the-raw-dicom-data-being-displayed-on-the-screen/1430) I need some help
