### ISSUE TITLE
[Feature Request] Open the list of measurements automatically after a user performed a measurement and improve the information displayed.

### ISSUE THREAD

**Issue by tabeascherer** [OHIF/Viewers#4034]
### What feature or change would you like to see made?

We conducted usability tests on OHIF Viewer with research and clinical radiologists, and one insight was that the users couldn't find the list of measurements.

**-> We suggest to open the list automatically once the first measurement is performed.**

Currently, measurements are named "(empty)" which is confusing to users – especially when they have a couple of measurements at once. They are expecting a better overview.

**-> We suggest to show a small thumbnail of the measurement/area in the list and change the word "(empty)" to "(measurement 1)".**

### Why should we prioritize this feature?

Showing the list of measurements automatically will make the viewer experience more intuitive. The thumbnail will help radiologists navigate through the list of measurements faster, resulting in less frustration and confusion.

**Comment by sedghi** [comment]
We have it commented out in longitudinal/index.js
You basically add a subscription for panel service to watch measuement added event
Uncomment it and it should work
