### ISSUE TITLE
[Feature Request] Don’t show irrelevant pop-ups.

### ISSUE THREAD

**Issue by tabeascherer** [OHIF/Viewers#4039]
### What feature or change would you like to see made?

During user testing with radiologists, we discovered that two pop-ups are not needed. 

1. When loading a segmentation, the users see a pop-up that asks, "Do you want to open this Segmentation?". This pop-up is not needed. We can open the segmentation right away, and show it in the list to reduce friction.

2. When performing a measurement, the user is asked, "Track measurement for this series?" We can track the measurement automatically and show it in the list here. It will make a radiologist's workflow smoother. 

### Why should we prioritize this feature?

The two pop-ups are not needed, and we can reduce friction by removing them.

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
