### ISSUE TITLE
[Feature Request] Is there any idea to support .ply format file in OHIF viewer?

### ISSUE THREAD

**Issue by cheparity** [OHIF/Viewers#4040]
### What feature or change would you like to see made?

# Is there any idea to support .ply format file in OHIF viewer?

> Note: It can be a low-priority issue. If busy, it's ok to just leave this issue alone.

I would like to support .ply format file specific to my needs, but I don't know how to start up my development. I only know that I can develop a mode => then extensions that can handle .ply files => done, but there are still some uncertain details for me. 

1. Can OHIF handle 3-D files directly? 
2. Should I modify the code in `core` to render, or just convert my .ply files to DICOM?

I will appreciate if you can give me some guides! :)

### Why should we prioritize this feature?

Sorry but no need to prioritize this feature. Maybe I can develop and contribute it by myself, and I am just looking for a helping hand for starting development.

**Comment by sedghi** [comment]
Not really
