### ISSUE TITLE
[Bug] ultrasound image from terason ultrasound not displaying correctly

### ISSUE THREAD

**Issue by DraconPern** [OHIF/Viewers#4042]
### Describe the Bug

I have a set of images from terason ultrasound that displays correctly in weasis and other dicom software but shows up as green in ohif.

### Steps to Reproduce

Unfortunately my images have patient info burned into them, will need to privately contact to provide the image.

### The current behavior

Shows this
![2024-04-16 07_55_38-OHIF Viewer](https://github.com/OHIF/Viewers/assets/1405101/56cd2793-47b0-4f14-b100-72a25767fdae)

### The expected behavior

A grey scale image

### OS

ubuntu 22.04

### Node version

18.17.1

### Browser

Chrome Version 123.0.6312.122

**Comment by DraconPern** [comment]
Alternatively, is there a way to configure ohif to use wadouri for image display?  Like the old version of ohif.  Setting imageRendering: 'wadouri' does not seem to work.

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
