### ISSUE TITLE
Segmentation Panel Will not add a new segmentation if Layout is changed [Bug]

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#4046]
### Describe the Bug

3.8.0-beta.85

When using Segmentation Mode, if the user changes their layout before creating a new Segmentation the Add Segmentation button will not work.  
![image](https://github.com/OHIF/Viewers/assets/112980389/199168d1-07a7-4fbd-8e55-26109e35c949)

When using the default layout it works fine.
![image](https://github.com/OHIF/Viewers/assets/112980389/48ba8006-17a4-4f66-8228-43b2b21c8250)

### Steps to Reproduce

1. Go to a study in Segmentation mode - https://viewer-dev.ohif.org/segmentation?StudyInstanceUIDs=1.2.840.113619.2.290.3.3767434740.226.1600859119.501
2. Change the layout to 2x2
3. Click  +Add Segmentation
4. Nothing will happen

### The current behavior

If the user changes from the default Layout while in segmentation mode before clicking +Add Segmentation button will no longer add new Segmentations. 

### The expected behavior

Add Segment should work regardless of  if Layout is changed before or after +Add Segmentation is clicked.

### OS

Windows 11

### Node version

Using OHIF Demo 

### Browser

123.0.6312.59 (Official Build) (64-bit)

**Comment by BrandonDatUHN** [comment]
Looks good on 3.8.90

**Comment by BrandonDatUHN** [comment]
@sedghi It looks like this bug is back in version 3.9.2 (what we have on our dev) and also on 3.9.4 (current https://viewer-dev.ohif.org/)

**Comment by BrandonDatUHN** [comment]
using https://viewer-dev.ohif.org/segmentation?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339

1. Change layout to 1x2
2. Will default to scout and PET
3. Drag the CT onto the scout window
4. Try and create a new segmentation on the CT nothing happens
5. Try and create on the PET segmentation will happen



using https://viewer-dev.ohif.org/segmentation?StudyInstanceUIDs=1.2.840.113619.2.290.3.3767434740.226.1600859119.501

1. change layout to 1x2
2. will default to 2 CTs on top
3. change left panel to a PET via drag and drop
4. Can't create segmentation on PET but can create on CT

So it seems to be more that you can't create it on a newly dragged in image set

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
