### ISSUE TITLE
[Bug] Exit of full screen viewport axial position seems to be lost

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#4061]
### Describe the Bug

See video, when moving the camera to a bottum location, going full screen and getting back to the TMTM HP, the axial seems shifted, upper slice became empty and the lower side of the volume is not viewable anymore

https://github.com/OHIF/Viewers/assets/25229822/7be7fbcf-b95b-4ad5-ab47-3ddfe9d8a6a0

### Steps to Reproduce

1. go to https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463
2. Move crosshair to the left kidney
3. Double click on fused coronal fused viewport to make it full screen
4. Double click again to return to main view
5. See axial view is shifted the fist slices are empty and lower part of volume not accessible

### The current behavior

The image seems to be shifted

### The expected behavior

All volume should be located like before the full screen entrance

### OS

Linux

### Node version

20

### Browser

Chrome latest

**Comment by salimkanoun** [comment]
Yes it does, now it is a bit different as it return in to the middle slice when exiting full view and also apprears a shift between the crosshair and the actual camera position

https://github.com/OHIF/Viewers/assets/25229822/c698b2a9-a0cd-4dc5-900b-81a58a5f4b62

**Comment by sedghi** [comment]
Is this still happening in latest master branch?

**Comment by salimkanoun** [comment]
Yes when exiting the full screen view, the camera is reset to the HP default and not the last position,

And more problematic, fusion is lost

https://github.com/user-attachments/assets/5e5e68cc-a74c-4bf1-b030-dd8f66315114

**Comment by sedghi** [comment]
Ok i will investigate

**Comment by sedghi** [comment]
I fixed the colormap, but don't have a proper fix for crosshair, i'm just resetting it after toggle one up for now
