### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by miqili** [OHIF/Viewers#4067]
### What feature or change would you like to see made?

Is it compatible with mobile phones?

### Why should we prioritize this feature?

When I open it on my mobile phone, the layout seems to be very messy. It would be better if it is compatible with the mobile version.

**Comment by miqili** [comment]
It would be a nice optimization if image viewing were compatible with mobile phones, but it could also cause problems with MPR and 3D functionality.

**Comment by sedghi** [comment]
we are working on this this year https://ohif.org/roadmap/Q2-2024

**Comment by zh7314** [comment]
> we are working on this this year https://ohif.org/roadmap/Q2-2024

thanks for your work，responsive UI is very important for me
