### ISSUE TITLE
[Bug] Dicom Upload Button is not enabling

### ISSUE THREAD

**Issue by Sairashwanthsk** [OHIF/Viewers#4069]
### Describe the Bug

dicomUploadEnabled configuration was set to "true" but upload button is not showing in the desired page.

### Steps to Reproduce

1. Opened "../platform/app/public/config/default.js"
2. Written dicomUploadEnabled in
  dataSources: [
    {
      ...
      configuration: {
        ...
        dicomUploadEnabled: true,
        ...
      }
    ...
    }
  ...
  ]

### The current behavior

No Upload Button is showing

### The expected behavior

Upload button should show as per the documentation

### OS

Ubuntu

### Node version

v16.20.2

### Browser

Edge

**Comment by Sairashwanthsk** [comment]
![uploader-cdf5964e61830032962cbf68b2bd9598](https://github.com/OHIF/Viewers/assets/79138719/ec6eac58-8f35-4175-ab36-ea623c3af82c)

This is the UI func shown in the docs.


![Capture](https://github.com/OHIF/Viewers/assets/79138719/f11892c9-7e30-4955-a8ca-945e59e2db80)

But this is how UI is shown without upload button

**Comment by sedghi** [comment]
i think it depends on your configuration. take a look at the google.js config that has the correct setup

**Comment by white1-doggy** [comment]
I add "dicomputadEnabled：true，" in all .js files, but it's useless

**Comment by sedghi** [comment]
@white1-doggy what is your backend dicom server?
