### ISSUE TITLE
[Bug] Ultrasound (US) Image Doesn't Show on The Viewer

### ISSUE THREAD

**Issue by tirta-ir** [OHIF/Viewers#4075]
### Describe the Bug

I’m currently working with OHIF as a DICOM Viewer. A few days ago, I connected the system with US modalities, transferred the DICOM Ultrasound Images, and attempted to view them on the OHIF basic viewer. However, when I access the viewer, it doesn’t display anything; only a blank screen appears on the viewport.

Here are the steps I’ve taken:

- Changed the image and thumbnail rendering to wadouri in the config (this did not solve the issue, so I change it back to wadors).
- Used both the release and master branches of ohif/viewer (3.8.0 and 3.9.0-beta.0) (this did not solve the issue).
- Opened the DICOM on OHIF v2 (the image displayed correctly in this version).

Please help me resolve this issue.

**Documentation**

- Image viewing on OHIF v3.9.0-beta.0 (blank screen)
![image](https://github.com/OHIF/Viewers/assets/70493416/2fdfe911-02c1-4869-b36e-29a8c09976bf)

- Image viewing on OHIF v2 (displayed correctly)
![image](https://github.com/OHIF/Viewers/assets/70493416/94e08a2b-b668-4844-8068-99b168ac84c3)

### Steps to Reproduce

1. Download the exported Ultrasound DICOM images from this link (https://drive.google.com/file/d/17xuICqMgf5v4cosGWRuNlt7R9n4Kq8aS/view?usp=sharing).
2. Upload the DICOM images to OHIFv3.
3. View the DICOM using the basic viewer.

### The current behavior

The viewer displays a blank screen and does not show anything.

### The expected behavior

The ultrasound image is displayed, just like in OHIF v2.

### OS

Ubuntu 22.04.3 LTS

### Node version

20.12.2

### Browser

Chrome 123.0.6312.122 (Official Build) (64-bit)

**Comment by rmasad** [comment]
I think it's the same that https://github.com/OHIF/Viewers/issues/4078

**Comment by sedghi** [comment]
This is fixed

**Comment by tirta-ir** [comment]
Thank you for the updates, I'll check the master branch

**Comment by tirta-ir** [comment]
Dear @sedghi , my ultrasound dicom still couldn't be viewed using the latest 3.9.0-beta27 basic viewer. When I check the console, it throws these error. Kindly check it, thank you

![image](https://github.com/OHIF/Viewers/assets/70493416/eea59864-4c27-4309-b0e0-b782ad3dae16)

**Comment by sedghi** [comment]
Yeah i see they don't show up.

**Comment by cfernandezdevp** [comment]
hey, whay is this version? "The ultrasound image is displayed, just like in OHIF v2."
Thanks
