### ISSUE TITLE
[Feature Request] sorting by Acquisition Datetime and nonClip display

### ISSUE THREAD

**Issue by niirdan** [OHIF/Viewers#4076]
What feature or change would you like to see made?

### sort by dicom tag (0008,002A)
In addition , disable the behavior of the system which creates a stack of images and display them each by it own.

Why should we prioritize this feature?

**This Option Will make OHIF Very useful for cardiologist's and will make much more sense when investigating studies**

**Comment by sedghi** [comment]
We added many sorting features to the UI.

Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)<br><br>----<br><br>Also see how to configure it<br><br>[https://docs.ohif.org/faq/technical/#how-can-i-change-the-sorting-of-the-thumbnail--study-panel--study-browser](https://docs.ohif.org/faq/technical/#how-can-i-change-the-sorting-of-the-thumbnail--study-panel--study-browser)
