### ISSUE TITLE
[Bug] "Failed to Execute 'postMessage' on Worker" in ultrasound study from a specific center

### ISSUE THREAD

**Issue by rmasad** [OHIF/Viewers#4078]
### Describe the Bug

I encountered an error while using the OHIF DICOM image viewer. When attempting to view an ultrasound study from a specific center, the following error occurred in the viewer:

`Uncaught DOMException: Failed to execute 'postMessage' on 'Worker': #<Promise> could not be cloned.`

Study Link: [[Study Link Here]](https://www.pastefile.com/tzz5tq)

This error seems to be related to a failure in executing the 'postMessage' function on a Worker. It's possible that there's an issue with the Promise object being passed as an argument, preventing it from being cloned properly.

**This study works with OHIF v2**.

### Steps to Reproduce

1. Open the OHIF DICOM image viewer.
2. Load the ultrasound study from the provided link.
3. Attempt to view the images.

### The current behavior

Load with error and doesn't show the images

### The expected behavior

The ultrasound study should load without any errors, and the images should be displayed correctly in the viewer.

### OS

Ubuntu

### Node version

18

### Browser

Chrome 124

**Comment by sedghi** [comment]
Seems like the issue is that the context getting passed to the worker has a `promise` which is the result of the palette metadata retrieval.

So instead of `bluePaletteColorLookupTableData` being numer[] it is a promise, which webworkers cannot handle, we should await those before decode. 

I'm working on this

**Comment by sedghi** [comment]
BTW it says files not available in your link, can you re-upload your study?

**Comment by rmasad** [comment]
Here it is: [elevic-an.zip](https://github.com/OHIF/Viewers/files/15396419/elevic-an.zip)

**Comment by sedghi** [comment]
It renders fine after my fix, i will merge it 

![CleanShot 2024-05-21 at 22 15 15@2x](https://github.com/OHIF/Viewers/assets/7490180/e0ca0a3d-ecb1-4d7d-8dfd-7130e3c6157b)

**Comment by rmasad** [comment]
Thanks @sedghi, we are waiting for when it's uploaded the change to test it.

**Comment by james-hanks** [comment]
#4110 parent issue

**Comment by arturojain** [comment]
I'm facing the same issue, I thought the problem was that I was missing sequence of ultrasound regions.

**Comment by sedghi** [comment]
@rmasad please open a separate issue for ct

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue

**Comment by rmasad** [comment]
Thanks @sedghi!
