### ISSUE TITLE
[Feature Request]  Make "Track Measurements for this Series?" Modal Optional

### ISSUE THREAD

**Issue by rmasad** [OHIF/Viewers#4079]
### What feature or change would you like to see made?

I would like to suggest a new feature for the OHIF DICOM image viewer. Currently, when accessing the measurement tools for a series, a modal dialog titled "Track measurements for this series?" appears, asking the user to confirm whether they want to track measurements for that series.

Can this be disable from config file?

### Why should we prioritize this feature?

We currently do not have this functionality enabled and it is annoying that every time a study diagnoses it asks you this.

**Comment by sedghi** [comment]
I think it is valuable addition

**Comment by sedghi** [comment]
Closing in favor of #4039
