### ISSUE TITLE
Add tags on Viewport

### ISSUE THREAD

**Issue by quinntera** [OHIF/Viewers#4080]
### What feature or change would you like to see made?

How to add new tags to the Viewport? Namely these tags: (0018,5101) "ViewPosition" and (0020,0062) "ImageLaterality", to display the tags of each object or each series of the window being viewed

![Screenshot_5](https://github.com/OHIF/Viewers/assets/150328829/b21918f2-8f17-48ff-b654-96f170251390)
![Screenshot_1](https://github.com/OHIF/Viewers/assets/150328829/ebfcd7a5-dd83-4fa6-965f-1bbcbf2925ff)

### Why should we prioritize this feature?

Some mammography machines do not write the projection value in the "Series Description" tag, so the projection is not displayed on the screen

**Comment by sedghi** [comment]
You can already use customization service to achieve do
Docs.ohif.org
