### ISSUE TITLE
[Bug] Ultrasound rendering problems epic issue

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4082]
### Describe the Bug

I'm just putting here all the info for ultrasound green issues to be organized

### Steps to Reproduce

https://github.com/OHIF/Viewers/issues/2887
https://github.com/OHIF/Viewers/issues/3216
https://github.com/OHIF/Viewers/issues/3958
https://github.com/OHIF/Viewers/issues/3964
https://github.com/OHIF/Viewers/issues/4042
https://github.com/OHIF/Viewers/issues/4075
https://github.com/OHIF/Viewers/issues/4078
https://github.com/OHIF/Viewers/issues/4089
https://github.com/OHIF/Viewers/issues/4218

### The current behavior

d

### The expected behavior

d

### OS

d

### Node version

d

### Browser

d

**Comment by BITC01** [comment]
@sedghi 
Do you want me to re-upload the example study here ?

**Comment by sedghi** [comment]
yes please @BITC01 provide us with all the ultrasound that is broken so that we fix this once for all

**Comment by BITC01** [comment]
Ok. Heres the one that I tested with that displays the green overlay. 
[BrokenUS.zip](https://github.com/OHIF/Viewers/files/15210415/BrokenUS.zip)

**Comment by BITC01** [comment]
Do I just pull the latest cornerstone3D release to test this fix?

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
