### ISSUE TITLE
[Bug] Crosshair misalignment potentially cause by tool state when switching HP

### ISSUE THREAD

**Issue by dxlin** [OHIF/Viewers#4088]
### Describe the Bug

Possible different manifestation of previous crosshair bug noted by @03shek:
https://github.com/OHIF/Viewers/issues/3911

Two bugs, not sure if related:
1. Crosshair still selectable after switching out of MPR
This was previously resolved with a callback in the mpr hanging protocol definition to run 'toggleHangingProtocol'.

The crosshair correctly stops being selectable after a new image set is selected.

2. For some images (e.g. PCAMPRI in OHIF PACS) crosshair when entering MPR or changing images while under MPR can become misaligned

### Steps to Reproduce

1. Open PCAMPRI study in Basic mode from viewer
        -> https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.3671.4754.298665348758363466150039312520
2. From layout selector pick MPR
3. Enable crosshairs
4. From layout selector pick single viewport
        -> crosshair still selectable here
5. Drag & drop second image set 'DWI'
        -> crosshair now correctly disables
6. Switch to MPR
        -> crosshairs misaligned
7. Drag & drop any other image
        -> crosshairs still misaligned

Note: crosshair alignment can be fixed by selecting crosshair again.

https://github.com/OHIF/Viewers/assets/3317781/2adac2dd-e44b-4faa-88d7-1622afe8430e

### The current behavior

1. When switching out of MPR to single viewport layout, crosshair still selectable
2. Crosshair misaligned after reproduction steps

### The expected behavior

1. When switching out of MPR to single viewport layout, crosshair expected to be disabled (correctly done when image is changed after viewport layout change)
2. Crosshair expected to continue to remain aligned after reproduction steps

### OS

Windows 10

### Node version

18.16.0

### Browser

Chrome 124.0.6367.119

**Comment by sedghi** [comment]
Is this still happening?

**Comment by 03shek** [comment]
This looks fixed. Thanks!
