### ISSUE TITLE
[Bug] DICOM Files showing exams rotated and mirrored

### ISSUE THREAD

**Issue by NurGVaras** [OHIF/Viewers#4089]
### Describe the Bug

We have a study in our platform that is showing incorrectly, it shows flipped and mirrored, as in the image:

![Screenshot 2024-05-06 at 17 24 38](https://github.com/OHIF/Viewers/assets/94997677/5baa006b-6bc2-44b1-a5a7-bb69b60af11b)

when open the same study on Horos, the study opens correctly

<img width="1078" alt="Screenshot 2024-05-06 at 17 27 36" src="https://github.com/OHIF/Viewers/assets/94997677/ad55892b-d66e-4036-9c09-2a7f32bff1e3">

Study:

[Anonimo anonimo Centro Imagen.zip](https://github.com/OHIF/Viewers/files/15225904/Anonimo.anonimo.Centro.Imagen.zip)

### Steps to Reproduce

open the study on the viewer

### The current behavior

it shows mirrored

### The expected behavior

should look with the right orientation

### OS

macOS 

### Node version

the last one

### Browser

Chrome

**Comment by sedghi** [comment]
Thanks, we will look

**Comment by sedghi** [comment]
I'm pretty sure this is fixed, can you try again please

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
