### ISSUE TITLE
[Feature Request] Render DICOM RTSTRUCT Point Contours visually

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#4093]
### What feature or change would you like to see made?

The new fix for RTstructs in the most recent beta 3.90.2 is allowing rendering of almost all the RTstructs that used to not display.

The one exception so far is point probes.

If created in MIM for example a point probe is created it shows it as a mini cross hair
![image](https://github.com/OHIF/Viewers/assets/112980389/79fd8a91-6dca-4dee-adf9-229a52c2116e)

Currently when rendering in OHIF it doesn't appear at all but if clicked on in the side panel will localize to the correct slice.
![image](https://github.com/OHIF/Viewers/assets/112980389/a9af2ea5-6025-43d5-80b5-a866b543af69)

If we could display that point in some way that would be great.

### Why should we prioritize this feature?

Point contours are used a lot in RTplans to mark max doses or just to identify  the focal center of a region.

Displaying them along with the rest of the contours would be great and wouldn't leave the user confused where the contour went which is listed on the side panel.

**Comment by BrandonDatUHN** [comment]
You can find the dataset here https://fileshare.uhn.ca/download/d09ca363-b381-4c09-bf35-da6cfb3631db  -password outlook
please note this will expire on June 6 2024

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
