### ISSUE TITLE
[Feature Request] Miscellaneous UI Improvements: Address outdated UI components and add new functionality across the application

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4097]
### What feature or change would you like to see made?

- Redesign the Capture Tool modal to align with the modern UI
- Update the design of the local drag-and-drop page
- Add a "More" menu to viewports with options like:
    - Making a viewport go full screen
    - Printing the active viewport
    - Adding a scaling/overlay scale tool https://github.com/OHIF/Viewers/issues/4154
- Reduce the gap between viewports in the viewport grid

### Why should we prioritize this feature?

There are several minor UI components and features that have outdated designs or lack functionality. Addressing these issues through a miscellaneous UI improvements effort will enhance the overall user experience and bring consistency across the application. These changes may seem small individually, but collectively they can significantly improve usability and modernize the application's look and feel.

**Comment by sedghi** [comment]
Print function in Weasis https://weasis.org/en/tutorials/print/index.html

**Comment by insinfo** [comment]
the printout will be very useful

**Comment by sedghi** [comment]
This wasn't included in the scope of 3.9, but we will revisit it in future versions.

**Comment by mipaifu328** [comment]
May I ask if this feature has not yet been implemented, and how long it will take to be realized in the future

**Comment by mipaifu328** [comment]
> May I ask if this feature has not yet been implemented, and how long it will take to be realized in the future

Adding a scaling/overlay scale tool

**Comment by xbmlz** [comment]
It seems that the scaling/overlay scale tool has not been added yet
