### ISSUE TITLE
[3.9-TS] Expand Test Coverage with End-to-End and Visual Regression Tests: Implement E2E and visual regression tests to improve stability and quality

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4098]
### What feature or change would you like to see made?

- Implement end-to-end (E2E) tests to validate the entire user flow and experience
- Add visual regression tests to catch any unintended visual changes or regressions

### Why should we prioritize this feature?

Enhancing test coverage, particularly with E2E and visual regression tests, is crucial for improving the stability and quality of the viewer application.

**Comment by IbrahimCSAE** [comment]
https://github.com/cornerstonejs/cornerstone3D/pull/1250

**Comment by james-hanks** [comment]
- Add list of test coverage once ticket is complete
- Publish guide to community so they can contribute to test writing
