### ISSUE TITLE
[3.9-WW] Improve Web Worker Integration and Documentation: Enhance web worker support, documentation, and user experience.

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4100]
### What feature or change would you like to see made?

- Provide comprehensive documentation on using web workers in OHIF, including best practices and guidelines
- Implement a service or API for interacting with web workers, abstracting away low-level details
- Introduce UI elements or indicators to inform users when a web worker task is running or in progress
- Explore utilizing existing UI component libraries (e.g., @Shadcn/ui,Sonnet) for visually representing web worker tasks and their status
- Address potential issues or scenarios involving multiple concurrent web worker tasks or background operations
- 
related https://www.cornerstonejs.org/docs/concepts/cornerstone-core/webWorker

### Why should we prioritize this feature?

Web workers offer significant performance benefits by offloading computationally intensive tasks to separate threads, improving the overall responsiveness and user experience

**Comment by sedghi** [comment]
vscode has something similar 



![Image](https://github.com/OHIF/Viewers/assets/7490180/05ac5621-8c9a-4cc5-b1bd-8ef757653457)

**Comment by james-hanks** [comment]
@dan-rukas to review design to make sure it is consistent with new design and add any update here (if necessary)

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue.
