### ISSUE TITLE
[3.9-SS] Add Support for Stack Segmentation: Enable segmentation directly within stack viewports for various image types.

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4103]
### What feature or change would you like to see made?

- Implement support for stack segmentation, enabling segmentation directly within stack viewports instead of converting to volume viewports
- Leverage the stack segmentation capabilities already available in Cornerstone 3D
- Extend stack segmentation support to various image types, such as ultrasound, MG, DX, and CR
- Research and design the interaction between segmentation and other viewports (e.g., displaying segmentation on PET when segmented on CT)
- Consider adding a control or button in the viewport "More" menu to toggle the display of segmentation across different viewports

### Why should we prioritize this feature?

Stack segmentation is a crucial feature for efficient and accurate segmentation workflows, particularly for modalities like ultrasound and other 2D image types. By prioritizing this feature, OHIF will enable users to perform segmentation directly within stack viewports, eliminating the need for conversions and providing a more intuitive and streamlined experience. 

Designing the interaction between segmentation and other viewports will ensure a cohesive and consistent experience across different data types and modalities.

**Comment by james-hanks** [comment]
Prereq Cornerstone 3D 2.0 ticket

https://github.com/cornerstonejs/cornerstone3D/issues/717

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue.
