### ISSUE TITLE
[3.9-PM] Support for Parametric Maps and AI Results Visualization: Enable display and analysis of parametric maps and AI results

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4105]
### What feature or change would you like to see made?

- Implement support for loading and displaying parametric maps within the OHIF viewer
- Enable overlaying AI results, such as probabilities or predictions, as parametric maps on top of the primary image data
- Connecting the colorbar or legend for visualizing the color mapping and values of the parametric map data
- Provide rendering controls and options to customize the color mapping, opacity, and appearance of the parametric map overlay

### Why should we prioritize this feature?

Visualizing and interacting with parametric maps and AI results is crucial for medical imaging applications in research and clinical settings. Prioritizing this feature positions OHIF as a powerful platform for exploring and analyzing AI-generated data like probability maps or later on RTDosemaps.

**Comment by sedghi** [comment]
Here is the data and how it renders in 3d slicer https://www.dropbox.com/scl/fo/x18i4nnvbxnokcf140jbk/AMcfA04DK_1oa0hJ_C_7DTQ?rlkey=lkc5e3fr0zpjn6lwesz9x9iar&dl=0


![CleanShot 2024-05-22 at 15 52 14@2x](https://github.com/OHIF/Viewers/assets/7490180/c860e34f-74b4-4e93-bdec-779c50f54903)

**Comment by fedorov** [comment]
@sedghi which specific file in the dropbox folder referenced above are you referring to as "parametric map"?

**Comment by sedghi** [comment]
There is one called `image_proba.dcm`

**Comment by fedorov** [comment]
Thank you. I just wanted to confirm this is a parametric map and not a probability SEG.

**Comment by sedghi** [comment]
Hmm, what is probability SEG? Like partial segmentation?

**Comment by fedorov** [comment]
DICOM SEG can be binary or fractional, with fractional reflecting probability or partial occupancy. You can see here: https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.20.2.html#table_C.8.20-2 and here https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.20.2.3.html.
