### ISSUE TITLE
How can i Layout Viewpoint By Study Instance？

### ISSUE THREAD

**Issue by wangning08115** [OHIF/Viewers#4111]
### What feature or change would you like to see made?

How can i Layout Viewpoint By Study Instance？
Now the Viewer Layout Viewpoint is by Series.
I want to see one Series all Instance in one ViewPort like below Screen:
All Dicom Image in one ViewPort, doctor can see the dicom image details.
![image](https://github.com/OHIF/Viewers/assets/3455705/d47cd89b-6946-4d44-9649-3e5feaee1f75)

### Why should we prioritize this feature?

All Dicom Image ine one ViewPort, doctor can see the dicom image details.

**Comment by sedghi** [comment]
See [Hanging Protocol Module](https://docs.ohif.org/platform/extensions/modules/hpModule) and [Hanging Protocol Service](https://docs.ohif.org/platform/services/data/HangingProtocolService)
