### ISSUE TITLE
[Bug] Viewport Properties are reseted when Different images are loaded on the same stack viewport

### ISSUE THREAD

**Issue by kushgadhvi16** [OHIF/Viewers#4117]
### Describe the Bug

When loading the attached MR image in OHIF with the useNorm16Texture option set to True, inconsistencies arise due to different data types across slices. Specifically, some images are of the data type UInt16, while others are Int16. This difference in data types causes the application to treat these as distinct images, resulting in the reset of viewport properties such as Zoom, Pan, and VOI settings upon scrolling through slices.
[1OK3XA55.zip](https://github.com/OHIF/Viewers/files/15269664/1OK3XA55.zip)

**OHIF Office Notes:-**
Q:  Preventing reset of viewport properties when different images are loaded on the same stack viewport.
A: One option is to split the images into separate display sets so that they are consistent within the display set.

For the zoom/pan data, the recent changes for getViewPresentation should help this, although it may not have gotten included at the right level. Once that has been merged to OHIF if it is still an issue, could you create an issue for this?

For the window level, it should be possible to preserve that VOI as long as the basic range between images is similar. The problem currently is that a new actor is required because of differences in rendering, and that causes the reset to occur. The fix is to re-apply the view presentation.

### Steps to Reproduce

1) Load the attached MR image in OHIF with useNorm16Texture set to True in default.js.
2) Scroll through the slice.
3) Observe that Zoom, Pan, and VOI settings

### The current behavior

Zoom, Pan , VOI and other viewport properties are reset 

### The expected behavior

Zoom, Pan , VOI and other viewport properties should be maintained when scrolling through the slices.

### OS

macOS 14.4.1

### Node version

18.12.1

### Browser

Chrome

**Comment by arturojain** [comment]
does this also happen with the `preferSizeOverAccuracy` option?

**Comment by sedghi** [comment]
This is fixed, check latest
