### ISSUE TITLE
[Bug] PDF appear dark (wont properly load)

### ISSUE THREAD

**Issue by niirdan** [OHIF/Viewers#4118]
### Describe the Bug

![Screenshot 2024-05-12 101944](https://github.com/OHIF/Viewers/assets/121875046/37ec61e6-2272-46f2-99dd-8bfd523fb3bc)
Looks like pdf couldn't be loaded properly 

### Steps to Reproduce

open a study containing pdf document

***note! i am using google healthcare api .**

### The current behavior

pdf viewer inside ohif wont load

### The expected behavior

pdf presented correctly 

### OS

window 11

### Node version

v18.17.1

### Browser

latest chrome update

**Comment by sedghi** [comment]
What is your server? can you provide the anonymized data?

Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by niirdan** [comment]
@sedghi hey sedghi , i am not sure i understood you 100% , but i attach the dicom's meta data (censoring its patient info )
I am using dcmtk for encapsulating the pdf to dicom and dcmtk dcmodify to add necessary information about the study and patient 
![Screenshot 2024-05-15 090416](https://github.com/OHIF/Viewers/assets/121875046/dba1664b-7a01-4511-be35-362b3c9cc0d2)

**Comment by niirdan** [comment]
good morning, popping up due that it is still appears in the latest version

**Comment by niirdan** [comment]
Hey alizera thanks for your response,
I uploaded a photo of the meta data’s file (pdf)
I confirm it doesn’t contain real patient information- it has been censored

**Comment by sedghi** [comment]
No i meant the actual dicom file, do you have it and can you share it?

**Comment by niirdan** [comment]
> No i meant the actual dicom file, do you have it and can you share it?
Yes Of course ! 
unfortunately github doesn't allow dcm format so i will upload it here : 
https://www.jumbomail.me/l/en/gallery/697273696E617777705662464B3342347436653838673D3D/1181030228
let me know if you an issue downloading it

**Comment by sedghi** [comment]
So when i drag and drop it in local it works fine https://viewer-dev.ohif.org/localbasic

![CleanShot 2024-05-28 at 18 10 46@2x](https://github.com/OHIF/Viewers/assets/7490180/afb13404-f496-46a4-bbf3-2ceb1fb18ea6)

What server are you using?
these things are most likely server depndent

Have you seen this
https://docs.ohif.org/configuration/datasources/dicom-web/#singlepart

**Comment by sedghi** [comment]
I saw you use google healthcare

I uploaded your data to our google healthcare and i see the instance is this

![CleanShot 2024-05-28 at 18 18 26@2x](https://github.com/OHIF/Viewers/assets/7490180/1e31b438-27af-4c76-ad38-3a468c18554a)

And basically this comes back undefined

```
 const pdfUrl = dataSource.retrieve.directURL({
      instance,
      tag: 'EncapsulatedDocument',
      defaultType: MIMETypeOfEncapsulatedDocument || 'application/pdf',
      singlepart: 'pdf',
    });
```

Since there is not `EncapsulatedDocument` tag that google sends back and as I understand this is a type 1 attribute

https://dicom.innolitics.com/ciods/encapsulated-pdf/encapsulated-document/00420011

I demo server provides a bulkDataURI

![CleanShot 2024-05-28 at 18 20 58@2x](https://github.com/OHIF/Viewers/assets/7490180/640e9ca1-11c4-4f63-af0e-f37056b0e08a)

And Orthanc provides this too

![CleanShot 2024-05-28 at 18 22 01@2x](https://github.com/OHIF/Viewers/assets/7490180/2eeced82-992e-48d0-be20-288b77f51289)

So i believe this is a issue with how google is responding back. 

Tagging @jasonklotzer to see if he knows more about DICOM PDF on Google Healthcare

**Comment by jasonklotzer** [comment]
BulkDataURI is only available when using the beta API right now. Please [try it out](https://cloud.google.com/healthcare-api/docs/how-tos/dicomweb#retrieve-bulkdata) and tell me how it goes.

**Comment by niirdan** [comment]
> BulkDataURI is only available when using the beta API right now. Please [try it out](https://cloud.google.com/healthcare-api/docs/how-tos/dicomweb#retrieve-bulkdata) and tell me how it goes.

Hey jason @jasonklotzer , thanks for responding 
do to mean to change    
          'https://healthcare.googleapis.com/v1**beta1**/projects/XXXX/locations/me-west1/datasets/XX-dataset/dicomStores/XX-datastore/dicomWeb' on ohif's google.js settings ? 
as far as i understand it still return undefined due to the fact that the file's meta data haven't changed .. 
I will be happy for a tiny explanation what to change in this process ?

**Comment by jasonklotzer** [comment]
@sedghi It would be helpful for you to take a look at the API and validate whether that conforms to the OHIF expectations for interacting with a BulkDataURI provider? 

@niirdan Yes, the Google Healthcare API DICOM store added support for generating BulkDataURI's and retrieving their referenced payload, and that support is currently in the `v1beta1` version of the API. The underlying database has also been populated (backfilled) with any relevant bulk data references, so upon using this version of the API you should see BulkDataURI references.

**Comment by sedghi** [comment]
Interesting, I'll check

**Comment by niirdan** [comment]
> @sedghi It would be helpful for you to take a look at the API and validate whether that conforms to the OHIF expectations for interacting with a BulkDataURI provider?
> 
> @niirdan Yes, the Google Healthcare API DICOM store added support for generating BulkDataURI's and retrieving their referenced payload, and that support is currently in the `v1beta1` version of the API. The underlying database has also been populated (backfilled) with any relevant bulk data references, so upon using this version of the API you should see BulkDataURI references.

Thanks for the response , after using v1beta1 looks like it's still returning undefined

**Comment by sedghi** [comment]
I see the bulkDataURI in the `v1beta1` 

![CleanShot 2024-06-05 at 22 57 22@2x](https://github.com/OHIF/Viewers/assets/7490180/3cc87ea8-1aea-4c34-8a57-23e2f69a0a48)

and i was able to render it 

![CleanShot 2024-06-05 at 23 02 17@2x](https://github.com/OHIF/Viewers/assets/7490180/7811f64f-b1bc-45aa-9d13-4b44f7dfca32)

these are the changes required

![CleanShot 2024-06-05 at 23 02 32@2x](https://github.com/OHIF/Viewers/assets/7490180/3f567ef0-b15a-44b9-ab43-61314ab3cc2d)

**Note the bulkDataURI enabled**

@niirdan Would you be able to add a section to our documentation with a pull request describing the `v1beta1` and `bulkDataURI`?

Maybe here https://docs.ohif.org/configuration/datasources/dicom-web/#bulkdatauri

**Comment by niirdan** [comment]
> I see the bulkDataURI in the `v1beta1`
> 
> ![CleanShot 2024-06-05 at 22 57 22@2x](https://private-user-images.githubusercontent.com/7490180/337084722-3cc87ea8-1aea-4c34-8a57-23e2f69a0a48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Nzc5ODAsIm5iZiI6MTcxNzY3NzY4MCwicGF0aCI6Ii83NDkwMTgwLzMzNzA4NDcyMi0zY2M4N2VhOC0xYWVhLTRjMzQtOGE1Ny0yM2UyZjY5YTBhNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTI0MTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE0ZmFjNjZlNWEyNGYzOGQ5ZjhiNjFiMTFkMjI2ZmYyMjY4NzIxNDI5ZWEzNWIxZWY4N2UyODcyODYxM2ZhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LedRiXR7MYVar6RvXxAwNsb_u71kuyBey6iIl58u1K4)
> 
> and i was able to render it
> 
> ![CleanShot 2024-06-05 at 23 02 17@2x](https://private-user-images.githubusercontent.com/7490180/337085453-7811f64f-b1bc-45aa-9d13-4b44f7dfca32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Nzc5ODAsIm5iZiI6MTcxNzY3NzY4MCwicGF0aCI6Ii83NDkwMTgwLzMzNzA4NTQ1My03ODExZjY0Zi1iMWJjLTQ1YWEtOWQxMy00YjQ0ZjdkZmNhMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTI0MTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUwNTEwOWQ1ZGY4ZWMxMzAwODU1MmM1NzY1YjQzMjNkNzI5Yzk3NzQyNGRjYzc0YTdiMGE2MWI5ZmQ0MWNlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-8mKOvr0HX5yIz-4kZB6Olsebmkki_cu3z3A6tGQC1s)
> 
> these are the changes required
> 
> ![CleanShot 2024-06-05 at 23 02 32@2x](https://private-user-images.githubusercontent.com/7490180/337085473-3f567ef0-b15a-44b9-ab43-61314ab3cc2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Nzc5ODAsIm5iZiI6MTcxNzY3NzY4MCwicGF0aCI6Ii83NDkwMTgwLzMzNzA4NTQ3My0zZjU2N2VmMC1iMTVhLTQ0YjktYWI0My02MTMxNGFiM2NjMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTI0MTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmE3MDMzYmFkZjA1NGQyYzE1MDBiYTA4Njc5NjZjMThiNGViZGM5YWY1ZGI5NTFiYTJlZmRiYjFiNmRkMjE2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eoUhZFX3k9DrDH7iWSJIwrFHbTJb6xtZ6VQw1Sl1T6U)
> 
> **Note the bulkDataURI enabled**
> 
> @niirdan Would you be able to add a section to our documentation with a pull request describing the `v1beta1` and `bulkDataURI`?
> 
> Maybe here https://docs.ohif.org/configuration/datasources/dicom-web/#bulkdatauri

Done !

**Comment by thereddycr** [comment]
@sedghi 
> I'm experiencing a similar issue where the page is blank, but only for the PDF viewer. All other viewers work well with the same setup, and the PDF viewer does work when I upload documents locally (`https://viewer-dev.ohif.org/localbasic`). I am using a `dicomjson` datasource with the following JSON data:
> 
> ```json
> {
>   "studies": [
>       {
>           "StudyInstanceUID": "1.2.276.0.7230010.3.1.2.2344313775.14992.1458058363.6979",
>           "StudyDate": "20130812",
>           "StudyTime": "164709.000",
>           "PatientName": "CARDIO",
>           "PatientID": "7B23891B-E78E-43DC-AE6C-55AFC72FC51C",
>           "AccessionNumber": "",
>           "PatientAge": "",
>           "PatientSex": "",
>           "Modalities": "OT",
>           "NumInstances": 0,
>           "series": [
>               {
>                   "SeriesInstanceUID": "1.2.276.0.7230010.3.1.3.1901948703.36080.1484835349.617",
>                   "SeriesNumber": 0,
>                   "Modality": "OT",
>                   "SliceThickness": 0,
>                   "instances": [
>                       {
>                           "metadata": {
>                               "Columns": 0,
>                               "Rows": 0,
>                               "InstanceNumber": 0,
>                               "SOPClassUID": "1.2.840.10008.5.1.4.1.1.104.1",
>                               "PhotometricInterpretation": "",
>                               "BitsAllocated": 0,
>                               "BitsStored": 0,
>                               "PixelRepresentation": 0,
>                               "SamplesPerPixel": 0,
>                               "PixelSpacing": [],
>                               "HighBit": 0,
>                               "ImageOrientationPatient": [1, 0, 0, 0, 1, 0],
>                               "ImagePositionPatient": [0, 0, 0],
>                               "FrameOfReferenceUID": "",
>                               "ImageType": [],
>                               "Modality": "OT",
>                               "SOPInstanceUID": "1.2.276.0.7230010.3.1.4.1901948703.36080.1484835349.618",
>                               "SeriesInstanceUID": "1.2.276.0.7230010.3.1.3.1901948703.36080.1484835349.617",
>                               "StudyInstanceUID": "1.2.276.0.7230010.3.1.2.2344313775.14992.1458058363.6979",
>                               "WindowCenter": 0,
>                               "WindowWidth": 0,
>                               "SeriesDate": "20130814"
>                           },
>                           "url": "dicomweb:https://bytepadstoragedev.blob.core.windows.net/dicom-dev-data/DCM/2.25.274511628741404487568958573697750835997/DCM_WITH_PDF_OT000000.dcm?sv=2023-01-03&st=2024-09-01T13%3A59%3A58Z&se=2027-12-31T14%3A00%3A00Z&sr=c&sp=rl&sig=oqZTTck06%2BipiSptCd4i7pmh8Y2A1ikNuB6Rx0%2BC22E%3D"
>                       }
>                   ]
>               }
>           ]
>       }
>   ]
> }
> ```
> 
> My current configuration is:
> 
> ```javascript
> /** @type {AppTypes.Config} */
> window.config = {
>   routerBasename: '/',
>   extensions: [],
>   modes: [],
>   dataSources: [
>     {
>       namespace: '@ohif/extension-default.dataSourcesModule.dicomjson',
>       sourceName: 'dicomjson',
>       configuration: {
>         friendlyName: 'dicom json',
>         name: 'json',
>         singlepart: 'bulkdata,video,pdf',
>         bulkDataURI: {
>           enabled: true,
>           relativeResolution: 'series',
>         },
>       },
>     },
>   ],
>   defaultDataSourceName: 'dicomjson',
> };
> ```
> 
> Additionally, in the console, I am seeing the following error message:
> 
> ```
> rendered:1  Uncaught (in promise) InvalidStateError: Failed to get ServiceWorkerRegistration objects: The document is in an invalid state.
> ```
> 
> I've tried different configurations without success. Are there any specific settings or configurations that might address the blank page in the PDF viewer? Any guidance would be appreciated.
