### ISSUE TITLE
Zoom tool not work in mobile

### ISSUE THREAD

**Issue by wangning08115** [OHIF/Viewers#4121]
### Describe the Bug

Zoom tool not work in mobile， it cant zoom the image, only can move the image

### Steps to Reproduce

1. open viewer in mobile
2. use Zoom tool
3. Zoom tool not work in mobile

### The current behavior

Zoom tool can zoom image in mobile

### The expected behavior

Zoom tool not work in mobile， it cant zoom the image, only can move the image

### OS

windows 10

### Node version

20

### Browser

chrome in mobile mode
![image](https://github.com/OHIF/Viewers/assets/3455705/965a09e5-5975-411a-afae-bb3e8b87900c)

**Comment by sedghi** [comment]
It is not configured in the app yet, we are pushing on mobile design in the next release, stay tuned

**Comment by sedghi** [comment]
https://ohif.org/roadmap/Q2-2024
