### ISSUE TITLE
[Bug] RTSTRUCT does not show up

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#4124]
### Describe the Bug

None of the RTSTRUCTs in this study show up in the viewer: https://viewer.imaging.datacommons.cancer.gov/v3/viewer/?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1078.3273.382194720873684027956624363347.

### Steps to Reproduce

Download the study referenced above and load in the viewer.

### The current behavior

No structures show up in the viewer. Some of the RTSTRUCTs loaded show up in the list, but clicking on the item in the list does not result in anything being shown.

### The expected behavior

Slicer + SlicerRT extension loads this

<img width="1126" alt="image" src="https://github.com/OHIF/Viewers/assets/313942/c66c8f7e-968f-48b6-9cd8-198037423071">

### OS

macOS

### Node version

n/a

### Browser

Chrome

**Comment by sedghi** [comment]
Seems like you are using an outdated version of OHIF. Could you please try the latest release? We have resolved some issues related to RT.

**Comment by fedorov** [comment]
@igoroctaviano can you please check and update?

**Comment by sedghi** [comment]
Maybe wait, @IbrahimCSAE is fixing another RT bug tomorrow, then update?

**Comment by igoroctaviano** [comment]
@sedghi @IbrahimCSAE please let me know when to test this.

**Comment by sedghi** [comment]
tomorrow

**Comment by igoroctaviano** [comment]
@pedrokohler please investigate/replicate this issue.

**Comment by fedorov** [comment]
This is now resolved!
