### ISSUE TITLE
[Bug] Study with a scout series, RTSTRUCT renders on scout instead of its source series.

### ISSUE THREAD

**Issue by jenny-hm-lee** [OHIF/Viewers#4130]
### Describe the Bug

ohif v3.9.beta-2

The example is a study with series of **same** FoR (frame of reference), but first series is a scout/localizer.  In a multiple viewport setup, RTSTRUCT always renders on scout/localizer instead of its source series.

Note that a scout/localizer is a quick scan performed by the machine to localize the patient in spaces.

### Steps to Reproduce

Use the dataset that was previously shared in #4093.   
Or you can find the dataset here https://fileshare.uhn.ca/download/d09ca363-b381-4c09-bf35-da6cfb3631db 
password outlook
please note this will expire on June 6 2024

1. open the study and set up 2 viewports.  Set the first (right) viewport to be "scout wb".  Set second (left) viewport to be "CT Std".
2. drag and drop "RT on CT.simplified" RTSTRUCT on the second (left) viewport.  Note, the source image of this RTSTRUCT is CT Std.
3. Expected behaviour is RTSTRUCT loads on second (left) viewport.  Actually, it loads on first (right) viewport **only**.

### The current behavior

In this multiple viewport setup, the RTSTRUCT renders ONLY on the scout image.  

### The expected behavior

In this multiple viewport setup, the RTSTRUCT should renders on its source image.  

### OS

Windows

### Node version

?

### Browser

chrome

**Comment by sedghi** [comment]
@jenny-hm-lee I think this is fixed right?

**Comment by jenny-hm-lee** [comment]
@sedghi ,
On 3.9.0.beta.26, on the basic mode, the rtstruct does not render on the scout anymore.  But now, when clicking on the ROI on the segmentation panel, the viewport does not localize to the ROI.

**Comment by sedghi** [comment]
I will close this and can we make another issue for jump?
