### ISSUE TITLE
UI bug in Segmentation panel "Segmentation List" panel does not display all segmentations in list - 3.9.0-beta.6 [Bug]

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#4132]
### Describe the Bug

The Segmentation dropdown in segmentation mode (and basic mode) is not displaying all Segmentations if there are more than 1 or 2.  In this screenshot there are 4 but the drop down only shows Segmentation 1 and 2.

![image](https://github.com/OHIF/Viewers/assets/112980389/75cbbd42-2635-4f46-9c95-a30fc6877bcc)

If I add more segments you will now be able to see all segmentations

![image](https://github.com/OHIF/Viewers/assets/112980389/a05697e4-992a-430f-b44e-7eafaa65614d)

Basically the dropdown goes as far down as the last Segment in the list.

### Steps to Reproduce

1) Load any study in segmentation mode
2) Add a new Segmentation 
3) repeat 3 more times until you should have 4
4) click the drop down to try and select segmentation 3, only segmentation 1 and 2 will be visible

### The current behavior

The segmentation selection dropdown is only showing the first couple list items (depending on number of segments in the current Segmentation)

### The expected behavior

All segmentations loaded should appear in the segmentation drop down.

### OS

Windows 11

### Node version

Using OHIF Demo 

### Browser

Version 124.0.6367.203 (Official Build) (64-bit)

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
