### ISSUE TITLE
Is this a bug ？_getViewportInstances function

### ISSUE THREAD

**Issue by wangning08115** [OHIF/Viewers#4134]
### What feature or change would you like to see made?

i think the _getViewportInstances function has bug

### Why should we prioritize this feature?

file:
D:\OhifViewerV3\extensions\cornerstone\src\Viewport\Overlays\CustomizableViewportOverlay.tsx

function: 

`
function _getViewportInstances(viewportData) {
  const imageIds = [];
  if (viewportData.viewportType === Enums.ViewportType.STACK) {
    imageIds.push(viewportData.data.imageIds[0]);
  } else if (viewportData.viewportType === Enums.ViewportType.ORTHOGRAPHIC) {
    const volumes = viewportData.data;
    volumes.forEach(volume => {
      if (!volume?.imageIds || volume.imageIds.length === 0) {
        return;
      }
      imageIds.push(volume.imageIds[0]);
    });
  }
  const instances = [];

  imageIds.forEach(imageId => {
    const instance = metaData.get('instance', imageId) || {};
    instances.push(instance);
  });
  return instances;
}`

i want to know the line : 
imageIds.push(viewportData.data.imageIds[0]);
is this a bug? it Always get the first image use 【imageIds[0])】
i think the _getViewportInstances function is get current Viewport all Instances , not the first image.
so is this a bug?

**Comment by wangning08115** [comment]
`function _getViewportInstances(viewportData) {
  const imageIds = [];
  if (viewportData.viewportType === Enums.ViewportType.STACK) {
    imageIds.push(viewportData.data.imageIds[0]);
  } else if (viewportData.viewportType === Enums.ViewportType.ORTHOGRAPHIC) {
    const volumes = viewportData.data;
    volumes.forEach(volume => {
      if (!volume?.imageIds || volume.imageIds.length === 0) {
        return;
      }
      imageIds.push(volume.imageIds[0]);
    });
  }
  const instances = [];

  imageIds.forEach(imageId => {
    const instance = metaData.get('instance', imageId) || {};
    instances.push(instance);
  });
  return instances;
}`

**Comment by sedghi** [comment]
it is not a bug, if we add all instances you will get all the same study information in here



![Image](https://github.com/OHIF/Viewers/assets/7490180/3df5d7a4-1300-4e56-b9cc-cacd94623e51)
