### ISSUE TITLE
[Feature Request] optionally install cypress and docusaurus in the dev install

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4137]
### What feature or change would you like to see made?

It takes a lot of time every `yarn install` we should make those really optional

### Why should we prioritize this feature?

d

**Comment by james-hanks** [comment]
#4016 fix

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
