### ISSUE TITLE
[Feature Request] add a button to print the image of the current view and also a button to print all images 

### ISSUE THREAD

**Issue by insinfo** [OHIF/Viewers#4140]
### What feature or change would you like to see made?

add a button to print the image of the current view, and also a button to print all images in a sequence similar to a PDF with an image on each page of the PDF and with patient data such as Name, patient ID and date of birth

### Why should we prioritize this feature?

Direct printing of the current view is a recurring request from doctors and radiologists, and I think it would be a very simple implementation to do.

**Comment by sedghi** [comment]
We have something in mind for basic print functionality. Stay tuned. https://github.com/OHIF/Viewers/issues/4097
