### ISSUE TITLE
[Bug] The Image Overlay doesn't work

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#4142]
### Describe the Bug

Click "Image Overlay", nothing is changed in the image viewport.

### Steps to Reproduce

- Open and go to an image viewport
- Click "Image Overlay" from the dropdown toolbar 

### The current behavior

Nothing is changed in the image viewport.

### The expected behavior

Show/hide information displayed on the current viewport when clicking

### OS

Ubuntu 

### Node version

21.7.3

### Browser

Chrome  124.0.6367.207

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by jenny-hm-lee** [comment]
this button is supposed to display the overlay data available in the dicom header.  If your dicom doesn't have such overlay data, nothing will changed on the viewport.

I was confused too, when I first saw the button.  I thought the button is for overlaying two images.

**Comment by sedghi** [comment]
Our data does not have overlay, but if your dicom file has it will show it
