### ISSUE TITLE
[Bug] StudyDate sort

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#4143]
### Describe the Bug

Sort by StudyDate is incorrect if there are multiple studies of the same date.
The sort by date only.

### Steps to Reproduce

Make sure you have multiple studies of the same date
- Go to the Studylist
- Click sort on StudyDate (sort ascending) 

### The current behavior

For studies of same date, the morning studies (AM) is displayed above the PM studies

### The expected behavior

For studies of same date, the PM studies must be displayed above the AM studies

### OS

Ubuntu 

### Node version

21.7.3

### Browser

Chrome  124.0.6367.207

**Comment by sedghi** [comment]
We are working on this in the next version

**Comment by niirdan** [comment]
> We are working on this in the next version

The next stable or beta version ? 
thanks in advance

**Comment by sedghi** [comment]
next beta soon and next release later
