### ISSUE TITLE
[Bug] Sometimes tmtv has wrong invert for the fusion

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4148]
### Describe the Bug

If you refresh, it seems like at some point, one of the viewports in the fusion row will become inverted for some reason in tmtv

### Steps to Reproduce

refresh tmtv

### The current behavior

d

### The expected behavior

d

### OS

d

### Node version

d

### Browser

d

**Comment by jenny-hm-lee** [comment]
we have seen this as well.

**Comment by 03shek** [comment]
This is in MPR mode also, viewports should be synced in inverting, but they're not

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
