### ISSUE TITLE
Switching between two SEGs causes hanging protocol button to become unresponsive (3.9.14)[Bug]

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#4158]
### Describe the Bug

After loading multiple SEGs and switching between them the layout/hanging protocol button will become unresponsive

### Steps to Reproduce

1) Load https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.3671.4754.298665348758363466150039312520
2) Load the first two segs
![image](https://github.com/OHIF/Viewers/assets/112980389/2ca0fb50-f2cb-47d0-b91e-3e5566aac28c)
3) switch back to the first SEG (T2 Weighted...)
4) The layout/Hanging protocol button will no longer work (other buttons still do)

### The current behavior

After loading multiple SEGs and switching between them the layout/hanging protocol button will become unresponsive

### The expected behavior

Hanging protocol button should work regardless of number of SEGs loaded or selection panel.

### OS

Win 11

### Node version

OHIF DEMO

### Browser

Version 125.0.6422.61 (Official Build) (64-bit)

**Comment by jenny-hm-lee** [comment]
This bug is found on OHIF v3.9.beta.14
