### ISSUE TITLE
Loading an SR with annotations after loading a DICOM Seg will cause OHIF to become unresponsive (3.9.14) [Bug]

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#4159]
### Describe the Bug

If you load up an image set with a DICOM SR of saved OHIF annotations they will load fine.  
![image](https://github.com/OHIF/Viewers/assets/112980389/737bb02b-045d-443a-945d-b92602725c24)
If you then load a SEG saved on the same series that will load fine too.
![image](https://github.com/OHIF/Viewers/assets/112980389/16e325c5-1996-4d9a-aac5-956424597644)
But if you try and load the SR after the SEG (or a second time once the seg is loaded) OHIF (and chrome) will become unresponsive.
![image](https://github.com/OHIF/Viewers/assets/112980389/8829c30e-5936-4c6f-8e69-5265734ede5e)

### Steps to Reproduce

There are no image sets in the OHIF DEV Viewer Demo with an SR of saved annotations and a SEG or RTstruct.

I've created the screen shots above using  https://viewer-dev.ohif.org/viewer/dicomlocal?StudyInstanceUIDs=2.16.840.1.114362.1.12114306.25269253871.663129508.995.565

You can download it here https://fileshare.uhn.ca/download/dae7eb16-b2e9-4fbe-b63f-7071699abe22 
Please note that this file upload will expire in 30 days. 

1) Load the image set in Basic Mode
2) Drag the SR into the main frame (3 circular annotations appear)
3) Drag the SEG into the main frame (it will render)
4) drag the SR into the main frame (OHIF will Hang)

Alternate

1) Load the image set in Basic Mode
2) Drag the SEG into the main frame (it will render)
3) drag the SR into the main frame (OHIF will Hang)

### The current behavior

Loading a DICOM SEG or RT STRUCT forces the view to switch to 3D.  Loading the SR based annotations after that appears to crash.

### The expected behavior

SRs should load properly on the 3D viewer after a Seg has loaded.  You can create new annotations after loading a SEG so the 3D window seems to handle it however it will crash when you try and export the report (can't do this on the demo but it does hang on 3.9.14 on QIPCM)

### OS

Win 11

### Node version

OHIF DEMO version

### Browser

Version 125.0.6422.61 (Official Build) (64-bit)

**Comment by sedghi** [comment]
This should have been fixed now with 3.9, can you double check? please re-open if not
