### ISSUE TITLE
[Feature Request] Viewport-Specific Control Panel

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4162]
### What feature or change would you like to see made?

There is a need for a fusion UI for foreground/background, as well as for segmentation. Since we are transitioning to stack-based segmentation as the default, another viewport will not display the segmentation by default. Previously, it would show segmentation since it was volume-based frame of reference segmentation rendering. However, for stack-based rendering, it will not. Therefore, a UI is required to enable rendering segmentation on this viewport as well.

![image](https://github.com/OHIF/Viewers/assets/7490180/ff070b04-f2d6-4e77-8844-9415f05b6744)

### Why should we prioritize this feature?

- Fusion inside UI for rendering foreground/background
- Rendering segmentation
- In the future, changing the segmentation representation from labelmap to contour, etc.
- Rendering segmentation in 3D viewports

### Requirements for Panel

- to be added

**Comment by sedghi** [comment]
Related https://github.com/OHIF/Viewers/issues/4163

**Comment by james-hanks** [comment]
@dan-rukas to provide concept for viewport panel then we will review and make sure all required features are added
