### ISSUE TITLE
About the issue of loading dicom files

### ISSUE THREAD

**Issue by Wyd7151961** [OHIF/Viewers#4166]
### What feature or change would you like to see made?

Now we can only double-click the left thumbnail to load the right file, which is not good for physical examination. When there are many images, double clicking can load them, which can affect usage. Is there any configuration? After the first thumbnail is loaded, it can be automatically loaded backwards until all the loading is completed

### Why should we prioritize this feature?

Now we can only double-click the left thumbnail to load the right file, which is not good for physical examination. When there are many images, double clicking can load them, which can affect usage. Is there any configuration? After the first thumbnail is loaded, it can be automatically loaded backwards until all the loading is completed

**Comment by sedghi** [comment]
We are working on background caching here; I will close this issue.

https://github.com/OHIF/Viewers/issues/3363

**Comment by Wyd7151961** [comment]
&nbsp;Which version is expected to solve my problem？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OHIF/Viewers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月24日(星期五) 晚上10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OHIF/Viewers] About the issue of loading dicom files (Issue #4166)





 
Closed #4166 as completed.

**Comment by sedghi** [comment]
follow 3363 please

**Comment by Wyd7151961** [comment]
Hello, using the example on our website, a sequence of over 200 images, clicking on the MPR will cause the browser to freeze and black screen. Is there a good solution for this







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OHIF/Viewers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月27日(星期一) 晚上11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OHIF/Viewers] About the issue of loading dicom files (Issue #4166)





 
follow 3363 please

**Comment by Wyd7151961** [comment]
Why does it take so long to download the orthanc dicom service directly configured on my local computer







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OHIF/Viewers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月27日(星期一) 晚上11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OHIF/Viewers] About the issue of loading dicom files (Issue #4166)





 
follow 3363 please
