### ISSUE TITLE
[Bug] Stack viewport broken when switch from volume viewport if set config useNorm16Texture = true

### ISSUE THREAD

**Issue by tunglt1810** [OHIF/Viewers#4167]
### Describe the Bug

Hi guys, 
I am working with a fork version which forked since 4 months ago.
I faced with an issue when trying switch hanging protocol from mpr to default.
The first time loaded and render is ok.
I switch to protocol `primaryAxial` is ok. But when switch back to protocol `default`, it looks like image is crashed.
But one more time when I switch to protocol `primaryAxial`, the viewports look fine.
<img width="1099" alt="first load ok" src="https://github.com/OHIF/Viewers/assets/19906349/1e2f4903-f8ab-4b61-b0c8-5ab7dfda2109">
<img width="1112" alt="primaryAxial ok" src="https://github.com/OHIF/Viewers/assets/19906349/93428e4e-7fca-4e41-b774-632297ce33dd">
<img width="1087" alt="errors" src="https://github.com/OHIF/Viewers/assets/19906349/0aa35c5b-fe7e-41a8-8a1e-a6aeeeee2dca">

Maybe I was wrong in wording, so I raise this issue to ask about some hints to debug this issue

### Steps to Reproduce

1. Run app
2. Open the first study `CTA Head and Neck`
<img width="951" alt="image" src="https://github.com/OHIF/Viewers/assets/19906349/90a37d43-f9d5-409f-9a0b-9f382b6b4e87">
3. Switch to hanging protocol `primaryAxial`
4. Switch back to handing protocol `default`

### The current behavior

After switch hanging protocol from `primaryAxial` to `default`, viewport image looks like broken

### The expected behavior

I expect that viewport image will be not broken

### OS

macOS 14.5

### Node version

v18.16.1

### Browser

Chrome 125.0.6422.61

**Comment by tunglt1810** [comment]
Or does stack viewport corrupted?

**Comment by tunglt1810** [comment]
Now I can reproduce the error.
I made a command that toggle between volume and stack viewport.
`
toggleSwitchMPR: async ({ orientation }) => {
			// console.log('switch viewport to MPR - orientation', orientation);
			const activeViewportID = viewportGridService.getActiveViewportId();
			const viewportInfo = cornerstoneViewportService.getViewportInfo(activeViewportID);
			const currentViewportData = viewportInfo.viewportData;
			const displaySetInstanceUID = currentViewportData.data.length
				? currentViewportData.data[0].displaySetInstanceUID
				: currentViewportData.data.displaySetInstanceUID;
			const displaySet = displaySetService.getDisplaySetByUID(displaySetInstanceUID);
			const dataSource = extensionManager.getActiveDataSource()[0];
			if (currentViewportData.viewportType === 'stack') {
				const viewportOptions = {
					viewportType: 'volume',
					orientation: orientation
				};
				const viewportData = await cornerstoneCacheService.createViewportData([displaySet], viewportOptions, dataSource);
				// console.log(viewportData);
				const publicViewportOptions: PublicViewportOptions = {
					id: orientation,
					viewportType: 'volume',
					toolGroupId: 'mpr',
					orientation: orientation
				};
				cornerstoneViewportService.setViewportData(
					activeViewportID,
					viewportData,
					publicViewportOptions,
					viewportInfo.displaySetOptions
				);
			} else {
				const viewportOptions = {
					viewportType: 'stack'
				};
				const viewportData = await cornerstoneCacheService.createViewportData([displaySet], viewportOptions, dataSource);
				// console.log(viewportData);
				const publicViewportOptions: PublicViewportOptions = {
					viewportType: 'stack',
					toolGroupId: 'default',
					initialImageOptions: {
						preset: 'middle'
					}
				};
				cornerstoneViewportService.setViewportData(
					activeViewportID,
					viewportData,
					publicViewportOptions,
					viewportInfo.displaySetOptions
				);
			}
		}
`

**Comment by ahlaughland** [comment]
> @ahlaughland I reallied that I am using this config to reduce memory sizing
> 
> ```
> useNorm16Texture: true,
> preferSizeOverAccuracy: true
> ```
> 
> Also found a config about rendering engine <img alt="image" width="992" src="https://private-user-images.githubusercontent.com/19906349/334820053-881d16fc-7534-446d-aab4-d015951735cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODE1MDMsIm5iZiI6MTcxNzA4MTIwMywicGF0aCI6Ii8xOTkwNjM0OS8zMzQ4MjAwNTMtODgxZDE2ZmMtNzUzNC00NDZkLWFhYjQtZDAxNTk1MTczNWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE1MDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjcyYmMxZTY5MmFjYTVkZDJlODk3ZWMzOWI4ZDU5Nzg2MmRkOTllODIyMDk4NzNiY2VhNjM3N2QyNmZjOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wjbAoFcFB1pk7xU5QNVLIyfJb9nyFheuye_99gZACZo">
> 
> If I config cornerstone like this, the issue is solved
> 
> ```
> cornerstone.setConfiguration({
> 	...cornerstone.getConfiguration(),
> 	rendering: {
> 		...cornerstone.getConfiguration().rendering,
> 		strictZSpacingForVolumeViewport: appConfig.strictZSpacingForVolumeViewport
> 	},
> 	enableCacheOptimization: false
> });
> ```

Thanks, I will research this `enableCacheOptimization` option.

**Comment by sedghi** [comment]
Can you check latest OHIF which has latest Cornerstone3D 2.0 additions?

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue.
