### ISSUE TITLE
failed to find studies on first run

### ISSUE THREAD

**Issue by vsaase** [OHIF/Viewers#417]
https://github.com/OHIF/Viewers/blob/7ff9a87b6e68f4fb8e9a527e292821c7ec9f966f/config/oidc-demo.json#L10

hi, i am very new to ohif.

on first running lesiontracker with a vanilla install OHIF.servers.getCurrentServer() seems to try to get the first server, but then fails to find studies because the first server does not have qidoRoot defined

changing the order of the servers in the config file makes it work

**Comment by dannyrb** [comment]
👋 Hi @vsaase, unfortunately we no longer have the bandwidth to address previous major versions. It may be worth trying out the latest version to see if it addresses your needs. Should you encounter issues, it will be easier for me to allocate time to support.
