### ISSUE TITLE
[Bug] Query parameters removed on page load

### ISSUE THREAD

**Issue by eriklofblad** [OHIF/Viewers#4176]
### Describe the Bug

When the OHIF Study List is loaded, all of the query params in the URL are removed. I've tried this in docker with ohif/app v3.5.0, v3.6.0, v3.7.0, v3.8.0 and v3.9.0-beta.21. With version 3.5.0 and 3.6.0 the query params are kept but in the other versions they are removed. This behavior is also seen on the current version of viewer.ohif.org.

### Steps to Reproduce

1. Go to: [https://viewer.ohif.org/?patientName=CTA&sortBy=studyDate&sortDirection=ascending](https://viewer.ohif.org/?patientName=CTA&sortBy=studyDate&sortDirection=ascending). The query parameters will be striped away and only [https://viewer.ohif.org/](https://viewer.ohif.org/) will be loaded.

### The current behavior

When trying to load https://viewer.ohif.org/?patientName=CTA&sortBy=studyDate&sortDirection=ascending the query params will be striped away and https://viewer.ohif.org/ will be loaded instead.

### The expected behavior

The query params should be kept on page load.

### OS

Windows 11, Android 14

### Node version

18.16.1

### Browser

Chrome 125.0.6422.77, Firefox 115.11.0esr, Chrome Android 125.0.6422.113

**Comment by eriklofblad** [comment]
Thank you @sedghi and @IbrahimCSAE for verifying and fixing this so quickly! It works like a charm now!

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
