### ISSUE TITLE
MPR timeline

### ISSUE THREAD

**Issue by CODEOrz** [OHIF/Viewers#418]
Hi, OHIF team.
Do you have a timeline (an estimated one is OK) for implementing MPR in The next version?

**Comment by dannyrb** [comment]
All programmer's hate estimates, but here are some very rough ballparks I can't even begin to guarantee:

- `React` branch becomes `master` and primary focus of support: Early to mid-May
- Refinement of Segmentation and MPR features: mid-May to late July

I'm hoping to clean up the issues and publish a more public roadmap after the `react` release.

**Comment by pieper** [comment]
As @swederik says, the timeline depends a lot on how many people contribute.  Community PRs welcome 😄

**Comment by swederik** [comment]
Here you go: https://github.com/OHIF/Viewers/pull/557

Visible on https://viewer.ohif.org
