### ISSUE TITLE
[Help - Bug] Setting up CORS correctly for viewing images from google storage 

### ISSUE THREAD

**Issue by highoncarbs** [OHIF/Viewers#4183]
### Describe the Bug

Setting up OHIF with CORS is quite a annoying issue. I would prefer the docs to be more in detail on how to tackle this.
So here;s my setup

1. I have this `/viewer/scan?id=<study_id>` , the study Id is used to call an API the returns a dicomjson with the urls as signed Google storage files.
2. When I try to open a study , I get this error 

`Access to XMLHttpRequest at 'https://storage.googleapis.com/64afbd53e081b578cba6fee4/663883b6ae9638024e4c468e/663883b6ae9638024e4c4693/allFiles/ead62bf9-7e1ae978-0c73aed5-a19f4848-8035ee86.dcm?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-ru9j2%40test-server-309204.iam.gserviceaccount.com%2F20240529%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240529T074956Z&X-Goog-Expires=518400&X-Goog-SignedHeaders=host&X-Goog-Signature=a078fea0fd0c1851a05af027effd16f7cc738531cd4a47afbc9355831cb33f125d1cad28cae7691d56a6d1c76eacceaadab3f4d47b61278ab96a0f30466d5b561d45cb79b0cc365785dc20f042de4c4fbc031e49c3dabc9e3f724bea659434c4b20290de254375e4766abbc0fb76993611da852eec1c939db3e9fb1de66f904ad3293892b41a8151c9328eff9e5c26aa8f955eedb569ec06268b32110c72955fd63a6b8dedd01752dad80a6198b9d05fbd34df1ee6bd4685f56a7c3944666eb99340062fefc2732e80dbea664a10061ce7576aa5bd5cf6ade27b4f8e78daa65d59fcf51025cbdb85d3379d77f456d515bbaed3f91078ac1530e33e7c727c67de' from origin 'https://ohifv3.svasthiya.in' has been blocked by CORS policy: Request header field accept is not allowed by Access-Control-Allow-Headers in preflight response.`

However, if I use the chrome extension - CORS Helper, I am able to view the images, which tells me that the GCP config is good. I just have to change the OHIF config.

**Will it be possible to provide the correct suggestion on how to navigate this.**

### Steps to Reproduce

Create a data source that calls a backend api that fetches a dicomjson with google storage url

### The current behavior

Images fail to load due to CORS issue

### The expected behavior

No CORS issue and images load

### OS

Windows 11

### Node version

20

### Browser

Latest Chrome and edge

**Comment by highoncarbs** [comment]
Even after using the chrome CORS extension, a few a failing to load

**Comment by sedghi** [comment]
You should set up your Google Healthcare server to allow your origin. See more details here:

https://docs.ohif.org/deployment/cors

**Comment by highoncarbs** [comment]
Hey @sedghi , I am not using google healthcare, it's just Google Storage S3 files. Do I need to setup the cors in OHIF for this? If yes, some guidance would be helpful

**Comment by highoncarbs** [comment]
@sedghi also the CORS config have been done correctly for Google Cloud Buckets, because the same urls are being fetched in OHIF v2, I guess I'm missing the areas where I'd have to update them in OHIF v3

**Comment by highoncarbs** [comment]
@sedghi I have tried everything - here's the GCP Cors 
![image](https://github.com/OHIF/Viewers/assets/6228854/cd25d4d6-7ac1-48ad-8154-512d2d0d598a)

Here's the webpack.pwa.js
![image](https://github.com/OHIF/Viewers/assets/6228854/ff4e366a-13ab-4d8c-bdd1-240c318ad374)

Here's my modified DicomJSONDataSource/index.js
![image](https://github.com/OHIF/Viewers/assets/6228854/cd4fff72-3a01-45eb-83b0-6a6398347cb7)

Been stuck on this for over a week.
