### ISSUE TITLE
Rectangle ROI Threshold tool in TMTV mode causes "Something Went Wrong" Error (3.9.0-beta.24) [Bug]

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#4187]
### Describe the Bug

Within TMTV mode when a user tries to create the "Rectangle ROI Threshold" to allow TMTV and SUV calculation a "Something Went Wrong" Error is popping up.

![image](https://github.com/OHIF/Viewers/assets/112980389/1db29602-28a3-46d6-a446-351f4b254496)
![image](https://github.com/OHIF/Viewers/assets/112980389/b0222ef8-f199-433b-aa6f-6c3d79a17289)

### Steps to Reproduce

1) Using OHIF viewer dev go to -  https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
2) Select the PET axial frame
3) Click "Add Segmentation"
4) Click the Rectangle ROI Threshold button

### The current behavior

When trying to create the Rectangle ROI Threshold to allow the user to create the TMTV stats and SUV Peak a "Something Went Wrong" Error is happening.

The following is displayed in the console

react-dom.production.min.js:188 TypeError: r.forEach is not a function
    at ToolboxUI.tsx:36:23
    at rl (react-dom.production.min.js:243:332)
    at Ic (react-dom.production.min.js:285:111)
    at react-dom.production.min.js:282:409
    at bc (react-dom.production.min.js:280:398)
    at lc (react-dom.production.min.js:272:439)
    at Ga (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273
ds @ react-dom.production.min.js:188
i.componentDidCatch.n.callback @ react-dom.production.min.js:189
Hi @ react-dom.production.min.js:156
Ml @ react-dom.production.min.js:260
Sl @ react-dom.production.min.js:259
yl @ react-dom.production.min.js:258
(anonymous) @ react-dom.production.min.js:282
bc @ react-dom.production.min.js:280
lc @ react-dom.production.min.js:272
Ga @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:266
Show 11 more frames
Show lessUnderstand this error
ErrorBoundary.tsx:78 Right Panel Error Boundary TypeError: r.forEach is not a function
    at ToolboxUI.tsx:36:23
    at rl (react-dom.production.min.js:243:332)
    at Ic (react-dom.production.min.js:285:111)
    at react-dom.production.min.js:282:409
    at bc (react-dom.production.min.js:280:398)
    at lc (react-dom.production.min.js:272:439)
    at Ga (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273 {componentStack: '\n    at yI (https://viewer-dev.ohif.org/app.bundle…f.org/app.bundle.4bd0ec2bf88352df9963.js:2:42632)'} Right Panel

### The expected behavior

Rectangle ROI Threshold should not cause an error and should instead allow the user to create an ROI

### OS

Windows 11

### Node version

OHIF dev Viewer version

### Browser

Version 125.0.6422.78 (Official Build) (64-bit)

**Comment by BrandonDatUHN** [comment]
So the error is no longer immediate but there is still a bug when trying to add the threshold rectangle ROI.
1)https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
2) Add segmentation
3) Click ROI threshold rectangle
4) Go to where you want to place the top slice
5) No square is drawn
Error in console RectangleROIStartEndThresholdTool.ts:279 Uncaught Error: Start slice does not match
    at re._computeProjectionPoints (RectangleROIStartEndThresholdTool.ts:279:13)
    at re.addNewAnnotation (RectangleROIStartEndThresholdTool.ts:190:10)
    at HTMLDivElement.T (mouseDownActivate.ts:32:35)
    at a (triggerEvent.ts:37:13)
    at mouseDownListener.ts:224:5
    at x (mouseDownListener.ts:414:3)
    at HTMLDocument.v (mouseDownListener.ts:246:7)

**Comment by sedghi** [comment]
This is fixed, if you upgrade cs3d version, we will push that

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
