### ISSUE TITLE
[Bug] For RTSTRUCT, unable to localize ROI from segmentation panel (v3.9.0-beta.29)

### ISSUE THREAD

**Issue by jenny-hm-lee** [OHIF/Viewers#4195]
### Describe the Bug

OHIF version: v3.9.0-beta.29
After loading an RTSTRUCT, unable to localized ROI on the viewport by clicking the ROI on the segmentation panel. 

### Steps to Reproduce

1. https://viewer-dev.ohif.org/
2. find a study with RTSTRUCT, and open basic mode
3. load a RTSTRUCT
4. on the segmentation panel, click an ROI.

### The current behavior

The current behaviour is for the viewport does not localize the ROI when clicking on the viewport.

### The expected behavior

Just like for a SEG or SR, the expected behaviour is for the viewport to localize the ROI when clicking on the viewport.

### OS

Windows 10

### Node version

v16.17.0

### Browser

Chrome Version 114.0.5735.110

**Comment by jenny-hm-lee** [comment]
@sedghi , this is the issue that jump from #4130 .

**Comment by jenny-hm-lee** [comment]
@sedghi , on v3.9.0-beta.33, loading RTSTRUCT has a new buggy behaviour.

1. open a study with RTSTRUCT
2. drag and drop an RTSTRUCT
3. click "Load" from top of the viewport


Actual result: "Something went wrong"
Expected result: able to load RTSTRUCT, and able to localize ROI from the segmentation panel.

**Comment by sedghi** [comment]
Yeah since we have moved to the new engine for rt we should rewrite the jump

**Comment by sedghi** [comment]
This is fixed i guess https://github.com/OHIF/Viewers/issues/4195#issuecomment-2150289183

**Comment by sedghi** [comment]
This is fixed

Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)
