### ISSUE TITLE
Post successful setup of ohif-orthanc in arm64 after selecting the study bad request is getting triggered I am sharing the curl with you  

### ISSUE THREAD

**Issue by Yashikajain2303** [OHIF/Viewers#4198]
### Describe the Bug

curl 'http://localhost:3000/dicom-web/studies/1.3.12.2.1107.5.8.3.788780.868487.80674849.2016032206524560/metadata' \
  -H 'sec-ch-ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"' \
  -H 'Accept: application/dicom+json, multipart/related; type=application/octet-stream; transfer-syntax=*; transfer-syntax=*' \
  -H 'Referer: http://localhost:3000/viewer?StudyInstanceUIDs=1.3.12.2.1107.5.8.3.788780.868487.80674849.2016032206524560' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua-platform: "Windows"'

### Steps to Reproduce

in arm64 setup, working fine on windows

### The current behavior

mentioned above

### The expected behavior

it should not get triggered

### OS

arm64

### Node version

16.20.2

### Browser

Brave and firefox

**Comment by Yashikajain2303** [comment]
Hi @sedghi, Were you able to reproduce the issue?

**Comment by sedghi** [comment]
What happened? can you update?

**Comment by Yashikajain2303** [comment]
I tried northanc docker to use new recipe based on nginx from one of your recent commit https://github.com/OHIF/Viewers/pull/4217, I was able to solve this problem.
