### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by rangata** [OHIF/Viewers#42]
Dear Friends,

I'm new in using this kind of systems.
I'm running Orthanc with plugins server on docker and clone Viewers.git repo. After run bin/orthancDICOMWeb.sh everythings works except when i open localhost:3000 there are no matches found every time. When I open Docker orhtanc sever via 8042 port and select the image I am able to open it with embedded  viewer. Could you please help me with setup on OS X 10.12 and Windows 10 as well.

Thank you very much!

**Comment by zhuhb1** [comment]
hi, rangata
i have got the same problem.
could you please tell me how you fix this?
any help will be greatly appreciated.
