### ISSUE TITLE
[Bug] cannot recover camera values after resizing (release v3.8 and master)

### ISSUE THREAD

**Issue by Joeycho** [OHIF/Viewers#4201]
### Describe the Bug

It happens to release and master (latest). 

https://github.com/OHIF/Viewers/assets/29337166/2b97ee60-9d56-4ca2-b02c-b55c78cb6398

### Steps to Reproduce

1. Open the browser as Developer mode to reduce viewport size less than the minimum (I tried with Chrome)
2. Open the images
3. Reduce the width extremely
4. Recover the width
5. Image won't be rendered 

### The current behavior

The image won't be rendered after viewport size is recovered.

The camera values are not recovered.

![Screenshot 2024-06-02 at 22 52 55](https://github.com/OHIF/Viewers/assets/29337166/0cc72a17-695b-45d1-b5b5-ad2abbc5280f)

### The expected behavior

Image should be visible if the viewport size is recovered. (v3.7 can be recovered, by zoom in again)

### OS

mac OS 14.4

### Node version

16.18

### Browser

Chrome  125.0.6422.113

**Comment by sedghi** [comment]
We should set a minimum width to like 5 % or something

**Comment by Joeycho** [comment]
Agree, or.. how about re-rendering?

**Comment by sedghi** [comment]
we can't re-render that small i guess
