### ISSUE TITLE
Example OHIF configuration for QIDO/binary dicom

### ISSUE THREAD

**Issue by wayfarer3130** [OHIF/Viewers#4204]
### What feature or change would you like to see made?

It would be very helpful to have an example OHIF configuration that uses QIDO to get the study/series/instance data and then uses binary retrieve for the remaining data.  This would support older PACS systems which don't support the newer standards.

### Why should we prioritize this feature?

This is a feature that some PACS users have no choice but to use since their PACS doesn't support the metadata call.  Enabling it would help them.

**Comment by sedghi** [comment]
You can use dicom json for this maybe, take a look here [https://docs.ohif.org/configuration/dataSources/introduction](https://docs.ohif.org/configuration/dataSources/introduction)
