### ISSUE TITLE
[Bug] async await.. SRs are not visible properly (I can create PR).

### ISSUE THREAD

**Issue by Joeycho** [OHIF/Viewers#4205]
### Describe the Bug

https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463

Click PT SR and then CT SR. It failed to visualize CT SR (the second one).

### Steps to Reproduce

1. Click PT SR
2. Click CT SR -> you will see no annotation there. Only image
3. click PT SR again
4. click CT SR again -> you will see annotation this time.

### The current behavior

https://github.com/OHIF/Viewers/blob/14221eb78ede2048392e352811a5f98a080c049f/extensions/cornerstone-dicom-sr/src/viewports/OHIFCornerstoneSRViewport.tsx#L266

https://github.com/OHIF/Viewers/blob/14221eb78ede2048392e352811a5f98a080c049f/extensions/cornerstone-dicom-sr/src/viewports/OHIFCornerstoneSRViewport.tsx#L280

While waiting load() (L266), the next useEffect() (L280).. can run. 

### The expected behavior

L266 should be finished before L280 code blocks. Therefore, srDisplaySet.isLoaded should be true.

### OS

mac OS 14.4

### Node version

16.18

### Browser

Chrome  125.0.6422.113

**Comment by Joeycho** [comment]
https://github.com/OHIF/Viewers/pull/4226 @sedghi

**Comment by sedghi** [comment]
I merged your PR, does it solve your issue?

**Comment by Joeycho** [comment]
Yes it is :)
