### ISSUE TITLE
[Bug] no longer works on WebGL-only browsers, WebGL2 for configuration only

### ISSUE THREAD

**Issue by edotassi** [OHIF/Viewers#4212]
In the latest version these lines have been introduced:

[https://github.com/OHIF/Viewers/pull/4052/files#diff-d84d3e071e77a96cd602c4c9fc02fb1dca91dc931167b87c5ef30eb3a4e87f36](url)
```
// get the maximum 3D texture size
const canvas = document.createElement('canvas');
const gl = canvas.getContext('webgl2');

const max3DTextureSize = gl.getParameter(gl.MAX_3D_TEXTURE_SIZE);
appConfigState.max3DTextureSize = max3DTextureSize;
```

doing so creates a direct dependency with WebGL2 making it a minimum requirement.
however Cornerstone3d also works in browsers that only support WebGL.

I applied this temporary patch and it started working again on our customer's browser:
```
const max3DTextureSize = gl ? gl.getParameter(gl.MAX_3D_TEXTURE_SIZE) : 2048;
```

Does it make sense as a solution?
Is it possible to do better?

Thank you

### Steps to Reproduce

1. open the viewer in a WebGL only browser

### The current behavior

the viewer does not load due to a js error:

```
const canvas = document.createElement('canvas');
const gl = canvas.getContext('webgl2');

const max3DTextureSize = gl.getParameter(gl.MAX_3D_TEXTURE_SIZE);
```

`gl` is `undefined`

### The expected behavior

the viewer works

### OS

Windows

### Node version

20

### Browser

Chrome

**Comment by sedghi** [comment]
Yeah, I don't think we have a plan to address this, and our focus will shift to WebGPU and its future rather than looking backward.
