### ISSUE TITLE
[Bug] 3D hanging protocol picks wrong series to render

### ISSUE THREAD

**Issue by haldawe2** [OHIF/Viewers#4213]
### Describe the Bug

3D, and sometimes MPR as well, picks the first available series that fits the HP criteria instead of the one currently active. Happens more often if there is a HP active before

### Steps to Reproduce

1. Go to https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5
2. Show in viewport 4th series (Body 4.0 CE) and choose 3D main
3. Check that it actually shows Body 3.0 CE series

Also:

1. Repeat steps 1 and 2, but do MPR instead, will work fine
2. Change to 1x1 layout and choose Body 4.0 CE series
3. Do MPR again, will show Body 3.0 CE series

### The current behavior

MPR and 3D HP sometimes do not pick the choosen viewport to render

### The expected behavior

MPR and 3D HP should render the active viewport to render always

### OS

Windows 10

### Node version

20.11.1

### Browser

Chrome 125.0.6422.77

**Comment by sedghi** [comment]
I apologize, but I am unable to reproduce the steps you provided. Could you please record a video demonstrating the issue? This would help me better understand and assist you.

**Comment by haldawe2** [comment]
[OHIF Viewer - Google Chrome 2024-06-21 10-24-22.zip](https://github.com/user-attachments/files/15924915/OHIF.Viewer.-.Google.Chrome.2024-06-21.10-24-22.zip)

Made the video showing the issue, had to compress it to be able to upload it.

Thank you for your time,

**Comment by sedghi** [comment]
Hmmm werid, thanks for the video

**Comment by sedghi** [comment]
This seems to be fixed 

Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?
Here are the migration guides:
Try OHIF locally: https://viewer-dev.ohif.org/localbasic Try Cornerstone3D 2.0 locally: https://www.cornerstonejs.org/live-examples/local.html
https://docs.ohif.org/migration-guide/3p8-to-3p9/
