### ISSUE TITLE
[Bug] US - Blank Images and throws 'Error: The image does not have a complete color palette. R, G, and B palette data are required.'

### ISSUE THREAD

**Issue by tirta-ir** [OHIF/Viewers#4218]
### Describe the Bug

Hi, I am still encountering the same error as in my previous issue #4075. My US (multi-frame) DICOM images with PALETTE COLOR photometric interpretation still cannot be viewed, even though I am using the latest master branch version (3.9.38) as you said it was fixed in dev.

### Steps to Reproduce

1. Download the exported Ultrasound (US) DICOM images from this link (https://drive.google.com/file/d/17xuICqMgf5v4cosGWRuNlt7R9n4Kq8aS/view?usp=sharing).
2. Upload the DICOM images to OHIF using the latest master branch version (3.9.38).
3. View the DICOM images using the basic viewer.

### The current behavior

The cornerstone in the basic viewer still returns a blank screen. For example, when using the version 3.9.38, it throws this error.

![image](https://github.com/OHIF/Viewers/assets/70493416/63b2fbb5-50fe-45da-95c0-e23442799490)

```
fetchPaletteColorLookupTableData.js:70 
 No data found for [object ArrayBuffer] palette
convertPALETTECOLOR.ts:59 
 Uncaught (in promise) 

Error: The image does not have a complete color palette. R, G, and B palette data are required.
    at convertPALETTECOLOR.ts:59:13
DataArray.js:518 
 Uncaught (in promise) 

RangeError: model.size is not a multiple of model.numberOfComponents
    at p (DataArray.js:518:11)
    at Object.n [as newInstance] (macros2.js:917:5)
    at ue.createVTKImageData (StackViewport.ts:1659:25)
    at ue._createVTKImageData (StackViewport.ts:1690:28)
    at ue._updateActorToDisplayImageId (StackViewport.ts:2352:10)
    at ue.renderImageObject (StackViewport.ts:2171:14)
    at renderToCanvasGPU.ts:178:36
    at new Promise (<anonymous>)
    at oe (renderToCanvasGPU.ts:101:10)
    at u (loadImageToCanvas.ts:146:7)
```

### The expected behavior

The DICOM should be displayed like this (OHIFv2 or other DICOM viewers like the MedDream demo).

**OHIFv2 Viewer**
![image](https://github.com/OHIF/Viewers/assets/70493416/1dfec2e8-9b18-4f0b-9725-528d06d92521)

**MedDream Viewer**
![image](https://github.com/OHIF/Viewers/assets/70493416/cf975730-c6a8-4717-9079-495c4a1dd7f3)

### OS

Ubuntu 22.04.3 LTS

### Node version

20.12.2

### Browser

Chrome 123.0.6312.122 (Official Build) (64-bit)

**Comment by sedghi** [comment]
So i will close the other issue since you opened a new one

**Comment by tirta-ir** [comment]
I got additional information for this issue. It might be that the issue is related to how OHIF or Cornerstone interprets the Palette Color metadata. The LUT handling isn't correctly implemented, resulting in a blank screen. 

I attempted to reproduce the issue using another ultrasound image from [[these sample]](https://www.aliza-dicom-viewer.com/download/datasets), which also uses palette color interpretation for US images, and encountered the same blank screen.

However, when I converted the DICOM file using my Python script to YBR then opened it on OHIF, it displayed correctly.

**Comment by sedghi** [comment]
Hey, which samples from this link https://www.aliza-dicom-viewer.com/download/datasets are you using to display? There are many available.

**Comment by tirta-ir** [comment]
I used multi-frame ultrasound image that appeared affected, so you can choose one of them from the datasets

**Comment by sedghi** [comment]
So this works fine in latest, i guess we can close this issue?

![CleanShot 2024-11-06 at 23 22 37@2x](https://github.com/user-attachments/assets/c0838417-0d20-44f4-9e84-eb649d81772b)

Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?
Here are the migration guides:
Try OHIF locally: https://viewer-dev.ohif.org/localbasic Try Cornerstone3D 2.0 locally: https://www.cornerstonejs.org/live-examples/local.html
https://docs.ohif.org/migration-guide/3p8-to-3p9/

**Comment by tirta-ir** [comment]
Wow, I tried it using the viewer-dev with the same DICOM from the datasets, and it worked just fine. Thanks a lot for this! We'll look into it further, but for now, we can close this issue. Thanks again.
