### ISSUE TITLE
Study List - Sorting & Date Search

### ISSUE THREAD

**Issue by davidi1** [OHIF/Viewers#422]
Hello, I noticed a couple of issues related to the Study Date field with the newest Docker version of OHIF Viewer (tag:travis-824). I am using the docker version of Orthanc as the backend. These issues seem related so I am putting them together. I hope that is OK, if not, let me know and I will open a new ticket for the second one.

1. If I click on the arrow next to Study Date to sort the list by Date, it will not display any studies that were done today. For example, I have a study that was done today and if I click that arrow, it will sort and display all of the other studies except for today's. I hope that makes sense.

2. If I click in the Study Date field and select any of those options from the drop down, it will not show any studies that were done on today's date either.

In order to see any study that was done today, I have to manually search for the patient. If I do that, the study will show. Any help would be appreciated.

**Comment by dannyrb** [comment]
Scoped and added to backlog: https://github.com/OHIF/Viewers/issues/830
