### ISSUE TITLE
[Feature Request] toolbar custom mip

### ISSUE THREAD

**Issue by tungvip2143** [OHIF/Viewers#4220]
### What feature or change would you like to see made?

I could not able to see “MIP modes” and “Slab thickness” in version 3 same as version 2.
![9dee2f77a77cb2ba4ad87dfde19e7be336894025_2_690x117](https://github.com/OHIF/Viewers/assets/83186487/99481387-b87b-4081-bebd-f98731ad9c4b)

### Why should we prioritize this feature?

If it were added, there would be more options available for use.

**Comment by sedghi** [comment]
You can use the crosshairs tool to increase slab thickness. However, the new toolbar service is flexible and powerful enough for you to add your custom React component that edits the slab thickness on the active viewport. But this feature is not planned for the near future.

https://docs.ohif.org/platform/extensions/modules/toolbar

**Comment by tungvip2143** [comment]
If I want to customize and add to my personal project, is there any way to leverage your system?
