### ISSUE TITLE
[Bug] Some DICOM files cannot be read.

### ISSUE THREAD

**Issue by a1120235890** [OHIF/Viewers#4222]
### Describe the Bug

I used Orthanc as the server and deployed OHIF with YARN. However, after uploading a series of CT DICOM files, I encountered an error when trying to view them, whereas OHIF on Orthanc can read these DICOM files without any issues.Then I discovered that the URLs for retrieving DICOM files are different: one uses "File" and the other uses "Series". How can I make OHIF differentiate between using "File" or "Series" to request Orthanc?
![42f9ea8a0db287d6206f40d6f8755d3](https://github.com/OHIF/Viewers/assets/57754489/14f89bab-05d1-48ea-a740-cfac56e8fbc6)
![e7ee192f9e4501cdcaa09d9e8caf293](https://github.com/OHIF/Viewers/assets/57754489/3dfa21e7-d5a7-41bd-b584-6af10e320dea)

### Steps to Reproduce

1

### The current behavior

1

### The expected behavior

1

### OS

windows 11

### Node version

v16.18.0

### Browser

Chrome 125.0.6422.142

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by a1120235890** [comment]
use 3.7.0 version can resolve this

**Comment by sedghi** [comment]
alright
