### ISSUE TITLE
[Feature Request] rectangle annotation sync in mpr

### ISSUE THREAD

**Issue by IT-Highmore** [OHIF/Viewers#4227]
### What feature or change would you like to see made?

  Hello everyone, rather than a new feature request, it is more like asking for your ideas or methods of implementation. 
For example, In MPR mode, use a rectangle tool to  draw a roi, and a rectangular roi will appear synchronously in the other two viewports. Similar to the three faces of a cuboid in three viewports.The length of the missing edges uses a fixed value or a maximum value. We can dynamically adjust the area of ​​the first rectangle, and the other two generated rectangles also change synchronously
    I don't know if I have described it clearly. Is there any possibility or idea to implement it in V3? 
    
![image](https://github.com/OHIF/Viewers/assets/48371393/bf5f8e6d-cb07-4906-a1f4-739094e9c807)

### Why should we prioritize this feature?

Looking forward to your reply, thank you very much.

**Comment by sedghi** [comment]
So it seems you are looking for a 3D rectangle, which can be quite challenging as you need to control three different values. However, creating a cuboid (3D square) is relatively straightforward. You could look at how we implement the sphere tool and adapt that approach. Though we can't prioritize this right now

https://github.com/cornerstonejs/cornerstone3D/blob/db03776bbec0e42811340a933744aea4261b5d18/packages/tools/src/tools/segmentation/SphereScissorsTool.ts#L44

**Comment by IT-Highmore** [comment]
> So it seems you are looking for a 3D rectangle, which can be quite challenging as you need to control three different values. However, creating a cuboid (3D square) is relatively straightforward. You could look at how we implement the sphere tool and adapt that approach. Though we can't prioritize this right now
> 
> https://github.com/cornerstonejs/cornerstone3D/blob/db03776bbec0e42811340a933744aea4261b5d18/packages/tools/src/tools/segmentation/SphereScissorsTool.ts#L44

Thank you very much for your reply, it means a lot to me.
