### ISSUE TITLE
[Bug] Double click on existing annotation looses text

### ISSUE THREAD

**Issue by tzuccher** [OHIF/Viewers#4229]
### Describe the Bug

When creating an annotation you are forced to add text on the annotation - the save button on the annotation window is not enabled until you add text.

When you double-click on the annotation on the image, the annotation window displays but the text field is blank. The existing text is gone. You only have a save (disabled until you add new text) and an x in the upper right corner to close the window. Neither option restores the lost text.

Currently on version:
![image](https://github.com/OHIF/Viewers/assets/143200290/07f5c880-3121-437a-9946-d3b5798726ce)

### Steps to Reproduce

1. Select a study and go to the viewer screen
2. Select the Annotation tool
3. Click on the image to create the arrow line with  an annotation
4. In the annotation window, enter text and click on the save button = the text appears next to the arrow on the image
5. Double click on the annotation line or text = annotation window displays with a blank field
![image](https://github.com/OHIF/Viewers/assets/143200290/1ff461bf-2b3e-4d42-a7cb-5c61d70c9975)

### The current behavior

When you double-click on an existing annotation the window appears with the text field blank (enter label) but the original text is not there. Options are the x in the top right-hand corner or type in text and click on the then-enabled save button.

If you choose either of these options (right click context menu & add label or pencil edit from measurements panel),  the correct behaviour is there: the window opens with the existing text in the field allowing you to keep and edit or add on to and save. Or, select the x in the top right-hand corner not to make any changes to the existing annotation text

### The expected behavior

When you double-click on the annotation, the annotation window should appear with the existing annotation text in the field, allowing you to add onto, edit or remove the current text info. Or, select x from the top corner to keep text as is and exit out of the window.

### OS

MacBook Pro - Sonoma 14.5

### Node version

unknown

### Browser

Chrome v125

**Comment by 03shek** [comment]
Keyboard Esc from the empty-text label popup does keep text as it was

**Comment by sedghi** [comment]
I can't reproduce this anymore
