### ISSUE TITLE
[Bug] Fail to display correctly 3D series

### ISSUE THREAD

**Issue by arturojain** [OHIF/Viewers#4231]
### Describe the Bug

The image fails to load correctly using DICOMJSON or drag and drop on both https://viewer.ohif.org or https://viewer-dev.ohif.org

### Steps to Reproduce

Load DICOM file on OHIF

### The current behavior

The image is shown as several low res miniates
![image](https://github.com/OHIF/Viewers/assets/5528886/c7aba498-8d55-44cf-a61a-2ff556d69361)

### The expected behavior

The image should display correctly
![rawgit_com_cornerstonejs_cornerstoneWADOImageLoader_master_examples_dicomfile_in](https://github.com/OHIF/Viewers/assets/5528886/b1dad9dd-9fd2-4671-aa79-b488238df871)

### OS

macOS 14.5

### Node version

20

### Browser

Chrome

**Comment by sedghi** [comment]
Hmmm, this is not about 3D, it is about color, i will look

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by arturojain** [comment]
Sorry for the delay, I'm sending the examples without PHI: [Anonymized - 08.zip](https://github.com/user-attachments/files/16897057/Anonymized.-.08.zip)

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
