### ISSUE TITLE
[Bug] Some series in MG or DX are not being displayed as series when using DICOMJSON

### ISSUE THREAD

**Issue by arturojain** [OHIF/Viewers#4239]
### Describe the Bug

When using DX or MG modalities and having series. The series are displayed as individual instances instead of series. This didn't happen previously in OHIF v2. 

### Steps to Reproduce

1. Download the [ZIP file](https://app.nubix.cloud/api/v1/organization/study/383131/files/zip?organization=auth0|5eb494581cc1ac0c14918bfe&access_code=xjOCrofs2jE4CUXk9GJnnrliM-OnUlSP_8m33IVOCC&pin=null&includeHtml=false) or [JSON](https://app.nubix.cloud/api/v1/organization/study/383131/files/ohif?organization=auth0%7C5eb494581cc1ac0c14918bfe&access_code=xjOCrofs2jE4CUXk9GJnnrliM-OnUlSP_8m33IVOCC).
2. View it using DICOMJSON on OHIF v3.

### The current behavior

The series are dispalyed as separate images.

### The expected behavior

The series should be displayed as a series.

### OS

macOS 14.5

### Node version

20

### Browser

Arc 1.47.1 (50893)

**Comment by fightroad** [comment]
the same  issue

**Comment by sedghi** [comment]
When using DICOM JSON, you are responsible for splitting the data. Since you are providing the JSON file statically, you can edit the JSON as needed, and it will work.
