### ISSUE TITLE
[Bug] Viewers 2-legacy version CT image window loading error, image blur.

### ISSUE THREAD

**Issue by liujun1998-liu** [OHIF/Viewers#4240]
### Describe the Bug

Normal loading:
![1718731154156](https://github.com/OHIF/Viewers/assets/56507144/e0377872-5639-46cd-8cde-57dd98d6c4b3)

---------------------------------------------------------
Viewers 2-legacy error loading:The image is blurry
![1718731210716](https://github.com/OHIF/Viewers/assets/56507144/0f5b4f51-16ca-4c80-b877-2747aac48ff8)

### Steps to Reproduce

1. Run the Viewers 2-legacy project
2. Load CT images

### The current behavior

Hopefully this will be fixed in Viewers 2-legacy, thanks.

### The expected behavior

Hopefully this will be fixed in Viewers 2-legacy, thanks.

### OS

Windows11

### Node version

v16.2.0

### Browser

 Chrome125.0.6422.142

**Comment by liujun1998-liu** [comment]
Is anybody there?

**Comment by sedghi** [comment]
> Is anybody there?
I mean you just posted 3 days ago ...

To address your question, we currently do not support Viewer 2 legacy, so the chances of prioritizing this task are minimal given our ongoing commitments.

Allow me to rephrase and inquire about your reasons for sticking with Viewer 2. Viewer 3 is superior in every aspect, so perhaps we could explore ways to facilitate your migration and bridge the gap.

**Comment by liujun1998-liu** [comment]
> > Is anybody there?
> 
> I mean you just posted 3 days ago ...
> 
> To address your question, we currently do not support Viewer 2 legacy, so the chances of prioritizing this task are minimal given our ongoing commitments.
> 
> Allow me to rephrase and inquire about your reasons for sticking with Viewer 2. Viewer 3 is superior in every aspect, so perhaps we could explore ways to facilitate your migration and bridge the gap.

The Viewer 2 legacy is currently in production.
Is there a solution to this problem?
