### ISSUE TITLE
[Bug] Can't set the ohif viewer to get whole images using retrieveurl

### ISSUE THREAD

**Issue by sylvainb31** [OHIF/Viewers#4247]
### Describe the Bug

I have tried different configurations in the app-config.js to get the ohif viewer to get the images using the retrieve url at study level by adding the following :
```
cornerstoneExtensionConfig: {
    retrieve: {
      enabled: true,
      urlTemplate: "{wadoRoot}/studies/{studyInstanceUid}",
    },
    prefetch: {
      enabled: false,
    },
  }
```
Is there a way to configure the viewer so that it can get whole study or serie with one query ? Instead of getting the images with one request for each image.
Thanks a lot !

### Steps to Reproduce

Using the documentation, I built the last version of the ohif viewer from this : https://github.com/OHIF/Viewers/archive/master.zip
I can't find any documentation to change the way the images are retrieved.

### The current behavior

Images are retrieved one by one, with wadors or wadouri urls.

### The expected behavior

I would like to get all images at once either at study or serie level.

### OS

Windows 10

### Node version

22.2.0

### Browser

Version 125.0.6422.176 (Build officiel) (64 bits)

**Comment by sedghi** [comment]
is it possible you are using old version of ohif , there is no mention of urlTemplate in our codebase
