### ISSUE TITLE
[Bug] In MPR mode, SR localization jumps to wrong instances sometimes

### ISSUE THREAD

**Issue by 03shek** [OHIF/Viewers#4250]
### Describe the Bug

In MPR mode, SR localization jumps to wrong instances (since it can become an inverted image stack) sometimes. Eg., default 1x1 viewport instance 1 is legs. Once in MPR mode, instance 1 is head in WB CT.

Phantom study that exhibits the bug without anatomy (pwd: "secrecy"):
https://fileshare.uhn.ca/download/39c5d602-6f95-4882-8cff-e3c2fe7e38bf 

### Steps to Reproduce

1. CT with default 1x1 viewport instance 1 is legs. Once in MPR mode, instance 1 is head in WB CT.
2. Default viewport see legs on i=1.
3. Make 2 measurements corresponding to i=1 (legs) and i=end (head).
![beginning](https://github.com/OHIF/Viewers/assets/115667958/47256d99-c607-4383-aaa9-be45074b3b59)

4. Load MPR mode.
5. Axial MPR mode i=1 shows head.
6. SR localization becomes inverted/wrong

### The current behavior

6. Localize to measurement for legs, but viewport jumps to head. Measurement at this location stays yellow (ie, not current).
7. Localize to measurement for head, but viewport jumps to legs. Measurement at this location stays yellow (ie, not current).
![mpr_localized](https://github.com/OHIF/Viewers/assets/115667958/98175b12-9498-44e7-9427-9c48fbfc6200)

8. Exiting MPR mode to Common Hanging protocol 1x1 does not fix this, only dragging series into 1x1 viewport does.
![triedtorestore](https://github.com/OHIF/Viewers/assets/115667958/df582a46-cca9-424d-a981-ed477d8540e0)

### The expected behavior

6. Localize to measurement for legs, and viewport jumps to legs. Measurement at this location is green (ie, current).
7. Localize to measurement for head, and viewport jumps to head. Measurement at this location is green (ie, current).

### OS

Windows 10

### Node version

000000

### Browser

Chrome 126.0.0

**Comment by sedghi** [comment]
I think i know what is happening

**Comment by sedghi** [comment]
I think this is fixed now, check latest

Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)
