### ISSUE TITLE
[Bug] OHIF does not use /rendered enpoint for video in an Orthanc Dicom Server

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#4257]
### Describe the Bug

Video reading in OHIF doesn't work if stored in an Orthanc server,

There is a difference in the /metadata API of OHIF dicom server and Orthanc

OHIF server answer is : 
`        
"7FE00010": {
            "vr": "OB",
            "BulkDataURI": "series/2.25.15054212212536476297201250326674987992/instances/2.25.179478223177027022014772769075050874231/pixeldata.mp4?length=47363258&offset=0"
        },`

while orthanc is : 
`  	"7FE00010" : 
	{
		"BulkDataURI" : "https://v2-test.gaelo.fr/dicom-web/studies/1.2.276.0.7230010.3.1.2.1667589682.1.1719172138.291254/series/1.2.276.0.7230010.3.1.3.1667589682.1.1719172138.291255/instances/1.2.276.0.7230010.3.1.4.1667589682.1.1719172138.291256/bulk/7fe00010",
		"vr" : "OB"
	}`

OHIF seems to not detect that the content is a video and continue to call /frame/{number} API which are obviously failing, while it should call the rendered api

I don't know if this problem is related to Orthanc which might no follow a standard or if OHIF should have more flexibility ?

### Steps to Reproduce

1. Try to open a video dicom stored in Orthanc

### The current behavior

Black viewport

### The expected behavior

Video shall be opened in a video reader

### OS

Linux

### Node version

20

### Browser

Chrome latest

**Comment by salimkanoun** [comment]
nevermind problem seems related to my dicom

**Comment by LucasCis92** [comment]
Hi, I have the same issue when trying to reproduce a video in OHIF with Orthanc, instead of callind /rendered it calls frames. May you share with me how did you solve this?

**Comment by salimkanoun** [comment]
humm it's not clear to me which is the decision rule to use each endpoint, if you have a reproducible scenario with a source dicom please post a new issue so we can try and see what's happening
