### ISSUE TITLE
[Bug] useBulkDataURI disapeared ?

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#4258]
### Describe the Bug

useBulkDataURI config param appear only in local_orthanc.js and configurationFiles.md
It doesn't seems to be used elsewhere in the code, it is a legacy parameter to be removed?

### Steps to Reproduce

none

### The current behavior

none

### The expected behavior

none

### OS

none

### Node version

none

### Browser

none

**Comment by sedghi** [comment]
I think you need to do this now?

bulkDataURI: {
          enabled: true,

@way

**Comment by wayfarer3130** [comment]
Yes, the useBulkDataURI has disappeared in favour of more complete configuration control to deal with various situations where the bulkdata uri is non-standard.  Please use the bulkDataURI: { enabled: true, ... }

**Comment by salimkanoun** [comment]
Ok i made a PR https://github.com/OHIF/Viewers/pull/4272 to remove this unused variable
