### ISSUE TITLE
[Bug] Tools disabled with different layout

### ISSUE THREAD

**Issue by KatkaG** [OHIF/Viewers#4260]
### Describe the Bug

Hello, some tools are disabled when I change the layout, even if I have selected the same view as before.

These are screenshots from Basic Viewer version 3.8.1. [link here](https://viewer.ohif.org/viewer?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2). In the first screenshot, there is only one view, and Freehand ROI, Splinewire ROI, and Calibration are available. When I press the layout button, select the 3D primary layout, and select the same view, these tools are not available (second screenshot).

![Screenshot 2024-06-25 at 08 59 05](https://github.com/OHIF/Viewers/assets/29623899/0a86f569-0edb-4644-891e-069c02f73260)

![Screenshot 2024-06-25 at 09 00 15](https://github.com/OHIF/Viewers/assets/29623899/ce44a6bc-f0b7-4d22-863a-be512125eb1f)

### Steps to Reproduce

1. Open basic viewer
2. Check if Splinewire ROI and Livewire ROI tools are available
3. Change layout (any from advanced presets) 
4. Select same view 
5. Check the tools again

### The current behavior

Freehand ROI, Splinewire ROI and Calibration tools are not available, when advanced layout is used.

### The expected behavior

Tools should be available when I am working with same view, it should not be dependant on layout

### OS

OS X 10.15.7

### Node version

20.6.1

### Browser

Safari 17.2.1, Chrome 126.0.0

**Comment by sedghi** [comment]
seems like a bug

**Comment by IbrahimCSAE** [comment]
no bug here, the reason the tools are disabled in the advanced layout is because it's no longer a stack viewport but a volume viewport. Spline, livewire and calibration tools are disabled for Volume Viewports.

**Comment by sedghi** [comment]
we should add them to volume viewports since they all works in cornerstone both on stack and volume
