### ISSUE TITLE
[Bug]  MPR Mode, mpr-coronal data error

### ISSUE THREAD

**Issue by IT-Highmore** [OHIF/Viewers#4261]
### Describe the Bug

 `cornerstoneViewportService.getRenderingEngine().getViewport('mpr-coronal').getCurrentImageIdIndex()` data incorrect which causes other data to be incorrect such as camera focalPoint data

### Steps to Reproduce

1. open link [https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463](url)
2. select mpr mode
3. `window.services.cornerstoneViewportService.getRenderingEngine().getViewport('mpr-coronal').getCurrentImageIdIndex()`  in console

### The current behavior

![image](https://github.com/OHIF/Viewers/assets/48371393/ecc25f5c-7c7d-45cf-bdd9-62b4c617b8ed)
current result is 63 incorrect

### The expected behavior

It should be 64

### OS

Windows 10

### Node version

18.17.0

### Browser

Chrome 126.0.6478.63

**Comment by sedghi** [comment]
use getSliceIndex or getViewReference

**Comment by IT-Highmore** [comment]
> use getSliceIndex or getViewReference

I don't want to take this index，What I want to say is that  mpr-coronal deault image index does not match the  focalPoint
