### ISSUE TITLE
[Bug] Error: EISDIR: illegal operation on a directory, symlink

### ISSUE THREAD

**Issue by RR2pao** [OHIF/Viewers#4264]
### Describe the Bug

Hello OHIF Team!
I was following the installation steps (https://docs.ohif.org/development/getting-started/), when I got this error at "yarn install":

`error Error: EISDIR: illegal operation on a directory, symlink 'A:\temp\Viewers-master\addOns\externals\dicom-microscopy-viewer' -> 'A:\temp\Viewers-master\node_modules\@externals\dicom-microscopy-viewer'`

![image](https://github.com/OHIF/Viewers/assets/67505133/c3085ff8-2c90-42e1-8615-1b7f38b3d2a2)

What I already tried:
- run terminal as administrator
- delete node modules folder, delete yarn cache
- installation with earlier yarn version

Details of my setup:
OS: Windows 11
user: admin

node --version
v20.14.0
npm --version
10.7.0
yarn --version
1.22.22

I was cloning the current master branch of OHIF viewer.

### Steps to Reproduce

0. clone master branch
1. yarn install

### The current behavior

`yarn install` throws the following error: 
`error Error: EISDIR: illegal operation on a directory, symlink 'A:\temp\Viewers-master\addOns\externals\dicom-microscopy-viewer' -> 'A:\temp\Viewers-master\node_modules\@externals\dicom-microscopy-viewer'`

### The expected behavior

`yarn install` should install dependencies.

### OS

Windows 11

### Node version

v20.14.0

### Browser

Chrome 126.0.6478.126

**Comment by sedghi** [comment]
This is strange. Can you clone the repository in a new location and check if the issue persists with a fresh clone?
