### ISSUE TITLE
[Bug] Unable to load SEG modality in 3.9.0-beta.16, works on 3.8.3

### ISSUE THREAD

**Issue by prerakmody** [OHIF/Viewers#4271]
### Describe the Bug

The images below explain the bug.
In `3.9.0-beta.16`, I get an error - `The selected display sets could not be added to the viewport due to a mismatch in the Hanging Protocol rules.`

# v3.8.3
 - .dcms were manually uploaded to [viewer.ohif.org/local](https://viewer.ohif.org/local)
<img width="1512" alt="image" src="https://github.com/OHIF/Viewers/assets/2803936/b41faa8c-6ee2-406d-a40a-24307cc917c7">

# v3.9.0-beta.16
 - .dcms were present within an Orthanc server ([jodogne/orthanc-plugins/1.12.3](https://hub.docker.com/layers/jodogne/orthanc-plugins/1.12.3/images/sha256-541a7fcb3ac67ffe323f023700420999b62da0ad972cd0d4390d58c94033208b?context=explore))
<img width="1476" alt="image" src="https://github.com/OHIF/Viewers/assets/2803936/b0f3692a-17a9-463f-9cd5-ba6135071285">

 - After checking the console, I see an error: `ReferencedSeriesSequence is missing for the SEG`.
   - I checked the .dcm file and it has this tag. 
   - I found this error in the OHIF code [here](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone-dicom-seg/src/getSopClassHandlerModule.ts#L65)
   - I do not see this error in the console of [viewer.ohif.org/local](https://viewer.ohif.org/local)

### Steps to Reproduce

1. Download [data](https://file.io/gFgWE0LCxapf)
   - The data consists of 3 x CT and 1 x SEG .dcms
   - If the download link expires, you can also download `Subject ID = HCC_004` from [TCIA](https://nbia.cancerimagingarchive.net/nbia-search/?MinNumberOfStudiesCriteria=1&CollectionCriteria=HCC-TACE-Seg). Go to `Search Results` tab.
3. Upload to [viewer.ohif.org/local](https://viewer.ohif.org/local) (currently v3.8.3) to check data sanity
    - view the segmentation.
4. Check in local OHIF (version `3.9.0-beta.16`)

### The current behavior

The segmentation does not show up in OHIF `3.9.0-beta.16`

### The expected behavior

The segmentation should show up

### OS

MacOS v14.2 (Sonoma)

### Node version

20.8.0

### Browser

Brave (Version 1.66.118)

**Comment by sedghi** [comment]
I know the `ReferencedSeriesSequence is missing for the SEG` issue. Technically this is required in the dicom standard and Orthanc is not following the standard

https://dicom.innolitics.com/ciods/rt-structure-set/common-instance-reference/00081115

You can bring it up in the orthanc discord

**Comment by prerakmody** [comment]
Posted on Orthanc discourse: https://discourse.orthanc-server.org/t/ohif-plugin-referencedseriessequence-is-missing-for-the-seg/4874

**Comment by amazy** [comment]
Hi @prerakmody,

We have just released the orthanc-OHIF plugin 1.3 that includes v3.8.3 of OHIF.
With [this setup](https://github.com/orthanc-server/orthanc-setup-samples/tree/master/docker/ohif), I do not see any errors in the console and it seems I can display the seg both with the plugin version and with the 'container' version that includes v3.9.0-beta.56.
- http://localhost/ohif/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1706.8374.643249677828306008300337414785
- http://localhost/orthanc-plugin/ohif/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1706.8374.643249677828306008300337414785

![image](https://github.com/user-attachments/assets/b17bc936-a6de-4314-a341-e759ff6498db)

Does it mean that your issue is somehow solved ?  If not, can you clarify what we need to do from the Orthanc side ?

**Comment by prerakmody** [comment]
Thanks for looking into this!
I will update my Orthanc and get back to you.

**Comment by prerakmody** [comment]
@amazy 
To get access to your latest changes to Orthanc:
  -  I used the [orthancteam/orthanc:24.7.3-full docker image](https://hub.docker.com/layers/orthancteam/orthanc/24.7.3-full/images/sha256-da4d95a58d0a55d3f2f96139c5bd4014b96198b6f160e24308feecf8486fabc2?context=explore). 
  - I then ran `docker run -e OHIF_PLUGIN_ENABLED=true -p 8042:8042 -v orthanc-db:/var/lib/orthanc/db/ orthancteam/orthanc:24.7.3-full` 
  - I go to `localhost:8042`

However, I still have the same issue where it says
 - "Unsupported Display Set" when I hover on the SEG icon in the left
 - "ReferencedSeriesSequence is missing for the SEG" in the console
 - "The selected display sets could not be added to the viewport due to a mismatch in the Hanging Protocol rules" in a popup when I double-click/drag-and-drop the image into the main viewport.
![image](https://github.com/user-attachments/assets/7c2274fa-9580-4668-9a86-c8b762cdd64c)

![image](https://github.com/user-attachments/assets/09b6e48e-8451-4755-a1fe-33c8ecd16a68)

**Comment by prerakmody** [comment]
Thanks! This worked.
Maybe this part can be highlighted somewhere in the documentation?

**Comment by amazy** [comment]
add a link to this issue in the doc: https://orthanc.uclouvain.be/hg/orthanc-book/rev/f8a335fdeae7

**Comment by sedghi** [comment]
Is this still an issue?

**Comment by amazy** [comment]
No, I think you can close the issue.

The next version of the orthanc-ohif plugin will have the `dicom-web` datasource by default which should reduce the occurrence of this problem. 

Thx !
