### ISSUE TITLE
[Bug] Memory leaks, larger memory footprint

### ISSUE THREAD

**Issue by jianyaoo** [OHIF/Viewers#4277]
### Describe the Bug

Hello,

When using the online viewer at https://viewer.ohif.org/, I noticed that repeatedly switching between studies causes the memory usage within the current tab to increase significantly (approximately after switching between 5 studies). Even when I return to the study list page from a particular study, the memory is not released.

I understand that the memory occupied by a study should be released after exiting its details, rather than continuously accumulating. I am encountering the same issue when using Cornerstone in my project, which could eventually lead to a page crash. Could you please advise on any effective handling methods or any configuration options I might have missed?

### Steps to Reproduce

Keep switching between studyList and study details

### The current behavior

The memory footprint keeps adding up

### The expected behavior

It is expected to reduce the memory footprint

### OS

macOS 13.6.7 

### Node version

18.16.0

### Browser

chrom 126.0.6478.127

**Comment by sedghi** [comment]
> I understand that the memory occupied by a study should be released after exiting its details

I'm not sure if that should be the default behavior. However, you can perform `cornerstone.cache.purgeCache` in the `onModeExit` function of your mode.
