### ISSUE TITLE
Ohif configuration opens four window levels

### ISSUE THREAD

**Issue by Wyd7151961** [OHIF/Viewers#4288]
### What feature or change would you like to see made?

I hope to be able to configure how many window bitmaps to open when opening the video reader. Currently, the program defaults to one, so I would like to change this to a configuration
![Uploading 微信图片_20240715152408.png…]()

### Why should we prioritize this feature?

I hope to be able to configure how many window bitmaps to open when opening the video reader. Currently, the program defaults to one, so I would like to change this to a configuration

**Comment by IT-Highmore** [comment]
Just change mode hangingProtocol from `default` to `@ohif/mnGrid`

**Comment by sedghi** [comment]
@IT-Highmore gave you the correct answer
