### ISSUE TITLE
Hounsfield (bone density) measurements are incorrect in nearly all cases. Typically by a factor of 7.

### ISSUE THREAD

**Issue by ArvindTrees** [OHIF/Viewers#4289]
### Describe the Bug

When using any tool that measures hounsfield units (bone density), such as the circle, ellipse tool, etc. the hounsfield units are off by a factor of 7. It might be a race condition since we have seen situations where the measurements are correct; however, upon a refresh of the browser/study the measurement will once again be incorrect. Air/empty space in a cone beam scan should read with a hounsfield value of -1000. In actuality the value is being reported as around -7000 more than nine times in 10.

### Steps to Reproduce

Use any tool such as the circle, freehand or ellipse tool that returns the bone density/hu/hounsfield measurements.

### The current behavior

the value returned is roughly 7 times the actual value. So areas that should be a -1000 (such as black space/air/empty space) are being reported as minus seven thousand instead.

### The expected behavior

It should return a correct HU value. The current value is extremely inaccurate.

### OS

OSX Sonoma 14.1.1

### Node version

unknown

### Browser

Chrome 126.0.6478.62

**Comment by sedghi** [comment]
is this related to this https://github.com/cornerstonejs/cornerstone3D/issues/1397 ?
