### ISSUE TITLE
Dear Team,Thank you for entire team for your support.When i try to open 3D .Browser hanging.It's going to no responsive mode for some cases.Any solution for this

### ISSUE THREAD

**Issue by psivasankarreddy1** [OHIF/Viewers#4300]
### Describe the Bug

When i try to open 3D .Browser handing.It's going to not response mode for some cases.Any solution for this

### Steps to Reproduce

When i try to open 3D .Browser handing.It's going to not response mode for some cases.Any solution for this

### The current behavior

When i try to open 3D .Browser handing.It's going to not response mode for some cases.Any solution for this

### The expected behavior

When i try to open 3D .Browser handing.It's going to not response mode for some cases.Any solution for this

### OS

windows server 16 standard 64 bit

### Node version

after publish

### Browser

Chrome 126.0.6478.182

**Comment by 934556826** [comment]
+1

**Comment by sedghi** [comment]
I don't understand the question, can you clarify with screenshots or errors
