### ISSUE TITLE
META's Segment Anything Model (SAM) for annotation

### ISSUE THREAD

**Issue by DrAkshaykumar** [OHIF/Viewers#4308]
### What feature or change would you like to see made?

META's Segment Anything Model (SAM) for faster annotations.

### Why should we prioritize this feature?

To help annotators annotate faster. Also useful in clinical trials.

**Comment by sedghi** [comment]
We have already implemented that feature for a commercial partner. They have agreed to open-source it in November. Stay tuned!

**Comment by DrRadiohead2** [comment]
@sedghi  Thanks. Will keep an eye on it :)
