### ISSUE TITLE
[Bug] OHIF doesn't load for an app hosted at non-root path

### ISSUE THREAD

**Issue by mtesopt** [OHIF/Viewers#4316]
### Describe the Bug

I’m embedding OHIF V3.7 inside a React app via an iframe.
When I run the application, the iframe is empty.

### Steps to Reproduce

1. I built the project,
2. Copied the build artifacts (contents of the dist folder), and
3. Placed them inside my React app’s public folder under **/ohif**

The React app is hosted at e.g. [https://www.example.com/med/study-images](https://www.example.com/med/study-images)
routerBaseName is **/med/study-images/ohif**
and PUBLIC_URL is **/med/study-images/ohif/**

I'm following the documentation from https://docs.ohif.org/deployment/custom-url-access

### The current behavior

The iframe is empty.

In the network panel, I see the request to ohif/ succeed with a 200 but
I don’t see subsequent calls to app-config, js bundles, and assets etc…

What is the correct configuration for routerBaseName and PUBLIC_URL when app is hosted at non-root path?

### The expected behavior

OHIF loads & shows the study list

### OS

Windows 10

### Node version

18.20.3

### Browser

Chrome v126

**Comment by helghast79** [comment]
Hi!

Had similar issue. Try using 
`PUBLIC_URL=/ohif/`
in your build script (/platform/app/package.json) and
`routerBasename: '/ohif'`
in your config file (/platform/app/public/config/yourConfig.js)

hope it helps, cheers!
