### ISSUE TITLE
[Feature Request] Report toggle within OHIF viewer

### ISSUE THREAD

**Issue by DrRadiohead2** [OHIF/Viewers#4320]
### What feature or change would you like to see made?

To have a report toggle button on the right upper corner, to make it possible for radiologists to write a report.

### Why should we prioritize this feature?

Especially useful for the teleradiology workflow.
Making this open-access would make teleradiology PACS development cheaper and more accessible.
This will also make OHIF a preferrable tool for future integrations.

**Comment by sedghi** [comment]
What do you mean by toggle?

**Comment by DrRadiohead2** [comment]
Thanks for your reply.

I meant a button which can bring up report screen after clicking from right
side and recede back when present again.

Toggle of report can be turned on or off showing what is written in the
report, which can include clinical history, radiology report, pathology
follow-up.

Only the authorised people would able to make changes in the report (can be
tied with some role functionality within xnat).

Will try to send some images tomorrow of this hypothetical toggle.

**Comment by sedghi** [comment]
I think this extends beyond OHIF's framework capabilities. However, I know companies and startups have developed products using OHIF as a front-end for radiology, with their own backends for storing and displaying reports. As you mentioned, this also falls within the scope of XNAT.

**Comment by AtulSiingh** [comment]
I was able to add Report Editor but there was issue that i was not able to get in the full view or in the viewport .

I use commands module but i was not able to access the viewport 
 openReport: () => {
      const { uiModalService } = servicesManager.services;
      if (uiModalService) {
        uiModalService.show({
          content: Report,
          title: 'Report',
          contentProps: {
            onClose: uiModalService.hide,
          },
        });
      }
    },
can u suggest me how to do it

**Comment by DrRadiohead2** [comment]
Dear Atul,
I am not sure how to fix this.
Can you post in the ohif and xnat Google community?

Regards
Akshaykumar
