### ISSUE TITLE
[Bug] MPR Distortion when studyPrefetcher Enabled

### ISSUE THREAD

**Issue by MedixonGit** [OHIF/Viewers#4323]
### Describe the Bug

When enabling the studyPrefetcher feature, the MPR (Multi-Planar Reconstruction) functionality results in distorted pixels. This issue does not occur when studyPrefetcher is set to false. I might have misunderstood the feature or there could be a lack of knowledge on my part. Any help or response would be greatly appreciated. Thanks!

### Steps to Reproduce

1. Set studyPrefetcher to true in the configuration.
2. Perform MPR on a study.
3. Observe the pixel distortion.

### The current behavior

When studyPrefetcher is enabled, performing MPR results in distorted pixels.

### The expected behavior

MPR should display without any pixel distortion, as it does when studyPrefetcher is disabled.

Distortion:
![Captura de pantalla 2024-08-01 123138](https://github.com/user-attachments/assets/52527ca8-1c7d-41ec-ad89-00cb12a27552)
![Captura de pantalla 2024-08-01 123128](https://github.com/user-attachments/assets/4205ff98-8bbe-4d34-8ed5-84b994d9e72e)

Without StudyPrefetch:
![Captura de pantalla 2024-08-01 123207](https://github.com/user-attachments/assets/6f1b888f-ea17-45a7-9450-a7110e08275d)

### OS

Windows 11

### Node version

18

### Browser

Brave: Version 1.68.134 Chromium: 127.0.6533.88

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)

**Comment by ReLifeNao** [comment]
It works ! , thanks a lot. Solved in latest ohif viewer.

**Comment by MedixonGit** [comment]
Yes , it works perfectly.
