### ISSUE TITLE
[Feature Request] Interactive Onboarding Guides

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4330]
Add an interactive onboarding guide feature using libraries such as `intro.js` or similar. This feature should be highly customizable, allowing users to add steps, target specific elements, and include descriptions. Additionally, it should incorporate validation to ensure each step is performed before proceeding to the next.

#### Detailed Description
Each mode can opt in to have an interactive onboarding guide to streamline the onboarding process for new users. This guide should leverage libraries such as `intro.js` to create user-friendly experience.

#### Key Features:
1. **Customizable Steps:**
   - Users should be able to add, remove, and rearrange steps in the guide.
   - Each step should include a description explaining the action or information needed.

2. **Element Targeting:**
   - Each step should be able to target specific elements on the page.
   - Highlight and focus on the target elements to draw user attention.

3. **Validation Mechanism:**
   - Implement validation to ensure the user performs the required action at each step.
   - Examples of actions include checking a service, listening to events, clicking a button, filling a form, etc.
   - The guide should prevent the user from advancing to the next step until the current step’s action is completed.

4. **Event Listening and Triggering:**
   - Listen for specific events to confirm the user has completed the required action.
   - Trigger custom events or actions based on user interactions with the guide.

5. **Feedback and Error Handling:**
   - Provide users with feedback if they attempt to skip steps.
   - Offer error messages or hints if the user encounters difficulties completing a step.

![CleanShot 2024-08-07 at 10 54 48@2x](https://github.com/user-attachments/assets/db0d0b55-d021-4188-8b6d-30880a3f657e)

Here's what I have found regarding libraries: Intro.js seems powerful, but it has limited licenses.

![image](https://github.com/user-attachments/assets/97354ed0-e291-445d-a664-7c2d50927e83)

**Comment by salimkanoun** [comment]
Nice, very nice design !
