### ISSUE TITLE
[Bug] Configuring activateViewportBeforeInteraction does not work

### ISSUE THREAD

**Issue by fightroad** [OHIF/Viewers#4334]
### Describe the Bug

Configuring activateViewportBeforeInteraction does not work.. use ohif 3.9 .

### Steps to Reproduce

Configuring activateViewportBeforeInteraction does not work.. use ohif 3.9 .

### The current behavior

Configuring activateViewportBeforeInteraction does not work.. use ohif 3.9 .

### The expected behavior

can work

### OS

windows10

### Node version

20

### Browser

chrome 122

**Comment by salimkanoun** [comment]
Can we get more details about your problem ? 
I don't see any problem in the latest build

activateViewportBeforeInteraction = true makes you require to first activate the viewport to interact with while activateViewportBeforeInteraction = false respond to the first click on the viewport
