### ISSUE TITLE
[Bug] Incorrect behavior when loading DICOM-SEG

### ISSUE THREAD

**Issue by MaartenDeMeyer** [OHIF/Viewers#4335]
### Describe the Bug

The OHIF viewer has incorrect behavior when loading certain DICOM Segmentation files:
- answering YES to the segmentation load popup only loads the labels, not the segmentation masks
- answering NO to the segmentation load popup only loads the segmentation masks, not the labels

Extra info:

- the segmentation files are valid to my knowledge.
- other tools display them just fine.
- we are aware of the issue with ReferencedSeriesSequence, and have included this sequence in our Segmentation files
- The issue does seem to be data-dependent; we have an external DICOM Segmentation file that does not show this behavior (on that one, even before the popup has been answered, the masks are visible after a doubleclick).
- Comparison of both files' tags doesn't show an immediate culprit, the dicom structures are very similar.

### Steps to Reproduce

1) Load attached DICOM MRI + segmentation file in https://viewer.ohif.org/localbasic (eg via load folder). Sample file: [ohif_seg_issue_repro.zip](https://github.com/user-attachments/files/16596853/ohif_seg_issue_repro.zip)
2) doubleclick Segmentation file thumbnail, observe popup is displayed
3) answer YES
4) Notice segmentation mask is not visible. Notice segmentation is present in segmentation panel list

5) refresh the page, and re-load the same folder
6) doubleclick Segmentation file thumbnail, observe popup is displayed
7) answer NO
8) notice segmentation mask IS visible, but labels in segmentation panel list are NOT

### The current behavior

The segmentation loading popup's 'NO' choice displays the segmentation mask, the popup's 'YES' choice loads the labels.

### The expected behavior

The segmentation loading popup's 'YES' choice should load both mask and labels. 'NO' choice should not result in loaded masks.

### OS

Ubuntu 22.04

### Node version

N/A

### Browser

Chrome 127.0.6533.99

**Comment by sedghi** [comment]
I think the latest OHIF 3.9 addresses this
