### ISSUE TITLE
[Bug] DICOM_SEG masks are displayed only when selecting `No` for the prompt `Do you want to open this Segmentation?`

### ISSUE THREAD

**Issue by Vlad-C-Crisan** [OHIF/Viewers#4342]
### Describe the Bug

DICOM_SEG masks are displayed only when selecting `No` for the prompt `Do you want to open this Segmentation?`

The metadata loads as expected when selecting `Yes`, but the mask data is only displayed when selecting `No`

### Steps to Reproduce

1. Open either https://viewer.ohif.org/localbasic (v3.8.3 at the time of writing) or https://viewer-dev.ohif.org/localbasic (v.3.9.0-beta.79 at the time of writing)
2. Download the public data from [HERE](https://kaikoai-my.sharepoint.com/:f:/g/personal/vlad_kaiko_ai/Els_foBsFNxIiUYKsZKr1sQBEQZzr0lWOnlQR5HvACJluQ?e=sTvuLe). The folder contains 2 examples. Each example has both the raw series and the DICOM_SEG annotation.
3. Load any of the folder examples from step 2 in any of the two OHIF versions from step 1.
4. Drag and drop the DICOM_SEG series. Select `Yes` when prompted `Do you want to open this Segmentation?`. Observe that metadata for the DICOM_SEG is loaded in the right panel, but there is no mask displayed when scrolling through the slices. Repeat the drag and drop an now select `No`. The masks are now present.

### The current behavior

Displaying masks in DICOM_SEG only works when selecting `No` for the prompt `Do you want to open this Segmentation?`

### The expected behavior

Masks should be displayed with the typical flow, when selecting `Yes`

### OS

OS X 10.15.7

### Node version

18.16.1

### Browser

Chrome 127.0.0

**Comment by Joeycho** [comment]
I also had the same issue, but I fixed in this way (I'm not sure whether it is optimal or temp solution). 

https://github.com/OHIF/Viewers/blob/4432b6b4209d39c625fe66010c45b1c7e8ce9c90/extensions/cornerstone-dicom-seg/src/viewports/OHIFCornerstoneSEGViewport.tsx#L149

L:149 at OHIFCornerstoneSEGViewport.tsx file, 'segIsLoading' should be reset from segDisplaySet (!segDisplaySet.isLoaded). After that I disabled the prompt and I programmatically passed (yes) by running 'onSubmit(RESPONSE.HYDRATE_SEG)'

**Comment by sedghi** [comment]
Coming soon

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)
