### ISSUE TITLE
[Bug] viewport overlays disappear for multiframe images when viewport initialImageOptions preset is 'middle'.

### ISSUE THREAD

**Issue by seandoyle** [OHIF/Viewers#4348]
### Describe the Bug

If the viewports are configured with 
```
            initialImageOptions: {
              preset: 'middle', // Triggers multiframe issue
            },
```
and the study contains multiple multi-frame images - the initial presentation of the study correctly shows the viewport overlays. But when an image icon is dragged onto the viewport - the overlays disappear. 

The issue is in `ohif/extensions/cornerstone/src/Viewport/Overlays/CustomizableViewportOverlay.tsx` - the imageIndex passed into displaySeriesProps is the frame number of the middle slice in the multiframe image. The value of `instances[imageIndex] `is undefined.

CustomizableViewportOverlay's displaySetProps appears to be called twice when the images are first drawn on the screen - once with the imageIndex of zero and then with the appropriate slice number.  But when an image is dragged onto the viewport only the imageIndex with the slice number is invoked. There is some other initialization that must have occurred in the images initially displayed on the screen which is not performed when images are dragged over. 

### Steps to Reproduce

1. Edit extensions/default/src/getHangingProtocolModule.js. Insert 
```
initialImageOptions: {
              preset: 'middle', // Triggers multiframe issue
            },
```
            into both viewports defined in this file (not sure which is used in the default basic image viewer). 
2. Display a study with multiple multiframe images in the Basic Viewer mode.
3. Drag an image that is not displayed in the viewport on top of the viewport.
4. The viewport overlays disappear. 

### The current behavior

Viewport overlay text disappears.

### The expected behavior

The viewport overlay text appears on every image. 

### OS

Ubuntu 20.04

### Node version

v20.14.0

### Browser

Chrome Version 126.0.6478.182 (Official Build) (64-bit)

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)

**Comment by seandoyle** [comment]
@sedghi  It looks like it still occurs. I was testing with OHIF 3.9.1 commit hash 610faa5a2738da5eabc40e57e338c359f481e852

There is a new error as well - a warning dialog appears when you drag/drop a series into a viewport.  Here's what is on the console. 

OHIFCornerstoneViewport: Rerender caused by: displaySet not found
ErrorBoundary.tsx:168 Route /viewer Error Boundary ReferenceError: IMAGE_REQUEST_TYPE is not defined
    at $e._stopPrefetching (StudyPrefetcherService.ts:682:49)
    at $e._restartPrefetching (StudyPrefetcherService.ts:692:12)
    at $e._setActiveDisplaySetsUIDs (StudyPrefetcherService.ts:313:10)
    at $e._syncWithActiveViewport (StudyPrefetcherService.ts:294:36)
    at Object.callback (StudyPrefetcherService.ts:241:18)
    at pubSubServiceInterface.ts:88:16
    at Array.forEach (<anonymous>)
    at q.l [as _broadcastEvent] (pubSubServiceInterface.ts:87:31)
    at ViewportGridService.ts:199:12 null Route /viewer

**Comment by IbrahimCSAE** [comment]
it might be related to using the frame index to fetch the instance, there's only 1 instance so it will return undefined

**Comment by IbrahimCSAE** [comment]
I cant replicate this, can you confirm its still a problem


https://github.com/user-attachments/assets/1c353a7f-233a-41f1-9e65-982b6c880234
