### ISSUE TITLE
GET http://127.0.0.1:81/dicom-web/studies/......./metadata 500 (Internal Server Error)

### ISSUE THREAD

**Issue by kongzhonglei** [OHIF/Viewers#435]
I have occasional problems like this here, GET http://127.0.0.1:81/dicom-web/studies/2.16.840.1.114492.45306600636776220.215577003565.10724.5370/metadata 500 (Internal Server Error).

I think it's about parsing the problem of METADATA. I tried to modify it, but I still can't solve it.

**Comment by kongzhonglei** [comment]
[2.16.840.1.114492.4530665600636776220.215577003566.10724.5372.zip](https://github.com/OHIF/Viewers/files/3185473/2.16.840.1.114492.4530665600636776220.215577003566.10724.5372.zip)
![DFE44$@{O60VAFG3 _$OFPH](https://user-images.githubusercontent.com/26484022/57827772-4d4dd380-77db-11e9-86f4-a1fc5caed17f.png)

**Comment by swederik** [comment]
Do you see any messages in your browser console? Maybe there is something wrong with this file, and the PACS refuses to serve it? Which PACS are you using?. If you are getting 500 errors from your PACS, that's not an OHIF issue.
