### ISSUE TITLE
[Bug] Images in planar configuration 1

### ISSUE THREAD

**Issue by rikous91** [OHIF/Viewers#4359]
### Describe the Bug

All RGB images with planar configuration 1 are not displayed correctly.

### Steps to Reproduce

1. Open the OHIF viewer from here --> https://viewer-dev.ohif.org/localbasic
2. Load this anonymized dicom into the zip--> [1.3.46.670589.33.1.30100659721411649347.27240394361720301982_anon.zip](https://github.com/user-attachments/files/16895040/1.3.46.670589.33.1.30100659721411649347.27240394361720301982_anon.zip)

### The current behavior

The image, instead of being displayed correctly, appears as small 3x3 images.

### The expected behavior

The image should be displayed correctly in color.

### OS

Windows 10

### Node version

18.15.0

### Browser

Chrome 128.0.6613.86

**Comment by arturojain** [comment]
I have a similar problem in https://github.com/OHIF/Viewers/issues/4231

**Comment by wayfarer3130** [comment]
Has been fixed in CS3D and needs to update libraries in OHIF

**Comment by sedghi** [comment]
Fixed now 
![CleanShot 2024-10-23 at 23 01 04@2x](https://github.com/user-attachments/assets/a23942e4-8e42-43ee-a407-29797309327d)
