### ISSUE TITLE
[Bug] Modes.json doesn't work

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#4362]
### Describe the Bug

I have changed values  to my language in the Modes.json but it doesn't work

### Steps to Reproduce

- Copy file Modes.json in \platform\i18n\src\locales\vi\Modes.json to your locales folder
- Change value
- Restart ohif viewer, go to the Study list, select one line and check the button name as "Basic Viewer", ....,

### The current behavior

It doesn't work

### The expected behavior

Change to your language after change values in Modes.json file

### OS

Ubuntu 24, Windows

### Node version

21.7.3

### Browser

Chrome

**Comment by IT-Highmore** [comment]
Maybe you doesn't export Modes.json in index.js.

**Comment by lam0620** [comment]
@IT-Highmore

I fixed it! Thank you for your support.
