### ISSUE TITLE
[BUG] Hot loading is not working

### ISSUE THREAD

**Issue by Dargouls** [OHIF/Viewers#4363]
### Describe the Bug

Using the latest version of the viewer, Hot loading does not work. I tested using webpack’s “hot module replacement”, but it takes about 30 seconds to compile. Is there a way to optimize this for development?

### Steps to Reproduce

1. Yarn install
2. Yarn dev
3. Make any visible changes

### The current behavior

The code changes is not made instantly. 

### The expected behavior

When you save your front-end code, your changes should be reflected immediately on the screen With hot loading.

### OS

Windows 10

### Node version

18.16

### Browser

Opera

**Comment by sedghi** [comment]
it works for me on my new branch, wait for next release, i guess it gets fixed automatically. re-open if not
