### ISSUE TITLE
What is the function in ohif viewer to retrive/parse annotation data in the format of inlinebinary?

### ISSUE THREAD

**Issue by chandrapenumarthi** [OHIF/Viewers#438]
Hi,
I am receiving the annotation data in inline binary format from dicom image.. I am unable to find the function which is converting the inline binary to meta data tags which having area and handler information..
Please let me know the debug steps for annotations

Thanks,
Chandra.p

**Comment by dannyrb** [comment]
The OHIF Viewer uses the CornerstoneWADOImageLoader, which uses DicomParser, to read the metadata tags from the DICOM file. The tags are made available to CornerstoneTools via Cornerstone's "MetaDataProvider". As it stands, I don't believe we pull any data from a DICOM file to initialize toolState. There is an effort being made to add out of the box support for this, but I'm not aware of the specifics.
