### ISSUE TITLE
[Feature Request] Show the patient's name along with the exam date above the exam images

### ISSUE THREAD

**Issue by insinfo** [OHIF/Viewers#4390]
### What feature or change would you like to see made?

Most medical exam image viewing software shows the patient's name and exam date on the exam images, this is very useful and avoids several problems.

![image](https://github.com/user-attachments/assets/a4b67866-ed44-498c-9620-36074ab029ae)

Oviyam
![image](https://github.com/user-attachments/assets/6fbf0a3f-6ad1-4d22-a2bd-99f3ebc3ae0d)

![image](https://github.com/user-attachments/assets/324777df-56a5-49ff-b555-68c88d10f60f)

### Why should we prioritize this feature?

The doctors and technicians at the municipal public hospital where we imported OHIF to replace Oviyam are asking me for this every day, because Oviyam had it, and they see it as something very important for their day-to-day work.

**Comment by fedorov** [comment]
To add to the above, PatientName was also shown in OHIF v2.

Screenshot below is from https://viewer.imaging.datacommons.cancer.gov/v3/viewer/?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1.32997549471155137588978062652800610146&SeriesInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1.25107758639041872550905433592432155670

![image](https://github.com/user-attachments/assets/986b3b73-b121-412c-8d13-eb30bdb13011)

**Comment by infrapmro** [comment]
![image](https://github.com/user-attachments/assets/9db7be21-d549-4028-8e58-40eba441ade6)

Hey @fedorov , we are using version above!!

**Comment by fedorov** [comment]
OHIF v2 is the previous generation of the viewer, which is at this point not supported. I just pointed that out to say that the feature you requested was available in the previous v2 generation, but was removed in v3. I agree it would be nice to bring it back.

**Comment by insinfo** [comment]
I didn't know this was displayed in version 2, it's too bad they removed it, in my opinion it was a regression, maybe there should be a configuration screen to enable or disable this, maybe recording in localstorage.

**Comment by leonardomw** [comment]
I agree it would be good to bring him back too. And it's a simple feature.

**Comment by erimes84** [comment]
important resource that will be very welcome.

**Comment by orodrigomellos** [comment]
removing it from the application really leaves the result incomplete. This application will make all the difference not only for the patient but also for the doctor.

**Comment by AmmarProIT** [comment]
If you wish to display the patient information in OHIF V3, simply replace the content of file (ViewportPane.js). However, ensure to create a backup of the file beforehand. This precaution will allow you to restore the original file in case any issues arise during the replacement
[ViewportPane.zip](https://github.com/user-attachments/files/17171928/ViewportPane.zip)

**Comment by sedghi** [comment]
We already support customizable overlays. Please refer to AmmarProIT's response. I'm closing this, but feel free to reopen it if there's a bug.

**Comment by sedghi** [comment]
it is not the source code it is the configuration file, please read the doc here [https://docs.ohif.org/platform/services/ui/customization-service/#customizable-viewport-overlay](https://docs.ohif.org/platform/services/ui/customization-service/#customizable-viewport-overlay)
