### ISSUE TITLE
[Bug] numInstances: PropTypes.number breaks when numInstances are in string

### ISSUE THREAD

**Issue by arunvc** [OHIF/Viewers#4391]
### Describe the Bug

numInstances: PropTypes.number breaks when numInstances are in string

change 
````
numInstances: PropTypes.number to
numInstances: PropTypes.any
```

### Steps to Reproduce

use any study where numInstances is configured as string

### The current behavior

error

### The expected behavior

handle numInstances as string and number 

### OS

Ubuntu 22

### Node version

18

### Browser

Latest Chrome and Firefox

**Comment by sedghi** [comment]
It seems like a bug is occurring in your specific use case. Can you help us with a PR?

**Comment by martinopiniator** [comment]
yes for us in some cases we are receiving the json in quotes 
numInstances: "1"

we are using any in our version

You may close this issue.
