### ISSUE TITLE
[Feature Request] The viewer's functionality and UI are compatible with tablets and mobile devices 

### ISSUE THREAD

**Issue by 18514098548** [OHIF/Viewers#4425]
### What feature or change would you like to see made?

Viewing the viewer on a mobile device browser can automatically adapt the UI and functions or have a dedicated UI design for mobile devices.

### Why should we prioritize this feature?

Access to medical images on mobile devices can make it convenient for patients to seek medical attention, and also enable doctors to have a better understanding of the patient's actual condition more quickly.

**Comment by sedghi** [comment]
In progress, checkout our roadmap please
