### ISSUE TITLE
[Bug] docker error

### ISSUE THREAD

**Issue by Rajat-Imme** [OHIF/Viewers#4428]
### Describe the Bug

when i run docker compose up defined in platform\app\.recipes\Nginx-Orthanc. It throws error as

![DICOM error](https://github.com/user-attachments/assets/edcf0307-8465-4230-96c3-81f76f77ffcc)

### Steps to Reproduce

1. navigate to platform\app\.recipes\Nginx-Orthanc

2. Run Docker compose up

### The current behavior

docker compose up throws error host not found in upstream orthanc in etc/nginx/nginx.conf:56

### The expected behavior

Docker should run both the images 

### OS

windows 11, I9 13th genration

### Node version

20.18.0

### Browser

Chrome

**Comment by arunvc** [comment]
This is ohif viewer repo,

if you are looking to setup Orthanc check this out  
https://github.com/orthanc-server/orthanc-setup-samples
