### ISSUE TITLE
[Bug] on arrow key down the left panel disappear and reappears

### ISSUE THREAD

**Issue by arunvc** [OHIF/Viewers#4431]
### Describe the Bug

on key down the left thumbs disappears, seems like   useExperimentalUI: false, is removed in 101 beta version
no issue using mouse scroll

https://github.com/user-attachments/assets/a7f36662-adbc-427b-bf2c-732b1bb6a4fa

### Steps to Reproduce

drag an image use keyboard arrow key down and up 

### The current behavior

the left panel thumbnail images hide and then appear or next down key press

### The expected behavior

 left panel thumbnail images should not disappear

### OS

ubuntu 22

### Node version

18

### Browser

firefox and chrome

**Comment by sedghi** [comment]
I have it fixed, i'll push a fix soon

but fyi for now 

![CleanShot 2024-10-23 at 23 05 31@2x](https://github.com/user-attachments/assets/418820a2-0eb4-41b2-80a0-7a48bc59ea42)
