### ISSUE TITLE
[Bug] Tools are made to entertain Investors not for real world usage

### ISSUE THREAD

**Issue by arunjoshtech** [OHIF/Viewers#4434]
### Describe the Bug

Zoom , Pan not working properly and it is lead to use other viewer instead.
Dear Ohif team, how you are working? Any viewer the fundamental tools must be stable and big free. Then you can project 3D or 4 D or even 5 D.
From Ohif version 2D onwards you are not making big free system instead full of glitched filled tools.
What is is the point to work on Community.

### Steps to Reproduce

zoom is moving very faster and not able to pan or apply other tools.

### The current behavior

Same as descriptions.

### The expected behavior

Same as descriptions.

### OS

Windiws

### Node version

Your standard 

### Browser

Chrome or edge any latast version

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)

**Comment by arunjoshtech** [comment]
lot of issues while add tools, Let me try once update here.
