### ISSUE TITLE
[Bug] "docker-compose: not found" when running yarn run orthanc:up

### ISSUE THREAD

**Issue by arnaudberenbaum** [OHIF/Viewers#4438]
### Describe the Bug

Impossible to run "yarn run orthanc:up" as reported here : [https://community.ohif.org/t/how-to-solve-this-error-data-source-connection-error-error-request-failed-please-ensure-the-following-data-source-is-configured-correctly-or-is-running-orthanc-server/1750/2](https://community.ohif.org/t/how-to-solve-this-error-data-source-connection-error-error-request-failed-please-ensure-the-following-data-source-is-configured-correctly-or-is-running-orthanc-server/1750/2)

### Steps to Reproduce

1. Download source code
2. cd to master forder
3. yarn run install
4. yarn run orthanc:up

### The current behavior

Impossible to run orthanc:up

### The expected behavior

Starting the orthanc docker

### OS

MacOS 15.0.1

### Node version

21.5.0

### Browser

Opera One(version: 115.0.5314.0) (arm64)

**Comment by sedghi** [comment]
I think this is fixed

Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic) Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)
