### ISSUE TITLE
 Do not work configuration file dcm4cheeDIMSE.json when I run "yarn run dev"

### ISSUE THREAD

**Issue by christianvargasforero** [OHIF/Viewers#445]
I am trying the new version but every time I want to connect through the configuration file dcm4cheeDIMSE.json, the following error is output: "TypeError: Can not read property 'routerBasename' of undefined" when wanting to see the configuration with: "window.config. routerBasename "is undefined. Still supports connections with DIMSE? If so, how should such a configuration be? I see that default.js is of type .js unlike dcm4cheeDIMSE is .json.
I send an image of the errors that appear in the console:

![Captura de Pantalla 2019-05-17 a la(s) 3 25 30 p  m](https://user-images.githubusercontent.com/11984387/57954696-43020700-78b9-11e9-9b66-e54c88c413e7.png)

> TypeError: Cannot read property 'routerBasename' of undefined
Module../src/components/OHIFLogo/OHIFLogo.js
src/components/OHIFLogo/OHIFLogo.js:5
  2 | import './OHIFLogo.css'
  3 | 
  4 | console.log("window.config ", window.config)
 5 | const Icons = `${window.config.routerBasename}/icons.svg`
  6 | 
  7 | function OHIFLogo() {
  8 |   return (
View compiled
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/WhiteLabellingContext.js
src/WhiteLabellingContext.js:1
> 1 | import OHIFLogo from './components/OHIFLogo/OHIFLogo.js';
  2 | import React from 'react';
  3 | 
  4 | const defaultContextValues = {
View compiled
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/connectedComponents/Viewer.js
http://localhost:5000/static/js/main.chunk.js:4607:83
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/connectedComponents/ConnectedViewer.js
src/connectedComponents/ConnectedViewer.js:1
> 1 | import { connect } from 'react-redux';
  2 | import Viewer from './Viewer.js';
  3 | import OHIF from 'ohif-core';
  4 | 
View compiled
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/connectedComponents/ViewerRetrieveStudyData.js
http://localhost:5000/static/js/main.chunk.js:5120:77
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/routes/IHEInvokeImageDisplay.js
http://localhost:5000/static/js/main.chunk.js:5750:105
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/OHIFStandaloneViewer.js
http://localhost:5000/static/js/main.chunk.js:665:90
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/App.js
http://localhost:5000/static/js/main.chunk.js:312:80
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/index.js
src/index.js:1
> 1 | /**
  2 |  * Entry point for development and production PWA builds.
  3 |  * Packaged (NPM) builds go through `index_publish.js`
  4 |  */
View compiled
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
0
http://localhost:5000/static/js/main.chunk.js:6933:18
__webpack_require__
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
checkDeferredModules
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | return result;
View compiled
Array.webpackJsonpCallback [as push]
/Users/christianvargas/Developer/Viewers/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:5000/static/js/main.chunk.js:1:57
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

 Thank you very much for your great work.

**Comment by dannyrb** [comment]
Here are the latest docs on configuration: https://docs.ohif.org/essentials/configuration.html

That particular file is a left-over from v1. Our latest version no longer has a "server side" (in v1, this was meteor), so we can no longer offer DIMSE support (at least out of the box). If there is a particular recipe you would find helpful that is not included in the docs, please let me know.

I'll add cleaning up the old configuration files to my task list 👍

**Comment by dannyrb** [comment]
I've gone ahead and merged a change that removed the old configuration files. If you have trouble following the updated documentation, or would like to see additional configuration/deployment recipes, please don't hesitate to create a new issue.
