### ISSUE TITLE
[Bug] JPEG Baseline with Transfer Syntax 1.2.840.10008.1.2.4.50 - MPR is not rendered correctly

### ISSUE THREAD

**Issue by HemantPatel30** [OHIF/Viewers#4450]
### Describe the Bug

JPEG  Baseline with Transfer Syntax 1.2.840.10008.1.2.4.50 - MPR is not rendered correctly

### Steps to Reproduce

Load data on local data source & select DCM files
Stack viewport is loaded correctly
And go to MPR

### The current behavior

MPR is loaded white

### The expected behavior

MPR should render same as stack viewport
<img width="961" alt="MPR" src="https://github.com/user-attachments/assets/52c46f6a-34aa-48e6-8f22-5a15a8bdfcbc">
<img width="961" alt="Stack" src="https://github.com/user-attachments/assets/9eab803e-ecad-4b21-af03-0bfd75a6f824">

### OS

MAC

### Node version

18.0.0

### Browser

Chrome

**Comment by sedghi** [comment]
can you try this branch? feat/cs3d-2

**Comment by IT-Highmore** [comment]
> can you try this branch? feat/cs3d-2

I try the feat/cs3d-2 branch in localhost, I accidentally find follow example mpr is not rendered correctly too.
![image](https://github.com/user-attachments/assets/652db638-156b-4fc8-8727-a0ac4b83f01f)

![image](https://github.com/user-attachments/assets/3f943642-601e-4c4b-9e29-f1299731afb4)

**Comment by sedghi** [comment]
Does this happen in latest master branch with cornerstone3D 2.0?
