### ISSUE TITLE
main image view port lost after resize

### ISSUE THREAD

**Issue by arunvc** [OHIF/Viewers#4453]
### Describe the Bug

resize the screen the main image is lost, try demo site

### Steps to Reproduce

https://github.com/user-attachments/assets/ab08d288-141b-4c11-b289-e060a3ed6b18

### The current behavior

image disappears

### The expected behavior

mail image should stay the same

### OS

ubuntu 22

### Node version

18

### Browser

Latest Chrome and Firefox

**Comment by sedghi** [comment]
We should set a minimum for viewport pane

**Comment by sedghi** [comment]
platform/ui/src/components/ViewportPane/ViewportPane.tsx
