### ISSUE TITLE
[Feature Request] Download Dicom image in STL format

### ISSUE THREAD

**Issue by Rajat-Imme** [OHIF/Viewers#4474]
### What feature or change would you like to see made?

Convert dicom files to STL format and download it

### Why should we prioritize this feature?

STL files represent a solid 3D object, and converting DICOM data to STL allows medical professionals and researchers to better visualize and understand the anatomical structures in three dimensions.

**Comment by sedghi** [comment]
You mean SEG right? I don't think you are talking about CT, MR

**Comment by sedghi** [comment]
We don't plan to add STL format downloads in SEG, but you can include this feature in your extensions. Refer to `SegmentationService` to learn how to export DICOM SEG, which we have implemented. Use it as a guide to implement STL. extensions/cornerstone-dicom-seg/src/commandsModule.ts
