### ISSUE TITLE
docker builds fails at 

### ISSUE THREAD

**Issue by EsrefDurna** [OHIF/Viewers#448]
$docker build -t ohif/viewer:latest -f dockerfile-web .

Step 9/15 : RUN yarn run build:web
 ---> Running in 2e15a7ff580e
yarn run v1.15.2
$ yarn run preBuild && react-scripts build
$ yarn run version && yarn run copy:webworkers
$ node -p -e "'export default \'' + require('./package.json').version + '\';'" > src/version.js
$ cpx 'node_modules/cornerstone-wado-image-loader/dist/*.min.js*' public
Creating an optimized production build...

at this step which is executing 
$cpx 'node_modules/cornerstone-wado-image-loader/dist/*.min.js*' public

hangs and docker build fails.

**Comment by dannyrb** [comment]
I have on my list to fix our public docker image to work with the version 2 of the viewer (the react changes that are now on master).

It's odd that the copy step is where it's getting hung up. I'll take a look at your PR today to see if it aligns with the direction we're aiming for.

If you want to expand on what you're trying to accomplish, or hoping that we support / continue to support, I am more than happy to try and accomodate ^_^

**Comment by swederik** [comment]
Looks like when you use [cpx](https://github.com/mysticatea/cpx) on linux you have to enclose any globs in double quotes.

> Since Bash expands globs, requires to enclose it with double quotes.

You have to escape them like:

`"cpx \"node_modules/cornerstone-wado-image-loader/dist/*.min.js*\" public"`

**Comment by EsrefDurna** [comment]
Thank you I will test and create a PR if it works

**Comment by EsrefDurna** [comment]
I found this issue is related with react-scripts build 
and the problem is related with the timeout. and to solve this timeout we have to set GENERATE_SOURCEMAP=false
for the docker builds. 
https://facebook.github.io/create-react-app/docs/advanced-configuration

**Comment by dannyrb** [comment]
@EsrefDurna, thanks for looking into this. I've changed a few things and left a comment on your in-progress PR. If you can resolve merge conflicts, I am more than happy to accept your changes.

**Comment by EsrefDurna** [comment]
it says

This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.

**Comment by dannyrb** [comment]
You can pull master's changes into your PR branch and then resolve conflicts in that branch, because you have ownership of it.

**Comment by EsrefDurna** [comment]
this issue is resolved, docker build currently works after applying.

ENV GENERATE_SOURCEMAP=false
