### ISSUE TITLE
[Feature Request] I want to change the default viewport when opening a study to 4 viewports, currently by default only 1 viewport can be loaded.

### ISSUE THREAD

**Issue by itcthienkhiem** [OHIF/Viewers#4482]
### What feature or change would you like to see made?

 I want to change the default viewport when opening a study to 4 viewports, currently by default only 1 viewport can be loaded.

### Why should we prioritize this feature?

Some doctors need to view 4 different image planes

**Comment by IT-Highmore** [comment]
Just change hangingProtocol to @ohif/mnGrid and set stages first 2x2 Or create a new hangingProtocol
