### ISSUE TITLE
[Bug] createSlabThicknessSynchronizer initial slice index issue

### ISSUE THREAD

**Issue by salkz** [OHIF/Viewers#4485]
### Describe the Bug

We noticed a peculiar issue with `createSlabThicknessSynchronizer` - if you add this synchronizer to a viewport then the initial loaded slice index will be some very weird number instead of the usual middle slice.

### Steps to Reproduce

Adding synchronizer to a viewport immediately on a `VIEWPORT_DATA_CHANGED` event it works unexpectedly:
```typescript
const synchronizerId = 'SLAB_THICKNESS_SYNCHRONIZER_ID';
const synchronizer = synchronizers.createSlabThicknessSynchronizer(synchronizerId);
const renderingEngineId = 'OHIFCornerstoneRenderingEngine';

...

useEffect(() => {
  cornerstoneViewportService.subscribe(
    cornerstoneViewportService.EVENTS.VIEWPORT_DATA_CHANGED,
    event => {
      synchronizer.add({
        renderingEngineId,
        viewportId: event.viewportId,
      });
    }
  );
}, []);
```

However, when added with a `setTimeout(..., 2000)`, it works as expected:
```typescript
useEffect(() => {
  cornerstoneViewportService.subscribe(
    cornerstoneViewportService.EVENTS.VIEWPORT_DATA_CHANGED,
    event => {
      setTimeout(() => {
        synchronizer.add({
          renderingEngineId,
          viewportId: event.viewportId,
        });
      }, 2000);
    }
  );
}, []);
```

### The current behavior

The initial slice indexes are some weird number as seen on the image:
![image](https://github.com/user-attachments/assets/1d6c9d1f-424c-408b-a217-ef5dbe930e69)

### The expected behavior

The initial slice indexes are for the middle slices in all viewports.

### OS

macOS 14.5 (23F79)

### Node version

v18.20.4

### Browser

Version 130.0.6723.70 (Official Build) (arm64)

**Comment by sedghi** [comment]
I pushed a fix, but the real solution is to recompute the image index when the slab thickness changes. We shouldn't keep the old slice numbers when the slab changes; instead, we should recalculate the number of slices after the slab thickness changes.
