### ISSUE TITLE
[Bug] On windows, scrollbar is absent from study browser and no method of scrolling seems available

### ISSUE THREAD

**Issue by wayfarer3130** [OHIF/Viewers#4487]
### Describe the Bug

On windows, the scrollbar seems to be missing entirely from the study browser, and there does not seem to be any way to actually scroll it.

It might be "nice" to not use the space for scroll bars, but the reality is that it is a critical notification to the user that there is more data to be seen.  Avoiding the scroll bars means potentially not indicating to the user that everything is visible and is thus a patient safety issue in a clinical setting.

Also, after closing the study in the study browser, it is no longer possible to open the study again - it will randomly show the contents for a second, but not reliably.

### Steps to Reproduce

1. Display a study with lots of series
2. Try to figure out where in the study browser list you are
3. Try scrolling

### The current behavior

No scroll bar is available
Scrolling doesn't work with any combination of mouse buttons etc I tried

### The expected behavior

I expect a scrollbar to be visible if there is more content than can be shown.
I expect to be able to scroll using the mouse wheel or left click drag or click middle and mouse move/click middle to finalize

### OS

Windows 11

### Node version

NA

### Browser

Brave, VIvaldi, Chrome

**Comment by sedghi** [comment]
This will fix it https://github.com/OHIF/Viewers/pull/4483
