### ISSUE TITLE
[Bug] addIcon from ui is missing in ui-next

### ISSUE THREAD

**Issue by wayfarer3130** [OHIF/Viewers#4489]
### Describe the Bug

Icons added using the ui.addIcon functionality aren't working in some places, and it isn't clear why they work in one spot and not another until one reads the code and finds out that something used the ui-next package, which doesn't support addIcon

### Steps to Reproduce

Use addIcon to add an icon

### The current behavior

Icons show error missing icon

### The expected behavior

Icons appear

### OS

NA

### Node version

NA

### Browser

NA

**Comment by sedghi** [comment]
fixed in https://github.com/OHIF/Viewers/pull/4490
