### ISSUE TITLE
DIMSE Support v2.0

### ISSUE THREAD

**Issue by christianvargasforero** [OHIF/Viewers#450]
DIMSE support According to the previous comments in the new version v2.0 there is no support for DIMSE requests, but it is possible to make this type of calls with a kind of proxy. We really see that it is necessary to have this type of request since not all PACS support DICOM-WEB, at least the old ones. Any idea where can I develop my own proxy?

**Comment by dannyrb** [comment]
👋 Hi @christianvargasforero, there are a few features that were either cut entirely, or are not yet implemented in version 2 of the viewer. If they are mission critical for your team, then it may make more sense to stay with version 1 (for at least the short term).

I can create a roadmap card for DIMSE support, but I don't believe it will be a high priority for our core team anytime soon without additional funding. That being said, I would be more than happy to review any PRs that add support.

One potential path is using the DIMSE code from version one, found and packaged nicely here: https://github.com/OHIF/dicom-dimse

You could use it as part of a standalone Node app, then provide some simple Express routes for DICOMWeb-style calls. Creating a node proxy between DICOMweb to make DIMSE calls.

**Comment by dannyrb** [comment]
I've created a roadmap card here: https://github.com/OHIF/Viewers/projects/3#card-21751449

More than happy to discuss implementation details. If you would like to claim the card or have further discussion items, please let me know.

**Comment by pieper** [comment]
@christianvargasforero I haven't tried it but Google offers this adapter that you may be able to use right out of the box:

https://github.com/GoogleCloudPlatform/healthcare/tree/master/imaging/dicom_adapter

Let us know if this works for you and if so we could add it to our documentation.

**Comment by christianvargasforero** [comment]
> @christianvargasforero I haven't tried it but Google offers this adapter that you may be able to use right out of the box:
> 
> https://github.com/GoogleCloudPlatform/healthcare/tree/master/imaging/dicom_adapter
> 
> Let us know if this works for you and if so we could add it to our documentation.

It's a good alternative, I'm going to explore, the only thing I see is that it depends on having a project in Google Cloud.

**Comment by fredericcervenansky** [comment]
@christianvargasforero did you find a way to submit dimse requests through a proxy? And for private and secure issues, I won't use the dicom adapter from Google.

**Comment by christianvargasforero** [comment]
> @christianvargasforero did you find a way to submit dimse requests through a proxy? And for private and secure issues, I won't use the dicom adapter from Google.

I have not yet been able to review the subject, since I have been working on other developments
