### ISSUE TITLE
3.9 Recovery 1 

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4500]
Issues 

- [ ] https://github.com/OHIF/Viewers/issues/4499
- [ ] https://github.com/OHIF/Viewers/issues/4485
- [ ] https://github.com/OHIF/Viewers/issues/4505
- [ ] https://github.com/OHIF/Viewers/issues/4519
- [ ] https://github.com/OHIF/Viewers/issues/4485
- [ ] https://github.com/OHIF/Viewers/issues/4531
- [ ] https://github.com/OHIF/Viewers/issues/4530
- [ ] https://github.com/OHIF/Viewers/issues/4352
- [ ] https://github.com/OHIF/Viewers/issues/4529
- [ ] https://github.com/OHIF/Viewers/issues/4535
- [ ] https://github.com/OHIF/Viewers/issues/4539
- [ ] https://github.com/OHIF/Viewers/issues/4536

**Comment by khivi** [comment]
Make it should be this.requestType.
