### ISSUE TITLE
[Bug]  Loading NM images locally throws error

### ISSUE THREAD

**Issue by ahlaughland** [OHIF/Viewers#4519]
### Describe the Bug

When testing OHIF locally at https://viewer-dev.ohif.org/localbasic
 
I loaded NM images but get an error:
![image](https://github.com/user-attachments/assets/cb868549-5666-448f-99f7-852b8c104a5a)

Clicking `Show Details` doesn't show anything.

### Steps to Reproduce

Load https://viewer-dev.ohif.org/localbasic
Drag DICOM files of NM modality

### The current behavior

I loaded NM images but get an error:
![image](https://github.com/user-attachments/assets/cb868549-5666-448f-99f7-852b8c104a5a)

Clicking `Show Details` doesn't show anything.

### The expected behavior

The NM should load into OHIF.

### OS

Windows 10

### Node version

18.16.1

### Browser

Chrome

**Comment by sedghi** [comment]
Can you share some NM dataset with us?

**Comment by ahlaughland** [comment]
Sure, let me ask what set(s) I can share.

**Comment by ahlaughland** [comment]
@sedghi Here is the `NM` dataset - it's SNMMI Challenge public data:

[t1.spect_rescale.zip](https://github.com/user-attachments/files/17836203/t1.spect_rescale.zip)

**Comment by sedghi** [comment]
Yeah i found the issue, thanks for sharing
