### ISSUE TITLE
[Bug] Cannot convert undefined or null to object with study has dicom tag (0043,1097) value's element = null

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#4524]
### Describe the Bug

Ohif viewer version: 3.9.1.
When open a study that has a dicom tag (0043,1097) value as attached, a error occurs: Cannot convert undefined or null to object.

at method: addRetrieveBulkDataNaturalized() of file: extensions\default\src\DicomWebDataSource\index.js

### Steps to Reproduce

Open a MR study that has a dicom tag (0043,1097) value as attached
![image](https://github.com/user-attachments/assets/e884db97-4d1a-495b-b145-3a3fc87ecbfa)

### The current behavior

A error occurs:
![image](https://github.com/user-attachments/assets/245beee1-f281-4edb-b726-e34ed2ff7900)

### The expected behavior

Can open image viewer correctly

Is it correct if I fix this by check: if (naturalized == null) return; as

```
      const addRetrieveBulkDataNaturalized = (naturalized, instance = naturalized) => {
        **if (naturalized == null) return;**
        for (const key of Object.keys(naturalized)) {
         ...
        }
    }
```

### OS

Windows 11

### Node version

21.7.3

### Browser

Chrome

**Comment by IbrahimCSAE** [comment]
I think this is already resolved, I uploaded this to dcm4chee locally and it opens up with no problems

**Comment by IbrahimCSAE** [comment]
<img src="https://uploads.linear.app/e0b640a9-3fd8-4513-bc84-af25921e5dc8/3970b6a1-f55c-461a-97ae-bf07b62e9cf2/002779c8-a3f7-4f78-89e6-916ac34f7d57?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UwYjY0MGE5LTNmZDgtNDUxMy1iYzg0LWFmMjU5MjFlNWRjOC8zOTcwYjZhMS1mNTVjLTQ2MWEtOTdhZS1iZjA3YjYyZTljZjIvMDAyNzc5YzgtYTNmNy00Zjc4LTg5ZTYtOTE2YWMzNGY3ZDU3IiwiaWF0IjoxNzM0Njg5MzcwLCJleHAiOjMzMzA1MjQ5MzcwfQ.tBJbdtGex7B4oAsiiTaNx7VGu7KGW1SydnpwpN7GOSA " alt="CleanShot 2024-12-20 at 05.09.00@2x.png" width="4362" data-linear-height="1916" />
