### ISSUE TITLE
[Bug] No way to show only primary study in left side Studies List by default.

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#4530]
### Describe the Bug

There should be some way to show only primary study in left side Studies List by default. Currently all of the patients studies are shown by default.
![386817256-9fdf8ec2-5305-4bfd-b8d7-9324c0a54b32](https://github.com/user-attachments/assets/0a0b584b-e088-4e53-a79f-e1d99bd98500)

### Steps to Reproduce

1

### The current behavior

all of the patient's studies are shown

### The expected behavior

some way to show only primary study

### OS

win 11

### Node version

18.16

### Browser

chrome

**Comment by sedghi** [comment]
I think we should add a config, you are right

**Comment by ranasrule** [comment]
@sedghi I see that this has been marked as closed. How can we now show only primary study in left side Studies List?

**Comment by IbrahimCSAE** [comment]
> [@sedghi](https://github.com/sedghi) I see that this has been marked as closed. How can we now show only primary study in left side Studies List?

See here: https://github.com/OHIF/Viewers/blob/095ab7e91622d9459a1434e9608870ae608bd520/extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx#L49

Use the customizationService and set mode to primary

**Comment by ranasrule** [comment]
> > [@sedghi](https://github.com/sedghi) I see that this has been marked as closed. How can we now show only primary study in left side Studies List?
> 
> See here:
> 
> [Viewers/extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx](https://github.com/OHIF/Viewers/blob/095ab7e91622d9459a1434e9608870ae608bd520/extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx#L49)
> 
> Line 49 in [095ab7e](/OHIF/Viewers/commit/095ab7e91622d9459a1434e9608870ae608bd520)
>  const { mode: studyMode } = customizationService.getCustomization('PanelStudyBrowser.studyMode', { 
> 
> Use the customizationService and set mode to primary [@ranasrule](https://github.com/ranasrule)

Thanks for your reply @IbrahimCSAE 

so I simply change 

```
const { mode: studyMode } = customizationService.getCustomization('PanelStudyBrowser.studyMode', {
    id: 'default',
    mode: 'all',
  });
```
to 

```
const { mode: studyMode } = customizationService.getCustomization('PanelStudyBrowser.studyMode', {
    id: 'default',
    mode: 'primary',
  });
```

and then build ohif ?

**Comment by ranasrule** [comment]
well that didnt work....I have no idea how to achieve the desired result with the customizationService. Can you guys give a simpleton like me a simple step by step @IbrahimCSAE @sedghi ?

**Comment by ranasrule** [comment]
> > > [@sedghi](https://github.com/sedghi) I see that this has been marked as closed. How can we now show only primary study in left side Studies List?
> > 
> > 
> > See here:
> > [Viewers/extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx](https://github.com/OHIF/Viewers/blob/095ab7e91622d9459a1434e9608870ae608bd520/extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx#L49)
> > Line 49 in [095ab7e](/OHIF/Viewers/commit/095ab7e91622d9459a1434e9608870ae608bd520)
> > const { mode: studyMode } = customizationService.getCustomization('PanelStudyBrowser.studyMode', {
> > Use the customizationService and set mode to primary [@ranasrule](https://github.com/ranasrule)
> 
> Thanks for your reply [@IbrahimCSAE](https://github.com/IbrahimCSAE)
> 
> so I simply change
> 
> ```
> const { mode: studyMode } = customizationService.getCustomization('PanelStudyBrowser.studyMode', {
>     id: 'default',
>     mode: 'all',
>   });
> ```
> 
> to
> 
> ```
> const { mode: studyMode } = customizationService.getCustomization('PanelStudyBrowser.studyMode', {
>     id: 'default',
>     mode: 'primary',
>   });
> ```
> 
> and then build ohif ?

this no longer works in OHIF 3.10 the below code is no longer present in [Viewers/extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx](https://github.com/OHIF/Viewers/blob/095ab7e91622d9459a1434e9608870ae608bd520/extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx#L49)

> const { mode: studyMode } = customizationService.getCustomization('PanelStudyBrowser.studyMode', {
>     id: 'default',
>     mode: 'all',
>   });
