### ISSUE TITLE
[Bug] Labelmap to surface conversion does not update during segmentation editing

### ISSUE THREAD

**Issue by Vlad-C-Crisan** [OHIF/Viewers#4532]
### Describe the Bug

In v3.9.1 release, the Labelmap to Surface rendering of the segmentation in 3D does not update while editing a segmentation

### Steps to Reproduce

1. Go to https://viewer.ohif.org/segmentation?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.256467663913010332776401703474716742458
2. Load the segmentation
3. Choose 3D four up layout
4. Choose a preset that allows easy visualization of the 3D segmentation, e.g. CT-lung
5. Choose sphere brush from the editing tools and remove anything from the segmentation, e.g. the whole liver segmentation
6. Observe that nothing changes in the 3D rendering of the segmentation

### The current behavior

3D representation of the DICOM_SEG does not update during segmentation editing

### The expected behavior

On each segmentation change, the 3D surface representation reflects in real time the change

### OS

 OS X 10.15.7

### Node version

18.16.1

### Browser

Chrome 131.0.0

**Comment by sedghi** [comment]
Hmm i'm surprised, since i can see it does 

https://share.cleanshot.com/myr6hG7R
