### ISSUE TITLE
[Bug] Sychronizer error when exiting full screen viewer

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#4535]
### Describe the Bug

When exiting the full screen view I have the following error 

`CornerstoneViewportService.ts:449 error in event listener of type:  CORNERSTONE_ELEMENT_ENABLED TypeError: Cannot read properties of undefined (reading 'element')
    at s.getViewportElement (Synchronizer.js:191:44)
    at s.getEventSource (Synchronizer.js:182:20)
    at Synchronizer.js:175:38
    at Array.forEach (<anonymous>)
    at s._updateDisableHandlers (Synchronizer.js:174:19)
    at s.addSource (Synchronizer.js:70:14)
    at s.add (Synchronizer.js:52:14)
    at SyncGroupService.ts:160:22
    at Array.forEach (<anonymous>)
    at xt.addViewportToSyncGroup (SyncGroupService.ts:146:21)`

### Steps to Reproduce

Open close the full view

### The current behavior

error in console

### The expected behavior

should not throw error

### OS

Linux

### Node version

20

### Browser

Chrome

**Comment by salimkanoun** [comment]
I updated the bug description, the colormap part was an error in my synchronizer,

However the error is visible in the console (even it seems to have not so much import, better to kill bugs early)

**Comment by sedghi** [comment]
How can i go fullscreen? what api are you using? can you clarify?

**Comment by salimkanoun** [comment]
full screen is toogle one up, here a video capture from your demo server
[Screenity video - Nov 22, 2024.webm](https://github.com/user-attachments/assets/9287970c-7941-4c55-8eab-653871d7fe01)
