### ISSUE TITLE
[Bug] Fail to load MR image

### ISSUE THREAD

**Issue by arunvc** [OHIF/Viewers#4538]
### Describe the Bug

![image](https://github.com/user-attachments/assets/1b9c3930-7a43-450c-8ce7-afb124a955e4)

![image](https://github.com/user-attachments/assets/4769e934-3d50-4612-9033-6bba52d568c6)

[245C095C.zip](https://github.com/user-attachments/files/17839683/245C095C.zip)

### Steps to Reproduce

upload attach image to 
https://viewer.ohif.org/local

### The current behavior

image not displayed

### The expected behavior

render the image

### OS

Ubuntu 22

### Node version

18

### Browser

firefox and chrome

**Comment by sedghi** [comment]
Yeah i see it is not working

**Comment by sedghi** [comment]
The issue appears to be the range of voxels which are extremely small , hmmm 

<img src="https://uploads.linear.app/e0b640a9-3fd8-4513-bc84-af25921e5dc8/2ee38d14-86e1-4d57-8a18-8b601454577b/644b722d-160c-43b0-b7a2-2d004b6cd805?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UwYjY0MGE5LTNmZDgtNDUxMy1iYzg0LWFmMjU5MjFlNWRjOC8yZWUzOGQxNC04NmUxLTRkNTctOGExOC04YjYwMTQ1NDU3N2IvNjQ0YjcyMmQtMTYwYy00M2IwLWI3YTItMmQwMDRiNmNkODA1IiwiaWF0IjoxNzM0NTQ1MjI0LCJleHAiOjMzMzA1MTA1MjI0fQ.OJMpJAWyd9wvvwv5eqJ4FqVxJGbKdXPJTFsZ4yO3cxE " alt="CleanShot 2024-12-18 at 13.06.42@2x.png" width="2574" data-linear-height="2390" />

**Comment by sedghi** [comment]
related https://discourse.canceridc.dev/t/dicom-window-level-formula-adjustment/655
