### ISSUE TITLE
[Bug] Toogle 1 up on a fused viewport update SUV quantification to UH

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#4539]
### Describe the Bug

In TMTV mode toogling one up in a fused viewport makes SUV quantification impossible after returning to the HP.
Existing ROIs which were displaying SUV are also converted to UH

See video
[Screenity video - Nov 21, 2024 (1).webm](https://github.com/user-attachments/assets/a700bd74-7f93-4697-904e-6184d70a0f59)

### Steps to Reproduce

1. Go to https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.2.840.113619.2.290.3.3767434740.838.1526468636.966
2. Make a elipse on the PET viewport, it displays SUV value (ok for now)
3. Double click on a fused viewport to toogle up a fused view
4. Double click to exit the full view and return to the HP
5. The existing ROI became UH (SUV a removed)
6. All new ROI on a PET viewport will display UH and no SUV

### The current behavior

Loss of existing SUV value and can't quantify PET component

### The expected behavior

Quantification on the PET viewport shall be stable on SUV values

### OS

Linux

### Node version

20

### Browser

Chome latest

**Comment by sedghi** [comment]
Not able to reproduce it in our demo, maybe you have some custom logic?

https://share.cleanshot.com/zm0qWRRt

**Comment by salimkanoun** [comment]
Yeah because you toogle 1 up the PET viewport, do it again with a fused viewport and it will become UH
