### ISSUE TITLE
[Bug] DICOM JSON - Invalid DICOM file, expected header is missing

### ISSUE THREAD

**Issue by BrunoSkezi** [OHIF/Viewers#4543]
### Describe the Bug

Hello,

I am using your script "dicom-json-generator.js" to generate the configuration JSON file that allows the "viewer" to read my DICOM files.
I have carefully followed the instructions on the page https://docs.ohif.org/configuration/dataSources/dicom-json, but when I run the script, I encounter this error message for certain series: "Error: Invalid DICOM file, expected header is missing."

These DICOM files were downloaded from Google Cloud Healthcare, so they should normally be well-formed.
Would you have an explanation or a solution to prevent the script from completely halting? For instance, is there a way to skip only the problematic files without causing an error that stops the entire script?

### Steps to Reproduce

It is not possible to reproduce without DICOM file with error.

### The current behavior

I have carefully followed the instructions on the page https://docs.ohif.org/configuration/dataSources/dicom-json, but when I run the script, I encounter this error message for certain series: "Error: Invalid DICOM file, expected header is missing."

### The expected behavior

The expected behavior is for the script to run to completion and generate the JSON file.

### OS

Ubuntu

### Node version

10.2.5

### Browser

Brave v1.73.91

**Comment by sedghi** [comment]
Did you try drag and drop it in other viewers to see if it works?

**Comment by BrunoSkezi** [comment]
Excuse me, I just found the problem. My DICOM files were downloaded incorrectly and were corrupted.
