### ISSUE TITLE
[Feature Request] Support other target platforms for Docker builds

### ISSUE THREAD

**Issue by untoldone** [OHIF/Viewers#4548]
### What feature or change would you like to see made?

It might make sense to add arm64 and other platforms for docker images to support non-x86 target hosts

### Why should we prioritize this feature?

It is likely a trivial build tool chain addition via `docker buildx`? I could be wrong but skimming through the dockerfile I didn't see anything that felt overly risky but perhaps there's missing node module support?

**Comment by sedghi** [comment]
It does makes sense yes. We will triage it. I'm gonna close this in favor of an older issue [https://github.com/OHIF/Viewers/issues/4180](https://github.com/OHIF/Viewers/issues/4180)
