### ISSUE TITLE
[Bug] Connecting remote pacs as modality with Orthanc

### ISSUE THREAD

**Issue by Rajat-Imme** [OHIF/Viewers#4550]
### Describe the Bug

I want to connect SANTE PACS SERVER to my Orthanc running in docker container. My basic intention is to use SANTE PACS as modality for Orthanc so that data is available from SANTE to Orthanc PACS.

remote pacs will act as modality(client) and orthanc as server. This allows remote pacs to get/find/put data in orthanc

{
  "Name": "Orthanc inside Docker",
  "StorageDirectory": "/var/lib/orthanc/db",
  "IndexDirectory": "/var/lib/orthanc/db",
  "StorageCompression": false,
  "MaximumStorageSize": 0,
  "MaximumPatientCount": 0,
  "LuaScripts": [],
  "Plugins": ["/usr/share/orthanc/plugins", "/usr/local/share/orthanc/plugins"],
  "ConcurrentJobs": 2,
  "HttpServerEnabled": true,
  "HttpPort": 8042,
  "HttpDescribeErrors": true,
  "HttpCompressionEnabled": true,
  "DicomServerEnabled": true,
  "DicomAet": "ORTHANC",
  "DicomCheckCalledAet": false,
  "DicomPort": 4242,
  "DefaultEncoding": "Latin1",
  "DeflatedTransferSyntaxAccepted": true,
  "JpegTransferSyntaxAccepted": true,
  "Jpeg2000TransferSyntaxAccepted": true,
  "JpegLosslessTransferSyntaxAccepted": true,
  "JpipTransferSyntaxAccepted": true,
  "Mpeg2TransferSyntaxAccepted": true,
  "RleTransferSyntaxAccepted": true,
  "UnknownSopClassAccepted": false,
  "DicomScpTimeout": 30,
  "RemoteAccessAllowed": true,
  "SslEnabled": false,
  "SslCertificate": "certificate.pem",
  "AuthenticationEnabled": true,
  "RegisteredUsers": {
    "test": "test",
    "immersive": "immersive"
  },
  "DicomModalities": { "sante_pacs": ["SANTE", "192.168.1.102", 11122] },
  "DicomModalitiesInDatabase": false,
  "DicomAlwaysAllowEcho": true,
  "DicomAlwaysAllowStore": true,
  "DicomCheckModalityHost": false,
  "DicomEchoChecksFind": true,
  "DicomScuTimeout": 10,
  "OrthancPeers": {},
  "OrthancPeersInDatabase": true,
  "HttpProxy": "",
  "HttpVerbose": true,
  "HttpTimeout": 10,
  "HttpsVerifyPeers": true,
  "HttpsCACertificates": "",
  "UserMetadata": {},
  "UserContentType": {},
  "StableAge": 60,
  "StrictAetComparison": false,
  "StoreMD5ForAttachments": true,
  "LimitFindResults": 0,
  "LimitFindInstances": 0,
  "LimitJobs": 10,
  "LogExportedResources": false,
  "KeepAlive": true,
  "TcpNoDelay": true,
  "HttpThreadsCount": 50,
  "StoreDicom": true,
  "DicomAssociationCloseDelay": 5,
  "QueryRetrieveSize": 10,
  "CaseSensitivePN": false,
  "LoadPrivateDictionary": true,
  "Dictionary": {},
  "SynchronousCMove": true,
  "JobsHistorySize": 10,
  "SaveJobs": true,
  "OverwriteInstances": false,
  "MediaArchiveSize": 1,
  "StorageAccessOnFind": "Always",
  "MetricsEnabled": true,
  "DicomWeb": {
    "Enable": true,
    "Root": "/dicom-web/",
    "EnableWado": true,
    "WadoRoot": "/wado",
    "Host": "127.0.0.1",
    "Ssl": false,
    "StowMaxInstances": 10,
    "StowMaxSize": 10,
    "QidoCaseSensitive": false
  }
}

This is my orthanc configuration for docker

### Steps to Reproduce

Run Nginx-Orthanc docker compose 
Install SANTE PACS Server . You can download it from google link : https://santesoft.com/downloads.html

Run Sante PACS as administrator and set orthanc as peer server 
![Uploading Screenshot (9).png…]()

### The current behavior

On Orthanc UI http://localhost:8042/  data from sante_pacs should be available on orthanc[
![Screenshot (10)](https://github.com/user-attachments/assets/ba0db9a3-1438-4b79-a7e3-f4946899d54d)
](url)

### The expected behavior

E1126 12:14:37.846266          HTTP-15 OrthancException.cpp:62] Error in the network protocol: DicomAssociation - connecting to AET "SANTE": TCP Initialization Error: Operation now in progress (Timeout)

Connection timeout error

### OS

Windows 11

### Node version

22

### Browser

Chrome

**Comment by sedghi** [comment]
I'm not sure what is SANTE PACS SERVER? Why you need that? isn't Orthanc enough as your server?

**Comment by Rajat-Imme** [comment]
I want to access the pacs of lets's say some hospital and access its data within my orthanc server. 
I am trying to build functionality i which i can connect to pacs of other system.

So i was trying to make an peer to peer connection using orthanc. 

Is there any other way around?

**Comment by Rajat-Imme** [comment]
SANTE PACS is online free pacs. I am using SANTE locally to test SANTE server as modality for orthanc to imitate my aforementioned task.

**Comment by sedghi** [comment]
What happened? did you solve it? what is the solution?
