### ISSUE TITLE
[Bug] mnGrid Hanging protocol does'n work properly in 3.9.1

### ISSUE THREAD

**Issue by jrudascas** [OHIF/Viewers#4563]
### Describe the Bug

Initial hanging protocol called @ohif/mnGrid always is using 2x2 layout

### Steps to Reproduce

Go to https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.2.826.0.1.3680043.2.1125.1.11608962641993666019702920539307840&hangingprotocolId=@ohif/mnGrid

### The current behavior

Initial hanging protocol called @ohif/mnGrid always is using 2x2 layout

### The expected behavior

1x1 stage should be automatically activated if there is only 1 viewable serie

### OS

All SO

### Node version

16.17

### Browser

124.0.6367.60

**Comment by sedghi** [comment]
There is only one series in that study, that is the expected view. You can try it on a study that has more than one series
