### ISSUE TITLE
[Bug] GPU OOM

### ISSUE THREAD

**Issue by tunglt1810** [OHIF/Viewers#4565]
### Describe the Bug

I'm using viewer with local mode to view a MR series.
After switch to MPR mode, the screen was flashing and become a black screen. There was this log in console
```WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost```

![image](https://github.com/user-attachments/assets/772ee987-e782-4597-9e6a-72a51d58844c)

### Steps to Reproduce

1. Download this series: https://drive.google.com/file/d/16HItlHayUtlYWapwNMmyDeyLbJXb8TTJ/view?usp=sharing
2. Open viewer with local mode: https://viewer-dev.ohif.org/local
3. Upload dicom files
4. Select MPR layout ```Axial Primary```

### The current behavior

- Black screen
- Black viewport
- GPU OOM

### The expected behavior

- 3 viewports MPR show up with no black screen and black viewport

### OS

Window 11 Home

### Node version

22.11.0

### Browser

Chrome Version 131.0.6778.86 (Official Build) (64-bit)

**Comment by sedghi** [comment]
It works fine when i try it local drag and drop, and the file size is unlikely to cause oom. 

[https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)

<img src="https://uploads.linear.app/e0b640a9-3fd8-4513-bc84-af25921e5dc8/4a797b81-105b-4fec-be8e-1e81f60d7332/1c24022b-1d8e-4ecd-9f09-67448c02c80a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UwYjY0MGE5LTNmZDgtNDUxMy1iYzg0LWFmMjU5MjFlNWRjOC80YTc5N2I4MS0xMDViLTRmZWMtYmU4ZS0xZTgxZjYwZDczMzIvMWMyNDAyMmItMWQ4ZS00ZWNkLTlmMDktNjc0NDhjMDJjODBhIiwiaWF0IjoxNzMzMTk1MzQ1LCJleHAiOjMzMzAzNzU1MzQ1fQ.tUSpqBJvAC4ll8IRfurOOIC3lUnyAJa6Za2aV7AEZ6E " alt="CleanShot 2024-12-02 at 22.08.26@2x.png" width="3896" height="2206" />

**Comment by tunglt1810** [comment]
I'm trying drag and drop dicom images instead of select folder
Pls look at this error message
GPU memory increase from 1.5GB to max
![Screenshot 2024-12-03 111117](https://github.com/user-attachments/assets/47917f91-7800-4ef6-8f76-45142f64ee09)
After flash black
![Screenshot 2024-12-03 110631](https://github.com/user-attachments/assets/a8fd433d-5ea6-4f93-b169-ac023ef61565)
![Screenshot 2024-12-03 110654](https://github.com/user-attachments/assets/c341ef10-caa0-4d10-8105-528968008038)

**Comment by sedghi** [comment]
That is weird, what is the spec of your system?

**Comment by tunglt1810** [comment]
I'm using ASUS Zenbook 14 Flip OLED UP3404VA-KN038W (13th Gen Intel Core i5, Iris Xe Graphics)
16GB Ram 8GB GPU

**Comment by sedghi** [comment]
Can you try this trick [https://github.com/OHIF/Viewers/issues/3207](https://github.com/OHIF/Viewers/issues/3207)

**Comment by tunglt1810** [comment]
WOW. It works in my side

**Comment by sedghi** [comment]
Yes, it's the Intel Xe series. It's frustrating, but try updating your libraries and PC; it might fix the issue. We should report it to them.

**Comment by tunglt1810** [comment]
Thank you so much!
