### ISSUE TITLE
[Bug] Average blend mode renders volume viewports as a solid color

### ISSUE THREAD

**Issue by vlasn** [OHIF/Viewers#4567]
### Describe the Bug

When setting a Volume Viewport to the Average intensity blend mode (`3`), the viewport renders a solid color instead of the blended image

### Steps to Reproduce

1. Open one of the following example datasets in a browser (note the explicit hanging protocol - we want to force using volume viewports):
  - https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.5099.8010.217836670708542506360829799868&hangingprotocolId=mpr
  - https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5&hangingprotocolId=mpr
  - https://viewer.ohif.org/viewer?StudyInstanceUIDs=2.25.232704420736447710317909004159492840763&hangingprotocolid=mpr
2. run the following in the browser console:
  - `services.cornerstoneViewportService.renderingEngine.getViewport('mpr-axial').setBlendMode(3)`
3. Depending on whether the viewport reacted or not, mouseover the axial viewport and scroll slightly

### The current behavior

The viewport renders a solid color for the entire image

### The expected behavior

The viewport renders the image(s) in Avg. blend mode

### OS

macOS 15.1 (24B83)

### Node version

v18.20.5

### Browser

Chrome v131.0.6778.69

**Comment by xiaoxiao5** [comment]
@sedghi 
How did this problem come about? Because I don't want to update the version
