### ISSUE TITLE
[Not Bug] Beginner Question

### ISSUE THREAD

**Issue by charlejc** [OHIF/Viewers#4570]
### Describe the Bug

When I build my ohif viewer it doesn't seem in include the dicom web client and the get request to retrieve the list of studies doesn't ever seem to happen. The strange part is run I run yarn start dev, the dicom web client is included in the build and the get request to retrieve the list of studies from the dicom web client is included and executes as expected. 

The two commands I'm using are yarn run build and yarn start

### Steps to Reproduce

Clone the repository
yarn install
yarn run dev, and everything runs as expected
yarn run build
deploy code from dist folder to web root
open browser and navigate to web root.

### The current behavior

A black html page is presented. There are no errors in the network tab of Chrome's development tools. I don't think it's a CORS issue or an asset loading issue. I literally don't change anything

### The expected behavior

I would expect the files produced by the build process located in the dist folder should be able to be deployed to a properly configured server and get the same results as running the site locally via node.

### OS

Windows 11

### Node version

23.3.0

### Browser

Chrome Version 131.0.6778.86 (Official Build) (64-bit)

**Comment by sedghi** [comment]
see our deployment recipes [https://docs.ohif.org/deployment/build-for-production](https://docs.ohif.org/deployment/build-for-production)
