### ISSUE TITLE
[Bug] CustomizationService.ts:418 Uncaught TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by tumbochka** [OHIF/Viewers#4578]
### Describe the Bug

Hello!
I've updated to the latest 3.10.0-beta.18 locally and it is working. Then I deployed the same version to my server (there was 3.9-beta.101 before and it was working) and getting the following error on the app init:
```
CustomizationService.ts:418 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at _e.addReference (CustomizationService.ts:418:40)
    at _e.addReferences (CustomizationService.ts:447:14)
    at _e.init (CustomizationService.ts:132:10)
    at qt (App.tsx:141:24)
    at fo (react-dom.production.min.js:160:137)
    at Ds (react-dom.production.min.js:196:258)
    at Cl (react-dom.production.min.js:291:88)
    at Sc (react-dom.production.min.js:279:389)
    at gc (react-dom.production.min.js:279:320)
    at fc (react-dom.production.min.js:279:180)
```
I debugged a  bit and found that it tries to find an extension `"@ohif/extension-cornerstone.customizationModule.cornerstoneDicomUploadComponent"` wich is missing in the modules map.

![Image](https://github.com/user-attachments/assets/621ed375-0d92-4b56-ba5e-c2ef557ed515)

![Image](https://github.com/user-attachments/assets/bb76f44b-aefa-46b0-8b90-a56cfdde328f)

Also I noticed that this bug was mentioned in another issue: https://github.com/OHIF/Viewers/issues/4562#issuecomment-2514524058

How can I fix it?

### Steps to Reproduce

Just deploy the latest version of the app with `dicomUploadEnabled: true` .

### The current behavior

The app doesn't load and shows the error in the console.

### The expected behavior

The app should load and show a list of studies.

### OS

Deployed on Micsrosoft Azure

### Node version

20.12.2

### Browser

Chrome Version 131.0.6778.86

**Comment by sedghi** [comment]
check latest default config, and for the data source add the dicomUploadEnabled: true,

**Comment by tumbochka** [comment]
@sedghi thank you -- it started working after I removed 

```
 dicomUploadComponent:
    '@ohif/extension-cornerstone.customizationModule.cornerstoneDicomUploadComponent',
```
from the   `customizationService: {}`.
