### ISSUE TITLE
Draw All Reference Lines at once (get all points to draw all reference lines)

### ISSUE THREAD

**Issue by shivam-pandey-qss** [OHIF/Viewers#4581]
### What feature or change would you like to see made?

In OHIF, the ReferenceLines tool allows you to draw a slice line relative to the active viewport and relative to the active image in the viewport. I want to display all possible slice lines relative to the active viewport instead of just one. But I don’t understand how to get all possible coordinates. For drawing with the drawLineSvg function. Please tell me how can I get coordinate values for each image.
Path to tool in cornerstone: src/node_modules/@cornerstonejs/tools/dist/esm/tools/ReferenceLinesTool.js

### Why should we prioritize this feature?

Enhanced Visualization for Radiologists
Improved Diagnostic Accuracy

**Comment by sedghi** [comment]
You are talking about the crosshair tools, you can have it activated.

**Comment by shivam-pandey-qss** [comment]
no i am not talking about crosshair tools i am aware of that , i want something like all reference lines appear at once in inactive viewports crrently as user is scrolling corresponding reference lines getting on inactive viewport i want all refrence lines at once. Something like
![Image](https://github.com/user-attachments/assets/ee7eb287-cd3c-40e2-8b50-d3523939b774).
when refrence lines are getting draw coordinates are being calculated 
https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/tools/src/tools/ReferenceLinesTool.ts
which are coming from
 annotation?.data?.handles?.points 
i just want to get all the coordinates at once . Can you please guide me for that.
You can also refer to this video https://youtu.be/DJjewvdyH2k for more clearity on feature i am requesting.

 

> You are talking about the crosshair tools, you can have it activated.

**Comment by shivam-pandey-qss** [comment]
> You are talking about the grid tool then https://www.cornerstonejs.org/live-examples/overlaygrid

This example is close but not exact, i have pasted an image and a youtube video link for more understanding in my previous comment. What i am am looking for is to show all the refrence lines at once in inactive viewports user don't have to scroll for the reference lines, all the refrence lines should get draw automatically.Some other term for this feature is localizer as well. I am very close to achieve the feature but just stuck for the coordinates, i am not able to get all the coordinates at once in a single array.
This question is also asked in community https://community.ohif.org/t/referencelines-get-all-points-to-draw-all-reference-lines/898
with code samples.
