### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property '0' of null

### ISSUE THREAD

**Issue by MaherJendoubi** [OHIF/Viewers#459]
Hello,

I got this error when trying to open the following exam:

![image](https://user-images.githubusercontent.com/1798510/58041074-74880600-7b37-11e9-8417-89b535526094.png)

![image](https://user-images.githubusercontent.com/1798510/58040948-2115b800-7b37-11e9-9e8a-2495ee568c02.png)

**Comment by dannyrb** [comment]
@MaherJendoubi can you include a minimal reproduction, or the steps required to reproduce this issue from a vanilla install?

**Comment by MaherJendoubi** [comment]
I cloned the repo. I run yarn install and then yarn start.

**Comment by MaherJendoubi** [comment]
@dannyrb Step1: I am using nodejs version 10.15.3 and Google Chrome version 74.0.3729.157 (Build officiel) (64 bits).
Step2: I cloned the current repo using the master branch.
Step3: I cd the Viewers folder and I run yarn install and then yarn start.
Step4: I try to open the following exam
![image](https://user-images.githubusercontent.com/1798510/58042717-b2872900-7b3b-11e9-9b5f-185190972ec6.png)

Step5: I got the error.

**Comment by dannyrb** [comment]
Hmm.. I actually have the same version of Node and Chrome, but I am unable to reproduce the error:

![image](https://user-images.githubusercontent.com/5797588/58046654-f23a1a80-7b13-11e9-8ddf-23f07fbe6b98.png)

Let me try clearing out my node modules and using a fresh clone.

**Comment by dannyrb** [comment]
To double back. I cannot reproduce this using a fresh clone either. If you're able to create a reproduction, I can re-open this issue.

**Comment by MaherJendoubi** [comment]
I cannot reproduce it too. Thank you.
