### ISSUE TITLE
[Bug] Black window after trying to open segmentation side bar

### ISSUE THREAD

**Issue by Jeniamakarchik** [OHIF/Viewers#4591]
### Describe the Bug

After loading a segmentation with multiple labels in the OHIF viewer, and attempting to open the segmentation tool, the screen goes black.

Version 3.10.0-beta.18

### Steps to Reproduce

1. Upload dicom files, including DICOM-SEG
2. Load segmentation in the viewer. 
3. Open Segmentation tool side bar.

### The current behavior

After loading segmentation to OHIF viewer and trying to open segmentation toll got message and black screen: 
![Image](https://github.com/user-attachments/assets/9f543040-7462-4905-b97c-0abc5745ef06)

### The expected behavior

Segmentation tools side bar is opened as expected.

### OS

Windows 10

### Node version

-

### Browser

Brave 1.73.97 Chromium 131.0.6778.108

**Comment by sedghi** [comment]
If you share anonymized data we can look

**Comment by Jeniamakarchik** [comment]
@sedghi You can find two scans with corresponding segmentations in .zip file attached. Thanks!

**Comment by sedghi** [comment]
Thanks we will look, but most likely a export issue, what are you using to export to DICOM SEG. I'm pretty sure [HighDICOM](https://github.com/herrmannlab/highdicom) we have support for (since it follows the standard)
