### ISSUE TITLE
[Bug] Segmentation not loaded by default with initialSeriesInstanceUID

### ISSUE THREAD

**Issue by xbankov** [OHIF/Viewers#4593]
### Describe the Bug

Parameter `initialSeriesInstanceUID` is not loading the segmentation by default.

### Steps to Reproduce

1. Go to [https://viewer.ohif.org/viewer?StudyInstanceUIDs=61.7.93273854116647800470730671671118421206&initialSeriesInstanceUID=61.7.280176113695462316231376981119115690926](https://viewer.ohif.org/viewer?StudyInstanceUIDs=61.7.93273854116647800470730671671118421206&initialSeriesInstanceUID=61.7.280176113695462316231376981119115690926)

### The current behavior

Segmentation present but not loaded by default.

### The expected behavior

Segmentation loads by default.

### OS

Not applicable

### Node version

Not applicable

### Browser

Mozilla Firefox 133.0, Google Chrome 131.0.6778.139

**Comment by sedghi** [comment]
Hmmmm

**Comment by xbankov** [comment]
I have similar problems with the RT modality. I tried to look into it, and I realize in 3.7.0 it works as indented, and 3.8.0 is already not loading segmentations by default. 

I was also surprised to see some segmentations not going through segmentation Viewport when opened, as I setup logging and some segmentation printed logs, and some not. 

I cannot really see the difference for the segmentations files itself, only that they also have associated CT ref AND RTSTRUCT.

Is there some inherent logic that loads every associated files that could prevent Segmentation to load?

**Comment by xbankov** [comment]
Thanks for the fix!
