### ISSUE TITLE
[Bug] /ohif/segmentation tag viewer does not work

### ISSUE THREAD

**Issue by xbankov** [OHIF/Viewers#4595]
### Describe the Bug

Tag-browser won't open in /ohif/segmentation/ endpoint.

### Steps to Reproduce

1. Go to [https://viewer.ohif.org/segmentation?StudyInstanceUIDs=61.7.110976287009623783394893059131426578073](https://viewer.ohif.org/segmentation?StudyInstanceUIDs=61.7.110976287009623783394893059131426578073)
2. Click on Segmentation, three dots, and access tag-browser

### The current behavior

Tag-browser is not shown and an error occurs without explanation. 
(It does work in /ohif/viewer/ endpoint.)

### The expected behavior

Tag-browser appears

### OS

Not applicable

### Node version

Not applicable

### Browser

Mozilla Firefox 133.0, Google Chrome 131.0.6778.139

**Comment by sedghi** [comment]
Good catch

**Comment by xbankov** [comment]
Thanks! Amazing project. Thanks for the quick response
