### ISSUE TITLE
Does not run on windows

### ISSUE THREAD

**Issue by marcelvanherk** [OHIF/Viewers#46]
Hi,

setting up test for Conquest DICOM server. Installed latest meteor, set METEOR_PACKAGE_DIRS=C:\Users\marcel\Desktop\Viewers-master\Packages 

run meteor, fails (after a long time) with:

  While loading package momentjs:moment@2.15.2:
  error: Command failed:
  C:\Users\marcel\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.window
.x86_32\dev_bundle\bin\npm.cmd
  rebuild --update-binary
  node-pre-gyp ERR! Tried to download:
  https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node
v46-win32-ia32.tar.gz
  node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and
  node@4.6.1 (node-v46 ABI) (falling back to source compile with
  node-gyp)
  gyp ERR! configure error
  gyp ERR! stack Error: Can't find Python executable

It seems there are more dependencies? Please advise.

Marcel

**Comment by jongo** [comment]
Hi Marcel,

Try this:
1. move project to shorter path, for example "c:\Viewers-master"
2. update "METEOR_PACKAGE_DIRS" variable
3. Open browser at http://localhost:3000
4. Then try running it again
5. Hopefully, there will be error message in web browser if some component is missing. It was babel-runtime for me, so I reinstalled it via npm

Hope it helps...

**Comment by radicalrob** [comment]
Are you still having this problem?
