### ISSUE TITLE
Why the startup takes almost 30 seconds?

### ISSUE THREAD

**Issue by MaherJendoubi** [OHIF/Viewers#467]

**Comment by dannyrb** [comment]
@MaherJendoubi great question. I don't have experience profiling things like this, but we're always more than happy to accept pull requests that improve dev or production build performance.

**Comment by swederik** [comment]
Can you be more specific? Which command is taking a long time? Starting the application with `yarn start`?

**Comment by MaherJendoubi** [comment]
From the moment I run the yarn start to the load of the viewer using Google Chrome latest version, I count 30 secondes. I switched to Firefox 67 and it's loading faster 6 secondes.

**Comment by MaherJendoubi** [comment]
@dannyrb I measure it and profile it:

Using Firefox 67:

![image](https://user-images.githubusercontent.com/1798510/58128825-c3f23300-7c18-11e9-96cd-e78085553e56.png)

**Comment by MaherJendoubi** [comment]
@swederik 80% of the total load time is idle.

![image](https://user-images.githubusercontent.com/1798510/58129085-4aa71000-7c19-11e9-9bd7-3d7f3d29bdbe.png)

**Comment by dannyrb** [comment]
That could very well just be an issue with the dev server. I know we can improve load times with some good ol' code splitting, and heavier asset caching via a service worker. Feel free to PR any improvements in this area and I can take a closer look.

**Comment by MaherJendoubi** [comment]
I will try to investigate it. But this low performance is affecting the inner loop of development.

**Comment by EsrefDurna** [comment]
Hello Maher,
Webpack and babel does many things on runtime.
Such as pollyfill, treeshaking, transpile
So this start time for me is normal for developer environment dev build.

Try it for the build version thats a real performance measurement.

If you are interested there is webpack plugins such as bundle analyzers which analyze the runtime and bundle size which can point the problem

**Comment by dannyrb** [comment]
I believe this has largely been mitigated with the recent monorepo switch. More than happy to accept new issues; reproductions or insights from tools like webpack analyzer are always appreciated ^_^
