### ISSUE TITLE
Crash: viewer.ohif.org can't be launched

### ISSUE THREAD

**Issue by CelerityAbbottPC** [OHIF/Viewers#47]
Just tried the viewer http://viewer.ohif.org/, but it crashed - please check:

```
Errors prevented startup:

While selecting package versions:
error: No version of mrt:moment satisfies all constraints: @2.15.1
Constraints on package "mrt:moment":
* mrt:moment@2.15.1 <- top level

Your application has errors. Waiting for file change.
```

**Comment by emfol** [comment]
Try running `meteor npm install` inside the app you're trying to run (e.g., OHIFViewer or LesionTracker folder) and let's see how that goes.

**Comment by radicalrob** [comment]
It's fixed - there was a temporary issue with the VM hosting the code.
