### ISSUE TITLE
Sometimes cannot view studies with Safari 

### ISSUE THREAD

**Issue by tiimoS** [OHIF/Viewers#478]
When I open a study in the studylist using Safari, in 9 out of 10 cases, I see the loading spinner for about 10s, then the page is reloaded and I am back on the studylist with the safari error message: "the page was reloaded because a problem occurred. ". It works with other browsers such as Chrome or Firefox. There is no error message thrown in the client or server console. We tested with several Macs on different networks and it did not work properly for any of them. 
We experience the same issue with the official OHIF viewer (https://viewer.ohif.org/studylist), so it seems to be a general issue and not specific to our project only. The issue is observed with Safari 12.1 (did not test with other versions)
It's pretty difficult to debug since no real error message is thrown. As far as I could make out, the cornerstone call to loadAndCacheImage that should return the image as a promise, is never returned or maybe skipped. This snippet can be found in the ohif-viewerbase/client/components/imageViewerViewport/imageViewerViewport.js
`let imagePromise;
    try {
        imagePromise = cornerstone.loadAndCacheImage(imageId);
    } catch (error) {
        OHIF.log.info(error);
        if (!imagePromise) {
            errorLoadingHandler(element, imageId, error);
            return;
        }
    }`
Not sure if that's really the root cause though
Any help would be highly appreciated

**Comment by dannyrb** [comment]
Thanks for the report @tiimoS! Hopefully someone else that is experiencing the same issue can chime in with more information. Unfortunately, I don't have Mac/iOS device to verify this behavior, and there's not enough information available for me to troubleshoot this as-is.

**Comment by pieper** [comment]
I was able to replicate this too on Safari Version 12.0.3 (14606.4.5) with the current https://viewer.ohif.org/studylist and doubleclicking on the first study in the list.  It's an extra pain to debug because when the page reloads it closes the web inspector/console.

**Comment by dannyrb** [comment]
@swederik, do we have access to something like https://www.browserstack.com/ so I can try to figure out what's going on here? If anyone else is able to dig in, I would appreciate help/guidance on this one ^_^
