### ISSUE TITLE
Loading data from CD and DICOM dir locally

### ISSUE THREAD

**Issue by mbbs** [OHIF/Viewers#483]
I was wondering if there OHIF supports reading DICOM files from local directories or CD. If not I am willing to work on it. I can come up with a design and propose it and then implement it. Only thing I would need is some pointer to where to start from

**Comment by dannyrb** [comment]
👋 Hi @mbbs, I think this is something we would eventually like to see support for. Most/all of our DICOM data comes in through a `cornerstone image loader`. Our specific implementation is the `cornerstoneWADOImageLoader`. There is an example of it loading a file from the local system here:

 https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

A simple/good MVP would likely add a toolbar button that allows file/directory selection. Once selected, we load and cache each image, and add the study(ies) to the current viewing session. I think the biggest hurdle here, if we're not going to persist the images to some sort of web accessible storage, will be memory limitations and informing the user appropriately when they're reached.

**Comment by swederik** [comment]
You can use the local viewer (at `/local`) where you can drag/drop files or use the Browser's file selector. If you want to send a PR to add a folder selector option that would also be fine, but I think that's Chrome-only: https://viewer.ohif.org/local

**Comment by anarnoli** [comment]
Hello @swederik Is there anyway to push File Base64 directly to Viewer rather than using `/local` for file selection option?
