### ISSUE TITLE
Reading is not same. on the image and measurement table.

### ISSUE THREAD

**Issue by Malik-Adil** [OHIF/Viewers#485]
Measurement tool shows different measurement and the table show different
![Screenshot from 2019-05-24 12-08-26](https://user-images.githubusercontent.com/20414066/58309165-e0f75380-7e1c-11e9-85ab-929bc7a30ffc.png)

**Comment by evren217** [comment]
@Malik-Adil Thanks for the report.

This is actually known issue and fixed by this [PR](https://github.com/cornerstonejs/cornerstoneTools/pull/917). @dannyrb could you please merge it?

**Comment by Zaid-Safadi** [comment]
Would using the new “completed” event in v3 fix this as well? 
I remember one of the reasons I added this event to CST v2 is to fix the measurement window being out of sync

**Comment by evren217** [comment]
This issue was already fixed on cornerstone-tools v3.9.4, so cornerstone-tools was bumped to the latest version in OHIF
