### ISSUE TITLE
Study Search Broken for Google Healthcare API Integration

### ISSUE THREAD

**Issue by dzelemba** [OHIF/Viewers#489]
OHIF is appending * to all QIDO request parameters, but this isn't supported yet by the Google Cloud Healthcare API (https://cloud.google.com/healthcare/docs/dicom#search_transaction).

**Comment by dannyrb** [comment]
@dzelemba, my guess would be that this is something we won't have the bandwidth to fix for `v1.x` (but would be willing to review/merge a pull request for). It is good to be aware of this as we add support in `v2.x`

**Comment by dannyrb** [comment]
I believe this has been resolved with the latest healthcare adapter merge. There is also a new configuration property to enable fuzzy searching if the target DICOMWeb implementation supports it.
