### ISSUE TITLE
"Invalid Date" shows up in Study List after sorting

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#492]
![Screenshot 2019-05-28 14 11 02](https://user-images.githubusercontent.com/607793/58476920-84fd3980-8152-11e9-93d1-aaf404314f2b.png)

Not sure what's going on here.

**Comment by dannyrb** [comment]
@biharck, an easy way to reproduce this is to sort/unsort by the date. Date's become invalid.

**Comment by biharck** [comment]
PR created https://github.com/OHIF/Viewers/pull/495
