### ISSUE TITLE
(empty) should show up in the Study List when Patient Name is missing

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#494]
This is how it appears in the Meteor version. It should do the same in the latest version.

![Screenshot 2019-05-28 14 33 18](https://user-images.githubusercontent.com/607793/58479338-600bc500-8158-11e9-9582-8507fe9114d1.png)

**Comment by biharck** [comment]
Fixed at https://github.com/OHIF/Viewers/pull/503

**Comment by biharck** [comment]
The changes were moved to react-viewwerbase project and it was fixed at https://github.com/OHIF/react-viewerbase/pull/86
