### ISSUE TITLE
MRI issue: Image numbering != position

### ISSUE THREAD

**Issue by CarnivorousRex** [OHIF/Viewers#50]
Output from MRI with parallel imaging can result in a stack of images that does not scroll in an orderly manner from one position to the next.  

It seems the default viewer behavior is to show the images sequentially by image number.  Is there any way to default to scrolling by position?  

Along the same lines, once ordered by position, can we reverse the stack?

**Comment by radicalrob** [comment]
Currently, we are only sorting by imageNumber.  That code is here:   
Packages/ohif-viewerbase/client/lib/createStacks.js.  You would need to alter image.sortBy.  We plan to offer a way to override this without re-writing it, but haven't gotten around to doing it yet.

**Comment by matthiasg** [comment]
while on this topic, is it possible to get an event when scrolling within an image to implement synchronous scrolling across aligned series ?

**Comment by dannyrb** [comment]
Unfortunately this issue has grown stale, and with the release of our most recent major version, it is unlikely that we will have the bandwidth to address this issue for our `v1.x` branch. 

If you find that this feature has not yet been implemented in our `master` branch, you are more than welcome to create a [GitHub Issue](https://github.com/OHIF/Viewers/issues/new) to request or discuss it. If you're curious to see what we have planned in the near future, you can [check out our roadmap](https://ohif.canny.io/), and [read our docs](https://docs.ohif.org/).

@matthiasg, this is an older issue. Your question will receive more attention in a new issue.
