### ISSUE TITLE
Loading thousands of dicom files caused the broswer page to crash.

### ISSUE THREAD

**Issue by ierye** [OHIF/Viewers#501]
On Stand-alone Viewer, when loading thousands of dicom files, the browser crashes and then will reload the page. I think that it may be the browser is loading too many dicom files and the memory is not enough to cause it to crash. Is there any solution?

**Comment by swederik** [comment]
How big is the study? How big are the display set stacks? Cornerstone's cache size limit should prevent too many from being loaded.

**Comment by swederik** [comment]
When you see the Error loading image and you open the JavaScript console, what does the error say?

**Comment by ierye** [comment]
The Viewers version I used is v1 with Meteor.
When then browser crashed, the console log "Uncaught TypeError" or "Uncaught RangeError", then the devTools crashed immediately and alert "Debugging connection was closed. Reason: Render process gone."

![http://bosdev.liangyihui.net/temp/1559197008.JPG](http://bosdev.liangyihui.net/temp/1559197008.JPG)

![http://bosdev.liangyihui.net/temp/1559196810.JPG](http://bosdev.liangyihui.net/temp/1559196810.JPG)

![http://bosdev.liangyihui.net/temp/1559196723.JPG](http://bosdev.liangyihui.net/temp/1559196723.JPG)

**Comment by swederik** [comment]
Looks like something is broken related to the web worker task?

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/b468ad706276daa4c3cf6aefb3beca924a588b61/src/webWorker/webWorker.js#L81

For some reason msg.data appears empty? (possibly due to that RangeError).

"Arraybuffer allocation failed" is a new one for me. How much memory do you have on your computer?

**Comment by ierye** [comment]
Windows 10
8GB RAM
i7-7550U

When the browser crash, the usage of memory only 42%.

**Comment by ierye** [comment]
I updated Chrome to the latest version 74.0.3729.169, the problem remains.
And I found that the problem is more likely on Windows computer.
On macOS system, it likely doesn't occur.

**Comment by ierye** [comment]
This is the [testDICOMs.json](https://bosdev.liangyihui.net/testDICOMs.json).
I update the Viewers to the latest version (v1.x), and the problem remains.
On windows computer win10 system, chrome v74.0.3729.169, the browser would crash when load more than half amount of dicom files, and sometimes there is no error message console log.

**Comment by dannyrb** [comment]
Unfortunately, we no longer have as much bandwidth to support `v1.x` issues. As this issue is a little older, I'm going to close it for now. Best of luck on resolving your issues -- I know that memory issues can be particularly irksome and annoying.
