### ISSUE TITLE
Study list should launch viewer on single click

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#506]
Double clicking to open a study is a common desktop pattern, but it feels out of place on web. It also makes it difficult for touch devices to open the study as `double tap` is often used to zoom in on the tapped area.

Ideally, a single tap or click should navigate the user to the viewer.

**Comment by pieper** [comment]
Agreed.  Even on desktop systems the doubleclick is not obvious to some people, and I'd suggest either open the study with a single click, or else on hover, bring up a button to open the study.

**Comment by swederik** [comment]
I think originally it was double click because you could select multiple studies with shift or ctrl, and then export or associate them to a timepoint. We probably want that functionality again.

**Comment by pieper** [comment]
In that case, probably we should have something like a select checkbox and an action menu (effectively what Dropbox and google drive have).  Then doubleclick is just a shortcut for select and open.

**Comment by biharck** [comment]
Fixed at https://github.com/OHIF/react-viewerbase/pull/87

**Comment by dannyrb** [comment]
This will be available in the next release that bumps `react-viewerbase` version. If we want support for selecting multiple studies, please feel free to create a new issue 🚀
