### ISSUE TITLE
Measurement's table "re-label" overflows screen and other issues

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#508]
- [ ] Placement should be centered
- [ ] Autofocus on search input
- [ ] Text searching always returns 0 results
- [ ] Should maybe appear w/ an overlay or inside a small container? When overlayed directly over a noisy area, it can make it hard on the eyes
- [ ] z-index issue (`options` in top right will appear over top of modal)

While I really like this UI for when we don't have the side panel open, or we're jumping into the flow from the bidirectional tool; I do think we can improve the UX of the experience for sidepanel edits. This may be worth discussing if someone decides to pick up this issue.

![kSbJyTjZyS](https://user-images.githubusercontent.com/5797588/58611600-adce1d80-827d-11e9-9ff7-3718eb6e1c15.gif)

**Comment by evren217** [comment]
That select tree dialog is actually supposed to be in 2 column (like the one in v1.x) when multiple column is supported in [react-viewerbase](https://github.com/OHIF/react-viewerbase), so its height will be smaller then.
