### ISSUE TITLE
Study list filtering should not require "enter"

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#509]
Currently, to filter the study list, you need to hit "enter" after supplying a value.

IE. Patient Name --> "Bobby B" --> *\*Enter\**

Not all tablet/mobile devices easily support this. A better user experience might be a 250ms debounced application of the filter, triggered on value change. Hitting enter, or the field losing focus could shortcut the debounce. If a new request is dispatched before the first finishes, it should be cancelled using a cancellation token.

**Comment by swederik** [comment]
Fixed after updating react-viewerbase here (https://github.com/OHIF/Viewers/commit/8a4306d1b04ae7346e5fd4ae0c37c818275835a5)
