### ISSUE TITLE
Not able to run server.

### ISSUE THREAD

**Issue by PritamUpadhyay** [OHIF/Viewers#51]
According to [Running and building the Standalone Viewer]( https://github.com/OHIF/Viewers/wiki/Running-and-building-the-Standalone-Viewer), I followed all the steps to deploy Server, Still I am not able to get it started.  Can anyone explain me what am I missing here?

**Things I tried**
1. Installed meteor using `sudo curl https://install.meteor.com/ | sh`
2.  `cd /home/systemuser/Viewers-master` -> meteor npm install **[Here, system crashed.]**

**I saw** [Having trouble getting started..](https://github.com/OHIF/Viewers/issues/2), but i am not able to find this file -> `./bin/localhostOrthanc.sh`. neither this -> `./setupLocalOrthanc.sh`.

Any help would be appreciated very much!
Thanks,

**Comment by PritamUpadhyay** [comment]
Can anyone please help me regarding this issue?

**Comment by radicalrob** [comment]
This area is for bug report and feature requests.  For this sort of help, you should post your question here: https://groups.google.com/forum/#!forum/cornerstone-platform

Also, I recommend including more details about what you tried and what errors you got.

**Comment by PritamUpadhyay** [comment]
Thanks. @radicalrob .
