### ISSUE TITLE
Lossy JPEG is not decompressed properly

### ISSUE THREAD

**Issue by vicOnGit75** [OHIF/Viewers#512]
DICOM image with Color Presentation YBRFull422 and lossy jpeg transfer syntax produces wrong iges after decompression- ~ gray biased to green/blue

**Comment by dannyrb** [comment]
Can you provide steps to reproduce this issue? Can you stand up a minimal example using a separate GitHub repository, CodeSandbox, or Codepen?

**Comment by vicOnGit75** [comment]
Was reproduced vs osimis/orthanc  docker container after uploading few US (Echo) DICOM images with mentioned compression.Checked that there is no problem with non compressed syntax or with lossless Jpeg( gray images)

Screenshots attached below:

![target](https://user-images.githubusercontent.com/13784498/58809792-45888e80-8625-11e9-8abd-fd48a8921a87.jpg)
![actual](https://user-images.githubusercontent.com/13784498/58809823-51745080-8625-11e9-8181-2f97e7531242.jpg)

**Comment by vicOnGit75** [comment]
Looks like the problem was on server side- image arrived already decompressed.
Sorry for misleading.

**Comment by swederik** [comment]
Glad you have sorted the issue out! Did you mean to re-open this?

**Comment by vicOnGit75** [comment]
I didn't mean to reopen it- looks that the problem is not on OHIF side...
Thanks,
Victor

**Comment by jeffmartina** [comment]
@vicOnGit75 Can you elaborate how you solved the issue it on Orthanc? Also is it a similar issue to what I encountered in this post? https://github.com/OHIF/Viewers/issues/1361
