### ISSUE TITLE
React Viewer demo does not run in IE11

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#515]
https://docs.ohif.org/demo

`Object.assign` is not available. We likely need to supply appropriate polyfills, and double check that babel transpilation is for the correct targets.

**Comment by swederik** [comment]
It looks like at least one Object.assign failure is coming from https://github.com/cornerstonejs/cornerstoneTools. (based on brief testing with https://www.browserling.com/browse/win/vista/ie/9/https%3A%2F%2Fdocs.ohif.org%2Fdemo%2F)

**Comment by dannyrb** [comment]
- [ ] Add appropriate polyfills to demo site
- [ ] Make sure `cornerstoneTools` is transpiling for the correct targets
    - [ ] Update `cornerstoneTools` examples to use IE 11 safe code and polyfills (notably, arrow functions)

**Comment by dannyrb** [comment]
This has largely been fixed. There are still some performance issues, but I intend to add a section on browser support to clarify our stance on browser specific issues.
