### ISSUE TITLE
OHIFViewer-meteor : docker image is not build using Source dockerfile.

### ISSUE THREAD

**Issue by viss3595** [OHIF/Viewers#516]
Hello Team,
Is there any stable dockerfile for Meteor OHIFViewer. so i can compose with my changes.

**Comment by swederik** [comment]
Hi there,

Everything from the Meteor version is on the v1.x branch. Here is the dockerfile: https://github.com/OHIF/Viewers/blob/v1.x/dockerfile

Hope that helps!

**Comment by viss3595** [comment]
Thank You @swederik 

Is there any changes in docker-compose.yml file. Because i need to build OhifViewer with my changes with create .tar file. and I use  docker-compose up command. so can u suggest me what's changes in my case. 

**docker-compose.yml**

version: '3.6'
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  viewer:
    image: ohif/viewer:latest  ########[This line is pull ohifviewer image from docker hub]########
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/ohif
    extra_hosts:
      - "pacsIP:192.168.0.2"
    volumes:
      - ./dockersupport/app.json:/app/app.json

**Comment by dannyrb** [comment]
https://cloud.docker.com/u/ohif/repository/docker/ohif/viewer

> ATTENTION: We have recently released a new major version of The OHIF Viewer. It has not yet reached feature parity with the previous major version. Please use the v1.x tag for the most recent Meteor version of our image. Use v0.x.x.x or latest tags for the newest React version of our image.

`:latest` tag is for `react`
`:v1.x` would be latest stable `meteor`

**Comment by viss3595** [comment]
Hello @dannyrb 

` https://cloud.docker.com/u/ohif/repository/docker/ohif/viewer ` is unable to open to open URL its getting 404 Error.
