### ISSUE TITLE
CORS error when open studies (orthanc1.8 + Nginx)

### ISSUE THREAD

**Issue by JustLoveIt** [OHIF/Viewers#517]
Hello all,
I used orthanc 1.8 as DICOM Server, and when I yarn start OHIP/Viewers localhost:5000 ,get an error:
![image](https://user-images.githubusercontent.com/12275035/58862149-9ca06900-86e2-11e9-9aca-20eefa883f0e.png)
According to the [instructions from orthanc book:]( https://book.orthanc-server.com/faq/same-origin.html ), I use Nginx to branch the REST API of Orthanc as a reverse proxy. It can load the list page now, but when loading images I got another similar error:
![image](https://user-images.githubusercontent.com/12275035/58862609-a1195180-86e3-11e9-848f-91b484455209.png)
How to solve this problem? Thank you very much.

**Comment by JustLoveIt** [comment]
PS: OHIFViewers-meteor is beyond this error.

**Comment by swederik** [comment]
That doesn't look like a CORS error. That looks like it's throwing an error 400 Bad Request on your DICOMWeb server, and the error itself doesn't have the CORS headers. Can you make the same call from a terminal?

**Comment by dannyrb** [comment]
Have you tried: https://docs.ohif.org/essentials/data-source.html#set-up-a-local-dicom-server

**Comment by dannyrb** [comment]
FWIW, we're now using the `react` proxy tag to simplify local `orthanc` dev. We also have several guides up to assist. If a specific guide or the current default setup is failing, please provide steps to reproduce and I can action this.
