### ISSUE TITLE
 Error: GetStudyMetadata: For some reason we could not retrieve the study's metadata for xxxxxxxxxx

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#519]
I have OHIF viewer connected to Orthanc PACS and I randomly get the following error when opening a study using a url like **http://200.85.104.19/StudyViewerOH.aspx?studyid=xxxxxxxxxx**

Error>>>  **Error: GetStudyMetadata: For some reason we could not retrieve the study's metadata for xxxxxxxxxx**

I have tried connecting via both DIMSE and DICOMWEB but the same issue occurs regardless

**Comment by dannyrb** [comment]
Can you provide a minimal reproduction of this error in codepen, codesandbox, or a repository? Do you have any additional information you can provide?

Do requests to Orthanc in any other capacity work as expected? Do you see any console errors? Are you using some kind of proxy to prevent CORS errors?

**Comment by ranasrule** [comment]
> 
> 
> Can you provide a minimal reproduction of this error in codepen, codesandbox, or a repository? Do you have any additional information you can provide?
> 
> Do requests to Orthanc in any other capacity work as expected? Do you see any console errors? Are you using some kind of proxy to prevent CORS errors?

thank you for your reply.Other viewers are opening all studies just fine. Im not using a proxy. Console shows following errors
![Capture](https://user-images.githubusercontent.com/5023419/58932767-7a5c2900-877e-11e9-82f9-a550289341be.PNG)

**Comment by swederik** [comment]
I guess you are connecting to your PACS from the Meteor server side. What do you see in the server console when this happens?

**Comment by ranasrule** [comment]
> 
> 
> I guess you are connecting to your PACS from the Meteor server side. What do you see in the server console when this happens?

I'm not sure I understand the question. Could you please guide me a bit as to what you want me to do?

**Comment by swederik** [comment]
Look at the terminal that is running the OHIF application and copy the logs (if any) that appear when this happens in the viewer.

**Comment by ranasrule** [comment]
> 
> 
> Look at the terminal that is running the OHIF application and copy the logs (if any) that appear when this happens in the viewer.

OHIF is running as a windows service on my machine so there is no terminal

**Comment by swederik** [comment]
OK, then look at the logs for the windows service? Surely Windows stores logs for services somewhere.

**Comment by ranasrule** [comment]
> 
> 
> OK, then look at the logs for the windows service? Surely Windows stores logs for services somewhere.

found nothing in the windows service logs but found these logs in the **\OHIF Viewer\bundle\daemon** folder
[ohifviewerserver.out.log](https://github.com/OHIF/Viewers/files/3255772/ohifviewerserver.out.log)
[ohifviewerserver.wrapper.log](https://github.com/OHIF/Viewers/files/3255773/ohifviewerserver.wrapper.log)
[ohifviewerserver.err.log](https://github.com/OHIF/Viewers/files/3255774/ohifviewerserver.err.log)

**Comment by swederik** [comment]
OHIF is saying that the response from your PACS is an empty string. If you make the same DICOMWeb call to the PACS in another manner, does that work? e.g. via cURL or Python?

**Comment by ranasrule** [comment]
> 
> 
> OHIF is saying that the response from your PACS is an empty string. If you make the same DICOMWeb call to the PACS in another manner, does that work? e.g. via cURL or Python?

Can you tell me the exact call to nake?

**Comment by ranasrule** [comment]
> 
> 
> OHIF is saying that the response from your PACS is an empty string. If you make the same DICOMWeb call to the PACS in another manner, does that work? e.g. via cURL or Python?

ok I just tried via cURL and the result is the same

**Comment by swederik** [comment]
I meant you should try requesting the same study metadata from PACS with cURL to make sure the PACS is responding properly.

**Comment by ranasrule** [comment]
> 
> 
> I meant you should try requesting the same study metadata from PACS with cURL to make sure the PACS is responding properly.

yes Im able to fetch study metadata just fine with cURL

**Comment by dannyrb** [comment]
Unfortunately, we don't have the bandwidth to continue support of issues related to `v1.x` and this issue has gone a couple of weeks without activity. I'm going to close it for now -- best of luck on your issue, and sorry we couldn't resolve this.
