### ISSUE TITLE
Add version and diagnostic information, accessible at all routes

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#529]
To make it easier to report issues, we should supply a visible version number and any other pertinent diagnostic information in the UI.

**Comment by swederik** [comment]
We should add the About modal that was in the Meteor version and add this information to it in a table. See viewer-legacy.ohif.org

**Comment by biharck** [comment]
I did some changes at https://github.com/OHIF/react-viewerbase/pull/98.
Since ReactJS is only working on the client side, there is no way to use child processes to get git revision and other kinds of stuff.

Waiting react-viewerbase be bumped so that I can add it to the Viewers.

**Comment by biharck** [comment]
Waiting for the PR https://github.com/OHIF/Viewers/pull/567 gets approved.

**Comment by dannyrb** [comment]
👟 🤖 💨
