### ISSUE TITLE
I'm trying to connect dcm4chee 2.18.3 to OHIF

### ISSUE THREAD

**Issue by JoshNull** [OHIF/Viewers#53]
How can I setup ae Title for OHIF? 

We can't echo OHIF but we can ping from dcm4chee. 

As of now, we have an instance of DCM4CHE ver 5 running and connected to OHIF. This is working fine. However, we need to connect OHIF to an existing DCM4CHE ver 2. The DCM4CHE ver 5 is on the same ip as OHIF, while DCM4CHE ver 2 is on a different one. 

This is how we tried to edit the DIMSE file. We read somewhere that DCM4CHE ver 2 doesn't support QIDO and that we might have to rely on a DIMSE connection.

{
  "servers": {
    "dicomWeb": [
      {
        "name": "DCM4CHEE",
        "wadoUriRoot": "http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/wado",
        "qidoRoot": "http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs",
        "wadoRoot": "http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs",
        "qidoSupportsIncludeField": false,
        "imageRendering": "wadouri",
        "requestOptions": {
          "auth": "admin:admin",
          "logRequests": true,
          "logResponses": false,
          "logTiming": true
        }
    }],
    "dimse": [{
      "name": "DCM4CHEE_DIMSE",
      "wadoUriRoot": "http://192.168.88.143:8080/wado",
      "requestOptions": {
        "auth": "admin:admin",
        "logRequests": true,
        "logResponses": false,
        "logTiming": true
      },
      "peers": [
        {
          "host": "192.168.88.143",
          "port": 11112,
          "aeTitle": "OHIFDCM",
          "default": true,
          "supportsInstanceRetrievalByStudyUid": false
        },
        {
          "host": "0.0.0.0",
          "port": 11112,
          "aeTitle": "DCM4CHEE",
          "default": true,
          "server": true
        }
      ]
    }]
  },
  "defaultServiceType": "dimse",
  "public": {
    "verifyEmail": false,
    "ui": {
        "studyListFunctionsEnabled": true
    }
  }
}

**Comment by radicalrob** [comment]
I think you have your DICOM peers reversed.  Try putting OHIFDCM with 0.0.0.0 and double check the port (is it really 11112?)

**Comment by swederik** [comment]
Did this work? Can I close the issue?

**Comment by eanzuresb** [comment]
Hi, i'm having the same issue, I can get connect dcm4chee 2.18.13 to ohif viewer, can you tell me if you did it? Cheers!

**Comment by zacrify** [comment]
Same here
Could you elaborate how to config OHIF for existing dcm4chee 2.18.3
