### ISSUE TITLE
Exception tracking for viewer.ohif.org

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#530]
We should provide a modified build that adds exception tracking, using [rollbar](https://rollbar.com/) or [sentry](https://sentry.io/welcome/), so we can catch exceptions raised on `viewer.ohif.org`. This would allow us to collect information on exceptions, their frequency, and the steps required to reproduce them; even if end users do not readily report these issues.

**Comment by swederik** [comment]
We used Rollbar for Crowds Cure Cancer, here is how it was added https://github.com/crowds-cure/cancer/search?utf8=%E2%9C%93&q=rollbar&type=

A Travis job pushed the source maps to rollbar on each release.
