### ISSUE TITLE
Where is config/oidc-googleCloud.json

### ISSUE THREAD

**Issue by Twinber** [OHIF/Viewers#536]
Hi!
I try to connect whit Google Cloud Healthcare.
I read this docs https://docs.ohif.org/connecting-to-image-archives/google-cloud-healthcare.html#
But where is config/oidc-googleCloud.json?

**Comment by dannyrb** [comment]
There is a note at the top of that page:

> ATTENTION: The original documentation for this integration lives in the legacy version 1 Meteor documentation. You can find it here. These docs will mirror the Meteor documentation until our React implementation has been updated to work with Google Cloud Healthcare.

Clicking `find it here` takes you to: https://docs.ohif.org/history/v1/connecting-to-image-archives/google-cloud-healthcare.html

All code for `v1` (the Meteor version) of the OHIF Viewer lives on this branch:

https://github.com/OHIF/Viewers/tree/v1.x

The file you're looking for lives here:

https://github.com/OHIF/Viewers/blob/v1.x/config/oidc-googleCloud.json
