### ISSUE TITLE
Question: Branch for Google Cloud Helthcare

### ISSUE THREAD

**Issue by Twinber** [OHIF/Viewers#537]
Please can you tell me, what is the correct branch to test the current version compatible with google cloud Healthcare?

**Comment by swederik** [comment]
Hi there,

Sure, it's the `v1.x` branch here: https://github.com/OHIF/Viewers/tree/v1.x

We are working on adding that stuff back in so it can work with the latest version as well (https://github.com/OHIF/Viewers/pull/523).

**Comment by Twinber** [comment]
Ok thanks, but I want to work with the rea version.
Which branch should I use?

**Comment by swederik** [comment]
That is not currently possible, the Google Cloud Healthcare adapter has not been integrated with the React version yet. That work is ongoing, you can check the progress in this PR: https://github.com/OHIF/Viewers/pull/523.

You'll have to use the Meteor version for now.
