### ISSUE TITLE
how to disable the text of length in drawing

### ISSUE THREAD

**Issue by vimalgupta** [OHIF/Viewers#542]
Hi

How can we disable the length text while annotating length like 128.89mm text.

**Comment by dannyrb** [comment]
The only way to do this currently would be to modify the `@ohif/extension-cornerstone` and it's use of `react-cornerstone-viewport`. You would need to modify `availableTools` to pass in options for the `lengthTool` to always have the textbox disabled.

Another approach would be using the stored reference to the `enabledElement` and call any tool option commands directly via `cornerstoneTools`.

Finer control for things like this in our extension and `react-cornerstone-viewport` via options we can pass in to the extension are something I'm interested in pursuing and/or accepting PRs for.
