### ISSUE TITLE
Microscopy extension viewport resizing incorrectly

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#550]
It looks like the @ohif/extension-microscopy Viewport is resizing incorrectly when the sidebars are changed. It appears to be resizing in CSS but not calling a redraw of the rendering on the Canvas. Note how the actual cell aspect ratios are being changed. This is not what should be happening.

![MicroscopyStretch](https://user-images.githubusercontent.com/607793/59427889-0c49de80-8ddc-11e9-863e-c24f2ce92371.gif)

**Comment by biharck** [comment]
There are two PRs to fix that.
https://github.com/dcmjs-org/dicom-microscopy-viewer/pull/30
https://github.com/OHIF/Viewers/pull/571

**Comment by biharck** [comment]
waiting for a new version from Microscopy in order to close this issue.

**Comment by Malik-Adil** [comment]
> It looks like the @ohif/extension-microscopy Viewport is resizing incorrectly when the sidebars are changed. It appears to be resizing in CSS but not calling a redraw of the rendering on the Canvas. Note how the actual cell aspect ratios are being changed. This is not what should be happening.
> 
> ![MicroscopyStretch](https://user-images.githubusercontent.com/607793/59427889-0c49de80-8ddc-11e9-863e-c24f2ce92371.gif)

Can you send me dicom file? I want to check the metadata of this file.

**Comment by swederik** [comment]
Hi @Malik-Adil,

The data we are using comes from here: ftp://medical.nema.org/medical/dicom/Datasets/WG26/

It was part of the IHE Connectathon: http://dicom.nema.org/Dicom/DICOMWSI/

Hope that helps!
