### ISSUE TITLE
Loading notification showing up incorrectly

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#551]
If you scroll in one viewport, sometimes the "Loading..." text appears in the wrong viewport. I don't know what is going on, but it's obviously broken somewhere.

![Loading](https://user-images.githubusercontent.com/607793/59429902-17533d80-8de1-11e9-8fed-357ad76ca048.gif)

**Comment by biharck** [comment]
Waiting for the PRs 
https://github.com/cornerstonejs/react-cornerstone-viewport/pull/22
https://github.com/OHIF/Viewers/pull/630

**Comment by dannyrb** [comment]
@biharck when you create a PR, please feel free to assign a reviewer. If more than 48-hours go by without a review, start poking around to see what the hold up is. Try to parent your work until it crosses the finish line.
