### ISSUE TITLE
Unmet peer dependency when building Recipes - User Account Control

### ISSUE THREAD

**Issue by dicomtechnologyadmin** [OHIF/Viewers#552]
**When running:**
docker-compose up

**On files:**
~/viewers/docker/openresty-orthanc-keycloak

**At step 4/5 linking dependencies, the following warnings are triggered:**
warning " > @ohif/extension-cornerstone@0.0.34" has incorrect peer dependency "ohif-core@^0.3.5".
warning " > @ohif/extension-vtk@0.0.2" has incorrect peer dependency "ohif-core@^0.3.3".
warning "@ohif/extension-vtk > react-vtkjs-viewport > vtk.js@8.4.9" has unmet peer dependency "wslink@^0.1.8".
warning "@ohif/extension-vtk > react-vtkjs-viewport > vtk.js@8.4.9" has unmet peer dependency "shader-loader@^1.3.1".
warning "@ohif/extension-vtk > react-vtkjs-viewport > vtk.js@8.4.9" has unmet peer dependency "worker-loader@^2.0.0".
warning " > ohif-dicom-html-extension@0.0.2" has incorrect peer dependency "ohif-core@^0.2.6".
warning " > ohif-dicom-microscopy-extension@0.0.5" has incorrect peer dependency "ohif-core@^0.2.6".
warning " > ohif-dicom-pdf-extension@0.0.6" has incorrect peer dependency "ohif-core@^0.3.4".
warning "react-scripts > pnp-webpack-plugin > ts-pnp@1.1.2" has unmet peer dependency "typescript@*".
warning " > rollup-plugin-peer-deps-external@2.2.0" has incorrect peer dependency "rollup@^0.x".

**Comment by dannyrb** [comment]
The bulk of these warnings have been resolved with our switch to a monorepo and updated versions. If you or anyone else sees these moving forward, please feel free to bump peer dependency versions in a small PR :+1:
