### ISSUE TITLE
How to Integrate OHIF Viewer with the Third Party Application 

### ISSUE THREAD

**Issue by shtl23** [OHIF/Viewers#56]
Hi,
We are integrating OHIF Viewer in our Web Application, 
Is there any documentation for Integrating OHIF Viewer with third party application.
Is there any way to combine OHIFViewer & LessionTracker Package into one module?

Thanks

**Comment by radicalrob** [comment]
I see that you posted your question to the cornerstone forum.  I think that's a better place for such a question; github issues is really for bugs and feature requests.
