### ISSUE TITLE
i18n breaks embedded viewer

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#565]
Release 0.2.0 added i18n support, but this broke the unpkg script tag use of ohif.

You can replicate this in the code sandox linked from the docs:

https://codesandbox.io/s/ohif-viewer-script-tag-usage-svmm2

change line 98 from:
   ` src="https://unpkg.com/ohif-viewer@0.0.9/dist/index.umd.js"`
to
   `src="https://unpkg.com/ohif-viewer@0.2.0/dist/index.umd.js"`

and the study list no longer loads (any version between 0.0.9 and 0.1.19 works).

code sandbox doesn't report anything specific, but when I test locally I get this message:

```
index.es.js:104 Uncaught ReferenceError: require is not defined
    at getLocales (index.es.js:104)
    at initI18n (index.es.js:123)
    at index.es.js:142
    at index.umd.js:4
    at index.umd.js:5
```

**Comment by swederik** [comment]
Looks like it's from here: https://github.com/OHIF/Viewers/blob/04e00fad20bbcacfc0eb9210c73ba907f2fc94bc/extensions/ohif-i18n/src/index.js#L41-L50
