### ISSUE TITLE
First run issue

### ISSUE THREAD

**Issue by dgxdev** [OHIF/Viewers#566]

**Comment by dgxdev** [comment]
I get the following error,  when I try to open an image (this is during first run):
TypeError: thumbnails.flat is not a function
Thanks,
Barbaros

**Comment by dgxdev** [comment]
It turns out this is an issue with Firefox (handling of JavaScript), things work in Chrome.
Thanks,
Barbaros

**Comment by dannyrb** [comment]
Fixed here: https://github.com/OHIF/Viewers/pull/573/files#diff-14b1e33d5bf5649597cdc0e4f684daddR33
