### ISSUE TITLE
OHIFViewer is always displaying "Loading..."

### ISSUE THREAD

**Issue by phdggg** [OHIF/Viewers#57]
Hello all,

   I installed the latest version of OHIFViewer wit Orthanc 1.2. I tried to run

   METEOR_PACKAGE_DIRS="../Packages" meteor --settings ../config/orthancDIMSE.json

   The output is as follows. The display in Chrome browser hang at loading the study... I could not see any display of my DICOM images. Can you help?

[[[[[ ~/Viewers/OHIFViewer ]]]]]              

=> Started proxy.                             

=> Started MongoDB.                           

I20170307-08:02:18.060(0)? Adding Servers from JSON Configuration

I20170307-08:02:18.110(0)?  {

I20170307-08:02:18.111(0)?   "servers": {

I20170307-08:02:18.111(0)?     "dimse": [

I20170307-08:02:18.111(0)?       {

I20170307-08:02:18.112(0)?         "name": "ORTHANC_DIMSE",

I20170307-08:02:18.112(0)?         "wadoUriRoot": "http://localhost:8042/wado",

I20170307-08:02:18.113(0)?         "requestOptions": {

I20170307-08:02:18.113(0)?           "auth": "orthanc:orthanc",

I20170307-08:02:18.114(0)?           "logRequests": true,

I20170307-08:02:18.114(0)?           "logResponses": false,

I20170307-08:02:18.114(0)?           "logTiming": true

I20170307-08:02:18.115(0)?         },

I20170307-08:02:18.115(0)?         "peers": [

I20170307-08:02:18.116(0)?           {

I20170307-08:02:18.116(0)?             "host": "localhost",

I20170307-08:02:18.117(0)?             "port": 4242,

I20170307-08:02:18.117(0)?             "aeTitle": "ORTHANC",

I20170307-08:02:18.117(0)?             "default": true,

I20170307-08:02:18.118(0)?             "server": false,

I20170307-08:02:18.118(0)?             "supportsInstanceRetrievalByStudyUid": true

I20170307-08:02:18.119(0)?           },

I20170307-08:02:18.119(0)?           {

I20170307-08:02:18.120(0)?             "host": "0.0.0.0",

I20170307-08:02:18.120(0)?             "port": 11112,

I20170307-08:02:18.121(0)?             "aeTitle": "OHIFDCM",

I20170307-08:02:18.121(0)?             "default": true,

I20170307-08:02:18.121(0)?             "server": true,

I20170307-08:02:18.122(0)?             "supportsInstanceRetrievalByStudyUid": true

I20170307-08:02:18.122(0)?           }

I20170307-08:02:18.122(0)?         ]

I20170307-08:02:18.123(0)?       }

I20170307-08:02:18.124(0)?     ]

I20170307-08:02:18.124(0)?   },

I20170307-08:02:18.125(0)?   "defaultServiceType": "dimse",

I20170307-08:02:18.125(0)?   "dropCollections": true,

I20170307-08:02:18.125(0)?   "public": {

I20170307-08:02:18.126(0)?     "verifyEmail": false,

I20170307-08:02:18.126(0)?     "ui": {

I20170307-08:02:18.126(0)?       "studyListFunctionsEnabled": true,

I20170307-08:02:18.127(0)?       "leftSidebarOpen": false,

I20170307-08:02:18.127(0)?       "displaySetNavigationLoopOverSeries": false,

I20170307-08:02:18.127(0)?       "displaySetNavigationMultipleViewports": true,

I20170307-08:02:18.128(0)?       "autoPositionMeasurementsTextCallOuts": "TRLB",

I20170307-08:02:18.128(0)?       "displayEchoUltrasoundWorkflow": false

I20170307-08:02:18.128(0)?     },

I20170307-08:02:18.129(0)?     "demoUserEnabled": true

I20170307-08:02:18.129(0)?   }

I20170307-08:02:18.129(0)? }

I20170307-08:02:18.136(0)? Adding DIMSE peers

I20170307-08:02:18.136(0)? listening on {"address":"0.0.0.0","family":"IPv4","port":11112}

=> Started your app.

W0307 07:56:10.471874 FromDcmtkBridge.cpp:142] Loading the external DICOM dictionary "/usr/share/libdcmtk5/private.dic"

W0307 07:56:10.479155 OrthancInitialization.cpp:489] Registering JPEG Lossless codecs

W0307 07:56:10.479189 OrthancInitialization.cpp:494] Registering JPEG codecs

W0307 07:56:10.487400 main.cpp:635] Loading plugin(s) from: /home/ubuntu/orthanc-webviewer/Build/libOrthancWebViewer.so

W0307 07:56:10.506998 PluginsManager.cpp:269] Registering plugin 'web-viewer' (version mainline)

W0307 07:56:10.507030 PluginsManager.cpp:168] Initializing the Web viewer

W0307 07:56:10.507216 PluginsManager.cpp:168] Web viewer using 1 threads for the decoding of the DICOM images

W0307 07:56:10.507232 PluginsManager.cpp:168] Storing the cache of the Web viewer in folder: OrthancStorage/WebViewerCache

=> App running at: http://localhost:3000/

I20170307-08:02:22.172(0)?  Services.DIMSE.Studies

I20170307-08:02:22.173(0)? Associating...

I20170307-08:02:22.174(0)? Starting Connection...

I20170307-08:02:22.175(0)? Connect

I20170307-08:02:22.175(0)? Connection established

I20170307-08:02:22.182(0)? ==Associated

I20170307-08:02:22.186(0)? Sending command C-FIND-RQ

I20170307-08:02:22.240(0)? Connection closed

I20170307-08:02:25.523(0)?  GetStudyMetadata(%s) 1.2.392.200036.9116.2.2.2.1762587269.1055387749.844680

I20170307-08:02:25.528(0)? Associating...

I20170307-08:02:25.528(0)? Starting Connection...

I20170307-08:02:25.529(0)? Connect

I20170307-08:02:25.530(0)? Connection established

I20170307-08:02:25.532(0)? ==Associated

I20170307-08:02:25.534(0)? Sending command C-FIND-RQ

I20170307-08:02:25.967(0)? Data received

I20170307-08:02:26.004(0)? Data received

I20170307-08:02:26.035(0)? Data received

I20170307-08:02:26.076(0)? Data received

I20170307-08:02:26.098(0)? Data received

I20170307-08:02:26.116(0)? Data received

I20170307-08:02:26.142(0)? Data received

I20170307-08:02:26.160(0)? Data received

I20170307-08:02:26.164(0)? Connection closed

I20170307-08:02:26.165(0)?  resultDataToStudyMetadata

**Comment by phdggg** [comment]
Could you please help? Thanks!

**Comment by radicalrob** [comment]
In Chrome, could you please hit F12 and post the contents of what's in the console?  Are there any errors there?

**Comment by phdggg** [comment]
Below were two GET requests failed with net::ERR_CONNECTION_REFUSED in the console log.
I setup the OHIF and Orthanc on a server machine. And the I visited by typing http://the server ip:3000 on a client machine. Very interestingly, I can download the file in the following two below URLs if I replace "localhost:3000" with "the server ip:3000". I also attach a figure showing the screen shot of the stuck page.
 
http://localhost:3000/__wado_proxy?url=http%3A%2F%2Flocalhost%3A8042%2Fwado%3FrequestType%3DWADO%26studyUID%3D1.2.392.200036.9116.2.2.2.1762587269.1055387749.844680%26seriesUID%3D1.2.392.200036.9116.2.2.2.1762587269.1055389538.155209%26objectUID%3D1.2.392.200036.9116.2.2.2.1762587269.1055389538.170091%26contentType%3Dapplication%252Fdicom&options=%7B%22auth%22%3A%22orthanc%3Aorthanc%22%2C%22logRequests%22%3Atrue%2C%22logResponses%22%3Atrue%2C%22logTiming%22%3Atrue%7D

http://localhost:3000/__wado_proxy?url=http%3A%2F%2Flocalhost%3A8042%2Fwado%3FrequestType%3DWADO%26studyUID%3D1.2.392.200036.9116.2.2.2.1762587269.1055387749.844680%26seriesUID%3D1.2.392.200036.9116.2.2.2.1762587269.1055389538.155209%26objectUID%3D1.2.392.200036.9116.2.2.2.1762587269.1055389788.773253%26contentType%3Dapplication%252Fdicom&options=%7B%22auth%22%3A%22orthanc%3Aorthanc%22%2C%22logRequests%22%3Atrue%2C%22logResponses%22%3Atrue%2C%22logTiming%22%3Atrue%7D

<img width="1418" alt="screen shot 2017-03-09 at 12 06 01 am" src="https://cloud.githubusercontent.com/assets/16751012/23741282/9514dae6-045c-11e7-9900-34037a2e7ab8.png">

**Comment by swederik** [comment]
Did you set a ROOT_URL?

If you plan to visit the URL at a specific URL, it needs to be set when you start the server. You'll need to set the environment variable ROOT_URL="the server ip:3000" if you want to be able to access it properly from there.

The reason is that internally the code will set some paths to things based on the ROOT_URL. By default your ROOT_URL is probably localhost:3000, but as you say, you are trying to access it on another URL (server ip:3000).

**Comment by phdggg** [comment]
I tried to export ROOT_URL="the server ip:3000" before loading 
METEOR_PACKAGE_DIRS="../Packages" meteor --settings ../config/orthancDIMSE.json

But I got the following errors
[[[[[ ~/Viewers/OHIFViewer ]]]]]              

=> Started proxy.                             
Errors prevented isopacket load:              
                                              
While loading isopacket `constraint-solver`:
packages/meteor.js:1221:19: Cannot read property 'slice' of null
at packages/meteor.js:1221:19
at packages/meteor.js:1233:4
at packages/meteor.js:1380:3


/home/ubuntu/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: isopacket load failed?

**Comment by phdggg** [comment]
Found the problem. You have to put http:// inside of ROOT_URL. So 
export ROOT_URL="http://the server ip:3000"

**Comment by deligence** [comment]
i am using nginx reverse proxy , i have export the Root_url to serverip:3000 but wado_uri become only server_ip without 8042 port , so , get request failed. but when i add 8042 port with serverip in orthancdicomweb.json file it can't load because of nginx. so what should i do.
