### ISSUE TITLE
Ability to modify OHIF Viewer extensions without rebuilding

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#570]
The OHIF Viewer can conveniently be extended with new features and functionality via Extensions. Unfortunately, the only way to modify the extensions we register is to import them and pass them to the `ExtensionManager` in `App.js`

This is largely due to reliance on our module system to resolve peerDependencies for extensions.

Ideally, extensions should be able to be passed in to our `App` component, so that extending the viewer does not require a rebuild.

**Comment by dannyrb** [comment]
This was made possible in our recent monorepo switch. We need to create some documentation around how to accomplish this with Script Tag and PWA usage. Both at build time, and run time. This gives us a good way to test the UMD builds of each extension, as likely no one was (or even could) use them in that way until now.

Assigning to myself.

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
