### ISSUE TITLE
Disable "study list" link using a config object

### ISSUE THREAD

**Issue by diego0020** [OHIF/Viewers#574]
In many applications users only want to open the viewer with a particular study. For this cases it would be useful to disable the `study list` link.  This could be specially useful in the embedded view.

**Comment by swederik** [comment]
You can use this now:
```javascript
showStudyList: false
```

inside your config files.

Here's an example: https://github.com/OHIF/Viewers/blob/4b3994e788b79fc4810ad9861fd644c357874362/public/config/demo.js#L3
