### ISSUE TITLE
Unable to load dicom files.[Urgent]

### ISSUE THREAD

**Issue by Shanky0009** [OHIF/Viewers#58]
Dicom files loads on local but when running from a hosted site it return with the following error:
<h4>uncaught exception: dicomParser.readPart10Header: DICM prefix not found at location 132 - this is not a valid DICOM P10 file.</h4>
Unable to figure out what the problem is, both local and live site gets Dicom files from same orthanc server which is also hosted live.
Any help is appreciated.

**Comment by swederik** [comment]
Could you provide any more information about the file? Is it a multi-frame image? Could you provide an anonymized version?

**Comment by Shanky0009** [comment]
This problem occurs with all Dicom files i have been using . They work properly on localhost but from live server they don't.
Here is the link for anonymized version of a Dicom file i am using:
http://www.dicomlibrary.com/?requestType=WADO&studyUID=1.2.826.0.1.3680043.8.1055.1.20170309093927163.498370348.4095933&manage=4e893a33910fdfa675bc0a45af004e00

**Comment by swederik** [comment]
What is the difference between your development and live servers? Is the live server built with 'meteor build'?

**Comment by swederik** [comment]
The file works fine for me. I guess it's not an issue with any of the files, but probably more of your setup. Can you post a screenshot of the Chrome developer console with the requests / responses for images from the server? I would guess you are not actually getting DICOM image data back, and that's why dicomParser can't parse it...

**Comment by Shanky0009** [comment]
No live server is built with Mup.
This is the screenshot from live server.
![screenshot](https://cloud.githubusercontent.com/assets/17160110/23745395/fd3b7f04-04dd-11e7-81f3-37d550f04708.jpg)

**Comment by swederik** [comment]
Can you show the network tab? I specifically want to see what is happening with the requests to retrieve the images.

**Comment by swederik** [comment]
It also looks like many of your icons aren't loading, so this could be the same ROOT_URL issue as https://github.com/OHIF/Viewers/issues/57

**Comment by Shanky0009** [comment]
ROOT_URL is already set in production to the ip of the site.
This is the network tab screenshot.
![screenshot2](https://cloud.githubusercontent.com/assets/17160110/23747148/b1970bd4-04e4-11e7-9a49-69e61b8b781d.jpg)

**Comment by Shanky0009** [comment]
Here is the header screenshot for WADO request.
![screenshot](https://cloud.githubusercontent.com/assets/17160110/23748282/f1fc8a24-04e8-11e7-904e-f2433c67d8d4.jpg)

**Comment by swederik** [comment]
That seems to indicate that the response is of type HTML. What is the response? It should not be HTML, it should be a DICOM image.

If you try to hit the URL on the bottom with cURL, do you get an image back?

**Comment by Shanky0009** [comment]
Response is HTML and after hitting the URL i am getting HTML.

**Comment by swederik** [comment]
We have identified the issue. It seems that some changes to support different ROOT_URLs are breaking things. You can see in your requestURL that there are two slashes (//) after the initial IP. A fix is on the way!

**Comment by evren217** [comment]
Actually, this bug was already fixed with the following code:

https://github.com/OHIF/Viewers/blob/master/Packages/ohif-core/both/utils/absoluteUrl.js#L5-L8

Are you sure that you are using the latest code from master?

**Comment by Shanky0009** [comment]
Sorry, I was one version behind. Thanks Mate.
