### ISSUE TITLE
Does new React version support display multiple frame image now?

### ISSUE THREAD

**Issue by soolaugust** [OHIF/Viewers#599]
I am using new React version, but found it doesn't support multiple frame image, it only request for one frame, when I scroll the series, it doesn't change.

So I wanna to know if new version support multiple frame image now?

**Comment by swederik** [comment]
Hello,

Yes there is a bug that is breaking this right now. There is an open issue about this already: https://github.com/OHIF/Viewers/issues/539

Please do a quick search next time before creating a new issue.

**Comment by swederik** [comment]
Fixed by #600
