### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by Ravenheart** [OHIF/Viewers#6]
Greetings, I have gotten the main meteor package running however each time I open a patient for viewing I get a:
![ohif](https://cloud.githubusercontent.com/assets/853378/13177117/cb0ba2f8-d71f-11e5-9bf7-884684175f14.png)

I have followed the tutorial (https://github.com/OHIF/Viewers/wiki/Usage) and step 3 cannot be done under Windows (which is why I believe its failing on every patient).

On a side note, not being able to run this without meteor is a serious drawback.

**Comment by chafey** [comment]
What is your specific concern about meteor and what would you suggest as an alternative?

**Comment by Ravenheart** [comment]
Ideally it should run without the need for any special servers, apache or iis.

**Comment by radicalrob** [comment]
I'm not sure what you're getting at.  We are using Cornerstone to implement the Viewport portion of the viewer applications, but we also have several server-side resources that only make sense when deployed as centralized resources (like databases, DICOM servers, etc); as such, the web client is simply a "view" of the data that's on the server.  

The OHIF viewer is not designed to be a client-only solution.  If that's what you're looking, then you might want to use Cornerstone directly (https://github.com/chafey/Cornerstone).

**Comment by Ravenheart** [comment]
Aha Cornerstone looks exactly like what I need, thank you very much.
