### ISSUE TITLE
Viewer-master is not working (Proxy Issue - Not allowed to open image into Dicom Viewer (on loading))

### ISSUE THREAD

**Issue by Nadeem123** [OHIF/Viewers#60]
i did install everything very well according to to the document on https://github.com/OHIF/Viewers/wiki/Getting-Started

rest of all working well my dockers server is running , 
NodeJS version v6.10.0 
npm 3.10.10 
meteor installed 
docker server is running and working fine
Got Latest Viewer-master source code

clone it and run with   "PACKAGE_DIRS="../Packages" meteor --settings ../config/orthancDICOMWeb.json"

successfully Run lunched the application http://localhost:3000

the study list appears perfect as soon click on study to view in dicom viewer it goes on LOADING....

here are attache images:

Docker running
Viewers started with metero
debug browser error where it showing the error in proxy_wado

if someone want to browse online and please go here 
http://www.medfiles.com:3000/ 
http://medfiles.com:8042/

![debugger_viewers_master](https://cloud.githubusercontent.com/assets/3659200/23884140/fa576c9a-0838-11e7-8790-1e259fc03086.png)
![docker](https://cloud.githubusercontent.com/assets/3659200/23884142/fa58ff6a-0838-11e7-963f-8d56fa7319da.png)
![running_ohif](https://cloud.githubusercontent.com/assets/3659200/23884141/fa577096-0838-11e7-8533-61576731be3a.png)

**Comment by radicalrob** [comment]
You need to set ROOT_URL when starting up meteor, otherwise your WADO requests will default to localhost causing the CORS proxy error you are seeing.  Also, the packages variable is now called "METEOR_PACKAGE_DIRS" instead of just "PACKAGE_DIRS".  It should look something like this in your case: 

ROOT_URL=http://www.medfiles.com:3000 METEOR_PACKAGE_DIRS="../Packages" meteor --settings ../config/orthancDICOMWeb.json"

I have updated the startup commands on the wiki.

**Comment by Nadeem123** [comment]
Thanks radicalrob for quick reply
This ROOT_URL do i have to update in some file ? some name the file which file

**Comment by radicalrob** [comment]
it's when you are starting meteor.  Just update the command you posted in your request with the one I posted.

**Comment by Nadeem123** [comment]
i did follow these line but image is still not diaplying its still loading 

its overhere http://www.medfiles.com:3000/ 
please have a look in debugger its showing  No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by Nadeem123** [comment]
Can u please have a look its everything fine now , some starnge issue now 
"500 Internal Server Error xh"
"Error: Problem with request to PACS: getaddrinfo ENOTFOUND http http:80"
