### ISSUE TITLE
Question: oidc-client and firebase auth

### ISSUE THREAD

**Issue by Twinber** [OHIF/Viewers#602]
I am trying to connect the authenticated user through oidc to sign in this with firebase.
I'm following this guide, https://cloud.google.com/identity-platform/docs/how-to-enable-application-for-oidc
But I can not get the correct parameters.
I receive this error:
"code": 400,
     "message": "OPERATION_NOT_ALLOWED: The identity provider configuration is not found.",
     "
I'm confused about the ClientID and Issuer URL parameters, what should they be?

**Comment by swederik** [comment]
I'm not sure about Issuer, maybe it's the same as Authority?

https://github.com/OHIF/Viewers/pull/584/files#diff-5e7788ecc82dfc0652cd6d272e7187c4R14

Maybe you need to enable the auth?

https://stackoverflow.com/questions/55522640/the-identity-provider-configuration-is-not-found-react-native-firebase-authent

**Comment by Twinber** [comment]
Finally I have achieved this by passing the id_token to the firebase method signInWithCredential, using firebase.auth.GoogleAuthProvider () as provider.
Now I have the user, also logged in firebase as I needed.

**Comment by Diex** [comment]
How could I do it the opposite way, login in to firebase and skip OHIF login popup (using google healtcare).?

**Comment by apgal** [comment]
@Diex - were you able to implement it?  Any help would be appreciated.  Thanks

**Comment by Diex** [comment]
Actually, I did not.
I can't recall what was the last attempt . I quit this project long time
ago.
sorry. :)

**Comment by apgal** [comment]
@Diex - No worries.  Thanks for responding
