### ISSUE TITLE
Opening study/series via URL pattern http://<base_url>/viewer/<study_instance_uid> in version OHIF Viewer 2.0

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#606]
Im unable to open study/series via URL pattern http://<base_url>/viewer/<study_instance_uid> in version OHIF Viewer 2.0. This is how I used to do it in version 1.x. When I try to do it in 2.0 I get the following:

![Annotation 2019-06-30 204628](https://user-images.githubusercontent.com/5023419/60399018-3dfecb80-9b78-11e9-9ed1-e5de738c270c.jpg)

**Comment by swederik** [comment]
If you go to http://<base_url> do you get the study list? If so I guess it's a setting for your IIS server. You need to redirect all paths which do not exactly match files in the directory to index.html. Similar setting exist for e.g. AWS S3, Google Cloud Storage Buckets, or Nginx when you are using them for hosting single-page applications.

e.g. https://stackoverflow.com/questions/7027636/nginx-send-all-requests-to-a-single-html-page

**Comment by ranasrule** [comment]
> 
> 
> If you go to http://<base_url> do you get the study list? If so I guess it's a setting for your IIS server. You need to redirect all paths which do not exactly match files in the directory to index.html. Similar setting exist for e.g. AWS S3, Google Cloud Storage Buckets, or Nginx when you are using them for hosting single-page applications.
> 
> e.g. https://stackoverflow.com/questions/7027636/nginx-send-all-requests-to-a-single-html-page

Yes I do get the study list when I go to http://<base_url>

**Comment by ranasrule** [comment]
You suggestion was exactly what was required. Thank you.

**Comment by swederik** [comment]
Great!
