### ISSUE TITLE
current Viewer-master is broken ()

### ISSUE THREAD

**Issue by Nadeem123** [OHIF/Viewers#61]
I was using Viewer-Master from last three months it was working fine , just got the latest and start using 

started metoer with these
ROOT_URL=http://<serverip>:<port> METEOR_PACKAGE_DIRS="../Packages" meteor --settings ../config/orthancDICOMWeb.json

which is started perfectly 
docker is running fine , 
installed nodeJS 6.x.x
npm installed

the studylist is coming in dicomeviewer , but when click on study to view in dicome view its Just loading loading....

here is live my system 👍 
http://medfiles.com:3000/
http://medfiles.com:8042/app/explorer.html

feel free to add more studyies to test it 

just noted in chrom debugger its shows under network tag these errors:

"500 Internal Server Error xh"
"Error: Problem with request to PACS: getaddrinfo ENOTFOUND http http:80"

**Comment by evren217** [comment]
Please correct your ROOT_URL like this:

ROOT_URL=http://medfiles.com:3000 METEOR_PACKAGE_DIRS="../Packages" meteor --settings ../config/orthancDICOMWeb.json

**Comment by Nadeem123** [comment]
sorry its type:
i did start with this 
ROOT_URL=http://www.medfiles.com:3000 METEOR_PACKAGE_DIRS="../Packages" meteor --allow-superuser --settings ../config/orthancDICOMWeb.json

**Comment by evren217** [comment]
Your wado url does not look correct. Please check wadoUriRoot in the config file.

`
Request URL:http://www.medfiles.com:3000/__wado_proxy?url=http%3A%2F%2Fhttp%3A%2F%2Fmedfiles.com%3A8042%2Fwado%3FrequestType%3DWADO%26studyUID%3D1.2.840.113745.101000.1008000.38271.5819.6607459%26seriesUID%3D1.3.12.2.1107.5.1.4.54023.30000004111815353957800003283%26objectUID%3D1.3.12.2.1107.5.1.4.54023.30000004111815353957800004095%26contentType%3Dapplication%252Fdicom&options=%7B%22auth%22%3A%22orthanc%3Aorthanc%22%2C%22logRequests%22%3Atrue%2C%22logResponses%22%3Afalse%2C%22logTiming%22%3Atrue%7D
`

Here, wado proxy tries to resolve "http://http://medfiles.com..." which is invalid.

**Comment by Nadeem123** [comment]
Thanks Its rock
