### ISSUE TITLE
OHIF viewer 2.0+Orthanc not working on IIS or Nginx on windows

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#611]
OHIF viewer 2.0+Orthanc not working on on IIS or Nginx on windows for me. It just displays a black page with the text Error:True in the left corner. It works fine when I use the default config that connects to  server.dcmjs.org but when I switch to the Orthanc config the following errors appear in the browser console:

![Annotation 2019-07-01 144654](https://user-images.githubusercontent.com/5023419/60427107-743b5a00-9c0f-11e9-934d-6abe471e177a.jpg)

**Comment by swederik** [comment]
In your picture you can see that your Orthanc is responding with a 404 to something like "http://localhost/dicom-web/studies?....". Are you **sure** that the URL you are using is correct? 
Because according to the error message your PACS is not responding.

**Comment by ranasrule** [comment]
> 
> 
> In your picture you can see that your Orthanc is responding with a 404 to something like "http://localhost/dicom-web/studies?....". Are you **sure** that the URL you are using is correct?
> Because according to the error message your PACS is not responding.

Sorry, Im a bit confused. I'm using the following config for Orthanc:
```
window.config = {
  routerBasename: '/',
  relativeWebWorkerScriptsPath: '',
  servers: {
    dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: '/wado',
        qidoRoot: '/dicom-web',
        wadoRoot: '/dicom-web',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        requestOptions: {
          requestFromBrowser: true,
        },
      },
    ],
  },
};

```

**Comment by swederik** [comment]
You have not configured IIS correctly to reach Orthanc.

You have configured OHIF to look for your PACS at a relative URL (e.g. qidoRoot: '/dicom-web').
You have not configured your proxy properly, so that URL (http://localhost/dicom-web) is not resolving to Orthanc.

You need to make IIS correctly forward traffic to localhost/dicom-web to Orthanc. Did you set up a rule in IIS to forward any traffic to /dicom-web/ or /wado to Orthanc?

**Comment by ranasrule** [comment]
Yeah I can see now that Orthanc isn't even receiving a request for data. This obviously isn't an OHIF issue. My apologies.

**Comment by Awxm** [comment]
Have you solved the problem

**Comment by Awxm** [comment]
> 对我来说，OHIF 查看器 2.0+Orthanc 无法在 Windows 上的 IIS 或 Nginx 上运行。它只显示一个黑色页面，左角有文本 Error:True。当我使用连接到 server.dcmjs.org 的默认配置时它工作正常，但是当我切换到 Orthanc 配置时，浏览器控制台中会出现以下错误：
> 
> ![批注 2019-07-01 144654](https://user-images.githubusercontent.com/5023419/60427107-743b5a00-9c0f-11e9-934d-6abe471e177a.jpg)

Brother, I have the same problem and I but I haven't solved it yet
