### ISSUE TITLE
Opening a  series via URL pattern <base_url>/study/<studyInstanceUid>/series/<seriesInstanceUid>

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#614]
Opening a  series via URL pattern `<base_url>/study/<studyInstanceUid>/series/<seriesInstanceUid>` seems to not be working in OHIF viewer 2. I'm getting the following in console:

![Annotation 2019-07-02 042141](https://user-images.githubusercontent.com/5023419/60472129-016ac700-9c81-11e9-8cfd-6de95428a09d.jpg)

**Comment by dannyrb** [comment]
Can you provide a link that reproduces this issue on `https://viewer.ohif.org`? If not, can you indicate the steps required to reproduce this issue? If it's not simple to reproduce, a minimal CodeSandbox or Repository that demonstrates this issue would be helpful.

**Comment by swederik** [comment]
Note for testing: this should display the third series:
https://viewer.ohif.org/study/1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5/series/1.3.6.1.4.1.25403.345050719074.3824.20170125095449.8

**Comment by ranasrule** [comment]
> 
> 
> Note for testing: this should display the third series:
> https://viewer.ohif.org/study/1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5/series/1.3.6.1.4.1.25403.345050719074.3824.20170125095449.8

![Annotation 2019-07-02 133402](https://user-images.githubusercontent.com/5023419/60497409-38b39500-9cce-11e9-8a36-217fde14b3eb.jpg)

**Comment by swederik** [comment]
Yes, we know it's broken, there's no need to add another screenshot...

**Comment by ranasrule** [comment]
My apologies. I thought you wanted me to test it.

**Comment by ranasrule** [comment]
@swederik I see you added a commit to fix this this commit is part of v0.12.1 but unfortunately it isnt working for me. The entire study with all series is shown even with specific series is specified. Please see screenshot:
![Annotation 2019-07-09 021540](https://user-images.githubusercontent.com/5023419/60843459-2666b900-a1f0-11e9-8f2b-7bc0e4ef423f.jpg)

**Comment by swederik** [comment]
Yes, I know. This is mentioned specifically in the PR description: https://github.com/OHIF/Viewers/pull/617

> Note: This does not actually fix what is loaded, it just stops the route from breaking. We will need to add another change to make it only display the specified series.

**Comment by dannyrb** [comment]
Scoped and added to backlog here: https://github.com/OHIF/Viewers/issues/879
