### ISSUE TITLE
oidc-client Cors issue

### ISSUE THREAD

**Issue by Twinber** [OHIF/Viewers#616]
Today I receive this error: 
"Access to XMLHttpRequest at 'https://www.googleapis.com/oauth2/v3/certs' from origin 'localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
, yesterday it worked perfectly, I have not made any changes, I do not understand this.

**Comment by swederik** [comment]
Yeah we are going to need a lot more information before we can do anything with this...

Can you post the entire set of logs? Sometimes there is an error sitting above something like this, it can sometimes appears to be a CORS issue and then it turns out there's something right above it, and the CORS issue is coming up for the error message or something.

What exactly were you doing? What is this from? Is this happening when refreshing the token?

**Comment by Twinber** [comment]
I am using the connection with gcloud healthcare.
For days it has been working well, now I get these errors right after granting the permissions in the google account.

Access to XMLHttpRequest at 'https://www.googleapis.com/oauth2/v3/certs' from origin 'http://localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
CallbackPage.js:24 Uncaught (in promise) Error: Error: Network Error
    at Object.errorCallback (CallbackPage.js:24)
    at r.n.onRedirectError (redux-oidc.js:204)
    at redux-oidc.js:215

The error occurs on the first attempt to enter the app, just when returning to the callback page, with the authentication data.
In the url is this info
callback # state = 3fe61635278d49a6ab0e2db5464b2482 & access_token = ya29.Gls5B1er9tQ6sK .....

**Comment by swederik** [comment]
That's really weird. We haven't changed anything that would affect that recently. Are you sure you still have localhost:5000 as an authorized javascript origin? The docs for the Meteor version are here so you can double check all the steps: https://docs.ohif.org/connecting-to-image-archives/google-cloud-healthcare.html#setup-a-google-cloud-healthcare-project

**Comment by Twinber** [comment]
I explain what I'm doing.
I have taken your PR https://github.com/OHIF/Viewers/pull/584
and merge with your master branch, I'm working with react, not with meteor.
I have the authorized domains well configured ...
The strange thing is that on Saturday everything is correct, and today this is happening to me, without having touched anything in my code either.

:(

**Comment by Twinber** [comment]
If I reload the page, being in / callback with the data of the token in the url, the error that comes out is this:
CallbackPage.js:24 Uncaught (in promise) Error: Error: No matching state found in storage
    at Object.errorCallback (CallbackPage.js:24)
    at r.n.onRedirectError (redux-oidc.js:204)
    at redux-oidc.js:215

**Comment by Twinber** [comment]
I solve this, settings manually the metadata and singinKeys for google auth.
`metadata: {
                issuer: "https://accounts.google.com",
                authorization_endpoint: "https://accounts.google.com/o/oauth2/v2/auth",
                token_endpoint: "https://www.googleapis.com/oauth2/v4/token",
                userinfo_endpoint: "https://www.googleapis.com/oauth2/v3/userinfo",
                jwks_uri: "https://www.googleapis.com/oauth2/v3/certs",

            },
            signingKeys: [
                {
                    "e": "AQAB",
                    "kty": "RSA",
                    "alg": "RS256",
                    "n": "rgPFxdeuvEf8c4PePDc3mNuG2pM1_OfoWNQmVFg7iyc1VBnjhEDFcynhpL3vy30PfwGse9LcRbTVQUNnWjnWNt09XAmuYKWQc-jpad_M_G1Vd3gHCGmPAo1bG7iu3XTYIT3sm-PuI-aKHcee7H76f0MxFfdZuOEw7l__pjTDtv0Md914cJbq7Egk8pAk4PWv0FI9DRqnVLCDR0r4rCJb4Dq_hNPbFJMXxUyxvLYp9Nq2BaCQN4ZuS910GQTpLHBkOkXtZWCy__vrtBg5cshG3ASZmCtCH8InsQugCpKkVXIEUuEwJC3bzxOaXGjXe32G0zsUH789s7BuIP-EGrt1fQ",
                    "use": "sig",
                    "kid": "118df254b837189d1bc2be9650a82112c00df5a4"
                },
                {
                    "e": "AQAB",
                    "kty": "RSA",
                    "alg": "RS256",
                    "n": "xL3TevYy9F9myjfAJw1dLV3LouuP8m24VlgWTehPypAce34YAprAHNWJhflKFCNQqqXRJEJYfyGn10K0OywIXrmpkq8-Sxmy3WmMT-DprKisP3YIbrW2gEm8BL8mQYyHosGQAFxM1ErhPtItiI56Avs7hj1bQ7SXJGElwqi19NqlN7sfoOUpTCuOp5E2wKRjMHKryi1pvPAXqxS58vDQ2no72d3Uoy1flQfK6pyCBqCMQkiP8ganuZV4oLaXEeS8e71w7HuoJ87o30r4J_WKAVwENwJJWhai1c_TvyWCCBFjEjdIDiQJaG4lGaaPV60mSHTGk2Sr_cf3aIKCbLGk0Q",
                    "use": "sig",
                    "kid": "afde80eb1edf9f3bf4486dd877c34ba46afbba1f"
                }
            ]`

the signingkeys are from https://www.googleapis.com/oauth2/v3/certs... 
I suppose this will not be a security problem because they are public.

**Comment by Twinber** [comment]
I have a collateral damage, configuring it in this way I asked to login every time the page loads.
It does not store the token in localstorage, or so I think.

**Comment by python-programmer** [comment]
Hello from the other side
I must've called a thousand times
To tell you 

"Browse the link https://www.googleapis.com/oauth2/v3/certs in your browser,
And check to see if it gives you an error.
This address gives different information **per request**".

good luck 😎

**Comment by python-programmer** [comment]
This address (https://www.googleapis.com/oauth2/v3/certs) gives me an 40X error.
When I test it with VPN,
Everything is fine.

Now is the time to reach a conclusion:
1. Google has restricted my IP, Or
2. Google has restricted insecure websites (HTTP)  that calling its URL
