### ISSUE TITLE
Reference lines in OHIF Viewer 2

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#619]
Reference lines seem to be missing in OHIF Viewer 2 when when two or more studies are opened at the same time. These were there in 1.x. Any chance they could be added at some point?

**Comment by dannyrb** [comment]
We're firming up some of our design around how we manage and surface information about multiple viewports. After things are a bit cleaner, features like this should be much easier to implement.

**Comment by dannyrb** [comment]
👋 @biharck can you take this one?
This should probably be implemented as a command, so we can keep the `cornerstone` specific logic contained in the appropriate extension. You can find an example command for `@ohif/extension-cornerstone` here:

https://github.com/OHIF/Viewers/blob/master/extensions/ohif-cornerstone-extension/src/commandsModule.js#L157-L164

For this to work, we'll likely need to implement reference lines differently than we have in the past. The biggest difference being that we won't use a "Synchronizer" here. I recommend taking a second to read over the [`ReferenceLinesTool.js`](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/ReferenceLinesTool.js) in cornerstone-tools. You'll see that:

- It has a default "renderer", `renderActiveReferenceLine`
- It takes a `synchronizationContext` as an option when being enabled
    - Keep in mind, a `Synchronizer` is really just:
        - An event to listen for
        - A list of "source" elements
        - A list of "target" elements
        - A function that should be called when the event we're listening for is raised on a source element
- Each time an element with this tool enabled is rendered, it draws a reference line for each "source" element on itself

Okay. So how do we accomplish this with a command?

- We're actually going to avoid using a tool here. The `synchronizationContext` in options makes it hard for us to accomplish what we want.
- Instead, when we "enable", let's add appropriate listeners for:
    - Active viewport changes
        - This may not already exist, but I'm okay w/ it being implemented in `Viewers`
    - Active viewport [shows a new image](https://github.com/cornerstonejs/cornerstone/blob/master/src/events.js#L1-L19)
    - And for each viewport's `cornerstoneimagerendered` event

So when do we need to update reference lines for all viewports?

- If `referenceLines` are enabled/disabled
- If the `activeViewport` changes
- If the `activeViewport` scrolls to a new index

When should we update a single viewport?

- Whenever it renders: `cornerstoneimagerendered`

How can I render a reference line without using a tool?

- Call `renderActiveReferenceLine(context, imageRenderedEvent, sourceElement, targetElement)` directly

Notes:

- The "source" element for us, will always be whichever `viewport` is "active".
- The "source" element should not render reference lines on itself
- All currently enabled elements can be accessed at: `cornerstoneTools.store.state.enabledElements`

Have questions or stuck? Don't hesitate to ping me.

**Comment by vimalgupta** [comment]
Hi ,
Any further update on it.

**Comment by dannyrb** [comment]
@vimalgupta some development was started and has stalled. This issue is up for grabs. If you need clarification/guidance to draft a PR, don't hesitate to ask questions.

**Comment by rohit-takhar** [comment]
Hi @dannyrb,
I am trying to implement the reference Lines feature using the approach mentioned by you. Since I am a beginner, will you please guide me a bit? How can I call the render function directly? I tried to import it the way `scroll` has been imported but it failed.

**Comment by dannyrb** [comment]
@rohit-takhar, if it's not exported in the cornerstone-tools `lib` exports, it may need to be added to the list with a small PR.

That's how that library exposes "internals" that are for tool authors and users looking for more granular control

**Comment by georgioschi** [comment]
Hi, 
is or will be any progress on this feature?
If not, is there any known working "unofficial" implementation that we could refer to?

Thank you.

**Comment by mechyserra** [comment]
Hi,
Is there any progress regarding this issue? Or the possibility to include this via an extension? 
Thank you in advance!

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
