### ISSUE TITLE
Some problems with loading images with different compressions

### ISSUE THREAD

**Issue by christianvargasforero** [OHIF/Viewers#62]
Good morning,

I have been testing the viewer with different modalities and different compressions and I have encountered the following problems:

In this example the image does not render well:
![captura de pantalla 2017-03-27 a las 5 01 48 p m](https://cloud.githubusercontent.com/assets/11984387/24380823/e39782b2-1312-11e7-8ad3-d9a9acaa6e7b.png)
file:
[lossy.dcm.zip](https://github.com/OHIF/Viewers/files/874002/lossy.dcm.zip)

Of equal way in this other parts of the image are lost:
![captura de pantalla 2017-03-27 a las 5 05 03 p m](https://cloud.githubusercontent.com/assets/11984387/24380835/e8ee953e-1312-11e7-8ffe-8a225c1b889b.png)
file:
[lossless.dcm.zip](https://github.com/OHIF/Viewers/files/874005/lossless.dcm.zip)

And lastly in this case does not work at levels tool:
![captura de pantalla 2017-03-27 a las 5 08 48 p m](https://cloud.githubusercontent.com/assets/11984387/24380841/ee44ed8a-1312-11e7-886b-629e71a98747.png)
file:
[levels no works.dcm.zip](https://github.com/OHIF/Viewers/files/874004/levels.no.works.dcm.zip)

I send the files so they can try.

thank you very much.

**Comment by radicalrob** [comment]
Thank you for this report and for the details, sample images, etc.  Very helpful.  We will look into it.

**Comment by swederik** [comment]
The first two images are now working with the latest Cornerstone WADO Image Loader.
The third image has a VOI LUT applied automatically. This is something we will have to address.
