### ISSUE TITLE
More descriptive/verbose progress indication when study/series downloading/loading

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#620]
It would be much more user-friendly if a more descriptive/verbose progress indication was shown to the user when a study/series downloading/loading in Ohif Viewer. For example "x of y images loaded" instead of the current simple "Loading" text. 

Could the devs consider this humble request. Thanks.

**Comment by pieper** [comment]
👍  yes, this is a good idea.  It was implemented in the crowds-cure.org version and it's very helpful.

**Comment by ranasrule** [comment]
> 
> 
> 👍 yes, this is a good idea. It was implemented in the crowds-cure.org version and it's very helpful.

Exactly...this would be perfect
![Annotation 2019-07-02 165051](https://user-images.githubusercontent.com/5023419/60510768-b33dde00-9ce9-11e9-9df5-d0bca6259a4a.jpg)

**Comment by swederik** [comment]
I do agree we should probably have *something*. One weird thing when you start tracking what is loaded is what you should display if some of the images get kicked out of the cache.

**Comment by pieper** [comment]
Hmm, yes, maybe a better concept would be to have some kind of cache status widget.  It could show how many are currently cached and how many are queue (perhaps a bar chart instead of numbers).

**Comment by ranasrule** [comment]
> 
> 
> Hmm, yes, maybe a better concept would be to have some kind of cache status widget. It could show how many are currently cached and how many are queue (perhaps a bar chart instead of numbers).

Yeah, Osimis Viewer shows a bar chart whereas Weasis uses a pie chart with percentage loaded in the center of it.

**Comment by ranasrule** [comment]
@swederik can this be accepted as feature to be added to the roadmap?

**Comment by dannyrb** [comment]
It's something I would be more than happy to review a PR for and merge if it was implemented well. That's our rough definition of "on the roadmap". I can't promise it's something we'll get to in the short term.

I've seen implementations of this that fill the progress bar in at slice indexes the correspond with images entering the cache. Sometimes with different colors to indicate state: not cached, requested, cached, decached

I'm unsure what representation is most beneficial to the end user, but as @swederik pointed out, using the bar to indicate "loaded" can be misleading. It's also worth being aware of this issue as we think on cache improvements for shared image + brush data.

**Comment by dannyrb** [comment]
Scoped and added to backlog here: https://github.com/OHIF/Viewers/issues/883

Closing.
