### ISSUE TITLE
oidc-client issue part 2

### ISSUE THREAD

**Issue by Twinber** [OHIF/Viewers#622]
Related to #616 
I have a collateral damage, configuring it in this way I asked to login every time the page loads.
It does not store the token in localstorage, or so I think.

Any suggestion?

**Comment by Twinber** [comment]
I solved with:

`<Route
            component={() => {
              userManager.getUser().then(user => {
                if (user) {
                  userManager.signinSilent();
                } else {
                  userManager.signinRedirect();
                }
              });

              return null;
            }}
          />`

in OHIFStandaloneViewer.js

**Comment by dannyrb** [comment]
FWIW, I believe there's an in-progress pull request to add support, custom components, etc. for your specific use case. It may be worth watching the repo and it's docs for updates so you don't need to maintain a fork.

**Comment by swederik** [comment]
@Twinber, I've taken a bunch of your comments into account here: https://github.com/OHIF/Viewers/pull/698

Thanks for posting your solutions! It was very helpful.
