### ISSUE TITLE
3D volume visualisation

### ISSUE THREAD

**Issue by renardfe** [OHIF/Viewers#63]
Hi,

I have a 3D volume in DICOM format. I would like to visualise it with a multiplanar view (sagittal, coronal and axial view) in the OHIF viewer. Is it possible?

If OHIF viewer can render only a 2D image, it is possible to change between sagittal, coronal and axial view?

Thanks!

**Comment by radicalrob** [comment]
There are plans to add MPR to the OHIF viewer at some point, but I don't know when.  For now, you can only display 2D views as acquired.  If all 3 views were acquired, then yes you can switch between them.  If you're not already, you might want to post to / monitor this discussion group: [https://groups.google.com/forum/#!forum/cornerstone-platform]
