### ISSUE TITLE
Brightness and contrast of MPR is too high

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#631]
When 2D MPR of a study is generated the its brightness and contrast of MPR is too high as can be seen in below images:

![1](https://user-images.githubusercontent.com/5023419/60761021-a0186e80-a059-11e9-8b6a-4c6a54450333.jpg)
![2](https://user-images.githubusercontent.com/5023419/60761022-a27ac880-a059-11e9-803e-2867a2429adb.jpg)

**Comment by swederik** [comment]
Yeah it's probably calculating W/L from the entire volume, we will have to check this.

**Comment by swederik** [comment]
We are now just adjusting W/L to cover the entire range of the volume, so I'll close this.

**Comment by pieper** [comment]
Do you read the WindowCenter/WindowWidth tags from the header to set the defaults?  That would be better than looking at the scalar range of the pixel data.

Maybe this should be a new issue, since many datasets have good suggested wc/ww values (they can even be a list)
