### ISSUE TITLE
Eroor when opening certain studies

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#632]
OHIF Viewer 2 is unable to open certain studies. I'm attaching an image from one of the studies and a screenshot of the error.
![Annotation 2019-07-07 233404](https://user-images.githubusercontent.com/5023419/60772431-c7317780-a10f-11e9-9e2f-c14c6f1744f9.jpg)

[7ff3fca2-967e-4095-9617-cc39d401ea54.zip](https://github.com/OHIF/Viewers/files/3365973/7ff3fca2-967e-4095-9617-cc39d401ea54.zip)

**Comment by swederik** [comment]
This file works perfectly fine for me. What other types of image are in this study?

**Comment by ranasrule** [comment]
I've been doing some digging into this and it seems this is an issue with Orthanc's dicomweb plugin.
