### ISSUE TITLE
Support for processing DICOM Structured Report 

### ISSUE THREAD

**Issue by christianvargasforero** [OHIF/Viewers#64]
Good Morning,

I am testing a series of studies that contain files with the diagnostic report in pdf, although the file extension of the report is not pdf since this is in dicom.

Try another viewer and as you can see this render it normally:
![captura de pantalla 2017-04-05 a las 4 50 04 p m](https://cloud.githubusercontent.com/assets/11984387/24729255/f5584f60-1a22-11e7-886c-b4bb4d9f8bc9.png)

And when I test it in the OHIF viewer the file is not rendered, as I suppose there is no support for this type of files:
![captura de pantalla 2017-04-05 a las 4 52 23 p m](https://cloud.githubusercontent.com/assets/11984387/24729265/fd58368a-1a22-11e7-9f65-bab5a5364699.png)

Likewise try to load with cornerstoneWADOImageLoader and throws the following error:
"Uncaught TypeError: Can not read property 'encapsulatedPixelData' of undefined"
![captura de pantalla 2017-04-05 a las 5 07 35 p m](https://cloud.githubusercontent.com/assets/11984387/24729274/089705a8-1a23-11e7-8992-c39954df0e70.png)

I send the study so that they can try:
[pepita - 00000000000.zip](https://github.com/OHIF/Viewers/files/900930/pepita.-.00000000000.zip)

I would like to know if it is possible to add this functionality ?, 
Thank you very much and I will be attentive to your response.

**Comment by swederik** [comment]
Hi Christian,

The file you have attached is not actually an encapsulated PDF. According to the DICOM dump (https://rawgit.com/chafey/dicomParser/master/examples/dumpWithDataDictionary/index.html) it is a DICOM Structured Report (SOPClassUID : "1.2.840.10008.5.1.4.1.1.88.11" [ Basic Text SR Storage ]). The viewer you are using is converting it to an image or PDF for display, I guess. 

DICOM SR support is on the roadmap, but I don't have a timeline for it. I'll leave this issue open for now so we can track the feature.

Thanks for the sample data.

**Comment by swederik** [comment]
This stuff renders now, though the display UI could be made to look a bit prettier. Happy to take a PR to update the dicom-html extension.
