### ISSUE TITLE
Add Zoom and Pan buttons for VTK Viewport

### ISSUE THREAD

**Issue by gzt036** [OHIF/Viewers#640]
basic operations like Zoom, pan, measurements, levels should be made available.

**Comment by swederik** [comment]
MPR is using VTK.js, but the rest of the application and tools are using Cornerstone, this is why we cannot show the tools in the MPR views yet. We do not have a timeline for that.

We can add buttons for Zoom and Pan though. You can also use right-click and middle-click (or shift+click?) for zoom and pan.

**Comment by dannyrb** [comment]
Scoped and added to the backlog here: https://github.com/OHIF/Viewers/issues/640
