### ISSUE TITLE
Using Live and local orthanc at same time.

### ISSUE THREAD

**Issue by Shanky0009** [OHIF/Viewers#65]
Is it possible to use live and local orthanc server at the same time?
By this I mean that can a live web application read DICOM files from its own live orthanc server as well as from the local machine its currently used on, so the OHIF viewer will show file from both live orthanc and local orthanc server.

**Comment by radicalrob** [comment]
Hi.  It's a good question.  If I understand what you're looking for, you'd like to aggregate query results from multiple DICOM sources and present the combined result set in the study list.    We don't have this implemented, nor is it in the roadmap at this time, but maybe you'd like to implement it and submit a pull request :-)
