### ISSUE TITLE
Hanging protocols v2

### ISSUE THREAD

**Issue by christianvargasforero** [OHIF/Viewers#657]
Good day team,

I would like to know if in its plans it is contemplated to implement some functionality to use hanging protocols in the new version?

cordial greeting and happy development 👍

**Comment by dannyrb** [comment]
@christianvargasforero, as far as I know, it's something we would like to see support for. I don't believe we will allocate development for it in the near future, but we would be more than happy to discuss spec/implementation if someone were interested in championing and PR'ing better hanging protocol support.

**Comment by christianvargasforero** [comment]
> @christianvargasforero, as far as I know, it's something we would like to see support for. I don't believe we will allocate development for it in the near future, but we would be more than happy to discuss spec/implementation if someone were interested in championing and PR'ing better hanging protocol support.

remember that in the community we are ready to support, if you have any clear line on how to approach the problem, we could collaborate with great pleasure

**Comment by dannyrb** [comment]
@swederik likely has the clearest vision around how this should be accomplished. I'll reach out to him and see if we can provide some guidance and expectations around an implementation.

**Comment by dannyrb** [comment]
Scoped and added to backlog: https://github.com/OHIF/Viewers/issues/901
