### ISSUE TITLE
Viewer should use SVG cursors from Cornerstone Tools

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#659]
CornerstoneTools supports SVG Cursors to show the user which tool they are using.

You can see them here: https://cornerstone-tools.netlify.com/

OHIF should enable these cursors in the viewer.

Not sure why this isn't in the Cornerstone Tools docs: https://github.com/cornerstonejs/cornerstoneTools/blob/b07435accf2a8eb306c39c786c4c5642bfc5a88a/examples/concepts/cursors.html#L26

**Comment by dannyrb** [comment]
Looks like the [home layout](https://github.com/cornerstonejs/cornerstoneTools/blob/b07435accf2a8eb306c39c786c4c5642bfc5a88a/examples/_layouts/home.html) doesn't link to it, or pull from any page data to list it.

You can still access it directly: https://tools.cornerstonejs.org/examples/concepts/cursors

-

**Comment by romulobordezani** [comment]
Pull Request with fix opened: https://github.com/OHIF/Viewers/pull/672

**Comment by romulobordezani** [comment]
@dannyrb  we implemented the same for ScgCursors support for CornerstoneTools examples in this https://github.com/cornerstonejs/cornerstoneTools/pull/990
