### ISSUE TITLE
How to make OHIF just list "today" studies ?

### ISSUE THREAD

**Issue by asdamha** [OHIF/Viewers#66]
Hi,

I want to customize the default studies  shows in the viewer to load just "Today" studies instead of loading whole images stored in the ORTHANC pacs
 thanks

**Comment by swederik** [comment]
I believe you can set the Meteor settings to use: "studyListDateFilterNumDays": 1

https://github.com/OHIF/Viewers/blob/024e590af3b19b2f7a0abefd46006f25eb5d9d85/Packages/ohif-study-list/client/components/studylist/studylistResult/studylistResult.js#L240

https://github.com/OHIF/Viewers/blob/master/config/orthancDIMSE.json#L35

**Comment by asdamha** [comment]
What should this line look like 
const dateFilterNumDays = OHIF.uiSettings.studyListDateFilterNumDays;

where to set => "studyListDateFilterNumDays": 1

**Comment by asdamha** [comment]
Ok it worked by setting 

const dateFilterNumDays = 1;

but, another issue appeared which is the studies is doubled after loading .
