### ISSUE TITLE
Importing studies in v2.x

### ISSUE THREAD

**Issue by tiimoS** [OHIF/Viewers#660]
How do I go about to allow importing new studies in the OHIF viewer v2.x. Previously there was the importStudies.js file. I don't find anything similar in the code. 
The study count is still visible in the UI, but the '+' next to it is missing, which previously allowed to select studies to be uploaded to the server. 
Thanks for the support.

**Comment by swederik** [comment]
That hasn't been implemented yet, though there is some very similar
functionality in the Google Cloud UI we just added. It uses STOW-RS to send
studies do the dicomweb endpoint. We should use that upload component.
Happy to take a PR for that if you want to try to implement it.

**Comment by swederik** [comment]
@biharck 
- Remove the Upload button from here: https://github.com/OHIF/Viewers/blob/master/src/studylist/StudyListWithData.js#L224
- Instead, the + button next to the number of studies should open the DICOM uploader: https://github.com/OHIF/Viewers/blob/master/src/studylist/StudyListWithData.js#L206

**Comment by swederik** [comment]
This was added in https://github.com/OHIF/Viewers/pull/717, you just have to ensure that studyListFunctionsEnabled is true in your config. You also have to ensure that your server supports STOW-RS at the same URL that it supports QIDO-RS.
