### ISSUE TITLE
OHIF 2.0 Viewing Studies from Orthanc Server Not Loading

### ISSUE THREAD

**Issue by CallumKiefer** [OHIF/Viewers#661]
I am trying to load CT Scan Series from the Orthanc Server I've been using for OHIF 1.0, but in 2.0 the series does not seem to load properly. Attached is a picture of the issue.
![Orthanc Not Loading](https://user-images.githubusercontent.com/10731811/61142495-ecbada00-a49d-11e9-8b07-54f622ffea73.PNG)

**Comment by dannyrb** [comment]
Steps to reproduce? Any information included with the `400` bad request error from your web server?

**Comment by CallumKiefer** [comment]
I loaded the dicom files in the orthanc server through the interface provided with docker and the command `docker run --rm -p 4242:4242 -p 8042:8042 jodogne/orthanc-plugins`. I then put some dicom files there from the LUNA30CT dataset. I then ran the `yarn run dev:orthanc` to start OHIF. I selected the images and the screen on the screenshot above was displayed to me. The screenshot below shows the errors thrown by the orthanc server.
![Docker errors](https://user-images.githubusercontent.com/10731811/61145372-4a9ef000-a4a5-11e9-974a-42d506f04077.PNG)

**Comment by dannyrb** [comment]
Hmm.. If you're able to share the images without PHI, I can take a look? At first glance, it looks like Orthanc does not like trying to retrieve frames for your source images.

**Comment by CallumKiefer** [comment]
[Sample Dicom.zip](https://github.com/OHIF/Viewers/files/3387396/Sample.Dicom.zip)

**Comment by CallumKiefer** [comment]
@dannyrb Were you able to reproduce the error?

**Comment by CallumKiefer** [comment]
Within the 23 commits between when I opened this issue and now, one of them resolved the issue! Thanks!
