### ISSUE TITLE
Extending OHIF 1.0

### ISSUE THREAD

**Issue by BenjaminReichman** [OHIF/Viewers#662]
I've been trying to extend OHIF 1.0 and a few questions regarding to how it performs certain tasks:

(a) Where is the best place to put code that should run right after the image is loaded by the viewer? (b) Where are annotations (such as the ellipse roi) stored once they are drawn? Can I expose that storage location to a toolbar function and have it insert new annotations/rois that are then displayed? (c) Is it possible to add new options to the right click menu of annotations that will run code? (d) Is it possible to add a new dialog viewport that is similar to the cine 
dialog? I tried copying exactly what was done to create the cine dialog, but for some reason my dialogue looks no where to what it looks like.

Thank you!

**Comment by dannyrb** [comment]
Unfortunately, our resources are limited and we're unable to allocate much time to anything v1 related. I'll leave this open, and hopefully a community member can assist you. If you'd like support, it may be worth upgrading to version 2 or seeking out help from a qualified consultant/consultancy.
