### ISSUE TITLE
Cannot connect to local Orthanc

### ISSUE THREAD

**Issue by t-fi** [OHIF/Viewers#663]
I am trying to set up a minimal example with Orthanc and the OHIF Viewer.
After running `yarn start` a new browser window opens, and I can see the demo datasets from the default config.

When I change the config to my local Orthanc, I see the following error:
![dicom](https://user-images.githubusercontent.com/16362866/61188595-c5bcfd80-a681-11e9-9510-f39d687b9ca2.jpg)

My only changes are to the `public/config/default.js`:
```
servers: {
    dicomWeb: [
      {
       // The commented out lines don't work!
       // name: 'MyOrthanc',
       // wadoUriRoot: 'https://localhost:8042/wado',
       // qidoRoot: 'https://localhost:8042/dicom-web',
       // wadoRoot: 'https://localhost:8042/dicom-web',

        name: 'DCM4CHEE',
        wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado',
        qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
        wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',

        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        requestOptions: {
          requestFromBrowser: true,
        },
      },
    ],
  },

```
Orthanc also returns a json with studies when I access `http://localhost:8042/dicom-web/studies` in my browser.

I compiled Orthanc (1.5.7) and the dicom-web plugin (1.0) from scratch on Ubuntu if that matters. I think they are set up correctly, since it is possible to access the dicom-web via the browser.

Any ideas? Am I missing something? I think that is exactly what the docs tell me to do 🤔

**Comment by swederik** [comment]
The Create-React-App proxy should be working if you use localhost:8042. Could it be because you are putting `https` instead of `http`? Does your localhost Orthanc probably have an SSL certificate, is that why you put HTTPS?

**Comment by t-fi** [comment]
I tried both `http` and `https`. The Orthanc log states:
```HttpServer.cpp:1178] HTTP server listening on port: 8042 (HTTPS encryption is disabled, remote access is allowed)```
In the end it should be preferable to have `https`, as it encrypts the cleartext passwords contained in the requests. But that is for later.

I'm coming from a different backgorund and am quite a webdev noob, and did not even check that console :D Thanks for the hint!

The relevant line is (CORS issue as you suspected):
```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8042/dicom-web/studies?limit=25&offset=0&includefield=00081030%2C00080060&StudyDate=19510202-20190715. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).```

Is there anything specific I can do? Maybe a simple configuration mistake?

**Comment by swederik** [comment]
This line (https://github.com/OHIF/Viewers/blob/master/package.json#L16) is supposed to be preventing that error... I'll mark this as a bug so we can check it.

**Comment by swederik** [comment]
If you use a local copy of Orthanc and you are relying on the `proxy` part of package.json, you should set the WADO/QIDO roots like this:

```
wadoUriRoot: '/wado',
qidoRoot: '/dicom-web',
wadoRoot: '/dicom-web' 
```

That way the requests properly pass through the proxy.

One issue I am seeing, though, is that the Accept headers for "application/dicom+json" do not seem to be respected, so all of the results are coming back in XML, which is not supported. I'm not sure yet if this is on our side or an Orthanc issue.

**Comment by t-fi** [comment]
That works, thanks a lot!
