### ISSUE TITLE
Doubled studies list problem

### ISSUE THREAD

**Issue by asdamha** [OHIF/Viewers#67]
Hi ,

I changed the const dateFilterNumDays to "dateFilterNumDays = 1;" ,to load today studies instead of loading all of them ,but another issue appeared which is the studies is doubled after loading .

How I could fix that .

thanks

**Comment by ayselafsar** [comment]
Hi @asdamha ,

I fixed this issue by not triggering 'change' event of Study Date input explicitly after updateInputText is called because it already triggers 'change' event.

Could you please check and confirm the fix?  If it's good, please close this issue.

Thanks
