### ISSUE TITLE
Pagination issues with Safari

### ISSUE THREAD

**Issue by tiimoS** [OHIF/Viewers#670]
**Description**
Pagination does not work properly using Safari. "Previous" button is disabled and does not work at all and "Next" button only works two times, then it stops working, i.e. you cannot go to the next page anymore. 

**STR**: 
- select "Next" button on bottom of the page to show the next studies page. 
- select "Previous" button to get back to the first page

**ER**: 
- next button triggers loading of the next xy studies (next page)
- previous button triggers loading of the previous xy studies (previous page)

**AR**: 
- previous button disabled with Safari 
- next button works two times (can move two times to the next page), then it stops working, i.e. no new studies are loaded and you are stuck on the current page. Thereby, the "Next" button is still available. only occurs with Safari. 
- pagination works properly with Chrome and Firefox

**Versions**: 
Safari v12.1.1
Chrome v75.0.3770.100
Firefox v68.0

**Comment by swederik** [comment]
Ugh that's a weird one. I can reproduce it here too. Thanks for the report!

**Comment by biharck** [comment]
Fixed at https://github.com/OHIF/react-viewerbase/pull/133

**Comment by swederik** [comment]
I just tested this and it has been fixed by @biharck's changes, so I'll close it.
