### ISSUE TITLE
OHIF Viewer Integration with Oracle JDeveloper 12c

### ISSUE THREAD

**Issue by bilaluwe** [OHIF/Viewers#673]
Hi All,

I'm a newbie to OHIF viewer. 

I want to embed the OHIF viewer into Oracle JDeveloper 12c page fragment which is a Java EE based framework for enterprise application development. Does anyone tried it before and can share some insights into how this integration will be achieved. Otherwise, if there is any resource that can be useful for this integration, I will greatly appreciate if you can share.

Thanks a lot.
Bilal

**Comment by dannyrb** [comment]
@bilaluwe, the OHIF Viewer is just a collection of static assets (html, css, js). You could utilize an iFrame, or attempt to use the `ohif-viewer` packaged source (script tag) and start the React app in whatever target element you want.

Try giving the deployment section in our docs a read. If you have trouble figuring things out, let us know what you've tried and where you're getting hung up.
