### ISSUE TITLE
"loading" animation not showing when opening study 

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#681]
The "loading" animation that used to appear in version 1 is not showing when opening a study. Instead just a plain black page shows which is confusing for the end user.

**Comment by swederik** [comment]
Yeah I agree this needs to be improved

**Comment by dannyrb** [comment]
Since this issue was created, we've added `nprogress` to indicate route level loading. After we add per study metadata loading, we may revisit this issue. If there are general improvements you would like to see, please feel free to create a PR.

**Comment by ranasrule** [comment]
any chance this can be implemented?
