### ISSUE TITLE
Wrong measurement units on non-CT data

### ISSUE THREAD

**Issue by radicalrob** [OHIF/Viewers#687]
An ellipse ROI reports measured values in HU even for non-CT data.  HU is only a valid measurement unit for CT data.

**Comment by dannyrb** [comment]
This would be a `cornerstone-tools` issue. It looks like we make sure the image's modality is `CT` before using HU:

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/EllipticalRoiTool.js#L340

However, it looks like we use the `modality` for the `series`:

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/EllipticalRoiTool.js#L154-L157

If you have a mixed modality series, or one with a pilot, I could see this issue surfacing.

**Comment by dannyrb** [comment]
I'm going to transfer this to the cornerstone tools repo.

**Comment by galelis** [comment]
Discussed with Danny and we decided to put this issue on hold untill we get the MeasurementService done, so it will be easy to fix this one.

**Comment by sedghi** [comment]
I don't think this happens in latest master. 

Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
