### ISSUE TITLE
Trouble adding modality filter to worklist

### ISSUE THREAD

**Issue by mtjvankuik** [OHIF/Viewers#7]
I have some trouble adding the modality and accessionnumber tags as filters to the worklist. Furthermore I want to display the amount if images per study in the worklist as well.

The accessionnumber and # images show NaN. This is correct for the accessionnumber, since in my case a prefix is added in my DICOM files before the ''actual accession number''. For example: UMCA12345678. However, I have no idea why #images is shown as NaN. What DICOM tag is used to display # images? 

I changed the following files to add these filters:
worklistResult.html
worklistStudy.html
retrieveMetaData.js
worklistResult.js
getStudyMetaData.js

I'm currently trying to get the modality filter, the accession number and the #images up and running. The modality filter is shown blank; it does not even load. 
![worklist](https://cloud.githubusercontent.com/assets/10122364/13568309/b4f6dcaa-e460-11e5-9232-f7a39ee2e4c2.png)

It is important to know that there are two DICOM tags: modality (0008,0060), and modalities (0008,0061).
My modalities tag is non-existent when I look at the dicom tags in orthanc, my modality tag is filled with the string "DX". 

Is there more documentation available? And does anyone have tips on how to accomplish this?

**Comment by swederik** [comment]
Hi Martin,

Yes we are aware of these worklist issues but I don't have a good answer for you right now. I think the issues are related to Orthanc, though, since dcm4chee seems to work:

![screenshot 2016-03-07 13 39 37](https://cloud.githubusercontent.com/assets/607793/13569753/2d9347da-e46a-11e5-8d9e-b6969d9fe97a.png)

I'll see if we can get these bugs pushed up in our agenda.

Thanks for the report!

Erik

**Comment by mtjvankuik** [comment]
@swederik No problem! Thanks for the headsup. Is there any more information available about dcm4cgee? Because I really need to make these filters work.

**Comment by swederik** [comment]
I was testing with the SIIM DCM4CHEE server, I haven't actually set it up myself, sorry.

**Comment by radicalrob** [comment]
Hi Martin,

Right now, we are using DicomWeb (QIDO) to query Orthanc to build the study list.  We also noticed this problem, but haven't had a chance to try and fix it yet ourselves.  The problem you're having is with the DICOMWeb plugin in Orthanc that does not return (or filter on) those DICOM tags; i.e. ModalitiesInStudy and NumberOfStudyRelatedInstances.  It's already been reported on the Orthanc issue tracker here: (https://bitbucket.org/sjodogne/orthanc/issues/14/aggregate-fields-empty-for-qido-rs-study).

Setting up DCM4CHEE isn't something I've done either, although I know that they are working on a new version of that server that has docker support, so perhaps that wouldn't be too hard; see here: (https://github.com/dcm4che/dcm4chee-arc-light/wiki/Running-on-Docker).  If you want to try that and report back to us how it went, that would be awesome!

- Rob

**Comment by mtjvankuik** [comment]
Thanks for your references. I already switched projects (instead of using the cornerstone demo, I'm using the OHIF viewer package) so if it's possible I'm probably not switching to DCM4CHEE. 

I'm still figuring out the code, implementation and their interactions, but it would take me a lot of time to solve this issue myself. However I'm still going to try it this week. 
It also seems that in 
> https://bitbucket.org/sjodogne/orthanc-dicomweb/src/cf5002bc63a885bf99c413718d612f199a8cd748/Plugin/QidoRs.cpp?at=default&fileviewer=file-view-default#QidoRs.cpp-169 

the DICOM tag used in the QIDO call is wrong.

`    result.push_back(gdcm::Tag(0x0008, 0x0056));  // Modality`

Shouldn't that be `    result.push_back(gdcm::Tag(0x0008, 0x0060));  // Modality` ?

**Comment by mtjvankuik** [comment]
I have replaced the modalities tag with the modality tag. Now I load the modality corresponding to the study into my worklist :) However, even after adding this line in WorklistResult.js, filtering with the modality tag is not possible:
`modality: getFilter($('input#modality').val()),`

Any ideas?

**Comment by swederik** [comment]
I'm going to close this since the same issue is being discussed in https://github.com/OHIF/Viewers/issues/30
