### ISSUE TITLE
How can I load DICOM from dcm4chee WADO with OHIF viewer

### ISSUE THREAD

**Issue by MichaelNode** [OHIF/Viewers#70]
Hello, I am creating a project in NODEJS which should allow you to see DICOM FILES, for this I want to do a project in NODEJS which contains a list of patients and that redirects to the study of each patient in another project where this OHIF viewer, Can you use OHIF viewer as an API? is this possible?

In the case of yes, as it is done to load a series in OHIF viewer from WADO

I have knowledge of how to get a DICOM file from wado, but I do not know how to GET a complete series.

I would appreciate your answers. And sorry for english

**Comment by swederik** [comment]
You would have to open the viewer at a URI with the specific studyInstanceUid in the URL. We have a route for that here:

https://github.com/OHIF/Viewers/blob/master/OHIFViewer/client/routes.js#L19

**Comment by proteeti13** [comment]
Hello! I clicked on the solution but the link seems invalid. I am looking a solution for the same issue. Any help with that? Thanks!
