### ISSUE TITLE
Refresh on a study is giving 404

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#701]
Hi, I have setup this new viewer. I am able to open a study by going to the studylist first and then clicking on a study but when I refresh on the page where the study is open it gives me 404, in the logs also in machine it gives me error (click on image link). Please provide a solution for this.

Error image: https://5c-public.s3.ap-south-1.amazonaws.com/Screenshot+2019-07-22+at+2.44.33+PM.png

**Comment by swederik** [comment]
You need to change your S3 host to redirect all 404s to index.html. We
should probably add this to the documentation somewhere.

https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html
