### ISSUE TITLE
Measurement Table uses wrong units

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#702]
Hi the measurement tool gives the values in pixels, and the sidebar just converts them in mm. but that doesn't seem to be correct. As in the image attached distance between two ribs is coming around 400 mm which is 40 cm which doesn't sound right. Is there any config for this?

Image: https://5c-public.s3.ap-south-1.amazonaws.com/Screenshot+2019-07-22+at+4.25.03+PM.png

**Comment by dannyrb** [comment]
The annotation overlayed the image looks at the DICOM tags for pixelSpacing. It uses these values to convert from `px` to `mm`. When the values are not present, we cannot convert, so the `px` unit is used.

It looks like the measurements panel assumes that pixelSpacing is always present. It uses the number values provided by the tools and adds `mm` to the end. This is a bug. Thanks for the report!

**Comment by swederik** [comment]
Oh yeah that is not good at all...

**Comment by evren217** [comment]
This is actually a bug in `ohif-core` package. See: https://github.com/OHIF/ohif-core/blob/master/src/measurements/tools/length.js#L4
