### ISSUE TITLE
Extension Configuration Per Module

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#706]
There is currently not a way to pass configuration/props to individual modules of an extension when they are registered.

This might be useful if, for example, you need to pass components as props to a custom side bar. Another example would be if you want to restrict which tools from an extension get added. E.g. an extension defines 10 tools/toolbar entries and you only want to use one. An extension could allow for this sort of functionality in its `getModule` methods.

The proposed API change would be for [this function in OHIF-core](https://github.com/OHIF/ohif-core/blob/2a2e6bb8693d48d34df503dacba21a2e5c1f07aa/src/extensions/ExtensionManager.js#L100):

```js
/**
   * @private
   * @param {string} moduleType
   * @param {Object} extension
   * @param {string} extensionId - Used for logging warnings
   * @param {Object} configuration - The module specific configuration.
   */
  _getExtensionModule(moduleType, extension, extensionId, configuration = {}) {
    const getModuleFnName = 'get' + _capitalizeFirstCharacter(moduleType);
    const getModuleFn = extension[getModuleFnName];

    if (!getModuleFn) {
      return;
    }

    try {
       // CHANGE : pass configuration to the module.
       const moduleTypeConfiguration = Object.assign(
         {},
         configuration.global,
         configuration[moduleType]
       );

      const extensionModule = getModuleFn(moduleTypeConfiguration);

      if (!extensionModule) {
        log.warn(
          `Null or undefined returned when registering the ${getModuleFnName} module for the ${extensionId} extension`
        );
      }

      return extensionModule;
    } catch (ex) {
      log.error(
        `Exception thrown while trying to call ${getModuleFnName} for the ${extensionId} extension`
      );
    }
}
```

Then in `App.js` of [this app](https://github.com/OHIF/Viewers/blob/a2cc477a1ac6fdbd405a68f794ad3a6d59030e78/src/App.js#L62):

```js
const myConfiguration = {
  global: { // Some config}
  panel: { // Some panel-specific config}
}; // Or imported from another plugin, for example.

extensionManager.registerExtensions([
  // Core
  GenericViewerCommands,
  MeasurementsPanel,
  OHIFCornerstoneExtension,
  [ExtensionWithConfiguration, myConfiguration]
]);
```

For some context, my current usecase is defining some components specific to the platform I'm pointing against, and passing these to a generic plugin (the segmentation plugin).

Thoughts?

**Comment by dannyrb** [comment]
Stale bot misbehaving: https://github.com/OHIF/Viewers/commit/a6341775785ffe6efea4f3803783c2d0eb6407e2

**Comment by sedghi** [comment]
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
