### ISSUE TITLE
Setting tools to passive when new tool is activated

### ISSUE THREAD

**Issue by Ggpsv** [OHIF/Viewers#713]
Hello!

If I'm understanding this correctly, `ToolbarRow.js` allows only one active button at a given time. That is because whenever a button other than the active one is clicked, a new `activeButtons` array is created containing the new button's id. 

All tools are set to `passive` mode when the viewer mounts. However, as tools are used and switched, some of their effects linger on. For example, sa you include the `ZoomMouseWheel` tool in the viewer. Once you activate it, and then switch over to another tool, the "zooming" is still attached to the corresponding mouse mask (mouse wheel). 

I'd assume this is not the expected behavior given that we constrain the toolbar to one button at the time. It also leads to unexpected behavior. 

I'm not sure if this is an issue as I don't know whether what I describe happens by design. If not, I've fixed this behavior by setting the current tool as `passive` right before the new tool is set to `active`. I'll put up a PR once this is confirmed as an issue.

Thanks

**Comment by dannyrb** [comment]
👋 Hello @Ggpsv, thanks for taking the time to create this issue and kick off a discussion.

For the sake of our conversation, let's assume we're talking about the more popular `@ohif/extension-cornerstone` and it's toolbar buttons and tools.

### Responses

> ToolbarRow.js allows only one active button at a given time.

While this may currently be the case, it's not something we feel strongly about. At this time, toolbar buttons do one of two things:

- Set the cornerstone tool bound to left click and touch OR
- Fire an arbitrary command

In the future, we may want to extend the menu to allow setting tools for other (or multiple) mouse/interaction bindings, setting entire "loadouts" of bindings, etc.

> As tools are used and switched, some of their effects linger on... I'd assume this is not the expected behavior.

This is only true for tools without binding conflicts. When activating a tool with a left click binding, it will make sure that no side effects exist from tools that had the same binding. However, middle and right click bindings would not be cleared. Nor would mousewheel.

This allows us to have multiple tools bound to different inputs and interaction types. The toolbar is not the only place these bindings are initialized. We provide [an array of `availableTools`](https://github.com/OHIF/Viewers/blob/0d5d804741cecf80fe02affe807659481f8daf69/src/setupTools.js#L144-L229) to the `cornerstone-viewport` that establish some "default" bindings.

When the [`globalToolSyncEnabled` flag](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/modules/globalConfigurationModule.js#L4) is true, you can also see some non-obvious default activations.

>  I've fixed this behavior by setting the current tool as `passive` right before the new tool is set to `active`.

This should actually already be happening for you, as this is what `cornerstone-tools` does under the hood. Take the following example:

1. You have `length` tool active and bound to `mouseButtonMask: 1`.
2. You set the `angle` tool to active, and bind it to `mouseButtonMask: 1`
    - Cornerstone Tools, as part of activation, [tries to remove any conflicts for the incoming activation](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/setToolMode.js#L312-L355)
    - After conflicts are removed, any tools with no bindings are [set to passive](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/setToolMode.js#L352)
3. End result: `angle` tool is active for left click; `length` tool is `passive`

**Comment by Ggpsv** [comment]
@dannyrb Thanks for the thorough explanation!

> However, middle and right click bindings would not be cleared. Nor would mousewheel.

In our case, we're particularly interested in making sure the above get cleared. Can you expand on why these are excluded from the treatment that the left click gets?

**Comment by dannyrb** [comment]
@Ggpsv, I'm not sure I follow. Do you only ever want their to be a single active tool at a time? The advantage of not doing this by default is that we can bind zoom to mousewheel on app load, and it always works. Even as we select different tools to use with left click.

**Comment by Ggpsv** [comment]
Let's take the `ZoomMouseWheelTool` tool as an example. 

When the viewer loads initially, the mousewheel is bound to stack scrolling. Then you activate `ZoomMouseWheelTool` and subsequently you activate another tool. Now, the mousewheel is bound to zooming despite `ZoomMouseWheelTool` no longer being active.

I would expect one of the following two behaviors:
1. **The original app-load mousewheel binding would persist when no other tool is active.** Under this scenario, once `ZoomMouseWheelTool` is deactivated the mousewheel gets bound yet again to the stack scrolling. 
2. **The mousewheel binding is automatically cleared when its tool is deactivated. **

I find it odd that the binding activated by `ZoomMouseWheelTool` will persist even if the tool gets deactivated in the context of the toolbar. This makes the use of tools unpredictable as it is uncertain whether the effects of a tool will linger even after another tool is activated. This is specially true if we're only currently allowing one tool to be active at the time as far as UX goes.

Perhaps I'm making the wrong assumptions here, which I would happily adjust given more context on the design goals.

**Comment by dannyrb** [comment]
> The mousewheel is bound to zooming despite ZoomMouseWheelTool no longer being active.

In your example scenario, `ZoomMouseWheelTool` would still be active.

> I find it odd that the binding activated by `ZoomMouseWheelTool` will persist even if the tool gets deactivated **in the context of the toolbar.**

It looks like we're talking about two different states. The demo viewer only contains "actions" that fire and forget, and tools that can be bound to the left mouse button click. If you add `ZoomMouseWheelTool` to the toolbar, yes, it's possible for the "active" state for the toolbar to be out of sync with the tools that are actually active for the viewports.

Here is a small diagram that shows how tool states change as you activate tools, functionally, for the viewports, with our "under the hood" implementation in cornerstone tools:

![example-activation](https://user-images.githubusercontent.com/5797588/62142523-80711080-b2bc-11e9-8d69-fa8c394336a7.png)

The toolbar's "active" tracking is only as complex as it needs to be for the existing default configuration in our demo viewer. If you would like it to improve more complex scenarios, like adding `MouseWheel` tools to the toolbar, then I would be more than happy to review a PR or discuss solutions.

I'm sorry if we were talking past each other on this one.
