### ISSUE TITLE
A tool can be repeatedly activated despite being active already

### ISSUE THREAD

**Issue by Ggpsv** [OHIF/Viewers#714]
Hello!

In the context of `ToolbarRow.js` a button is set as the active button once it is clicked on. Once active, if you repeatedly click it, the underlying tool will be repeatedly activated as well. 

Is this by design?

If not, I have the following fix, such that we only update the state if the clicked button is not already active. 

```js
if (button.type === 'setToolActive' && !_isButtonAlreadyActive.call(this, button)) {
    this.setState({
      activeButtons: [button.id],
    });
  }
```

I'll put up a PR once this is confirmed as an issue.

**Comment by dannyrb** [comment]
I'm not sure there's any harm in allowing a tool to be activated once already active. At least not for any maintained `cornerstoneTools`. I could see there being issues if assumptions were made in a tool's activation callback?

Is there a specific problem you're encountering that has you looking for a solution here? We could certainly do this, I'm just trying to better understand the why/value.

**Comment by Ggpsv** [comment]
@dannyrb No concrete examples to be honest. That said, it is an unnecessary update if re-activating does not make any tangible difference in the UI. 

In our case, this behavior was causing `setToolActive` to be called twice, which may not necessarily be an issue on itself but may cause unexpected behavior given the `activeCallback` behavior of any tool.

**Comment by dannyrb** [comment]
@Ggpsv, I'd say that's reasonable. I would be happy to review a small PR to prevent multiple activations for the same tool :+1:

**Comment by Ggpsv** [comment]
@dannyrb Great, I'll post a PR next week.
