### ISSUE TITLE
Viewer Configurations

### ISSUE THREAD

**Issue by mmbauskar** [OHIF/Viewers#716]
Hello Team,

I am trying to setup OHIF-Viewer (latest version) using the following configuration

```
{
        name: 'LH-DICOM',
        wadoUriRoot: 'http://localhost:9000',
        qidoRoot: 'http://localhost:9000',
        wadoRoot: 'http://localhost:9000/viewer/api',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        requestOptions: {
          requestFromBrowser: true,
        },
}
```

we are able to fetch Study Meta from the server but while rendering the image we are facing the issue, Please check the below image for reference.

<img width="428" alt="Screenshot 2019-07-24 at 4 55 09 PM" src="https://user-images.githubusercontent.com/43605784/61795472-19c5a000-ae41-11e9-8424-0d1760758e1d.png">

the original image is as follows

<img width="369" alt="Screenshot 2019-07-24 at 6 31 32 PM" src="https://user-images.githubusercontent.com/43605784/61795613-6dd08480-ae41-11e9-8354-30a2145bfe02.png">

I am not able to find the root cause of the issue, how can we solve the above issue?

**Comment by dannyrb** [comment]
@mmbauskar do you have a minimal reproduction or steps that we can follow to reproduce?

**Comment by mmbauskar** [comment]
@dannyrb,

we are reading a DCM file from the server and sending as `multipart/related` response to the viewer.

**Comment by dannyrb** [comment]
@mmbauskar are you able to create a repository, docker image, or CodeSandbox that reproduces this issue? I don't think this is a purely OHIF viewer configuration issue. I've seen similar output with decode issues on occasion, but I don't have enough information to go off of here.

**Comment by swederik** [comment]
This is impossible for us to debug without more information. Does your DICOM image display correctly if you load it here? https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

Or here? https://viewer.ohif.org/local

If it displays correctly on these pages, then it is an issue with your server not serving pixel data correctly. If not, then it may be an issue with the file itself or the image loader / decoder. Please test this and let us know.
