### ISSUE TITLE
How to mask or remove the study information like patient name etc..

### ISSUE THREAD

**Issue by vimalgupta** [OHIF/Viewers#718]
Hi,

How can i mask or remove the study information like patient name etc.. while we open the study in viewer 2.x.

**Comment by dannyrb** [comment]
It depends on your end goal. If you want to mask/hide information so it's easier to take screenshots without PHI, we could introduce a feature that allows you to toggle that information.

If you don't want that information to be accessible to the end user of the viewer, you would likely need to leverage anonymized DICOMs, or have endpoints that can provide the application with anonymized DICOM metadata.
