### ISSUE TITLE
Switch OHIF Logo from text + font to SVG

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#723]
We are currently loading the entire Sanchez font only to use it for the OHIF Logo. We should remove the font and use the Logo as an SVG instead.

References to Sanchez:
https://github.com/OHIF/Viewers/search?utf8=%E2%9C%93&q=sanchez&type=

Here's a link to the logo in Sanchez (it's in White so may not be visible): https://www.dropbox.com/s/j4ugchl97w74p13/ohiflogo.svg?dl=0

This will simplify script-tag usage, since this font will no longer need to be pulled from Google Fonts.

**Comment by biharck** [comment]
Fixed at https://github.com/OHIF/Viewers/pull/744

**Comment by dannyrb** [comment]
**Acceptance Criteria:**

- [ ] Remove Sanchez Font from template/import
- [ ] Add OHIF "text logo" only in `platform/viewer`
- [ ] Update Header usage to leverage SVGs for icon and text

**Comment by dannyrb** [comment]
Closed by: https://github.com/OHIF/Viewers/pull/1021
