### ISSUE TITLE
Include Roboto font via WebPack

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#724]
In the Meteor version we eventually switched from Google fonts to locally including the Roboto font. We should do this again. Here was the commit originally: https://github.com/OHIF/Viewers/commit/87d61298b438604140a671cfb03449ae36498f58. This was helpful because otherwise testing the viewer when offline meant that it would load very slowly since it kept trying to reach out to Google to get the fonts.

WebPack can be used to import the font:

https://webpack.js.org/guides/asset-management/#loading-fonts

This will simplify script-tag usage, since this font will no longer need to be pulled from Google Fonts.

**Comment by dannyrb** [comment]
@swederik, I would actually prefer we don't bundle the font, unless it's for script tag usage. For PWA, having it as a separate include allows us to offload the request to Google's lightning fast CDN and leverage caching that many users will have from having requested that same font for a different website (and Roboto is popular).

For PWA offline scenarios, we can make sure our service worker has a copy of assets we load from Google's CDN. If the asset is fresh enough, or if we're offline, we can use the locally cached copy instead.

This keeps our bundle size lower, improves load times, and makes it easier to not lock users into a specific font.

**Comment by swederik** [comment]
That's fine with me too, I just don't want the end user for script-tag usage to have to include the fonts in their HTML page, I don't really have a strong opinion on the solution.

**Comment by dannyrb** [comment]
**For Script Tag:**

Let's embed. It's one less thing for the user to care about, and we're not as concerned with performance tuning there.

**For Embeded:**

We'll need to modify it's WebPack build.

- Look at [`webpack-workbox-plugin`](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin)
- Here is a [recipe for caching google fonts](https://developers.google.com/web/tools/workbox/guides/common-recipes)

Caching WebPack application files is probably outside the scope of this issue. There are a few hurdles to navigate carefully, and we don't want to over-complicate this ticket.

**Comment by dannyrb** [comment]
**Additional guidance:**

For bundling w/ the commonjs/umd build, import the font in `index-umd.js`. The entry point file for that bundle.

It _should_ load and bundle. If not, you'll need to add a webpack loader that supports the font's file format.

For PWA, look at my most recent comment on that issues. It's mostly about setting the correct caching rules for the service-worker.
