### ISSUE TITLE
component.schema.resetValidation(); not found

### ISSUE THREAD

**Issue by itcthienkhiem** [OHIF/Viewers#73]
Dear ad,
i added new server DIMSE but a problem  component.schema.resetValidation(); not found
do you commit this function yet?
Thank so much
![capture](https://cloud.githubusercontent.com/assets/2140355/25944227/bd69d7de-366c-11e7-9181-98c7cf31b8f8.PNG)

**Comment by swederik** [comment]
Looks like there was a bug in the form schema (or none existed). I don't get this error on the current master so I will close this. If you still see this, feel free to reopen it.
