### ISSUE TITLE
Standalone routing does not work

### ISSUE THREAD

**Issue by kongzhonglei** [OHIF/Viewers#731]
my english is very bad,Please accept my full apologies.
standalone can use in v2?
 like http://localhost:5000/?url=http://xxx.xxx/xxx.json

**Comment by dannyrb** [comment]
@swederik do you have an example URL for custom JSON you can provide?

@kongzhonglei, I believe it's supported; but the documentation on it is sparse.

**Comment by kongzhonglei** [comment]
http://dcm.shuaiyimedical.cn/3006/20190712/54006/54006.json

**Comment by swederik** [comment]
Hmm looks like there is a bug with the URL query string parsing.

Here is the code: https://github.com/OHIF/Viewers/blob/f7ba7621efb284980c0cf0b86767002cad18dd86/src/routes/StandaloneRouting.js#L13

The idea is that something like this should work: http://viewer.ohif.org/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/PTCTStudy.json (but right now it doesn't)

**Comment by kongzhonglei** [comment]
if can,please tell me the full url. thank you

**Comment by swederik** [comment]
Just fixed this. This URL should work soon: http://viewer.ohif.org/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/JSON/PTCTStudy.json

You have to wait for the tests etc to run on master first though, maybe wait 10-15 minutes before testing this.
