### ISSUE TITLE
Retrieve binary DICOM instance

### ISSUE THREAD

**Issue by MathisGuilhin** [OHIF/Viewers#736]
Hello OHIF team,

According to [DICOM WADO-RS specifications](https://www.dicomstandard.org/dicomweb/retrieve-wado-rs-and-wado-uri/), we should be able to retrieve binary DICOM instances from the PACS.
But where is it actually manipulated? Where can i retrieve this instance (that I would like to save)?

**Comment by swederik** [comment]
When we use WADO-RS we are retrieving the pixel data and the metadata separately. First we do a Study Metadata call and then we grab the pixel data for each frame.

If you want the entire instance you'll have to do the call separately or use WADO-URI.

**Comment by MathisGuilhin** [comment]
With the [DICOMWeb-client api](https://github.com/dcmjs-org/dicomweb-client/blob/master/src/api.js), I managed to retrieve DICOM binary instance with this method:

https://github.com/dcmjs-org/dicomweb-client/blob/5c1a0a0138b0a77db661df84a6ac80737668b7e1/src/api.js#L1121

But when I use ```retrieveSeries``` or ```retrieveStudy```, only the first instance of DICOM is readable.
Besides, is there a way to save a whole series in one DICOM File? 

Thank you!

**Comment by swederik** [comment]
Hmm that could be a bug with retrieveSeries and/or retrieveStudy, I did change those recently.

You can't get them in one file, retrieveSeries/Study with dicomweb-client should give you back a list of instances as arraybuffers though. If it's not doing that, we should create an issue there.

**Comment by MathisGuilhin** [comment]
It actually gives back a list of instances as arraybuffers, but only the first one is readable (or maybe im not doing it right).
A loop with instance should do the trick here, but it's still weird it isn't working though

**Comment by MathisGuilhin** [comment]
No, As I said I was only able to retrieve DICOM instances, but I haven't tried with all the recent commits you've made since

**Comment by swederik** [comment]
We should move this to dicomweb-client then. That sounds like an issue on that library.

**Comment by dannyrb** [comment]
https://github.com/dcmjs-org/dicomweb-client/issues/21
