### ISSUE TITLE
Few studies don't open with error in console

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#742]
Hi, 

This doesn't happen for every case but it is happening with 10% of the cases. I get some error in browser console (Screenshot attached)

I have added weasis in my dcm arc light server, its opening, I downloaded the zip from dcm, that is also opening in horos. Kindly look into this.

Thanks

Error:
![Error in console](https://user-images.githubusercontent.com/23245538/62157965-f95b8100-b32b-11e9-80f0-dfcffdfe9f56.png)

Case in DCM:
![Study in DCM](https://user-images.githubusercontent.com/23245538/62157978-06787000-b32c-11e9-89b0-106a060298f5.png)

Opening in weasis:
![Opening in weasis](https://user-images.githubusercontent.com/23245538/62157988-0e381480-b32c-11e9-8d29-dafa67da101a.png)

Dicom file in horos:
![Zip getting downloaded and is open in horos](https://user-images.githubusercontent.com/23245538/62157999-155f2280-b32c-11e9-8202-929e7e7b6a98.png)

**Comment by dannyrb** [comment]
Do you have a minimial reproduction, or a way for us to test and encounter this same case ourselves?

**Comment by bhavesh-pandey** [comment]
Hi Danny, I mailed you the info. Please check.
