### ISSUE TITLE
Reference lines React Version

### ISSUE THREAD

**Issue by jemin136** [OHIF/Viewers#747]
Hi

I was able to see Reference lines features in version 1 but seem it's  missing in version 2(React Version).

Thanks,
Jemin Patel

**Comment by swederik** [comment]
Yes that has not implemented yet. I'm closing this issue as a duplicate. Please at least try to do a basic search to check if there is already an open issue about your problem before opening a new one. See https://github.com/OHIF/Viewers/issues/619
