### ISSUE TITLE
Local PACS acting differently

### ISSUE THREAD

**Issue by MathisGuilhin** [OHIF/Viewers#749]
Hello team,

For my research work, I'm trying to deploy an OHIFViewer server in a hospital in France. 
Until now, I was using the virtual PACS that you propose (https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado), but now I'm trying to use the one in the hospital.

When I tried, this happened : 

![LocalPacsError](https://user-images.githubusercontent.com/45480583/62469248-2aa6d780-b798-11e9-9ad7-3b5ed1a703b8.PNG)

Then I tried to see the data at least in my browser without running OHIFViewer.
I see that when go at https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs/studies, I can see all the studies in a json format.

When I do the same thing with the hospital PACS, it downloads a mhtml file which looks like this : 

![localPacsHtml](https://user-images.githubusercontent.com/45480583/62469641-fb449a80-b798-11e9-83bc-58d129e48c93.PNG)

Is it possible that I don't have the right wadoroot? Otherwise, is there a way to make it works with OHIF?

Thanks again!

**Comment by pieper** [comment]
It looks like your PACS isn't providing the current DICOMweb version of WADO (or maybe you aren't accessing the right endpoint).  Probably you need to do some research about the PACS server or contact the vendor.

If you find that your PACS doesn't natively support the current DICOMweb standard, then you may want to set up a proxy that speaks traditional DICOM networking (DIMSE) to the PACS and DICOMweb to OHIF.  Google provides an open source implementation of that, but I can't put my fingers on a link to it right now.

**Comment by swederik** [comment]
Here it is: https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter

I'd be curious to hear about your experience using it.

**Comment by MathisGuilhin** [comment]
Hello guys,
I found out what was missing.
According to the DICOM CONFORMANCE STATEMENT of the PACS I'm using, the default response type is xml. I just had to add a accept header with json specified as a format like that : 

```javascript
headers.Accept = `application/json`;
```
in getAuthorizationHeader class. Now everything works fine ! 
Thank you for your answers
