### ISSUE TITLE
User forum link is broken

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#75]
When I try to follow the user forum link on the repo front page, I get "connection refused"

http://forum.ohif.org/

**Comment by swederik** [comment]
Hi Andrey,

Sorry about that. We killed off that forum a while ago in favour of the cornerstone-platform mailing list. The proper link is here: https://groups.google.com/forum/#!forum/cornerstone-platform and now I've fixed the link in the README.

Thanks!
