### ISSUE TITLE
Is it possible to modify ohif's configuration in its docker image after the build step?

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#751]
Hello, yesterday I tried to upgrade from version 1 to version 2. Since there is a docker image available, I tried to use this distribution method.

Unfortunately, I didn't find a way to modify basic configuration ( the ip address of the PACS server), without rebuilding the docker image from a modified Dockerfile.

I tried the following, as the documentation suggests at https://hub.docker.com/r/ohif/viewer, but it didn't work:

`
FROM ohif/viewer:v0.19.5.2049 

RUN rm /usr/share/nginx/html/config/*
ADD ohif.js /usr/share/nginx/html/config/default.js
`

The next thing I can try is modifying this line in the main image's Dockerfile:
https://github.com/OHIF/Viewers/blob/master/Dockerfile#L38

Or, alternatively, modifying the config file the Dockerfile refers to:
https://github.com/OHIF/Viewers/blob/master/public/config/default.js

After doing either, I would run the docker build command and I would have a docker image with my configuration baked in it, any time I needed to configure 

Before I proceed with this steps, I want to make sure whether there is a way to use ohif's docker image without cloning the repo and rebuilding the image.

Thank you.

**Comment by dannyrb** [comment]
@TZubiri, the web application pulls in `default.js` and uses the configuration it contains. That would be the approach I would recommend. If you're having issues getting it to work, chances are the documentation is slightly outdated -- possibly filenames or locations in the container.

It may be some time before I can look into the exact issue, but hopefully this info helps.

**Comment by TZubiri** [comment]
I'll go ahead and clone the repo and rebuild the image with my configuration.
If you want to look at this, I'd suggest you try to change something about the configuration with a new Dockerfile, like so:

`FROM ohif/viewer:latest
ADD customconfig.js /path/to/default.js`

I haven't been able to do so yet, I'll update this thread and the documentation if I manage to do it.

**Comment by TZubiri** [comment]
Solved!

I must have made a mistake before, because the Dockerfile I wrote in the OP worked fine:


> FROM ohif/viewer:v0.19.5.2049
> 
> RUN rm /usr/share/nginx/html/config/*
> ADD ohif.js /usr/share/nginx/html/config/default.js

I can even make of the config folder a volume and change the configuration without rebuilding my derived image or even restarting my container:

> sudo docker run -td -p 80:80 -v config:/usr/share/nginx/html/config myohif

Excellent job!

**Comment by mh33dev** [comment]
Although it's closed another approach. Mounting /usr/share/nginx/html to a external folder ./data or even only the required config file on the host in order to edit for example the app-config.js is possible, results however in an empty folder.
Solution:
1) Start Container without mounting the volume
2) docker cp CONTAINERNAME:/usr/share/nginx/html ./data
3) Stop container
4) edit app-config.js
5) Restart container mounting the volume

**Comment by TZubiri** [comment]
This seems solved, the docker page mentions:

"To configure The OHIF Viewer, you can replace the configuration file located at:

/usr/share/nginx/html/app-config.js with your own."

@mh33dev 
Could you test whether this official method works? I haven't used ohif in a while.
