### ISSUE TITLE
Clicking a series doesn't open it in the viewport. [v2.x]

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#752]
Instead, one must drag and drop the study into the viewport.

If I remember correctly, in the Meteor version, one could click (or double click) the thumbnail in the series vertical bar, and the series would appear in the viewport.

**Comment by dannyrb** [comment]
I agree that this would align better with the expected experience. My only call-out is that we need to be careful on touch devices to differentiate between a scroll and a tap.

**Comment by dannyrb** [comment]
Scoped and added to backlog: #895
