### ISSUE TITLE
Some documentation links are broken

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#754]
Some links in the following page https://docs.ohif.org/deployment/recipes/nginx--image-archive.html appear to be linking to itself, but with a # symbol appended at the end of the URL.

Examples are the links that correspond to the following words "HERE" "dockerfile" "config.js"

**Comment by TZubiri** [comment]
HERE probably linked to this docker compose setup https://github.com/OHIF/Viewers/tree/master/docker/Nginx-Orthanc

**Comment by dannyrb** [comment]
Small doc issues often slip through the cracks. Please feel free to make even very small PRs to update any issues you find. If you don't feel comfortable doing that, or if you're unsure of how to make something "right" or clearer, issues like this are a ton of help.

Thank you :pray:

**Comment by dannyrb** [comment]
A large number of these have been resolved in a recent PR. We're doing a more comprehensive document update after some straggling CI steps have been resolved. In the mean time, anyone and everyone is more than welcome to PR changes to the docs. Even small typos ^_^
