### ISSUE TITLE
Configuration OHIF to ClearCanvas Server

### ISSUE THREAD

**Issue by shree2695** [OHIF/Viewers#756]
Dear all,
I want to connect OHIF to clear canvas server. I am using latest OHIF Viewer. How to do configuration. I have used the following configuration file. Can you guide me the Configuration with ClearCanvas?  
window.config = {
	"servers": {
	"dicomWeb": [{
			"name": "ClearCanvas",
			"wadoUriRootNOTE" : "either this uri is not correct for wado-uri or wado-uri is not configured on ClearCanvas currently",
			"wadoUriRoot" : "http://172.16.4.150:1000/wado/SERVERAE",
			"qidoRoot": "http://172.16.4.150:1000",
			"wadoRoot": "http://172.16.4.150:1000/wado/SERVERAE",
			"qidoSupportsIncludeField": false,
			"imageRendering" : "wadouri",
			"requestOptions" : {
			"auth": "none:none",
			"logRequests" : false,
			"logResponses" : false,
			"logTiming" : false
			}	
		}],
	"dimse": [{
			"name": "ClearCanvas",
			"peers": [{
				"host" : "172.16.4.150",
				"port" : 104,
				"aeTitle" : "SERVERAE",
				"default" : true,
				"supportsInstanceRetrievalByStudyUid": false
			},
			{
				"host" : "0.0.0.0",
				"port" : 11112,
				"aeTitle" : "OHIFDCM",
				"default" : true,
				"server" : true
			}
		  ]
		}],
	},
	"defaultServiceType": "dimse"
}

thanks all.

**Comment by lam0620** [comment]
@shree2695 CC ImageServer doesn't support dicomweb.

Refer to https://github.com/OHIF/Viewers/issues/450

Or try it
https://github.com/sync-for-science/dcmrs-broker

**Comment by shree2695** [comment]
Thanks for your reply. Currently, I have implemented with ORTHANC server. I will try with the given link.
