### ISSUE TITLE
How can I change the default layout from 1x1 to 2x2?

### ISSUE THREAD

**Issue by MarlonLiu1991** [OHIF/Viewers#759]

**Comment by dannyrb** [comment]
This is not currently a feature. We have discussed more robust viewport/layout management, and even different layouts depending on the context (ie. loading an MR versus an US modality study).

If this is functionality you would like to add yourself, or if you would like to discuss potential implementations, please don't hesitate to reach out.

**Comment by MarlonLiu1991** [comment]
Thanks! I just want to add a feature to my own project descripted like this: after I click the data in studylist , four layouts should be displayed, they are coronal plane ,sagittal plane, axial plane, and leave a layout for future features.

**Comment by evren217** [comment]
@MarlonLiu1991 You can actually do it with [hanging protocol engine](https://github.com/OHIF/ohif-core/blob/master/src/hanging-protocols/ProtocolEngine.js), but there is no hanging protocol editor (GUI) like the one in v1.x yet, so you will need to define hanging protocols in JSON and initialize the engine with those protocols.

Hanging protocol data structure is the same with the one in v1.x, so as a workaround, you may create your hanging protocol and export it using hanging protocol editor in v1.x, then add it using [protocol store](https://github.com/OHIF/ohif-core/blob/master/src/hanging-protocols/protocolStore/classes/ProtocolStore.js) in v2.x

Also, we would be happy to accept any pull request implementing hanging protocol editor (GUI) like the one in v1.x

**Comment by MarlonLiu1991** [comment]
@evren217 Thanks for your advice!  I have  looked the "ProtocolEngine.js", but I have not find what I need, maybe it hard to me. When I look the OHIF/Viewers project, I found the "setMPRLayout.js" realizes the function of button "2D MPR" . After click "2D MPR", it shows three layout(1x3) with three views of the image data. I think if I can change the code in "setMPRLayout.js" to realize layout(2x2)?

**Comment by MarlonLiu1991** [comment]
Now I have realized the layout(2x2) setting, after click "2D MPR" , it shows four layouts(2x2). Can I change it to the default display(2x2) instead of having to click the "2D MPR"?

**Comment by dannyrb** [comment]
As far as I know, this is not something that is easily configurable today. Smarter and custom default/automatic layouts is something we would eventually like to add or accept a PR for.

**Comment by dannyrb** [comment]
Scoped and added to backlog: https://github.com/OHIF/Viewers/issues/901

**Comment by trung1704ptit** [comment]
Hi everyone, I try to implement hanging-protocol but I cannot find the way to do that,
Di you integrate it into project?
