### ISSUE TITLE
How can I load images in the Viewer from a CD/DVD (DICOMDIR)?

### ISSUE THREAD

**Issue by rallard71** [OHIF/Viewers#76]
In OHIF Viewer, is it possible to import and view images from a DVD (DICOMDIR) that are not stored in Orthanc?

**Comment by swederik** [comment]
We haven't built that yet, but it's something that's been discussed. I think it would be nice to be able to load local studies, but that requires building a directory scanner + filtering down to DICOM files before parsing them and loading them into the viewer. It's certainly possible, but not trivial.

**Comment by Shyam-thoughti** [comment]
Do we have this feature now?

**Comment by PunyFlash** [comment]
this feature should save my day...

**Comment by swederik** [comment]
You can use the drag/drop viewer but it needs some work: https://viewer.ohif.org/local

**Comment by PanchakshariPM** [comment]
On loading the DICOMDIR file on [https://viewer.ohif.org/local](url) , it's not loading any data. Instead, the viewer display's a blank screen.
