### ISSUE TITLE
Function getModalities()

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#760]
Hi,

While displaying Studylist, I got error at calling getModalities() line becuase CC ImageServer returns Modality (0008,0060) value = ""(empty) but it returns value of Modalities in Study(0008,0061) correctly.

```
...
   "00080060":{  
      "vr":"CS"
   },
   "00080061":{  
      "vr":"CS",
      "Value":[  
         "ES"
      ]
   },
...
```

The error at line "`if (modalities.Value.indexOf(value) === -1`)" because modalities.Value is empty.

I don't understand what are difference btw "`if (modalities.vr && modalities.vr === modalitiesInStudy.vr) {`" and its "`else`" in logic.

```
export default function getModalities(modality, modalitiesInStudy) {
  let modalities = {};
  if (modality) {
    modalities = modality;
  }

  if (modalitiesInStudy) {
    // Find vr in modalities
    if (modalities.vr && modalities.vr === modalitiesInStudy.vr) {
      for (let i = 0; i < modalitiesInStudy.Value.length; i++) {
        const value = modalitiesInStudy.Value[i];
        if (modalities.Value.indexOf(value) === -1) {
          modalities.Value.push(value);
        }
      }
    } else {
      modalities = modalitiesInStudy;
    }
  }
  return modalities;
}
```

What is wrong if you change getModalities() to as below

```
export default function getModalities(modality, modalitiesInStudy) {
  let modalities = {};

  if (modality) {
    modalities = modality;
  }

  if (modalitiesInStudy) {
    modalities = modalitiesInStudy;
  }
  return modalities;
}
```

**Comment by dannyrb** [comment]
The logic could definitely be a bit cleaner. I know we recently added tests for this, so it might be worth taking a stab at a refactor, so long as the tests pass or there's a good justification to add/remove some:

https://github.com/OHIF/ohif-core/blob/60ca6f075abd2d7588e0d0fec1505223c78cfae1/src/DICOMWeb/getModalities.test.js

Always happy to review PRs for stuff like this ^_^

I'm not an expert on DICOM tags _per se_, but `00080060` is [Type 1 required](https://dicom.innolitics.com/ciods/cr-image/general-series/00080060)? The assumption might be that it should always have a modality specified?

If there's a good reason to change this assumption, or if I'm misinterpreting the standard (not unlikely), then please feel free to weigh in.

**Comment by lam0620** [comment]
@dannyrb I rechecked the document. I think I should check CC source code because DICOM tags per se, but 00080060 is Type 1 required.

Thanks and closed!
