### ISSUE TITLE
overlay: A viewerport shows more than two images

### ISSUE THREAD

**Issue by IIAT-MR-XWW** [OHIF/Viewers#761]
We have a set of dicom data and labled data. We want to show them to same viewerport, so that we  can compare whether the lable image is accurate.
we dont know how to achieve this now，do you have any suggestions? thanks
![1565335934(1)](https://user-images.githubusercontent.com/52899958/62762210-2c83da00-babb-11e9-9377-23f92987d0d4.png)

**Comment by dannyrb** [comment]
Thanks for taking the time to create an issue ^_^
A few clarifying questions:

Do you have a minimal reproduction you can share on CodePen or CodeSandbox of what you have tried so far? Is the provided image what you're trying to achieve, or have already achieved? What format is your data in? Are there any desktop applications that model the behavior you're trying to achieve?

**Comment by pieper** [comment]
@IIAT-MR-XWW -

If your data is already DICOM SEG (or you are willing to convert it to a valid DICOM SEG) then OHIF will display it automatically.

For example the study for patient "f4aa242907c17eab660a3547a0ae78c3" on viewer.ohif.org has an MR brain segmentation as shown below.  Patient "Dummy" is another MR with SEG and patient "QIN-HEADNECK-01-0139" has PET with SEG overlays.  [This paper](https://peerj.com/articles/2057/) provides all the detail and background on the QIN-HEADNECK data, and [the dcmqi open source code](https://github.com/QIICR/dcmqi) can be used to convert standard research formats like nifti or nrrd into valid DICOM SEG.

Let us know how it goes for you.

![image](https://user-images.githubusercontent.com/126077/62807291-05310b00-bac3-11e9-8e49-ae33345c358c.png)

**Comment by IIAT-MR-XWW** [comment]
> Thanks for taking the time to create an issue ^_^
> A few clarifying questions:
> 
> Do you have a minimal reproduction you can share on CodePen or CodeSandbox of what you have tried so far? Is the provided image what you're trying to achieve, or have already achieved? What format is your data in? Are there any desktop applications that model the behavior you're trying to achieve?

Thanks for your reply. 
We just use [papaya](https://github.com/rii-mango/Papaya) to show our result. And we try to achieve this function  at OHIF-Viewer. Our original image and labled image are both DICOM format now.

**Comment by IIAT-MR-XWW** [comment]
@pieper 
Thanks for your suggestions. It's a good way to achieve "overlay" by generating  DICOM SEG. And it works out. 
And I am wondering if there are other ways to accomplish this function. Like using cornerstone to show overlay at canvas, so that we can modify the overlay if the segmentation has little error.
Do you have any suggestions? Thanks!

**Comment by pieper** [comment]
By modify do you mean edit the segmentation?  Yes, @JamesAPetts is working on the painting tools to support this.  So you get back a new DICOM SEG that is a modified version of the original.

**Comment by MarlonLiu1991** [comment]
@pieper @dannyrb   I have found a similar issue in the cornerstoneTools (https://github.com/cornerstonejs/cornerstoneTools/issues/1000). Can we realize the feature of 'multiple Layer per Stack' in OHIF/Viewers?

**Comment by dannyrb** [comment]
This issue is covered by @JamesAPetts's in-progress work to add `cornerstone-tools@4` segmentation tools and updates to the OHIF Viewer. The changes also include basic UX enhancements, like unifying `SEG` and `Series` thumbnails.

Rather than duplicate the scope for this in our backlog, I'm going to mark this question closed for the time being. As it's a larger change, we'll announce these changes when @JamesAPetts completes them. At that time, if there are enhancements/issues you would like to report, please don't hesitate to create new issues ^_^

**Comment by venkatesh-soulpage** [comment]
Hi, we've converted nifti mask file to dicom seg using rt-utils and tried to render in ohif viewer v2 & v3, but we are only getting a blank screen and the file is not being detected by the viewer. Please find the below link of dicom files with seg file for your reference.
https://drive.google.com/file/d/1sn-Niusgi2bbmrE5tk-oZsxwAi-vqr-r/view?usp=sharing
