### ISSUE TITLE
HTTPS for standalone usage

### ISSUE THREAD

**Issue by DICOMSOFT** [OHIF/Viewers#762]
Hello,

I want launch ohif with ssl certificate, but since the new version i can't do it.
I tried without success with webpack-dev-server.

Do you have an idea or solution please?

In anay case, thank you for your work.

**Comment by dannyrb** [comment]
@DICOMSOFT, I'm not entirely sure I follow. The OHIF Viewer is a collection of static assets. Whatever server is hosting the assets is responsible for SSL.

If you need your development instance to use SSL, you should be able to configure it using the instructions laid out here: https://webpack.js.org/configuration/dev-server/#devserverhttps

**Comment by omartoutounji** [comment]
@DICOMSOFT, you can run the `yarn run build:web` command in your OHIF application directory and then drag and drop the `build` folder to [Netlify Drop](https://app.netlify.com/drop), you'll get a deployed version with HTTPS.

If you're not happy with Netlify's default HTTPS settings you can easily change them, it's very user-friendly.
