### ISSUE TITLE
Element not enabled at Object.getEnabledElement for cine control

### ISSUE THREAD

**Issue by vicOnGit75** [OHIF/Viewers#774]
Application enters infinite loop of errors while returning to Study list during  cine  playback state: 
Uncaught Error: element not enabled at Object.getEnabledElement (:5000/static/js/0.chunk.js:134813) at getElementToolStateManager (:5000/static/js/0.chunk.js:158218) at Object.getToolState (:5000/static/js/0.chunk.js:158267) at CornerstoneViewport.updateViewportSpecificData (:5000/static/js/0.chunk.js:8294) at invokeFunc (:5000/static/js/0.chunk.js:3080) at trailingEdge (:5000/static/js/0.chunk.js:3125) at timerExpired (:5000/static/js/0.chunk.js:3113)
causing huge memory leckage/high CPU.
( problem with Object.getToolState (:5000/static/js/0.chunk.js:158267) at CornerstoneViewport.updateViewportSpecificData )

Not reproduced on viewer.ohif.org

**Comment by dannyrb** [comment]
@vicOnGit75 are you able to provide a minimal reproduction of this issue, or a way for us to verify/investigate?

**Comment by vicOnGit75** [comment]
-Clone /download OHIF viewer from GIT
-yarn install/start
- wado/qido roots- https://server.dcmjs.org/dcm4chee-arc/aets( default)
-choose RUBO XA- the last one
-Cine
-playback
-Studylist
--------->error loop/memory permanent reallocation

not hppened if  erform from viwer.ohif.org

**Comment by vicOnGit75** [comment]
I didn't monitor commits, but the version that I downloaded today hasn't this misbehavior.
IMO bug is fixed

**Comment by dannyrb** [comment]
This may have been fixed by a lifecycle change we made in `react-cornerstone-viewport`
