### ISSUE TITLE
Images not loading when running from systemd autostart

### ISSUE THREAD

**Issue by akosijoy** [OHIF/Viewers#78]
Hello,

Whenever i run the Viewer normally by running:

`"METEOR_PACKAGES_DIRS="../Packages" meteor --settings ../config/localDIMSE.json"`

in the OHIFViewer Directory. It works fine with no issue

Now, I created a startup script in systemd:

```
[Service]
WorkingDirectory=/opt/Viewers-master/OHIFViewer/
ExecStart=/usr/local/bin/meteor --settings ../config/localDIMSE.json --production
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=viewer
User=myuser
Environment=NODE_ENV=production
Environment=PWD=/opt/Viewers-master/OHIFViewer
Environment=PORT=3000
Environment=HTTP_FORWARDED_COUNT=1
```

When I go to port:3000, I can access the page normally, and I can see the list of images in the dcm server properly, but as soon as I open an image the image never loads (it just shows the spinning loading icon) and i get an error in the console that says:

```
Exception from Tracker recompute function:
84b0e402d163fe183ba8074f6307495edbeb3c49.js:3 
ReferenceError: OHIF is not defined
    at f.TemplateInstance.<anonymous> (84b0e402d163fe183ba8074f6307495edbeb3c49.js:216)
    at 84b0e402d163fe183ba8074f6307495edbeb3c49.js:95
    at Function.e._withTemplateInstanceFunc (84b0e402d163fe183ba8074f6307495edbeb3c49.js:95)
    at n (84b0e402d163fe183ba8074f6307495edbeb3c49.js:95)
    at f.View.<anonymous> (84b0e402d163fe183ba8074f6307495edbeb3c49.js:95)
    at n (84b0e402d163fe183ba8074f6307495edbeb3c49.js:94)
    at Object.o.nonreactive (84b0e402d163fe183ba8074f6307495edbeb3c49.js:34)
    at 84b0e402d163fe183ba8074f6307495edbeb3c49.js:94
    at Object.f._withCurrentView (84b0e402d163fe183ba8074f6307495edbeb3c49.js:94)
    at Object.f._fireCallbacks (84b0e402d163fe183ba8074f6307495edbeb3c49.js:94)
```

Would anybody be able to help me solve this problem as it is very difficult and confusing to trace? thank you.

**Comment by swederik** [comment]
That's interesting.. Can you see where it's trying to be used? Which template instance is it failing in?

**Comment by akosijoy** [comment]
thanks for the response. made an edit forgot to mention that it works fine if run normally. Here's the full log from when there's an error.

```
WorklistSearch
84b0e40….js?meteor_js_resource=true:243 

openNewTab                        84b0e40….js?meteor_js_resource=true:243 

worklist: Switching to tab: 5df521c1-e567-4424-a822-61de7b665081                  
84b0e40….js?meteor_js_resource=true:243 

getStudyMetadata: 1239.570068359375ms                84b0e40….js?meteor_js_resource=true:276 
OHIFViewer: Setting default ViewerData                     84b0e40….js?meteor_js_resource=true:3 

Exception from Tracker recompute function:
84b0e40….js?meteor_js_resource=true:3 ReferenceError: OHIF is not defined
    at f.TemplateInstance.<anonymous> (84b0e40….js?meteor_js_resource=true:216)
    at 84b0e40….js?meteor_js_resource=true:95
    at Function.e._withTemplateInstanceFunc (84b0e40….js?meteor_js_resource=true:95)
    at n (84b0e40….js?meteor_js_resource=true:95)
    at f.View.<anonymous> (84b0e40….js?meteor_js_resource=true:95)
    at n (84b0e40….js?meteor_js_resource=true:94)
    at Object.o.nonreactive (84b0e40….js?meteor_js_resource=true:34)
    at 84b0e40….js?meteor_js_resource=true:94
    at Object.f._withCurrentView (84b0e40….js?meteor_js_resource=true:94)
    at Object.f._fireCallbacks (84b0e40….js?meteor_js_resource=true:94)
```

So I'm assuming this means that it starts in the worklistSearch -> openNewTab -> worklist: -> getStudyMetadata then the error happens

**Comment by akosijoy** [comment]
sorry it might be a bit confusing. the 84b0e30.......js?meteor lines are the ones on the right side of the console linking to where the error is supposed to be. but I think they don't open actual lines in the code but rather lines to a generated code? I'm a bit confused as well as to how to debug this

**Comment by swederik** [comment]
Is this still happening? I guess it's a missing import.

**Comment by akosijoy** [comment]
sorry, I completely forgot about this. I was able to figure out that the cause for the problem was because I wasn't using the dcm4chee_redhat.sh to auto-start my dcm4che and instead created a bash script that used the run.sh instead. When I used the dcm4chee_redhat.sh properly, the ohif autostart worked with no issue. Thank you for the reply.

**Comment by swederik** [comment]
OK Thanks! I found a couple instances where the OHIF variable wasn't imported and fixed those just in case. Good sign that we need to get ESLint setup.
