### ISSUE TITLE
Undefined on saveEnable()

### ISSUE THREAD

**Issue by kusiroll** [OHIF/Viewers#786]
saveEnabled() {
        const server = OHIF.servers.getCurrentServer();
        return (server && server.type === 'dicomWeb');
    }
pls this issue is related to v1.x but its relevant to me because I am currently maintaining a site which works this. The above function returns undefined and this disables my save to Archive function and whole lot of other stuff. can anyone give me a brief on whats going on here?

**Comment by dannyrb** [comment]
It looks like your application's server config is being checked. If your server type supports DICOMWeb, then we know the save functionality is supported. If this is the case, then you likely just need to update the type property on your configuration?

Unfortunately, we don't have much bandwidth to support v1 questions and issues. We've built v2 to more easily major version updates moving forward. If this is a long-term project, I recommend migrating so you may continue to benefit from bug fixes, enhancements, and security updates.
