### ISSUE TITLE
How do I open OHIF to C-MOVE?

### ISSUE THREAD

**Issue by Vo-coder** [OHIF/Viewers#789]
Firstly I apologize for my low English knowledge.I'm a student. I want to get a study from my ClearCanvas server with OHIF viewer. I'm using clearcanvas for trial purposes. The Hospital server that I work on cannot use the WADO service. this application is taking study from my hospital smoothly. but I don't know how I can get it with the OHIF viewer. can you help me? thank you so much.

**Comment by pieper** [comment]
There's not a perfect answer for this at the moment, but you can see the suggestions here:

https://groups.google.com/forum/#!topic/cornerstone-platform/nKOwFTXIJKY

**Comment by Vo-coder** [comment]
I'm currently working on the solution @EmilOJ.
https://github.com/OHIF/Viewers/pull/191 

I've done the first step in the solution you've shared below.In addition, I've adapted the source code experiments you shared to my project. But I didn't understand the OHIFViewer / docker-compose.yml startup process and the continuation that you mentioned in step 2.Can you tell me how to make Linux in Ubuntu?

**Comment by pieper** [comment]
I wonder if #191 is still active - it was being built against the older OHIF.

**Comment by Vo-coder** [comment]
I'm just using a meteor version of 1.0 for this problem.

**Comment by EmilOJ** [comment]
#191 is unfortunately not active anymore since DIMSE support has been removed from OHIF.

**Comment by dannyrb** [comment]
As others have pointed out, when we dropped Meteor this feature became something we could no longer support. As it is a common ask, I am happy to accept documentation PRs that outline how one might go about adding support by leveraging other solutions.
