### ISSUE TITLE
Problem On Windows (FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory)

### ISSUE THREAD

**Issue by nh1984** [OHIF/Viewers#79]
Hi guys
I've installed NodeJS and Meteor.
In OHIFViewer folder I goto bin folder and Run ORTHANCDICOMWEB.Bat
It Starts Processing but It finish with following Error.
Would you please Help:
--------------------------------------------------------
`
D:\OHIFW\OHIFViewer>orthancdicomweb

D:\OHIFW\OHIFViewer>set METEOR_PACKAGE_DIRS=..\Packages

D:\OHIFW\OHIFViewer>meteor --settings ../config/orthancDICOMWeb.json
[[[[[ ~\D\OHIFW\OHIFViewer ]]]]]

=> Started proxy.
=> Started MongoDB.

Unable to resolve some modules:

  "jspdf" in /D/OHIFW/OHIFViewer/Packages/ohif-measurements/client/reports/base.js (web.browser)
  "chaijs~type-detect@0.1.1" in
/D/OHIFW/OHIFViewer/StandaloneViewer/SampleClientOnlyBuild/48eac8c64f443010750ab1b683a69e5f65dba791.js
(web.browser)
  "chaijs~assertion-error@1.0.0" in
/D/OHIFW/OHIFViewer/StandaloneViewer/SampleClientOnlyBuild/48eac8c64f443010750ab1b683a69e5f65dba791.js
(web.browser)
  "chai/lib/chai/utils/getPathInfo.js" in
/D/OHIFW/OHIFViewer/StandaloneViewer/SampleClientOnlyBuild/48eac8c64f443010750ab1b683a69e5f65dba791.js
(web.browser)
  "chai/lib/chai/utils/hasProperty.js" in
/D/OHIFW/OHIFViewer/StandaloneViewer/SampleClientOnlyBuild/48eac8c64f443010750ab1b683a69e5f65dba791.js
(web.browser)
  "chai/lib/chai/utils/type.js" in
/D/OHIFW/OHIFViewer/StandaloneViewer/SampleClientOnlyBuild/48eac8c64f443010750ab1b683a69e5f65dba791.js
(web.browser)
  "chaijs~deep-eql@0.1.3" in
/D/OHIFW/OHIFViewer/StandaloneViewer/SampleClientOnlyBuild/48eac8c64f443010750ab1b683a69e5f65dba791.js
(web.browser)
  "chai/lib/chai/utils/getPathValue.js" in
/D/OHIFW/OHIFViewer/StandaloneViewer/SampleClientOnlyBuild/48eac8c64f443010750ab1b683a69e5f65dba791.js
(web.browser)
  "chai/lib/chai/utils/getName.js" in
/D/OHIFW/OHIFViewer/StandaloneViewer/SampleClientOnlyBuild/48eac8c64f443010750ab1b683a69e5f65dba791.js
(web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save jspdf chaijs~type-detect@0.1.1 chaijs~assertion-error@1.0.0 chai chaijs~deep-eql@0.1.3

   Linking                                   /
<--- Last few GCs --->

  275917 ms: Scavenge 692.5 (730.2) -> 692.5 (730.2) MB, 1.1 / 0 ms (+ 3.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  276352 ms: Mark-sweep 692.5 (730.2) -> 692.5 (730.2) MB, 434.9 / 0 ms (+ 5.0 ms in 2 steps since start of marking, biggest step 3.0 ms) [last resort gc].
  276787 ms: Mark-sweep 692.5 (730.2) -> 692.2 (730.2) MB, 435.8 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 3FB6CC95 <JS Object>
    1: addMappingWithCode(aka addMappingWithCode) [C:\Users\EDP-Service\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\source-map\lib\source-node.js:~144] [pc=25280430] (this=3FB080DD <undefined>,mapping=1BAA0B81 <an Object with map 396FFB15>,code=3FB2A919 <String[1]: e>)
    2: /* anonymous */ [C:\Users\EDP-Service\AppData\Local\.meteor\packages\met...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

D:\OHIFW\OHIFViewer>`

**Comment by swederik** [comment]
I think you need to run:

````bash
meteor npm install
````

to install the required NPM modules first.

**Comment by nh1984** [comment]
@swederik 
Dear Erik
Thanks for Your prompt replay, I've tried that, it seems less error, but still some faults there. Would you please help:

`D:\OHIFW\OHIFViewer>meteor --settings ../config/orthancDICOMWeb.json
[[[[[ ~\D\OHIFW\OHIFViewer ]]]]]

=> Started proxy.
=> Started MongoDB.
   Building for web.browser                  |
<--- Last few GCs --->

  388601 ms: Mark-sweep 697.7 (741.3) -> 693.7 (737.3) MB, 747.9 / 1 ms [allocation failure] [GC in old space requested].
  389338 ms: Mark-sweep 693.7 (737.3) -> 693.7 (737.3) MB, 737.5 / 0 ms [allocation failure] [GC in old space requested].
  390085 ms: Mark-sweep 693.7 (737.3) -> 693.7 (737.3) MB, 746.6 / 1 ms [last resort gc].
  390835 ms: Mark-sweep 693.7 (737.3) -> 693.6 (737.3) MB, 750.9 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 2F96CC95 <JS Object>
    1: clone [C:\Users\EDP-Service\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\babylon\lib\index.js:~630] [pc=5065B574] (this=08825901 <a State with map 3A3988BD>,skipArrays=2F9080DD <undefined>)
    2: arguments adaptor frame: 0->1
    3: parseConditional [C:\Users\EDP-Service\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

D:\OHIFW\OHIFViewer>`

**Comment by swederik** [comment]
How much memory does your computer have?

**Comment by nh1984** [comment]
My system have 4 Gb Ram, and I monitor the system resources, during running project with meteor, it uses maximum 60% .

I'm wondered why this issue happen.

**Comment by nh1984** [comment]
Dear Erik

I've Re-Installed OS and The issue is solved. I'll go ahead and if any other issue I'll keep you posted.

**Comment by SANTHOSH-SJ** [comment]
> 
> 
> How much memory does your computer have?

i'm running on 8GB i5 win 10

**Comment by swederik** [comment]
You might need to set the TOOL_NODE_FLAGS environment variable to increase the memory available to the app while it builds: https://forums.meteor.com/t/meteor-wont-start-with-max-old-space-size-solved/44745/2

e.g. set NODE_OPTIONS=–max-old-space-size=8192

**Comment by SANTHOSH-SJ** [comment]
> 
> 
> You might need to set the TOOL_NODE_FLAGS environment variable to increase the memory available to the app while it builds: https://forums.meteor.com/t/meteor-wont-start-with-max-old-space-size-solved/44745/2
> 
> e.g. set NODE_OPTIONS=–max-old-space-size=8192


It shows this message
**node.exe: -max-old-space-size=8192 is not allowed in NODE_OPTIONS**

**Comment by SANTHOSH-SJ** [comment]
> 
> 
> You might need to set the TOOL_NODE_FLAGS environment variable to increase the memory available to the app while it builds: https://forums.meteor.com/t/meteor-wont-start-with-max-old-space-size-solved/44745/2
> 
> e.g. set NODE_OPTIONS=–max-old-space-size=8192


It shows this message
node.exe: -max-old-space-size=8192 is not allowed in NODE_OPTIONS
