### ISSUE TITLE
Improve user confidence that all advertised features work (E2E Tests)

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#793]
> This is a work-in-progress ticket. Please don't hesitate to weigh in.

[As part of a recent change](https://github.com/OHIF/Viewers/issues/528), we added a few small E2E tests to make sure we weren't accidentally publishing a very broken viewer. I'd like us to raise the bar higher and create tests that show that critical features and functionality are guaranteed to work for every build.

Testing all of these features will likely require more than one build. Identifying a good, small number, of "fake" product configurations + extension setups .

## Education

We want to make sure testing is easy and obvious for would-be contributors. Identifying good litmus tests, examples, or practices may help with that goal. I'm currently playing with a small _guide_ that would be added to our docs.

- [ ] [Contributing: Testing](https://github.com/OHIF/Viewers/blob/0a2acdf2a0cf20ee7775211c557deb3d1c872266/docs/latest/contributing/testing.md)

## Proposed Initial Tests

Please feel free to comment with additional features/functionality you believe should be tested. Even if they don't make this iteration, identifying community needs would be very helpful:

### Builds

- CommonJS: Bundled extensions
- CommonJS: Run-time extensions
- PWA: Bundled extensions (code-split)

### Extensions: Generic

- [ ] Toolbar Module can/is
    - [x] Fire commands
    - [x] Set the active tool
    - [x] Display the specified icon
    - [x] Leverage "built in" CINE show/hide
    - [ ] Only visible for global/specific viewport context
- [x] Side Panel Module can/is
    - [x] Adds menu option w/ specified icon
    - [x] When menu option is clicked, shows panel contents
    - [x] Closes/opens/transitions when we do X
    - [x] Is only visible if the specified context is active

### Extensions: Specific

- [ ] TODO: Identify and add critical tests for...
    - [x] Measurement's Panel Extension
    - [ ] VTK Extension
    - [ ] Microscopy Extension
    - [x] Cornerstone Extension
    - [ ] DICOM HTML Extension
    - [ ] DICOM PDF Extension

### Configuration

- [ ] Hotkey configuration can/is
    - [ ] Reflected in `UserPreferences` modal
    - [ ] Fire commands for single key
    - [ ] Fire commands for key combinations
- [ ] Expand: OpenID-Connect
- [ ] Expand: Google Cloud Healthcare Integration
- [ ] Expand: Internationalization

### App

- [ ] Thumbnail drag-n-drop loads series
    - [x]  MR/CT/SEG series (Cornerstone Extension)
    - [ ]  SR series (DICOM HTML Extension)
    - [ ]  DOC series (DICOM PDF Extension)
    - [ ]  SM series (Microscopy Extension)
- [ ] Expand: Routing works

**Comment by dannyrb** [comment]
Bad stale bot: https://github.com/OHIF/Viewers/commit/7bd1507a89b9e50f1101b7590824aec3e679d5cf

**Comment by mirnasilva** [comment]
**Test cases implemented:** ( #904 )
- Drag and drop thumbnail into the viewport
- Verify if thumbnails are being displayed
- Verify if side panels Series and Measurements are being displayed/hidden

> 
> ### Extensions: Generic
> * [ ]  Toolbar Module can/is
>   
>   * [ ]  Fire commands
>   * [ ]  Set the active tool
>   * [ ]  Display the specified icon
>   * [ ]  Leverage "built in" CINE show/hide
>   * [ ]  Only visible for global/specific viewport context
> * [x]  Side Panel Module can/is
>   
>   * [x]  Adds menu option w/ specified icon
>   * [x]  When menu option is clicked, shows panel contents
>   * [x]  Closes/opens/transitions when we do X
>   * [x]  Is only visible if the specified context is active
> 
> ### Extensions: Specific
> * [ ]  TODO: Identify and add critical tests for...
>   
>   * [ ]  Measurement's Panel Extension
>   * [ ]  VTK Extension
>   * [ ]  Microscopy Extension
>   * [ ]  Cornerstone Extension
>   * [ ]  DICOM HTML Extension
>   * [ ]  DICOM PDF Extension
> 
> ### Configuration
> * [ ]  Hotkey configuration can/is
>   
>   * [ ]  Reflected in `UserPreferences` modal
>   * [ ]  Fire commands for single key
>   * [ ]  Fire commands for key combinations
> * [ ]  Expand: OpenID-Connect
> * [ ]  Expand: Google Cloud Healthcare Integration
> * [ ]  Expand: Internationalization
> 
> ### App
> * [x]  Thumbnail drag-n-drop loads series
> * [ ]  Expand: Routing works

**Comment by dannyrb** [comment]
These are largely completed. We're continually improving out E2E and visual testing with more granular tickets.
