### ISSUE TITLE
Conflict With Bootstrap

### ISSUE THREAD

**Issue by mtm12** [OHIF/Viewers#796]
In a modal component I use bootstrap.min for formatting but bootstrap.min prevents the "More" toolbar button from opening the drop down. Does anyone know what the conflict is with bootstrap.min? Is there a way to import bootstrap.min and not conflict with the "More" drop down?

**Comment by dannyrb** [comment]
@mtm12, are you using `bootstrap` for a different application that embeds the viewer, or for a forked version of the viewer? I know we recently did some work so bootstrap would no longer be a required dependency, but any time you include external style scripts you risk conflicts.

I can suggest strategies based on what you're trying to achieve.

**Comment by mtm12** [comment]
The application is a forked version of the viewer. I use bootstrap to format the content of a modal window where the user selects imaging processing properties. Import bootstrap.min.css causes the conflict with the "More" toolbar button drop down.

**Comment by mtm12** [comment]
I recompiled bootstrap.css with the dropdown classes removed with this tool: https://getbootstrap.com/docs/3.4/customize/ . The "More" drop down works with this bootstrap. The files are attached if anyone needs them.
[bootstrap.zip](https://github.com/OHIF/Viewers/files/3532355/bootstrap.zip)

**Comment by dannyrb** [comment]
@mtm12, good catch :+1:
We should probably provide a similar ability for our classes, or to prefix all classes with a "vendor" prefix to reduce the chance of conflicts.
