### ISSUE TITLE
location of previous \public\config\default.js in ohif-viewer-0.50.7 source

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#798]
Hello,
         I'm having trouble figuring out how to build the new rebased source code of 0.50.7. Before what ever you wanted your default config to be you entered in \public\config\default.js but I cant seem to find that anywhere. Any help would be greatly appreciated.

**Comment by ranasrule** [comment]
Ok I think I found it....

 \platform\viewer\public\config\default.js

Is this correct?

**Comment by dannyrb** [comment]
If you haven't already, you may want to read this announcement:
https://github.com/OHIF/Viewers/issues/768

This repository's previous contents are now in `platform/viewer/*`
