### ISSUE TITLE
H5 Pacs Viewer To TCP Server

### ISSUE THREAD

**Issue by zhan2016** [OHIF/Viewers#80]
HI, I just strugglled to complish a printscu based on this h5 Pacs client. Is it possible? There is no TCP socket for me to connect and communicate with a printscp. Any suggestion? Best regard!

**Comment by radicalrob** [comment]
Hi.  That's cool.  I don't think there is a way to do that directly from the client.   You would need to run the PrintSCU code on the server.  So you would essentially make a meteor server method to pass the image data from the client to the PrintSCU.  Then from the server, you can communicate with the PrintSCP using TCP.

Have you considered contributing it back when it's done?

**Comment by zhan2016** [comment]
Thank you very much.It's my honor to  countribute back.
