### ISSUE TITLE
Option to open series directly in MPR mode

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#800]
Can an option to open a series directly in MPR mode be added somehow? Maybe using a URL pattern like **<base_url>/study/<studyInstanceUid>/series/<seriesInstanceUid>/mpr** ?

**Comment by dannyrb** [comment]
Related: https://github.com/OHIF/Viewers/issues/759

Are you interested in contributing this as a new feature? I think this is something we would be interested in supporting, but unless a contributor writes a PR, this would be low priority for us.

**Comment by MarlonLiu1991** [comment]
@ranasrule That's a good idea. Have you realized it?

**Comment by dannyrb** [comment]
Scoped and added to backlog: https://github.com/OHIF/Viewers/issues/901
