### ISSUE TITLE
Running viewer without an dicom-server?

### ISSUE THREAD

**Issue by kristofferlidman** [OHIF/Viewers#804]
Hi,

Not sure if OHIF is really right for me, but i'll try anyways: I want to use the viewer without any sort of dicom-server or anything like that. I just want the user to be able to click a button to open the default OS file selector, select a dicom-file and view it in the viewer. An alternative is that the viewer loads with a pre selected file from an url. Can that be done? And if so, what documentation should i look for?

I have read about the standalone viewer etc, but i'm not sure if it can do what i want...

Thanks!

**Comment by kristofferlidman** [comment]
@pieper Thanks! Will check it out.

@dannyrb I'm building a web based application were dicom files sometimes will be attached to database entries, and i want the user to be able to view the image directly in the app, instead of downloading it and viewing it in an external program.

**Comment by drsherifk** [comment]
I was wondering how about adding support of viewing zip archives like the one exported from orthanc contain dicomdir or maybe with additional metadata file like the standalone viewer.
I think there is a user on the support group that shows a good working modefied wadoimageloader with the name of archiveimageloader that can load images from zip archives, maybe it would be useful to use it without much modification to the viewer

**Comment by dannyrb** [comment]
This may be of some benefit to you if your data isn't coming from a traditional PACS:

https://github.com/OHIF/Viewers/issues/733

**Comment by vnarepalepu** [comment]
Hi, 

I've noticed that the dicom files are server through the configuration within a json file. I am looking for the same but we have all the dicom files zipped up with the below folder structure within our filesystem on centos. This file system path is accessible to the public through the url:
**/[FileSystemPath]/MRI/dsr_24/T1w/run_2/raw/folder.zip** 
.zip contains all the .dcm files. 

So can I use OHIF Viewer to open the dIcom files by directly referring to the url as 
**http://hostname:3000?url=hostname/FileSystemPath/UnzippedFolderContainingDicoms**
or is it necessary to create a json in a definite format to include all these dicom files path? 

Appreciate any suggestions on these that would help us decide if OHIF is right for us. 

Thanks

**Comment by dannyrb** [comment]
@vnarepalepu, you may want to create a new issue.
We don't often revisit closed issues; open issues are kind of a running "todo list" for us.

Unfortunately you can't just point the app at a publicly accessible folder of DICOMs.

You can use our drag-n-drop local viewing functionality:

- https://viewer.ohif.org/local

Or you can create JSON/schema the viewer can use in lieu of a public DICOMWeb instance. However, all files would still need to be accessible using web requests; the browser does not have permission to access files on the local system unless initiated by the user (file input, drag-n-drop, etc)

I don't know your requirements, but standing up a local PACS may be to your benefit. There are ready made docker images that simplify things quite a bit.

**Comment by vnarepalepu** [comment]
Thanks @dannyrb. Sorry about commenting here on closed ones. I did create a new issue #939 and did/was not getting a response.
