### ISSUE TITLE
Support zip archives

### ISSUE THREAD

**Issue by drsherifk** [OHIF/Viewers#815]
I think loading study files from web servers or file hosting services as one zip file would be more practical and efficient than loading file by file specially in bad network areas and for security reasons.

I was wondering how about adding support of viewing zip archives like the one exported from orthanc contain dicomdir or maybe with additional metadata file like the standalone viewer.

I think there is a user on the support group that shows a good working modefied wadoimageloader with the name of archiveimageloader that can load images from zip archives, maybe it would be useful to use it without much modification to the viewer

**Comment by dannyrb** [comment]
https://viewer.ohif.org/local

We would take a PR to support DICOMDir zip from the local file system; but this is not something we have the bandwidth to prioritize adding support for at this time.

**Comment by spideep** [comment]
Is this still a pending feature?
