### ISSUE TITLE
I try to some highlight nodule data on the image. so how can I highlight some pixel data? 

### ISSUE THREAD

**Issue by viss3595** [OHIF/Viewers#825]
Hello Team,

In my case, I want some highlight the data using some pixel data. If possible, how I can develop. Ohif is existed Brush Tool but I want to draw using pixel data.

**Comment by dannyrb** [comment]
@viss3595 what have you tried? What was the expected result versus the actual result? In particular, why does the brush tool not work for you? Have you tried "painting" by updating its internal representation (which is essentially against the pixels)
