### ISSUE TITLE
build version the viewer

### ISSUE THREAD

**Issue by hisham1184** [OHIF/Viewers#826]
The development run is good but when i build the viewer i get the following error as in img:
the first page displayed good but any http request get this error.
I'm useing windows 10 , orthanic   
![image](https://user-images.githubusercontent.com/54667796/63933056-2dc47900-ca61-11e9-9300-a953beb85512.png)

any help please

**Comment by dannyrb** [comment]
It looks like the request may not be reaching your PACS. What does your Orthanc setup, OHIF Viewer config, and server configuration look like?

**Comment by hisham1184** [comment]
thank you for res.
this is default config for viewer:
window.config = {
  routerBasename: '/',
  showStudyList: true,
  servers: {
    dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: '/wado',
        qidoRoot: '/dicom-web',
        wadoRoot: '/dicom-web',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        requestOptions: {
          requestFromBrowser: true,
        },
      },
    ],
  },
};

this is viewer proxy:
 "proxy": "http://localhost:8042",
the local Orthanic installed as default and use port 8042

**Comment by hisham1184** [comment]
when i modify config to :
        wadoUriRoot: 'http://localhost:8042/wado',
        qidoRoot: 'http://localhost:8042/dicom-web',
        wadoRoot: 'http://localhost:8042/dicom-web',

i get CORS Error:
![image](https://user-images.githubusercontent.com/54667796/64091643-cb69c200-cd59-11e9-98c8-b10b90f8e6c7.png)

**Comment by hisham1184** [comment]
I use development ver. now, 
is there is any way to solve CORS problem.

I'll  operate the system in 8 hospitals and more in my region.

**Comment by dannyrb** [comment]
> "proxy": "http://localhost:8042",

Is a legacy of an older version of our application. Please set `PROXY_TARGET` and `PROXY_DOMAIN` environment variables to resolve during development.

For production, you will need to set appropriate CORS headers yourself.

**Comment by hisham1184** [comment]
Thank for you
Where, and how I can set CORS headers.pls
Thanks

**Comment by dannyrb** [comment]
In production? It depends. Generally via configuring your web server, and it varies by server.

https://enable-cors.org/

In dev? Set the env variables I've indicated above.
