### ISSUE TITLE
Series Sidebar never opens - BUG

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#83]
I downloaded new release built on meteor 1.5.  I'm using **Standalone** Viewer.

I set the **leftSidebarOpen** to true in **Server.js** file.  I gave it a try to make sure that the leftSidebar stays open under localhost:3000/testDICOMs.  To my surprise it was intermittent. In other words, sometime the leftSidebar would be open when I open my browser and sometime it would not be open when I open my browser.  And when it was not opened the toggle button would **not** make it open upon clicking.

I moved forward and created a client build.  But client build never showed the leftSidebar even by clicking the toggle button.

Many thanks!

**Comment by vas1468** [comment]
same problem here :( - I don't have the time to investigate more atm. richsmith123 if you manage to fix it please share :)

**Comment by ayselafsar** [comment]
Iron Router overwrites template data (as well as state reactive-dict) when it's called multiple times if state reactive-dict is assigned to template data. state reactive-dict is assigned to template instance instead of template data to fix this issue.

**Comment by radicalrob** [comment]
@richsmith123 - can you confirm the fix?  If it's good, please close this issue.  Thx.

**Comment by richsmith123** [comment]
Hi Rob, 

I ran couple of test and it looks good.  I will let you know if I run into any issue on my thorough testing.  

Many thanks for looking into this.  Much appreciated!

Warm regards,
Rick
