### ISSUE TITLE
How can I open Modal Popup by clicking Toolbar menu Button?

### ISSUE THREAD

**Issue by Vishal568** [OHIF/Viewers#832]
I want open Modal by clicking toolbar menu like Boostrap Modal. Is it possible to show Modal by clicking toolbar menu? If possible Which steps I follow for this kind of changes.

**Comment by dannyrb** [comment]
@Vishal568 today there is not a great option outside of modifying `platform/viewer`. I'll create a new issue to add support for a "ModalModule" that will allow you to register new ones, get the state of current "modals", and open/close it by name.

**Comment by dannyrb** [comment]
Tabled. We've been discussing internally about how to improve this; but I'm not sure I have enough information to type anything up yet. This has gone stale, but if anyone really wants to see this done, feel free to reach out and I can assist with your PR draft.

**Comment by dannyrb** [comment]
We now have a `UIModalService` for this behavior: https://docs.ohif.org/services/ui/ui-modal-service.html
