### ISSUE TITLE
Limitation on loading files size in local mode

### ISSUE THREAD

**Issue by vicOnGit75** [OHIF/Viewers#848]
While trying to upload  files greater than ~10MB in server/Local

get exception:
Uncaught (in promise) RangeError: Source is too large
    at Uint8Array.set (<anonymous>)
    at ReadBufferStream.concat (webpack:.../node_modules/dcmjs/build/dcmjs.es.js?:855)
Problematic files is XA cine.    
Files ~0.5 MB/single frames are loaded successfully.

**Comment by swederik** [comment]
I just tried this with a 28mb mammogram and everything worked fine. Could you de-identify your dataset and share it? Does it work if it is uploaded to a PACS first?

**Comment by vicOnGit75** [comment]
Just before anonimaization:
-files was multiframe XA and it was applied directly from local disk.

**Comment by vicOnGit75** [comment]
Thanks for the fast response!

**Comment by vicOnGit75** [comment]
It worked while provided by WADO-RS

**Comment by swederik** [comment]
Good to know. It might be an issue with multiframe images on the local viewer. I notice that the multiframe images I am testing are not working either (the ?frame=N is probably not being added to the imageId). They aren't crashing, though.

**Comment by vicOnGit75** [comment]
Please see uploaded problematic file at https://github.com/vicOnGit75/TmpStorage;
Anyway I guess this behavior you watched- not crashing, but not exiting from uploading state with
error :Uncaught (in promise) RangeError: Source is too large
at Uint8Array.set ()
...
in console.

**Comment by dannyrb** [comment]
@vicOnGit75 what browser are you using? I think the max array size may be lower depending on your browser vendor.

**Comment by vicOnGit75** [comment]
on my chrome 76
 i get
> window.performance.memory.jsHeapSizeLimit
2197815296
Should I check smth else?
