### ISSUE TITLE
Can they access specific study (http://.../Viewer/StudyUID)?

### ISSUE THREAD

**Issue by vicOnGit75** [OHIF/Viewers#849]
Exception:
 Uncaught TypeError: Cannot read property 'hotkeys' of undefined   at _initExtensions (webpack:///./App.js?:238)
in case I run vs build locally.

Configuration" showStudyList" setting doesn't influence. A regular entry by StudyList works fine.

Works properly with viewer.ohif.org

**Comment by swederik** [comment]
I do not understand the question. Yes there is a route for that: https://viewer.ohif.org/viewer/1.3.6.1.4.1.14519.5.2.1.2744.7002.373729467545468642229382466905

`showStudyList` configuration determines whether or not the study list is available at all.

**Comment by vicOnGit75** [comment]
Yes, this the problem:
It works fine with https://viewer.ohif.org,
but not with server build locally ( both prod or dev environments)

**Comment by dannyrb** [comment]
> but not with server build locally ( both prod or dev environments)

Please provide a reproduction.

**Comment by vicOnGit75** [comment]
-clone/download
-yarn install
-yarn start
-http://localhost:3000/
-Choose study from list ( any) & click ( for example 1.2.276.0.50.192168001099.7810872.14547392.270 from DCM4CHEE)
- image is displayed
-open new tab
- select  same study (http://localhost:3000/viewer/1.2.276.0.50.192168001099.7810872.14547392.270)

Result : black screen with 
error
Cannot read property 'hotkeys' of undefined
    at _initExtensions (webpack:///./App.js?:238)
...
in console

**Comment by dannyrb** [comment]
I was unable to reproduce. If you're still having this issue, please let me know.
