### ISSUE TITLE
Is there a dicom conformance statement or list of supported Syntax transfers?

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#853]
We are a small team with limited resources. Your question is much more likely to
be answered if it is
[a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

I wanted to check what transfer syntaxes are accepted by OHIF, but I couldn't find any Dicom conformance statement. Thanks to the monorepo branch, I was able to find that transfer syntax is handled by the [Cornerstone Wado Image Loader dependency](https://github.com/cornerstonejs/cornerstoneWADOImageLoader) . I couldn't find a Conformance statement in there either.

**Comment by dannyrb** [comment]
This is the closest thing we have:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/docs/TransferSyntaxes.md

Is there specific information you are looking for or think would be valuable to document?

**Comment by TZubiri** [comment]
Thank you! My search parameters must have grazed this file in the cornerstone repo.

I opened this because someone in a dcm4che group was trying to use compression. https://groups.google.com/forum/#!forum/dcm4che

[ I remember trying this in the meteor version a while back](https://github.com/OHIF/Viewers/issues/357) but decided against it because it required a level of skill I did not have.

I think configuration options would be a good place to focus regarding documentation. If I found a list of  all configuration options, I could quickly check whether alternate TransferSyntaxes are easily configurable, and move on if not.

**Comment by swederik** [comment]
You should be able to configure the WADO Image Loader (as here: https://github.com/crowds-cure/cancer/pull/24/files#diff-30a5f46d2481f3745ed7cc8070f71a04R40) to request a specific transfer syntax but we have not added any configuration for that at the OHIF level. That would be a good idea.

I agree we should write a DICOM Conformance statement for OHIF, and probably also for the WADO Image Loader itself.
