### ISSUE TITLE
What are all the possible configuration options?

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#854]
Greetings, I write with this very innocent question that might arise from the perspective of a non technical user. However I will provide some insight from what I gathered by looking at the source code.

I couldn't find a list of all the configuration options available in the docs, there is a sample file, but it doesn't include all the possible options. So I'm assuming there's some other options hidden.

I tried looking in the source code for some file that acts as a de facto schema for the options configuration file, like a config parser would be, but it appears that due to the dynamic nature of javascript this doesn't exist, options are consumed by the respective module that needs them, and deeply nested configuration options might only appear in deeply nested call stacks. This is fine, it's ok to encapsulate these otherwise global user-provided variables, but I kind of hoped there would be a single point where all such variables would explicitly converge.

Here is an example of an option that is hidden deep in a call stack, and nowhere else:

https://github.com/OHIF/Viewers/blob/8c3b7c85735176a7d30c9b37099c9435ed1ccc00/platform/core/src/studies/services/qido/studies.js#L121
https://github.com/OHIF/Viewers/blob/8c3b7c85735176a7d30c9b37099c9435ed1ccc00/platform/core/src/studies/searchStudies.js#L20
https://github.com/OHIF/Viewers/blob/8c3b7c85735176a7d30c9b37099c9435ed1ccc00/platform/viewer/src/studylist/StudyListWithData.js#L82
https://github.com/OHIF/Viewers/blob/8c3b7c85735176a7d30c9b37099c9435ed1ccc00/platform/viewer/src/App.js#L83
https://github.com/OHIF/Viewers/blob/8c3b7c85735176a7d30c9b37099c9435ed1ccc00/platform/viewer/src/index.js#L47

With the current codebase, how would you go on about enumerating all configuration options?

**Comment by swederik** [comment]
Yeah we used to have a schema that defined all of the configuration options (https://github.com/OHIF/Viewers/blob/v1.x/Packages/ohif-servers/both/schema/servers.js) but most of these are now out of date.

There is a ticket to clean up the configuration that is ongoing (https://github.com/OHIF/Viewers/pull/852). I agree we need to find a good place to document these that will stay in sync with the code. Maybe just documented in propTypes for the App component.

**Comment by dannyrb** [comment]
Related: https://github.com/OHIF/Viewers/issues/739

**Comment by dannyrb** [comment]
Scoped and added to backlog: #892
