### ISSUE TITLE
Local viewer does not display multiframe DICOM instances properly

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#855]
Related: https://github.com/OHIF/Viewers/issues/848, https://github.com/OHIF/Viewers/issues/539

Here is a multiframe MR displayed in the viewer: https://viewer.ohif.org/viewer/1.3.6.1.4.1.5962.99.1.3814087073.479799962.1489872804257.3.0

When you load the same image on https://viewer.ohif.org/local it does not display correctly. This is probably because [`filesToStudies` ](https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/lib/filesToStudies.js) is not adding the frame parameter to the end of the imageIds when creating images from the multiframe instance. I don't think `filesToStudies` has any logic for multiframe data at all right now.

Here is a multiframe you can use for testing: https://www.dropbox.com/s/gkazkv95qsxylea/multiframe.dcm?dl=0

See:
https://github.com/OHIF/Viewers/blob/master/platform/core/src/utils/getImageId.js#L22
https://github.com/OHIF/Viewers/blob/master/platform/core/src/utils/getWADORSImageId.js#L1

**Comment by ladeirarodolfo** [comment]
Loading local multiframe will be covered on:[https://github.com/OHIF/Viewers/issues/838](#838 )

**Comment by swederik** [comment]
Closing because this was fixed by @ladeirarodolfo
