### ISSUE TITLE
Issue when running OHIF Viewer in windows

### ISSUE THREAD

**Issue by djones4487169** [OHIF/Viewers#86]
Done this from inside OHIF Viewer:

>set METEOR_PACKAGE_DIRS="..\Packages"
>meteor --settings ..\config\orthancDICOMWeb.json

=>Started MongoDB
Building package ohif:core (OK)
Building package ohif:log (freezes here)

builds ohif:core OK but then hangs on ohif:log whilst Building packages?? Oblique sign (/) is spinning as though it is doing something but I have left it running for over half hour can't be right?

Any ideas?

**Comment by radicalrob** [comment]
Did you solve this or is it still happening?
