### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#863]
Getting an error 

Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 402653184, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 

on opening few studies, on searching I found that it might be a possible memory leak
(https://github.com/diegomura/react-pdf/issues/314) (https://github.com/diegomura/react-pdf/pull/591)

![Screenshot 2019-09-05 at 12 37 50 AM](https://user-images.githubusercontent.com/23245538/64283858-e87adc80-cf75-11e9-815c-01a926e3fba7.png)

**Comment by dannyrb** [comment]
Steps to reproduce?

**Comment by bhavesh-pandey** [comment]
Is there any server where I can send the images for this issue? Or I can also share the zipped dicom file. Let me know what works.

**Comment by bhavesh-pandey** [comment]
This opens perfectly in weasis

**Comment by dannyrb** [comment]
Does the image open fine in our local viewer? https://viewer.ohif.org/local
What kind of image are you trying to open?
What output do you see when using https://rawgit.com/cornerstonejs/dicomParser/master/examples/dumpWithDataDictionary/index.html ?

**Comment by bhavesh-pandey** [comment]
Not opening in local viewer

![Screenshot 2019-09-05 at 1 39 44 AM](https://user-images.githubusercontent.com/23245538/64287739-22e87780-cf7e-11e9-915f-57423e16b3a3.png)

At ragwit - Status: Error - dicomParser.readPart10Header: DICM prefix not found at location 132 - this is not a valid DICOM P10 file. (file of size 28.865 MB )

**Comment by bhavesh-pandey** [comment]
I have an old dcm4chee-web3 server which is connected with Oviyam viewer, I sent this study to that and it open properly there

![Screenshot 2019-09-05 at 1 44 27 AM](https://user-images.githubusercontent.com/23245538/64288067-c33e9c00-cf7e-11e9-889d-5b8bbb0be557.png)

**Comment by bhavesh-pandey** [comment]
> What kind of image are you trying to open?

This is CR Mammo

**Comment by bhavesh-pandey** [comment]
I have anonymised it an uploaded the dicom file on drive

https://drive.google.com/file/d/1iuPTjSzrUqzP_QY5laKCS524pdNxIuYn/view?usp=sharing

**Comment by dannyrb** [comment]
:mans_shoe: :dash: :robot:

**Comment by dannyrb** [comment]
I don't know that we have the bandwidth to address this issue directly. We do have some long term enhancements for our image cache management and image loader decoding, but I can't guarantee those are near future.

If anyone wants to spike a change, I can provide guidance.

**Comment by dannyrb** [comment]
Stale issue. We don't have the bandwidth to address this. If someone is able to pinpoint the cause, or would like to spike a PR, please don't hesitate to reach out.
