### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#865]
This error comes for almost 10% of the studies coming to our server. Its reproducible by sending the same image to any dcm4chee-arc light server. Let me know where can I send the images for reproducing the issue.

![Screenshot 2019-09-05 at 1 08 42 AM](https://user-images.githubusercontent.com/23245538/64285845-fd596f00-cf79-11e9-8d43-383141d8610a.png)

**Comment by bhavesh-pandey** [comment]
This opens perfectly in weasis

**Comment by dannyrb** [comment]
Does the image open fine in our local viewer? https://viewer.ohif.org/local
What kind of image are you trying to open?
What output do you see when using https://rawgit.com/cornerstonejs/dicomParser/master/examples/dumpWithDataDictionary/index.html ?

**Comment by bhavesh-pandey** [comment]
not opening in local viewer 

![Screenshot 2019-09-05 at 1 48 11 AM](https://user-images.githubusercontent.com/23245538/64288255-3ea04d80-cf7f-11e9-8d69-0ea95d75c077.png)

rawgit: Status: Error - dicomParser.readPart10Header: DICM prefix not found at location 132 - this is not a valid DICOM P10 file. (file of size 28.865 MB )

I sent the case to old dcm4chee-web3 server which is connected with an oviyam viewer, where it opens properly, in my local horos viewer also the study is opening

![Screenshot 2019-09-05 at 1 49 46 AM](https://user-images.githubusercontent.com/23245538/64288390-96d74f80-cf7f-11e9-911f-56c8df1df676.png)

![Screenshot 2019-09-05 at 1 50 33 AM](https://user-images.githubusercontent.com/23245538/64288393-9a6ad680-cf7f-11e9-9649-747b2879f87f.png)

**Comment by bhavesh-pandey** [comment]
> What kind of image are you trying to open?

This one is CT Abdomen

**Comment by bhavesh-pandey** [comment]
I have anonymised the study and uploaded it on drive

https://drive.google.com/file/d/1sLCKsEO37-yI4v_LlZIKh9w28Ctst43e/view?usp=sharing

**Comment by bhavesh-pandey** [comment]
Found the issue. Few patient protocol images doesn't have Value in 00081155 sequence. Just added a check to prevent UI from crashing in https://github.com/OHIF/Viewers/pull/921

**Comment by swederik** [comment]
Sounds like we can close this. Thanks @bhavesh-pandey!
