### ISSUE TITLE
Too much memory usage after adding compression syntax in accept header

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#869]
We recently added JPEG 2000 Lossless compression to our dcm4chee-arc-light server so now all the images are getting compressed as soon as they are coming to the server. And I have also added the 'multipart/related; type="image/jp2"' in the accept header as advised here (https://github.com/OHIF/Viewers/issues/357) which links to (https://github.com/crowds-cure/cancer/pull/24/files)

After adding this header, the images are loading with lightening speed but now every browser tab takes about 1 GB of memory (Google Chrome Helper (Renderer) process). 

![Screenshot 2019-09-05 at 9 06 52 PM](https://user-images.githubusercontent.com/23245538/64357222-ebcba200-d021-11e9-9260-b292d31c7564.png)
Here I have opened 6 tabs which is taking more than 7 GBs of memory 

In systems with low RAM, browser page starts giving error 'Not enough memory to open this page' after opening 3-4 tabs together. In tabs and mobile devices even opening one study is giving memory error sometimes.

Is there any configuration in viewer's code which we can do to resolve this?

**Comment by dannyrb** [comment]
@bhavesh-pandey, not that I'm aware of. Memory issues can be a pain to track down. The Cornerstone LRU Cache should prevent your memory from ballooning to that size. If the only change is the transfer syntax / decoder used, it could be an issue with that codec's decode in the CornerstoneWadoImageLoader.

I vaguely remember some users having better luck with the `dynamic memory` version of that decoder, and/or killing webworkers periodically after they had processed X images or become idle.

**Comment by dannyrb** [comment]
This has gone stale, so I'm going to close it. A small reproduction in the `cornerstone-wado-image-loader` repo would go a long way towards moving us closer to a solution here. As would automating the decoder creation from OpenJPEG with Emscripten w/a docker container.
