### ISSUE TITLE
Error when running meteor on windows

### ISSUE THREAD

**Issue by djones4487169** [OHIF/Viewers#87]
See attached error message that occurs after the line:

>meteor --settings ../config/OrthancDICOM.json

Any ideas anyone?

![error](https://user-images.githubusercontent.com/20462692/27765260-ff044d54-5ea4-11e7-86b1-698c0a67e5e6.jpg)

**Comment by radicalrob** [comment]
I've not seen this error before.  

Try deleting the .meteor/local folder (see here: [https://stackoverflow.com/questions/40560723/meteor-windows-10-error-eperm-operation-not-permitted-unlink-dev-bundle](url)
