### ISSUE TITLE
why there's no free hand tool for the master version?

### ISSUE THREAD

**Issue by zhaoyu162** [OHIF/Viewers#875]
**Description**

Hello everybody, I feel weired that i found there are two demo online versions of OHIF viewers.
One is 0.1.9 which has free hand tool, the other is 0.19.6, which does not, what are the differences between them?
And the master version has no free hand tool, can any one tell me why, thanks.

**Comment by dannyrb** [comment]
👋 Hi @zhaoyu162, there are a lot of tools we could include. We incorporate the most popular ones in the demo, but otherwise try to make it easy to modify/configure which tools should be available.

I'm not sure I understand the version numbers you're using.
