### ISSUE TITLE
OHIF & Eclipse (or other IDE)

### ISSUE THREAD

**Issue by djones4487169** [OHIF/Viewers#88]
Does anybody know how I can import this project into Eclipse IDE to develop the software further? Or any other IDE to get things up and running for development?

**Comment by radicalrob** [comment]
We use WebStorm.  I don't know anyone who uses Eclipse for it

**Comment by djones4487169** [comment]
Thanks for the replies - about WebStorm can the downloaded repo be
integrated straight into a WebStorm project that I can edit, run and
display? Do I need anything else running installed alongside WebStorm?
