### ISSUE TITLE
OHIF: Cannot view CR image

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#89]
It is OK if view CT image. But I can not view CR image. Viewer is in loading....

Error: Uncaught TypeError: Cannot read property '0' of undefined

Anyone help me.

Please refer attachment.
![ohif_cr](https://user-images.githubusercontent.com/12405565/28113573-4965129a-6727-11e7-93ca-c69af2880d68.png)

**Comment by radicalrob** [comment]
This looks like there is something missing from the CR image which probably exposed a bug.  Is the image anonymized?  Can you post it?

**Comment by lam0620** [comment]
Thank you for your quick response. 
Yes, it is anonymized image.

Please find attachment test CR image
[1.2.840.114257.42903.2015122103590801842.1.1.1.dcm.zip](https://github.com/OHIF/Viewers/files/1141792/1.2.840.114257.42903.2015122103590801842.1.1.1.dcm.zip)

**Comment by ayselafsar** [comment]
This issue is fixed by cornerstoneWADOImageLoader PR #117: https://github.com/chafey/cornerstoneWADOImageLoader/pull/117

**Comment by lam0620** [comment]
Excellent!
Thank you so much.
