### ISSUE TITLE
Why introduce a third-party plugin core-js will throw some errors

### ISSUE THREAD

**Issue by JenayLee** [OHIF/Viewers#897]

**Comment by swederik** [comment]
I do not understand what you are asking for. Are you having issues with something? On a specific browser? What type of errors? Please provide more information.

**Comment by JenayLee** [comment]
![image](https://user-images.githubusercontent.com/25001032/64512762-a527c180-d319-11e9-8002-3ca313ad4d8d.png)
![image](https://user-images.githubusercontent.com/25001032/64512838-d0121580-d319-11e9-85e2-e2709176549a.png)
As above, there are no extra operations

**Comment by dannyrb** [comment]
@JenayLee we're leaning toward `core-js` over something like pollyfill.io. did you have thoughts or want to weigh in? Worth noting that the needs of users leveraging our UMD build versus our PWA build are different.

**Comment by JenayLee** [comment]
@dannyrb @swederik Thank you for your answer
