### ISSUE TITLE
What is the data of the mht file, where can I find the parsing of its data?

### ISSUE THREAD

**Issue by JenayLee** [OHIF/Viewers#898]
![image](https://user-images.githubusercontent.com/25001032/64523838-c72c3e80-d32f-11e9-84e2-51b51a1ce367.png)

**Comment by dannyrb** [comment]
We try to be helpful and answer community questions as we're able, but your questions are much more likely to be answered if they follow these guidelines:

https://stackoverflow.com/help/how-to-ask

That looks like a DICOM file? We use `cornerstone-wado-image-loader` under the hood to query. It uses a collection of codecs to decode, and `dicom-parser` to parse.

**Comment by swederik** [comment]
I think you are looking at the response to the RetrieveFrames WADO-RS Request (http://dicom.nema.org/dicom/2013/output/chtml/part18/sect_6.5.html). As @dannyrb said, we use [Cornerstone WADO Image Loader](https://github.com/cornerstonejs/cornerstoneWADOImageLoader) for that. If you are looking for a generic DICOMWeb client library, you can use [dicomweb-client](https://github.com/dcmjs-org/dicomweb-client).

**Comment by JenayLee** [comment]
@swederik Thank you, your answer is very helpful to me.
