### ISSUE TITLE
Adding dicom tags to viewport

### ISSUE THREAD

**Issue by mtjvankuik** [OHIF/Viewers#9]
I want to add several dicom tags to the viewport. I have modified ViewportOverlay.html and ViewportOverlay.js, and QidoRs.cpp in Orthanc. 
`result.push_back(gdcm::Tag(0x0032, 0x4000));  // Study Comments` in Querylevel Study.

I also added the following lines in studies.js to retrieve the following dicom tag:
`studyComments: DICOMWeb.getString(study['00324000'])`

I added these lines to ViewportOverlay.html
`        <div class="topleft dicomTag">
            <div>{{formatPN patientName}}</div>
            <div>{{patientId}}</div>
            <div>{{studyComments}}</div>
            <div class='priorIndicator'>{{prior}}</div>
        </div>`
And finally these changes to ViewportOverlay.js:
`    studyComments: function(){
        return getInstance.call(this, 'studyComments');
    },`

However, when debugging ViewportOverlay.js, the studyComments parameter is undefined. Did i forget to make additional changes to other files?

My suspicion is that the retrieval of the dicom tag does not take place in studies.js; however I am not certain.

**Comment by swederik** [comment]
Hi Martin,

It looks like studyComments has not been added to the Cornerstone metadata provider. Check here:

https://github.com/OHIF/Viewers/blob/b2c5b587bc6ec68164466a989412876aee053400/Packages/viewerbase/lib/metaDataProvider.js#L40

Called from here:

https://github.com/OHIF/Viewers/blob/70b3f938cf3dd29e36789904caa848b195700d2a/Packages/viewerbase/client/components/viewer/imageViewerViewport/imageViewerViewport.js#L67

Hope that helps!

**Comment by mtjvankuik** [comment]
Hi Erik,

Thanks for the tip, however I am still unable to display this dicom tag in the viewport. Instead of adding it to studyMetaData, I have added it to instanceMetaData. 
`    metaData.instance = {
        wadouri: instanceMetaData.wadouri,
        imageType: instanceMetaData.imageType,
        photometricInterpretation: instanceMetaData.photometricInterpretation,
        sopInstanceUid: instanceMetaData.sopInstanceUid,
        sopClassUid: instanceMetaData.sopClassUid,
        instanceNumber: instanceMetaData.instanceNumber,
        laterality: instanceMetaData.laterality,
        viewPosition: instanceMetaData.viewPosition,
        sliceThickness: instanceMetaData.sliceThickness,
        studyComments: instanceMetaData.studyComments,
        index: imageIndex
    };`
I added this line to Instance level in QidoRs.cpp 
`result.push_back(gdcm::Tag(0x0032, 0x4000)); // Study Comments`

**Comment by mtjvankuik** [comment]
UPDATE: I can add dicom tag 0008,0070. It is displayed wonderfully in the upper left corner. Once I replace this tag with 0032,4000 (the desired tag), it stays blank. I suspect it is because this is not a regular DICOM tag, but added by the specific software manufacturer.

I guess there should be a translation file in which all standard dicom tags are noted. I shall keep you informed.
