### ISSUE TITLE
Change standalone viewer to accept `url` param instead of `id`

### ISSUE THREAD

**Issue by hauleth** [OHIF/Viewers#91]
This should match more use cases when standalone viewer is needed.

**Comment by swederik** [comment]
Agreed. I have recently setup a standalone version on AWS S3 that does this here:

http://ohif-viewer.s3-website.eu-central-1.amazonaws.com/?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/sampleDICOM.json

You can download the actual JSON here (https://s3.eu-central-1.amazonaws.com/ohif-viewer/sampleDICOM.json) and point it to whatever you want to load. The JSON host just needs to support CORS.

I'll leave this open until the Standalone Viewer is updated.

**Comment by jmckniff** [comment]
Do you know when the stand alone viewer might be updated?

**Comment by Zaid-Safadi** [comment]
This would be a great feature to quickly integrate with any web server. Is it possible for the URL to be in the format of wado-rs or even wado-url?

**Comment by Zaid-Safadi** [comment]
Hi @swederik , any updates on when this would be available or how would I go with supporting such a feature? 

Thanks!

**Comment by swederik** [comment]
This commit should do it:

https://github.com/OHIF/Viewers/commit/25690ef888df2a889c87ab2a7a6af79246824ce9

If I run the standalone viewer, I can now use:

http://localhost:3000/?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/sampleDICOM.json

and it works fine. Note: I didn't rebuild the SampleClientOnlyBuild folder, so that version won't do it.

**Comment by Zaid-Safadi** [comment]
This is a nice addition to the standalone viewer @swederik

I was able to quickly integrate the OHIF viewer to the [DICOMcloud](https://github.com/DICOMcloud/DICOMcloud) project by supporting the JSON format in the URL parameter.

You can check the demo if you like here: http://dicomweb.azurewebsites.net/ to see this feature working live.

**Comment by swederik** [comment]
@Zaid-Safadi That's very cool! Nice job!

**Comment by hasanmansor** [comment]
@Zaid-Safadi  Cool demo! 
I tried to access some test dicom images on my local file system from the standalone viewer but it didn't work .. I think my query urls were not good .. My images are in the StandaloneViewer/public/images/ folder .. Do you have any idea how can I access them?

**Comment by Zaid-Safadi** [comment]
Thanks @hasanmansor, I believe this could be better handled in a new issue

**Comment by ashu231083** [comment]
Hi, 
I have try to integrate ohif viewer with DicomCloud. Get error in Metadata API.
Metadata API return 404 issue.
