### ISSUE TITLE
Measurements not load when I deploy using docker.

### ISSUE THREAD

**Issue by Vishal568** [OHIF/Viewers#914]
Hello,

There is an issue with the measurements Item list not load when I deploy using docker. And it's working properly no issue in a development environment.

Anyone can help what is the issue.

Thanks in advance.

![bug2](https://user-images.githubusercontent.com/54707074/64858361-bee04600-d644-11e9-8acb-e3e052750c88.gif)

**Comment by dannyrb** [comment]
@Vishal568, the docker image has not been updating since the monorepo switch. On my near future list. Thanks for the report!

**Comment by Vishal568** [comment]
Thanks @dannyrb 👍

**Comment by dannyrb** [comment]
The automated docker image publishing was recently restored.

`docker run -p 3000:80 ohif/viewer:latest`
and visiting `http://localhost:3000` no longer exhibits this issue.

The latest tag should continue to align with code merged to master.
