### ISSUE TITLE
Open viewer page directly in embedded viewer option

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#916]
Hi I am using embedded viewer in my application

I followed the documentation here https://docs.ohif.org/deployment/deployment/recipes/embedded-viewer.md

Basically this sandbox: https://codesandbox.io/s/viewer-script-tag-tprch

But this loads the studylist, how can I pass it a studyUID in embedded viewer and load the viewer page directly 

I want to show this page directly in my embedded viewer: https://viewer.ohif.org/viewer/1.2.826.0.1.3680043.2.1125.1.64437961787692356795839206220978202

How can I achieve this?

Thanks

**Comment by bhavesh-pandey** [comment]
Any suggestions for this @dannyrb ?

**Comment by dannyrb** [comment]
@bhavesh-pandey what have you tried?

There is a config property: `showStudyList: true` that you could set to `false`
Opening to a specific study is mostly a matter of `iframe` + `route` + server config:

Routes are defined here:
```js
    const routes = [
      {
        path: '/local',
        Component: ViewerLocalFileData,
      },
      {
        path: '/viewer',
        Component: StandaloneRouting,
      },
      {
        path: '/viewer/:studyInstanceUids',
        Component: ViewerRouting,
      },
      {
        path: '/study/:studyInstanceUids/series/:seriesInstanceUids',
        Component: ViewerRouting,
      },
      {
        path: '/IHEInvokeImageDisplay',
        Component: IHEInvokeImageDisplay,
      },
    ];
```

I don't believe you can set the study to open to directly w/ props, but that's something we would probably accept a PR for.

**Comment by the-kenny** [comment]
We are also interested in this. Ideally, we would integrate a component which shows the studies for a given patient (whose id, name, whatever) is passed as a prop and a second component which when passed a studyUID shows that study in the viewer.

**Comment by dannyrb** [comment]
@the-kenny, something like this might be good enough for your use case?

- https://react.cornerstonejs.org/grid

If you want a fully featured viewer, the easiest way currently is to show the viewer in an iFrame; then change the URL to update the props to target your specific study.

I don't think we could export the container for the Viewer route as is, but is something we could work toward if we saw enough need.

**Comment by dannyrb** [comment]
Again, more than happy to pursue this further, but would like to see proposals/discussion. It's not something I likely have time to move forward, but could provide guidance and PR reviews for. As this issue has gone stale, I'm going to close it for now. Please feel free to create a new issue referencing this one if you'd like to start the conversation back up.
