### ISSUE TITLE
Probe tool not working

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#917]
Hi Probe Tool is not working. Reproducible at https://viewer.ohif.org/

Earlier it use to come like this: 

![Screenshot 2019-09-16 at 2 44 58 PM](https://user-images.githubusercontent.com/23245538/64946607-e0ce0880-d890-11e9-8c68-094939c93aef.png)

Now the values are not coming:

![Screenshot 2019-09-16 at 2 45 38 PM](https://user-images.githubusercontent.com/23245538/64946631-ee838e00-d890-11e9-8231-4e6670a90bae.png)

**Comment by swederik** [comment]
Looks like this was fixed in Cornerstone Tools here: https://github.com/cornerstonejs/cornerstoneTools/pull/1070 but hasn't been updated in OHIF yet.
