### ISSUE TITLE
When is retrieveInstanceFrames called?

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#931]
Hi,

I viewed in Network tab of browser, I see the system call
http://localhost:5000/dicom-web/studies/1.2.392.200036.9125.2.1884891154190227.64838413177.2776989/series/1.2.392.200036.9125.3.1884891154190227.64838413177.2776990/instances/1.2.392.200036.9125.4.0.253264251.4057054256.1536868067/frames/1
I have bean researched it but no way to know where it is called from.

I set debug in index.es.js of ohif-core packate at retrieveInstanceFrames

>  key: "retrieveInstanceFrames",
>     value: function retrieveInstanceFrames(options) {
>       if (!("studyInstanceUID" in options)) {
>         throw new Error("Study Instance UID is required for retrieval of instance frames");
>       }
> 
>       if (!("seriesInstanceUID" in options)) {
>         throw new Error("Series Instance UID is required for retrieval of instance frames");
>       }
> 
>       if (!("sopInstanceUID" in options)) {
>         throw new Error("SOP Instance UID is required for retrieval of instance frames");
>       }
> 
>       if (!("frameNumbers" in options)) {
>         throw new Error("frame numbers are required for retrieval of instance frames");
>       }
> 
>       console.log("retrieve frames ".concat(options.frameNumbers.toString(), " of instance ").concat(options.sopInstanceUID));
>       var url = "".concat(this.wadoURL, "/studies/").concat(options.studyInstanceUID, "/series/").concat(options.seriesInstanceUID, "/instances/").concat(options.sopInstanceUID, "/frames/").concat(options.frameNumbers.toString());
>       var mediaTypes = options.mediaTypes;

but it did't come to.

Could you show me where (file/package) it is called from?

**Comment by swederik** [comment]
Those calls are probably from the WADO Image Loader https://github.com/cornerstonejs/cornerstoneWADOImageLoader, rather than dicomweb-client.

**Comment by lam0620** [comment]
Thanl you so much @swederik 
I'll research more!
