### ISSUE TITLE
Question about MPR

### ISSUE THREAD

**Issue by rallard71** [OHIF/Viewers#933]
Hi,

I just want to know, in 2d MPR View, how can I go back to 2d View easily and how can I reset tools like Rotation.

Thank you.

**Comment by TZubiri** [comment]
I have to refresh the webpage to go back to the normal view. It seems this is still an experimental feature.

**Comment by dannyrb** [comment]
@TZubiri is right. This is a known issue we haven't scoped a solution for yet. There is an in-progress PR that simplifies our layout management a bit. We've had brief talks about introducing hanging protocol/ viewing modes, and a cleaner way for extensions to register new ones, as well as exit/transition between them.

As it stands, there is a string `plugin` value for each viewport, and that dictates (to some degree) which registered viewport extension module is responsible for handling/displaying the data for that viewport/slot in the viewport grid.

If you have any thoughts, test cases, implementation (code or design) suggestions, please feel free to pipe up ^_^

**Comment by dannyrb** [comment]
https://github.com/OHIF/Viewers/pull/984 closes, but we intend to investigate more elegant solutions.
