### ISSUE TITLE
Standalone installation on linux server to dynamically open the custom MRI scans [V2.0]

### ISSUE THREAD

**Issue by vnarepalepu** [OHIF/Viewers#939]
Hi,

- We have a website that allows researchers to collaborate in viewing the meta-data that includes MRI scans. 
- So the idea is to have a link against each subject (listed in a table on a web page) that references to the path of a folder including multiple dicom files for one run and clicking on the link would append this path to localhost:3000/{appended path} there by allowing the users to view the scanned image through OHIF web viewer. Using the options within the OHIF viewer to interact with the image scan.
- So far we had been using papaya viewer for this and currently thinking to explore the usage of OHIF viewer for this case.

Below is the configuration:
---------------------------

> OS: Centos7 (with no user interface access, only command line)
> apache webserver 2.4
> php 7.3
> yarn 1.17.3
> npm 6.9.0
> node v10.16.3

What I did so far by referring to the documentation:
----------------------------------------------------

> 1) Installed required yarn, npm, nodejs
> 2) git clone the repository
> 3) yarn install
> 4) cd Viewers/platform/viewer
> 5) Within viewer folder, I ran yarn build:viewer
> 6) Then yarn start
> 7) then got the message: running on http://localhost:3000
> 8) Then opened the port for 3000 in firewall
> 9) Tried to access the OHIF viewer on linux server through http://IP_Address:3000 using my personal PC windows browser. Could not connect/ connection refused

I have tried all the above steps on my windows machine and I was able to access it using localhost:3000 

Questions that I have:
---------------------

1. How to access OHIF using an IP address in the root url? Is there a configuration that I can set somewhere within default.js or any other relevant file using the environment variable "ROOT_URL"? Not sure if I am missing anything else with configuration on my linux machine
2. Can I use OHIF viewer to dynamically open the custom scans in a specific path? can I view these scans by simply appending the path url to the root url? example: **http://server_address:3000?url="folder_path_containing_dicomfiles"**
3. Am I missing any installation or configuration that would be necessary to suffice the requirement as mentioned in point 2. ?
4. I am basically trying to host the viewer on a linux server and access it through the port 3000 from external clients to dynamically open and view the scans (dicom files) placed on the server

I  am still going though the various documents and the help forum to understand the architecture of OHIF viewer and its usage. Any help is much appreciated even with reference to any docs that would suffice the requirements mentioned above.  

Please let me know if there are any other additional details that I could help with understanding the above. We hope to use OHIF viewer for our multiple research projects in biomedical imaging.

#788
#804

**Comment by pieper** [comment]
@vnarepalepu - would you be able to use a DICOMweb server for your MR images?  (e.g. dcm4chee, orthanc or dicomweb-server?).  Then you would be able to link directly to the study and not change OHIF much, if at all, and instead just set the configuration to point to the server.

**Comment by vnarepalepu** [comment]
Thanks for the comment @pieper . Using a DICOMweb server is a possibility except that we would to check how we would be able to integrate the DICOMweb server with our system. 
For now, we have zip files containing the .dcm files and need to check how to make use of a DICOMweb server to  link with these zip files and eventually be able to point the OHIF viewer towards any scan that the user needs. And at the same time we are also working on creating JSON/schema for these .zip files so that the viewer can use somehow.

**Comment by pieper** [comment]
It sounds like you have some constraints to work around.  If you put the files in a DICOMweb server probably you'll have duplicates (can't put the zip files in directly).  You could send the zip to the client and unzip them locally and figure out a way to put them into OHIF, but that doesn't sound very clean.
