### ISSUE TITLE
Avoid using variable name "module"

### ISSUE THREAD

**Issue by ivan-aksamentov** [OHIF/Viewers#940]
### Describe the Bug

On [some configurations](https://github.com/webpack/webpack/issues/7369) variables named `module` may clash with the predefined JS global.

I receive the following error in browser console:

```
Uncaught SyntaxError: Identifier 'module' has already been declared
```

The error refers to this variable:

https://github.com/OHIF/Viewers/blob/882d04c9bfee8c5bbd3c5ce7cd9035021b2bdf3f/platform/core/src/studies/retrieveStudyMetadata.js#L3

### What steps can we follow to reproduce the bug?

We are using custom build configuration, so it's a bit difficult to reproduce in upstream.

### Question

Would it be possible to rename this variable to something more neutral?

**Comment by dannyrb** [comment]
Good call out. More then happy to accept a PR. Adding this to our backlog.
