### ISSUE TITLE
About  the standalone viewer in V1 Rect Version support a url query

### ISSUE THREAD

**Issue by peerct** [OHIF/Viewers#941]
I think to  supports a url query parameter to retrieve the study in V1 Rect Vision.  
Old meter version  is OK  (see issue [#91](https://github.com/OHIF/Viewers/issues/91))

**Comment by swederik** [comment]
This works, but it is at `/viewer` now:

See https://viewer.ohif.org/viewer?url=https://s3.eu-central-1.amazonaws.com/ohif-viewer/sampleDICOM.json

**Comment by peerct** [comment]
@swederik execute me,thanks to reply.
i try to test this question,you are right,this rect V1 version is also OK. 
but when i use vs code and cosloe exe :yarn run dev,that is OK;when use yarn run build and Publish to IIS is not OK.
**metor version** : http://ohifviewer.azurewebsites.net/?url=https://dicomcloud.azurewebsites.net/ohif/study/1.2.392.200036.9116.2.6.1.3268.2051314020.1461904638.200374/series
**rect V1 Version** : https://viewer.ohif.org/viewer?url=https://dicomcloud.azurewebsites.net/ohif/study/1.2.392.200036.9116.2.6.1.3268.2051314020.1461904638.200374/series
**I am IIS Version** : http://118.89.249.150:3000/viewer?url=https://dicomcloud.azurewebsites.net/ohif/study/1.2.392.200036.9116.2.6.1.3268.2051314020.1461904638.200374/series

I base @ohif/viewer@1.1.5 to Publish.

i don't how to why ? please help me

**Comment by peerct** [comment]
![test](https://user-images.githubusercontent.com/6157454/65806642-2ce84980-e1bd-11e9-8395-e9cd823b0237.png)
when I USE ‘yarn run build’ to publish to my local IIS7.5,URL'http://localhost:30003/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170125112931.11' is error. 
when I USE 'yarn run dev' to test,that url is success. please check for me,thanks.

**Comment by dannyrb** [comment]
Does the base url work?
Do you serve the base index.html for all 404s?

**Comment by peerct** [comment]
@dannyrb  thanks to reply me.
the base url work , i publish to network,you can see: [http://10.141.51.88:3000/](url)
direct to [http://10.141.51.88:3000/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170126082902.1](url) is not work.

**Comment by dannyrb** [comment]
That URL technically has no file at it. You need to update your server to serve the base index file for 404s

**Comment by peerct** [comment]
@dannyrb  Thank you for your guidance. The problem that has been bothering me for two weeks has finally been solved。According to your instructions, I made the following Settings on the server IIS7.5 and the problem was solved.
![test](https://user-images.githubusercontent.com/6157454/65816469-8c327200-e22e-11e9-9764-3d73b546eb9f.png)

you can see from my update server : [http://118.89.249.150:3000/viewer?url=https://dicomcloud.azurewebsites.net/ohif/study/1.2.392.200036.9116.2.6.1.3268.2051314020.1461904638.200374/series](url)

@swederik  thanks very much, It is all right now.
