### ISSUE TITLE
MPR crashes viewer on some ct scans 

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#948]
## Bug Report

When clicking on MPR, screen immediately goes black, console mentions
Error compiling shader macro.js:64:2
Among other errors

### What steps can we follow to reproduce the bug?
Use MPR on this study
https://viewer.ohif.org/viewer/1.2.276.0.50.192168001099.9140875.14547392.4

**Comment by swederik** [comment]
Hmm well that is only one slice so MPR is kind of pointless, but I agree that it shouldn't have crashed. I am going to close this though because we have a ticket already existing which seems to cover this problem: https://github.com/OHIF/Viewers/issues/561

Thanks!
