### ISSUE TITLE
Fix entrypoint.sh for Docker Image

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#957]
Created By: https://github.com/OHIF/Viewers/issues/956

- Simplify entrypoint to remove Google Cloud string replacement
- Add documentation about how/where to sub out the bundled configuration file

**Comment by dannyrb** [comment]
See: https://github.com/OHIF/Viewers/pull/958

We need to be careful not to break the DOCKER command outlined in our docs:
https://docs.ohif.org/connecting-to-image-archives/google-cloud-healthcare.html#running-via-docker

**Comment by sedghi** [comment]
I think our docker works fine in latest master

Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
