### ISSUE TITLE
How can I add Brush tool in meteor based OHIFViewer?

### ISSUE THREAD

**Issue by Vishal568** [OHIF/Viewers#959]
Hello,

I want to add Brush tool in Meteor based OHIF Viewer. How can I add?

**Comment by dannyrb** [comment]
We no longer actively support the Meteor version of the OHIF Viewer. Unfortunately, we are resource constrained, and our efforts are focused on improving and supporting the current version and its many components/extensions.

You may be able to find assistance in the Google Group, past issues, or previous docs.
