### ISSUE TITLE
Have only a part of my DICOM server avalaible for the viewer

### ISSUE THREAD

**Issue by renardfe** [OHIF/Viewers#96]
Hi,

I would like to create a web application with OHIF. I have a large number of images on a dicom server (multiple cohorts), and I would like to limit the access to only a part of it (one cohort). Is it possible? I understand in the example with the Orthanc server that all the images in server are avalaible.

Is it also possible to use another DICOM server than Orthanc?

Thanks for your answer!
Best regards
Félix

**Comment by radicalrob** [comment]
This has been asked (and answered) on google groups.  It's not really an "issue".  Follow-up should happen on groups.
