### ISSUE TITLE
Request 401

### ISSUE THREAD

**Issue by liliang8858** [OHIF/Viewers#960]
> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

## Bug Report
![image](https://user-images.githubusercontent.com/38367404/65751722-e3a4e500-e13d-11e9-9b61-93adff1483f8.png)

### Describe the Bug

_A clear and concise description of what the bug is._

### What steps can we follow to reproduce the bug?

1. First step
2. Second step
3. ...

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by liliang8858** [comment]
username 
password   
Where is the configuration

**Comment by liliang8858** [comment]
You can access it using localhost, you can access it using IP inside and you will be prompted for a password. Where is this controlled? Is it the binding port?

**Comment by liliang8858** [comment]
Another question is to introduce your own image data server. Can you package it like this? @dannyrb 
package.json:
"build:orthanc": "lerna run build:orthanc --stream",

platform\viewer\package.json
"build:orthanc": "cross-env NODE_ENV=production PROXY_TARGET=http://192.168.1.70:8042 PROXY_DOMAIN=http://192.168.1.70:8042 APP_CONFIG=config/docker_nginx-orthanc.js  node --max_old_space_size=4096 ./../../node_modules/webpack/bin/webpack.js --config .webpack/webpack.pwa.js --progress",

**Comment by dannyrb** [comment]
@liliang8858, were you able to resolve your issue?
