### ISSUE TITLE
Examples of Orthanc Endpoints for app-config.json file

### ISSUE THREAD

**Issue by sglanger** [OHIF/Viewers#965]
Trying to find example endpoint syntax for WADI, QIDO etc URI's. The only ones I have found assume the imaage repository is DCM4chee  like this

https://docs.ohif.org/history/v1/connecting-to-image-archives/dcm4chee-with-docker.html

**Comment by dannyrb** [comment]
There is a rough guide here:
- https://docs.ohif.org/deployment/recipes/nginx--image-archive.html

Doc links are talking about the recipe files located here:
- https://github.com/OHIF/Viewers/tree/master/platform/viewer/.recipes/OpenResty-Orthanc

You need to make sure the version of Orthanc you're using is the `jodogne/orthanc-plugins` one (contains the DICOMWeb plugin). If you're not hosting both Orthanc and OHIF at the same domain + port, then you'll need to either use a proxy for requests to Orthanc, or reverse proxy requests to it using something like `nginx` so you can add appropriate CORS headers.

**Comment by sglanger** [comment]
Are you saying that this
https://github.com/OHIF/Viewers/blob/master/platform/viewer/.recipes/OpenResty-Orthanc/config/orthanc.json

replaces the commented lines below from this :: /usr/share/nginx/html/app-config.json

window.config = {
  // default: '/'
  routerBasename: '/',
  extensions: [],
  showStudyList: true,
  servers: {
    dicomWeb: [
      //{
      //  name: 'DCM4CHEE',
      //  wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado',
      //  qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
      //  wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
      //  qidoSupportsIncludeField: true,
      //  imageRendering: 'wadors',
      //  thumbnailRendering: 'wadors',
      //},
________________________________

**Comment by dannyrb** [comment]
That config is for `orthanc`. This one would be for OHIF:

https://github.com/OHIF/Viewers/blob/master/platform/viewer/public/config/docker_openresty-orthanc.js

It also assumes you've configured `nginx` as a reverse proxy for `Orthanc`
