### ISSUE TITLE
OHIF does not see Orthanc on same Centos 7 box

### ISSUE THREAD

**Issue by sglanger** [OHIF/Viewers#969]
Orthanc from DOckerHub with DICOMweb extensions. Has studies on it

OHIF:latest from Dockerhub, points to above using the  below Endpoints (as per the Orthanc book) in /usr/share/nginx/html/app-config.json. See nothing of the above studies. Thoughts?

 servers: {
    dicomWeb: [
      //{
      //  name: 'DCM4CHEE',
      //  wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado',
      //  qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
      //  wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
      //  qidoSupportsIncludeField: true,
      //  imageRendering: 'wadors',
      //  thumbnailRendering: 'wadors',
      //},
      {
        name: 'ewocs_orthanc',
        wadoUriRoot: 'http://10.0.2.2:8042/wado',
        qidoRoot: 'http://10.0.2.2:8042/dicom-web/studies',
        wadoRoot: 'http://10.0.2.2:8042/dicom-web/studies',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
      },
    ],
  },
  // Extensions should be able to suggest default values for these?

**Comment by dannyrb** [comment]
1. Can you hit those URLs in a browser on the same machine?
2. I don't think you want to append `studies` to those URLs. That may be the route for getting a list of studies, but I wouldn't call it the root:

https://github.com/OHIF/Viewers/blob/master/platform/viewer/public/config/docker_openresty-orthanc.js#L9

3. When accessing the viewer in your browser, are you able to open the developer tools? Do you see any errors under the `console` or `network` tab? I'm suspicious that your setup may be prone to CORS errors unless you've taken deliberate steps to address them.

**Comment by dannyrb** [comment]
👋 Hi @sglanger, it's been a while since we've heard from you. It seemed like we were working making progress on your issue; were you eventually able to identify a setup that worked for you? Anything else we can assist with?

If you're still stuck, I could spend some time to draft a docker script that accomplishes what you're trying on a CentOS image and share the script?

**Comment by sglanger** [comment]
Well, as a clinical worker I typically get 15-30 minute bursts to work on things, and this was complex and very unclearly documented. With the help of friends in Canada and Malaysia, we finally get it working. See the below and in particular the settings in the /files/ohif folder

https://github.com/sglanger/ohif-vagrant

feel free to share
________________________________
