### ISSUE TITLE
uBlock Origin breaks deploy previews

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#979]
No idea why, but it needs to be turned off for the deploy previews right now.

**Comment by dannyrb** [comment]
Could be related to rollbar, or specific class names? Interesting that we're tripping anything at all.

**Comment by jwitos** [comment]
Maybe it could be related to Netlify itself? There are two filters that include this domain but I'm not sure yet how to exactly interpret these rules

`netlify.com,scrims.io##+js(bab-defuser.js)`
or 
`||netlify.com/$script,redirect=noopjs,domain=duellinksmeta.com`

**Comment by swederik** [comment]
This seems to have been resolved upstream in uBlock Origin. Thanks @mapx and @MarkTielemans!
