### ISSUE TITLE
Is there a way to load a specific series in a study by URL?

### ISSUE THREAD

**Issue by atisman89** [OHIF/Viewers#98]
It looks like the viewer supports URL pattern http://<base_url>/viewer/<study_instance_uid>. This will get meta data of all series in the study and the series view can be toggled in the left panel. And the default series that is loaded in the viewport would be the first one (whatever order) in the study. However, I'm wondering if there's a way to "initially" load a specific series in a study by URL. For example, it would be great if the viewer supports a URL pattern something like this: http://<base_url>/viewer/series/<series_instance_uid>. Does this request make sense?

**Comment by radicalrob** [comment]
Yes, it makes sense, but it's not been implemented yet.  However, for the URL, I would recommend something more like http://<base_url>/viewer/<study_instance_uid>/<series_instance_uid>.  In case you want to give it a try, the code for that route is here: [https://github.com/OHIF/Viewers/blob/024e590af3b19b2f7a0abefd46006f25eb5d9d85/OHIFViewer/client/routes.js](url)

- Rob

**Comment by ayselafsar** [comment]
Hi @atisman89 

I implemented to show series in study by URL: `<base_url>/study/<studyInstanceUid>/series/<seriesInstanceUid1>;<seriesInstanceUid2>;<seriesInstanceUid3>`

Example to open 1 series: 

`http://localhost:3000/study/2.16.124.113543.6003.1257388728.18418.18538.407646098/series/2.16.124.113543.6003.806948520.16087.19697.991551387`

Example to open 2 series: 

`http://localhost:3000/study/2.16.124.113543.6003.1257388728.18418.18538.407646098/series/2.16.124.113543.6003.806948520.16087.19697.991551387;2.16.124.113543.6003.623533160.62510.19090.2852520608`

Could you please give it a try? If it's good, please close the issue. Thanks.

**Comment by atisman89** [comment]
Great! It works as described. Thank you!

**Comment by Zaid-Safadi** [comment]
Is there a documentation about this feature? what format is the server expected to return? 
Thanks

**Comment by ayselafsar** [comment]
This is not an API to return a value. It is to view the requested study and series from study list in browser.
There is no documentation yet but we are working on it.

**Comment by Zaid-Safadi** [comment]
thanks @ayselafsar, I believe I got it now. For some reason I though this is related to #91

**Comment by Ulver56** [comment]
But, i cant understand how can i use it with Standalone Viewer?

**Comment by cherhaishan** [comment]
Hi @ayselafsar,

I tried to open a serie using the url <base_url>/study/<studyInstanceUid>/series/<seriesInstanceUid1>;<seriesInstanceUid2>;<seriesInstanceUid3>
but I'm getting an error saying that "Sorry, this page does not exist."
Need I set up a route first in routes.js?

Thank you in advance for your help!

**Comment by cherhaishan** [comment]
Hello,
Nobody can help me please?
hi @radicalrob, could you share the routes.js? the above link no longer works, thank you!

**Comment by fedorov** [comment]
If you are asking about v2, you can do it like this with `seriesInstanceUID` argument: https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.6279.6001.224985459390356936417021464571?seriesInstanceUID=1.2.276.0.7230010.3.1.3.0.57823.1553343864.578877,1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680

If this is about v3, this feature is missing there at the moment, to the best of my knowledge.

**Comment by cherhaishan** [comment]
Thanks a lot for this information @fedorov, I'm using the v3, I will try with the v2, I hope this feature will be soon available in v3 as well.

**Comment by fedorov** [comment]
@cherhaishan I have just learned that this partially works in v3 as well using `?StudyInstanceUIDs=` argument. Partially, because you can only specify one SeriesInstanceUID, while in v2 you can have a comma-separated list. But I know this will be fixed, because it is a priority for our project, and we are funding implementation of this fix.

**Comment by cherhaishan** [comment]
@fedorov that's great! 
I just tried with this url http://localhost:3000/viewer/1.3.6.1.4.1.5962.99.1.2786334768.1849416866.1385765836848.3.0?**SeriesInstanceUID**=1.3.6.1.4.1.5962.99.1.2786334768.1849416866.1385765836848.377.0
SeriesInstanceUID without 's', it works, but others series are also showed in the left panel, when I specify the serie by using ?SeriesInstanceUID=xxx,  this serie is just put on the top of the list, maybe this is a normal behaviour.
Is it also possible in v3 to specify the &SOPInstanceUID=xxx after SeriesInstanceUID=xxx to scroll down to the Image and show it first?

**Comment by ketki-kerkar** [comment]
Hello, 
We were trying to integrate OHIF Viewer with GCP and ReactJs. W e are running ohif viewer on port 3000 locally. In another reactjs Application we have iframe. In this iframe we are opening ohif viewer. When we give local host 3000 it loads the initial page and works fine. However when we try to open a particular image by giving its url in src of iframe eg.:http://localhost:3000/viewer?StudyInstanceUIDs=1.2.840.113619.2.15.1008000062035011254.825190719.2.31 Then the image is not loading.
The console shows following error
![Screenshot 2024-04-03 162501](https://github.com/OHIF/Viewers/assets/155997714/75a2597d-250e-4473-a231-0b8c3bc2dece)
We have already gone through documentation. If anyone has the solution to this it will be really helpful. 
Thank you in advance for any assistance.
