### ISSUE TITLE
Returning to the Study List should clear the requestPool

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#980]
If you open a study then go back to the study list, CornerstoneTools will continue requesting a ton of stuff from your previous study. We need to clear the request pool when we unmount the viewer.

**Comment by dannyrb** [comment]
@emfol, I may have accidentally fixed this in my ongoing PR. I'll let you know tomorrow if this still needs actioned.

**Comment by dannyrb** [comment]
Provided guidance:

If you give it a quick test, and it's still an issue, then feel free to look at it.
Should be able to verify by:
- Opening the network tab in inspector
- Navigate to a CT study with many images
- Drop a large CT into an active viewport (lots of requests should queue and begin firing)
- Navigate back to study list

If the requests stop, then we're good
If they keep going, then on `willUnmount` we need to make sure we're clearing the request pool.
You'd probably do that in `react-cornerstone-viewport`, not OHIF/viewers

**Comment by swederik** [comment]
> You'd probably do that in `react-cornerstone-viewport`, not OHIF/viewers

But then wouldn't the request pool be cleared every time the layout is changed and the viewport is destroyed?

**Comment by emfol** [comment]
After following the provided steps I could verify that the queued requests stop when returning to the study list. So this issue can be closed.
One thing that I noticed though was that if I return to the study list before all series have finished loading, multiple errors are logged in the console. I logged an issue for that: https://github.com/OHIF/Viewers/issues/1075
