### ISSUE TITLE
Tools are not being displayed as active on toolbar

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#981]
### Description

Once user selects the cornerstone tool **"Annotate"**, the same is not being displayed with active icon on the toolbar. The same is happening with tools **"Bidirectional"** and **"Eraser"**.
We can see the mouse cursor displaying the selected tool, but the same is not active on the toolbar.
The "More" button `svg` is also not being replaced by **"Bidirectional"** and **"Eraser"** `svg` icons. 

### Steps to Reproduce

1. Load view studies page
2. Select the Annotate/Bidirectional/Eraser tool on the toolbar
3. Check that the mouse cursor has changed to the tool's svg icon

### Actual Result:

Although the Annotate/Bidirectional/Eraser tool is selected, the same is not being displayed as an active tool on the toolbar.

### Acceptance Criteria:

Update toolbar's active icon to be a computed/reactive state. It shouldn't be possible for the two to have different states. Once Annotate/Bidirectional/Eraser tool is selected, it should be displayed as an active tool on toolbar.

**Comment by mirnasilva** [comment]
Possibly related to #903

**Comment by dannyrb** [comment]
Resolved here: https://github.com/OHIF/Viewers/pull/1020
