### ISSUE TITLE
Viewer crashing on clicking MPR (on viewer.ohif.org)

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#986]
Hi,

Just synced my local branch with latest OHIF branch and the viewer is crashing when clicking on MPR. Checked the demo here

https://viewer.ohif.org/viewer/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170

its crashing there too.

**Comment by dannyrb** [comment]
```
Error compiling shader '#version 300 es
#define attribute in
#define textureCube texture
#define texture2D texture
#define textureCubeLod textureLod
#define texture2DLod textureLod





#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
precision highp int;
#else
precision mediump float;
precision mediump int;
#endif

...
```

`Uncaught (in promise) TypeError: Cannot read property 'isAttributeUsed' of null`

Can reproduce. Not sure what's up.

@Zaid-Safadi or @swederik?

**Comment by Zaid-Safadi** [comment]
This is a series with one image so you can't create an MPR. Probably related to this: https://github.com/OHIF/Viewers/issues/561

**Comment by swederik** [comment]
I'm getting deja vu here... https://github.com/OHIF/Viewers/issues/948

**Comment by dannyrb** [comment]
Thanks friends. I saw `CT` and didn't notice it only had a single image.
Closing, duplicates https://github.com/OHIF/Viewers/issues/561
