### ISSUE TITLE
Measurement saving only support three types

### ISSUE THREAD

**Issue by zhaoyu162** [OHIF/Viewers#988]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

I used the branch version of Issue #758 for saving measurements.
And i found that the dcmjs library can only support three types of measurement, which are Length, Freehand and Biodirectional, so other measurements like Angel, Circle and Rectangle throws exceptions while saving.
Maybe I am new to this library, can anyone help me to figure it out?
Thanks.

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by dannyrb** [comment]
There is some ongoing work in this PR to save measurements as DICOM SRs:
https://github.com/OHIF/Viewers/pull/954

If you intend to save your data to a database, or in a proprietary format, you can map the cornerstone tool state to any representation of your choice, so long as you provide a way to map that data back when retrieving it ^_^

**Comment by zhaoyu162** [comment]
@dannyrb ,thank you!
Yes, I made a trick to skip over the dcmjs library and directly store the tool states as JSON to database, then restore tool states  from JSON at next time. So, every thing works fine based on this great project!
Thank you !

**Comment by Dwill-chen** [comment]
After skipping the dcmjs library, how can other metrics (such as rectangle) be displayed when the page is loaded

**Comment by phoenixsac** [comment]
@zhaoyu162 @dannyrb  can you give pointers or references on how i can achieve this? I was able to store the measurements in json onto my backend from the MeasurementService.ts, but when i load the json back and pass it to the annotationToMeasurement method, it throws errors like source not defined and mappings not present. Is this the correct way? Do i need to make any other code changes?
