### ISSUE TITLE
when I use it in win it hint me that Your app is crashing. Here's the latest log:

### ISSUE THREAD

**Issue by zzz0906** [OHIF/Viewers#99]
While processing files with stylus (for target web.browser):
Packages/ohif-themes-common/themes/theme-crickets.styl: Stylus compiler error: Packages/ohif-themes-common/themes/theme-crickets.styl:1:19
   1| $ohifThemesCommon['crickets'] = {
------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

cannot perform $ohifThemesCommon []= ('crickets')

Packages/ohif-themes-common/themes/theme-honeycomb.styl: Stylus compiler error: Packages/ohif-themes-common/themes/theme-honeycomb.styl:1:19
   1| $ohifThemesCommon['honeycomb'] = {
------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

cannot perform $ohifThemesCommon []= ('honeycomb')

Packages/ohif-themes-common/themes/theme-mint.styl: Stylus compiler error: Packages/ohif-themes-common/themes/theme-mint.styl:1:19
   1| $ohifThemesCommon['mint'] = {
------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

cannot perform $ohifThemesCommon []= ('mint')

Packages/ohif-themes-common/themes/theme-overcast.styl: Stylus compiler error: Packages/ohif-themes-common/themes/theme-overcast.styl:1:19
   1| $ohifThemesCommon['overcast'] = {
------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

cannot perform $ohifThemesCommon []= ('overcast')

Packages/ohif-themes-common/themes/theme-quartz.styl: Stylus compiler error: Packages/ohif-themes-common/themes/theme-quartz.styl:1:19
   1| $ohifThemesCommon['quartz'] = {
------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

cannot perform $ohifThemesCommon []= ('quartz')

Packages/ohif-themes-common/themes/theme-tide.styl: Stylus compiler error: Packages/ohif-themes-common/themes/theme-tide.styl:1:19
   1| $ohifThemesCommon['tide'] = {
------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

cannot perform $ohifThemesCommon []= ('tide')

Packages/ohif-themes-common/themes/theme-tigerlily.styl: Stylus compiler error: Packages/ohif-themes-common/themes/theme-tigerlily.styl:1:19
   1| $ohifThemesCommon['tigerlily'] = {
------------------------^
   2|   // Common palette
   3|   $uiYellow: #E29E4A
   4|   $uiSkyBlue: #6FBDE2

cannot perform $ohifThemesCommon []= ('tigerlily')

Your application has errors. Waiting for file change.
Started MongoDB.

**Comment by zzz0906** [comment]
how can i solve it?

**Comment by ayselafsar** [comment]
Hi @zzz0906 

I cannot reproduce this issue in win10 x64 with the latest master branch. Do you still have it?

```
C:\Workspace\OHIF\Viewers\OHIFViewer>"bin\orthancDICOMWeb.bat"

C:\Workspace\OHIF\Viewers\OHIFViewer>set METEOR_PACKAGE_DIRS=..\Packages

C:\Workspace\OHIF\Viewers\OHIFViewer>meteor --settings ../config/orthancDICOMWeb.json
[[[[[ C:\Workspace\OHIF\Viewers\OHIFViewer ]]]]]

=> Started proxy.
=> Meteor 1.5.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by zzz0906** [comment]
thx @ayselafsar  
I faced this problem when I used previous version and I just copy packages into ohifViewer dir and did not configure packages environment, so I cloned a new pro and do not have this problem.
