### ISSUE TITLE
Extensions in UMD Build

### ISSUE THREAD

**Issue by sedenardi** [OHIF/Viewers#991]
**Description**

I was trying to use the MDR view in the UMD build and noticed the extensions weren't being bundled in the build. Passing the extensions in as a prop to `<App />` in `index-umd.js` builds fine and works great.

Is there a specific reason that extensions (`OHIFVTKExtension`, `OHIFDicomHtmlExtension`, `OHIFDicomMicroscopyExtension`, `OHIFDicomPDFExtension`) aren't included by default in the UMD build?

**Comment by dannyrb** [comment]
@sedenardi they can be added via configuration. I know microscopy works. We haven't extensively tested all of them.

**Comment by sedenardi** [comment]
Yup, apologies for the issue, I had missed that part in the docs.
