### ISSUE TITLE
Does @ohif/core included cornerstone-core and cornerstone-wado-image-loader?

### ISSUE THREAD

**Issue by tunglt1810** [OHIF/Viewers#992]
Hi guys,

I am currently using ohif-core in my project. Size of index file is only 1.2 MB.
After changing dependency from 'ohif-core' to '@ohif/core', i can not load image after retrieve metadata because the lib cannot find meta data for wadors image id.
I have checked the size of new core index file, it is 4.3MB. So i think it includes cornerstone-core and cornerstone-wado-image-loader and they have another instance inside core. These instance control meta data of studies so another instance cornerstone can not load image in these studies.

Can someone explain this issus?

Thank you.

**Comment by dannyrb** [comment]
👋 Hi @tunglt1810. What version of `ohif-core` were you using previously? We've recently made a lot of changes to how our application is built and bundled.

I think it's possible, and other issues have pointed at this, that we're not excluding dependencies correctly when building our packaged bundles for `npm`. 

## Why we haven't noticed

We're less likely to notice, as our two primary use cases are:

- PWA Build, created by monorepo
    - Everything is built from all `platform` and `extension` source, as part of a single WebPack build
- UMD Build + Runtime Extensions
    - Platform packages (`core`, `ui`, `viewer`, `i18n`) and a couple extension packages (`cornerstone`) create a primary bundle (`@ohif/viewer`) that you can register additional extensions with via configuration

## Verifying Issue

So there's a couple of things we can do to test, and then fix the issue. The first step is adding WebPack Bundle Analyzer, and running the package build for the package you want to test. This should give you a good map of what's being included in the bundle:

- https://www.npmjs.com/package/webpack-bundle-analyzer
- `@ohif/core`: [webpack.prod.js](https://github.com/OHIF/Viewers/blob/master/platform/core/.webpack/webpack.prod.js)
    - It builds off of our base configs here: [umd](https://github.com/OHIF/Viewers/blob/master/.webpack/webpack.commonjs.js), [base](https://github.com/OHIF/Viewers/blob/master/.webpack/webpack.base.js)

## The Fix

The fix would be to update the package's [`externals` key](https://webpack.js.org/configuration/externals/#root) to make sure these dependency's aren't included in the output bundle, and to inform the bundle of how/where they can be found. If we're having issues w/ `@ohif/core`, they probably exist in the other packages as well.

I'm more than happy to review and merge PRs that fix these issues. Unfortunately, my time is pretty tight to provide anything other than guidance.

**Comment by tunglt1810** [comment]
I will try and response asap

**Comment by tunglt1810** [comment]
Hi,
The last version of `ohif-core` i have use is `0.10.6`.
I have created a pull request with external config in webpack config of  `@ohif/core`. I also test with output bundle and the issues is no longer available

**Comment by sedghi** [comment]
Right now in v3, they are separate libraries. 

Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.
