### ISSUE TITLE
CINE control buttons with wrong titles

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#995]
### Description

To improve user experience, we would like to have labels/titles coherent with its button's functionality.

On CINE control, the current labels/titles of buttons 'Next image' and 'Skip to last image' may mislead the user, since they are not coherent with the functionality of each button.

![cine-labels](https://user-images.githubusercontent.com/13245529/66157039-50662680-e5f9-11e9-95c0-35062b33b2d6.gif)

### Steps to Reproduce

1. Load view studies page
2. Select the Cine tool on the toolbar
3. Hover on the 4th button and verify that the label says "Play Image"
4. Hover on the 5th button and verify that the label says "Skip, to last image"

### Acceptance Criteria

To be coherent with its functionality:
-  the 4th button should have title/label "Next image"
-  the 5th button should have title/label "Skip to last image"

**Comment by dannyrb** [comment]
@rodrigolabs can you pick up this quick fix?

**Comment by rodrigolabs** [comment]
> @rodrigolabs can you pick up this quick fix?

Yes! 🙌🏻
