### ISSUE TITLE
dicomLoaderService does not add header tokens

### ISSUE THREAD

**Issue by MuriloSchaefer** [OHIF/Viewers#997]
Hi,
I'm having an issue with tokens, in my config file I have a token that needs to be passed to every request to my data server (metadata and images itself). But the function `fetchIt` inside `dicomLoaderService.js` does not pass any `requestOptions` object to the function `DICOMWeb.getAuthenticationHeader()`  so it considers it hasn't a token or has a user logged in. But in my case, I need a token to fetch images and there is no logged user.

and also I couldn't find a way to put the server config on it, how can I add the server configs in there?

EDIT:
I need to add the server auth config in this request to getAuthenticationHeader(), but I can't have access to server config in there, so how can I do it?

```
const wadorsRetriever = (
  url,
  studyInstanceUID,
  seriesInstanceUID,
  sopInstanceUID,
  headers = DICOMWeb.getAuthorizationHeader()
) => {
  const config = {
    url,
    headers,
  };
  const dicomWeb = new api.DICOMwebClient(config);

  return dicomWeb.retrieveInstance({
    studyInstanceUID,
    seriesInstanceUID,
    sopInstanceUID,
  });
};
```

**Comment by swederik** [comment]
Related: https://github.com/OHIF/Viewers/pull/928

**Comment by dannyrb** [comment]
@MuriloSchaefer, has #928 resolved your issue?

> and also I couldn't find a way to put the server config on it, how can I add the server configs in there?

Have you read the deployment docs, or our docs on configuration?

- https://docs.ohif.org/essentials/configuration.html

**Comment by MuriloSchaefer** [comment]
It solved my issue :) Thx
