### ISSUE TITLE
Current viewport is not being set as active after changing Layout selection back to one viewport

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#999]
### Description

If user changes the viewport selection to more than one viewport and interacts with those viewports, once he/she switches back to only 1 viewport, the current viewport is not being set as active. This is causing the application to throw an exception when the user selects another tool at the toolbar menu.

![layout-bug](https://user-images.githubusercontent.com/13245529/66244550-68b07100-e6df-11e9-8d7c-f76b79aabb06.gif)

### Steps to reproduce

1. Load view studies page
2. Select the Layout tool on the toolbar
3. Change the layout selection to 3 (or more)
4. Click on any viewport different from the 1st one
5. Change the layout selection back to 1
6. Click on Reset tool on the toolbar
7. Check that exception `element not enabled` was thrown 

### Actual result

Exception `element not enabled` is being thrown and user is not able to use the selected tool

### Acceptance criteria

After changing the viewport number selection and returning back to only 1 viewport, the current viewport should be set as `active` by default.

**Comment by dannyrb** [comment]
👋 Take it away, @igoroctaviano

**Comment by dannyrb** [comment]
Resolved here: https://github.com/OHIF/Viewers/pull/1018
